### ISSUE TITLE
Mobile/Tablet Support

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#1]
We want to get the UI working on tablets.

There is some early support already in there for touch events, but it is not complete. For example, you can start to drag a new link between nodes, but it doesn't end properly.

The layout could also do with being optimised.
### Function Changes
- [x] enable dragging out of palette
- [x] prevent native zoom
- [x] enable pinch-zoom in workspace ( PR coming from @TJKoury )
- [x] unable to wire nodes together (a3dea6ec0dc92ae2880a035b2fb4361b697f3ad0)
- [x] double tap to edit rather than long-touch (ec5985eaa32066c34ecd39bc1099aeb6d6a16e64)
- [x] how to delete a node (radial menu: e524393d8792e4cd75b6520b727e65b803457792)
- [x] how to undo change (radial menu: e524393d8792e4cd75b6520b727e65b803457792)
- [x] how to group select (lasso) - long-touch to disable scroll/enable lasso? (0e8f0735cc207c1503f1ef91a7a9c43604a802c7)
- [ ] import flow placement - click to place, needs a visual cue to touch as you don't drag the nodes
- [ ] pinch zoom deselects current selection
- [x] pinch zoom triggers radial menu (2fa82d9)
- [x] trigger radialMenu on long-touch with link selected
### Mobile-specific UI changes
- [ ] decide on server-side or client-side mobile detection (ie serve mobile.html, or insert mobile specific css/javascript adaptations)
- [x] mobile-only tool bar to enable delete/undo/other? actions (not needed due to radialMenu)
- [x] sidebar resize target needs to be more obvious (aa4bf4d64060dab47d75c5dfc00dc4dd06429e23)
- [x] sidebar drag in from RH side (aa4bf4d64060dab47d75c5dfc00dc4dd06429e23)
- [ ] drop-down menu changed to be slide-in menu
- [ ] palette drag in from LH side

**Comment by ristomatti** [comment]
Is this currently on hold since there hasn't been any comments for quite some time? I wound up here while looking for a way to remove a connection without cut & paste a node. I've found using the editor othrrwise quite feasible for some small edits on a 10" tablet but this is the most frustrating issue for me.

I have some ideas:

Since it's already possible to select a connection, would it be possible to add support for long tap menu with the option to remove (after the connection is selected)? Or possibly long click to remove directly as that'd probably be the only thing you could do. Another option would be to add an X icon next to the selected connection for removing.

**Comment by knolleary** [comment]
@ristomatti there has been much demand for this and I very rarely use NR on touch screens, so it simply hasn't been a priority.

The issue with deleting wires is one of the main outstanding basic issues for touchscreens. See my comment above on what needs doing - we already have a radial menu that appears on long-touch of nodes. It 'just' needs enabling for long-touch of wires.

**Comment by ristomatti** [comment]
@knolleary ah sorry somehow missed it! Are there any plans when this would be implemented or is this perhaps something open for pull requests?

**Comment by knolleary** [comment]
A pull request that enabled the existing radial menu on wires would be welcome!

**Comment by holomekc** [comment]
When you are working on a subflow the connection between a node with input and output (e.g. function) you are not able to connect it to an output. I tested this on an ipad with safari, chrome and firefox. I am using node-red 0.20.7.

**Comment by knolleary** [comment]
I spent a bunch of time fixing up basic touch support in the editor for the 1.1.x release.

I don't think there's much value having this issue sit in the open state. If there are specific bugs with the touch support, they can be raised and addressed as such. If there are larger feature enhancements needed, they can also be addressed in the usual way.
