### ISSUE TITLE
Drop down menues remain default

### ISSUE THREAD

**Issue by pingu2211** [node-red/node-red#1000]
OpenWeatherMap's "forcast type"and TextBelt's country drop down menues always remain at the default. 
Editor does not regester changes to these nodes and enable deployment.

**Comment by dceejay** [comment]
This is not actually a core node - so ideally the issue would be raised over here https://github.com/node-red/node-red-web-nodes

But can you provide more context - where is this running ? what browser / OS ? which version of Node-RED ?

**Comment by pingu2211** [comment]
Im new to git, can I move this? node-red version 3.10.3
 running on Ubuntu LTS 14.02 server,
editing flows on a seperate machine in the local network using chrome version 53.0.2785.116 on windows 10 v1511 build 10586.589
