### ISSUE TITLE
No settings.js file in Raspberry Pi 3 Raspbian Jessie 

### ISSUE THREAD

**Issue by SidVader** [node-red/node-red#1003]
I have error downloading new node modules in Raspberry Pi 3 Model B, Raspbian Jessie as the .node-red directory doesn't have the settings.js file.
So, how can I download new node modules.

**Comment by dceejay** [comment]
Hi - we prefer general questions like this to the google group mailing list -  or slack channel. I see you have also posted it there so closing this issue
