### ISSUE TITLE
Websocket path always reverts to / after saving configuration

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#1011]
create ws
![image](https://cloud.githubusercontent.com/assets/5375409/19318993/b9c6afbe-90a2-11e6-800a-d6d8c4314773.png)
Hit Update to save
![image](https://cloud.githubusercontent.com/assets/5375409/19319010/c5df5738-90a2-11e6-83e2-d29d6a80f0d8.png)

**Comment by knolleary** [comment]
Bidi related? @wajnberg
