### ISSUE TITLE
 CTRL+. is not working on non US/UK based keyboard layouts 

### ISSUE THREAD

**Issue by j2l** [node-red/node-red#1012]
On my keyboard layout (FR), I need to hold shift to get a dot (.).
I also have it on the numpad, but none of them (CTRL+SHIFT+; or CTRL+.(numpad)) show the search box on fresh 0.15.1.
Any idea? Beside switching to US/UK keyboard layout of course :)

**Comment by dceejay** [comment]
need to move this shortcut... but where to ?
ctrl ,      ?

**Comment by j2l** [comment]
ctrl , is ok for me but I'm pretty sure there's a common universal map
somewhere on the web to take in account all or most of mappings.

**Comment by knolleary** [comment]
Moving to `Ctrl-F` in 0.16
