### ISSUE TITLE
Test fails "delay Node handles bursts using a buffer" on ARMv8 (aarch64)

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#1013]
Environment: 96 core ARMv8 server, node v4.2.6 from Ubuntu 16.04.

Linux version 4.4.0-38-generic (buildd@bos01-arm64-006) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.2) ) #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016 (Ubuntu 4.4.0-38.57-generic 4.4.19).

Repeat by:

1. Check out node-red, build according to package directions.
2. npm install -g istanbul
3. npm install coveralls
4. Execute the test that TravisCI runs, namely

```
istanbul cover ./node_modules/.bin/grunt --report lcovonly && istanbul report text && ( cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true ) && rm -rf coverage
```

Lots of tests pass, but this one fails:

```
1) delay Node handles bursts using a buffer:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  
Warning: Task "simplemocha:nodes" failed. Use --force to continue.
```

Suggestions on a separate test invocation to test all the tests to completion? I don't know where the "--force" flag would go.

As an aside, on this very heavily parallel server, it's noticed when the build seems to run slowly; in particular, "npm install" looks single-threaded.

**Comment by hardillb** [comment]
All nodejs apps are single threaded, adding cores will not change anything

**Comment by knolleary** [comment]
This is a test that has occasionally failed for some time now - but not often enough to go chase down.

Had a look at it and made a bit more forgiving. But given we can't reliably make it fail, I can't say for certain if this will fix the issue. Obviously I don't have access to the hardware you've used here.

**Comment by vielmetti** [comment]
@knolleary (or anyone else) - if you're interested in getting access to this hardware, let me know; I'm using it at a hosted provider, and they have offered to provide access to others for testing.
