### ISSUE TITLE
Second HTTP Request always hangs when separated by a Template node

### ISSUE THREAD

**Issue by ajgbarnes** [node-red/node-red#1015]
In a simple flow which is configured as on Node Red 0.14.6
1. HTTP input node
2. HTTP Request node (to any service)
3. Template node constructing any JSON
4. HTTP Request node (to any service but assume a POST one)
5. HTTP output node

The second HTTP request node will always hang until timing out (it will not call the service).

If you remove the Template node then the second HTTP Request will proceed.

Simple test case example below:

[{"id":"221e8671.dec0fa","type":"http in","z":"2dcb935.1fd3b6c","name":"","url":"/andy/stuff","method":"get","swaggerDoc":"","x":126,"y":101,"wires":[["88031b8f.0e40e"]]},{"id":"88031b8f.0e40e","type":"http request","z":"2dcb935.1fd3b6c","name":"","method":"GET","ret":"txt","url":"http://md5.jsontest.com/?text=hello","tls":"","x":310,"y":101,"wires":[["6732303d.c6b458","6944ddb7.e1fd14"]]},{"id":"6732303d.c6b458","type":"template","z":"2dcb935.1fd3b6c","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{\n    \"Hello\": \"World\"\n}","x":467,"y":101,"wires":[["623e8f1c.1b0b4"]]},{"id":"623e8f1c.1b0b4","type":"http request","z":"2dcb935.1fd3b6c","name":"","method":"POST","ret":"txt","url":"https://httpbin.org/post","tls":"","x":620,"y":100,"wires":[["1acd8a4b.231bae","6944ddb7.e1fd14"]]},{"id":"1acd8a4b.231bae","type":"http response","z":"2dcb935.1fd3b6c","name":"","x":790,"y":100,"wires":[]},{"id":"6944ddb7.e1fd14","type":"debug","z":"2dcb935.1fd3b6c","name":"","active":true,"console":"false","complete":"false","x":488,"y":234,"wires":[]}]

**Comment by andysc** [comment]
note the HTTP input and output nodes are not relevant to this - if you just use an inject node to start it, the same happens.

**Comment by hardillb** [comment]
This will be http headers from the first request being fed into the second one. A change node or function node should be inserted between the 2 request nodes to remove them

**Comment by andysc** [comment]
Thanks Ben!!!! :)

**Comment by ajgbarnes** [comment]
Thank you Ben - and for responding so quickly to this.

**Comment by dceejay** [comment]
Can we close ? Not an issue ?

**Comment by ajgbarnes** [comment]
I don't know if this is expected behaviour or not?  I'm happy with the workaround for right now, I'd like not to do it but if that isn't what is supposed to happen then it's an issue.

**Comment by hardillb** [comment]
This is working as designed, not a bug

**Comment by andysc** [comment]
I think the behaviour was unexpected. I don't know what in the headers object was causing the second service to hang. Would there be any case for "input headers" and "output headers", so they don't accidentally pollute each other. 
Athough I agree it's not a bug, it tied two of us up for quite a long time trying to fathom it out, so it's a usability concern (albeit possibly an edge case as probably not many people chain HTTP requests together, but who's to say...?).

**Comment by andysc** [comment]
In fact, thinking about it, the response headers would never be the correct request headers for another call, so carrying this through in the same variable is more likely to cause problems than be the desired behaviour

**Comment by knolleary** [comment]
We've had this discussion before.
We cannot change these properties. They have existed since day one and we would break a lot of working flows if they changed.
We need to find a way to help the user avoid hitting it, without breaking anything.

**Comment by andysc** [comment]
just a random idea, but could the HTTP request  node put a copy of the header in a secret place, then if a subsequent instance checks that and sees it's exactly the same as the passed-in msg.headers, raise a debug warning "complex header object passed through from previous call". I just can't see a use case when that would be the desired behaviour, so the warning should be welcome. Maybe put a "mute header warnings" checkbox in the node config dialogue for those who want to do it.

**Comment by ajgbarnes** [comment]
We've mused some more on this - and whilst I get @knolleary 's point on 'how it has always worked' I think the fundamental issue is that people who use Node-RED may not understand Node.js etc underneath and they expect it to work in a certain way.  So the behaviour either has to change to meet user expectations OR, maybe a compromise, that the HTTP Request node documentation on the Info tab is changed to highlight the workaround that you have to perform if you need to do two HTTP Requests in a single flow.  It's not obvious and many people will come to Node.js through Node-RED and will burn hours (like I did) playing with this to figure out what's going on or just give up.  /cc @andysc

**Comment by knolleary** [comment]
Yes, as I said on my last comment:

> We need to find a way to help the user avoid hitting it, without breaking anything.

**Comment by andysc** [comment]
a documentation change would be a good way of not breaking anything ;)

**Comment by dceejay** [comment]
as long as they read it...

**Comment by andysc** [comment]
is it msg.headers, or msg.req.headers you have to reset? msg.headers, coming into the second request node, looks quite innocent - is there a hidden iceberg under the surface somewhere?

**Comment by knolleary** [comment]
`msg.headers`

**Comment by ajgbarnes** [comment]
Looking again as well - it WORKS if you have:

http in -> http request -> http request -> http out

But it stops working if you do :

http in -> http request -> template -> http request -> http out

So why does the second require a reset of msg.headers and not the first?!

**Comment by andysc** [comment]
(where template changes msg.payload only...)

**Comment by knolleary** [comment]
By 'stops working' do you mean it hangs as per your original description?

My guess is the async action inside the Template node separates the event being emitted by the first Request node from the one that triggers the next request.

If you replace the Template node with a no-op Change node, does it also hang?

**Comment by ajgbarnes** [comment]
Haha yes that was a little vague and nebulous - yes it hangs.

[{"id":"95c8d536.631ae8","type":"http in","z":"dc3b6e96.6939a8","name":"","url":"/test/andy","method":"get","swaggerDoc":"","x":126,"y":247,"wires":[["7f72173a.8b7c38"]]},{"id":"7f72173a.8b7c38","type":"http request","z":"dc3b6e96.6939a8","name":"","method":"GET","ret":"txt","url":"http://md5.jsontest.com/?text=hello","tls":"","x":300,"y":215,"wires":[["545a7bf9.7216c4"]]},{"id":"4f2be188.ec8ff","type":"http request","z":"dc3b6e96.6939a8","name":"","method":"POST","ret":"txt","url":"https://httpbin.org/post","tls":"","x":632,"y":248,"wires":[["fcf84440.497c98"]]},{"id":"fcf84440.497c98","type":"http response","z":"dc3b6e96.6939a8","name":"","x":778,"y":248,"wires":[]},{"id":"545a7bf9.7216c4","type":"template","z":"dc3b6e96.6939a8","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{\n   \"hello\" : \"stuff\"\n}","x":430,"y":270,"wires":[["4f2be188.ec8ff"]]}]

**Comment by ajgbarnes** [comment]
What do you mean by a no-op Change node - if I add a change node I always have to change something even if it's setting say msg.payload to msg.payload.

**Comment by knolleary** [comment]
Ok no-op was a bad choice of words. Add a Change node that does something/anything - the point being, the Change node is synchronous in its operation, so if my theory is right, this should behave as if you had your Request nodes directly wired.

**Comment by ajgbarnes** [comment]
It still hangs on the second HTTP request if I replace the Template node with a Change node (it just sets msg.payload to msg.payload).

[{"id":"95c8d536.631ae8","type":"http in","z":"dc3b6e96.6939a8","name":"","url":"/testy/andy","method":"get","swaggerDoc":"","x":126,"y":247,"wires":[["7f72173a.8b7c38"]]},{"id":"7f72173a.8b7c38","type":"http request","z":"dc3b6e96.6939a8","name":"","method":"GET","ret":"txt","url":"http://md5.jsontest.com/?text=hello","tls":"","x":300,"y":215,"wires":[["29e70ac1.7c7246"]]},{"id":"4f2be188.ec8ff","type":"http request","z":"dc3b6e96.6939a8","name":"","method":"POST","ret":"txt","url":"https://httpbin.org/post","tls":"","x":632,"y":248,"wires":[["fcf84440.497c98"]]},{"id":"fcf84440.497c98","type":"http response","z":"dc3b6e96.6939a8","name":"","x":778,"y":248,"wires":[]},{"id":"29e70ac1.7c7246","type":"change","z":"dc3b6e96.6939a8","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"msg.payload","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":452,"y":299,"wires":[["4f2be188.ec8ff"]]}]

**Comment by knolleary** [comment]
Whilst I still need to figure out the hang, we have a plan for dealing with `msg.headers`. Here's what we're thinking:

1. Add a custom property to `msg.headers` when it is emitted by the request node, called `x-node-red-http-request-node`
2. When a request node receives a message with `msg.headers` set, it can check for that property. If not set, then we know this is a 'clean' set of headers to be used with the request. If set, we know these headers have come from another request node and should be ignored.

There is one edge case to consider; what if a flow sets its own properties under `msg.headers` sufficient to make the second request work (ie, `content-type` and `content-length` being the most probable.). If they simply overwrite those properties but leave `msg.headers` otherwise intact, it would now have our custom property and we'd ignore the whole set. That would mean a once-working flow would stop working.

So, the next part of the proposal we're considering is to set the value of the custom `x-node-red-http-request-node` property to be some sort of checksum of the contents. That way the second request node can detect it its contents has been modified.

Needs some tinkering, but I _think_ this approach would let a chain of request nodes Just Work without the user having to read the help.

**Comment by andysc** [comment]
yes, I like that idea - actually, I just realised it's effectively what I suggested on 18-Oct, but you did it properly, using a checksum :).
I do sometimes just set the properties I want in the new headers object, so your edge case would apply there.

**Comment by andysc** [comment]
Thanks Nick!
