### ISSUE TITLE
Unable to stop flows once deployed

### ISSUE THREAD

**Issue by professorhantzen** [node-red/node-red#1017]
I am able to start flows in node-red, but I am not able to stop them. If it is not possible, it's an issue with the code (and if it is possible, it's not easy to find).  It is required behaviour in a system that if the user starts something, they can also stop it - typically with the same button.

**Comment by hardillb** [comment]
Please use the Mailing list (https://groups.google.com/forum/#!forum/node-red) for feature requests. This has been discussed before few times, but I can't find the definitive answer just now

**Comment by hardillb** [comment]
https://groups.google.com/forum/#!msg/node-red/kkggrkgNQbs/YhCMhrcgovMJ;context-place=forum/node-red

**Comment by professorhantzen** [comment]
Ok, I will post again there. Thanks for the quick reply.

**Comment by dceejay** [comment]
:-)  I tried pressing the "Pay" button on Amazon twice and it didn't stop anything...
