### ISSUE TITLE
Node-red problem

### ISSUE THREAD

**Issue by abhikanimilli** [node-red/node-red#1021]
I cannot copy the code in  function space and also in template body while editing the template node & function node even i am not getting the cursor to write in that space.

**Comment by hardillb** [comment]
What platform and browser are you using? The default browser on Raspberry pi has problems,so please use chrome or Firefox.

**Comment by abhikanimilli** [comment]
i am using default browser on Raspberry pi.

**Comment by abhikanimilli** [comment]
can i download chrome or Fromefox on Raspberry

**Comment by hardillb** [comment]
See the end of the "Running on Raspberry Pi" section of the documentation here:

**Comment by knolleary** [comment]
@abhikanimilli for future questions, please use the mailing list or slack - both linked from the bottom of http://nodered.org

Thanks!

**Comment by abhikanimilli** [comment]
@hardillb Thanks for your advice i have installed chrome in my raspberry pi every thing is working fine know.
