### ISSUE TITLE
msg.options not set in XML builder

### ISSUE THREAD

**Issue by martin-doyle** [node-red/node-red#1022]
In the info of the XML node it sais: 

> You can also pass in a msg.options object to overide all the multitude of parameters.

This works for **parsing** XML strings since the function call
`parseString(msg.payload, options, function (err, result) {` 
fits to the parameter in node-xml2js 
`exports.parseString = function(str, a, b) ...` 

For **building** XML in the function call
`builder.buildObject(msg.payload, options)` 
the options parameter is ignored since in node-xml2js buildObject only takes the input object 
`Builder.prototype.buildObject = function(rootObj)`.

That means that the initial options `var builder = new xml2js.Builder({renderOpts:{pretty:false}});` are fixed and cannot be changed.

The options should be set in the constructor **after** parsing `msg.options` instead.

See also #975.

**Comment by dceejay** [comment]
Hi,
thanks for spotting this - as per contribution guidelines we still need a CLA if you want to raise this as a PR... but as it's just a few lines I'm happy to manually patch them in based on your example :-)
up to you

**Comment by knolleary** [comment]
I'm sure I raised this a while ago... maybe it didn't make it out of slack

**Comment by dceejay** [comment]
OK - paying attention this time :-)...  will let @martin-doyle raise a CLA and PR if he would like - if not I'll patch manually.

**Comment by martin-doyle** [comment]
Please patch it manually, Sounds easier and faster.
