### ISSUE TITLE
HTTPIn converts binary files

### ISSUE THREAD

**Issue by nyxz** [node-red/node-red#1023]
When sending binary file to HTTPIn it gets out as a string, but not Buffer. I've tested it with text files and it works perfectly. I've tried to save binary file without going through HTTPIn node (see the configuration provided) and it worked.

So I am guessing HTTPIn is doing something wrong or I am missing something big here. I suspect the request body is converted to string instead of using the Buffer, so I converted the payload to Buffer as so:

```
const buf = new Buffer(msg.payload, 'hex');
msg.payload = buf.toString();
return msg;
```

but this made the payload empty string.

Here is my node configuration. It consists of:

1. Sending WAV file flow.
1. Receiving requests on HTTPIn `/PostWav` and saving them to file on the filesystem.
1. Sample file save/copy flow just to verify the file can be moved without the HTTPIn node.

```
[{"id":"1b0d473e.900d99","type":"http in","z":"1ee61851.2a5d4","name":"WAV handler","url":"/PostWav","method":"post","swaggerDoc":"","x":100,"y":314.4444580078125,"wires":[["5b1cd1fb.fa993","5325b83d.678a98","c112f01e.bf42f"]]},{"id":"5b1cd1fb.fa993","type":"function","z":"1ee61851.2a5d4","name":"Say \"Got it\"","func":"msg.payload=\"got it, YEAH!\";\nreturn msg;","outputs":1,"noerr":0,"x":336.4444580078125,"y":314.5714111328125,"wires":[["614bc4b8.6db024"]]},{"id":"614bc4b8.6db024","type":"http response","z":"1ee61851.2a5d4","name":"Output to requester","x":667.873046875,"y":315.84130859375,"wires":[]},{"id":"3aaf66c5.2e08f2","type":"inject","z":"1ee61851.2a5d4","name":"Send Local Wav","topic":"","payload":"/Users/nyxz/hello.wav","payloadType":"str","repeat":"","crontab":"","once":false,"x":116.01593017578125,"y":148.047607421875,"wires":[["a19875b4.7f51e","b27c5108.01fd48"]]},{"id":"c5929832.827f18","type":"http request","z":"1ee61851.2a5d4","name":"HTTP Post WAV","method":"POST","ret":"txt","url":"http://localhost:1880/PostWav","tls":"","x":1064.1785888671875,"y":146.829345703125,"wires":[["2ee67588.6e8332"]]},{"id":"2ee67588.6e8332","type":"debug","z":"1ee61851.2a5d4","name":"Log response","active":true,"console":"false","complete":"true","x":1250.730224609375,"y":146,"wires":[]},{"id":"a19875b4.7f51e","type":"debug","z":"1ee61851.2a5d4","name":"Log file path","active":true,"console":"false","complete":"payload","x":332,"y":225,"wires":[]},{"id":"3f61aed6.1bacfa","type":"file","z":"1ee61851.2a5d4","name":"Save to file","filename":"/Users/nyxz/saved.wav","appendNewline":false,"createDir":false,"overwriteFile":"true","x":646,"y":374,"wires":[]},{"id":"babfbd83.d30e28","type":"debug","z":"1ee61851.2a5d4","name":"Print binary file content","active":true,"console":"false","complete":"payload","x":685,"y":428,"wires":[]},{"id":"a9c3d2a8.bef88","type":"file in","z":"1ee61851.2a5d4","name":"Read file","filename":"","format":"","x":599,"y":148,"wires":[["5a0526c1.80b658","d40835bd.03c8d"]]},{"id":"5a0526c1.80b658","type":"debug","z":"1ee61851.2a5d4","name":"Log binary file","active":true,"console":"false","complete":"true","x":821,"y":208,"wires":[]},{"id":"d40835bd.03c8d","type":"function","z":"1ee61851.2a5d4","name":"Set Request Headers","func":"msg.headers = {\n  'Content-Type': 'application/octet-stream',\n}\nreturn msg;","outputs":1,"noerr":0,"x":822,"y":148,"wires":[["5114ac0e.e65d74","c5929832.827f18"]]},{"id":"c2fe7946.7852d8","type":"inject","z":"1ee61851.2a5d4","name":"Send Local Wav","topic":"","payload":"/Users/nyxz/Downloads/hello.wav","payloadType":"str","repeat":"","crontab":"","once":false,"x":135.5714111328125,"y":574,"wires":[["7df3e087.fde458"]]},{"id":"37acb260.933f46","type":"file in","z":"1ee61851.2a5d4","name":"Read file","filename":"","format":"","x":652.9840087890625,"y":573.2381591796875,"wires":[["4724cf62.8b02b8"]]},{"id":"4724cf62.8b02b8","type":"file","z":"1ee61851.2a5d4","name":"Save to file","filename":"/Users/nyxz/test.wav","appendNewline":false,"createDir":false,"overwriteFile":"true","x":853.428466796875,"y":572.2857055664062,"wires":[]},{"id":"b27c5108.01fd48","type":"change","z":"1ee61851.2a5d4","name":"Set filename from payload","rules":[{"t":"move","p":"payload","pt":"msg","to":"filename","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":149,"wires":[["a9c3d2a8.bef88"]]},{"id":"7df3e087.fde458","type":"change","z":"1ee61851.2a5d4","name":"Set filename from payload","rules":[{"t":"move","p":"payload","pt":"msg","to":"filename","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":417.2857666015625,"y":573.4285888671875,"wires":[["37acb260.933f46"]]},{"id":"5114ac0e.e65d74","type":"debug","z":"1ee61851.2a5d4","name":"Log Request object","active":true,"console":"false","complete":"true","x":1072,"y":206,"wires":[]},{"id":"5325b83d.678a98","type":"function","z":"1ee61851.2a5d4","name":"Convert Payload to Buffer","func":"const buf = new Buffer(msg.payload, 'hex');\nmsg.payload = buf.toString();\nreturn msg;","outputs":1,"noerr":0,"x":376,"y":373,"wires":[["3f61aed6.1bacfa","babfbd83.d30e28"]]},{"id":"c112f01e.bf42f","type":"debug","z":"1ee61851.2a5d4","name":"","active":true,"console":"false","complete":"payload","x":337,"y":435,"wires":[]}]
```
Note: When testing the issue change the payload in the input node `Send Local WAV` and also the filename in `Save to file` node.

```
Node-RED version: v0.15.1
Node.js  version: v6.8.1
Darwin 16.1.0 x64 LE
```

**Comment by knolleary** [comment]
What are you setting the `content-type` http header to?

**Comment by nyxz** [comment]
I set it to 'application/octet-stream'.

**Comment by knolleary** [comment]
Looks like the HTTP In node isn't handling `application/octet-stream` properly - will get that fixed.

In the meantime, if you use `audio/wav` as the `content-type` it will be handled properly

**Comment by nyxz** [comment]
Yep, that one worked! Thanks.

**Comment by piptan** [comment]
I am using  0.17.5 when I test these steps.

- Put file.zip on NodeRED public folder

- Use browser to get this file directly via http://example.com/file.zip. It works fine.

- create HTTP In node to accept GET request from /file.zip

- create HTTP response node and set the following response headers

    `Content-Disposition` to `attachment; filename= file.zip`

    `Content-Type` to `application/octet-stream`

- When I request this url from browser, file.zip can be downloaded but it can not be opened (corrupted). When I look at network debugger tool on browser, I can see that the Content-Type response header is `application/octet-stream; charset=utf-8` whereas Content-Disposition is set as expected .

- This is my test flow.
`[{"id":"53aa1c0f.399e14","type":"http response","z":"bbd08317.c316e","name":"display page","statusCode":"","headers":{"Content-Disposition":"attachment; filename=file.zip","Content-Type":"application/octet-stream"},"x":553,"y":316,"wires":[]},{"id":"8dc37b8a.2556b8","type":"http in","z":"bbd08317.c316e","name":"get /file.zip","url":"/file.zip","method":"get","upload":false,"swaggerDoc":"","x":203,"y":316,"wires":[["53aa1c0f.399e14"]]}]`

I wonder if my problem is the same issue here.

**Comment by hardillb** [comment]
Your sample flow doesn't actually send any data so it's always going to be corrupt (empty)

**Comment by piptan** [comment]
I have file.zip in public directory. How can I tell http-in node to send this file as an attachment (as in Content-Disposition) ? I misunderstood that it will send this file in the response.

**Comment by hardillb** [comment]
You would need to include a file node to load in the content of the file into a msg.payload before passing it to the http-response node.

Or the simpler version would be just just include it in a dir and uncomment the httpStatic section in the `settings.js` (and point it to the relevant directory) that way you wouldn't need any nodes to serv up the content.

**Comment by piptan** [comment]
Since I use NodeRED on Bluemix, is it possible for me to use file node ?

**Comment by hardillb** [comment]
It is possible, but you have to edit bluemix-settings.js to re-enable it.

But if you just want to serve static files the other method is simpler and the `httpStatic` directory should have already been enabled pointing to the `public` directory

**Comment by piptan** [comment]
I need to put some logic (check for membership) before serving the file so I have to use http in node. Where can I find the nstructions to re-enable it ?

**Comment by hardillb** [comment]
details are in bluemix-settings.js

This issue is not related to what you are trying to do, please move any further discussion to slack or the Google Group

**Comment by piptan** [comment]
I was able to use functionGlobalContext and readFileSync to load the content of the file before sending it to http response node. Thank you.
