### ISSUE TITLE
Can run tree control build using angular 

### ISSUE THREAD

**Issue by gillerman** [node-red/node-red#1027]
I am trying to run the pure angular Lidor Treeview in a ui-template.   This tree is a good one because it can dynamically load the tree on demand.  But, the tree doesn't render.  You can get a trial of the tree at: http://www.lidorsystems.com/downloads/integralui-studio-web-reg.aspx  Note sure what I am doing wrong...

**Comment by knolleary** [comment]
Hi, for general questions like this, please using the mailing list, linked from the bottom of nodered.org.

This repo is for the core of node-red, not the dashboard nodes.

**Comment by gillerman** [comment]
OK, thank you.

**Comment by knolleary** [comment]
You may want to include some more details on what you've tried when you post to the mailing list.
