### ISSUE TITLE
Connect arduino USB on docker

### ISSUE THREAD

**Issue by BartNetJS** [node-red/node-red#1028]
Hi, I'm trying to connect a arduino via usb to my docker instance running on my local machine
The command I use is:

docker run -it -p 1880:1880 -v /dev/bus/usb:/dev/bus/usb mynodered

But when i try to connect to the com3 port (where arduino is connected to), i got the error message "Cannot Open COM3"

The same nodered flows runs fine on my local machine without docker

any idea?

**Comment by knolleary** [comment]
Hi, can you ask this over on the mailing list? Link at the bottom of nodered.org. We keep the issue list for things that need fixing.

**Comment by BartNetJS** [comment]
tx @knolleary 
moved to:
https://groups.google.com/forum/#!topic/node-red/I6af5q2tGMI
