### ISSUE TITLE
Include "lodash library"?

### ISSUE THREAD

**Issue by MarceloProjetos** [node-red/node-red#1029]
Every time I update the node red, I add support lodash changing the file:

> npm\node_modules\node-red\settings.js

Adding lodash in the function functionGlobalContext: 

What do you think of the idea to include "lodash library" in nodered?

https://www.npmjs.com/package/lodash
It is 495.687 downloads in the last day.

**Comment by knolleary** [comment]
Please use the mailing list for suggestions like this.

We have no plans to add any modules to the default context.

If you move the settings file to your user directory, you won't need to reapply your changes when you update node-red.
