### ISSUE TITLE
Adding new rule into switch node

### ISSUE THREAD

**Issue by elyobelyob** [node-red/node-red#1031]
As per https://groups.google.com/forum/#!topic/node-red/uy_MHfJWUJk

If I add a new rule, it is added last by default. If I then move the rule higher, the existing links to nodes don't move down with the rules.

The new rule (say #12) becomes rule #7 and retains the links that the original rule in that position had. Ideally the previous rule #7 should move the links with it as it becomes rule #8.

Thanks

**Comment by dvv** [comment]
+1. To me, this, along with absense of hinting labels (condition or custom text) beside outputs, limits switch usage to only several outputs.

**Comment by knolleary** [comment]
Fixed in the `0.16` branch
