### ISSUE TITLE
rpi-gpio in node failed to get the valid pin state occasionally

### ISSUE THREAD

**Issue by dbaba** [node-red/node-red#1039]
I tested rpi-gpio in node in order to get the pin state whenever the state changes (low/high). Thorough the test, I found rpi-gpio in node didn't always emit the valid pin state, sometimes sent the wrong state.

Here's the schematic I tested:
```
RPi GPIO27(pullup) ---- SW(open or close) ----+ 
                                              |
RPi GND --------------------------------------+
```
The GPIO27 is pullup and is connected to GND when SW is close, so the value should be 0 (low) in that case. When SW turns to open, the state should be 1 (high).

When I turned SW on (close) and off (open) repeatedly, sometimes the pin state was incorrect, i.e. 0 for SW open.

I tried to get the pin state in the different way. This is the command I ran on the bash command line.
```
while true; do cat /sys/class/gpio/gpio27/value; sleep 0.5; done
```
The responses were always valid when the SW turned to open and close. 

So I think rpi-gpio in node seems to have some issue regarding pin state event handling but I haven't identified it yet.
Is this a bug? or is there any limitations?

---
Raspberry Pi Model: Raspberry Pi2 Model B
uname -a : Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux
NR version: v0.15.2
Node.js version: v0.12.15
Tested flow:
```
[
    {
        "id": "9d461a3.aca2068",
        "type": "rpi-gpio in",
        "z": "564f132f.1f551c",
        "name": "GPIO27 input (pullup)",
        "pin": "13",
        "intype": "up",
        "debounce": "25",
        "read": true,
        "x": 280,
        "y": 280,
        "wires": [
            [
                "2af96086.8f2ec"
            ]
        ]
    },
    {
        "id": "2af96086.8f2ec",
        "type": "debug",
        "z": "564f132f.1f551c",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 550,
        "y": 280,
        "wires": []
    }
]
```

**Comment by dbaba** [comment]
I've figured out that RPi's GPIO python library didn't work properly. So the issue is out of Node-RED scope.

Step to reproduce:

Insert a jumper wire to RPi GPIO4(Pin 7) and another jumper wire to RPi GND. Then, enter the following command on RPi.
```
cd node-red/nodes/core/hardware
$ ./nrgpio in 7 up 25
```
Now you'll see the output of the detected pin state, 0 or 1.
In order to change pin7 state, just Pin7 jumper wire to connect to GND jumper wire and the pin 7 state becomes low (grounded) or to disconnect from GND jumper wire and the pin 7 state becomes high. 
Here is a table showing my test result.

Pin State | Detected Output (0=low/1=high) | Expected?
--------- | ------------- | -------------
high         | 1                     | Yes
low         | 0                     | Yes
high         | 0                     | NO!
low         | 0                     | Yes
high         | 1                     | Yes
low         | 0                     | Yes
high         | 0                     | NO!

The GPIO library failed to detect the correct state twice in 8 state changes. This is really too bad. Changing bounce time didn't help me. The issue has been persist.

Again, the rpi-gpio in node didn't work properly because of the python library issue. I think it's a good idea for NR team to consider to provide another implementation of the node.
I also consider to develop a new node for getting GPIO state in order to avoid this issue.
Anyway, I close this issue.

**Comment by dbaba** [comment]
Filed a [ticket](https://sourceforge.net/p/raspberry-gpio-python/tickets/143/) in RPi.GPIO project.

The workaround is to use `exec` node performing `gpio` command.

```
[
    {
        "id": "d80b6cff.8f74b",
        "type": "exec",
        "z": "db437e90.74c768",
        "command": "gpio",
        "addpay": false,
        "append": "-g read 17",
        "useSpawn": "",
        "timer": "",
        "name": "Read GPIO Pin 11 (GPIO17)",
        "x": 420,
        "y": 320,
        "wires": [
            [
                "d0dae19a.b43438"
            ],
            [],
            []
        ]
    },
    {
        "id": "d0dae19a.b43438",
        "type": "debug",
        "z": "db437e90.74c768",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 650,
        "y": 240,
        "wires": []
    },
    {
        "id": "29c9250b.73973a",
        "type": "rpi-gpio in",
        "z": "db437e90.74c768",
        "name": "",
        "pin": "11",
        "intype": "up",
        "debounce": "25",
        "read": true,
        "x": 300,
        "y": 220,
        "wires": [
            [
                "d80b6cff.8f74b"
            ]
        ]
    }
]
```

**Comment by dceejay** [comment]
Thanks for digging into this. Usually the correct combination of pullup or pull down plus adjusting debounce fixes it... but obviously not here.
There is the alternative node-red-contrib-gpio that may well be worth a try also.
I did have a look at using the pigpio daemon library but that seemed to need to be run as root.

**Comment by AutoDoc1955** [comment]
I agree with dbaba.  I am seeing the same behavior.  I also agree that changing pullup settings and debounce have no effect on this behavior.  It's as if the node sends the msg.payload (containing the previous GPIO state) before evaluating the GPIO state.  If I move a node around on the flow and then deploy, the GPIO state always (I think always) comes back correctly.  I will try dbaba's exec function to see if I can put this frustrating few days struggling with this behind me.  Thanks to dbaba for the workaround!

**Comment by AutoDoc1955** [comment]
dbaba, I want to try your workaround, but I don't understand how to use it in the context of NodeRED.  Could you explain, or perhaps paste in the flow code here?
Thanks!

**Comment by AutoDoc1955** [comment]
P. S. The "gpio" command used by dbaba's Exec node needs wiringPi to be installed on the RPi.  My installation did not have wiringPi installed (I started with a Jessie Lite distro).  I installed it (sudo apt-get install wiringPi), and am now getting consistent GPIO values heading to my logfiles.  Now onto the next problem (MySQL stuff).  Thanks again to dbaba for the easy workaround!

**Comment by dbaba** [comment]
@AutoDoc1955 Thank you for the info. I wasn't aware of wiringPI.
Instead of `gpio` command, `cat` command can be a better way to get GPIO status, I guess. Try `cat /sys/class/gpio/gpioNN/value` where NN is the GPIO pin number (rather than physical pin number) if you have a chance.

**Comment by AutoDoc1955** [comment]
@dbaba yes, that seems to work.  I am having no issues with wiringPi so, for now, I will leave it alone, but if I feel like being efficient somewhere down the road, I'll go the "cat" way.

**Comment by pucbaldwin** [comment]
I had same issue - solved using the WiringPI fix above. Thanks for the suggestion.
