### ISSUE TITLE
To create a bot of facebook with node-red

### ISSUE THREAD

**Issue by Maoferro** [node-red/node-red#1040]
Goodnight,
I am a user of Node-Red And I have a problem to create a bot of facebook since some examples are not clear, also everything comes with code, while to see examples of slack or telegram these are very simple, I would like to know if with facebook you can similar to these, Thank you

**Comment by knolleary** [comment]
Hi,

for general questions, please use the mailing list - https://groups.google.com/forum/#!forum/node-red
