### ISSUE TITLE
infinite spin when remove a node that reject an error

### ISSUE THREAD

**Issue by lucas-pouchot** [node-red/node-red#1043]
Hi, why you don't set shade on this call : 
https://github.com/node-red/node-red/blob/master/editor/js/ui/palette-editor.js#L518 ?

To call shade.hide() on fail here : 
https://github.com/node-red/node-red/blob/master/editor/js/ui/palette-editor.js#L90

**Comment by knolleary** [comment]
Hi,

thanks for spotting this. We need to improve the error reporting in general, but this is a bug that needs fixing.

Nick
