### ISSUE TITLE
the remove action in palette manager don't always use the good path

### ISSUE THREAD

**Issue by lucas-pouchot** [node-red/node-red#1044]
In my case, some nodes listed in the palette manager are installed in userdir, and some in node-red home

But here : 
https://github.com/node-red/node-red/blob/master/red/runtime/nodes/registry/installer.js#L154
if the userdir is defined, the remove action will fail for nodes installed in the node-red home
Do you think the use of the file .config.json to spot the path of the node is a good idea ? Thanks.

**Comment by knolleary** [comment]
It is intended that the add/remove api only works for nodes in userDir.

It is not for nodes that have been globally installed (for example) as they are likely to have been installed as a different user (ie root) to that running node-red.

Please consider using the mailing list or slack if you have general questions about the behaviour - we try to keep the issue list for identified issues.
