### ISSUE TITLE
node-red-node-mongodb 66-mongodb.js, node-red aborts during start

### ISSUE THREAD

**Issue by pelis** [node-red/node-red#1045]
I just installed node version 7.1.0 and re-installed node-red-node-mongodb
It falls over the connect timer (setTimeout) and will not start node-red:

in 66-mongodb.js:
var connectToDB = function() {
            MongoClient.connect(node.mongoConfig.url, function(err, db) {
                if (err) {
                    node.status({fill:"red",shape:"ring",text:RED._("mongodb.status.error")});
                    node.error(err);
                    node.tout = setTimeout(connectToDB(), 10000);

I removed () so the line is now:
                    node.tout = setTimeout(connectToDB, 10000);

Now node-red restarts properly...

**Comment by hardillb** [comment]
Can you include the actual error message please

**Comment by hardillb** [comment]
Actually ignore that last request, just spotted what you meant

**Comment by dceejay** [comment]
Hi - thanks @pelis 
closed by - a9d669411c7947bff22bda250e134dc11ded75d1
now v0.0.10
