### ISSUE TITLE
Generate a node.js file from node-red

### ISSUE THREAD

**Issue by phuckhoi2494** [node-red/node-red#1047]
Hi everyone, I have created some flows in node-red. 
I think after pressing "Deploy", Node-red will generate a node.js file to run the code.
Could you please tell me how to read the node.js file which is generated from node-red ?
Thank you very much.

**Comment by dceejay** [comment]
Hi, for general questions please use the mailing list or slack channel.
we would prefer to keep the issues for problems with the code. thanks

It generates a flows_....json file that is json not js.  It is meant to be read and executed by Node-RED - though you are welcome to look at it if you wish.
