### ISSUE TITLE
Add support for env vars in credentials

### ISSUE THREAD

**Issue by zain** [node-red/node-red#1051]
In the MQTT broker config, setting username and password to env vars (e.g. `$(MQTT_USER)` and `$(MQTT_PASS)`) has no effect. Would be great to support env vars for credentials too.

**Comment by knolleary** [comment]
Reopening after adding a review comment to https://github.com/node-red/node-red/commit/d042169f2e4c15cbdc975e62a035b44d04aa5186#commitcomment-19854436

**Comment by dceejay** [comment]
re-closed by 8d5286703f6e873b6b4bb7131a6509310a2ec4e0
