### ISSUE TITLE
Suggestion: MongoDB node - connection retries

### ISSUE THREAD

**Issue by pelis** [node-red/node-red#1052]
I have a few mongodb nodes in my flows.
The all try to connect during node registration and continue to try to re-connect for ever, even when the node does not receive any input. That leads to permanent erros on the console and the debug window. That's why I have to remove such nodes when I am not connected to the mongodb...

I suggest that:
- the node tries to connect when the first input comes in
or
- you could somehow tell the node when it should connect (make that configurable)
or
- stop trying to re-connect when no message comes in for a certain time

**Comment by dceejay** [comment]
... or we could just suppress all but the first error...  ?

**Comment by dceejay** [comment]
Publish a fix (to stop all but first warning) as v0.0.11 on npm - Note this is actually against the node-red-nodes project - 7a39c6f70be58ae03c44cd4b4c25f04dff3e6f86
