### ISSUE TITLE
Stall / Hang during deploy

### ISSUE THREAD

**Issue by niklaswall** [node-red/node-red#1056]
Hi,

I have been evaluating node-red for some weeks now and I am very happy with how it works!

One thing that happens to me frequently (on two installations) is that the "deploy action" hangs and I'm forced to restart node-red for the flows to work again.

Console output:
```
Welcome to Node-RED
===================

16 Nov 20:36:11 - [info] Node-RED version: v0.15.2
16 Nov 20:36:11 - [info] Node.js  version: v4.2.6
16 Nov 20:36:11 - [info] Linux 4.4.0-21-generic x64 LE
16 Nov 20:36:11 - [info] Loading palette nodes
16 Nov 20:36:13 - [info] Dashboard version 2.1.0 started at /ui
16 Nov 20:36:13 - [warn] ------------------------------------------------------
16 Nov 20:36:13 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
16 Nov 20:36:13 - [warn] ------------------------------------------------------
16 Nov 20:36:13 - [info] Settings file  : /home/niho/.node-red/settings.js
16 Nov 20:36:13 - [info] User directory : /home/niho/.node-red
16 Nov 20:36:13 - [info] Flows file     : /home/niho/.node-red/flows_homer.json
16 Nov 20:36:13 - [info] Server now running at http://127.0.0.1:1880/
16 Nov 20:36:13 - [info] Starting flows
16 Nov 20:36:13 - [info] [inject:Off] crontab = 00 23 * * *
16 Nov 20:36:13 - [info] [inject:Auto] crontab = 00 06 * * *
16 Nov 20:36:13 - [info] Started flows
16 Nov 20:36:14 - [info] [mqtt-broker:f38f94e0.d36968] Connected to broker: mqtt://api.example.com:1883
16 Nov 20:39:21 - [info] Stopping flows
16 Nov 20:39:21 - [info] [inject:Off] stopped
16 Nov 20:39:21 - [info] [inject:Auto] stopped
```

Looking at the dev-console in Chrome reveals that the POST to http://10.10.10.10:1880/flows takes a very long time and finally returns with the body `{"code":"version_mismatch"}`, and then a dialog with the message "The server is running a more recent set of flows. Are you sure you want to deploy?" shows up.

At this stage no more information is shown in the console, and if i restart node-red and reload the UI the changes have been saved and exists.

This basically happens every time I deploy... but it occasionally works.

Any idea? What more information do you want?

**Comment by knolleary** [comment]
What non-core nodes are you using? One of them is hanging when it has been requested to stop.

If you can narrow down which node is causing it, we can point this issue in the right direction.

**Comment by niklaswall** [comment]
I'm using Inject, mqtt, bigtimer (node-red-contrib-bigtimer) and ui_switch (node-red-dashboard)... and I'm pretty sure that bigtimer is the only one that is the common denominator with my other install.

What's the easies way forward to confirm that that's the problem?

**Comment by niklaswall** [comment]
Problem disappeared after removing bigtimer.
