### ISSUE TITLE
Locales not read using custom nodes in separate nodes folder

### ISSUE THREAD

**Issue by zlatinejc** [node-red/node-red#1060]
When using custom nodes in separate nodes folder, node-red won't apply the locales folder (i18n).

The problem does not appear if custom nodes are moved to node-red's node_modules folder.

**Comment by knolleary** [comment]
The locale support is only available to properly packaged nodes - those that provide a package.json file and are on the module path. It is not available to local nodes (ones which are just the .js and .html files)

**Comment by zlatinejc** [comment]
Just to be clear, "on the module path" means that they must be either linked or physically exist in the node-red's node_modules dir ?

**Comment by hardillb** [comment]
Or installed in the global node_modules directory

**Comment by knolleary** [comment]
They can either be in the same `node_modules` directory as you have `node-red` installed, or, more typically, in the `node_modules` directory under your user directory - usually `~/.node-red/node_modules`

**Comment by zlatinejc** [comment]
ok, that makes sense, but could you explain the meaning of the field "nodesDir" in the settings.js

The settings.js says:

// Node-RED scans the `nodes` directory in the install directory to find nodes.
// The following property can be used to specify an additional directory to scan.

Is this redundant then ?

**Comment by dceejay** [comment]
or indeed - remove from settings file ? (but leave code there for legacy)

**Comment by zlatinejc** [comment]
It would be nice to extend it's functionality again.

I would personally use it as a separate project container and reuse it with the same runtime environment.

Thank you guys for your quick responses.

**Comment by sbarwe** [comment]
just walked in the same situation, that locales under ./node-red/nodes/xxxxx/nodename seemed not be accessible from within the nodes html but indeed it loaded into the node-red namespace from the runtime as the i18ln data was available from the url http://host:1880/locales/node-red/nodename.  I didn't track it down, but maybe it does not work becauses the locales out of the .nodes directory are not in the right namespace? 

I will move away from ./nodes directory and will use "npm link"-approach.

**Comment by knolleary** [comment]
Correct. A node's namespace is determined by the module it is loaded from. If it is not loaded from a module it is assumed to be in the default node-red namespace.

Will make the docs more explicit.

**Comment by sbarwe** [comment]
I moved with "npm link" and the namespace changed as you mentioned. Nevertheless it is still not working for me, but I do not see what's going wrong comparing my to other nodes using i18n... details here https://groups.google.com/forum/#!topic/node-red/X9ZZi8idu1A

**Comment by knolleary** [comment]
Closing as we have #1604 that covers the same issue
