### ISSUE TITLE
Can not set msg.payload.$set in Change Node

### ISSUE THREAD

**Issue by ukiller** [node-red/node-red#1063]
When I use a Function Node I can assign a value to msg.payload.$set. This is not supported in the Change Node. I found no escape notation for the $. Either I am doing something wrong or this assignment is not supported in the Change Node.

I need this feature to update records in mongodb.

![functionnode](https://cloud.githubusercontent.com/assets/11464601/20494692/6fe78d5a-b01e-11e6-898f-103fb6a096b7.jpg)
![changenode](https://cloud.githubusercontent.com/assets/11464601/20494691/6fe41f4e-b01e-11e6-8f90-bbb4819a422d.jpg)

Kind regards
Udo

**Comment by knolleary** [comment]
As with normal JavaScript you cannot use a $ unquoted.

Try `payload['$set']`

**Comment by ukiller** [comment]
Tanks for your fast reply. Why is the invalid notation supported in the
function node?

Am 21.11.2016 19:23 schrieb "knolleary" <notifications@github.com>:

**Comment by knolleary** [comment]
Huh - you're quite right. Some over zealous syntax checking - `msg.payload.$set` is valid javascript.

You can use the `['$set']` workaround for now, but will get this fixed.

**Comment by knolleary** [comment]
Note to self - need to allow either `$` or `_` to appear at the start of an identifier.

**Comment by ukiller** [comment]
Looking forward to it.

Am 21.11.2016 19:45 schrieb "knolleary" <notifications@github.com>:

**Comment by ukiller** [comment]
Sorry to bug you: Where do I find typedInput.js in my installation, so I can patch in your changes?
Thanks for the fix.

Am 21.11.2016 um 22:37 schrieb knolleary <notifications@github.com>:

Closed #1063 <https://github.com/node-red/node-red/issues/1063> via 564902b <https://github.com/node-red/node-red/commit/564902b886282dd9443c39487869af13e2d12bbf>.

**Comment by dceejay** [comment]
It will be in the minified js file - you will need to download the development version from master and build it locally (using grunt build) to repack it. I'd suggest the workaround suggested may be easier for now.

**Comment by ukiller** [comment]
Thanks for clarification. 

The recommended workarround doesn't work in the Change Node. It is just ignored. No problem here as I can use the function node. So msg.payload['$set'] changes nothing in the Change Node. Give it a try.

Am 22.11.2016 um 09:48 schrieb Dave Conway-Jones <notifications@github.com>:

It will be in the minified js file - you will need to download the development version from master and build it locally (using grunt build) to repack it. I'd suggest the workaround suggested may be easier for now.

**Comment by knolleary** [comment]
Odd - the workaround works just fine for me. What version of node-red are you using?

**Comment by ukiller** [comment]
It says v0.15.2 after the last update (this weekend).
