### ISSUE TITLE
Possible to enforce some rules on connector types?

### ISSUE THREAD

**Issue by kayazinc** [node-red/node-red#1064]
Example, Enforce some rules that node "male" output can only be used as input to node "female", other  nodes cannot be used as input to node "female".

p.s: non-sexist, this is just an example.

**Comment by knolleary** [comment]
Hi,

as per our contribution guidelines, please use the mailing list to discuss ideas for features etc.

In this instance we already have #872 to cover this sort of thing. It isn't something we've got plans for currently, but the idea has been captured.

Thanks,
Nick
