### ISSUE TITLE
Is there a limit to the size when making HTTP POST requests ?

### ISSUE THREAD

**Issue by fchanson** [node-red/node-red#1075]
Hi,

when using a HTTP in node, with POST method, I obtain the error "Error : request entity too large".

Is there a limit to the size of the request ?
If so, what is this limit ?

Thanks.

**Comment by hardillb** [comment]
The default is 5mb and it can be set in the settings.js

Look for apiMaxLength key:

```
// The maximum size of HTTP request that will be accepted by the runtime api.
// Default: 5mb
//apiMaxLength: '5mb',
```

**Comment by fchanson** [comment]
Thanks a lot hardillb.
