### ISSUE TITLE
I got stuck with running serialport

### ISSUE THREAD

**Issue by chanhyeoni** [node-red/node-red#1076]
When I hit the command node-red, I could not find out the Arduino nodes which I thought downloaded. And it seems that the following message shows I have problems with serialport.

```
Welcome to Node-RED
===================

1 Dec 16:24:26 - [info] Node-RED version: v0.15.2
1 Dec 16:24:26 - [info] Node.js  version: v7.2.0
1 Dec 16:24:26 - [info] Darwin 16.1.0 x64 LE
1 Dec 16:24:26 - [info] Loading palette nodes
1 Dec 16:24:27 - [info] Dashboard up and running
1 Dec 16:24:27 - [warn] ------------------------------------------------------
1 Dec 16:24:27 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
1 Dec 16:24:27 - [warn] [serialport] Error: The module '/usr/local/lib/node_modules/node-red-node-serialport/node_modules/serialport/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
1 Dec 16:24:27 - [warn] [upm-grove-button] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-led] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-light] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-relay] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-rgb-lcd] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-rotary] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-sound] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-temperature] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-grove-servo] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [upm-curieimu] Error: Cannot find module 'mraa'
1 Dec 16:24:27 - [warn] [arduino] Error: Cannot find module 'firmata/node_modules/serialport'
1 Dec 16:24:27 - [warn] ------------------------------------------------------
1 Dec 16:24:27 - [info] Settings file  : /Users/chlee021690/.node-red/settings.js
1 Dec 16:24:27 - [info] User directory : /Users/chlee021690/.node-red
1 Dec 16:24:27 - [info] Flows file     : /Users/chlee021690/.node-red/flows_Changhyuns-MacBook-Air.local.json
1 Dec 16:24:27 - [info] Server now running at http://127.0.0.1:1880/
1 Dec 16:24:27 - [info] Starting flows
1 Dec 16:24:27 - [info] Started flows
^C1 Dec 16:24:34 - [info] Stopping flows

```

What I did was to install what I think would be missing libraries (firmata, node-red-node-serialport, serialport, etc) and to downgrad the node version, but it still didn't work. Is there anything I'm missing?

**Comment by dceejay** [comment]
we don't support node.js 7.x

**Comment by mrsalhaoui** [comment]
please I have the same Problem : 

4 Apr 11:30:10 - [info] Node-RED version: v0.17.5
4 Apr 11:30:10 - [info] Node.js  version: v6.9.2
4 Apr 11:30:10 - [info] Linux 4.4.18-yocto-standard ia32 LE
4 Apr 11:30:23 - [info] Loading palette nodes
4 Apr 11:31:06 - [info] Dashboard version 2.1.0 started at /ui
4 Apr 11:31:20 - [warn] ------------------------------------------------------
4 Apr 11:31:20 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
4 Apr 11:31:20 - [warn] [upm-grove-button] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-led] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-light] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-relay] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-rgb-lcd] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-rotary] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-sound] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-temperature] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-grove-servo] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] [upm-curieimu] Error: Cannot find module 'mraa' (line:3)
4 Apr 11:31:20 - [warn] ------------------------------------------------------
4 Apr 11:31:20 - [info] Settings file  : /home/root/.node-red/settings.js
4 Apr 11:31:20 - [info] User directory : /home/root/.node-red
4 Apr 11:31:20 - [info] Flows file     : /home/root/.node-red/flows_iot2000.json
4 Apr 11:31:21 - [info] Server now running at http://127.0.0.1:1881/
4 Apr 11:31:21 - [info] Starting flows
4 Apr 11:31:21 - [info] Started flows
4 Apr 11:35:06 - [info] Stopping flows

**Comment by knolleary** [comment]
@mrsalhaoui hi - rather than add a comment to an old, closed issue, you may want to email the node-red mailing list for support. Links on nodered.org
