### ISSUE TITLE
How to store an object between flow invocations

### ISSUE THREAD

**Issue by fchanson** [node-red/node-red#1077]
Hi,

the context of a function can be used to store object between each invocation of this function.

Is it possible to store object between each invocation of a flow ?
For example : 
- a client invokes a flow and we store a value at the end of this flow.
- the same client invokes again the same flow and at the beginning of the flow, we want to retrieve the previous stored value.

I don't want to use a database or a file to store/retrieve the value.

**Comment by knolleary** [comment]
Hi, please use the mailing list for general questions. Linked at the bottom of nodered.org.

Have a look at the 'Waiting Function' docs and the section of flow/global context.

thanks, Nick

**Comment by knolleary** [comment]
Oops - Writing Functions - http://nodered.org/docs/writing-functions#storing-data

**Comment by knolleary** [comment]
Ok - rereading your question, I see you are aware of context in a Function node. You can also get/set context properties using the Change node. I'm not clear what else you require.... but as I said, please take this to the mailing list.
