### ISSUE TITLE
xFunction: extended feature based on function node

### ISSUE THREAD

**Issue by gbrault** [node-red/node-red#1078]
I have relaxed a bit the sandbox of the function node, please ([see](https://github.com/gbrault/xfunction)).
This allows to write more powerful flows with the xFunction Node using the Node-Red editor without going to the Node design level...

**Comment by knolleary** [comment]
Hi,

Am not sure what the purpose of this issue is. Are you proposing these changes get made to the core Function node?

**Comment by gbrault** [comment]
Thanks for the quick answer! I would recommend to add this node to the core, not replace the existing core function node which provides a more restricted sandbox: this is good to avoid issues for basic programming.
One alternative could be to have a switch to the function configuration: depending on the switch, the function behaves as per today core function or as the xfunction I am proposing!
Your decision of course!

**Comment by dceejay** [comment]
Are there any particular RED functions you are trying to get to, that maybe we should expose rather than opening it up totally ?

There is a contributed unsafe function node that let's you do anything you like.

**Comment by gbrault** [comment]
Thanks for the lead, yes, I can use that except for that: I have to check.

**Comment by gbrault** [comment]
I tried, but wasn't able to make it work...

**Comment by dceejay** [comment]
what exactly are you trying to do ?
(though this thread would be better discussed on the mailing list or slack as it's not really an issue)

**Comment by gbrault** [comment]
Just give me a link where to discuss this issue... Thanks

**Comment by dceejay** [comment]
Hi - either Slack - https://nodered.org/slack
or the Mailing list - https://groups.google.com/forum/#!forum/node-red

**Comment by knolleary** [comment]
Hi - going to close this issue. We're not adding another Function node as that will confuse users.
There are existing community nodes that don't run in the sandbox env our node does - there are trade-offs to be made on performance over convenience over security.

**Comment by gbrault** [comment]
Thanks @knolleary perfectly understood: it was just a suggestion!
