### ISSUE TITLE
MQTT - Continue to Publish (QoS1/2) Messages to Queue when Connection Broken.

### ISSUE THREAD

**Issue by muglar** [node-red/node-red#1079]
Or have the ability to increase the connection timeout.  Believe this is currently 15 minutes.  If this could be set as a variable - would accomplish a similar result.

**Comment by zlatinejc** [comment]
Why not take advantage of MQTT's cache system ?

**Comment by muglar** [comment]
Would love too, but you can expose this feature based on the default
imlipmenation in node red.

**Comment by muglar** [comment]
zlantinejc, do you know how to take advantage of MQTT's cache system when the out MQTT detects a disconnection from the broker?

**Comment by dceejay** [comment]
please have general how-to discussions on the mailing list or slack channel.
The default reconnect timeout is set in settings.js and is 15s. The keepalive timeout is set in the broker configuration and defaults to 60s. If you want/need to add queueing to the client (not the broker) then you need to implement that.

**Comment by zlatinejc** [comment]
@muglar just to answer your question, the caching system is available by default (only in ram mode). If you want to rewrite it (for persistent storage), you have to look at it's npm implementation to do that.
