### ISSUE TITLE
HTTP Request Pass Through

### ISSUE THREAD

**Issue by wrathagom** [node-red/node-red#1080]
For the HTTP Request Node, can we pass through the request msg to the response and store it in msg.request ? I think this would help with troubleshooting but could also be used for sequential API requests. Ideally there would be a flag wether or not you wanted the request passed through and a way to set which field it was stored to. That would allow alot of flexibility.

`msg = {'body': 'Hello, World"}`

**HTTP Request Node** 

`msg = {payload: 'Hello, Back", statusCode: 200, headers: {...}, request: {'body': 'Hello, World"}}`

**Comment by wrathagom** [comment]
Please let me know if you think this would be better served in a repo, I can create a node-red-http-passthrough repo and base it off of your core http node.

**Comment by knolleary** [comment]
Are there specific fields of the request object that are of interest?

Can you explain how it would help with sequential api requests?

**Comment by wrathagom** [comment]
This may be highly too specific, but a couple of use cases for me specifically would be corporate APIs, where I have to GET an order, that order has a customer ID, so then I have to get Customer. Sometimes I have to make several calls to complete the record for what I am looking for.

Another example is elastic search, where I may want to GET a record based on some input, perform some operation on it and re-insert it.

Do those help or not?

**Comment by knolleary** [comment]
The question is then what properties of the response are you trying to access that we don't already make available on the message object sent by the node?

**Comment by wrathagom** [comment]
I don't want additional response properties, I want the full message sent as an input to the node to pass through and be part of the output.

**Comment by dceejay** [comment]
So mainly around GET requests then. The response object has a property res.responseUrl  that has the full url that provided the response...  so sounds like what you would be after.

**Comment by wrathagom** [comment]
Sorry, I clearly am not doing a good job of explaining what I need. So let's say I send this as the input to the http node:

```
{
  "payload": {
    "orderNumber": 12345,
    "partNumber": ABC123jhda,
    "orderQuantity": 37,
    "netPrice": 127.00,
    "customerId": 1234
  }
}
```

I want to perform a GET to load the customer info. so I use the http node, method: GET, url: http://myrestapi/customer/{{customerId}}

I would like it to return something along the lines:
```
{
  "payload": Response Body,
  "statusCode": 200,
  "headers": headers object,
  "request": {
    "payload": {
      "orderNumber": 12345,
      "partNumber": ABC123jhda,
      "orderQuantity": 37,
      "netPrice": 127.00,
      "customerId": 1234
    }
  }
}
```

So my resulting message has all of the info going into the node, plus all of the information from the response.

Maybe I am missing a really easy way of doing this, which would be a Nice surprise. Thanks for working through it with me.

**Comment by wrathagom** [comment]
Nevermind, I was able to use change node's to move the payload to a new field and continue to do that to build my object.
