### ISSUE TITLE
chrome auto-fill acts innappropriately with some node configs

### ISSUE THREAD

**Issue by btsimonh** [node-red/node-red#1081]
with reference to:
https://groups.google.com/forum/#!topic/node-red/NOajBI_3_Hc

for some node configs (any with an input field marked as 'password'), Chrome will try to auto-fill the fields if a password has been saved against the IP:port of RED.

e.g. HTTP Request
Make sure you have stored a user/password in chrome for the node-red address.
Drop an HTTP Request node onto a flow.  Open the config, click Done, then open the config a second time:  The 'enable basic authentication' is now checked with auto-filled user and password...

Research indicated that *one* way to solve this is to hide a dummy password entry box as the first item in the form; a little 'hacky', but it was the simplest/best solution I found,

If this seems a sound solution, then we would need to is:
Identify and update all core nodes which need updating.
Add a recommendation to the documentation on making node-red nodes.

**Comment by btsimonh** [comment]
Looking at the red.js code, it seems a hidden input text element is pre-pended to the forms already.  (3 places in editor/js/ui/editor.js).
Maybe pre-pending a hidden password entry would solve this for all nodes; if we felt that auto-fill was not appropriate for node forms at all?

**Comment by knolleary** [comment]
@btsimonh possibly. I need to dig into this some more. I know Chrome has changed how you can disable its auto-fill function a number of times, so needs to be done with some care to not be too hacky.

Currently heads down on some other things at the moment, which is why I've not done anything on this issue yet, but we will endeavour to resolve it one way or another in the next release.

**Comment by btsimonh** [comment]
@knolleary Understood, was not chasing - just though I'd note the find of the other hidden field here for reference; found the hidden field whilst generally trying to understand node-red config - I was not looking specifically for a solution to this issue.  I don't see this issue as a show stopper or urgent :)....
