### ISSUE TITLE
Need to Reset delay node

### ISSUE THREAD

**Issue by tomtom30** [node-red/node-red#1087]
Hi,
I need to reset delay after it launched.
Is it possible to add this feature to existing core delay node?
Really thx

**Comment by knolleary** [comment]
Hi, as per our contributing guidelines, please discuss feature requests on the mailing list.

In this instance you'll also have to provide some more details. I'm not clear what you mean by resetting the delay, or how you would want that to work.

It may be possible to do what you want with the existing Trigger node... but without details I cannot say for sure.

Nick

**Comment by tomtom30** [comment]
Hi, I'am new on github and i don't understand how it works. Where is the mailing list?

**Comment by knolleary** [comment]
Hi @tomtom30 - no problem.
When you clicked 'new issue', you would have seen this:

<img width="502" alt="cursor_and_new_issue_ _node-red_node-red" src="https://cloud.githubusercontent.com/assets/51083/21245811/a37eeb3e-c31c-11e6-8bd7-77ceec06266f.png">

Click the highlighted 'guidelines for this repository' and it will tell you what you need to know, including a link to the mailing list.

**Comment by tomtom30** [comment]
Oh really thx ! sorry for this fake issue
