### ISSUE TITLE
Salesforce - SOQL - Dynamic parameters

### ISSUE THREAD

**Issue by tmdvd07** [node-red/node-red#1090]
I am newbie to node-red and seeking for your help. I installed salesforce node-red libraries and able to establish a connection with salesforce. I am trying to fetch salesforce account by id where id is a query parameter (pass param in run time).

Select Id, name from Account where id = ?

Input = either query parameter or body. (input = msg.req.headers.accountId)

Can you please help me how to pass the parameter run time ? Thanks in advance.

**Comment by knolleary** [comment]
Hi, this issue list is for the core of Node-RED. Please use the mailing list for questions about third party nodes.
