### ISSUE TITLE
What's the z property ?

### ISSUE THREAD

**Issue by vimniky** [node-red/node-red#1091]
Hi !  What's the `z` property  of a  node ? I'm confused !

Here's the description from the node-red doc:
`There are some reserved names for properties that must not be used. These are:
  type, x, y, z, wires, outputs`

**Comment by knolleary** [comment]
Hi,

For general questions please use the mailing list. 

The 'z' property of a node identifies which flow/subflow the node appears on.

Nick

**Comment by vimniky** [comment]
@knolleary Thanks !
