### ISSUE TITLE
enhancement: visual indication of console output on debug node

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1094]
It's hard to tell which debug node is writing output to the console.
Would it be possible to add a little icon to the outside of the debug node, to show when it's in "debug tab and console" output mode?

**Comment by dceejay** [comment]
just a static indication presumably ?  
If you have 2 then you would still have to work it out... but...

**Comment by knolleary** [comment]
At most it would be something prepended to the label, as we do for repeating inject nodes.

**Comment by dceejay** [comment]
(yup that's where I was heading) - or appended

**Comment by andysc** [comment]
yes, absolutely fine… just so you don’t have to open each one to see if it’s the one that’s spewing content
