### ISSUE TITLE
Benefits of declaring modules beforehand in the settings.js?

### ISSUE THREAD

**Issue by wstam88** [node-red/node-red#1097]
I'm wondering what the benefits are when declaring modules beforehand in the settings.js.

For example, why use it like this: 'os:require('os')' in settings.js? Why not use 'require:require' in settings.js and use it in functions like context.global.require('os')? With the latest example one can install node modules and use them without restarting node-red or altering the settings.js.

I use the last example all the time without any known downsides.

Are there any known reasons why not to go with the last example?

**Comment by knolleary** [comment]
Hi, please use the mailing list for discussions and questions like this. Many thanks, Nick

**Comment by wstam88** [comment]
No problem! Thanks for answering!
