### ISSUE TITLE
node-red-node-serialport

### ISSUE THREAD

**Issue by Dinotoh1971** [node-red/node-red#1099]
I have installed node-red-node-serialport via 'Manage palette'. I can see the nodes Serial In and Serial Out in palette after installed. After I reboot the device, the Serial In and Serial Out nodes no longer can be seen in palette.

Can anyone helps on this issue? Thank you.

**Comment by knolleary** [comment]
Hi, for general help/support questions, please use the mailing list linked at the bottom of https://nodered.org

**Comment by dceejay** [comment]
by default we currently pre-install the serialport - so there should be no reason to have to install it.
If it wasn't there already - which platform is this and which version of Node-RED. 

NOTE - as  of v 0.16 we WON"T preinstall serialport so you will need to add it... - but at time of writing that hasn't happened)
