### ISSUE TITLE
normalisePropertyExpression seems not to return the correct answer + follow up discussion

### ISSUE THREAD

**Issue by vucuong12** [node-red/node-red#1101]
When I tried to get global value: globalContext.get("192.168.1.1"), an error appears:

> TypeError: Cannot read property '168' of undefined

I found out that the key "192.168.1.1" is changed by function normalisePropertyExpression in (`red/node-red/runtime/util.js`) to an array `msgPropParts: ["192",168,1,"1"]`. Therefore, basically, we no longer have the key "192.168.1.1". We instead have 4 keys: `"192",168,1,"1"`, which causes the above exception.

I am wondering what is the purpose of such a change made by normalisePropertyExpression function since it goes against the rule of pure JavaScript in this case.

**Comment by knolleary** [comment]
Hi,

in JavaScript, `192.168.1.1` on its own is not a valid property expression:

For example, you cannot do:

    var a = b[192.168.1.1]

If you want to use `192.168.1.1` as a key to an object, it has to be treated as a string:

    var a = b['192.168.1.1']

So you cannot simply use `192.168.1.1` as a property key.

You should use `'192.168.1.1'` - a subtle but vital difference. However it appears we also choke on that - which is a bug and I'll fix it for 0.16 release.


In the meantime, you could add another layer in your property name:

    globalContext.get("ipAddress['192.168.1.1']")

Or just do a `.replace(".","-")` before passing to `globalContext.get()` to avoid the issue at all.

**Comment by vucuong12** [comment]
Hi Nick,

Thanks for noticing the bug and the suggestion for the temporary solution. 

I actually used the string "192.168.1.1" (not 192.168.1.1). Replacing ".' with '_' is a good idea for btw :)

**Comment by knolleary** [comment]
Hi @vucuong12 

You are using ` globalContext.get("192.168.1.1")`

The value of the string you are passing is `192.168.1.1`.

Once we fix it, you'd need to use: `globalContext.get("'192.168.1.1'")` - note the extra quotes.

**Comment by vucuong12** [comment]
Thanks @knolleary . I got it :)
