### ISSUE TITLE
Missing type when override existed module

### ISSUE THREAD

**Issue by cfsghost** [node-red/node-red#1106]
My application is working on IBM Bluemix, so that the mongodb module is coming from `node-red-bluemix-nodes` NPM module. for reasons, I must override the mongodb module of `node-red-bluemix-nodes` by my customized module. 

I suppose that old one will be ignored if my module exists in the `nodesDir` directory(Is it right?), but I got the problem below: 
> Welcome to Node-RED
> ===================
> 
> 8 Jan 03:18:43 - [info] Node-RED version: v0.15.3
> 8 Jan 03:18:43 - [info] Node.js  version: v6.2.1
> 8 Jan 03:18:43 - [info] Darwin 15.6.0 x64 LE
> 8 Jan 03:18:44 - [info] Loading palette nodes
> 8 Jan 03:18:44 - [warn] [ibm hdfs in] Deprecated call to RED.runtime.nodes.registerType - node-set name must be provided as first argument
> 8 Jan 03:18:44 - [warn] [ibm hdfs] Deprecated call to RED.runtime.nodes.registerType - node-set name must be provided as first argument
> 8 Jan 03:18:45 - [warn] [ibmpush] Deprecated call to RED.runtime.nodes.registerType - node-set name must be provided as first argument
> 8 Jan 03:18:45 - [warn] ------------------------------------------------------
> 8 Jan 03:18:45 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
> 8 Jan 03:18:45 - [warn] [mongodb] Error: mongodb already registered
> 8 Jan 03:18:45 - [warn] [tcp] Error: tcp in already registered
> 8 Jan 03:18:45 - [warn] [udp] Error: udp out already registered
> 8 Jan 03:18:45 - [warn] ------------------------------------------------------
> 8 Jan 03:18:45 - [info] Settings file  : /Users/fred/projects/works/iii/iovdp/settings.js
> 8 Jan 03:18:45 - [info] User directory : /Users/fred/.node-red
> 8 Jan 03:18:45 - [info] Flows file     : /Users/fred/.node-red/flows_FENG-HSIANGdeMacBook-Pro.local.json
> 8 Jan 03:18:45 - [info] Server now running at http://127.0.0.1:1880/
> 8 Jan 03:18:45 - [info] Waiting for missing types to be registered:
> 8 Jan 03:18:45 - [info]  - mongodb (provided by npm module node-red-node-mongoldb
> 8 Jan 03:18:45 - [info]  - mongoldb in
> 8 Jan 03:18:45 - [info] To install any of these missing modules, run:
> 8 Jan 03:18:45 - [info]   npm install <module name>
> 8 Jan 03:18:45 - [info] in the directory:
> 8 Jan 03:18:45 - [info]   /Users/fred/.node-red)

If I remove the `mongo` folder of `node-red-bluemix-nodes`, it works well.

**Comment by knolleary** [comment]
Hi, you cannot have the same type registered twice.

You need to either remove `node-red-bluemix-nodes` as a dependency, or give your custom mongo nodes unique type names - eg `cfsghost-mongdb`

If you have any further questions, please follow up on the node-red mailing list. This issue list is for core issues.

Many thanks,
Nick
