### ISSUE TITLE
looping when serial port goes away

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#111]
If you pull out the plug on a USB serial connection which is being written to by a serial output node, it goes into a flat spin, saying:
[error] [serial out:HRM] Error: Error Input/output error calling write(...)
zillions of times a second, and also putting an error in the debug window.
My flow is only writing to the port once every 5 seconds, but it's making vastly more error messages than that.
Can we have a retry timer and maybe an eventual timeout on serial write errors, please?

**Comment by dceejay** [comment]
Has been fixed upstream - no longer spins on unplug of USB serial port.
