### ISSUE TITLE
mqtt cannot connect with protocol version mqttv311

### ISSUE THREAD

**Issue by arthurlutz** [node-red/node-red#1110]
There seems to be no way to configure the protocol version to be used by mqtt in node-red.

I'm trying to connect to a mqttv311 server, so my node ends up "disconnected". 

On the mqtt server side I get : 

```
INFO:hbmqtt.broker:Connection from 127.0.0.1:48710 on listener 'default'
WARNING:hbmqtt.broker:[MQTT-3.1.0-1] (client @=127.0.0.1:48710): Can't read first packet an CONNECT: [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"
```

To connect to it using mosquitto client I do : 

```
mosquitto_sub -v -V mqttv311 -t "#" -h localhost
```

**Comment by knolleary** [comment]
<img width="251" alt="node-red" src="https://cloud.githubusercontent.com/assets/51083/21769171/395a22d4-d675-11e6-815d-dcea5a460862.png">

There is the checkbox in the broker properties dialog.

**Comment by arthurlutz** [comment]
@knolleary thanks for your answer, which version of node-red is that ? am on 0.15.2 from raspbian. If I need to upgrade what is the recommended path ?

**Comment by knolleary** [comment]
That option is in 0.15.2 - it defaults to using 3.1, so you need to untick it to get 3.1.1.

**Comment by arthurlutz** [comment]
I don't have that configuration, am I missing something ? some additional configuration somewhere ? some additional npm install ? 

![screenshot_2017-01-09_15-40-36](https://cloud.githubusercontent.com/assets/108437/21770068/fef39bd6-d681-11e6-95d9-3530a0725247.png)

**Comment by knolleary** [comment]
The option I showed has been in since 0.12. Your screenshot is from a much olded version of node-red than 0.15.2.

Can you double check what version you are running?

**Comment by knolleary** [comment]
Any update?

**Comment by arthurlutz** [comment]
sorry, I had an old nodered.js that was in the way so eventhough dpkg told me the version was 0.15.2 I was running an older version. Moved it out of the way and go the settings like your screenshot. Thanks for your help.
