### ISSUE TITLE
Securing Node-RED with user and password

### ISSUE THREAD

**Issue by namgk** [node-red/node-red#1111]
Hi,

Seems like a bug, steps to reproduce at commit 75855d54504f28677947659857ae5ea906487001:

* Clone the repo, npm install and npm run build.
* Modify settings.js: un-comment the adminAuth block
* Start node red and go to http://localhost:1880
* Login

Unexpected result: cannot load editor.

**Comment by knolleary** [comment]
Hi, we will need some more details to understand what's happening here.

1. Did you confirm you can load the editor before you enable adminAuth?
2. Did you just uncomment adminAuth or did you also configure it with proper values?
3. What error do you get when trying to load the editor?

**Comment by knolleary** [comment]
Recreated - investigating.

**Comment by knolleary** [comment]
Thanks for spotting this!
