### ISSUE TITLE
Node Red TCP connection to Helvar DALI router

### ISSUE THREAD

**Issue by albertogazzin** [node-red/node-red#1112]
Hi all,
I need to push HelvarNet (example of ASCII string for request a firmware version to router: >V:1,C:191#) string to Helvar DALI Router.
I use the TCP-in connection block and I set the IP of my Helvar Router. The block show me "Connected". At the input of this block i put the inject block with ASCII command >V:1,C:191# as string payload type.
I put the TCP-out block and I set the IP of my Helvar Router. The block show me "Connected". I connect the output of TCP-out block with debug block for read the response from my Helvar Router. It should be ?V=1,C=1, but nothing appear in debug window.

Where I have a mistake?
Many thanks for your help!

**Comment by knolleary** [comment]
Hi - for general question/help please use the node-red mailing list - https://groups.google.com/forum/#!forum/node-red 

The issue list is for tracking development of the project.

**Comment by dceejay** [comment]
try the **tcp-request** node instead
(but yes - should be on the mailing list or slack channel)

**Comment by albertogazzin** [comment]
I'm sorry!

                  Alberto Gazzin

----- Messaggio originale -----
Da: "knolleary" <notifications@github.com>
Inviato: ‎10/‎01/‎2017 22:41
A: "node-red/node-red" <node-red@noreply.github.com>
Cc: "albertogazzin" <alberto.gazzin@gmail.com>; "Author" <author@noreply.github.com>
Oggetto: Re: [node-red/node-red] Node Red TCP connection to Helvar DALI router(#1112)

Hi - for general question/help please use the node-red mailing list - https://groups.google.com/forum/#!forum/node-red
The issue list is for tracking development of the project.
