### ISSUE TITLE
MQTT in and out nodes not recognised by 0.16.0

### ISSUE THREAD

**Issue by Bra1nK** [node-red/node-red#1113]
Just upgraded to 0.16.0 to the newly released version 16 and all my flows are stopped due missing node types. From the log 
Waiting for missing types to be registered:
- mqtt-broker
- mqtt in
- mqtt out
MQTT seems to be broken on the version, how do I revert to previous version ?

**Comment by knolleary** [comment]
Hi,

The Node-RED log will report why the mqtt nodes have failed to register. What does it say?

How have you got Node-RED installed and how did you update it?

**Comment by Bra1nK** [comment]
I was on version 0.15.3
pm2 logs node-red gives me :+1: 
node-red-4 (out): 11 Jan 22:27:18 - [info] Loading palette nodes
node-red-4 (out): 11 Jan 22:27:31 - [info] Dashboard version 2.2.1 started at /ui
node-red-4 (out): 11 Jan 22:27:39 - [warn] ------------------------------------------------------
node-red-4 (out): 11 Jan 22:27:39 - [warn] [mqtt] SyntaxError: /usr/lib/node_modules/node-red/node_modules/mqtt/lib/connect/index.js:100
node-red-4 (out):     const isSecure = ['mqtts', 'wss'].indexOf(opts.protocol) !== -1
node-red-4 (out):     ^^^^^
node-red-4 (out): Use of const in strict mode.
node-red-4 (out): 11 Jan 22:27:39 - [warn] ------------------------------------------------------
node-red-4 (out): 11 Jan 22:27:39 - [info] Settings file  : /home/brian/.node-red/settings.js
node-red-4 (out): 11 Jan 22:27:39 - [info] User directory : /home/brian/.node-red
node-red-4 (out): 11 Jan 22:27:39 - [info] Flows file     : /home/brian/.node-red/flows_raspberrypi2.json
node-red-4 (out): 11 Jan 22:27:39 - [info] Server now running at http://127.0.0.1:1880/
node-red-4 (out): 11 Jan 22:27:39 - [debug] loaded flow revision: 8ca039d5bae519dcf89f09299c386a9a
node-red-4 (out): 11 Jan 22:27:39 - [debug] red/runtime/nodes/credentials.load : no user key present
node-red-4 (out): 11 Jan 22:27:39 - [debug] red/runtime/nodes/credentials.load : using default key
node-red-4 (out): 11 Jan 22:27:39 - [info] Waiting for missing types to be registered:
node-red-4 (out): 11 Jan 22:27:39 - [info]  - mqtt-broker
node-red-4 (out): 11 Jan 22:27:39 - [info]  - mqtt in
node-red-4 (out): 11 Jan 22:27:39 - [info]  - mqtt out

**Comment by knolleary** [comment]
What version of node.js are you using?

**Comment by Bra1nK** [comment]
v0.12.9

**Comment by knolleary** [comment]
Ok, skipping ahead, I believe you are using node.js 0.10 or 0.12.

As per the release blog post, those versions are no longer supported by node-red, nor the node foundation itself.

For now, you can use `node-red@0.15.3` as the argument to whatever npm install command you ran to upgrade in order to go back to that previous level.

**Comment by dceejay** [comment]
so ...
sudo npm cache clean
sudo npm install -g --unsafe-perm node-red@0.15.3

**Comment by knolleary** [comment]
Only use `sudo` and `-g` if you used then previously....!

**Comment by Bra1nK** [comment]
I did (see above) and it's running now. How do I upgrade to a more recent version of node.js (I'm using a raspberrypi2) so I can upgrade node-red.

**Comment by knolleary** [comment]
Sorry, I missed that bit of your comment. Thanks to dcj for spotting.

How did you install node.js? The fact you've got 0.12 means you've done it manually somehow as the prepackaged version is 0.10

**Comment by dceejay** [comment]
![image](https://cloud.githubusercontent.com/assets/5375409/21870304/9c91bb34-d853-11e6-9765-37c962920d54.png)

![image](https://cloud.githubusercontent.com/assets/5375409/21870312/a8a294de-d853-11e6-80db-193f1b1053c9.png)

http://nodered.org/docs/hardware/raspberrypi#upgrading

**Comment by dceejay** [comment]
which will end up with

    wget https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered -O update-nodejs-and-nodered
    update-nodejs-and-nodered

**Comment by Bra1nK** [comment]
OK I'll look at that tomorrow as it's well past my bedtime and I've just got my flows running again. Thanks both of you for your prompt help . Next time I'll RTM !!

**Comment by thomasvnl** [comment]
I'm having the same problem, but with Node-red 0.16.2

OS: Ubuntu 16.04
Node version: v6.10.2
Npm version: 3.10.10

I've got build-essential, make, gcc, g++, python installed so any prerequisite should be covered.

This is the only logging I get from node-red when starting:

```10 Apr 19:23:14 - [info]

Welcome to Node-RED
===================

10 Apr 19:23:14 - [info] Node-RED version: v0.16.2
10 Apr 19:23:14 - [info] Node.js  version: v6.10.2
10 Apr 19:23:14 - [info] Linux 4.4.0-72-generic x64 LE
10 Apr 19:23:14 - [info] Loading palette nodes
10 Apr 19:23:15 - [warn] ------------------------------------------------------
10 Apr 19:23:15 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
10 Apr 19:23:15 - [warn] [mqtt] Error: Cannot find module 'util-deprecate'
10 Apr 19:23:15 - [warn] [feedparse] Error: Cannot find module 'util-deprecate'
10 Apr 19:23:15 - [warn] ------------------------------------------------------
10 Apr 19:23:15 - [info] Settings file  : /home/thomas/.node-red/settings.js
10 Apr 19:23:15 - [info] User directory : /home/thomas/.node-red
10 Apr 19:23:15 - [info] Flows file     : /home/thomas/.node-red/flows_JARVIS.json
10 Apr 19:23:15 - [info] Creating new flow file
10 Apr 19:23:15 - [info] Starting flows
10 Apr 19:23:15 - [info] Started flows
10 Apr 19:23:15 - [info] Server now running at http://127.0.0.1:1880/
```
