### ISSUE TITLE
new debug logging omits keys starting with underscore

### ISSUE THREAD

**Issue by travisghansen** [node-red/node-red#1117]
When payload is a structured (and perhaps other msg properties) object that contains keys starting with `_` then the debug tab omits them with displaying the object.

raw json sent
```
{"params": ["WikiStart"], "_method": "wiki.getPage", "id": 123}
```
debug tab message (copy/pasted)
```
msg.payload : Object
object
params: array[1]
0: "WikiStart"
id: 123
```

I'm certain the messages are being passed through correctly with the properties there, it's just a debug tab issue.

**Comment by knolleary** [comment]
This was done on purpose in the early stages of developing the new debug view - the msg.req/res objects emitted by the `HTTP In` node are huge and contain lots of 'internal' properties that start with a `_`.  Filtering these properties had a huge performance impact - but I did intend to revisit it before release. Thanks for bringing it up.

**Comment by dceejay** [comment]
maybe an option in debug - "show hidden properties" ? (like many file explorers)

**Comment by knolleary** [comment]
No need - can largely remove the filter as there were lots of other performance improvements made along the way - for example, we don't build the full message - we only build each 'level' as you expand it. That solved the main issue the `_` properties caused.

**Comment by travisghansen** [comment]
@knolleary yeah, that sounds sane.  Looking forward to the update!
