### ISSUE TITLE
Option to delete all config nodes on tab deletion

### ISSUE THREAD

**Issue by biancode** [node-red/node-red#1118]
Hi,

it would be very helpful, if there could be an option to decide for deletion of all config nodes referenced in tab on delete. That would help in stress testing.

cya

**Comment by knolleary** [comment]
As mentioned before, feature suggestions on the mailing list please.

**Comment by knolleary** [comment]
Config nodes owned by a tab should already get deleted when the tab is deleted. What is the behaviour you would like?

**Comment by dceejay** [comment]
At the bottom right of a config node there is a select box... 
![image](https://cloud.githubusercontent.com/assets/5375409/21965072/0c9c2c08-db50-11e6-97ea-6aa7c9d7c459.png)
by default configs start off global... If they are set to a particular tab they should get deleted. 
If global they will remain in case anyone else may want to use them.
