### ISSUE TITLE
Wrong placeholder expression

### ISSUE THREAD

**Issue by dbaba** [node-red/node-red#1120]
I've found a weird substitution expression [here](https://github.com/node-red/node-red/blob/0.16.1/red/runtime/locales/en-US/runtime.json#L31) as shown below.
```
            "install-failed-not-found": "$t(install-failed-long) module not found",
```

The entry is used by the following [code](https://github.com/node-red/node-red/blob/0.16.1/red/runtime/nodes/registry/installer.js#L99):
```
log.warn(log._("server.install.install-failed-not-found",{name:module}));
```
So I think the entry should be `__name__ module not found` rather than `$t(install-failed-long) module not found`. What about it?

NR version: v0.16.1

**Comment by knolleary** [comment]
The `$t()` is valid syntax used to reference another message in the catalog. See http://i18next.com/docs/jsons/#v1 for details.

So this is intended to result in the `install-failed-long` message followed by the text `module not found`. However it looks like you have found a bug - the `$t()` expression needs to be fully qualified. Fix pushed to master.
