### ISSUE TITLE
Authentication of inbound websocket connections

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#1127]
Provide a mechanism to allow inbound connections to be authenticated.

Spinning this out from #797 which covers outbound requests.

**Comment by knolleary** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authentication of Inbound WS connections](https://trello.com/c/2iLYs9CJ/79-authentication-of-inbound-ws-connections)

**Comment by ruchiranet1** [comment]
This is available on Node.js.  I have tried the following and it is working fine for me. Need similar in NodeRED. 

In client we need to set the token. 
ws = new WebSocket 'ws://localhost:8001',{
        headers : {
          token: "OurToken"
        }
      }

In server side access it by,  req.headers.token
http://iostreamer.me/ws/node.js/jwt/2016/05/08/websockets_authentication.html

**Comment by knolleary** [comment]
The `WebSocket.Server` object can take a `verifyClient` function that is called to authenticate connections. That is the hook we need to expose.

That'll be done via the settings file; where you will be able to provide that function, just as you can provide custom HTTP middleware for the HTTP nodes.

**Comment by knolleary** [comment]
**Note**: the ability to set custom HTTP headers on the initial HTTP Upgrade request is a feature of the Node.js websocket library. It is **not** part of the standard WebSocket object available in browsers - https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by atsage** [comment]
Add line `msg.req = socket.upgradeReq;` in `WebSocketListenerNode.prototype.handleEvent` (somewhere around line 180) will pass HTTP headers through in the msg object.
