### ISSUE TITLE
0.16.1: Cannot paste in editor, and no alternatives to keyboard combo.

### ISSUE THREAD

**Issue by Lenbok** [node-red/node-red#1128]
I upgraded Node-Red on my raspberry pi from the standard distro version (0.14?) to the current release 0.16.1. My flows are all running fine, however I have editing problems.

I can copy nodes with ctrl-c (and the popup appears to confirm that they have been copied), but ctrl-v will no longer paste. 

This is using Chromium on linux. Under Firefox copy and paste works fine.

**Comment by knolleary** [comment]
Hi, what browser are you using to access Node-RED? There are known issues with the default Pi browser. We recommend Firefox or Chrome.

**Comment by Lenbok** [comment]
I'm accessing from Chromium on Ubuntu 16.04. It also works fine from an incognito window.

Suspecting extensions, I disabled them and restarted the browser, and copy/paste works fine. I re-enabled the extensions, and it still works fine, so maybe it was the browser restart that was required to clear some kind of state.

Sorry for the noise, I'll close this.
