### ISSUE TITLE
functionGlobalContext initialization not working

### ISSUE THREAD

**Issue by bsculley** [node-red/node-red#1130]
I'm running node-red on Raspberry Pi. 

Heres the syslog for service startup:

```
Jan 26 05:14:51 porkpi Node-RED[9936]: 26 Jan 05:14:51 - [info] Node-RED version: v0.16.2
Jan 26 05:14:51 porkpi Node-RED[9936]: 26 Jan 05:14:51 - [info] Node.js  version: v4.7.2
Jan 26 05:14:51 porkpi Node-RED[9936]: 26 Jan 05:14:51 - [info] Linux 4.4.38-v7+ arm LE
Jan 26 05:14:52 porkpi Node-RED[9936]: 26 Jan 05:14:52 - [info] Loading palette nodes
Jan 26 05:14:56 porkpi Node-RED[9936]: 26 Jan 05:14:56 - [info] Dashboard up and running
Jan 26 05:15:00 porkpi Node-RED[9936]: 26 Jan 05:15:00 - [info] Dashboard version 2.2.1 started at /ui
Jan 26 05:15:04 porkpi Node-RED[9936]: 26 Jan 05:15:04 - [info] Settings file  : /home/pi/.node-red/settings.js
Jan 26 05:15:04 porkpi Node-RED[9936]: 26 Jan 05:15:04 - [info] User directory : /home/pi/.node-red
Jan 26 05:15:04 porkpi Node-RED[9936]: 26 Jan 05:15:04 - [info] Flows file     : /home/pi/.node-red/flows_porkpi.json
Jan 26 05:15:04 porkpi Node-RED[9936]: 26 Jan 05:15:04 - [info] Server now running at http://127.0.0.1:1880/
Jan 26 05:15:04 porkpi Node-RED[9936]: 26 Jan 05:15:04 - [info] Starting flows

```

I currently have this setting for functionGlobalContext:

```
    functionGlobalContext: {
        net: require('net'),
        nine: 9
    },

```
I have tried this in /home/pi/.node-red/settings.js and in  /usr/lib/node-modules/node-red/settings.js.  I tried it individually, in each file, simultaneously in both files, all combinations; nothing works.  

The net library I'm trying to use is installed under the home/pi/.node-red directory, but I also included the simple "nine" setting just to eliminate any complications.  That doesn't work either.  I have tried to access these settings with both global.nine and the global.get('nine') style access
[settings.zip](https://github.com/node-red/node-red/files/732490/settings.zip)
.  Doesn't work.  Result is always "undefined".

I'm sure this is something simple I'm doing wrong, but I can't figure it out.  I have attached the /home/pi/.node-red/settings.js file.

[settings.zip](https://github.com/node-red/node-red/files/732496/settings.zip)
Any help will be greatly appreciated.

**Comment by knolleary** [comment]
Hi,
I am not able to reproduce this. Using exactly the value you provide, I am able to access both properties as expected - see example flow below.

You can see in the log output that Node-RED is using `/home/pi/.node-red/settings.js` - so that is the settings file you should be editing.

One point is `net` is the name of a node.js built-in module. By calling `require('net')` you are probably going to get the built-in version, not one you've installed yourself.. but I'm not sure.



```
[{"id":"60bff2f6.e8c7ac","type":"function","z":"feee1df.c3263e","name":"","func":"msg.payload = global.get('nine');\nreturn msg;","outputs":1,"noerr":0,"x":270,"y":340,"wires":[["143dfd40.bd7d13"]]},{"id":"bfc2651.ef77c98","type":"inject","z":"feee1df.c3263e","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":131,"y":344,"wires":[["60bff2f6.e8c7ac"]]},{"id":"143dfd40.bd7d13","type":"debug","z":"feee1df.c3263e","name":"","active":true,"console":"false","complete":"false","x":410,"y":340,"wires":[]}]
```

**Comment by bsculley** [comment]
Hi,
Thanks for checking this.  I am editing /home/pi/.node-red/settings.js.  That's the file I attached.  I imported the flow you generated but it still doesn't work for me.  Debug shows:
```
‎1‎/‎26‎/‎2017‎ ‎9‎:‎02‎:‎54‎ ‎AMnode: 53b919cc.2d3c38
msg.payload : undefined
undefined

```
Is there any trace or log I can enable/use to troubleshoot this?

**Comment by bsculley** [comment]
I figured it out.  I had two functionGlobalContext blocks in the settings.js file and the second one was apparently overriding the first.  I know it was a bonehead mistake, but still it would be nice if there was some way to detect it.  
Is this considered an error?  If so, it would be good to log it somewhere, and if not I suggest that the function of the second instance should be to add new definitions or override like named ones.

**Comment by hardillb** [comment]
Unfortunately this is just the way javascript works, if you have multiple matching keys in an object then it will only use the last one

**Comment by bsculley** [comment]
Too bad.
