### ISSUE TITLE
functionGlobalContext is not importing function.

### ISSUE THREAD

**Issue by AndreGuerra123** [node-red/node-red#1132]
I'm trying to import a module called: integrate.
npm install -g integrate

I changed the settings.js in \.node-red correctly.

this is the error I get after trying global.get("integrate")  inside a  function.

ok, there it goes:

var Integrate= new global.get("integrate");
 
function myODE(t, y) {
  // ordinary differential function to integrate.
  
  y=context.u*y;
  
  
  
  return y;  // for an initial value y=0, this function is also known as 'e^x' 
}
 
// step 1: get the integrators for your function 
var integrate = Integrate.Integrator(myODE);

var y = context.X0,
    t = context.dt,
    step = 0.25;
    

while (true) {
  // step 2: integrate! 
  console.log('t = ' + t + '   \t', y);
  if ((t += step) && t > 2) break;
  y = integrate.euler(y, t, step);
}

return msg;

And the result:

1/27/2017, 8:31:01 PM node: Integrator
function : (error)
"TypeError: Integrate.Integrator is not a function"

Any tip? 

Best regards, 
André

**Comment by hardillb** [comment]
As mentioned in the contributing guidelines questions should be asked on the Newsgroup or the Slack channel linked to from the http://nodered.org page.

but remove the "new" from the first line

**Comment by AndreGuerra123** [comment]
I registered in that Slack group, sorry I'm a beginner, it will not happen again. By the way removing the 'new' didn't work (I tried that before). You can delete this post and I will keep my questions in that group.

**Comment by sbarwe** [comment]
shouldnt it be context.global ?

**Comment by knolleary** [comment]
@sbarwe that is the old syntax. http://nodered.org/docs/writing-functions#storing-data

@AndreGuerra123 I believe this was resolved in slack? Please let me know so we can close this issue off.

**Comment by sbarwe** [comment]
@knolleary oh, missed that (settings.js contains wrong syntax then https://github.com/node-red/node-red/blob/master/settings.js#L175)

**Comment by knolleary** [comment]
Closing. Please reopen if you believe this is a genuine issue.
