### ISSUE TITLE
Cloudflare HTTP Proxy causes palette loading to fail

### ISSUE THREAD

**Issue by flaviuspopan** [node-red/node-red#1134]
When enabling the HTTP proxy on cloudflare, node-red fails to load the palette, claiming "Imported unrecognized types". Works fine when cloudflare proxy disabled. 

HTTP_PROXY Environmental variable set outside of settings.js:

`HTTP_PROXY=http://cloudflare.com:443`

SSL successfully terminates on HAProxy load balancer in front of node-red, but the same problem exists when node-red itself is setup for HTTPS.

Node-RED version: v0.16.1
Node.js  version: v6.9.4

The following messages are displayed in the console:

**red.min.js:16 WebSocket connection to 'wss://test.mydomain.io/comms' failed: Error during WebSocket handshake: Unexpected response code: 503**

**Uncaught TypeError: d._ is not a function
    at Array.eval (main.min.js:16)
    at WebSocket.d.onmessage (red.min.js:16)**

**Comment by Belphemur** [comment]
Disable the RocketLoader in CloudFlare, it's still in beta and doesn't work well with any javascript heavy website.

**Comment by flaviuspopan** [comment]
@Belphemur ......I would just like you to know that my gratitude right now is astronomical. I've been trying to fix this for _weeks_. I can't believe it was all because of that, wow. Thanks!
