### ISSUE TITLE
Cannot show subflow on touch devices

### ISSUE THREAD

**Issue by andig** [node-red/node-red#1136]
i.e. on iPad long-press on subflow (either nodes pane or flow editor) does not bring up any option to show the subflow contents.

**Comment by nielsnl68** [comment]
I have the dame issuebon my android tablet

**Comment by knolleary** [comment]
Lots of touch-related issues with subflows were fixed in 1.1.0 (and earlier). You can dbl click a subflow instance node and then click the 'edit subflow template' button in the edit dialog to access the subflow template.
