### ISSUE TITLE
Tcp request node: creates multiple linked messages

### ISSUE THREAD

**Issue by M0ebiu5** [node-red/node-red#1137]
I feed the tcp request node one message to read settings from logitech media server.  The tcp node emmits the response from the server with 2 messages. 
This messages have a different payload, but all other attributes are identical (even _msgid) and linked. So if i filter the messages by topic and then change the topic, the second message never gets through, cause the topic change of the first message also affects the second one.

Is this behavior intentional? If yes, how can i avoid this linked messages?

example:`[{"id":"df6514ea.ae8728","type":"tab","label":"Flow 5"},{"id":"74b57bea.33ac84","type":"function","z":"df6514ea.ae8728","name":"read settings","func":"msg.payload = \"\"\nmsg.payload += \"00:04:20:28:87:d3 playlist shuffle ?\\n\"\nmsg.payload += \"00:04:20:28:87:d3 mixer volume ?\\n\"\nmsg.payload += \"00:04:20:28:87:d3 power ?\\n\"\n\nmsg.topic = \"read settings\";\nreturn msg;","outputs":1,"noerr":0,"x":281,"y":95,"wires":[["e69e9a96.bc59e8"]]},{"id":"e69e9a96.bc59e8","type":"tcp request","z":"df6514ea.ae8728","server":"big","port":"9090","out":"sit","splitc":"0","name":"","x":462,"y":144,"wires":[["e739aed2.0606e"]]},{"id":"e739aed2.0606e","type":"function","z":"df6514ea.ae8728","name":"buffer to string","func":"\n//var b = new Buffer( msg.payload, 'hex' );\nmsg.payload = msg.payload.toString()\nreturn msg;\n\n","outputs":1,"noerr":0,"x":639,"y":181,"wires":[["3bd66e11.2d40d2"]]},{"id":"1c271b70.369b35","type":"inject","z":"df6514ea.ae8728","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":87,"y":74,"wires":[["74b57bea.33ac84"]]},{"id":"3bd66e11.2d40d2","type":"debug","z":"df6514ea.ae8728","name":"","active":true,"console":"false","complete":"true","x":811,"y":195,"wires":[]}]`

**Comment by dceejay** [comment]
Is it actually two parts of the same packet that have been split (that should really be joined first before continuing) ? or two separate messages ? 
Where are you changing the topic ?

**Comment by M0ebiu5** [comment]
How do i know, if the package has been split and i have to join them? Now, i send one message into the tcp node and i get two out. Or at least it looks like 2 messages... 

Here is the flow including the split and change node.  `[{"id":"df6514ea.ae8728","type":"tab","label":"Flow 5"},{"id":"74b57bea.33ac84","type":"function","z":"df6514ea.ae8728","name":"read settings","func":"msg.payload = \"\"\nmsg.payload += \"00:04:20:28:87:d3 playlist shuffle ?\\n\"\nmsg.payload += \"00:04:20:28:87:d3 mixer volume ?\\n\"\nmsg.payload += \"00:04:20:28:87:d3 power ?\\n\"\n\nmsg.topic = \"read settings\";\nreturn msg;","outputs":1,"noerr":0,"x":281,"y":95,"wires":[["e69e9a96.bc59e8"]]},{"id":"e69e9a96.bc59e8","type":"tcp request","z":"df6514ea.ae8728","server":"big","port":"9090","out":"sit","splitc":"0","name":"","x":462,"y":144,"wires":[["e739aed2.0606e"]]},{"id":"e739aed2.0606e","type":"function","z":"df6514ea.ae8728","name":"buffer to string","func":"\n//var b = new Buffer( msg.payload, 'hex' );\nmsg.payload = msg.payload.toString()\nreturn msg;\n\n","outputs":1,"noerr":0,"x":639,"y":181,"wires":[["7fa1f341.2a7b8c"]]},{"id":"1c271b70.369b35","type":"inject","z":"df6514ea.ae8728","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":87,"y":74,"wires":[["74b57bea.33ac84"]]},{"id":"3bd66e11.2d40d2","type":"debug","z":"df6514ea.ae8728","name":"","active":true,"console":"false","complete":"true","x":1220,"y":230,"wires":[]},{"id":"7fa1f341.2a7b8c","type":"switch","z":"df6514ea.ae8728","name":"only reads","property":"topic","propertyType":"msg","rules":[{"t":"cont","v":"read","vt":"str"}],"checkall":"true","outputs":1,"x":829,"y":191,"wires":[["a770afb0.af0e4"]]},{"id":"a770afb0.af0e4","type":"change","z":"df6514ea.ae8728","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"restore settings","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1032,"y":211,"wires":[["3bd66e11.2d40d2"]]}]`

**Comment by dceejay** [comment]
well - what do the packets coming back look like ? Is one always the same size and the other smaller  ?

**Comment by M0ebiu5** [comment]
this are the 2 messages (output from debug node):
`2/2/2017, 12:53:46 AMb70a3bb2.7fd1a8
read settings : msg : Object
{ "topic": "read settings", "payload": "00%3A04%3A20%3A28%3A87%3Ad3 playlist shuffle 0\n", "acknowledged": true, "timestamp": 1485993218229, "lastchange": 1485993218229, "from": "system.adapter.amazon-dash.0", "name": "Dash button pressed", "_msgid": "634cde42.9cb32" }
2/2/2017, 12:53:46 AMb70a3bb2.7fd1a8
read settings : msg : Object
{ "topic": "read settings", "payload": "00%3A04%3A20%3A28%3A87%3Ad3 mixer volume 30\n00%3A04%3A20%3A28%3A87%3Ad3 power 0\n", "acknowledged": true, "timestamp": 1485993218229, "lastchange": 1485993218229, "from": "system.adapter.amazon-dash.0", "name": "Dash button pressed", "_msgid": "634cde42.9cb32" }`

**Comment by M0ebiu5** [comment]
Thanks for the fast fix and overall thanks for node-red - it's really great, elegant and powerful!

**Comment by dceejay** [comment]
thanks for spotting the bug !
