### ISSUE TITLE
mqtt: Sending messages without payload should trigger error

### ISSUE THREAD

**Issue by andig** [node-red/node-red#1138]
According to my testing messages without payload are not received by the broker (or not forwarded) and should therefore not be allowed?

**Comment by hardillb** [comment]
MQTT messages with null/empty payloads are used to clear retained messages so are a valid usecase. 

I will have to check the code to see what the MQTT out node does if there is no payload if it just swallows the message or sends a null payload

**Comment by andig** [comment]
Thanks. I've only used listeners and noticed.. nothing. So behaviour may be correct. In that instance please excuse me and thanks for the hint.

**Comment by dceejay** [comment]
if `msg.payload` does not exist then nothing is sent. If it exists as `null` or "" (blank) then it sends that - and as Nick said it can be used to clear a retained topic.

This is as designed. So closing this as nothing to fix.

**Comment by andig** [comment]
I had not set payload at all. Obviously an oversight on my side but I'd have expected the send note to tell me something's wrong then?

**Comment by dceejay** [comment]
no - we don't do that.
