### ISSUE TITLE
CSV truncates unquoted strings containing IP addresses

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red#1142]
Hi!
If we try to parse a CSV file that contains unquoted strings or double quoted strings, the result is truncated.
For example:
10.1.2.3  becomes 10.1
"10.1.2.3" becomes 10.1
'10.1.2.3' becomes "'10.1.2.3'" (double and single quotes)

**Comment by dceejay** [comment]
If you want to test  (thanks !)... can you try changing line 128 of file  70-CSV.js
to be
var reg = new RegExp("^[-]?[0-9]*\.?[0-9]+$");

Should be slightly tighter test before allow parsing as a number.

**Comment by Hugobox** [comment]
You mean line 115?
It works like a charm! Thanks!

**Comment by dceejay** [comment]
actually this seems to work better - var reg = /^[-]?[0-9]*\.?[0-9]+$/;
no idea why the different declaration makes a difference but it does...

**Comment by Hugobox** [comment]
Hi! I finally tried with your latest regExp and for my case it doesn`t work and truncates IP addresses again.

So:
 var reg = new RegExp("^[-]?[0-9]*.?[0-9]+$"); 
works!
while:
var reg = new RegExp("^[-]?[0-9.]*[\.]?[0-9]*$");
truncates my IP addresses like such:
10.102.3.7 becomes 10.102
(from a CSV line that looks like: 1001,10.102.3.7,1,1,40

**Comment by dceejay** [comment]
are you sure you have latest version ? I get
![image](https://cloud.githubusercontent.com/assets/5375409/23224185/35888600-f925-11e6-8e7f-71857a81ff97.png)
from the flow
[{"id":"622500a6.430a","type":"inject","z":"44b1be6f.c939c","name":"","topic":"","payload":"1001,10.102.3.7,1,1,40","payloadType":"str","repeat":"","crontab":"","once":false,"x":155.5,"y":737,"wires":[["bfe9152c.7bf9a8"]]},{"id":"bfe9152c.7bf9a8","type":"csv","z":"44b1be6f.c939c","name":"","sep":",","hdrin":false,"hdrout":false,"multi":"one","ret":"\\n","temp":"","x":347,"y":770,"wires":[["78c52db9.abeb54"]]},{"id":"78c52db9.abeb54","type":"debug","z":"44b1be6f.c939c","name":"","active":true,"console":"false","complete":"false","x":515,"y":794,"wires":[]}]

**Comment by Hugobox** [comment]
I copied https://raw.githubusercontent.com/node-red/node-red/master/nodes/core/parsers/70-CSV.js
in place of my 70-CSV.js instance, restarted NR and still get:
col1: 1001
col2: 10.102
col3: 1
col4: 1
col5: 40

**Comment by dceejay** [comment]
ah - cos it's not there.... it here
https://raw.githubusercontent.com/node-red/node-red/50838970eccc68819ba7b7706e62743e3aef83e8/nodes/core/parsers/70-CSV.js

**Comment by Hugobox** [comment]
Oh! So its not yet part of the master branch yet! Sorry. Thanks!

**Comment by knolleary** [comment]
Although bug fixes, which this is, ought to be in master so they get into the next maintenance release and not held out until the next milestone. Can we port it over?
