### ISSUE TITLE
email node "Error: Greeting never received"

### ISSUE THREAD

**Issue by maylo1993** [node-red/node-red#1148]
Hi!
I am a newbie on node-red, and I am trying to send an email, when a GPIO button is pressed.
Latest version of node-red (installed a week ago) on Raspbian Jessie distro RPi ver.3

I tried with 3 different mail clients that I use (gmail, outlook, yahoo) but I still get the same error on the debug tab: "Error: Greeting never received".
The email starts sending proccess and after 2-3 secs it says "send failed" and the error on the debug tab appears.

Is there any solution to this?
Thank you in advance.

**Comment by hardillb** [comment]
Please use the Google Group or Slack to ask usage questions, both are linked to from the Node-RED home page.

**Comment by maylo1993** [comment]
Ok, thank you!

**Comment by dceejay** [comment]
Actually this may be a bug... or at least could be made more easily worked around locally.
(by exposing security option).

**Comment by dceejay** [comment]
Closed by 367237d94647ea1b4b4ccc8c7f546d1481755669
