### ISSUE TITLE
Installing node-red-contrib-freeboard

### ISSUE THREAD

**Issue by patiltushar023** [node-red/node-red#1150]
Hi ,

I have installed node-red successfully .its working ,
But now i want to install   "node-red-contrib-freeboard".

I followed the instruction on https://www.npmjs.com/package/node-red-contrib-freeboard

but when i hit the "npm install node-red-contrib-freeboard" command in my node red root directory

i get this error :  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> node-red-contrib-freeboard@0.0.7 postinstall C:\Users\admin\.node-red\node_modules\node-red-contrib-freeboard
> node rewritefiles.js

{ Error: ENOENT: no such file or directory, open 'C:\Users\admin\.node-red\node_modules\node-red-contrib-freeboard\node_modules\freeboard\index.html'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\admin\\.node-red\\node_modules\\node-red-contrib-freeboard\\node_modules\\freeboard\\index.html' }
{ Error: ENOENT: no such file or directory, open 'C:\Users\admin\.node-red\node_modules\node-red-contrib-freeboard\node_modules\freeboard\js\freeboard.js'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\admin\\.node-red\\node_modules\\node-red-contrib-freeboard\\node_modules\\freeboard\\js\\freeboard.js' }
events.js:160
      throw er; // Unhandled 'error' event

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Please help me to make it run.How do i resolve this issue??

Thank you.
![screenshot 6](https://cloud.githubusercontent.com/assets/25752255/22898584/d6951bd2-f24d-11e6-86a6-9b29d4125bfb.png)

**Comment by knolleary** [comment]
Please raise this against the node's github repo. It is not one this project maintains.

**Comment by Paul-Reed** [comment]
Have a word with Stephen Krywenko via the openenergymonitor forum (PM or forum post) - https://community.openenergymonitor.org/t/a-howto-install-freeboard-with-mqtt-for-emontx-shield/1581

He's become a bit of an expert with Freeboard, and I'm sure he will help you.

Paul
