### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jvalsam** [node-red/node-red#1151]
link has changed to https://github.com/kelektiv/node.bcrypt.js/archive/v1.0.2.tar.gz

> bcrypt@1.0.2 install D:\Dropbox\PhD\Development\Puppy\node-red\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.9.3 (node-v48 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

**Comment by knolleary** [comment]
Hi, that appears to be an issue with the packaging of the bcrypt module. Have you raised an issue against their project? It isn't something we control.

**Comment by knolleary** [comment]
In fact, it appears a relevant issue has already been raised: kelektiv/node.bcrypt.js#486

**Comment by knolleary** [comment]
Checking in the upstream issue, I think this has been resolved. Closing this issue as there's nothing in our power to do about it. But please report back if you still have issues.
