### ISSUE TITLE
New install: node-red-node-feedparser

### ISSUE THREAD

**Issue by bruskiza** [node-red/node-red#1154]
Hi All,

New to reporting issues about node modules, so please forgive me if this is slightly incorrect.

Node version:

`$ node -v
v0.10.11
$ 
`

Error:

`
npm ERR! Error: No compatible version found: node-red-node-feedparser@'0.1.*'
`

Is it an out-of-date node-red-node-feedparser library?

**Comment by knolleary** [comment]
Hi,

whilst I'm not sure if it is the root cause of this specific issue, please note that we no longer support node.js 0.10 - https://nodered.org/blog/2017/01/11/version-0-16-released

Nick

**Comment by bruskiza** [comment]
:) Thanks Nick, lets try an updated node version.

**Comment by bruskiza** [comment]
All good.

node 6.9.5 works perfectly.
