### ISSUE TITLE
Support textarea for nodes

### ISSUE THREAD

**Issue by jcking** [node-red/node-red#1157]
The documentation only mentions using \<input\> or \<select\> tags in the property editor dialog. The textarea appears to work as is, however it is not styled correctly. It allows nicely copy and pasting of larger blobs of text, for instance JSON. It is missing the width style applies to the \<input\> tags, which is currently "width: 70%", so it doesn't line up nicely. Having "white-space: nowrap" applied by default would be nice as well. Going forward exposing the rich text editor, I assume CodeMirror is being used, would be nice as well for editing properties. Thoughts?

**Comment by knolleary** [comment]
We already expose a rich editor that should be used in preference to a <textarea>

You can see it in action with the Function node, the Template node etc.

It isn't properly documented on nodered.org, but you can see how to use it from those nodes.

**Comment by jcking** [comment]
Ah, okay. I started down that avenue, however I am running into an issue. This is a config node so it is different from Function and Template, "oneditprepare" is never called. Instead it calls oneditresize first, which is unexpected. Additionally there is a typo at https://github.com/node-red/node-red/blob/0a96259ddfacb10713d1419c155b40123dc54100/editor/js/ui/editor.js#L891 "editing_node" should be "editing_config_node".

**Comment by knolleary** [comment]
@jcking It does appear for config nodes that the first call to `oneditresize` happens before `oneditprepare` is called - that is a bug we'll fix. But you can easily code around it within your oneditresize function in the meantime.

**Comment by jamsden** [comment]
Could you provide some information on how to use the rich editor. I looked at the Function and Template html files, and could possibly replicate that, but some brief summary might save a lot of time and debugging.

**Comment by Digital-Thor** [comment]
I'm just casting my vote for some high-level guidance on how to invoke the editor and access the final stored data.  I looked at the [code for the 80-template and 80-function nodes](https://github.com/node-red/node-red/tree/master/nodes/core/core), but there is a lot of extra magic going on in both of them.  After spending half a day on it, I'd be happy with just a <textarea> example.
