### ISSUE TITLE
Trigger behavior

### ISSUE THREAD

**Issue by Sineos** [node-red/node-red#1159]
I have created a trigger node with following settings:

```
[
    {
        "id": "4c7b42bf.2c02dc",
        "type": "trigger",
        "z": "9c5e5fb6.9a74b",
        "op1": "",
        "op2": "0",
        "op1type": "pay",
        "op2type": "num",
        "duration": "2",
        "extend": true,
        "units": "s",
        "reset": "",
        "name": "",
        "x": 220,
        "y": 620,
        "wires": [
            []
        ]
    }
]
```

Current behavior:

1. 1st message arrives
2. Time-Out starts running
3. 1st message is passed on to the node's output 
4. 2nd message arrives
5. Time-Out is reset
6. 2nd message is **not** passed to the node's output, i.e. all subsequent messages are not piped through, although they do reset the time-out

I would have expected that all incoming messages are passed through to the output until no new messages arrive within the set interval, then `op2` is send.

Is this behavior intended?

**Comment by dceejay** [comment]
Yes - the intended behaviour is to only output the first "edge" and then the second "edge"... anything in-between is discarded until the trigger resets.

As per the contribution guidelines we prefer general Q&A via the slack channel or google group mailing list.
