### ISSUE TITLE
saving flows to API instead of local file

### ISSUE THREAD

**Issue by estradamarkie** [node-red/node-red#1161]
I managed to find the function that saved the flows into a localfile.json, instead of saving it into a local system wanted to save it to an API endpoint.

```
saveFlows: function (flows) {
        if (settings.readOnly) {
            return when.resolve();
        }


        try {
            fs.renameSync(flowsFullPath, flowsFileBackup);
        } catch (err) {
        }


        var flowData;


        if (settings.flowFilePretty) {
            flowData = JSON.stringify(flows, null, 4);
        } else {
            flowData = JSON.stringify(flows);
            saveToApi(flowData) // function below
        }
        return writeFile(flowsFullPath, flowData);
    }
```

So I've created a new function in localfilesystem.js however not sure if this is correct of doing it to send it to API, I did try this code but it was giving me some XMLHttp... error similar issue if I use jQuery ajax.post()

```
function saveToApi(content) {
    console.log('Send this to Server >> ', content)
    var xhr = new XMLHttpRequest();
    var url = '/api/Flow';
    xhr.open("POST", url, true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    var jflow = JSON.stringify({Definition: content});
    xhr.send(jflow);
}
```

I tried reading the doc but it isn't clear for me. Can someone point a correct way, please.

**Comment by knolleary** [comment]
This type of question is best suited for the mailing list, where I see you've already posted. Closing this issue.
