### ISSUE TITLE
I found a problem with the csv node.

### ISSUE THREAD

**Issue by sakaba37** [node-red/node-red#1162]
I appreciate Node-RED, a very useful tool. But, I have a problem with the csv node.

The csv node converts one double-quote in an array object to double-quote x2.
If the array object has a JSON string and it has an empty string, The csv node, it converts to double-quote x4.

However, double-quote x4 of CSV string the csv node converts to double-quote x3. It is NOT double-quote x2.

I'm happy if you fix it.

[{"id":"aecf647e.19e3b8","type":"inject","z":"1645f62c.3dbeca","name":"","topic":"","payload":"\"a\",\"b\"\"\"\"b\",\"c\"","payloadType":"str","repeat":"","crontab":"","once":false,"x":230,"y":620,"wires":[["e004d159.6444d8"]]},{"id":"e004d159.6444d8","type":"csv","z":"1645f62c.3dbeca","name":"","sep":",","hdrin":false,"hdrout":false,"multi":"one","ret":"\\n","temp":"","x":370,"y":620,"wires":[["f070aeb5.3e9018"]]},{"id":"f070aeb5.3e9018","type":"debug","z":"1645f62c.3dbeca","name":"","active":true,"console":"false","complete":"false","x":510,"y":620,"wires":[]}]

**Comment by dceejay** [comment]
Yes - from https://www.ietf.org/rfc/rfc4180.txt

       7. If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.

so "b""""b"  should become  b""b

**Comment by knolleary** [comment]
Does this fix need porting to `master` so it will be in the next maintenance release?

**Comment by dceejay** [comment]
already there - a625eeeac87dbaef69744fda67cf0a412daa8a77

**Comment by knolleary** [comment]
Ah okay, that commit doesn't reference this issue so I missed that. This issue can be closed then?

**Comment by dceejay** [comment]
sorry - yes guess so.
