### ISSUE TITLE
Neopixel Node Issue

### ISSUE THREAD

**Issue by DrLucyRogers** [node-red/node-red#1165]
Neopixels on a Pi 2 (Have tried with two Pi2’s and 3 sets of neopixels
Node v6.9.5   Npm 3.10.10 Node-RED V0.16.2

**Preliminary steps:**
1.	Download newest Jessie image from https://www.raspberrypi.org/downloads
2.	Install on SD card Instructions:  https://www.raspberrypi.org/documentation/installation/
3.	Plug SD card in to Pi, connect to wifi  and  sudo raspi-config Expand disk. Make sure ssh is enabled if you want to log on from a different computer on network
4.	Run this bash command: http://nodered.org/docs/hardware/raspberrypi
5.	update-nodejs-and-nodered 
6.	Follow instructions for Unicorn HAT https://learn.pimoroni.com/tutorial/unicorn-hat/getting-started-with-unicorn-hat
7.	Run nodered to get a .node-red directory
8.	npm install node-red-node-pi-neopixel into .node-red directory
9.	sudo systemctl enable nodered.service
10.	Attach Neopixel to 5V, Ground and data in to Pin 12 on Pi
11.	Open node-red and insert this flow:

[{"id":"3552b66d.5ca2ba","type":"inject","z":"44264cc8.daffb4","name":"Green","topic":"","payload":"1,00,FF,00","payloadType":"str","repeat":"","crontab":"","once":false,"x":81.5,"y":118,"wires":[["c141a05e.4b986"]]},{"id":"c141a05e.4b986","type":"rpi-neopixels","z":"44264cc8.daffb4","name":"","pixels":"1","bgnd":"","fgnd":"","wipe":"40","mode":"pcent","rgb":"rgb","x":323.5,"y":126,"wires":[]},{"id":"403dfbfd.0b4934","type":"inject","z":"44264cc8.daffb4","name":"","topic":"","payload":"black","payloadType":"str","repeat":"","crontab":"","once":false,"x":90,"y":234,"wires":[["c141a05e.4b986"]]},{"id":"bd2e46d3.384098","type":"inject","z":"44264cc8.daffb4","name":"Red","topic":"","payload":"1,255,0,0","payloadType":"str","repeat":"","crontab":"","once":false,"x":90,"y":70,"wires":[["c141a05e.4b986"]]},{"id":"21598ad8.9da716","type":"inject","z":"44264cc8.daffb4","name":"Blue","topic":"","payload":"1,00,00,255","payloadType":"str","repeat":"","crontab":"","once":false,"x":92,"y":182,"wires":[["c141a05e.4b986"]]},{"id":"9d1524a3.a4bd78","type":"inject","z":"44264cc8.daffb4","name":"Red","topic":"","payload":"Red","payloadType":"str","repeat":"","crontab":"","once":false,"x":86.5,"y":20,"wires":[["c141a05e.4b986"]]},{"id":"3d40d043.58dc1","type":"inject","z":"44264cc8.daffb4","name":"","topic":"","payload":"1,0,0,0","payloadType":"str","repeat":"","crontab":"","once":false,"x":89.5,"y":280,"wires":[["c141a05e.4b986"]]}]

Not giving correct colour responses if any response.

I have also used a level converter (https://www.kickstarter.com/projects/mypifi/mypifi-neopixel-controller-board-for-raspberry-pi)  with independent 5V supply. Same results.

Hope you can help!
Thanks
Lucy

**Comment by dceejay** [comment]
Hi

(to be accurate you should really raise this against the node-red-nodes project.... as that is where the code is sitting... but...)

If you set them all to (say) red ... what colour do you get
and green ? and all blue ?
Is the Pixel order box set correctly for the LED strip you have ?

**Comment by dceejay** [comment]
also you seem to be in percent mode and sending it 1(,255,0,0) - so 1 percent of 10 pixels is 0. (ish)

and indeed if in bar mode - then the first pixel is 0  :-)  so if you have 1 pixel then you need 0,255,0,0   etc (and they need to be numbers... not FF )

**Comment by DrLucyRogers** [comment]
"red" gives magenta, "1,255,0,0" and all the other "numbered" ones make it turn off. They are definitely all RGB's - but changing it to GRB makes a different not-right colour change. And apologies yet again for putting this in the wrong place.  I seem to be blind to the different places.

**Comment by dceejay** [comment]
so combining both my answers gives -
[{"id":"fbe1135d.bfce5","type":"inject","z":"ead6f540.d24f28","name":"Red","topic":"","payload":"Red","payloadType":"str","repeat":"","crontab":"","once":false,"x":206,"y":796,"wires":[["e953cecc.465ec"]]},{"id":"e953cecc.465ec","type":"rpi-neopixels","z":"ead6f540.d24f28","name":"","pixels":"1","bgnd":"","fgnd":"","wipe":"40","mode":"pixels","rgb":"rgb","x":443,"y":902,"wires":[]},{"id":"17e081ef.3a17de","type":"inject","z":"ead6f540.d24f28","name":"Green","topic":"","payload":"0,0,255,00","payloadType":"str","repeat":"","crontab":"","once":false,"x":201,"y":894,"wires":[["e953cecc.465ec"]]},{"id":"2a0af109.0b7bfe","type":"inject","z":"ead6f540.d24f28","name":"","topic":"","payload":"black","payloadType":"str","repeat":"","crontab":"","once":false,"x":209.5,"y":1010,"wires":[["e953cecc.465ec"]]},{"id":"6f0edc5c.c63b14","type":"inject","z":"ead6f540.d24f28","name":"Red","topic":"","payload":"0,255,0,0","payloadType":"str","repeat":"","crontab":"","once":false,"x":209.5,"y":846,"wires":[["e953cecc.465ec"]]},{"id":"dcebc2d3.db8a4","type":"inject","z":"ead6f540.d24f28","name":"Blue","topic":"","payload":"0,0,00,255","payloadType":"str","repeat":"","crontab":"","once":false,"x":211.5,"y":958,"wires":[["e953cecc.465ec"]]},{"id":"99e106f1.fae6d8","type":"inject","z":"ead6f540.d24f28","name":"","topic":"","payload":"0,0,0,0","payloadType":"str","repeat":"","crontab":"","once":false,"x":209,"y":1056,"wires":[["e953cecc.465ec"]]}]

**Comment by DrLucyRogers** [comment]
d'oh. However, deleting my flow and adding yours gives:

"Red" and "0,255,0,0) = Magenta
Green = white
Blue = black
Black = black

I swapped the RGB for GRB and got green and red swapped.

**Comment by dceejay** [comment]
weird.... not sure what to suggest now... these are RGB pixels and not RGBW ones ?

**Comment by DrLucyRogers** [comment]
Am using three different sets of RGB ones - all of which have been successful on Wemos.

**Comment by DrLucyRogers** [comment]
And in maybe related news - if I add the push switch, (Pull up resistor) it sometimes doesn't register a switch 1,0,1,0,0,0,1,0 etc.

**Comment by dceejay** [comment]
what happens if you "jsut' send the colour name

red
green
blue

etc - no pixel number  - just the word

**Comment by DrLucyRogers** [comment]
Same thing as when I use numbers and the pixel number.

**Comment by dceejay** [comment]
so - you installed the Pimoroni library so you should have a ~/Pimoroni/unicornhat/examples directory. go to there...   
stop Node-RED  `node-red-stop`
then    `sudo python rainbow.py`
should create a fairly fast rainbow effect

or edit the simple.py to change the set_pixel line to be x,y,255,0,0   for red etc... to test

**Comment by DrLucyRogers** [comment]
Lots of pretty rainbows

**Comment by dceejay** [comment]
re your comment re switch... can you try a) checking there are no other GPIO using pin 12... and b) removing all other GPIO nodes and just having neopixel node...  
(after re-starting Node-RED of course)... ` node-red-start`

**Comment by DrLucyRogers** [comment]
I can get in and edit the simple.py but not sure what I should be changing to what - there's a  unicorn.set_pixel(x,y,255,0,255) line - is that it?

**Comment by DrLucyRogers** [comment]
OK, removed switch and GPIO input node. It's just got the neopixel node and the injects on now. Nothing else is connected to the Pi.

**Comment by DrLucyRogers** [comment]
(Apart from USB - wifi dongle, keyboard, mouse and HDMI monitor)

**Comment by dceejay** [comment]
re three ago - yes that line - mess with it (one edit at a time) to try   x,y,255,0,0  (red) x,y,0,255,0  (green)  etc...

**Comment by dceejay** [comment]
(and or do the node-red thing... )

**Comment by DrLucyRogers** [comment]
FIXED IT!!

Apologies - it's not a Node-RED problem. It's a Pimoroni / Unicorn HAT problem.

A Pimoroni Pirate Phil Howard (@Gadetoid On twitter) says" something changed recently-ish which caused Raspbian desktop to glom onto the audio hardware much more than it used to."

To fix this: When installing using the one line unicorn HAT installer (curl -sS get.pimoroni.com/unicornhat | bash). When you get asked to choose an audio output node, Select Option 3 "Force route to digital (HDMI hot plug disabled) DO NOT USE OPTION 0.

If you have already run the script and selected the wrong option:

edit the config.txt file ( sudo nano /boot/config.txt) , Use the arrow keys, and go to the end of the file and add the following two lines;

hdmi_force_hotplug=1
hdmi_force_edid_audio=1

Save and exit, sudo reboot.

It then all works :)

Pimoroni are now aware of this, but it may be worth putting "When you get asked to choose an audio output node, Select Option 3 "Force route to digital (HDMI hot plug disabled) " somewhere in the pre-requisite notes?

**Comment by DrLucyRogers** [comment]
Pimoroni have now changed the one line unicorn HAT installer to no longer give the audio options. If there are still neopixel problems, re-run "curl -sS get.pimoroni.com/unicornhat | bash"
