### ISSUE TITLE
API GET /flow/{id} does not include database nodes configuration

### ISSUE THREAD

**Issue by SalehAly** [node-red/node-red#1166]
Hey

if I have a database node and I GET the flow containing the node via API ` GET localhost:1880/flow/{flowId}` then the configuration of the database node is not included, however, it is included in the export of the node-red UI.

I have tested it using influxdb node and mongodb node

Thanks

API
```js
{
  "id": "4880e9bc.a5c798",
  "label": "Flow 2",
  "nodes": [
    {
      "id": "126af684.cc3459",
      "type": "mongodb out",
      "z": "4880e9bc.a5c798",
      "mongodb": "5efe8db7.bf6ee4",
      "name": "",
      "collection": "test",
      "payonly": false,
      "upsert": false,
      "multi": false,
      "operation": "store",
      "x": 324.5,
      "y": 263,
      "wires": [
        
      ]
    }
  ]
}
```

Export
```js
[
    {
        "id": "126af684.cc3459",
        "type": "mongodb out",
        "z": "4880e9bc.a5c798",
        "mongodb": "5efe8db7.bf6ee4",
        "name": "",
        "collection": "test",
        "payonly": false,
        "upsert": false,
        "multi": false,
        "operation": "store",
        "x": 324.5,
        "y": 263,
        "wires": []
    },
    {
        "id": "5efe8db7.bf6ee4",
        "type": "mongodb",
        "z": "",
        "hostname": "127.0.0.1",
        "port": "27017",
        "db": "mongo",
        "name": ""
    }
]
``

**Comment by dceejay** [comment]
for general questions we prefer the mailing list (google group) or slack channel - both linked from the home page.

the config for the node is (by default) held globally ("on all pages") so you need to fetch the whole flow to get them - though people can specify them to go on a particular flow by selecting the button in the bottom right of a config page - in which case the config would be with that same flow id

![image](https://cloud.githubusercontent.com/assets/5375409/23225203/fba319ce-f928-11e6-9019-10ff70246288.png)

**Comment by SalehAly** [comment]
Thanks for your response, yes normally I use the mailing list, however, I thought this was an issue.
I haven't noticed this part of the configuration in the online documentation though, but now everything goes into place.

Thank you
