### ISSUE TITLE
Permissive switch property

### ISSUE THREAD

**Issue by vicary** [node-red/node-red#1167]
Unlike debug node, the switch node doesn't wrap `RED.util.evaluateNodeProperty(node.property,node.propertyType,node,msg);` in a try ... catch block and fall back to `undefined` in case of an error.

For example, incoming POST requests via http in nodes which may or may not come with `req.body.foo.bar` where I would like to switch on that value, and the existence of that path.

Is there a particular reason to let it throw?

**Comment by knolleary** [comment]
Thanks for the issue. Will take a look to see if we're doing that for a reason or it's an oversight.

**Comment by knolleary** [comment]
Thanks again - agreed we should be handling this better. We now treat such properties as undefined. Have added a test case to cover it as well.

**Comment by vicary** [comment]
Thank you!
