### ISSUE TITLE
RED.start() returns before flows have started 

### ISSUE THREAD

**Issue by hlapp** [node-red/node-red#1168]
The issue is in [`red/runtime/index.js#start()`](https://github.com/node-red/node-red/blob/master/red/runtime/index.js#L151) (which is called from [`RED.start()`](https://github.com/node-red/node-red/blob/master/red/red.js#L82)). As a result, the returned promise resolves before `redNodes.loadFlows().then(redNodes.startFlows)` has necessarily resolved as well.

In a standalone application of Node-RED this isn't an issue because by the time the editor starts interacting with the admin API, the flows will almost certainly have started. However, in an embedded application the controlling application has no means of knowing when flows have finished loading and starting, short of simply waiting some amount of time and hoping for the best. An alternative would be be to wait for the [`nodes-started` event(s)](https://github.com/node-red/node-red/blob/master/red/runtime/nodes/flows/index.js#L296), but the `events` API isn't exposed in the runtime.

If the flows haven't finished loading and starting by the time an API call is made that involves them, some static variables have not been initialized yet, resulting in obscure exceptions for referencing properties for an object that is `null`.

I can work out a patch for this, but before I do and submit a PR I wanted to ask whether this would be welcome, or whether the present behavior is intentional.

**Comment by knolleary** [comment]
This is the intended behaviour. See #698 and the other issues it references for background.

**Comment by hlapp** [comment]
I appreciate the difficulties of addressing the larger problem as described in #698. But what I was referring to was relatively narrow, and (I think) relatively well defined - namely how can I know when it is safe to call the flows runtime API without getting an exception.

Anyway, I don't want to belabor this. For the record, and possible benefit of others coming across this in the future, I've put up a solution based on waiting for `nodes-started` on npm: <https://www.npmjs.com/package/node-red-embedded-start>
