### ISSUE TITLE
How to get MYSQL NODE in node-red?

### ISSUE THREAD

**Issue by chaitanya9249** [node-red/node-red#1169]
Hi
I am new to node-red.I want to connect with mysql database from node-red. I have 
**installed npm install node-red-node-mysql**.It successfully installed.But I need Mysql node in node red.
If you have any idea about this please help me for how to get Mysql Node in node red.

I want this 
![image](https://cloud.githubusercontent.com/assets/25222593/23366203/f1d7c1fe-fd2b-11e6-9627-f5e92593b177.png)

Thank u
Name : Chaitanya 
mail : chaitu.modela99@gmail.com

**Comment by hardillb** [comment]
As per the contribution guide please use the Google Group (Mailing list) or the Slack channel for general questions, both are linked to from the bottom of the Node-RED website. Issues are for actual defects in Node-RED

**Comment by dceejay** [comment]
If you installed it correctly it should appear in your palette. Depending on how you installed it you may need to stop and restart the server, and refresh the browser page.

**Comment by knolleary** [comment]
As per the comments above, for support questions like this please using the mailing list/slack channel.
