### ISSUE TITLE
HTTP Request node with http_proxy

### ISSUE THREAD

**Issue by etrg** [node-red/node-red#1172]
When I use url = google.com and do a get request, i get error: econnrefused, and I see that _currentUrl is http://www.google.com
When I use url = www.google.com and do the same request, I get status 200 and I see that _currentUrl is http://proxy:port/http://www.google.com as it should be.
I can see the proxy information populated in both cases in the opts. But at request, the url without the www seem to miss the proxy information as shown on the req._currentUrl.

Why am I missing the proxy information on the first request when i don't use the www,
and why can't we make it behave the same? Since I would like to use this node with domain names that doesn't necessarily start with www.

**Comment by hardillb** [comment]
Can you supply a simple test flow to trigger the problem and details of what proxy environment variables you have set.

**Comment by etrg** [comment]
`[{"id":"bd72240e.909e48","type":"http request","z":"24555554.10b64a","name":"","method":"GET","ret":"txt","url":"https://google.com/","tls":"","x":444,"y":3162,"wires":[["71ff5999.6b5f08"]]},{"id":"71ff5999.6b5f08","type":"debug","z":"24555554.10b64a","name":"","active":true,"console":"false","complete":"true","x":622,"y":3158,"wires":[]},{"id":"e8306d9d.c1f5","type":"inject","z":"24555554.10b64a","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":267,"y":3160,"wires":[["bd72240e.909e48"]]}]`

I set the environment variable, http_proxy and no_proxy.
And it shows as it is using it, since the noproxy is undefined vs true and the information is read correctly as : prox http://x.x.x.x:port noprox [ 'localhost', ' 127.0.0.1' ]

I see that req._redirectCount increment as it is redirected to www.google.com; but during this time my options does seem to be lost. If I do the request to www.google.com, there is no redirect and the options are set correctly and it works.

**Comment by hardillb** [comment]
This looks like a bug in the follow-redirect package, I've opened a upstream issue with the https://github.com/olalonde/follow-redirects/issues/53

**Comment by hardillb** [comment]
This has now been fixed in the upstream follow-redirects project (https://github.com/olalonde/follow-redirects/issues/53) and it looks like the fix is now in released version 1.2.2

**Comment by knolleary** [comment]
Thanks @hardillb! Have updated `package.json` for this update. Will be in our next `0.16.x` maintenance release (or `0.17`... whichever comes first).
