### ISSUE TITLE
custom loggers not documented

### ISSUE THREAD

**Issue by guillaume-d** [node-red/node-red#1188]
Since Node-RED 0.10.8 at least (May 2015, when #633 got merged in 0c5c344), custom loggers can be used for Node-RED to log to other places than the console.

Unfortunately this is not documented anywhere I could find. Also settings.js contains a wrong comment:
> // Only console logging is currently supported

Maybe the description in #626 could be linked to or copied from in settings.js?
(BTW the description of `handler` is wrong there: it is a initialization function returning a logging function, not the logging function itself.)

**Comment by knolleary** [comment]
Hi, thanks for the issue. This is something we're aware of and last week started to capture the info needed in a design note on the wiki - https://github.com/node-red/node-red/wiki/Design%3A-Logging-Framework

I know this was something @kazuhitoyokoi was interested in, so he may pick up the task of filling out the content for the docs.

**Comment by kazuhitoyokoi** [comment]
Thank you for the comments. I wrote the following page.
https://github.com/node-red/node-red/wiki/Design%3A-Logging-Framework

**Comment by vkuehn** [comment]
just found this by acciedent and I am confused about the state...it's an open issue but a supported feature ?

**Comment by knolleary** [comment]
@vkuehn its an open issue labeled as `docs` - as our formal documentation on https://nodered.org/docs doesn't mention it at all.

**Comment by vkuehn** [comment]
@knolleary thanks. As a starter on NR there are just to many paths to node-red documentation..thought
@kazuhitoyokoi could you kindly copy your input to https://github.com/node-red/node-red.github.io/blob/master/docs/configuration.md

**Comment by knolleary** [comment]
@vkuehn the wiki page is not intended as user docs - they are technical design notes for the various features we have. They do then feed content into the main docs - which is the next step and why this issue is still open.

This particular topic is too big to add to the configuration page - it will be on its own page.

**Comment by vkuehn** [comment]
ok sorry

**Comment by knolleary** [comment]
Docs updated - http://nodered.org/docs/user-guide/logging
