### ISSUE TITLE
Re-deploying flows when the MQTT node is waiting to reconnect leaves phantom mqtt client running in the background

### ISSUE THREAD

**Issue by tedhuang** [node-red/node-red#1193]
To reproduce:

1. Connect to a MQTT client using the MQTT node
2. Connect to the same client id using some external application (MQTT.fx) or another NR instance
3. When your MQTT node in NR get disconnected, immediately (under the 5s reconnect period) make a change and deploy the flow again in NR.

This leaves an MQTT client that is not cleaned up when Node-RED restarts its the flows on re-deploy. When the new client is created, the reconnect event from the previous client will trigger and compete for the connection with the new one and the old client won't be cleaned up until your restart NR.

The bug is due to "end()" only being called on the mqtt client inside the broker node when:
- client is connected
- client is connecting
and not when the client is waiting to make an automatic reconnect attempt after a close event

Fix is to also check for the boolean "node.client.reconnecting" as a case for calling node.client.end();

> /nodes/core/io/10-mqtt.js - line 301 (#0.16.2)

change:
```} else if (this.connecting) {```

to:

```} else if (this.connecting || node.client.reconnecting) {```

**Comment by dceejay** [comment]
Hi,

would you like to raise a PR for this ? Or as it's only a single line patch I'm happy to apply by hand here if you like. Up to you ?

**Comment by tedhuang** [comment]
Sure, it would be great if you could help. Thanks!
