### ISSUE TITLE
Add description to flow same as subflow

### ISSUE THREAD

**Issue by Kazuki-Nakanishi** [node-red/node-red#1194]
I'd like to add a description to flow same as subflow. There are three ways to implement it.

1) Always show node information and description.
pros: User can always know node type and id.
cons: Tips will never be shown.

2) Show tips if flow description is not specified. Show node information and description if description is specified.
pros: Tips can be shown. The output is similar to subflow.
cons: Even if flow description is not specified, it is more natural to show node information.

3) Show tips if flow description is not specified. Show only description if description is specified.
pros: Tips can be shown. The output is same as clicking subflow node.
cons: User cannot know the flow id same as before.

Although I feel that "3" seems to be more natural, "2" would be also good.
Which one seems to be better?

**Comment by knolleary** [comment]
This is in relation to this whiteboard task: https://trello.com/c/OZEGB7kc

**Comment by knolleary** [comment]
Added to 0.17 branch.
