### ISSUE TITLE
disable debug node - bug or feature?

### ISSUE THREAD

**Issue by jjssoftware** [node-red/node-red#1195]
NodeJS: v6.9.1
Node-RED: v0.16.2

Disabling/deactivating a debug node via the button to the right of the node is an action that persists only for the lifetime of an admin flow page in view in the browser and as soon as the page is refreshed, that debug node reverts to enabled state. 

Is that a bug or is that behaviour by design?

**Comment by dceejay** [comment]
Hi,
please ask general questions on the mailing list or slack channel if you're not sure it's a code issu.
The state of the debug is held in the flow. So on refresh it will revert to the saved state, whether enabled or not. This is as designed,
