### ISSUE TITLE
Using $(ENV_VARIABLE) misbehaves with Email credential fields

### ISSUE THREAD

**Issue by pre** [node-red/node-red#1198]
Node-RED 0.16.2, MacOS Sierra

In Email Node's credential fields the contents of `$(ENVIRONMENT_VARIABLE)` are displayed instead of displaying the name of the variable. 

I have successfully used environment variables with `$(VARIABLE_NAME)` with the Change Node where it works as expected. The problem seems to affect (at least) credential fields.

See the picture for details:
1. The Server address field works as expected and displays $(VARIABLE_NAME)
2. The UserId field misbehaves and displays the content of the environment variable after deploy.

However, the environment variable works. If I change the env variable's content and restart Node-RED, I see changes reflected in the UI. But, if I change the value in the UI, I lose the reference to the environment variable.

This makes it not apparent to the admin that the UserId value is actually read from the environment. If Admin changes the value in the UI, it will be difficult to find out why the Node configuration no longer works as expected.

![node-red-9](https://cloud.githubusercontent.com/assets/63895/24038054/88a5b00c-0b08-11e7-91bd-22adf2adc08e.jpg)

![node-red-7-2](https://cloud.githubusercontent.com/assets/63895/24038493/555f2e10-0b0a-11e7-825f-6014f85a2635.jpg)

**Comment by pre** [comment]
As a side-effect, whenever a new credential is added in any node, the previously configured environment variables are replaced with their values in `flows_cred.json`.

![1 git add -p](https://cloud.githubusercontent.com/assets/63895/24245798/0813cafe-0fcd-11e7-84bf-d81b23b58af5.jpg)

**Comment by nachiket-p** [comment]
Would love to see this fixed. 
My workaround: Don't use credentials, instead use env variables (and config nodes)
