### ISSUE TITLE
Debug node in a subflow prints output as expected but it cannot be disabled

### ISSUE THREAD

**Issue by pre** [node-red/node-red#1204]
Expected: Debug node in a subflow prints output and can be disabled as in normal flows.

Current behaviour: Debug node in a subflow prints output but CANNOT be disabled. Instead it prints "Node actions disabled within subflow".

![node-red](https://cloud.githubusercontent.com/assets/63895/24145332/691b98d0-0e39-11e7-9202-3f11afe01f2b.jpg)

**Comment by knolleary** [comment]
Hi, 

as you can see from the warning, this is explicitly a known limitation of debug nodes - it is not a bug or issue. 

If you think the behaviour should be different, then you're welcome to discuss it on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack) 
Thanks!

**Comment by RickBross** [comment]
Why the hell shouldn't you be able to debug a node from within a subflow?

**Comment by knolleary** [comment]
@RickBross you can use the Debug node from within a subflow. The limitation is you cannot use the button on the Debug node to toggle its enabled/disabled state.

**Comment by RickBross** [comment]
@knolleary Gotcha! Hit me back on email when you get the chance.
