### ISSUE TITLE
Security: CORS not working except for http in (and possibly other) nodes?

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#1208]
Sorry, my knowledge of CORS is still a little shaky. However, I would expect to see CORS headers on a number of resources delivered by Node-RED, for example static resource files. But this does not appear to be the case.

They do appear for resources delivered via the http in node.

Is this by design? Does it negatively impact the security of Node-RED derived UI's?

**Comment by knolleary** [comment]
The cors setting is only applied to the HTTPIn nodes.

It isn't a security issue as the lack of cors headers means requests cannot be made cross origin by default.

It is a separate question as to whether the cors settings ought to be exposed in other resources, but we've had no requirement to do so, so far.

**Comment by TotallyInformation** [comment]
Thanks Nick, perhaps that should be clarified in the documentation for the settings.

I imagine that, at some point, it might be useful to apply it across the board. Both for consistency and so that resources could be handled externally.
