### ISSUE TITLE
Security: No easy way to assure websocket connections?

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#1209]
Hopefully I am wrong on this but presently there seems to be no built-in way to assure websocket connections.

That is to say that, although they will match the protocol of the parent site (e.g. http or https), if you apply an authentication requirement to your Node-RED derived webpages, this cannot apply to any websocket connections used on those pages and so it is possible for an attacker to spoof sending of data if they can get a copy of the page (easy enough if a valid user's machine is compromised).

If this is the case, I believe **it should be considered unsafe to use any Node-RED derived UI using websockets to control Node-RED over the Internet even when using TLS**. As such, an enhancement should be considered to close that loophole.

From RFC6455:

> This protocol doesn't prescribe any particular way that servers can
> authenticate clients during the WebSocket handshake.  The WebSocket
> server can use any client authentication mechanism available to a
> generic HTTP server, such as cookies, HTTP authentication, or TLS
> authentication.

- https://auth0.com/blog/auth-with-socket-io/ - a really clear description of the issue and some ideas for fixing
- https://gist.github.com/subudeepak/9897212 - a look at websockets and some advice on security - most importantly, a recommendation to use `Content-Security-Policy : connect-src 'self'` (NB: doesn't help on IE11)
- https://devcenter.heroku.com/articles/websocket-security - good background and some advice
- http://stratumsecurity.ghost.io/2016/06/13/websockets-auth/ - has some sensible thoughts and some real-life examples of how to secure

Looks like using JWT is the best method to share authentication between the web side and the socket side if you need to secure pure ws:/wss: connections.

However, there are a number of addins for Socket.IO that add security features - perhaps now would be a good time to look at switching.

Apologies if I've got this completely wrong but this seems like a very important issue, especially as Node-RED is increasing in visibility and getting much wider use as it clearly is from the volume of new nodes and traffic in the Google Group.

**Comment by knolleary** [comment]
Hi, let's discuss on the mailing list. It is not an issue with Node-RED core; the websocket connection the editor uses does use a token based system to ensure only authorised clients can connect.

**Comment by TotallyInformation** [comment]
No Problem. I will post there. I didn't want to embarrass myself too much if I'd got it completely wrong!

**Comment by jeroenst** [comment]
> Hi, let's discuss on the mailing list. It is not an issue with Node-RED core; the websocket connection the editor uses does use a token based system to ensure only authorised clients can connect.

Thanks for the info
