### ISSUE TITLE
Shared Subscription with EMQ Cluster and Node-Red MQTT Node not working

### ISSUE THREAD

**Issue by mruepp** [node-red/node-red#1215]
latest docker image emqtt-docker and latest node-red docker image

Two emqttd docker containers in clustered mode and four node-red docker containers.

We want to ingest data from the emq cluster as shared subscription. When we connect to the cluster with multiple mosquitto_sub -t '$queue/topic/#' -h fqdn.emq 
we get queued subscriptions.

When connecting with the node red mqtt node however, no messages are getting processed.

So the MQTT Node of Node Red does not support shared messages?

Best,

Michael

**Comment by knolleary** [comment]
Shared messages are not a standard part of MQTT. They are a broker-specific feature - in this case they are exposed by subscribing to a particular topic.

The MQTT Node in Node-RED is pure MQTT - it will subscribe to the topic you ask it to subscribe to and it will emit the messages it receives; there is no question of it 'supporting' shared messages.

Have you tried using the nodes with a normal topic on your broker to verify the basic connection is working as you'd expect?

**Comment by mruepp** [comment]
How does the mqtt node handle the $queue topic? Does it omit it when parsing it or does it forward it to the broker? I suspect the topic to be wrongly parsed maybe.

**Comment by knolleary** [comment]
I just tested with exactly the topic you've reported and it worked fine.

**Comment by knolleary** [comment]
I'm going to close this as we've had no other reports of this - and the MQTT node does treat any topic differently.
