### ISSUE TITLE
mongo db aggregate not works

### ISSUE THREAD

**Issue by gabbiano83** [node-red/node-red#1217]
on CLI:
 db.users.aggregate([{ $group: { _id : "$customer"}}])
{ "_id" : "customer1" }
{ "_id" : "customer2" }
{ "_id" : "customer3" }

on nodered the payload contain all data like a simple db.users.find() call.

Someone can explain me why?

**Comment by hardillb** [comment]
The Mongo node is part of the [node-red-nodes](https://github.com/node-red/node-red-nodes) project not this one.

Also please ask general usage questions on the mailing list (Google Group) or the Slack team, both of which are linked to from the [node-red](http://nodered.org) homepage.

**Comment by hardillb** [comment]
Also looking at the [docs](https://github.com/node-red/node-red-nodes/tree/master/storage/mongodb) suggest the node only supports .find queries

**Comment by knolleary** [comment]
Closing as the mongo node is not part of this repository.
