### ISSUE TITLE
TCP IN node crashes when receiving invalid data

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red#1222]
Here's the log:

5 Apr 16:05:40 - [red] Uncaught Exception:
5 Apr 16:05:40 - TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:655:11)
    at Socket.<anonymous> (C:\Users\userName\projectPath\node-red\node_modules\node-red\nodes\core\io\31-tcpin.js:448:59)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1074:10)
1 Comment Collapse

**Comment by Hugobox** [comment]
Another slightly different log (this time on Linux, 1st one being on windows):

6 Apr 22:24:21 - [red] Uncaught Exception:
6 Apr 22:24:21 - TypeError: Cannot read property 'msg' of undefined
    at Socket.&lt;anonymous&gt; (/usr/src/node-red/node_modules/node-red/nodes/core/io/31-tcpin.js:464:47)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by dceejay** [comment]
do you have an example of data/a flow that shows this ?

**Comment by Hugobox** [comment]
Unfortunatly I havn't had time to troubleshoot fully as this arises occasionally on startup only on a pretty big flow using a lot of TCP request nodes and mqtt. If the crash log could pinpoint which node triggered the issue that would be helpful. Will try to pinpoint next week.

**Comment by natcl** [comment]
The else if block on line 464 should have an additionnal check:
`if (clients[connection_id])`
Want me to do a PR ?

**Comment by dceejay** [comment]
should it just drop the message ? or should it just create the .msg property (then add the payload) ?

**Comment by natcl** [comment]
I have a feeling it should drop the message but I'll dig a tad more to better understand the impact.

**Comment by Hugobox** [comment]
I've changed all my TCP requests return option from the default (after a fixed timeout of 0ms, which is a suboptimal default) to never - keep connection open. Will report later! Thanks for your time!

**Comment by Hugobox** [comment]
Thanks Natcl, Didn't see the error again since changing to "Keep connection open" which I would suggest to be the default option.

**Comment by Hugobox** [comment]
Hi! Just for keeping track, the crash error:
TypeError: Invalid data, chunk must be a string or buffer, not object
at Socket.write (net.js:655:11)

happenned twice today on synology server despite having all TCP request nodes set to keep connection open.

**Comment by natcl** [comment]
net.js is not a node-red file, any reference to a line number in tcpin in the error ? Is it still line 448 ?Several edge cases were fixed in master since 16.2

**Comment by Hugobox** [comment]
Yes 31-tcpin.js:448:59

**Comment by natcl** [comment]
ok that one should be fixed in master.

**Comment by Hugobox** [comment]
Awesome! Thanks guys!

**Comment by knolleary** [comment]
Closing as this issue has had fixes applied in master. Will be in the next release.
