### ISSUE TITLE
Not able to select flows on the tab bar with touch interface.

### ISSUE THREAD

**Issue by nielsnl68** [node-red/node-red#1223]
Hi as mentioned some time ago in slack. 

I use the node-red editor mainly on my android tablet. Since the option to resort the flow tabs i have a hard time selecting other tabs. 

I hope this can ne fixed.

Ps. One a related issue also adding connection lines between differend nodes can be painful  at time.

**Comment by knolleary** [comment]
This is specifically on touch interfaces right? The title of the issue sounds much broader

**Comment by nielsnl68** [comment]
You are Correct it is the tiuch interface.

**Comment by btsimonh** [comment]
One current workaround - touch, hold, wiggle, drop.  When the tab is being dragged, it drops as selected.

**Comment by ristomatti** [comment]
Double tapping seems to occasionally work also. Might trigger the same event as @btsimonh mentioned.

**Comment by knolleary** [comment]
This was resolved in 1.1.0 (if not earlier).

**Comment by ristomatti** [comment]
Confirmed.
