### ISSUE TITLE
automatic testing sometimes failed due to timing

### ISSUE THREAD

**Issue by Kazuki-Nakanishi** [node-red/node-red#1226]
The current CI environment, which automatically runs a test after sending a pull request, sometimes failed even if the committed code has no error.
I'd like to solve this problem because I also ran into this problem.

At first, I checked build history, and I found several such cases.
https://travis-ci.org/node-red/node-red/builds

* delay node
https://travis-ci.org/node-red/node-red/jobs/210357256
how to fix: Change the delta in approximately function from 50 to about 200.
(Date.now() - t).should.be.approximately(500,50);

* trigger node
https://travis-ci.org/node-red/node-red/jobs/208285345
how to fix: Widen a range.

* tail node
https://travis-ci.org/node-red/node-red/jobs/199751989
https://travis-ci.org/node-red/node-red/jobs/189677875
how to fix: Add a delay just after a flow has been loaded.

* LocalFileSystem
https://travis-ci.org/node-red/node-red/jobs/213023060
how to fix: Add a delay between writing and reading.

Do you have any better idea about how to fix?  Or may I fix the problems following the above idea?

**Comment by knolleary** [comment]
Yes, these tests do occasionally fail and it would be good to stop them doing that.

Please go ahead and make the changes you think we resolve them; just make sure the tests remain valid :)

Thanks!
