### ISSUE TITLE
problem authenticating with twitter

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#123]
In v0.5.0, when I tried to authenticate my account in a twitter input node, it said: 
on the console:
{ statusCode: 401,
  data: 'Failed to validate oauth signature and token' }

and on the web page:
"yeah no. didn't work. "

**Comment by BerndGewehr** [comment]
Hi knolleary, have you only fixed the error message quality or was the auth error fixed, too? I'm using the twitter node in bluemix node-red and it throws a single word as the error message:

Unauthorized

What can i do to overcome the error?

**Comment by DaviGuanabara** [comment]
@BerndGewehr , My problem is exactly the same than yours. ive tried on Google Chrome and Safari, and my os is OS X El Capitan 10.11.6 .
When i click the button "click here to authenticate with twitter", inside twitter output node > Edit twitter-credentials node, on node red, im redirected to this link: 

https://natiar.mybluemix.net/red/twitter-credentials/c21ab585.fa4938/auth?callback=https%3A%2F%2Fnatiar.mybluemix.net%3A%2Fred%2Ftwitter-credentials%2Fc21ab585.fa4938%2Fauth%2Fcallback

that throws a single word: 

> Unauthorized

@knolleary , any solution ?
