### ISSUE TITLE
node.context().global is undefined

### ISSUE THREAD

**Issue by AYapejian** [node-red/node-red#1230]
Node-Red Hash: commit b2390f1cafefb413f4413e069d1de12f900e6b94
Node Version:  v7.8.0

I'm trying to understand at what point, and where is the global context initialized and available.  I have a configuration node, defined with the following slimmed down code.  It's used within another node and works correctly, allowing for shared settings.  However the global context is always undefined.

I've checked both on initialization as well as hooking into an event and checking the property, just trying to make sure that the context isn't being initialized later, sometime after this config node. 

I guess what I'm trying to achieve is a way to create a node that populates the global context with some configuration data at node-red startup.  I've searched issues and found some reference to not having `settings.js` setup correctly in regards to the global property, but mine is set with an empty object.

I also checked out the code for the `node-red-contrib-config` node and I must be missing something as it seems to be doing the same exact thing at a base level. Any hints, tips or tricks would be greatly appreciated

```
module.exports = function(RED) {
    function ConfigServer(config) {
        const node = this;
        RED.nodes.createNode(this, config);
        debugger;
        console.dir(node.context().global);
    }
    RED.nodes.registerType('server', ConfigServer);
}
```

**Comment by knolleary** [comment]
Didn't we discuss this in slack/mailing list recently?

It does appear to be an issue specific to config nodes, rather than regular flow nodes - can confirm that `node.context().global` is unexpectedly undefined for them. Will sort that out.

What's your use case for using global context? It intended to be used by the flow author in their flow - not for nodes to use it for some internal purpose.

**Comment by AYapejian** [comment]
Thanks for the quick reply, and sorry relatively new to then node-red framework from a dev standpoint so I'm not on the mailing list or slack, I'll make sure to check those out.

Indeed, normal flow nodes seem to be fine accessing the global context.  I suppose this would work, but given your question perhaps I'm not thinking in a very 'node-red' way about accomplishing what's needed.  

Basically I have a server somewhere, that server contains a list of states.  I'd like those states surfaced to nodes in a fashion that allows nodes in the flow to use the states to base logic paths on.  Maybe having a 'state' node that takes the object id of what you're after as input then outputs that objects state, then use that as input to another node to use in whatever way is needed.  The global context seemed logical to me, but again, maybe I just need to change my way of thinking a bit.
