### ISSUE TITLE
Logging with node.log("Log") does not log to debug tab in sidepanel

### ISSUE THREAD

**Issue by thomasvnl** [node-red/node-red#1232]
Hi there,

I'm running Node-RED@0.16.2 on NodeJS@6.10.2 and I'm experiencing the following issue: When trying to use node.log() from within a function, I don't get to see it's output in the debug sidebar. I can use node.warn() and node.error() just fine, those show up. Using node.log() does show up in the terminal as an [info] log message, like this (the warn and error are included, message is the same).

```
12 Apr 21:11:43 - [info] [function:Set global ventilation mode] HALLO
12 Apr 21:11:43 - [warn] [function:Set global ventilation mode] HALLO
12 Apr 21:11:43 - [error] [function:Set global ventilation mode] HALLO
```

The function isn't doing that much and the node.log() statement comes before any other logic inside the function.

**Comment by knolleary** [comment]
Correct - log messages go to the console, not the debug tab.

**Comment by thomasvnl** [comment]
Oh, okay. That doesn't feel intuitive to me to be honest, otherwise I wouldn't have bothered creating an issue. Thanks for clearing that up though.

**Comment by dceejay** [comment]
well the thinking is/was that all logging should (naturally) go to the log (by default the console) . The side window is actually the debug panel - but we thought it made sense to put warnings and errors there as they would tend to indicate something was wrong and needed debugging, and we didn;t want to clog it up with normal logging that tends to be more informational.
