### ISSUE TITLE
MQTT IN node not respecting QoS and Retain?

### ISSUE THREAD

**Issue by i8beef** [node-red/node-red#1233]
Noticed this tonight as I was trying to troubleshoot where some retain messages were coming (or not coming) from on a Mosquitto server. I was watching the debug log in node-red expecting the msg.qos and msg.retain to reflect the incoming message sent from another publisher... I see mosquitto respects the retain that I expected to be on the message, but in node-red I don't see that reflected in the debugger. Is this by design (e.g. the retain only has meaning to the broker, so when it publishes it out to subscribers it drops the retain)?

**Comment by i8beef** [comment]
Never mind, appears I was right, the retain comes through correctly on a NEW connection, but if already connected the message is pushed to subscribers without the RETAIN even though Mosquitto DOES retain the message for future connections.

**Comment by dceejay** [comment]
Correct, this is as per the MQTT spec. If you are already subscribed when a message arrives at the broker you will receive it immediately (so the retain flag is not set on your message). If you subscribed after a retained message had been sent to the broker, then you would receive it with the retain flag set.

That way you can tell live and stale data apart.

**Comment by i8beef** [comment]
Yeah, it made sense once I saw it, I just jumped the gun and thought it was a bug. My bad. :-)
