### ISSUE TITLE
Existing flow file is not valid json

### ISSUE THREAD

**Issue by DavePilks** [node-red/node-red#1239]
I have a PowerShell script that updates the values of certain nodes in the `flows.json` file on my build server. All it does is set the server value of a config node. I have used KDiff3 to confirm that there were no changes to the JSON structure and that only values were updated.

However, when I run Node-Red after updating the file, it warns

> Existing flow file is not valid json

I have taken the contents of the `flows.json` file and given it to two JSON validators online, both say it is valid. According to your code, if Node-Red fails to parse the JSON, it throws this error. However, I have also run the contents through two JSON parsers and they do not have an issue with it.

If I take the contents of the file and import it into Node-Red, it is works. But not if I just edit the `flows.json` file. What could be causing this.

**Comment by hardillb** [comment]
Can you supply one of the files that does not load?

**Comment by knolleary** [comment]
Check the encoding of the file: we assume utf8 and some windows apps use a different encoding.

It's all to do with the initial BOM characters in the file, which are dropped if you copy and paste which is why it appears valid.

**Comment by TotallyInformation** [comment]
You might also check line endings? I note that parsers often choke on the Windows default.

**Comment by knolleary** [comment]
@DavePilks any input on the various questions above?

**Comment by DavePilks** [comment]
@knolleary Sorry for the late reply I have been off the grid for a while. After some investigation, it turns out that you were correct regarding the encoding of the file. When I changed to to what you described (regarding the BOM characters) in Notepad++, it worked. 

Out of interest sake, is that documented somehwere? Might be worth adding.

**Comment by knolleary** [comment]
Have added a check for this in `localfilesystem` so it will be handled properly.

Will be in the next release.
