### ISSUE TITLE
settings.nodesExcludes and 0.17's settings.nodesIncludes not documented officially

### ISSUE THREAD

**Issue by guillaume-d** [node-red/node-red#1240]
Since Node-RED 0.7.0 at least (April 2014, 43073de), all Node-RED nodes contained in a given Node.JS module can be disabled simply by adding its filename to the `settings.nodesExcludes` array. Since Node-RED 0.10.8 at least (June 2015, bb1fe8d) the module name can be used instead of the filename.
Also the inverse mechanism using `settings.nodesIncludes` should become available in Node-RED 0.17 thanks to #1184.

Unfortunately this is not documented officially but only in https://github.com/node-red/node-red/wiki/Design:-Node-blacklist-whitelist-function at the moment. Not knowing this we devised a workaround using `settings.nodesDir` and interposing empty .js and .html files to disable Node-RED nodes.

It would be great if the docs could be updated. Maybe in one go for 0.17?

**Comment by knolleary** [comment]
@guillaume-d please raise docs issues here: https://github.com/node-red/node-red.github.io/issues

**Comment by knolleary** [comment]
Just to add - there's lots we don't have documented. Whats even better than an issue highlighting it is a pull-request to fix it.

Also, the #docs channel in our slack team is a good place to discuss missing parts of the docs and to help improve them.

**Comment by guillaume-d** [comment]
OK, I did not know about these other avenues, I will try to use these in the future.
