### ISSUE TITLE
Provide area for in-depth documentation of configuration nodes

### ISSUE THREAD

**Issue by troywweber7** [node-red/node-red#1241]
Just an idea: it seems like it might be useful to provide in-depth documentation for a configuration node just like you can for a regular node.

**Comment by knolleary** [comment]
If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to discuss feature requests/ideas on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack). The issue list is for confirmed issues that need addressing.

Just to be clear - do you mean the node-provided documentation visible in the info sidebar? Config nodes already can - although not all do.



Thanks!

**Comment by dceejay** [comment]
which version of Node-RED are you running ? Since version 0.16 config nodes have been able to provide their own info help that appears in the right hand panel.

**Comment by troywweber7** [comment]
troy@Darryls-Mac-Pro:~/.node-red$ npm list node-red
/Users/troy/.node-red
└─┬ synap-new-architecture@0.1.0 -> /Users/troy/ownCloud/Dev/troy/code/synap-newarchitecture
  └── node-red@0.16.2  extraneous

npm ERR! extraneous: node-red@0.16.2 /Users/troy/.node-red/node_modules/synap-newarchitecture/node_modules/node-red
troy@Darryls-Mac-Pro:~/.node-red$ npm list -g node-red
/Users/troy/.nvm/versions/node/v7.8.0/lib
└── node-red@0.16.2

How do you view that info help? Is it during configuration of the node? Or can you view it by selecting the node in the configuration node tab?

**Comment by dceejay** [comment]
during configuration of the node - though as Nick points out as it is fairly recent not all config nodes may provide very full information. 

for example here is the MQTT broker config info

![image](https://cloud.githubusercontent.com/assets/5375409/25289286/dcba6858-26c0-11e7-9e72-75794ccf2e17.png)

**Comment by troywweber7** [comment]
Ahh, I see, that looks great. Are there features that are in the help guide which are missing, though? I copied and pasted the example from the [help style guide](http://nodered.org/docs/creating-nodes/help-style-guide) but some of the tags/classes don't appear to be doing anything.

![screen shot 2017-04-21 at 10 34 16 am](https://cloud.githubusercontent.com/assets/4765979/25289725/b4283136-267f-11e7-97bf-972e6d56bcbc.png)

**Comment by knolleary** [comment]
The necessary CSS is being added in 0.17... we have only just (last week) published the style guide in anticipation.

**Comment by troywweber7** [comment]
Okay, thanks for all the help and info! It looks great, you guys!
