### ISSUE TITLE
Switch node default property for JSONata

### ISSUE THREAD

**Issue by andreas-ibm** [node-red/node-red#1244]
I had a look at the code and didn't see how to do this easily without breaking something.

The switch node's default `PropertyType` is `msg`, which works well with it's default `Property` set to `payload`.  but when you switch to `PropertyType` `JSONata` the default `Property` of `payload` won't work as it needs to be `msg.payload`.

Having less experience in editing frontends I don't want to start hacking away at it (I was hoping there would be a different default value per `PropertyType`!)

**Comment by knolleary** [comment]
In the next release we're deprecating the need to use `msg` in JSONata expressions. That will, in part, resolve this.

More generally, the hard part with a default value is knowing when its safe to change the entered value - you don't want to replace something the user has purposefully entered.
