### ISSUE TITLE
Lost connection when connecting to 5th Server using Modbus Getter

### ISSUE THREAD

**Issue by Kartheek1512** [node-red/node-red#1250]
I am trying to pull data from 3 different devices located at different server address and ports.  I am using three Modbus getter nodes to pull data from 3 different servers. When i run them individually, I am getting data. But when I have all three in one flow and deploy it, it is giving "Lost connection to server" error. Once I get this error, even if I remove the third modbus getter node, the remaining two does not work. I have to remove the .json file and start from scratch. Can anyone help me!!

**Comment by Kartheek1512** [comment]
When I deploy it with 3 Modbus getters with 3 servers, the status of the Modbus getters will switch between "waiting' and "active"

**Comment by Hugobox** [comment]
Which Modbus Node are you using and which version? I run a similar setup but no problem so far. This issue should be opened on the modbus node's github as its a 3rd party node and not part of Node-Red.

**Comment by dceejay** [comment]
Closing here, as this should be raised against the modbus node's project, or asked more generally on the mailing list.

**Comment by Kartheek1512** [comment]
Hi, I am using node-red version v0.16.2 . I am using "Modbus getter". I got it by following
npm install node-red-contrib-modbus command. Do you recommend any other node that i have to use?

![image](https://cloud.githubusercontent.com/assets/9099868/25838981/876e0930-344a-11e7-80da-ca355c2877ab.png)

**Comment by Hugobox** [comment]
I see! I'm using Modbus Read (not Getter) as I'm suing less than 10 nodes  per server as the doc suggests. You can still read multiple devices per Modbud Read node. Hopefully this is applicable to your setup.

**Comment by Kartheek1512** [comment]
I am using Getter because, I can trigger it at specific intervals. Modbus
read will continuously keep getting data which I dont want. I was able to
do more than 10 nodes per server successfully but not able to do more than
3 servers. (4 nodes per server). Breaking my head!!
