### ISSUE TITLE
suggestion: customize "component" through GUI options

### ISSUE THREAD

**Issue by imnvr** [node-red/node-red#1251]
NODE-RED is amazing for wiring things together but wouldn't it be better if you could also create new "components" without writing code in the traditional sense of the activity but instead do it through GUI options ? Thanks.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle feature suggestions on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack)  

The issue list is primarily for development issues that need addressing.

Thanks!
