### ISSUE TITLE
MQTT publish breaks deploy

### ISSUE THREAD

**Issue by btsimonh** [node-red/node-red#1254]
The simple flow below causes node-red 0.17 (10th may 2017) (and possibly 0.15.2) to not deploy correctly in the following circumstances.
(change the MQTT server before trying...).

delete flows.json
start node-red.
import the flow. deploy.
move a node, and deploy again, all is normal.

click on inject - it posts one message to MQTT.  Observe the message received elsewhere (i.e. MQTT is working).
Now move a node and deploy.
The Deploy symbol in the editor remains grey.
The console log ends with 'Stopping flows'.
NR is now non-operational.
A little while later (on a timer?), the browser shows the 'The server is running a more recent set of flows.' dialogue.
Clicking 'Ignore and deploy' logs a save flow revision message (no stop/start), as do subsequent deploys.

Flow:

[
    {
        "id": "ea1a5a8f.4702c8",
        "type": "mqtt out",
        "z": "d0ad3fa.5a528c",
        "name": "",
        "topic": "",
        "qos": "2",
        "retain": "true",
        "broker": "8a277dc1.98453",
        "x": 386.89588928222656,
        "y": 62.54519081115723,
        "wires": []
    },
    {
        "id": "c5accdf9.0328a",
        "type": "inject",
        "z": "d0ad3fa.5a528c",
        "name": "",
        "topic": "test",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 132.83684539794922,
        "y": 75.52777826786041,
        "wires": [
            [
                "ea1a5a8f.4702c8"
            ]
        ]
    },
    {
        "id": "8a277dc1.98453",
        "type": "mqtt-broker",
        "z": "",
        "broker": "nebula.yella.tv",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "compatmode": true,
        "keepalive": "60",
        "cleansession": true,
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": ""
    }
]

console log:
Welcome to Node-RED
===================

11 May 20:17:43 - [info] Node-RED version: v0.16.2
11 May 20:17:43 - [info] Node.js  version: v6.9.1
11 May 20:17:43 - [info] Windows_NT 10.0.14393 x64 LE
11 May 20:17:44 - [info] Loading palette nodes
11 May 20:17:46 - [warn] ------------------------------------------------------
11 May 20:17:46 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
11 May 20:17:46 - [warn] [tail] Not currently supported on Windows.
11 May 20:17:46 - [warn] ------------------------------------------------------
11 May 20:17:46 - [info] Settings file  : C:\Data\dev\yella\build\yellarednew\local\settings.js
11 May 20:17:46 - [info] User directory : C:\Data\dev\yella\build\yellarednew\local/
11 May 20:17:46 - [info] Flows file     : C:\Data\dev\yella\build\yellarednew\local/flows.json
11 May 20:17:46 - [info] Creating new flow file
11 May 20:17:46 - [info] Server now running at http://127.0.0.1:1880/
11 May 20:17:46 - [debug] loaded flow revision: ffcb4091ed15571c04bac6e987615199
11 May 20:17:46 - [debug] red/runtime/nodes/credentials.load : no user key present
11 May 20:17:46 - [debug] red/runtime/nodes/credentials.load : using default key
11 May 20:17:46 - [info] Starting flows
11 May 20:17:46 - [debug] red/nodes/flows.start : starting flow : global
11 May 20:17:46 - [info] Started flows
baloon showed
baloon timed out
11 May 20:18:12 - [debug] saved flow revision: d1c44e70c7a7811d84882bf19b2cbdf1
11 May 20:18:12 - [info] Stopping flows
11 May 20:18:12 - [info] Stopped flows
11 May 20:18:12 - [info] Starting flows
11 May 20:18:12 - [debug] red/nodes/flows.start : starting flow : global
11 May 20:18:12 - [debug] red/nodes/flows.start : starting flow : 180db849.c24678
create config node mqtt-broker
create node mqtt out
create node inject
11 May 20:18:12 - [info] Started flows
11 May 20:18:12 - [info] [mqtt-broker:7865b28b.61fe8c] Connected to broker: mqtt://nebula.yella.tv:1883
11 May 20:18:16 - [debug] saved flow revision: 6c50a72fac9bafe891db032f2752f79b
11 May 20:18:16 - [info] Stopping flows
11 May 20:18:16 - [info] [mqtt-broker:7865b28b.61fe8c] Disconnected from broker: mqtt://nebula.yella.tv:1883
11 May 20:18:16 - [info] Stopped flows
11 May 20:18:16 - [info] Starting flows
11 May 20:18:16 - [debug] red/nodes/flows.start : starting flow : global
11 May 20:18:16 - [debug] red/nodes/flows.start : starting flow : 180db849.c24678
create config node mqtt-broker
create node mqtt out
create node inject
11 May 20:18:16 - [info] Started flows
11 May 20:18:16 - [info] [mqtt-broker:7865b28b.61fe8c] Connected to broker: mqtt://nebula.yella.tv:1883
11 May 20:18:18 - [debug] saved flow revision: 90b3a0a991f6bfd5c82661bea02c78fb
11 May 20:18:18 - [info] Stopping flows
11 May 20:18:18 - [info] [mqtt-broker:7865b28b.61fe8c] Disconnected from broker: mqtt://nebula.yella.tv:1883
11 May 20:18:18 - [info] Stopped flows
11 May 20:18:18 - [info] Starting flows
11 May 20:18:18 - [debug] red/nodes/flows.start : starting flow : global
11 May 20:18:18 - [debug] red/nodes/flows.start : starting flow : 180db849.c24678
create config node mqtt-broker
create node mqtt out
create node inject
11 May 20:18:18 - [info] Started flows
11 May 20:18:18 - [info] [mqtt-broker:7865b28b.61fe8c] Connected to broker: mqtt://nebula.yella.tv:1883
11 May 20:18:30 - [debug] saved flow revision: 3eef10ded34201f007451449c77aee7d
11 May 20:18:30 - [info] Stopping flows

**Comment by dceejay** [comment]
That flow is only one node...

**Comment by btsimonh** [comment]
sorry, editted it after posting.
But more info:
It's QOS=2 which kills NR.  works for QOS 0/1.

**Comment by dceejay** [comment]
working good for me against my local broker. Who's broker is it ? What Broker software are they running ?

**Comment by btsimonh** [comment]
it's a local mosca on a VM.

**Comment by dceejay** [comment]
Mosca doesn't support QoS 2

https://github.com/mcollina/mosca

**Comment by btsimonh** [comment]
is it worth looking into why it kills NR?  I assume that mqtt.js is holding up the close; but there should be a way to terminate with prejudice so it does not stall the whole node stopping process....
Mosca logs show nothing unusual in this circumstance :(.

**Comment by btsimonh** [comment]
mqtt.js -> 2.7.1 does *not* solve the issue :(

**Comment by dceejay** [comment]
Well there an option on end() to kill the connection immediately but that could potentially then break other things. It may be the case that as we are closing we don't care but....   it would need thinking about before just applying.

**Comment by knolleary** [comment]
I'd like to see if there's a fix needed upstream and get it raised against mqtt.js before we do anything to work around it.... unless of course it is a fault with our use of mqtt.js.

**Comment by dceejay** [comment]
well - the broker doesn't support QoS2 so any message sent won't get an ack... the end() call will only callback if it gets an ack - so the end will hang...  (is my thinking).  .end(true);  will close the connection without waiting for any acks for inflight messages... which may also be a bad thing... unless it's acceptable, as we have sent them, just not seen the ack.

**Comment by btsimonh** [comment]
testing now. 
This bit:
this.client.once('close', function() {
      done();
});
never calls done().  Maybe the 'once' implementation is broken; or just maybe something already called it (so it would not execute)!  In theory there are tests for it in mqtt.js.
You would have thought since mcollina is behind both mqtt.js and mosca, it would not have an issue....
When I remove this call, and put the done() after our end(), it works fine; but as dave says, it may break other things like leave garbage lying about...

**Comment by dceejay** [comment]
as per above .. try changing the .end();  lines 300 and 302   to .end(true);

**Comment by btsimonh** [comment]
this is the code I ran; 

        this.on('close', function(done) {
            this.closing = true;
            if (this.connected) {
                console.log("mqtt close once(close)");
                //this.client.once('close', function() {
                //    console.log("mqtt close once(close) finished");
                //    done();
                //});
                console.log("mqtt close calling client end");
                this.client.end();
                console.log("mqtt close calling client end returned");
                done();
            } else if (this.connecting || node.client.reconnecting) {
                console.log("mqtt close calling client end (2)");
                node.client.end();
                console.log("mqtt close calling client end returned (2)");
                done();
            } else {
                done();
            }
        });

produces log:
11 May 21:15:32 - [info] Stopping flows
mqtt close once(close)
mqtt close calling client end
mqtt close calling client end returned
11 May 21:15:32 - [info] Stopped flows

so end() does not stall; just once() does not run the function passed.
before commenting out, I did not see 'mqtt close once(close) finished'

**Comment by btsimonh** [comment]
this smacks of a wider issue; if a node has been asked to stop, and done() is not invoked for a period of time, is there something general which can be done by NR to at least partially recover the situation so that NR still works.

**Comment by knolleary** [comment]
It's hard to recover when we don't know the state. What we do need is better logging to help identify what has hung. That's a separate concern to this issue.

**Comment by btsimonh** [comment]
submitted a test js file and created an issue at mqtt.js:
https://github.com/mqttjs/MQTT.js/issues/611

**Comment by btsimonh** [comment]
I'm going to leave this for now, as I was using QOS 2 in error anyway.

**Comment by btsimonh** [comment]
Note: Mosca has had some patches which allows (optionally) a QoS 2 message to get a puback (which makes mqtt.js happy), and Nick has kindly added a timeout on nodes closing in NR (0.17 branch), so this issue should now be covered.
