### ISSUE TITLE
node.send with string parameter crashes Node-RED

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#1255]
I think that it should return an error that can be handled by flows.

```
13 May 18:00:04 - [red] Uncaught Exception:
13 May 18:00:04 - TypeError: Cannot create property '_msgid' on string 'xxxxxxxxx'
    at sendResults (C:\Users\user\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\nodes\core\core\80-function.js:40:40)
    at Object.send (C:\Users\user\AppData\Roaming\nvm\v6.9.1\node_modules\node-red\nodes\core\core\80-function.js:90:21)
    at Object.send (evalmachine.<anonymous>:1:210)
    at evalmachine.<anonymous>:5:10
    at Socket.socket.on (C:\Users\user\.node-red\myGlobals.js:24:13)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:10)
```

I know it is a daft error to make but it is all too easy to forget what you are passing, especially for beginners and it would be very helpful if it didn't kill the node-red server.

**Comment by knolleary** [comment]
It's a fatal error only because your code in myGlobals.js hasn't registered an error handler on the socket it's created.

You'll want to address that for yourself as there could be other unexpected errors you aren't handling.

We will add a better error message when we detect node.send being called with a non-object type.

**Comment by TotallyInformation** [comment]
Thanks. It is because the call is actually done from a callback function so I guess the nested functions doesn't let Node.JS handle the error gracefully.

The final code, with the right output of course, is now here:
http://flows.nodered.org/flow/09e0f1a6b4446c214b1cb5c22f7c8d08

**Comment by knolleary** [comment]
Change pushed to 0.17 branch - https://github.com/node-red/node-red/commit/8a7bb1be9f07dbec64830d9e570fd663263ad6c2

We will now log an error and drop the message.

**Comment by knolleary** [comment]
Closing as this will be in the next release
