### ISSUE TITLE
file-node : error message for files in ~/.node-red/

### ISSUE THREAD

**Issue by Urs-Eppenberger** [node-red/node-red#1258]
I have placed a file in the directory ~/.node-red/ to be read with the file node.
It works.
But in the GUI, below the file node, in gray, there is an error message:
key 'node-red:.node-red/switch1.json (en-US)' returned an object instead of string.

The content of the file is a JSON formatted string. Out of curiosity I changed that, still the same error message.
Then I placed the file into another directory: ~/device-configs/
Now the message below the file-node reads:
device-configs/switch1.json

The error message only appears for files in the ~/.node-red/ directory.

Since everything works fine, this is not a big issue.
But I still would like to understand if there is a reason behind the different behavior, so I can place the files according to the intention of the inventors of node-red.

Kind regards,
Urs.

**Comment by knolleary** [comment]
Fixed in 0.17 branch

**Comment by Urs-Eppenberger** [comment]
Thanks for the support.
Is there a way to send you a beer or something?
