### ISSUE TITLE
Problem while Installing Node-red

### ISSUE THREAD

**Issue by Nikitha-Kondapalli** [node-red/node-red#1260]
I am having a problem while installing while executing this command " npm run build" how to solve this attached is the screenshot of the error occurred while executing the above command.
![screenshot from 2017-05-19 12-29-31](https://cloud.githubusercontent.com/assets/20740359/26236612/debf64a8-3c8e-11e7-977e-c597990b5b4a.png)

**Comment by knolleary** [comment]
How did you install node-red?

**Comment by knolleary** [comment]
What I meant to ask was, what steps have you taken before this point?

The fact you're trying to run the build suggests you've clone the code from git rather than install from npm. Is that right?

**Comment by Nikitha-Kondapalli** [comment]
Yes I have cloned it from git and then tried installing and building npm

**Comment by knolleary** [comment]
So you:

1. `git clone`
2. `npm install`
3. `npm run build`

The `npm install` should have got grunt installed for you.

**Comment by sudhirbitsgoa** [comment]
do 
```
npm i -g grunt 
```
and run 
```
npm run build.
```

**Comment by dceejay** [comment]
is this now fixed ? ok to close ?

**Comment by knolleary** [comment]
Closing this issue as there has been no further updates. If you're still having problems, please contact the mailing list of slack team - links on nodered.org
