### ISSUE TITLE
Embending node-red but "can't establish a connection to the server at ws://localhost:3000/red/comms.

### ISSUE THREAD

**Issue by ethyde** [node-red/node-red#1268]
Hi,

I try to install node-red as simple embed app with express 4. With simple/basic intégration node-red work normaly, but when i run the embed code I allways have the folowing error `can't establish a connection to the server at ws://localhost:3000/red/comms.` and after some minutes i have the alert message "Lost connection to server, reconnecting in ..."

Repo : https://github.com/ethyde/heroku_node-red

Local config : 
```
26 May 10:12:02 - [info] Node-RED version: v0.16.2 
26 May 10:12:02 - [info] Node.js  version: v6.10.3
```

Thanks.

**Comment by knolleary** [comment]
Hi,

what have you done to try to debug this? I'm not going to dig through your repository to find the relevant bits of your code - please link to where you are actually embedding Node-RED.

**Comment by ethyde** [comment]
Right now, I'm starting to install and use it by following the [doc](http://nodered.org/docs/embedding).

Code for embeding with ExpressJS are [here](https://github.com/ethyde/heroku_node-red/blob/master/app/app.js) and it use this [settings](https://github.com/ethyde/heroku_node-red/blob/master/app/node-red.settings.js) files.
NPM Script : `"dev:server": "cross-env NODE_ENV=development nodemon boot.js",`

Normal (non-embed) settings file are [here](https://github.com/ethyde/heroku_node-red/blob/master/app/node-red.settings.es5.js) it's the same as previous but with module.export instead of ES2015 syntax.
NPM Script : `"node-red": "./node_modules/.bin/node-red --settings ./app/node-red.settings.es5.js"`

Server listening are [here](https://github.com/ethyde/heroku_node-red/blob/master/server.js)

I have read about some issue with param `userDir: '/home/nol/.node-red/', but it is well commented, so what can i do ?

**Comment by knolleary** [comment]
The problem is here: https://github.com/ethyde/heroku_node-red/blob/master/app/app.js#L21

The first argument you pass to `RED.init` must be an HTTP Server instance, not an Express app instance.

**Comment by ethyde** [comment]
Hi thanks for your answer !

I have made the correction, but issue still existe : https://github.com/ethyde/heroku_node-red/blob/master/app/app.js#L24

**Comment by knolleary** [comment]
You pass a `server` to `RED.init`, but then you call `app.listen` which causes express to create its own `server` instance and not use the one you provided.

You should call `server.listen` on the instance of `server` you pass `RED.init`.

**Comment by ethyde** [comment]
Ok, it's not a real embending : node-red use it's own server instance ? And even embed, to interact with it, it's like requesting an any other external API ?

**Comment by knolleary** [comment]
It does not use its own server instance. You provide the server instance.

We haven't formally documented the runtime api yet, but what is available is listed here: http://nodered.org/docs/api/runtime/api Any questions, please use the node-red mailing list etc.

So I assume your immediate issue is resolved?

**Comment by ethyde** [comment]
My first configuration is similar/same to the one I can have in production, and node-red can not use it.
So ATM, I can not use node-red in embed, because it can not use an existing server instance, so node-red can't be embed in another app. I have to use node-red with embed code as a Core of an app, it's not the same things.

But I think yes, immediate issue is solved.

**Comment by RaiBnod** [comment]
In my case, it goes on pending state:
![image](https://user-images.githubusercontent.com/6800775/58085959-74424600-7bdd-11e9-997d-34253f399bc6.png)

![image](https://user-images.githubusercontent.com/6800775/58086028-8b813380-7bdd-11e9-900d-14875790d076.png)

Is there any extra thing to do?
