### ISSUE TITLE
Missing CSS classes for node help style

### ISSUE THREAD

**Issue by tovafi** [node-red/node-red#1269]
In Node-Red documentation, there is a new guide for node help style. 
That guide refers to some CSS classes as the right way to define the node help style. 
Those CSS classes don't exist in node-red repository. 
To be specific, I mean to the node-help.scss file, which exists in node-red.github.io repository (the repository for Node-Red site, where the guide is) but doesn't exist in node-red repository, so it's possible to follow the guide's instruction for the right node-help style.

rbe node is an example for a node that its help is written according to "Node help style guide" and uses those CSS classes. (but its final style,  of course, is not as expected, due to missing of those classes)

**Comment by dceejay** [comment]
For once the docs are ahead of the released code... they are in the 0.17 branch here
https://github.com/node-red/node-red/blob/0.17/editor/sass/tab-info.scss#L105

**Comment by tovafi** [comment]
So, it's only matter of time for being in the master. 
Well, Thanks for your quick response.

**Comment by dceejay** [comment]
yes - hopefully sooner rather than later.
