### ISSUE TITLE
custom user authentication - Cannot find module when

### ISSUE THREAD

**Issue by roccomuso** [node-red/node-red#1272]
I'm following the [security](https://nodered.org/docs/security) guide to build a custom user authentication with some external REST.

> Rather than hardcode users into the settings file, it is also possible to plug in custom code to authenticate users. This makes it possible to integrate with existing authentication schemes.

I put the `user-authentication.js` file inside `/data` with the `settings.js` and then edit the line:

    adminAuth: require("./user-authentication"),

Node-red is executed inside a container with the command:

    $ npm start -- --userDir /data

This the error I'm having:

```
nodered_1    | Error loading settings file: /data/settings.js
nodered_1    | Error: Cannot find module 'when'
nodered_1    | npm info lifecycle node-red-docker@0.16.2~poststart: node-red-docker@0.16.2
```

There's something wrong with the PATH possibly?

**Comment by knolleary** [comment]
That example assumes you know enough node.js to know that you'd need to run `npm install when` in the directory you have the `user-authentication.js` file.

This is a docs issue to make that clearer.

**Comment by roccomuso** [comment]
@knolleary yeah at end I've replaced `when` with the built-in `Promise` (node >= v4). Even though deploying it from a container and have to do a `npm install when` it's a bit unhandy.

**Comment by knolleary** [comment]
Finally updated the docs to replace `when` with built-in Promises. https://github.com/node-red/node-red.github.io/commit/baa3b501e3770d3dfb88ba2b0735d104b4304df4
