### ISSUE TITLE
Reload flows gives status 204 when api version is v2

### ISSUE THREAD

**Issue by dheerajjoshim** [node-red/node-red#1273]
As per document if api version is v1 then reload of flows will give status code 204. And if v2 is used then reload flows will give status 200 with new revision information.
However when api verison v2 is used reload flows still gives status 204. Ideally it  should have given the new revision number

Request is

```
curl -X POST \
  http://NODEREDIP:PORT/flows \
  -H 'authorization: Bearer ***********Secret*******' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'node-red-api-version: v2' \
  -H 'node-red-deployment-type: reload'
```

Response is

Status code 204

**Comment by knolleary** [comment]
Fixed in 0.17 branch
