### ISSUE TITLE
How to have timestamp as part of the filename?

### ISSUE THREAD

**Issue by Kartheek1512** [node-red/node-red#1277]
Hi,

 I am using file node to create a file where I have to type the file name.   I would like to automate the file creation process. Every 10 mins, i want to create a file with the sensor data and the file name has to be "sensor-data-mm-dd-yy-hh-mm-ss.csv"

Can anyone please help. 

![image](https://user-images.githubusercontent.com/9099868/26979650-68f1b990-4ce4-11e7-97ab-a6954e9c697f.png)

**Comment by dceejay** [comment]
For general how-to type questions please use either the mailing list or slack channel as per the contribution guidelines.

A quick look at the info panel for the node would show you this
![image](https://user-images.githubusercontent.com/5375409/26979908-6c17cdbe-4d28-11e7-9b67-cc85b7a8d402.png)

so in a previous (function) node add 'msg.filename = "some filename of your choosing";`
