### ISSUE TITLE
httpin respects apiMaxLength?

### ISSUE THREAD

**Issue by vicary** [node-red/node-red#1278]
According to [this link](https://developer.ibm.com/answers/questions/257954/bluemix-node-red-error-request-entity-too-large.html) and [this link](https://groups.google.com/forum/#!topic/node-red/6b4jaTcVKbE), I assume that `http in` nodes will respect configuration parameter `apiMaxLength`.

By looking at ~[21-httpin.js:23](https://github.com/node-red/node-red/blob/master/nodes/core/io/21-httpin.js#L23)~ [21-httpin.js:24](https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/nodes/core/io/21-httpin.js#L24) there are no `limit` parameters passing in, should it be there?

**Comment by knolleary** [comment]
Hi - sorry for the slow response.

Despite what I had said in those threads, `apiMaxLength` is specifically for admin API. We will need to introduce a new setting for the http nodes.

**Comment by vicary** [comment]
Not sure if you guys had an idea about the name yet; but following `httpRequestTimeout`, `httpRequestLimit` may be a good start.

**Comment by jonathanrcarter** [comment]
is there any way to hack the node red code to increase the limit??

**Comment by knolleary** [comment]
@jonathanrcarter you can edit `21-httpin.js` here https://github.com/node-red/node-red/blob/3b12076d4bc8f42c3f824ef0be466649f1b4de39/nodes/core/io/21-httpin.js#L24 to be:

    var jsonParser = bodyParser.json({limit: '5mb'});

**Comment by vicary** [comment]
Is there other considerations preventing this change? If not I can make a PR.

**Comment by knolleary** [comment]
I don't think there's much in the way here... just need to agree the name of the property this will introduce. To be consistent with other properties, I would suggest `httpNodeMaxLength`. A PR would be most welcome.

**Comment by vicary** [comment]
Took a few looks of the inner workings and found that incoming body is already parsed in [red/api/index.js:103](https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/red/api/index.js#L103) before [21-http.js:24](https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/nodes/core/io/21-httpin.js#L24) can touch it.

Which means the `jsonParser` in 21-httpin.js has never done anything from the very beginning.

We have a few approaches here:
1. `apiMaxLength` takes precedence as `settings.apiMaxLength || settings.httpNodeMaxLength || '5mb'`;
2. Use the `bytes` library and `Math.min()` to pick the smallest one.
3. Delete `req.body` and `req._body` in every requests received by 21-http.js to force a re-parse.

Although 3. Make the most sense to me, it does have a performance hit and the error falls into the flow context and if people doesn't use a catch node the client will see `500 Internal server error` instead.

This really affects the inner workings, I could use your advise here.

**Comment by knolleary** [comment]
There are two separate express apps here.

`adminApp` is the express app that handles the admin api and is controlled by `apiMaxLength`.

The HTTP Nodes attach to a different express app here: https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/red/runtime/index.js#L62

So the jsonParser in 21-httpin.js should be being used and separately configured to the `adminApp` one.

**Comment by vicary** [comment]
I placed a logging middleware at these two lines.
https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/red/api/index.js#L104
https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/nodes/core/io/21-httpin.js#L248

According to the logs the request passes through `red/api/index.js`, then carries the parsed JSON in `req.body` and then arrives `21-httpin.js` where it ignores the parsing because of [lib/types/json:98](https://github.com/expressjs/body-parser/blob/0632e2f378d53579b6b2e4402258f4406e62ac6f/lib/types/json.js#L98).

---

Diving in and out I arrived at these two lines,
https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/red.js#L244
https://github.com/node-red/node-red/blob/c9317659c5049f1929c4fe60bafe3c7dffa97b02/red.js#L250

I suspect with the same express app connecting two separate apps, namely `httpAdmin/adminApp` and `httpNode/nodeApp`, they in fact shares the same request object.

**Comment by knolleary** [comment]
Coming back to this, given your last comment, and further testing, `apiMaxLength` _does_ apply to the http nodes.

So I'm not sure there's anything to address here.

**Comment by vicary** [comment]
When `httpNodeRoot` and `httpAdminRoot` is the same, in the default mode (not embedded) `httpNodeMaxLength` will be inherently dependent on `apiMaxLength` because express has no way to distinguish between them as of yet.

`RED.httpAdmin` will always parse the body before `RED.httpNode` has a chance to do so.

# Possible Scenarios

## `apiMaxLength >= httpNodeMaxLength`
- We are wasting a few milliseconds to "reparse" the body with `httpNodeMaxLength`.
- If body exceed the limit, http nodes will respond with 500 instead of 412 unless users put a catch node and manually craft a 412 response.

## `apiMaxLength < httpNodeMaxLength`
- It just won't arrive the http nodes at all because `apiMaxLength` in `RED.httpAdmin` already respond with 412.

**Comment by vicary** [comment]
Fair enough, happy to see this resolved. Thanks!
