### ISSUE TITLE
File Writer node does not honor the message order when appending.

### ISSUE THREAD

**Issue by btsimonh** [node-red/node-red#1280]
the flow below illustrates this.
The presented array of numbers 1-10 from inject, split and written as separate payloads appended to a file, does not result in a file with the numbers ordered 1-10.

[{"id":"612f9b83.603904","type":"inject","z":"17707dcb.af0322","name":"","topic":"","payload":"[1,2,3,4,5,6,7,8,9,10]","payloadType":"json","repeat":"","crontab":"","once":false,"x":171.390625,"y":265.08203125,"wires":[["1acbe6d6.164359"]]},{"id":"1acbe6d6.164359","type":"function","z":"17707dcb.af0322","name":"","func":"\nfor (var i = 0; i < msg.payload.length; i++)\n{\n    var newmsg = {payload:msg.payload[i]};\n    node.send(newmsg);\n}\n\n","outputs":1,"noerr":0,"x":375.375,"y":263.28515625,"wires":[["3853c276.02dafe"]]},{"id":"3853c276.02dafe","type":"file","z":"17707dcb.af0322","name":"","filename":"c:\\temp\\test.txt","appendNewline":true,"createDir":false,"overwriteFile":"false","x":596.3828430175781,"y":263.3594026565552,"wires":[]}]

**Comment by dceejay** [comment]
fix in commit b91c1782002e198c663bc47242af31263e211b20
(works with above flow and other like it... )
