### ISSUE TITLE
In the Windows environment, Node-RED creates a user folder on the drive other than system drive

### ISSUE THREAD

**Issue by Kazuki-Nakanishi** [node-red/node-red#1281]
Problem:
As the system drive of my PC is C drive, my home path is "C:\Users\\{username}".
I ran Node-RED on D drive.
Then Node-RED created a folder in "D:\Users\\{username}\\.node-red", not in the home path.

---
The root cause of this problem is the following code in localfilesystem.js.

settings.userDir = fspath.join(process.env.HOME || process.env.HOMEPATH ||
                               process.env.USERPROFILE || process.env.NODE_RED_HOME,".node-red");

I checked the actual value of the above environment variables on each platform.
The result was as follows.

_ | HOME | HOMEPATH | USERPROFILE | NODE_RED_HOME
------------ | ------------- | ------------- | ------------- | ------------- 
Windows10| undefined | \Users\\{username} | C:\Users\\{username} | D:\work\\node-red
Linux(Ubuntu) | /home/{username} | undefined | undefined | /home/{username}/work/node-red
macOS(Sierra) | /Users/{username} | undefined | undefined | /Users/{username}/work/node-red

According to the table, it seems to work fine if I change the order of HOMEPATH and USERPROFILE.  But I come up with two things.

\# 1. I'm not sure this change works fine in all environments not only the above environments.
\# 2. If the Node-RED users who correspond with the above problem upgrades to the latest version, their flows will disappear on the editor because the settings.userDir will change.

One of the way to solve \# 2 is to check process.env.HOMEPATH first, and if it does not exist, creates a folder in process.env.USERPROFILE.  But it seems not a perfect solution.
Is there any similar situation before?

**Comment by knolleary** [comment]
Fixed by #1317
