### ISSUE TITLE
Exec node doesn't handle whitespaces in argument path when using spawn() + possible solution

### ISSUE THREAD

**Issue by fgrhlt** [node-red/node-red#1286]
The exec node can't handle lines like: 

```java -cp "folder name with space" MyClass```

where there are spaces in the arguments. 

A similar problem was issued before https://github.com/node-red/node-red/issues/1100, where [dceejay](https://github.com/dceejay) made a solution where you could have spaces in the command part of the line, e.g

```"Some path/myexec" -l whatever"```  

by adding a line to the exec node: 

```if (/^"."$/.test(cmd)) { cmd = cmd.slice(1,-1); }```

But this only looks at the command part of the line you want to execute, and not the array of arguments. The line that was added is needed since the [spawn()](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) method provided by Node can't handle quotes in either the command or the argument array. 

I wrote a possible solution for this in a [pull request](https://github.com/node-red/node-red/pull/1285)

**Comment by dceejay** [comment]
Closed by that PR  #1285
