### ISSUE TITLE
ipv6 mqtt broker address

### ISSUE THREAD

**Issue by grimace** [node-red/node-red#1289]
I'm trying to connect to an MQTT broker with an IPV6 address.  When I setup the broker, it says 'connecting' but when I hit deploy it just says 'disconnected'.  No logging available.  Is there a way to do this?

**Comment by hardillb** [comment]
How are you specifying the address, what format?

**Comment by grimace** [comment]
There actually is a log, I was running on docker and so took me a while to find it: 

I've tried with and without square brackets []

the log is: Connection failed to broker: fourteen@mqtt://[fe80::16da:e9ff:fe08:8dae]:1883

**Comment by hardillb** [comment]
It's working for me with the square brackets (and a fully routed address 2001:8b0:2c1.....) but not with a link local address.

Are you sure your broker is listening on the link local address?

Also make sure you can ping on the link local address

**Comment by grimace** [comment]
My broker is running on a separate linux box.  I can publish to it via my OS/X machine via global or link ( with %en0 ).  I'm running mosquitto 1.3.4 on my linux box.  ...good to hear that you can connect via square brackets. I'll have to keep trying.  Thx.

**Comment by hardillb** [comment]
Just connected from my laptop (ubuntu) to mosquitto on my pi with the following address:
```
[fe80::8b59:9ca2:f3f6:9fa6%wlan0]
```

That version of mosquitto is very old, you should look to update to at 1.4.x

**Comment by knolleary** [comment]
Hi, given @hardillb has this successfully working, I'm going to close this issue as it isn't likely to be a bug with the node.

If you want to follow-up on the discussion, please do so on the Node-RED mailing list or slack channel (both linked from the bottom of nodered.org).

Thanks!

**Comment by waksando** [comment]
Not working 
mqtt is running on a pi3 model b and laptop(ubuntu) acts as client
mosquitto_sub -h "[fe80::5b44:e6c6:8494%wlan0]" -t "test/1"

**Comment by anfractuosity** [comment]
@waksando try without the square brackets so: 
 mosquitto_sub -h "fe80::5b44:e6c6:8494%wlan0" -t "test/1"
That kind of version works for me.
