### ISSUE TITLE
How to set the status of and http response?

### ISSUE THREAD

**Issue by Iambecomeroot** [node-red/node-red#1293]
I don't see any documentation on how to set the status code for an http response. I looked [here](https://cookbook.nodered.org/http/), searched around, and looked through the issues and I have found nothing. I have tried `msg.res.status = 401` and `msg.status = 401`. I eventually just did `msg.res.sendStatus(401)` but that gives `"Deprecated call to msg.res.sendStatus"`. If we don't have access to the `res` methods, how do we set the status code?

**Comment by hardillb** [comment]
As clearly documented in the http-response node's info sidebar:

```
msg.statusCode, if set, is used as the response status code (default: 200)
```

**Comment by hardillb** [comment]
Also please read the Contributing guide about asking questions, they should be asked in the Slack channel or on the Google Groups list, both linked to from the Node-RED home page

**Comment by knolleary** [comment]
Hi @Iambecomeroot - as @hardillb has said, the info does give you the info you need. I'm going to close this issue. If you'd like to follow-up, please use the mailing list. Thanks!
