### ISSUE TITLE
Would it be abnormal to add support for my own flow control library?

### ISSUE THREAD

**Issue by bugs181** [node-red/node-red#1294]
Before realizing Node-RED existed, I was/am in the process of writing my own flow control library. It's vanilla ES6 javascript exposing simple database/utility semantics like `.add`, `.remove`, `.update`, `.delete` etc for various databases and utilities. In addition it allows you to expand on the built-in operations to provide more via an adapter/plugin architecture.

At it's core it behaves almost identically to Node-RED with a few exceptions (which I admittedly only briefly covered the docs), like waiting for an operation to finish before moving onto the next. I understand you could do this with the Flow in/out mechanism, but chaining say 20 operations in a single flow could get tedious. I was thinking my library could expose the general .add/.remove as Nodes and then provide a simple HTML UI to configure parameters for those.

An example simple use case:

    const leto = require('Leto')
    let leto = new Leto()

    leto
      .use('neo4j') // Synonymous with require(), but does some special processing.
      .connect({ user, pass, host }) // Pass in a config option for .connect() but has defaults too.
      .create('Person', 'name') // Creates a label constraint on the name prop
      .add(myPerson) // Add the myPerson object to neo4j. No Cypher syntax needed. ;)
      .catch(err => console.log(`Error occured: ${err}`)

In addition to the simple syntax, you can stack multiple "outputs" as such:

    leto
      .use('neo4j')
      .use('elasticsearch')
      .add(...) // Adds an object to both databases. Waiting for neo4j to finish before continuing.

There are future plans to add pre-filtering and post-filtering. There already exists ways to ignore specific operations, and `else` cases to support for a variety of different things. Leto not only targets databases, but common utility modules as well.

My belief is that by adding support for Node-RED could further improve the Node-RED user-base, in addition to adhering to your philosophy of not having to write code. Leto would expose output operations such as `.connect`, `.add`, `.remove`, etc and allow stacking by adding more Nodes.

An example would be:
http node input -> leto.add -> http output

During the brainstorming stage: Inside that node's HTML would be the parameters for the object (msg.payload), in addition to targeting specific databases/utilities (`.use()`. The `.else` case would target a second output which could then further be used for Node inputs or an additional `leto.add()`, for example targeting a Kibana/Redis instance for data logging.

What are your thoughts on me adding support to my project for Node-RED?

**Comment by knolleary** [comment]
Hi, it sounds interesting, but this is not the right place to discuss it.

Please move this over to the node-red mailing list (link at bottom of nodered.org), so the wider community can join the discussion, rather than just the core dev team. Thanks!
