### ISSUE TITLE
Update ace to 1.2.7

### ISSUE THREAD

**Issue by sakazuki** [node-red/node-red#1295]
ace 1.2.4 has a IME bug. 
This bug insert IME inputs duplicatedly.
See the attached image.
![ace-ime-bug](https://user-images.githubusercontent.com/1878694/27410994-199a7b42-5726-11e7-9bad-709dff40e3b4.gif)

This bug was resolved in 1.2.6

> 2016.12.03 Version 1.2.6
>
>* Fixed IME handling on new Chrome
https://github.com/ajaxorg/ace/blob/master/ChangeLog.txt#L9-L11

So please update ace to 1.2.6  or 1.2.7.

**Comment by knolleary** [comment]
Hi @sakazuki - thanks for raising this. I hadn't checked to see if there were new releases of ace for some time. We will update for the 0.17 release of Node-RED.

**Comment by dceejay** [comment]
Updated to v1.2.7 with commit bc472eb

**Comment by sakazuki** [comment]
Thank you for update. I confirmed the IME bug was fixed.
