### ISSUE TITLE
Uncatched exception in Function node will crash the whole node-red app. 

### ISSUE THREAD

**Issue by mylind** [node-red/node-red#1296]
As described in the title, we found an issue for function node, when we try to access an undefined variable in function node, an exception will occur, it will crash the whole Node-Red app. I think it should be a defect.

**Comment by knolleary** [comment]
Can you provide an example?

The following Function code:
```
msg.payload = i_dont_exist;
return msg;
```

Results, correctly, in an error message in the log:

```
22 Jun 08:57:54 - [error] [function:3449a264.10deae] ReferenceError: i_dont_exist is not defined (line 1, col 15)
```

But no crash.

**Comment by knolleary** [comment]
Hi - are you able to provide an example or any further details? What version of node.js etc?

**Comment by knolleary** [comment]
Any more information? We'll close this issue soon if we can't get any more details.

**Comment by knolleary** [comment]
Closing the issue. If you can provide any further information, please reopen.
