### ISSUE TITLE
Outbound IBM IoT Node Error When Domain Is Set

### ISSUE THREAD

**Issue by ajgbarnes** [node-red/node-red#1297]
Create a flow as below:

Set the domain name in the outbound IBM IoT node to internetofthings.ibmcloud.com, click the button to inject into the flow and it shows the following error:

"TypeError: domain.enter is not a function"

Note that you MUST use a valid APIKEY so the outbound node can connect to WIoTP.

[{"id":"e8f930cb.80204","type":"ibmiot out","z":"deb0d57.1c46528","authentication":"apiKey","apiKey":"45820aea.516204","outputType":"evt","deviceId":"deviceid","deviceType":"device","eventCommandType":"event","format":"json","data":"test","qos":0,"name":"IBM IoT","service":"registered","x":586,"y":309,"wires":[]},{"id":"7d254455.eca46c","type":"inject","z":"deb0d57.1c46528","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":303,"y":309,"wires":[["e8f930cb.80204"]]},{"id":"45820aea.516204","type":"ibmiot","z":"","name":"Test","keepalive":"60","domain":"internetofthings.ibmcloud.com","cleansession":true,"appId":"","shared":false}]

**Comment by knolleary** [comment]
Hi, that is not a node maintained by the Node-RED project.

Please raise on their repository.

https://github.com/ibm-watson-iot/node-red-contrib-scx-ibmiotapp
