### ISSUE TITLE
node-red overhead

### ISSUE THREAD

**Issue by scsi1042** [node-red/node-red#1302]
I experienced some trouble with my node-red application due to the workload of the processor. Thus, I want to reduce this workload and was thinking to implement the same code without using node-red. 

Has anybody made any experiences with this before and can tell whats the overhead created by node-red? And if it would be worth implementing the same code without the user-friendly engineering environment?

Here some information about my system
Version: node.js v6.9.2
Platform: Linux iot2000 4.4.18-yocto-standard
Processor: Intel Quark® x1020 400 MHz

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

This would be better discussed on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or, [slack team](https://nodered.org/slack). That way the whole Node-RED user community can contribute, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
Closing this issue as per my comment above.
