### ISSUE TITLE
#0.17 blue dots don't always clear

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1310]
The blue dots aren't always clearing down when you deploy.
The flows work fine, as if they have deployed, they just show blue dots still.
<img width="464" alt="screen shot 2017-06-30 at 23 19 23" src="https://user-images.githubusercontent.com/2693674/27755883-acf3360c-5dea-11e7-89bd-20f7cf285621.png">

This is with 0.17 on Safari on Mac.

**Comment by knolleary** [comment]
Fixed by f3840512ba9464dfd49d3dfa163f1b7eceac1152

Expect 0.17.1 over the weekend.
