### ISSUE TITLE
UI tick boxes missing

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1312]
On the menu, in View, the tick boxes next to Dashboard and Debug messages are missing, so you can't toggle them on and off. 
In fact, they do make them appear, but you can't then make them disappear.

There used to be a ticky box for node status indicators - has that been dumped in favour of always on?
Fine with me, but just wondered if it was meant to be there still?

**Comment by knolleary** [comment]
The debug/dashboard options never were tick boxes. They are options to show that sidebar tab.

The status option has moved into the settings dialog under the view tab.

**Comment by knolleary** [comment]
Just to expand on that...

Not all sidebar tabs can be hidden. Debug/info are not hideable. Config nodes and dashboard are hideable.

The menu is not (and never was) a toggle. They bring the corresponding tab to the front. If you want to remove a hideable tab, you click the cross in its tab bar.

**Comment by andysc** [comment]
thanks - yup - makes good sense :)
