### ISSUE TITLE
activating or deactivating a debug node turns the deploy button red

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1313]
Maybe related to #1310 ?

**Comment by natcl** [comment]
That intended as this change is actually written to file, pre 0.17 behaviour is actually a bug.

**Comment by knolleary** [comment]
Yup - working as designed.

Disabling a debug node is a material change to your flow config and needs a deploy to be saved.

Previously, if you disabled your debug nodes, and didn't deploy, if NR restarted they would all become active again. That had caused problems with users who had disabled their nodes for performance reasons and they unexpectedly reenabled.

**Comment by andysc** [comment]
interesting - I actually thought it was saving those changes to the state of debug nodes "under the covers"... thanks for clarifying :)
