### ISSUE TITLE
Node "rpi-gpio out" doesn't do the expected in GPIO 18 (Pin 12)

### ISSUE THREAD

**Issue by bpolzin** [node-red/node-red#1314]
What you do:
You configure a node "rpi-gpio out" to GPIO 18 (Pin 12), and click Done.

What you get: 
- GPIO 27 (Pin13) works instead of the configured one.
- If you open the configuration tab again, you see the GPIO 27 (Pin 13) selected.
- Pin 13 never shows up in:   Pins in Use: 7,11,12,15,16,18,22,29,31,33,35

Behavior shows up since node-red 0.17.0 on Raspberry-Pi, node-js v6.11.0

I guess, it's caused by node-red/nodes/core/hardware/36-rpi-gpio.html
where lines 84 and 335 show:
`<div class="pinTableCellL pinColorGPIO">GPIO27 - 13 <input type="radio" name="pins" value="12" style="width:auto;"></div>`
Here the selected GPIO27 (Pin 13) is connected with Pin 12 in some way.

**Comment by knolleary** [comment]
Node-RED 0.17.2 was released earlier today to address this. Please upgrade and let us know if it's working again.

**Comment by dceejay** [comment]
make sure to use the bash upgrade script on the docs page

**Comment by bpolzin** [comment]
Wow, quick answer! 

I had 0.17.2 installed just today.
I've run update-nodejs-and-nodered again,
The strange behavior (only at Pins 12 and 13) is still there.
The incorrect lines as described above are still there.
The fix today at node-red/nodes/core/hardware/36-rpi-gpio.html didn't address the special problem with Pins 12 and 13. 

I checked twice.
Sorry, something is still there.

**Comment by dceejay** [comment]
hmm - let me check

**Comment by dceejay** [comment]
Temporary fix - locally you can run

    sudo perl -pi -e 's/GPIO27 - 13 <input type="radio" name="pins" value="12"/GPIO27 - 13 <input type="radio" name="pins" value="13"/g' /usr/lib/node_modules/node-red/nodes/core/hardware/36-rpi-gpio.html

**Comment by bpolzin** [comment]
Temporary fix works for me in every respect. Thanks!

**Comment by knolleary** [comment]
Fixed by #1314 - will be available in 0.17.3

**Comment by knolleary** [comment]
Node-RED 0.17.3 now available with this fix.
