### ISSUE TITLE
Checkboxes in property pages do not display properly in v0.17.2

### ISSUE THREAD

**Issue by yutter** [node-red/node-red#1315]
Checkbox text starts behind the checkbox (spacing between checkbox and text is wrong) in v0.17.2. I have tried both Chrome and Safari on a Mac (latest version of macOS - v10.12.5) and the issue is the same in both. See screen shots attached

<img width="493" alt="screen shot 2017-07-02 at 21 45 27" src="https://user-images.githubusercontent.com/6246062/27773392-80ec9cce-5f70-11e7-9f88-1224776eb3d1.png">
<img width="345" alt="screen shot 2017-07-02 at 21 45 00" src="https://user-images.githubusercontent.com/6246062/27773393-83f42086-5f70-11e7-8640-74f69923cea8.png">

**Comment by knolleary** [comment]
Look fine here:

<img width="67" alt="node-red" src="https://user-images.githubusercontent.com/51083/27773401-cc3273a2-5f70-11e7-9ef6-0805eaceb325.png">

Could you use the Chrome inspector to see if there's any css being applied to them from somewhere else? I wonder if a node you have installed is setting some generic CSS style to checkboxes.

**Comment by yutter** [comment]
Hey Nick, I have uninstalled all nodes that are not part of base and restarted Node-RED. I have checked with inspector and can't see anything odd.
I did not uninstall previous Node-RED, just did an NPM install over the top. I will remove the entire Node-RED install and start again to check

Chris

**Comment by yutter** [comment]
OK, removing my previous install of 0.16.x and re-installing v0.17.2 has fixed it. I will go back and install the nodes (including my own) that I had installed and see if I can recreate.

**Comment by yutter** [comment]
Can't recreate it. All working fine now

**Comment by knolleary** [comment]
Great 👍
