### ISSUE TITLE
Unexpected behaviour in trigger & block since node-red 0.17

### ISSUE THREAD

**Issue by RDCH106** [node-red/node-red#1316]
Because of the following update in the **trigger & block** node introduced **since v 0.17**:

> By default, when it receives a message, it sends on a message with a payload of 1. It then waits 250ms before sending a second message with a payload of 0.

**An unexpected behaviour is present** in my flows that use this node because I can receive 1 value and then 250ms a message with 0 value is sent from the node.

I am experimenting also problems when 0 value arrives and another message is sent 250ms later with the same value received previously (0).

I think that the problem is generated by the new behaviour. It is impossible to update from version 0.17 because it is necesary reimplent many flows and avoid to use the problematic values.

I am not sure if the problem with the 0 value is considered, it could be a bug. In the case of the 1 value it could be very interesting add an option to activate or deactivate the new behaviour. _To ensure the backward compatibility with deployed flows, the behaviour must be deactivated by default._

**Comment by knolleary** [comment]
Hi @RDCH106 - could you share an example node configuration and a description of the behaviour in 0.16 and how that has changed for you in 0.17? We certainly don't want to change behaviour and anything new should be opted-in.

**Comment by RDCH106** [comment]
@knolleary Ok, I will do.

I give you an example:

![imagen](https://user-images.githubusercontent.com/1483414/27792776-9348f080-5ffb-11e7-923c-6906d801e847.png)

The following flow requests every minute for a value stored from a platform called EmonCMS. The value returned is 0 o 1 and thanks to switch node is redirected to the correct output:

![imagen](https://user-images.githubusercontent.com/1483414/27792220-fdbb6ce8-5ff8-11e7-95ea-653c278ef4db.png)

The configuration of the two trigger & block nodes are the same:

![imagen](https://user-images.githubusercontent.com/1483414/27792263-212fb468-5ff9-11e7-8b30-298dd2f8b0cb.png)

In addition two nodes more are used to send the reset message to the opposite trigger & and block node. The behaviour of the trigger & blocks nodes is like a [flip-flop](https://en.wikipedia.org/wiki/Flip-flop_(electronics)). The code of Reload nodes is very simple:

``` javascript
msg.payload="reload";
return msg;
```

Then there is a debug node to see the final result.

Until 0.16.2 version the expected behaviour was when a 0 o 1 value arrives to one of the two triggers, only one message is sent and and the following messages are blocked until the opposite trigger recives a value, sending only one message and sending a reset message to the opposite trigger using the reload node.

Since version 0.17, the behaviour is the following one: when a message arrives to any trigger & block node, the message is send and then and extra message is sent in a period less than 1 second. The wait behaviour is not present...

**Comment by RDCH106** [comment]
OK!

```json
[{"id":"d53e9a6f.08a178","type":"emoncms in","z":"15c0023b.5c0e0e","name":"Running","emonServer":"","feedid":"1","x":240,"y":100,"wires":[["f333159c.f0d158"]]},{"id":"2d2f0a9c.541636","type":"inject","z":"15c0023b.5c0e0e","name":"","topic":"","payload":"","payloadType":"date","repeat":"15","crontab":"","once":false,"x":70,"y":100,"wires":[["d53e9a6f.08a178"]]},{"id":"8f4b2275.d8a49","type":"trigger","z":"15c0023b.5c0e0e","op1":"3:1","op2":"0","op1type":"pay","op2type":"val","duration":"0","extend":false,"units":"ms","reset":"reload","name":"","x":559.1666584014893,"y":168.5,"wires":[["60df987e.01dbc8","5aa1cdbc.2d2b94"]]},{"id":"f333159c.f0d158","type":"switch","z":"15c0023b.5c0e0e","name":"Activation","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"1","vt":"num"},{"t":"eq","v":"0","vt":"num"}],"checkall":"true","outputs":2,"x":291.16666984558105,"y":201.24999904632568,"wires":[["8f4b2275.d8a49"],["7e815e38.c83ee"]]},{"id":"7e815e38.c83ee","type":"trigger","z":"15c0023b.5c0e0e","op1":"3:1","op2":"0","op1type":"pay","op2type":"val","duration":"0","extend":false,"units":"ms","reset":"reload","name":"","x":556.6666584014893,"y":254.5,"wires":[["b4f791c7.d5b54","5aa1cdbc.2d2b94"]]},{"id":"b4f791c7.d5b54","type":"function","z":"15c0023b.5c0e0e","name":"Reload","func":"msg.payload=\"reload\";\nreturn msg;","outputs":1,"noerr":0,"x":548.916654586792,"y":335.00000190734863,"wires":[["8f4b2275.d8a49"]]},{"id":"60df987e.01dbc8","type":"function","z":"15c0023b.5c0e0e","name":"Reload","func":"msg.payload=\"reload\";\nreturn msg;","outputs":1,"noerr":0,"x":555.1666584014893,"y":93.74999809265137,"wires":[["7e815e38.c83ee"]]},{"id":"5aa1cdbc.2d2b94","type":"debug","z":"15c0023b.5c0e0e","name":"","active":true,"console":"false","complete":"true","x":905,"y":213,"wires":[]}]
```

**Comment by knolleary** [comment]
Thanks - have recreated and will investigate.

Here's a slightly modified version of your testcase that removes the dependency on `emoncms`

```
[{"id":"89f077fa.b57ea8","type":"switch","z":"e381ba5e.18b408","name":"Activation","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"1","vt":"num"},{"t":"eq","v":"0","vt":"num"}],"checkall":"true","outputs":2,"x":220,"y":100,"wires":[["25629a90.683816"],["c1aae137.1b1f"]]},{"id":"25629a90.683816","type":"trigger","z":"e381ba5e.18b408","op1":"3:1","op2":"0","op1type":"pay","op2type":"val","duration":"0","extend":false,"units":"ms","reset":"reload","name":"","x":480,"y":80,"wires":[["627a690f.891068","4a8e3070.6c0c1"]]},{"id":"c1aae137.1b1f","type":"trigger","z":"e381ba5e.18b408","op1":"3:1","op2":"0","op1type":"pay","op2type":"val","duration":"0","extend":false,"units":"ms","reset":"reload","name":"","x":480,"y":140,"wires":[["a95a312c.1da2c","9511f9f4.e040a8"]]},{"id":"dcb6bd58.03241","type":"inject","z":"e381ba5e.18b408","name":"","topic":"","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"x":90,"y":140,"wires":[["89f077fa.b57ea8"]]},{"id":"5c90734a.61ce4c","type":"inject","z":"e381ba5e.18b408","name":"","topic":"","payload":"0","payloadType":"num","repeat":"","crontab":"","once":false,"x":90,"y":80,"wires":[["89f077fa.b57ea8"]]},{"id":"627a690f.891068","type":"function","z":"e381ba5e.18b408","name":"Reload","func":"msg.payload=\"reload\";\nreturn msg;","outputs":1,"noerr":0,"x":460,"y":40,"wires":[["c1aae137.1b1f"]]},{"id":"4a8e3070.6c0c1","type":"debug","z":"e381ba5e.18b408","name":"","active":true,"console":"false","complete":"true","x":690,"y":60,"wires":[]},{"id":"a95a312c.1da2c","type":"function","z":"e381ba5e.18b408","name":"Reload","func":"msg.payload=\"reload\";\nreturn msg;","outputs":1,"noerr":0,"x":460,"y":200,"wires":[["25629a90.683816"]]},{"id":"9511f9f4.e040a8","type":"debug","z":"e381ba5e.18b408","name":"","active":true,"console":"false","complete":"true","x":710,"y":160,"wires":[]}]
```

**Comment by knolleary** [comment]
Node-RED 0.17.3 now available with this fix.
