### ISSUE TITLE
Support period characters as flow name in flow library menu 

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#1319]
Node-RED editor menu doesn't show the flow name which contains period characters correctly.
For example, a user inputs "1.sampleflow" as flow name to save a flow.

![export](https://user-images.githubusercontent.com/20310935/27813144-c62b2960-60ae-11e7-91a3-8f52d487df69.png)

After that, editor menu shows only "1" because current Node-RED  removes the characters which are placed after the period.

![import](https://user-images.githubusercontent.com/20310935/27813148-cdb5458a-60ae-11e7-93f2-2784355d598b.png)

I think that correct handling removes only file extension, ".json" and shows flow name without the file extension.

**Comment by knolleary** [comment]
Closed by #1320

**Comment by knolleary** [comment]
Node-RED 0.17.3 now available with this fix.

**Comment by kazuhitoyokoi** [comment]
Thank you @knolleary . Node-RED v0.17.3 on my Raspberry Pi showed flow name correctly.
