### ISSUE TITLE
msg.payload being modified unexpectedly

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1323]
I have a flow which creates an entry in a sub-object array of msg.payload, then later adds another entry to the sub-object array. 
Before the second entry is added, a function node, between setting the first and adding the second entry, sees the later value (with both entries).
I don't know if this is something to do with pointers to objects, or asynchronous parts of the flow, or what, but it's seriously messing up my application.

```
[{"id":"3d4473bf.d02c34","type":"change","z":"f8a22461.b9e17","name":"JSON headers","rules":[{"t":"set","p":"statusCode","pt":"msg","to":"200","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":4240,"y":560,"wires":[[]]},{"id":"fc7bdd6c.eea5b","type":"json","z":"f8a22461.b9e17","name":"","x":1670,"y":520,"wires":[["dd811b2b.f99278","b067fe67.c6fe78"]]},{"id":"4c07319f.b3b558","type":"comment","z":"f8a22461.b9e17","name":"special cases","info":"All catalogues are assumed to be either /cat or under /cat (e.g. /cat/house)\n\nWe return the *new* item from a CREATE item POST.\nThis is consistent with the PUT/POST REPLACE call\n\nPOST will create or update an existing entry, regardless of the existence of a query string\n\nAn UPDATE must not change the href of an item.\n\nDELETE returns 204 (OK but nothing returned) on successful completion\n\n","x":70,"y":760,"wires":[]},{"id":"9f21a1a3.03a818","type":"change","z":"f8a22461.b9e17","name":"meta","rules":[{"t":"set","p":"metadata","pt":"msg","to":"payload.catalogue-metadata","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":2030,"y":540,"wires":[["e664aa5.e80eed8"]]},{"id":"e664aa5.e80eed8","type":"function","z":"f8a22461.b9e17","name":"add metadata","func":"\n// add in the required metadata items\nmsg.metadata.push({rel: \"added later\"});\n\nreturn msg;","outputs":1,"noerr":0,"x":2200,"y":540,"wires":[["54ce5a63.8d0a04"]]},{"id":"54ce5a63.8d0a04","type":"function","z":"f8a22461.b9e17","name":"build catalogue","func":"msg.payload = {'catalogue-metadata': msg.metadata};\n\nreturn msg;","outputs":1,"noerr":0,"x":2400,"y":540,"wires":[[]]},{"id":"dd811b2b.f99278","type":"function","z":"f8a22461.b9e17","name":"warn payload","func":"node.warn(msg.payload);\n\nreturn msg;","outputs":1,"noerr":0,"x":1840,"y":540,"wires":[["9f21a1a3.03a818"]]},{"id":"8266c66f.568698","type":"inject","z":"f8a22461.b9e17","name":"Initialise","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"x":140,"y":120,"wires":[["e45023f8.d82cb"]]},{"id":"e45023f8.d82cb","type":"change","z":"f8a22461.b9e17","name":"Hypercat","rules":[{"t":"set","p":"Hypercat","pt":"flow","to":"{}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":300,"y":120,"wires":[[]]},{"id":"922376ec.404cf","type":"function","z":"f8a22461.b9e17","name":"un-cache","func":"flow.set(\"Hypercat['\"+msg.path+\"']\", undefined);\nreturn msg;","outputs":1,"noerr":0,"x":200,"y":900,"wires":[[]]},{"id":"38448e07.73aa3a","type":"link in","z":"f8a22461.b9e17","name":"remove from cache","links":["fda5355b.20b32"],"x":75,"y":900,"wires":[["922376ec.404cf"]]},{"id":"b067fe67.c6fe78","type":"debug","z":"f8a22461.b9e17","name":"","active":true,"console":"false","complete":"false","x":1850,"y":480,"wires":[]},{"id":"7d74891f.7479e8","type":"template","z":"f8a22461.b9e17","name":"content","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"{\n\t\"catalogue-metadata\": [{\n\t\t\"rel\": \"should be here\"\n\t}],\n\t\"items\": []\n}","output":"str","x":1510,"y":520,"wires":[["fc7bdd6c.eea5b"]]},{"id":"6eabe9cb.9cfd78","type":"inject","z":"f8a22461.b9e17","name":"go","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":1330,"y":520,"wires":[["7d74891f.7479e8"]]}]
```

The "warn payload" node shows both entries in the catalogue-metadata array, whereas the debug node directly before it (after the JSON node) only shows one entry.

Is this a bug, or if not, how can I avoid it?

**Comment by knolleary** [comment]
Well, I don't know what's going on here yet as trying to import this flow hits a bug:
```
onadd: TypeError: Cannot read property 'links' of null
    at Object.onAdd (eval at <anonymous> (vendor.js:2), <anonymous>:186:18)
    at Object.importNodes (red.js:11681)
    at HTMLDivElement.click (red.js:16870)
    at HTMLButtonElement.s.click (vendor.js:17)
    at HTMLButtonElement.dispatch (vendor.js:4)
    at HTMLButtonElement.r.handle (vendor.js:4)
```

**Comment by knolleary** [comment]
OH ignore me - that's benign... I just had to scroll further to find all your nodes...

**Comment by knolleary** [comment]
Ok... I can't make sense of your flow.

Once I gathered all the nodes that were spread across the workspace, this is what I've got:

<img width="501" alt="cursor_and_node-red" src="https://user-images.githubusercontent.com/51083/27843725-dba0e572-610e-11e7-8b67-39f05acc3808.png">

What steps do I take to recreate the issue?

**Comment by knolleary** [comment]
Ok, figured it out.

Remember the original fix we did for your memory issue? I made sending to Debug asynchronous to the flow.

Also, remember from your other issue about cloning messages what we've said before.. essentially, if a node is wired to one other node, we don't clone the message, if it is wired to more than one node, we do clone the message.

The message coming out of the JSON node is wired to two places, so they get cloned. The Debug node gets its unique copy and the `warn payload` node gets its own copy. Its call to `node.warn` queues up a now-asynchronous call to Debug to display the message. After queuing up that call (ie adding it as an event to the queue), it then synchronously continues the flow... all the way to your Function node that modifies the message object. At that point, the event queue unwinds and processes the next task - sending the message to Debug from the earlier node. But at this point, the message has been modified, so you see the modified version in Debug.

I'm going to revert the 'make sending to Debug asynchronous' fix from earlier as this is an undesirable side-effect. Also, the subsquent fix I made for your memory issue was much more at the heart of the issue.

Of course, if we always cloned messages, that would also address it - but with a performance penalty.

**Comment by andysc** [comment]
sorry for the debris of node bits spread around my worksheet - you should have seen the flow I hacked  down to make this use case ;)
I was about to come back and say that when I examined msg.payload in the function node, it had the right number of items (1), so was going to say there is something else going on, probably with debug... so you beat me to it - thank you :)

Yes, I agree the async debug thing would have caused lots of grief, so good plan to back it out.

Thanks (yet again!)
