### ISSUE TITLE
gpio-table is partly hidden so that i can't select GPIO 26 or GPIO20

### ISSUE THREAD

**Issue by bpolzin** [node-red/node-red#1328]
The new rpi gpio-table is partly hidden behind the following parts as you can see in the screenshot. I can't select GPIO 26 or GPIO20. 
![screenshot-gpio](https://user-images.githubusercontent.com/29841947/27880197-79be09b4-61c4-11e7-920f-5966cce419c2.png)

Firefox 54.0 for Linux Mint
Node-RED version: v0.17.3
Node.js  version: v6.11.0
Linux 4.9.28-v7+ arm LE on RaspberryPi

Details:
In /usr/lib/node_modules/node-red/nodes/core/hardware/36-rpi-gpio.html the table is ment to be 380px high, but is 440px high. It's because every row is 22px high instead of planned 19px. 22px come from the radio button, which is rendered 16px high with a margin-top of 4px and two borders of 1px. The margin-top of 4px is defined in red/style.min.css.

Possible solution:
For this special table, i think it's ok to delete the margin-top. 
I for myself inserted the following style twice into "36-rpi-gpio.html" :
`        div.pinTableRow input {
                margin-top:0;
        }
`

**Comment by knolleary** [comment]
I don't see this myself when I test on Chrome or Firefox, but I do see if happen if I modify the heights of `div.pinTableRow`... which is odd until I realised the containing form has a `max-height` set on it - which is preventing the form from growing to accommodate variations in size.

I don't see any need for `max-height`, so will remove. That should address the problem.

**Comment by bpolzin** [comment]
Works for me.
Nice solution, indeed!
