### ISSUE TITLE
Link node properties show variable names

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#1329]
Link node properties incorrectly show variable names in their tables as follows.

- name and hint
![linknode1](https://user-images.githubusercontent.com/20310935/27894232-e5b36566-6245-11e7-9657-e352455ffd40.png)

- flow and hint
![linknode2](https://user-images.githubusercontent.com/20310935/27894233-e5b5650a-6245-11e7-9edc-ded32ca56c88.png)

I think that there're 2 reasons of the problem.
- messages.json doesn't have these messages.
- 60-link.html doesn't refer them correctly.

**Comment by knolleary** [comment]
Thanks for raising this.

Have added the missing messages, but as you observed, that was not enough to fix it. Have properly namespaced the keys - not sure why that's needed... possibly due to the use of the `[title]` prefix. Will investigate separately.

**Comment by kazuhitoyokoi** [comment]
Thank you @knolleary . I learned it. :)
There're 4 bugs in the issue. So I'll post pull request to fix 2 bugs.
