### ISSUE TITLE
node changes while deploying appear clean, when dirty

### ISSUE THREAD

**Issue by openSoftMan** [node-red/node-red#1332]
System Info:
- v0.17.3
- node -v v6.11.0
- Linux 4.9.28+ #998 armv6l
- Good ole Rpi v1 B 512mb
- Environment="NODE_OPTIONS=--max-old-space-size=256"
- My flows file is 436KB

Steps to reproduce ( I use deploy Modified Nodes most of the time, unless I want to reset vars):
1) Add a function node
2) Add a msg.payload = "11111";  before the default return msg;
3) Deploy it and while it's deploying, go back into the function node.
4) Quickly add another char to the string "111b11", click Done.
5) Once the deploy completes, the flow is clean.
6) Go back into the function node, you'll see the "111b11"
7) Refresh the page, no warning to leave the page will appear as all seems clean.
8) Go back into the function node, you'll see the "11111"

I don't ever remember having this prior to .17

Regards.

**Comment by knolleary** [comment]
Thanks for the clear issue description.

With the fix I've pushed, we'll disable the editor whilst the deploy is in flight so you can't make changes until the deploy completes.
