### ISSUE TITLE
Make oneditdelete available for normal nodes

### ISSUE THREAD

**Issue by yqf3139** [node-red/node-red#1346]
`oneditdelete` is only used by configuration nodes, it should be available for normal nodes.
This issue is discussed in slack. Make an issue to track it. If it is logged in other places, please close it.

**Comment by knolleary** [comment]
After it was discussed on slack, I added an item to the Trello backlog: https://trello.com/c/PCH0BvZO/123-oneditdelete-should-be-available-to-regular-nodes

**Comment by knolleary** [comment]
Fixed in 0.18 branch
