### ISSUE TITLE
CORS HTTP POST with preflight request: cors headers missing in the response

### ISSUE THREAD

**Issue by khelkun** [node-red/node-red#1347]
I've been in trouble using an HTTP-IN node with POST method with the suitable _httpNodeCors_ option object in settings.js:
```
httpNodeCors: {
        origin: "*",
        methods: "GET,PUT,POST,DELETE,OPTIONS",
        preflightContinue: true
},
```
If there is no [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) everything works fine. But if there's one then this preflight request works fine but the real HTTP POST request doesn't get the "Access-Control-Allow-Origin" and the others CORS headers in the response.

According to [this issue](https://github.com/expressjs/cors/issues/2) on the expressjs/cors @troygoode (main contributor of the cors module) wrote a code snippet in his second answer:
```
app.options('/api/login', cors(corsOptions), login.login); //add this line
app.post('/api/login', cors(corsOptions), login.login);
```
So I looked where the _httpNodeCors_ option is passed to the [HTTP-IN node code](https://github.com/node-red/node-red/blob/master/nodes/core/io/21-httpin.js#L169) of node-red.
IMHO there should be an additional line [here](https://github.com/node-red/node-red/blob/master/nodes/core/io/21-httpin.js#L169):
```
    if (RED.settings.httpNodeCors) {
        corsHandler = cors(RED.settings.httpNodeCors);
        RED.httpNode.options("*",corsHandler);
        RED.httpNode.post("*",corsHandler); // I added this line
    }
```
If I add this line then my HTTP POST request with a preflight request works fine. I'm not confident enough to submit a merge request about this so thank you if a node-red contributor can look into this. Plus may be it should be done for the others HTTP methods like PUT & DELETE. Please also note that the GET with preflight request works fine as far as I saw.

**Comment by khelkun** [comment]
Sorry
Just forget it: this line I added in node-red/nodes/core/io/21-httpin.js has nothing to do with my issue. Apparently my POST request was just wrong and was triggering an exception in the HTTP-IN node and so forth the response hadn't the cors headers

**Comment by rajan-g** [comment]
Simple add following code with function node before http response:
msg.headers = {};
msg.headers["Access-Control-Allow-Origin"]= "*";
msg.headers["Access-Control-Allow-Methods"]= "POST, GET, OPTIONS";

**Comment by floriancastelain** [comment]
Thank you very much @rajan-g . After 1 hour on this, you saved my day.

**Comment by mu3** [comment]
> Simple add following code with function node before http response:
> msg.headers = {};
> msg.headers["Access-Control-Allow-Origin"]= "*";
> msg.headers["Access-Control-Allow-Methods"]= "POST, GET, OPTIONS";

Seems like it stops working when you need to include some headers on a client:

    fetch('https://node-red-backend.com/', { headers: { jwt: token } })

**Comment by rajan-g** [comment]
@mu3  msg.headers is reponse header. 
fetch('https://node-red-backend.com/', { headers: { jwt: token } }) -> it has request header  
For this case only httpNodeCors in settings helps. -> there also the recommend to use middle ware, in a middle ware we have to add  response header
