### ISSUE TITLE
Blue lights

### ISSUE THREAD

**Issue by scargill** [node-red/node-red#1349]
When altering a node, a blue round indicator lights up - when you DEPLOY the node, it then goes away.  Except that I am on version 0.17 and I've just noticed that sometimes when working on multiple nodes/functions, it does NOT. If you hit refresh of the browser (Chrome on Windows 10 64) it goes away...  not sure if this is recent or not as I just noticed it.

**Comment by knolleary** [comment]
@scargill which exact version are you on? This was an issue with 0.17.0 but was fixed in the subsequent maintenance release. 0.17.4 is the latest.

**Comment by scargill** [comment]
Ah right I was just writing in to say that it seems to happen when you MOVE a node.  And yes according to my screen I'm on 0.17.0 so I will upgrade to 0.17.4 - thanks Nick.
