### ISSUE TITLE
File Node doesn't recreate file after delete

### ISSUE THREAD

**Issue by robertsLando** [node-red/node-red#1351]
I use a Button "Delete" in Dashboard UI that sends a msg to File Node setted with action "Delete file" to delete a file stored in my Raspi /home/pi/data/ folder. I use File-In node setted with action "Append to File" and the Tick on "Create directory if it doesn't exist.". Sometimes after pressing Delete button in my UI the file is correctly deleted but It is not recreated when a new input is sent to File-In node (and no error log are shown in debug), I need to redeploy to make it work again.

**Comment by dceejay** [comment]
Is this with a fixed file name ? Or one that is passed on on msg?

**Comment by dceejay** [comment]
Is behaviour the same if you don't have create directory ticked ?

**Comment by robertsLando** [comment]
@dceejay: fixed file name, didn't tried with the option "create dir if doesn't exist" unticked. The strange thing is that there isn't any error log to understand what's happening

**Comment by dceejay** [comment]
Ok, thanks. Have identified a possible fail path when file deleted underneath us. Fix will be in 0.17.5
