### ISSUE TITLE
Mustache expressions in Change-Node

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red#1353]
Dear,

I would like to request a new feature in the Change-Node, to allow Mustache expressions to be used.  It can be implemented using a single line of code, similar to the HttpRequest node.

# Problem description

Suppose there is a global variable '_topics_' containing following data:
![image](https://user-images.githubusercontent.com/14224149/28592900-c62d94d8-718a-11e7-9445-2eaa404673af.png)

A message arrives with following two fields:
- `msg.payload`: containing '_new value_'
- `msg.topic`: containing '_TOPIC2_'

I want to use a single Change-node to apply the new value to topic2 in the global json array.  If I'm not mistaken this is currently not possible, but _**correct me if I'm wrong**_ !!!!!!!!

# Solution

I have added following code to the 15-change.js file:

![image](https://user-images.githubusercontent.com/14224149/28593430-907ab8d2-718c-11e7-9c10-65e2642e3de6.png)

![image](https://user-images.githubusercontent.com/14224149/28593488-befcd3b6-718c-11e7-8d31-74fd8b0d3a74.png)

# The result

When I use now following Mustache formatted expression:
![image](https://user-images.githubusercontent.com/14224149/28594542-a32c7dae-7190-11e7-8840-9ee9e4a27efa.png)

In following flow:
![image](https://user-images.githubusercontent.com/14224149/28594347-ef3ddd60-718f-11e7-9698-a5af94ef8079.png)
```
[{"id":"cce10850.07aec8","type":"inject","z":"d0d4f76e.209b68","name":"Inject new value","topic":"TOPIC2","payload":"new value","payloadType":"str","repeat":"","crontab":"","once":false,"x":803.6668033599854,"y":805.6666679382324,"wires":[["5a39220.3d2f7e"]]},{"id":"5a39220.3d2f7e","type":"change","z":"d0d4f76e.209b68","name":"Set last value","rules":[{"t":"set","p":"topics['{{topic}}'].last_value","pt":"global","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":997.6668643951416,"y":805.6666679382324,"wires":[[]]},{"id":"f78c767c.de6eb8","type":"inject","z":"d0d4f76e.209b68","name":"Initialize global context","topic":"MAGN_KEUK","payload":"{\"TOPIC1\":{\"last_value\":\"old value\"},\"TOPIC2\":{\"last_value\":\"old value\"},\"TOPIC3\":{\"last_value\":\"old value\"}}","payloadType":"json","repeat":"","crontab":"","once":false,"x":784.6666259765625,"y":760.6666259765625,"wires":[["9ce689a6.09fe38"]]},{"id":"9ce689a6.09fe38","type":"change","z":"d0d4f76e.209b68","name":"Set global variable","rules":[{"t":"set","p":"topics","pt":"global","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1009,"y":760.6666259765625,"wires":[[]]}]
```

The result seems to be correct:
![image](https://user-images.githubusercontent.com/14224149/28594329-dbd35476-718f-11e7-8abe-810739ea01b9.png)

Hope you guys like this feature...

Kind regards,
Bart

**Comment by knolleary** [comment]
Hi, please check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to discuss feature requests on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack).

Introducing mustache support is something we've chosen not to do in general - but I can see the use case you're raising isn't easily handled otherwise (short of using a Function node). A significant issue will be doing this in a way that doesn't break existing flows - however unlikely, "{{payload}}" is a valid identifier that an existing flow may be using. If we start parsing it as mustache it will break.

**Comment by bartbutenaers** [comment]
Good evening Nick,

Thought I could skip the discussion on the mailing list, because the same feature was already available in the HttpRequest node...  I will take it into account next time.

Indeed I first used a function node, but seemed to be a bit silly since the entire solution (based on Mustache) was already part of Node-Red.  

Since it will break existing flows, you can skip this feature request.   I can help myself with my function node...

Kind regards,
Bart

**Comment by knolleary** [comment]
Hi @bartbutenaers - please do use the mailing list in the first instance. Whilst the mustache approach may or may not be the right solution, I do think you have a valid use case here that we should think about. Thanks for bringing it up.
