### ISSUE TITLE
basic authentication password truncated for http request node

### ISSUE THREAD

**Issue by wnmills3** [node-red/node-red#1354]
I'd attempted storing my bluemix userid and password in a node to call a bluemix service.
Using basic authentication caused the password to be truncated when the flow was reloaded.
It behaves as though there is a short limit on characters for a password.

I was able to work around this using https://<user>:<password>@host... but if you offer basic authentication, the fields should not be truncated.

**Comment by wnmills3** [comment]
It appears the basic-auth settings are managed by red.js with a limit on password.length of 32. Is there any reason this should limited, given the gorp bluemix uses for authorization? Or at least something more reasonable like 128 (arbitrary choice...).

**Comment by knolleary** [comment]
Was the request actually failing?

The runtime *never* returns password credentials back to the editor. When you reload the editor, it fills the password field in with a placeholder to indicate a value is known, but as it doesn't know the actual value it isn't able to use a placeholder of the appropriate length. That can suggest it has been truncated, but it hasn't. Within the runtime, the proper password is known and used.

**Comment by wnmills3** [comment]
Thank you for the explanation. I'll have to test but given this is a know feature I suspect I jumped the gun. I'll close and reopen if there are any problems.
