### ISSUE TITLE
http request node should provide option for parsing response

### ISSUE THREAD

**Issue by wnmills3** [node-red/node-red#1356]
It would be nice if there was an ability to provide a filter on the response object returned from a REST call made using the http request node. When calling an OpenWhisk microservice you get back a slew of crap with the response holding what the microservice actually returned. It would be nice if we could select a key from the response to map to the msg.payload on the outgoing msg, or perhaps to be merged into the original msg.payload presented. In its current form, we have to piggyback every http request node with a clean up filter and we may also have to use split/join to enable the original msg payload to be preserved from one side of the http request to the other.

**Comment by knolleary** [comment]
We don't want to overload functionality in each node. The HTTP Request node makes http requests and returns the response. That's its purpose. If you then want to extract particular values, a Change node can do that.

(Same note as on #1355 - feature proposals should be made on the mailing list or slack)
