### ISSUE TITLE
delay node - rate limit stopped after reset

### ISSUE THREAD

**Issue by vsimko** [node-red/node-red#1360]
```
node version: v7.10.1
node-red version: v0.17.5
```

I wanted to implement a start-stop button pair.
The idea was that the start button generates a bunch of messages which are then delayed using the `delay` node (1msg/second).

While processing the pending messages, I wanted to use a stop button to send a `reset` command to the `delay` node as described in the documentation.

Stopping the delay node works but after that, I cannot process any more messages.
All subsequent messages are piled up before being sent.

![image](https://user-images.githubusercontent.com/7080773/28966351-f7c8ca84-7915-11e7-948f-316faa80c374.png)

Here is my flow:
```json
[
    {
        "id": "8dbd94bc.ad7c78",
        "type": "delay",
        "z": "ef18c1ce.2f9e8",
        "name": "",
        "pauseType": "rate",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 550,
        "y": 180,
        "wires": [
            [
                "30ea1ad5.d240e6"
            ]
        ]
    },
    {
        "id": "30ea1ad5.d240e6",
        "type": "debug",
        "z": "ef18c1ce.2f9e8",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "payload",
        "x": 730,
        "y": 180,
        "wires": []
    },
    {
        "id": "187856c5.917d89",
        "type": "function",
        "z": "ef18c1ce.2f9e8",
        "name": "add reset",
        "func": "msg.reset = true;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 340,
        "y": 180,
        "wires": [
            [
                "8dbd94bc.ad7c78"
            ]
        ]
    },
    {
        "id": "19564af5.6f89e5",
        "type": "inject",
        "z": "ef18c1ce.2f9e8",
        "name": "Start",
        "topic": "",
        "payload": "20",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 190,
        "y": 120,
        "wires": [
            [
                "efec5431.622c68"
            ]
        ]
    },
    {
        "id": "9028802.996758",
        "type": "inject",
        "z": "ef18c1ce.2f9e8",
        "name": "Stop",
        "topic": "",
        "payload": "false",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 190,
        "y": 180,
        "wires": [
            [
                "187856c5.917d89"
            ]
        ]
    },
    {
        "id": "efec5431.622c68",
        "type": "function",
        "z": "ef18c1ce.2f9e8",
        "name": "Sequence",
        "func": "const n = msg.payload;\nconst range = Array.from(Array(n).keys());\n\nrange.forEach( x => node.send({payload:x}) );\n",
        "outputs": 1,
        "noerr": 0,
        "x": 340,
        "y": 120,
        "wires": [
            [
                "8dbd94bc.ad7c78"
            ]
        ]
    }
]
```

**Comment by dceejay** [comment]
What do you mean by "piled up". The reset just flushes any existing queue of messages. Anything then arriving will be delayed as per normal, so yes will be piled up.

**Comment by vsimko** [comment]
The problem is that once the reset signal is received by the node, it doesn't send any more messages.

**Current behavior:**
1. Start button clicked
2. 20 messages arrive to the `delay` node
3. `delay` node starts sending messages 1msg/sec and shows 20,19,18,...
4. Stop button clicked
5. `delay` node shows "reset" and stops sending messages
6. Start button clicked again
7. `delay` node shows "20" and doesn't send any messages anymore
8. Start button clicked again 5 times
9. `delay` node shows "120" and still doesn't send any messages

**Expected behavior:**
6. Start button clicked again
7. `delay` node starts sending messages 1msg/sec and shows 20,19,18,...

**Comment by knolleary** [comment]
@vsimko thanks for providing an example flow that demonstrates the problem. I've recreated it locally and will investigate.
