### ISSUE TITLE
Can't export from subflows.

### ISSUE THREAD

**Issue by thexperiments** [node-red/node-red#1362]
If I'm within a subflow I can't export the selected content via the menu.

Tested with 0.17.5 git tag.
System:
Windows + Chrome/Firefox latest.

Output on javascript console in chrome:
```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at h (red.min.js:16)
    at Object.g [as createExportableNodeSet] (red.min.js:16)
    at HTMLAnchorElement.<anonymous> (red.min.js:16)
    at HTMLAnchorElement.dispatch (vendor.js:4)
    at HTMLAnchorElement.r.handle (vendor.js:4)
    at Object.trigger (vendor.js:4)
    at HTMLAnchorElement.<anonymous> (vendor.js:4)
    at Function.each (vendor.js:2)
    at m.fn.init.each (vendor.js:2)
    at m.fn.init.trigger (vendor.js:4)
```

**Comment by knolleary** [comment]
Thanks. Quick work around until we get it fixed - ensure you don't have any of the input/output 'nodes' selected when you try to export.

Nick

**Comment by thexperiments** [comment]
Thanks for the quick feedback!
I can confirm that this "works" however I also need to be able to export these to share the subflows.

X

**Comment by knolleary** [comment]
To export a subflow, you wouldn't want to do it from 'within' the subflow as that would not pickup the top-level subflow properties. You should add an instance of the subflow to your workspace, then export that node - that will pull in the subflow definition into the export. There are problem better ways we could expose that action, but that's the current way to do it.

**Comment by thexperiments** [comment]
Thanks for the tip.
Works for me :)

By the way the latest master@head doesn't show most of the interface due to a js exception. Should I file a bug or is it considered ok that head is unstable?

**Comment by knolleary** [comment]
oops - a work-in-progress slipped in. Master should generally be stable - but if you spot something, worth pinging me on slack in the first instance.

**Comment by knolleary** [comment]
Master is fixed
