### ISSUE TITLE
Function node "Outputs" field causes freeze on negative number

### ISSUE THREAD

**Issue by TrevorMuraroAtVigilent** [node-red/node-red#1370]
I've run into an issue with the configs of the Function node when messing around with it.  If a non-number is put into the "Outputs" field, clicking "Done" simply grays out the button text and does nothing, forcing the user to replace the non-number with a valid input.  However, if a negative number is put into the "Outputs" field and the "Done" button is clicked, the node-red browser window will freeze and become unresponsive.  All other browser windows for the same machine will be fine.

Obviously this will only happen if a user actually tries to break the node, and it doesn't cause any actual problems unless you forgot to deploy your work before trying to break the node, but I figured it's worth documenting anyway.

Node red v0.17.5, node.js v6.9.2, Chrome 60.0.3112.90.

**Comment by dceejay** [comment]
Yes we ought to handle better

- and also similar (but not as broken) on inject and delay nodes spinners (can set times to negative)
