### ISSUE TITLE
Websocket connection options?

### ISSUE THREAD

**Issue by devnewton** [node-red/node-red#1379]
With Websocket node of type _listen on_, default timeout is very low and there is no way to set a custom value in node-red GUI.

Is there a way to setup the following websocket parameters?

- send/receive/connection timeouts.
- heartbeat ping interval.
- text message max size.
- binary message max size.

**Comment by knolleary** [comment]
No, none of those options are currently exposed in any way.

**Comment by knolleary** [comment]
Given we try not to use this issue list to track feature requests, we have this item on our backlog that covers this: https://trello.com/c/nx4islGu

We also have #797 which is related. Going to close this issue as we don't need both.
