### ISSUE TITLE
 category tab not removed even when all corresponding nodes are disabled

### ISSUE THREAD

**Issue by satya23k** [node-red/node-red#1382]
even though I have disabled all the nodes from manage palette options, the category(Elasticsearch over here) still persists in the node repository tab. It goes away only after a page refresh.
![node red](https://user-images.githubusercontent.com/10613860/30082768-92508bf6-9251-11e7-9b23-3b331dc7b3d6.png)

**Comment by knolleary** [comment]
That is the current implemented behaviour. I assume you're suggesting the category should be removed when it is empty?

**Comment by satya23k** [comment]
yes

**Comment by dceejay** [comment]
currently disable is a hide type action rather than remove  - so i guess the category should also be hidden if empty...  maybe something like this in `editor/js/ui/palette.js`

```
function hideNodeType(nt) {
        var nodeTypeId = escapeNodeType(nt);
        var paletteNode = $("#palette_node_"+nodeTypeId);
        paletteNode.hide();
        var categoryNode = paletteNode.closest(".palette-category");
        var cl = categoryNode.find(".palette_node");
        var c = 0;
        for (var i = 0; i < cl.length; i++) {
            if ($(cl[i]).css('display') === 'none') { c += 1; }
        }
        if (c === cl.length) { categoryNode.hide(); }
    }

```
 ```
   function showNodeType(nt) {
        var nodeTypeId = escapeNodeType(nt);
        var paletteNode = $("#palette_node_"+nodeTypeId);
        var categoryNode = paletteNode.closest(".palette-category");
        categoryNode.show();
        paletteNode.show();
    }
```
