### ISSUE TITLE
Azure AD as OAuth v1.0 Authentication Method

### ISSUE THREAD

**Issue by VeitSanner** [node-red/node-red#1393]
I am trying to create an authentication package which allows to use Azure AD as authentication method. But there seems to be an issue when Azure AD redirects the user after the login. The user always ends up on the page he started the login procedure. And the only way to proceed is to select "Sign in" again. From node-red perspective the sign-in in Azure AD never seem to happen.

I use [passport-azure-ad](https://github.com/AzureAD/passport-azure-ad) from _Microsoft_ as plugin for passport.

The authentication plugin for node-red uses the collowing configuration. (Hardcoded to test the issue more easily)

```Javascript
var adminAuth = {
        type: "strategy",
        strategy: {
            name: "azuread-openidconnect",
            label: "Sign in with Azure",
            icon: "fa-windows",
            strategy: azureadStrategy.OIDCStrategy,
            options: {
                identityMetadata: "https://login.microsoftonline.com/[Azure AD Tenant].onmicrosoft.com/.well-known/openid-configuration",
                clientID: "[CLIENT_ID]",
                responseType: "code",
                passReqToCallback: false,
                // Required
                responseMode: "query",

                // Required, the reply URL registered in AAD for your app
                redirectUrl: "http://localhost:1880/auth/strategy/callback",

                // Required if we use http for redirectUrl
                allowHttpForRedirectUrl: true,

                // Required if `responseType` is 'code', 'id_token code' or 'code id_token'. 
                // If app key contains '\', replace it with '\\'.
                clientSecret: "[CLIENT_SECRET]",
            },
            verify: function (profile, done) {
                done(null, profile);
            }
        },
        users: opts.users
    };
````
After the sign-in in Azure the user is redirected to `http://localhost:1880/auth/strategy/callback`. Depending on the `responseType`the following parameters are provided to node-red.

| Method        | Callback QueryString                                                        |
|---------------|-----------------------------------------------------------------------------|
| code          | code=[CODE]&state=[STATE]&session_state=[SESSION_STATE] |
| code id_token | code=[CODE]&id_token=[ID_TOKEN]&state=[STATE]&session_state=[SESSION_STATE] |
| id_token code | code=[CODE]&id_token=[ID_TOKEN]&state=[STATE]&session_state=[SESSION_STATE] |
| id_token      | id_token=[ID_TOKEN]&state=[STATE]&session_state=[SESSION_STATE]             |

Does anyone have an idea what is wrong with my setup?

| Software          | Version |
|-------------------|--------:|
| node-red          | 0.17.5  |
| node              |  8.5.0  |
| passport-azure-ad |  3.0.8  |

*Update [17-Sep-2017]: Added verify callback.*

**Comment by knolleary** [comment]
Hi,

I've not used this strategy before and I'm not setup on Azure to trying it out, so I can't try it out myself.

One thing I can see is you've commented out the verify function. Looking at the docs for the OIDCStrategy, it requires a [custom verify function](https://github.com/AzureAD/passport-azure-ad#5111-sample-using-the-oidcstrategy):

```
function(iss, sub, profile, accessToken, refreshToken, done) {
    if (!profile.oid) {
      return done(new Error("No oid found"), null);
    }
    // asynchronous verification, for effect...
    process.nextTick(function () {
      findByOid(profile.oid, function(err, user) {
        if (err) {
          return done(err);
        }
        if (!user) {
          // "Auto-registration"
          users.push(profile);
          return done(null, profile);
        }
        return done(null, user);
      });
    });
  }
```

**Comment by VeitSanner** [comment]
@knolleary, thanks for pointing out that the verify callback was commented out. I did that while looking at the different scenarios. 

I tested again, with simplest of the possible callbacks but without any success. The verify function is never called. I have updated my initial code sample to reflect this.

What I know is that in *node-red* the line in [node-red/red/api/auth/index.js](https://github.com/node-red/node-red/blob/a42e99c4aa19c2aa981558e78d61554f73ae39bf/red/api/auth/index.js#L189) is called.

```Javascript
adminApp.get('/auth/strategy/callback',
    passport.authenticate(strategy.name, {session:false, failureRedirect: '/' }), // this is called during authentication
    function(req, res) {
        var tokens = req.user.tokens;
        delete req.user.tokens;
        // Successful authentication, redirect home.
        res.redirect('/?access_token='+tokens.accessToken);
    }
);
```
And that I get a related audit log entry.

````
17 Sep 12:11:00 - [audit] {"event":"auth.login.fail.oauth","level":98,"timestamp":1505643060581}
````
But I do not see a hint what actually went wrong.

**Comment by knolleary** [comment]
The verify callback you've updated your example to has a signature of:

```
function (profile, done)
```

but the verify function in the docs has a signature of:
```
function(iss, sub, profile, accessToken, refreshToken, done)
```

That said, if your function isn't being called at all, then that suggests its failing somewhere else.

Can you see if https://github.com/node-red/node-red/blob/a42e99c4aa19c2aa981558e78d61554f73ae39bf/red/api/auth/index.js#L168 gets called?

**Comment by VeitSanner** [comment]
I think we are narrowing the problem down.

The verify callback is for *passport-azure-ad* at the wrong position. It must be handed over as a property of *options* and not as a property of *strategy*. (I took that from the [twitter auth extension](https://github.com/node-red/node-red-auth-twitter/blob/8fb5580aeeb066a6e0c458ca6fc278f94949cb3e/lib/index.js#L50). 

After I corrected that, the verify callback is called. But now I have the issue that in completeVerify the user is null, and hence I still run into an authentication issue.

https://github.com/node-red/node-red/blob/a42e99c4aa19c2aa981558e78d61554f73ae39bf/red/api/auth/index.js#L121-L134

**Comment by VeitSanner** [comment]
I did some further debugging and there seems to be an incorrect assumption where the *username* is stored.

https://github.com/node-red/node-red/blob/a42e99c4aa19c2aa981558e78d61554f73ae39bf/red/api/auth/users.js#L26-L32

The code assumes that if username is not a string, there is a property username. But this is not the case for Azure AD. I do have the property *upn* which gives me the *username*.

Is there a place in my code where I can add an additional property *username* with the value from *upn*?

**Comment by knolleary** [comment]
Great - glad to hear you got it working. I thought `username` was part of the standard profile that passport strategies should expose. Will check on that and see if we can make it more obvious.

As you've got it all working, going to close this issue. Thanks!
