### ISSUE TITLE
Full msg and rc in the same port on Exec

### ISSUE THREAD

**Issue by nygma2004** [node-red/node-red#1399]
Hi Guys,

I have a video conversion flow in node red. I am storing the output file in msg.outputfile attribute and passing the full conversion command to the exec node in payload. I noticed that I can see msg.outputfile in the first port of the exec, but not in second and third. I want to do some further processing of the output file based on the return code of the command, but both of this information is not available in the same port.

Can you please consider making them available one way or another?
You can find the discussion on this in the Node Red group: https://mail.google.com/mail/u/0/#inbox/15e872eecfaf1af1

Regards,
Csongor Varga

**Comment by dceejay** [comment]
Seems sensible to be to add something like `msg.rc` to both output 1 (stdout) and/or 2 (stderr) when in exec mode as required, as all the results are available at the same time. It wouldn't impact existing functionality.

I don't think it makes sense to add to spawn mode as the return code is not available until after the command has completed and the stdout (or stderr) emits are separate events...

Will need extra info in docs.
