### ISSUE TITLE
Make link nodes show their names

### ISSUE THREAD

**Issue by codeaholics** [node-red/node-red#1405]
Link nodes should show their names. If a link node doesn't have a name, it should show the names of (some or all of ?) the nodes it is linked to (at least, those which have names).

For example, I have an input link node called "Send exception report to GMail" which links to a change node (to set email content), a rate limiting node and finally a mail output node. There are then several output link nodes which link to this input. At the moment, I have no way of knowing where the links go without clicking on them to see the dotted line. It would be nice if the input link node showed "Send exception report to GMail" (because that is its name), and the output link node showed the same because they don't have their own names, but show the name of the input link node they're linked to.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to discuss feature requests on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack).

This has already been discussed a few times, to no clear conclusion, on the mailing list.

Thanks!

**Comment by codeaholics** [comment]
Sorry, I missed the contribution guidelines. 

Could you point me at one of the previous discussions, please? I'm interested to see what other people's points of view are on what seems to me to be a relatively straightforward improvement!

Thanks!
