### ISSUE TITLE
Inject node "at specific time", time box behaves incorrectly

### ISSUE THREAD

**Issue by MatsKarlsson** [node-red/node-red#1406]
NR 0.17.5 (and previous versions also) recently updated.

- Add a `inject node`
- Edit node, set `Repeat` to `at a specific time`
- Click the up/down arrows on time-text box. 
- Set focus to the textbox press up/down arrow on keyboard.

always subtracts 1h and moves 1 min in the right direction (+ or -) 

How I would like it: up/down arrow (keyboard) moves Hour or Minute depending on where the caret is.
clicking up/down arrows should perhaps add/remove 10min?

**Comment by dceejay** [comment]
which browser ? and hardware ?
Mac seems to struggle with the difference between up arrow and page up.

**Comment by MatsKarlsson** [comment]
@dceejay Tried with: Windows and Linux and browsers: Chrome and Firefox. 
Guessing you would be able to recreate mouse-clicking the up/down arrows problem, even on a Mac.

There are two problems: 1) up and down arrow doesn't behave as expected. 2) clicking up/down arrows doesn't behave as expected.

**Comment by knolleary** [comment]
Fixed in 0.18 branch
