### ISSUE TITLE
http response node - resizing the config view

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red#1408]
Dear,

When the config view of the httpresponse node is being resized in the flow editor, the layout of the text boxes is getting messed up: a row contains two text boxes (one for header name and another for header value) which are sometimes aligned nicely horizontally.  Bot most of the time they are aligned vertically.

Here is a (zipped) movie that illustrates the problem:
[resize_problem_movie.zip](https://github.com/node-red/node-red/files/1326531/resize_problem_movie.zip)

I'm using Chrome version 60.0.3112.113.
Have been looking at the CSS, but unfortunately I don't have enough experience with it to find the root cause.

If you need extra information, don't hesitate to let me know !!!!

Good luck with it !
Bart Butenaers

**Comment by knolleary** [comment]
A single screen shot would be quicker to show what you mean, rather than an entire movie...

**Comment by bartbutenaers** [comment]
Hi Nick,

Here is the picture:
![image](https://user-images.githubusercontent.com/14224149/30773321-d684b844-a06e-11e7-8d87-54d6e215bcbd.png)

I have just fetched the latest version of the **21-httpin.html** file, but result was the same...

**Comment by bartbutenaers** [comment]
Good evening,

When I change the following value from `15` to `30`:

![image](https://user-images.githubusercontent.com/14224149/30776573-12a3d154-a0a9-11e7-96f1-3bc64d794605.png)

Then it seems to work **_a bit better_** : When moving the mouse horizontally (to change the width of the node config view), the textboxes are still being aligned vertically.  But as soon as I release the mouse, the textboxes are nicely horizontally aligned...

**Comment by knolleary** [comment]
Fixed in 0.18 branch
