### ISSUE TITLE
Adding new Twitter credentials fails to add properly using IE11

### ISSUE THREAD

**Issue by thiseldo** [node-red/node-red#141]
I'm trying to add new twitter credentials to one of my feeds and I end up with blank twitter name in the dropdown list of accounts.
I select 'Add new twitter-credentials', click the edit button and follow the authorise app links.
The app gets authorised, on returning to the node red page, the username has not been entered into the dropdown.

If I check the flows json file there is a twitter-credentials element that has no screen name entered.

I am using latest pull from github, i.e. from today. I've tried this a number of times and the result is the same.

However, this worked perfectly on Firefox.

 btw, IE11 is not my normal browser, I was using that as I was already logged into my regular twitter account in another browser and couldnt be bothered to logout and log back in again when setting up the new credentials in Node-Red.

thanks

Andrew

**Comment by knolleary** [comment]
Going to close this as we've had no other complaints against IE11 since this was raised. I'd like to think this has resolved itself...
