### ISSUE TITLE
Change node with set action on payload doesn't work with object.

### ISSUE THREAD

**Issue by fab33** [node-red/node-red#1410]
`[{"id":"d646c40d.7cad2","type":"debug","z":"bbea8466.89e15","name":"","active":true,"console":"false","complete":"true","x":546.5,"y":124.59999084472656,"wires":[]},{"id":"472dad95.9b1164","type":"inject","z":"bbea8466.89e15","name":"","topic":"","payload":"Test","payloadType":"str","repeat":"","crontab":"","once":false,"x":88.5,"y":125,"wires":[["811c8ef1.54ed98"]]},{"id":"811c8ef1.54ed98","type":"change","z":"bbea8466.89e15","name":"","rules":[{"t":"set","p":"payload.payload.value","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":316.5,"y":124.59999084472656,"wires":[["d646c40d.7cad2"]]}]`
When you press inject msg.payload = Test 
You must have msg.payload = Object (with payload.value = Test).
It work ok when using move instead set.

**Comment by hardillb** [comment]
This is probably working as intended, you can't set a field on a string, but only on an object. The move works because it is replacing the whole `msg.payload` with an object rather than just trying to set a field on an existing object.

**Comment by dceejay** [comment]
@hardillb is correct. You can't set a field on an existing string object - you have to replace it - by using move instead.
