### ISSUE TITLE
Join node can not combine complete messages

### ISSUE THREAD

**Issue by HirokiUchikawa** [node-red/node-red#1411]
If the following node properties are set, the join node can not combine complete messages.

Mode：`manual`
Combines each：`complete message`
to create：`an Array` or `a key/value Object`
Send the message: `after a count` or `after a timeout`

Example
![circular](https://user-images.githubusercontent.com/31908137/30906763-c94926cc-a3b3-11e7-9366-89bce7dba02c.png)

In the above, the join node sends a `msg` after 3 messages are received.
`msg.payload` should be an array of these messages, but `msg.payload [2] ` refers to `msg` not third received message.
```
msg.payload[0] ---> first received message
^   payload[1] ---> second received message
|   payload[2] -+  <- circular reference!
|               |
+---------------+
```
When the join node combines `complete message`,in the following code,
'group.msg' is the last received message and 'group.payload' has a reference to the last received message.
https://github.com/node-red/node-red/blob/master/nodes/core/logic/17-split.js#L303
So setting 'group.payload' to a property of 'group.msg', a circular reference occurs.

**Comment by dceejay** [comment]
Thanks, for finding and fixing, will review.
