### ISSUE TITLE
Race condition in TCP Request (TcpGet) node

### ISSUE THREAD

**Issue by codeaholics** [node-red/node-red#1414]
These lines are the root of a more deep-seated problem:

https://github.com/node-red/node-red/blob/d99432bff17b215987f560990c71f415767dce0e/nodes/core/io/31-tcpin.js#L426-L429

Scenario:
- Message A arrives
- No existing connection; create entry in `clients`; store incoming message A
- Make TCP connection and send request for message A
- Message B arrives
- Existing connection; overwrite `clients[...].msg` with message B
- Send request for message B
- Response arrives for request A (server or network was slow, perhaps)
- Response is attached to payload of message B and forwarded; `clients` cache is cleared
- Response for message B arrives, data is dropped because no entry is found in cache

The response for request A has been sent on as the payload for message B; the response for message B has been lost.

**Comment by boneskull** [comment]
Do you have a reproducible example where this occurs?  Seems plausible, at least.

**Comment by codeaholics** [comment]
Any time when a new message arrives while a network request is in-flight.

**Comment by codeaholics** [comment]
Sorry, I misread your reply! Not able to make an example right now, but I imaging if you inject an array of multiple addresses, then split it, then put that into this node, you’ll be able to reproduce quite easily.

**Comment by boneskull** [comment]
okay, thanks.

**Comment by boneskull** [comment]
OK, I can reproduce this, or something like it.

![image](https://user-images.githubusercontent.com/924465/37617714-2f5f2a52-2b71-11e8-987a-4f7cb35f15f9.png)

The echo server handling requests:

```js
const net = require('net');
let count = 0;
const server = net.createServer((c) => {
  // 'connection' listener
  let id = ++count;
  console.error(`client ${count}`)
  c.on('end', () => {
    --count;
    console.error(`client d/c'd`);
  });
  c.setEncoding('utf8');
  c.on('data', data => {
    console.error(`writing ${data} to client ${id}`);
    c.write(data);
  });
});
server.on('error', (err) => {
  throw err;
});

server.listen(9999, () => {
  console.error('server bound');
});
```

(I couldn't get NR's `TcpIn` node to cooperate, but I imagine the echo server can be written in it as well.)

There are a few problems here:

1.  Messages come in to the `TcpGet` node synchronously, and for each message, a new connection is attempted for the same server.  
2.  As noted by @codeaholics, the message is overwritten each time by the next connection created in the call stack.  
3.  Client connections established this manner will be overwritten (maybe even leaking memory / resources) except the last one on the call stack.  This causes each call to write its payload to the last connection; all of which are the last connection's payload.    

I think this can all be solved by:

1.  Implementing a message queue to be flushed when the client is connected, and
2.  Maintaining a "connecting" state flag, and only attempting to connect (not connected) when this flag is false

The code is clear in its intention to reuse connections; it just doesn't happen if messages arrive synchronously (or likely even too quickly).

**Comment by boneskull** [comment]
@knolleary If my solution(s) sound good to you, I can implement and send a PR.

**Comment by dceejay** [comment]
sounds good to me... happy to look at a PR.

**Comment by codeaholics** [comment]
Excellent work @boneskull!!! I was just about to sit down and try and reproduce this. I thought of using an echo server and trying to build that in NR, so I'm glad you dodged that particular bullet. :D

**Comment by codeaholics** [comment]
What's the status on this? I can see @boneskull has made a bunch of commits
(thank you!), but the issue remains open.

**Comment by dceejay** [comment]
well reminded.. - yes - will re-target this to the 0.19 branch.
