### ISSUE TITLE
[security] XSS jquery-ui-dialog 1.10.3 dependency has known vulnerabilities	

### ISSUE THREAD

**Issue by code2nguyen** [node-red/node-red#1416]
Hello, 

Node-Red editor uses JQuery-ui-dialog@1.10.3 has a known, high severity vulnerability allowing XSS attack.

More details here:
https://snyk.io/vuln/npm:jquery-ui:20160721 
https://github.com/jquery/api.jqueryui.com/issues/281 

Should we upgrade to newer versions of JQuery-ui-dialog in order to eliminate this vulerability

**Comment by knolleary** [comment]
Hi,

as per the vulnerability description:

> If you allow user input to be passed through to the closeText property, you may have a Cross-Site Scripting (XSS) vulnerability.

I don't believe we do that anywhere in the code base, so I don't believe we are exposed to this.

We should, of course, keep current with dependencies and will update in the next maintenance release - but I don't think this is an immediate concern.

**Comment by nareshmail** [comment]
have you explained in any demo this xss

**Comment by nareshmail** [comment]
if you have't explain than could you explain in summary

**Comment by dceejay** [comment]
This issue was closed over a year ago. This is a report of a vulnerability against one of the libraries we used. You should look at either the documentation for vulnerability, or the library, to find out the information you need.
