### ISSUE TITLE
Difficult to recieve a json array on the websocket node

### ISSUE THREAD

**Issue by andersea** [node-red/node-red#1420]
If you have the Websocket node in convert JSON to msg mode, you run into trouble if you recieve an array as the root JSON object.

The node send method is designed to split up arrays and send them to different outputs, so when an array is recieved, it gets mangled by the send method because there is only one output port of the node.

It is possible to work around this by outputting recieved messages as text on the output and convert it using the json node.

However, when I run the message through the flow and reply to the message with the websocket end node, the server doesn't recieve the reply. Don't know why. I find the behaviour of these nodes to be somewhat strange.

**Comment by knolleary** [comment]
The mode to send the received data as the full msg object is there as a convenience if you know you are receiving msg objects. If you aren't receiving objects,  don't use that mode - use the msg.payload option and access the data from there.

If anything, we could add a warning/error message if, when in that mode, a non-Object is received.

Or have I misunderstood the issue here?

**Comment by andersea** [comment]
You are correct. I have trouble sending a reply but that is a different issue.

Why are are the server and client nodes the same nodes? Shouldn't they be different if you were to follow the guidelines?

**Comment by knolleary** [comment]
> Why are are the server and client nodes the same nodes? Shouldn't they be different if you were to follow the guidelines?

Do you mean the fact the websocket nodes can be configured to either connect to remote systems or listen for connections? That's a pattern used by the TCP and UDP nodes as well. It's all about striking the right balance between having the right functionality available to the user and not flooding the palette that makes it hard to find.
