### ISSUE TITLE
Ability to disable a node

### ISSUE THREAD

**Issue by chevdor** [node-red/node-red#1422]
Tabs can be disabled.
The same way, it would ne nice being able to disable a single node.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer feature requests/suggestions are raised on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack).

In this instance, this is a feature that has been discussed many times on the mailing list. It is not something we're considering doing.

Thanks!

**Comment by dceejay** [comment]
This has been discussed several times in the, including a few days ago on the slack channel ( https://node-red.slack.com/archives/C03M2TAQ8/p1506593456000322 )

**Comment by chevdor** [comment]
Hi guys, sorry I missed the info.
Would you mind summarising so that a trace remain in Github? I am not on slack and don´t really plan on creating yet-another account. I found some long threads in the mailing list that seems to be 2+ years old.

**Comment by dceejay** [comment]
Most nodes manipulate something on the way through such that the following node then expects that new thing… - just passing through duff data won’t help anyone. For example - if a node has multiple outputs, what would you send to each output ? If you disable an http request node - do you just pass through the url that was asked for ? If you just block and don't pass anything then nothing will continue. There are very few cases where simply disabling a node would have value.

**Comment by chevdor** [comment]
Since you ask :) There is a very similar 'landscape' in GnuRadio. Once a node is disable, it no longer produces any output. 

>  if a node has multiple outputs, what would you send to each output ?
Nothing at all

> If you disable an http request node - do you just pass through the url that was asked for ?
I would pass nothing at all

> If you just block and don't pass anything then nothing will continue
That´s exactly what I would wish for :)

> There are very few cases where simply disabling a node would have value.
I see this differently but surely don´t have your level of experience with node-red yet

Thanks for taking the time to explain. 🤝

**Comment by dceejay** [comment]
Thanks for the thought. Well never say never... but it's not on any planned list so don't hold your breath :-)

**Comment by chevdor** [comment]
I won´t hold my breath then but may be this issue deserves another tag ✋ such as 'Maybe Later'.

**Comment by dceejay** [comment]
That's way too optimistic 8-)
http://dictionary.cambridge.org/dictionary/english/don-t-hold-your-breath

**Comment by chevdor** [comment]
@dceejay I just found an old post where you mention interesting workaround so for the sake of the documentation: #94
