### ISSUE TITLE
Express-session memory leak

### ISSUE THREAD

**Issue by roccomuso** [node-red/node-red#1434]
The default server-side in memory session storage for `express-session` is purposely not designed for a production environment. It will leak memory under most conditions and will be removed in a feature major release.
This is the recommended [Memory Storage](https://www.npmjs.com/package/memorystore).

This can be easily integrated in [auth/index.js#L151](https://github.com/node-red/node-red/blob/master/red/api/auth/index.js#L151):

```javascript
var crypto = require("crypto")
var session = require('express-session')
var MemoryStore = require('memorystore')(session)

adminApp.use(session({
  // As the session is only used across the life-span of an auth
  // hand-shake, we can use a instance specific random string
  secret: crypto.randomBytes(20).toString('hex'),
  resave: false,
  saveUninitialized: false,
  store: new MemoryStore({
    checkPeriod: 86400000 // prune expired entries every 24h
  })
}));
```

**Comment by knolleary** [comment]
Hi, thanks for this. Can you open a PR with the proposed change?

**Comment by roccomuso** [comment]
@knolleary sure, I'll do it right now.

**Comment by knolleary** [comment]
Looking at this in more detail, I see your proposing your own `memorystore` module here; so is that your own recommendation or is there a wider discussion you can point us at about it? A quick search does find other modules that claim to address the same issue.

**Comment by roccomuso** [comment]
There are not other modules listed on the official [express-session](https://github.com/expressjs/session) module documentation, this is the the only "memory session store made for production" as pointed on the doc.

This is part of a wider discussion with the express-session mantainers, [here](https://github.com/expressjs/session/pull/487).

**Comment by knolleary** [comment]
Hi @roccomuso - thanks for the links. Really useful context for this change.

**Comment by knolleary** [comment]
Closing as the associated PR is merged.
