### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by tx4x** [node-red/node-red#1445]
Hi,
is it possible to rename 'node-red' to something else and remove all hints to 'node-red' from the license and all files and then distribute it as part of a proprietary product to a closed group of customers ? My company is just doing that with Node-Red and I am wondering it's legal at all?

thanks,
g

**Comment by knolleary** [comment]
Hi.

The project is licensed under the [Apache v2 License](https://github.com/node-red/node-red/blob/master/LICENSE).

You should ensure you are familiar with, and meet, the conditions it sets out for redistribution of the project - particular in Section 4 of the license.

In summary (but not exhaustive... read the license!)

 - you MUST include the existing, unmodified, LICENSE.
 - you MUST add prominent notices to any files that you change
 - all existing copyright/attribution notices must be retained
