### ISSUE TITLE
NR editor search doesn't find matches in the rules of Change and Switch nodes

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red#1446]
### What are the steps to reproduce?

- Create a Switch or a Change node
- Add some rules  ex: set msg.payload to flow.myvar 
- ctrl+f to search for myvar

### What happens?

No matches found

### What do you expect to happen?

1 match

### Please tell us about your environment:

- [ ] Node-RED version: 0.17.2
- [ ] node.js version: 
- [ ] npm version: 
- [ ] Platform/OS: Windows
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
The search currently only indexes node properties that are String types. The Switch/Change nodes encode their rules into a single property as an Object, so are ignored.

Would need to index all properties and do a broader search.

This would be a good first pull-request for anyone interested in contributing. The function in question is here: https://github.com/node-red/node-red/blob/5b137c457b2c2b5c1c8eb0b3cdb6271eab93f503/editor/js/ui/search.js#L29

**Comment by gokulchandra** [comment]
Has this issue been fixed? If not I would like to take it up.

**Comment by knolleary** [comment]
Hi @gokulchandra - nope, not fixed, so you're welcome to it. 

Just ask if you have any questions - please make sure you target the 0.18 branch with any pull-request you send.

Thanks!

**Comment by gokulchandra** [comment]
Hi @knolleary ,

I did the following but was unable to reproduce the issue: 

1. Created a switch node. 
2. Renamed the the property to **flow.sample**.
3. Pressed Cmd+F to get the search bar
4. On typing "sample" it listed the Switch node. 

Is this the expected behaviour? Am I missing something? 

## Environment
 Node-RED version: Master Branch
 node.js version: 8.9
 npm version: 5.5.1
 Platform/OS: OSX
 Browser: Chrome

**Comment by knolleary** [comment]
The property field is stored as a String, so is correctly indexed.

The issue are the switch rules that can be added - they are stored in a single Object, which doesn't get indexed.

**Comment by gokulchandra** [comment]
@knolleary Thanks for that.

**Comment by gokulchandra** [comment]
#1558 PR to resolve this issue. Please let me know if you have any feedback. Thanks.
