### ISSUE TITLE
Cannot display a number in the debug tab

### ISSUE THREAD

**Issue by HirokiUchikawa** [node-red/node-red#1451]
### What are the steps to reproduce?
step1. Send a buffer as `msg.payload` to a debug node.
step2. Change the buffer format from `row` to `string` in the debug tab.
step3. Send a number as `msg.payload` to the debug node.
![format_error](https://user-images.githubusercontent.com/31908137/31819198-967a5a06-b5d6-11e7-9055-4b155cb767c7.png)

### What happens?

Cannot display the number in the debug tab.

I think this issue is caused by that the number and buffer refer to the same formatting choice.
Formatting choices are stored like key-value pairs in following functions.
https://github.com/node-red/node-red/blob/298e37ec53e8e3dfbcf348f2ea4dce51fc6fddd9/editor/js/ui/utils.js#L173
https://github.com/node-red/node-red/blob/298e37ec53e8e3dfbcf348f2ea4dce51fc6fddd9/editor/js/ui/utils.js#L206
Functions associate formatting choice with `sourceId` and `path`.
```javascript
formattedPaths[sourceId][path] = format;
```

debug node ID is set to `sourceId` and `msg` object property path is set to `path`.
In the above steps, the buffer's and number's formatting choices are associated with the same key.

So after change the buffer format to `string`,the debug tab cannot display the number.
Because the debug tab try to display the number as undefined `string` format.

### What do you expect to happen?

display the number in the debug tab.

I think it would be better to add a key for each type.

In formatBuffer function
```javascript
formattedPaths[sourceId][path]['buffer'] = format;
```
In formatNumber function
```javascript
formattedPaths[sourceId][path]['number'] = format;
```
What do you think about this idea?

### Please tell us about your environment:

- [x] Node-RED version:v0.17.5
- [x] node.js version:v6.11.4
- [x] npm version:v3.10.10
- [x] Platform/OS:Windows7
- [x] Browser:Version 62.0.3202.62 (Official Build) (32-bit) on Windows 7

**Comment by knolleary** [comment]
Hi,

yes, adding a key based on the type of object would help. 👍

**Comment by HirokiUchikawa** [comment]
Hi,
thank you for your reply.
I'll send a pull request.:thumbsup:
