### ISSUE TITLE
Node-Red pallete fails to load due to syntax error in vendor.js

### ISSUE THREAD

**Issue by Shreya7793** [node-red/node-red#1457]
Node-RED version:
node.js version: 5.10.1
npm version: 3.8.3
Platform/OS: Linux AWS instance

Error: 
Uncaught SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at vendor.js:2
    at Function.globalEval (vendor.js:2)
    at text script (vendor.js:5)
    at Pb (vendor.js:5)
    at x (vendor.js:5)
    at b (vendor.js:5)
    at Object.send (vendor.js:5)
    at Function.ajax (vendor.js:5)
    at Function.m._evalUrl (vendor.js:5)
(anonymous) @ vendor.js:2
globalEval @ vendor.js:2
text script @ vendor.js:5
Pb @ vendor.js:5
x @ vendor.js:5
b @ vendor.js:5
send @ vendor.js:5
ajax @ vendor.js:5
m._evalUrl @ vendor.js:5
domManip @ vendor.js:4
append @ vendor.js:4
success @ main.min.js:16
j @ vendor.js:2
fireWith @ vendor.js:2
x @ vendor.js:5
b @ vendor.js:5

Tried with node version v6 as well.

**Comment by knolleary** [comment]
This will be due to one of the 3rd-party nodes you have installed - it has a syntax error in its HTML file.

Have you recently added any new nodes or are you developing your own?

**Comment by Shreya7793** [comment]
Thanks for the quick response. Yes, installed crate,swagger and splitter. Everything was working fine initially. Then suddenly ran into this issue. Simply re-installing Node-Red was not helping. But deleting the '.node-red' folder which contains the settings.js and starting afresh worked.

**Comment by knolleary** [comment]
Great - glad you got it working.

**Comment by syedlnt** [comment]
same issue  for me, PLease let me know what need to do

i am using Node-red on my IOT2040 Gateway module
