### ISSUE TITLE
[CSV Core node] Code doesn't support spaces in column names

### ISSUE THREAD

**Issue by herriejr** [node-red/node-red#1460]
I was processing some data that needed to be exported to CSV format. The column names (header) I needed to use contain spaces. This gave an error when using the CSV core node.

After digging through the code, I found that the error happened at this line of the code:
https://github.com/node-red/node-red/blob/f57a0d4d6b3cea2fa782cf8fe2d12a887869c79d/nodes/core/parsers/70-CSV.js#L104

I changed this line of code to 
var p = RED.util.ensureString(eval("msg.payload[s]['"+node.template[t]+"']"));

and this works for me. Maybe this can be changed in the future versions of this node.

Kind regards.

**Comment by dceejay** [comment]
looks sensible to me.

**Comment by hardillb** [comment]
Just make sure you can't run arbitrary code entered as a header with that `eval`

**Comment by knolleary** [comment]
That eval really ought to be removed and replaced with `RED.util.getMessageProperty` - https://github.com/node-red/node-red/blob/f57a0d4d6b3cea2fa782cf8fe2d12a887869c79d/red/runtime/util.js#L235

Although, istr having this conversation before, so there may be a reason for it not already doing that...

**Comment by dceejay** [comment]
just time and testing I think. So yes - time to move over.
