### ISSUE TITLE
Removing modules from config - not working

### ISSUE THREAD

**Issue by rudacs** [node-red/node-red#1464]
Add a node (npm)
Launch app
Remove node (npm)
Launch app

the message appears saying that it has been removed from the config, but it is not removed

Start the app again

The same message appears

- Node-RED version: 0.17.5
- node.js version: 7.5.0
- npm version: 4.1.2
- Platform/OS: OSX (Darwin 16.6.0 x64 LE)
- Browser: Safari 10.12.5

**Comment by knolleary** [comment]
Hi, please can you provide more details to help us understand the issue.

> the message appears saying that it has been removed from the config, but it is not removed

Can you clarify what you mean by 'it is not removed'? Do you mean the node still appears in the palette?

There is a known issue if you are developing your own node and add/remove node types from within the node module that can cause the 'removed' message to appear each time. But if you are just installing/removing published node modules it should not happen.

**Comment by knolleary** [comment]
Hi, any update on this? Not much we can do with this issue without some more information. Thanks!

**Comment by knolleary** [comment]
Going to close this due to lack of information. Please reopen if you can provide the requested info.
