### ISSUE TITLE
UDP:out error requires node-red restart after deployment

### ISSUE THREAD

**Issue by gusev-genotek** [node-red/node-red#1470]
With a UDP sender node, I have to restart node-red after each redeployment, because of the error thrown when I hit Deploy button (after that UDP sender does not work). I am using it with a preceding OSC node (node-red-contrib-osc), but the error is thrown regardless of OSC. I have confirmed it both on ubuntu and OSX. The flow is attached.

The error:

```
30 Oct 10:54:49 - [info] Node-RED version: v0.17.5
30 Oct 10:54:49 - [info] Node.js  version: v7.10.1
30 Oct 10:54:49 - [info] Linux 4.4.0-72-generic x64 LE
30 Oct 10:54:50 - [info] Loading palette nodes
30 Oct 10:54:50 - [warn] ------------------------------------------------------
30 Oct 10:54:50 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
30 Oct 10:54:50 - [warn] ------------------------------------------------------
30 Oct 10:54:50 - [info] Settings file  : /home/vgusev/.node-red/settings.js
30 Oct 10:54:50 - [info] User directory : /home/vgusev/.node-red
30 Oct 10:54:50 - [info] Flows file     : /home/vgusev/.node-red/flows_dellgv.json
30 Oct 10:54:50 - [info] Server now running at http://127.0.0.1:1880/
30 Oct 10:54:50 - [info] Starting flows
30 Oct 10:54:50 - [info] Started flows
30 Oct 10:54:50 - [info] [udp out:65bd6199.7fee1] udp broadcast ready: 3000 -> 255.255.255.255:3000
30 Oct 10:54:50 - [info] [udp in:e00d1277.83cb9] udp listener at 0.0.0.0:3001
30 Oct 10:55:29 - [info] Stopping flows
30 Oct 10:55:29 - [info] [udp out:65bd6199.7fee1] udp output stopped
30 Oct 10:55:29 - [info] [udp in:e00d1277.83cb9] udp listener stopped
30 Oct 10:55:29 - [info] Stopped flows
30 Oct 10:55:29 - [info] Starting flows
**30 Oct 10:55:29 - [error] [udp out:65bd6199.7fee1] Error: Not running**
30 Oct 10:55:29 - [info] Started flows
30 Oct 10:55:29 - [info] [udp in:e00d1277.83cb9] udp listener at 0.0.0.0:3001
```
[flows_dellgv.json.zip](https://github.com/node-red/node-red/files/1426385/flows_dellgv.json.zip)

**Comment by echtelerp** [comment]
I have some similar issue: 
When I change the Port inside a UPD node send or recieve, I also have to reboot my pi. After the reboot the UDP receiver node can receive again.

**Comment by dceejay** [comment]
Should only need to stop / restart Node-RED rather than reboot... but yeah tis a bug.

**Comment by pbawesome** [comment]
I'm still having this issue in v 3.1.10

**Comment by hardillb** [comment]
@pbawesome latest version of 3.1.x is 3.1.14

If you can reproduce the problem with 3.1.14 (or better yet on 4.0.5) then please open a new issue with an example flow and details about you triggered it.

**Comment by pbawesome** [comment]
I don't think I can use 3.1.14 (I'm running inside venus OS (victron))

Here is some code you can import to make this fail.
I'm simply sending 2 digits on a UDP port to a relay module.
The relay module is connected, port is open.

Restarting node red fixes the issue.

`[
    {
        "id": "e5982b22c1803bf6",
        "type": "function",
        "z": "156617d11cfa6074",
        "g": "7a00a7e2a1d6b0cd",
        "name": "Home Starlink On",
        "func": "\n// Relay state 11 is on\n// Relay state 21 is off\n\nvar home = global.get(\"home\")\nvar internet = global.get(\"internet\")\n\n// I am home so turn on Starlink\nif( home == 1){\n    msg.payload = 11\n}\n\n// // T-Mobile isn't giving internet so we need to turn on starlink\n// else if( internet == 0 ){\n//     msg.payload = 1\n// }\n\n// I am not home so turn off Starlink\nelse{\n    msg.payload = 21\n}\n\nif (msg.payload == 21){\n    node.status({fill: 'red', shape: 'dot', text:`home:${home} internet:${internet} Starlink:${msg.payload}`})\n\n}\nif (msg.payload == 11){\n    node.status({fill: 'green', shape: 'dot', text:`home:${home} internet:${internet} Starlink:${msg.payload}`})\n}\n\n// node.warn(`home:${home}, internet:${internet}, msg.payload=${msg.payload}`)\nreturn msg;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 370,
        "y": 120,
        "wires": [
            [
                "acfd3944f7a69414"
            ]
        ]
    },
    {
        "id": "601ecfa77a88f207",
        "type": "inject",
        "z": "156617d11cfa6074",
        "g": "7a00a7e2a1d6b0cd",
        "name": "5min Starlink",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "5",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 160,
        "y": 120,
        "wires": [
            [
                "e5982b22c1803bf6"
            ]
        ]
    },
    {
        "id": "479172e8410a1fd5",
        "type": "function",
        "z": "156617d11cfa6074",
        "g": "7a00a7e2a1d6b0cd",
        "name": "Home Camera Off",
        "func": "\n// Relay state 12 is on\n// Relay state 22 is off\n\nhome = global.get(\"home\")\n\n// I am home so turn off Cameras\nif( home == 1){\n    msg.payload = 22\n}\n// I am not home so turn on Cameras\nelse{\n    msg.payload = 12\n}\n\n\nif (msg.payload == 22){\n    node.status({fill: 'red', shape: 'dot', text:`home:${home} nvr:${msg.payload}`})\n\n}\nif (msg.payload == 12){\n    node.status({fill: 'green', shape: 'dot', text:`home:${home} nvr:${msg.payload}`})\n}\n\nreturn msg;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 370,
        "y": 180,
        "wires": [
            [
                "c2d7f80332859a37"
            ]
        ]
    },
    {
        "id": "e8834f6b99d23c78",
        "type": "inject",
        "z": "156617d11cfa6074",
        "g": "7a00a7e2a1d6b0cd",
        "name": "5min NVR",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "5",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 170,
        "y": 180,
        "wires": [
            [
                "479172e8410a1fd5"
            ]
        ]
    },
    {
        "id": "acfd3944f7a69414",
        "type": "udp out",
        "z": "156617d11cfa6074",
        "g": "7a00a7e2a1d6b0cd",
        "name": "Starlink Relay",
        "addr": "192.168.50.103",
        "iface": "",
        "port": "60001",
        "ipv": "udp4",
        "outport": "",
        "base64": false,
        "multicast": "false",
        "x": 600,
        "y": 120,
        "wires": []
    },
    {
        "id": "c2d7f80332859a37",
        "type": "udp out",
        "z": "156617d11cfa6074",
        "g": "7a00a7e2a1d6b0cd",
        "name": "NVR Relay",
        "addr": "192.168.50.103",
        "iface": "",
        "port": "60001",
        "outport": "",
        "base64": false,
        "multicast": "false",
        "x": 590,
        "y": 180,
        "wires": []
    }
]`

**Comment by hardillb** [comment]
@pbawesome I have a potential work around for you to try.

In the UDP-out node, set a local bind port (rather than let NR pick a random one)

**Comment by dceejay** [comment]
The first seems to be configured like this
<img width="433" alt="Screenshot 2024-12-10 at 18 13 28" src="https://github.com/user-attachments/assets/ee034542-7829-4879-9ba9-57ad8db86807">

and the second
<img width="453" alt="Screenshot 2024-12-10 at 18 13 37" src="https://github.com/user-attachments/assets/0b7cd994-69dc-415a-a374-8055cf83b327">

So the second seems to have ipv4 not set...  but otherwise they are identical ? so why not just use one node and wire both flows to it ?
