### ISSUE TITLE
"TypeError: this is not a typed array." with a simple split node

### ISSUE THREAD

**Issue by devnewton** [node-red/node-red#1472]
How to reproduce:

- using node-red 0.17.5 under linux (Ubuntu 16.04).
- create a flow, put a split node.
- click deploy button.

**Comment by hardillb** [comment]
We are going to need more information than that.

What exactly is in the flow with the split node?

An empty flow with a split node works just fine

**Comment by devnewton** [comment]
Here is the flow and the error:

![image](https://user-images.githubusercontent.com/1859457/32334442-bce18494-bfea-11e7-8882-5634e07ee5e6.png)

**Comment by knolleary** [comment]
What version of node.js are you using?

**Comment by knolleary** [comment]
You need at least 4.6 - but should really get the latest 4.8 with all the recent security fixes.

**Comment by sebastienpattyn93** [comment]
I had the same issue with version 4.2.6 . upgrading to the latest LTS version of NodeJS fixed the issue for me.

**Comment by knolleary** [comment]
@devnewton I'm closing this issue as its due to the old version of Node you were using.
