### ISSUE TITLE
Delay can flood the status messages to the browser

### ISSUE THREAD

**Issue by btsimonh** [node-red/node-red#1473]
When sending the Delay module 150 messages per second (configured for per-topic restrict messages to once per second), the browser CPU usage hit the max (80% on i7). 

Delay could be 'fixed' (and probably should), but the 'final' solution should probably be to only send status at a specified interval, so that new, and contrib, modules can't abuse the link.
The efficiency of updating status on modules in the browser could also be examined...

**Comment by dceejay** [comment]
Which mode are you in ? and which version of Node-RED are you running ?
I though this was fixed for rate limit mode back in 18615640e0de378c6d4993a66c6d8bb71f8aa70f

**Comment by dceejay** [comment]
Ah- just seen your mail on the mailing list re a more general solution...

**Comment by btsimonh** [comment]
@dceejay - the admin panel reports 0.17.5 - it's a std install on RPi (not one of my specials :) ).  Looks like that commit *is* in 0.17.5.
I've done some more testing.  The flow below uses ~25% of my i7 (not sure what my other flow was doing to get to 80%!).  If you change the Delay node from 'For each message topic' to 'All messages', then CPU used by Chrome drops significantly (close to zero?).
(I only guessed at 'status update' as I hit pause in chrome to see what it was doing with all it's time, and then traced on to something I recognised).


`[{"id":"ab5e9758.cd6398","type":"inject","z":"327e5cd9.d2d764","name":"","topic":"","payload":"","payloadType":"date","repeat":"0.040","crontab":"","once":false,"x":150,"y":200,"wires":[["83252fce.1e7a1"]]},{"id":"9b426965.c28a58","type":"delay","z":"327e5cd9.d2d764","name":"","pauseType":"timed","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":630,"y":160,"wires":[["610177f8.879458"]]},{"id":"58b8098.f8c15f8","type":"function","z":"327e5cd9.d2d764","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":460,"y":160,"wires":[["9b426965.c28a58"]]},{"id":"83252fce.1e7a1","type":"function","z":"327e5cd9.d2d764","name":"split","func":"var newmsg1 = {topic:'1', payload:msg.payload}; \nnode.send([newmsg1, null, null]);\nnode.send([newmsg1, null, null]);\nnode.send([newmsg1, null, null]);\nvar newmsg2 = {topic:'2', payload:msg.payload}; \nnode.send([null, newmsg2, null]);\nnode.send([null, newmsg2, null]);\nnode.send([null, newmsg2, null]);\nvar newmsg3 = {topic:'3', payload:msg.payload}; \nnode.send([null, null, newmsg3]);\nnode.send([null, null, newmsg3]);\nnode.send([null, null, newmsg3]);\n","outputs":"3","noerr":0,"x":300,"y":180,"wires":[["58b8098.f8c15f8"],["58b8098.f8c15f8"],["58b8098.f8c15f8"]]},{"id":"610177f8.879458","type":"debug","z":"327e5cd9.d2d764","name":"","active":true,"console":"false","complete":"false","x":620,"y":280,"wires":[]}]`

**Comment by knolleary** [comment]
@dceejay does the comms batching added by #1499 help here?

**Comment by dceejay** [comment]
Should do - will re-test tomorrow

**Comment by dceejay** [comment]
Yes seems much better

**Comment by knolleary** [comment]
Closing as resolved on 0.18
