### ISSUE TITLE
registerType does not allow async

### ISSUE THREAD

**Issue by cloudhack** [node-red/node-red#1482]
The following will fail

```
    RED.nodes.registerType("test in", async function (n) {
        RED.nodes.createNode(this, n);
        this.name = n.name;
        var node = this;

        this.on('input', function (msg) {
            var me = this;
            try {
                node.send(msg);
            } catch (err) {
                node.error(err.message);
            }
        });

    });

```
fails with

> 11 Nov 11:45:41 - [info] Node-RED version: v0.17.5
11 Nov 11:45:41 - [info] Node.js  version: v8.8.1
11 Nov 11:45:41 - [info] Linux 4.13.0-16-generic x64 LE
11 Nov 11:45:41 - [info] Loading palette nodes
11 Nov 11:45:43 - [warn] ------------------------------------------------------
11 Nov 11:45:43 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
11 Nov 11:45:43 - [warn] [test] TypeError: Cannot convert undefined or null to object (line:6)
11 Nov 11:45:43 - [warn] ------------------------------------------------------
11 Nov 11:45:43 - [info] Waiting for missing types to be registered:
11 Nov 11:45:43 - [info]  - test in

But if i rewrite it, like this, it does work, but is abit ugly 

```
    RED.nodes.registerType("test in", function (n) {
        const realfunc = async function async(n) {
            RED.nodes.createNode(this, n);
            this.name = n.name;
            var node = this;
    
            this.on('input', function (msg) {
                var me = this;
                try {
                    node.send(msg);
                } catch (err) {
                    node.error(err.message);
                }
            });
        }
        realfunc.apply(this, [n]);
    });

```

- Node-RED version: v0.17.5
- node.js version: v8.8.1
- npm version: 5.4.2
- Platform/OS: Linux 4.13.0-16-generic x64 LE
- Browser: Chrome

**Comment by knolleary** [comment]
Correct, the API does not support async/await.

**Comment by knolleary** [comment]
In fact, there is no reason for this particular api to by asynchronous. Your example code does nothing to require it to be async.

Do you have a use case for it to be async?

**Comment by cloudhack** [comment]
The above code, was just an example.

i don't NEED it per se ... 
But in many of my nodes i do some async initialization
instead of doing ( Phydo code again, i have a lot more nesting, then's  )

```
dbprovider.init().then((db)=>{
    db.query("_type eq 'instance'").then((items) => {
       // do something
    }, err => { return handleerror(node, err); });
}, err => { return handleerror(node, err); });

```
it would be nice to just do

```
try {
    var db = await dbprovider.init();
    var items = db.query("_type eq 'instance'");
   // do something
} catch (err) {
  handleerror(node, err);
}


```

**Comment by knolleary** [comment]
Sorry, bit slow this morning. This is not to do with `registerType` - that api is just registering the function the runtime uses to create a new instance of a given node.

The issue here is you want to be able to asynchronously complete the creation of a node.

The problem is the function you pass in is a class constructor function - it is invoked with the code:

    var newNode = new YourFunctionHere(config);

And, after a quick bit of research, its impossible to make a class constructor function support async/await directly - https://stackoverflow.com/questions/43431550/async-await-class-constructor

So you'll need to work around this within your own code.

**Comment by cloudhack** [comment]
Ahhh, makes sense .... 
Closing ticket

**Comment by GrimbiXcode** [comment]
Wouldn't it be possible to call an asynchronous factory function?
Then the runtime could check if a function is asynchronous or not and call the constructor as before or call the factory function asynchronously.
