### ISSUE TITLE
Can't load flow editor in Chrome (Aw,Snap!)

### ISSUE THREAD

**Issue by gxvigo** [node-red/node-red#1484]
Hi There,

I have installed locally on my mac latest version of node-red with npm.
When I try to open the flow editor (localhost:1880) the top bar shows up for few seconds than the browser returns the error:
Aw, Snap!
Something went wrong while displaying this web page.
Can't see any error in Terminal, can't see any error in Chrome debug or network as devtools disconnect.
If I open the same page in Firefox, it just works fine.
I tried to completely wipe out node-red and reinstall but nothing changed.

Really puzzled by the situation.

Cheers.

- [ ] Node-RED version: v0.17.5
- [ ] node.js version: v6.10.3
- [ ] npm version: 3.10.10
- [ ] Platform/OS: Mac Sierra 10.12.6
- [ ] Browser: Chrome

**Comment by hardillb** [comment]
What do the Node-RED logs show (the output on the console where you ran `node red`)?

**Comment by knolleary** [comment]
Have you installed any extra nodes?

Do you have an chrome browser extensions installed? If so, can you try disabling them?

**Comment by gxvigo** [comment]
giovanni .npm $ node-red
19 Nov 00:22:25 - [info] 

Welcome to Node-RED
===================

19 Nov 00:22:25 - [info] Node-RED version: v0.17.5
19 Nov 00:22:25 - [info] Node.js  version: v6.10.3
19 Nov 00:22:25 - [info] Darwin 16.7.0 x64 LE
19 Nov 00:22:25 - [info] Loading palette nodes
19 Nov 00:22:26 - [warn] ------------------------------------------------------
19 Nov 00:22:26 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
19 Nov 00:22:26 - [warn] ------------------------------------------------------
19 Nov 00:22:26 - [info] Settings file  : /Users/giovanni/.node-red/settings.js
19 Nov 00:22:26 - [info] User directory : /Users/giovanni/.node-red
19 Nov 00:22:26 - [info] Flows file     : /Users/giovanni/.node-red/flows_giovannis-MacBook-Pro.local.json
19 Nov 00:22:26 - [info] Creating new flow file
19 Nov 00:22:26 - [info] Starting flows
19 Nov 00:22:26 - [info] Started flows
19 Nov 00:22:26 - [info] Server now running at http://127.0.0.1:1880/


Vanilla installation, nothing on top of it (after uninstall and delete all node-red files/folders in my machine). I tried to disable all extensions, but no luck.

**Comment by gxvigo** [comment]
![image](https://user-images.githubusercontent.com/11827712/32979753-209d93e2-ccc0-11e7-975c-95c5d23f474d.png)

**Comment by knolleary** [comment]
Hi - is this still an issue? Not had any other reports of it and I'm slightly at a loss to suggest what's going on.

**Comment by mzsolnay** [comment]
Hi !

Having similar issue this morning. Note red editor not opening in chrome.
Restarted raspberry.
Dashboard in browser was loaded, but not the editor !
stopped node-red, renamed my flows file, started node-red (a new empty flow file was created
dashboard in browser loaded (as empty of course) but still editor is not loading ...
Than I got an idea and tried with internet explorer instead of chrome
node-red editor opened with user/pass auth screen as normal !
(...strangely some of my palettes showed as missing, as if they were not yet installed ... but they are)
![missing or not](https://user-images.githubusercontent.com/7197310/88883286-3c4c7f00-d234-11ea-8e9f-486464a0bda7.JPG)

stopped node red, deleted the new flow file, renamed my old one started node red
Editor with all my original flows opened in IE, Dashboard also, but still no response in chrome
Dasboard in Chrome opening, but not the editor
deleted the saved password for the editor page - nothing
disabled all chrome plugins & extensions - nothing

**Comment by mzsolnay** [comment]
UPDATE !

Editor in Chrome private window opens ! But still not in "normal" window.

**Comment by mzsolnay** [comment]
UPDATE !

Chrome cache deleted, Now it works again.
