### ISSUE TITLE
Inject node by hours not working

### ISSUE THREAD

**Issue by NovaGL** [node-red/node-red#1485]
When using the inject node if you use the hours field it is ignored and data is send every second.

Way to test. 
Select minutes choose 60.  (Works as desired)
Select hours choose 1 (flow is sent every second)

**Comment by dceejay** [comment]
I'm not seeing this error ?
Any way to confirm ? example flow ?
thanks

**Comment by NovaGL** [comment]
What version of node-red and node.js are you using I reported this first on the Google group and others could reproduce it that's why posted here.

**Comment by dceejay** [comment]
yeah - I'm working on 0.18 branch for next release (which is why I'm trying to fix it)
More to the point which version are you on where it doesn't work ?

**Comment by NovaGL** [comment]
I will try when I get home as the x64 version of node 0.17.5 with node.js 6.10.1 works on Windows but the 0.17.5 version on Raspbian does not work. Will confirm node.js version when I get home

**Comment by NovaGL** [comment]
Here is what I am running and have the issues
Raspbian GNU/Linux 8 (jessie)
Node-Red v0.17.5
Node.JS v6.11.0

Create inject node, set repeat interval to hours and set the time as 59940.
Link to debug node.

 I will try that again on Windows as 1 hr works but that value doesn't.
The reason is I want something to only occur every few days or once a month.

**Comment by dceejay** [comment]
Ah right - ok yes you are overflowing the timer...

https://stackoverflow.com/questions/16314750/settimeout-fires-immediately-if-the-delay-more-than-2147483648-milliseconds

**Comment by NovaGL** [comment]
The strange thing is it used to work. I need something that can inject at a long interval otherwise I need to do some formulas to calculate   when the timer was last run and only accept if greater than a month.

**Comment by dceejay** [comment]
well - it can't have worked if you used the interval option as it has always been like that. Max seems to be about 24 days.

Meanwhile there are other more suitable nodes such as node-red-node-timeswitch or bigtimer that are possibly better suited for long term timers

**Comment by NovaGL** [comment]
Ok will look. I didn't set that value. I tried to do 7 days and on the old version it worked but on the new node-red it just changed the value inside the inject node

**Comment by dceejay** [comment]
7 days = 168 hours - seems to work just fine.

**Comment by NovaGL** [comment]
I must have been doing longer then. Is there anyway to improve the functionality of it. Or is this a won't fix?

**Comment by dceejay** [comment]
looking at it - but probably not. Setting very long timers in this way is very susceptible to power outages/ reboots/ redeploys etc... as they would all rest the timer... which could mean the event never fires. 
What we may well do is flag this more obviously to warn the user.

**Comment by NovaGL** [comment]
That's fine if there is some way to warn or limit input that would be good. Or make big timer included

**Comment by dceejay** [comment]
Yes will do. 
There are plenty of other scheduler nodes to choose from - see http://flows.nodered.org - so we won't pick one.

**Comment by knolleary** [comment]
Fix on 0.18 branch
