### ISSUE TITLE
Admin HTTP API - POST /flow and flow ID

### ISSUE THREAD

**Issue by elbriga** [node-red/node-red#1494]
I'm integrationg node-red on my project as a diagram/flow editor, using the admin API for this.

On the docs it says:
The runtime will assign a new id for the flow. If the provided flow configuration object includes an id field it will be replaced and the z property of all nodes updated to match.

It's not clear to me if the "id" that I've provided on my POST will be used instead of generating a new ID for the flow.
That is what happens, it will discard the "id" that i've sended and generate a new one. Is this what the docs are saying?
Can I add a new flow with a defined "id" instead of getting a new one?

**Comment by knolleary** [comment]
Hi, for general questions, please consider using the mailing list or slack team as described by the issue template you were presented whilst opening this issue.

The docs describe the behaviour; any provided id will be ignored and a new one generated. There is no mechanism to use this api and have the provided flow id used.

There are a few things I don't like about the `/flow` api - this is just one of them. But it is what the api does today.

**Comment by elbriga** [comment]
OK, thanks, sorry for the wrong place
