### ISSUE TITLE
UDP Node hex Input gets passed through in wrong format

### ISSUE THREAD

**Issue by echtelerp** [node-red/node-red#1501]
If I try to send a HEX string with the UDP node, it changes the output to something different. this should not be done or be adjustable, to support HEX stings, used in Industrial Automation Projects.

**Comment by dceejay** [comment]
Do you have an example ? Are you sending a buffer ? Or a string ? A string will be treated as utf8

**Comment by echtelerp** [comment]
Hi Dceejay, Thanks for your fast reply: 
I try to connect to a Balluff IO-Link Master, via UDP. 
To do so I have to send a HEX string: "05 00 02 1A 03" 
when I send the Sting it get's decoded and transferred in a different type. I guess in some Utif 8 or so. 
but it should be transferred the way I send it. 
I figured that out via Wireshark: see the attached images. 
To set up my test system, I installed two Pi's, to see the UDP massages, incl. Tshark, and used Wireshark on my Mac. 

also another issue, related to the UDP node: I have to reboot, to set the Bound Port of the sender Node correctly. otherwise it will us a random Port. Also seen in the Tshark log. 

![wireshark](https://user-images.githubusercontent.com/19430312/33568738-c2397f36-d927-11e7-8db9-74725b18e189.png)

![pi 61](https://user-images.githubusercontent.com/19430312/33568827-0cadf5ba-d928-11e7-9ad5-89cc7065efd1.png)

![pi ip 30](https://user-images.githubusercontent.com/19430312/33568835-0f60b2e8-d928-11e7-8002-dd35bcf0b86e.png)

[Flow IP30.txt](https://github.com/node-red/node-red/files/1528308/Flow.IP30.txt)
[Flow61.txt](https://github.com/node-red/node-red/files/1528309/Flow61.txt)

**Comment by hardillb** [comment]
Please limit issues to one problem at a time, you have already mentioned the other issue in the comment on that issue.

The UDP node is doing the right thing, you gave it a string so it sent that string.

What you calling a hex string is just a representation of a raw byte stream to send. If you want to send a stream of bytes then you need to create a Buffer object with those bytes and send it.

You can create the Buffer in a function node before the output node. You can do that as follows:

`msg.payload = new Buffer("05 00 02 1A 03","hex");`

**Comment by echtelerp** [comment]
Hi Hardillb, 
Thanks for the reply. As I just started with JS, my skills are quite limited. 
But, this is only a Workaround. 
It should still be possible to send HEX Strings without the need of manipulating them. Since there are a lot of Automation devices out there working with HEX Stings. :-) 
maybe an enhancement of the node to set the input type could be easily implemented?

**Comment by dceejay** [comment]
Well you can set an inject like this to do it - 
![image](https://user-images.githubusercontent.com/5375409/33570814-fbf7bce4-d925-11e7-8d8f-2c55ed283e4d.png)

**Comment by echtelerp** [comment]
The inject is just a quick Sample. For example a more realistic: 
I would let someone type the Sting into the NodeRed Dashboard... the typed in String is then transferred via UDP to the master. of course this can be done with the "hack"  :-) there are a lot more use cases in the future. :-)

**Comment by dceejay** [comment]
it's not  hack - that is the way you need to convert hex strings to hex in javascript
(actually with latest versions of node.js (6.x onwards) it should be

    msg.payload = Buffer.from("0500021a03", "hex");

or as a function (between your UI input and the udp node

    msg.payload = Buffer.from(msg.payload, "hex");

**Comment by echtelerp** [comment]
Perfect. As I Already mentioned, I'm still at the beginning. :-)
You made my day. As a noob in JS, I can go to my developers tomorrow and jell at them, why a economics-engineer finds the solution other then them :-) 
great thanks for that :-)

**Comment by dceejay** [comment]
magic - welcome aboard. Go get em.

PS - in general we prefer how-to type questions via the google group mailing list or slack channel so everyone can help.

**Comment by echtelerp** [comment]
I honestly thought this was a Issue, since my developers spend already a few hours on this. just talked to them this afternoon and they said, it is not possible since the nodeRed UDP node adds some values where they should not be. :-)
now I have a answer and they have to pay me a PIZZA...

**Comment by dceejay** [comment]
save us a slice - we only charge 12.5% ;-)

**Comment by echtelerp** [comment]
one last question about the Node: can I set the source port (bind to local Port) also via msg. ... 
like the Ip and destination port? 
some sort like I did here?

msg.ip = '192.168.2.61';
msg.port = '1999';
msg.payload = Buffer.from('0500021A02',"hex");

return msg;

**Comment by dceejay** [comment]
Don't think so - if you are binding it you set it during config and it binds to that.

**Comment by echtelerp** [comment]
would be also a nice feature, since I only can use one UDP sender node at a time, to set the binding Port my msg. 
Maybe in the future :-)

**Comment by dceejay** [comment]
why not have two nodes ?

**Comment by echtelerp** [comment]
i Read somewhere that this is not possible? Haven’t tried it jet. But I will soon. 
To the other problem where I need to restart node red (in my case sudo reboot), when I change the ports so they will work, is another issue open. I will try that out tomorrow, to reproduce the problem, and post it under the other issue.

**Comment by dceejay** [comment]
you can have two nodes as long as they are on different ports :-)
(and yes - don't mix issues - thanks)
