### ISSUE TITLE
Support for classes when assigning storageModule

### ISSUE THREAD

**Issue by cloudhack** [node-red/node-red#1507]
When loading a storage module, created as an class hasOwnProperty returns false for functions ( but not properties ) there by making storageModuleInterface report settingsAvailable and sessionsAvailable equal false ( in storageModuleInterface.init )
https://github.com/node-red/node-red/blob/master/red/runtime/storage/index.js

By changing the code to below it will work for classes too
```
settingsAvailable = (typeof storageModule.getSettings === "function") && (typeof storageModule.saveSettings === "function")
sessionsAvailable = (typeof storageModule.getSessions === "function") && (typeof storageModule.saveSessions === "function")

```

As an work around to get a storage module work right now, rename the 4 functions and creating 4 properties with the function name, then setting them in the constructor 

```
    getSettings: Function = null;
    saveSettings: Function = null;
    getSessions: Function = null;
    saveSessions: Function = null;
    constructor() {
        this.getSettings = this._getSettings;
        this.saveSettings = this._saveSettings;
        this.getSessions = this._getSessions;
        this.saveSessions = this._saveSessions;
    }

```

**Comment by knolleary** [comment]
The storage API expects an Object not a Class. So I'm not sure what to do with this issue. If you are proposing the api be extended to support Classes then please propose what is needed to do that.

**Comment by cloudhack** [comment]
Updated text to be a suggestion, but it won't let me add the "enhancement" label

**Comment by knolleary** [comment]
To be clear, this isn't an issue. You want to use the API in a way that it wasn't designed for. So a discussion needs to be had around why this is needed and what the benefits are.

**Comment by cloudhack** [comment]
Ok ... Closing then
