### ISSUE TITLE
Certain key combo causes all wires to be gathered into one giant mesh - reproducible

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red#1517]
A certian combination of key and mouse presses causes all wires to be gathered into one large orange group of wires removing existing wires between nodes. 

### What are the steps to reproduce?
1) hold CTRL and LEFT click and you will see this:
![1-ctrl-left-mouse-click](https://user-images.githubusercontent.com/11473405/33859931-4943bcfe-dea4-11e7-979c-a06cb5e0f27d.jpg)

2) click in the search area
![2-click-in-search](https://user-images.githubusercontent.com/11473405/33859947-610699ba-dea4-11e7-9526-cf2bcfb1930d.jpg)
and the cut/copy/paste window will go away
![3-moue-to-blank](https://user-images.githubusercontent.com/11473405/33859963-76e8eada-dea4-11e7-89d4-77fa27183c57.jpg)

3) move the mouse to a blank spot on the screen:
![4-move-mouse-outside](https://user-images.githubusercontent.com/11473405/33859981-88236f8c-dea4-11e7-8cf1-45841eb86747.jpg)

4) press the shift key and you will see:
![5-press-shift-key](https://user-images.githubusercontent.com/11473405/33860005-a2d2c8fa-dea4-11e7-8643-5ea4450857da.jpg)

### What happens?
If you deploy at this time, ALL wires on ALL tabs will be gone. If however you just refresh the screen, the issue is cleared up.

### What do you expect to happen?
Not what happens

### Please tell us about your environment:

- [ ] Node-RED version: 0.17.5
- [ ] node.js version: 6.11.0
- [ ] npm version: 3.10.10
- [ ] Platform/OS: OSX 10.12.6, Win 10 
- [ ] Browser: Safari, FireFox, Chrome

**Comment by knolleary** [comment]
Fixed in 0.18 branch
