### ISSUE TITLE
mqtt publish null values stopped working

### ISSUE THREAD

**Issue by quazzie** [node-red/node-red#1521]
### What are the steps to reproduce?
publish null with mqtt to a topic

### What happens?
publishes the string "null"

### What do you expect to happen?
publish null value (clear)

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version: 0.17.5:
- [ ] npm version:
- [ ] Platform/OS: linux
- [ ] Browser:

**Comment by knolleary** [comment]
Hi - thanks for reporting. When you say 'stopped working' - did this previously work for you? I'm not aware of this code path changing for some time, so likely to have been like this for quite a while.

**Comment by dceejay** [comment]
Hmm yeah... workaround for now is to send ""  ie a blank string...

**Comment by quazzie** [comment]
I wan't to say it has been working but I might got it confused. I'm just returning to node-red and I want to say it worked last time I messed around. 

Blank string is not null :-) 
Found another workaround though, new Buffer(0).

**Comment by dceejay** [comment]
well a blank string "" is 0x  so yeah... like what I said...

**Comment by quazzie** [comment]
@dceejay I'm apparently a mess today, i thought i did try "" and didn't get null. But i tried it again and yes of course it worked.

**Comment by dceejay** [comment]
:-) - but indeed sending a real null ought to also do the right thing - so thanks for spotting it.

**Comment by knolleary** [comment]
Fixed on the 0.18 branch
