### ISSUE TITLE
Trigger node malfunction when output fed back to input.

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#1527]
### Steps to reproduce
Deploy the flow below. Clicking the inject node causes no output, as expected, and when the inject is no longer clicked then after 5 seconds a timeout message is sent. The timeout msg feeds back to the input and so starts a new timeout, and timeout messages appear every 5 seconds as expected. However if the inject button is clicked repeatedly then this should hold off the timeout again, but it does not. Each time the inject is clicked the blue status appears but it is as if the Extend Delay option is not selected.  Also the blue status is not shown for the event triggered by the feedback message.

In addition I notice that once started then redeploying the complete flow does not stop the timeout messages appearing, which I find odd.

If the Pass Through function node is replaced with a 1 second Delay node then it works as expected.

### Environment:

- [ ] Node-RED version: 0.17.5
- [ ] node.js version: 6.12.2
- [ ] npm version: 3.10.10
- [ ] Platform/OS: Ubuntu 17.10
- [ ] Browser: Waterfox

### Flow

`[{"id":"81d80b76.383e88","type":"inject","z":"f0414dd0.dd514","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":130,"y":354,"wires":[["e3ac289e.7ef28"]]},{"id":"e3ac289e.7ef28","type":"trigger","z":"f0414dd0.dd514","op1":"","op2":"timeout","op1type":"nul","op2type":"str","duration":"5","extend":true,"units":"s","reset":"","name":"","x":316,"y":354,"wires":[["2ac43a98.81d86e","29162320.8bf47c"]]},{"id":"2ac43a98.81d86e","type":"debug","z":"f0414dd0.dd514","name":"","active":true,"console":"false","complete":"false","x":522,"y":355,"wires":[]},{"id":"29162320.8bf47c","type":"function","z":"f0414dd0.dd514","name":"Pass Through","func":"return msg;","outputs":1,"noerr":0,"x":321,"y":416,"wires":[["e3ac289e.7ef28"]]}]`

**Comment by dceejay** [comment]
yes - I see that..

holdoff works fine without the feedback loop - so must be hitting some timing edge case.

**Comment by colinl** [comment]
I am guessing the message fed back is coming in before the state variables in the node have been fully reset.

**Comment by colinl** [comment]
Following a discussion on the node-red group [1] it appears that node.send() does not necessarily return immediately but completes any synchronous activity before returning. In the test flow I believe this may mean that, for example, the call of node.send at line 135 of 89-trigger.js will re-enter the trigger node before the lines below (tout=nul, and setting node.status) will execute. There are a couple of other places where node.send is called that may also cause similar problems.  If so then the solution may be to re-order the code so that node.send is the last code in the timer function.

[1] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/node-red/OCHTT8aA3lk/cw9oKfMoDAAJ

**Comment by dceejay** [comment]
does the fix already implemented not actually fix it then ?

**Comment by colinl** [comment]
I don't know, for some reason I didn't get the notification email, so did not see that.  Will try it.  Whether it does or not am I right in saying that potentially there could be a problem, particularly with clearing tout after node.send rather than before it?

**Comment by dceejay** [comment]
we don't clear tout after a send so can't quite be like that.... we clear it before a send and restart it (the extend functionality).

**Comment by colinl** [comment]
Doesn't line 135 of 89-trigger.js do that, or am I misinterpreting the code? It appears to call node.send and then null tout, rather than nulling tout and then calling node.send.

**Comment by dceejay** [comment]
Yes - but that's not the fixed version - see link to fixed version above.
https://github.com/node-red/node-red/commit/f737ea96f309f1e5f59fc94a5f2687fae3d5d806

**Comment by colinl** [comment]
Sorry, I missed the fact that it was on a branch.
Isn't there the same issue with delete node.topics[topic] and node.status({})? that these may get executed after another message has come in from within the call to node.send?

**Comment by dceejay** [comment]
no. The status and delete will happen, and the if at (new) line 138 will stop the send after the timeout if it was set in error.

**Comment by colinl** [comment]
Sorry, still not getting it. Am I wrong in thinking that the following could happen:
node.send is called at line 140
Within node.send the message will be passed to the function node that just passes the message through
Still within node.send that message will get passed to the trigger node
Still within node.send the trigger node line 82 will set node.topics[topic] and then run through dealing with this message
Eventually node.send will hit something asynchronous and will return
Now back in the timer function node.topics[topic] will be deleted and the status cleared.

**Comment by dceejay** [comment]
err possibly (stretching both our brains at this point)... worst case yes the async bit it would hit would be the setTimeout at 132.  So then they get deleted and cleared. The timeout then pops - but as the flag has been deleted nothing gets sent (line 138)

**Comment by colinl** [comment]
Having said I would test it, how do I go about installing that branch of node-red?

**Comment by colinl** [comment]
To answer my own question:
git clone https://github.com/node-red/node-red.git
cd node-red
git checkout 0.18
npm install
npm run build
node red.js

**Comment by colinl** [comment]
For me it does not work with branch 0.18, however if I adjust the code at line 114 to 
```
                        node.topics[topic].tout = setTimeout(function() {
                            var msg2 = null;
                            if (node.op2type !== "nul") {
                                msg2 = RED.util.cloneMessage(msg);
                                if (node.op2type === "flow" || node.op2type === "global") {
                                    node.topics[topic].m2 = RED.util.evaluateNodeProperty(node.op2,node.op2type,node,msg);
                                }
                                msg2.payload = node.topics[topic].m2;
                            }
                            delete node.topics[topic];
                            node.status({});
                            node.send(msg2);
                        }, node.duration);
```
and at line 133
```
                    node.topics[topic].tout = setTimeout(function() {
                        var msg2 = null;
                        if (node.op2type !== "nul") {
                            msg2 = RED.util.cloneMessage(msg);
                            if (node.op2type === "flow" || node.op2type === "global") {
                                node.topics[topic].m2 = RED.util.evaluateNodeProperty(node.op2,node.op2type,node,msg);
                            }
                            if (node.topics[topic] !== undefined) {
                                msg2.payload = node.topics[topic].m2;
                            }
                        }
                        delete node.topics[topic];
                        node.status({});
                        node.send(msg2);
                    }, node.duration);
 ```

Then it does appear to work.

**Comment by colinl** [comment]
Sorry, the second part is not right, for line 133 should be
```
                    node.topics[topic].tout = setTimeout(function() {
                        var msg2 = null;
                        if (node.op2type !== "nul") {
                            if (node.op2type === "flow" || node.op2type === "global") {
                                node.topics[topic].m2 = RED.util.evaluateNodeProperty(node.op2,node.op2type,node,msg);
                            }
                            if (node.topics[topic] !== undefined) {
                                msg2 = RED.util.cloneMessage(msg);
                                msg2.payload = node.topics[topic].m2;
                            }
                        }
                        delete node.topics[topic];
                        node.status({});
                        node.send(msg2);
                    }, node.duration);
```

**Comment by dceejay** [comment]
would you like to make that into a pull request ?

**Comment by knolleary** [comment]
Closing as #1539 is merged
