### ISSUE TITLE
Inconsistent datatype of outputs field for function components when exporting flows to JSON

### ISSUE THREAD

**Issue by boriwo** [node-red/node-red#1532]
### What are the steps to reproduce?

Create a flow with a function node with a single output and export to clipboard. Then create a flow with a function with two outputs and export to clipboard.

### What happens?

You will notice that the function with a single output will create the outputs field value in JSON as the number 1 while the function with two outputs will create the output field value as string "2".

Example:

```
[{"id":"dac8cbb3.80ca8","type":"function","z":"e38443ae.9b984","name":"my_func","func":"","outputs":1,"noerr":0,"x":544.86669921875,"y":141.99993896484375,"wires":[["1b1832f9.609a5d"]]}]
```
```
[{"id":"fdf2984f.c171e","type":"function","z":"e38443ae.9b984","name":"my_func","func":"{\n    \"delay_seconds\" : \"15s\",\n    \"timer_id\" : \"meta.id\"\n}","outputs":"2","noerr":0,"x":277.86669921875,"y":402.7833251953125,"wires":[["dac8cbb3.80ca8"],["3f0372a9.69335e"]]}]
```

### What do you expect to happen?

The outputs field should have a consistent datatype of number in both cases. Otherwise this can cause problems when trying to parse Node-red flows.

### Please tell us about your environment:

- [x] Node-RED version: 0.17.5
- [ ] node.js version:
- [ ] npm version:
- [x] Platform/OS: OSX
- [x] Browser: Firefox

**Comment by knolleary** [comment]
Can you explain what specific issue this is causing? The runtime happily handles this property expressed as either a string or number.

**Comment by boriwo** [comment]
I am working on a separate tool (outside of node-red), that allows importing flows created in node-red. Of course I can make my tool handle either string or number input in the outputs field, it just seems odd and it requires special handling.
