### ISSUE TITLE
What is jsonata.functions in ui/editor ??

### ISSUE THREAD

**Issue by kristianmandrup** [node-red/node-red#1534]
Can't figure out `jsonata.functions` in this context. `jsonata` library doesn't seem to export such a constant. What am I missing?

I'm trying to work on my own extension to node-red, but stuck here. 

`import { jsonata } from 'jsonata'`

Please advise. Thanks :)

I raised the question here https://github.com/jsonata-js/jsonata/issues/104 as well

[editor.js](https://github.com/node-red/node-red/blob/master/editor/js/ui/editor.js#L1719)

```js
Object.keys(jsonata.functions).forEach(function(f) {
     funcSelect.append($("<option></option>").val(f).text(f));
})
```

However, it seems to be an extension configured in [vendor/jsonata/formatter.js](https://github.com/node-red/node-red/tree/master/editor/vendor/jsonata/formatter.js)

What is the deal with these vendor libs? Is it using an old version 1.2 of jsonata with these configs built in?

**Comment by dceejay** [comment]
Hi,

as per our contribution guidelines we prefer general how-to questions via either the mailing list, slack channel, or stack-overflow (tagged node-red), as that way they get seen by a much wider audience. Especially in this case as many more jsonata experts are in the wider community.

**Comment by knolleary** [comment]
We bundle jsonata in the editor, although we're slightly back-level as we've not done a maintenance releases of node-red for a while.

The code under vendor/jsonata includes some Node-RED specific extensions that help provide the jsonata expression editor component of node-red; syntax highlighting and autocomplete for example.

As Dave says (as did the issue template you deleted when opening this), please use the mailing list or slack for questions.
