### ISSUE TITLE
dead link on README and CONTRIBUTING.md

### ISSUE THREAD

**Issue by biancode** [node-red/node-red#1540]
Hi, 

on click I saw the following link does not work anymore:
https://github.com/orgs/node-red/teams/core

Happy new year!
Klaus

**Comment by hardillb** [comment]
That link works just fine, it points to a page listing Nick and Dave

**Comment by knolleary** [comment]
@hardillb as you are a member of the organisation it is visible to you. It appears that link is not visible to non-members.

**Comment by biancode** [comment]
hm, for me it shows a 404
<img width="899" alt="grafik" src="https://user-images.githubusercontent.com/4369867/34469008-94a8ec24-ef15-11e7-9322-164278c463bd.png">

**Comment by knolleary** [comment]
Fixed in 0.18
