### ISSUE TITLE
RED.settings.get('userDir') returns undefined

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#1543]
### What are the steps to reproduce/What Happens?

In a node's js file `module.exports` section, try to obtain the `userDir` using `RED.settings.get('userDir')`, it returns `undefined`.

But if you instead use `RED.settings.userDir`, it returns the expected folder name.

### What do you expect to happen?

`RED.settings.get('xxxx')` should work consistently.

### Please tell us about your environment:

- [x] Node-RED version: v0.17.5
- [x] node.js version: v6.11.3
- [x] npm version: 3.10.10
- [x] Platform/OS:  Windows_NT 10.0.16299 x64 LE
- [x] Browser: Chrome latest

**Comment by knolleary** [comment]
The `RED.settings` api provides access to two different types of settings: runtime settings and user settings.

User settings are those provided by the settings file and are read-only. They are accessed as properties of the `RED.settings` object such as `RED.settings.userDir`

Runtime settings are ones that can change while node-red is running and need to be persisted. These are the settings accessed via `RED.settings.get()/set()`. When running with the default storage, this is what is saved in the `.config.json` file in your user directory.

**Comment by TotallyInformation** [comment]
OK, thanks for the clarification. But it is confusing & hard to remember.
