### ISSUE TITLE
Cannot connect SSL websocket

### ISSUE THREAD

**Issue by thamht4190** [node-red/node-red#1565]
I have a SSL websocket running background on my Windows. When I run NodeRED server then use websocket node to connect to my websocket, it doesn't work. This is the log when I add more console.log() to file \node-red\nodes\core\io\22-websocket.js:
Code:
```
socket.on('error', function(err) {
                console.log(err); // <-- log that I've added
                node.emit('erro');
                if (!node.closing && !node.isServer) {
                    clearTimeout(node.tout);
                    node.tout = setTimeout(function() { startconn(); }, 3000); // try to reconnect every 3 secs... bit fast ?
                }
            });
```
Error logs that I've got:
```
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

This is my environment information:
- [ ] Node-RED version: 0.18
- [ ] node.js version: 8.9.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Windows 10 Pro
- [ ] Browser: (not available)

Is it a issue? How can I connect NodeRED with my SSL websocket? Thanks.

**Comment by knolleary** [comment]
Hi,

we need to expose TLS options in the WebSocket client node to do this properly.

As a workaround, if you add:

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

to the top of your settings it should stop complaining.

I have added a task to the backlog to add the TLS options in the node - https://trello.com/c/AKcEi5Kb

**Comment by thamht4190** [comment]
thanks @knolleary. It will be helpful to have TLS options added in NodeRED.

**Comment by knolleary** [comment]
Added in the 0.18 branch https://github.com/node-red/node-red/commit/73ee657d7444df14e1d0d2a973af733a9bfa3093
