### ISSUE TITLE
MQTT node is not reconnecting

### ISSUE THREAD

**Issue by milosjovac** [node-red/node-red#1566]
### What are the steps to reproduce?

With [this flow](https://gist.github.com/milosjovac/29b748244206378a39cf19f5c2fe6bb9) do the following:

- [ ] Make change to nodes position, or change debugger node state so that flow can be redeployed
- [ ] Turn off internet connection (or unplug LAN cable)
- [ ] Deploy flow
- [ ] Wait until 'Remote MQTT BROKER' node is disconnected and "Error stopping node: Timed out after 1500ms" is thrown in the debug tab
- [ ] Turn on internet connection (or plug LAN cable back)

![image](https://user-images.githubusercontent.com/2808506/35112121-5a1808a4-fc7d-11e7-9408-79fc6299f891.png)

### What happens?

MQTT client node never reconnects

### What do you expect to happen?

MQTT client node to try and reconnect at some intervals 

### Please tell us about your environment:

- [ ] Node-RED version: v0.17.5
- [ ] node.js version: v7.10.0 
- [ ] npm version: v4.5.0
- [ ] Platform/OS: Linux 4.9.24-v7+ arm LE / Raspbian 8.0
- [ ] Browser: Chromium v56.0.2924.84

**Comment by knolleary** [comment]
Closed on 0.18
