### ISSUE TITLE
html node does not return empty array if no match found

### ISSUE THREAD

**Issue by bluepup** [node-red/node-red#1582]
The html node drops the message if no match is found for a selector.
That behaviour breaks flows that pick certain data out of a html document.

Examples are using a flow to grab values out of a document in a serial fashion one after another. If only one of the selectors does not find a match the whole flow is broken.

![screenshot2](https://user-images.githubusercontent.com/966043/35434232-b6d16e50-0286-11e8-92cc-138f192bc86b.png)

The other possibility was to split an array of Instructions (selectors) and process the document with the html node. But a subsequent join fails if not all messages from the split arrive at the join node.

![grafik](https://user-images.githubusercontent.com/966043/35434390-422b6730-0287-11e8-8301-16e213452feb.png)

The html node needs to return an empty array, at least as an option for the user.

**Comment by dceejay** [comment]
Sympathetic to this idea - as the current options are to either return single messages or as an array of messages... I think it would make sense if the array was always emitted even if blank... as the next step is usually to iterate over them or join them - both of which operations should be able to handle an empty array. 
The emit single messages option - would not emit anything.

**Comment by dceejay** [comment]
will be 0.18
