### ISSUE TITLE
double split and join can lead to unpredictable results

### ISSUE THREAD

**Issue by bluepup** [node-red/node-red#1583]
A flow using two split nodes and then two join nodes (automatic) leads to a different array than was started with. I would expect an array [[1,1,1],[2,2],[3,3,3]] to return at the end of the flow. But when the flow contains some processing in the middle with varying execution time (network requests) the result is always different. the result can for example be [ null, [ null, 2, 1 ], [ 3, 1 ] ] or [ [ 1, 1 ], null, [ 3 ] ].

### What are the steps to reproduce?
![screenshot2](https://user-images.githubusercontent.com/966043/35466754-0fa8b12a-0307-11e8-922b-4845681192f3.png)
All nodes in default configuration, the middle node is a random delay from 1 to 5 seconds (default for random).

### What happens?

The array seems to join but the values are mixed and messages seem to get a new order or even null values. Some of the values seem to get lost so that the automatic joins fail with no output at the end. My guess is that it has something to do with not using different _msgid after a split.

### What do you expect to happen?

The array at the end of the flow should at best be exactly the same as the input  [[1,1,1],[2,2],[3,3,3]].
At least no mixing of values should occur, order is not so important even if desirable.  [[1,1,1], [3,3,3], [2,2]] could be ok.

### Please tell us about your environment:

- [ ] Node-RED version: 0.15.3
- [ ] Platform/OS: raspbian

**Comment by bluepup** [comment]
I see that my version is quite old and the split node has had some changes since 0.15.3
Cannot test it with latest version, so sorry if this is not relevant any more.

**Comment by hardillb** [comment]
Any reason why you can't test with 0.17.5?

**Comment by knolleary** [comment]
No problem. @dceejay had a look and this is an existing issue. Thanks for reporting!

**Comment by dceejay** [comment]
Don't worry. It's still a problem. The current implementation is such that if it sees a "new" group start to arrive it closes off and sends the current one. So one level of out of order will work, but not two ( or more)

**Comment by dceejay** [comment]
actually was caused by re-using an ID for parts.id for repeated splits... which is obviously (now) a bad idea... using a new random one keeps the sub-parts in order...  (tested to depth 4)

Thanks for reporting it.

**Comment by danielelopez1** [comment]
Hello, I'm using nodered v3.1.0 but the problem persists. Do you have any idea how to "workaround" this? 
Thanks for your time

**Comment by hardillb** [comment]
@danielelopez1 this is a closed 6 year old issue that was closed as fixed.

If you believe you are seeing the same behaviour please open a new issue and supply an example flow that shows the problem.

I would also recommend testing with 3.1.9 as that is the latest stable release (and if you can with the 4.0.0 beta release)
