### ISSUE TITLE
show grid has turned itself on

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1600]
v0.18.0
after the upgrade, starting node-red has show-grid on.

you have to go into settings, turn it on, then turn it off, in order to turn it off

**Comment by knolleary** [comment]
We now store your editor config on the server side rather than in localStorage of the browser you happen to use. This means you get a consistent experience when accessing it from different browsers.

It _should_ have migrated your existing settings over - but maybe not.

Fixing the migration is going to offer diminishing returns as more users upgrade.

**Comment by andysc** [comment]
ah, OK - that would also explain why snap to grid turned itself off, then :)
As you say, diminishing returns.

**Comment by andysc** [comment]
when you say server-side, though, do you mean in the flow file currently in use?
Notwithstanding the move to projects, wouldn't that mean *inconsistent* experience when you move between flow files, as it would drop back to the defaults (grid on, snap off) the first time you use an existing flow file after migration to 0.18 ?
Or maybe you now have a secret stash somewhere else server-side?

**Comment by knolleary** [comment]
It is stored in the runtime config file: .config.json

**Comment by andysc** [comment]
good :) in that case, the only remaining problem is that the "show grid" checkbox in settings doesn't accurately reflect the current state, as the grid will be on (the new initial default) but the checkbox shows it's off. So you have to turn it on, then off to turn the grid off.

**Comment by andysc** [comment]
I'm sure you've got far bigger fish to fry ;)

**Comment by knolleary** [comment]
Going to flag this as 'wontfix' given my comments above about diminishing returns. Sorry!
