### ISSUE TITLE
enhancement to custom node icons

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#1602]
v0.18.0

as the names of the icons generally don't match what they look like (e.g. "bridge" for the MQTT node!), could we have a preview of the selected node icon at the side under "icon" after selecting from the pull-downs, so you can see what you're going to end up with when you click Done ?

**Comment by knolleary** [comment]
Yes that is the plan eventually.

As discussed, please use the mailing list or slack for feature enhancements. We have lots of things planned and don't want to fill the issue list with feature requests.
