### ISSUE TITLE
Instances of "play audio" node in separate flows use same voice though voice selection differs

### ISSUE THREAD

**Issue by dennishvo** [node-red/node-red#1618]
The play audio node behaves as if the voice selection is global to the node-red instance, i.e. when I have multiple play audio nodes that use different voices, it uses the voice I last selected and deployed in all play audio nodes.

### What are the steps to reproduce?
I created two flows, each of which has a play audio node. I set the voices on each play audio node to be different. For example, in one flow it's Samantha, while the other uses Fred.

### What happens?
 When I deploy, the voice heard on both flows will be the same voice, e.g. only Fred. When I look at the settings of both nodes, the voices are correct, i.e. they are the ones I originally selected, and they are different voices.

### What do you expect to happen?
My assumption was that the voice selected would be used in each play audio node.

### Please tell us about your environment:

Node-RED version: 0.18.2
node.js version:  8.9.4
npm version: 5.6.0
Platform/OS: Raspberry Pi / linux 4.9.35-v7+ arm LE
Browser: chrome on Mac OS 10.13.3

**Comment by knolleary** [comment]
Which node exactly are you using? From what module?

If it's from a node-red-contrib- module, then you should raise an issue against their repository. We don't have any play audio nodes in the Node-RED project.

**Comment by dennishvo** [comment]
It's called node-red-contrib-play-audio. I assumed it was part of the Node-RED project because I never explicitly installed it. I'll go to their project. Thanks!
