### ISSUE TITLE
Merge prompt won't show clicking on flow.json unmerged changes

### ISSUE THREAD

**Issue by AlbeRCLife** [node-red/node-red#1619]
### What are the steps to reproduce?

- Create a gitlab project with one simple flow (for example one http request node, a function node with node.log and a http response node)
- Commit and push the changes.
- From one machine just move one node where you wish and push that change, while in other machine move another node where you wish too, but wait for the first person tu push the changes.
- It won't let you push the changes so you'll have to pull them, a merge conflict advise is shown.
- Click that notification and then try to click on "flow.json" merge issue. Nothing happens.

![image](https://user-images.githubusercontent.com/16323399/36027346-35f6d426-0d9b-11e8-93fa-d55ebf1b515f.png)

### What happens?
When you try to click that merge problem to see the changes it won't show anything, this errors are shown in the console:
![image](https://user-images.githubusercontent.com/16323399/36027374-5e3a9e86-0d9b-11e8-8f98-d1ae760de562.png)

### What do you expect to happen?
A prompt showing me the changes between my workflow and the one pushed, to chose to keep one of them or merge them mannually.

As a side note here:
I debugged this issue to try to fix it with my environment, and I made this:
With pretty formatted minified file changed inside function R(e), where it says 
                 if (f)
                    n.file = f[1];
I added a check (if (n === undefined) n={}; ) and then I needed to add another check in the hunks section:
return o && n.hunks.push(o),
        l.push(n),
        l
I added above this -> if (n.hunks === undefined) n.hunks = []; 
And then I could see that prompt, although I had one issue trying to commit the changes, as somehow it adds "<<<<<< HEAD" in flow.json and that makes the flow not show in the editor as is not correct.
Couldn't really continue debugging  and I thought of openning this issue.

Just so you have a reference this code is as I could see inside node-red/editor/js/ui/diff.js , line 2079 for the first error (the n.file one) and line 2123 for the second one (the one within n.hunks.push).

### Please tell us about your environment:

- [ ] Node-RED version: v0.18.2 (the issue was originally catched in version v0.18.1, but I updated and tried on the same project and it happend too)
- [ ] node.js version: v6.12.3
- [ ] npm version: 3.10.10
- [ ] Platform/OS: Linux 4.4.0-87-generic x86_64 (docker nodered/node-red-docker image)
- [ ] Browser: Versión 63.0.3239.132 (Build oficial) (64 bits)

**Comment by knolleary** [comment]
Hi - thanks for reporting. I actually got this fixed yesterday - will be in 0.18.3 later today.

**Comment by AlbeRCLife** [comment]
Tested the new version v0.18.3 and this test case is fixed (thank you). 
Although I'll open other issues related with this one.
