### ISSUE TITLE
First project won't be created

### ISSUE THREAD

**Issue by almadsen** [node-red/node-red#1620]
I'm tying to create the first project bu it won't "stick".
I get as far as the last screen (see below) but then it won't go any further.
In the ~/.node-red/project/ folder I can se some files and folders been created Be that's about it, can't use it, where to go from here? Any ideas any one?

<img width="615" alt="skarmavbild 2018-02-09 kl 18 20 31" src="https://user-images.githubusercontent.com/1423040/36040647-6a690474-0dc6-11e8-9af9-af0a951a50fa.png">

**Comment by knolleary** [comment]
Hi.

What version of Node-RED are you using? A number of fixes have gone into 0.18.1 and 0.18.2 that would be worth having before we try to debug this too far.

**Comment by almadsen** [comment]
I was on 0.18.1 but updated to 0.18.2 and now it works.
Thanx a bunch.

**Comment by knolleary** [comment]
Great!
