### ISSUE TITLE
Cannot read property 'addMembership' of null

### ISSUE THREAD

**Issue by Thinkscape** [node-red/node-red#1623]
### What are the steps to reproduce?

Keep node-red running for a few days

### What happens?

Crashes with 
````
node_red_1                   | 10 Feb 19:53:12 - [red] Uncaught Exception:
node_red_1                   | 10 Feb 19:53:12 - TypeError: Cannot read property 'addMembership' of null
node_red_1                   |     at Timeout.addMembership [as _onTimeout] (/data/node_modules/node-ssdp/lib/index.js:182:18)
node_red_1                   |     at ontimeout (timers.js:488:11)
node_red_1                   |     at tryOnTimeout (timers.js:323:5)
node_red_1                   |     at Timer.listOnTimeout (timers.js:283:5)
node_red_1                   | npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
node_red_1                   | npm ERR! code ELIFECYCLE
node_red_1                   | npm ERR! errno 1
````

### What do you expect to happen?

No crash

### Please tell us about your environment:

- Node-RED version: v0.17.4
- node.js version: v8.1.4
- npm version: 5.0.3
- Platform/OS: running from `node-red` docker image.
- Browser: Chrome

**Comment by hardillb** [comment]
This is down to one of the node's you've installed not catching an error, not Node-RED it's self.

What nodes have you installed that do discovery?

**Comment by knolleary** [comment]
Hi, this is being thrown by node-ssdp which isn't a module the core of Node-RED uses. So this is coming from one of the contrib nodes you have installed. As such, there's nothing we can do about it in this repository - the issue needs raising against the node using node-sspd.

**Comment by knolleary** [comment]
Closing this issue as it isn't related to the core of node-red.

Happy to help narrow down the node at fault if needed - just need some answers to the questions above.

**Comment by Thinkscape** [comment]
Hmm.. I was under the impression that node-red would `try{} catch{}` nodes' exceptions... however in this case that might be triggered from a timer. I wish there was a better way to prevent nodes' code to crash the whole system...

**Comment by knolleary** [comment]
Right - we will catch all errors that are thrown synchronous to our code. But any asynchronously thrown error that is not handled properly by the node is going to be fatal. That is a purposeful decision we've taken - an unhandled asynch error means we have no idea what state the system is in. The only way to ensure things are is a known state is to recycle the runtime.
