### ISSUE TITLE
npm install failed on Raspberry Pi

### ISSUE THREAD

**Issue by Kazuki-Nakanishi** [node-red/node-red#1629]
### What are the steps to reproduce?
1. Launch a terminal on Raspberry Pi.
1. clone Node-RED repository from GitHub.
1. run `npm install`

### What happens?
Installing chromedriver failed.

### What do you expect to happen?
Avoid installing chromedriver (and other related packages) when running `npm install` on Raspberry Pi.

### Please tell us about your environment:

- [x] Node-RED version: 0.18.3
- [ ] node.js version:
- [ ] npm version:
- [x] Platform/OS: Raspbian OS
- [ ] Browser:

**Comment by Kazuki-Nakanishi** [comment]
@knolleary Thank you very much for your comment.

I wanted to have the `dev` version of optionalDependencies in package.json.  This was already discussed here, and npm does not support it as of now.
https://github.com/npm/npm/issues/3870

At this moment, I agree with the option that lets a user install chromedriver manually. I also need to update a design wiki.
I will send a PR for it soon.

**Comment by boneskull** [comment]
My opinion: don't worry about it.  Users installing from a working copy on a platform that doesn't support the dev dependencies can simply `npm install --production` to avoid installing them.

**Comment by dceejay** [comment]
not really. If they install from git they need to build the project in order to get a working version... so they need the grunt tools.

**Comment by boneskull** [comment]
ah, you're right about that.  solution: use `npm` to install `node-red` instead of cloning it.  :wink:

**Comment by boneskull** [comment]
so then, @Kazuki-Nakanishi Why do you need to clone the repo and install this way on your RPi?  Why can't you use e.g. `npm install -g node-red`?

I agree running NR on an RPi is great and awesome, but I wouldn't really want a RPi as my dev environment.

**Comment by dceejay** [comment]
I don't think he does particularly... he is just responding to a problem I raised that IF someone did want to do this it currently breaks (and indeed same with other architectures re that other issue) - It's only for testing the UI side - so the bulk of the existing tests work fine without it.

**Comment by Kazuki-Nakanishi** [comment]
Hi @boneskull, Thank you for your comments.
The reason is as @dceejay explained.  And one actual scenario would be that Node-RED contributors sometimes run `npm install` on Raspberry Pi to test their code.

**Comment by knolleary** [comment]
Closing as per the merged PR above.
