### ISSUE TITLE
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE raised by HTTP(s) request node 

### ISSUE THREAD

**Issue by juzam** [node-red/node-red#163]
When calling an https url and the CA or the certificate fails to validate, this error is raised.
example url: https://api.wheretheiss.at/v1/satellites/25544 
(this uses a certificate issued by RapidSSL)

Should be fixable by specifying "{rejectUnauthorized:false}" as an option to tls.connect() call.

Is there a way to specify such kind of option directly in node-red interface?

**Comment by tverilytt** [comment]
Hi!

I needed to make a https request, including server & client certificates (this was for testing the Bluemix Cloud Integration Secure Connector service).
I ended up creating a simple Node-RED "https-request" node to get hold of the certificate content and
calling https.request.

I was unsure if I could use the node-red-node http-request for this.
If not, it would be handy to be able to provide the https options to a Node-RED node. Maybe not all
options needs to be available in the UI, will get pretty messy.

Cheers
-jo

**Comment by bmwilli** [comment]
@tverilytt, Have you published your https-request node?  Can you share it?

**Comment by tverilytt** [comment]
Hi!

I did ask about this on the Node-RED Google Groups group:
https://groups.google.com/forum/#!searchin/node-red/https$20node/node-red/vj1-xF5wni8/R4ORMEzzpQUJ

If the base http-request node can be used for https with support for all the https options, that
will be cool for me :-)

Cheers
-jo

**Comment by knolleary** [comment]
Currently, the existing nodes don't support the provision of all of the relevant https configuration options needed. They can be used for HTTPS requests, but the environment variable documented above may be required to disable certificate checking.

The right answer will be for us to update the nodes with the suitable minimum set of options to enable https to be handled properly. The task is to identify what that minimal set is - we don't want to overwhelm or overcomplicate the UI.

**Comment by tverilytt** [comment]
Thanks for that Nick!

Could it be done like - provide minimal properties for the UI, whilst at same time be able to receive
https options object covering (potentially) all options in e.g. msg.options.httpsoptions?
That is mainly what I have done - no particular UI support, but receiving the options in the msg object.

cheers
-jo

**Comment by borpin** [comment]
@tverilytt Trying to insert a suitable header to get round an DEPTH_ZERO_SELF_SIGNED_CERT error when talking to an Edimax SmartPlug.  Can you explain (I'm new to Node-RED) how you inserted the header?  I tried the link above but it did not seem to offer the solution.  Cheers, B

**Comment by tverilytt** [comment]
Hi!
If you want to add / modify HTTP(S) header in Node-RED before calling a http-request node, you can add desired header key/value pairs in a function node before the http-request node.
This should work for both http and https.
Here is an example from a thread on the Google+ Node-RED group:
https://groups.google.com/forum/#!searchin/node-red/http$20header/node-red/nl9Be0dN55g/NuKMABr_M1EJ

I made a home made Node-RED https-request node to be able to use certificates, I started out with this Node.js doc on https request:
https://nodejs.org/api/https.html#https_https_request_options_callback

Cheers
-jo
