### ISSUE TITLE
node-red-node-serialport: 100% CPU use if serial port is used by another process

### ISSUE THREAD

**Issue by Dannsei** [node-red/node-red#1633]
### What are the steps to reproduce?

1. create a flow communicating via serialport using node-red-node-serialport 
2. run a Python script also using the serial port (using pySerial module, not set to exclusve access to the serial port)

### What happens?

node red works as expected and CPU usage is minimal until the Python script is run.  When the Python script starts running, node red uses all available CPU, and continues to do so even after the Python script terminates and until node red is stopped.  Serial communication in both node red and Python works without errors.  When node red is not running, the Python script runs with minimal CPU usage.

### What do you expect to happen?

no excessive CPU use when sharing access to the serial port.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.2
- [ ] node.js version: 8.9.4
- [ ] npm version:
- [ ] Platform/OS: Raspbian OS Stretch (Linux 4.9.59+ #1047) 
- [ ] Browser:

using node-red-node-serialport v.0.6.3 

(running on Raspberry Pi Zero Wireless)

**Comment by knolleary** [comment]
fyi - node-red-node-serialport is maintained here: https://github.com/node-red/node-red-nodes

This repo is for the core runtime of node-red.

**Comment by dceejay** [comment]
Not sure if this is a Node-RED problem - seems more like Linux in general and or how the serialport is implemented in node.js.
https://superuser.com/questions/488908/sharing-a-serial-port-between-two-processes

**Comment by Dannsei** [comment]
It doesn't seem to be a Linux issue - as explained in tone of the answers in the thread you linked to, the problem is not that only one process can access the serial port, but rather to do with a process being able to get exclusive access.

I checked out the issues in node.js serialport.  I couldn't find anything about sharing a serial port between processes.  However I did find an issue with CPU running at 100% when 115200 baud rate is set (which is as I have it).  That issue is closed, though not resolved:

https://github.com/node-serialport/node-serialport/issues/402

I suspect that may be it.  There also seem to be issues with memory leaks etc. So yes, I think can conclude the issue is how serialport is implemented in node.js as you suggested.

I guess the best workaround is to not use serialport in node red and use the Python script for all serial communication, and link to node red via MQTT (or websockets, TCP etc.).

(It would be very nice if node red could use Python under the hood rather than node.js for things like serial port as it seems more stable and mature).

**Comment by dceejay** [comment]
well all the indications are that sharing a port is fraught, and also OS / platform dependent as well... so the best way to share it is to do as you suggest and have only one thing grab the port and then send everything via that. Whether you choose to do that via python or node is up to you... All I can say is that when used exclusively the serial port has been very stable for me... (in my limited uses of it)... and yes, I share things through it by using mqtt to act as the funnel. 

Once upon a time I had a rawSerial port node that just redirected to /dev/tty... etc - that worked fine as well (but didn't have baud control etc as it really was just a pipe :-)

**Comment by knolleary** [comment]
Moving this conversation over to https://github.com/node-red/node-red-nodes/issues/406

Thanks!
