### ISSUE TITLE
Flow with subflow merge won't let you see changes in flow

### ISSUE THREAD

**Issue by AlbeRCLife** [node-red/node-red#1635]
### What are the steps to reproduce?
Take a flow with let's say 4 nodes, 1 of it is a subflow node pointing to its own things.
Make a change in one of the other 3 nodes of the flow containing the subflow.
Commit it but don't push. 
Prepare in other machine on the same project a change in one of that 3 nodes (not inside the subflow or the subflow itself). Push this changes.

Pull from the first machine the changes made on the second one. 
Merge will start. 

If you click the flow.json to check for the changes the name of the flow that contains the subflow won't show the changes and so you won't be able to merge anything if it says there's at least one conflict.

### What happens?
In this test case you won't be able to finish the merge and so you will be stuck in that situation.

### What do you expect to happen?
The name of the flow that contains the subflow lets you open the changes and chose the version you want as with a normal merge case.

### Please tell us about your environment:

- [x] Node-RED version: v0.18.3
- [x] node.js version: v6.12.3
- [x] npm version: 3.10.10
- [x] Platform/OS: Linux 4.4.0-87-generic x86_64 (docker nodered/node-red-docker image)
- [x] Browser: Chrome Versión 63.0.3239.132 (Build oficial) (64 bits)

**Comment by knolleary** [comment]
Reproduced - thanks for the issue report.
