### ISSUE TITLE
Merging nodes with just the name changed doesn't show the changes

### ISSUE THREAD

**Issue by AlbeRCLife** [node-red/node-red#1636]
### What are the steps to reproduce?
Create a gitlab project with just one flow inside the nodered project and 3 or 4 nodes. 
Upload it to the project.

Make a pull of that project to stay in the last revision of that git project. 
Change just the name of the node (don't move the node). Commit and push.
From another machine before making a pull of this changes change the same node to another name (don't move it neither).

Start the merge. It won't let you see that changes.

### What happens?
It won't show the changes made until you move the node and so it says the x and y property of the json is changed too.

### What do you expect to happen?
I expect to see the change in the name even if the node isn't moved. (this may go forward not just in name but in content, but I didn't test it, I just tried with tha name)

### Please tell us about your environment:

- [x] Node-RED version: v0.18.3
- [x] node.js version: v6.12.3
- [x] npm version: 3.10.10
- [x] Platform/OS: Linux 4.4.0-87-generic x86_64 (docker nodered/node-red-docker image)
- [x] Browser: Chrome Versión 63.0.3239.132 (Build oficial) (64 bits)

**Comment by knolleary** [comment]
I'm not able to recreate this.

I have a merge conflict on just a node's name property and it is correctly displayed in the flow diff.

<img width="1153" alt="node-red" src="https://user-images.githubusercontent.com/51083/36257505-11e23072-124f-11e8-8375-cd37ed716575.png">

Can you share a pair of flow files that exhibit this issue when one is merged over the other?

**Comment by AlbeRCLife** [comment]
I tried it again and I couldn't reproduce it.
It seems that I made a mistake as it was tested in the same flow of closed issue  https://github.com/node-red/node-red/issues/1635

Sorry for the inconvenience, I close the issue.
