### ISSUE TITLE
chromedrive is not building on ppc64, ppc64le, s390, s390x, x86

### ISSUE THREAD

**Issue by al-k21** [node-red/node-red#1637]
### What are the steps to reproduce?
```
npm pack node-red
tar -xf node-red-0.18.3.tgz
cd package
npm it
```

chromedrive is a devDependency added in https://github.com/node-red/node-red/commit/b9213b73bdf12d2438ccaeb764f2ef62aa5b1c2d.
### Please tell us about your environment:

- [x] Node-RED version: 0.18.3
- [x] node.js version: 6.13.0
- [x] npm version: 3.10.10
- [x] Platform/OS: ppc64, ppc64le, s390, s390x, x86
#

**Comment by dceejay** [comment]
This is actually the same problem as #1629

**Comment by dceejay** [comment]
iF you are packing it locally yourself the workaround for now is to just remove it from the devdependencies.

**Comment by knolleary** [comment]
To be clear, this is being raised by the CITGM team. CITGM automatically tests popular node modules against new node.js builds as a way to regression test node.js.

The fact they want to run our test suite on platforms that chromedriver isn't available on is not our project's responsibility. Yes it happens there is an issue with chromedriver on one of our key platforms (pi) and we as a project are choosing to do something about it via #1629.

**Comment by boneskull** [comment]
@al-k21 For any further failures, please create an exception in your CITGM configuration
