### ISSUE TITLE
Projects > Open button is greyed out when no active project

### ISSUE THREAD

**Issue by edorgeville** [node-red/node-red#1639]
Hey everyone,
First of all, great job on release v18. Thank you for all the work you put in this project.

### What are the steps to reproduce?
- Fresh install
- Clone a repository in .node-red/projects/<projectname>
- Open node-red editor
- Get prompted to create your first project
- Close the window

### What happens?
Projects > Open button is greyed out

### What do you expect to happen?
Open button not to be greyed out, so we can load the already cloned project.

The disabling happens here : 
https://github.com/node-red/node-red/blob/326c6c496e6e07f6b98df82a578a93b89c80f026/editor/js/main.js#L69

Is there a reason I am not getting for this ? Right now it just forces the user to create a new project even if there is another one, just not active.

Thanks !

**Comment by knolleary** [comment]
Yes, right now the editor assumes you are migrating into projects, so if it doesn't know about any projects it takes you through the first run dialog. This is just a point in time thing - we'll be broadening out the options quite quickly as we get feedback (like this issue).

The workaround right now is to close the first run dialog then use ctrl-alt-o as the shortcut for the open project dialog.

**Comment by edorgeville** [comment]
Hadn't considered the shortcut. The explanation makes sense. Thanks !
