### ISSUE TITLE
Request: Nextcloud integration with node-red

### ISSUE THREAD

**Issue by sunjam** [node-red/node-red#1643]
Please consider adding support for [Nextcloud integration,](https://github.com/nextcloud) an open source platform that provides a [large community alternative to the proprietary Google suite and Dropbox.](https://nextcloud.com/)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you had read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you were presented in the issue template, you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack). This issue tracker is used to track issues in the core code, not for feature requests.

Anyone is able to create their own nodes and publish them to npm to enable integration with any particular system. We don't add integrations for particular systems within the core of node-red.

Thanks!
