### ISSUE TITLE
Trigger needs resetting if set to 'nothing'

### ISSUE THREAD

**Issue by jrmedd** [node-red/node-red#1644]
When using trigger to output a number, then send nothing, I can usually re-trigger without a reset. As of v0.18.3, it will only output once, then not be retriggered.

Expected behaviour: any payload will out the number specified in 'send', and nothing else. I can trigger it as many times as I like.

Actual behaviour: any payload will output the number specified in 'send', but won't ever trigger again!

**Comment by jrmedd** [comment]
[{"id":"9ebb5def.edead","type":"trigger","z":"7f118d5f.5f11a4","op1":"5","op2":"","op1type":"num","op2type":"nul","duration":"1","extend":false,"units":"ms","reset":"","bytopic":"all","name":"5","x":790,"y":420,"wires":[["14ebe537.ab11bb"]]},{"id":"207c9fe6.eda51","type":"inject","z":"7f118d5f.5f11a4","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"","x":650,"y":420,"wires":[["9ebb5def.edead"]]},{"id":"14ebe537.ab11bb","type":"debug","z":"7f118d5f.5f11a4","name":"","active":true,"console":"false","complete":"false","x":930,"y":420,"wires":[]}]

**Comment by jrmedd** [comment]
Set 'then send' to anything but 'nothing' and it re-triggers. I ran a workshop with fresh installs of Node-RED a few weeks ago and this didn't seem to be a problem. I noticed the trigger edit menu on participants' laptops today had changed so have updated myself.

**Comment by knolleary** [comment]
Thanks - this appears to have been broken by ff05fb14a615091071afd648d488700f9d4cdd37

Will sort out a fix. Thanks for reporting!
