### ISSUE TITLE
TypeError: Cannot set property 'users' of null

### ISSUE THREAD

**Issue by tchristian32** [node-red/node-red#1645]
### What are the steps to reproduce?
Upgraded to 0.18.3 version of Node-Red, running it inside another application.  So settings are done in server.js file.  Debug the application and load Node Red.

### What happens?
Welcome to Node-RED
===================
20 Feb 12:18:48 - [info] Node-RED version: v0.18.3
20 Feb 12:18:48 - [info] Node.js  version: v9.2.1
20 Feb 12:18:48 - [info] Darwin 17.4.0 x64 LE
20 Feb 12:18:48 - [info] Loading palette nodes
20 Feb 12:18:49 - [warn] ------------------------------------------------------
20 Feb 12:18:49 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
20 Feb 12:18:49 - [warn] ------------------------------------------------------
20 Feb 12:18:49 - [info] HTTP Static    : /public
20 Feb 12:18:49 - found collection
20 Feb 12:18:49 - found collection
20 Feb 12:18:49 - [info] Starting flows
20 Feb 12:18:49 - [info] Started flows
TypeError: Cannot set property 'users' of null
    at Object.setUserSettings (/project/node_modules/node-red/red/runtime/settings.js:182:34)
    at updateUserSettings (/project/node_modules/node-red/red/api/editor/settings.js:90:18)
    at Layer.handle [as handle_request] (/project/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/project/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /project/node_modules/node-red/red/api/auth/index.js:63:13
    at Layer.handle [as handle_request] (/project/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/project/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/project/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/project/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /project/node_modules/node-red/node_modules/express/lib/router/index.js:281:22

### What do you expect to happen?
Not to see an error

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.3
- [ ] node.js version: 9.2.1
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Mac
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Hi - can you share the settings object you pass into node-red?

**Comment by tchristian32** [comment]
Sure:

`var settings = {
    httpAdminRoot:"/",
    httpNodeRoot: "/api",

    // Retry time in milliseconds for MQTT connections
    mqttReconnectTime: 15000,

    // Retry time in milliseconds for Serial port connections
    serialReconnectTime: 15000,

    // Retry time in milliseconds for TCP socket connections
    //socketReconnectTime: 10000,

    // Timeout in milliseconds for TCP server socket connections
    //  defaults to no timeout
    //socketTimeout: 120000,

    // Timeout in milliseconds for HTTP request connections
    //  defaults to 120 seconds
    //httpRequestTimeout: 120000,

    // The maximum length, in characters, of any message sent to the debug sidebar tab
    debugMaxLength: 30000,

    // Colourise the console output of the debug node
    debugUseColors: true,

    // The file containing the flows. If not set, it defaults to flows_<hostname>.json
    //flowFile: 'flows.json',

    // To enabled pretty-printing of the flow within the flow file, set the following
    //  property to true:
    //flowFilePretty: true,

    // By default, credentials are encrypted in storage using a generated key. To
    // specify your own secret, set the following property.
    // If you want to disable encryption of credentials, set this property to false.
    // Note: once you set this property, do not change it - doing so will prevent
    // node-red from being able to decrypt your existing credentials and they will be
    // lost.
    //credentialSecret: "a-secret-key",

    // By default, all user data is stored in the Node-RED install directory. To
    // use a different location, the following property can be used
    //userDir: '/home/nol/.node-red/',

    // Node-RED scans the `nodes` directory in the install directory to find nodes.
    // The following property can be used to specify an additional directory to scan.
    //nodesDir: '/home/nol/.node-red/nodes',

    // By default, the Node-RED UI is available at http://localhost:1880/
    // The following property can be used to specifiy a different root path.
    // If set to false, this is disabled.
    //httpAdminRoot: '/admin',

    // Some nodes, such as HTTP In, can be used to listen for incoming http requests.
    // By default, these are served relative to '/'. The following property
    // can be used to specifiy a different root path. If set to false, this is
    // disabled.
    //httpNodeRoot: '/red-nodes',

    // The following property can be used in place of 'httpAdminRoot' and 'httpNodeRoot',
    // to apply the same root to both parts.
    //httpRoot: '/red',

    // When httpAdminRoot is used to move the UI to a different root path, the
    // following property can be used to identify a directory of static content
    // that should be served at http://localhost:1880/.
    httpStatic: '/public/',

    // The maximum size of HTTP request that will be accepted by the runtime api.
    // Default: 5mb
    //apiMaxLength: '5mb',

    // If you installed the optional node-red-dashboard you can set it's path
    // relative to httpRoot
    //ui: { path: "ui" },

    // Securing Node-RED
    // -----------------
    // To password protect the Node-RED editor and admin API, the following
    // property can be used. See http://nodered.org/docs/security.html for details.
    //adminAuth: {
    //    type: "credentials",
    //    users: [{
    //        username: "admin",
    //        password: "$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN.",
    //        permissions: "*"
    //    }]
    //},

    // To password protect the node-defined HTTP endpoints (httpNodeRoot), or
    // the static content (httpStatic), the following properties can be used.
    // The pass field is a bcrypt hash of the password.
    // See http://nodered.org/docs/security.html#generating-the-password-hash
    //httpNodeAuth: {user:"user",pass:"$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN."},
    //httpStaticAuth: {user:"user",pass:"$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN."},

    // The following property can be used to enable HTTPS
    // See http://nodejs.org/api/https.html#https_https_createserver_options_requestlistener
    // for details on its contents.
    // See the comment at the top of this file on how to load the `fs` module used by
    // this setting.
    //
    //https: {
    //    key: fs.readFileSync('privatekey.pem'),
    //    cert: fs.readFileSync('certificate.pem')
    //},

    // The following property can be used to cause insecure HTTP connections to
    // be redirected to HTTPS.
    //requireHttps: true

    // The following property can be used to disable the editor. The admin API
    // is not affected by this option. To disable both the editor and the admin
    // API, use either the httpRoot or httpAdminRoot properties
    //disableEditor: false,

    // The following property can be used to configure cross-origin resource sharing
    // in the HTTP nodes.
    // See https://github.com/troygoode/node-cors#configuration-options for
    // details on its contents. The following is a basic permissive set of options:
    //httpNodeCors: {
    //    origin: "*",
    //    methods: "GET,PUT,POST,DELETE"
    //},

    // If you need to set an http proxy please set an environment variable
    // called http_proxy (or HTTP_PROXY) outside of Node-RED in the operating system.
    // For example - http_proxy=http://myproxy.com:8080
    // (Setting it here will have no effect)
    // You may also specify no_proxy (or NO_PROXY) to supply a comma separated
    // list of domains to not proxy, eg - no_proxy=.acme.co,.acme.co.uk

    // The following property can be used to add a custom middleware function
    // in front of all http in nodes. This allows custom authentication to be
    // applied to all http in nodes, or any other sort of common request processing.
    //httpNodeMiddleware: function(req,res,next) {
    //    // Handle/reject the request, or pass it on to the http in node by calling next();
    //    // Optionally skip our rawBodyParser by setting this to true;
    //    //req.skipRawBodyParser = true;
    //    next();
    //},

    // Anything in this hash is globally available to all functions.
    // It is accessed as context.global.
    // eg:
    //    functionGlobalContext: { os:require('os') }
    // can be accessed in a function block as:
    //    context.global.os

    functionGlobalContext: {
        // os:require('os'),
        // octalbonescript:require('octalbonescript'),
        // jfive:require("johnny-five"),
        // j5board:require("johnny-five").Board({repl:false})
    },

    // The following property can be used to order the categories in the editor
    // palette. If a node's category is not in the list, the category will get
    // added to the end of the palette.
    // If not set, the following default order is used:
    paletteCategories: ['form', 'subflows', 'input', 'output', 'function', 'social', 'mobile', 'storage', 'analysis', 'advanced'],

    // Configure the logging output
    logging: {
        // Only console logging is currently supported
        console: {
            // Level of logging to be recorded. Options are:
            // fatal - only those errors which make the application unusable should be recorded
            // error - record errors which are deemed fatal for a particular request + fatal errors
            // warn - record problems which are non fatal + errors + fatal errors
            // info - record information about the general running of the application + warn + error + fatal errors
            // debug - record information which is more verbose than info + info + warn + error + fatal errors
            // trace - record very detailed logging + debug + info + warn + error + fatal errors
            level: "info",
            // Whether or not to include metric events in the log output
            metrics: false,
            // Whether or not to include audit events in the log output
            audit: false
        }
    },
    editorTheme: {
        page: {
            title: "LendingTree Form Builder",
            favicon: path.join(__dirname, "./assets/favicon.ico"),
            css: path.join(__dirname, "./styles/main.css")
        },
        header: {
            title: "Form Builder",
            image: path.join(__dirname, "./assets/logo.png"), // or null to remove image
            url: "http://www.example.com" // optional url to make the header text/image a link to this url
        },
        deployButton: {
            type:"simple",
            label:"Save",
            icon: path.join(__dirname, "./assets/save.png") // or null to remove image
        },
        menu: { // Hide unwanted menu items by id. see editor/js/main.js:loadEditor for complete list
            //"menu-item-import-library": false,
            //"menu-item-export-library": false,
            //"menu-item-keyboard-shortcuts": false,
            "menu-item-help": {
                label: "Help Link Text",
                url: "http://example.com"
            }
        },
        //userMenu: false, // Hide the user-menu even if adminAuth is enabled
        login: {
            //image: "/absolute/path/to/login/page/big/image" // a 256x256 image
        }
    }
}
`

**Comment by knolleary** [comment]
Your settings don't show it, but the log output suggests you are using a custom storage module. Can you confirm that is the case?

The issue is due to the fact the storage module's getSettings function is returning null. This would explain why it hasn't been seen elsewhere.

We probably need to handle this scenario a bit better - but means we won't be able to save any user-customisation of the editor (keyboard shortcuts etc).
