### ISSUE TITLE
Projects: Unable to load remote git repo in Windows

### ISSUE THREAD

**Issue by rophy** [node-red/node-red#1649]
### What are the steps to reproduce?

1. Set up SSH key in User Settings -> Git config
2. Add the SSH key in github.com -> Personal settings -> SSH Keys
3. Create a project
4. Set remote repository e.g. git@github.com:my-org/my-repo.git
5. Go to history -> Commit History -> Manage remote branch -> Expand the remote repo to load it
6. When `Authentication required for repository` prompt shows up, enter passphrase and click Retry

### What happens?

```
{ Error: Warning: Identity file C:Usersrophy.node-redprojects.sshkeys__default_chc not accessible: No such file or directory.
git@github.ibm.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (D:\Users\rophy\npm\node_modules\node-red\red\runtime\storage\localfilesystem\projects\git\index.js:48:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  stdout: '',
  stderr: 'Warning: Identity file C:Usersrophy.node-redprojects.sshkeys__default_chc not accessible: No such file or directory.\ngit@github.ibm.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n',
  code: 'git_auth_failed',
  remote: 'origin' }
```

### What do you expect to happen?

SSH key should work, instead of complaining "No such file or directory".
Notice in the error message that path separators `\`  of ssh key are missing, may be this is the cause? (say, ssh key was saved with incorrect handling of slashes in windows)

### Please tell us about your environment:

- [x] Node-RED version:  v0.18.2
- [x] node.js version: v8.9.3
- [x] npm version: v5.6.0
- [x] Platform/OS: Windows 7 
- [ ] Browser:

**Comment by knolleary** [comment]
Fixed by e8fd7484b6b19b11d067cf31b612681d4cb42870 and ce5242cfe8efc2c09b4a652578d8f72c894263771 - will be in 0.18.4 released very soon.

Still some issues with HTTPS authentication on Windows 10 - but ssh urls all working now.

**Comment by scelle** [comment]
> Still some issues with HTTPS authentication on Windows 10 - but ssh urls all working now.


@knolleary 
trying to connect to remote repo on windows 10, using https, without succes.  No feedback messages, just timing out after some time.    You mentioned there are still some issues.  Is this still the case?  is this documented somewhere?

**Comment by mannharleen** [comment]
++ for HTTPS GIT connection on Windows10
