### ISSUE TITLE
MQTT connection doesn't work behind a proxy.

### ISSUE THREAD

**Issue by stefanDeveloper** [node-red/node-red#1651]
### What are the steps to reproduce?
1.  Node-Red started behind a proxy
2.  Try to connect to a MQTT Broker outside of the company network

### What happens?
`1 Mar 09:46:15 - [info] [mqtt-broker:71f14e32.a2d1e] Connection failed to broker: "clientId"@mqtt://mqtt.relayr.io:1883`

In the nodes/core/io/10-mqtt.js File there are no checks if an http_proxy environment variable is set.
I already asked this question in the mailing list, but I didn't get an answer.

### Please tell us about your environment:

- [v0.18.3] Node-RED version:
- [8.9.4] node.js version:
- [5.6.0 ] npm version:
- [Windows 10 ] Platform/OS:
- [Google Chrome] Browser:

### To solve it
 A possible solution is to check if this environment variable is already set. When it's set, a HttpsProxyAgent must be define in the wsOptions of the MQTT connect options. 
```
// check if proxy is set in env
var prox;
if (process.env.http_proxy != null) { prox = process.env.http_proxy; }
if (process.env.HTTP_PROXY != null) { prox = process.env.HTTP_PROXY; }
if (prox) {
    // Set BrokerUrl wss:// for mqtt connection with proxy. E.g. in node_modules/mqtt/examples/wss/client_with_proxy.js
    this.brokerurl = 'wss://'+ this.broker + ":" + this.port;
    var parsedUrl = url.parse(this.brokerurl);
    var proxyOpts = url.parse(prox);
    // true for wss
    proxyOpts.secureEndpoint = parsedUrl.protocol ? parsedUrl.protocol === 'wss:' : true;
    // Set Agent for wsOption in MQTT
    var agent = new HttpsProxyAgent(proxyOpts);
    node.options.wsOptions = {
        agent: agent
    }
}
```

Are there any plans to add proxy settings for MQTT like above in the next release?

**Comment by knolleary** [comment]
Thanks for the detailed issue description - that always makes life easier.

> Are there any plans to add proxy settings for MQTT like above in the next release?
There weren't any plans to as this wasn't something we were aware of until now... 😁

Would happily look at a pull request that includes your proposed fix.

**Comment by stefanDeveloper** [comment]
Thanks for the quick response.

I'll create a pull request for this.

**Comment by stefanDeveloper** [comment]
Just one hint. I realized that the connection over `wss` need the port 443 instead of 1883 or 8883, obviously for SSL. 

![hint](https://user-images.githubusercontent.com/18898803/36837313-4db107ca-1d3c-11e8-81d2-a8f10e334869.JPG)
I specified this in the MQTT Broker. 

Is this oke for you, or should I do an other approach? Otherwise I'm not sure if anybody will figure this out.

**Comment by dceejay** [comment]
if it can auto switch when you switch protocol (and back again) - that would be good.

**Comment by stefanDeveloper** [comment]
I'm sure if this will work because the npm MQTT package only works with `wss` when an agent in the wsOptions is defined.

**Comment by stefanDeveloper** [comment]
@dceejay can you give me some more details what you exactly mean?

So far, I implemented it like in the code snippet above. I suggest that when a proxy is defined the user  should be able to disable the proxy setting in mqtt to auto switch.
Something like this:
![proxy](https://user-images.githubusercontent.com/18898803/36843704-05c3f404-1d50-11e8-8625-ddc9b9f8f0f9.JPG)

Otherwise auto switch to:
![proxy1](https://user-images.githubusercontent.com/18898803/36843841-83eed2c2-1d50-11e8-80be-2a7de23d7b84.JPG)

And when no environment variable is defined, there are no proxy to enable, of course.

**Comment by dceejay** [comment]
in your first example... how does it know I want to use http/ws ? I may well be with happy with mqtt...
so it should only show the proxy option if the server starts with `ws:` or `wss:`

My thought was - should we also detect if httpProxy is set and if so then force it to 443 - ie no option at all ?

**Comment by stefanDeveloper** [comment]
> My thought was - should we also detect if httpProxy is defined and if so then force it to 443 - ie no option at all ?

I would recommend it, my examples are nonsense. We only have to check if an http_proxy is defined, then we tunnel a wss connection through a proxy, i.e. no option at all. That's it. Sorry for that :-)

**Comment by knolleary** [comment]
Just to clarify, in the current MQTT node, the use must explicitly use `ws://` (or `wss://`) at the front of the path in order to enable a websocket connection. Only in that case should we then check the proxy env var for additional configuration. If the host doesn't start with `ws://` then its a regular tcp connection and the httpProxy settings are irrelevant.

**Comment by knolleary** [comment]
Closed via #1652

**Comment by khairiGithub** [comment]
> ### What are the steps to reproduce?
> 
> 1.  Node-Red started behind a proxy
> 
> 2.  Try to connect to a MQTT Broker outside of the company network
> 
> 
> 
> ### What happens?
> 
> `1 Mar 09:46:15 - [info] [mqtt-broker:71f14e32.a2d1e] Connection failed to broker: "clientId"@mqtt://mqtt.relayr.io:1883`
> 
> 
> 
> In the nodes/core/io/10-mqtt.js File there are no checks if an http_proxy environment variable is set.
> 
> I already asked this question in the mailing list, but I didn't get an answer.
> 
> 
> 
> ### Please tell us about your environment:
> 
> 
> 
> - [v0.18.3] Node-RED version:
> 
> - [8.9.4] node.js version:
> 
> - [5.6.0 ] npm version:
> 
> - [Windows 10 ] Platform/OS:
> 
> - [Google Chrome] Browser:
> 
> 
> 
> ### To solve it
> 
>  A possible solution is to check if this environment variable is already set. When it's set, a HttpsProxyAgent must be define in the wsOptions of the MQTT connect options. 
> 
> ```
> 
> // check if proxy is set in env
> 
> var prox;
> 
> if (process.env.http_proxy != null) { prox = process.env.http_proxy; }
> 
> if (process.env.HTTP_PROXY != null) { prox = process.env.HTTP_PROXY; }
> 
> if (prox) {
> 
>     // Set BrokerUrl wss:// for mqtt connection with proxy. E.g. in node_modules/mqtt/examples/wss/client_with_proxy.js
> 
>     this.brokerurl = 'wss://'+ this.broker + ":" + this.port;
> 
>     var parsedUrl = url.parse(this.brokerurl);
> 
>     var proxyOpts = url.parse(prox);
> 
>     // true for wss
> 
>     proxyOpts.secureEndpoint = parsedUrl.protocol ? parsedUrl.protocol === 'wss:' : true;
> 
>     // Set Agent for wsOption in MQTT
> 
>     var agent = new HttpsProxyAgent(proxyOpts);
> 
>     node.options.wsOptions = {
> 
>         agent: agent
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> Are there any plans to add proxy settings for MQTT like above in the next release? 

Hi, I am a new member here. I am also facing the same issue of working with Node-Red MQTT broker outside of corporate http proxy. How can I use Node-Red to connect to a public mqtt broker such as hivemq behind a corporate proxy? Really appreciate your feedback. Thank you!

**Comment by knolleary** [comment]
Hi @khairiGithub 

the best place to get help with general how-to questions is the forum - https://discourse.nodered.org - rather than on an issue that has been closed for over 2 years.

Thanks.
