### ISSUE TITLE
Email node breaks at high refresh rates

### ISSUE THREAD

**Issue by DeanMauro** [node-red/node-red#1659]
When the refresh rate in a **Mail in** node is set above 1,000,000, the node breaks, refreshing constantly and blocking all other operations. 

### What are the steps to reproduce?
Add an **Email in** node to the flow and set the refresh rate to 1000001 seconds.
### What happens?
The node goes crazy, refreshing multiple times per second
### What do you expect to happen?
The node would refresh every 1000001 seconds (11.5 days)
### Please tell us about your environment:

- [ ] Node-RED version: 0.17.5
- [ ] node.js version: 4.2.6
- [ ] npm version: 3.5.2
- [ ] Platform/OS: Ubuntu Linux
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Hi @DeanMauro, thanks for the issue report. My guess is such a large value is wrapping when passed to setTimeout - we saw a similar issue with another node recently istr. This is going to be a limitation of the node - unless there's a particular need for the node to only check for new email with such a large interval.

This repo is actually for the core of node-red; the email node is maintained over here: https://github.com/node-red/node-red-nodes - so any fix will be done over there, not here.

**Comment by knolleary** [comment]
Fix applied to the node and published as version 0.1.29.

If the node is configured with a value that exceeds the limit, it logs an error and clips the value to the maximum interval available.
