### ISSUE TITLE
Install fails on rpi3 with OSMC

### ISSUE THREAD

**Issue by Head** [node-red/node-red#1668]
### What are the steps to reproduce?
install fresh OSMC, install node-red

### What happens?
I get an loop with
`Node-RED is not yet fully installed
Fetching Node-RED update.`

I had errors with `lxpanelctl` not installed, `/bin/ping` was a symlink and the group `gpio` didn't exist.
Also the optional bcrypt dependency caused some errors.
But in the end it was just the `if [[ $(which node-red) ]]; then` what is failing. I can start it with running `/opt/node/lib/node_modules/node-red/bin/node-red-pi`

### Please tell us about your environment:

- [x] Node-RED version: 0.18.4
- [x] node.js version: v8.10.0
- [x] npm version: 5.6.0
- [x] Platform/OS: OSMC 2018.02-1
- [ ] Browser: /

Something about the PATH and `/opt/node/lib/node_modules/` going wrong here?

**Comment by knolleary** [comment]
How exactly are you installing node-red? What command are you running?

**Comment by knolleary** [comment]
By OSMC, following a google search, I assume you mean https://osmc.tv/ ?

You'll have to give us some background on it - is it a full SD card image your download or something you install on top of Raspbian?

We don't have the bandwidth to support every possible image provided by other projects - but it should just be a case of identifying what dependencies are missing and ensuring they are satisfied.

**Comment by Head** [comment]
I was trying to install with `bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)` after I had a HARD TIME trying with docker (gave up on that one...)

Yep, it's a "normal" Debian with focus on running kodi:
`osmc@osmc:~$ cat /proc/version`
`Linux version 4.14.15-5-osmc (root@vero3-db) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP PREEMPT Sun Mar 4 08:39:02 UTC 2018`

**Comment by knolleary** [comment]
>  a HARD TIME trying with docker (gave up on that one...)

I haven't seen a response to my questions on the issue you raised on the docker repo - https://github.com/node-red/node-red-docker/issues/67#issuecomment-372681212

If you want to run the dockerized version of NR on your Pi, you _should_ just be able to run:

    docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker:rpi

You do not need to build the docker image from scratch.

> I had errors with lxpanelctl not installed, /bin/ping was a symlink and the group gpio didn't exist.

The update script is intended for running on Raspbian. Clearly the OSMC image is different.

It may be easier to discuss on slack or the mailing list, where others in the community may be able to help out, rather than depend on the core development team.

**Comment by Head** [comment]
Yep, sorry for opening two issues. Thought it's unrelated. Maybe also not worth fixing the install script for _strange_ Debian packages. But adding a line to the **Container versions** sections how to run it with the quick start part could maybe save a lot of time for other docker newbs.
Thank you very much! I'm now cleaning up the mess I made and start playing with node-red! <3

**Comment by knolleary** [comment]
No problem - glad you're making progress, and thanks for the feedback on the docker docs.

**Comment by dceejay** [comment]
@Head - FWIW I just installed a clean SD card with OSMC, ssh in and ran the command line bash installer for Node-RED as the osmc user and it works  (almost) - enough to start and run.

It is missing **make** so it doesn't compile in a couple of nodes that are optional (Most notably serialport)
If this is required then 

    sudo apt-get install build-essential

then re-run the install.
I don't think we want to force people to have to have that if they don't want to so I'm going to leave it as-is for now.

(ok so it also doesn't show green ticks for \u2714 during install progress, but...)

**Comment by dceejay** [comment]
You don't get the Pi GPIO nodes as the underlying libraries are not there - and don't seem to be in the osmc repo.
