### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by badryan** [node-red/node-red#167]
Hi,

This NodeRED crash came out of thin air:

26 Feb 15:15:20 - [red] Uncaught Exception:
26 Feb 15:15:20 - Error: write EIO
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

That's git log
commit a0aec3f8f1c2b5591e26e4c5582eb6fa72790ddf
Author: Nick O'Leary <nick.oleary@gmail.com>
Date:   Sun Feb 23 20:58:24 2014 +0000

on a Raspberry Pi running the latest Raspian with a flow involving serial port communication and MQTT.

**Comment by knolleary** [comment]
Not sure we're likely to get to the specific cause of this and we've not had any similar issues since it was raised over a year ago.

Closing.

**Comment by nomissniggih** [comment]
Hi for anyone who has this issue, as I did, this can be resolved by upgrading npm before you install node-red.
