### ISSUE TITLE
Several core nodes do not display a name in the node icon when dragged to a flow

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red#1673]
### What are the steps to reproduce?
Drag the function, template, comment, watch or exec node from the sidebar to a flow

### What happens?
You will see an icon with no text identifying it

### What do you expect to happen?
The icon should have, as a default, the name of the node

### Please tell us about your environment:

- [ ] Node-RED version:  v0.18.4
- [ ] node.js version: v6.11.0
- [ ] npm version: 3.10.10
- [ ] Platform/OS: OSX 10.12.6
- [ ] Browser: Safari

**Comment by juggledad** [comment]
So do you mean you have a lot of functions that are blank in your flows?? Isn't that confusing? (grin) 

Once you add a name to the function it shows. I just tought it was strange that all but these 5 nodes displayed the name of the node (or something else) and for consistency these should too.

**Comment by dceejay** [comment]
yes - basically agree. 
Multiple function node - confusing ? - occasionally - but I've never felt the need for them all to tell me they are function nodes.
The watch node reports an error if it doesn't have anything entered so it's only blank if it's in error anyway. Comment node - well it's a blank comment... say no more :-)  
Before you could change Icons you could always tell what something was by it's icon so it didn't really matter - now that we can change icons I guess it make more sense to at least have the name be consistent, though as I suggested we may want to think about translation at the same time.
