### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by deinok** [node-red/node-red#1674]
### What are the steps to reproduce?
Clone, `npm install` and `npm start`

### What happens?
Server don't lisents to IPv6 address

### What do you expect to happen?
To lisent IPv6 address

### Please tell us about your environment:

- [x] Node-RED version: 0.18.3
- [x] node.js version: 9.3
- [x] npm version: 5.6
- [x] Platform/OS: Win10
- [x] Browser: Chrome 63

**Comment by dceejay** [comment]
In settings.js you can set what you want to listen to - you can change it as follows to enable ipv6

        uiHost: "::",

**Comment by deinok** [comment]
Thanks @dceejay , but is there a reason to have IPv6 blocked by default?

**Comment by dceejay** [comment]
I don't think it is - maybe is just the way express defaults ?  Will investigate.

**Comment by deinok** [comment]
Nope, the following code:
```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

Executed with `node ./app.js`

Is exposed at IPv4 and IPv6.

I can send a PR to fix this if required

**Comment by dceejay** [comment]
no worries - Think it's just line 180 of red.js

**Comment by deinok** [comment]
Seems like replacing the "0.0.0.0" with "::" (The IPv6 Addr) enables IPv6 and also IPv4

**Comment by dceejay** [comment]
yes
