### ISSUE TITLE
Moving node does not cause inject node to fire once on "Deploy Modified flows"

### ISSUE THREAD

**Issue by andig** [node-red/node-red#1679]
Started from https://github.com/node-red/node-red-nodes/issues/418

### What are the steps to reproduce?

Use 

    [{"id":"47661190.83f43","type":"inject","z":"e3e3666a.550d1","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":"0.1","x":170,"y":110,"wires":[["97b7a741.920c2"]]},{"id":"2755aae3.99049e","type":"debug","z":"e3e3666a.550d1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":560,"y":240,"wires":[]},{"id":"97b7a741.920c2","type":"trigger","z":"e3e3666a.550d1","op1":"received","op2":"missing","op1type":"str","op2type":"str","duration":"2","extend":true,"units":"s","reset":"","bytopic":"all","name":"","x":360,"y":170,"wires":[["2755aae3.99049e"]]}]

Move a single node around, then "Deploy modified flows" 

### What happens?

Nothing.

### What do you expect to happen?

Injected message should trigger output.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.4 on docker
- [ ] Platform/OS: Synology NAS
- [ ] Browser: Safari

**Comment by knolleary** [comment]
Simply moving a node is not regarded as a material change to the node configuration to consider it need to be restarted on deploy.

In the early days it was treated as a material change, but user feedback was they didn't like the act of 'tidying up' their flow appearance leading to everything being restarted.

**Comment by andig** [comment]
That makes perfect sense- but then it shouldn't enable the deploy button?

**Comment by dceejay** [comment]
but it fires if we deploy full... (not unreasonably).
Fair enough if you move things on other flows... but if you move things on a flow and the deploy button lights up then anything on a flow that has changed should count ?

**Comment by knolleary** [comment]
>  but then it shouldn't enable the deploy button?

If you want the change in position to be saved, you need to deploy.

> but if you move things on a flow and the deploy button lights up then anything on a flow that has changed should count

A move of a node has not been counted as a material change for 2 or 3 years now.

**Comment by andig** [comment]
> If you want the change in position to be saved, you need to deploy.

That's the tricky part. Deploy saves to disk plus restarts runtime. No good idea how to handle the distinction :/

**Comment by knolleary** [comment]
So, just to clarify, the issue as raised is describing intentional behaviour. I don't think there's anything more to do here, so unless I've missed a concern here, can we close?

**Comment by andig** [comment]
Thank you for investing time in nideßred!
