### ISSUE TITLE
Trigger Node does not support concurrent messages

### ISSUE THREAD

**Issue by kenime** [node-red/node-red#1683]
### What are the steps to reproduce?
I have a trigger node followed by an IO node (e.g. Watson Conversation Node). If IO node returns something, it will reset the trigger node.

### What happens?
When the IO node is waiting for respond (msg A), it will wait asynchronously and Node Red will start to process another message (msg B). In such case, when msg A completed IO and reset trigger node, it will reset msg B's trigger as well.

### What do you expect to happen?
The reset should only reset the trigger bound to the corresponding message.

### Please tell us about your environment:

- [ ] Node-RED version: Latest
- [ ] node.js version: 6.11.1
- [ ] npm version: 3.x (the one coming with node.js)
- [ ] Platform/OS: Any
- [ ] Browser: Any

**Comment by knolleary** [comment]
Hi @kenime,
You are right that the trigger does not treat individual messages separately - that is working as designed.

You can configure the node to treat each msg.topic as a separate 'stream' of messages to be triggered - so to achieve what you want, give each message a unique msg.topic property and enable that option in the node.

**Comment by kenime** [comment]
Thanks @knolleary! I missed this option as I have just recently upgraded from v0.17.5 which does not have this.
