### ISSUE TITLE
Can't change button background color in Internet Explorer

### ISSUE THREAD

**Issue by kas2** [node-red/node-red#1687]
- Within IE11, when changing button/Background to any color, dashboard always keeps it blue (default)
  button/Colour (foreground) acts as expected.

- Same actions are 100% OK using Chrome

Strange isn't it...

Windows 10, Raspberry Pi Zero W, node-red v0.18.4

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

As this is related to node-red-dashboard and not the core of node-red, please raise it here: https://github.com/node-red/node-red-dashboard and provide an example flow that demonstrates the issue for you.

Thanks!
