### ISSUE TITLE
UI needed to reset credentials and start flows when projects are disabled and credentials secret is wrong

### ISSUE THREAD

**Issue by mblackstock** [node-red/node-red#1689]
### What are the steps to reproduce?

1. Ensure projects is disabled in Node-RED settings.
2. Set a `credentialsSecret` in the `settings.js` file.
3. Start Node-RED
4. Deploy a simple flow with credentials.
5. Stop Node-RED
6. change the `credentialsSecret` in the `settings.js` file
7. start Node-RED
8. The user interface will present an alert "Flows Stopped as credentials could not be decrypted..." and a "Setup Credentials" button.
9. Click on the button.

### What happens?

A blank dialog called "Project Information" appears with a single close button.

### What do you expect to happen?

if credentials secret provided in settings.js:
- UI dialog to allow user to confirm reset/delete credentials file,

otherwise
- Dialog to allow user to enter credentials secret explicitly, saved in the .config file

### Please tell us about your environment:

- [x] Node-RED version: 0.18.5
- [x] node.js version: 8.9.3
- [x] npm version: 5.6.0
- [ ] Platform/OS: Mac
- [ ] Browser: Chrome

**Comment by tedhuang** [comment]
Link to beginning of discussion on Slack:
https://node-red.slack.com/archives/C9RSU6S56/p1522345959000438

**Comment by tedhuang** [comment]
Added a pull request #1694 

[Demo of PR](https://i.imgur.com/bNUORg2.gif)

**Comment by knolleary** [comment]
#1694 merged
