### ISSUE TITLE
Need Hierarchical Categories and Nodes

### ISSUE THREAD

**Issue by gloriajsf** [node-red/node-red#1693]
### What are the steps to reproduce?
Just open any existing project, you know it
### What happens?
Add new feature
### What do you expect to happen?
Currently, Node-RED only allows flat structured categories, that restricts the possibilities of forming complicated category-category and category-node relations. 
As development work accumulates and number of nodes increases, a flat structured design poses limits.

It would be nice to have sub-categories or great-sub-categories inside existing core categories or new categories. So that even if user doesn't recall a particular node's searchable phrase, as long as she/he recalls a super-category or great-super-category, they would be able to locate or target those categories.
### Please tell us about your environment:
Mac OS and Linux Ubuntu

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by Digicrat** [comment]
I think this would be a great addition, though it might be logistically difficult to implement as a default hierarchy.

A more flexible approach would be to allow for a user-configurable grouping, like a "Favorite Nodes" feature.  This would provide similar functionality as the original suggestion, but should be less disruptive to implement.  

Such a feature might look like:
- Tab on the nodes listing to switch between existing categorical/full view and new 'favorites' menu
- User can right-click (or long touch) on any node in categorical view and 'Add to Favorites'.  A submenu can provide the ability to directly choose folder/subfolders. There are plenty of JS libraries to implement such menus -- and such right-click menus would be useful elsewhere in the UI as well.
- User can edit favorites at any time to add/remove/move entries between preferred categories with arbitrary nesting of folders/categories. 
- User can place a single node in multiple folders under their 'Favorites' if desired.
- Favorites list can be imported/exported

**Comment by knolleary** [comment]
As per our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) (that are shown in the issue template presented when opening a new issue), discussions around feature requests belong on the [forum](https://discourse.nodered.org/c/development/feature-requests).

I'm closing this issue to ensure discussion is had in the right place.
