### ISSUE TITLE
Errors in subflows are difficult to trace

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#1698]
When an error occurs within a subflow the error that appears in the debug pane doesn't contain a link to that subflow, this makes it hard to debug error when multiple subflows are present. Would be nice if hovering on the error message could hilight the subflow instance that triggered the error and clicking the link could open the flow template and hilight the node that caused it.

**Comment by knolleary** [comment]
A message coming from a node inside a subflow will now:

 - highlight the subflow instance node when the msg is hovered
 - clicking on the node id in the msg will reveal the subflow instance node
 - if the subflow template is open, highlight the node the msg came from when the msg is hovered

This isn't quite what you suggested - it is a two step process to get to the node as you have to manually open the subflow template. If we jumped straight to opening up the subflow template, you wouldn't know which instance of the subflow the error had come from.

Nor does this work if the subflow is inside another subflow - it only works one level deep. Will need a fair bit more work to make it work at arbitrary depths of subflow nesting.

**Comment by natcl** [comment]
Thanks ! That will already help alot!
