### ISSUE TITLE
on script error, send the full err

### ISSUE THREAD

**Issue by farfromrefug** [node-red/node-red#1699]
[here](https://github.com/node-red/node-red/blob/master/nodes/core/core/80-function.js#L221)
when you catch a script error sometimes there is no stack.
If i add a console.log within the catch i get the full stack. But the errorMessage does not have the stack.

For me this is important because on the server side i catch all node error by overriding flows.handleError. The idea is to show to the user where the error happened in the function script. The idea is to help them.

Would it be possible on catch to add "error" to the msg so that we can do whatever we want with it?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. 

The [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you were shown when raising this issue highlighted that we prefer to first discuss feature requests/suggestions on the [mailing list](https://groups.google.com/forum/#!forum/node-red) or [slack team](https://nodered.org/slack) in the first instance.

You say you're overriding flows.handleError - why are you doing that? It isn't part of the public api so there's no guarantee it will always be there.

I haven't looked at this in more recent versions of node, but I found the stack returned by the vm module to be of little use. Maybe I didn't test with complex enough Function node code. Do you have some examples where having the stack is useful?

Thanks!

**Comment by farfromrefug** [comment]
I created a related PR
https://github.com/node-red/node-red/pull/1700

**Comment by knolleary** [comment]
Merged #1700
