### ISSUE TITLE
remove usage of Buffer constructor

### ISSUE THREAD

**Issue by boneskull** [node-red/node-red#1709]
The `Buffer` constructor is newly [deprecated again](https://nodejs.org/api/buffer.html#buffer_class_buffer) in Node.js v10.

`Buffer.from` (or `Buffer.alloc`, depending) is preferred; the [safe-buffer](https://npm.im/safe-buffer) package provides a polyfill for Node.js v4.x, which I think we're on the hook to support for awhile.

**Comment by knolleary** [comment]
Fixed in `dev` branch for 0.20
