### ISSUE TITLE
Investigate use of Domains

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#171]
If a node doesn't handle all the errors it should, it will crash all of node-red. This is not ideal and a pain to debug - see #169 for example.

Node 0.8 added the `domain` module so you can compartmentalise the error handling of an application.

Need to investigate the consequences of running each node in its own domain - then any uncaught error could trigger just that node to be recreated, rather than crash the entire runtime.

**Comment by mcollina** [comment]
:-1: Domains will be deprecated at some point, at least this is what the node core team said. Better not to use them, also they work very badly and are hard to test.

**Comment by knolleary** [comment]
@mcollina interesting - got a link to anything to read on that?

**Comment by mcollina** [comment]
Not really. This was told in a nodeup show and at some conferences. Anyway,
almost nobody uses them in production, as they cause more harm than what
they solve.
Il giorno ven 30 gen 2015 alle 18:07 knolleary <notifications@github.com>
ha scritto:
