### ISSUE TITLE
Callbacks don't work as expected in function node

### ISSUE THREAD

**Issue by candronikos** [node-red/node-red#1718]
Using async functions that allow the user to pass callbacks seems to cause problems when another message comes in before it's already processed in the function node.

## Version details
- [ ] Node-RED version: v0.18.4
- [ ] npm version: 3.10.10
- [ ] node.js version: v6.14.1
- [ ] Platform/OS: Raspbian; `uname -a` Linux USER 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

I've noticed this primarily with the requests library in the function node:

```
moment = context.global.moment;
request = context.global.request;
metaDataServer = context.global.get('config').metaDataServer

var now = moment().tz('Australia/Sydney')
var yesterday = now.clone().subtract(1,"days")
ret = { series_dict: {}, points: [], point_dict:{} }

map = context.get("map") || {}

//node.warn(msg)

request_func = function (error, response, body) {
    lines = body.split('\n')
    meta = lines[0].match(/ id\:(.*?)(?: |$)/)
    id = meta[1]

    values = lines.slice(2)

    ret.points.push(id)
    ret.series_dict[id] = values

    //meta = context.get("meta") || {}
    //node.warn(id)
    meta_dict = context.get("meta") || {}

    if(id in meta_dict)
        ret.point_dict[id] = meta_dict[id]

    if(ret.points.length == point_array.length) {
        ret.equipRef = map[id]
        
        ret.equipMeta = msg.equipMeta
        node.send(ret)
        ret = { series_dict: {}, points: [], point_dict:{} }
    }
};

point_array = msg.payload

for(var i in point_array) {
    point = point_array[i];

    ret.equipRef = point.equipRef.value

    meta = context.get("meta") || {}
    meta[point.id.value] = point
    context.set("meta",meta)
    //node.warn(meta)

    map[point.id.value] = point.equipRef.value
    context.set("map",map)

    body = 'request:historical_data'

    auth_section = metaDataServer.username + ':' + metaDataServer.password + '@'
    url = 'http://' + auth_section + metaDataServer.url + '/readHistoricalData'
    request.post({url:url,body:body}, request_func)
}

return null;
```

The variable `ret` has the issue here. I believe it's because it is altered from the callback. The function seems to mix up this variable with values from other messages. I thought that the context was spawned for each message and run in isolation. Is there a work around here? At the moment, I'm using a rate limiter to ensure that the node has finished processing the message before taking a new one.

## EDIT
* Version details (2018-05-07)

**Comment by knolleary** [comment]
Hi, you were given an issue template to fill in that asks for some standard information from you to save me from having to write this comment... What version of node.js, node-red etc are you using?

Are you able to provide a more simple example that demonstrates the issue?

We do reuse the VM context so we don't have the overhead of spinning up a new one for every message... So whilst I'm not in a position to try it out right now, what you describe is plausible.

You could try using a closure to ensure the variables your callback uses are in scope of the particular instance of the callback function.

Equally, if you're just doing an http request, we have a node for that, so you could avoid the asynchronous callback altogether.

**Comment by candronikos** [comment]
* Added version details as per @knolleary 's request.
* I'll get back to you about a simpler version of the question. Basically as long as the callback takes long enough that the next message comes through, I tend to get unexpected results which are very hard to debug!
* If I understand correctly, are you saying to enclose everything that I want preserved in another function and then call that within the function node? Are you saying that the variables of this closure will be protected from whatever can happen from a subsequent message?
* The reason I'm not using the node is because I want to combine the results from multiple requests

**Comment by francoishill** [comment]
Hi @candronikos, your `point_array` seems to an array that comes from the previous node's `msg.payload`, right?

You should be able to use the `split` node, then do an `http request` on each and then `join` them again. In the `join` node you can choose `automatic` which states "when paired with the split node, it will automatically join the messages to reverse the split that was performed.".

So to summarize it will be `split -> http request -> join`. You can also add anything else before/after the http request that will execute on each "point". For instance, if you want to process your response you can add a `function` after it.

**Comment by candronikos** [comment]
@francoishill Those are good points. And had I know that sooner I may have saved myself some trouble :)

Thanks for your feedback. I think I have enough to close this issue.

**Comment by francoishill** [comment]
Glad we could help @candronikos
