### ISSUE TITLE
Cant click Deploy

### ISSUE THREAD

**Issue by bphermansson** [node-red/node-red#1724]
I changed some things in the flows and Deploy goes red. But when I click it nothing happens. 

- [ ] Node-RED version: Node-RED v0.18.4
- [ ] node.js version: v8.11.1
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Rock64 / Debian stretch/sid
- [ ] Browser: Mozilla Firefox

The console says:
TypeError: n.wires[p.sourcePort] is undefined[Läs mer]  red.min.js:16:31171
Tom sträng skickad till getElementById(). vendor.js:2:24487

The last message means "Empty string sent to getElement...

What can be wrong?

**Comment by knolleary** [comment]
Hi, sorry for the slow response. Is this still an issue or have you found a way past it?

Looking at the code, I can see where the error is being hit, I just can't figure out how you've got into the situation to hit it. The fix to guard against the error is simple enough, but it would be interesting to understand how you've hit it at all.

**Comment by bphermansson** [comment]
@knolleary I did a new install on a Raspberry Pi, then moved my flows from an old installation. Only way I got past it was to build the flows from scratch instead of moving them.
