### ISSUE TITLE
No debug messages in the editor

### ISSUE THREAD

**Issue by oehm2007** [node-red/node-red#1725]
Hi, I have an issue with the debug window on the right sode of the editor. In former times it just worked as designed, like showing all the messages entering the debug node. Now I just cannot make it work again. Nothing is shown in the debug window. I already reinstalled node- red, restarted several times, changed the browser, deleted the cache of the browser. The only weired thing os, that I can see the log inside the console with node-red-log. Everything is there, but its not shown in the editor window. It juat drives me nuts, because I tried a lot of things now, but the behavior didnt change. I really appreciate any help with that issue. So many thanks in advance. 

### What are the steps to reproduce?
Just adding a debug node to a flow.
### What happens?
Empty debug window in the editor
### What do you expect to happen?
Guess what :-)
### Please tell us about your environment:
Node-red is installed on a raspberry pi 3 within openhabian. 
- [x ] Node-RED version: updated to v0.18.4
- [ x] node.js version: v6.14.2
- [x ] npm version: 3.10.10
- [ x] Platform/OS: Openhabian Openhab Snapshot 2.3.0
- [x ] Browser: Chrome and IE

**Comment by knolleary** [comment]
Have you looked in your browser's javascript console for any error messages?

**Comment by oehm2007** [comment]
Yes, there are no errors. Everything should be fine.

**Comment by oehm2007** [comment]
Problem solved :-) . The virus scanner/firewall was obviously blocking the port.
