### ISSUE TITLE
Editor: wireClippedNodes is not defined

### ISSUE THREAD

**Issue by eithe** [node-red/node-red#1726]
### What are the steps to reproduce?
In [editor/js/nodes.js line 1037](https://github.com/node-red/node-red/blob/f4c2938b415e5c584419875fbe4f50c9a4032cbb/editor/js/nodes.js#L1037) if 'wires' is longer than outputs, it is designed to clip the wire.

### What happens?
It tries to add the node to an undefined array wireClippedNodes on line 1039. The issue is related to https://github.com/node-red/node-red/commit/f4c2938b415e5c584419875fbe4f50c9a4032cbb

The error halts further processing (on Chrome at least) so no nothing is rendered on the editor canvas.

Edit: Obviously there's also something wrong somewhere in my flows, but it's a big project so it's like looking for a needle in a haystack. Downgrading to 0.18.4 makes the editor work again.

### What do you expect to happen?

Clip the wire and continue as normal. Perhaps notify the user about the issue?

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.5
- [ ] node.js version: :v8 docker
- [ ] npm version: :v8 docker
- [ ] Platform/OS: :v8 Docker host, Windows client
- [ ] Browser: Chrome (latest)

**Comment by knolleary** [comment]
Thanks - apologies for the inconvenience. Fix pushed, will be doing a new maintenance release in the next few days so keep an eye out for that.
