### ISSUE TITLE
Messages no longer retained

### ISSUE THREAD

**Issue by realjax** [node-red/node-red#1729]
When using the mqtt output node, messages are not  retained. Either set by the msg itself (retain = true;) or setting retain to true in the configuration of the node itself does not have the desired effect.

-  Node-RED version: 0.18.4: 
-  node.js version:v 8.11.1
-  npm version: 5.6.0
-  Platform/OS: Armbian

MQTT server : Mosquito 1.3.4

**Comment by hardillb** [comment]
I've just tested this with a 0.18.6 and its working fine.

I would sayt this is much more likely to be a problem in that incredibly ancient version of mosquitto you are running. The version 1.5.0 has just shipped, but the latest "stable" build is 1.4.15

**Comment by realjax** [comment]
Haha that might just be it. Unfortunately theres no new version  (readily) available for the pi. Funny thing is that it did work before. 
Ah well. Looks like a mosquitto upgrade is in order then.
Thanks!

On May 19, 2018 11:37:03 AM GMT+02:00, Ben Hardill <notifications@github.com> wrote:
>I've just tested this with a 0.18.6 and its working fine.
>
>I would sayt this is much more likely to be a problem in that
>incredibly ancient version of mosquitto you are running. The version
>1.5.0 has just shipped, but the latest "stable" build is 1.4.15
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/node-red/node-red/issues/1729#issuecomment-390392899

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by hardillb** [comment]
The version is raspbian is much newer than 1.3 iirc and there are instructions on the mosquitto web site on how to add a ppa to get the latest

**Comment by realjax** [comment]
I just did, now running 1.5 and the problem is solved. Thanks for your help!
