### ISSUE TITLE
Can't uninstall modules

### ISSUE THREAD

**Issue by realjax** [node-red/node-red#1752]
Node-red falsely claims modules are still in use and therefore does not allow uinstall.
I have a feeling it has to do with possible config-nodes which cannot be removed through the UI.  The only way to remove those is to manually alter the flows file.

**Comment by knolleary** [comment]
Have you opened the configuration node sidebar from the main menu and deleted the nodes?

**Comment by dceejay** [comment]
a name of one of these nodes/modules may give us some pointers to help.

**Comment by realjax** [comment]
Any module that has a config node.  Both tradfri modules for instance. Or the Telegram module. Or the Slack modules. Install them. Complete a configuration node and from then one they can no longer be uninstalled.

On June 2, 2018 6:19:47 PM GMT+02:00, Dave Conway-Jones <notifications@github.com> wrote:
>a name of one of these nodes/modules may give us some pointers to help.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/node-red/node-red/issues/1752#issuecomment-394098763

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by realjax** [comment]
Not sure, will try that!

On June 2, 2018 6:19:30 PM GMT+02:00, knolleary <notifications@github.com> wrote:
>Have you opened the configuration node sidebar from the main menu and
>deleted the nodes?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/node-red/node-red/issues/1752#issuecomment-394098750

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by knolleary** [comment]
@realjax so which module are you trying to delete? contrib-telegrambot,  contrib-tradfri or contrib-tradfri?

Are you absolutely certain you've deleted all of the `telegram bot` configuration nodes? If you search your flows (Ctrl-F  with the workspace focussed, or via the drop-down menu) for `telegram` does it find anything?

**Comment by realjax** [comment]
yes, I was absolutely sure I had removed all config nodes but I still could not remove the nodes. However, after a restart of node-red it worked, the remove buttons was clickable again and I manged to remove them without issues!  Wasn't aware that it also required a restart.

Thanks for the help!
