### ISSUE TITLE
NodeRed updates .config.json with local path instead of npm path

### ISSUE THREAD

**Issue by computerFriend** [node-red/node-red#1757]
This is related to a previously reported issue (https://github.com/node-red/node-red/issues/1756) and happens only when developing custom nodes locally, & then deploying them.

### Steps To Reproduce:
- npm install a node locally (e.g., npm install /path/to/node/package),
- run node-red locally
- verify that the module appears in the palette & functions fine)
- stop node-red
- npm uninstall that same module: `npm uninstall {path/to/package}`
- clear browser cache & history
- search entire node red project for the module (Ctrl+F) to ensure it is completely gone from the project (make sure it's gone from .config.json, the node_modules folder, & the package.json files)
- Install the module of the same name, but _from npm_ (not locally), e.g.,
`npm install node-red-contrib-c8y-events`
- start node-red
- observe that the .config.json updates, setting the "file" parameter equal to the local path, instead of the npm path (/usr/local/lib/..etc)

### What happens?
- When updating the .config.json file at runtime, Node-Red appears to "remember" the local path of the locally developed node, and it injects that path to the flow, instead of the correct path from npm.

The node will appear in the palette, but if dragged onto a flow, it will not work, and the console will reveal the following error:

> RED.events.emit error: [nodes:add] TypeError: Cannot read property 'module' of undefined
> red.min.js:16 TypeError: Cannot read property 'module' of undefined
>     at Array.<anonymous> (red.min.js:16)
>     at Object.emit (red.min.js:16)
>     at Object.X [as add] (red.min.js:16)
>     at HTMLDivElement.drop (red.min.js:16)
>     at e.(:443/anonymous function).(anonymous function)._trigger (http://localhost:443/vendor/vendor.js:16:10003)
>     at e.(:443/anonymous function).(anonymous function)._drop (http://localhost:443/vendor/vendor.js:16:40380)
>     at e.(:443/anonymous function).(anonymous function)._drop (http://localhost:443/vendor/vendor.js:16:5029)
>     at e.(:443/anonymous function).(anonymous function).<anonymous> (http://localhost:443/vendor/vendor.js:16:42279)
>     at Function.each (vendor.js:2)
>     at Object.drop (vendor.js:16)

### What do you expect to happen?

When installing a new module from npm, the .config.json should update with the npm path of that module -- not the local path from earlier development.

### Environment:
- [ ] Node-RED version: v0.18.7
- [ ] node.js version: v9.11.1
- [ ] npm version: 6.1.0
- [ ] Platform/OS: MacBook Pro: MacOS High Sierra Version 10.13.4 (17E202)
- [ ] Browser: Google Chrome Version 66.0.3359.181 

### Comments:
This could also reveal some sort of problem with npm? In which case I'll submit an issue to them instead.  Interested to hear your thoughts.

**Comment by knolleary** [comment]
As I said on the previous issue, Node-RED only writes to .config.json what it finds. If it has written the 'local path', then that is where it has found the files.

Comparing the two npm install commands you've listed:

    npm install /path/to/node/package
    npm install node-red-contrib-c8y-events

There is *no* difference in where npm will install the files. The only difference is where it gets the package from in order to install.

If you are in the directory `/home/pi/.node-red`, running either of those npm install commands will result in the module being installed in `/home/pi/.node-red/node_modules/node-red-contrib-c8y-events`.

npm will only install to `/usr/local/lib/..` if you specify the `-g` option with the install command in order to install it as a global module.

**Comment by computerFriend** [comment]
Hey Nick,
Thanks for your patience & explanation. I see what you are saying. I muddled the clarity of my original issue by incorrectly assuming the cause.  Unfortunately, I do still have a problem, which I will restate clearly in another issue.  Sorry about it!  This time I'll be really really clear & won't make any assumptions.  I think this next issue will be the last one I post. 3rd time is the charm!
Best,
Allie

**Comment by knolleary** [comment]
No problem. If you wanted to discuss on slack or the forum before raising an issue then that may be easier. Links at the bottom of nodered.org

**Comment by computerFriend** [comment]
Oh great! I actually just sent you a direct email haha
I will check out the forums as well
