### ISSUE TITLE
Admin Http API GET /nodes does not return list of nodes

### ISSUE THREAD

**Issue by phcollignon** [node-red/node-red#1760]
### What are the steps to reproduce?
curl http://127.0.0.1:1880/nodes

### What happens?
return an html page

### What do you expect to happen?
return json with list of nodes

### Please tell us about your environment:
Docker Node-RED image (image: nodered/node-red-docker)
- [ ] Node-RED version: v0.18.7
- [ ] node.js version: v6.14.2
- [ ] npm version: 6.0.1
- [ ] Platform/OS: Linux 4.13.0-43-generic x64
- [ ] Browser: curl or Chrome

**Comment by knolleary** [comment]
You need to set the `Accept` header to `application/json` to get the list of nodes.

If it is unset, or set to `text/html`, you will get the HTML content for the nodes.

https://nodered.org/docs/api/admin/methods/get/nodes/

**Comment by phcollignon** [comment]
Oops ok thanks for super quick answer ..

Note that for other methods, it works without that header GET /flows, GET /nodes/:node-module ...
