### ISSUE TITLE
The pi 3 B+ crash and reboot when install node-red

### ISSUE THREAD

**Issue by chaim1986** [node-red/node-red#1762]
### What are the steps to reproduce?

pi@raspberrypi:~ $ sudo npm install  -g node-red
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
npm WARN deprecated i18next-client@1.10.3: you can use npm install i18next from version 2.0.0
npm WARN deprecated nodemailer@1.11.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailparser@0.6.2: This project is unmaintained
npm WARN deprecated mimelib@0.3.1: This project is unmaintained
npm WARN deprecated mailcomposer@2.1.0: This project is unmaintained
npm WARN deprecated buildmail@2.0.0: This project is unmaintained
packet_write_wait: Connection to 192.168.89.164 port 22: Broken piperegistry.np
chaimdeiMac-2:~ chaim$ 

### What happens?
The pi crash and reboot.

### Please tell us about your environment:

pi@raspberrypi:~ $ node -v
v8.11.2
pi@raspberrypi:~ $ npm -v
5.6.0
pi@raspberrypi:~ $ 

- [ ] Platform/OS:  pi 3 B+

RASPBIAN STRETCH LITE
Minimal image based on Debian Stretch
Version:April 2018
Release date:2018-04-18
Kernel version:4.14
Release notes:Link

**Comment by dceejay** [comment]
can you try the recommended bash script from the docs ? - and supply the log it writes to /var/logs/ directory ?
Thanks
(In general we prefer how-to type questions via the discourse.nodered.org forum or the slack channel so that the widest possible audience can help)

**Comment by chaim1986** [comment]
thank u , lots of npm cmd can make the pi reboot. so the bug should from the raspberry system. i will close this issue and open it to the raspberry forums.
