### ISSUE TITLE
Sentiment node with differente languages

### ISSUE THREAD

**Issue by deedos** [node-red/node-red#1763]
Hi,

The node sentiment only works with the english language. Once is a core node, I think is not ideal to make a contrib node for that, instead, would be better to change the core node to allow a form of localization to it ?

thanks in advance

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. As per the issue template you deleted whilst raising this, we prefer to have discussions around feature requests on the [forum](https:/discourse.nodered.org) or [slack team](https://nodered.org/slack).

If you are aware of a freely available sentiment analysis library, that doesn't depend on web-based APIs and supports multiple languages, then please do suggest something.

Thanks!
