### ISSUE TITLE
French traduction node_modules/node-red/red/api/editor/locales/en-US

### ISSUE THREAD

**Issue by julienrat** [node-red/node-red#1765]
Hello ! i have made a french version of editor.json  ... available here : https://pastebin.com/kzYRdXUQ
But i don't understand how to configure node-red to select fr-FR folder here
/node_modules/node-red/red/api/editor/locales/fr-FR

**Comment by knolleary** [comment]
It uses your browsers locale setting to pick the language.

For example, in Chrome, open up your browser settings, search for 'languages' and make sure your preferred language is top of the list:

<img width="736" alt="settings" src="https://user-images.githubusercontent.com/51083/41497535-e9c2cde0-714e-11e8-8c83-d0d0e2ca1423.png">

Other browsers will provide a similar capability.

Any contribution will need to be made as a pull-request - we cannot take files outside of the proper contribution process.

**Comment by julienrat** [comment]
THX ! it works like a charm ! pull-request done !

**Comment by GogoVega** [comment]
@knolleary,

If I contribute to complete the French translation, will it be integrated into the new version or is the French not considered to be heavily used?

**Comment by GogoVega** [comment]
Can be closed 🙃
