### ISSUE TITLE
Authentication required for repository login button says "[object Object]"

### ISSUE THREAD

**Issue by asage-me** [node-red/node-red#1768]
### What are the steps to reproduce?
Restart the node-red service
Go to the admin UI
Click the History tab
Expand Commit History
Click the Retry button on manage remote branch

### What happens?
The login button on the Authentication required for repository pop up says "[object Object]"

### What do you expect to happen?
Should say something like login or ok.  Spoke to @knolleary on slack and he mentioned the menus were recently reworked to support translation and this may have been missed.

### Please tell us about your environment:

- [x] Node-RED version: 0.18.7
- [x] node.js version: 6.14.2
- [ ] npm version:
- [x] Platform/OS: Docker
- [ ] Browser:

**Comment by knolleary** [comment]
Fixed in 0.19 branch.
