### ISSUE TITLE
Odd behaviour with CSV Node and including quotation marks. 

### ISSUE THREAD

**Issue by Coderkido** [node-red/node-red#1775]
I need to store a value into CSV as “Value”, but when I add delimited quotations in a function node value, send through the csv node and store into a file, if I open the resulting file in Notepad I get “”“Value”"" but if I open in Excel it shows as “Value”. I have tried a wide variety of ways, but with no success. I either get NO Quotations, or Triple Quotations. Single Quotations seem to work.

I have even tried:
var foo = "foo";
var quotes = String.fromCharCode(34);
foo = quotes + foo + quotes;

### What are the steps to reproduce?
From a function node:

var arr = [];
var foo = "foo"
foo = "\"" + foo + "\""
arr.push(foo);
msg.payload = arr;
return msg;

Send through csv node, view output of msg.payload. 

### What happens?
Any quotation mark with an escape character turns into triple quotations. IE: """foo"""
### What do you expect to happen?
Single quotations. "foo"
### Please tell us about your environment:

[ ] Node-RED version: 0.18.7
[ ] node.js version: 8.11.2
[ ] npm version: 5.6.0
[ ] Platform/OS: Ubuntu 18.04 LTS

### Workaround

Naturally the work around is use the function node and have a CSV function, which I have done, but I think this should be able to be handled by the CSV node.
Node-Red Forum post about this issue and workaround:
**https://discourse.nodered.org/t/solved-csv-nodes-creates-triple-quotations/1112**

**Comment by dceejay** [comment]
The CSV spec - https://tools.ietf.org/html/rfc4180 says that quotes are not required unless the actual value contains a comma (or the separator value)... so we are following the spec.

**Comment by Coderkido** [comment]
That does make sense regarding the current behaviour, however, does that mean that the following should also be supported:

>   7.  If double-quotes are used to enclose fields, then a double-quote
>        appearing inside a field must be escaped by preceding it with
>        another double quote.

I have also tested this and experience the same behaviour as using a normal escape character.

**Comment by dceejay** [comment]
we do  
If I set   var b = 'B"B';
and then send it through the CSV node I get    "B""B"
which is consistent

```
[{"id":"ebbf93e9.4db9d","type":"inject","z":"745a133b.dd6dec","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":70,"y":1940,"wires":[["1dea699d.538d66"]]},{"id":"1dea699d.538d66","type":"function","z":"745a133b.dd6dec","name":"","func":"    \nvar b = 'B\"B';\n    \nmsg.payload = { a:\"A\", b:b, c:\"C\" }\nreturn msg;  \n    ","outputs":1,"noerr":0,"x":210,"y":1940,"wires":[["38ed39ea.1e6486"]]},{"id":"38ed39ea.1e6486","type":"csv","z":"745a133b.dd6dec","name":"","sep":",","hdrin":"","hdrout":"","multi":"one","ret":"\\n","temp":"c,b,a","skip":"0","x":350,"y":1940,"wires":[["cf2e509a.45784"]]},{"id":"cf2e509a.45784","type":"debug","z":"745a133b.dd6dec","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":490,"y":1940,"wires":[]}]
```

**Comment by Coderkido** [comment]
Ah, I see now. Ok based on the RFC then I guess this works as intended. My target application just doesn't meet that standard.

Thanks for clearing that up.
