### ISSUE TITLE
Passing Infinity payload to Debug node seems to hang all debug nodes till browser refresh

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#1778]
### What are the steps to reproduce?
Pass a payload containing the value Infinity to a debug node, see the flow at the end for an example

### What happens?
The debug node shows nothing at all.
In the browser console I see
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
and thereafter no debug nodes show any output until I force a browser refresh.
Browser refresh allows other debug nodes to restart.

### What do you expect to happen?
Debug node should show Infinity

### Please tell us about your environment:

Node-RED version: 0.18.7
node.js version: 8.11.3
npm version: 5.6.0
Platform/OS: Ubuntu 18.04
Browser: Waterfox 56.2.1 and Google Chrome 67.0.3396.99 

Sample flow
[{"id":"ab58f7b7.48084","type":"function","z":"6dc690a3.1abc88","name":"Infinity","func":"msg.payload = 1/0;\nnode.warn(\"1/0 = \" + msg.payload);\nreturn msg;","outputs":1,"noerr":0,"x":359,"y":967,"wires":[["1b9142fe.83800d","90926ede.3f7af"]]},{"id":"983090da.2b36b8","type":"inject","z":"6dc690a3.1abc88","name":"","topic":"","payload":"Trigger","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":115,"y":968,"wires":[["ce92b95f.acae6","ab58f7b7.48084"]]},{"id":"1b9142fe.83800d","type":"debug","z":"6dc690a3.1abc88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":564,"y":966,"wires":[]},{"id":"ce92b95f.acae6","type":"debug","z":"6dc690a3.1abc88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":455,"y":1052,"wires":[]},{"id":"90926ede.3f7af","type":"debug","z":"6dc690a3.1abc88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":542,"y":1007,"wires":[]}]

**Comment by knolleary** [comment]
Thanks - fixed in 0.19 branch.

One side-effect: if you click the 'copy value' button on an element containing `NaN` or `Infinity` they will be replaced with `null` in the JSON that is copied to your clipboard as these two values are not support by JSON.

Oh, also handles `-Infinity` because edge cases are fun.
