### ISSUE TITLE
Passing NaN to debug node shows null payload in complete msg view

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#1779]
### What are the steps to reproduce?
Pass a payload of NaN to a debug node set to show complete msg.
When set to show msg.payload then it operates as expected.
See example flow below

### What happens?
The payload is shown as null in the debug window

### What do you expect to happen?
It should show NaN

### Please tell us about your environment:
Node-RED version: 0.18.7
node.js version: 8.11.3
npm version: 5.6.0
Platform/OS: Ubuntu 18.-04
Browser: Waterfox 56.2.1

Example flow
[{"id":"983090da.2b36b8","type":"inject","z":"6dc690a3.1abc88","name":"","topic":"","payload":"Trigger","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":129,"y":878,"wires":[["765f87eb.43281"]]},{"id":"765f87eb.43281","type":"function","z":"6dc690a3.1abc88","name":"Nan","func":"msg.payload = NaN;\nnode.warn(\"Payload is \" + msg.payload);\nreturn msg;","outputs":1,"noerr":0,"x":364,"y":878,"wires":[["f4737ee.b3c5b8","c63ad58a.db64f8"]]},{"id":"f4737ee.b3c5b8","type":"debug","z":"6dc690a3.1abc88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","x":565,"y":876,"wires":[]},{"id":"c63ad58a.db64f8","type":"debug","z":"6dc690a3.1abc88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":549,"y":924,"wires":[]}]

**Comment by knolleary** [comment]
See my comment in #1778 - thanks!
