### ISSUE TITLE
mqtt node does not set tls servername property

### ISSUE THREAD

**Issue by binnes** [node-red/node-red#1805]
### What are the steps to reproduce?
Use the Watson IoT platform as the broker and set a custom CA and server certificate, then configure the tls connection in Node-RED mqtt node requesting to validate the server

### What happens?
The connection will fail as the server will not respond with the correct certificate because the servername option on the tls connection is not set

### What do you expect to happen?
The connection should connect and the certificate verification should work

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.7
- [ ] node.js version:
- [ ] npm version: 
- [ ] Platform/OS: Raspberry Pi/Raspbian stretch
- [ ] Browser:

**Comment by knolleary** [comment]
I have added servername to the list of options exposed by the TLS config node: https://github.com/node-red/node-red/commit/54d9656f098c38def58d9d7a979a0d9a38a4f084

This will be in the 0.19 release.
