### ISSUE TITLE
Add multiple language support to sentiment node

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#1814]
As discussed here - https://discourse.nodered.org/t/sentiment-node-with-differente-languages/791
the sentiment node is currently English only - there is a drop in replacement library called "multilang-sentiment" - that supports many different languages. It would make sense to move to that to enable wider use of this node.

However - it may make sense to also move it out of the core project into the node-red-nodes project. This issue is to track that so it co-ordinated with the release of 0.19 (or not).

I have code (and tests) ready - just need to know when and where to push it.

**Comment by dceejay** [comment]
code pushed to here - https://github.com/node-red/node-red-nodes/commit/50fc196c6f8d689ac82052d62f1065e6c5924ae6
but not published to npm (yet)

**Comment by knolleary** [comment]
Published to npm and 0.20.0-beta.2 updated to pull it in from there.
