### ISSUE TITLE
Updating Node Red on Windows 7 fails with errors

### ISSUE THREAD

**Issue by rdpaul** [node-red/node-red#1841]
I have Node Red installed on Windows 7 and after updating Node.js to the latest version, I have tried to update Node Red but the process fails with errors.

### What are the steps to reproduce?
Update Node.js by running the latest installer for Windows.

Update Node Red by using the following commands in the Windows Command Prompt:

- npm clean cache --force (without using the --force flag the command does not work)

- npm install -g --unsafe-perm node-red

### What happens?
Am getting the following errors:

npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-
around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt ha
shes
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wide-align@^1.1.0 (node_modules\
node-red\node_modules\gauge\node_modules\wide-align):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input whi
le parsing near '...ndencies":{"tap":"^2.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sshpk@^1.7.0 (node_modules\node-
red\node_modules\http-signature\node_modules\sshpk):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input whi
le parsing near '...:{"tape":">=3.5.0 <4.'

npm ERR! Unexpected end of JSON input while parsing near '...mOxZsrKKzBsw7WDYHPd
QC'

After the above errors, I am still able to run my installed version of Node Red (0.18.4) but the version does not update.

### What do you expect to happen?
Node Red should update smoothly without errors.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.4
- [ ] node.js version: 8.11.3
- [ ] npm version: 5.6
- [ ] Platform/OS: Windows 7
- [ ] Browser: Google Chrome Version 67.0.3396.99

**Comment by knolleary** [comment]
Hi

this will be related to an issue with npm rather than node-red.

A quick search for the error - `npm ERR! Unexpected end of JSON input while parsing near` reveals this is a known npm issue that is hit quite often. For example: https://github.com/npm/npm/issues/19072

I'd suggest trying some of the ways commenters on that issue have resolved it.

**Comment by rdpaul** [comment]
Hi,

Thanks for your response. I had seen the thread referenced by you and did try `npm clean cache --force` before updating Node Red but that did not help.

I also had updated Node.js before updating Node Red and thus am assuming that NPM would also have been updated.

Completely uninstalling and reinstalling Node.js/NPM seems to be the only thing remaining to try as per the thread referenced.

Another related question, if I uninstall and re-install Node Red and then copy my earlier default .node-red directory back, will all my earlier installed nodes be available again for use - or I will have to reinstall them again.

Thanks in advance for your help.

**Comment by knolleary** [comment]
If you leave the `.node-red` directory intact, then you should get all your added nodes back

**Comment by rdpaul** [comment]
Thank you so much for your help. I am closing this issue for the time being.
