### ISSUE TITLE
Payload too large when deploy big flows

### ISSUE THREAD

**Issue by atellezr** [node-red/node-red#1849]
### What are the steps to reproduce?

Use the editor and build a flow bigger than 100kb (in my case, Content-Length: 108251), and then click over the deploy button

### What happens?

The call to POST /flows returns an error 413 Payload too large

### What do you expect to happen?

Be able to deploy the flow correctly

### Please tell us about your environment:

- [ ] Node-RED version: we're working over the 0.18.4, but I've seen that is the same code in the last commit of that file currently in the repo

### My initial analysis

Basically is what you read above, when trying to deploy a big flows I get this error (413 Payload too large)
I have check another issues (like #1278) but this seems to be a different thing, since the problem here is with the node-red API service `POST /flows`.

What I've seen is that this service is declared within the file `red\api\admin\index.js`:

> var adminApp = express();
> ...
> adminApp.post("/flows",needsPermission("flows.write"),flows.post,apiUtil.errorHandler);

Here it is not being specified the _body-parser_ limit for the **adminApp** (as done in `red\api\index.js` with the _apiMaxLength_), so I guess it is using the default value `100kb` [https://github.com/expressjs/body-parser#limit](https://github.com/expressjs/body-parser#limit), what fits in my error

Is this intended? Is there a recommended limit for the flows to be posted? In my case, the most of the size is being consumed by the code inside functions (I have in mind create custom nodes for solving this kind of operations I have to do)

**Comment by knolleary** [comment]
You don't say whether you've tried setting `apiMaxLength` - as that is the setting for exactly this issue.

The json parser is applied in `red/api/index.js` with `apiMaxLength` set and will apply to all subsequent routes added to the admin route - such as `/flows`.

Are you using Node-RED as-is or embedding it in your own app?

**Comment by atellezr** [comment]
We have in our settings.js:

`apiMaxLength: process.env.NODE_API_MAX_LENGTH || "5mb"`

And I'm using node-red embedded, starting it with this code:

```
const http = require("http");
const express = require("express");
const bodyParser = require("body-parser");
const RED = require("node-red");
const RED_CUSTOM = require("./index");
const settings = require("./settings");
const { deployMiddleware } = require("./middlewares/deploy");
const app = express();
const server = http.createServer(app);
RED.init(server, settings);
app.use(bodyParser.json({ limit: settings.apiMaxLength }));
app.use(
  bodyParser.urlencoded({ limit: settings.apiMaxLength, extended: true })
);
app.use("/", express.static("public"));
deployMiddleware(app);
if (settings.httpAdminRoot !== false) {
  app.use(settings.httpAdminRoot, RED.httpAdmin);
}
if (settings.httpNodeRoot !== false) {
  app.use(settings.httpNodeRoot, RED.httpNode);
}
RED.start()
  .then(() => RED_CUSTOM.success(server, settings))
  .otherwise(RED_CUSTOM.fail);
```

In the `deployMiddleware` what we're doing is:

```
const request = require('request-promise');

function deployMiddleware(app) {
    app.use(async (req, res, next) => {
        switch(req.url) {
            case '/flows': {
...
                    await request.post(notifyOpts);
                } catch(ex) {
                    console.log("Error on", ex);
                }
                break;
            }
        }
        next();
    });  
}
module.exports.deployMiddleware = deployMiddleware;
```
(the idea is to export the flows any time that we deploy them, as back up strategy)

**Comment by knolleary** [comment]
You are setting your own bodyParser on the top-level `app`. That will parse the incoming data before it reaches any node-red code. By the time it reaches the node-red route handler the body will already be parsed and there will be nothing for our bodyParser instance to do.

**Comment by atellezr** [comment]
We've checked our application and we were using an old version of our app, without the bodyParser properly set
We've updated to the version I refer in my previous comment and it worked
I'm sorry for the inconveniences

**Comment by knolleary** [comment]
No problem - happy to help you figure it out 👍
