### ISSUE TITLE
missing editor locales.

### ISSUE THREAD

**Issue by farfromrefug** [node-red/node-red#1859]
### What are the steps to reproduce?
upgrade to 0.19.1

### What happens?

node-red module folder is missing the editor locales.
Thus the editor interface is not localized.

### What do you expect to happen?
locales

### Please tell us about your environment:

- [ ] Node-RED version: 0.19.1
- [ ] node.js version: 9.11.2
- [ ] npm version: 6.4.0
- [ ] Platform/OS: MacOS
- [ ] Browser: Electron / chromium

**Comment by knolleary** [comment]
Hi - please use the issue template you are presented when raising an issue and provide the requested details.

**Comment by dceejay** [comment]
Well English, Japanese and Chinese are there - we are still waiting for some kind volunteers to offer up other language translations :-)

**Comment by farfromrefug** [comment]
@dceejay actually you are right I now found them but i18n does not seem to find them. My editor ui shows ```sidebar.info.info``` instead of ```Information```

And after looking more precisely even the core does not seem to find locales from "node_modules" anymore. I see ```runtime.welcome``` in the console.

I know you upgraded i18n. Is there a setting to change for i18n to find my locales files?

**Comment by knolleary** [comment]
@farfromrefug  There is nothing for you to configure here - it all should just work and does for everyone else who has installed 0.19.1. So it would help if you could provide more information about your local install.

How have you installed node-red? Are you running it normally or are you embedding it in your own app? Again, please answer the questions the issue template asks.

**Comment by farfromrefug** [comment]
@knolleary no need to react like that! I did give infos about my install, and I did follow you template, didn't i? Also as I mentioned I just upgraded node-red from 0.18 to 0.19.

now about my setup I use node-red embedded in my electron app using express. 
I can't post all the code, but the important part for node-red are those:
```
var settings = {
    verbose: true,
    httpAdminRoot: nodeRedSettings.adminUrl,
    httpNodeRoot: '/',
    httpStatic: path.join(userDataPath, 'public'),
    userDir: userDataPath,
    flowFile: nodeRedSettings.flowfile,
    editorTheme: {
        page: {
            css: path.join(__dirname, '../editor.css'),
            scripts: path.join(__dirname, '../editor.js') // As of 0.17
        }
    }
};

// Initialise the runtime with a server and settings
RED.init(server, settings);
// Serve the editor UI from /red
red_app.use(settings.httpAdminRoot, RED.httpAdmin);
// Serve the http nodes UI from /api
red_app.use(settings.httpNodeRoot, RED.httpNode);
red_app.use('/', express.static(settings.httpStatic));
```

the 0.18.7 version works flawlessly, If I 
* update the version number
* run npm I
* start

then no i18n localization. But no error in the console.
It also works again if I simply do the step backward putting 0.18.7 version again.


Sorry to bother you...

**Comment by knolleary** [comment]
My apologies, I hadn't refreshed the page to see you had edited the original description with the template - although there isn't much detail there. The fact you're running embedded in electron is a fairly significant detail that would have been useful to mention at the very beginning.

Could this be a caching issue in electron? It isn't an environment I've done anything in for a long time.

**Comment by farfromrefug** [comment]
@knolleary honestly it has nothing to do with electron almost 100% (you are never really sure ;)). The runtime is running within my main.js which does not run in a renderer thread. 
It's just like running node-red from a simple node js script (well actually it is).
The only thing to know in this case is node version used by electron.

At first I thought it was just the Editor not finding locales, but it's the whole node-red which is not "loading" the locales. 
And yes the locales files are there in node_modules/node-red.

I am almost sure it comes from the changes in i18n. I am correct in saying you made a major i18next upgrade in 0.19.0 ?
I feel like the i18n backend is not "loading/finding" node-red files. 
I will dig into the i18n code from node-red to see what going on and report here.

**Comment by knolleary** [comment]
Yes, we did a major update to the `i18n` module. But the fact it works running 'normally' and for others who embed it, means there must be something particular with your environment that is upsetting it. Given that, if you are able to dig in and track it down, that would be great.

**Comment by farfromrefug** [comment]
After putting i18next in debug mode I found the reason of the issue. 

I also use i18next in my app and both were not using the same "language" but the same i18next instance.
I was using ```en``` when  node-red was using ```en-US```

Now even after fixing this on my side use [createInstance](https://www.i18next.com/overview/api#createinstance).
Could you use it too to make sure it does not happen to someone else?

One thing to note is that In my env I have 
```
LANG=en_US.UTF-8
```

in node-red this is seen as ```en``` from ```getCurrentLocale``` when It should be seen as ```en-US```.
This is not really an issue yet as only en-US is supported and it is the fallback one. But as soon as you had new ones like ```fr-FR``` then it will fail for people having ```LANG=fr_FR.UTF-8``` in their env.

I close the issue as it is resolved for me. But please use ```createInstance``` so that I am the only one this happens to.

Thanks for your help
