### ISSUE TITLE
function error not propagated to debug when executed in subflow

### ISSUE THREAD

**Issue by jueank** [node-red/node-red#1865]
I have a function node with the following code:
```
msg.topic = "abc." + 
    msg.get("xyz") + "." + 
    msg.payload;
return msg;
```
That code contains an error since i changed flow.get("xyz") to msg.get("xyz"), which is wrong.
`(function : (error) "TypeError: msg.get is not a function")`

However, when this function node is executed as part of a subflow, i don't get an error in the debug panel, while i get the error in the debug panel, when the function node is executed directly in a flow.

**Comment by knolleary** [comment]
Hi - there was a template you were shown when raising the issue, it would help if you could fill that out. Specifically, information about the environment you're running in:
```
### What are the steps to reproduce?

### What happens?

### What do you expect to happen?

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:
```

With 0.19, I have put that code in a Function inside a Subflow and when it is triggered I get the error in the debug sidebar - so based on what you've described, I cannot reproduce it.

Do you have any Catch nodes on the same tab is your Subflow instance node? If there is, that node will be catching the error which stops it from being otherwise logged.

**Comment by jueank** [comment]
### What are the steps to reproduce?
flow follows at the end of this post

### What happens?
described above
Besides that: Node-Red is awesome! BIG THANKS!

### What do you expect to happen?
same behavior, either by directly placing the 2 nodes (function + read) or by using the subflow

### Please tell us about your environment:

- [] Node-RED version: 0.19
- [ ] node.js version: 8.11.3
- [ ] npm version: 
- [ ] Platform/OS: Windows 8, 64 bit
- [ ] Browser: Chrome


[{"id":"d7865612.27b3d8","type":"subflow","name":"read timplan data","info":"","category":"","in":[{"x":40,"y":40,"wires":[]}],"out":[{"x":380,"y":40,"wires":[{"id":"d7865612.27b3d8","port":0}]}]},{"id":"e00f805a.e00e4","type":"key-value-read","z":"d7865612.27b3d8","store":"17fb9375.3ee4cd","key":"","name":"","x":270,"y":40,"wires":[[]]},{"id":"814a36a7.b25b28","type":"function","z":"d7865612.27b3d8","name":"","func":"msg.topic = \"timeplans.\" + \n    msg.get(\"timeplan\") + \".\" + \n    msg.payload;\nreturn msg;","outputs":1,"noerr":0,"x":150,"y":40,"wires":[["e00f805a.e00e4"]]},{"id":"17fb9375.3ee4cd","type":"key-value-store","z":"","filepath":"shuttercontrol.json","namespace":"","name":"shuttercontrol"},{"id":"9071e536.b47118","type":"inject","z":"8b6c3371.fa7ea","name":"","topic":"","payload":"plan1","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":90,"y":40,"wires":[["afec1c34.779fe"]]},{"id":"afec1c34.779fe","type":"ui_dropdown","z":"8b6c3371.fa7ea","name":"","label":"Zeitplan","place":"Select option","group":"14ca7f6e.0847e1","order":1,"width":"0","height":"0","passthru":true,"options":[{"label":"Plan 1","value":"plan1","type":"str"},{"label":"Plan 2","value":"plan2","type":"str"}],"payload":"","topic":"","x":240,"y":40,"wires":[["748a1996.607a48"]]},{"id":"88fcda85.477928","type":"change","z":"8b6c3371.fa7ea","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"active","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":140,"y":160,"wires":[["ca09f446.73ae28"]]},{"id":"476387a4.7ff3f8","type":"inject","z":"8b6c3371.fa7ea","name":"","topic":"","payload":"plan2","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":80,"wires":[["afec1c34.779fe"]]},{"id":"748a1996.607a48","type":"change","z":"8b6c3371.fa7ea","name":"","rules":[{"t":"set","p":"timeplan","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":40,"wires":[["88fcda85.477928"]]},{"id":"7dc1f1ee.8c238","type":"change","z":"8b6c3371.fa7ea","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"active","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":530,"y":160,"wires":[["a816d64.67ebd28"]]},{"id":"7e2ee4b4.1e776c","type":"subflow:d7865612.27b3d8","z":"8b6c3371.fa7ea","name":"","x":340,"y":160,"wires":[[]]},{"id":"40735ca5.35eee4","type":"key-value-read","z":"8b6c3371.fa7ea","store":"17fb9375.3ee4cd","key":"","name":"","x":390,"y":220,"wires":[["7dc1f1ee.8c238"]]},{"id":"ca09f446.73ae28","type":"function","z":"8b6c3371.fa7ea","name":"","func":"msg.topic = \"timeplans.\" + \n    msg.get(\"timeplan\") + \".\" + \n    msg.payload;\nreturn msg;","outputs":1,"noerr":0,"x":270,"y":220,"wires":[["40735ca5.35eee4"]]},{"id":"14ca7f6e.0847e1","type":"ui_group","z":"","name":"Zeitplanung","tab":"88436355.2df0f","disp":true,"width":"8","collapse":false},{"id":"88436355.2df0f","type":"ui_tab","z":"","name":"Zeitplanung","icon":"dashboard"}]

**Comment by jueank** [comment]
The 'read' node is from that plugin: node-red-contrib-key-value-store

**Comment by knolleary** [comment]
It took me a while to figure it out.... but then I spotted it.

Your Function node inside the Subflow is not wired to the subflow input node.... its just sat on top of the wire that goes straight from input to output.

Ooops 😉

**Comment by jueank** [comment]
ugh! That's right! Sorry for stealing your time!
'Was just a try for checking node-reds bug response time. It's impressive  ;) :P

**Comment by knolleary** [comment]
👍
