### ISSUE TITLE
Node color bug

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#1876]
### What are the steps to reproduce?
1. git clone https://github.com/node-red/node-red.git
2. cd node-red
3. mv nodes/99-sample.html.demo nodes/99-sample.html
4. mv nodes/99-sample.js.demo nodes/99-sample.js
5. npm install
6. npm run build
7. node red.js
8. Access to Node-RED flow editor (http://locahost:1880) using browser.
9. Drag and drop sample node to work space

### What happens?
Sample node has black color because color property does not exist in 99-sample.html. Therefore, Node-RED users cannot read node name.

![nodecolorbug](https://user-images.githubusercontent.com/20310935/45149538-c5073f80-b204-11e8-8fe8-54973fbb2dee.png)

### What do you expect to happen?
Sample node has gray color (same as palette) in work space when color property does not exist.

### Please tell us about your environment:
- [x] Node-RED version: 0.19.2
- [x]  node.js version: 8.10.0
- [x] npm version: 3.5.2
- [x] Platform/OS: Ubuntu 18.04 (Bash on Windows 10)
- [x] Browser:68.0.3440.106 (Official Build) (64 bit)

**Comment by knolleary** [comment]
Just to clarify - this only happens if a node does not define a `color` property in its definition?

**Comment by kazuhitoyokoi** [comment]
@knolleary Yes, it happens only when node does not have color property.
I think that 99-sample.html needs color property. Therefore, I'll submit another pull request to add it.

**Comment by knolleary** [comment]
Add it to the existing PR - no need to open another

**Comment by kazuhitoyokoi** [comment]
@knolleary OK. I'll do that. 👍
