### ISSUE TITLE
Race conditions in file context access 

### ISSUE THREAD

**Issue by HirokiUchikawa** [node-red/node-red#1888]
In some case, race condition occurs in file context access.

#### No-caching mode
1. Set the following contextStorage property in `settings.js`, then run Node-RED.
  ```javascript
    contextStorage: {
        nocache: {
            module: "localfilesystem",
            config: {
                cache:false
            }
        }
    }
  ```
2. Import the following flow.json.
```
[{"id":"e6a270fd.6ad0c","type":"inject","z":"568fc0eb.2ccfc","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":280,"y":240,"wires":[["3d092b87.cd8d94","161228be.acfac7"]]},{"id":"3d092b87.cd8d94","type":"function","z":"568fc0eb.2ccfc","name":"Set key1","func":"flow.set(\"key1\",\"val1\",\"nocache\",()=>{\n    node.send(msg);\n});","outputs":1,"noerr":0,"x":500,"y":200,"wires":[[]]},{"id":"161228be.acfac7","type":"function","z":"568fc0eb.2ccfc","name":"Set key2","func":"flow.set(\"key2\",\"val2\",\"nocache\",()=>{\n    node.send(msg);\n});","outputs":1,"noerr":0,"x":500,"y":280,"wires":[[]]}]
```
3. Deploy and execute the flow.

#### Caching mode
1. Set the following contextStorage property in `settings.js`, then run Node-RED.
  ```javascript
    contextStorage: {
        nocache: {
            module: "localfilesystem",
            config: {
                cache:true,
                flushInterval:0 // Set 0 to reproduce race condition easily.
            }
        }
    }
  ```
2. Import the following flow.json.
```
[{"id":"c7b448f5.ae5628","type":"inject","z":"b783f676.8728c8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":360,"y":180,"wires":[["ffabbf20.25467"]]},{"id":"ffabbf20.25467","type":"function","z":"b783f676.8728c8","name":"Set key to array(100000) then delete it","func":"var val = new Array(100000).fill(\"foo\");\nflow.set(\"key\",val,\"cache\",()=>{\n    //This timeout makes the key to be deleted immediately after writing.\n    setTimeout(()=>{\n        flow.set(\"key\",undefined,\"cache\",()=>{\n            node.send(msg);\n        });\n    }, 2); // This number may need to be changed according to machine performance\n});","outputs":1,"noerr":0,"x":670,"y":180,"wires":[[]]}]
```
You may need to change the value of timeout according to your machine performance.

3. Deploy and execute the flow.

#### No-caching mode
Only either `key1` or` key2` was saved

#### Caching mode
Broken json data like below was saved.
```
{}    "key": [
        "foo",
        "foo",
        ....
        "foo",
        "foo"
    ]
}
```
Race conditions occur when run writing multiple times on the same context file, because the order of write processing is not controlled.

#### No-caching mode
Both keys will be saved.

#### Caching mode
Empty json data (`{}`) will be finally saved.

### Please tell us about your environment:

- [x] Node-RED version:19.3
- [x] node.js version: 8.12.0
- [x] npm version:6.4.1
- [x] Platform/OS: Windows 7, Ubuntu 18.04
- [x] Browser: chrome

**Comment by knolleary** [comment]
Hi @HirokiUchikawa - thanks for raising this. Are you investigating it further or should I?

I was planning to releasing 0.19.4 this afternoon, but if there is a simple resolution to this, I'd rather hold the release to get it in.

**Comment by HirokiUchikawa** [comment]
Hi @knolleary .
I was investigating it and I am trying to fix this.
I created codes to fix this but it only solves the problem on cache mode.
The problem on non-cache mode is still under consideration now.

So should I create PR to solve only the problem on cache mode?
Or should I do it after creating code to solve both problems?

**Comment by knolleary** [comment]
Create a PR with what you have so far so I can review - but I won't merge until you have both cases fixed.

**Comment by HirokiUchikawa** [comment]
OK. I will create a PR. I would appreciate if you review it.
Thank you.

**Comment by knolleary** [comment]
And have now pushed the above fix to resolve the caching case. It uses the same approach as the non-caching case - using `writePromise` to ensure only one action is happening at any time.

There is an optimisation to be made - currently it blocks all writes until the last has finished, even if the write is to a different file. We should change it to have a promise per file - so two updates to different contexts can happen at the same time. But that can be a future enhancement.
