### ISSUE TITLE
Severe problem when passing big payload

### ISSUE THREAD

**Issue by pelis** [node-red/node-red#1897]
I am running into a rather severe issue when trying to send a message payload containing a 200.000+ JSON object Array. Once the sending node actually sends the message, the receiving node receives the message after 3 to 10 minutes (!). In the meantime, node-red server is almost dead…
In some cases, the node-red server hangs after a while. It seems not to be a matter of memory.
The behavior is rather odd – as it does NOT happen, when the receiving node is “in the same domain” as the sending node, example:
When an http in-node receives a request, processes the request (e.g. in a function node that generates a big payload) and sends it to the http-out node then the http-out node will receive the message without delay. However, when there is another node linked to the sending node (e.g. a function node), then the described problem occurs.

Below, I have added a sample flow that reproduces the problem... 

- [x] Node-RED version: 0.18.7
- [x] node.js version: 10.8.0
- [ ] npm version:
- [x] Platform/OS: Windows 10 X64 (tested on various machines)
- [ ] Browser:

Flow:
[{"id":"8f6c2f3e.c9ce2","type":"function","z":"ad2eb039.e69a5","name":"create docs","func":"var p = [];\nfor (var i = 0; i < 500000; i++) {\n    p.push(\n        {\n        \"valueName\" : \"cycleExecution\",\n        \"value\" : \"started\",\n        \"duration\" : 442,\n        \"tsStart\" : 1533622505000.0,\n        \"tsEnd\" : 1533622510000.0,\n        \"msgType\" : \"bucket\",\n        count: i\n        });\n}\n\nmsg.payload = \"payload created: \" + p.length + \" JSON objects\";\nnode.send(msg, null);\n\nsetTimeout(function () {\n    msg.payload = p;\n    node.send([null, msg]);    \n}, 500)\n","outputs":2,"noerr":0,"x":307,"y":108,"wires":[["1d0b8c57.00ed94"],["ba763974.935e48","f971b8ed.1fd5e8"]]},{"id":"9f54b732.5d58c8","type":"inject","z":"ad2eb039.e69a5","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":137,"y":108,"wires":[["8f6c2f3e.c9ce2"]]},{"id":"1d0b8c57.00ed94","type":"debug","z":"ad2eb039.e69a5","name":"","active":true,"console":false,"complete":"false","x":517,"y":103,"wires":[]},{"id":"ba763974.935e48","type":"function","z":"ad2eb039.e69a5","name":"Reveiving msg???","func":"msg.payload = \"Function-node received OK\";\nreturn msg;","outputs":1,"noerr":0,"x":522,"y":203,"wires":[["4ad250a0.e845b"]]},{"id":"4ad250a0.e845b","type":"debug","z":"ad2eb039.e69a5","name":"","active":true,"console":false,"complete":"false","x":712,"y":198,"wires":[]},{"id":"f971b8ed.1fd5e8","type":"change","z":"ad2eb039.e69a5","name":"<dummy receive>","rules":[{"t":"set","p":"hello","pt":"msg","to":"world","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":522,"y":153,"wires":[[]]}]

**Comment by pelis** [comment]
I have done a bit more testing:
It seems that when the flow is a one by one flow (every node is only linked to one node), then there is no problem. Only when the "big payload node" has more than one connections then the problem comes up.

**Comment by dceejay** [comment]
when a flow forks we have to clone the message rather than pass by references (so that actions on the other leg of the flow do not modify the object in the first) - cloning an object the size you have mentioned will a) take at least 2x the memory and b) time !

**Comment by knolleary** [comment]
@pelis as Dave describes, if you have a flow that branches, it has to clone the message to prevent one 
branch modifying the message in another branch.

Do you need to send the full 200,000 element array down each branch? Can you optimise your flow to avoid sending the full payload where it isn't needed?

There isn't much we can do about this in the core of Node-RED.

**Comment by pelis** [comment]
OK, I can certainly modify the flow (which I already did).
I just thought that the behavior itself might be worth mentioning and looking at.

Looking at it, redUtil.cloneMessage(m) is a rather long-lasting method. Just for testing purposes I have replaced that with “var clonedmsg = JSON.parse(JSON.stringify(m));” On my machine this is about 100 times faster, I am sure you have good reasons why it is as it is, but I consider that very important to know when designing flows. So when a flow is dealing with heavy load data, whether it comes in as a stream or a bulk array, you better do not fork the output…

We actually have had similar issues before, when we had streaming scenarios with heavy data loads. We ran into back pressure problems and had to solve it with different approaches.

However, thanks for replying

**Comment by knolleary** [comment]
Thanks for the update. I've been poking around to see if we can make any further optimisations to avoid cloning... but all the obvious things have already been done.

The problem with the `JSON.parse/stringify` technique is that it only works for JSON encodable data For other types, such as Date and Buffer, they get transformed by the stringify step and not properly restored by the parse step. Some other types are silently dropped.

Optimising the message path is something we always need to consider - but I'm not sure having a perennially open issue on the matter will benefit us. I'm going to close.
