### ISSUE TITLE
Can't load a node beetween users

### ISSUE THREAD

**Issue by Balouzard** [node-red/node-red#1898]
Hello everyone ! 

I'm having an issue using node-red. Basically I programmed a pretty complex automation system. I did it all with my default user (pi). I needed some 3rd party nodes so I installed them using npm (since I don't have an active internet connection on my host) with the "-g" argument.  
I now need to use a modbus server and run on port 502, which means I have to use root in order for node-red to be able to use this port.
I launched node-red under root but node-red won't load 1 particular node named "node-red-node-sqlite"
I did try to reinstall it but it still won't work.

I'm running node-red under raspbian 9.4 with everything up to date.

Thank you for your help :)

**Comment by knolleary** [comment]
Hi, from the issue template you've ignored when raising this, general help type questions should be asked in the forum - linked from the issue template and nodered.org. thanks.
