### ISSUE TITLE
Delay node - rate limit holds back first message if  "per topic" is enabled

### ISSUE THREAD

**Issue by M0ebiu5** [node-red/node-red#1902]
The delay node does not let the first message pass, if it is configured as "Rate limit" with "for each msg.topic".

**Comment by dceejay** [comment]
do you have an example flow that shows this ?
The way the node works is that there is a background timer tick that at each tick emits either the next topic or all topics in the queue (depending on the setting). So the first message out may be delayed by up to the necessary interval (defined by rate).
It is designed so that the latest value for each topic is sent - in order to reduce bandwidth used and so as not to bother send old data points.
It was called a depth 1 round-robin queue but no-one understood what that was :-)

**Comment by M0ebiu5** [comment]
Here is the example - you can see clearly the counters on the nodes which indicate the queue length:
`[{"id":"99b2e027.7494a","type":"inject","z":"5bf1accb.0a7be4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":421,"y":598,"wires":[["f5f8c8c0.b1a348","81508202.55d92"]]},{"id":"f5f8c8c0.b1a348","type":"delay","z":"5bf1accb.0a7be4","name":"","pauseType":"rate","timeout":"20","timeoutUnits":"seconds","rate":"1","nbRateUnits":"23","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":658,"y":601,"wires":[[]]},{"id":"81508202.55d92","type":"delay","z":"5bf1accb.0a7be4","name":"","pauseType":"timed","timeout":"20","timeoutUnits":"seconds","rate":"1","nbRateUnits":"23","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":673,"y":648,"wires":[[]]}]`

**Comment by dceejay** [comment]
Ah - right - actually it's just the status not being reported correctly :-)
Though in the case of this mode of operation the status would indicate how "wide" the queue is rather than depth (ie how many different topics were waiting to be sent) - as there is only one possible value for each. Will fix it anyway (will be in dev branch for 0.20 as not a critical fix)

**Comment by M0ebiu5** [comment]
No, the status is correct - if you add a debug node, you only get one msg instead of two on initial activation.
`[{"id":"99b2e027.7494a","type":"inject","z":"5bf1accb.0a7be4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":421,"y":598,"wires":[["f5f8c8c0.b1a348","81508202.55d92"]]},{"id":"f5f8c8c0.b1a348","type":"delay","z":"5bf1accb.0a7be4","name":"","pauseType":"rate","timeout":"20","timeoutUnits":"seconds","rate":"1","nbRateUnits":"23","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":658,"y":601,"wires":[["3f0355d3.b6d8fa"]]},{"id":"81508202.55d92","type":"delay","z":"5bf1accb.0a7be4","name":"","pauseType":"timed","timeout":"20","timeoutUnits":"seconds","rate":"1","nbRateUnits":"23","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":673,"y":648,"wires":[["3f0355d3.b6d8fa"]]},{"id":"3f0355d3.b6d8fa","type":"debug","z":"5bf1accb.0a7be4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":928,"y":597,"wires":[]}]`

**Comment by dceejay** [comment]
Like I said "there is a background timer tick that at each tick emits either the next topic or all topics in the queue (depending on the setting). So the first message out may be delayed by up to the necessary interval (defined by rate)."

So in your case you may have to wait up to 23 s for the message to arrive. This is working as designed.

**Comment by M0ebiu5** [comment]
Sorry, but this cant be right. The initial msg has to go thru immediately, like it works without the topic mode.

In my use case, i need to limit the appearance of different warnings to 12hrs. Now, what works perfect with one topic, fails badly with multiple topics...

And why does the timer start with deployment and not with the first input msg?

**Comment by dceejay** [comment]
Maybe what you need is a trigger node - set to send the initial message - then wait for 12 hours - send nothing, don't extend - by topic... ?
[{"id":"b654a8d7.b62ea8","type":"trigger","z":"d511095d.512808","op1":"","op2":"","op1type":"pay","op2type":"nul","duration":"12","extend":false,"units":"hr","reset":"","bytopic":"topic","name":"","x":470,"y":860,"wires":[[]]}]

**Comment by M0ebiu5** [comment]
It looks like i've misinterpreted how the multiple topics mode in the delay node works.

Maybe it should be renamed to "Rate limit with a random delay at the start (0 to max rate limit time)" :)

**Comment by dceejay** [comment]
yes - will look at how better to describe it
