### ISSUE TITLE
Enabling adminAuth in settings.js breaks UI refresh in projects panel

### ISSUE THREAD

**Issue by Steveorevo** [node-red/node-red#1903]
### What are the steps to reproduce?

1. Enable projects in Node-RED
2. Enable settings.js' adminAuth section with type: "credentials"
3. Login to Node-RED and make edits under a new project

### What happens?
The project history tab requires one to press the refresh icon when adding, committing, and after commenting a change to the given repo. A "Failed to load resource: the server responded with a status of 401 (Unauthorized)" appears in the JavaScript console. Clicking "refresh" shows operations complete.

### What do you expect to happen?
Without enabling adminAuth section in settings.js, Node-RED's projects UI works as expected.

### Please tell us about your environment:

- [ ] Node-RED version: 0.19.4
- [ ] node.js version: 8.12.0
- [ ] Platform/OS: macOS 10.13.6
- [ ] npm version: 6.4.1
- [ ] Browser: Safari 12.0

**Comment by knolleary** [comment]
Odd - appears to be a Safari specific bug. All works fine in Chrome and Firefox - just Safari that complains. Sigh.

**Comment by knolleary** [comment]
There are certain parts of the Projects HTTP API that responds with a 303 redirect to get the result of the action from a different part of the API.

It appears that Safari handles that redirect differently to other browsers; the authorization header does not get copied over.

One fix is to redirect to a url that has the `access_token` as a query parameter... that fixes Safari but breaks other browsers as the passport strategy we us throws an error if a token is provided by both query parameter and auth header.

Another fix is to hand the errors in the browser and then resubmit the redirected request with the auth header. There's quite a few places in the editor code that would need updating to do that.

The fix I've just pushed to `dev` is to not do any redirecting, and just return the response of the url we would have redirected to. I'm not 100% sure its the right semantic fix - I think the second fix above would be more correct. But this will do for now.
