### ISSUE TITLE
[chore] move some core nodes to their own packages

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#1904]
Move some core nodes 
   - [x] sentiment -> node-red-nodes/multilang-sentiment - adds multilang support
        - [x] push node-red-nodes/multilang-sentiment to git
        - [x] publish node-red-nodes/multilang-sentiment to npm
        - [x] add new module to package.json
        - [x] add entry to `@node-red/registry/lib/deprecated.js`
   - [x] tail -> node-red-nodes/tail - new version that works with windows (not yet in repo)
        - [x] push node-red-nodes/tail to git
        - [x] publish node-red-nodes/tail to npm
        - [x] add new module to package.json
        - [x] add entry to `@node-red/registry/lib/deprecated.js`
   - [x] email -> version 1.x (already in node-red-nodes, but 1.x is node8+ only)
        - [x] update to package.json to pull in 1.x
   - [x] pi gpio -> node-red-nodes  - drop from core package.json - not everyone is running on a Pi :-)
        - [ ] push node-red-nodes/pi-gpio to git
        - [ ] publish node-red-nodes/pi-gpio to npm
        - [ ] update Pi install script to include
        - [x] add entry to `@node-red/registry/lib/deprecated.js`
   - [x] feedparser ->  drop from core nodes package.json ? just leave in node-red-nodes ?
        - [ ] remove from package.json
        - [x] add entry to `@node-red/registry/lib/deprecated.js`

Consider dropping some extra nodes from core 
 - [x] possibly remove email node
 - [x] possibly remove twitter node

**Comment by knolleary** [comment]
Have updated the description with a more details task list to help track where we are at.

**Comment by dceejay** [comment]
need to revisit this for 1.0.0

**Comment by dceejay** [comment]
See PR #2165 
(just need to publish gpio to node-red-nodes)

**Comment by knolleary** [comment]
All done I think...
