### ISSUE TITLE
Context sidebar is disabled when editing a node

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#1921]
### What are the steps to reproduce?

Edit a node then, with the edit still active, switch the sidebar view to the context data.

### What happens?

The whole sidebar appears disabled and you cannot interact with the context data

### What do you expect to happen?

Behaviour should be the same as the information and debug sidebars - you should be able to fully interact with the context data since you often need to look at that data while editing a node (functions, switch, change, etc.).

### Please tell us about your environment:

- [x] Node-RED version: 0.19.4
- [x] node.js version: 8.12
- [x] npm version: 6.4.1
- [x] Platform/OS: Windows 10 1803 & Pi Rasbian 9
- [x] Browser: Chrome 69.0.3497.100 (Official Build) (64-bit)

**Comment by TotallyInformation** [comment]
Thanks.

**Comment by knolleary** [comment]
Hi - this isn't a bug as such as it is behaving exactly as was intended. So this is a proposed change in behaviour.

There were some originally conceived uses for the context sidebar that would have potentially clashed with the node edit dialog. But they happen, so we can safely enable the sidebar.
