### ISSUE TITLE
Errors while installing palette

### ISSUE THREAD

**Issue by MrTreffnix601** [node-red/node-red#1925]
### What happens?
I installed the node-red-contrib-s7comm palette and received the following error:

15 Oct 08:19:05 - [info] Installing module: node-red-contrib-s7comm
15 Oct 08:20:31 - [info] Installed module: node-red-contrib-s7comm
15 Oct 08:20:32 - [info] Added node types:
15 Oct 08:20:32 - [info] - node-red-contrib-s7comm:s7comm read : SyntaxError: Unexpected token )
15 Oct 08:20:32 - [info] - node-red-contrib-s7comm:s7comm write : SyntaxError: Unexpected token )
15 Oct 08:20:32 - [info] - node-red-contrib-s7comm:s7comm : SyntaxError: Unexpected token )

I have already searched in the s7comm.js file for incorrect syntax, but I don´t know if this is the right place to search for the error?

Wenn I try to use the new nodes, I get this error...

15 Oct 08:24:26 - [info] Waiting for missing types to be registered:
15 Oct 08:24:26 - [info] - s7comm read
15 Oct 08:24:26 - [info] - s7comm write
15 Oct 08:24:45 - [info] Stopping flows
15 Oct 08:24:45 - [info] Stopped flows
15 Oct 08:24:45 - [info] Waiting for missing types to be registered:
15 Oct 08:24:45 - [info] - s7comm
15 Oct 08:24:45 - [info] - s7comm read
15 Oct 08:24:45 - [info] - s7comm write

Whats does this mean? Does this have anything to do with the other error?

### Please tell us about your environment:

- [v0.16.2 ] Node-RED version:
- [v6.12.3 ] node.js version:
- [ ] npm version:
- [Siemens IoT Gateway 2040, Yocto Linux ] Platform/OS:
- [Chrome ] Browser:

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

From the issue template:

>
> If your issue is:
>   - a general 'how-to' type question,
>   - a feature request or suggestion for a change,
>   - **or problems with 3rd party (`node-red-contrib-`) nodes**
> 
> please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

This allows the whole Node-RED user community to help, rather than rely on the core development team.

For this particular issue, I would guess the nodes you are trying to install require node 8.

Thanks!
