### ISSUE TITLE
file-out node fails on back-to-back messages

### ISSUE THREAD

**Issue by tve** [node-red/node-red#1926]
### What are the steps to reproduce?

Create a file (-out) node, configure it to overwrite, and leave filename emtpy.
Send it two back-to-back messages (e.g. using a function node that returns an array of two messages) to write some payload to two different files (different msg.filename).

### What happens?

Error: "failed to write to file: Error: write after end"

Looking at the code: https://github.com/node-red/node-red/blob/master/nodes/core/storage/50-file.js#L155-L166 the problem appears to be that `queue.shift();` happens in the callback. This means that for back-to-back messages the second message triggers processQ while the write of the first message is still in progress asynchronously and as a result the assignment of `var msg = queue[0];` picks off the first message again and now there are two overlapping writes of the same file.

### What do you expect to happen?

The two files to be written.

### Please tell us about your environment:

- [ ] Node-RED version: 0.9.14
- [ ] node.js version: v6.11.0
- [ ] npm version:
- [ ] Platform/OS: arm linux
- [ ] Browser: firefox

**Comment by knolleary** [comment]
Hi - the code in git master that you are looking at has already had a proposed fix for this issue applied - https://github.com/node-red/node-red/pull/1894

If you're able to, could you grab the latest version of the file and see if it fixes the issue for you? https://raw.githubusercontent.com/node-red/node-red/master/nodes/core/storage/50-file.js

**Comment by tve** [comment]
I see, will do.

**Comment by dceejay** [comment]
closed in 0.19.5
