### ISSUE TITLE
Http request GET method - download corrupted ZIP file

### ISSUE THREAD

**Issue by ThibautRuy** [node-red/node-red#1944]
### What are the steps to reproduce?
Here is a super basic flow to download a ZIP file from URL in the flow (warning remove / when downloading manually). When I download the file manually it can be unzipped, but when using the http request node it seems it gets corrupted (no issue with the unzip node according to the owner), or maybe I do not use the proper headers?

`[{"id":"8d902fcf.90bb7","type":"inject","z":"1bb46b7e.ef9715","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":160,"wires":[["6de920ba.fac75"]]},{"id":"a71868ce.3820d8","type":"http request","z":"1bb46b7e.ef9715","name":"","method":"GET","ret":"bin","url":"","tls":"","x":570,"y":160,"wires":[["a9ce6cd9.365f2"]]},{"id":"6de920ba.fac75","type":"function","z":"1bb46b7e.ef9715","name":"prep query","func":"msg.headers = {};\nmsg.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0'\nmsg.headers['Content-Disposition'] = 'Content-Disposition to attachment; filename= file.zip'\nmsg.headers['Content-Type'] = 'application/octet-stream';\n\nmsg.headers['Content-Description'] = 'File Transfer';\n\nmsg.headers['Content-Transfer-Encoding'] = 'binary';\n\n\nmsg.url=\"https://donnees.roulez-eco.fr/opendata/jour/20181024/\";\nreturn msg;","outputs":1,"noerr":0,"x":390,"y":160,"wires":[["a71868ce.3820d8"]]},{"id":"f4ae454.5fc5cb8","type":"debug","z":"1bb46b7e.ef9715","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1130,"y":160,"wires":[]},{"id":"a9ce6cd9.365f2","type":"zip","z":"1bb46b7e.ef9715","name":"","mode":"decompress","filename":"","outasstring":true,"x":970,"y":160,"wires":[["f4ae454.5fc5cb8"]]}]`

![capture d ecran 2018-10-25 a 20 15 36](https://user-images.githubusercontent.com/14328511/47521266-e5618b00-d892-11e8-925c-70bb99ab76dc.png)

### What happens?
File is downloaded but with a corrupted format

### What do you expect to happen?
Unzipping a file correctly

### Please tell us about your environment:

- [x] Node-RED version: V0.18.4 git
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Thanks for raising an issue. At this point, it's not clear if this is an issue with node-red, or just a how-to type question.

Your `prep query` function is setting lots of invalid headers - 
```
msg.headers['Content-Disposition'] = 'Content-Disposition to attachment; filename= file.zip'
msg.headers['Content-Type'] = 'application/octet-stream';
msg.headers['Content-Description'] = 'File Transfer';
msg.headers['Content-Transfer-Encoding'] = 'binary';
```

None of those are request headers - they are headers expected in a response to a request. So I don't think they are adding anything here.

When I do a GET of `https://donnees.roulez-eco.fr/opendata/jour/20181024/` I get an HTML page.
When I do a GET of `https://donnees.roulez-eco.fr/opendata/jour/20181024` I get an error from node (as in, the underlying node library) that the response is invalid and cannot be parsed (`hpe_invalid_constant`) - which is odd.

Testing the url with curl:

```
curl -vvv https://donnees.roulez-eco.fr/opendata/jour/20181024
```

shows it sends headers of:

```
> GET /opendata/jour/20181024 HTTP/1.1
> Host: donnees.roulez-eco.fr
> User-Agent: curl/7.54.0
> Accept: */*
```

and it gets the zip file in return.

I've tried setting the headers to match those in your flow, but still get the `hpe_invalid_constant` error.

At this point, I'm really not sure where this is going wrong.

**Comment by ThibautRuy** [comment]
If you want to download via curl you need to add the / at the end I believe...

Best regards
Thibaut Ruy
Manager ONE Order standard and technology
IATA
________________________________

**Comment by knolleary** [comment]
> If you want to download via curl you need to add the / at the end I believe...

No, running `curl https://donnees.roulez-eco.fr/opendata/jour/20181024 > /tmp/test.zip` worked just fine for me.

**Comment by knolleary** [comment]
Closing due to the lack of activity. If this remains an issue, please reopen with updated details.
