### ISSUE TITLE
Out of date documentation for getting started from local install

### ISSUE THREAD

**Issue by bigdoods** [node-red/node-red#1952]
It seems that the bin script for starting node-red locally is not present anymore despite this being the only way that the readme provides to start node-red from a local install.

### What are the steps to reproduce?

Install to local folder via npm

$ npm install --unsafe-perm node-red

Change directory
$ cd <dir> 

Try to start node-red via bin script
$ node node_modules/node-red/bin/node-red

### What happens?

Error: Cannot find module '/home/bigdoods/projects/nr-auth-flow/node_modules/node-red/bin/node-red'

### What do you expect to happen?

node-red to start

### Please tell us about your environment:

- [x] Node-RED version: 19.5
- [x] node.js version: 10.2.1
- [x] npm version: 6.2
- [x] Platform/OS: Ubuntu 18.04.1 LTS
- [x] Browser: Chrome

**Comment by knolleary** [comment]
Good point, those docs are out of date - and have been for a very long time.

You should see in the bin directory is the script `node-red-pi` - you can use that.

**Comment by knolleary** [comment]
Have raised an issue against the docs here: https://github.com/node-red/node-red.github.io/issues/87
