### ISSUE TITLE
Node 10 LTS support

### ISSUE THREAD

**Issue by tkurki** [node-red/node-red#1958]
### What are the steps to reproduce?

Read the documentation and see _Node.js LTS 8.x_ as the recommended and latest version.

### What happens?

Disappointment at Node.js 10, the newly current LTS, not officially supported.

### What do you expect to happen?

Read announcement about  supporting or even recommendation for Node.js 10 or indication if Node-RED is known to work on it.

### Please tell us about your environment:

- [X] Node-RED version:0.19.5
- [X] node.js version:v8.12.0

**Comment by knolleary** [comment]
Node-RED supports Node 10.

Node 10 went LTS 48 hours ago. I'm sorry we were too busy to update the website.

**Comment by tkurki** [comment]
Thanks for the comments. 

Now that 10 is out you could state publicly an intention of moving to it to start herding the crowd.

**Comment by knolleary** [comment]
@tkurki yes and we will when we get a chance to discuss it. Node 10 only went LTS 48 hours ago and we have been busy.

**Comment by dceejay** [comment]
(and still are)

**Comment by tkurki** [comment]
Sorry about the noise....but now that you closed this one is there an issue I could watch to get notified of progress on this? I assume I am not the only one interested.
