### ISSUE TITLE
Corrupted Flows?

### ISSUE THREAD

**Issue by AutoDoc1955** [node-red/node-red#1964]
I have an Ubuntu machine running Node-RED and while I believe that its running the flows that I have written for it because my MySQL tables are showing data in them that is created with Node RED logic, but I am unable to browse (Chrome) to the webpage and see proper names for my flow tabs, but instead the webpage sits and sits, with only the left hand panes with installed nodes showing.  There are no tabs nor any flow logic showing in the main pane of the page.  If I wait long enough (minutes), I may see tab headers with cryptic flow names and a handful of nodes on the pages that are just junk and not my logic.  I have not yet tried to uninstall/reinstall, but before I do, I wanted to float this behavior up here to see if it has been seen anywhere before.  I apologize for the nebulous way in which this post is written, but will be happy to provide any answers to particular questions.  Below is a little piece of logfile to show versions involved here.  npm is 5.6.0.  pm2: 3.0.0.

Thanks in advance!

Node-RED version: v0.17.5
Node.js  version: v8.11.3
Linux 4.13.0-16-generic x64 LE
8 Nov 09:37:04 - [info] Loading palette nodes
8 Nov 09:37:06 - [warn] ------------------------------------------------------
8 Nov 09:37:06 - [warn] [AVR-Yamaha] ReferenceError: document is not defined
8 Nov 09:37:06 - [warn] [bigtimer] ReferenceError: document is not defined (line:681)
8 Nov 09:37:06 - [warn] [google] ReferenceError: document is not defined
...

**Comment by knolleary** [comment]
Is you Node-RED instance exposed on the internet? What you describe sounds like you've been infected by a crypto-miner virus that finds unsecured Node-RED instances on the internet and takes them over.

More details on the forum - where we prefer general help type questions: https://discourse.nodered.org/t/malware-infecting-unsecured-node-red-servers/3460

**Comment by AutoDoc1955** [comment]
I'm heading over to the referenced link shortly, but I think you're probably right.  I ran htop and was running all for processors at 100%, most of it taken up by sustes which apparently is crypto-mining stuff.  I killed that off, but the NodeRED behavior persists.  Leave this thread open and I'll report back here what I found and then we can close it.  Thanks for the quick response!

**Comment by AutoDoc1955** [comment]
Yes, it's for sure crypto-mining.  It looks like it will be a nasty cleanup.  I tried a quick hack by just grabbing an old set of flows and tossing them into the .node-red directory to no avail.  This will take some time to fix and I'm not in a big hurry.  Thanks again for your help.

**Comment by knolleary** [comment]
Closing as this is already discussed widely on the forum.
