### ISSUE TITLE
Export to library produces empty folder when name has a trailing slash

### ISSUE THREAD

**Issue by DSiekmeier** [node-red/node-red#1985]
### What are the steps to reproduce?

- Start Node-RED
- Create a flow and try to export it to library
- Name the library **foo/** (with trailing slash)

### What happens?

- The trailing slash leads Node-RED to create an empty folder in the library menu
- The exported flow cannot be imported anymore

### What do you expect to happen?

- Node-RED should maybe ignore the trailing slash and do not create an empty folder

### Please tell us about your environment:

- [X] Node-RED version: 0.19.5
- [X] node.js version: 6.11.4
- [X] npm version: 3.5.2
- [X] Platform/OS: (X)Ubuntu 16.04
- [X] Browser: Firefox 61.0.1

Also had this behaviour with Node-RED 0.18.4 and a NodeJS version 8.x.

**Comment by arunnattarayan** [comment]
**DSiekmeier** file name wont end with trailing slash. it consider as path and expecting file name after that.

**Comment by DSiekmeier** [comment]
> **DSiekmeier** file name wont end with trailing slash. it consider as path and expecting file name after that.
Sure: this is how it works. But nothing stops the user from omitting the "file name" part. I think it is a good practice to validate user inputs as good as possible. And I think (although I am not sure) this issue should be quite easy to avoid.

Kind Regards
