### ISSUE TITLE
Support for POST when using passport strategy

### ISSUE THREAD

**Issue by cloudhack** [node-red/node-red#1998]
### What are the steps to reproduce?
Assing a custom AdminAuth module, that requires a POST when receiving reply, like passport-saml
### What happens?
You get an 404 error, since node-red only listens for GET
### What do you expect to happen?
The request getting handleded by passport.authenticate
### Please tell us about your environment:
- [0.19.5 ] Node-RED version:
- [ 8.11.3] node.js version:
- [ 6.3.0] npm version:
- [ Ubuntu] Platform/OS:
- [ Chrome] Browser:

a quick hack/workaround was adding the following after RED.start();

```javascript
var passport = require("passport");    
var adminApp = RED.httpAdmin;    
adminApp.post('/auth/strategy/callback',    
passport.authenticate("saml", {session:false, failureRedirect: settings.httpAdminRoot }),    
function (req,res) {    
    var tokens = req.user.tokens;    
    delete req.user.tokens;    
    // Successful authentication, redirect home.    
    res.redirect(config.redfqdn + '?access_token='+tokens.accessToken);    
}
```

But I would recomend adding the following at line 189 in [red/api/auth/index](https://github.com/node-red/node-red/blob/master/red/api/auth/index.js#LC181)

```javascript
adminApp.post('/auth/strategy/callback',
    passport.authenticate(strategy.name, {session:false, failureRedirect: settings.httpAdminRoot }),
    completeGenerateStrategyAuth
);
```

**Comment by knolleary** [comment]
I think it's fair to say a strategy wouldn't require both GET and POST on the callback - and would rather not add them both if they aren't both needed. So would adding an option to pick the required callback method be a reasonable fix?

We would still default to GET, but you'd be able to specify the `callbackMethod` as `post` if needed.

**Comment by cloudhack** [comment]
I agree, an option pick one would be better.
