### ISSUE TITLE
Password Error in Node Red

### ISSUE THREAD

**Issue by BellaRosa1** [node-red/node-red#2006]
I am having a problem getting Node-Red to run in Home Assistant. As you can see in the log the password is not good, I have tried many others

```
```
[[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED v1.2.1
 Flow-based programming for the Internet of Things
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.13 / HA 0.83.3 / SU 141 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
WARNING: Password is in the Have I Been Pwned database!
WARNING: Password appeared 150 times!
FATAL: Please choose a different http_node password, this one is unsafe!
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.](url)
```
```
```
Config:
{
  "log_level": "info",
  "credential_secret": "mxxxxxxd",
  "http_node": {
    "username": "mxxxxxxs",
    "password": "bxxxxxxx1"
  },
  "http_static": {
    "username": "",
    "password": ""
  },
  "port": 1880,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [],
  "init_commands": []
```
}

**Comment by hardillb** [comment]
You will have to contact the add-on author as none of those log messages are from Node-RED

**Comment by BellaRosa1** [comment]
Thank you, what is the best Node Red Addon to use?



Mickie Pitts

**Comment by hardillb** [comment]
No idea, you will have to ask the Home Assistant community
