### ISSUE TITLE
CRASHES NODE-RED Multiple dashboards oppened in any brownser.

### ISSUE THREAD

**Issue by RogerioCassares** [node-red/node-red#2011]
### What are the steps to reproduce?
Multiple node-red dashboard opened in different browsers in web during a period of time.

### What happens?
Crash the node-red application service!

### What do you expect to happen?
Not crash the application of Node-red service

### Please tell us about your environment:

- [ ] Node-RED version: v0.17.5
- [ ] node.js version: v8.9.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Ubuntu 16.04.09
- [ ] Browser: Any brownser in notebooks, tablets, tvs

### ###Node-RED log file with error:

```
<--- Last few GCs --->

[18497:0x30b4aa0]  8308665 ms: Mark-sweep 130.7 (156.0) -> 130.7 (146.0) MB, 175.0 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 175 ms) last resort GC in old space requested
[18497:0x30b4aa0]  8308817 ms: Mark-sweep 130.7 (146.0) -> 130.7 (146.0) MB, 152.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x10235ca5ee1 <JSObject>
    2: sendPacket [/home/smartcampus/.node-red/node_modules/engine.io/lib/socket.js:380] [bytecode=0x3bec63321789 offset=37](this=0xc22273c2861 <Socket map = 0x244308ce53b9>,type=0x2f3e45697231 <String[4]: open>,data=0x7e89751ccc1 <String[96]: {"sid":"4SMSHo3Chj7jlU28AAJD","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}>,options=0x7e89751cce9 <Object map = 0x3e9e132823b9>,callb...


```

**Comment by knolleary** [comment]
Hi - your flows have run out of memory. Not much we can do about that.

The [forum](https://discourse.nodered.org) is a good place to seek assistance from the community to understand what your flows are doing that could be causing this. But it isn't something for us to fix in the core of node-red.

**Comment by RogerioCassares** [comment]
HI @knolleary ! thanks for the quick answer! 

Maybe max-old-space has something related? 

Maybe you could advert me something related that i can improve or discard, please? 

Here is the dash i have mentioned. Divide the widgets in more tabs may improve this challenge? 

[https://smartcampus.maua.br/dash/](https://smartcampus.maua.br/dash/)

There something that accumulates memory to show data in the dashes that crashes the service? 

Thanks in advance for your tips. Any help will guide us to the solution.

**Comment by knolleary** [comment]
For general how-to advice, particular for non-core nodes such as the dashboard, please use the [forum](https://discourse.nodered.org/).

**Comment by RogerioCassares** [comment]
:) Thanks for advice! i will use forum. 

Best Regards! 

Roger Cassares

**Comment by RogerioCassares** [comment]
https://discourse.nodered.org/t/crashes-node-red-multiple-dashboards-oppened-in-any-brownser/6034[https://discourse.nodered.org/t/crashes-node-red-multiple-dashboards-oppened-in-any-brownser/6034](url)
