### ISSUE TITLE
Add TLS support for MQTT

### ISSUE THREAD

**Issue by rjbrown99** [node-red/node-red#202]
Feature request to add TLS support for MQTT. I'm using Mosquitto as a server with TLS and the current implementation won't support a data pull without code changes.

**Comment by TotallyInformation** [comment]
I agree that it seems sensible to focus on TLS transport initially with client cert authentication being a nice to have extension later.

**Comment by vielmetti** [comment]
Noting that this will be a necessary requirement for interfacing with AWS IOT.

**Comment by stefanoco** [comment]
This is a long running issue. My two cents: as a workaround I'm using in order to connect to brokers that expose TLS mode only is running a local broker where nodered is hosted and configuring this for TLS based bridging to the external service.

**Comment by knolleary** [comment]
TLS support for MQTT nodes is coming in 0.14.0. Thank you for waiting. ⌛
