### ISSUE TITLE
Node Red project features always disabled

### ISSUE THREAD

**Issue by argon2075** [node-red/node-red#2022]
### What happens?

Following the official guide in node red web site i enabled project features setting true to editorTheme but when i lunch node red it read always false

### What do you expect to happen?

i espect to have the first project pop up at the beginning

### Please tell us about your environment:

- [x] Node-RED version: 0.19.5
- [x] node.js version: 8.12.0
- [x] npm version: 6.4.1
- [x] Platform/OS:windows 7
- [x] Browser:chrome

**Comment by argon2075** [comment]
dear Mr Knolleary many thank for the super quick response, i'm sorry but i'm very new in this field and i don't know where to check the log :(

**Comment by knolleary** [comment]
As you are on Windows, when you run Node-RED, it writes to the command window where you started it.

**Comment by hardillb** [comment]
Which version of `settings.js` did you edit? The one in the userdir (also listed in the startup log) or the one in the install directory (which you should leave alone)

**Comment by argon2075** [comment]
in the install directory

**Comment by argon2075** [comment]
i have installed node red locally not globally i change the setting.js in the main directory

**Comment by knolleary** [comment]
@argon2075 NR logs the settings file it is using what it starts. Make sure you are editing the file it is using. Typically, you would edit the settings file `HOME/.node-red/settings.js` - so you don't lose the edits you make when you update Node-RED in the future.

**Comment by argon2075** [comment]
i edited exaclty the file HOME/.node-red/settings.js but i don't know why node red read false instead of true

**Comment by knolleary** [comment]
And you have confirmed that is the file NR is logging on startup?

What exactly did you put in the file? Can you share the file here?

**Comment by argon2075** [comment]
i didn't add the optionTheme it was already there, i setted just true

**Comment by argon2075** [comment]
sorry only now i undersood my mistake, i edited the wrong file in the loc al directory, now i set the right file but it say me project disabled git command not found but i try to investigate i don't want to disturb anymore

**Comment by knolleary** [comment]
OK - you need to ensure you have the git command line installed and on your path so node-red can find it.

**Comment by knolleary** [comment]
If you get stuck, the forum is a great place to get support from the community discourse.nodered.org - this issue tracker is for confirmed bugs and issues rather than general how-to support.

**Comment by argon2075** [comment]
i checking how install the git command there thank you very much you are very kind

**Comment by argon2075** [comment]
you were a good tutor the witch will not bring you the coal :)
