### ISSUE TITLE
Option to not parse floats in CSV node

### ISSUE THREAD

**Issue by antonio-fiol** [node-red/node-red#2024]
### What are the steps to reproduce?
Use the CSV node with the following input:
A,B,C
01,"01", 01

### What happens?
The output object is:
{"A":1,"B":1,"C":" 01"}

### What do you expect to happen?
Output value to be:
{"A":"01","B":"01","C":" 01"}

### Please tell us about your environment:
- [ ] Node-RED version: 0.9.14

For my application, I need all the input columns to be interpreted as strings, and definitely not drop a potential leading zero because it is being parsed as a float.

I understand that this might not be the optimal behavior for many other cases, so my suggestion would be adding an option to the node configuration letting the user decide whether floats should be parsed or left as strings.
- [X] leave numbers and empty columns as strings

Alternatively, this could be handled as part of the output format selection, as in:
- a message per row (intelligent parsing)
- a message per row (raw strings)
- a single message [array] (intelligent parsing)
- a single message [array] (raw strings)

From a coding perspective, I see that the change would be relatively simple. If a regular contributor suggests the best UI option (from the above or else), I can create a pull request.

Issue #707 is somehow related in the sense that the columns treatment is maybe too intelligent for some applications, hence my reference to "empty columns" or "intelligent" parsing.

**Comment by dceejay** [comment]
Hi - this has been fixed in the dev branch via this commit - https://github.com/node-red/node-red/commit/1c4df785fddbcba9e6559413e5ca59ee6490681f

This gives the following output for your example

![image](https://user-images.githubusercontent.com/5375409/50850010-8b8c3f80-1370-11e9-9529-f27921d1751c.png)

It will be part of the 0.20 release (or you can hand edit it in locally.)
