### ISSUE TITLE
urlencoding of cookies in headers

### ISSUE THREAD

**Issue by jamestutton** [node-red/node-red#2025]
### What are the steps to reproduce?

Example flow
`
[{"id":"a00f9c90.2c3ff","type":"tab","label":"Flow 6","disabled":false,"info":""},{"id":"58999abe.926be4","type":"http in","z":"a00f9c90.2c3ff","name":"","url":"/hello-cookie","method":"get","swaggerDoc":"","x":168.7935562133789,"y":116.45075798034668,"wires":[["7e857f3.1c8338","adab2a53.f532d8"]]},{"id":"7e857f3.1c8338","type":"function","z":"a00f9c90.2c3ff","name":"Format cookies","func":"msg.payload = JSON.stringify(msg.req.cookies,null,4);\n     msg.FBBOK = \"NO\";\n     msg.HWOK = \"NO\";\n     msg.ENCHWOK = \"NO\"\nif (msg.req.headers.cookie) {\n\n\n    if (msg.req.headers.cookie.indexOf(\"hello+world\") >-1 ) {\n    msg.HWOK = \"YES\";\n    }else{\n        \n    }\n    \n    \n    if (msg.req.headers.cookie.indexOf(\"hello%2Bworld\") >-1 ) {\n    msg.ENCHWOK = \"YES\";\n    }\n    \n    \n    if (msg.req.headers.cookie.indexOf(\"foo_bar_baz\") >-1 ) {\n    msg.FBBOK = \"YES\";\n    }\n}\nreturn msg;","outputs":1,"noerr":0,"x":388.9046630859375,"y":138.89520263671875,"wires":[["46bf8c95.a8e964"]]},{"id":"46bf8c95.a8e964","type":"template","z":"a00f9c90.2c3ff","name":"page","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"<html>\n    <head></head>\n    <body>\n        <h1>Cookies</h1>\n        <p></p><a href=\"hello-cookie/add\">Add a cookie</a> &bull; <a href=\"hello-cookie/clear\">Clear cookies</a></p>\n        <pre>{{ payload }}</pre>\n        \n        <pre>WHAT cookies are in the raw Headers</pre>\n        <pre>hello+world cookie {{ HWOK }}</pre>\n        <pre>hello%2Bworld cookie {{ ENCHWOK }}</pre>\n        <pre>foo_bar_baz cookie {{ FBBOK }}</pre>\n    </body>\n</html>","x":578.9046630859375,"y":138.89520263671875,"wires":[["bc2e229f.7dbdd"]]},{"id":"bc2e229f.7dbdd","type":"http response","z":"a00f9c90.2c3ff","name":"","x":798.9046630859375,"y":138.89520263671875,"wires":[]},{"id":"22c96db1.8eb442","type":"function","z":"a00f9c90.2c3ff","name":"Add a cookie","func":"msg.cookies = { };\nmsg.cookies[\"demo-\"+(Math.floor(Math.random()*1000))] = Date.now()+\"hello++world\";\nmsg.cookies[\"demo-hello\"] = \"hello+world\";\nmsg.cookies[\"demo-foo\"] = \"foo_bar_baz\";\nreturn msg;","outputs":1,"noerr":0,"x":378.9046630859375,"y":178.89520263671875,"wires":[["c4da5723.31ffe8"]]},{"id":"6843b3ed.e123bc","type":"function","z":"a00f9c90.2c3ff","name":"Clear cookies","func":"// Find demo cookies and clear them\nvar cookieNames = Object.keys(msg.req.cookies).filter(function(cookieName) { return /^demo-/.test(cookieName);});\nmsg.cookies = {};\n\ncookieNames.forEach(function(cookieName) {\n    msg.cookies[cookieName] = null;\n});\n\nreturn msg;","outputs":1,"noerr":0,"x":388.9046630859375,"y":218.89520263671875,"wires":[["c4da5723.31ffe8"]]},{"id":"150140c0.02762f","type":"http in","z":"a00f9c90.2c3ff","name":"","url":"/hello-cookie/add","method":"get","swaggerDoc":"","x":188.9046630859375,"y":178.89520263671875,"wires":[["22c96db1.8eb442"]]},{"id":"40a0507c.849ac","type":"http in","z":"a00f9c90.2c3ff","name":"","url":"/hello-cookie/clear","method":"get","swaggerDoc":"","x":188.9046630859375,"y":218.89520263671875,"wires":[["6843b3ed.e123bc"]]},{"id":"c4da5723.31ffe8","type":"change","z":"a00f9c90.2c3ff","name":"Redirect to /hello-cookie","rules":[{"t":"set","p":"statusCode","pt":"msg","to":"302","tot":"num"},{"t":"set","p":"headers","pt":"msg","to":"{}","tot":"json"},{"t":"set","p":"headers.location","pt":"msg","to":"/hello-cookie","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":619.0142211914062,"y":200.00567626953125,"wires":[["bc2e229f.7dbdd"]]},{"id":"adab2a53.f532d8","type":"debug","z":"a00f9c90.2c3ff","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","x":389.78694915771484,"y":48.911930084228516,"wires":[]}]
`

### What happens?
Cookies sent with request are urlencoded + becomes %2B

### What do you expect to happen?
Cookies should not be encoded as per https://tools.ietf.org/html/rfc6265 + is a valid character and should be sent as +

### Please tell us about your environment:

- [0.19.5] Node-RED version: 0.19.5 From docker nodered/node-red-docker
- [ ] node.js version:
- [ ] npm version: 
- [ ] Platform/OS: docker 
- [ ] Browser: NA

Above flow highlight the issue.  But discovered when doing POST to 3rd party REST API that has "+" chars in JSESSIONID a session such as abx+123ghg+ghh is sent as abx%2B123ghg%2Bghh and hence the remote app doesnt match the session to the existing session.  

Node red itself suffers from the same issue but party gets around it as msg.cookies appears to urldecode the values where as msq.headers.cookie see's the raw incorrectly encoded values.

**Comment by HirokiUchikawa** [comment]
The cookies in the example flow (i.e. http response node) are eventually encoded in the [cookie](https://github.com/jshttp/cookie) module.
And [this commit message](https://github.com/jshttp/cookie/commit/68669c89f16e9b03902aec3ebfa64ecf90cf88e9) is why `+` is encoded in the module.

You can avoid encoding by setting `encode` option to `String`.

```
msg.cookies = { };
msg.cookies["demo-hello"] = {value:"hello+world",encode:String};
// You can also change the function used for cookie value encoding
msg.cookies["demo-hello2"] = {value:"hello+world",encode:encodeURI};

return msg;
```

But the cookies in the http **request** node are always serialized as @jamestutton mentioned.

@knolleary 
Should the http request node be changed so that we can choose the encoding function as above?

**Comment by knolleary** [comment]
I can't think of a reason why setting `encode:String` would be a bad thing - especially if it means things work as expected.

Lets make sure we have a test case added as well to cover it.

**Comment by HirokiUchikawa** [comment]
There is no test case to check that the cookie values are encoded (or not done)...

**Comment by HirokiUchikawa** [comment]
@knolleary
The http **request** node in `master` branch always encodes cookies. (see @jamestutton comment)
Can I make a PR so that the node can handle encode option like http **response** node ?

In additon, the **request** node in `dev` branch does not encode cookies...
I would like to change it along with above.

**Comment by knolleary** [comment]
@HirokiUchikawa yes - please do raise a PR.

The dev branch must have the same default behaviour as the master branch.
