### ISSUE TITLE
Wires get duplicated when installing missing node types

### ISSUE THREAD

**Issue by jturner-22** [node-red/node-red#2032]
## Description

Take a flow with nodes of the same type connected to each other. If the project is moved to another instance of Node-RED without the nodes already installed and then the missing node types are installed through the Manage Palette tool, then the wires between the same node types will get duplicated.

## Steps to Reproduce

1. Create a fresh project (optional but easiest to see)
1. Install _node-red-node-smooth_ (any non-core node with an input and output should show the same behavior)
1. Connect an Inject node, 2 Smooth nodes, and a Debug node ( Inject -> Smooth -> Smooth -> Debug )
1. Deploy
1. Hit the Inject node's button
1. In the Debug tab, only one message is shown for each press of the Inject node. This is expected behavior. (A single message is flowing from left to right.)
1. Stop the Node-RED server
1. From the shell, uninstall the node (e.g. `npm uninstall node-red-node-smooth` from the correct directory).
1. Start the Node-RED server. It will complain about missing node types.
1. Refresh the browser.
1. There should be errors regarding the missing module types.
1. Through the Manage Pallete tool, install the missing node. This is when the duplication occurs.
1. Do NOT refresh the browser. So far, the wires have only been duplicated in the browser.
    * They are not yet on the server, or at least not in the flows file yet. Not sure what's in memory.
    * If any change is made and deployed, the browser's version will be saved to the server.
1. Make a small change, like moving a node slightly.
1. Deploy
1. Now when hitting Inject, two messages will be shown in the Debug tab.
    * The duplicate wire is between the two Smooth nodes. So the message from the first node is cloned and a separate copy sent to the second Smooth node. Each is processed by the second Smooth node and sent on.
    * If 3 had been connected in a row, you'd get 4 messages, 4 nodes would give 8 messages, 5 would give 16, etc.

The resulting JSON looks like this:

```
    {
        "id": "e0744f5.41738b",
        "type": "smooth",
        "z": "bcbfc69d.8855e8",
        "name": "",
        "property": "payload",
        "action": "mean",
        "count": "10",
        "round": "",
        "mult": "single",
        "x": 497.18055725097656,
        "y": 213.2396011352539,
        "wires": [
            [
                "f05d7ab8.922328",
                "f05d7ab8.922328"
            ]
        ]
    },
```

The "wires" property has duplicate references.

## Versions

Occurs in the current 0.19.5 version.

Seems to have been introduced in 0.17.4, perhaps in ba6209ba54b0ea8ddf3a5633fe4fdecb799b9383 for "Replace Unknown nodes with their real versions when node loaded". Before that, the user had to refresh their browser to see newly installed nodes that had been missing.

## Cause

The duplicate wires are effectively being created [here](https://github.com/node-red/node-red/blob/0.19.5/editor/js/nodes.js#L1106), when a link is being added to the existing list. The existing links are still there. Eventually, the new link gets saved as an additional wire reference.

Not sure if the real problem is deeper than that.

**Comment by knolleary** [comment]
Thanks @jturner-22 . Great write-up of quite an obscure issue - it only happens when you have two unknown nodes of the same type wired together. There's no deeper issue - the code that swaps the 'real' node back in when it gets loaded was causing the duplicate link to get added.

All fixed in the `dev` branch for the 0.20 release.
