### ISSUE TITLE
CSS settings that make it difficult to create editor themes with different colors

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#2036]
As requested, here's a list of issues I found while trying to create an editor theme with different colors:

- Hardcoded styles
    - [x] ~~Link Nodes properties~~
    - [ ] Projects -> New - Credentials
    - [ ] Project Settings - Settings - Credentials State (both icon and text)
    - [ ] Node Status
        White background
    - [ ] Dashboard - Tabs & Links
        I don't know if this is the right place to talk about this one
    - [ ] Navigator (div, svg and rect)
    - [ ] [Debug Tools Window](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/core/lib/debug/view.html) doesn't load custom CSS
- Wrong (?) classes
    - [ ] Commit Changes
        Some parts of the diff table use debug message panel styles
- \!important rules
    - `diff.scss`
        - [ ] background (Line 456)
        - [ ] background (Line 459)
    - `palette-editor.scss`
        - [ ] background (Line 125)
        - [ ] background (Line 217)

I'll update this list if I find similar issues elsewhere.

**Comment by dceejay** [comment]
good info - thanks.
(slightly reformatted to add tickboxes, and yes please add other as you find them)

**Comment by bonanitech** [comment]
Just added another item to the list.

**Comment by bonanitech** [comment]
Added CSS \!important rules.

**Comment by bonanitech** [comment]
Removed lines related to fa-terminal since I found a workaround.

**Comment by andydesjardins** [comment]
Hello. 

I just wanted to be sure. Is there is improvement on that issue? I like that theme, but that issue is annoying.

Thank you

**Comment by bonanitech** [comment]
I checked an item that seems to have been fixed:

-  Link Nodes properties

**Comment by knolleary** [comment]
@bonanitech we are working on a complete reworking of the editor CSS. This is a massive change to pretty much everything.

As a breaking change it will be part of the upcoming 1.0 release.

The work for that release is in the `dev` branch. The pr that introduced most of the changes is here: https://github.com/node-red/node-red/pull/2158

One of the goals for this will be to also make it easier to create themes. The restructuring of the sass files puts all colours into one file. I plan to create a theme roller app that makes it easy to plug in a custom set of colours and generate a theme CSS. Once we have that, it would be great to use your midnight theme as a test case and have it available when we release 1.0.

I'll be in touch once we have a few more pieces in place.

**Comment by dceejay** [comment]
Hi  hope you are following the 1.0 dev branch. We have namespaces the CSS so just about every name has changed. This will of course break your existing theme changes, but we felt it was necessary to do this before/as part of the major semver change. Hopefully on the plus side it should also allow you to get at most of the missing parts that you need. (Or we can fix as part of the 1 beta)

**Comment by bonanitech** [comment]
Closing this since everything seems to be fixed in 1.0.

Thank you guys!
