### ISSUE TITLE
Frequent flow editing and deploying drops the changes

### ISSUE THREAD

**Issue by ramesh-gurunathan** [node-red/node-red#2039]
Hi
**Frequent flow editing and deploying drops the changes.**

We use node-red for dynamic api in one of our project. Our developers use the node-red editor for creating some custom api on the go. Our users edit the flows at the same time. So they see merge conflict and try to resolve it through review window.
when one of the users is resolving the conflict through merge window, any other user deploys the changes, the server detects one more conflict and triggers flow merge window. This time the previous changes gets deleted in the second merge. 

Why is it happening? I don't know why. Our users are going through merge window properly.

Steps to reproduce:
1. Assume two users are edit/drawing flows at the same time. User1  and User2
2. **User1** designs a flow and deploys it first. the other **user(User2)** will be notified of the changes through notification.
3. When the **User2** is resolving the conflict through **merge window**, User1 modifies the flow again and deploys it.
4. Now User2 clicks the deploy button.Again User2 will see merge conflict. If he clicks the review changes, in the review window the previous merge will be marked as deleted.

**Node-red** : 0.19.4
**NodeJS** : 6.11.0
**NPM**: 3.10.10
**Platform**: Ubuntu 16.0 
**Browser**: Firefox/Chrome

Can someone help me to avoid this from happening?

Thanks

**Comment by knolleary** [comment]
Hi @ramesh-gurunathan, I've tried to reproduce this issue and whilst it has highlighted a couple problems to investigate, I can't quite follow the specific issue you have.

I'm missing some detail at step 4.

1. *Assume two users are edit/drawing flows at the same time. User1 and User2*
2. *User1 designs a flow and deploys it first. the other user(User2) will be notified of the changes through notification.*
3. *When the User2 is resolving the conflict through merge window, User1 modifies the flow again and deploys it.* 
  **Question:** Does User2 still has the resolve conflict dialog open at this point or have then already finished resolving conflicts and has closed the dialog? When User1 clicks the deploy again, I would expect User2 to be notified again of the deploy - what do they do with that notification?
4. *Now User2 clicks the deploy button. Again User2 will see merge conflict. If he clicks the review changes, in the review window the previous merge will be marked as deleted.*
  **Question:** can you clarify what 'the previous merge will be marked as deleted.' means here? What does he see in the merge dialog - what do you *expect* him to see?

**Comment by ramesh-gurunathan** [comment]
Thanks @knolleary 
I can explain the step 3 and step 4.
**Question:** Does User2 still has the resolve conflict dialog open at this point or have then already finished resolving conflicts and has closed the dialog? When User1 clicks the deploy again, I would expect User2 to be notified again of the deploy - what do they do with that notification?

**Ans:** Yes, User2 will be reviewing the changes. So the conflict would be resolved but not deployed. At the time any other user(User1) deploys it again. one more notification dialog will pop up. And the user2 clicks merge button in the resolve conflict window. The conflict show the previous merge as deleted.

**Question:** can you clarify what 'the previous merge will be marked as deleted.' means here? What does he see in the merge dialog - what do you expect him to see?
**Ans:** The user2 may have added a flow or a node in the existing flow. It should be retained. Instead editor just marks it as deleted and user had no choice to preserve his changes.

Below video will help you to reproduce the issue.
**https://youtu.be/VSJGUW5uzGc**

Thanks for reply @knolleary

**Comment by arunnattarayan** [comment]
me too facing the same issue

**Comment by knolleary** [comment]
@ramesh-gurunathan thanks for the extra details - I can now recreate this.

The quickest route to recreate is:

1. start with blank flow, loaded in two separate browser windows
2. add node1 in browser1 - do not deploy
3. add node2 in browser2 - deploy
4. merge change in browser1
5. move node2 in browser2 - deploy
6. review change in browser1 - *node1* is marked as deleted

**Comment by knolleary** [comment]
I've pushed a fix for this to the `dev` branch - it will be available in the next 0.20 beta. If you are able to keep an eye out for that and test it, that would be great.

I think there are still some edge-case quirks with the flow merge/diff, but this has certainly addressed the problem you've been hitting.

**Comment by ramesh-gurunathan** [comment]
Thanks @knolleary 
Sure  I will watch it.

Thanks again.

**Comment by ramesh-gurunathan** [comment]
@knolleary 

This bug is fixed in node-red@0.20.0-beta.5. I verified it in my local machine.

Thanks
