### ISSUE TITLE
Project clone is not working(git ssh with rsa)

### ISSUE THREAD

**Issue by ramesh-gurunathan** [node-red/node-red#2057]
Hi

**Project clone is not working**

I installed node-red@0.20.0-beta.5 and tried the project flow versioning using github repo. The previous**(node-red@0.19.4)** version of node-red I was able to create a project using
https and git ssh. Now the node-red beta release throws error when I try to clone the same repo with **ssh**.

### What are the steps to reproduce?
1. Enable projects feature in the node-red settings file.
2. In the editor, click Projects->New.
3. In the popup click Clone Repository
4. Fill in the Username and email of your existing git repo and click next.
5. In the Git repository URL text paste your git repo url. It should be ssh url. (I assume you've already set up ssh authentication for your repo).
6. Hit Clone Project button. 

### What happens?
It throws error. "runGitCommand(..).finally is not a function" 

### What do you expect to happen?
The configured git repo must be cloned and allow the user to create/design flows.

Node-red : 0.20.0-beta.5
NodeJS : 6.11.0
NPM: 3.10.10
Platform: Ubuntu 16.0
Browser: Firefox/Chrome

It looks like, the git util fails when copying the templates from default location. Below is the error message.
The error message, I printed it using console.log it.
{ code: 128,
  stdout: '',
  stderr: 'Cloning into \'.\'...\nfatal: cannot copy \'/usr/share/git-core/templates/hooks/pre-commit.sample\' to \'/home/{user}/.node-red/projects/noderedtestproject/.git/hooks/pre-commit.sample\': No such file or directory\n' }

This is default error
(node:9302) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error

Thanks
Ramesh G

![image](https://user-images.githubusercontent.com/15322997/52550035-51451080-2dfc-11e9-8b49-66929e382af5.png)

**Comment by knolleary** [comment]
Thanks - fix pushed to `dev`

**Comment by ramesh-gurunathan** [comment]
Thanks for the reply and fix @knolleary
