### ISSUE TITLE
#Enhancement Request :- Handling issues when there are too many flows

### ISSUE THREAD

**Issue by saratSubramaniam** [node-red/node-red#2058]
The tab-based UI is getting a bit too difficult to handle when there are too many flows.
Say there are 50 flows in the Node-RED instance. If I need to go to the last flow from the first one, it takes much time and effort on the scrolling.

Is there already a way to make this easy, that I am not aware ? Else, what could be a possible solution ? I think it is better to see all the flows vertically scrollable or in a dropdown on a side-panel. And open only the ones I want to currently work on, as tabs.

Additionally, is there a way I can customize the way the 'tabs' or the 'Create flow button' look ?

### What are the steps to reproduce?
Add a higher number of flows.
### What happens?
Scrolling gets difficult when navigating from 1st to last.
### What do you expect to happen?
An easier way of opening a flow from the list.
### Please tell us about your environment:

- [x] Node-RED version: v0.20.0-beta.5
- [x] node.js version: 11.8.0
- [x] npm version: 6.5.0
- [x] Platform/OS: Windows
- [x] Browser: Chrome

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

The issue template you've filled in says:


> If your issue is:
>  - a general 'how-to' type question,
>  - a feature request or suggestion for a change,
>  - or problems with 3rd party (`node-red-contrib-`) nodes
>
> please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

This has been discussed a couple times on the forum.

Today you can use the 'Search flows' dialog (Ctrl-F) and search for your tab by name to open it.

We are considering alternative UI options, but there's nothing definitive decided yet.

**Comment by saratSubramaniam** [comment]
Apologies, thanks for the response.
