### ISSUE TITLE
Project Settings tray seems to have a wrong header

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#2064]
### What are the steps to reproduce?
Click on the side menu button -> Projects -> Project Settings
### What happens?
The header is `User Settings`
### What do you expect to happen?
I think the header should be `Project Settings`
### Please tell us about your environment:

- [ ] Node-RED version: 0.19.5
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Already fixed in 0.20

**Comment by bonanitech** [comment]
Thanks
