### ISSUE TITLE
Unable to remove node-red-node-email

### ISSUE THREAD

**Issue by mrzacharycook** [node-red/node-red#2065]
### What are the steps to reproduce?
Install Ubuntu 18.04.2 LTS
sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g --unsafe-perm node-red
cd /usr/local/lib/node_modules/node-red/
sudo npm uninstall --unsafe-perm node-red-node-email

### What happens?
Receive error identifying "Cannot read property 'target' of null

### What do you expect to happen?
node-red-node-email successfully is removed

### Please tell us about your environment:

- [ ] Node-RED version: 0.19.5
- [ ] node.js version: v8.10.0
- [ ] npm version: v3.5.2
- [ ] Platform/OS: Ubuntu 18.04.2 LTS
- [ ] Browser: N/A, putty

**Comment by knolleary** [comment]
Can you provide more compete log output from npm?

**Comment by mrzacharycook** [comment]
Ah - that's strange.  I'd added the debug log to this.  Does this show up?
[npm-debug.log](https://github.com/node-red/node-red/files/2898189/npm-debug.log)

**Comment by dceejay** [comment]
> 2 info using npm@3.5.2
> 3 info using node@v8.10.0

These are slightly out of date versions - especially npm.... but before we suggest upgrading... could you try the uninstall from the ` /usr/local/lib/node_modules/node-red/node_modules` directory instead - i.e. the one below where the email node is actually installed... hopefully it will find it there.

If not I suggest upgrading both node.js and npm - you can stay on node 8 as it is still getting upgrades (currently around 8.15.0) or go to 10... either should also upgrade npm to 6.4 or better.

**Comment by mrzacharycook** [comment]
Thank you for the quick response!  The same error occurs when attempting from /usr/local/lib/node_modules/node-red/node_modules.

Per documentation here: https://github.com/nodesource/distributions/blob/master/README.md I've updated to the latest versions and **node-red-node-email removal succeeded.**

The reason I was attempting to remove the package per the instructions here: https://flows.nodered.org/node/node-red-node-email

The documentation states: "Version 0.x of this node is usually installed by default by Node-RED. To install version 1.x you need to uninstall the existing version."

**Comment by knolleary** [comment]
@mrzacharycook that readme needs updating. You can simply install a different version in `~/.node-red` (where you normally install modules) and the runtime will use that in preference to anything you have globally installed.

**Comment by dceejay** [comment]
Thanks for pointing that out - Have updated the readme and republished as version 1.3.0
