### ISSUE TITLE
localfilesystem.getNodeFiles missing parameter?

### ISSUE THREAD

**Issue by fangqifan** [node-red/node-red#2073]
I found a problem on [loader.js](https://github.com/node-red/node-red/blob/d8b4c1e20948f3d9d6692ae500e8864fe30358a6/red/runtime/nodes/registry/loader.js#L41) when I read code,**localfilesystem.getNodeFiles** is called with two parameter,but the [localfilesystem.getNodeFiles](https://github.com/node-red/node-red/blob/d8b4c1e20948f3d9d6692ae500e8864fe30358a6/red/runtime/nodes/registry/localfilesystem.js#L237) only have one parameter named 'disableNodePathScan'.
Is this a mistake?

**Comment by knolleary** [comment]
Thanks for highlighting. These functions are never called with any arguments when running normally - they are only there for the unit tests to use. In this case, only `disableNodePathScan` is needed which the unit tests were still passing in a string for, so was being handled as `true` with the right result.

Have tidies up the api and tests.
