### ISSUE TITLE
userDir in settings.js incorrect documentation 

### ISSUE THREAD

**Issue by peopeo** [node-red/node-red#2082]
Hi,
I installed an additional local instance of nod-red into a new directory on my Mac with
"npm install --save --unsafe-perm node-red"
Here is the version info:
7 Mar 09:48:21 - [info] Node-RED version: v0.19.6
7 Mar 09:48:21 - [info] Node.js  version: v10.15.1
7 Mar 09:48:21 - [info] Darwin 17.7.0 x64 LE

If I cd into the node-red  directory and start it with 
"node red.js -v -s ./settings.js"
and the original unchanged setttings.js it uses my "home/.node-red" as userDir and starts the flow file of my existing installation. The comment in the settings.js file says
"
// By default, all user data is stored in the Node-RED install directory. To
// use a different location, the following property can be used
// userDir:.....
"
Only after uncommenting it and pointing it to my new directory it worked.

Am I missing something or should te doc be changed?

Peter

**Comment by knolleary** [comment]
Yes, the comment in the example settings file is incorrect - we changed the default behaviour here a very long time ago. Will fix that up for 0.20.

By default it uses `~/.node-red`.
