### ISSUE TITLE
Provide a 'formatted' flow.json option when working in GIT based Projects mode.

### ISSUE THREAD

**Issue by adenysen** [node-red/node-red#2085]
@knolleary - It would be VERY helpful if the Node-RED [Projects](https://nodered.org/docs/user-guide/projects/) feature could provide an option to have generated `flow.json` files to be **formatted** (i.e. multi-line and indented instead of all a single line - as is possible when exporting a flow manually) so that when flow changes are committed to a GIT repo - the diff changes can ALSO be sensibly interpreted using standard GIT diff commands/tools.

This way anyone looking at the history of the `flow.json` file within a Node-RED GIT repo, outside of Node-RED flow editor, can interpret flow.json like other artifacts within that repo (e.g. `README.md`).

Aside from this one feature request, the Node-RED Projects feature is excellent and provides an integrated and simplified developer experience for using Node-RED with GIT.

See attachment for how jumbled a `flow.json` DIFF looks like using [Atlassian's Sourcetree](https://www.sourcetreeapp.com/).
![Sourcetree flow diff](https://user-images.githubusercontent.com/3720596/54133270-2692ab80-43ec-11e9-8345-69d406187a6a.PNG)

**Comment by hardillb** [comment]
As described in the template you removed, questions and feature requests should be brought up on Slack or the Forum first.

Also have a look at the following:

https://github.com/node-red/node-red/blob/master/settings.js#L72

**Comment by knolleary** [comment]
Hi. The issue template you've ignored asks that feature requests or questions get raised on the forum, not this issue tracker.

`flowFilePretty` can be set in your settings file to format the flows file.

**Comment by adenysen** [comment]
Sorry about not following the proper protocol - will be sure to do that next time - thank you for responding.
