### ISSUE TITLE
 Waiting for missing types to be registered:

### ISSUE THREAD

**Issue by limengsong** [node-red/node-red#2092]
I have made a custom node now.
In the js file, I want to introduce a C++ dynamic library file. prompt: Waiting for missing types to be registered。
When deleted, no error is reported.

**Comment by hardillb** [comment]
As mentioned in the template you deleted, questions should be asked on the forum or slack. Issues are for code defects in Node-RED.

This means you have errors in your custom node, when you fix then it will go away.
