### ISSUE TITLE
[warn] [node-test/test] Error: Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by limengsong** [node-red/node-red#2093]
When doing node-red node development, introduce C++ dynamic library. There is a problem with the error introduction path. And the actual path has no problems。
![image](https://user-images.githubusercontent.com/26559533/54340050-79c96000-4671-11e9-8146-1e4d8644089d.png)
`var dcrInstance = ffi.Library('./lib/dcrf32.dll', {
		"dc_init": [ 'pointer', [ 'short','int' ] ]
		// "dc_exit":['short',['pointer']],
		// "dc_beep":['void',['pointer','int']],
		// "dc_reset":['short',['pointer','int']],
		// "dc_config_card":['short',['pointer','string']],
		// "dc_card_n":['short',['pointer','int',IntArray,IntArray]],
		// "dc_read":['short',['pointer','int',IntArray]],
		// "dc_authentication_passaddr":['short',['pointer','int','int',IntArray]],
		// "dc_write":['short',['pointer','int',IntArray]]
   		});`

**Comment by hardillb** [comment]
Again this had nothing to do with core Node-RED, somebody may be able to help you debug your code on the forum or slack, but this is not the place.

**Comment by limengsong** [comment]
thank you ！ I will try
