### ISSUE TITLE
Broken code editor view.

### ISSUE THREAD

**Issue by byakkko** [node-red/node-red#2098]
### What are the steps to reproduce?

- Update Node-RED to last version (v0.20.2). 
- Import a flow or create a new one with a function node.
- Try to see the code in the function node.

### What happens?
The code editor inside the nodes functions does not allow me to see the written code, instead a gibberish appears but if I select it I copy and paste it in another place the code is correct, besides the flow works correctly, it seems to be all the visualization of the code within the editor, but this makes the development much slower.

### What do you expect to happen?
See the code in editor.

### Please tell us about your environment:

- [ ] Node-RED version: v0.20.2
- [ ] node.js version: v10.15.1
- [ ] npm version: 6.4.1
- [ ] Platform/OS:  Windows_NT 10.0.17134 x64 LE / docker under Ubuntu 16.04 
- [ ] Browser: Chrome, Firefox, IE11, Edge.

**Comment by dceejay** [comment]
If you have one of the python nodes installed - they are currently causing a problem. remove them from your flow and it should be OK...

Fixed by commit a242475b382e0e3d80692f3251fc8569ffbcfeaa

Will be released as v0.20.3 later today

**Comment by byakkko** [comment]
That was the error when uninstalling the python module everything works correctly. Thanks.
