### ISSUE TITLE
How to interact with ActiveMQ?

### ISSUE THREAD

**Issue by lulu002** [node-red/node-red#2103]
I want to do an example, consume data from the ActiveMQ queue, and also can generate data into the ActiveMQ queue, but I have not found a suitable solution, I need everyone's help.

**Comment by knolleary** [comment]
Please read the issue template you were shown - it makes it clear this issue list is not for general questions. For help, please use the forum or slack team.

**Comment by lulu002** [comment]
> Please read the issue template you were shown - it makes it clear this issue list is not for general questions. For help, please use the forum or slack team.

ok.I understand.
thanks.
