### ISSUE TITLE
Underscore Hidden in Function Editor

### ISSUE THREAD

**Issue by soloam** [node-red/node-red#2104]
Hello, since I updated to the new 0.20 nodered, all my variables with underscores have the underscore hidden, but if I use the browser (chrome) builtin zoom function, up or down, I can see the underscore.

Thank You

**Comment by knolleary** [comment]
We had one similar report in the forum - but it doesn't appear to be wide spread. So may be related to specific platform/browser combinations.

--- 
As an aside,  when you hit the 'new issue' button, you were presented with a template to fill in.

We've seen an increase in people ignoring the template - as you have. I'd be interested in your feedback on why you didn't fill in the template. Did you see it? Did you chose to ignore it? Was it not clear?

**Comment by soloam** [comment]
### What are the steps to reproduce?

- Create A Function and a variable with underscore in that function

### What happens?

- The Underscore is hidden, but shows if I do Zoom In or Zoom Out in the browser

### What do you expect to happen?

- Show the variable underscore

### Please tell us about your environment:

- [ ] Node-RED version: v0.20.3
- [ ] node.js version: v8.15.1
- [ ] npm version: 6.4.1
- [ ] Platform/OS: FreeBSD (FreeNAS 11.2 Jail) 
- [ ] Browser: Chrome 72.0.3626.96 (Official Build) (64-bit)

:) Sorry

**Comment by hardillb** [comment]
What platform are you running the Chrome on?

**Comment by soloam** [comment]
Linux Debian

**Comment by richcrabtree** [comment]
I have this issue on Arch Linux. Only in Chrome. The underscores are still visible in Firefox. At least 2 of my Arch Linux computers are affected.

node v11.9.0
npm 6.7.0
Chrome Version 66.0.3359.181 (Official Build) (64-bit)
node-red 0.20.2

**Comment by rweglarz** [comment]
I have the same issue on:
  Node-RED version: 0.20.3
  node.js version: v10.14.2
  npm version: 6.4.1
  Platform/OS: hassio
  Browser: chromium 73.0.3683.75

as stated in initial report, changing the zoom level to 90% or 110% causes the underscores to appear

**Comment by knolleary** [comment]
The 0.20.5 release updated to the latest version of the embedded ACE editor we use. It owns all the CSS styling and rendering of the widget - so any issue is going to be, in the first instance, theirs.

If we can't reproduce it ourselves or no-one who reproduce it is able to debug and provide a fix, then there's not a lot we're going to be able to do.

**Comment by albfan** [comment]
This seems to be related with ACE editor:

As soon as you zoom-in underscore is seen:
- 100%: ![100% ace editor](https://user-images.githubusercontent.com/220968/69745235-1bcaa300-1142-11ea-864e-a8c9c0a3b1d5.png)
- 110%: ![110%](https://user-images.githubusercontent.com/220968/69745261-27b66500-1142-11ea-8e37-352810f60ad9.png)

font-family for ACE editor is:
```
font-family: Menlo,Consolas,"DejaVu Sans Mono",Courier,monospace !important;
```
If you do not have that fonts installed it is not seen. As soon as you remove that property underscore is seen.

With that property it renders to Arial:

![arial rendering](https://user-images.githubusercontent.com/220968/69746936-b37dc080-1145-11ea-8d88-df0336a9a58d.png)

Removing the property it renders to Ubuntu mono here:
![Captura de pantalla de 2019-11-27 18-40-18](https://user-images.githubusercontent.com/220968/69746994-ce503500-1145-11ea-9a37-dc2125069c8c.png)

So basically, it is using a no monospace font, that renders behind the bottom line.

I found a similar report here:
https://github.com/rust-lang/mdBook/issues/1061

I think this needs to be reported on ACE editor, in https://github.com/ajaxorg/ace/issues/4000

**Comment by jeroenst** [comment]
I have the same problem in Google Chrome Version 81.0.4044.113 (Official Build) (64-bit) on Ubuntu 20.04...
