### ISSUE TITLE
ACE css worker not found

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#2106]
### What are the steps to reproduce?

Open the admin config panel for any node that uses ACE and edits CSS files

### What happens?

Browser console shows the error:

![image](https://user-images.githubusercontent.com/1591850/54824325-861d7080-4ca2-11e9-893d-b71b476cc5e4.png)

Trying to browse to that location gives:

    Cannot GET /red/vendor/ace/worker-css.js

### What do you expect to happen?

No error.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.0 (happens with other versions as well
- [x] node.js version: 10.15.1
- [x] npm version: 6.4.1
- [x] Platform/OS: Windows 10
- [x] Browser: Vivaldi latest (Chromium based similar to Chrome)

Note that I have `httpAdminRoot: '/red',` in my settings.js

**Comment by knolleary** [comment]
We've never bundled every mode and worker with our copy ACE. We limited it to just the modes we used in the core nodes - in an attempt to reduce the install footprint.

At this point, it's a needless restriction and we'd already decided to add in all of the other modes etc.

Now we have an issue to remind us to do it 😉

**Comment by TotallyInformation** [comment]
Thanks. It doesn't really do any harm but it offends my OCD :)
