### ISSUE TITLE
Change node.js - version for node-red with nvm

### ISSUE THREAD

**Issue by RMA001** [node-red/node-red#2112]
Hi together! 
I would like to run node-red with node.js verison 10.15.3 and therefore I installed nvm to be able to easily change between different node.js-versions. However, node-red always starts up with version 8.11.1 independently what I have selected with nvm. It seems that node-red always starts-up with the system-version of node, but I could not figure out how I can change the system node-red version. Is this possible with nvm? How can I force node-red to use the node.js-version that I have selected with nvm?

The only command that worked was "nvm exec 10.15.3 node-red". In this case node-red started up with node.js-verison 10.15.3 but only this time. After I have rebooted the raspberry pi, node-red again worked with node.js-version 8.11.1.

I tried the following commands:

nvm use 8.15.3
nvm alias default 10.15.3
...

I am a beginner on Linux and it would be great to receive some assistance regarding this issue. Thanks in advance and best regards,
René

------------------------------------Additional Information-------------------------
Operating system: 

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Output "nvm debug":

vm --version: v0.34.0
$SHELL: /bin/bash
$SHLVL: 1
$HOME: /home/pi
$NVM_DIR: '$HOME/.config'
$PATH: $NVM_DIR/versions/node/v10.15.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
$PREFIX: ''
$NPM_CONFIG_PREFIX: ''
$NVM_NODEJS_ORG_MIRROR: ''
$NVM_IOJS_ORG_MIRROR: ''
shell version: 'GNU bash, Version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)'
uname -a: 'Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux'
OS version: Raspbian GNU/Linux 9
curl: curl ist /usr/bin/curl, curl 7.52.1 (arm-unknown-linux-gnueabihf) libcurl/7.52.1 OpenSSL/1.0.2r zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
wget: wget ist /usr/bin/wget, GNU Wget 1.18 übersetzt unter linux-gnueabihf.
git: git ist /usr/bin/git, git version 2.11.0
grep: grep ist ein Alias von `grep --color=auto'., grep (GNU grep) 2.27
awk: not an option: --version
awk: awk ist /usr/bin/awk,
sed: sed ist /bin/sed, sed (GNU sed) 4.4
cut: cut ist /usr/bin/cut, cut (GNU coreutils) 8.26
basename: basename ist /usr/bin/basename, basename (GNU coreutils) 8.26
rm: rm ist /bin/rm, rm (GNU coreutils) 8.26
mkdir: mkdir ist /bin/mkdir, mkdir (GNU coreutils) 8.26
xargs: xargs ist /usr/bin/xargs, xargs (GNU findutils) 4.7.0-git
nvm current: v10.15.3
which node: $NVM_DIR/versions/node/v10.15.3/bin/node
which iojs:
which npm: $NVM_DIR/versions/node/v10.15.3/bin/npm
npm config get prefix: $NVM_DIR/versions/node/v10.15.3
npm root -g: $NVM_DIR/versions/node/v10.15.3/lib/node_modules

Output "nvm ls":

v8.11.1
-> v10.15.3
system
default -> 10.15.3 (-> v10.15.3)
node -> stable (-> v10.15.3) (default)
stable -> 10.15 (-> v10.15.3) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/dubnium (-> v10.15.3)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.0 (-> N/A)
lts/carbon -> v8.15.1 (-> N/A)
lts/dubnium -> v10.15.3

NodeRED start-up log:

Starting as a systemd service.
Started Node-RED graphical event wiring tool.
27 Mar 08:36:58 - [info]
Welcome to Node-RED
===================
27 Mar 08:36:58 - [info] Node-RED version: v0.19.4
27 Mar 08:36:58 - [info] Node.js  version: v8.11.1
27 Mar 08:36:58 - [info] Linux 4.14.98-v7+ arm LE
27 Mar 08:37:00 - [info] Loading palette nodes
27 Mar 08:37:04 - [info] Settings file  : /home/pi/.node-red/settings.js
27 Mar 08:37:04 - [info] Context store  : 'default' [module=memory]
27 Mar 08:37:04 - [info] User directory : /home/pi/.node-red
27 Mar 08:37:04 - [warn] Projects disabled : editorTheme.projects.enabled=false
27 Mar 08:37:04 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
27 Mar 08:37:04 - [info] Server now running at http://127.0.0.1:1880/
27 Mar 08:37:04 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
27 Mar 08:37:04 - [info] Starting flows
27 Mar 08:37:04 - [info] Started flows
27 Mar 08:37:04 - [info] [mqtt-broker:RaspberryPI] Connected to broker: NodeRED@mqtt://172.26.200.84:1883

nvm version:
6.4.1

**Comment by hardillb** [comment]
As described in the template you were shown when opening this issue, questions should be asked on the forum or slack, issues are only for actual defects in Node-RED.

**Comment by knolleary** [comment]
Closing this issue as the issue template has not been filled in. We'll be happy to help on the forum or slack.

**Comment by dceejay** [comment]
Short answer. Don’t use nvm. 

Longer answer. The way nvm works is to use some clever switching scripts that run as the user. They aren’t available to root at boot time when the service starts so it doesn’t get activated at that time. 

So running at the command line works, but at boot time it doesn’t. 

Why not just install node 10 properly. If this is on a pi then (after removing nvm) our update script should handle that for you.

**Comment by RMA001** [comment]
Hi Dave, thanks for your helpful reply. I will try to properly install node 10 on my raspberry pi with the following command:

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

Which update script do you mean? This one?

bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)

**Comment by knolleary** [comment]
@RMA001 yes, that is the update script we provide.
