### ISSUE TITLE
Node info for nodes in flow needs double click on node to display in Info tab (v0.20.3)

### ISSUE THREAD

**Issue by yutter** [node-red/node-red#2117]
**I have tested with Node-RED v0.20.3 and v0.19.5. Bug only seems to be in v0.20.3**

When single clicking on a node in a flow the node's info does not display in the Node-RED Info tab. A double click (to open node's config page) does cause the node's info to display.

Single clicking on a node in the palette does show node info 

Previous versions of Node-RED only require a single click on nodes in flow to display the node's info 

- [x] Node-RED version: 0.20.3
- [x] node.js version: 10.14.0
- [ ] npm version:
- [x] Platform/OS: Alpine Linux on Balena.io
- [x] Browser: Safari 12.1

**Comment by yutter** [comment]
P.S. Node-RED is embedded in our MobiusFlow in case the makes a difference. I’ve not tested stand alone. 
If you can’t reproduce let me know and I will try it on stand alone Node-RED

**Comment by dceejay** [comment]
indeed. - can't reproduce that here.

**Comment by yutter** [comment]
Dave, I will try to reproduce stand-alone

**Comment by yutter** [comment]
Resolved! It was an issue with our web app.
