### ISSUE TITLE
MQTT In-node repeating messages when deployed using modified nodes/flows

### ISSUE THREAD

**Issue by bakman2** [node-red/node-red#2119]
### What are the steps to reproduce?

Test flow:
```
[{"id":"380b9424.fcc454","type":"mqtt in","z":"c0f7a95e.a66d08","name":"","topic":"test/testtopic","qos":"2","datatype":"auto","broker":"73843d1e.7f20dc","x":170,"y":160,"wires":[["a8b9efe1.03a4e"]]},{"id":"a75bc06d.f0bcd8","type":"mqtt out","z":"c0f7a95e.a66d08","name":"","topic":"test/testtopic","qos":"0","retain":"false","broker":"73843d1e.7f20dc","x":410,"y":260,"wires":[]},{"id":"a8b9efe1.03a4e","type":"debug","z":"c0f7a95e.a66d08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":330,"y":160,"wires":[]},{"id":"cc1366c5.2d0998","type":"inject","z":"c0f7a95e.a66d08","name":"","topic":"","payload":"{\"test\":true}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":260,"wires":[["a75bc06d.f0bcd8"]]},{"id":"73843d1e.7f20dc","type":"mqtt-broker","z":"","name":"mqtt","broker":"10.0.0.202","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":"","closeTopic":"","closeQos":"0","closeRetain":"false","closePayload":"","willTopic":"","willQos":"0","willRetain":"false","willPayload":""}]
```

1. Set deploy to modified flows or modified nodes.

- Deploy
- Inject

2. Change the mqtt-in node from `auto-detect` to `a parsed JSON object`

- Deploy
- Inject

3. Change the mqtt-in node from `a parsed JSON object` to `auto-detect`

- Deploy
- Inject

### What happens?
Messages are repeated when deploy is set to  modified flows or modified nodes.

### What do you expect to happen?
A single response.

### Please tell us about your environment:

- [x] Node-RED version:0.20.3
- [x] node.js version: 10.15.3
- [x] npm version: 6.4.1
- [x] Platform/OS: 4.14.98-v7+ armv7l GNU/Linux
- [x] Browser: Macos/Safari 12.0.3

**Comment by knolleary** [comment]
This has already been fixed in master by https://github.com/node-red/node-red/commit/63829b63822a159951b4d9a11c264944eac75b11

Will be in 0.20.4

**Comment by bakman2** [comment]
You might be too quick @knolleary thanks!
