### ISSUE TITLE
Cloning a project doesnt respect ssh key in git config

### ISSUE THREAD

**Issue by jomeier** [node-red/node-red#2120]
Hi,

I'm running node-red in a docker image (https://hub.docker.com/r/nodered/node-red-docker) in version 0.20.3.

I'd like to clone an existing project from my company's gitlab repository.

I created the gitconfig (git@...repo.git syntax), created a ssh key through node-red's ui, added the public key to my gitlab repo).

If I press "Clone Repository" the message

```
Authentication failed
```

is shown.

docker logs mynodered shows this

```
31 Mar 12:16:38 - [trace] git["clone","git@SECRET:SECRET/dudu.git","."]
31 Mar 12:16:38 - [debug] git -c credential.helper= clone git@SECRET:SECRET/dudu.git .
31 Mar 12:16:38 - [debug] [err] Cloning into '.'...
31 Mar 12:16:38 - [debug] [err] Permission denied, please try again.
31 Mar 12:16:38 - [debug] [err] Permission denied, please try again.
31 Mar 12:16:38 - [debug] [err] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
31 Mar 12:16:38 - [debug] [err] fatal: Could not read from remote repository.
31 Mar 12:16:38 - [debug] [err]
31 Mar 12:16:38 - [debug] [err] Please make sure you have the correct access rights
31 Mar 12:16:38 - [debug] [err] and the repository exists.
31 Mar 12:16:38 - [debug] rc=128
```

If I put the following code in my Dockerfile:
```
FROM nodered/node-red-docker
ARG HTTP_PROXY
RUN npm config set https-proxy $HTTP_PROXY
RUN npm install node-red-dashboard
RUN npm install node-red-admin
RUN npm install node-red-contrib-gitlab
ENV GIT_SSL_NO_VERIFY=true
COPY settings.js node_modules/node-red/settings.js
RUN mkdir ~/.ssh
RUN ssh-keyscan code.rsint.net >> ~/.ssh/known_hosts
ENV GIT_SSH_COMMAND="ssh -i /data/projects/.sshkeys/admin_node-red"
```

(especially the last line) the clone process works.

It seems as if node-red's cloning procedure does ignore the ssh keys which are defined in the ui.

Best regards,

Josef

**Comment by knolleary** [comment]
> It seems as if node-red's cloning procedure does ignore the ssh keys which are defined in the ui.

There must be something else going on here because this does work. We *do* set the `GIT_SSH_COMMAND` env when we run the git clone - https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/projects/git/index.js#L107


We did identify an issue last week around the use of certain custom auth plugins which would cause this issue. Have you got anything custom around `adminAuth` setup?

**Comment by knolleary** [comment]
I have just pushed a fix for an issue that was stopping us from using the right user key if adminAuth was enabled in any form. Can you confirm you are using adminAuth?

**Comment by knolleary** [comment]
Please retry with the 0.20.5 release that has now been published.

**Comment by jomeier** [comment]
@knolleary:
It‘s working now. Thanks a lot!

Josef

**Comment by knolleary** [comment]
Excellent - thanks for verifying.
