### ISSUE TITLE
Payload from HttpNode changed in 0.20 when posting a FormData

### ISSUE THREAD

**Issue by marcioluis** [node-red/node-red#2122]
### What are the steps to reproduce?
I have a Angular app that POST a manually build FormData to a HttpNode in NodeRed with a file as Base64 encoded. Something like this.

```
uploadImaged(dadosImaged: UploadImaged): Observable<HttpEvent<Imaged>> {
    const url = `${environment.NODE_RED_URL}/uploadImaged`;
    let body = new FormData();
    body.set('codTipoDoc', `${dadosImaged.codTipoDoc}`);
    body.set('descricao', dadosImaged.descricao);
    body.set('file', dadosImaged.file);
    body.set('filename', dadosImaged.filename);
    body.set('indices', JSON.stringify(dadosImaged.indices));
    const req = new HttpRequest('POST', url, body, { reportProgress: true });
    return this.http.request<any>(req).pipe(catchError(this.errorHandler));
}
```

### What happens?
Until version 0.19.X the PAYLOAD of HttpNode was show as a _buffer_ or a _raw_ string in debug node.
In version 0.20.X when POSTing to HttpNode an exception is raised. **TypeError: invalid media type**.
Activating the flag _Accept file uploads?_ the payload is parsed but I need the buffer version to make an HttpRequest to another backend.

Example:
[Evidence Image/imgur](https://imgur.com/ph4ash9)

### What do you expect to happen?
Payload should be a buffer formdata like in version 0.19

### Please tell us about your environment:

- [x] Node-RED version:
0.20.X
- [x] node.js version:
8.15.1
- [x] npm version:
6.4.1
- [x] Platform/OS:
Linux Mint
- [x] Browser:
Any

**Comment by knolleary** [comment]
Fixed in master - will be in 0.20.4 this week
