### ISSUE TITLE
Httpin Invalid Media Type

### ISSUE THREAD

**Issue by KamalAman** [node-red/node-red#2123]
### What are the steps to reproduce?
   Setup a flow with the following configuration with an http in node and http response node
```
[
    {
        "id": "ebb295ab.e35dd8",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "3d6dd12d.e3060e",
        "type": "http in",
        "z": "ebb295ab.e35dd8",
        "name": "Uploads XML documents",
        "url": "/xml_upload",
        "method": "post",
        "upload": false,
        "swaggerDoc": "",
        "x": 450,
        "y": 280,
        "wires": [
            [
                "1df08233.db4f9e"
            ]
        ]
    },
    {
        "id": "1df08233.db4f9e",
        "type": "http response",
        "z": "ebb295ab.e35dd8",
        "name": "",
        "statusCode": "",
        "headers": {},
        "x": 770,
        "y": 200,
        "wires": []
    }
]
```

Post the following payload to the server
```
curl -X POST \
  http://127.0.0.1:1880/api/xml_upload \
  -H 'Content-Type: application/xml; name=123' \
  -d '<Tag><Child></Child></Tag>'
```

### What happens?
500 Internal Server Error - media-typer is unable to handle Content-Types with parameters

### What do you expect to happen?
200 OK 

Content-Type of `application/xml; name=123` should be valid according to [RFC 2045](https://www.ietf.org/rfc/rfc2045.txt), Content-Types should support parameters `type "/" subtype *(";" parameter)` 

An issue has been created with media-typer https://github.com/jshttp/media-typer/issues/9
Consider moving to the better supported content-type npm module for the http in node. https://www.npmjs.com/package/content-type

### Please tell us about your environment:

- [x] Node-RED version: 0.20
- [x] node.js version: 10
- [x] npm version: 6.4
- [x] Platform/OS: OSX
- [x] Browser: Chrome

**Comment by KamalAman** [comment]
As media-typer suggested in [jshttp/media-typer#9](https://github.com/jshttp/media-typer/issues/9) you should use content-type instead for proper RFC support.

**Comment by knolleary** [comment]
Thanks for the pointer. Have switched over to the `content-type` module. Will be in 0.20.4 this week.
