### ISSUE TITLE
node.status({text: ''}) results in Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rweglarz** [node-red/node-red#2128]
trying to change node status by setting text to empty results in call stack size exceedec

### What are the steps to reproduce?

1. create three nodes: inject, function, debug
2.  in function node put:
```
node.status({text: ''});
return msg;
```
2. connect inject to function input, function output to debug
3. deploy
4. inject

### What happens?
in console chromium reports the following:
> vendor.js:39 Uncaught RangeError: Maximum call stack size exceeded
>    at String.split (<anonymous>)
>    at F (vendor.js:39)
>    at E (vendor.js:39)
>    at Object.<anonymous> (vendor.js:39)
>    at Object.each (vendor.js:2)
>    at F (vendor.js:39)
>    at E (vendor.js:39)
>    at Object.<anonymous> (vendor.js:39)
>    at Object.each (vendor.js:2)
>    at F (vendor.js:39)
and flow is broken

### What do you expect to happen?
no error, no broken flow

### Please tell us about your environment:

- [ ] Node-RED version: 0.20.3
- [ ] node.js version: v10.14.2
- [ ] npm version: 6.4.1
- [ ] Platform/OS: hassio
- [ ] Browser: chromium 73.0.3683.75

**Comment by knolleary** [comment]
Hi - I cannot reproduce this on 0.20.3 (or 0.20.5).

Here's the flow, just as you describe:
```
[{"id":"69151122.9348b","type":"inject","z":"41b925f9.3c983c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":120,"wires":[["a3e75a12.3d2e18"]]},{"id":"a3e75a12.3d2e18","type":"function","z":"41b925f9.3c983c","name":"","func":"node.status({text:\"\"});\nreturn msg;","outputs":1,"noerr":0,"x":330,"y":120,"wires":[["48ff3904.d12f88"]]},{"id":"48ff3904.d12f88","type":"debug","z":"41b925f9.3c983c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":490,"y":120,"wires":[]}]
```
It works as expected.

**Comment by hotNipi** [comment]
Can confirm. 

> 10 Apr 08:24:45 - [info] Node-RED version: v0.20.5
> 10 Apr 08:24:45 - [info] Node.js  version: v10.14.0
> 10 Apr 08:24:45 - [info] Windows_NT 10.0.17134 x64 LE

**Google Chrome
Version 73.0.3683.103 (Official Build) (32-bit)**
﻿
```
vendor.js:39 Uncaught RangeError: Maximum call stack size exceeded
    at C (vendor.js:39)
    at E (vendor.js:39)
    at Object.<anonymous> (vendor.js:39)
    at Object.each (vendor.js:2)
    at F (vendor.js:39)
    at E (vendor.js:39)
    at Object.<anonymous> (vendor.js:39)
    at Object.each (vendor.js:2)
    at F (vendor.js:39)
    at E (vendor.js:39)
```
**Firefox Quantum 60.2.2esr (64-bit)**

```
Empty string passed to getElementById().                                  vendor.js:2:24487
too much recursion[Learn More]                                                vendor.js:39:13808
F
http://localhost:1880/admin/vendor/vendor.js:39:13808
E
http://localhost:1880/admin/vendor/vendor.js:39:11179
F/<
http://localhost:1880/admin/vendor/vendor.js:39:14194
each
http://localhost:1880/admin/vendor/vendor.js:2:3027
F
http://localhost:1880/admin/vendor/vendor.js:39:14168
E
 ..... long list continues here

```

Note that Firefox shows (twice) the warning at the moment the Inject button is pressed.  
`Empty string passed to getElementById()`

No issue with  `node.status({text:" "});`
Can be reproduced with  `node.status({text:""});` and `node.status({text:''});`

**Comment by knolleary** [comment]
Hi @hotNipi

Please can you provide a flow that reproduces this error?

**Comment by hotNipi** [comment]
Tested with your flow (post 4 days ago)

**Comment by hotNipi** [comment]
Test with my laptop at home

```
10 Apr 16:59:00 - [info] Node-RED version: v0.20.5
10 Apr 16:59:00 - [info] Node.js  version: v8.11.3
10 Apr 16:59:00 - [info] Windows_NT 10.0.17134 x64 LE
```

**Firefox Quantum 66.0.1 (64-bit)
Can't reproduce**

**Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Can't reproduce**

**Comment by knolleary** [comment]
The error is in the runtime - so choice of browser is not relevant here.

So you can reproduce on one machine but not another?

Did you have any other flows deployed on the machine that can recreate it? Any Status nodes or subflows?

**Comment by hotNipi** [comment]
It was this flow only I think, only one tab, no subflows, may be some unused config nodes but can't check it out before tomorrow morning.

**Comment by dceejay** [comment]
@knolleary - I have made it fail on that WIn10 VM I almost gave you....

**Comment by knolleary** [comment]
@dceejay but can you reproduce it anywhere else?

**Comment by dceejay** [comment]
not yet - but it is solid fail.

**Comment by dceejay** [comment]
Same (copied) flow on Mac - works on chrome - and on FF - but DOES have same 
`Empty string passed to getElementById().    vendor.js:2:24487`
error on FF 66.0.2 (64-bit) that precedes crash above.

```
[
    {
        "id": "5ef3fadf.31201c",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "c5ac061d.e47e78",
        "type": "function",
        "z": "5ef3fadf.31201c",
        "name": "",
        "func": "\nnode.status({text:\"\"});\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 280.9283447265625,
        "y": 79.56982421875,
        "wires": [
            []
        ]
    },
    {
        "id": "76c90a29.b065a4",
        "type": "inject",
        "z": "5ef3fadf.31201c",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 120,
        "y": 80,
        "wires": [
            [
                "c5ac061d.e47e78"
            ]
        ]
    }
]
```
​

**Comment by hotNipi** [comment]
Tried to get closer to cause of issue. Prettified the vendor.js
It seems to come from i18next section

![image](https://user-images.githubusercontent.com/35291460/55940330-90e77780-5c48-11e9-9b25-16b57750e808.png)

**Comment by knolleary** [comment]
Oh - sorry. I completely misread the original report and assumed the max call stack was happening in the runtime.... that changes *everything*...

**Comment by dceejay** [comment]
@hotnipi  - for me it looks more like in jquery... - vendor.js
    1216       if (d = y.getElementById(c[2]), d && d.parentNode) {
So it may well be that is just where it has gone bang

**Comment by hotNipi** [comment]
Then Chrome must have some kind of forgiveness about `.getElementById("")` . I did tests today only with Chrome and missed that completely.

**Comment by dceejay** [comment]
well they may both be symptoms of something else entirely.

**Comment by hotNipi** [comment]
Highly possible.
As my experiences and understanding around node-red core is (still) way too limited to suspect anything I probably can be that guy who can do some dedicated tests with machine where it reproduces if needed but not more.
