### ISSUE TITLE
Elect / Nominate representative(s) to the OpenJS Foundation CPC

### ISSUE THREAD

**Issue by jorydotcom** [node-red/node-red#2129]
## Context
As part of the new [OpenJS Foundation's bylaws](https://github.com/openjs-foundation/bootstrap/blob/master/artifacts/OpenJS-Foundation-Initial-Merged-Bylaws.pdf), the Cross Project Council (CPC) has been [chartered](https://github.com/openjs-foundation/bootstrap/tree/master/proposals/stage-2/CPC_CHARTER) to serve as the primary governing body for programs and regular support of Foundation projects. For example, it will be responsible for things like infrastructure, travel assistance, CoC support, accepting new projects into the foundation, and mentorship programs to name a few. It will also be responsible for electing board representative(s) to the OpenJS Foundation board of directors.

**Any interested person from our project communities can attend CPC meetings and volunteer to participate in tasks.** For most programs, the CPC is expected to operate on the consensus of OpenJS Foundation project members. Issues that require a vote - namely the election of Board representatives and accepting a new project - will be memorialized by a voting CPC membership comprised of up to 2 representatives from Impact level projects and 2 representatives from Growth and At-Large stages.

If you'd like more info/context on the governance of the OpenJS Foundation, please let me know or follow this repo. The main point I hope you take away is that the foundation is to be run by and for the projects, and to do that we need participants from the project community.

## Request
As a Growth stage project, node-red is strongly encouraged to send representatives to participate in CPC meetings, to advise on programs and support that will be helpful to it, and to nominate someone from the project community to serve in a voting capacity. 

We anticipate having our first 'official' CPC meeting on May 30 or 31 at the Collaborator Summit in Berlin (sidebar, you should come!). In the interim, we would love for node-red project members to participate in the Bootstrap CPC meetings which are currently held on Mondays (watch [this repo](https://github.com/openjs-foundation/bootstrap/issues/150) for meeting details).

If this is not the correct forum to raise this, please let me know and I will close the issue and post it in the preferred channel. Note that I'm posting essentially the same message to all OpenJS Foundation project repos, because I want to get the word out and make sure we all have the same information. 

your pal,
Jory

**Comment by knolleary** [comment]
Hi @jorydotcom,

how do we go about nominating someone? I have been attending the bootstrap meetings as best I can based on timezone and availability, and am probably best placed to be on the CPC moving forwards.

**Comment by jorydotcom** [comment]
@knolleary great question! we haven't really created that process yet, because it's a bit of a chicken and egg problem... we need to form the CPC, so we can form the CPC 😆 

To clarify, node-red can elect people from the project to attend in an official capacity - in a "speaks on behalf of the entire project" - in whatever manner it would like. Internal project governance remains up to individual projects. The nomination I'm referring to above is that growth & at large projects will collectively nominate a few people from those projects to serve as voting members (because there are some items, as referenced, that will require an official vote).

Does that help?

**Comment by dceejay** [comment]
Hi,
So how do we go about seconding Nick's nomination ? Or do we just just say here that he is absolutely the right person for this job.

**Comment by knolleary** [comment]
That's up to us in the project to decide. If no-one else objects, then I'll happily take it on.

**Comment by knolleary** [comment]
Thanks - will close this off and add a note to the bootstrap issue.
