### ISSUE TITLE
Flow context object unusable to store variable temporarily

### ISSUE THREAD

**Issue by sunsharebox** [node-red/node-red#2130]
I planned to use a context flow variable (flow.set("object",{object})) to store a few variable for 15 min. This flow object had to update every 15 min.
As it was continuously updating, I had to modify my code and use a [table] to store the variables.
I am surprised of this behaviour on nodered .... Is this normal ?
See flow below

### Please tell us about your environment:

- [? ] Node-RED version:
- [ v8.10.0] node.js version:
- [v3.5.2 ] npm version:
- [raspbian, ubuntu ] Platform/OS:
- [firefox ] Browser:

### Flow example with context variable
[{"id":"72298dd7.06a614","type":"function","z":"41cd0a0a.197f14","name":"short","func":"var tab3 = [];\nvar object3 = flow.get(\"shortObject\");\nif (object3.variable == 'init') object3.variable = 0;\nobject3.variable = object3.variable + 1;\nflow.set(\"shortObject\" , object3);\ntab3[0] = object3.variable;\nflow.set(\"shortTab\" , tab3);\n\nmsg.payload = object3.variable;\nreturn msg;","outputs":1,"noerr":0,"x":250,"y":160,"wires":[[]]}]

**Comment by knolleary** [comment]
I'm not really clear what issue you are reporting. What is the behaviour you are seeing?

**Comment by sunsharebox** [comment]
Thanks for your answer.
In the example, the Object StoreObject is changing every second whereas it should change only every 15'', like the tab "storeTab" is.
It seems to me the "storeObject" and the "shortObject" are linked at the same memory place on the disk.
regards

**Comment by hardillb** [comment]
NodeJS is a pass by reference language.

This means `shortObject.variable` always points to the same object as `tab3[0]`. 

If you want instances you will have to clone the object and store the copy.

**Comment by knolleary** [comment]
JavaScript passes objects by reference. If you are using the memory store then if you modify the object it returns, you're modifying the object in the store.

If you don't want to modify the copy in the store, you'll need to clone the object that is returned. Something like:

```
var object3 = RED.util.cloneMessage(flow.get("shortObject"));
```

**Comment by sunsharebox** [comment]
thanks !
