### ISSUE TITLE
Headers overwritten by node "http request".

### ISSUE THREAD

**Issue by cjostx** [node-red/node-red#2131]
### What are the steps to reproduce?
Make a simple flow with an inject node followed by a function that sends in the message the authentication header to an http request node

```
[{"id":"3da26b15.1b75b4","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"9529c538.4f6c68","type":"inject","z":"3da26b15.1b75b4","name":"","topic":"","payload":"access_token","payloadType":"global","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":220,"wires":[["5b8935e2.d1d83c"]]},{"id":"3fb6152f.3c28ba","type":"debug","z":"3da26b15.1b75b4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":630,"y":220,"wires":[]},{"id":"5b8935e2.d1d83c","type":"function","z":"3da26b15.1b75b4","name":"","func":"let URI = \"http://www.webdomain.com\"\n\nnewMsg = {}\nnewMsg.url = `${URI}/api/devices`\nnewMsg.method = 'GET'\nnewMsg.headers = {\n    \"Authorization\": global.set(\"access_token\"),\n}\n\n\nreturn newMsg;","outputs":1,"noerr":0,"x":310,"y":220,"wires":[["14471ae1.dbc925"]]},{"id":"14471ae1.dbc925","type":"http request","z":"3da26b15.1b75b4","name":"","method":"use","ret":"txt","paytoqs":false,"url":"","tls":"","proxy":"","authType":"basic","x":460,"y":220,"wires":[["3fb6152f.3c28ba"]]}]
```

### What happens?

My headers are overwritten and / or deleted.

### What do you expect to happen?

I need to pass the authentication header through the node, because it depends on a global variable.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.3
- [x] node.js version: v10.15.3
- [x] npm version: 6.4.1
- [x] Platform/OS: Ubuntu 16.04 LTS
- [x] Browser: Google Chrome

**Comment by knolleary** [comment]
Your function node uses the following code to set `msg.headers`:
```
newMsg.headers = {
    "Authorization": global.set("access_token"),
}
```

You are using `global.set` - if you change that to `global.get` it works.

**Comment by cjostx** [comment]
> Your function node uses the following code to set `msg.headers`:
> 
> ```
> newMsg.headers = {
>     "Authorization": global.set("access_token"),
> }
> ```
> You are using `global.set` - if you change that to `global.get` it works.

yes, the problem is maintained, just copy and delete the sensitive content. but I have another method in my complete code

**Comment by knolleary** [comment]
Do you mean you *are* using `.get` and still hit this problem?

Can you try hardcoding a value in place:

```
newMsg.headers = {
    "Authorization": "some-value"
}
```

I did just that and verified the header is properly set when the request is sent.

**Comment by cjostx** [comment]
> Do you mean you _are_ using `.get` and still hit this problem?
> 
> Can you try hardcoding a value in place (to help identify the problem):
> 
> ```
> newMsg.headers = {
>     "Authorization": "some-value"
> }
> ```
> I did just that and verified the header is properly set when the request is sent.

I had already tried, and the browser sometimes erased the node configuration.

Change the global name of access_token to token and it worked without problems.
