### ISSUE TITLE
Misleading startup [info] log entry 

### ISSUE THREAD

**Issue by miopa** [node-red/node-red#2132]
By default, the UI web server is listening on all IPs, but the startup log entry may mislead the user that it's listening only on loop-back interface and is not accessible from outside.
`[info] Server now running at http://127.0.0.1:1880/`

A solution would be to have two log entries, one describing the server listening properties, like
`[info] HTTPS server now listening at 0.0.0.0:1880`
and a second entry with the access URL

**Comment by knolleary** [comment]
Closing as a duplicate - we don't need both on the list.
