### ISSUE TITLE
Subflow in Nored-Red 0.20.5 no execution

### ISSUE THREAD

**Issue by flight2k** [node-red/node-red#2134]
Before update to 0.20.5 the subflow working great but now nothing happend in the subflow.

### What are the steps to reproduce?

1. Create subflow with just input->function->output
2. Inject anything in subflow
3. Put debug node after subflow.

### What happens?
Nothing - the subflow not working. No execution in subflow

### What do you expect to happen?
Execution of command in the subflow

### Please tell us about your environment:

- [ ] Node-RED version: 0.20.5
- [ ] node.js version: 6.11
- [ ] npm version: 6.9
- [ ] Platform/OS: Ubuntu 14.04
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
You are using node 6.x.

Node-RED 0.20 requires 8.x or later.

**Comment by flight2k** [comment]
Update Node to 8.0 resolve the issue. Thanks a lot
