### ISSUE TITLE
trigger node bug or feature?

### ISSUE THREAD

**Issue by pelis** [node-red/node-red#2141]
### What are the steps to reproduce?
Path 1:
-	Use the flow attached hereto
-	Set “Handling" to “All Messages” and deploy
-	Press inject “incoming topic1”
-	Presse inject “done t1” (before 5000 millisecs have expired)
Path 2:
-	Set  “Handling“ to „each message topic independently”” and deploy
-	Next steps as above (Path 1)

### What happens?
Path 1:
-	The initial messages is passed on, as expected.
-	Sending a “reset” will stop the timer, no more message is sent, as expected
Path 2:
-	The initial messages is passed on, as expected.
	Sending a “reset” seems to stop the timer, however, after the timeout has expired message is sent

### What do you expect to happen?
Path 1: as expected.
Path 2: same behavior as Path 1: I would hope that I could reset the timer for each topic.

### Please tell us about your environment:

- [ ] Node-RED version: v0.19.5-git
- [ ] node.js version: v10.8.0
- [ ] npm version: 6.2.0
- [ ] Platform/OS: Win 10
- [ ] Browser: Chrome

Test flow:
```
[{"id":"edf99204.5d08","type":"debug","z":"e4ea77ca.b3b088","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":735,"y":495,"wires":[]},{"id":"205b0179.a9585e","type":"trigger","z":"e4ea77ca.b3b088","op1":"","op2":"done","op1type":"pay","op2type":"str","duration":"5000","extend":true,"units":"ms","reset":"done","bytopic":"topic","name":"","x":515,"y":515,"wires":[["edf99204.5d08"]]},{"id":"e6d1636e.b1cad","type":"inject","z":"e4ea77ca.b3b088","name":"","topic":" topic1","payload":"done t1","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":105,"y":590,"wires":[["a6f5262e.f2cf78"]]},{"id":"ce4e2011.b9f4d","type":"inject","z":"e4ea77ca.b3b088","name":"","topic":"topic1","payload":"\"incoming topic1\"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":510,"wires":[["205b0179.a9585e"]]},{"id":"a6f5262e.f2cf78","type":"function","z":"e4ea77ca.b3b088","name":"done","func":"msg.reset = true;\nmsg.payload = \"done\";\nreturn msg;","outputs":1,"noerr":0,"x":320,"y":590,"wires":[["205b0179.a9585e"]]}]
```

**Comment by knolleary** [comment]
*Please* use the issue template you were shown.

**Comment by pelis** [comment]
Did  some more testing on "each message topic independently" with multiple topics:
I turned on "resend it every" 3000 millisecs.
Result: sending "reset" to every topic does not stop the timer, for none of the topics.

**Comment by dceejay** [comment]
You have a space before the word topic1 in your inject that does the reset

![image](https://user-images.githubusercontent.com/5375409/56646950-7fef2b00-6678-11e9-9dfb-2f22c048913c.png)

so the topics don't match so your are not resetting the topic you thought you were.

**Comment by pelis** [comment]
ups - sorry for wasting your time, that's really embarrasing...
