### ISSUE TITLE
ui_template auto giving random div sizes on refresh.

### ISSUE THREAD

**Issue by nospam2k** [node-red/node-red#2142]
Here is an example of the ui_template problem I mention in the title. Using this flow, when the page first loads, it's fine. Refresh and "bottom line" height changes between 25px(?) and the passed 100px from the msg.payload in the function.

[{"id":"92b6f0d9.127df8","type":"ui_template","z":"a47b7c22.4362f8","group":"987f770.d9f8e08","name":"","order":3,"width":0,"height":0,"format":"<div ng-style=\"{'height': '100px'}\">{{msg.payload.top}}</div>","storeOutMessages":true,"fwdInMessages":false,"templateScope":"local","x":660,"y":200,"wires":[[]]},{"id":"aa4cbce0.1f9f","type":"ui_template","z":"a47b7c22.4362f8","group":"987f770.d9f8e08","name":"","order":5,"width":0,"height":0,"format":"<div ng-style=\"{'height': msg.payload.height}\">{{msg.payload.bottom}}</div>","storeOutMessages":false,"fwdInMessages":false,"templateScope":"local","x":660,"y":240,"wires":[[]]},{"id":"f7989716.27bf68","type":"function","z":"a47b7c22.4362f8","name":"Test","func":"var topLine = 'Top line';\nvar bottomLine = 'Bottom line';\nvar payload = {top: topLine, bottom: bottomLine, height: '100px'};\nreturn {payload : payload};","outputs":1,"noerr":0,"x":510,"y":220,"wires":[["92b6f0d9.127df8","aa4cbce0.1f9f"]]},{"id":"835b6c82.58b058","type":"inject","z":"a47b7c22.4362f8","name":"OneTime","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":360,"y":220,"wires":[["f7989716.27bf68"]]},{"id":"987f770.d9f8e08","type":"ui_group","z":"","name":"Test Group","tab":"f320b5e6.9c06b","order":1,"disp":false,"width":"6","collapse":false},{"id":"f320b5e6.9c06b","type":"ui_tab","z":"","name":"Testing","icon":"dashboard","order":5}]

**Comment by knolleary** [comment]
Hi,

As the issue template you've ignored states, this issue tracker is for the core of node-red.

Please reopen against the node-red-dashboard repo here: [https://github.com/node-red/node-red-dashboard/issues]()

When you open the issue, please read and use the issue template you are provided. Ignoring the issue template will only result in us asking you to fill in the template.
