### ISSUE TITLE
Delay node label shows 'reset' status

### ISSUE THREAD

**Issue by bakman2** [node-red/node-red#2145]
Cosmetic only : Delay node ~~without label~~ shows 'reset' node status as initial status

### What are the steps to reproduce?

- Drag an inject node in the editor.
- Drag a delay node in the editor.
- Connect the 2 nodes
- Double click the node, select 'delay each message' , 'fixed delay', 2 seconds. 
~~- Select appearance tab, label: hide.~~
- Deploy (modified nodes)

### What happens?

Node shows 'reset' as node status in the editor.

![Screenshot 2019-04-21 at 08 13 47](https://user-images.githubusercontent.com/333960/56466164-6e561b00-640d-11e9-8453-bcbde5ae1a6e.jpg)

### What do you expect to happen?

No status. 

### Please tell us about your environment:

- [x] Node-RED version: 0.20.5
- [x] node.js version:v10.15.3
- [x] npm version:6.9.0
- [x] Platform/OS: macos 10.14.4
- [x] Browser: safari 12.1

*note i just realised it applies to both with,without label.

**Comment by dceejay** [comment]
You could argue that indeed it has been reset on a deploy so isn't actually wrong, but yeah, other nodes don't do it.

**Comment by bakman2** [comment]
> You could argue that indeed it has been reset on a deploy so isn't actually wrong, but yeah, other nodes don't do it. fixed.

I agree, I was removing all the labels in my flow and it suddenly it became apperent that it showed reset.
