### ISSUE TITLE
Built in CRON time support

### ISSUE THREAD

**Issue by skylord123** [node-red/node-red#2149]
I've been using the cron npm module `node-red-contrib-cron` for a while now (and just recently convinced the company I work for to use Node-RED for scheduled tasks). The problem is this package hasn't been updated in a long time and I honestly feel like the same functionality should just be part of node-red (either by making the Inject node support CRON time or by adding another node that supports it).

It would be nice to not have to worry that future versions will break this.

I really like the inject node it just isn't as flexible as CRON. Using CRON syntax also makes moving our scheduled tasks over super easy and opens the doors to some really cool scheduling.

**Comment by knolleary** [comment]
Hi @skylord123 - please read the issue template you've delete when raising this issue.

Feature requests etc should happen on the forum/slack. The issue tracker is not the place for feature requests.

**Comment by skylord123** [comment]
@knolleary Sorry about wasting your time. I will go that route, thanks.

**Comment by skylord123** [comment]
I just wanted to update this in-case anyone else comes across it:

This has been added to the trello board and should be done sometime in the future. If it's not done by the time I get some free time I will be jumping in to do it. https://trello.com/c/deSvO2ge
