### ISSUE TITLE
Feature Request: allow script type="module" in client side .html file

### ISSUE THREAD

**Issue by Holger-Will** [node-red/node-red#2150]
it would be nice to be able to use esm 

`<script type="module" src="foo"></script>`

on the client side. 

What i currently do is inject the script tag myself:

```
var st = document.createElement("script")
st.setAttribute("type","module")
st.setAttribute("src","enocean-js/test.js")
document.body.appendChild(st)
```
but that seems hackish...

I migth be able able to create a PR, but i'm fairly new to node-red, so a pointer in the rought direction to where the nodes .html loading happens would be great...

**Comment by knolleary** [comment]
Hi, thanks for raising an issue. However we do not use the issue list for feature requests. The issue template you've ignored makes this fairly clear. Please use the forum to start a discussion.



Thanks!

**Comment by dceejay** [comment]
maybe add to this discussion - https://discourse.nodered.org/t/include-js-in-a-html-custom-module/10434/7
