### ISSUE TITLE
httpServerOptions / x-powered-by...

### ISSUE THREAD

**Issue by adamiD** [node-red/node-red#2151]
Hello guys,

I started using this wonderful tool, I am impressed with the potentialities.
So far everything went very well, but I can not use the configuration below:

httpServerOptions: {
		"x-powered-by": false
},

Anything I'm forgetting?

Good "nodes" to everyone!

- [0.20.5] Node-RED version:
- [10.15.3] node.js version:
- [6.9] npm version:
- [W64/Debian] Platform/OS:

**Comment by hardillb** [comment]
Any particular reason you ignored the template you were shown, specifically the bit about asking questions on the forum/slack as issues are for actual problems with the code?

Also when you ask this elsewhere, you need to supply a LOT more information, specifically what you are trying to achieve and what you are seeing, just saying you can't use the option with no explanation to why/what you are actually trying to do is useless.

**Comment by adamiD** [comment]
@hardillb Thanks for the directions, I'll put the question in the most appropriate place.
