### ISSUE TITLE
Sending Mail to Microsoft Exchange fails

### ISSUE THREAD

**Issue by WeeSee** [node-red/node-red#2155]
Sending Mail using the Email-Node to Microsoft Exchange fails. 

Debugging gives a TLS/SSL problem when communication with Microsoft Exchange.

My research on this problem lead to modifications in the included nodemailer package:
[https://stackoverflow.com/questions/19509357/not-able-to-connect-to-outlook-com-smtp-using-nodemailer](https://stackoverflow.com/questions/19509357/not-able-to-connect-to-outlook-com-smtp-using-nodemailer)

Will this be fixed in the NodeRED releases anytime - maybe as an option in the Mail Node settings in the Editor?

How can I modify settings.js for multiple deployments on our site?

**Comment by knolleary** [comment]
Hi - please use the issue template you given when raising an issue.

The email node is not maintained in this repository. Please open an issue, using the issue template, here: https://github.com/node-red/node-red-nodes

> How can I modify settings.js for multiple deployments on our site?

That is a question you should ask on the discussion forum - https://discourse.nodered.org - as the issue template says, the issue list is *not* a place for general how-to type questions.

**Comment by DrAniza** [comment]
Hhdhsh
