### ISSUE TITLE
Link node cause stop subflow when link flow to subflow to flow

### ISSUE THREAD

**Issue by prothorin** [node-red/node-red#2164]
### What are the steps to reproduce? Create a wiring link chain:
Flow1 -> subflow1->subflow2->subflow3->subflow4->subflow5->flow1 (connect multiple nodes in subflows)

### What happens? Subflows are stop working, 
error: TypeError: this.subflowInstanceNodes[sfId].getNode is not a function

### Please tell us about your environment:

- [ ] Node-RED version: 20.5
- [ ] node.js version: 10.15.3 LTS
- [ ] npm version: 6.4.1
- [ ] Platform/OS: Ubuntu 18.04 LTS
- [ ] Browser: Chome

**Comment by knolleary** [comment]
Hi - you mention the Link node in the issue title, but the description doesn't.

Can you please clarify? Are there are more details you can share about what happens in the runtime? Any log messages?

Can you share a flow json that demonstrates the issue?

**Comment by prothorin** [comment]
When I create this link chain back to flow 1  i got this error.
After that all subflow that used in chain stop working.
If i delete wiring link nodes, subflows still not working.

A moment I create a json,

**Comment by prothorin** [comment]
Warning!  Used only in empty!

[{"id":"1261da8e.128f05","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"510ee227.2ad51c","type":"subflow","name":"Subflow 1","info":"","in":[{"x":200,"y":60,"wires":[{"id":"59242362.bd0a0c"}]}],"out":[]},{"id":"7f0b94d9.2c95cc","type":"subflow","name":"Subflow 2","info":"","in":[{"x":50,"y":30,"wires":[{"id":"45fa2b54.d40c14"}]}],"out":[]},{"id":"26b00c38.afa344","type":"subflow","name":"Subflow 3","info":"","in":[{"x":140,"y":60,"wires":[{"id":"d1bb0c6e.f2ed2"}]}],"out":[]},{"id":"681b4263.d9d16c","type":"subflow","name":"Subflow 4","info":"","in":[{"x":50,"y":30,"wires":[{"id":"f5167a1e.566c48"}]}],"out":[]},{"id":"7818d86d.ef4a08","type":"subflow","name":"Subflow 5","info":"","in":[{"x":180,"y":180,"wires":[{"id":"27371be6.859644"}]}],"out":[]},{"id":"af60565a.549b88","type":"inject","z":"1261da8e.128f05","name":"","topic":"","payload":"0","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":100,"wires":[["9380ad91.cdd05"]]},{"id":"da823f2d.3893c","type":"function","z":"510ee227.2ad51c","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":180,"wires":[["235f0a50.6b2406"]]},{"id":"df0c9063.5c186","type":"function","z":"7f0b94d9.2c95cc","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":330,"y":200,"wires":[["53fb5f65.dbf19"]]},{"id":"b70b4965.54be68","type":"function","z":"26b00c38.afa344","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":260,"wires":[["18febf8f.917d7"]]},{"id":"3b0f78a6.d61b98","type":"function","z":"681b4263.d9d16c","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":340,"wires":[["eb6a427c.efcf8"]]},{"id":"ec2eb2c0.91fdb","type":"function","z":"7818d86d.ef4a08","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":260,"wires":[["73690c5c.4257d4"]]},{"id":"9380ad91.cdd05","type":"function","z":"1261da8e.128f05","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":340,"y":100,"wires":[["bd957fb9.5bed8"]]},{"id":"bd957fb9.5bed8","type":"link out","z":"1261da8e.128f05","name":"","links":["e17cedd.7991c1"],"x":480,"y":100,"wires":[]},{"id":"e17cedd.7991c1","type":"link in","z":"510ee227.2ad51c","name":"","links":["bd957fb9.5bed8"],"x":220,"y":180,"wires":[["da823f2d.3893c"]]},{"id":"235f0a50.6b2406","type":"link out","z":"510ee227.2ad51c","name":"","links":["c233d3d8.04608"],"x":500,"y":180,"wires":[]},{"id":"c233d3d8.04608","type":"link in","z":"7f0b94d9.2c95cc","name":"","links":["235f0a50.6b2406"],"x":195,"y":200,"wires":[["df0c9063.5c186"]]},{"id":"53fb5f65.dbf19","type":"link out","z":"7f0b94d9.2c95cc","name":"","links":["fcc2ad18.a45"],"x":450,"y":200,"wires":[]},{"id":"fcc2ad18.a45","type":"link in","z":"26b00c38.afa344","name":"","links":["53fb5f65.dbf19"],"x":255,"y":260,"wires":[["b70b4965.54be68"]]},{"id":"18febf8f.917d7","type":"link out","z":"26b00c38.afa344","name":"","links":["ee1d179c.041788"],"x":515,"y":260,"wires":[]},{"id":"ee1d179c.041788","type":"link in","z":"681b4263.d9d16c","name":"","links":["18febf8f.917d7"],"x":245,"y":340,"wires":[["3b0f78a6.d61b98"]]},{"id":"eb6a427c.efcf8","type":"link out","z":"681b4263.d9d16c","name":"","links":["5f4c436c.549c5c"],"x":485,"y":340,"wires":[]},{"id":"5f4c436c.549c5c","type":"link in","z":"7818d86d.ef4a08","name":"","links":["eb6a427c.efcf8"],"x":235,"y":260,"wires":[["ec2eb2c0.91fdb"]]},{"id":"73690c5c.4257d4","type":"link out","z":"7818d86d.ef4a08","name":"","links":["17b7f488.78ff8b"],"x":455,"y":260,"wires":[]},{"id":"fd30a64e.309798","type":"debug","z":"1261da8e.128f05","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":370,"y":180,"wires":[]},{"id":"17b7f488.78ff8b","type":"link in","z":"1261da8e.128f05","name":"","links":["73690c5c.4257d4"],"x":255,"y":180,"wires":[["fd30a64e.309798"]]},{"id":"59242362.bd0a0c","type":"debug","z":"510ee227.2ad51c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":380,"y":60,"wires":[]},{"id":"eb07f709.6248e8","type":"subflow:510ee227.2ad51c","z":"1261da8e.128f05","name":"","x":360,"y":240,"wires":[]},{"id":"e551104f.abdba","type":"subflow:7f0b94d9.2c95cc","z":"1261da8e.128f05","name":"","x":360,"y":300,"wires":[]},{"id":"a8c3694d.824ec8","type":"subflow:26b00c38.afa344","z":"1261da8e.128f05","name":"","x":360,"y":360,"wires":[]},{"id":"8f2c8132.2a401","type":"subflow:681b4263.d9d16c","z":"1261da8e.128f05","name":"","x":360,"y":420,"wires":[]},{"id":"60dbdea2.2748d","type":"subflow:7818d86d.ef4a08","z":"1261da8e.128f05","name":"","x":360,"y":480,"wires":[]},{"id":"45fa2b54.d40c14","type":"debug","z":"7f0b94d9.2c95cc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":220,"y":40,"wires":[]},{"id":"d1bb0c6e.f2ed2","type":"debug","z":"26b00c38.afa344","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":300,"y":60,"wires":[]},{"id":"f5167a1e.566c48","type":"debug","z":"681b4263.d9d16c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":310,"y":40,"wires":[]},{"id":"27371be6.859644","type":"debug","z":"7818d86d.ef4a08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":300,"y":180,"wires":[]},{"id":"430e56e0.648bd8","type":"inject","z":"1261da8e.128f05","name":"","topic":"","payload":"Hello","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":340,"wires":[["eb07f709.6248e8","e551104f.abdba","a8c3694d.824ec8","8f2c8132.2a401","60dbdea2.2748d"]]}]

**Comment by prothorin** [comment]
Working with only 1 subflow,
I think the error is in the subflow to flow system.

**Comment by knolleary** [comment]
Why have you closed this?
