### ISSUE TITLE
switching between two flows.json programatically

### ISSUE THREAD

**Issue by sivachaitanya** [node-red/node-red#2169]
I have two .json flow files, flowA.json and flowB.json. At the front-end when certain drop down selection has happened I would like to load node-red editor with flowA.json / flowB. json, what would be the best approach to achieve this ?

**Comment by hardillb** [comment]
Please read the template you were shown when opening this issue. Questions skid be asked on the forum/slack/StackOverflow.

This was also pointed out on the closed issue you commented on
