### ISSUE TITLE
some TypedInput options dont emit change events

### ISSUE THREAD

**Issue by nileio** [node-red/node-red#2179]
Hi All,

I have a custom node with a TypedInput with multiple types including msg, flow, str, global and a custom type. 
I would like to detect the change when the user selects any of the types. 
The change event is successfully received if the type is either str, or msg
However, the change event is not emitted if the type selected is anything else including my custom type. The code looks exactly the same. I can send more details but just wonder if this is a possible bug or I maybe missing something ?
Here is how I defined the custom types
```

            $("#node-input-symbol")
                .typedInput({
                    typeField: $("#node-input-symbolType"),
                    //  default: ["symbolslist"],
                    types: [
                        {
                            value: "symbolslist",
                            label: "Symbol",
                            icon: "red/images/typedInput/09.png",
                            options: ["none"]
                        },
                        "str",
                        "msg",
                        "flow",
                        "global"
                    ]
                })
                .typedInput("width", "68%");
```
The following event NEVER fires although I can confirm that symbolType value changes every-time I select a new type from the drop-down types list

```
  $("#node-input-symbolType").on("change", function() {
                console.log(
                    "detected a change in symbol type");
                );
            });
```
The following fires ONLY IF the type selected is str, or msg
```
    $("#node-input-symbol").on("change", function(type, value) {
                //value is true if at first load and no change
                console.log("symbol change: ", type, value);
  });

```
All other types do not emit the change event
Am I doing anything wrong ? Is there something I am missing ?

**Comment by nileio** [comment]
Hi all,
after hours of debugging , I found the problem about the custom type event emit.. It turns out that the attribute hasValue must be included in the custom type. 
The bug in red.js is here

```
_updateOptionSelectLabel: function(e) {
            var t = this.typeMap[this.propertyType];
            this.optionSelectLabel.empty(),
            e.icon ? 0 === e.icon.indexOf("<") ? c(e.icon).prependTo(this.optionSelectLabel) : -1 !== e.icon.indexOf("/") ? c("<img>", {
                src: e.icon,
                style: "height: 18px;"
            }).prependTo(this.optionSelectLabel) : c("<i>", {
                class: "red-ui-typedInput-icon " + e.icon
            }).prependTo(this.optionSelectLabel) : e.label ? this.optionSelectLabel.text(e.label) : this.optionSelectLabel.text(e.value),
            **t.hasValue** && (this.optionValue = e.value,
            this._resize(),
            this.input.trigger("change", this.propertyType, this.value()))
```
this.input.trigger is never called because t.hasValue fails. If you do not have hasValue attribute in your custom type then the line will never execute.

Please confirm. and Could you please fix this in next release ??!
I am still not sure why global, and flow types do not also emit change events.

**Comment by knolleary** [comment]
There are two separate things here.

1. change events not being triggered on the typeField input
2. change event not always being triggered on the main input.

Item 1 is something we can address. The assumption was users would only set a listener for a Change event on the main input element - as we trigger that whenever the type is changed. But it doesn't seem unreasonable to also trigger the change event on the typedField input if the user has given us one.

As for item 2, I cannot reproduce this on either 0.20.5 or 1.0.0-beta.2. In my testing, I always get a change event whenever I change the type, option or value.

Can you provide some more information (the issue template you were shown asked these questions for a reason, so we didn't have to ask again for them - please try to use the template in the future).

1. what version of NR you are using
2. what browser(s) you've tested this with
2. provide a specific sequence of steps you take, with as much detail as possible, you take to reproduce the issue?

**Comment by nileio** [comment]
@knolleary yes, that's right. there are 2 items.
As for item 1, I think it makes sense to trigger the change on typeField value. I understand the rationale for not currently having it but I think there will be use cases for it, so I guess we need an enhancement to trigger the change event on typeField value change.

As for item 2, here are the details
### What are the steps to reproduce?
define 2 fields
```
 symbol: { value: "", required: false },
 symbolType: { value: "str", required: false },
```
In <script type="text/x-red">, define the following form-row which will hold the field.
Note that display:none initially . This is because I manipulate the show/hide based on other fields selections. This is part of a bigger form.
```
                <div class="form-row node-input-api-symbol" style="display: none;">
                   <label for="node-input-symbol"><i class="fa fa-exchange"></i> Symbol</label>
                   <input type="text" id="node-input-symbol">
                   <input type="hidden" id="node-input-symbolType">
                </div>
```
define a typedInput as follow
```
$("#node-input-symbol")
                .typedInput({
                    typeField: $("#node-input-symbolType"),
                    types: [
                        {
                            value: "symbolslist",
                            label: "Symbol",
                            icon: "red/images/typedInput/09.png",
                            options: ["none"]
                        },
                        "str",
                        "msg",
                        "flow",
                        "global"
                    ]
                })
                .typedInput("width", "68%");
```
The listener as follows:
```
 $("#node-input-symbol").on("change", function(type, value) {
                //value is true if at first load and no change
                console.log("symbol change: ", type, value);
  });
```
### What happens?
Only str, msg events are received. If the user selects flow,global or symbolslist(the custom type) no event is received.
If i add the attribute hasValue:true to each of flow,global and symbolslist, then I receive all events as expected.
### What do you expect to happen?
receive events for all types
### Please tell us about your environment:

- [ ] Node-RED version:  0.20.5
- [ ] node.js version: v10.14.2
- [ ] npm version: 6.5.0
- [ ] Platform/OS: MacOS
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
I still cannot reproduce this. I get the change event in all cases. There must be something particular about your scenario that I'm missing.

**Comment by nileio** [comment]
this is bizarre ! I will need to try reproduce this from scratch then and report back.. I have plenty of other things happening in this custom node but can't think of something that maybe interfering with the event listener really.. will try learn some more
I will try do it later tonight

**Comment by nileio** [comment]
will close this issue @knolleary I cannot reproduce it either now on my new custom nodes. that was my first custom node so I think it might be a different code interfering..

**Comment by H3llsing** [comment]
### What are the steps to reproduce?       

- Writing a custom node
- defining one dropdown and a typedinput
- add a change listener on the dropdown in the oneditprepare event
- react on change and change the typedinput's label
```
<script type="text/javascript">
    const nameProp = 'TypedInputTest'


    RED.nodes.registerType(nameProp, {
        category: 'test',
        color: '#C0DEED',
        defaults: {
            // visible
            iaType: {value: "a", required: true},


            // HTTP
            httpEndpointType: {'value': 'a'},
            httpEndpointValue: {
                value: "", validate: function (v) {
                
                        let isValidEndpoint = $("#node-input-httpEndpointValue").val().trim().length > 0
                        return isValidEndpoint
            
                    return true
                }
            },
        inputs: 1,
        outputs: 1,
    oneditprepare: function () {
        let aType = {types:[{label:"a", value:"str"}]}
        let bType = {types:[{label:"b", value:"str"}]}
        let cType = {types:[{label:"c", value:"str"}]}

        $("#node-input-iaType").change(function () {
            switch ($(this).val()) {
                case 'a':
                    console.log('a')
                    $("#node-input-httpEndpointValue").typedInput(aType);
                    break
                case 'b':
                    console.log('b')
                    $("#node-input-httpEndpointValue").typedInput(bType);
                    break
                case 'c':
                    console.log('c')
                    $("#node-input-httpEndpointValue").typedInput(cType);
                    break
                default:
                    console.log('default')
            }

        })
    }
```

extracted html part
```
<script type="text/html" data-template-name="property">
 <div class="form-row">
        <label for="node-input-iaType"><i class=""></i> Type</label>
        <select id="node-input-iaType" style="width:70%">
            <option value="a" selected="selected">A</option>
            <option value="b">B</option>
            <option value="c">C</option>
        </select>
    </div>

<div class="form-row">
              <div id="http-settings">
                    <label for="node-input-httpEndpointValue"><i class=""></i> Endpoint</label>
                    <input class="form-control" type="text" id="node-input-httpEndpointValue"
                           placeholder="" style="width:70%">
                    <input type="hidden" id="node-input-httpEndpointType">
                </div>
</div>
</script>
```

### What do you expect to happen?
when switching the dropdown of iaType (a,b,c) i would expect, that the change listener triggers and the typeinput switches the label immedeatly

### What happens?
the console.log is beeing printed with the correct value, but the typedinput does not change. Only if you click done and reopen the node config it has been changed.
if you use   ` $("#node-input-httpEndpointValue").typedInput('types',['num']);`  ` $("#node-input-httpEndpointValue").typedInput('types',['str']);`  ` $("#node-input-httpEndpointValue").typedInput('types',['bool']);`  instead of the typedefinitions, you see it changing directly!


### Please tell us about your environment:

-  Node-RED version: 1.22
-  node.js version: v12.18.2
-  npm version: 6.14.5
-  Platform/OS: Windows x64
-  Browser: Chrome

**Comment by knolleary** [comment]
@H3llsing this issue has been closed for over a year.

Please a new issue.
