### ISSUE TITLE
WebSocketListenerNode.prototype.broadcast - variable "i" is not defined

### ISSUE THREAD

**Issue by kedzior-io** [node-red/node-red#2182]
https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/io/22-websocket.js#L210

```
        catch(e) { // swallow any errors
            this.warn("ws:"+i+" : "+e);
        }
```

`i` is not defined within the function. 

Also I think there is a typo:
https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/io/22-websocket.js#L98
```

            this.serverConfig.on('erro', function(event) {
                node.status({
                    fill:"red",shape:"ring",text:"common.status.error",
                    event:"error",
                    _session: {type:"websocket",id:event.id}
                });
            });
```

`erro `-> `error`

**Comment by knolleary** [comment]
`erro` is a terrible name for an event, but it is not a type. I assume it was chosen to be distinct from a proper `error` event - but I don't recall the specifics now.

You can see the `erro` event is listened for here: https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/io/22-websocket.js#L240
