### ISSUE TITLE
Change node: problem with JSONata and $lookup when used with a chain (~>) operator

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#2183]
### What are the steps to reproduce?
Send messages in quick succession (such as with a split node) to a change node configured to do a $lookup in JSONata using the chaining operator. (see example flow)
### What happens?
The change node emits this error:
```
"Invalid JSONata expression: Argument 2 of function "lookup" does not match function signature"
```
And from that point any message sent to it won't work.
### What do you expect to happen?
I expect this to work. It broke in Node-RED 0.19.0, worked prior to this.
### Please tell us about your environment:

- [ ] Node-RED version: 0.20.5
- [ ] node.js version: 8.15
- [ ] npm version: 6
- [ ] Platform/OS: MacOs
- [ ] Browser: Safari

```
[{"id":"d10dc7f.f9241b8","type":"change","z":"26437d6.f72e102","name":"lookup with ~>","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\t   '1': 'goat',\t   '2': 'cheese'\t} ~> $lookup($string(payload))","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":600,"y":380,"wires":[["3a429d39.22976a"]]},{"id":"3a429d39.22976a","type":"debug","z":"26437d6.f72e102","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":930,"y":380,"wires":[]},{"id":"ef556b69.b978f","type":"split","z":"26437d6.f72e102","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":390,"y":380,"wires":[["d10dc7f.f9241b8"]]},{"id":"514ba59c.28eff4","type":"inject","z":"26437d6.f72e102","name":"","topic":"","payload":"[1,2]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":230,"y":500,"wires":[["ef556b69.b978f"]]},{"id":"f48614b5.fef1c8","type":"inject","z":"26437d6.f72e102","name":"","topic":"","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":230,"y":180,"wires":[["d10dc7f.f9241b8"]]},{"id":"2214ce8.31041b2","type":"inject","z":"26437d6.f72e102","name":"","topic":"","payload":"[1]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":230,"y":340,"wires":[["ef556b69.b978f"]]},{"id":"684840a.05628c","type":"comment","z":"26437d6.f72e102","name":"Always works","info":"","x":230,"y":140,"wires":[]},{"id":"6fe1d59.c37c2ac","type":"comment","z":"26437d6.f72e102","name":"Breaks the change node forever","info":"","x":290,"y":460,"wires":[]},{"id":"c9969e9d.8c62","type":"change","z":"26437d6.f72e102","name":"lookup without ~>","rules":[{"t":"set","p":"payload","pt":"msg","to":"$lookup({\t   '1': 'goat',\t   '2': 'cheese'\t}, $string(payload))\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":610,"y":600,"wires":[["3a429d39.22976a"]]},{"id":"5f560f46.11214","type":"comment","z":"26437d6.f72e102","name":"Fails","info":"","x":570,"y":340,"wires":[]},{"id":"1e8c4e7e.1f1d12","type":"comment","z":"26437d6.f72e102","name":"Works","info":"","x":570,"y":560,"wires":[]},{"id":"5cf5af58.3d0468","type":"inject","z":"26437d6.f72e102","name":"","topic":"","payload":"[1,2]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":230,"y":600,"wires":[["9ce71d82.5c2e1"]]},{"id":"9ce71d82.5c2e1","type":"split","z":"26437d6.f72e102","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":410,"y":600,"wires":[["c9969e9d.8c62"]]}]
```

**Comment by knolleary** [comment]
This is an issue with parallel execution of a jsonata expression that involves `~`.

The following code reproduces it in a vanilla JSONata test case:

```
const jsonata = require("jsonata");

const expr = jsonata("{'1':'goat','2': 'cheese'} ~> $lookup($string(payload))");

expr.evaluate({"payload":1}, {}, function(err,result) {
    console.log("1",err);
    console.log("1",result);
});
expr.evaluate({"payload":2}, {}, function(err,result) {
    console.log("2",err);
    console.log("2",result);
});
```

As a callback is provided to the `evaluate` function it is put into async evaluation mode. This allows the second call to `evalute` to be made before the first has completed.

I suspect it is wrong for us to be calling `evaluate` a second time on an expression with the first call outstanding. But we certainly benefit from being able to do so for other types of expression as we don't have to queue work up.

Think we need some input from @andrew-coleman here.

Is this an issue with jsonata or is it entirely our fault for calling evaluate in parallel?

One workaround would be to inspect the expression for `~>` (assuming that is the magic piece causing the issue) and put the node in to a more blocking evaluation mode. That would limit the performance hit to just those sorts of expression.

**Comment by andrew-coleman** [comment]
Would it be any use if you wrapped the invocation of evaluate in a promise?  E.g.:

```
var jsonataPromise = function(expr, data, bindings) {
    return new Promise(function(resolve, reject) {
        expr.evaluate(data, bindings, function(error, response) {
            if(error) reject(error);
            resolve(response);
        });
    });
};
```
Then `jsonataPromise(expr, {"payload":1})` would return a promise that you could either chain, or use Promise.all() if you want to run them in parallel.

Not sure if that helps

**Comment by knolleary** [comment]
We try to avoid promises on the main message path due to the performance overhead - learnt that the hard way.

We can queue up the evaluations if needed (via promises or otherwise), but I wanted to confirm this error was a natural result of how we were using jsonata and not a bug in jsonata itself.

**Comment by andrew-coleman** [comment]
Sorry, I should have paid more attention to the original bug report.  This is clearly a JSONata bug.  Interestingly, this test case works against jsonata v1.3 - I did something to regress it since then.  Please feel free to raise an issue... https://github.com/jsonata-js/jsonata/issues/new

**Comment by natcl** [comment]
Version 1.6.5 of JSONata was released with the fix !
