### ISSUE TITLE
how to get the node-red and drag the event of the node.

### ISSUE THREAD

**Issue by limengsong** [node-red/node-red#2184]
Hello:
I want to get the node-red and drag the event of the node.
such as:
There are some nodes that can be dragged to the workspace, and some nodes are forbidden to drag to the workspace.
Do not know how to judge?
Request help

**Comment by knolleary** [comment]
Please read the template you were shown when raising this issue.

> If your issue is:
>  - a general 'how-to' type question,
>  - a feature request or suggestion for a change,
>  - or problems with 3rd party (`node-red-contrib-`) nodes
>
> please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).
