### ISSUE TITLE
Flow context updates value when it shouldn't

### ISSUE THREAD

**Issue by notenoughtech** [node-red/node-red#2199]
I'm using flow.set to set a JSON object:
`{"state":"ON","linkquality":0,"brightness":255,"color":{"x":0.3227,"y":0.329},"color_temp":155}`

I'm loading this JSON as var `test =flow.get()`
then changing the value with 
`test.state = "value";
return msg;` . 

That function node doesn't update the context again (no flow.set()), however, the context explorer reports value change to : `{"state":"value","linkquality":0,"brightness":255,"color":{"x":0.3227,"y":0.329},"color_temp":155}`
and it shouldn't.

 Running the same function again to load the JSON from the context, gives me 
`"state": "value"`
 not 
`"state": "ON"`

NodeRED 0.20.5 (docker:latest tag)

**Comment by knolleary** [comment]
This is a result of using the in-memory context store.

All context values are stored in memory. JavaScript passes objects be reference, which means when you retrieve it from context, you are retrieving a reference to the object in context. Modifying that object will modify the object held in context.

If you need to modify the value without changing the value in context, you can clone it first:

```
var test = RED.util.cloneMessage(flow.get("test"));
```

**Comment by notenoughtech** [comment]
Thanks, bunch. I wasn't sure if this is intended behaviour, I guess I was trying to be lazy :) I appreciate the quick response!
