### ISSUE TITLE
Error thrown when installing 0.20.6

### ISSUE THREAD

**Issue by vicary** [node-red/node-red#2218]
### What are the steps to reproduce?
`sudo npm i -g node-red`

### What happens?
The current version on npm (0.20.6) depends on `@node-red/util@0.20.6` which seems to be not available yet.

Installing the last version (0.20.5) tries to build `bcrypt@3.0.5` but `node-gyp` throws on EACCESS [npm-install.log](https://github.com/node-red/node-red/files/3314644/npm-install.log).

### What do you expect to happen?
Install proceed normally.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.6
- [x] node.js version: 12.4.0
- [x] npm version: 6.9.0
- [x] Platform/OS: darwin
- [x] Browser: N/A

**Comment by knolleary** [comment]
`@node-red/util@0.20.6` has now been published.
