### ISSUE TITLE
Https node with session resumption 

### ISSUE THREAD

**Issue by Kiran6224** [node-red/node-red#2233]
Hi, 
 
I am using device with webserver installed on it with http and https protocol. i am using https node in node red to request to device. i rapidly request to device for same data with inject node.
 
Problem - When i run python and java script to request to the device it is create one session and though that i am getting result for the rapid requests
but in case of node red https node it creating new session/socket for every request. that why my device sending timeout for some requests.

thanks,

so i want to session resumption/(keep session/socket) alive.

**Comment by hardillb** [comment]
Please read the template you were shown (and deleted) when opening this issue, it explicitly points out that questions should be asked on the forum/slack/StackOverflow and that issues are for actual code defects only.

**Comment by Kiran6224** [comment]
i already did it on node red forum. The expert suggested me to raise this issue on github. 
please refer the below link 
https://discourse.nodered.org/t/enable-tls-ssl-session-resumption-in-https-node/13200/3

**Comment by hardillb** [comment]
Where Nick (the project lead) has explicitly told you NOT to do this.

Even if you did have a legitimate reason to open an issue it would be closed without the template anyway as this collects the required information to know where to start.

**Comment by knolleary** [comment]
@hardillb I added that comment before I noticed this issue had been raised.

@Kiran6224 As the issue template says, we don't use this issue tracker for feature requests. Julian was well intentioned in suggesting you raise an issue, but as its a core node of the project, we prefer to discuss feature requests on the forum in the first instance. There is a category for that: https://discourse.nodered.org/c/development/feature-requests - I have moved your post to that category.

I have no idea how to enable this feature. A search around doesn't find any answers. If you wanted to do some more research on how to do this for an express.js based server, then please let us know.

But as per our contribution process, I'm going to close this issue and we can continue the discussion on the forum.
