### ISSUE TITLE
Request: add message API to support smooth iframe integration

### ISSUE THREAD

**Issue by anatolyw** [node-red/node-red#2239]
In my product I integrate node-red in `<iframe>` inside a bigger admin dashboard which is written in Angular. Also I put a list of node-red flows to the left-side menu of my dashboard as it is more convenient for me from UI perspective.

**CURRENT STATE**: when I select flow on my left-side menu I have to reload content of iframe as there is no possibility to communicate with node-red inside and instruct it to switch to different flow smoothly. Result: refresh of node-red inside iframe.

**PROPOSAL**: include in `index.mst` following script:
```javascript

...

<!-- PATCH: BEGIN -->
<script>
    function displayMessage (evt) {
        const selector =  `red-ui-tab-${evt.data}`
        const el = document.getElementById(selector);
        const elTrigger = el.querySelector('a');
        if (elTrigger.onclick) {
        elTrigger.onclick();
        } else if (elTrigger.click) {
        elTrigger.click();
        }
    }

    if (window.addEventListener) {
        // For standards-compliant web browsers
        window.addEventListener("message", displayMessage, false);
    } else {
        window.attachEvent("onmessage", displayMessage);
    }
</script>
<!-- PATCH: END -->

</body>
</html>
```

with such script in place it would be possible to have implementation on Angular front-end similar as below and have smooth switch between flows inside `iframe`:

HTML:
```html
<iframe #noderedframe id="noderedframe" class="editor__frame" src="http://localhost:8000/red/" width="100%" height="768"></iframe>
```

Angular + TypeScript:
```typescript
  @ViewChild('noderedframe') nodered: ElementRef<HTMLIFrameElement>;
...
  postMessageSelectedFlow(flowId: string) {
    this.nodered.nativeElement.contentWindow.postMessage(flowId.replace('.', '-'), 'http://localhost:8000');
  }
```

**ADDITIONAL PROPOSAL (OPTIONAL)**: extend node-red front-end with richer API in order to control its behavior inside `iframe`, for example: hide native tab-bar with flow names if it is implemented outside as in above scenario.

**Comment by hardillb** [comment]
Please supply the link to the forum where this was discussed as described in the contribution guide (pointed to in the template you have removed)

**Comment by anatolyw** [comment]
Thank you for notice. I have opened a new feature on the forum. I will post a link here as soon as it will be approved.

**Comment by hardillb** [comment]
That wasn't the point, the point was that the template clearly points out that issues are for defects only, not questions or feature requests

**Comment by anatolyw** [comment]
I have seen that some issues are marked with `feature` label, but I could not set one.

**Comment by hardillb** [comment]
That doesn't mean you should ignore the instructions in the template

**Comment by anatolyw** [comment]
OK, please, tell me how to proceed and go forward. I have opened feature request on the forum as you have suggested, but my account there is on-hold and request is in review. It will take some time. What should I do with this issue?

**Comment by hardillb** [comment]
Close it, if it the feature requests is accepted then it will be added to the appropriate place

**Comment by anatolyw** [comment]
ok

**Comment by knolleary** [comment]
The admins of the forum and maintainers of Node-RED are currently on holiday. So your post in the forum may not be responded to instantly. A little patience is appreciated.
