### ISSUE TITLE
Recurring “The flows on the server have been updated” message

### ISSUE THREAD

**Issue by nodecentral** [node-red/node-red#2249]
This issue was reported first on the forum, and was requested to be raised here.

https://discourse.nodered.org/t/recurring-the-flows-on-the-server-have-been-updated-message/13885

Q: What are the steps to reproduce?
A: A simple browser referesh returns a conflict message

Q: What happens?
A: Every time I refresh the browser, either to purge unwanted changes, or to get an updated config, this message comes up, reporting no conflicts, yet still asks me to either merge or ignore (see forum post for more details)

Q: What do you expect to happen?
A: I do not expect this message unless there is an actual conflict

My environment:

- [ 20.7] Node-RED version:
- [ 10.6.0] node.js version:
- [6.10.2 ] npm version:
- [ Seen on iOS and WIndows 10] Platform/OS:
- [Safari (iOS) or Chrome (PC) ] Browser:

**Comment by knolleary** [comment]
Identified as an issue with the current version of `node-red-contrib-harmony-websocket`.
