### ISSUE TITLE
Limitation of parallel connections

### ISSUE THREAD

**Issue by danielpfeiferatadamos** [node-red/node-red#2254]
### What are the steps to reproduce?
I use node-red (gui) with several data-point-items nodes and one opc-ua client node.
The server is provided by a third-party-company.
This was working fine in the past.

### What happens?
The third-party-company limit parallel connections to server to 4 per client.
So I tried to limit the number of connections to 4 too, but this is not working.

### What do you expect to happen?
I would expect some property will limit the number of connections of node-red (or the express-server). I tried different, no one have have any effect.

e.g. 

let events = require('events');
events.maxListeners = 4;
events.maxConnections=4;

var http = require('http');
var https = require('https');
http.globalAgent.maxSockets = 4;
https.globalAgent.maxSockets =4;

or for export-part:

maxSockets: 2,

or 

server: {
  events: {
    maxConnections: 4
  }
},
  http: {
    agent: {
      maxSockets: 4
    }
  },

### Please tell us about your environment:

- [x] Node-RED version:  v0.20.7
- [x] node.js version:  v12.6.0
- [x] npm version: 6.9.0
- [x] Platform/OS: Windows_NT 10.0.17763 x64 LE
- [x] Browser: Version 76.0.3809.87 (Offizieller Build) (64-Bit)

**Comment by knolleary** [comment]
Can you clarify which bit you are trying to limit.

You say you have a 3rd party server that only allows up to 4 connections per client.

You ask about limiting the Express connections, but that is the HTTP server in Node-RED and completely unrelated to Node-RED acting as a client and connecting to other systems.

You mention an opc-ua client node - isn't it that node which should be configured to limit the number of connections it makes? If so, you should ask the author of that node.

**Comment by danielpfeiferatadamos** [comment]
Node-Red use Express for http-server for gui only, not providing/handling connections (eg. via middlewares) to to other systems?
Perhaps I misunderstood the setup.

**Comment by knolleary** [comment]
Express is an HTTP Server framework, it has nothing to do with making http requests to other servers.

It is up to individual nodes on how they manage their connections of whatever type they happen to be.

If you are using an opc-ua node in your flow to create the connection, then you should be talking to its author if you have a particular requirement of it.

**Comment by danielpfeiferatadamos** [comment]
Ok, I had wrong impression for the responsibility. Thank you for your answer.
I'll try this.

**Comment by danielpfeiferatadamos** [comment]
I'll close this immediately
