### ISSUE TITLE
Install does not add to PATH

### ISSUE THREAD

**Issue by JamesBlakeyMilner** [node-red/node-red#2270]
### What are the steps to reproduce?
install via npm on windows
attempt to run via windows cmd
as per instructions: https://nodered.org/docs/getting-started/windows#quick-start
### What happens?
Installation using npm completes as expected. cmd cannot find node-red. ie. node red is not added to the windows PATH.
There is no documentation to manually add node-red to the windows path.
I am unable to run it at all.
### What do you expect to happen?
node-red should be added to the PATH while installing and be recognized by the windows cmd.
### Please tell us about your environment:

- Node-RED version: [0.20.7 ] 
- Node.js version: [10.15.2] 
- npm version: [6.10.3] 
- Platform/OS: [Windows 10  17763] 
- Browser: [Chrome]

**Comment by knolleary** [comment]
Node-RED isn't responsible for setting up your path.

When you install an npm module globally, any executable is placed in the npm global module bin directory.

If node/npm is properly installed, then that directory should be in your path already.

How did you install node?

**Comment by votecoffee** [comment]
It's common that windows path is too long to append automatically when installing Node.js

Manually modify the Path to add these entries:
C:\Program Files\nodejs\bin
C:\Program Files\nodejs
C:\Program Files\nodejs\node_modules\npm\bin
%AppData%\npm

**Comment by knolleary** [comment]
Closing as this hasn't had any activity and Node-RED cannot be responsible for how `node` sets up the path environment.
