### ISSUE TITLE
Localfilesystem context corrupted in some crash-cases

### ISSUE THREAD

**Issue by w4tsn** [node-red/node-red#2271]
### What are the steps to reproduce?

Setup a persistent local context storage with the `localfilesystem` module and default configuration.

Create a rather large global context by saving objects with, let's say, 10 arrays each having 1000 lines.

Cause a memoy-leak.

### What happens?

When a memory-leak occures or a very memory-consuming process consumes all available memory and a flush occures at the same time the write process and therefore the json containing the global context get's damaged and ignored on a nodered restart, leading to an empty global context.

### What do you expect to happen?

The localfilesystem module and persistent global context should be resilient to many if not all kinds of errors that may happen in a typical execution of the nodered runtime. I'd expect the module to choose an atomic file write operation, like `mv` command on linux systems in combination with a `*.tmp` file to counter file write corruption.

### Please tell us about your environment:

- [x] Node-RED version: 0.19.2
- [x] Node.js version: v8.11.2
- [x] npm version: 5.6.0
- [x] Platform/OS: Raspbian GNU/Linux 9 (stretch)
- [ ] Browser:

**Comment by knolleary** [comment]
Thanks - have pushed a fix to `dev` (for 1.0) that does just what you suggest.
