### ISSUE TITLE
Deploy button doesn't work after link connection delete

### ISSUE THREAD

**Issue by Installka** [node-red/node-red#2274]
### What are the steps to reproduce?
Delete connection between link out and link in nodes.

### What happens?
Deploy button still turned off, so user can't deploy flow.

### What do you expect to happen?
Deploy button should turn on.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.7
- [x] Node.js version: 10.16.3, 10.16.2
- [x] npm version: 6.9.0
- [x] Platform/OS: Windows 7 x64, Debian 9.3
- [x] Browser: Google Chrome 76.0.3809.100

**Comment by knolleary** [comment]
Fixed in the `dev` branch for 1.0
