### ISSUE TITLE
CSS class of submit button in login form

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red#2275]
### What are the steps to reproduce?

Using node-red-contrib-theme-midnight-red@1.0.0-beta.8, editor authentication enabled, open Node-RED in browser and see login form.

### What happens?

Submit button style is not applied because class `red-ui-button` isn't used, text is not readable

![image](https://user-images.githubusercontent.com/2503307/63722424-73abf200-c853-11e9-8a86-7fd3709943a9.png)

### What do you expect to happen?

Submit button in login form should have class `red-ui-button` so the correct styling is used

### Please tell us about your environment:

- [x] Node-RED version: 1.0.0-beta.3
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

Tried to find out where this Button is defined and create a PR - but must admit that I wasn't successful, didn't find it...

Reference: https://github.com/bonanitech/node-red-contrib-theme-midnight-red/issues/6

**Comment by dceejay** [comment]
I think its in `packages/node_modules/@node-red/editor-client/src/js/user.js`

**Comment by knolleary** [comment]
Closing as this was fixed by #2277
