### ISSUE TITLE
How to recover from a crash ?

### ISSUE THREAD

**Issue by dsl400** [node-red/node-red#2278]
I call this: "bad experience"
there is no solution to recover after a typo

### What are the steps to reproduce?
` functionGlobalContext: {
	SPI:require('pi-spi'),`

create a function node, 

`spi.transfer(b,b.length,function(e,d){
    /* call to undefined function in the callback of spi.transfer*/
   undefindenFunction()
`

### What happens?
Node-Red crashed, no UI 

> This site can’t be reached 192.168.0.31 refused to connect.

> 4 Sep 08:22:55 - [red] Uncaught Exception:
4 Sep 08:22:55 - ReferenceError: undefindenFunction is not defined
    at Function node:cdf5d431.98a838 [Camera Init]:14:5
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.

### What do you expect to happen?
now what?
what can I do from here ?
where is the undo button ?

### Please tell us about your environment:
- [ ] Node-RED version: v0.20.7
- [ ] Node.js  version: v10.16.3
- [ ] NPM version: 6.11.2
- [ ] Platform/OS: linux/raspbian
- [ ] Browser: chrome

**Comment by knolleary** [comment]
For general help, please use the [forum](https://discourse.nodered.org/)

The best thing to do here is to start Node-RED in safe mode (use `--safe` after the `node-red` command). That will allow you to edit the function, fix the error and deploy the change.

**Comment by dsl400** [comment]
I'm so happy for the fast reply.
However it's not about me or about getting help. It's about new users that get completely lost. Imagine that it is your second time you use node-red and you have very little experience with anything that makes it work.
I suggest using `--safe` as default and inform the advanced user about it

**Comment by hardillb** [comment]
Safe as default doesn't work because it requires a deploy to start the flow, which means that is you run Node-RED as a Daemon it won't start at the flow without manual intervention

**Comment by knolleary** [comment]
You have highlighted a particularly hard to solve issue - where an error is thrown in an asynchronous callback the user has created without any proper error handling. We cannot add error handling for that because it isn't our code.

From node's own [documentation on handling 'uncaughtExceptions'](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly)

> Unhandled exceptions inherently mean that an application is in an undefined state. Attempting to resume application code without properly recovering from the exception can cause additional unforeseen and unpredictable issues.

If you have a suggestion for something to improve or change, then, as the issue template you filled in said, please use the `feature-request` category on the forum.

**Comment by dsl400** [comment]
This is not my request. Only a suggestion 
in your code you know the server has crashed 

> 4 Sep 08:22:55 - [red] Uncaught Exception:
4 Sep 08:22:55 - ReferenceError: undefindenFunction is not defined
at Function node:cdf5d431.98a838 [Camera Init]:14:5
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.

and instead of stopping the server and leaving the user in mid air you can redirect to a page that describes the situation and present the user with  some options. 

![image](https://user-images.githubusercontent.com/4988046/64316544-d02eb000-cfbd-11e9-82cc-b0ba6d64c311.png)

**Comment by knolleary** [comment]
Discussion moved to the forum: https://discourse.nodered.org/t/recover-from-server-crash/15132
