### ISSUE TITLE
node-red lacks a security contact

### ISSUE THREAD

**Issue by sam-github** [node-red/node-red#2279]
https://github.com/node-red/node-red/security/policy is empty, and there is no contact in the readme, or nodered.org, please consider adding this information.

The Node.js ecosystem security team has received a report for node-red and I'm searching for who to report it to. I've reached out privately to @knolleary so far.

**Comment by knolleary** [comment]
Hi @sam-github - thanks for bringing that to our attention. We'll get a security policy in place.

What channel have you reached out to me via? I do not see any messages via the various ways I can be reached

**Comment by knolleary** [comment]
Ah - I see the HackerOne message now. Thanks.

**Comment by knolleary** [comment]
Security policy now in place - thanks! https://github.com/node-red/node-red/security/policy

**Comment by sam-github** [comment]
Great, thanks.
