### ISSUE TITLE
Can we get a self contained executeable windows installer?

### ISSUE THREAD

**Issue by gigajoules** [node-red/node-red#2280]
Sorry if this is an improper channel but I am having great difficulty installing on windows within our corporate environment due to our stern security policies. 

I've found a lot of people have similar problems and it seems a good workaround would be to have an exe that doesn't need to pull any more data from repos and just lets you get up and running with some basic features?

**Comment by knolleary** [comment]
Hi @gigajoules. As per the issue template you were shown, please use discourse.nodered.org to discuss this sort of request.

**Comment by knolleary** [comment]
Closing as per my comment above.

**Comment by ericoloewe** [comment]
Why you don't use [nexe](https://github.com/nexe/nexe) to generate an executable?
