### ISSUE TITLE
Cannot connect to OPCUA Demo Server from Unified Automation (UaNetServer) using Node-RED IIoT Read or Write

### ISSUE THREAD

**Issue by parth-ifam** [node-red/node-red#2288]
### Issue
Unable to connect to OPCUA Server created by Unified Automation .NET classes

### What happens?
- The IIoT OPCUA Read or Write block shows connecting but cannot connect to the Server.
- Server is the demo server (ServerGettingStarted_Net40.sln) from Unified Automation .NET classes. Example Lesson01
- No errors are reported by Node-RED except Error Stopping the Nodes_ Close timed out _upon deploying_
- Both server and client are running locally. With UaExpert it is possible to connect to the server
- The server does not have any security and certificates are not used.
- OPCUA Read and Write can connect to other OPCUA servers not programmed with Unified Automation.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.8
- [x] Node.js version: 10.16.3
- [x] npm version: 6.9.0
- [x] Platform/OS: Windows 10
- [x] Browser: Mozilla Firefox 60.7.2esr

**Comment by knolleary** [comment]
Hi - this is the issue tracker for the core Node-RED runtime and editor. It does not provide any opcua functionality.

From the issue template:

> If your issue is:
>  - a general 'how-to' type question,
>  - a feature request or suggestion for a change,
>  - **or problems with 3rd party (`node-red-contrib-`) nodes**
>
>please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

Alternatively, you should raise an issue against which ever node module you installed to get the OPCUA nodes in your palette.
