### ISSUE TITLE
Function-Node: Wrong declared object variable will crash/freeze node-Red process!

### ISSUE THREAD

**Issue by n300home** [node-red/node-red#2292]
### What are the steps to reproduce?
In function node trying to fill an object property with data. But the object variable isn't properly declared.

e.g
```
var myvar; //<-- this declaration is incomplete cause property "myProperty" hasn't been definded!
myvar.myProperty = 5; //<-- Fill myProperty Prop with any data. After executing this line node-Red becomes unresponsive for ever.
```

### What happens?
node-Red process freezes completely. I can see via linux top that the process runs at 100% usage on one cpu core and nod-Red stops working. Also the editor becomes unresponsive. The only way to fix this is restarting nod-Red completely.
First time I had this problem it took me some time to debug, because also trace log stops just before the moment this mistake happens. Therefore I hadn't any idea in which function node this script mistake is located. At beginning I even had no idea where to start my debugging at all. It was also possible that one or more nodes from my installed palette triggers this behavior.

### What do you expect to happen?
A careless mistake in script should not crash complete node-Red Environment. I would expect an exception throw.

### Please tell us about your environment:

- [0.20.5 ] Node-RED version:
- [10.15.3 ] Node.js version:
- [6.9.0 ] npm version:
- [RaspberryPi 3b/RaspberryMatic with Redmatic ] Platform/OS:
- [Chromium ] Browser:

**Comment by knolleary** [comment]
There certainly are some types of error in the Function that will cause the node-red process to exit, because they are errors that are impossible for us to handle. But your example is not one of them.

When I run those two lines of code in a Function node I get an error in the log:

```
 24 Sep 11:48:08 - [error] [function:7ac716e2.e7c4e8] TypeError: Cannot set property 'myProperty' of undefined
```

and everything keeps running.

There must be something else going on here.

**Comment by n300home** [comment]
Strange thing, I think you're right. In a specific function node I experienced exactly my documented issue - reproduce able. 
But in a new one not. No idea what's the difference.
I'm quite new in node-red scripting. Maybe I used the catch-nodes per flow in a wrong way. I've fixed that now. We will see if this problem appears one more.
But many thanks for assistance :)
