### ISSUE TITLE
Subflow node color bug

### ISSUE THREAD

**Issue by bakman2** [node-red/node-red#2298]
### What are the steps to reproduce?

- hamburger menu > subflows > create subflow
- 1 input, 1 output, connect the 2.
- edit properties, appearance tab
- change the color
- new subflow node appears with new color, deploy
- add new flow
- drag the subflow node into the flow
- deploy

### What happens?
Subflow node changes color back to the original color (#DDAA99)
Refresh the browser and the node color is correctly shown as configured.

### What do you expect to happen?
The subflow node should show the inital node color as configured.

### Please tell us about your environment:

- [x] Node-RED version:1.0.0
- [x] Node.js version: v10.16.3
- [x] npm version: 6.11.3
- [x] Platform/OS: linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
- [x] Browser: MacOS/Safari 13.0.1

Some screenshots

![Screenshot 2019-10-01 at 22 03 52](https://user-images.githubusercontent.com/333960/65996308-7378c500-e497-11e9-81f1-d5d1760f8826.jpg)

![Screenshot 2019-10-01 at 22 04 01](https://user-images.githubusercontent.com/333960/65996317-75db1f00-e497-11e9-91c0-5576e5d43c1b.jpg)

**Comment by pdong** [comment]
@bakman2 I was able to reproduce.  It seems like this only occurs when the subflow doesn't exist on any flow tabs.  The contents of the subflow actually doesn't matter.  (You can simplify repro as just adding a subflow, changing the color, and dragging it onto a flow tab)

I opened a PR to attempt to fix this 🙏
