### ISSUE TITLE
1.0.1: package search not working as expected

### ISSUE THREAD

**Issue by andig** [node-red/node-red#2310]
I'm unable to find new packages using `Manage Palette` -> `Install`.

Entering `node-red-contrib-volkszaehler` or `volkszaehler` as search term and clicking the refresh icon does not give any result.

Expected result: a hit of https://www.npmjs.com/package/node-red-contrib-volkszaehler

### Please tell us about your environment:

- [X] Node-RED version: nodered/node-red:lastest-12
- [x] Node.js version: 12.0
- [x] Platform/OS: OSX
- [x] Browser: Safari

**Comment by hardillb** [comment]
You have not included the `node-red` keyword in your `package.json`

**Comment by hardillb** [comment]
https://nodered.org/docs/creating-nodes/packaging#packagejson

**Comment by knolleary** [comment]
The palette manage uses the catalogue provides by flows.nodered.org.

If your node isn't listed there, then it won't show up in the palette manager.

As Ben has said, you have not packaged the node properly for it to be picked up by the flow library.
