### ISSUE TITLE
Deleting links between LINK nodes doesn't activate `DEPLOY` button

### ISSUE THREAD

**Issue by Just-another-pleb** [node-red/node-red#2327]
I have a flow with `link` nodes that are interconnected.

Deleting the virtual links between the link nodes does not activate the DEPLOY button.

NR 0.20.8
Dashboard 2.16.3
node version 10.15.2
npm version 5.8.0
Ubuntu 18.4 LTS
Firefox 69.0.2

![Screenshot from 2019-10-13 22-50-32](https://user-images.githubusercontent.com/39888280/66797347-29dbb000-ef56-11e9-923e-f60a717fb295.png)

![Screenshot from 2019-10-13 22-50-48](https://user-images.githubusercontent.com/39888280/66797355-3233eb00-ef56-11e9-8515-fe49e692bc37.png)

**Comment by knolleary** [comment]
This is fixed in 1.0
