### ISSUE TITLE
Missing units in parameter-info

### ISSUE THREAD

**Issue by GitHubTestBln** [node-red/node-red#2333]
Please provide the unit of a parameter also in the info-pane. For example Milliseconds for timeout.
Many thanks.

**Comment by GitHubTestBln** [comment]
hello dceejay.
The context here is Node-Red v0.20.7 and my flow using a http-request-node. Reading the node-information I have not seen any unit. Especially for beginners it is essential to give unit-information as well - at least in my eyes.
I think this is a global requirement. Therefor I have not give more detailed information. I am sorry if this was confusing.

**Comment by knolleary** [comment]
What units are you referring to in the HTTP Request node? If you could give a concrete example of a core node that expects some numeric value and *doesn't* specify units in its help, then we can take a look.

**Comment by dceejay** [comment]
I guess you mean this  ? 
![image](https://user-images.githubusercontent.com/5375409/66994874-ebfd9980-f0c5-11e9-8c77-32d9d2939064.png)
as it's the only numeric parameter I can see...  but yes much easier when you point us to them directly...

**Comment by GitHubTestBln** [comment]
Yes. As I wrote "Milliseconds for timeout" in the "http-request-node". 
But again, I think it is a global requirement in documentation.

**Comment by knolleary** [comment]
Sorry, but your original comment did not identify the node - which is why we had to ask.

Thanks for reporting, we can get that fixed.

For future reference, please do use the template we provide when raising an issue as it helps to ensure enough information is provided first time.

**Comment by GitHubTestBln** [comment]
Okay.
Thanks for fixing!
 
BTW: great tool - great work! :-)

**Comment by dceejay** [comment]
All the other instances I can find either have the units in the edit dialog where you change them, or sometimes in the field prompt text. I think this is a rarity in being a settings.js value being overridden by the msg property. So currently just fixing this one.
Please shout if you spot any more.
