### ISSUE TITLE
commit button not visible in German 

### ISSUE THREAD

**Issue by unixweb** [node-red/node-red#2338]
That way the whole Node-RED user community can help, rather than rely on the core development team.

To help us understand the issue, please fill-in as much of the following information as you can:
-->

### What are the steps to reproduce?
If you switch in Settings language in German

### What happens?
Commit Button for "Local Changes" not visible if you change in Settings to German

### What do you expect to happen?
Commit for Local Changes not available
![Bildschirmfoto 2019-10-18 um 19 07 31](https://user-images.githubusercontent.com/12023025/67114082-63711d00-f1db-11e9-9cfa-14c350a6e989.png)
![Bildschirmfoto 2019-10-18 um 19 07 59](https://user-images.githubusercontent.com/12023025/67114083-63711d00-f1db-11e9-8bb5-db9ba4bd706d.png)

 

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.1
- [ ] Node.js version: 10.15.2
- [ ] npm version:  5.8
- [ ] Platform/OS: GNU Linux Buster 
- [ ] Browser: Firefox

**Comment by knolleary** [comment]
If you make the sidebar a bit wider does the button appear?

Suspect the length of the German text is pushing the button offscreen.

**Comment by unixweb** [comment]
Correct Nick if i push the sidebar wider i can see it ...
The German translated text is very long and covers the menu 
![Bildschirmfoto 2019-10-18 um 19 17 26](https://user-images.githubusercontent.com/12023025/67114440-2eb19580-f1dc-11e9-8830-cfeb1b78cfd2.png)

**Comment by jwende** [comment]
Ok ... i see the problem. Any recommendation for a better translation is welcome.
Cheers
Joerg

**Comment by pdong** [comment]
Thoughts on something like this?

![ellipsis](https://user-images.githubusercontent.com/5158502/67139133-5cf59c00-f201-11e9-9fde-a33085ebdf1b.gif)

We could position the buttons absolutely and then set padding on the `red-ui-sidebar-vc-change-header` headers then have the text overflow with ellipsis.

The tricky part is that since the buttons have translation strings they can be different widths as well.

**Comment by kuema** [comment]
> Ok ... i see the problem. Any recommendation for a better translation is welcome.

Besides the display issue, I would leave "commit" as-is in the translation. "Festschreiben" does not  even make sense to me.
The same goes for other _technical_ translations as well (e.g., "Deploy").
