### ISSUE TITLE
Integrating Passport.js

### ISSUE THREAD

**Issue by TJKoury** [node-red/node-red#234]
I've figured out a way to integrate Passport.js as an inline node; I'll post it to my node-red-nodes fork when it's done, just wondering if this is something that anyone else has tried or has an interest in seeing work a particular way.

**Comment by bigdoods** [comment]
This was a long time ago :) I couldn't find it in your node-red-nodes fork. Really looking for a way to use passport as part of a flow rather than using it as part of express middleware.
