### ISSUE TITLE
JSON5 support in json editor

### ISSUE THREAD

**Issue by copywrite** [node-red/node-red#2348]
I want to write hex values in json mode, then i find out that  the editor in node-red is Ace https://ace.c9.io/#nav=about, and the latest version of Ace does not support JSON5。

**Comment by dceejay** [comment]
so did you raise an issue on that project ? so when they fix it we can use it ?

**Comment by knolleary** [comment]
Hi @copywrite 

We provide a template for issues that ensures enough information is provided when they are raised. We also provide a template just for Feature Requests, which asks for them *not* to be raised here, but to be discussed on the forum in the first instance.

In this case, as @dceejay points out, you are reporting an issue that ACE doesn't support JSON5. We don't claim JSON5 support anywhere in Node-RED.

**Comment by copywrite** [comment]
> so did you raise an issue on that project ? so when they fix it we can use it ?

Raised an issue just now.

https://github.com/ajaxorg/ace/issues/4096

searched through Ace issues, and i found an old issue on hjson mode, but its slightly different than json5.

**Comment by copywrite** [comment]
> Hi @copywrite
> 
> We provide a template for issues that ensures enough information is provided when they are raised. We also provide a template just for Feature Requests, which asks for them _not_ to be raised here, but to be discussed on the forum in the first instance.
> 
> In this case, as @dceejay points out, you are reporting an issue that ACE doesn't support JSON5. We don't claim JSON5 support anywhere in Node-RED.

Copy that. 

I would close this issue and follow the Feature Requests instructions.
