### ISSUE TITLE
Debug node inside a nested subflow will not have the copy/pin/etc buttons show up

### ISSUE THREAD

**Issue by boisei0** [node-red/node-red#2358]
Somewhat related to #2315 

When using debug nodes inside subflows, for subflows that are inside other subflow instances the buttons for copy/pin/... won't show up when hovering. 

### What are the steps to reproduce?
1. Import the following flow
```
[{"id":"2e97756d.7272ba","type":"subflow","name":"Demo subflow for debug node copying","info":"","category":"","in":[{"x":80,"y":120,"wires":[{"id":"621445d.428bd3c"},{"id":"9fd0610c.563bf8"}]}],"out":[{"x":520,"y":120,"wires":[{"id":"9fd0610c.563bf8","port":0}]}],"env":[],"color":"#DDAA99"},{"id":"621445d.428bd3c","type":"debug","z":"2e97756d.7272ba","name":"payload at start (inside nested subflow)","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":340,"y":20,"wires":[]},{"id":"9fd0610c.563bf8","type":"function","z":"2e97756d.7272ba","name":"pass on message","func":"\nreturn msg;","outputs":1,"noerr":0,"x":290,"y":120,"wires":[["ebcb8b61.2f441"]]},{"id":"ebcb8b61.2f441","type":"debug","z":"2e97756d.7272ba","name":"full message at end (inside nested subflow)","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":680,"y":60,"wires":[]},{"id":"4c91a829.837a38","type":"subflow","name":"Demo for subflow in subflow","info":"","category":"","in":[{"x":20,"y":60,"wires":[{"id":"67dbfefa.087b68"}]}],"out":[{"x":320,"y":120,"wires":[{"id":"67dbfefa.087b68","port":0}]}],"env":[],"color":"#DDAA99"},{"id":"68b0cc1e.01c244","type":"debug","z":"4c91a829.837a38","name":"Complete object in parent subflow after subflow","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":480,"y":60,"wires":[]},{"id":"67dbfefa.087b68","type":"subflow:2e97756d.7272ba","z":"4c91a829.837a38","name":"Nested subflow","env":[],"x":160,"y":60,"wires":[["68b0cc1e.01c244"]]},{"id":"66e3a6a5.2053a8","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"9546445f.babac","type":"inject","z":"66e3a6a5.2053a8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":80,"wires":[["7a273c4d.d3f15c"]]},{"id":"8b3bdd37.17ba8","type":"debug","z":"66e3a6a5.2053a8","name":"Complete object in outer parent flow after subflow","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":670,"y":80,"wires":[]},{"id":"7a273c4d.d3f15c","type":"subflow:4c91a829.837a38","z":"66e3a6a5.2053a8","name":"","x":320,"y":80,"wires":[["8b3bdd37.17ba8"]]}]
```
2. Open debug sidebar
3. Press the inject button
4. Hover over the different messages

### What happens?
Notice that the buttons only appear for the debug nodes in the outermost flow, and the direct subflow instance (see #2315, which got fixed in 1.0.2), but not for the nested subflow instance.

### What do you expect to happen?
That the buttons appear for every subflow instance regardless of whether or not they're nested.

### Please tell us about your environment:

- [x] Node-RED version: 1.0.2
- [x] Node.js version: 10.17.0
- [x] npm version: 6.11.3
- [x] Platform/OS: Raspberry pi 4, ubuntu 19.10 server arm64
- [x] Browser: Firefox 70.0 on MacOS Catalina (10.15.0)

**Comment by dceejay** [comment]
hmm - working here
![image](https://user-images.githubusercontent.com/5375409/67806929-b8d6e500-fa8b-11e9-8b04-87a41764215a.png)

**Comment by boisei0** [comment]
Yes, if you take a look at the debug node's name it shows that it's located in the outer parent flow. Matching the condition stated in "what happens". The buttons do not show up for "payload at start (inside nested subflow)" and "full message at end (inside nested subflow)".

**Comment by boisei0** [comment]
see the following: 
<img width="452" alt="Screenshot 2019-10-29 at 21 40 45" src="https://user-images.githubusercontent.com/1899092/67807286-d2c8f580-fa94-11e9-8bf7-cfd645df55f3.png">

**Comment by okhiroyuki** [comment]
I tried the sample flow.
Certainly, this problem has occurred.

-  Node-RED version: 1.0.3
-  Node.js version: 10.13.0
-  npm version: 6.13.1
-  Platform/OS: Mac OS Catalina
-  Browser: Chrome on MacOS Catalina (10.15.0)
