### ISSUE TITLE
Config both MQTT in and out nodes causes disconnection

### ISSUE THREAD

**Issue by copywrite** [node-red/node-red#2360]
### What are the steps to reproduce?

1. create a new flow
2. config MQTT in and out nodes, and set the same broker url
3. the broker allow only one connection per client

### What happens?

Only one mqtt node could in the connected status, with a 60 seconds re-conn, if the in node connected, then the out node got kicked.

### What do you expect to happen?

shared connection? both the in and out nodes could connect 

### Please tell us about your environment:

- [ ] Node-RED version: v1.0.1
- [ ] Node.js version: v10.16.0
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Darwin 18.2.0 x64 LE
- [ ] Browser: chrome

**Comment by hardillb** [comment]
How many MQTT config nodes do you have? There should only be one shattered between both the MQTT-in & MQTT-out node

**Comment by dceejay** [comment]
and if you do have two then they need to have different clientid s (or use random ones)

**Comment by copywrite** [comment]
> How many MQTT config nodes do you have? There should only be one shared between both the MQTT-in & MQTT-out node

i cleaned all other config nodes then both in&out nodes connected ok

thanks

**Comment by copywrite** [comment]
> and if you do have two then they need to have different clientid s (or use random ones)

the clientId was fixed per username
