### ISSUE TITLE
Subflow status not showing i18n version of contained core nodes status

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#2375]
### What are the steps to reproduce?

 - create a subflow containing a core node (like tcp out - set to connect to anywhere valid or invalid) 
- add a status node inside the subflow and wire it to  the subflow's status output node.
 - deploy the new subflow as part of a flow

### What happens?

the subflow shows the untranslated status message

![image](https://user-images.githubusercontent.com/5375409/68382376-7ed0a780-014b-11ea-8b30-7f1303d8b849.png)

### What do you expect to happen?

It should show the i18n translated version - - in this case just "error"

It does work for some nodes (like mqtt node) - as they have their status strings set like
```
text:"node-red:common.status.disconnected"
```

Those without the `node-red:` namespace (about 80% of our core nodes) fail as per above.

One possible fix is to hack Subflow.js -line 203 to be
```
                    if (msg.status.hasOwnProperty("text") && msg.status.text.indexOf("common.") === 0) {
                        msg.status.text = "node-red:"+msg.status.text;
                    }
```
which forces any messages starting `common.`  to add the `node-red:` header - but I suspect this isn't the best fix :-)

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.2-git
- [ ] Node.js version: 12
- [ ] npm version: 
- [ ] Platform/OS:  Mac
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Fixed by #2388
