### ISSUE TITLE
Create flow with custom id

### ISSUE THREAD

**Issue by jwedel** [node-red/node-red#2384]
### What are the steps to reproduce?

- Create a new flow using the Admin api `POST /flow` with body: 
```
{
	"id": "12345678",
	"label": "Test Flow 1",
	"nodes" : []
}
```

### What happens?

- A flow is created and a random id is returned, e.g.: 
```
{
    "id": "9b1dd862.6dd5e8"
}
```

### What do you expect to happen?

- According to the [docs](https://nodered.org/docs/api/admin/methods/post/flow/), an id can be passed as argument but the response does not contain the passed id. I would expect that response:
```
{
    "id": "12345678"
}
```
### Please tell us about your environment:

- [ ] Node-RED version: 1.0.2
- [ ] Node.js version: ?
- [ ] npm version: ?
- [ ] Platform/OS: Linux
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Hi @jwedel - it is *not* possible to pass in a custom ID.

From the page you link to:

> **The runtime will assign a new id for the flow**. If the provided flow configuration object includes an id field it will be replaced and the z property of all nodes updated to match.

The second sentence there could be slightly clearer, but it is saying that if you provide your own ID, it will be replaced with the auto generated one.

**Comment by jwedel** [comment]
@knolleary You're right. I missed that. I actually ready the part that it must be unique... Damn, RTFM.

But why is there an example request body including the id? That was the part led me to the idea that it works... 
```{
  "id": "91ad451.f6e52b8",
  "label": "Sheet 1",
  "nodes": [ ],
  "configs": [ ]
}
```
