### ISSUE TITLE
Change node with JSONata $parseInteger fails with "#" picture string

### ISSUE THREAD

**Issue by michaelblight** [node-red/node-red#2387]
### What are the steps to reproduce?
Create a flow with inject->change->debug, set the change node to set JSONata data using $parseInteger (see code pasted below). The JSONata in the sample code is:
```
{
    "result": $parseInteger("50", "#")
}
```
Deploy and click on the inject.

`[{"id":"820000ea.4d1ca","type":"inject","z":"ac49425d.84b26","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":620,"wires":[["339793f0.0fc3ac"]]},{"id":"339793f0.0fc3ac","type":"change","z":"ac49425d.84b26","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\t    \"result\": $parseInteger(\"50\", \"#\")\t}\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":620,"wires":[["212fd0ff.3adc7"]]},{"id":"212fd0ff.3adc7","type":"debug","z":"ac49425d.84b26","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":535,"y":620,"wires":[],"l":false}]`

### What happens?
An error from the change node:
`Invalid JSONata expression: matchSpec.parse is not a function`

### What do you expect to happen?
In the case with the code above, `payload.output` to end up with the integer 50.

**NOTE:** I thought I'd see if `$formatInteger(50, "#")` had the same issue. This time I got a different error, which better explains the problem:
`Invalid JSONata expression: Formatting an integer as a sequence starting with "#" is not supported by this implementation`
Changing the two picture strings to be "0" instead makes the code work. So until "#" is supported, it would be better if $parseInteger produced a similar error message.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.2
- [ ] Node.js version: 10.16.3
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Ubuntu
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Hi - this is an upstream issue; the error messages in question are those generated by JSONata. Please raise an issue against JSONata itself - https://github.com/jsonata-js/jsonata/issues

**Comment by michaelblight** [comment]
Done
