### ISSUE TITLE
Search Library returns 404

### ISSUE THREAD

**Issue by IanAdd** [node-red/node-red#2389]
### What are the steps to reproduce?
Any link from google to node-red library results in a 404 error.
### What happens?
search with google 'node red 'sun events'
gives a number of possible links to node red resources
eg https://flows.nodered.org › node › node-red-contrib-sunevents

Results in a page saying '404 - Thing not found'
### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
The Flow Library is back up.
https://flows.nodered.org/node/node-red-contrib-sunevents

For future reference, this issue tracker is for the node-red application itself. Issues relating to the flow library should be raised here: https://github.com/node-red/flow-library or on the discussion forum - discourse.nodered.org.
