### ISSUE TITLE
Global variables set before API calls get updated alongside msg object.

### ISSUE THREAD

**Issue by JKnutson-Axcess** [node-red/node-red#2394]
### What are the steps to reproduce?
Build a msg object to pass into an API. Set global.request variable to the msg object. Pass into an API. Check global.request. I made a simple sample flow demoing the bug.

```
[{"id":"65495e61.8a491","type":"debug","z":"5051cb93.cf0d34","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":470,"y":900,"wires":[]},{"id":"23b7ad8f.6943b2","type":"function","z":"5051cb93.cf0d34","name":"Populate global.response","func":"global.set(\"response\", msg);\nreturn msg;","outputs":1,"noerr":0,"x":530,"y":860,"wires":[["65495e61.8a491"]]},{"id":"a9bcf7de.da9188","type":"http request","z":"5051cb93.cf0d34","name":"GET call","method":"GET","ret":"obj","paytoqs":false,"url":"","tls":"","persist":false,"proxy":"","authType":"","x":480,"y":820,"wires":[["23b7ad8f.6943b2"]]},{"id":"cf27c48a.8a9018","type":"function","z":"5051cb93.cf0d34","name":"Build request","func":"// initialize\nmsg = {};\n\n// set url \nmsg.url = \"https://api.spotify.com/v1/albums\"; \n\nglobal.set('request', msg);\n\nnode.log(\"Complete\");\nnode.status({fill:\"green\",shape:\"ring\",text:\"Done\"});\nreturn msg;","outputs":1,"noerr":0,"x":490,"y":780,"wires":[["a9bcf7de.da9188"]]},{"id":"309e8eac.da7e72","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":480,"y":740,"wires":[["cf27c48a.8a9018"]]}]
```

### What happens?
Global.request updates alongside msg object, despite that it was set, and not intended to be updated.

### What do you expect to happen?
Global.request to show a representation of the original msg before it was passed into the API.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.2
- [ ] Node.js version: 12.12.0
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Windows 10
- [ ] Browser: Google Chrome

**Comment by knolleary** [comment]
JavaScript passes values by reference, so storing something in Context means you store a reference to the msg, not a copy.

If you want a copy, you'll need to clone it first.

```
var myCopy = RED.util.cloneMessage(msg);
```

But you must also keep in mind that your flow could be triggered more than once at the same time - so storing per-message state in context is not an ideal pattern as a second message will overwrite what the first message was storing.

If you want to preserve `msg.payload` before passing it to the Request node, then you can copy it to a different message property.

**Comment by JKnutson-Axcess** [comment]
@knolleary thank you! I suppose this isn't an issue at all then! I'll close it.
