### ISSUE TITLE
Trigger node fails with "TypeError: Cannot read property 'req' of undefined" when receiving a msg without a .payload property

### ISSUE THREAD

**Issue by jonferreira** [node-red/node-red#2399]
### What are the steps to reproduce?
```
[{"id":"aea0d91b.814468","type":"trigger","z":"eb821e6c.c1615","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"2","extend":true,"units":"min","reset":"","bytopic":"all","name":"","x":510,"y":1980,"wires":[["62035509.0bddbc"]]},{"id":"9edb2cc5.f7759","type":"inject","z":"eb821e6c.c1615","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":1980,"wires":[["a23c6d9d.ee3908"]]},{"id":"a23c6d9d.ee3908","type":"function","z":"eb821e6c.c1615","name":"","func":"var msg = {};\nmsg.query = \"bla\";\n\nreturn msg;","outputs":1,"noerr":0,"x":340,"y":1980,"wires":[["aea0d91b.814468"]]},{"id":"62035509.0bddbc","type":"debug","z":"eb821e6c.c1615","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":670,"y":1980,"wires":[]}]
```

### What happens?
"TypeError: Cannot read property 'req' of undefined"

### What do you expect to happen?
To work :)

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.3
- [ ] Node.js version: 13.2.0
- [ ] npm version: 6.13.1
- [ ] Platform/OS: Debian 9
- [ ] Browser: any

**Comment by okhiroyuki** [comment]
Looking at the source code, it should handle the msg object, but it appears to handle msg.payload.
- the existing msg object
- the original msg object
- the latest msg object

## refs

https://github.com/node-red/node-red/blob/a4c351fd4f4114d11f516b40c5c0d770b7c087e5/packages/node_modules/%40node-red/nodes/core/function/89-trigger.js#L127

https://github.com/node-red/node-red/blob/a4c351fd4f4114d11f516b40c5c0d770b7c087e5/packages/node_modules/%40node-red/nodes/core/function/89-trigger.js#L211

https://github.com/node-red/node-red/blob/a4c351fd4f4114d11f516b40c5c0d770b7c087e5/packages/node_modules/%40node-red/nodes/core/function/89-trigger.js#L248
