### ISSUE TITLE
Context from localFileSystem: Sync flow.get('var', storeName) error

### ISSUE THREAD

**Issue by guilhermesbrito** [node-red/node-red#2406]
Hi everyone,

Using node-red v1.0.3 with nodejs v10.

I've started to use the context from localFileSystem, for persistence.
I managed to use it and store items with global.set(...) and flow.set(...) inside function nodes.

I have a contextStore named 'file', and stored a variable a variable with flow.set('count',123,'file'), with a function node. Everything worked well. 

The bug i've found is when i try to retrieve **synchronously** from the 'file' contextStore. Using function node i have this:

```
//ASYNC - working
/*flow.get('count','file',function(err, myCount) {
    if(err){
        node.error(err, msg);
    }else{
        msg.payload=myCount;
        node.send(msg);
    }    
});*/

//SYNC - not working
var a = flow.get('count','file');
msg.payload=a;
return msg;
```

And i get the following error:
12/12/2019, 15:03:10node: c5ed7f86.e463function : (error)
"Error: Callback must be a function"

I've tracked down the error path into the following file from source: @node-red/runtime/lib/nodes/context/localfilesystem.js -> line 248

where it seems that its always expecting a callback function even if its sync:

```
LocalFileSystem.prototype.get = function(scope, key, callback) {
...
    if(typeof callback !== "function"){
        throw new Error("Callback must be a function");
    }
...
```

Hope you guys can fix it shortly,

Cheers,
G.B.

**Comment by knolleary** [comment]
Thanks for raising this. For future reference, please use the issue template we provide as it ensures all relevant information is provided first time. In this instance, I think your issue covers everything we'd need to investigate.

**Comment by knolleary** [comment]
@guilhermesbrito you don't mention in the issue description how exactly you've configured the file context store.

If you have turned off the `cache` option by setting it to `false`, then the file store only supports asynchronous access: https://nodered.org/docs/api/context/store/localfilesystem

The error message needs improving to make that more obvious in this scenario.

**Comment by guilhermesbrito** [comment]
@knolleary 

> If you have turned off the cache option by setting it to false, then the file store only supports asynchronous access

Ok, somehow I missed to read this line from the docs :/ my fault
That's exactly the problem, because in my specific case I don't want to wait for the cache flush when I use the file context store (since it may not persist the data while the flush don't happen)

I set the Context stores with the following configuration:
 
`settings.contextStorage={
    default: "memoryOnly",
    memoryOnly: { module: 'memory' },
    file: { 
        module: 'localfilesystem',
        config:{
            dir:runtimeDir,
            cache:false
        }
    }
}`

I guess there's a reason for not having synchronous access when cache is set to false(?),  so I believe you may close this issue.

Thanks for all

**Comment by knolleary** [comment]
I've pushed a fix to change the error message to:

> File Store cache disabled - only asynchronous access supported

That should at least help point users in the right direction, rather than the technically-correct, but unhelpful message you had hit.
