### ISSUE TITLE
UI-test: memory leak. runtime-deploy event in deploy()

### ISSUE THREAD

**Issue by onozuka** [node-red/node-red#2407]
### What are the steps to reproduce?
do `grunt test-ui`

then output error
`(node:56611) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 runtime-event listeners added. Use emitter.setMaxListeners() to increase limit
`

### What happens?
Every time "deploy()" called, an event is added,

test/editor/pageobjects/editor/workspace_page.js L74
```
function deploy() {
    browser.call(function () {
        return when.promise(function(resolve, reject) {
            events.on("runtime-event", function(event) {
                if (event.id === 'runtime-deploy') {
                    resolve();
                }
            });
```

Added log for debugging.
```
                if (event.id === 'runtime-deploy') {
                    console.log("called event runtime-deploy");
                    resolve();
                }
```
1st time
called event runtime-deploy

2nd times
called event runtime-deploy
called event runtime-deploy

3ed times
called event runtime-deploy
・・・

### What do you expect to happen?
When adding some processing (for example, closing a deployment message) to runtime-event.
It will be executed multiple times.

### solution
remove event.
```
            events.on("runtime-event", function(event) {
                if (event.id === 'runtime-deploy') {
                    events.removeListener("runtime-event", arguments.callee);
                    resolve();
                }
            });
```

### Please tell us about your environment:

- [x] Node-RED version: 1.0.3
- [x] Node.js version: v10.13.0
- [x] npm version: 6.13.4
- [x] Platform/OS:Mac 10.15.1（19B88）
- [x] Browser: Chrome 78.0.3904.108（Official Build）（64bit）

**Comment by knolleary** [comment]
Fixed by #2408 - thanks!
