### ISSUE TITLE
filter nodes - Filtering select should use the actual node name - not the DOM-rendered name

### ISSUE THREAD

**Issue by neillindberg** [node-red/node-red#2409]
In the "Filter Nodes" filtering search, top of the left nav, I've found a behaviour I'd describe as a bug in that:

Say you have a sub module called, "My Module Foo". The "Foo" will wrap, visually, in the sidebar nav:
```
My Module
Foo
```

But, if you go to search for the specific module in the filtering select and type, "My Module Foo" nothing is found! To find it you have to leave the space out between where it wraps.
Instead, searching by, "My ModuleFoo" finds the item. I think this is bad and therefore filing a bug on the UI.

node-red: ~1.0.3
On Win10, Chrome: 78.0.3904.108 (Official Build) (64-bit) (cohort: Stable)

**Comment by knolleary** [comment]
Thanks for reporting. I suspect the filter code is using the formatted text rather than the raw text - so the newline is tripping it up.

For future issues, please use the template we provide as it makes it easier to capture all the necessarily information.

**Comment by neillindberg** [comment]
@knolleary It is. Furthermore, today I tried to filter using the search term "3.0" and got the following, so I inspected it and see this, which has no 3.0 in it whatsoever:
![image](https://user-images.githubusercontent.com/1066286/71285429-c17cc680-232a-11ea-93ee-9704025b1b27.png)

Anyway, I want to contribute. I want to make the search regex-able, and I don't want it to consider the added br tags - which really makes no sense to me because CSS can control wrapping behaviour and there is no need for these br tags.

How do I contribute? I'd love to! I'll read into it. Can somebody assign this task to me? I really dig NodeRED, especially for IoT stuff made painfully easy. I am a full stack guy and would love to give back. Sound good?

**Comment by okhiroyuki** [comment]
@neillindberg 
Hi.
This seems to be occurring because the text is acquired in the following part.

packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
```js
    function filterChange(val) {
        var re = new RegExp(val.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'),'i');
        $("#red-ui-palette-container .red-ui-palette-node").each(function(i,el) {
            var currentLabel = $(el).find(".red-ui-palette-label").text();  // ← the part
            var type = $(el).attr("data-palette-type");
            if (val === "" || re.test(type) || re.test(currentLabel)) {
                $(this).show();
            } else {
                $(this).hide();
            }
        });
```

## Example
`Demo for subflow in subflow` is recognized as `Demo forsubflow insubflow` .

<img width="1680" alt="スクリーンショット 2019-12-21 9 02 47" src="https://user-images.githubusercontent.com/23309/71299560-45898980-23d1-11ea-8e0d-fcae4d8677f5.png">

**Comment by knolleary** [comment]
@okhiroyuki from the discussion, @neillindberg had asked how to contribute to the project. You've jumped in and provided a fix ignoring his request to fix it himself.

So whilst I appreciate your enthusiasm to help fix issues, please do not do that when someone else has already said they would like to do it.

**Comment by okhiroyuki** [comment]
@knolleary @neillindberg 
I have done something very rude.
Once the Pull Request is closed.

**Comment by neillindberg** [comment]
I'm happy to have reported and had such a turn around from the community. No worries y'all. Thanks.

I looked at the PR and it is closed. Did it get approved and merged? I don't see that action. Did it just get tombstoned?

I've very little insight into the NodeRED GUI, so thank you. I'll likely run into more. Like, you know the instances count on the subflow info panel? Wouldn't it be cool to click-to a usage?

**Comment by dceejay** [comment]
You had offered to do it, and the other guy jumped in. Once it was pointed out - he apologised and withdrew his pull request. We want to encourage more people to contribute and leaping in ahead of them won't encourage anybody... 

Anyway net is the code was not merged - so please feel free to go ahead and create your own fix - or indeed approve his as long as it is tested and works.

**Comment by neillindberg** [comment]
I can see the valid change and this experience demonstrated how one would contribute. I still plan to do that. Right now I need to focus on fixing a broken app (I'm newish to NodeRED, but not NodeJS) using my explorer project to diff flow files...
https://github.com/neillindberg/node-red-explorer
I'll get involved on forum. Thank you all!

**Comment by dceejay** [comment]
So... would you like @okhiroyuki to re-open his pull-request ?

**Comment by neillindberg** [comment]
Yes, please. I reviewed it. Just a selector issue. Perhaps a test to
confirm that bar is effectively ignored?

**Comment by neillindberg** [comment]
@okhiroyuki Would you please re-open your pull request? I don't see any point in redoing your work. Thank you for showing me how to contribute, here! If you don't reopen soon I will just do what you've already done. Thank you!

**Comment by okhiroyuki** [comment]
@neillindberg Thank you for your comment.
I have withdrawn Pull Request, so I am not thinking about doing it again.
Please make a pull request.
