### ISSUE TITLE
node-red-node-tail still on version 0.0.3 instead of 0.1.0

### ISSUE THREAD

**Issue by mikeS7** [node-red/node-red#2415]
### What are the steps to reproduce?
install Node-RED
### What happens?
node-red-node-tail version 0.0.3
### What do you expect to happen?
version 0.1.0
looks like "node-red-node-tail": "^0.0.3" in package.json should be updated to "node-red-node-tail": "^0.1.0" or something simular
### Please tell us about your environment:

- [ x] Node-RED version: 1.0.3
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by dceejay** [comment]
Npm will only update versions that start 0. at the patch level so it is behaving correctly. This is not an issue with Node-RED.

**Comment by knolleary** [comment]
Right, but is there a reason our package.json doesn't reflect the latest available even with a `~` prefix? It ought to.

**Comment by dceejay** [comment]
Ah. No reason apart from forgetting to update it.
