### ISSUE TITLE
variable for name of source NODE.

### ISSUE THREAD

**Issue by elpaso666** [node-red/node-red#2416]
Hello,

is there a way to read within a function name of NODE from which payload.msg is coming from? It would help me with automatization of copy/paste for Zigbee integration.

thank you

**Comment by hardillb** [comment]
Please read the template you were shown when you opened this issue. Questions should be asked on the Forum/Slack/StackOverflow, issues are for actual defects in the code.

To answer the question, No nodes have no access to information about nodes earlier in the flow unless it is include in the `msg` object.  You will need to look at the Zigbee node to see what it outputs but this sort of thing is normally included in the `msg.topic`

**Comment by elpaso666** [comment]
i am sorry, I am closing the issue. thx for tip I was able to find in the meta data of msg.
