### ISSUE TITLE
Routes in editor-api with regex match too broad

### ISSUE THREAD

**Issue by boisei0** [node-red/node-red#2418]
While debugging a highly specific issue for a contrib node (https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/45) that nobody so far had managed to reproduce, I noticed the following situation: URLs with their own prefixes or even located on the node-red-dashboard UI Path can trigger routes in the editor-api. This is caused by routes created based on regex, where there is no start-of-path defined in the expression so that the route will match URLs that don't start on the path set in it.

A practical example, the line that triggered all this in v0.20.7 is the following:
https://github.com/node-red/node-red/blob/aab0b0b4bfa2485ade1f6c12615525d2e295f26c/packages/node_modules/%40node-red/editor-api/lib/editor/index.js#L97
This regex will also match paths that don't start with `/library`, but have it halfway the address, such as `ui/ui_svg_graphics/library/svg-pan-zoom.min.js` like the affected contrib node has. This specific route changed in 1.0.x, however it can still be reproduced there too.

### What are the steps to reproduce?
*Note that for this issue to occur you won't need any of the contrib nodes mentioned so far. If it actually works and the path isn't defined in the core it will give a 404 error (a 200 OK if it is defined in a contrib node), but if it triggers this issue it will come up with a 400 error.*

A)
1. Start a clean Node-RED install, version 0.20.x
2. Point the browser to the Node-RED base URL, followed by "/ui/ui_svg_graphics/library/svg-pan-zoom.min.js"
3. Note that the page comes back with a status 400 and the following error:
`{"code":"unexpected_error","message":"Unknown library type 'svg-pan-zoom.min.js'"}`

B)
1. Start a clean Node-RED install, version 1.0.x
2. Point the browser to the Node-RED base URL, followed by "/ui/ui_svg_graphics/library/foo/svg-pan-zoom.min.js"
3. Note that the page comes back with a status 400 and the following error:
`{"code":"unexpected_error","message":"Unknown library type 'svg-pan-zoom.min.js'"}`

### Additional information
It appears that the issue is caused by URL routes set using regex. See the quick comparison between the 0.20.7 version (https://regex101.com/r/fzbb8i/1), and a quick fix for it (https://regex101.com/r/fzbb8i/2)
This issue hits for a number of URLs, but I'm not familiar enough with the core to find all of them. For 0.20.x it's library get/set entry endpoints (https://github.com/node-red/node-red/blob/aab0b0b4bfa2485ade1f6c12615525d2e295f26c/packages/node_modules/%40node-red/editor-api/lib/editor/index.js#L97-L98) and the locales endpoint (https://github.com/node-red/node-red/blob/aab0b0b4bfa2485ade1f6c12615525d2e295f26c/packages/node_modules/%40node-red/editor-api/lib/editor/index.js#L91).
For 1.0.3 the same endpoints are still hit, be it with slightly different routes. A quick look through other parts of the code suggest the Admin API on the other hand is doing fine (https://github.com/node-red/node-red/blob/1.0.3/packages/node_modules/%40node-red/editor-api/lib/admin/index.js#L51).

### Fixing it
As I don't know which other files/routes might be affected, I'm not sure if I'm the right person to file a PR for this issue. The routes can be found by looking for regex routes that are supposed to start at the first term inside, but don't have a `^` at the start. To fix it, prefix the regex with `^\/`.
For 0.20.7 that would look like the following:
```
            // Locales
            var locales = require("./locales");
            locales.init(runtimeAPI);
            editorApp.get(/^\/locales\/(.+)\/?$/,locales.get,apiUtil.errorHandler);

            // Library
            var library = require("./library");
            library.init(runtimeAPI);
            editorApp.get("/library/flows",needsPermission("library.read"),library.getAll,apiUtil.errorHandler);
            editorApp.get(/^\/library\/([^\/]+)(?:$|\/(.*))/,needsPermission("library.read"),library.getEntry);
            editorApp.post(/^\/library\/([^\/]+)\/(.*)/,needsPermission("library.write"),library.saveEntry);
```

### Please tell us about your environment:

- [x] Node-RED version: 0.20.7 & 1.0.2, but based on code confirmed on the entire 0.20.x and 1.0.x line
- [x] Node.js version: 13.5.0, 10.16.2
- [x] npm version: 6.13.4
- [x] Platform/OS: MacOS, Raspbian
- [x] Browser: Firefox 71.0, Chrome 79.0

**Comment by knolleary** [comment]
Fixed by #2419
