### ISSUE TITLE
node-red-pi --help is a bad option but it's shown in the help

### ISSUE THREAD

**Issue by timaschew** [node-red/node-red#2421]
### What are the steps to reproduce?
`node-red-pi --help`

### What happens?
```
$ node-red-pi --help
Node-RED v1.0.3
Usage: node-red [-v] [-?] [--settings settings.js] [--userDir DIR]
                [--port PORT] [--title TITLE] [--safe] [flows.json]

Options:
  -p, --port     PORT  port to listen on
  -s, --settings FILE  use specified settings file
      --title    TITLE process window title
  -u, --userDir  DIR   use specified user directory
  -v, --verbose        enable verbose output
      --safe           enable safe mode
  -?, --help           show this help

Documentation can be found at http://nodered.org
$ node-red-pi --safe --max-old-space-size=256
node: bad option: --safe
```
### What do you expect to happen?
It just works.

### Please tell us about your environment:

Node-RED version: v1.0.3
Node.js  version: v12.14.0
npm version 6.13.4
Linux 4.19.75-v7+ arm LE (Raspberry 3B+)

**Comment by dceejay** [comment]
if you use the actual command `node-red --safe` as shown in the usage it should work. You are using node-red-pi which is a shortcut command. that passes different options down to the underlying node process.

**Comment by timaschew** [comment]
Yes, it worked, thanks.
