### ISSUE TITLE
Unrecoverable crash with bad server URL

### ISSUE THREAD

**Issue by Slyke** [node-red/node-red#2427]
### What are the steps to reproduce?
1. Add a server to the Home Assistant 'get_entities' object.
2. Add 'localhost:8123' as the server.
3. Inject some flow into it and deploy.

### What happens?
NodeRed completely crashes.

### What do you expect to happen?
NodeRed to report an error to fix.

### Please tell us about your environment:

- [ ] Node-RED version: v1.0.3
- [ ] Node.js version: v10.18.0
- [ ] npm version:
- [ ] Platform/OS: Linux 4.19.75-v7l+ arm LE
- [ ] Browser: Chrome

### Docker logs:
```
17 Jan 03:34:44 - Error: Invalid URL: wslhost:8123/api/websocket
    at initAsClient (/data/node_modules/ws/lib/websocket.js:484:11)
    at new WebSocket (/data/node_modules/ws/lib/websocket.js:72:7)
    at connect (/data/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:352:28)
    at Timeout.setTimeout [as _onTimeout] (/data/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:416:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@1.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-17T03_34_44_716Z-debug.log
```

### Fix:
In order to get NodeRed running again, I had to edit the actual flow.json file in vim, and remove the offending server entry. Docker kept restarting it otherwise.

**Comment by knolleary** [comment]
This needs to be reported against the home assistant module. They need to handle this error in their code. The nature of the error means the Node-RED runtime isn't able to safely recover from it without a full restart.

**Comment by Slyke** [comment]
I will report it there too.

Shouldn't NodeRed be able to block the plugin/component or otherwise allow the user to at least start NodeRed to fix it? The plugin cannot even be removed without manually editing config files once this crash happens.

**Comment by knolleary** [comment]
Uncaught exceptions leave the system in an unknown state and we cannot safely keep running.

This is what node.js says about them: https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly

> Attempting to resume normally after an uncaught exception can be similar to pulling out the power cord when upgrading a computer. Nine out of ten times, nothing happens. But the tenth time, the system becomes corrupted.

**Comment by Slyke** [comment]
Ah ok! I will close this issue then.
