### ISSUE TITLE
Edit Function - Filtering is hiding search results

### ISSUE THREAD

**Issue by niemyjski** [node-red/node-red#2428]
I'm using version 1.0.3 via docker on Safari latest. Let's say I want to search for `entity_id`...
![image](https://user-images.githubusercontent.com/1020579/72616298-3b897680-38fc-11ea-9cf8-59b9a78b73b4.png)

I can no longer see the find occurrences :\
![image](https://user-images.githubusercontent.com/1020579/72616314-4217ee00-38fc-11ea-8c3a-de943c659e52.png)

I think the best solution for this would be to have a dedicated content area for search right above the editor surface. Thoughts?

**Comment by knolleary** [comment]
@niemyjski please use the issue template when raising an issue as it ensures enough information is provided in a consistent way. It also points feature requests and ideas to the forum.

The edit widget we use is https://ace.c9.io/ and the search functionality is a built in part of that component. In other words, it isn't something we can easily customise or modify.

**Comment by knolleary** [comment]
Given this functionality is all part of ACE and not something we can change I'm going to close this issue as there's little else we can do with it.
