### ISSUE TITLE
Add 'ALPNProtocols' option to TLS Node

### ISSUE THREAD

**Issue by afiz** [node-red/node-red#2434]
Hi all,

In some branches network, where the security policy is strict (eg. only allowing http/https), running mqtt using port 8883 is not working. My options is using only port 443, but it's not working. After few dyas, i learned that we need to specified Application Layer Protocol Nego (ALPN) options in [TLS handshaking](https://aws.amazon.com/blogs/iot/mqtt-with-tls-client-authentication-on-port-443-why-it-is-useful-and-how-it-works/). 

I'm not into a programming, but i try editing one of the file below, is working.

file: `@node-red/nodes/core/io/05-tls.js`
Excerpt:

`TLSConfig.prototype.addTLSOptions = function(opts) {`
	`...`
	`...`
        `opts.ALPNProtocols = ["x-amzn-mqtt-ca"];`
        `return opts;`
 `}`

My question is, can we include this options in the node-red GUI on mqtt tls options? At least user can specified what is the ALPN strings that they want.

Thanks you

**Comment by knolleary** [comment]
Hi @afiz - so this is a feature request to add further options to the TLS node?

That can be done - but as with all things, it will sit on the backlog until someone is able to do it.

For future reference, please read and use the issue template you are shown when raising an issue - it helps to ensure enough information is provided, but also points feature requests to the forum rather than this issue list.

**Comment by tarunbatra** [comment]
I would like to take this up, if not already taken. @knolleary

**Comment by knolleary** [comment]
Hi @tarunbatra - sure. Before you dive into the code, would be good to agree what exactly the scope would be.

There are lots of possible options on the TLS node - I had wanted to do a bit of a review to see if there were any other 'obvious' ones to ought to be exposed in some way.

**Comment by tarunbatra** [comment]
Yes, that makes sense.

**Comment by hbcelik** [comment]
Hello all, is there any update regarding this feature ?

**Comment by f00f** [comment]
Same question here. I have the same use case, but this issue seems to be stagnating.

@knolleary are there any news?

@tarunbatra are still interested in taking this?

**Comment by afiz** [comment]
Sorry for not replying earlier. I have tested and it works, just specify the mqtt server port to 443 (from the usual 8883) and ALPN protocols to "x-amzn-mqtt-ca" (for AWS IOT service)

Thanks to you all
