### ISSUE TITLE
Code-snippets missing from dropdown in Function Editor

### ISSUE THREAD

**Issue by aolsendk** [node-red/node-red#2438]
### What are the steps to reproduce?
Open the function node editor.
Start typing "for" as in a for-loop.
Press ctrl+space in order to activate code-snippets dropdown.

### What happens?
Dropdown is only populated by keywords, variables ect. No code snippet/templates are shown

### What do you expect to happen?
Code-snippets should be present in dropdown menu.

As per https://discourse.nodered.org/t/js-editor-code-completion-templates/20863/6 it is due to missing snippet support in the current custom version of the JavaScript Mode.

### Please tell us about your environment:

- [1.0.3 ] Node-RED version:
- [ v8.17.0] Node.js version:

**Comment by dceejay** [comment]
ah yes - not intentionally...
As part of fixing a few unnecessary linting warnings when used with Node-RED Nick had to create a nrjavascript set of helpers... I suspect they won't by default just pick up the javascript snippets. So yes needs to be re-instated. Thanks for spotting.

(EG it works inside the template node if you select javascript highlighting (but it's the tab key you need))

**Comment by dceejay** [comment]
link back to discussion - https://discourse.nodered.org/t/js-editor-code-completion-templates/20863/4

**Comment by knolleary** [comment]
The same link that is in the original issue 😛

**Comment by dceejay** [comment]
still pre-coffee

**Comment by knolleary** [comment]
I've added back the javascript snippets to the custom `nrjavascript` mode we use.

I've removed some of the ones that aren't relevant to the Function node, as well as adding in some NR specific ones:

```
nodes -> node.send(msg)
clone -> RED.util.cloneMessage(msg)
```
and others.

Will be in 1.0.4
