### ISSUE TITLE
Metric logging should record a end of message processing

### ISSUE THREAD

**Issue by k-toumura** [node-red/node-red#2446]
### What are the steps to reproduce?
Write a following flow:
![Picture1](https://user-images.githubusercontent.com/30313213/73521846-f6d30480-43fe-11ea-9644-c245169b1121.png).

Then, enable metric logging in `settings.js`, and start tracing for all messages.

### What happens?

From metric log below, we can confirm that node “D” receives message “X”, run join process, and then emit message to node “E”.
But, because of completion of message processing of messages "Y" and "Z" don't involve emission of messages, we can't confirm that messages “Y” and “Z” been processed (or still queued in node “D”). 

```
14:21:51 - [metric] {"level":99,"nodeid":"B","event":"node.inject.receive","msgid":"Y","timestamp":1579670511861}
14:21:51 - [metric] {"level":99,"nodeid":"B","event":"node.inject.send","msgid":"Y","timestamp":1579670511862}
14:21:51 - [metric] {"level":99,"nodeid":"D","event":"node.join.receive","msgid":"Y","timestamp":1579670511863}
14:21:53 - [metric] {"level":99,"nodeid":"C","event":"node.inject.receive","msgid":"Z","timestamp":1579670513507}
14:21:53 - [metric] {"level":99,"nodeid":"C","event":"node.inject.send","msgid":"Z","timestamp":1579670513508}
14:21:53 - [metric] {"level":99,"nodeid":"D","event":"node.join.receive","msgid":"Z","timestamp":1579670513508}
14:21:56 - [metric] {"level":99,"nodeid":"A","event":"node.inject.receive","msgid":"X","timestamp":1579670516424}
14:21:56 - [metric] {"level":99,"nodeid":"A","event":"node.inject.send","msgid":"X","timestamp":1579670516424}
14:21:56 - [metric] {"level":99,"nodeid":"D","event":"node.join.receive","msgid":"X","timestamp":1579670516424}
14:21:56 - [metric] {"level":99,"nodeid":"D","event":"node.join.send","msgid":"X","timestamp":1579670516425}
14:21:56 - [metric] {"level":99,"nodeid":"E","event":"node.debug.receive","msgid":"X","timestamp":1579670516425}
```

### What do you expect to happen?

Runtime should write metric logs when message processing are completed
(i.e. when done() is called).
For example, following log may be emitted.
```
14:21:56 - [metric] {"level":99,"nodeid":"D","event":"node.join.done","msgid":"Y","timestamp":1579670516425}
14:21:56 - [metric] {"level":99,"nodeid":"D","event":"node.join.done","msgid":"Z","timestamp":1579670516425}
```

### Please tell us about your environment:

- [x] Node-RED version: 1.0.3
- [x] Node.js version: v12.14.1
- [x] npm version: 6.13.6
- [x] Platform/OS: macOS Catalina v10.15.3
- [ ] Browser: -

**Comment by knolleary** [comment]
I believe this has been resolved by https://github.com/node-red/node-red/pull/2685
