### ISSUE TITLE
HTTP Post reply 400

### ISSUE THREAD

**Issue by averlon** [node-red/node-red#2448]
### What are the steps to reproduce?
Setting a HTTP Post request with node "http request" preparing parameters as input with a function node:

`msg.topic = 'Gruenbeck post';
msg.method = 'POST';
msg.url = 'http://f42240gb.example.com/mux_http';
msg.payload = 'id=625&show=D_A_1_2~';
msg.headers = {};
msg.headers={
    'Content-Length': '22',
    'Content-Type': 'application/x-www-form-urlencoded'
};

return msg;`

### What happens?
reply is:

´<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"xml:lang="en" lang="en">
<head>
<title>Error</title>
</head>
<body>
<b>400 Bad Request: No Host Header</b>
<br/>
/mux_http
<br/>
</body>
</html>´

### What do you expect to happen?
some reply from the web-service.
The reply looks like the hostname is not submitted.

### Please tell us about your environment:

- [ ] Node-RED version:1.03
- [ ] Node.js version: 8.11.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: CCU3
- [ ] Browser: Firefox

**Comment by dceejay** [comment]
As per the Issue form we prefer how-to type questions via the Discourse forum or Slack channel so the widest possible audience can offer help - there two similar questions being handled on discourse as we speak.
 How do you have the http request node configured ? (maybe attach the relevant part of your flow that shows how this call being made) .
But as the error is fairly explicit I would try adding to the msg.headers object something like `Host:{your machines hostname}`

**Comment by averlon** [comment]
Hi,
thank you for your hint. This now works.

I have searched the net very intensively but nowhere found such a hint to add the host to the message header. But I am not a HTTP Specialist.
Probably worth to include such a type example in the how-to section of your documentation.

I will update my case on Discourse!
Thanks for help

**Comment by knolleary** [comment]
The request node should be adding the Host header automatically as it's a fundamental part of a request. 

So whilst you've "fixed" it, let's keep this issue open so we can investigate why the header wasn't there.

**Comment by dceejay** [comment]
If I change the sample given to just use example.com (so that it resolves) - then wireshark captures

```
POST /mux_http HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 22
host: example.com
Connection: close

id=625&show=D_A_1_2~
```

so the host is there just fine... I think we would need to see the real server being used if we want to see the real answer why it doesn't work for @averlon

**Comment by averlon** [comment]
Hi dceejay,
you can not test it with the real server since this is in my INTRANET only.

But:
Using curl - it works!
Using the solution you recommended - it works!
Using some http header requester e.g. in firefox - it works!

Only the config I showed in the original post did not work.
That's all I can say.
I could try to install tshark on the ccu3 - but I am not sure how to do this and I don't want to crash the mashine - as I am a little bit familiar with linux (Ubuntu) but not with the OS on my CCU3.

**Comment by dceejay** [comment]
ok - I think the only way to get to the bottom of this is to actually sniff the request packet on the wire - at one end or the other. You may be able to run `sudo tcpdump -A port 80` and see the request.
As I said when I do that I can see the headers being set to
```
Content-Type: application/x-www-form-urlencoded
Content-Length: 22
host: example.com
Connection: close
```
(I only set the Type and Length as per your original issue). the `host` and `Connection` ones are being added by the request library we use. So... it would be interesting to see what yours looks like in both cases (working and non-working).  

It MAY be that the `host` being lower case is not being handled by your server correctly... but...

**Comment by averlon** [comment]
Hi dceejay,
please give me some more help to identify what I shall do where.

The target host is a closed (technical) device - no way to sniffer there.

So I would need to sniffer on the ccu3 for some outgoing traffic.

But I guess, the command you offered, was more to be used on the target host - correct?
If I am right: Any suggestions how to sniffer the traffic on the ccu3 without to get tons of data?

**Comment by dceejay** [comment]
Hi - no - that command should work at either end so should work on ccu3 as long as it is linux based and you can install tcpdump. Yes you will get lots of traffic if there is lots going on on port 80... - but tcpdump has loads of option to filter - eg tcpdump src 1.1.1.1  to only see data from that source ip etc... 
see https://danielmiessler.com/study/tcpdump/

**Comment by averlon** [comment]
Hi dceejay,
I have tried to install tcpdump on the ccu3 but failed, since the partition is read only.
I would probably need to set an installation directory for tcpdum under /opt - but I don't know the npm-command for this.
So there is not a real way to get this done.

I know, my router has a sniffer function. I will try to check if I can use that.

**Comment by averlon** [comment]
Hi dceejay,
I have done some caputuring on my router.

Attached you find two files.
ccu3_trace_works.txt - where the additional "host"-parameter is set - so it works.
ccu3_trace_error.txt - where I eliminated the additional host-parameter and it so does not work.
Note: I have change the domain again!
[ccu3_trace_error.txt](https://github.com/node-red/node-red/files/4144151/ccu3_trace_error.txt)
[ccu3_trace_works.txt](https://github.com/node-red/node-red/files/4144152/ccu3_trace_works.txt)

Regards
Kallewirsch

**Comment by hardillb** [comment]
The HTTP [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) says that headers are not case sensitive

**Comment by dceejay** [comment]
yes - so it is the server at fault not us :-) Please raise an issue against the provider of that server !

**Comment by averlon** [comment]
mmh - you are the experts.

why does it work with curl?
why does it work with the additional host parameter?
in all cases I have only used small characters to seht the URL!
Where do you geht the information from the device refuses small characters?

To be honest - I don't care as it currently works.
But I have seen some exapmles to access the Grünbeck SC18 device via CUxD, yes, via a script which uses curl, but anyhow - these work - as I was told.

Sorry, but you havn't convinced me - but you don't need to - anyway!

**Comment by hardillb** [comment]
Your trace output shows the difference between working/not working is the case of the `host`/`Host` header, I've linked to the spec that explicitly says that the server should accept both versions.

You haven't supplied any trace from curl (but I'll guess it's using `Host`).

There is nothing else to say, your server is not conforming to the spec, if you want this fixed you need to open an issue with them.

**Comment by dceejay** [comment]
When you set it manually to `Host` in Node-RED it works - you could also try setting it manually to `host`  and see if that still works.
If you like you can grab a trace from whatever box you are running curl from (using tcpdump or wireshark) and compare.

**Comment by averlon** [comment]
Hi,
sorry, totally wrong track. "host" and "Host" both work.
Please go back to the start of my post. The story is totally different.
If I have some time today I will come back an explain in more detail.
I am still on the way it is a bug in nod http-request.

**Comment by hardillb** [comment]
How can you say `host` works when ccu3_trace_error.txt shows it doesn't?

**Comment by dceejay** [comment]
several references to this in the underlying request library - e.g. https://github.com/request/request/issues/346

And the answer is still the same - the server should accept both - it is simply not following the spec - so you need to contact the owner of that device and ask them to fix it. The workaround is as you have - to set the header to be Host manually.
Nothing more we can do here.

**Comment by averlon** [comment]
> 
> 
> How can you say `host` works when ccu3_trace_error.txt shows it doesn't?

Because ccu3_trace_error.txt is without host parameter.

**Comment by averlon** [comment]
> 
> 
> several references to this in the underlying request library - e.g. [request/request#346](https://github.com/request/request/issues/346)
> 
> And the answer is still the same - the server should accept both - it is simply not following the spec - so you need to contact the owner of that device and ask them to fix it. The workaround is as you have - to set the header to be Host manually.
> Nothing more we can do here.

It does accept both!

But http node does not work if host parameter - regardless how it is written - is not set via function node.

**Comment by dceejay** [comment]
The error is coming from the server end - the server is rejecting it... we only report back what your server tells us.
The example traces you gave us - the txt files - both show the host parameter there. It is not missing.
Can you provide a trace where you set it to `host` manually and it then does work ?

**Comment by hardillb** [comment]
From ccu3_trace_error.txt:

```
POST /mux_http HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 22
host: f42240gb.example.com
Connection: close
```

the penultimate line clearly contains the `host` entry

`host:  f42240gb.example.com`

It's there and shows the error.

**Comment by averlon** [comment]
Hi all,
sorry, I have got confused on all my tests I have done.

You are right !!!!!!!

I have tested again and "H" and "h" is treated different - obviously by the server.

Sorry for the confusion I produced - please close issue!

**Comment by richardson134** [comment]
This is very innovative blog.. I have been using this tool many years ago... Also download [http debugger](https://licensedaily.com/http-debugger-crack/)
