### ISSUE TITLE
Errors while installing the node

### ISSUE THREAD

**Issue by iliyas18** [node-red/node-red#2450]
npm WARN ts-jest@24.3.0 requires a peer of jest@>=24 <25 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\zigbee-herdsman\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ node-red-contrib-new-websocket-lower-case@1.0.0
added 1 package and audited 2252121 packages in 14.721s
found 8 vulnerabilities (2 low, 1 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Hello I'm getting the above error while installing the this node in node-red
Please help me out with this....

**Comment by knolleary** [comment]
Hi, the issue template you've ignore kindly asks that any general help question should be asked on the forum. Especially when it is regarding a node we aren't responsible for.

If you have questions about a particular node, then you should raise it against that node.

In this instance, yes there are some warnings with that install, but they are not errors and the install has succeeded.
