### ISSUE TITLE
GPIOD issues - loses connection with GPIO

### ISSUE THREAD

**Issue by PiRune** [node-red/node-red#2456]
### What are the steps to reproduce?
Run node-red in the official docker container.

Verify that the gpiod nodes have connection to the gpiod (daemon). Check that gpio input node actually works (e.g. use a simple switch to connect pin 5 to ground and see "OK" changing to 1 or 0). 
![Skærmbillede 2020-02-09 kl  23 14 03](https://user-images.githubusercontent.com/20454469/74111272-c5db9800-4b93-11ea-9d33-331c2dd6bcfa.png)

Wait an hour or two. 

Check that gpio input node still works (in my setup it stoppes working). The gpiod node still states "OK" which indicates the gpio daemon is running. running ps aux confirms this. HOWEVER -connecting a pin to ground no longer makes the node change state. 

restart the docker container - now it works again for a limited time.

### Please tell us about your environment:
- [ ] Node-RED version: 1.0.3
- [ ] Node.js version: latest?
- [ ] npm version: latest?
- [ ] Platform/OS: latest docker image. host os raspian
- [ ] Browser: google chrome (not a browser issue).

+ pigiod is latest version:
![Skærmbillede 2020-02-09 kl  23 38 54](https://user-images.githubusercontent.com/20454469/74111529-6e3e2c00-4b95-11ea-803e-bb3eb0e0e888.png)

**Comment by dceejay** [comment]
you've raised this issue in the main Node-RED project... the node itself is part of the node-red-nodes project and the docker container is part of the node-red-docker container. 
Does this behaviour exist if you run it outside of docker ?

**Comment by PiRune** [comment]
Apologies if I posted it the wrong place. I don’t know if the issue exists outside docker. Last time I used Node-RED outside docker, there was no PiGPIOdaemon and gpiod nodes - only default GPIO nodes (this was before version 1.0.)

Please share a link to the proper page, if this issue should be raised elsewhere.

**Comment by dceejay** [comment]
Well the proper page depends if it fails outside of docker or not... 
If it does still fail then https://github.com/node-red/node-red-nodes
else https://github.com/node-red/node-red-docker
(Also which raspberry Pi hardware and version of raspbian are you using ?)

**Comment by PiRune** [comment]
Thanks. I don’t know if it fails outside docker, so I guess the best place is github.com/node-red/node-red-docker.

Running latest Raspbian buster on a Rpi 3B+

**Comment by knolleary** [comment]
Closing as this isn't a core Node-RED issue
