### ISSUE TITLE
Trying to connect to an MQTT broker via IPv6 address fails due to invalid broker URL

### ISSUE THREAD

**Issue by Kilobyte22** [node-red/node-red#2462]
### What are the steps to reproduce?
Create new MQTT Input. Create new MQTT broker. Enter `::1` as address. Make sure an mqtt broker is running on the local machine

### What happens?
Connect fails. Log reveals it tried to connect to `node-red@mqtt://::1:1883`.

### What do you expect to happen?
node-red to attempt the connection to `node-red@mqtt://[::1]:1883` (with square brackets).

### Workaround
Put the IPv6 address in square brackets when entering it into the broker address. Depending on how the fix is implemented this may break after the fix has been implemented.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.3
- [ ] Node.js version: v13.8.0
- [ ] npm version: 6.13.6
- [ ] Platform/OS: Arch Linux
- [ ] Browser: Mozilla Firefox 72.0

**Comment by knolleary** [comment]
The fix I've pushed will wrap an IPv6 address in square brackets if it isn't already wrapped - so will be compatible with the existing workaround you have identified.
