### ISSUE TITLE
Syntax highlighting in JSONata editor broke when using double quote in regex

### ISSUE THREAD

**Issue by tmdoit** [node-red/node-red#2465]
### What are the steps to reproduce?
Use ie. $replace function like: `$replace("bee",/"/,"bear")`
### What happens?
Text after `$replace("bee",/"` is badly highlighted.
![Screenshot 2020-02-17 at 09 20 23](https://user-images.githubusercontent.com/26081817/74685206-1bd0c100-51ce-11ea-864b-3708eea1c8b4.png)

With complex expression it's hard to use it, below example - insert stmt for MySQL:
`"INSERT INTO MobileApp.Vouchers (VoucherCode, CustomerCode, VoucherCreationDate, AwardCredits,IsActive,CsCart,Altum,IsUsed,SalesOrderNumber,Document) VALUES "
& $join($map(data,function($v) {
    "('" & $v.VoucherCode & "','" & $v.CustomerCode & "', DATE_FORMAT(" & $replace($string($v.CreationDate),/\.[^"]*/,"") & ",'%Y-%m-%d  %H:%i:%s') ," & $v.AwardCredits & "," & $v.IsActive & "," & $v.CsCart & "," & $v.Altum & "," & $v.IsUsed & ",'" & $v.SalesOrderNumber & "','" & $v.Document & "') "
}),",")`

![Screenshot 2020-02-17 at 21 43 10](https://user-images.githubusercontent.com/26081817/74685453-e8dafd00-51ce-11ea-89a7-20f267ff3ef5.png)

### What do you expect to happen?
Correct syntax highlight.
### Please tell us about your environment:

- [x] Node-RED version: 1.0.2
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Thanks for highlighting this. Have pushed a fix to improve the syntax highlighting - will be in 1.0.4.

**Comment by knolleary** [comment]
I've also used your SQL example as a test bed for improving the formatter. Fixed two issues:
1. it had the same issue with quotes appearing in regex
2. it didn't consider wrapping long lines on the `&` character.

Formatting your example now results in:

<img width="1048" alt="Node-RED" src="https://user-images.githubusercontent.com/51083/75169400-639c9e80-5720-11ea-8eef-cb6f7276f6b7.png">

**Comment by tmdoit** [comment]
Appreciate, thanks for your support!

**Comment by gitolicious** [comment]
Not sure if it is a side effect from this fix but when using slashes for division or within a string (instead of regex), the syntax highlighting is going crazy.
Tried with v1.1.3 Docker image, Chromium 84.
![image](https://user-images.githubusercontent.com/26963495/89579569-46720d00-d834-11ea-931a-ec63bd971473.png)
