### ISSUE TITLE
MQTT Node doesn't allow for port to be edited. 

### ISSUE THREAD

**Issue by Mrc0113** [node-red/node-red#2467]
Hi, 

The MQTT Input node does not seem to allow you to edit the server port but instead has it locked to 1883.

Note: We were participating in a hackathon over the weekend where several different groups were trying to use MQTT input nodes and all ran into the same issue with their own installations.  

### What are the steps to reproduce?
Add a MQTT Input node to your flow graph. 
Double click on node to edit. 
Click pencil icon to edit server

### What happens?
The `Port` field is not editable. 

### What do you expect to happen?
The `Port` field should be editable for servers that don't use the default port of 1883. 

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.3: Maintenance Release
- [ ] Node.js version: v13.6.0
- [ ] npm version: 6.13.4
- [ ] Platform/OS: macOS Catalina
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Can you try with a supported version of Node.js ? I.E. 12.x LTS version ?

**Comment by knolleary** [comment]
A different version of node will have no bearing on the behaviour of an edit dialog that runs in the browser. So suggesting the upheaval of changing node version isn't the idea first step.

Can you check the browser console for any error messages? The port input should certainly be editable and I can't think of any logic in the node that would change that.

Am away from my laptop for a few days, so will have a look later.

**Comment by Mrc0113** [comment]
Same issue with Node.js version: v12.16.0

I also tried to debug in console but it's not giving me anything to really go on. 
I see the following warnings before I try to edit but that's it. Nothing new after editing. 

![image](https://user-images.githubusercontent.com/1815312/74755476-41e37900-5241-11ea-9357-e43dbeeb7c8c.png)

Note the issue seems to occur after I import another flow with mqtt server info. Then when I try to edit a MQTT input node in that flow or in a new flow I can't edit the port. If you want to quickly test it out I'm importing [this flow](https://github.com/SolaceLabs/makeuoft-hackathon/blob/master/raspberrypi2solace/subscribe/SCADA_subscribe.json )

**Comment by dceejay** [comment]
Why are you setting the server address to tcp:// ? 
That is what is disabling the port field... 
OK - we need to investigate why it blocks it - but normally you don't need a prefix (for mqtt) or ws: (for websockets)

**Comment by Mrc0113** [comment]
Ah okay. I just set it out of habit. Some of the client APIs and examples I find include "tcp://" or "ssl://" or "ws://" or "wss://" depending on the transport. 

We also found that if you use the full url in the servername field that it seemed to work even though it locked the port field, e.g: "tcp://hostname:12345"

**Comment by knolleary** [comment]
Ah yes, that's the expected behaviour. If you specify a fully qualified URL then you don't set a port separately - otherwise we have to deal with deciding if the user wants us to use the port from the URL or from the input.

**Comment by Mrc0113** [comment]
Thanks for the confirmation. It makes sense now that we've had this conversation but it might be a good idea to add that to the "Node Help" section as well.
