### ISSUE TITLE
JSONATA editor

### ISSUE THREAD

**Issue by ahartman** [node-red/node-red#2472]
The JSONATA expressions editor in the Switch node adds a carriage return each time one clicks the 'format expression' button.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.3
- [ ] Node.js version: 10.18.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: RaspberryPI 4.19.75-v7+
- [ ] Browser: Safar 13.0.5

**Comment by knolleary** [comment]
Thanks for reporting. Have pushed a fix for 1.0.4
