### ISSUE TITLE
login url generation error with adminAuth type strategy

### ISSUE THREAD

**Issue by endemecio02** [node-red/node-red#2473]
### What are the steps to reproduce?
Set settings.httpAdminRoot to "/red"
Set settings.adminAuth.type to "strategy"
Set settings.adminAuth.strategy to an appropriate strategy configuration
Start the node server by using your own http.createServer and not the default which comes in node-red.
Attempt to log into admin console

### What happens?
The response from {httpAdminRoot}/auth/login contains a malformed url.
Line 103 of @node-red/editor-api/lib/auth/index.js sets var urlPrefix to settings.httpAdminRoot.
Line 106 sets prop url to by concatenating urlPrefix and "auth/strategy".
This incorrectly generates url value "/redauth/strategy".

### What do you expect to happen?
This should generate a url value of "/red/auth/strategy".
Fix:
Line 103 should test if settings.httpAdminRoot ends with a forward slash and append a forward slash to urlPrefix if it does not
or
Line 106 should test if urlPrefix ends with a forward slash and append a forward slash before appending "auth/strategy" to generate the url

### Please tell us about your environment:

- [x] Node-RED version: v1.0.3
- [x] Node.js version: v12.16.1
- [x] npm version: v6.13.4
- [x] Platform/OS: MacOS Catalina v10.15.3
- [x] Browser:  Firefox v73.0.1

**Comment by knolleary** [comment]
Thanks for raising. If you have identified a fix, please consider raising a pull request we can review.

For now, you can ensure `httpAdminRoot` ends in a slash in your own configuration
