### ISSUE TITLE
http request GET with body behavior 

### ISSUE THREAD

**Issue by fabrizior** [node-red/node-red#2476]
### What are the steps to reproduce?
Any http request that needs a body. 
The request work with curl but not with http request.
Refer to [this ](https://stackoverflow.com/questions/60356824/node-red-set-get-http-request-parameters) StackOverflow discussion:

### What happens?
One error returned. This: 
_Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)_ 
for Content-Type: application/json body

### What do you expect to happen?
GET method behavior modified.
### Please tell us about your environment:

- [ ] Node-RED version: v1.0.3
- [ ] Node.js version: v12.13.1
- [x] npm version: 6.12.1
- [ ] Platform/OS: Windows 10
- [ ] Browser: any

**Comment by hardillb** [comment]
It looks like the latest version of the HTTP spec has made behaviour around having a GET body less defined (see comments on [this](https://stackoverflow.com/questions/978061/http-get-with-request-body) other question), but there are a number of services out in the wild expecting a body to be present.

I think we should add this as a gated option to prevent the unexpected sending of a body with existing GET requests.

I have a rough and ready fix (that needs a gating option adding), I'll add that and submit a pull request against dev for review.

**Comment by knolleary** [comment]
Thanks @hardillb  - agreed, this needs to be an option. We already have an option to append msg.payload as query parameters. Maybe that should be extended to be a select box to chose what to do with msg.payload:
 - do nothing
 - append as query parameters
 - send as body

**Comment by Steve-Mcl** [comment]
Fixed in https://github.com/node-red/node-red/pull/2478 right?
