### ISSUE TITLE
[Info] OpenJS Conference & Collab Summit FYIs for Project Communities

### ISSUE THREAD

**Issue by jorydotcom** [node-red/node-red#2477]
Hi node-red Community 🤗

I've been asked to help make sure that all the OpenJS Foundation project communities are aware that the deadline for our [OpenJS Conference Call for Proposals](https://events.linuxfoundation.org/openjs-world/program/cfp/) has been extended through Feb. 28. Previously, this event was called 'Node + JS Interactive' and it leaned heavily toward Node.js. We're hoping to have a wider range of sessions about all the OpenJS Foundation projects, so we'd love to see presentations about node-red!

I also wanted to make sure you're aware of the Collaborator's Summit, an event focused on project maintainers, collaborators & contributors. The goal for the collab summit is to provide opportunities for face-to-face working sessions within a single project or across multiple projects. So if you wanted to get your core team together you could do that, or if you want to have a session for new contributors to your project, or if you wanted to work across multiple OpenJS Foundation projects on issues like accessibility, privacy, security, modules, etc. you could do that too. **If you're interested in securing session space at the collab summit, please ping me here, reach out on slack or twitter, or open an issue on the [/summit](https://github.com/openjs-foundation/summit) repo.** 

The OpenJS World conference is June 23-24 and Collaborator's Summit is June 25-26 in Austin, TX. These are ticketed events, but **members of OpenJS Foundation project communities are eligible for [Travel Fund](https://github.com/openjs-foundation/cross-project-council/blob/master/project-resources/MEMBER_TRAVEL_FUND.md) assistance.** If you have questions or would like to find out more, please chime in on our /summit repo. 

as always, let me know how I can help <3
Jory Burson
OpenJS Foundation Community Manager

**Comment by knolleary** [comment]
Hi @jorydotcom 

I have reached out to some of the community and I know they either have already or plan to submit talks. I submitted a bunch a couple weeks ago as well.

I'll cross post this to our discussion forum (discourse.nodered.org) as well.

**Comment by knolleary** [comment]
Closing as there's little prospect of the summit going ahead in-person given current events. Even if they decide to go ahead with an in-person event, I couldn't, in clear conscience, advocate for people to travel in this time frame.

As it stands, all of the Node-RED talks I know were submitted to the CFP have been rejected. So unless someone submitted something I don't know about that has been accepted, then once again there isn't going to be any Node-RED content at OpenJS World.
