### ISSUE TITLE
Change Node error using "%" as parent path operator

### ISSUE THREAD

**Issue by jonsieck** [node-red/node-red#2482]
I am using a change node to transform JSON and aggregate some objects
I do some grouping and aggregate these, afterwards i then wan't to 
return the OrgObjects with the Group/value on each object.

The issue i am trying to raise is the use of Parent path-operator.

It seems that the % isn't valid within the jsonata-expr in changenode.

Made a test dataset and did a 'groupby' and afterwards try to use the %.test in my result Jsonata.

The Jsonata "%" as i understand is introduced of jsonata@1.8.0+ and Node-red have this version in core as well ?!

Did test the the  payload and Jsonata in the Exersizer   
[]()https://try.jsonata.org/O5lyumTX

`[{"id":"abec1e90.8cb73","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"8995f6fa.8f6808","type":"inject","z":"abec1e90.8cb73","name":"","topic":"","payload":"[{\"key1\":1,\"key2\":2,\"group1\":\"value1\",\"group2\":\"value2\",\"bolean\":\"true\"},{\"key1\":1,\"key2\":2,\"group1\":\"value1\",\"group2\":\"value2\",\"bolean\":false},{\"key1\":3,\"key2\":4,\"group1\":\"value1\",\"group2\":\"value3\",\"bolean\":true},{\"key1\":1,\"key2\":2,\"group1\":\"value1\",\"group2\":\"value3\",\"bolean\":true}]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":570,"y":140,"wires":[["6be3ef9a.bf12d"]]},{"id":"6be3ef9a.bf12d","type":"change","z":"abec1e90.8cb73","name":"Test_With_GroupBy","rules":[{"t":"set","p":"payload","pt":"msg","to":"\tpayload{\t   group2 : * \t\t}  ~> $each(\t   function($v, $k) {\t       {\t           \"group\": $k,\t           \"result\" : $v,\t           \"test\" : $sum($v.key2)\t       \t       \t       }\t\t   \t   \t   }\t\t\t)\t\t\t\t\t\t\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":560,"y":240,"wires":[["1d4fa1ef.bfd52e","a459857d.293a18"]]},{"id":"a459857d.293a18","type":"debug","z":"abec1e90.8cb73","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":750,"y":380,"wires":[]},{"id":"1d4fa1ef.bfd52e","type":"change","z":"abec1e90.8cb73","name":"Parent_test","rules":[{"t":"set","p":"ParentTest","pt":"msg","to":"payload.result.{\t  \t       \"key1\":key1,\t       \"key2\":key2,\t       \"group1\":group1,\t       \"group2\":group2,\t       \"bolean\":bolean,\t       \"ParentTest\" : %.test\t   }\t\t\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":550,"y":320,"wires":[["a459857d.293a18"]]}]`

- [ v1.0.3 ] Node-RED version: 
- [ v12.10.0 ] Node.js version:
- [6.14.0 ] npm version: 
- [ win 10] Platform/OS: 
- [chrome ] Browser:

**Comment by knolleary** [comment]
Node-RED 1.0.3 was published before JSONata 1.8.0 was released - so no, the `%` operator is not available.

Node-RED 1.0.4 will be published later this week and includes the latest JSONata 1.8.1.
