### ISSUE TITLE
Enhance request function

### ISSUE THREAD

**Issue by cmdares** [node-red/node-red#2483]
At present, the function of "http request node" is less.
You can refer to the operation interface ( UI )  Reference the "postman"
https://www.postman.com/
It mainly includes the following contents
query params
headers
body
authorization

The request function needs to include these operations and configurations.
thanks!

**Comment by hardillb** [comment]
We've closed this request once already before, for the following reasons

 1. You've not followed the supplied template
 2. It really isn't clear what you are asking

Feature requests need to be discussed on the forum or slack before being raised here, issues are for defects in the code.
