### ISSUE TITLE
Incorrect state for form input fields in 'Port labels' in node Appearance settings when dynamically changing node input/output port availability

### ISSUE THREAD

**Issue by tmdoit** [node-red/node-red#2484]
### What are the steps to reproduce?
Disable node's input (set 'Inputs' to 0) which is by default enabled ('Inputs" is set to 1) and deploy changes.
### What happens?
Edit node, go to 'Appearance' tab and see that form input for disabled port is enabled
### What do you expect to happen?
Because I disabled port for node it shouldn't be configurable - form input for disabled port should be disabled.
It works as expected with opposite direction - when node has by default set 'Inputs' to 0 and then you changing dynamically to 1.

This is how it works (input/output ports are enabled by default):
![node](https://user-images.githubusercontent.com/26081817/75441422-f0806b80-595d-11ea-8183-d6bcaac17939.gif)
This is how it should work (input/output ports are disabled by default):
![node2](https://user-images.githubusercontent.com/26081817/75441442-fa09d380-595d-11ea-8ce7-6c2aa150bb03.gif)

### Please tell us about your environment:

- [x] Node-RED version: 1.0.3
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
1. have you added `inputs` and `outputs` to your node's defaults property?
2. how are those checkboxes configured to modify the properties? Is it done in `oneditsave` or have you added a change listener to them and you change the value whenever they are clicked?

**Comment by dceejay** [comment]
is this still valid - ( I think it was closed via a side conversation ?)

**Comment by tmdoit** [comment]
No, I couldn't update it yesterday because of some Github error.
The cause was bad use of "input" and "output" properties, in properly programmed node this will not happen.
Below is the example of node how to make it work :

`
<script type="text/javascript">
  RED.nodes.registerType("digitaloak-postgresql", {
    category: "storage",
    color: '#5991c9',
    defaults: {
      name: { value: "" },
      server: { type: "digitaloak-postgresql-server", required: true },
      inputs: { value: 1 },
      outputs: { value: 1 }
    },
    outputs: 1,
    inputs: 1,
    icon: "icons/postgres.png",
    align: "left",
    label: function() {
      return this.name || "postgresql";
    },
    paletteLabel: "postgresql",
    labelStyle: "label-color"
  });
</script>

<script type="text/x-red" data-template-name="digitaloak-postgresql">
  <div class="form-row">
    <label for="node-input-name"><i class="icon-tag"></i> <span>Name</span></label>
    <input type="text" id="node-input-name" placeholder="name">
  </div>
  <div class="form-row">
    <label for="node-input-server"><i class="fa fa-server"></i> <span>Server</span></label>
    <input type="text" id="node-input-server">
  </div>
  <div class="form-row">
    <h4>Ports</h4>
  </div>
  <div class="form-row">
    <label for="node-input-inputs">Input:</label>
    <select id="node-input-inputs">
      <option value="1">Enabled</option>
      <option value="0">Disabled</option>
    </select>
  </div>
  <div class="form-row">
    <label for="node-input-outputs">Output:</label>
    <select id="node-input-outputs">
      <option value="1">Enabled</option>
      <option value="0">Disabled</option>
    </select>
  </div>
</script>
`
