### ISSUE TITLE
Join node fails for 'Array', Key/value' and 'merged object'  if using was set to buffer

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red#2491]
### What are the steps to reproduce?
1) add join node
2) set mode to ’manual
3) set ‘join using’ to buffer
4) set ‘to create’ to any of 'an Array',  ‘a key/value Object’ or 'a merged Object'
5) set ‘After a number of message parts’ to 2
6) uncheck ‘and every subsequent message.’
7) Hit ‘Done’

### What happens?
If you now sent two msgs to the join with different topics, the join will not happen. The reason is that when you set ‘Join using’ to buffer, internally ‘joinerType’ has been set to ‘bin’ but it needs to be ‘str’
 
### What do you expect to happen?
The join should work

### Please tell us about your environment:

- [ ] Node-RED version: V1.0.3
- [ ] Node.js version: v12.13.0
- [ ] npm version: 6.13.4
- [ ] Platform/OS: macOS 10.14.6
- [ ] Browser: Safari

**Comment by dceejay** [comment]
Can you supply a small test case that shows this ? If I try a simple join bot the array and key/value object work fine and the merged object fails as the inputs aren't objects. (in my case).

**Comment by juggledad** [comment]
Here is a flow with a good join and one that doesn't work:
[{"id":"b00f156.29f2368","type":"tab","label":"Flow 14","disabled":false,"info":""},{"id":"3baa6f27.4b00c","type":"inject","z":"b00f156.29f2368","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":180,"wires":[["fa01acf.91f11d","dc8b9d65.3ac2f8"]]},{"id":"fa01acf.91f11d","type":"change","z":"b00f156.29f2368","name":"Topic 't1'payload 'hello'","rules":[{"t":"set","p":"payload","pt":"msg","to":"hello","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"t1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":160,"wires":[["3976176a.83ac98"]]},{"id":"dc8b9d65.3ac2f8","type":"change","z":"b00f156.29f2368","name":"Topic 't2'payload 'world'","rules":[{"t":"set","p":"payload","pt":"msg","to":"world","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"t2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":200,"wires":[["3976176a.83ac98"]]},{"id":"980cc088.081b88","type":"debug","z":"b00f156.29f2368","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":690,"y":180,"wires":[]},{"id":"3976176a.83ac98","type":"join","z":"b00f156.29f2368","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"str","accumulate":false,"timeout":"","count":"2","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":550,"y":180,"wires":[["980cc088.081b88"]]},{"id":"4922786.124bc88","type":"comment","z":"b00f156.29f2368","name":"This flow works","info":"","x":180,"y":100,"wires":[]},{"id":"610231f2.ac005","type":"inject","z":"b00f156.29f2368","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":340,"wires":[["b7a2cdeb.3f0f68","c33fa9ef.5f9128"]]},{"id":"b7a2cdeb.3f0f68","type":"change","z":"b00f156.29f2368","name":"Topic 't1'payload 'hello'","rules":[{"t":"set","p":"payload","pt":"msg","to":"hello","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"t1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":320,"wires":[["b165420e.906658"]]},{"id":"c33fa9ef.5f9128","type":"change","z":"b00f156.29f2368","name":"Topic 't2'payload 'world'","rules":[{"t":"set","p":"payload","pt":"msg","to":"world","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"t2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":360,"wires":[["b165420e.906658"]]},{"id":"5cd82fcd.f6d5f","type":"debug","z":"b00f156.29f2368","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":690,"y":340,"wires":[]},{"id":"b165420e.906658","type":"join","z":"b00f156.29f2368","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"bin","accumulate":false,"timeout":"","count":"2","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":550,"y":340,"wires":[["5cd82fcd.f6d5f"]]},{"id":"8f45c296.742a88","type":"comment","z":"b00f156.29f2368","name":"This flow does not works","info":"","x":210,"y":260,"wires":[]}]

if you export just the join node you get this
this is the join node from the good flow

[{"id":"3976176a.83ac98","type":"join","z":"b00f156.29f2368","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"str","accumulate":false,"timeout":"","count":"2","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":550,"y":180,"wires":[["980cc088.081b88"]]}]


this is the join node from the bad flow

[{"id":"b165420e.906658","type":"join","z":"b00f156.29f2368","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"bin","accumulate":false,"timeout":"","count":"2","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":550,"y":340,"wires":[["5cd82fcd.f6d5f"]]}]

if you look at the "joinerType" in the working flow it is 'str' in the bad flow it is 'bin'

**Comment by juggledad** [comment]
It looks to me that the issue is if you set the 'to create' option to 'string' or 'buffer' and change the 'join using to 'buffer, then switch  the 'to create' option' to  'an Array', ‘a key/value Object’ or 'a merged Object' the problem occurs

**Comment by dceejay** [comment]
I actually get an error when I try to deploy that flow.
Which seems to be because the join buffer is missing.
(so that needs to be fixed anyway - but not sure if that is what you are describing)

**Comment by juggledad** [comment]
The 'bad' flow doesn't output anything in the debug.

**Comment by dceejay** [comment]
well no - because it deploys with an error - (but it shouldn't)
![image](https://user-images.githubusercontent.com/5375409/75700413-ecc84e00-5ca9-11ea-9c74-c838f689d854.png)

**Comment by juggledad** [comment]
Yes I see that error and it is caused by the joinerType being 'bin' but you can ttell that flooking at the node becasue it doesn show the 'join using' when the 'to create' is set to 'an Array', ‘a key/value Object’ or 'a merged Object

I would think the code should change the joinetType to 'str' when you choose one of those three 'to create' types
