### ISSUE TITLE
Link works with node with 0 outputs

### ISSUE THREAD

**Issue by Installka** [node-red/node-red#2494]
### What are the steps to reproduce?
You should copy a function node with 0 outputs and paste it on the link between 2 nodes.

### What happens?
A function node inserts between 2 nodes, but output still does not work. 
![image](https://user-images.githubusercontent.com/26421878/75899923-3b621d80-5e4d-11ea-8054-97f74b89a52c.png)
Output link disappears on page refresh.

### What do you expect to happen?
Function node should not link between 2 other nodes.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.4
- [ ] Node.js version: 12.16.1
- [ ] npm version: 6.14.1
- [ ] Platform/OS: Windows 7 x64 with all updates
- [ ] Browser: Edge 80.0.361.62, Chrome 80.0.3987.132, Firefox 73.0.1

**Comment by knolleary** [comment]
Interesting... if you try dragging the a Function node with 0 outputs over a wire, it won't get spliced in. But if, as you report, you copy and paste, you can then drop the pasted node onto the wire. That's odd as its pretty much the same code for both cases... must be some subtle difference.

Thanks for reporting.
