### ISSUE TITLE
Switch Node - Wrong behaviour if "Otherwise" is on top

### ISSUE THREAD

**Issue by almostserious** [node-red/node-red#2499]
### What are the steps to reproduce?
Create a switch node listening to a specific message. Create 2 conditions and make the first one the "otherwise" option. Example flow:

`[{"id":"cd982c0c.f9b7d","type":"debug","z":"28e73868.21cde8","name":"HA","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1590,"y":120,"wires":[]},{"id":"418c82f1.7c28ec","type":"server-state-changed","z":"28e73868.21cde8","name":"Spotify?","server":"2fba4297.e4145e","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"media_player.spotify","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"paused","halt_if_type":"str","halt_if_compare":"is_not","outputs":2,"output_only_on_state_change":false,"x":1000,"y":160,"wires":[["410b739a.fe2b7c"],["610e10c3.b2b5e"]]},{"id":"410b739a.fe2b7c","type":"rbe","z":"28e73868.21cde8","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"data.new_state.attributes.source","x":1290,"y":160,"wires":[["b439db28.c516f8"]]},{"id":"610e10c3.b2b5e","type":"change","z":"28e73868.21cde8","name":"reset","rules":[{"t":"set","p":"data.new_state.attributes.source","pt":"msg","to":"reset","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1150,"y":200,"wires":[["410b739a.fe2b7c"]]},{"id":"b439db28.c516f8","type":"switch","z":"28e73868.21cde8","name":"Source?","property":"data.new_state.attributes.source","propertyType":"msg","rules":[{"t":"else"},{"t":"eq","v":"HomeAssistant","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1420,"y":160,"wires":[["cd982c0c.f9b7d"],["b72104c4.762a28"]]},{"id":"b72104c4.762a28","type":"debug","z":"28e73868.21cde8","name":"off","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1590,"y":180,"wires":[]},{"id":"2ed7605c.70a4c","type":"comment","z":"28e73868.21cde8","name":"Switch Node Issue - Otherwise on first check","info":"","x":1110,"y":100,"wires":[]},{"id":"2fba4297.e4145e","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true}]`
## What happens?
If the check all conditions is selected, the message will come on both ends, even though one of them is incorrect
### What do you expect to happen?
The message should only come out on the correct end. If "otherwise" is on the bottom, this works fine.
### Please tell us about your environment:

- [x] Node-RED version: 1.0.4
- [ ] Node.js version:
- [ ] npm version:
- [x] Platform/OS: Ubuntu / HomeAssistant
- [x] Browser: Chrome
Using this addon for HomeAssistant:
https://github.com/hassio-addons/addon-node-red

**Comment by knolleary** [comment]
Rules are checked from the top to the bottom.

"otherwise" means "if nothing above has matched". If you put it at the top of the list then nothing above it will have matched so you get the message from that rule.

**Comment by nileio** [comment]
@almostserious shouldn't this issue be closed now ?

**Comment by almostserious** [comment]
You are right.
