### ISSUE TITLE
twitter output node can lose messages at startup

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#250]
Twitter output node authenticates with twitter asynchronously, and until it has done so, any tweets sent to the node are ignored.

This is a problem if you want your flow to tweet that it has started up (e.g. http://flows.nodered.org/flow/c402d340dcd8f4e1376e ), and to make this work you have to use a short delay to make sure twitter output node has inititialised.

It would be good if the twitter node (and other asynchronous output nodes, like MQTT and serial out) could buffer messages pending initial start up, then process them. If the connection fails, they can dump the messages and report an error... 

This would make the behaviour "as expected", rather than needing a bit of a work-around to work in certain situations.

**Comment by knolleary** [comment]
We removed the async auth of the output node a while ago, but failed to close this off - 961c9f3fa945a5e197275b94254fc416f0129592
