### ISSUE TITLE
subflow $parent. does not return a value after nodered restart

### ISSUE THREAD

**Issue by nileio** [node-red/node-red#2513]
please refer to https://discourse.nodered.org/t/facing-issues-using-parent/23231/8

### What are the steps to reproduce?

![2020-03-18_09-16-47 (1)](https://user-images.githubusercontent.com/24714766/77221529-7c249b00-6b9e-11ea-9a28-b91a1b6cbd83.gif)

1. create a subflow from existing nodes and use `$parent.` to retrieve parent context.
2. `$parent.` returns the value as expected of parent context.
3.  create a new flow and place that subflow on it, and make sure you have a context var to use for test.
4. use an inject node to test the subflow return value.
if you get the value, check again after a restart of nodered
### What happens?
in my environment, no `undefined` is returned nor the context value. I use a dev machine that has the issue and also the machine i migrated to also has the issue. My workaround is to create the subflow from scratch again, which then works fine. However, when I place the created subflow on a new flow, the `$parent.` stop working again. It is unclear to me what exactly is causing this: my subflow itself, bug with `$parent.`, or subflow from existing nodes function , or subflow bug.
### What do you expect to happen?
return the parent context value
### Please tell us about your environment:

- [ ] Node.js version: 10.19.0
- [ ] Node-RED version: 1.04
- [ ] npm version: 6.13.4
- [ ] Platform/OS: archlinux (docker image minimal)
- [ ] Browser: Chrome

**Comment by nileio** [comment]
I finally nailed down the issue and consistently re-produce the behavior. 
In my subflow I use the contrib node q-gate (https://github.com/drmibell/node-red-contrib-queue-gate)..
It is very odd behavior but when I removed the node q-gate from the subflow, the issue is resolved and works after restarts,etc. consistently. When I add the node q-gate back , the issue returns again.

I reviewed the code of that node and cannot immediately determine why this particular node would interfere with the use of `$parent.` or rather why would node-red have an issue with this node placed on a sub-flow. The node works fine on the root flow.
For now, I removed the node and substituted with my own code but I will keep an eye on this to understand the root cause..

**Comment by knolleary** [comment]
I've figured out the issue, although the fix will take a bit of time to get right.

The issue is all of the nodes you've identified access their context in their constructor function. They are absolutely allowed to do that, but it exposes a problem with the way subflow instance context is created - it gets done *after* the nodes are created. But as the nodes have already accessed their context by that time, it breaks the link between the node context and its parent.

Need to get the subflow instance context created before the node contexts - but that requires some careful work to get right.

**Comment by nileio** [comment]
thanks @knolleary for timely and prompt response on this issue
