### ISSUE TITLE
Node-red is crashed when some nodes are crashed

### ISSUE THREAD

**Issue by dinhvanviet2608** [node-red/node-red#2520]
### What are the steps to reproduce?
- add two customized nodes which open a same TCP port such as 12000 with no exception handling
- click button deploy
### What happens?
- node-red is crashed
- if user runs node-red again, node-red is crashed
### Please tell us about your environment:

- [x] Node-RED version: 1.0.3
- [x] Node.js version: v12.16.1
- [x] npm version:  6.13.4
- [x] Platform/OS: Windows 10 64 bit version 1909
- [x] Browser: Chrome

**Comment by knolleary** [comment]
Yes. If a node is badly written and doesn't handle errors properly it will cause the runtime to stop as it cannot safely continue.

To start Node-RED without running the flows you can use the `--safe` commanf li e argument. That will allow you to edit and fix your flows before deploying to start them.
