### ISSUE TITLE
Trigger node gives error if msg.payload doesn't exist

### ISSUE THREAD

**Issue by cymplecy** [node-red/node-red#2536]
### What are the steps to reproduce?
Pass message with no msg.payload and try to send it on
![image](https://user-images.githubusercontent.com/2357428/79040870-85c08200-7be3-11ea-80e1-27b7958db550.png)

### What do you expect to happen?
The msg object is passed on

- [1.0.4 ] Node-RED version:
- [10.16.3 ] Node.js version:
- [6.13.4 ] npm version:
- [ Win 10] Platform/OS:
- [Chrome ] Browser:

**Comment by hardillb** [comment]
Are you sure that is the trigger node throwing the error? I can't find anywhere in the node where it tries to access a field called `req`.

If you mouse over the error it will highlight the node that threw the error.

**Comment by knolleary** [comment]
The error comes from trying to clone undefined and was fixed in 1.0.4 (see #2399)... so odd that you are still seeing it in 1.0.4.

**Comment by cymplecy** [comment]
Much apologies - I thought all my Node-REDs were on 1.0.4 - this one was on 1.0.3 - sorry fro time wasting :(

**Comment by dceejay** [comment]
Actually it does still fail if msg = null object - rather than undefined.

**Comment by dceejay** [comment]
should https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/util/lib/util.js#L84
be
```
if (typeof msg !== "undefined" && msg !== null) {
```
