### ISSUE TITLE
Automatic Object creation

### ISSUE THREAD

**Issue by kempert** [node-red/node-red#2537]
No Automatic Object creation in the Objects Tab

The object State Changing is litstet in the events.

Node Red is installed on an Multihost Slave at ioBroker.

`

node-red.1 | 2020-04-15 00:45:52.509 | info | (9782) Automatic objects creation is not enabled. You can enable it in the node configuration
-- | -- | -- | --
node-red.1 | 2020-04-15 00:45:32.244 | debug | (9767) 15 Apr 00:45:32 - [info] serial port /dev/ttyACM0 opened at 9600 baud 8N1
node-red.1 | 2020-04-15 00:45:32.173 | debug | (9767) 15 Apr 00:45:32 - [info] Flows gestartet
node-red.1 | 2020-04-15 00:45:32.042 | debug | (9767) 15 Apr 00:45:32 - [info] [inject:Abrufen - PH Wert] Wiederholen = 20000
node-red.1 | 2020-04-15 00:45:31.218 | debug | (9767) 15 Apr 00:45:31 - [info] Flows starten
node-red.1 | 2020-04-15 00:45:30.556 | debug | (9782) statesDB connected
node-red.1 | 2020-04-15 00:45:30.548 | debug | (9782) States connected to redis: 192.168.178.8:9000
node-red.1 | 2020-04-15 00:45:30.468 | debug | (9767) 15 Apr 00:45:30 - [info] Server wird jetzt auf http://192.168.178.7:1881/ ausgeführt.
node-red.1 | 2020-04-15 00:45:29.804 | debug | (9767) 15 Apr 00:45:29 - [info] Flow-Datei: /opt/iobroker/iobroker-data/node-red/projects/Pool-Steuerung-Kemper/flows.json
node-red.1 | 2020-04-15 00:45:29.786 | debug | (9767) 15 Apr 00:45:29 - [info] Aktives Projekt: Pool-Steuerung-Kemper
node-red.1 | 2020-04-15 00:45:29.720 | debug | (9782) States create System PubSub Client
node-red.1 | 2020-04-15 00:45:29.662 | debug | (9782) States create User PubSub Client
node-red.1 | 2020-04-15 00:45:29.454 | debug | (9782) Redis States: Use Redis connection: 192.168.178.8:9000
node-red.1 | 2020-04-15 00:45:29.423 | debug | (9782) objectDB connected
node-red.1 | 2020-04-15 00:45:29.345 | debug | (9782) Objects connected to redis: 192.168.178.8:9001
node-red.1 | 2020-04-15 00:45:28.985 | debug | (9782) Objects client initialize lua scripts
node-red.1 | 2020-04-15 00:45:28.977 | debug | (9782) Objects create User PubSub Client
node-red.1 | 2020-04-15 00:45:28.962 | debug | (9782) Objects create System PubSub Client
node-red.1 | 2020-04-15 00:45:28.905 | debug | (9782) Objects client ready ... initialize now
node-red.1 | 2020-04-15 00:45:27.803 | warn | (9782) no connection to objects DB
node-red.1 | 2020-04-15 00:45:20.274 | debug | (9782) Redis Objects: Use Redis connection: 192.168.178.8:9001
node-red.1 | 2020-04-15 00:45:27.696 | debug | (9767) 15 Apr 00:45:27 - [info] Benutzerverzeichnis: /opt/iobroker/iobroker-data/node-red/
node-red.1 | 2020-04-15 00:45:27.670 | debug | (9767) 15 Apr 00:45:27 - [info] Kontextspeicher: 'default' [ module=memory]
node-red.1 | 2020-04-15 00:45:27.644 | debug | (9767) 15 Apr 00:45:27 - [info] Einstellungsdatei: /opt/iobroker/iobroker-data/node-red/settings.js
node-red.1 | 2020-04-15 00:45:22.633 | debug | (9767) 15 Apr 00:45:22 - [info] Dashboard version 2.20.0 started at /ui
node-red.1 | 2020-04-15 00:45:12.358 | debug | (9767) 15 Apr 00:45:12 - [info] Polymer started at /polymer
node-red.1 | 2020-04-15 00:44:52.114 | debug | (9767) 15 Apr 00:44:52 - [info] Paletten-Nodes werden geladen
node-red.1 | 2020-04-15 00:44:45.643 | debug | 15 Apr 00:44:45 - [info] Linux 4.19.97+ arm LE
node-red.1 | 2020-04-15 00:44:45.643 | debug | (9767) 15 Apr 00:44:45 - [info] Node.js Version: v10.20.1
node-red.1 | 2020-04-15 00:44:45.620 | debug | (9767) 15 Apr 00:44:45 - [info] Node-RED Version: v1.0.5
node-red.1 | 2020-04-15 00:44:45.587 | debug | ===================
node-red.1 | 2020-04-15 00:44:45.587 | debug | Willkommen bei Node-RED!

`

- [ ] Node-RED version:  1.0.5
- [ ] Node.js version: 10.20.1
- [ ] npm version: 6.14.4
- [ ] Platform/OS: Raspberry Pi B+ (Raspbian Buster)

**Comment by knolleary** [comment]
That message is coming from one of the nodes you have installed. It is not coming from the core of Node-RED.

You will need to identify what node is logging it and then take the appropriate action to fix it.

**Comment by kempert** [comment]
Thank you for your information, but I found this node wich create a object in Iobroker, but i mean it is correctly configured. But no object is created.

![image](https://user-images.githubusercontent.com/51061932/79431963-75394e80-7fcb-11ea-875f-c6499a14b2d1.png)

**Comment by dceejay** [comment]
This is not a node maintained by the Node-ED project - please raise the issue against that project.
https://github.com/ioBroker/ioBroker.node-red/issues
thanks
