### ISSUE TITLE
optimize the flow management panel

### ISSUE THREAD

**Issue by cmdares** [node-red/node-red#2541]
At present, the platform has 80 flow and needs to optimize the flow management panel
Problem:
1、Slow opening speed
2、There is no hierarchy in management

Hope for improvement:
1. Add close button to each tab
2. flow can be saved and opened through catalog
Reference example:
![flow_manager](https://user-images.githubusercontent.com/5292190/79586873-4ecafe80-8104-11ea-90b1-1879a834b0cd.png)

thanks!
regard.

**Comment by knolleary** [comment]
The issue template you have deleted asks that feature suggestions are made on the forum. This issue list is for bugs and code issues. It is not where we maintain our backlog of features.

**Comment by knolleary** [comment]
Just to add, the topic of managing flows has been discussed frequently on the forum. Please search to see what has been discussed and what is already in the plan to address it.
