### ISSUE TITLE
flow.set doesnt work inside subflows with function nodes

### ISSUE THREAD

**Issue by LRagji** [node-red/node-red#2552]
### What are the steps to reproduce?
Docker run NR version 1.0.6

### What happens?
flow.set doesnot work inside subflow with function node; while global.set works

### What do you expect to happen?
flow.set to set value in flow context.

### Please tell us about your environment:

- [ ] Node-RED version:1.0.6
- [ ] Node.js version: as used by docker image
- [ ] npm version: as used by docker image
- [ ] Platform/OS: Mac
- [ ] Browser: Chrome 81

**Comment by hardillb** [comment]
You are probably going to have to be more explicit here, just saying "it doesn't work" isn't very helpful. Please supply a sample flow that demonstrates the problem and explain how you are testing the variable is/isn't set.

**Comment by knolleary** [comment]
Hi,

The `flow` context inside a subflow is scoped to the subflow itself. It is not the flow context the instance of the subflow is on.

If you want to access the flow context of the flow the subflow instance is on, you need to prefix the key with `$parent.`

**Comment by LRagji** [comment]
The way i am checking is clicking the refresh button on context panel..
Here is my subflow:
`[{"id":"f2e4613c.d9ae3","type":"subflow","name":"Tenancy-Set","info":"","category":"","in":[{"x":120,"y":160,"wires":[{"id":"1a8271dd.7e7f6e"}]}],"out":[],"env":[{"name":"Tenant","type":"str","value":"Dev"}],"color":"#DDAA99"},{"id":"1a8271dd.7e7f6e","type":"function","z":"f2e4613c.d9ae3","name":"","func":"msg.key= env.get(\"Tenant\")+\"-\"+msg.key;\nflow.set(msg.key,msg.payload)\nreturn msg;","outputs":1,"noerr":0,"x":250,"y":160,"wires":[["a26eeb74.e13c18"]]},{"id":"a26eeb74.e13c18","type":"debug","z":"f2e4613c.d9ae3","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":370,"y":160,"wires":[]}]`

**Comment by LRagji** [comment]
> Hi,
> 
> The `flow` context inside a subflow is scoped to the subflow itself. It is not the flow context the instance of the subflow is on.
> 
> If you want to access the flow context of the flow the subflow instance is on, you need to prefix the key with `$parent.`

Did that still nothing; But a funny thing is when i use a change node inside a subflow and set flow context it works perfect.(does the parent thing not apply to this node?)

**Comment by knolleary** [comment]
What exactly did you change your function code to? Just share the code, not the whole flow again.

**Comment by LRagji** [comment]
`flow.set(msg.key,msg.payload);`
to
`$parent.flow.set(msg.key,msg.payload);`
also i got an error $parent is not defined

**Comment by LRagji** [comment]
> What exactly did you change your function code to? Just share the code, not the whole flow again.

Ooop's sorry it worked my prev comment was some else problem but this is different from what docs says https://nodered.org/docs/user-guide/writing-functions#api-reference
Is this the correct way or workaround..

**Comment by knolleary** [comment]
The docs on using context do highlight the need to use `$parent` to access the parent flow context from inside a subflow: https://nodered.org/docs/user-guide/context#context-scopes

The function node docs don't make particular mention of subflows, but they could do.

**Comment by LRagji** [comment]
We can do better if we link these documents, i feel; anyways closing this issue, Thanks for the help
