### ISSUE TITLE
MQTT in cannot import password from environment variables

### ISSUE THREAD

**Issue by Myzhar** [node-red/node-red#2560]
### What are the steps to reproduce?

Cannot import the password to connect to the MQTT broker getting it from environment variables

### What happens?

The environment variable is not solved, it seems that using the syntax `$(ENV_VAR)` or `${ENV_VAR}` in the "password" field is not supported

### What do you expect to happen?

I expect that the environment variable is substituted runtime

### Please tell us about your environment:

- [ ] Node-RED version: v1.0.5
- [ ] Node.js version:  v8.10.0
- [ ] npm version: v3.5.2
- [ ] Platform/OS: Ubuntu 16.04
- [ ] Browser: Chrome

**Comment by hardillb** [comment]
Please provide a sample flow showing the problem and details about how you are starting Node-RED and where you are setting the environment variable.

Also are you only seeing this with the password field or other fields as well?

**Comment by Myzhar** [comment]
This happens only for the password field. I use the same technique to get the address and the port of the MQTT broker and the login.
The password is correctly available as environment variable because I can use a sub-flow with a Javascript function block to print it in the debug console, copy it and paste in the password field.

It's like is the `$(ENV_VAR)` or the `${ENV_VAR}` chars are fully used as chars of the password instead of being replaced before starting the flow.

I also tried to manually add the credential fields in the JSON of the flow, but it does not work either.

**Comment by hardillb** [comment]
Please supply all the things I requested in the previous comment (sample flow and details of exactly how you are setting the environment variables).

Environment variables for MQTT broker passwords work fine here with v1.0.6 so we need to see exactly how you are setting them up to see if there is a problem.

**Comment by Myzhar** [comment]
This is how I tried to configure the "MQTT in" node:

```
[
    {
        "id": "c424a025.abca3",
        "type": "tab",
        "label": "Test MQTT",
        "disabled": false,
        "info": ""
    },
    {
        "id": "5e16d1f1.dcda4",
        "type": "mqtt in",
        "z": "c424a025.abca3",
        "name": "",
        "topic": "/local_device/data/event_social_distance",
        "qos": "1",
        "datatype": "auto",
        "broker": "adbd6123.33c2c",
        "x": 220,
        "y": 160,
        "wires": [
            []
        ]
    },
    {
        "id": "adbd6123.33c2c",
        "type": "mqtt-broker",
        "z": "",
        "name": "",
        "broker": "127.0.0.1",
        "port": "${SL_MQTT_PORT}",
        "clientid": "",
        "usetls": false,
        "compatmode": true,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "credentials": {
            "user": "application",
            "password": "${SL_APPLICATION_TOKEN}"
        }  
    }
]
```

**Comment by hardillb** [comment]
Please help us to help you, give ALL the details I've asked.

You haven't answered how/where you are setting the environment variables outside of Node-RED or how you are starting Node-RED.

Also since that flow has credentials attached, are you:

 - entering the flow via the editor
 - upload the flow with the API
 - pasting the flow into the import window?

**Comment by hardillb** [comment]
That flow when pasted into the Import option for Node-RED v1.0.6 is working as expecting and picking up the environment variables that are in scope before Node-RED is started.

**Comment by Myzhar** [comment]
The node-red server starts with a docker container. The flow is copied in the container in the folder `/usr/src/node-red/data` and the environment variable `FLOWS=./data/flows.json` is set so the flow is loaded when node-red starts.

To make the tests to verify that the "automatic login" works I'm now pasting the JSON in the import window.

**Comment by hardillb** [comment]
And HOW have you set the SL_APPLICATION_TOKEN environment variable? Show your docker command line.

You seem to be giving the minimal possible answer to every question I ask, which is making it VERY hard to help you.

**Comment by knolleary** [comment]
Here is a simple Inject -> Debug flow you can use to verify the SL_APPLICATION_TOKEN is actually set in your Node-RED environment:
```
[{"id":"c44c79bb.a34fa8","type":"inject","z":"6a4f2112.f1006","name":"","topic":"","payload":"SL_APPLICATION_TOKEN","payloadType":"env","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":590,"y":300,"wires":[["bfabd934.039748"]]},{"id":"bfabd934.039748","type":"debug","z":"6a4f2112.f1006","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":800,"y":300,"wires":[]}]
```

**Comment by Myzhar** [comment]
The `SL_APPLICATION_TOKEN` is correctly present in environment variables because I use a Javascript node to read it and print it in the debug console to manually copy and paste in the MQTT form to manually login

**Comment by dceejay** [comment]
please try to bear with us and answer Ben's question exactly as asked... Show us how you are passing in the environment variable to docker.

**Comment by Myzhar** [comment]
I cannot reply to this question because the container has been created by other persons and I only know that the environment variable is present.

However I just tested the flow as I posted above on the system and now it seems to work.
I only changed my docker compose file adding `user: root`

**Comment by Myzhar** [comment]
I noticed another important issue about this topic.
If you import the flow file with the "credentials" fiels in the JSON everything works for the first connection. 
If you modify the flow and you deploy it everything continue to work.
If you restart the container the flow files updated by the deploy does not contain the credential fields and the automatic connection does not happen...

**Comment by hardillb** [comment]
This sounds like you have a permissions problem with the useData directory and you are having problems updating/overwriting the credentials file. 

 1. Do you have a volume mounted to `/data`
 2. What are the permissions on `/data` (both in the container and where ever the volume is mounted from)
 3. Include your Docker compose file so we can SEE EXACTLY how everything is being started.
 4. Have you looked at the container logs for any output (add the output from when you deploy, both the first and the second time)?

Please update with answers to ALL these and previous questions.

**Comment by Myzhar** [comment]
I'm waiting for info about how the environment variables are injected in the container.

1. Yes, in order to have persistence for modifications in the flow
2. Locally the `./data` folder has r/w permissions for all users and groups. How can I check it in the container?
3. Here it is the composer file:
```
version: '2.3'
services:
  social_dist_notifier:    
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "1880:1880"
      - "3456:3456"
    privileged: true
    network_mode: "host"
    environment:
      - FLOWS=/usr/src/node-red/data/flows.json
    volumes:
        - ./save_files:/usr/src/node-red/save_files
        - ./data:/usr/src/node-red/data
```
4. I checked the JSON file inside the local folder before and after deploy and I confirm that after the deploy the credential fields disappear:
Before: [flows_before_deploy.zip](https://github.com/node-red/node-red/files/4610002/flows_before_deploy.zip)
After: [flows_after_deploy.zip](https://github.com/node-red/node-red/files/4610003/flows_after_deploy.zip)

The log does not report any error about MQTT broker connection

**Comment by hardillb** [comment]
The credential field is not meant to be in the flow file, the credentials are stripped out and encrypted then stored in a separate file called `flows_cred.json` when you deploy

You don't appear to be using the Node-RED docker container, so I can't tell where you have set the userDir so we have no idea if the file is ending up in one of the directories you have as a mounted volume. Post the content of your `Dockerfile`

**Comment by Myzhar** [comment]
> The credential field is not meant to be in the flow file, the credentials are stripped out and encrypted then stored in a separate file called flows_cred.json when you deploy

This is important. I did not know it (thank you for reporting)

This is actually the Docker file that I'm using:
```
FROM nodered/node-red:latest

RUN mkdir -p /usr/src/node-red/data
RUN mkdir -p /usr/src/node-red/save_files
RUN chown node-red /usr/src/node-red/data
RUN chown node-red /usr/src/node-red/save_files

USER node-red

RUN npm install node-red-contrib-counter
RUN npm install node-red-contrib-alexa-remote2
```

**Comment by hardillb** [comment]
OK, so the problem here is that your credentials file will still be being stored in the `userDir` which is  `/data` in the container. You are not mounting this as a volume so it will not be persisted across a container restart. So your creds file will be lost, hence not being able to reconnect to the MQTT broker.

I suggest you don't bother with the `/usr/src/node-red/data` or `/usr/src/node-red/save_files` at all and just put everything in `/data` and make sure that is mounted as volume.

You also will not need the `user:root`.

We would have got here a lot quicker if you had fully described what you were doing at the start.

**Comment by Myzhar** [comment]
> We would have got here a lot quicker if you had fully described what you were doing at the start.
You are right, but I'm a C++ developer and I'm starting using node-red and docker containers a few days ago, so it was not easy to understand all of your requests.

Thank you for your patience :)

**Comment by Myzhar** [comment]
@hardillb last question before closing the issue.

I finally got info about how environment variables are injected in the container. There is an IoT manager that modifies the `docker-compose.yaml` file adding the required environment variable as
```
    environment:
      - SL_APPLICATION_TOKEN=<password_token`
```

Now the question: how is the variable stored in the `flows_cred.json`? Is it stored after it's retrieved from the environment variables or is it stored as `${SL_APPLICATION_TOKEN}`?

I guess it is resolved before been stored and in this case it is a problem for me because when the system reboots the variable is changed and in the persistence volume the variable stored is old.
When the flow start in the file `flows.json` the fields 
```
    "credentials": {
            "user": "application",
            "password": "${SL_APPLICATION_TOKEN}"
```
are no more present and the password is not updated.

You could say: "well, you could simply restore the original flow file before each startup", but with this solution I lose all the changes eventually made to the flow while the system is running...

**Comment by hardillb** [comment]
It stores the environment variable name and resolves it at at start up

**Comment by Myzhar** [comment]
That's good, I can finally close the issue. 

Thank you very much again
