### ISSUE TITLE
Dashboard can't authorize in Home Assistant Mobile app

### ISSUE THREAD

**Issue by tampa44** [node-red/node-red#2565]
### What are the steps to reproduce?
Home assistant app installed on android phone from play store. Going to node red addon > dashboard in right menu and clicking on pop out window icon to open the node red ui

### What happens?
In internet browsers we can easily open the browser and authorise the browser with the node red username and password we set. However in the home assistant app when we click on the pop out window it opens up in our phones default browser and the browser gets authorised not the home assistant app.

### What do you expect to happen?
The home assistant app needs authorisation to view the node red dashboards

### Please tell us about your environment:

- [ ] Node-RED version: 6.2.0
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS: Home Assistant 
- [ ] Browser: Home Assistant app for android

**Comment by hardillb** [comment]
First point, this repo is specifically for the the core of Node-RED not the Dashboard UI, are you sure you are raising this against the right repo?

Second, without the template fully filled out this is likely to just get closed immediately.

**Comment by tampa44** [comment]
Sorry I accidentally pressed enter on the keyboard and it posted an empty message.

My bad I don't do alot of posting in git hub I see now that there is a section for the dashboard I will post there and close this one.

**Comment by hardillb** [comment]
Having now read the description, this needs raising against HomeAssistant not Node-RED

**Comment by tampa44** [comment]
Cool
