### ISSUE TITLE
Unable to create a new project 

### ISSUE THREAD

**Issue by gitsaycat** [node-red/node-red#2575]
In node-red running in docker (tag 1.0.6/5-10) - v1.0.6/5 I am unable to complete the steps to create a new project 
### What are the steps to reproduce?
Simple pull up the new project dialog and proceed on a brand new container

### What happens?
The NEXT button does not get enabled and am unable to proceed

### What do you expect to happen?
In tag 1.0.4-10 - v1.0.4 - at this point the NEXT button is enabled allowing the user to proceed

Below is the screenshot for **1.0.4:**
![image](https://user-images.githubusercontent.com/14805543/82408228-c5f60880-9a9d-11ea-84c8-f355c83e1419.png)

Below is the screenshot for **1.0.6**
![image](https://user-images.githubusercontent.com/14805543/82407498-de652380-9a9b-11ea-8064-ea3d300213d7.png)

**Comment by knolleary** [comment]
Hi @gitsaycat  - this is a strange one. Not able to reproduce locally.

From the screenshot it looks like it has got stuck validating whether 'test' is an existing project name or not - but that's an entirely local action that just checks it against the list of known projects and what characters you've used. I can't see anything that would cause it to appear to hang like this. Nor has this area of code changed *at all* for about 2 years - so definitely strange that it should suddenly stop working for you between 1.0.4 and 1.0.6.

To help narrow down any potential causes, could you try a different browser? I can't imagine that would help, but always worth a quick check if you can.

**Comment by gitsaycat** [comment]
Hi Nick - thanks for looking into this.
I'm running node-red in a docker container and had the node-red **data** folder mapped to a folder in the host machine.
I changed the setup to now use a docker volume that is no longer mapped to a host machine folder and the problem is resolved
I am surprised at the result because the original configuration is working in several other environments and can only guess that some permission related issue could be the problem.
Please close this issue if that makes sense for now, I will reopen if I find more concrete data
Regards, gitsaycat
