### ISSUE TITLE
Suggestion: Automated UI testing on Travis CI

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#2591]
The Node-RED project has automated UI testing to prevent bugs related to UI. Currently, the UI developers need to execute the UI test on their PC using `grunt test-ui` command after executing the install command, `install-ui-test-dependencies.sh` manually. I think that it is useful for contributors to execute the UI testing on Travis CI automatically when they submit their pull requests and commits.

To realize it on `.travis.yml` setting file, there are the following two methods.

- Method 1: Install Google Chrome on Travis environment, and then execute UI testing
  - Pros
    - Short execution time because of local testing process on Travis
  - Cons
    - Testing for Google Chrome only

- Method 2: Execute UI testing using BrowserStack from Travis
  - Pros
    - Test for both Firefox and Google Chrome
    - Ability to check UI behaviors from screen-captured video on BrowserStack
  - Cons
    - Long execution time due to network response between Travis and BrowserStack servers, etc.
    - BrowserStack approval as OSS to use it free

How about this suggestion? I can contribute the code whichever.

**Comment by knolleary** [comment]
I think you are right we should be running the UI tests regularly.

I would suggest we start with Method 1 and see how we go. I think it is pretty rare that we get any sort of difference in behaviour between Chrome/FF - so I don't feel the need to jump straight to testing a full matrix of browsers with BrowserStack.

At the moment we run the existing tests against 4 different versions of Node - 8, 10, 12, 14. I don't think it is necessary to run the UI tests against all of those. I suggest picking one of them for the UI tests (which may as well be Node 14).

**Comment by kazuhitoyokoi** [comment]
@knolleary Thank you for your comment. I will try to create `travis.yml` for method 1 tomorrow.

**Comment by knolleary** [comment]
Closing as we have now enabled the UI tests in Node 10
