### ISSUE TITLE
Node-Red Editor: bug Inject-Node

### ISSUE THREAD

**Issue by AndreasHeine** [node-red/node-red#2594]
### What happens?
If i want to change the Interval of the Inject Node i select Interval and nothing appeares...
![inject](https://user-images.githubusercontent.com/56362817/83643439-4d6c6d00-a5b0-11ea-81d4-6fef615e9c45.PNG)
the HTML Element is "hidden" !
![html](https://user-images.githubusercontent.com/56362817/83643513-64ab5a80-a5b0-11ea-95bc-3f7a1f0a7f46.PNG)
If i delete the "hidden" in the Inspector the option appears
![manualy delete hidden](https://user-images.githubusercontent.com/56362817/83643459-552c1180-a5b0-11ea-96ba-53358cc83d2a.PNG)
### What do you expect to happen?
If i select Interval i expect that it appears automaticaly!

### Please tell us about your environment:

- [x] Node-RED version: 1.03
- [x] Node.js version: v10.18.0
- [x] npm version: 6.13.4
- [x] Platform/OS: Client is Win10 and Node-Red runs on Linux (RevPi Connect+) Rasbian Stretch
- [x] Browser: Mozilla Firefox 76.0.1 (64-Bit) / Microsoft Edge 44.17763.831.0 / Google Chrome
Version 83.0.4103.61 (Offizieller Build) (64-Bit)

**Comment by knolleary** [comment]
Not been able to reproduce this here and haven't had any similar reports from the community.

I assume there aren't any associated errors in the browser developer console?

**Comment by AndreasHeine** [comment]
first line appears on droping the inject node and second line on opening the node config tab!

![Unbenannt](https://user-images.githubusercontent.com/56362817/93340935-c9bc5080-f82d-11ea-9e1e-c877f7c1e32e.PNG)

on changing to interval nothing happens...  hope its what you asked for!

**Comment by knolleary** [comment]
I was hoping for something in English I can read... but I don't think either of those are relevant from what I can pick out.

**Comment by AndreasHeine** [comment]
sorry about that german os / browser installation...

1. Error processing value for cursor. Declaration ignored.
2. Password fields are available on an insecure (http: //) page. This is a security risk and credentials can be stolen.

**Comment by AndreasHeine** [comment]
atm i am running it in container and it workes but not on the native Rasbian Stretch

`sudo docker run -it -p 1880:1880 --name mynodered nodered/node-red`
container version of node v10.22.0 node-red v1.1.3

i mean this workaround works but it made some things more complex

**Comment by dceejay** [comment]
I can't think we had any changes in this area but I note the Pi version is 1.0.3 vs the newer 1.1.3 in docker.

**Comment by AndreasHeine** [comment]
i have managed to figure out when it happens... finaly ^^
it happens always if i flash a backup on the revPi so after flashing the bug appears! if i just start with a blank os and install everything fresh everything is fine, then if i make a image of the revpi and reflash it, the bug appears again...
does that sound familiar to anyone? i am kind of lost on that issue...

**Comment by dceejay** [comment]
So it's fine if you install clean on the rev-pi ?
We don't have the ability to test on devices like that so anything extra it may be doing during backup/restore is going to be hard to diagnose remotely.

**Comment by AndreasHeine** [comment]
tbh it does not matter if i use the rev-pi or just a raspi3, i assume its happening while flashing...

**Comment by AndreasHeine** [comment]
UPDATE:
somehow its gone in the latest version!
thanks
