### ISSUE TITLE
[BUG] En/Disable configuration node on Outliner works only once

### ISSUE THREAD

**Issue by gfcittolin** [node-red/node-red#2597]
### What are the steps to reproduce?
 1. Add a configuration node to the flow
 2. On the Outliner, click to disable the configuration node
 3. Click again to re-enable the configuration node

### What happens?
 - The configuration node doesn't get reenabled. Looks like the click event is going through the button and getting caught by the whole row.
 - This happens only for configuration nodes. Flows, flow nodes and subflow nodes seem to work normally.
 - Refreshing the browser cleans it up and enables the button again, for one more shot.

![Peek 2020-06-04 20-17 - NodeRED Outliner disable config node](https://user-images.githubusercontent.com/2856088/83820026-d8796000-a6a1-11ea-9e39-4b51d23aa565.gif)

### Please tell us about your environment:

- [ ] Node-RED version: 1.1.0-beta.1
- [ ] Node.js version: 14.4.0
- [ ] npm version: 6.14.5
- [ ] Platform/OS: Kubuntu 20.04
- [ ] Browser: 
  - Chrome 83.0.4103.61 (Official Build) (64-bit)
  - Firefox 76.0.1 (64-bit)

**Comment by gfcittolin** [comment]
Additional note: this also happens when creating a group of nodes from selection, but only in the session when this is performed. Loading the editor with a flow already containing a group doesn't show up the symptom

**Comment by knolleary** [comment]
Fixed in the `dev` branch - will do a beta.2 soon.
