### ISSUE TITLE
[BUG] Flow gets "visually broken" when merging changes from the server

### ISSUE THREAD

**Issue by gfcittolin** [node-red/node-red#2598]
### What are the steps to reproduce?
 1. Open the same flow on two different browsers/tabs
 2. Modify and deploy the flow on one tab
 3. On the other tab, merge the incoming changes

### What happens?
The flow gets "visually broken" (what would be a better term for that? :smile: )

![Peek 2020-06-04 20-41 - NodeRED Merge flow nodes placement](https://user-images.githubusercontent.com/2856088/83823017-1e85f200-a6a9-11ea-9214-8d448f14e584.gif)

By inspecting the DOM, we can see `NaN` where should be the position, but couldn't find out where it came from:

![image](https://user-images.githubusercontent.com/2856088/83822977-031ae700-a6a9-11ea-9992-a6fa6c6636b4.png)

### Please tell us about your environment:

- [ ] Node-RED version: 1.1.0-beta.1
- [ ] Node.js version: 14.4.0
- [ ] npm version: 6.14.5
- [ ] Platform/OS: Kubuntu 20.04
- [ ] Browser:
  - Chrome 83.0.4103.61 (Official Build) (64-bit)
  - Firefox 76.0.1 (64-bit)

**Comment by knolleary** [comment]
Fixed in the `dev` branch - will do a beta.2 soon.
