### ISSUE TITLE
Outliner doesn't refresh list with an active filter

### ISSUE THREAD

**Issue by jeancarl** [node-red/node-red#2601]
### What are the steps to reproduce?

1. Example flow with three comment nodes:
```
[{"id":"19ea7c09.8e3a3c","type":"tab","label":"Flow 5","disabled":false,"info":""},{"id":"be2efdb9.ccb368","type":"comment","z":"19ea7c09.8e3a3c","name":"","info":"","x":760,"y":120,"wires":[]},{"id":"32ca02c3.023486","type":"comment","z":"19ea7c09.8e3a3c","name":"","info":"","x":760,"y":160,"wires":[]},{"id":"167ad3eb.01ac04","type":"comment","z":"19ea7c09.8e3a3c","name":"","info":"","x":760,"y":200,"wires":[]}]
```

2. Use outliner to search for `type:comment`. Outliner properly filters nodes and shows the three comment nodes in the outliner.
3. Copy and paste a fourth comment node.

### What happens?
The list in the outliner doesn't update when an active search filter is applied.

<img width="597" alt="Screen Shot 2020-06-05 at 10 24 05 AM" src="https://user-images.githubusercontent.com/1245985/83906142-e2d64100-a717-11ea-8245-0ab71e9d4e36.png">

### What do you expect to happen?

List should automatically update regardless of whether a search filter is active.

### Please tell us about your environment:

- [x] Node-RED version: 1.1.0-beta.1
- [x] Node.js version: 12.16.1
- [x] npm version: 6.14.3
- [x] Platform/OS: Raspberry Pi 3
- [x] Browser: Firefox

**Comment by knolleary** [comment]
Thanks - fixed in git.
