### ISSUE TITLE
Restart some random points

### ISSUE THREAD

**Issue by MeisterQ** [node-red/node-red#2602]
### Please tell us about your environment:

- [1.0.6] Node-RED version:
- [10.20.1] Node.js version:
- [6.14.4] npm version:
- [Raspbian] Platform/OS:
- [Firefox 76.0.1] Browser:

Hello, 

my Node-Red restarts randomly after i updated it via the installationscript like suggested.

The log from "node-red-log" shows following:

8 Jun 22:00:53 - [red] Uncaught Exception:
8 Jun 22:00:53 - Error: connect ETIMEDOUT 192.168.2.169:49000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 3.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
8 Jun 22:00:55 - [info]
Welcome to Node-RED

Whats happening there?

**Comment by knolleary** [comment]
One of the contrib nodes you have installed is missing some necessary error handling and is the cause of the crash.

The node at fault is trying to connect to 192.168.2.169:49000

If you start Node-RED in safe mode (`node-red --safe`), you should be able to open the editor and see if you can find the node in question. Delete the node and hit deploy to restart your flows.

Let us know which node you narrow it down to - we should make sure an issue is raised against it. But this isn't a core node-red issue.

**Comment by MeisterQ** [comment]
> 
> 
> One of the contrib nodes you have installed is missing some necessary error handling and is the cause of the crash.
> 
> The node at fault is trying to connect to 192.168.2.169:49000
> 
> If you start Node-RED in safe mode (`node-red --safe`), you should be able to open the editor and see if you can find the node in question. Delete the node and hit deploy to restart your flows.
> 
> Let us know which node you narrow it down to - we should make sure an issue is raised against it. But this isn't a core node-red issue.

Actually 192.168.2.168 is my Fritzbox, and after i enabled Callmonitor on IOBroker, it opend Port 49000, so the TR-064 Adapter from IOBroker and Node-Reds "node-red-contrib-presenchecker" having conflicts.

After i disabled node-red-contrib-presenchecker, its not restarting anymore. Same result if i disable IObrokers TR-064 Adapter.

Thank you that was the problem

**Comment by dceejay** [comment]
Thanks for letting us know. It may be worth adding an issue to that node - though it is over 3 years old and doesn't look to be maintained at all - so maybe more as a warning to others .
