### ISSUE TITLE
Hardcoded CSS

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#2603]
I found some hardcoded CSS here.

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/projects/projects.js#L1619-L1626

This makes creating themes a little tricky because a workaround could create unwanted changes in the UI.

**Comment by bonanitech** [comment]
![Screen Shot 2020-06-12 at 10 10 04 AM](https://user-images.githubusercontent.com/29807944/84512260-b67d7000-ac95-11ea-8d76-813371000655.png)

**Comment by bonanitech** [comment]
Found similar code in the following places.

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/subflow.js#L1169-L1171

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/subflow.js#L1199-L1203

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/subflow.js#L1347-L1349

**Comment by knolleary** [comment]
Fixed in `dev`. Thanks for reporting.
