### ISSUE TITLE
Node Status - text is null

### ISSUE THREAD

**Issue by softy2k** [node-red/node-red#2606]
If **text** is **null** in NodeStatus, Debug in Editor doesn't handle a payload will a null value.

Tested in :
-  Node-Red 1.0.5 and 1.0.6
-  NodeJS 10 and 12 (all version of 12)
-  Windows 7, 10 and Ubuntu

More details here : https://discourse.nodered.org/t/node-status-queries-about-text-is-null/28104

**Comment by knolleary** [comment]
Fixed in the `dev` branch for the 1.1 release.
