### ISSUE TITLE
auto-conversion of output of HTTPrequest node

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#261]
currently the HTTPrequest node returns a string. 

If the msg.headers.content-type of the returned body indicates that it's application/json or application/xml, could we do a JSON or XML parse in the HTTPrequest node to return a pre-parsed body?

This would save the "do I need to insert a JSON parse node or not?" ambiguity which currently has to be debugged by finding out that the payload which looks like JSON, actually isn't.

**Comment by knolleary** [comment]
The HTTP Request node includes an option for what to return. Not sure when we added it in the last 4 years... but this issue can be closed.

**Comment by andysc** [comment]
so it does! Thank you for pointing that out :)
