### ISSUE TITLE
[BUG] Using "\n" as node name is not working when the node has more than 2 outputs

### ISSUE THREAD

**Issue by machadotiago** [node-red/node-red#2614]
### What are the steps to reproduce?
- Drop a node with 3 (or more) outputs to the editor
- Name it as "123 \n 456"

### What happens?
The second line is hidden. 
![image](https://user-images.githubusercontent.com/3775353/84526549-e6d40700-acb3-11ea-9cbb-b319fe55d44c.png)

### What do you expect to happen?
Since 1.1.0 it is possible to use "\n" in the Nodes name but it is only working for nodes with 1 or 2 outputs.

### Please tell us about your environment:

- [ ] Node-RED version: v1.1.0-beta.1
- [ ] Node.js version: v12.13.1
- [ ] npm version: 6.12.1
- [ ] Platform/OS: Win 10
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Fixed in `dev` for `beta.2`
