### ISSUE TITLE
TypeError with "id" Default Field and Config Nodes

### ISSUE THREAD

**Issue by BertTheAvenger** [node-red/node-red#2620]
### What are the steps to reproduce?
After a little bit of testing, I've determined that to reproduce this error it seems you need:
1) A configuration node
2) A node that has a field for the configuration node and an "id" field in the default properties. The template only has to have a way to set the config node.

To actually reproduce, you must:
1) Install both modules so they're accessible in the editor.
2) Add the simple node to the flow.
3) Create a new configuration node using the dialog inside the simple node's properties.
4) Select the newly created config node inside the simple node's properties and attempt to exit using either "Done" or clicking outside the panel.

### What happens?
A somewhat cryptic TypeError is thrown, preventing the properties window from closing.
`
red.min.js:16 Uncaught TypeError: Cannot read property 'splice' of undefined
    at click (red.min.js:16)
    at HTMLButtonElement.<anonymous> (red.min.js:16)
    at HTMLButtonElement.dispatch (vendor.js:2)
    at HTMLButtonElement.v.handle (vendor.js:2)
`

After some investigation, it looks like the root cause is that the "user" field on the simple node's representation is undefined. This only happens if "id" is part of its defaults. If "id" (or the property for the config node) is removed, all works as expected.

### What do you expect to happen?
I expect for this combination (config node and "id" field) to be allowed, as there's nothing in the [node properties documentation](https://nodered.org/docs/creating-nodes/properties#reserved-property-names) about reserving the "id" field. 

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.6
- [ ] Node.js version: 12.18.0
- [ ] npm version: 6.13.0
- [ ] Platform/OS: Windows
- [ ] Browser: Chrome

I've attached a package with two nodes that should demonstrate the issue. I've tested it after deleting .node-red and the same behavior is produced. 

[nodes-config-dependant.zip](https://github.com/node-red/node-red/files/4794091/nodes-config-dependant.zip)

**Comment by knolleary** [comment]
`id` is one of the reserved keywords for a node's properties. I was about to share the link the list of reserved names (https://nodered.org/docs/creating-nodes/properties) but then I realised `id` isn't on that list.... it should be.

**Comment by knolleary** [comment]
Have now taken a look at your example nodes and I can confirm the issue is you cannot use `id` as the name of a node property - it is a reserved name.

I'll update the docs to expand the list (there are a few others then those listed).

**Comment by BertTheAvenger** [comment]
Awesome, thank you!
