### ISSUE TITLE
TCP In doesn't Stream Base64 messages

### ISSUE THREAD

**Issue by jeancarl** [node-red/node-red#2622]
### What are the steps to reproduce?

1) Import flow:
```
[{"id":"ffae3f16.f92168","type":"tcp in","z":"190414fd.d965d3","name":"","server":"server","host":"","port":"4448","datamode":"stream","datatype":"base64","newline":"\\n","topic":"","base64":false,"x":160,"y":1280,"wires":[["9e9cebb1.92821"]]},{"id":"9e9cebb1.92821","type":"debug","z":"190414fd.d965d3","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":310,"y":1280,"wires":[]},{"id":"f481e5d2.a1a65","type":"inject","z":"190414fd.d965d3","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"test","payloadType":"str","x":170,"y":1360,"wires":[["5ac43782.89d15"]]},{"id":"5ac43782.89d15","type":"tcp request","z":"190414fd.d965d3","server":"localhost","port":"4448","out":"immed","splitc":" ","name":"","x":350,"y":1360,"wires":[["ee5c10b.30fef7"]]},{"id":"ee5c10b.30fef7","type":"debug","z":"190414fd.d965d3","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":530,"y":1360,"wires":[]}]
```

2) Trigger inject to send data to the TCP port. 

### What happens?

The TCP In node doesn't receive data and send base64 encoded messages as a stream.

### What do you expect to happen?

The TCP In node should send a message with a base64 encoded string as a payload.

### Please tell us about your environment:

- [x] Node-RED version: 1.1.0-beta.3
- [x] Node.js version: v11.1.0
- [x] npm version: 6.4.1
- [x] Platform/OS: Mac 10.14.6
- [x] Browser: Firefox 68.9.0esr (64-bit)

**Comment by dceejay** [comment]
Yes - "streaming" mode doesn't actually make much sense for base64 if you are just sending a single small packet, you are better off just configuring it to single packets... but maybe it is the example that is too trivial...  indeed there is a bug with longer base64 messages that go over a single packet size... so yes. 
Now fixed in dev.
