### ISSUE TITLE
storageModule / Storage API doesn't provide a method for palette manager installed nodes persistence

### ISSUE THREAD

**Issue by WeekendWarrior1** [node-red/node-red#2627]
### What are the steps to reproduce?
- Run Node-RED in a container without file-system persistence (like docker)
- Install and use [node-red-contrib-storagemodule-postgres](https://github.com/WeekendWarrior1/node-red-contrib-storagemodule-postgres) for settings persistence
- Install a node through the palette manager.
- Deploy a flow with a node installed in the last step
- Reboot the container

### What happens?
Nodes installed through the palette manager no longer exist, and flows using them are broken.

### What do you expect to happen?
The storageModule should provide an interface to keep track of modules installed through the palette manager. Since installing node-modules pretty much has to be done on the filesystem, I would expect a Node-RED using a different storageModule to install the palette manager /extra nodes on boot.
At the moment I can do this by eg. adding some postgres code in `@node-red/registry/lib` to keep track of nodes installed via the palette manager, and use `@node-red/registry/lib/installer.js` to install them all on boot.
This solution however, isn't easily portable to end users, and not something I can easily package into my postgres storageModule.

I did notice that `.config.json` is basically just a list of installed nodes. If this was brought into storageModule, a custom storageModule could use it to manage installing nodes on Node-RED start.

### Please tell us about your environment:

- Node-RED version: `1.0.6`
- Node.js version: `13.12.0` 
- npm version: `6.14.5` 
- Platform/OS:  `Ubuntu/docker`

**Comment by knolleary** [comment]
The `.config.json` file is already created via the storage module - https://nodered.org/docs/api/storage/methods/#storagegetsettings

If you want Node-RED to automatically reinstall modules that are listed in its runtime settings (ie .config.json), then you can add `autoInstallModules: true` to your settings file. This is how we do it for the Node-RED image on IBM Cloud that uses a Cloudant-based storage plugin - https://github.com/IBM/node-red-app/blob/master/bluemix-settings.js#L58

**Comment by WeekendWarrior1** [comment]
Thanks Nick, will look into it.
