### ISSUE TITLE
Broken labels in Debug's open in new window 

### ISSUE THREAD

**Issue by jeancarl** [node-red/node-red#2630]
### What are the steps to reproduce?

1) Open Debug sidebar in new window
<img width="315" alt="debug-open-in-new-window" src="https://user-images.githubusercontent.com/1245985/86274925-52a8e180-bb87-11ea-989a-96735325d877.png">

### What happens?

1) Label for the all nodes button doesn't display properly:

<img width="974" alt="Screen Shot 2020-07-01 at 10 29 30 AM" src="https://user-images.githubusercontent.com/1245985/86275059-88e66100-bb87-11ea-879e-7ea08dfcb54f.png">

2) Tooltip label doesn't display properly:

<img width="318" alt="Screen Shot 2020-07-01 at 10 42 58 AM" src="https://user-images.githubusercontent.com/1245985/86275148-b0d5c480-bb87-11ea-9be7-37ec0c2f31dc.png">

3) Filters labels don't display properly:

<img width="601" alt="Screen Shot 2020-07-01 at 10 45 39 AM" src="https://user-images.githubusercontent.com/1245985/86275444-26419500-bb88-11ea-9ab7-cc99b600ec2b.png">

### What do you expect to happen?

Labels should replicate the Debug sidebar in the editor:

<img width="313" alt="Screen Shot 2020-07-01 at 10 51 50 AM" src="https://user-images.githubusercontent.com/1245985/86275989-fba40c00-bb88-11ea-9dde-b26e72773a31.png">

### Please tell us about your environment:

- [x] Node-RED version: 1.1.0
- [x] Node.js version: v12.18.1
- [x] npm version: 6.14.5
- [x] Platform/OS: Raspberry Pi 3
- [x] Browser: Firefox 68.9.0esr (64-bit)

**Comment by knolleary** [comment]
Same as #2629
