### ISSUE TITLE
Hardcoded styles

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#2633]
I was trying to change that white stroke in the group for the dark theme and found more hardcoded CSS.

<img width="1280" alt="Screen Shot 2020-07-02 at 9 59 57 AM" src="https://user-images.githubusercontent.com/29807944/86368588-59009180-bc4b-11ea-8ef5-66e46266604e.png">

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L4188

**Comment by bonanitech** [comment]
Similar lines:

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L4139-L4140

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L4201-4203

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L4313-L4316

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L4341

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/view-navigator.js#L106-L109

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/touch/radialMenu.js#L115

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/touch/radialMenu.js#L119

https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/editor-client/src/js/ui/touch/radialMenu.js#L122

I don't know if all of them need to be changed.

**Comment by knolleary** [comment]
Thanks @bonanitech. Have tidied these up. Some of those are removing style, rather than setting, so didn't need changing.

One new addition to the theme colours file - `$group-default-label-color` - the default colour of a group's label.

I've also updated the group theme logic so if any group style is set to its default value (which comes from the CSS), it won't get stored in the flow configuration. This means it will pickup the theme-provided default - useful if sharing a group between users with different themes.

**Comment by bonanitech** [comment]
Thanks for being so quick on fixing the issue and for all the details.

**Comment by knolleary** [comment]
@bonanitech I also fixed it so you don't have to be in the `scripts` directory to run ;)

**Comment by bonanitech** [comment]
> I've also updated the group theme logic so if any group style is set to its default value (which comes from the CSS), it won't get stored in the flow configuration. This means it will pickup the theme-provided default - useful if sharing a group between users with different themes.

WOW! That's awesome.

**Comment by knolleary** [comment]
Oh, one more thing... it adds a comment to the top of the CSS with the date/time and Node-RED version it was generated against.

**Comment by bonanitech** [comment]
> @bonanitech I also fixed it so you don't have to be in the `scripts` directory to run ;)

Please don't remind me of that shameful question. 😂
