### ISSUE TITLE
How do upgrade node from palette that uses git repo?

### ISSUE THREAD

**Issue by mannharleen** [node-red/node-red#2634]
Installing node from palette that is hosted on a git repo works perfectly. However, I can't figure out how the 'upgrade' feature will work? 

### What are the steps to reproduce?
- catalog.json at the start
```
...
{
            "id": "schemaValidator",
            "version": "1.0.1",
            "description": "schemaValidator",
            "updated_at": "2020-07-03T00:00:00.000Z",
            "url": ".....",
            "pkg_url": "git+https://..........schemaValidator#v1.0.1"
 },
```
- On the browser then I installed this node from the palette
- Then on the git repo of the node, I bumped the version to v1.0.2 both **in package.json and as the repo tag**
- I then edited the catalog.json to reflect the new version as:
```
...
{
            "id": "schemaValidator",
            "version": "1.0.2",
            "description": "schemaValidator",
            "updated_at": "2020-07-03T00:00:00.000Z",
            "url": ".....",
            "pkg_url": "git+https://..........schemaValidator#v1.0.2"
 },
```

### What happens?
After restarting node-red, I then go to the palette and against schemaValidator it says "1.0.2" but **rather than showing "upgrade" it shows the "installed" status**

### What do you expect to happen?
Palette should show a button to "upgrade"

### Please tell us about your environment:

- [x] Node-RED version: v1.1.0
- [x] Node.js version: v14.2.0
- [x] npm version: 6.14.4
- [x] Platform/OS: Win 10 x64
- [x] Browser: chrome

> reference: https://discourse.nodered.org/t/how-do-upgrade-node-from-palette-that-uses-git-repo/29422

**Comment by knolleary** [comment]
After updating the catalog with the new version number, you need to tell the editor to reload the catalog to spot the change.

You do that by either:

1. going to the Install tab and clicking the refresh button - 
![image](https://user-images.githubusercontent.com/51083/86785587-c3a23a80-c05a-11ea-9795-480723462e5d.png)

2. reload the editor

I've just stepped through this whole process and it worked - once you know you have to manually reload the catalog if you aren't going to reload the editor.

**Comment by mannharleen** [comment]
I refreshed the palette, and it now reflects the new verions "1.0.3" instead of "1.0.2" but the status is still "installed".

What does your catalog.json look like? Did you update the tag at the end of the repo url?

**Comment by mannharleen** [comment]
So it turns out that the option to install a new version/upgrade is displayed under the "Nodes" tab:
![image](https://user-images.githubusercontent.com/22973248/87031618-ba65c900-c226-11ea-8191-e7d82a7ee770.png)
