### ISSUE TITLE
1.1.0 regression: markdown rendering no longer encoding URLs

### ISSUE THREAD

**Issue by zosky** [node-red/node-red#2635]
congrats on reaching another awesome milestone!! groups are great
... unfortunately getting them borked my flow-descriptions

### What are the steps to reproduce?
- use static folder for serving pictures
- put some *spaces* in the filenames
- add pictures to flow description `![pix](url/to/my pix.png)`

### What happens?
- links *without* spaces work 
- links *with* spaces are no longer converted to %20
- find-replace > space for %20 > _fixed-ish_

### What do you expect to happen?
please encode markdown URLs again. 
_( any solution that does not need manually fixing 242 links across 47 flows would be great )_ 

![image](https://user-images.githubusercontent.com/112049/86484732-e19f3080-bd24-11ea-8389-ee3707104c90.png)

### Please tell us about your environment:

- [x] Node-RED version: *v1.1.0*
- [x] Node.js version: *v8.15.1*
- [x] npm version: *v6.4.1*
- [x] Platform/OS: *ubuntu xenial*
- [x] Browser: *chrome*

**Comment by knolleary** [comment]
The markdown format has never supported having spaces in link urls - in fact, a space in the url has a particular meaning allowing you to provide a Title attribute for the link. The more formalised CommonMark spec doesn't support spaces either.

Before 1.1.0, we were using a very old version of the [`marked` library](https://github.com/markedjs/marked/) for rendering the markdown. It was not following the spec properly and was allowing the spaces in the url. In 1.1.0, we updated to the latest version of marked, which addressed a number of potential security issues. It has also fixed its handling of invalid urls with spaces in.

We are not going to revert our move to the latest marked library, so I'm afraid it's unlikely this is something we can "fix".

It ought to be possible to create a script that walks through your flow file and fixes up any invalid links it finds. I'll see if I can put together something...

**Comment by knolleary** [comment]
This should do it...

Change the path in line 2 to point at your flows file.

It will print the 'fixed' flows to the console - so you will want to redirect the output to another file. It will output minified json - if you want formatted json, swap over the console.log lines at the end.

If you do run it - I strongly suggest you then diff its output with your existing flows to check its done the right thing. This script is a quick hack and it involves regular expressions - whilst it works for my brief testing, I cannot guarantee it won't cause minor earthquakes or other unexpected results. But I hope if helps.



```
const fs = require("fs");
const file = fs.readFileSync("/full/path/to/your/flows/file");
const flow = JSON.parse(file);
const newFlow = flow.map(n => {
  if (n.hasOwnProperty('info')) {
     let info = n.info;
     var m;
     const reg = /(^[\s\S]*\[[^[\]]*?\]\([^)]+) ([^)]+\)[\s\S]*$)/g;
     while((m = reg.exec(info)) != null) {
         info = m[1]+"%20"+m[2]
     }
     n.info = info;
  }
  return n;
});

// minified output
console.log(JSON.stringify(newFlow))
// formatted output
// console.log(JSON.stringify(newFlow," ", 4))
```

**Comment by zosky** [comment]
thank you for the explanation & quick reply. 

i primarily view these in the side-panel. I am also concatenating descriptions into the project's readme.md ... now i see all the same links are broken there too. 

For new ones, i will escape the string before putting markdown into the clipboard. For the rest, i really appreciate the help. ill give it a go over the weekend.
