### ISSUE TITLE
Not possible to connect wires to subflow specific nodes on Android Chrome

### ISSUE THREAD

**Issue by ristomatti** [node-red/node-red#2637]
### What are the steps to reproduce?

1. Create a subflow
2. Disconnect any wire going to subflow output
3. Open the subflow for editing on an Android device
4. Try to connect a wire from subflow input or from any "normal" node to subflow output (or subflow status)

### What happens?

Wire drawing begins but the end does not attach on the subflow special nodes. Same happens if attempting to wire in reverse starting from the output node.

### What do you expect to happen?

Connecting wires works as between regular nodes.

### Please tell us about your environment:

- [x] Node-RED version: 1.1.0
- [x] Node.js version: 14.3.0
- [x] npm version: 6.14.5
- [x] Platform/OS: Samsung Galaxy Tab S2 (Android 5.0)
- [x] Browser: Latest Chrome

**Comment by knolleary** [comment]
Fixed in 1.1.1
