### ISSUE TITLE
Cannot pan flow page in iOS/iPadOS

### ISSUE THREAD

**Issue by steve28** [node-red/node-red#2647]
Prior to 1.1 it was possible to pan around a a flow on the ipad by putting your finger on a blank area of the page and dragging.  This no longer works.
### What are the steps to reproduce?
1) Open a flow on iPad
2) Put finger on blank area
3) drag
### What happens?
nothing
### What do you expect to happen?
pan the page around
### Please tell us about your environment:

- [ ] Node-RED version: 1.1.0
- [ ] Node.js version: 10.21.0
- [ ] npm version: 6.14.4
- [ ] Platform/OS: iPadOS 13
- [ ] Browser: Safari

**Comment by bdormael** [comment]
I can confirm I have the same issue on my iPad Pro

**Comment by knolleary** [comment]
Fixed in just-released 1.1.2
