### ISSUE TITLE
Editor Changes in V 1.1.x - causes problems for other nodes (light scheduler)

### ISSUE THREAD

**Issue by mickym2** [node-red/node-red#2650]
The problem is that my light-scheduler Nodes are no longer editable. It happens since the editor changes - the nodes itself are working without problems. 

I opened an issue to the developer of the node. However I think it is related to the changes of the GUI of the editor.

https://github.com/niklaswall/node-red-contrib-light-scheduler/issues/52

### What are the steps to reproduce?
Add a light-scheduler node - and try to add a schedule.

### What happens?
bars cannot be edited, defined ...

### What do you expect to happen?
it should work as in node Red version 1.0.2

### Please tell us about your environment:

- [x ] Node-RED version: 1.1.2 back to 1.0.2
- [x] Node.js version: 12.18.2
- [ x] npm version: 6.14.5
- [x ] Platform/OS: Buster
- [x ] Browser: Chrome, Edge

**Comment by knolleary** [comment]
Have you checked the browsers JavaScript console for any errors?

**Comment by mickym2** [comment]
I am not the developer of these nodes: I got the following errors - but I am not sure if they are related to this issue (using Chrome):


vendor.js:4 JQMIGRATE: Migrate is installed, version 3.3.0
red.min.js:16 Node-RED: 1.1.0
red.min.js:16 Versions
red.min.js:16 jQuery 3.5.1
red.min.js:16 jQuery UI 1.12.1
red.min.js:16 ACE 1.4.3
red.min.js:16 D3 3.0.3
DevTools failed to load SourceMap: Could not load content for http://server.fritz.box:1880/vendor/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
2
DevTools failed to load SourceMap: Could not load content for http://server.fritz.box:1880/gridstack.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by xbonnaire** [comment]
> The problem is that my light-scheduler Nodes are no longer editable. It happens since the editor changes - the nodes itself are working without problems.

I have the same issue with the light-scheduler node. I cannot edit the node settings (schedule bars). It was perfectly working before my last Node-Red update. I don't know if it is the only node affected by this update.

There are the following error in the JavaScript console:
vendor.js:4 JQMIGRATE: Migrate is installed, version 3.3.0
red.min.js:16 Node-RED: 1.1.0
red.min.js:16 Versions
red.min.js:16 jQuery 3.5.1
red.min.js:16 jQuery UI 1.12.1
red.min.js:16 ACE 1.4.3
red.min.js:16 D3 3.0.3
red.min.js:16 Projects disabled
(unknown) [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
oneditprepare
2api/hassio_ingress/2kpd8wopYCJDUobJ-OxNym8s8rFjuMxdhAoU1VkRXoo/nodes/node-red-contrib-light-scheduler:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
red.min.js:16 Uncaught ReferenceError: id is not defined
api/hassio_ingress/2kpd8wopYCJDUobJ-OxNym8s8rFjuMxdhAoU1VkRXoo/nodes/node-red-contrib-light-scheduler:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
api/hassio_ingress/2kpd8wopYCJDUobJ-OxNym8s8rFjuMxdhAoU1VkRXoo/#flow/cef82113.6a6f5:7 Uncaught TypeError: Cannot read property 'event' of undefined
vendor.js:4 JQMIGRATE: Migrate is installed, version 3.3.0
red.min.js:16 Node-RED: 1.1.0
red.min.js:16 Versions
red.min.js:16 jQuery 3.5.1
red.min.js:16 jQuery UI 1.12.1
red.min.js:16 ACE 1.4.3
red.min.js:16 D3 3.0.3
red.min.js:16 Projects disabled
auth/token:1 Failed to load resource: net::ERR_NETWORK_CHANGED
vendor.js:4 JQMIGRATE: Migrate is installed, version 3.3.0
red.min.js:16 Node-RED: 1.1.0
red.min.js:16 Versions
red.min.js:16 jQuery 3.5.1
red.min.js:16 jQuery UI 1.12.1
red.min.js:16 ACE 1.4.3
red.min.js:16 D3 3.0.3
red.min.js:16 Projects disabled
DevTools failed to load SourceMap: Could not load content for http://192.168.1.32:8123/api/hassio_ingress/2kpd8wopYCJDUobJ-OxNym8s8rFjuMxdhAoU1VkRXoo/vendor/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM1590:7 Uncaught TypeError: Cannot read property 'event' of undefined
    at HTMLDivElement.<anonymous> (<anonymous>:7:22874)
    at Function.each (vendor.js:2)
    at s.fn.init.each (vendor.js:2)
    at Et.e.constructor.renderFgSegEls (<anonymous>:7:22823)
    at Et.e.constructor.renderFgSegsIntoContainers (<anonymous>:8:26181)
    at Et.e.constructor.renderFgSegs (<anonymous>:8:24463)
    at Et.e.constructor.renderFgEvents (<anonymous>:7:22441)
    at Et.e.constructor.renderEvents (<anonymous>:7:22269)
    at Et.e.constructor.renderEvents (<anonymous>:10:12003)
    at Et.e.constructor.executeEventsRender (<anonymous>:9:5168)
(anonymous) @ VM1590:7
each @ vendor.js:2
each @ vendor.js:2
renderFgSegEls @ VM1590:7
renderFgSegsIntoContainers @ VM1590:8
renderFgSegs @ VM1590:8
renderFgEvents @ VM1590:7
renderEvents @ VM1590:7
renderEvents @ VM1590:10
executeEventsRender @ VM1590:9
(anonymous) @ VM1590:9
runTaskFunc @ VM1590:6
runTask @ VM1590:6
runNext @ VM1590:6
e @ VM1590:6
runTaskFunc @ VM1590:6
runTask @ VM1590:6
runNext @ VM1590:6
tryStart @ VM1590:6
resume @ VM1590:6
stopBatchRender @ VM1590:8
resetEvents @ VM1590:9
i @ vendor.js:2
n @ VM1590:6
dispatch @ vendor.js:2
v.handle @ vendor.js:2
trigger @ vendor.js:2
triggerHandler @ vendor.js:2
trigger @ VM1590:7
i @ VM1590:6
M @ VM1590:6
k @ VM1590:6
(anonymous) @ VM1590:6
each @ vendor.js:2
each @ vendor.js:2
t.fn.fullCalendar @ VM1590:6
select @ VM1577:114
publiclyTrigger @ VM1590:9
publiclyTrigger @ VM1590:8
triggerSelect @ VM1590:9
reportSelection @ VM1590:9
interactionEnd @ VM1590:7
trigger @ VM1590:7
handleInteractionEnd @ VM1590:7
handleInteractionEnd @ VM1590:7
endInteraction @ VM1590:7
i @ vendor.js:2
n @ VM1590:6
dispatch @ vendor.js:2
v.handle @ vendor.js:2
trigger @ vendor.js:2
triggerHandler @ vendor.js:2
trigger @ VM1590:7
handleMouseUp @ VM1590:7
i @ vendor.js:2
dispatch @ vendor.js:2
v.handle @ vendor.js:2
Show 27 more frames

The following error is a major problem for me:
(unknown) [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

As I only run Home Assistant (hassio) on my local network and use The NabuCasa service for the Google Assistant integration, I do not have the need to run it using HTTPS (this is not possible so far with hassio).

Node-Red: 1.1.0 (Home Assistant Add-on version 7.0.0)

**Comment by knolleary** [comment]
Looks like the node in question has been updated and a new version published.

Looking at the code changes, I _think_ the node was using an internal property set by the older version of jQuery... so was going to break at some point regardless.

**Comment by xbonnaire** [comment]
> Looks like the node in question has been updated and a new version published.
> 
> Looking at the code changes, I _think_ the node was using an internal property set by the older version of jQuery... so was going to break at some point regardless.

Thanks for the information, the light scheduler node has been update to version 0.0.16 and it's now working fine for me :-) Anyway, Node-Red is the best add-on for Home Assistant. It makes automations so much easier :-))) Great Job!

**Comment by mickym2** [comment]
Problem solved - thanks for your support.
