### ISSUE TITLE
Host key verification failed - working with Projects

### ISSUE THREAD

**Issue by mmick08** [node-red/node-red#2654]
### What are the steps to reproduce?

- Projects enabled
- Git over SSH configured (using intranet bitbucket)

### What happens?

after container restart we are getting "Host key verification failed. - The repository host key could not be verified. Please update your known_hosts file and try again." Error when trying to push/pull git.
it seems that it is necessary to maintain known_hosts file but that's not possible in openshift/docker environment. 
As sometimes the GIT Repository is also hosted by a company within the intranet the host-key changes from time to time.

Therefore it should be possible to set **StrictHostKeyChecking no** somewhere in the Container Environment.

### What do you expect to happen?

it should be possible to use GIT Integration within projects without maintenance of known_hosts file.

### Please tell us about your environment:

- [ ] Node-RED version: v1.1.0 (latest container image)
- [ ] Node.js version: 
- [ ] npm version: 6.14.4 (latest container image)
- [ ] Platform/OS: official container image hosted on openshift platform
- [ ] Browser: Edge Chromium

**Comment by hardillb** [comment]
First, this really should have been raised against the [docker](https://github.com/node-red/node-red-docker) project not the main project.

And no, host-keys should not "change from time to time", if they change you should have to do something explicitly about it as it should be a sign of a major security issue.

**Comment by mmick08** [comment]
thanks for the hint i will migrate this issue over to the docker project...

**Comment by hardillb** [comment]
https://github.com/node-red/node-red-docker/issues/191
