### ISSUE TITLE
Projects - git credential changes

### ISSUE THREAD

**Issue by thechane** [node-red/node-red#2656]
### What are the steps to reproduce?

1. Clone a git repository into projects dir (https not ssh) with a username and password.
2. git --git-dir=data/projects/whatever/.git remote set-url origin https://somewhere.com/project.git/
3. git --git-dir=data/projects/whatever/.git branch --set-upstream-to=origin/master
4. Open that project.
5. See that project in the projects panel, make updates, commit and push - no problems, everything works. 
6. Change git password (in github / bitbucket / whatever - not nodered).
7. Make a change, commit in the projects panel.
8. Try to push to remote again.

### What happens?
​Code is not pushed and no visible error produced, in the browser console:

code: "unexpected_error"
message: "fatal: Authentication failed for 'https://somewhere.com/project.git/'\n"

### What do you expect to happen?
Prompt for new username and password.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.6
- [ ] Node.js version: 12.16.3
- [ ] npm version: 6.14.4
- [ ] Platform/OS: Alpine Linux (node:12-alpine so alpine:3.11)
- [ ] Browser: Firefox 78.0.2

**Comment by knolleary** [comment]
We have code that looks for all the different ways the git client can report back that the authentication has failed so we can set the response code to `git_auth_failed` which will cause the Editor to prompt the user to reenter their credentials.

https://github.com/node-red/node-red/blob/a9d1a64c32a0a933c2b257498aaaefc83c7e4462/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/projects/git/index.js#L47-L53

Need to reproduce this so we can see the full text being returned by the client, and then see why it isn't being caught by the existing code and add a rule for it.

**Comment by knolleary** [comment]
I've just tried reproducing this with gitlab (I run it locally for ease of testing) - and couldn't reproduce. After changing me password, NR correctly parsed the error and prompted me to re-enter my details.

What hosted git environment are you hitting this with? You mention both GitHub and BitBucket - have you reproduced against both of those?

**Comment by knolleary** [comment]
If you set your log level to `debug` in your settings file, then you should see the response from the git command when the authentication fails. Something like:

```
    31 Jul 16:17:57 - [debug] git -c credential.helper= push origin HEAD:master --porcelain
    31 Jul 16:17:58 - [debug] [err] remote: HTTP Basic: Access denied
    31 Jul 16:17:58 - [debug] [err] fatal: Authentication failed for 'http://localhost:8929/root/nr-project-7.git/'
    31 Jul 16:17:58 - [debug] rc=128
```

The output above works because we look for the `HTTP Basic: Access denied` bit.

It would be helpful if you can provide the output when you hit this issue.

**Comment by thechane** [comment]
Sure thing, I have just reproduced with bitbucket. Working:

```
2 Aug 17:34:35 - [debug] git -c credential.helper= push origin HEAD:master --porcelain
2 Aug 17:34:44 - [debug] [out] To https://bitbucket.org/thechane/nodered.git
2 Aug 17:34:44 - [debug] [out]  	HEAD:refs/heads/master	349bede..8369b6d
2 Aug 17:34:44 - [debug] [out] Done
2 Aug 17:34:44 - [debug] rc=0
```

Change my [Atlassian account password](https://id.atlassian.com/manage-profile/security) and:

```
2 Aug 17:36:53 - [debug] git -c credential.helper= push origin HEAD:master --porcelain
2 Aug 17:36:54 - [debug] [err] remote: Invalid username or password
2 Aug 17:36:54 - [debug] [err] fatal: Authentication failed for 'https://bitbucket.org/thechane/nodered.git/'
2 Aug 17:36:54 - [debug] rc=128
```

This is a private repository. Thanks again for looking into this.

**Comment by thechane** [comment]
I'm now reproducing in a private GitHub repo, but it's not quite the same. After changing my password I do not see anything in the debugging only this popup when I try to select the remote branch:

```
An unexpected error occurred:
remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/thechane/nodered.git/'
code: unexpected_error
```

... in the browser console I see:

```
code: "unexpected_error"
message: "remote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/thechane/nodered.git/'\n"
remote: "origin"
```

**Comment by knolleary** [comment]
I've added `Authentication failed` to the list of things we look for. Let's see if that does it when 1.1.3 is released, or you could try patching your local copy with the two line change - https://github.com/node-red/node-red/commit/e691b1b7c32e5c1524f12799bb8588ce3252744c
