### ISSUE TITLE
Confusing german translation bug

### ISSUE THREAD

**Issue by aunwin** [node-red/node-red#2660]
## What are the steps to reproduce?

Install node red on german language settings
Drag a "Change" Node to the flow
Open it's configurations

### What happens?

The english version of `set msg.payload **to** <foo>` is translated into german as "`Festlegen msg.payload **bis** <foo>`

### What do you expect to happen?
The correct translation would be:
"`Festlegen msg.payload **auf** <foo>`

### Please tell us about your environment:

- [ ] Node-RED version:1.0.6
- [ ] Node.js version: v8.10.0
- [ ] npm version: 3.5.2
- [ ] Platform/OS: Ubuntu 18_04
- [ ] Browser: Firefox 78.0.2 (64-Bit)

**Comment by knolleary** [comment]
Happy to accept a pull request with the update it - just need to get it peer-reviewed about another native German speaker as we can't assess this sort of change ourselves.

**Comment by HLeithner** [comment]
It's better but still wrong in my opinion, it should be `Festlegen **von** msg.payload **auf** <foo>`

**Comment by hobbyquaker** [comment]
https://github.com/node-red/node-red/pull/2666
