### ISSUE TITLE
Flows UI Frontend: Debug sidebar not working in Safari

### ISSUE THREAD

**Issue by jmojico** [node-red/node-red#2687]
### What are the steps to reproduce?
Create Inject node, put some data in payload, connect to a debug node and start the flow.

### What happens?
No data/messages shown in the debug sidebar.

### What do you expect to happen?
Messages should be shown in the debug sidebar.

### Please tell us about your environment:

- [X] Node-RED version: v1.1.2
- [ ] Node.js version:
- [ ] npm version:
- [X] Platform/OS: OSx Catalina (10.15.6)
- [X] Browser: Safari 13.1.2

**Comment by knolleary** [comment]
It is working fine for me here.

Are there any errors in the Node-RED log or the browser's developer console?

Is Node-RED running on the same machine as the browser?

**Comment by jmojico** [comment]
> It is working fine for me here.
> 
> Are there any errors in the Node-RED log or the browser's developer console?
> 
> Is Node-RED running on the same machine as the browser?

Node-Red is running in Google Cloud. 
I login with my MacBook Pro in Safari to node-red admin UI, then put some debug nodes, toggle the debug sidebar (this works fine), but after triggering the flow, **nothing shows in the Debug sidebard.**.

Replicating the previous in Chrome, it works as expected and I can see debugging messages.

Let me know if you need any info/testing that can be of help.

**Comment by knolleary** [comment]
As I asked before, are there any errors in the browser's developer console?

**Comment by jmojico** [comment]
I tried again, the messages are working as expected now .... Weird.
Maybe my session was finished but Safari did not handled properly. (so it seems you are still logged in, but you don't)
This is a a very common issue in Safari.

Anyway, thanks for the support anyway.
