### ISSUE TITLE
Configure list of CORS origins

### ISSUE THREAD

**Issue by mu3** [node-red/node-red#2688]
### What happens?

Currently, `httpNodeCors` option in [Settings](https://nodered.org/docs/user-guide/runtime/configuration) supports specifying only 1 domain:

    httpNodeCors: {
      origin: "https://example.com",
    }

### What do you expect to happen?

    httpNodeCors: {
      origin: ["https://example.com", "http://localhost:3000"],
    }

### Please tell us about your environment:

- [ ] Node-RED version: 1.1.3

**Comment by knolleary** [comment]
Please use the issue template you are given when raising an issue.

As it stands, it is not clear what issue you are reporting.

**Comment by hardillb** [comment]
But the first 2 lines of the template given when you pick "Anything Else" does ask you not to use issues to make feature requests and directs you to the Node-RED forum or Slack team.

> Please DO NOT raise an issue.
> 
> We DO NOT use the issue tracker for general support or feature requests. Only bug reports should be raised here using the 'Bug report' template.

**Comment by knolleary** [comment]
Hi @mu3

as @hardillb has pointed out, the 'Anything Else' option is there to explicitly point people to the forum for feature requests. We do not use this issue tracker for that.

As for your specific request, you link to the docs for the `httpNodeCors` setting here: https://nodered.org/docs/user-guide/runtime/configuration. From there we link to the docs for the underlying cors module we use - which gives full details on the options in supports: https://github.com/expressjs/cors#configuration-options

Those docs show that it already supports the `origin` property being an array of valid origins:

> Array - set origin to an array of valid origins. Each origin can be a String or a RegExp. For example ["http://example1.com", /\.example2\.com$/] will accept any request from "http://example1.com" or from a subdomain of "example2.com".
