### ISSUE TITLE
Bump nodes mqtt dependency from 2.18.8 - Current version is 4.2.1 - Getting deprecated warning

### ISSUE THREAD

**Issue by scottpageindysoft** [node-red/node-red#2694]
### What are the steps to reproduce?
- Start node-red
- Observe log while node-red is starting

### What happens?
Warning logged `(node:7223) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

### What do you expect to happen?
No warning

### Please tell us about your environment:
- [x] Node-RED version: 1.1.3-git (embedded)
- [x] Node.js version: 14.4.0
- [x] npm version: 6.14.5
- [x] Platform/OS: Any
- [x] Browser: Chrome

### Resolution
Update mqtt dependency in nodes/package.json.  node-red uses 2.18.8 and the current version of mqtt.js is 4.2.1

**Comment by hardillb** [comment]
Does MQTT.JS version 4.2.1 still support  NodeJS version v8? (https://nodered.org/docs/faq/node-versions)

**Comment by knolleary** [comment]
Updating the MQTT dependency had been on the to-do list for ages. Just need to figure out what two major version bumps means in terms of any breaking changes.

**Comment by knolleary** [comment]
I've updated this dependency in the `dev` branch for the 1.2 release.
