### ISSUE TITLE
null instead of undefined

### ISSUE THREAD

**Issue by Daneev** [node-red/node-red#2696]
Good day.

```
const set = [];
set.push (undefined)
msg.payload = [... set];
return msg;
```

the result is null
msg.payload: array [1]
[null]
Why not undefined?

The same code in the browser:
```
const set = [];
set.push (undefined)
1
[... set]
[undefined]
```

Regards, Yuri.

- [ ] Node-RED version: 1.1.3
- [ ] Node.js version: 14.7.0
- [ ] npm version: 6.14.7
- [ ] Platform/OS: Win10Pro2004-19041.450
- [ ] Browser: Chrome 85.0.4183.83

**Comment by knolleary** [comment]
Link to discourse discussion for context: https://discourse.nodered.org/t/null-instead-of-undefined/32490

The value is undefined as expected, but the Debug sidebar incorrectly displays it as `null` instead. So this is an issue with the Debug sidebar's display of the data, not the actual value.

**Comment by Daneev** [comment]
an error at the output of the function and can affect the further logic of the process.

**Comment by Daneev** [comment]
`[{"id":"4290dec2.c896d","type":"inject","z":"b51d87d0.c86408","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":1420,"wires":[["ffef1f99.e3147"]]},{"id":"ffef1f99.e3147","type":"function","z":"b51d87d0.c86408","name":"","func":"var set = new Set();\nset.add(undefined);\nmsg.payload = [...set];\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":400,"y":1420,"wires":[["a03fb66f.8b2a68"]]},{"id":"d9c498c9.9c4988","type":"debug","z":"b51d87d0.c86408","name":"yes","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":810,"y":1380,"wires":[]},{"id":"a03fb66f.8b2a68","type":"switch","z":"b51d87d0.c86408","name":"is of type undefined?","property":"payload","propertyType":"msg","rules":[{"t":"istype","v":"undefined","vt":"undefined"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":600,"y":1420,"wires":[["d9c498c9.9c4988"],["d0a30f32.cf1b3"]],"outputLabels":["yes","no"]},{"id":"d0a30f32.cf1b3","type":"debug","z":"b51d87d0.c86408","name":"no","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":810,"y":1460,"wires":[]},{"id":"a17fdd37.62873","type":"inject","z":"b51d87d0.c86408","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":1480,"wires":[["5afb409a.c968b"]]},{"id":"5afb409a.c968b","type":"function","z":"b51d87d0.c86408","name":"undefined","func":"node.send({payload: undefined});","outputs":1,"noerr":0,"initialize":"","finalize":"","x":400,"y":1480,"wires":[["a03fb66f.8b2a68"]]}]`

**Comment by knolleary** [comment]
It isn't about whether it looks pretty. It is a bug in the Debug sidebar that needs fixing. Thank you for raising this issue so it can be resolved.

To be clear, it is just a bug in the debug display and the logic in your flow should not be affected.

**Comment by dceejay** [comment]
Just to add to this - if msg.payload contains a property undefined - that is also not shown.
(shows OK in console as `{ foo: undefined }`

Test case with array, object and undefined msg.
```
[{"id":"fee19045.8e25","type":"inject","z":"7bb573e4.96f29c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":820,"wires":[["d811f9b9.451928"]]},{"id":"d811f9b9.451928","type":"function","z":"7bb573e4.96f29c","name":"array with undefined","func":"msg.payload = []\nmsg.payload.push(undefined);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":340,"y":820,"wires":[["dd647ff7.4aa6"]]},{"id":"dd647ff7.4aa6","type":"debug","z":"7bb573e4.96f29c","name":"","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":580,"y":860,"wires":[]},{"id":"84adab04.2bb1d8","type":"function","z":"7bb573e4.96f29c","name":"msg.payload undefined","func":"msg.payload = undefined;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":350,"y":860,"wires":[["dd647ff7.4aa6"]]},{"id":"9a7e2b87.d52938","type":"function","z":"7bb573e4.96f29c","name":"object with undefined","func":"msg.payload = {foo:undefined}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":340,"y":900,"wires":[["dd647ff7.4aa6"]]},{"id":"88b042d.a88cbc","type":"inject","z":"7bb573e4.96f29c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":860,"wires":[["84adab04.2bb1d8"]]},{"id":"f8f1ead4.102618","type":"inject","z":"7bb573e4.96f29c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":900,"wires":[["9a7e2b87.d52938"]]}]
```

**Comment by Steve-Mcl** [comment]
Hi All, just a note - the status of the debug node does indeed show correct information (same as the console) - only the debug output differs.

Hope that is of some use?

![image](https://user-images.githubusercontent.com/44235289/92373023-a4289c00-f0f5-11ea-8936-1c0d387bcaf5.png)

**Comment by Daneev** [comment]
Yes of course. We've already figured it out.
The question is that the output in the NR console will need to be modified so that its values correspond to the output of the system console.
