### ISSUE TITLE
Not possible to use all the Font awesome icons on custom node.

### ISSUE THREAD

**Issue by simonradier** [node-red/node-red#2699]
Dear Node-Red team,

I'm working on the development of the custom node and I wanted to use the Font Awesome icons. I used the exemple provided in the documentation. I tried the value `icon : "font-awesome/fa-automobile"`  which works ![image](https://user-images.githubusercontent.com/1102782/93481149-87167900-f8fe-11ea-8274-3ef763d956c0.png). If I check the html code in the flow I see the following code :
```
<g class="red-ui-flow-node-icon-group" x="0" y="0" transform="" style="pointer-events: none;">
    <rect x="0" y="0" class="red-ui-flow-node-icon-shade" width="30" height="30"></rect>
    <path d="M 30 1 l 0 28" class="red-ui-flow-node-icon-shade-border"></path>
    <text xlink:href="font-awesome/fa-automobile" class="fa-lg" x="15" y="21.5"></text>
</g>
```
But if I put the value `icon : "font-awesome/fa-chrome"`, it use a fallback icon based on "arrow-in" svg. ![image](https://user-images.githubusercontent.com/1102782/93481341-be852580-f8fe-11ea-8a6f-6536c68193d3.png). I can find the following html code in the flow view :
```
<g class="red-ui-flow-node-icon-group" x="0" y="0" transform="" style="pointer-events: none;">
    <rect x="0" y="0" class="red-ui-flow-node-icon-shade" width="30" height="30"></rect>
    <path d="M 30 1 l 0 28" class="red-ui-flow-node-icon-shade-border"></path>
    <image xlink:href="icons/node-red/arrow-in.svg" class="red-ui-flow-node-icon" x="0" width="30" height="30" y="0" style=""></image>
</g>

```
I checked the html code on the side view as well : 
![image](https://user-images.githubusercontent.com/1102782/93482689-46b7fa80-f900-11ea-9102-24b93e607c53.png)
For the `fa-automobile`, I have
```
<div class="red-ui-palette-icon-container">
    <i class="red-ui-palette-icon-fa fa fa-fw fa-lg fa-automobile"></i>
</div>
```
If i edit the class field on the browser, I can have the correct icon on the info view. 
![image](https://user-images.githubusercontent.com/1102782/93483482-2177bc00-f901-11ea-9d26-1deb999149a9.png)

For the 'fa-chrome', I have
```
<div class="red-ui-palette-icon-container">
    <div class="red-ui-palette-icon" style="background-image: url(&quot;icons/node-red/arrow-in.svg&quot;);">
</div></div>
```

### What are the steps to reproduce?
Set up the icon value to `icon : "font-awesome/chrome"`

### What happens?
Font Awesome icon is not used.

### What do you expect to happen?
Font Awesome icon should appear as the target icon for the node.

### Please tell us about your environment:

- [ ] Node-RED version: 1.1.3
- [ ] Node.js version: 14.4.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Ubuntu LTS 20.4
- [ ] Browser: Chrome 85

__Thanks for your help on this topic and the great job you did on the development of Node-Red!__

**Comment by knolleary** [comment]
`fa-chrome` is part of the 'brand' icon set in [Font Awesome 4.7](https://fontawesome.com/v4.7.0/icons/)

We chose to restrict their usage to avoid any potential trademark issues by what is provided in the core of Node-RED.

**Comment by simonradier** [comment]
Arf, clear and understood. In this case, how should I put (and how can I call them) custom icons in the my custom node folder (if I want to support these icons)? I haven't found any information in the documentation.

Best regards,
