### ISSUE TITLE
Incorrect syntax highlighting in the JSONata Expression editor in the change node.

### ISSUE THREAD

**Issue by janvda** [node-red/node-red#2701]
### What are the steps to reproduce?

```
[{"id":"e9e09a72.fc9348","type":"change","z":"bfd23e84.79e77","name":"bad syntax highlighting","rules":[{"t":"set","p":"cases","pt":"msg","to":"/* returns an array of\t     { \"x\" : date_in_ms,\t       \"y\" : average_number_of_cases }\t*/\t( $subset := COVID19BE_CASES_AGESEX[     PROVINCE = $$.PROVINCE \t                                      and AGEGROUP = $$.AGEGROUP\t                                      and SEX      = $$.SEX].{ \"date_int\" : $toMillis(DATE)/(24*60*60*1000),\t                                                               \"cases\"  : CASES};\t  $first_day := $subset.date_int~>$min();\t  $last_day := $subset.date_int~>$max();\t  [ $first_day ..  ( $last_day -AVERAGE_PERIOD+1)].(\t      $start_period :=$;\t      $end_period   :=$start_period + $$.AVERAGE_PERIOD -1;\t      $sum_cases    := $subset[ date_int >= $start_period and date_int <= $end_period].cases~>$sum();\t      {\t     \"x\" : ($start_period + $end_period )*24*60*60*1000/2,\t     \"y\" :$sum_cases~>$exists()?$sum_cases/($$.AVERAGE_PERIOD): 0\t     })\t)","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":350,"y":520,"wires":[[]]}]
```

### What happens?

![image](https://user-images.githubusercontent.com/17238398/93705908-accf9800-fb21-11ea-8e5f-3ef92b23523d.png)

### What do you expect to happen?

From the end of line 7 up to the end of line 16 is highlighted as comment.  This is not correct.

The `/` is apparently interpreted as the start or end of the comment.  Which is not always correct.  `/` can also mean the "division operator".  Only `/*` and `*/`should be considered the start and end of a comment.

### Please tell us about your environment:

- [x] Node-RED version: v1.1.3 
- [x] Node.js version: v12.18.3 
- [x] npm version: 6.14.6
- [x] Platform/OS: Linux 4.18.0-193.6.3.el8_2.x86_64 x64 LE
- [x] Browser: chrome

**Comment by knolleary** [comment]
Have pushed a fix to the `dev` branch.

The syntax highlighting mode had no support for comments at all (as its a relatively new addition to JSONata). What you were seeing was an issue with the regular expression highlighting - any section starting with a `/` was being identified as a regex - including the comment block at the start.

It needed some additional logic to prevent it mistaking a divide for the start of a regex. Thankfully the existing JavaScript highlight mode showed me the way to disambiguate the two.

I've also added support for `/* ... */` comments, and fixed up some highlighting of variables that contain a known function name (eg `$sum_cases` was getting `$sum` highlighted as a known function).

Here's what it looks like with the fixes:

![image](https://user-images.githubusercontent.com/51083/93759297-d829b400-fc01-11ea-9bf9-9d4d71fd4e4f.png)
