### ISSUE TITLE
npm install -g node-red , success on node-v10, fail on node-v12,node-v14 (node.bcrypt.js not found)

### ISSUE THREAD

**Issue by shuimugan** [node-red/node-red#2702]
- [ ] Node-RED version:1.1.3
- [ ] Node.js version:12,14
- [ ] npm version:6.14.7
- [ ] Platform/OS:Debian,Manjaro

if use Node.js v14, run ` sudo npm install -g --unsafe-perm node-red` 
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v83-linux-x64-glibc.tar.gz 

if use Node.js v12 , run ` sudo npm install -g --unsafe-perm node-red` 
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz 

And I see https://github.com/kelektiv/node.bcrypt.js/releases/ v3.0.6 ,not exist bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz  
and bcrypt_lib-v3.0.6-node-v83-linux-x64-glibc.tar.gz

**Comment by hardillb** [comment]
Those are just warnings not errors.

It will fall back to use the pure NodeJS version of bcrypt rather than the quicker native version.

**Comment by knolleary** [comment]
Hi,

this is not an issue with Node-RED.

We have an *optional* dependency on the `bcrypt` module that includes a binary component. They only pre-build that binary component for certain combinations of node.js and platform. If a pre-build binary is not found, it will attempt to compile the binary from source. If *that* also fails, then it won't install `bcrypt` and it will fall back to the pure JavaScript implementation in the `bcryptjs` module.

None of that will cause the install to fail.

**Comment by luixal** [comment]
Related to this thread, could bcrypt (the optional dependency) be updated to version 5?

Prior versions seem to have some security issues and github keeps complaining when publishing a package due to that dep.

**Comment by knolleary** [comment]
Not without doing a major version change of Node-RED itself - the latest bcrypt drops support for node 8.

The specific vulnerability with the bcrypt module is not relevant to how Node-RED uses it. Unfortunately the tools are too crude for us to use that knowledge to stop it flagging us.

But that is all unrelated to the issue you have commented on. If you want to discuss further, please do on the forum.
