### ISSUE TITLE
Change node JSONata editor display

### ISSUE THREAD

**Issue by E1cid** [node-red/node-red#2720]

**Comment by knolleary** [comment]
@E1cid yes, the syntax highlighting has been fixed in 1.2 to handle the division symbol and regular expressions.

A note for the future - please remember to use the issue template we provide when raising an issues. Thanks.

**Comment by E1cid** [comment]
@knolleary, due to my physical handicap typing is extremely difficult at times. You will have to forgive me if i take a shorter route.

**Comment by dceejay** [comment]
no problem - but we probably then have to come back and ask for the info anyway....  so it just takes longer all round.
(unless you close the issue of course :-)

**Comment by E1cid** [comment]
I try to put all info just abrievated to make easier. Of course i would attempt to answer follow ups if there is confussion.
