### ISSUE TITLE
Node-RED has forgotten about my projects after upgrading to 1.2.0

### ISSUE THREAD

**Issue by fvbommel** [node-red/node-red#2724]
### What are the steps to reproduce?
1. Use the projects feature in a previous version of Node-RED.
2. Upgrade to Node-RED 1.2.0 using the [Raspberry Pi script](https://nodered.org/docs/getting-started/raspberrypi).
   * Lightly modified to run Node-RED under a dedicated `nodered` user, but that may not be relevant.

### What happens?
When I started the new version of Node-RED it didn't know about my projects anymore, so it offered to create a new one or open an existing one. Opening an existing one worked but did not restore the credentials.

(I was able to fix this by manually copying the projects data from `.config.json` to `.config.projects.json`, but that should have been automatic, shouldn't it?)

### What do you expect to happen?
After the upgrade, it should open the same project that was opened before, and the credentials should still be present.

### Please tell us about your environment:

- [ ] Node-RED version: 1.1.3 (I *think*, but I'm not 100% sure) => 1.2.0
- [ ] Node.js version: v12.16.3
- [ ] npm version: 6.14.8
- [ ] Platform/OS: x64 / Linux Mint 18.3 Sylvia
- [ ] Browser: Firefox 81.0

**Comment by knolleary** [comment]
Thanks @fvbommel  - I've just identified a race condition that causes this. 1.2.1 being published shortly.

**Comment by fvbommel** [comment]
Well, that was quick :)
