### ISSUE TITLE
Button texts occasionally don't show

### ISSUE THREAD

**Issue by stofferr** [node-red/node-red#2725]
I use the buttons for several of my lights. In the dashboard page they show up and functionally work, so icons, messages received and sent do work, however occasionally, the button texts don't show.

### What are the steps to reproduce?
- I can trigger the issue usually by moving to another flow, and then come back to the flow with the buttons.

### What happens?
- button texts do not show

### What do you expect to happen?
- visible button texts
- I can solve the issue by refreshing the page (F5 in windows)

### Please tell us about your environment:

- [ ] Node-RED version: 2.23.4 / Editor 1.1.3
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS: Android 8+10, Windows 10
- [ ] Browser: Chrome, FullyAndroid, Edge
- Docker image nodered/node-red

**Comment by hardillb** [comment]
This repo is specifically for issue with the core of Node-RED. This sounds like you should be raising it against the node-red-dashboard project.

**Comment by stofferr** [comment]
You're right, apologies I will close.
