### ISSUE TITLE
Restart Flows option does not work - "runtime.flows.loadFlows is not a function"

### ISSUE THREAD

**Issue by cakefornoreason** [node-red/node-red#2726]
### What are the steps to reproduce?
1. Click the down arrow menu on the "Deploy" button in the upper right corner of the Node-Red interface
2. Select "Restart Flows"

### What happens?
The flow does not restart, and instead the error "Deploy failed: {"code":"unexpected_error","message":"runtime.flows.loadFlows is not a function"}" is shown in the popup area that appears at the top of the screen in the middle.

### What do you expect to happen?
Previously, the "Restart Flows" option has worked as expected, restarting my flows when clicked.

### Please tell us about your environment:
Reproduced in two separate Node Red instances using both the RPi Chromium browser on the server itself and Safari from an independent Mac on the same network. The two node red instances have different sets of third-party nodes installed, but do have at least two in common: node-red-contrib-node-lifx, and node-red-contrib-darksky.

Node-Red Server 1 =====
- [ ] Node-RED version:
v1.2.1
- [ ] Node.js version:
v12.19.0
- [ ] npm version:
v6.4.18
- [ ] Platform/OS:
Raspberry Pi (3B+)
- [ ] Browser:
Chromium on same host as Node-Red, Safari on Mac on same network

Node-Red Server 2 =====
- [ ] Node-RED version:
v1.2.1
- [ ] Node.js version:
v12.19.0
- [ ] npm version:
v6.4.18
- [ ] Platform/OS:
Raspberry Pi (4B - 4GB)
- [ ] Browser:
Chromium on same host as Node-Red, Safari on Mac on same network

**Comment by knolleary** [comment]
Thanks - this was reported on the forum last night. We'll have 1.2.2 published later today with a fix.

**Comment by cakefornoreason** [comment]
My apologies for not checking the forum first. Thanks for your quick attention just the same!

**Comment by nicedevil007** [comment]
still not available as docker image correct?

**Comment by knolleary** [comment]
1.2.2 has not been released yet. Coming tomorrow.
