### ISSUE TITLE
http in no params in msg.payload

### ISSUE THREAD

**Issue by E1cid** [node-red/node-red#2727]
when http in set to POST the query params are not set in msg.payload, infact it is an empty object, they can be found in msg.req.query, but in GET they are set in msg.payload. this seems inconsistant.

to reproduce set http in node to POST

what happens - the query paramaters are not set in msg.payload

expected - the query params in msg.payload

- [ ] Node-RED version: 1.1.2
- [ ] Node.js version:13
- [ ] npm version: ?
- [ ] Platform/OS: android
- [ ] Browser: firefox

**Comment by knolleary** [comment]
If we did that, where would the payload of the POST request be put?

**Comment by E1cid** [comment]
Not sure what you mean this is the in node not a request, for a get request you send params to payload. any response would be set after the in node jst as it would for a get request

**Comment by hardillb** [comment]
POST requests have a BODY

**Comment by E1cid** [comment]
so if it had a json body the params would be in payload?

**Comment by hardillb** [comment]
No, the JSON would be in the payload, the query parameters (if they exist would be in `msg.req.query`

GET requests do not have a payload

**Comment by E1cid** [comment]
sorry my pharses are not exact i mean the json body would be parsed and sent to msg.payload?

**Comment by hardillb** [comment]
yes

**Comment by E1cid** [comment]
Ok thakyou for the clarification.
