### ISSUE TITLE
v1.2.2: Recovered nodes warning for z=null when importing

### ISSUE THREAD

**Issue by boraozgen** [node-red/node-red#2731]
Hello @knolleary,

I have an application where I generate and import nodes. It had this convenient feature that imports the nodes to the cursor instead of a fixed position when `z` is set to `null`. I am getting a "recovered nodes" warning when I import these nodes on v1.2.2. It is probably caused by this line:

https://github.com/node-red/node-red/blob/8049e44decdce487382f16dfc6e3d8af4da5bfd0/packages/node_modules/%40node-red/editor-client/src/js/nodes.js#L1156

Is there a particular reason that this was introduced?

**Comment by boraozgen** [comment]
Moreover, the nodes still get imported properly, except the warning and an empty "Recovered nodes" flow being created.

**Comment by knolleary** [comment]
Hi @boraozgen 

that is not a scenario I considered when we introduced this fix to handle the cases were a flow has got 'bad' nodes in it - ie nodes that have lost their `z` property.

The fix on your side would be to make sure you give the generated nodes a non-null `z` property - if it doesn't point to a known tab, the nodes will get attached to the mouse to be placed in the current workspace.

But it would also be reasonable to maintain the existing behaviour you have relied on. I'll look at how we can revert this change for when doing a manual import.

**Comment by boraozgen** [comment]
Thanks for the quick response. It works when I set it to `"0"` but not `""` or `0`. Anyway, I think I will be sticking to v1.2.1 until you decide whether you will revert it or not.

**Comment by knolleary** [comment]
I've just pushed a fix that only applies the recovery nodes logic when doing the initial import of flows. That means your workflow will continue to behave as it did.

Not going to rush a 1.2.3 out with just this in, but we'll see what else comes up in the next week.
