### ISSUE TITLE
Restart Flows not working

### ISSUE THREAD

**Issue by zeldalegends** [node-red/node-red#2740]
What are the steps to reproduce?
Click on "Restart Flows"

What happens?
A notification appears:
Deploy failed: {"code":"unexpected_error","message":"runtime.flows.loadFlows is not a function"}

What do you expect to happen?
Flows restarted without errors.

Please tell us about your environment:
Node-RED version: v1.2.1
Node.js version: v12.19.0
npm version: v6.14.8
Platform/OS: Windows_NT 10.0.18363 x64 LE
Browser: Chrome 86.0.4240.75

**Comment by knolleary** [comment]
Fixed in 1.2.2
