### ISSUE TITLE
String replaceAll() not working in Function node

### ISSUE THREAD

**Issue by zeldalegends** [node-red/node-red#2741]
What are the steps to reproduce?
Create a Function node, with default inject and debug.
Put the following code in Function node:
var a = "aaa bbb aaa ccc";
var b = a.replaceAll("aaa", "xxx");
msg.payload = b;
return msg;
Deply and inject.

What happens?
The Debug panel responds:
TypeError: a.replaceAll is not a function

What do you expect to happen?
Debug panel responding:
xxx bbb xxx ccc

Please tell us about your environment:
 Node-RED version: v1.2.1
 Node.js version: v12.19.0
 npm version: v6.14.8
 Platform/OS: Windows_NT 10.0.18363 x64 LE
 Browser: Chrome 86.0.4240.75

**Comment by knolleary** [comment]
`String.replaceAll` is not a function that is available in node.js yet.

You can use `String.replace` with a regular expression and the `g` flag:

```
var b = a.replace(/aaa/g, "xxx");
```
