### ISSUE TITLE
Inject node with interval autostarts on Restart Flows

### ISSUE THREAD

**Issue by zeldalegends** [node-red/node-red#2759]
### What are the steps to reproduce?
Connect one inject and one debug node. Set the interval as 1 second and leave unchecked Inject afer 0.1 seconds. Deploy. Trig the inject node at run time, and it starts writing timestamps in debug. Move the inject node and Restar Flows.

### What happens?
The inject node starts sending timestamps without being triggered.

### What do you expect to happen?
The inject node should wait to be triggered before starting sending timestamps to debug.

### Please tell us about your environment:

12 Nov 15:17:08 - [info] Node-RED version: v1.2.3
12 Nov 15:17:08 - [info] Node.js  version: v14.15.0
12 Nov 15:17:08 - [info] Windows_NT 10.0.18363 x64 LE

**Comment by dceejay** [comment]
Thanks for the report,
The fire at interval is independent of both the fire at start and the manual trigger button, and will always fire at the interval specified (at the end of the interval). This is working as deigned and not a bug.

**Comment by knolleary** [comment]
As per @dceejay's comment - when the Inject node is configured to repeat at a given interval, it is entirely independent of if/when you click the manual inject button.
