### ISSUE TITLE
MQTT Node broken - Missing URL Reference

### ISSUE THREAD

**Issue by erik-l** [node-red/node-red#2767]
### What are the steps to reproduce?
Use builtin MQTT node

### What happens?
MQTT doesn't connect and stays disconnected

### What do you expect to happen?
Proper connection as this was working for years with my existing flows

### Error stack
Nov 21 09:38:11 rpi-matrix Node-RED[1014]: ReferenceError: URL is not defined
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at Object.connect (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/connect/index.js:64:18)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at MQTTBrokerNode.connect (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/network/10-mqtt.js:245:40)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at MQTTBrokerNode.register (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/network/10-mqtt.js:221:22)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at new MQTTOutNode (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/network/10-mqtt.js:504:29)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:493:31)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:194:48)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:345:33)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at stop.then.then (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:210:21)
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at <anonymous>
Nov 21 09:38:11 rpi-matrix Node-RED[1014]:     at process._tickCallback (internal/process/next_tick.js:189:7)

# Quickfix to solve this
Add the following line to the top lines of the file **/usr/lib/node_modules/node-red/node_modules/mqtt/lib/connect/index.js**

`var URL = require('url').URL;`

**Comment by hardillb** [comment]
Please include the FULL template, including all the version numbers.

**Comment by hardillb** [comment]
Also the change file is part of the MQTT.js package not Node-RED.

And the line to add the use of URL class was added 2 months ago

https://github.com/mqttjs/MQTT.js/commit/70a247c29e0b05ddd8755e7b9c8c41a4c25b431b

**Comment by knolleary** [comment]
The key question is what version of node.js is being used?

**Comment by hardillb** [comment]
Are you using Nodejs v8?

**Comment by erik-l** [comment]
I'm just using the official install (and update) script for the RPi.

`bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)`
(see https://nodered.org/docs/getting-started/raspberrypi)

`NodeJS v8.17.0`

NodeJS was not manually updated by me. It could only be updated via the above script.

I just ran the script by this morning and after updating to `Node-Red v1.2.5` all my MQTT nodes were not connected.
I searched the issue and found that log messafe that I attached above.

Of course you could argue that MQTT it is a 3rd party module but it is used and referenced in a way that currently it doesn't work anymore with a plain Node-Red only installed and maintained the official way.

**Comment by hardillb** [comment]
What OS and hardware are you running this on?

What's happened is that MQTT.js have made changes that are not compatible with NodeJS v8 (which is no longer formally supported by NodeJS anymore but still supported by Node-RED until v2.0).

Having dependencies drop support for end of life NodeJS versions is going to be more and more of a problem before v2.0

As of NodeJS v10 the URL class is globally available without having to import it.

I thought the install script would upgrade NodeJS, but it doesn't look like it has in this case. I suggest you upgrade to NodeJS v12 (or newer) if you can while we work out if we can pin MQTT.js at a version that will continue to work on NodeJS v8

**Comment by erik-l** [comment]
**HW**
Raspberry Pi 3 Model B

**OS**
Debian 9 stretch (Raspian)
Linux version 4.19.66-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1253 SMP Thu Aug 15 11:49:46 BST 2019

Thanks for the detailed information on that issue with NodeJS versions. I did that quickfix and shared it since I use Node-Red for home automation and it is kind of "critical" for that.

**Comment by knolleary** [comment]
Node-RED 1.2.6 has been published which picks up the fixed MQTT module (they reverted their change that broke things).
