### ISSUE TITLE
Installing node as tarball on windows not possible

### ISSUE THREAD

**Issue by beorgler1** [node-red/node-red#2769]
Hi all,

I can't install a node module from a tarball on node-red running on windows.
I think the problem is in @node-red/registry/lib/installer.js.
The regexp localtgzRe checks if the path starts with "/". This doesn't work on windows. 
Maybe you could change the regexp to something like ` /^([a-zA-Z]?\:|\/).+tgz$/`

### What are the steps to reproduce?

1. Run node-red on windows
1. upload module tgz file

### What happens?
We get an error message:
"Failed to install: node-red-contrib-os-0.1.7.tgz

Invalid url

Check the log for more information"

Logs:
Installation of module node-red-contrib-os failed: invalid url: C:\\\<user-dir>\\\.node-red\nodes\node-red-contrib-os-0.1.7.tgz

### What do you expect to happen?
The node module should be installed

### Please tell us about your environment:

- [ ] Node-RED version: v1.2.3
- [ ] Node.js version: v14.15.1
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Have you tried with `C:/<user-dir>/.node-red/nodes/node-red-contrib-os-0.1.7.tgz`?

**Comment by knolleary** [comment]
Ah sorry - yes, it checks for the leading `/` as well. So yes, the regex could be more useful.
