### ISSUE TITLE
Trigger node sending wrong timestamp in delayed output message

### ISSUE THREAD

**Issue by brainbugfix** [node-red/node-red#2771]
### What are the steps to reproduce?

1. Set actions on activate and deactivate to "Timestamp"
2. Activate the trigger node
3. Let it expire

### What happens?

The output is the same timestamp twice.

### What do you expect to happen?

Both representing the current time.

See also [Forum](https://discourse.nodered.org/t/trigger-timestamp-output/36586)

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.6
- [ ] Node.js version: 12.19.1
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Raspberry Pi / Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l
- [ ] Browser: Firefox

**Comment by colinl** [comment]
@brainbugfix it might be better to edit the title of this to something like "Trigger node sending wrong timestamp in delayed output message"

**Comment by colinl** [comment]
I suggest that this is a bug.  It is conceivable that someone is relying on the timestamp being that of the initial trigger but I think that it is unlikely.
