### ISSUE TITLE
Cannot login admin after using httpNodeAuth on IOS 

### ISSUE THREAD

**Issue by linhtranvu** [node-red/node-red#2776]
### What are the steps to reproduce?

1. Using IOS
2. Open dashboard with basic authentication on Safari
2. Close dashboard, open admin, enter username and pass. Now you cannot login although input right authentication info

### What happens?

Cannot login admin after using httpNodeAuth on ios 

### What do you expect to happen?

Admin must be authorized

### Please tell us about your environment:

- [x] Node-RED version: 1.2.1
- [x] Node.js version: 12.16.1
- [x] npm version: 6.13.4
- [x] Platform/OS:  IOS 13.5.1 (but also confirm on other IOS version)
- [x] Browser: Safari

**Comment by VishalVrk** [comment]
facing same issue not getting the Auth screen

**Comment by linhtranvu** [comment]
I test on MacOS today and confirm it having issue too, so core Safary on mobile and MacOS share the same problem
