### ISSUE TITLE
UI screws up when defining custom 'parseFloat' function in 3rd party node

### ISSUE THREAD

**Issue by gvdhoven** [node-red/node-red#2786]
### What are the steps to reproduce?
Define the following method in any of the HTML files the node runtime loads:
```
        function parseFloat(value, fallback) {
                return (/^(\-|\+)?([0-9]+(\.[0-9]+)?|Infinity)$/.test(value)) ? Number(value) : fallback;
        }
```

### What happens?
![image](https://user-images.githubusercontent.com/186093/102715074-169f3f80-42d3-11eb-9e7d-5261fc349a00.png)

### What do you expect to happen?

The tab menu to not cause an error in `vendor.js` (as can be seen in console)

### Please tell us about your environment:

- [X] Node-RED version: 1.2.6 (docker image)
- [X] Node.js version: 12
- [X] npm version: default docker image version
- [X] Platform/OS: Windows
- [X] Browser: Chrome

**Comment by hardillb** [comment]
Why are you overriding the standard `parseFloat()` function?

**Comment by knolleary** [comment]
Yes, if you override a built-in function like `parseFloat` that behaves differently to the built-in `parseFloat` then you are going to break lots of things. I'm not sure why you would expect Node-RED to continue working.

```
> parseFloat("10px")
10

> yourParseFloat("10px")
undefined
```

**Comment by gvdhoven** [comment]
Good point nick, i needed a parse or fallback float method; I now changed the name so it doesn't screw up the built-in function.
