### ISSUE TITLE
HmIP-FBL Level2 for adjusting slat position is not wirking

### ISSUE THREAD

**Issue by N7-Shepard** [node-red/node-red#2787]
It's not possible to change the slat position via the datapoint level2 for HmIP-FBL devices. a normal Get-Value is working and delivers the correct value stored in the CCU, but a set-value is not transmitted to the ccu and therefore not transmitted to the device itself. 
There is no error in the log or debug windows. 

- [ ] Node-RED version: 1.2.6
- [ ] CCU3

**Comment by hardillb** [comment]
This sounds like you are talking about a specific node, this repository is only for issues with the core of Node-RED. You need to raise any issue with a contributed node directly with that node's author.

There is currently not enough details in what you have provided for use to help point to at the right node.

**Comment by dceejay** [comment]
Closing this here as this is not a core node and thus not an issue we can deal with here.
