### ISSUE TITLE
swapped description of encodeUrl/encodeUrlComponent and decodeUrl/decodeUrlComponent

### ISSUE THREAD

**Issue by heikokue** [node-red/node-red#2790]
### What are the steps to reproduce?
choosing the JSONata in a node properties dialog (e.g. switch node)

### What happens?
for encodeUrl the description og encodeUrlComponent is shown
for encodeUrlComponent the description og encodeUrl is shown
for decodeUrlthe description og decodeUrlComponentis shown
for decodeUrlComponentthe description og decodeUrlis shown

### What do you expect to happen?
right description shown

### Please tell us about your environment:

- [X] Node-RED version: v1.2.6
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Fixed in dev for 1.3
