### ISSUE TITLE
Multiple context stores are error prone

### ISSUE THREAD

**Issue by ChristianMayer** [node-red/node-red#2793]
### What are the steps to reproduce?
- Set up multiple context stores as described in the documentation at https://nodered.org/docs/user-guide/context
- store some data there by selecting e.g. `file` for `flow.myData`.
- access that `flow.myData` in a different node without remembering to also change the store from `default` to `file`

### What happens?
The information stored in `flow.myData` (as set in the node with `file` store) isn't visible

### What do you expect to happen?
It's a global setting that `flow.myData` will allways be either `default` or `file` and not a per node setting.

Using the context store in many different nodes is very error prone as it will become very likely that at least one node will have the wrong storage selected.

### Please tell us about your environment:

- [x] Node-RED version: latest Docker: 1.2.6
- [ ] Node.js version: latest Docker: ?
- [ ] npm version: latest Docker: ?
- [x] Platform/OS: latest Docker on x86
- [x] Browser: Firefox and Chrome

**Comment by knolleary** [comment]
You say you have selected a non-default store in one node, and then forgot to change selection of store in another node.

But your suggested fix is for there to be a default store that all nodes use by default.

That is exactly what the `default` store is meant to be.

I don't understand. You've

**Comment by ChristianMayer** [comment]
There's a misunderstanding here :)

The problem is that it should never happen that one node thinks that `flow.myData` is `file` and **at the same time** a different node thinks that `flow.myData` is `default`. 

Actually calling `default` "default" in this example is quite bad as it can lead to this misunderstanding. Renaming it to `memory` might make it more clear. So the problem could be rephrased to:
The problem is that it should never happen that one node thinks that `flow.myData` is `file` and **at the same time** a different node thinks that `flow.myData` is `memory`. This is error prone and will lead to frustrated users.

**Comment by knolleary** [comment]
But that is how it works.

Each store is its own namespace. I do acknowledge the confusion this can cause, but there is no fundamental change to the model we can make that won't risk breaking existing users. It has worked like this for a number of years at this point.

The one change we should make is to have the selected context store more obvious in the TypedWidget. I've never been completely happy with how the store information is hidden under a drop-down menu in the widget.

**Comment by ChristianMayer** [comment]
It might also help when you show a warning sign (or at least just an information hint) that the same name is now used in two different storage namespaces at the same time.

I guess that most users do not want to use the same name in two different name spaces on purpose but that this might nearly always be a configuration error.

**Comment by mlh5599** [comment]
I have experienced bugs related to this as well.  Troubleshooting would be a lot easier if the selected store wasn't hidden behind a drop down.

I most frequently experience this when I decide a memory variable needs to persisted after I've already built flows around it.  An option to update all nodes pointing at the old store to the new store on save would be a great improvement that should be backward compatible.

**Comment by knolleary** [comment]
I have pushed a fix for 1.3 that displays the context store name. It's fairly subtle as there isn't a lot of room to spare - but at least its now there.

![image](https://user-images.githubusercontent.com/51083/110674201-913c7480-81c9-11eb-97c9-108cc44fe0a7.png)
