### ISSUE TITLE
support node worker_threads 

### ISSUE THREAD

**Issue by cmdares** [node-red/node-red#2813]
node-red is used to provide micro services in high concurrency scenarios.
The utilization rate of multi-core server is too low.
If can be used "worker_threads" with nodejs in one node-red instance rather than  deploy nginx(round_robin)+N*node-red instances.

thanks.

**Comment by knolleary** [comment]
Hi, please use the issue template we provide.

We do not use this issue list for feature requests. Thanks.

Worker threads are something we'll be looking at in the future.
