### ISSUE TITLE
Make maxBuffer configurable for the exec node ?

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#2817]
I've run into an edge case where I'm requesting a lot of data from the exec node and hitting the 10000000 bytes limit that is currently set in this line:
https://github.com/node-red/node-red/blob/06ceb056f36ada560e66c16e71453c1c15dd0795/packages/node_modules/%40node-red/nodes/core/function/90-exec.js#L34

Would it make sense to make that configurable ?

**Comment by dceejay** [comment]
probably - I'm thinking more of over-rideable in settings rather than in the node itself.
The default is only 1024x1024 so we are already 10x that :-)

**Comment by natcl** [comment]
Ok, I'll do a PR soon.
In my case I'm using curl to get logs from the Docker socket and those logs are huge...

**Comment by dceejay** [comment]
can you not use options like since, until or follow to get the relevant part ?

**Comment by natcl** [comment]
In my use case the goal is to download the whole log file.

**Comment by dceejay** [comment]
You could use spawn mode instead and then handle each chunk as it comes - (or indeed send straight to a file out node)

**Comment by natcl** [comment]
My current  flow was 
http in --> exec --> http out so I'm not sure spawn would help me in this case.
I could also tell curl to output to a file instead and then ask node-red to read the file.

**Comment by natcl** [comment]
Hmm but I see what you mean I  could just let node-red store it and when I get rc = 0 I output the full file.

**Comment by dceejay** [comment]
yeah spawn won't help that - it would create multiple responses... 
so file probably it - or indeed hack that code :-)

**Comment by natcl** [comment]
If you're ok with that I still think it might be reasonable to have this option as a config value in settings.js like you mentioned.. will work on that asap.

**Comment by dceejay** [comment]
ok with me. (was just exploring workarounds in the meantime :-)

**Comment by natcl** [comment]
Yes thanks :) the spawn idea does seem work with http in/out if I cache the file in a function node in between :)

**Comment by hardillb** [comment]
Do you need a function node, would a join node note work (does the spawn node send the end marker for a join node?)

**Comment by natcl** [comment]
hmm good point, in manual mode it works:
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/77556/104247581-127bc300-5436-11eb-86eb-924da6dde99d.png">
 Thanks !

**Comment by dceejay** [comment]
Good thought. And if not it should be able to..

**Comment by natcl** [comment]
Or would the correct way be to use the  complete node instead ?

**Comment by dceejay** [comment]
Technically yes - complete node would be the canonical way - but as this node has that 3rd output that does exactly that for the return code - I can't see a reason not to add msg.complete to that... to make wiring it up a doddle.

**Comment by dceejay** [comment]
actually - adding msg.complete to the node is dumb :-) - as you need to have a change node afterwards to remove the payload you can add it there if needed.  I do suspect though that joining things afterwards is just as likely to blow memory as using exec mode...  using spawn to a file works as it saves them chunk at a time. 

Net is yes - feel free to proceed with your PR re exec memory in settings, as was.
