### ISSUE TITLE
Http-request node simple GET does not work.

### ISSUE THREAD

**Issue by mickev36** [node-red/node-red#2824]
### What are the steps to reproduce?

As originally reported in this reddit thread : https://www.reddit.com/r/nodered/comments/kqvupx/httprequest_redirected_to_my_own_ip/

Make a simple flow using the request node to make a simple GET query to "pornhub.com". Any other website that I tested works.

I've pinned down the problem to the library "request". I've been able to reproduce the same issue using the library "request" (used by the http-request node) in a separate node environment, so the issue is related to the library and not the node's code. I'm not sure what's different with this case, but is looks like a bug in the library.

Howether, the library "request" has long been deprecated, so issues like this might keep arising. What's next for the request node ? Is a new http node, rewritted with core Node.js http features for example in the backlog ?

### What happens?

EHOSTUNREACH error, with my local ip address as url 

### What do you expect to happen?

Retrieve the html contents of the home webpage (works for google.com, facebook.com, twitter.com, etc...)

### Please tell us about your environment:

- [x ] Node-RED version: 1.0.4
- [x ] Node.js version: 13.9.0
- [x ] npm version:6.13.7
- [x ] Platform/OS:Ubuntu latest
- [ x] Browser:Firefox latest

**Comment by hardillb** [comment]
Which IP address are you talking about. Your LAN address or the public address assigned by your ISP?

**Comment by mickev36** [comment]
Public address, as provided by the ISP

**Comment by knolleary** [comment]
Given the nature of the site you are trying to reach, is your ISP blocking access?

**Comment by hardillb** [comment]
Did your router support hairpin NAT?

**Comment by knolleary** [comment]
As I see you say it works with other http libraries and we already have an open issue to replace the request library in the http node, I'm going to close this one. You can follow #2481 for updates.
