### ISSUE TITLE
Unable to store or propagate Map()

### ISSUE THREAD

**Issue by labodj** [node-red/node-red#2832]
### What are the steps to reproduce?
Hi I'm unable to store (in contexts) or send a Map(), I'm not sure this behaviour is expected
You can try with the following code:

`[{"id":"db349157.7c371","type":"inject","z":"d9d1ebef.95ffd8","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":130,"y":60,"wires":[["fa7d4bf1.35e2c8"]]},{"id":"fa7d4bf1.35e2c8","type":"function","z":"d9d1ebef.95ffd8","name":"","func":"const myMap = new Map([\n    [1, 'one'],\n    [2, 'two'],\n    [3, 'three']\n]);\nreturn {\n    payload: myMap\n};\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":270,"y":60,"wires":[["ed432998.288418"]]},{"id":"ed432998.288418","type":"debug","z":"d9d1ebef.95ffd8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":400,"y":60,"wires":[]}]`

### What happens?
Debug node shows a payload that is an empty object
### What do you expect to happen?
Maps are useful, I don't know if this is a bug, if not it should be a nice feature for the future.
### Please tell us about your environment:

- [ ] Node-RED version: 1.2.7 (Docker latest-12 image)
- [ ] npm version: the one shipped with latest-12 docker image
- [ ] Node.js version: 12
- [ ] Browser: Chorme 88.0.4324.96 64 bit
- [ ] Platform/OS: Raspberry Pi 4 / Raspberry Pi OS

**Comment by hardillb** [comment]
This is expected because a Map can not be serialised to JSON. You will need to use basic objects.

**Comment by labodj** [comment]
Ok, are the messages/objects always serialized to JSON when propagated or stored in context?

**Comment by dceejay** [comment]
Yes
