### ISSUE TITLE
sometimes sub-Flow opens multiple times after latency and even clears some values

### ISSUE THREAD

**Issue by crackytsi** [node-red/node-red#2840]
### What are the steps to reproduce?
If within the flow, a sub-flow node exists, I have sometimes a strange situtation:
Usually, when I double-click on the sub-flow, a dialog and I can change properties or edit the subflow.
But sometimes it does not react and when I click multiple times, suddenly it opens.
Here a screenshot:
![image](https://user-images.githubusercontent.com/11610825/106115787-6afad200-6151-11eb-8cad-1ea5d3df7816.png)

Click repeated in a very short time on a sub-flow
OR
configure authentication (e.g. using header variable) and wait for a longer time. Then double-click on a sub-flow.

### What happens?
If within the flow, a sub-flow node exists, I have sometimes a strange situtation:
Usually, when I double-click on the sub-flow, a dialog and I can change properties or edit the subflow.
But sometimes it does not react and when I click multiple times, suddenly it opens.
It seems that related to that, sometimes values set for Environment-Variables on the object get deleted.

See also https://discourse.nodered.org/t/strange-issue-or-bug-opening-a-sub-flow/39866

### What do you expect to happen?
-Multiple opens should be prevented
-clearing of values should not happen

### Please tell us about your environment:

- [x] Node-RED version: 1.2.7
- [x] Node.js version: v12.18.0
- [x] npm version: 6.14.4
- [x] Platform/OS: debian latest
- [x] Browser: chrome

**Comment by crackytsi** [comment]
@knolleary Unfortunately the issues still appear even with latest version. So I have still the issue that objects sometimes double open or the field contents gets cleared.
Btw I do not see the mentioned load dialog. Might this be a different issue?

**Comment by knolleary** [comment]
What version are you testing with? This is fixed in the 1.3.0-beta.1 release that I published about 10 minutes ago.

**Comment by crackytsi** [comment]
Ah i tested 1.2.9
