### ISSUE TITLE
RED.stop() is not working as expected

### ISSUE THREAD

**Issue by Norberg95** [node-red/node-red#2861]
### What are the steps to reproduce?
Running the code below with NodeJS
```
const http = require('http');
const express = require('express');
const RED = require('node-red');
const path = require('path');

// Create an Express app
const app = express();

// Add a simple route for static content served from 'public'
app.use('/', express.static('public'));

// Create a server
const server = http.createServer(app);

const settings = {
  httpAdminRoot: '/red',
  httpNodeRoot: '/api',
  userDir: path.resolve(__dirname, 'nodeRedResources'),
  functionGlobalContext: {},
};

// Initialise the runtime with a server and settings
RED.init(server, settings);

// Serve the editor UI from /red
app.use(settings.httpAdminRoot, RED.httpAdmin);

// Serve the http nodes UI from /api
app.use(settings.httpNodeRoot, RED.httpNode);

server.listen(8000);

// Start the runtime
RED.start().then(() => RED.stop());
```

### What happens?
Throws the following error:

> C:\dev\node-red\node-red-empty\node_modules\@node-red\editor-api\lib\editor\comms.js:224
>                     wsServer.handleUpgrade(request, socket, head, function done(ws) {
>                              ^
> 
> TypeError: Cannot read property 'handleUpgrade' of null
>     at Server.upgrade (C:\dev\node-red\node-red-empty\node_modules\@node-red\editor-api\lib\editor\comms.js:224:30)
>     at Server.emit (events.js:315:20)
>     at onParserExecuteCommon (_http_server.js:695:14)
>     at onParserExecute (_http_server.js:608:3)

### What do you expect to happen?
To stop the flows and wait until RED.start() is called to restart the flows.
### Please tell us about your environment:

- [ ] Node-RED version:1.2.9
- [ ] Node.js version:14.15.5 
- [ ] npm version:6.14.10 
- [ ] Platform/OS:Windows
- [ ] Browser:Chrome

**Comment by hardillb** [comment]
Iirc thehe Node-RED engine is only intended to be started once, you can not call `RED.start()` after calling `RED.stop()`

**Comment by Norberg95** [comment]
My goal was to stop and restart the flows.
I have figured out that you can stop the flows with `RED.nodes.stopFlows()` and then restart it with `RED.nodes.startFlows()`.
