### ISSUE TITLE
JSON Editor is not available due to  .red-ui-typedInput-container.width =60% !important  On Chrome 88.0.4324.15

### ISSUE THREAD

**Issue by SergiuToporjinschi** [node-red/node-red#2862]
### What are the steps to reproduce?
* add an inject node;
* edit node inject properties
* add field of type JSON to msg

### What happens?
* edit button from the right of the value file is not visible 
### What do you expect to happen?
* edit button from the right to be visible and accessible
### Please tell us about your environment:

- [x] Node-RED version: 1.2. 9
- [x] Node.js version: 12.13.0
- [x] npm version: 6.12.0
- [x] Platform/OS: Windows10
- [x] Browser: Chorme 88.0.4324.15
### Possible solution 
* in CSS  .red-ui-typedInput-container remove !important flag
### pictures:
Before removing flag;
![image](https://user-images.githubusercontent.com/9376439/107115150-413d5b80-6873-11eb-8380-ce47f07d5728.png)
After  removing flag:
![image](https://user-images.githubusercontent.com/9376439/107115152-469aa600-6873-11eb-85da-3689354b1161.png)

**Comment by knolleary** [comment]
Hi,

the `60% !important` style is *not* coming from the core of Node-RED.

Looking at your screenshot, I can see its coming from a `<style>` tag - which suggests a node you have installed has incorrectly set this style without scoping it to just their node.

If you click on the `<style>` link in the red box you've highlighted, you should be able to identify which node it is based on what content is around the style tag.

**Comment by SergiuToporjinschi** [comment]
Yes I found it. 10x

**Comment by knolleary** [comment]
Can you let me know which node it was? Are you going to follow up with them?

**Comment by SergiuToporjinschi** [comment]
:D No, I'm a shame about that :D. It was one of my nodes locally,  some older attempt of main to create a node. And I had this instance not used for quite a long time and after updating the node-red I saw that and to be honest, I also saw that is in a <style> tag  and I was like what are they doing there !?!? I'm using style tag on my junk projects for quick testing something, but this guys ... they are releasing that why they are using style tags :D and in the end It was me :D 

Nevertheless, I was so happy that I could provide even a possible solution for "your bug" :D;
By the way, can you remove this issue ?!?!  :))))
