### ISSUE TITLE
Join node not reset when operating in automatic mode

### ISSUE THREAD

**Issue by deab6** [node-red/node-red#2866]
In automatic join mode, with two input messages supplied with .parts parameters specified in order to make a combined message in the correct sequence order, the join node does not appear to stop the joining process when issued with a reset command between each set of input messages.

The join node should only be returning output when all parts of the incoming messages have been received. The automatic functionality is desired as this is the only one that appears to use the .parts function in order to maintain correct sequence order (to account for potential time delay differences in the preceding branches which could, for example, be querying data from Modbus devices)  

### What are the steps to reproduce?
Using the following simple flow, adapted from issue #2188 and injecting in the following order:

`[{"id":"ac5a770f.97b148","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"b17c6fd0.cc286","type":"inject","z":"ac5a770f.97b148","name":"prop1","props":[{"p":"payload"},{"p":"topic","vt":"str"},{"p":"parts","v":"{\"id\":\"group\",\"count\":2,\"len\":1,\"index\":0}","vt":"json"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"prop1\":\"value1\"}","payloadType":"json","x":482,"y":312,"wires":[["721aa4a4.2e7bec"]]},{"id":"721aa4a4.2e7bec","type":"join","z":"ac5a770f.97b148","name":"","mode":"custom","build":"array","property":"","propertyType":"full","key":"topic","joiner":"\\n","joinerType":"str","accumulate":false,"timeout":"","count":"2","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":936,"y":468,"wires":[["e2d98dc7.a1575"]]},{"id":"e2d98dc7.a1575","type":"debug","z":"ac5a770f.97b148","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1076,"y":468,"wires":[]},{"id":"21543c43.15cf14","type":"inject","z":"ac5a770f.97b148","name":"prop2","props":[{"p":"payload"},{"p":"topic","vt":"str"},{"p":"parts","v":"{\"id\":\"group\",\"count\":2,\"len\":1,\"index\":1}","vt":"json"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"prop2\":\"value2\"}","payloadType":"json","x":506,"y":528,"wires":[["721aa4a4.2e7bec"]]},{"id":"e2a2d142.5bd34","type":"change","z":"ac5a770f.97b148","name":"msg.reset -> true","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"},{"t":"delete","p":"payload","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":594,"y":408,"wires":[["721aa4a4.2e7bec"]]},{"id":"54880bbb.db1eb4","type":"inject","z":"ac5a770f.97b148","name":"reset","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":410,"y":408,"wires":[["e2a2d142.5bd34"]]}]`

Test Case 1

- prop1
- prop2

Test Case 2
- prop2
- prop1

Test Case 3
- prop1
- reset
- prop2

Test Case 4
- prop2
- reset
- prop1

Test Case 5
- prop1
- prop1

### What happens?
Test Case 1: Output is a combined message with payload order [0] value1, [1] value2
Test Case 2: Output is a combined message with payload order [0] value1, [1] value2
Test Case 3: Output is an error message followed by a combined message with payload order [0] value1, [1] value2
Test Case 4: Output is an error message followed by a combined message with payload order [0] value1, [1] value2
Test Case 5: Output is a combined message with payload order [0] value1

### What do you expect to happen?
Test Case 1: As expected
Test Case 2: As expected with desired sequence order as specified in message parts.
Test Case 3: As a reset message was sent before the second message I expect the counter and intermediate/incomplete object to be discarded. Therefore no output is sent at that moment in time.
Test Case 4: As a reset message was sent before the second message I expect the counter and intermediate/incomplete object to be discarded. Therefore no output is sent at that moment in time.
Test Case 5: Two parts have been supplied (given two injections of prop1 node) but only a payload of size 1 is returned as values have been overwritten. No test appears to be made to ensure all parts of the message are present before returning output. Ie although the count is two input messages only a single index value is present.

### Please tell us about your environment:

- [ ]  Node-RED version: v1.2.7
- [ ] Node.js version: 12.19.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
So the only actual error condition is 5 - where indeed if the parts are supplied with an index and you are building an array then  it should replace any existing index and not count towards the total array. Bit of an odd case as you would not expect to have parts with a duplicate index - but yes it shouldn't output.
