### ISSUE TITLE
Config Node is destroyed before other nodes on re-deploy

### ISSUE THREAD

**Issue by hrueger** [node-red/node-red#2876]
### What happens?
I hava a couple of Nodes which need a Config Node. This config Node holds a socket client object. The nodes send commands to the socket via the config node. Now on a redeploy my nodes listen to the "close" event to send a last (in my case a reset) command to the socket. However, the config node has already been exited and during its exit process it has closed the socket.

So now my question / bug: Can I set the nodes to be exited before the config node?
### What do you expect to happen?
I would like to have the nodes being exited before the config node.

### Please tell us about your environment:

- [x] Node-RED version: v1.2.7
- [x] Node.js version: v14.13.0
- [x] npm version: 6.14.11
- [x] Platform/OS: Windows_NT 10.0.19042 x64 LE
- [x] Browser: Firefox

**Comment by knolleary** [comment]
We certainly ensure config nodes are started before flow nodes - I thought we had a similar approach for config nodes, but maybe not.

Will investigate.

**Comment by knolleary** [comment]
Have raised a PR for 1.3 with a fix - see #2880 for details
