### ISSUE TITLE
Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by GerwinvBeek** [node-red/node-red#2878]
### What are the steps to reproduce?
Open a node red editor with custom nodes installed

### What happens?
I use a nodered environment with around 110 custom nodes. I installed these nodes using npm install [foldername].
Now whenever I open nodered I get errors about node-red not being able to read the color of undefined:
![image](https://user-images.githubusercontent.com/26113706/108383739-58346400-720a-11eb-85b0-3bebc37175d2.png)

Say for example I have a node called "activity quality control":
![image](https://user-images.githubusercontent.com/26113706/108383991-96318800-720a-11eb-92b0-46a4dc20abf3.png)

When I keep my breakpoint at the same spot and filter for the same node type and continue the code it will come back in the same method at some point with the color:
![image](https://user-images.githubusercontent.com/26113706/108384155-c7aa5380-720a-11eb-9866-3f859dc40335.png)

### What do you expect to happen?
I feel like this method is called too early for custom nodes or this method should contain a null check preventing the error.

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9
- [ ] Node.js version: 12.18.4
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Windows
- [ ] Browser: Chrome/Edge
- [ ] running in Docker: No

**Comment by knolleary** [comment]
We're going to need more information to understand what is happening here.

There is nothing special about 'custom' nodes versus any node that has been npm installed - they all get loaded into the editor in exactly the same way.

When exactly did this error start occurring? Was it immediately after you installed your custom nodes?

If you've installed 100s of custom nodes have you ruled out it being a bug with one of them?

**Comment by GerwinvBeek** [comment]
Based on your information that customnodes get loaded at the same time as normal nodes I did some extra research.

For the development I tried to use as much typescript as possible. This resulted in me using require.js to develop the node definition in a .ts file:
![image](https://user-images.githubusercontent.com/26113706/108387259-b6af1180-720d-11eb-8ca1-31c8d187d383.png)

it looks like this require.js is a little bit too slow for node-red resulting in the node not being loaded when NodeRed calls the getNodeColor function.

I'll try to find another workaround for this.
Thanks for your information!

**Comment by knolleary** [comment]
Closing this issue as you've found the issue in your code.

**Comment by lgrkvst** [comment]
@GerwinvBeek, I just had the same error using the same setup `npm install [foldername]`.

It turned out that my `customNode.html` had a `data-help-name` that didn't match the name of the node. Fixed that and the error was gone.

So there's that...
