### ISSUE TITLE
MQTT drops messages when topic starts with '$'

### ISSUE THREAD

**Issue by exilitco** [node-red/node-red#2884]
### What are the steps to reproduce?

Using MQTT broker, subscribing to or publishing with topic beginning with a '$' sign.
Example: $aws/<whatever>

Same problem when subscribing to '#' wildcard. Messages originating from topics starting with dollar sign are dropped.

Suspect env-vars parsing might conflict with topic naming? But that would be weird considering incoming messages should not be modified.

### What happens?

Sent messages are dropped

### What do you expect to happen?

Messages to be received/sent

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9
- [ ] Node.js version: dont now, bundled/hidden with hassio
- [ ] npm version: dont now, bundled/hidden with hassio
- [ ] Platform/OS: linux/docker
- [ ] Browser: Chrome 
- [ ] running in Docker: yes

**Comment by knolleary** [comment]
What broker are you using?

By default a subscription to `#` is not required to return topics that start with `$` - you have to explicitly subscribe to them.

See http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718108

> A subscription to “#” will not receive any messages published to a topic beginning with a $

**Comment by exilitco** [comment]
I'm using the built-in mqtt broker of Aws Greengrass (Aws Iot "edge"/offline device)

The topic in question for publishing (Mqtt out) is $aws/things/<other_device_name>/shadow/update 
And $aws/things/<other_device_name>/shadow/update/accepted for subscription (Mqtt in)

Using the same credentials (certificates) from golang I can both receive and publish messages to the above topics as expected.

**Comment by knolleary** [comment]
Okay, I realise I only answered the part of your issue about subscribing to `#` not receiving topics that begin with a `$`.

Will investigate the publishing part of your issue.

**Comment by knolleary** [comment]
I have created a flow that has an MQTT In node subscribed to `$test`. I then use a second flow to publish to `$test` and I see the message arrive as expected.

I have also tested with a similar topic structure you are using - `$aws/things/blob/shadow/update` - but with mosquitto as I don't have Greengrass available. Again, all working as expected.

Could Greengrass be rejecting the message for some reason? Does it require a particular payload format?

You could try reconfiguring the nodes to test against a public MQTT broker such as test.mosquitto.org to verify exactly what you are sending looks like whatever greengrass would expect. (Don't forget that mosquitto won't do the topic mapping like greengrass does, so you'd need an MQTT In node subscribed to the same topic as the out node.)

**Comment by exilitco** [comment]
I've upgraded outdated components in the stack (os, greengrass) and redeployed the gateway and changed some node-red node configuration (QoS to 0). I'm now able to send messages towards $aws/.. topics without any problem. 

Also did some wire sniffing and no packages were received by node red so I'm now sure my problems lies with the broker and/or the configuration of the broker or node.

I'm closing this issue. 

Thank you!
