### ISSUE TITLE
Catch node not triggering on node.error();

### ISSUE THREAD

**Issue by mdkrieg** [node-red/node-red#2887]
### What are the steps to reproduce?
The below flow reproduces a problem I'm having with the catch nodes. I'm relying on them to catch an error in another block and behind the scenes it seems to be a problem with the catch block.

![image](https://user-images.githubusercontent.com/66855036/109394656-b8ec2c80-78ed-11eb-998e-465e254d1fcf.png)

`
[{"id":"23feb3f1.16d81c","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"3ebeb3ce.9fc46c","type":"function","z":"23feb3f1.16d81c","name":"","func":"node.error(\"foo\");\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":360,"y":60,"wires":[[]]},{"id":"5c51d682.c75e48","type":"catch","z":"23feb3f1.16d81c","name":"","scope":null,"uncaught":false,"x":200,"y":120,"wires":[["47b9e5c5.ca925c"]]},{"id":"36b2bca9.851e44","type":"inject","z":"23feb3f1.16d81c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":60,"wires":[["3ebeb3ce.9fc46c"]]},{"id":"47b9e5c5.ca925c","type":"debug","z":"23feb3f1.16d81c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":350,"y":120,"wires":[]},{"id":"93c0353c.9c8ab8","type":"catch","z":"23feb3f1.16d81c","name":"","scope":["3ebeb3ce.9fc46c"],"uncaught":false,"x":190,"y":160,"wires":[["517a9f38.fdab7"]]},{"id":"517a9f38.fdab7","type":"debug","z":"23feb3f1.16d81c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":350,"y":160,"wires":[]}]
`
### What happens?
The error gets thrown from the source instead of triggering the catch block. in my actual application I have a node that is flooding error messages and I need to catch them to be able to filter out what is happening.
### What do you expect to happen?
From the docs: "If an error is caught by a Catch node, it will not be logged to the Debug sidebar."  I would expect a message from the debug nodes, and not the function node.
### Please tell us about your environment:

- [x] Node-RED version: 1.2.9-git (previously an issue on 1.1.2 as well)
- [x] Node.js version: 10.21.0
- [x] npm version: 6.14.4
- [x] Platform/OS: AWS EC2 / Ubuntu 18.04.4 LTS
- [x] Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by knolleary** [comment]
From the docs: https://nodered.org/docs/user-guide/writing-functions#handling-errors

> To trigger a Catch node on the same tab, the function should call node.error with the original message as a second argument:
```
node.error("hit an error", msg);
```

In you example flow, you are not passing the msg as the second arg to node.error.

**Comment by hardillb** [comment]
You need to pass the input message to `node.error()` as well as the message for it to be catchable

```
node.error(''foo", msg)
```

**Comment by mdkrieg** [comment]
Ahhh, that's it. This explains why the contrib node won't catch either. Sorry for the bother

Thank both of you for the quick attention, best regards!
