### ISSUE TITLE
Installed new Nodes with embedding node-red not Attached into Editor

### ISSUE THREAD

**Issue by d0d04m3** [node-red/node-red#2889]
hi 
I cant show any Nodes in Editor when Installing new nodes
full story in node-red forums
https://discourse.nodered.org/t/i-cant-install-any-nodes-in-embedded-node-red/41791
- [ ] Node-RED version:1.2.9
- [ ] Node.js version: 12.16.3
- [ ] npm version: 6.14.4
- [ ] Platform/OS: win 10
- [ ] Browser: opera or chrome or any browser same Error

**Comment by knolleary** [comment]
If it's already been discussed in the forum, then there's no need for an issue here until we know there's a bug to be fixed.
