### ISSUE TITLE
Http In  GET - Body is lost | Not possible to receive body but possible to send.

### ISSUE THREAD

**Issue by carstenpi** [node-red/node-red#2891]
### What are the steps to reproduce?
Send a Get Request via Http Request Node with body/payload and the Option - 
Payload: "Send as request body" -  to a Http In GET Node. 
OR
Send a Get Request with body/payload to a Http In GET Node. 

### What happens?
The msg.payload is empty and the send body/payload is lost.

### What do you expect to happen?
Same behavior like http In POST/PUT Node. 
The sended body/payload of the Request shout be in the msg.payload.

Maybe Counterpart of #2476
It's possible to put a body/payload into a GET Request but it's not possible to 
receive the body/payload of a GET Request with the Http in GET Node.

### Please tell us about your environment:

- [1.2.9 ] Node-RED version:
- [12.21.0 ] Node.js version:
- [ 7.6.0] npm version:
- [ Linux 5.10.13 arm LE] Platform/OS:
- [] Browser:

![NodeRedGetRequestBehavior](https://user-images.githubusercontent.com/28219687/109927609-c5dd9700-7cc4-11eb-8d19-59c08bf8006f.PNG)

**Comment by hardillb** [comment]
This is likely to be the express app that Node-RED runs on ignoring the body on a GET request, which is inline with the HTTP spec as pointed out in #2476

**Comment by knolleary** [comment]
Given a GET request generally does not have a body, Node-RED has always put the query parameters, if any are set, into the payload as that is *probably* the most useful thing to do.

The body of the request is still accessible as `msg.req.body` - as long as the request has set the `content-type` to `application/json`.
