### ISSUE TITLE
CPU load increases over time 

### ISSUE THREAD

**Issue by M0ebiu5** [node-red/node-red#2893]
### What are the steps to reproduce?
Currently unknown - will try to provide an example flow.
The flows basically use dashboard, mqtt and influxdb with user interaction (=no heavy computing).

### What happens?
CPU load increases over time - like a "cpu leak"
Restarted node-red instance has about 3% and is increasing by about 1-2% each day.
As i discovered the problem, the machine had ~35% load on the node-red process. 
Disabling each flow separately showed, that most cpu time was consumed by flows with many dashboard nodes, but it never went down under 10% (only with a node-red restart).

### What do you expect to happen?
cpu load not constantly increasing by a time factor

### Please tell us about your environment:
|node-red | 6 Mar 16:46:23 - [info] Node-RED version: v1.2.6
|node-red | 6 Mar 16:46:23 - [info] Node.js  version: v13.8.0
|node-red | 6 Mar 16:46:23 - [info] Linux 5.4.0-58-generic x64 LE

**Comment by knolleary** [comment]
This is likely to be related to the nodes your are using rather than a core issue.

So without an example flow it doesn't give is much to go on. And it's likely going to be an issue you need to raise against the relevant nodes.

**Comment by M0ebiu5** [comment]
Ok, i will check the used non core nodes.
