### ISSUE TITLE
typedInput loses the selected contextOptions when the types method is called

### ISSUE THREAD

**Issue by zachowj** [node-red/node-red#2896]
### What are the steps to reproduce?

1. Have more than one context location setup.

![image](https://user-images.githubusercontent.com/37859597/110580250-19b10b80-811d-11eb-816c-8ab8325a7a92.png)

2. setup typedInput `$("#node-input-value").typedInput({default: "flow", types: ["msg", "flow", "global"]});`

3. select a context option other than the first one in the list

4. Calling the types method, `$("#node-input-value").typedInput("types", ["flow", "global"]);`, 
will lose which context option is selected and default to the first one. Calling types with the same array will cause it to also lose the selected context type, `$("#node-input-value").typedInput("types", ["msg", "flow", "global"]);`

### What happens?

Calling the `types` method of a typedInput loses the selected context location and default back to the first context location.

### What do you expect to happen?

Not to lose the selected context location when the `types` method is called.

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9
- [ ] Node.js version: 12.18.3
- [ ] npm version: 6.14.6
- [ ] Platform/OS: Windows_NT 10.0.19041 x64 LE
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Fix pushed for 1.3 - it now remembers the selected sub-option when changing types.

This also means it remembers the selection when the user switches between flow/global options.
