### ISSUE TITLE
HTML selector does not work if output is not msg.payload

### ISSUE THREAD

**Issue by lixas** [node-red/node-red#2902]
### What are the steps to reproduce?

![screenshot 1615840354](https://user-images.githubusercontent.com/2889604/111217597-66458c80-85de-11eb-87b4-64f303b63339.png)

If i set html output to something else than `msg.payload` - parser does not work anymore.

Flow for import available here
https://pastebin.com/cirMJn7H

both HTML's output names are `msg.payload` 
Change one of the HTML parser output to something else, like `msg.traffic` to observe unexpected behaviour

![screenshot 1615840506](https://user-images.githubusercontent.com/2889604/111218090-f5eb3b00-85de-11eb-8826-5a5c521b7ffa.png)
### What happens?
node outputs full page source, selector does not work. Data is still in `msg.payload`

![screenshot 1615840899](https://user-images.githubusercontent.com/2889604/111218629-a78a6c00-85df-11eb-9a7d-4f3b4347308c.png)

### What do you expect to happen?
my selected value from page in predefined tag `msg.traffic`

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9 Maintenance Release
- [ ] Node.js version: v15.11.0
- [ ] npm version: 7.6.0
- [ ] Platform/OS: Raspbian GNU/Linux 10 (buster)
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
@lixas  - For me it is fine- your debug node above is set to msg.payload so when you set the html node to send it's output to msg.traffic then the msg.payload sent out is the same as the input. If you change the debug to show whole msg or msg.traffic you will see your required output.
OK to close ?

**Comment by lixas** [comment]
That default debug setting (msg.payload) got me. If i change debug settings- I do get what is expected. Everything works correctly.
