### ISSUE TITLE
Switch Node Blocking Exception on Bad RegEx Pattern and Variable Property

### ISSUE THREAD

**Issue by plfinch** [node-red/node-red#2905]
### What are the steps to reproduce?
SETUP:
1. Create flow with switch node receiving Property (string to match) as msg.string and regex as msg.regex and performing a "matching regex" test. Also specify "otherwise" match as output 2.
2. Add inject node 1 to pass a property string ("foo") as msg.string and a good regex ("foo") as msg.regex.
3. Add inject node 2 to pass a property string ("foo") as msg.string and a bad regex ("[\[") as msg.regex.
4. Add debug nodes on output 1 and 2 writing string "MATCH" or "NOT MATCH" respectively.
5. Deploy.

TEST EXECUTION:
1. Select inject 1 and debug 1 displays "MATCH" in console.
2. Select inject 2 and a bad regex exception is raised.
3. Select inject 1 again and no debug console output will appear. The switch node has become unhealthy and no longer processes messages.

### What happens?
The switch node has become unhealthy and no longer processes messages.

### What do you expect to happen?
The exception is raised and cleared within the node and normal processing then resumes. Note this is what happens if the Switch Node Property is specified as a JSONata expression (string) rather than a msg. flow. or global. variable.
### Please tell us about your environment:

- [x] Node-RED version: v1.2.7
- [x] Node.js version: v12.21.0
- [x] npm version: 6.14.11
- [x] Platform/OS: Raspberry Pi 4 Model B Rev 1.2 CPU: 4xARMv7 RAM: 3919128kB, Linux NetMon 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux, Raspbian GNU/Linux 10 (buster) version 10.8
- [x] Browser: Windows 10 Edge or Chrome (all latest), MacOS Catalina Safari or Chrome (all latest)
[SwitchNodeBlockingException.json.txt](https://github.com/node-red/node-red/files/6164888/SwitchNodeBlockingException.json.txt)

**Comment by plfinch** [comment]
Additional discussion can be found at [Discourse Topic 42235](https://discourse.nodered.org/t/flow-exception-recovery-for-dynamic-regex-syntax-error/42235).

**Comment by dceejay** [comment]
copied tester flow over from discourse
```
[{"id":"26f5fb49.791c54","type":"tab","label":"BAD REGEX","disabled":false,"info":""},{"id":"94fa80a9.96479","type":"inject","z":"26f5fb49.791c54","name":"GOOD REGEX - MATCH YES","props":[{"p":"string","v":"foo","vt":"str"},{"p":"regex","v":"foo","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":360,"y":380,"wires":[["1738b231.f9025e"]]},{"id":"1738b231.f9025e","type":"switch","z":"26f5fb49.791c54","name":"msg.string ~  msg.regex","property":"string","propertyType":"msg","rules":[{"t":"regex","v":"regex","vt":"msg","case":false},{"t":"else"}],"checkall":"false","repair":false,"outputs":2,"x":690,"y":420,"wires":[["9708b837.5dc0e8"],["f0dbaae1.e6e608"]],"outputLabels":["TRUE","FALSE"]},{"id":"9708b837.5dc0e8","type":"debug","z":"26f5fb49.791c54","name":"MATCH","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"'MATCH'","targetType":"jsonata","statusVal":"","statusType":"auto","x":980,"y":400,"wires":[]},{"id":"f0dbaae1.e6e608","type":"debug","z":"26f5fb49.791c54","name":"NO MATCH","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"'NO MATCH'","targetType":"jsonata","statusVal":"","statusType":"auto","x":990,"y":440,"wires":[]},{"id":"65d1ddbd.8cdd14","type":"inject","z":"26f5fb49.791c54","name":"GOOD REGEX MATCH NO","props":[{"p":"string","v":"foo","vt":"str"},{"p":"regex","v":"bar","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":360,"y":420,"wires":[["1738b231.f9025e"]]},{"id":"92ae5657.35f878","type":"inject","z":"26f5fb49.791c54","name":"BAD REGEX EXCEPTION","props":[{"p":"payload"},{"p":"regex","v":"[\\[","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"foobar","payloadType":"str","x":350,"y":460,"wires":[["1738b231.f9025e"]]},{"id":"5c1ead9e.719d84","type":"inject","z":"26f5fb49.791c54","name":"GOOD REGEX - MATCH YES","props":[{"p":"payload"},{"p":"regex","v":"foo","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"foo","payloadType":"str","x":360,"y":520,"wires":[["6f63530f.e737cc"]]},{"id":"6f63530f.e737cc","type":"switch","z":"26f5fb49.791c54","name":"msg.payload ~  msg.regex","property":"payload","propertyType":"msg","rules":[{"t":"regex","v":"regex","vt":"msg","case":false},{"t":"else"}],"checkall":"false","repair":false,"outputs":2,"x":690,"y":560,"wires":[["ab999332.1d4e7"],["2d28b3d4.76fabc"]],"outputLabels":["TRUE","FALSE"]},{"id":"ab999332.1d4e7","type":"debug","z":"26f5fb49.791c54","name":"MATCH","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"'MATCH'","targetType":"jsonata","statusVal":"","statusType":"auto","x":980,"y":540,"wires":[]},{"id":"2d28b3d4.76fabc","type":"debug","z":"26f5fb49.791c54","name":"NO MATCH","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"'NO MATCH'","targetType":"jsonata","statusVal":"","statusType":"auto","x":990,"y":580,"wires":[]},{"id":"8fddbc13.49e18","type":"inject","z":"26f5fb49.791c54","name":"GOOD REGEX MATCH NO","props":[{"p":"payload"},{"p":"regex","v":"bar","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"foo","payloadType":"str","x":360,"y":560,"wires":[["6f63530f.e737cc"]]},{"id":"279c010b.ab231e","type":"inject","z":"26f5fb49.791c54","name":"BAD REGEX EXCEPTION","props":[{"p":"string","v":"foobar","vt":"str"},{"p":"regex","v":"[\\[","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"str","x":350,"y":600,"wires":[["6f63530f.e737cc"]]},{"id":"158bf56c.c5e10b","type":"inject","z":"26f5fb49.791c54","name":"GOOD REGEX - MATCH YES","props":[{"p":"regex","v":"foo","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":360,"y":120,"wires":[["288c9672.db581a"]]},{"id":"288c9672.db581a","type":"switch","z":"26f5fb49.791c54","name":"j:exp ~ msg.regex","property":"'foo'","propertyType":"jsonata","rules":[{"t":"regex","v":"regex","vt":"msg","case":false},{"t":"else"}],"checkall":"false","repair":false,"outputs":2,"x":670,"y":160,"wires":[["f7050f94.0ddef"],["e10c107d.2ac0b"]],"outputLabels":["TRUE","FALSE"]},{"id":"f7050f94.0ddef","type":"debug","z":"26f5fb49.791c54","name":"MATCH","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"'MATCH'","targetType":"jsonata","statusVal":"","statusType":"auto","x":980,"y":140,"wires":[]},{"id":"e10c107d.2ac0b","type":"debug","z":"26f5fb49.791c54","name":"NO MATCH","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"'NO MATCH'","targetType":"jsonata","statusVal":"","statusType":"auto","x":990,"y":180,"wires":[]},{"id":"f0c9f7cd.90fc38","type":"inject","z":"26f5fb49.791c54","name":"GOOD REGEX MATCH NO","props":[{"p":"regex","v":"bar","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":360,"y":160,"wires":[["288c9672.db581a"]]},{"id":"aefa8f7e.cfc59","type":"inject","z":"26f5fb49.791c54","name":"BAD REGEX EXCEPTION","props":[{"p":"regex","v":"[\\[","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"str","x":350,"y":200,"wires":[["288c9672.db581a"]]},{"id":"13cf2eb5.279e61","type":"comment","z":"26f5fb49.791c54","name":"JSONata String Works Fine","info":"","x":710,"y":60,"wires":[]},{"id":"cefaeb81.3e7c78","type":"comment","z":"26f5fb49.791c54","name":"msg.* Strings Yield Blocking Exception","info":"","x":730,"y":300,"wires":[]}]
```

**Comment by dceejay** [comment]
How do we want to fix this ? the simple fix is to add a try catch around the regex invocation and just return false. If we want to create an error then we need to make this into a special case :-(

**Comment by plfinch** [comment]
The desired behavior is that a catchable and recoverable exception is thrown anytime the regex evaluates to invalid. A 'match' should not be given in the case of an invalid regex. This desired behavior is exactly what happens in the following Switch Node 'matches regex' scenarios with Property (target string) evaluating to 'foo' and regex evaluating to invalid expression '[\[':

1. Property specified as JSONata expression and regex specified as string.
2. Property specified as JSONata expression and regex specified as msg variable object part (or flow or global).

So the question becomes, how are the above properly functioning scenarios coded versus when the target string is specified as a message object part (or flow or global) which is the most common scenario? I have not looked at the Switch Node code but will if I find time today. It is interesting that what is changing between works and doesn't work is the source of the target string, not the source of the regex itself. I would have expected all that to be behind us and inconsequential when the regex is actually evaluated.

One other item of note. In the works-as-expected scenarios described above the recoverable exception thrown is:
`Invalid JSONata expression: Invalid regular expression: /[\[/: Unterminated character class`

The scanrios with non-recoverable exceptions throw:
`SyntaxError: Invalid regular expression: /[\[/: Unterminated character class`

Looks like the exceptions are raised at 2 completely different points in the code. Which, again, is odd since what is changing is the source of the target string and NOT the source of the regex containing the invalid exception.

**Comment by dceejay** [comment]
well - one id thrown by the jsonata evaluation and one by the regex evaluation so yes two different places.
As I said above it's easy enough to try/catch the regex error and make it return false (no match). Which is "a quick fix".
Depends if we want to actually raise a `node.error` to alert the user as to the real cause  - if so that is harder and will some extra re-plumbing.

**Comment by knolleary** [comment]
The node will now log an error in this scenario (that can be caught be the Catch node) and carry on processing the next message.
