### ISSUE TITLE
How to install a stable "LTS" version of node-red on Debian 10 "Buster"?

### ISSUE THREAD

**Issue by jayjupdhig** [node-red/node-red#2906]
Hi there

Question: How to install a stable "LTS" version of node-red on Debian 10 "Buster"?

I only can see some manuals about Debian 9 and Raspbian 9 or 10.

Thank you very very much for your feedbacks. :-)

**Comment by knolleary** [comment]
As the issue template says, please use the forum for questions.

**Comment by jayjupdhig** [comment]
ok
