### ISSUE TITLE
Change node silently fails if there is a space after msg.parameter name.

### ISSUE THREAD

**Issue by fredsparkle** [node-red/node-red#2911]
`[{"id":"f8556b5c.35f438","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"8131b01c.36f2e","type":"inject","z":"f8556b5c.35f438","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":370,"y":260,"wires":[["b645b487.e39c78"]]},{"id":"b645b487.e39c78","type":"change","z":"f8556b5c.35f438","name":"","rules":[{"t":"set","p":"doZone ","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":590,"y":260,"wires":[["2764c820.fa4988"]]},{"id":"2764c820.fa4988","type":"debug","z":"f8556b5c.35f438","name":"Change Node","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":830,"y":260,"wires":[]}]`

Test Procedure

1. Load the sample flow from above.
2. Click on the inject node and examine the debug output
3. There should be a parameter msg.doZone; which will be missing.
4. Edit the change node and remove the space after "doZone", save and deploy.
5. Click on the inject node and examine the debug output.
6. The msg.doZone parameter will now appear.

I got into this situation by modifying a number of change nodes with the contents on the clipboard which had a trailing space, after "doZone".

Since this is a user entered name field maybe you should trim leading and trailing spaces?

My Environment:

Node-red V1.2.9
Node-JS v14.15.5
NPM 6.14.11
Raspberry Pi Debian 5.10.11-v7l+
Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by knolleary** [comment]
It is worth noting that, with a space at the end, the input is highlighted in red to show it is invalid:

![image](https://user-images.githubusercontent.com/51083/112696531-eb9e2c00-8e7d-11eb-8685-9b4685117775.png)


There is a separate issue related to the fact the config error isn't surfaced when the editor dialog is closed.

**Comment by knolleary** [comment]
I have added validation code for the node so any invalid properties will cause the node to be marked invalid when the edit dialog is closed.
