### ISSUE TITLE
Error in Inject node does not mark the Inject node as incomplete and allows deployment

### ISSUE THREAD

**Issue by hardillb** [node-red/node-red#2914]
### What are the steps to reproduce?
Create a Inject node, change the topic value to be equal to `msg.` and do not fill anything in the text area.
Wire inject to debug node, deploy and hit inject button

```
[{"id":"73e15eff.866b3","type":"debug","z":"a98232e2.89bb4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":610,"y":360,"wires":[]},{"id":"ee29a71.86c0b58","type":"inject","z":"a98232e2.89bb4","name":"","props":[{"p":"payload"},{"p":"topic","v":"","vt":"msg"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":400,"y":360,"wires":[["73e15eff.866b3"]]}]
```
Error found while answering SO question:
https://stackoverflow.com/questions/66947913/cant-get-a-response-from-mysql-using-nodered-function/66950432#66950432

### What happens?
Error: Invalid property expression: zero-length

### What do you expect to happen?
Warning should be deployed as inject node is not properly configured

### Please tell us about your environment:

- [ x ] Node-RED version: 1.2.9
- [ x ] Node.js version: 12.22.0
- [ x ] npm version: 6.14.11
- [ x ] Platform/OS: Ubuntu 20.04.4
- [ x ] Browser: Firefox

**Comment by dceejay** [comment]
well indeed - even having the option msg. is odd as there is no input msg to the node - though in theory you could in rule 1 set msg.foo then refer to it in rule 2.
