### ISSUE TITLE
Deploy event custom callback is never called

### ISSUE THREAD

**Issue by laura-eprosima** [node-red/node-red#2917]
### What happens?
In eProsima we are developing a [plugin](https://github.com/ramp-eu/node-red-ros2-plugin/tree/feature/first_nodes) that includes new nodes to the Node-RED palette. 

The problem is that we try to add a callback on the `deploy` event within the node javascript constructor, but the callback is never called.

### What do you expect to happen?

We expect that when the deploy button is pressed and all the nodes in the canvas are deployed, Node-RED emits the `deploy` event and our callback is called.

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9
- [ ] Node.js version: 14.16.0
- [ ] npm version: 6.14.11
- [ ] Platform/OS: Linux
- [ ] Browser: Firefox

**Comment by hardillb** [comment]
Can you point to the actual code, then we don't have to look through the whole repository

**Comment by knolleary** [comment]
What deploy event are you referring to? Is this in the runtime or editor?

**Comment by laura-eprosima** [comment]
We are trying to capture the event emitted [here](https://github.com/node-red/node-red/blob/fad8dcd304728014551da41186d25db9f7320abd/packages/node_modules/%40node-red/editor-client/src/js/ui/deploy.js#L482), by using the following function:

```
RED.events.on("deploy", function() {
....
});
```

**Comment by hardillb** [comment]
You've not answered the question of where you are trying to do this in **your** code.

**Comment by laura-eprosima** [comment]
In this [line](https://github.com/ramp-eu/node-red-ros2-plugin/blob/57effe4714bce892da43f4fa82737e5f304305b6/src/publisher/publisher.js#L19)

**Comment by knolleary** [comment]
The deploy event is in the editor only. It is not an event that is exposed in the runtime.

There are a different set of events in the runtime depending on what exactly you are trying to do and what point of the deploy lifecycle you are interested in.

Not at my laptop currently, but will share a link a bit later.

**Comment by laura-eprosima** [comment]
We are interested in two points within the deploy lifecycle:
- The moment the deployment starts and the flows are stopped
- The moment the deployment finishes and the flows are restarted

**Comment by knolleary** [comment]
In the runtime you can use:
 - `flows:stopping`
 - `flows:stopped`
 - `flows:starting`
 - `flows:started`

**Comment by laura-eprosima** [comment]
We tested those events but every time there is a new deployment, the event is called once more than in the previous deploy. 
![Result](https://user-images.githubusercontent.com/52071480/113997251-3fcee600-9858-11eb-9dd6-5bb4046948e6.png)

**Comment by hardillb** [comment]
That's because you are adding the listener in the node constructor which is valued every time the node is instanciated

**Comment by knolleary** [comment]
That is because you are registering a new listener on the event inside your node constructor. So every time there is a deploy, a new listener gets registered. But you don't remove the listener in the node's own `close` event.

But of course when the flows are stopped and your node is closed, it will remove the event listener and you won't get the `flows:stopped` event. Likewise, if the event listener is only registered in the node constructor you'll never get the `flows:starting` event.

What are you trying to achieve here?

**Comment by laura-eprosima** [comment]
We need to launch another application when the deploy is finished and stop it before doing a new deploy, that's why we are interested in those events.

How we can remove the event listener? We check the [API documentation](https://nodered.org/docs/api/modules/v/1.0/@node-red_runtime_events.html) and there appear only two methods: `on` and `emit`.

**Comment by knolleary** [comment]
If you are doing it inside the node, then can you not just use the node's own 'close' event to know the flows are stopping and use the call to the node constructor as the sign the flows are starting?

**Comment by knolleary** [comment]
> How we can remove the event listener? We check the API documentation and there appear only two methods: on and emit

`RED.events` is an instance of `EventEmitter` - https://nodejs.org/api/events.html

**Comment by laura-eprosima** [comment]
> If you are doing it inside the node, then can you not just use the node's own 'close' event to know the flows are stopping and use the call to the node constructor as the sign the flows are starting?

We can use the node's close for stopping the application, but the case of the constructor is different as we need to wait until some data is configured before launching the program. However, the `flows:started` event works for us.

Additionally, instead of removing the listener on the node's close, we use `RED.events.once()` method.

**Comment by knolleary** [comment]
Closing as this is resolved.
