### ISSUE TITLE
File node outputs message before closing file

### ISSUE THREAD

**Issue by theonlypwner** [node-red/node-red#2921]
### What are the steps to reproduce?
Use the 'file' node with its output connected to a node that depends on the file.

### What happens?
The file is still locked when the file write node outputs a message to the next node.

### What do you expect to happen?
I expect the node to output after the file is closed.

### Please tell us about your environment:

- [x] Node-RED version: I observed this in 0.20.8 but the code shows this issue still in 1.3.1
- [x] Node.js version: 8.12.0
- [ ] npm version: irrelevant
- [x] Platform/OS: Windows 10
- [ ] Browser: irrelevant

In the code for 0.20.8 (https://github.com/node-red/node-red/blob/0.20.8/packages/node_modules/%40node-red/nodes/core/storage/50-file.js#L96-L163) and 1.3.1 (https://github.com/node-red/node-red/blob/1.3.1/packages/node_modules/%40node-red/nodes/core/storage/10-file.js#L97-L164), the code for the write looks like
```js
wstream.on("open", function() {
    wstream.end(buf, function() {
        nodeSend(msg);
        done();
    });
})
```

The node will output a message when [`callback` in `writable.end`](https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback) is called.

The problem is that when the write finishes, it emits the `'finish'` event, and a listener will close the file (because `autoClose` is `true`), and then a later listener will call `callback`. When the file close eventually finishes, it will emit a `'close'` event, which is not used by the node.

* `'finish'` handler calls `close` if `autoclose` is enabled https://github.com/nodejs/node/blob/v8.12.0/lib/fs.js#L2148-L2153
* `close` emits `'close'` event if successful https://github.com/nodejs/node/blob/v8.12.0/lib/fs.js#L2091-L2096
* `Writable.prototype.end` calls `endWritable` https://github.com/nodejs/node/blob/v8.12.0/lib/_stream_writable.js#L572
* `endWritable` registers `'finish'` event with the callback https://github.com/nodejs/node/blob/v8.12.0/lib/_stream_writable.js#L623-L626
* From the above, `callback` would be called before the `'close'` event.

To fix it, the code for the writes should look something like
```js
wstream.on("open", function() {
    wstream.once("close", function() {
        nodeSend(msg);
        done();
    });
    wstream.end(buf);
})
```

**Comment by dceejay** [comment]
looks good - do you want to create a pull request - or happy for us to cut/paste ?

**Comment by theonlypwner** [comment]
I'm OK if you cut/paste, but it appeared in multiple places in `10-file.js`, so you'd have to update all of them.

**Comment by dceejay** [comment]
I think the only other one is the else around line 170
