### ISSUE TITLE
JSON node: update ajv to 8.x

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#2923]
The `ajv` module is used by the JSON node. We currently use `6.12.6` - the latest available is `8.0.5`. There are a number of changes between these versions that will potentially impact end users of Node-RED.

A full migration guide is provided here: https://github.com/ajv-validator/ajv/blob/master/docs/v6-to-v8-migration.md

The main change of concern is that the module no longer supports JSON-Schema draft-04 - an old version that has long been superseded.

A summary of the supported JSON-Schema versions is here: https://ajv.js.org/guide/schema-language.html

This will need to be documented in the Node-RED 1.x -> 2.x migration guide.

**Comment by dceejay** [comment]
there was also a proposal by someone to handle schemas better / in the node etc - so we could get feedback direct from them as presumably they are using this at some level already.

**Comment by natcl** [comment]
On our side the migration to the more recent drafts is not an issue, draft-04 is indeed quite old at this point.
