### ISSUE TITLE
Parsing fails with Separator semicolon and first row contains column names

### ISSUE THREAD

**Issue by holgerpieta** [node-red/node-red#2925]
### What are the steps to reproduce?
Setup a flow that parses a semicolon-based CSV and set "first row contains column names" in the CSV node.
Example CSV:
```
col_a;col_b
1;2
```

Example flow:
```
[{"id":"36ab15aa.d8a9a2","type":"inject","z":"b5a4d88b.9f0a58","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":290,"y":140,"wires":[["c31bdf0b.728088"]]},{"id":"d12f4cb2.2313b","type":"debug","z":"b5a4d88b.9f0a58","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":750,"y":140,"wires":[]},{"id":"c31bdf0b.728088","type":"function","z":"b5a4d88b.9f0a58","name":"","func":"msg.payload = \"col_a;col_b\\n1;2\\n\"\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":460,"y":140,"wires":[["f7bed2cc.924de"]]},{"id":"f7bed2cc.924de","type":"csv","z":"b5a4d88b.9f0a58","name":"","sep":";","hdrin":true,"hdrout":"none","multi":"one","ret":"\\n","temp":"","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":610,"y":140,"wires":[["d12f4cb2.2313b"]]}]
```

### What happens?
Parsing fails and the output is not usable:
Payload:
`{"col_a;col_b":1}`

### What do you expect to happen?
Useful output:
`{"col_a":1,"col_b":2}`

### Please tell us about your environment:

- [ ] Node-RED version: v1.3.1 from docker container image
- [ ] Node.js version: As delivered in node-red docker image
- [ ] npm version: As delivered in node-red docker image
- [ ] Platform/OS: Raspberry Pi OS Buster 32 bit with ARMv8 64bit kernel, fully updated
- [ ] Browser: Firefox

**Comment by hardillb** [comment]
As a work around put a split node before the CSV node.
This will break the input string up into separate messages with one line in each and this looks to work properly

**Comment by hardillb** [comment]
This looks to be the case for any delimiter except for comma.

**Comment by dceejay** [comment]
yup - confirmed. will fix.
