### ISSUE TITLE
broken mqtt-broker config window (some languages)

### ISSUE THREAD

**Issue by heikokue** [node-red/node-red#2927]
### What are the steps to reproduce?
* select another language than en-US
* open the mqtt-broker config node 
* enable TLS checkbox

### What happens?
the i18n text of "Use TLS" does fit:

![grafik](https://user-images.githubusercontent.com/74769863/114285477-cd2c5900-9a57-11eb-9db6-d35c71f5fe89.png)
![grafik](https://user-images.githubusercontent.com/74769863/114285485-d3bad080-9a57-11eb-951f-4ba1e39d08cc.png)
![grafik](https://user-images.githubusercontent.com/74769863/114285489-d87f8480-9a57-11eb-8415-933a11405e42.png)

### What do you expect to happen?
here the correct of en-US:
![grafik](https://user-images.githubusercontent.com/74769863/114285549-517edc00-9a58-11eb-9bd9-94360704a583.png)

### Please tell us about your environment:
- [x] Node-RED version: 1.3.1
- [ ] Node.js version:
- [ ] npm version:
- [x] Platform/OS: W
- [x] Browser: Firefox 87.0

**Comment by heikokue** [comment]
@knolleary If you want, I could change the i18n-text of all other unfitting lanuages to "TLS" only.
I think, the checkbox and "TLS" are enough for the user to understand.
Here for example for DE: 
![grafik](https://user-images.githubusercontent.com/74769863/114285660-22b53580-9a59-11eb-95fb-0dc994d8a80e.png)
This would be pragmatic approach and the other language translators will have no work...

**Comment by knolleary** [comment]
I think changing it to `TLS` in all languages is probably okay. For Korean and Chinese I've updating it to say "Use TLS" to be a bit more consistent. The Russian and German translations for `Use TLS` wasn't much shorter than what they are now, so I have reduced that to just TLS. I've also given the label a little more width.
