### ISSUE TITLE
Want to be a contributors 

### ISSUE THREAD

**Issue by PmcFizz** [node-red/node-red#2928]
Hey, Node-Red developers, you've really developed a nice low code platform for the Internet of Things. 
I am a front-end developer in China, and I usually write some blogs. On CSDN, a tech blogging platform in China, it has more than 10,000 followers and 70w page views. 
I've written a series of articles about Node-red. The readers loved it. 
I've learned about Node-Red's architecture and now I'd like to try and contribute to the Node-Red community. 

Do you still need contributors? What are the simple tasks that can be assigned to contributors?

ps： 
[my blog link](https://fizzz.blog.csdn.net/)
[node-red articles](https://blog.csdn.net/github_35631540/category_10785682.html)

**Comment by knolleary** [comment]
Hi, thanks for making contact.

The best way to talk to us is through the project slack or forum - as explained by the issue template you've not used.

We're always open to contributors - it there a particular area you are interested in?

**Comment by PmcFizz** [comment]
thanks for your reply。 I am interested in UI layout   and translate to Chinese。

**Comment by knolleary** [comment]
Great. I'm sure the translations could do with some updates! 

As I mentioned, the best place to discuss items you'd like to contribute to is either the [forum](discourse.nodered.org) or [slack](https://nodered.org/slack).
