### ISSUE TITLE
Misspelling of variable causing reference error

### ISSUE THREAD

**Issue by zachowj** [node-red/node-red#2933]
### What are the steps to reproduce?

Create an editableList where the `addButton` option is a string.

### What happens?

`ReferenceError: addTitle is not defined` is thrown.

https://github.com/node-red/node-red/commit/60c8a2c5989e0655dab5d08415d943ca7d67a4c7 had a misspelled variable `addTittle`. Which causes `addTitle` to be undeclared on line 92 when `this.options.addButton` is of type `string`.

https://github.com/node-red/node-red/blob/39274b0c5dbd88650618639a3c03390bc7a4e31b/packages/node_modules/%40node-red/editor-client/src/js/ui/common/editableList.js#L73-L94

### What do you expect to happen?

Show an add item button with the custom label without throwing a reference error

### Please tell us about your environment:

- [x] Node-RED version: 1.31
- [ ] Node.js version: 
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Good timing - was just about to release 1.3.2.
