### ISSUE TITLE
HTTPIn converts content-type: "application/x-protobuf" to string 

### ISSUE THREAD

**Issue by digchg-mweiss** [node-red/node-red#2935]
"application/x-protobuf" refers to binary [Protocol Buffers](https://en.wikipedia.org/wiki/Protocol_Buffers) so output should be a Buffer

#1023 was a similar issue

Tested on Docker Image nodered/node-red:latest (created 2021-04-08)
NODE_VERSION | 10.24.1
YARN_VERSION | 1.22.5
NODE_RED_VERSION | v1.3.1

**Comment by knolleary** [comment]
Fixed in 1.3.3
