### ISSUE TITLE
typedInput label overflow when setting a to short width

### ISSUE THREAD

**Issue by Zehir** [node-red/node-red#2941]
### What are the steps to reproduce?
Create a custom node with this code in oneditprepare ;
```javascript
$(".input").typedInput({
    typeField: ".my-type-field",
    types: [
        {
            value: "set",
            label: "Set",
            icon: "fa fa-arrow-circle-right",
            hasValue: false
        },
        {
            value: "inc",
            label: "Increment",
            icon: "fa fa-arrow-circle-up",
            hasValue: false
        },
        {
            value: "dec",
            label: "Decrement by",
            icon: "fa fa-arrow-circle-down",
            hasValue: false
        }
    ]
});
$(".input").typedInput('width', '50px');
```

### What happens?
![image](https://user-images.githubusercontent.com/845225/115144324-65c06b80-a04c-11eb-83a0-0f867941e812.png)
![image](https://user-images.githubusercontent.com/845225/115144329-6bb64c80-a04c-11eb-92fd-8441276d360f.png)

### What do you expect to happen?
Having the label that don't overflow the input with `Inc...` or only display the icon.
Idea for fixing : Display the icon or having a seperate value for the label in the list and the label when selected.

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.1
- [ ] Node.js version: 15.3.0
- [ ] npm version: 7.0.14
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome 90 in private mode

**Comment by Zehir** [comment]
Note, I using a custom theme but the issue is identical without it
```javascript
{
    editorTheme: {
        page: {
            css: "my_user_dir/.node-red/node_modules/@node-red-contrib-themes/midnight-red/theme.css"
        },
        projects: {
            // To enable the Projects feature, set this value to true
            enabled: false
        }
    }
}

```

**Comment by knolleary** [comment]
Fixed by https://github.com/node-red/node-red/commit/9eb668ab30c9f99db8c40727e8fdcaeb5c941739
