### ISSUE TITLE
typedInput disable and disabled methods not working as expected

### ISSUE THREAD

**Issue by Zehir** [node-red/node-red#2942]
I think there is issue in the code and with the [documentation of typedInput](https://nodered.org/docs/api/ui/typedInput/).

### What are the steps to reproduce?
Use any typedInput.

### What happens?
Calling `$('#node-input-domain').typedInput('disable');` -> Do nothing.
Calling `$('#node-input-domain').typedInput('disable', true);` -> Disable the typedInput but the doc don't say that or we missing the 'enable' method.
Calling `$('#node-input-domain').typedInput('disabled');` -> return "disabled" which is not a boolean.
Calling `$('#node-input-domain').typedInput('disable', false);` -> Enable the typedInput.
Calling `$('#node-input-domain').typedInput('disabled');` -> return the jQuery element.

### What do you expect to happen?
Calling `$('#node-input-domain').typedInput('disable');` -> Disable the typedInput.
Calling `$('#node-input-domain').typedInput('disable', true);` -> Disable the typedInput -> Working
Calling `$('#node-input-domain').typedInput('disabled');` -> return `true`
Calling `$('#node-input-domain').typedInput('disable', false);` -> Enable the typedInput. -> Working
Calling `$('#node-input-domain').typedInput('enable');` -> Enable the typedInput. -> Alternate way but expected if we look other methods (show/hide).
Calling `$('#node-input-domain').typedInput('disabled');` -> return `false`

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.1
- [ ] Node.js version: 15.3.0
- [ ] npm version: 7.0.14
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome 90 in private mode

**Comment by knolleary** [comment]
Thanks for highlighting these inconsistencies. I've pushed a fix to tidy it up:

 - `typedInput('disabled')` now returns a boolean as expected
 - `typedInput('disable')` will disable the input
 - `typedInput('enable')` will enable the input
 - `typedInput('disable', value)` will disable the input if `value` is true-like, or enable it if false-like

**Comment by Zehir** [comment]
> Thanks for highlighting these inconsistencies. I've pushed a fix to tidy it up:
> 
>  - `typedInput('disabled')` now returns a boolean as expected
>  - `typedInput('disable')` will disable the input
>  - `typedInput('enable')` will enable the input
>  - `typedInput('disable', value)` will disable the input if `value` is true-like, or enable it if false-like
> 

Thanks for this quick fix
