### ISSUE TITLE
typed Input with no value is not removing focus class when unfocus + selected item of the list is not focused in the list

### ISSUE THREAD

**Issue by Zehir** [node-red/node-red#2945]
Edit : There is an other similar issue in the first comment If you want me to open a new issue tell me ;)

### What are the steps to reproduce?
Open a new change node,
Add some timestamp value
Focus the timestamp value and select something else.
### What happens?
The blue border is not removed when unfocus like the other inputs

### What do you expect to happen?
Don't have the blue border when unfocus.
This hapen every time the selected type has no value

I made a gif to make this more easier to understand.
![Qzi7xYUQFU](https://user-images.githubusercontent.com/845225/115460269-5d248c80-a228-11eb-989a-a626cc526588.gif)

### Please tell us about your environment:
- [ ] Node-RED version: 1.3.2
- [ ] Node.js version: v15.14.0
- [ ] npm version: 7.10.0
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome 90 in private mode

**Comment by Zehir** [comment]
I found a similar case with the selected option of the list. It's still the first item that is displayed as selected.
In the gif we can see that when the false is selected it's still true that is darker.
![HzGOSpXwqy](https://user-images.githubusercontent.com/845225/115463066-acb88780-a22b-11eb-98f3-c49ec111ed03.gif)

**Comment by Zehir** [comment]
Thanks @knolleary , did that fix the second issue too ?

**Comment by knolleary** [comment]
Yes, there are two separate commits, one for each issue.

**Comment by Zehir** [comment]
Perfect thanks à lot, you did a really good job with typedInput. It's verry easy to create new nodez with it
