### ISSUE TITLE
node-red-contrib-sap-node node installation Fail from manage palette

### ISSUE THREAD

**Issue by aadi1999** [node-red/node-red#2948]
### What are the steps to reproduce?
 - try to install node-red-contrib-sap-node from manage palette in node-red .
 
### What happens?

 

 If we try to install the sap hana node from manage palette it is failing to install.
 
1. Tested Node-Red Image using
docker run command using proxy network able to install SAP Hana node in the specified UserDir.
but same image using docker compose file with proxy network installation of SAP node is failing in specified UserDir.

 

2.Tried with root user using docker compose file Node installation is failed.

 

Error:

 

node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc48/hana-client.node: failed to map segment from shared object
TypeError: Cannot read property '__stopAllWork' of null
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @sap/hana-client@2.8.16 install: `node checkbuild.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @sap/hana-client@2.8.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-21T06_57_45_674Z-debug.log

 

### What do you expect to happen?
-it should install the sap hana node with docker compose also in the specified UserDir.

 

### Please tell us about your environment:

 

- [ ] Node-RED version: 1.2.5
- [ ] Node.js version: v10.19.0
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Docker / Debian OS
- [ ] Browser: Mozilla firefox/ Google Chrome

**Comment by hardillb** [comment]
That node is not part of the core of node-red, you probably need to raise this with the author directly.

If I remember correctly this is because the SAP code will not build on Alpine based Docker Images

**Comment by knolleary** [comment]
Closing as this isn't a core Node-RED issue.

As @hardillb says, the Node-RED docker images we provide are alpine based and may not contain all the build tools needed for every node out there. You may need to create your own docker image with the necessary bits in.
