### ISSUE TITLE
'Expand' button hidden behind scrollbar in function node editor

### ISSUE THREAD

**Issue by glynni** [node-red/node-red#2955]
### What are the steps to reproduce?
1. Create a function node and open the editor (not expanded)
2. Create enough new lines to exceed the editor space
3. Try to click the expand button

### What happens?
Expand button is hidden behind the scroll bar / not clickable

### What do you expect to happen?
Expand button to be clickable / not be hidden behind the scrollbar

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.3
- [ ] Node.js version: 14.16.0
- [ ] npm version: 6.14.11
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome
- [ ] running in Docker: No

**Comment by My-Random-Thoughts** [comment]
Can this be reopened, it looks like it's been regressed in version 2.0.3.

![image](https://user-images.githubusercontent.com/21334396/126903132-71c5e1e0-4b8b-4ed1-a4ae-baf1f1d3df72.png)

**Comment by elecpower** [comment]
Still an issue in 
Node-RED version: 2.1.3
Platform/OS: Windows 10
Browser: Chrome

**Comment by PeterHunt** [comment]
Just wanted to confirm that this issue returned some versions ago. I really use the function node very often and its a pretty PITA to expand the window with this very small, invisible button ;)
