### ISSUE TITLE
selected option in typedInput is not remembered when `hasValue == false`

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#2962]
### What are the steps to reproduce?

Add a typed input with options and `hasValue = false`

```js
    let _types = {
        value: "type",
        label: "Type",
        showLabel: true,
        hasValue: false,
        options: [
            { value: "byte", label: "byte" },
            { value: "int8", label: "int8" },
            { value: "uint8", label: "uint8" },
            { value: "int16le", label: "int16 (le)" },
            { value: "int16be", label: "int16 (be)" },
            //... snip for brevity
            { value: "ucs2", label: "ucs2" },
            { value: "latin1", label: "latin1" },
            { value: "binary", label: "binary" },
            { value: "buffer", label: "buffer" },
        ]
    }


    let row1_1 = $('<div/>', { style: "display:flex;", class: "buffer-parser-row-item" }).appendTo(row1);
    let typeField = $('<input/>', { class: "node-input-item-property-type", type: "text", width: "165px" })
        .appendTo(row1_1)
        .typedInput({ types: [_types] })

```

### What happens?
Selected item is not highlighted/remembered when clicking the RH dropdown 
![lZpFd7NXq8](https://user-images.githubusercontent.com/44235289/116236429-f7b82a80-a756-11eb-955d-1708feea7b77.gif)

If I change [this code](https://github.com/node-red/node-red/blob/0e02d03d9a87aa2fb47f7dd8623ce037b2199271/packages/node_modules/%40node-red/editor-client/src/js/ui/common/typedInput.js#L659) from this...

```js
                    if (opt.hasValue) {
                        this.optionValue = o.value;
                        this.input.trigger('change',[this.propertyType,this.value()]);
                    }
```

to this...

```js
                    this.optionValue = o.value;
                    if (opt.hasValue) {
                        this.input.trigger('change',[this.propertyType,this.value()]);
                    }
```

... then `this.optionValue` gets set and the selection is remembered...

![EPw1zMTPXO](https://user-images.githubusercontent.com/44235289/116236753-57aed100-a757-11eb-8c01-b1ecc9a50939.gif)

However I do not have enough knowledge to know the ramifications of setting `this.optionValue` for a typedInput when `hasValue = false`.

### What do you expect to happen?

The chosen/set item to be highlighted/selected

### Please tell us about your environment:

- [ ] Node-RED version: <= V1.33 and V2.0.0-beta.1
- [ ] Node.js version: 14.16.1
- [ ] npm version: 6.14.12
- [ ] Platform/OS: Win 10
- [ ] Browser: Chrome latest

**Comment by knolleary** [comment]
I *think* this was fixed a few days ago by https://github.com/node-red/node-red/commit/23a5cb1917fa6f7fd80e8cae8d04c753c76eecbb#diff-3856852af6b22821b9da448a6a510bd2342bf80111ff1efe7b1c5675f39c8a79

**Comment by Steve-Mcl** [comment]
Hi Nick, I can confirm that does indeed fix it.  

I missed this due to being on dev branch at the moment. 

Sorry for the noise.

Thanks.
