### ISSUE TITLE
Custom themes are not loaded when debug is opened in a new window

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#2968]
While investigating the cause for [this issue](https://github.com/node-red-contrib-themes/midnight-red/issues/27), I noticed that the custom themes are not loaded when debug is opened in a new window.

<img width="600" alt="Screen Shot 2021-04-28 at 6 57 45 PM" src="https://user-images.githubusercontent.com/29807944/116483038-52837c00-a854-11eb-8300-df2f4ce2996f.png">
<img width="585" alt="Screen Shot 2021-04-28 at 6 57 39 PM" src="https://user-images.githubusercontent.com/29807944/116483049-58795d00-a854-11eb-9156-457b930f257f.png">

And adding the custom theme's CSS.

<img width="600" alt="Screen Shot 2021-04-28 at 6 58 33 PM" src="https://user-images.githubusercontent.com/29807944/116483093-6fb84a80-a854-11eb-976f-51c8c088cd2b.png">
<img width="585" alt="Screen Shot 2021-04-28 at 6 58 30 PM" src="https://user-images.githubusercontent.com/29807944/116483098-734bd180-a854-11eb-8222-6c5a21262944.png">

### What are the steps to reproduce?

Open debug in a new window.

### What happens?

Custom themes are not loaded.

### What do you expect to happen?

Custom themes to be loaded.

### Please tell us about your environment:

- [x] Node-RED version: v1.3.3
- [x] Node.js version: v12.22.1
- [x] npm version: 6.14.12
- [x] Platform/OS: macOS Big Sur 11.2.3
- [x] Browser: Chrome / Safari

**Comment by hardillb** [comment]
Please fill out the complete template when opening issues, it supplies the information we need to work on a problem

**Comment by bonanitech** [comment]
Oops, sorry. Done!
