### ISSUE TITLE
Oracle InstantClient Support

### ISSUE THREAD

**Issue by ronny35** [node-red/node-red#2970]
Hello,

In order to use node-red-contrib-oracledb-mod  module, Oracle InstantClient binary is needed.
I do not found documentation about Node-RED Docker build about it.

Could you provide me a Dockerfile example please ?

**Comment by knolleary** [comment]
Please use the forum as the issue template asks.

**Comment by ronny35** [comment]
This discussion has not solution : https://discourse.nodered.org/t/oracle-database-in-node-red-docker/11691

**Comment by knolleary** [comment]
That's from two years ago. I suggest you post a new thread. We don't know anything about oracle instant client, so not going to be able to give you a working dokerfile for it.

**Comment by dceejay** [comment]
You will probably need to build your own custom using the Debian based Dockerfile so it has all the build tools in.
The default image uses the cut down Alpine image that often doesn't have the necessary bindings for native code like database drivers. see https://github.com/node-red/node-red-docker/tree/master/docker-custom
