### ISSUE TITLE
Editor cursor is misaligned on Linux

### ISSUE THREAD

**Issue by metronidazole** [node-red/node-red#2972]
### What are the steps to reproduce?
0. Use linux
1. Create a node e.g. function node
2. Edit the node with the built in text editor
3. Attempt to precisely enter text with the cursor

See demo https://i.imgur.com/dvvm1gV.gif

The problem doesn't occur on Android/Firefox. I've tried changing the zoom level on my browser but that didn't help. I suspect it could be a font issue, but I'm not sure how best to proceed.

### What happens?
Text is entered away from the actual cursor position.

### What do you expect to happen?
Text is entered exactly at the cursor position.

### Please tell us about your environment:

- [x] Node-RED version: 1.3.3
- [x] Node.js version: 14.16.1
- [x] npm version: 6.14.12 
- [x] Platform/OS: Arch Linux (also tested in Android/Firefox - bug is not reproducible there)
- [x] Browser: Firefox & Chromium

**Comment by Steve-Mcl** [comment]
This might be helpful - could you test and feedback?

https://gist.github.com/gnuns/75badb58795ac78dc96a0ebaf5aa68f5

**Comment by metronidazole** [comment]
Cool, so based off that and further reading, it seems the issue was that the default fontconfig configuration substitutes fonts that don't have the same spacing as the ones expected. 

I installed fonts-meta-extended-lt (AUR) and enabled (symlinked) the supplied fontconfig. That seemed to fix the problem.

Thanks!
