### ISSUE TITLE
Nodes remain after removing flow

### ISSUE THREAD

**Issue by upkarlidder** [node-red/node-red#2977]
### What are the steps to reproduce?
1. Import [this flow](https://raw.githubusercontent.com/johnwalicki/Node-RED-Water-Sustainability-Dashboard/master/flows/atlantawatershed.json)
2. remove flow
3. re-import the flow again
4. Node-RED complains `You are importing existing nodes`
![image](https://user-images.githubusercontent.com/3187457/117372958-3ea4cf00-ae7f-11eb-837e-903e996416cb.png)

### What happens?
Node-RED complains `You are importing existing nodes`

### What do you expect to happen?
Not get the error since I already delete the old flow.

### Please tell us about your environment:

- [ ] Node-RED version:v1.3.4
- [ ] Node.js version:v14.16.1
- [ ] npm version:6.14.12
- [ ] Platform/OS:Linux fedora 5.11.15-300.fc34.x86_64
- [ ] Browser:latest Chrome

@jritten

**Comment by hardillb** [comment]
How did you remove the flow?

Did you also remove the config nodes that were included in the original flow?

**Comment by upkarlidder** [comment]
1. I removed the flow using the "remove flow" shortcut
![image](https://user-images.githubusercontent.com/3187457/117373719-a7407b80-ae80-11eb-91b3-b1a11f5bd5c0.png)

2. This dialog opens up when I click on "view nodes"
![image](https://user-images.githubusercontent.com/3187457/117373695-9abc2300-ae80-11eb-8c50-7cf70042f395.png)

3. I did not remove the nodes before removing the flow. Just assumed the nodes will go away if I remove the parent flow.

**Comment by knolleary** [comment]
By default, config nodes are global - meaning they aren't tied to any one flow. Deleting a flow won't delete global config nodes.

You can change the scope of a config node to a single flow using the select box in the footer of its edit dialog. And then it will get deleted when the flow is deleted.

**Comment by upkarlidder** [comment]
Thank you @knolleary and @hardillb. Makes sense.
