### ISSUE TITLE
node-red deployed on kubernetes(as a pod) to intereact with azure iot edge 

### ISSUE THREAD

**Issue by omarine** [node-red/node-red#2992]
### What are the steps to reproduce?

deploy node-red via helm /or as a module to azure kubernetes services
### What happens?

![image](https://user-images.githubusercontent.com/13197345/119336267-bea7a300-bc8d-11eb-85a6-e71aec7d60d2.png)

### What do you expect to happen?
node-red (Module Client - input ) should be able to receive telemetry from another module
### Please tell us about your environment:

- [ ] Node-RED version: 1.3.4
- [ ] Node.js version: 10.24.1
- [ ] npm version: n/a
- [ ] Platform/OS: azure kubernetes services
- [ ] Browser:

**Comment by knolleary** [comment]
Hi, please use the forum if you have questions about how to use Node-RED in particular environments.

This issue list is for bugs etc in the core of the project.

**Comment by knolleary** [comment]
Closed as this has been moved over to the forum.
