### ISSUE TITLE
Function node uses "node.done" in comments

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red#2998]
Hey guys,

### What are the steps to reproduce?

In the following example flow, the Complete-node watches both function nodes.
But only the first function node will trigger the Complete-node:

![image](https://user-images.githubusercontent.com/14224149/120041490-9d85e000-c008-11eb-8c2f-084dc7e6d606.png)
```
[{"id":"e48085d7.32f838","type":"complete","z":"c2a7925b.6e143","name":"","scope":["53955b4b.c098b4","55bb2150.5fdde"],"uncaught":false,"x":170,"y":580,"wires":[["c8ab2289.02c92"]]},{"id":"c8ab2289.02c92","type":"debug","z":"c2a7925b.6e143","name":"Msg completed","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":380,"y":580,"wires":[]},{"id":"53955b4b.c098b4","type":"function","z":"c2a7925b.6e143","name":"Function without comment","func":"node.send(msg)","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":420,"y":480,"wires":[[]]},{"id":"dc9eb150.c058","type":"inject","z":"c2a7925b.6e143","name":"Test 1","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Test 1","payloadType":"str","x":170,"y":480,"wires":[["53955b4b.c098b4"]]},{"id":"55bb2150.5fdde","type":"function","z":"c2a7925b.6e143","name":"Function with comment","func":"/*setTimeout(function() {\n    msg['payload'] = 'New payload';\n    node.send([msg]);\n    node.done();\n}, 0);*/\nnode.send(msg)","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":410,"y":520,"wires":[[]]},{"id":"1a07acc9.efedd3","type":"inject","z":"c2a7925b.6e143","name":"Test 2","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Test 2","payloadType":"str","x":170,"y":520,"wires":[["55bb2150.5fdde"]]}]
```

### What happens?
The second function node contains (compared to the first function node) only an extra comment, including `node.done()`.  It doesn't matter if it is a single line (`//`) or multiline (`/* */`)  comment.

Due to this comment, we will pass the regex test at line 110 of the Function-node:

![image](https://user-images.githubusercontent.com/14224149/120041949-7ed41900-c009-11eb-88cc-9b49ece44e9c.png)

Which means `handleNodeDoneCall` becomes false at line 111.
As a result - when a message has been processed by the Function node - that message won't be send to the Complete node: 

![image](https://user-images.githubusercontent.com/14224149/120042484-75977c00-c00a-11eb-92e1-9546720cc341.png)

### What do you expect to happen?
I expect a `node.done` to be ignored when it is inside a comment.

Perhaps this could be solved by removing the comments from node.func (via a temporary variable), before passing the source code to the regex check on line 110?  I mean something like this:
```
// Remove comments e.g. based on a regex from https://stackoverflow.com/a/5989450
var funcWithoutComments = node.func.replace(/some_regex_to_remove_comments/g, "");

if (/node\.done\s*\(\s*\)/.test(funcWithoutComments )) {
   handleNodeDoneCall = false;
}
```

Thanks!
Bart

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.4
- [ ] Node.js version: 12.19.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
I will admit, the detection for `node.done` is a bit of a hack. We can certainly improve the regex to cover more cases, but there will still remain plenty of edge cases that could result in false-positive/negatives.

The only fully reliable way is to do a full parse of the JavaScript to look for the call... so that's what we'll done.

**Comment by bartbutenaers** [comment]
Your new approach is indeed much better.
Thanks!
