### ISSUE TITLE
Chinese translation bug

### ISSUE THREAD

**Issue by kervin521** [node-red/node-red#3002]
### What happens?
packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json

Line number：651

### What do you expect to happen?
上下午 --> 上下文
### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9 +
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
@kazuhitoyokoi can we get this suggested change reviewed?

**Comment by kazuhitoyokoi** [comment]
These characters are famous in Japanese but I'm not sure about the word meaning in Chinese.

@JiyeYu @xiuqi08 Could you help the issue to answer?
Which is the best as Chinese translation of ["context"](https://github.com/node-red/node-red/blob/1.3.5/packages/node_modules/@node-red/editor-client/locales/en-US/editor.json#L672),  "上下午" or "上下文"?
Additionally, it is the same among [Simplified Chinese (zh-CN)](https://github.com/node-red/node-red/blob/1.3.5/packages/node_modules/%40node-red/editor-client/locales/zh-CN/editor.json#L651) and [Traditional Chinese (zh-TW)](https://github.com/node-red/node-red/blob/1.3.5/packages/node_modules/%40node-red/editor-client/locales/zh-TW/editor.json#L651)?

**Comment by JiyeYu** [comment]
上下文 is correct. @kazuhitoyokoi 
Sorry, it's a typo. I will correct it.

**Comment by kazuhitoyokoi** [comment]
@JiyeYu Great! Thank you for submitting the pull request. 👍
