### ISSUE TITLE
Commit messages not shown (possible code injection)

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#3006]
### What are the steps to reproduce?
In project mode, create a commit message following the conventional commit standard (for example,`feat(users): allow deletion of users`. 

### What happens?
The commit message is not shown in the History sidebar.
See screenshot below.

### What do you expect to happen?
It should appear.

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.5
- [ ] Node.js version: 14
- [ ] npm version: -
- [ ] Platform/OS: Docker
- [ ] Browser: Safari

<img width="2145" alt="image" src="https://user-images.githubusercontent.com/77556/120829669-abb58e00-c52b-11eb-8d99-1676de012e02.png">

**Comment by natcl** [comment]
So on further testing:
`alert(hey)` works
`alert(hey):` works too
`alert(hey):` test doesn't show up

**Comment by knolleary** [comment]
There's no code injection issue here. Just an over greedy regex whilst parsing out the commit log. Now fixed.

**Comment by natcl** [comment]
Thanks!
