### ISSUE TITLE
Custom icons cannot be used in appearance section

### ISSUE THREAD

**Issue by antoine-em** [node-red/node-red#3013]
> Note : Originally opened on the forum here -> [Related link for the Forum](https://discourse.nodered.org/t/custom-icons-cannot-be-used-in-appearance-section/46905)

### What are the steps to reproduce?
- Create a custom node
- Add some custom svg images in the `icons` folder
- Add the node from the palette in the wiresheet and check the `appearance` section
- Click on the `icon` button and select one of the other svg resources added in your icons folder

### What happens?
The icon is not changed after being selected.

### What do you expect to happen?
The icon to be changed accordingly to the selection.

### Please tell us about your environment:
- [x] Node-RED version: v1.3.5-git
- [x] Node.js version: v16.2.0
- [x] npm version: 7.13.0
- [x] Platform/OS: Darwin 20.5.0 x64 LE
- [x] Browser: Firefox 88.0.1 (64-bit)

**Comment by antoine-em** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/59947685/121343261-7363e480-c95d-11eb-82a2-5759be76298d.png">

If I select any other icon in this list the selection is failing.
Any other icons, it is working.

**Comment by knolleary** [comment]
Hi @antoine-em 

I've tried to reproduce this locally on 1.3.5 and it appears to be working for me.

When you say 'the icon is not changed' - is that after you close the edit dialog?

I notice your svg icons appear black rather than the expected white. As an experiment, could you try with a png icon instead? There may be something about your svgs that is causing an issue, although I'm not sure what that would be.

Is the src for your node available somewhere I can have a look and try to recreate?

**Comment by antoine-em** [comment]
@knolleary 

Thank you for checking it.
I made the change from svg to png but the issue is the same.
What I have noticed is that the name/path is changed properly (cf. hover label), but the icon remains unchanged.

https://user-images.githubusercontent.com/59947685/121499348-43c5e280-ca18-11eb-838e-1689f00ef3b6.mov

> Is the src for your node available somewhere I can have a look and try to recreate?
Unfortunately I cannot share the whole code. But I can share the html file if needed.

**Comment by knolleary** [comment]
Can you check the browser console for any error messages?

**Comment by antoine-em** [comment]
This time in Chrome but same issue.
Unfortunately I cannot see any trace in the console.
Shall I turn my Node-RED instance in debug mode for more verbosity ?

https://user-images.githubusercontent.com/59947685/121500848-a23f9080-ca19-11eb-9f51-5076b35dc3a7.mov

**Comment by knolleary** [comment]
I noticed in your video your module name has a scope (the `@part`). Sure enough, our icon path parsing code in the editor wasn't handling scoped modules.

Fix pushed to master.

**Comment by antoine-em** [comment]
Thank you very much for the quick fix !
Sorry I am not familiar with the release deployment of this project. 
May I ask you how / when would be produced the new npm containing the changes you've pushed on the master branch ?

**Comment by dceejay** [comment]
we released v2 beta yesterday with it in. We will probably do another 1.x release in a few weeks around the same time we release 2.0.  We tend to not rush out releases for cosmetic fixes, and usually bundle up a few at a time.

**Comment by antoine-em** [comment]
@dceejay 
Thank you for your explanations, I understand and looking forward to updating it 👍 🙂
