### ISSUE TITLE
Unable to change log level in setting.js

### ISSUE THREAD

**Issue by fabrix76** [node-red/node-red#3014]
looking my node-red running on raspberry pi, there are a lot of log entries per second of info as severity.
changing log level to warn in setting.js and restarting daemon, it continue to generate this log.
moreover this, the same log is written in daemon.log (according rsyslog default configuration) and syslog.
I like to maintain the default rsyslog configuration i need to reduce the verbosity of node-red, but it seems there isn't any way to do this

update:
I had also tried to specify configuration file in startup script /usr/bin/node-red-start /usr/bin/node-red-pi but it's always the same level

### What are the steps to reproduce?
changing log level to warn in setting.js and restarting daemon (service nodered restart)
### What happens?
any other logging level is ignored, it's always at information level
### What do you expect to happen?
the change of log verbosity of course
### Please tell us about your environment:

- [ ] Node-RED version: 1.2.5 and 1.3.5 
- [ ] Node.js version: v12.22.1
- [ ] npm version: 6.14.12
- [ ] Platform/OS: rasbian 10.9
- [ ] Browser: firefox
- [ ] running in Docker: no, installed via github script as in documentation for raspberry

**Comment by hardillb** [comment]
Which `settings.js` file are you editing? What is the full path to the file?

**Comment by fabrix76** [comment]
Hi Hardbill, thank you for lightspeed reply, it has been installed as root, so the path is in /root/.node-red/settings.js

**Comment by fabrix76** [comment]
I had also tried to specify configuration file in startup script /usr/bin/node-red-start /usr/bin/node-red-pi but it's always the same level

**Comment by hardillb** [comment]
The service doesn't run as root unless you have specifically modified the service definition file, check if there is a `/home/pi/.node-red/settings.js`

The settings file that is being used is explicitly logged at the start of the output when it starts.

**Comment by fabrix76** [comment]
Looking pi directory ( /home/pi/ ) there isn't .node-red directory.
installation has been done from root (not using sudo from pi user, but directly root)

**Comment by fabrix76** [comment]
this is the output of /usr/bin/node-red-start

Start Node-RED

Once Node-RED has started, point a browser at http://192.168.1.23:1880
On Pi Node-RED works better with the Firefox or Chrome browser

Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot

To find more nodes and example flows - go to http://flows.nodered.org

Starting as root systemd service.
10 Jun 16:16:18 - [warn] Projects disabled : editorTheme.projects.enabled=false
10 Jun 16:16:18 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
CTOR: MessageCounterNode
INFO! 2 | seconds | true
timeToNextTick: 1186
CTOR: MessageCounterNode
INFO! 2 | seconds | true
timeToNextTick: 1183
2021-06-10T14:16:20.360Z
INFO: 2 | seconds | true
timeToNextTick: 1629
2021-06-10T14:16:20.372Z
INFO: 2 | seconds | true
timeToNextTick: 1626

**Comment by hardillb** [comment]
Add some of the sample log output you are trying to reduce, because apart from the logs about startup the only default output is when there is a flow deployment.

Anything else will either be coming from debug nodes set to output to the console as well as the sidebar or something specific to the nodes you are using which will not be effected by Node-RED's logging levels

**Comment by hardillb** [comment]
Yep, that output is coming from a 3rd party node (probably the MessageCounterNode) and not something Node-RED has any control over.

**Comment by hardillb** [comment]
Also the top of the log has been missed, but should be available with the `node-red-log` command

**Comment by fabrix76** [comment]
the flood is this
Jun 10 16:18:46 meeter Node-RED[17299]: CTOR: MessageCounterNode
Jun 10 16:18:46 meeter Node-RED[17299]: INFO! 2 | seconds | true
Jun 10 16:18:46 meeter Node-RED[17299]: timeToNextTick: 1580
Jun 10 16:18:46 meeter Node-RED[17299]: CTOR: MessageCounterNode
Jun 10 16:18:46 meeter Node-RED[17299]: INFO! 2 | seconds | true
Jun 10 16:18:46 meeter Node-RED[17299]: timeToNextTick: 1576
Jun 10 16:18:48 meeter Node-RED[17299]: 2021-06-10T14:18:48.006Z
Jun 10 16:18:48 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:48 meeter Node-RED[17299]: timeToNextTick: 1983
Jun 10 16:18:48 meeter Node-RED[17299]: 2021-06-10T14:18:48.018Z
Jun 10 16:18:48 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:48 meeter Node-RED[17299]: timeToNextTick: 1980
Jun 10 16:18:48 meeter Node-RED[17299]: Found BMx280 chip ID 0x60 on bus i2c-1, address 0x76
Jun 10 16:18:50 meeter Node-RED[17299]: 2021-06-10T14:18:50.001Z
Jun 10 16:18:50 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:50 meeter Node-RED[17299]: timeToNextTick: 1997
Jun 10 16:18:50 meeter Node-RED[17299]: 2021-06-10T14:18:50.003Z
Jun 10 16:18:50 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:50 meeter Node-RED[17299]: timeToNextTick: 1995
Jun 10 16:18:52 meeter Node-RED[17299]: 2021-06-10T14:18:52.000Z
Jun 10 16:18:52 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:52 meeter Node-RED[17299]: timeToNextTick: 1998
Jun 10 16:18:52 meeter Node-RED[17299]: 2021-06-10T14:18:52.006Z
Jun 10 16:18:52 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:52 meeter Node-RED[17299]: timeToNextTick: 1992
Jun 10 16:18:54 meeter Node-RED[17299]: 2021-06-10T14:18:54.000Z
Jun 10 16:18:54 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:54 meeter Node-RED[17299]: timeToNextTick: 1998
Jun 10 16:18:54 meeter Node-RED[17299]: 2021-06-10T14:18:54.005Z
Jun 10 16:18:54 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:54 meeter Node-RED[17299]: timeToNextTick: 1993

but take in mind, my flow get every 0.005 secs a measurement from a dac, so it's normal to get this flood, the best thing should be to increase nodered log level, i don't need info, warn or error could be right for me


this is ste starting log from node-red-log output
Started Node-RED graphical event wiring tool.
10 Jun 16:22:30 - [warn] Projects disabled : editorTheme.projects.enabled=false
10 Jun 16:22:30 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
CTOR: MessageCounterNode
INFO! 2 | seconds | true
timeToNextTick: 1129
CTOR: MessageCounterNode
INFO! 2 | seconds | true
timeToNextTick: 1125
2021-06-10T14:22:32.411Z
INFO: 2 | seconds | true
timeToNextTick: 1577
2021-06-10T14:22:32.424Z
INFO: 2 | seconds | true
timeToNextTick: 1574
Found BMx280 chip ID 0x60 on bus i2c-1, address 0x76
2021-06-10T14:22:34.000Z
INFO: 2 | seconds | true
timeToNextTick: 1998
2021-06-10T14:22:34.003Z
INFO: 2 | seconds | true
timeToNextTick: 1995

**Comment by fabrix76** [comment]
sorry but the issue isn't regarding the flood, but changing verbosity level it doesn't work.

**Comment by dceejay** [comment]
Thanks - please add a comment here or a link to it so we can track and close.

**Comment by hardillb** [comment]
It is working, the line listing which settings file you are using is at INFO level, which is why it's missing from the output you've posted (hence proving it has been used).

```
Jun 10 16:18:54 meeter Node-RED[17299]: 2021-06-10T14:18:54.000Z
Jun 10 16:18:54 meeter Node-RED[17299]: INFO: 2 | seconds | true
Jun 10 16:18:54 meeter Node-RED[17299]: timeToNextTick: 1998
```
That output while containing the label "INFO" is not using the Node-RED logging system.

**Comment by dceejay** [comment]
Actually there is already an issue and a pull request from 2018 - https://github.com/PKGeorgiev/node-red-contrib-message-counter/pull/4
so you may be out of luck - though the author is still active on github.

**Comment by fabrix76** [comment]
ahh, now it's clear! :)
reading INFO i think it was the severity .... that log is full of info lines.... ok ok, now it's all clear, so it sound strange that in 1.2.5 and 1.3.5 version of node-red there is the same issue in logging.

Ok guys, thank you very much

**Comment by fabrix76** [comment]
if someone need
looking message-counter.js (3rd party mod) there is 

function measure(isReset) {
          
          console.log(new Date());
          console.log("INFO: " + node.interval + " | " + node.units + " | " + node.alignToClock);

comment this two line and it's done.
Thank you again guys
