### ISSUE TITLE
File In node does not pass extra message properties to the output in msg per line mode

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#3034]
### What are the steps to reproduce?
Configure a File In node and set it to output a message per line.  Inject a message with an additional message property.

### What happens?
The additional message property is not present in the messages sent

### What do you expect to happen?
Additional message properties should be preserved.  If the output is set to single string then properties are preserved.

### Please tell us about your environment:

- [ ] Node-RED version: 1.3.5
- [ ] Node.js version: 16.3.0
- [ ] Platform/OS: Ubuntu on PC
- [ ] Browser: Firefox

**Comment by knolleary** [comment]
ref https://discourse.nodered.org/t/how-to-persist-a-message-property-between-nodes/47553

**Comment by dceejay** [comment]
This was originally a conscious decision not to append them. If you have a 500,000 line log file (say) and a large input message then we have to clone that 500,000 times which may hit performance somewhat. The usual use case for splitting per line is for reading large files in order to boost performance so cloning seemed like a bad thing to do.
Of course we can revisit that decision.

**Comment by colinl** [comment]
Good points.  It is difficult to know what the best route is in such cases.

**Comment by dceejay** [comment]
Given that the expectation is that they should be there - and indeed as Steve points out in the thread using a split node does preserve them - then I guess we should probably change it.
(looking at the code I note we do copy over just the msg.topic and msg.filename)

**Comment by knolleary** [comment]
No, we should not change it. That would be a big change in behaviour. Both behaviours are reasonable and next week someone will raise an issue saying the behaviour they relied on had changed.

I suggest it is made an option on the node when 'msg per line' is selected with the default to be the existing behaviour.
