### ISSUE TITLE
While trying to install/update or remove any node, its gives an error and fails`

### ISSUE THREAD

**Issue by the100rabh** [node-red/node-red#3036]
### What are the steps to reproduce?
Click on to install a new node or remove or update an existing node

### What happens?
It fails. The the message in logs is as follows 

```
17 verbose Linux 5.10.17-v7+
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "remove" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "node-red-contrib-nbrowser"
19 verbose node v10.24.1
20 verbose npm  v6.14.12
21 error Unexpected token ` in JSON at position 73799 while parsing near '...V/1PA9BvXnCNQ�"
21 error     `   },
21 error   $    "parp...'
22 verbose exit [ 1, true ]
```

### What do you expect to happen?

It should not throw this error and atleast tell me which file is having a parsing issue.

### Please tell us about your environment:

- [x] Node-RED version: 1.3.5
- [x] Node.js version: 10.24.1
- [x] npm version: 6.14.12
- [x] Platform/OS: Rpi Docker image
- [x] Browser: firefox

**Comment by hardillb** [comment]
This looks like a npm problem and is going to either be a problem with a file downloaded from the network or a corrupted package.json in the /data directory.

Can you test by running a shell in the container and trying to us npm to install the package on the command line.

You can get a shell in the container by running something like:

```
docker exec  -it node-red /bin/bash
```

Where `node-red` is the name of the container instance (last entry in the `docker ps` output.

You can also cat the `/data/package.json` file to check it's content.

Also worth asking, have you mounted a directory from the pi on `/data` or are you using a named volume?

**Comment by the100rabh** [comment]
I did load the `/data` using the named volume. It seems package-lock.json was corrupted. I deleted this and now its working fine now. Thanks for the help. 

Also it seems weird that my docker volume files are not being updated anymore. It seems a little scary to me now.

**Comment by the100rabh** [comment]
Please ignore it was probably docker at fault there. Thanks. I think all is good here.
