### ISSUE TITLE
Incorrect height of selecting nodes dialog

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#3045]
### What are the steps to reproduce?
1. Place complete node to the workspace.
2. Open the node property UI.
3. Click the "Select nodes..." button.

### What happens?
Notification dialog has incorrect height. Therefore, entire buttons are not visible.

![image](https://user-images.githubusercontent.com/20310935/124126609-cee54600-dab5-11eb-81b1-16ce76d9ff14.png)

### What do you expect to happen?
Notification dialog has correct height. The following screenshot is flow editor in Node-RED v1.3.4.

![image](https://user-images.githubusercontent.com/20310935/124126627-d3a9fa00-dab5-11eb-8170-0c626fe9ca4d.png)

This problem seems to come from [the commit](https://github.com/node-red/node-red/commit/ed3aa8189f2a0e59de71cf9bf0ac539e1a02d91a#diff-3f65d896ccbf0f068eadd0531391d587cd232ca7e77a94063125cab892d58509) between v1.3.4 and v1.3.5.

### Please tell us about your environment:

- [x] Node-RED version: v2.0.0-beta.1
- [x] Node.js version: v16.1.0
- [x] npm version: v7.11.2
- [x] Platform/OS: Ubuntu 21.04 (WSL2 on Windows 10)
- [x] Browser: Google Chrome  91.0.4472.124(Official Build)(64 bit)

**Comment by knolleary** [comment]
As this is broken in 1.3.5, I've cherry-picked the commit into the master branch as well for the next 1.x maintenance release.

**Comment by kazuhitoyokoi** [comment]
Yes, it is also needed for Node-RED v1.3.6. Thank you for your caring.
