### ISSUE TITLE
Problem in the flow context when using auxiliary variables.

### ISSUE THREAD

**Issue by JorgeAlberto91MS** [node-red/node-red#3053]
### What are the steps to reproduce?
Flow included in description

### What happens?
There are two variables A and B.
A is an auxiliary variable, the information stored in A is later stored in a position of B (B is an array).
When information is written in different positions of the array B, it is observed that all of them have the same information.

If you disable the node that takes the information from A to write it later in B. B continues taking the values stored in A. (With the nodes disabled).

### What do you expect to happen?
A is an auxiliary variable and the values will be changing to store them in B, therefore B should have different information. (But all the positions are written with the last state of the variable A).

This continues to happen even when the function node that performs the change of information is deactivated or even when it is deleted.

### Please tell us about your environment:

- [x] Node-RED version: 1.3.5
- [x] Node.js version: 12.22.1
- [x] npm version: 6.14.12
- [x] Platform/OS: Raspberry Pi/Raspbian
- [x] Browser: Chromium

[{"id":"b8da2bc4.d09ff8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"5d3a6d1e.f36e64","type":"ui_switch","z":"b8da2bc4.d09ff8","name":"","label":"Disponible","tooltip":"","group":"c5f05af1.a4c158","order":6,"width":"6","height":"1","passthru":true,"decouple":"false","topic":"topic","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":240,"y":310,"wires":[["ca8542a4.5ca1d"]]},{"id":"a5204587.b883d8","type":"ui_text_input","z":"b8da2bc4.d09ff8","name":"","label":"Nombre del pozo","tooltip":"","group":"c5f05af1.a4c158","order":2,"width":0,"height":0,"passthru":false,"mode":"text","delay":300,"topic":"topic","x":220,"y":110,"wires":[["f4be3cec.c935f"]]},{"id":"120f2cfa.456e63","type":"ui_dropdown","z":"b8da2bc4.d09ff8","name":"Posición cluster","label":"","tooltip":"","place":"Seleccione una posición","group":"c5f05af1.a4c158","order":1,"width":0,"height":0,"passthru":true,"multiple":false,"options":[{"label":"Slot 1","value":0,"type":"num"},{"label":"Slot 2","value":1,"type":"num"},{"label":"Slot 3","value":2,"type":"num"},{"label":"Slot 4","value":3,"type":"num"},{"label":"Slot 5","value":4,"type":"num"},{"label":"Slot 6","value":5,"type":"num"},{"label":"Slot 7","value":6,"type":"num"},{"label":"Slot 8","value":7,"type":"num"},{"label":"Slot 9","value":8,"type":"num"},{"label":"Slot 10","value":9,"type":"num"},{"label":"Slot 11","value":10,"type":"num"},{"label":"Slot 12","value":11,"type":"num"}],"payload":"","topic":"","x":230,"y":60,"wires":[["c842b748.2bafd8"]]},{"id":"7522f5b8.a4638c","type":"ui_dropdown","z":"b8da2bc4.d09ff8","name":"Levantamiento","label":"","tooltip":"","place":"Tipo ALS","group":"c5f05af1.a4c158","order":3,"width":0,"height":0,"passthru":false,"multiple":false,"options":[{"label":"ESP","value":"ESP","type":"str"},{"label":"PCP","value":"PCP","type":"str"}],"payload":"","topic":"","x":230,"y":160,"wires":[["43505e5f.1b221"]]},{"id":"dd9f6ceb.ddbe7","type":"ui_dropdown","z":"b8da2bc4.d09ff8","name":"Marca Variador","label":"","tooltip":"","place":"Marca de variador","group":"c5f05af1.a4c158","order":4,"width":0,"height":0,"passthru":false,"multiple":false,"options":[{"label":"ABB","value":"ABB","type":"str"},{"label":"SLB Uniconn","value":"SLB_Uniconn","type":"str"},{"label":"CILA2S®","value":"CILA2S","type":"str"},{"label":"SIEMENS","value":"SIEMENS","type":"str"},{"label":"Centerlift","value":"Centerlift","type":"str"},{"label":"SMCFlex","value":"SMCFlex","type":"str"},{"label":"Variadores S.A","value":"VariadoresSA","type":"str"}],"payload":"","topic":"","x":230,"y":210,"wires":[["cfa9bf86.2a8a3"]]},{"id":"f8ac9870.c119d8","type":"ui_dropdown","z":"b8da2bc4.d09ff8","name":"Marca Sensor de fondo","label":"","tooltip":"","place":"Marca Sensor de fondo","group":"c5f05af1.a4c158","order":5,"width":0,"height":0,"passthru":false,"multiple":false,"options":[{"label":"SSU","value":"SSU","type":"str"},{"label":"Zenith","value":"Zenith","type":"str"},{"label":"Centinel","value":"Centinel","type":"str"},{"label":"Phoenix","value":"Phoenix","type":"str"},{"label":"Scout","value":"Scout","type":"str"}],"payload":"","topic":"","x":200,"y":260,"wires":[["3a0224.13cb4ddc"]]},{"id":"22860dee.e67e42","type":"ui_button","z":"b8da2bc4.d09ff8","name":"","group":"c5f05af1.a4c158","order":7,"width":"3","height":"1","passthru":false,"label":"Configurar","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":240,"y":360,"wires":[["bbcf7cf4.41f79"]]},{"id":"5517b73.bd02348","type":"ui_button","z":"b8da2bc4.d09ff8","name":"","group":"c5f05af1.a4c158","order":8,"width":"3","height":"1","passthru":false,"label":"Borrar","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":260,"y":400,"wires":[[]]},{"id":"f4be3cec.c935f","type":"change","z":"b8da2bc4.d09ff8","name":"","rules":[{"t":"set","p":"Pozo.Nombre","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":110,"wires":[[]]},{"id":"43505e5f.1b221","type":"change","z":"b8da2bc4.d09ff8","name":"","rules":[{"t":"set","p":"Pozo.ALS","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":420,"y":160,"wires":[[]]},{"id":"cfa9bf86.2a8a3","type":"change","z":"b8da2bc4.d09ff8","name":"","rules":[{"t":"set","p":"Pozo.Variador","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":210,"wires":[[]]},{"id":"3a0224.13cb4ddc","type":"change","z":"b8da2bc4.d09ff8","name":"","rules":[{"t":"set","p":"Pozo.Sensor","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":260,"wires":[[]]},{"id":"c842b748.2bafd8","type":"change","z":"b8da2bc4.d09ff8","name":"","rules":[{"t":"set","p":"Pozo.Posicion","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":430,"y":60,"wires":[[]]},{"id":"ca8542a4.5ca1d","type":"change","z":"b8da2bc4.d09ff8","name":"","rules":[{"t":"set","p":"Pozo.Disponible","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":310,"wires":[[]]},{"id":"bbcf7cf4.41f79","type":"function","z":"b8da2bc4.d09ff8","name":"","func":"var Pozo        = flow.get(\"Pozo\")||[];\nvar Cluster     = flow.get(\"Cluster\")||[];\n\nData = Pozo;\nvar Pos         = Pozo.Posicion;\nCluster[Pos]    = Pozo;\nflow.set(\"Cluster\",Cluster);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":390,"y":360,"wires":[[]]},{"id":"c5f05af1.a4c158","type":"ui_group","name":"Slot1","tab":"dfe3c396.db089","order":1,"disp":false,"width":"6","collapse":false},{"id":"dfe3c396.db089","type":"ui_tab","name":"Configuración cluster","icon":"settings","order":7,"disabled":false,"hidden":false}]

**Comment by knolleary** [comment]
Hi @JorgeAlberto91MS 

when sharing flows, please format them as code blocks - otherwise they get formatted as markdown by github.

I've managed to import your flow by editing your issue comment to get the 'raw' flow. Unfortunately I don't know how the flow relates to your issue. There are multiple dashboard nodes and no indication as to what I should do to try to recreate the issue or where I should be looking. There are no variables called `A` and `B`.

I suspect this is caused by JavaScript's pass-by-reference nature.

If you put A 'inside' B, and continue to modify A, then you are still modifying the same object in memory.

If you want to break that connection, you'll need to clone the object to take a copy.

**Comment by JorgeAlberto91MS** [comment]
Hi @knolleary.

First, sorry for the poor description of the problem contained in the attached flow.
Second, thank you very much for the time spent in examining the situation.

Your assumption is correct and the problem is caused by "JavaScript's pass-by-reference nature". **The object was cloned using the spread operator and the problem was solved.**

The issue  **was not caused by Node-Red environment**. 

Thank you so much.
