### ISSUE TITLE
MQTT in MQTT out nodes show wrong connection status

### ISSUE THREAD

**Issue by PreethamBhat** [node-red/node-red#3060]
### What are the steps to reproduce?
install aedes broker
provide no authentication: userid/pwd
connect an mqtt in node without any auth: userid/pwd
connect an mqtt out node without any auth: userid/pwd
attach an inject node to mqtt out and debug node to mqtt in
inject a timestamp
![image](https://user-images.githubusercontent.com/50608824/125092787-530b7f00-e0ef-11eb-85aa-43453a987355.png)

### What happens?
mqtt in and mqtt out nodes status indicators show disconnected in red
data is seen in the debug messages 

### What do you expect to happen?
mqtt in and mqtt out nodes must show the status indicators as connected in green

### Please tell us about your environment:

- [ ] Node-RED version: v1.2.5
- [ ] Node.js version: v10.19.0
- [ ] npm version:
- [ ] Platform/OS: docker container running on debian OS. Docker Container used is  node:10.19.0-buster-slim
- [ ] Browser: chrome

**
Note1:
This issue is only seen when i run node-red inside a docker container
I have written a dockerfile and using docker compose to run on debian OS

Note2:
I also tried below method to run node red:
 git clone https://github.com/node-red/node-red.git
 cd node-red
 npm install
 npm run build
 npm start

When i npm start node-red and try the same steps , issue is not reproducible.**

####Logs:
> node-red@1.2.5 start /home/nodered/node-red
> node packages/node_modules/node-red/red.js -s template-settings.js

9 Jul 13:52:17 - [trace] git["--version"]
9 Jul 13:52:17 - [trace] git["config","--global","user.name"]
9 Jul 13:52:17 - [trace] git["config","--global","user.email"]
9 Jul 13:52:17 - [trace] git init: {"version":"2.20.1"}
9 Jul 13:52:17 - [info] 

Welcome to Node-RED
===================

9 Jul 13:52:17 - [info] Node-RED version: v1.2.5
9 Jul 13:52:17 - [info] Node.js  version: v10.19.0
9 Jul 13:52:17 - [info] Linux 4.19.165-cip41-rt18+ind3 x64 LE
9 Jul 13:52:18 - [info] Loading palette nodes
9 Jul 13:52:18 - [debug] Module: node-red-contrib-aedes 0.5.2
9 Jul 13:52:18 - [debug]         /home/nodered/node-red-home/node-red-flows/node_modules/node-red-contrib-aedes
9 Jul 13:52:18 - [debug] Module: node-red-node-tail 0.1.1
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-node-tail
9 Jul 13:52:18 - [debug] Module: node-red-contrib-livetwin-node 1.0.1
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-contrib-livetwin-node
9 Jul 13:52:18 - [debug] Module: node-red-contrib-modbus 5.13.3
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-contrib-modbus
9 Jul 13:52:18 - [debug] Module: node-red-contrib-opcua 0.2.89
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-contrib-opcua
9 Jul 13:52:18 - [debug] Module: node-red-contrib-s7 2.2.2
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-contrib-s7
9 Jul 13:52:18 - [debug] Module: @mindconnect/node-red-contrib-mindconnect 3.10.0
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/@mindconnect/node-red-contrib-mindconnect
9 Jul 13:52:18 - [debug] Module: node-red-dashboard 2.24.1
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-dashboard
9 Jul 13:52:18 - [debug] Module: node-red-node-email 1.8.2
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-node-email
9 Jul 13:52:18 - [debug] Module: node-red-node-rbe 0.2.9
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-node-rbe
9 Jul 13:52:18 - [debug] Module: node-red-node-sentiment 0.1.6
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-node-sentiment
9 Jul 13:52:18 - [debug] Module: node-red-contrib-s7comm 1.1.6
9 Jul 13:52:18 - [debug]         /home/nodered/node-red/node_modules/node-red-contrib-s7comm
9 Jul 13:52:20 - [s7comm-Info] - Debug configuration for logLevelNodeS7:{"debug":0,"silent":true}
9 Jul 13:52:20 - [s7comm-Info] - Debug configuration for logLevelNodeRED:{"debug":2,"silent":true}
9 Jul 13:52:21 - [info] Dashboard version 2.24.1 started at /ui
9 Jul 13:52:21 - [trace] utils.writeFile - copied /home/nodered/node-red-home/node-red-flows/.config.nodes.json TO /home/nodered/node-red-home/node-red-flows/.config.nodes.json.backup
9 Jul 13:52:21 - [trace] utils.writeFile - written content to /home/nodered/node-red-home/node-red-flows/.config.nodes.json.$$$
9 Jul 13:52:21 - [trace] utils.writeFile - renamed /home/nodered/node-red-home/node-red-flows/.config.nodes.json.$$$ to /home/nodered/node-red-home/node-red-flows/.config.nodes.json
9 Jul 13:52:21 - [info] Settings file  : /home/nodered/node-red/template-settings.js
9 Jul 13:52:21 - [info] Context store  : 'default' [module=memory]
9 Jul 13:52:21 - [info] User directory : /home/nodered/node-red-home/node-red-flows
9 Jul 13:52:21 - [warn] No active project : using default flows file
9 Jul 13:52:21 - [info] Flows file     : /home/nodered/node-red-home/node-red-flows/flows.json
9 Jul 13:52:21 - [debug] loaded flow revision: a7907fe9cb838f6f7925e8c85d598a98
9 Jul 13:52:21 - [debug] red/runtime/nodes/credentials.load : no user key present
9 Jul 13:52:21 - [debug] red/runtime/nodes/credentials.load : using default key
9 Jul 13:52:21 - [debug] red/runtime/nodes/credentials.load : keyType=system
9 Jul 13:52:21 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

9 Jul 13:52:21 - [trace] runtime event: {"id":"runtime-state","retain":true}
9 Jul 13:52:21 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"a7907fe9cb838f6f7925e8c85d598a98"},"retain":true}
9 Jul 13:52:21 - [info] Starting flows
9 Jul 13:52:21 - [debug] red/nodes/flows.start : starting flow : global
9 Jul 13:52:21 - [debug] red/nodes/flows.start : starting flow : 116ed64b.ff74da
9 Jul 13:52:21 - [trace] [flow:global] start flow [global]
9 Jul 13:52:21 - [trace] [flow:global] ------------------|--------------|-----------------
9 Jul 13:52:21 - [trace] [flow:global]  id               | type         | alias
9 Jul 13:52:21 - [trace] [flow:global] ------------------|--------------|-----------------
9 Jul 13:52:21 - [trace] [flow:global]  16005ce6.60bb93  | mqtt-broker  | 
9 Jul 13:52:21 - [trace] [flow:global] ------------------|--------------|-----------------
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da] start flow [116ed64b.ff74da]
inside mqttinnode function checking if() 
inside mqttoutnode function checking user and pass in if() 
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da] ------------------|--------------|-----------------
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da]  id               | type         | alias
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da] ------------------|--------------|-----------------
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da]  7a282be4.c79984  | aedes broker | 
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da]  c6c85a31.2d7828  | inject       | 
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da]  67de9856.331138  | debug        | 
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da]  734ceba5.41a5b4  | mqtt in      | 
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da]  b9e6035b.2f0ff   | mqtt out     | 
9 Jul 13:52:21 - [trace] [flow:116ed64b.ff74da] ------------------|--------------|-----------------
9 Jul 13:52:21 - [trace] runtime event: {"id":"runtime-state","retain":true}
9 Jul 13:52:21 - [info] Started flows
9 Jul 13:52:21 - [info] [aedes broker:7a282be4.c79984] Binding aedes mqtt server on port: 1883
9 Jul 13:52:22 - [info] [mqtt-broker:16005ce6.60bb93] Connected to broker: mqtt://localhost:1883
inside connect function checking user and pass  
inside connect function checking user and pass  
9 Jul 13:52:22 - [info] Server now running at http://127.0.0.1:1880/

**Comment by hardillb** [comment]
Have you tested this with anything later than v1.2.5?

The latest is v1.3.5 and v2.0.0-beta.2 is also available.

**Comment by knolleary** [comment]
Node-RED v1.2.5 is quite old. There have been a number of releases since then.

Given you cannot reproduce it when running the latest code from git (ie 1.3.5), then I'm not sure there's anything for us to do here.
