### ISSUE TITLE
Internal credentials object prevents setting of a custom own auth header in http request node

### ISSUE THREAD

**Issue by cmuench** [node-red/node-red#3067]
### What are the steps to reproduce?

1. Create a HTTP request with a function node as input
2. Set a Authorization header as input message

Example:
   
```javascript
return {
  'method': 'GET',
  'url': 'https://example.com',
  'headers': {
    'Authorization': 'bearer abc123'
  }
};
```
Problem is that the check if credentials are available is always true.

file: packages/node_modules/@node-red/nodes/core/network/21-httprequest.js line 208

```javascript
if (this.credentials) {  // <-- always true -> empty object
```

### What happens?

The Authorization header value will be overwritten with ''Basic " in the http request node.

### What do you expect to happen?

The custom Authorization should be used.

### Please tell us about your environment:

- [X] Node-RED version: 2.0.0
- [X] Node.js version: v16.5.0
- [X] npm version: 7.19.1
- [X] Platform/OS: Arch Linux
- [X] Browser: Firefox

**Comment by hardillb** [comment]
Just to be clear here, you are setting credentials in the http-request node?

**Comment by cmuench** [comment]
No. I did not set the credentials in the HTTP request node. If I set the credentials (hardcoded) then it works.
In my case I have to fetch/refresh a bearer token and want to set the token via the header.

**Comment by cmuench** [comment]
I added a `console.log(this.credentials);` in the request node.
Output is `{}`.

**Comment by cmuench** [comment]
I am not experienced in NodeJS, but this fixes my issue:

```javascript
//if (this.credentials) {
if (Object.keys(this.credentials).length > 0) {
```

**Comment by hardillb** [comment]
Close enough, I was going with `if (Object.keys(this.credentials).length != 0) {`
