### ISSUE TITLE
http request node resolving https addresses to 127.0.0.1

### ISSUE THREAD

**Issue by zachowj** [node-red/node-red#3072]
### Current Behavior

When using an HTTPS URL, https://example.com, in an HTTP request node it throws a connection refused error with the resolved address being 127.0.0.1. If you use the same domain but as non-secure, http://example.com, it fetches from the correct address. I was also getting this error in the first beta for 2.0 but didn't have the time to look into it.

### Expected Behavior

For it to resolve the correct address.

### Steps To Reproduce

In my example flow below I set up two additional function nodes one using `got` and the other using `request` with their basic examples. The `got` one throws the same error as the HTTP request node but the function node using `request` resolves and fetches the page without error.

using `https://example.com`

![image](https://user-images.githubusercontent.com/37859597/126449640-811cf84a-541c-4e1d-966d-9dd2651da5a5.png)

using `http://example.com`

![image](https://user-images.githubusercontent.com/37859597/126449955-8684f05c-fb87-42ae-9c9d-03352df1bfdb.png)

### Example flow

```
[{"id":"1665f32d24673182","type":"inject","z":"d1774d73.fd337","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"https://example.com","payloadType":"str","x":218,"y":1280,"wires":[["36ed86c780c5bd92","74d45a281d9f4d6c","e23044f6b5dab588"]]},{"id":"864ca400c0c3d150","type":"debug","z":"d1774d73.fd337","name":"got","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":562,"y":1280,"wires":[]},{"id":"36ed86c780c5bd92","type":"function","z":"d1774d73.fd337","name":"got","func":"(async () => {\n    try {\n        msg.payload = await got(msg.payload);\n        node.send(msg);\n    } catch (error) {\n        node.error(error);\n    }\n})();","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"got","module":"got"}],"x":402,"y":1280,"wires":[["864ca400c0c3d150"]]},{"id":"74d45a281d9f4d6c","type":"function","z":"d1774d73.fd337","name":"request","func":"request(msg.payload, function (error, response, body) {\n    if(error) {\n        node.error(`error: ${error}`);        \n        return;\n    }\n    msg.payload = {\n        statusCode: response && response.statusCode,\n        body: body\n    };\n    node.send(msg);\n});","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"request","module":"request"}],"x":412,"y":1328,"wires":[["f891cadb84b62e04"]]},{"id":"f891cadb84b62e04","type":"debug","z":"d1774d73.fd337","name":"request","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":572,"y":1328,"wires":[]},{"id":"e23044f6b5dab588","type":"http request","z":"d1774d73.fd337","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"{{{payload}}}","tls":"","persist":false,"proxy":"","authType":"","x":422,"y":1232,"wires":[["849475fd46481e32"]]},{"id":"849475fd46481e32","type":"debug","z":"d1774d73.fd337","name":"http request","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":582,"y":1232,"wires":[]},{"id":"c06790249ec9d021","type":"inject","z":"d1774d73.fd337","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"http://example.com","payloadType":"str","x":218,"y":1328,"wires":[["e23044f6b5dab588","36ed86c780c5bd92","74d45a281d9f4d6c"]]}]
```

### Environment

Tried with both official docker images for node 12 and 14 same results

- Node-RED version: 2.0.1
- Node.js version: v14.17.3
- npm version:
- Platform/OS: Linux 5.4.0-77-generic x64 LE
- Browser:

**Comment by hardillb** [comment]
The provided flow works just fine for me, both in a local install and using the NodeJS 14 based 2.0.1 container.

And some manual testing I've set up myself

Are you running in an environment that makes use of a proxy at all, may be a transparent proxy?

**Comment by zachowj** [comment]
You are correct it works on a separate docker host. 

No proxy that I am aware of running on that VM other than docker. It working with `request`  and not `got` threw me for a loop.

**Comment by knolleary** [comment]
Reopening as we've had similar reports on the forum about this behaviour - although not inside docker in that case.

**Comment by hardillb** [comment]
Other instance also reported to happen when using IP address in URL not a host name (which makes it even stranger)

**Comment by hardillb** [comment]
@zachowj Can you let us know what extra nodes you have installed please

**Comment by zachowj** [comment]
This does fix my case. 

For reference, it was https://github.com/ceujorge/dialogflowv2 that uses agent-base@4.3.0.
