### ISSUE TITLE
Tab image issue in Safari

### ISSUE THREAD

**Issue by sroebert** [node-red/node-red#3073]
### Current Behavior

The design of tabs in the user interface in Safari is not showing correctly, it looks like the wrong part of the image is stretched.

<img width="636" alt="Screenshot 2021-07-21 at 10 49 57" src="https://user-images.githubusercontent.com/81575/126462276-8979eecc-7c40-4c5e-a8bf-10232355ba30.png">

### Expected Behavior

In Chrome it works correctly:

<img width="644" alt="Screenshot 2021-07-21 at 11 03 56" src="https://user-images.githubusercontent.com/81575/126462357-54a42866-9fab-4ef6-bf2d-ee086374f8d0.png">

### Steps To Reproduce

Run Node-RED 2.0/2.0.1 in Safari

### Environment

- Node-RED version: 2.0 / 2.0.1
- Node.js version: 14.17.3
- npm version: 6.14.13
- Platform/OS: Mac OS Big Sur 11.4
- Browser: Safari 14.1.1

**Comment by hardillb** [comment]
If this is after an upgrade from 1.3.x please make sure you have cleared the cache in Safari and force a full reload of the page to make sure it's not still using any cached styles from the older version.

**Comment by knolleary** [comment]
@hardillb in this instance, this is a real issue with safari's handling of `linear-gradient` css.

**Comment by sroebert** [comment]
> If this is after an upgrade from 1.3.x please make sure you have cleared the cache in Safari and force a full reload of the page to make sure it's not still using any cached styles from the older version.

Yes, I did clear the cache already.
