### ISSUE TITLE
Delay Node: Error with Rate Limit and msg.reset

### ISSUE THREAD

**Issue by deonp** [node-red/node-red#3074]
In V2.01 with a delay node set as Rate Limit and a msg.reset message the delay node will throw the following error: TypeError: Cannot read property 'hasOwnProperty' of undefined

Flow to reproduce:
`[{"id":"49c5f93c6e9995b4","type":"inject","z":"8ae02d5f.40148","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":920,"y":1140,"wires":[["2e22d894ed0e714c"]]},{"id":"2e22d894ed0e714c","type":"change","z":"8ae02d5f.40148","name":"","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":1080,"y":1140,"wires":[["644d0a36bf3c0011"]]},{"id":"644d0a36bf3c0011","type":"delay","z":"8ae02d5f.40148","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":1250,"y":1140,"wires":[[]]}]`

**Comment by knolleary** [comment]
@deonp thanks for reporting. Found the issue straight away.

BTW - please use the 'Report a bug' template in the future as it helps ensure all relevant information is provided.

**Comment by deonp** [comment]
Thanks @knolleary for the quick fix.
I looked for 10 minutes and didn't notice the repeated call.

Yes, missed the template I think due to signing into GitHub on a different PC after clicking Raise an Issue.
