### ISSUE TITLE
https calls returning within docker container

### ISSUE THREAD

**Issue by liukonen** [node-red/node-red#3077]
### Current Behavior

Making a get call to a file on a web server that displays in a web browser now returns "RequestError: connect ECONNREFUSED 127.0.0.1:443 : https:/url/of/file.txt" This function was working before yesterdays release to the docker images. I have basic auth turned on with nothing filled in. Attempting to open the port for 443 communication on my container did not fix the issue. And there has been no updated documentation on how to get this working again.  Also found that 3rd party modules such as "speed test" also failing

### Expected Behavior

the call to the https server to either return the string value and/or header info, and not error on an econnrefused error message

### Example flow

```
paste your flow here
```
[{"id":"29dba99b81f2f6c4","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"2a7818d9b770bd52","type":"inject","z":"29dba99b81f2f6c4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":190,"y":160,"wires":[["d2e2e17092ef9217"]]},{"id":"b8bb8392a7e5c1cc","type":"debug","z":"29dba99b81f2f6c4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":600,"y":160,"wires":[]},{"id":"713144e3a1f661d8","type":"catch","z":"29dba99b81f2f6c4","name":"","scope":null,"uncaught":false,"x":370,"y":240,"wires":[["b8bb8392a7e5c1cc"]]},{"id":"d2e2e17092ef9217","type":"http request","z":"29dba99b81f2f6c4","name":"","method":"HEAD","ret":"txt","paytoqs":"ignore","url":"https://bot.liukonen.dev","tls":"","persist":false,"proxy":"","authType":"basic","x":380,"y":160,"wires":[["b8bb8392a7e5c1cc"]]}]

### Environment

- Node-RED version: 2.0.1
- Node.js version: 14.17.3
- npm version: 6.14.13
- Platform/OS: Docker docker pull nodered/node-red:latest Alpine Linux v3.11 (Parent Ubuntu 20.04 LTS)
- Browser: Chrome

**Comment by hardillb** [comment]
duplicate: https://github.com/node-red/node-red/issues/3075

**Comment by hardillb** [comment]
Sorry, wrong issue, duplicate of https://github.com/node-red/node-red/issues/3072

**Comment by hardillb** [comment]
v2.0.2 has been shipped which has a fix for this, but you should read this:
https://discourse.nodered.org/t/node-red-2-0-2-released/48767 because as you mentioned the speedtest node will probably need updating to work properly with v2.0.x

**Comment by liukonen** [comment]
Thank you for the quick turnaround. I'll pull latest :)
