### ISSUE TITLE
httprequest overwrites payload on any error condition

### ISSUE THREAD

**Issue by ramoriusvt** [node-red/node-red#3086]
### Current Behavior

Fast forward to now, when I just updated my node-red server to v2.0.1. The response we're getting now is
`HTTPError: Response code 404 (Not Found) : https://xxx.xxxapicom/Orders?OrderNumber=00012345`
That is overwriting the response from the api server. The overwriting occurs on line 509 of node-red/nodes/core/network/21-httprequest.js

Since the payload is being forced to meet the specified structure regardless of what the api actually returned, I have no certainty if the request is being processed or if it really is a bad url. 

I'm struggling to come up with a scenario that justifies the overwriting of the response from the server. Hence, I recommend the following change to line 509:
`msg.payload = (msg.payload==null ? err.toString() + " : " + url :msg.payload;
`
This will retain the response from the server and only provide the specified response if there is no other.

### Expected Behavior

On an older version of node-red (v0.20.8), I was able to submit a request (in this case looking for a specific OrderNumber) to an api and it would return:
`
{
    "Errors": [
        "Order not found!"
    ]
}
`
This told me that the order hadn't been submitted yet, so it was safe to submit as it would not create a duplicate order. Because of the formatted response, I knew that the request had been properly processed and was not just a default error.

### Steps To Reproduce

Go to http://3.81.133.27:1880/Orders?OrderNumber=00012345 in any browser, you'll get the response
`{"Errors":["Order not found!"]}`

Go to the same url in Node Red and you get: 
`HTTPError: Response code 404 (Not Found) : http://3.81.133.27:1880/Orders?OrderNumber=00012345`
in addition to the output from the catch node error:
`{"message":"HTTPError: Response code 404 (Not Found)","source":{"id":"d9326f242d1d708e","type":"http request","name":"Test1","count":1},"stack":"HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/lib/node_modules/node-red/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}`
which still does not provide the actual response from the url.

Note: this is a fabricated response. Going to any other order number will return a valid 200 response.

### Example flow

```[{"id":"e3b6b82974580613","type":"tab","label":"404Test","disabled":false,"info":""},{"id":"8d036fc8428223b7","type":"inject","z":"e3b6b82974580613","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":220,"wires":[["d9326f242d1d708e"]]},{"id":"1bcace955749fa02","type":"catch","z":"e3b6b82974580613","name":"","scope":["d9326f242d1d708e"],"uncaught":false,"x":370,"y":160,"wires":[["c35beb4176eee803"]]},{"id":"d9326f242d1d708e","type":"http request","z":"e3b6b82974580613","name":"Test1","method":"GET","ret":"obj","paytoqs":"ignore","url":"http://3.81.133.27:1880/Orders?OrderNumber=00012345","tls":"","persist":false,"proxy":"","authType":"","x":370,"y":220,"wires":[["40f5171fce61b54a"]]},{"id":"40f5171fce61b54a","type":"debug","z":"e3b6b82974580613","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":530,"y":220,"wires":[]},{"id":"c35beb4176eee803","type":"debug","z":"e3b6b82974580613","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":530,"y":160,"wires":[]}]
```

### Environment

- Node-RED version: 2.0.1
- Node.js version: v12.22.2
- npm version: 6.14.13
- Platform/OS: Ubuntu
- Browser: Chrome

**Comment by knolleary** [comment]
This was fixed in 2.0.2

**Comment by ramoriusvt** [comment]
Wow - you're fast! I just updated to 2.01 on 7/21!

I can confirm that after upgrading to 2.03, it's providing the api response (as expected).
Thank you!
