### ISSUE TITLE
v2.0.2 existing rbe nodes have config error

### ISSUE THREAD

**Issue by 877dev** [node-red/node-red#3087]
### Current Behavior

After upgrading to v2.0.2 from 1.x, the rbe nodes have been renamed to filter nodes and are working fine.

![image](https://user-images.githubusercontent.com/46575282/126910251-9c9deb83-6d35-49e5-bc0f-897e1de6e015.png)

However, when editing the existing node and making no changes:
Pressing Cancel is ok and gives no error
![image](https://user-images.githubusercontent.com/46575282/126910257-dcee200a-37b1-476e-a0db-cf7c7700ae9c.png)

Pressing Done give the red triangle error, hovering over the triangle gives this:
![image](https://user-images.githubusercontent.com/46575282/126910275-4f265173-8557-4315-9998-473b391d7767.png)

Same happens when unticking the "Apply mode" box and pressing Done,

Replacing the node with a new 'filter' node with the exact same settings work fine.

### Expected Behavior

Expect Cancel and Done to effectively do the same thing when no changes are made to an existing rbe node.

### Steps To Reproduce

Double click on an existing RBE node (now named filter)
Make no changes
Press Done

The node now shows a red triangle warning, hovering over shows "Invalid Properties - topi"  (sic).

### Example flow

```
[{"id":"4f375b87.405fc4","type":"rbe","z":"3b92f612.6f7b5a","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":true,"property":"payload","x":1330,"y":1380,"wires":[["a2d9b40c.19f7b8"]]}]
```

### Environment

- Node-RED version: 2.0.2
- Node.js version: 14 (pulled 'latest' Docker image)
- npm version: 10.24.0
- Platform/OS: SSH into Pi4 using Windows Putty
- Browser: Chrome

**Comment by knolleary** [comment]
A new required field was added to the node, but no logic added to help with the case of all existing nodes that don't have that field set.

We should be filling in that new field if it isn't otherwise set.

**Comment by 877dev** [comment]
Thank you, I see you made a commit to address this. Will the changes be in the next release?

**Comment by knolleary** [comment]
Yes.

**Comment by 877dev** [comment]
Thank you
