### ISSUE TITLE
2.0.3 http request node - TLS certificate verification no longer succeeds

### ISSUE THREAD

**Issue by agarity** [node-red/node-red#3088]
### Current Behavior

When running nodered v1.3.5 everything works as expected, all http request nodes leveraging TLS with a certificate authority present and verification enabled, work without issue.

Post upgrade to 2.0.3 every http request node leveraging a TLS profile that verifies the certificate fails with "RequestError: self signed certificate in certificate chain" appearing in debug and SELF_SIGNED_CERT_IN_CHAIN displayed as the node status for the http request node.  The only way I've found around this is to disable certificate verification.  Validating certificate of the server the http node is hitting in openssl against the same certificate uploaded to the TLS config under CA certificate works and passes verification.

Restoring my backup prior to upgrade to go back to 1.3.5, the same flow works again.  Upgrade a 2nd time, and it no longer works with the same behavior.

### Expected Behavior

http request node querying a server with a valid cert, and CA present in TLS config, should not fail certificate verification.

### Steps To Reproduce

Using the example flow (modify to your environment) Import your Certificate Authoirty cert into the TLS config.  Change the http request URL to a valid host that has a valid certificate issued by your CA.  The request will fail due to certificate verification failure.

### Example flow

```
[
    {
        "id": "ede8f8bc3ed1d623",
        "type": "http request",
        "z": "90a227ad3d39d234",
        "name": "",
        "method": "POST",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "https://em01.ag.home.lab/api/login",
        "tls": "06b9d026eb93bb05",
        "persist": false,
        "proxy": "",
        "authType": "",
        "credentials": {},
        "x": 400,
        "y": 400,
        "wires": [
            [
                "7ff06071f1d48158"
            ]
        ]
    },
    {
        "id": "06b9d026eb93bb05",
        "type": "tls-config",
        "name": "CA Verify",
        "cert": "",
        "key": "",
        "ca": "",
        "certname": "",
        "keyname": "",
        "caname": "ca01.ag.home.lab.crt",
        "servername": "",
        "verifyservercert": true,
        "alpnprotocol": "",
        "credentials": {}
    }
]
```

### Environment

- Node-RED version: 2.0.3
- Node.js version: 14.17.2
- npm version: 6.14.13
- Platform/OS: Ubuntu 20.04 LXC container
- Browser: Google Chrome 92.0.4515.107

**Comment by knolleary** [comment]
Think I've found the cause.

The `got` module we've moved to in 2.x has decided to rename some of the standard core node.js TLS properties "for better readability". So we can't just pass in a standard tls config object.

https://github.com/sindresorhus/got/blob/main/documentation/5-https.md#certificateauthority

**Comment by hardillb** [comment]
This looks like `got` uses the opt.https.certificateAuthority` not `opts.https.ca`

**Comment by agarity** [comment]
Armed with the knowledge above, I did a quick test of updating opts.ca to opts.certificateAuthoirty in 05-tls.js allows certificate verification to work again.

**Comment by hardillb** [comment]
That is not a good fix as multiple other nodes make use of the TLS configuration node and they all expect `opts.ca`
