### ISSUE TITLE
http request with mutual TLS not working anymore

### ISSUE THREAD

**Issue by Leosirth** [node-red/node-red#3091]
### Current Behavior

Hi,

I have an http request node that call an endpoint over SSL with mutual TLS therefore I have a TLS configuration providing:

- private key
- certificate
- ca

After upgrading to latest version this is not working anymore getting only the following error (also on trace level)

`27 Jul 18:04:15 - [error] [http request:get localImages] RequestError: socket hang up`

Executing the same call using CURL directly from node-red container (giving the same key and certificate) works fine.

### Expected Behavior

The SSL invocation should work as expected since from the same container I can successfully execute it.

### Example flow

```
[{"id":"4ac98b0e8fc390d8","type":"tab","label":"Flow 4","disabled":false,"info":""},{"id":"325f9272aaf06b72","type":"inject","z":"4ac98b0e8fc390d8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":350,"y":180,"wires":[["077719d828db4d15"]]},{"id":"077719d828db4d15","type":"http request","z":"4ac98b0e8fc390d8","name":"","method":"GET","ret":"obj","paytoqs":"ignore","url":"https://127.0.0.1:2376/images/json","tls":"25181b59e2d5d266","persist":false,"proxy":"","authType":"","x":600,"y":180,"wires":[[]]},{"id":"25181b59e2d5d266","type":"tls-config","name":"test","cert":"/cert/cert.pem","key":"/cert/key.pem","ca":"/cert/ca.pem","certname":"","keyname":"","caname":"","servername":"","verifyservercert":false,"alpnprotocol":""}]
```

### Working CURL from same container

`curl -vk --key /cert/key.pem --cert /cert/cert.pem https://127.0.0.1:2376/images/json`

### Environment

Using nodered/node-red:latest docker image

- Node-RED version: v2.0.3
- Node.js version: v14.17.3
- npm version: 6.14.13
- Platform/OS: x64 unix
- Browser: Firefox 91 (not relevant)

**Comment by hardillb** [comment]
I think this should be fixed in 2.0.4 due very shortly see #3088

**Comment by Leosirth** [comment]
Thanks @hardillb,

I tought it was a different topic since I do not get the SELF_SIGNED_CERT_IN_CHAIN error (having the "verify server certificate" disabled on the TLS configuration)

If still relevant I would wait for next version and report back.

Thanks and regards

**Comment by hardillb** [comment]
The CA cert was not being used with the current code.

But I'll have a closer look when I get home

**Comment by hardillb** [comment]
OK, this is not fixed by the previous fix, but it is very similar, I will fix in the morning and it should make the 2.0.4 release

**Comment by hardillb** [comment]
2.0.4 has been released, should be fixed now.

**Comment by Leosirth** [comment]
Hi @hardillb,

the #3092 fix this issue and I confirm that mutual TLS is now working again on version 2.0.4

Thank you for your quick fix.
Have a nice day
