### ISSUE TITLE
Http Request node doesnt render msg.url as a mustache template

### ISSUE THREAD

**Issue by smiziara** [node-red/node-red#3094]
### Current Behavior

When passing a URL to the Http Request node using the msg.url field, the URL is not rendered as a mustache template.

The " isTemplatedUrl" is only calculated on the constructor.
When a message is received, this variable is checked against the default value (nodeUrl) and not the msg.url received on input. So the msg.url is not rendered as mustache template.

### Expected Behavior

The msg.url field that constains a mustache template, should be rendered on the input of a Http Request node.

### Steps To Reproduce

Send a message to a Http Request node, setting the msg.url to an URL with a mustache template.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.0.4
- Node.js version: 16.1
- npm version: 7.16
- Platform/OS: Windows
- Browser: Google Chrome

**Comment by knolleary** [comment]
This is the expected behaviour. The mustache template is only applied for the URL configured in the node.

If you are passing in the URL, you can build up the full URL outside of the node.

To change this behaviour would potentially break flows that pass in a URL with {{foo}} in, expecting that to be left as-is.

**Comment by smiziara** [comment]
Okey.
I believe it would be much easier to use if the rendering behavior was consistent.. This way is just creating an undocumented business rule.

If someone needed to send a url with {{foo}}, they could just send it encoded like %7B%7B.
