### ISSUE TITLE
flows.json does not get written with newlines, making it difficult to version-control

### ISSUE THREAD

**Issue by anaisbetts** [node-red/node-red#3099]
### Current Behavior

flows.json gets `JSON.stringify`ed without the whitespace parameter, meaning that versioning `flows.json` is difficult to parse and read - every diff consists of the entire file. This makes Git significantly less usable with flows.json, for no benefit

### Expected Behavior

Serializing flows as `JSON.stringify(theData, null, 2)` would result in human-readable JSON, which would also be diffable, without causing any compatibility issues.

**Comment by hardillb** [comment]
This is configurable in `settings.js` in your userDir (logged in the first few lines of the start up log)

Make sure `flowFilePretty: true,`

There should be a comment out example in the file.

**Comment by hardillb** [comment]
Also iirc this should get enabled automatically if the Projects feature is enabled to manage keeping flows in github.

**Comment by anaisbetts** [comment]
Thanks @hardillb. Can we make the default for this to true? afaik there's no compelling reason to write out that file as minified JSON

**Comment by hardillb** [comment]
It already is (for new instances) https://github.com/node-red/node-red/blob/master/packages/node_modules/node-red/settings.js#L50

**Comment by anaisbetts** [comment]
@hardillb Perfect! Thanks for helping me out
