### ISSUE TITLE
 Github no longer allows you to use id and password when cloning projects.

### ISSUE THREAD

**Issue by eeswq** [node-red/node-red#3111]
### Current Behavior

![image](https://user-images.githubusercontent.com/39664988/130005673-282fbcf7-38a2-4cc2-b985-57ae1f77f128.png)
git-blog : https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations

Github no longer allows you to use id and password when cloning projects.
How do I clone a project?

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
As their error message states, use a personal access token in place of your password.
