### ISSUE TITLE
SCSS files use relative paths for images, which doesn't work on themes

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3118]
### Current Behavior

A theme created using `build-custom-theme.js` has relative paths for images. That doesn't work because it ends up pointing to `/theme/css/images/`, where the correct should be `/red/images/`.

### Expected Behavior

Since those are the default UI image files, I believe there's no need to create a copy of them for each theme. That would be a waste of resources.

### Steps To Reproduce

Create a theme using the default `colors.scss` file, and then load that theme.

### Environment

- Node-RED version: 2.0.5
- Node.js version: v14.17.3
- npm version: 6.14.13
- Platform/OS: macOS Big Sur 11.5.2
- Browser: Chrome and Safari

**Comment by bonanitech** [comment]
I think that a possible solution would be replacing those paths with absolute ones.

For example:

```diff
.red-ui-icons-flow {
-    background-image: url('images/subflow_tab.svg');
+    background-image: url('/red/images/subflow_tab.svg');
    background-repeat: no-repeat;
    background-size: contain;
    filter: brightness(2.5);
}
```

Would this work?

**Comment by knolleary** [comment]
We cannot use absolute paths because we cannot assume the editor is being served from `/` - if the user has set `httpAdminRoot` to `/admin` (for example), the full path would be `/admin/red/images/subflow_tab.svg`.

If I understand the issue properly, I think the fix is to strip out any CSS that references a default image instead of including it in the theme.

**Comment by bonanitech** [comment]
I removed the references to SVG files from the generated theme file in the updates for Node-RED 2.0.6. It seems to be working fine.

I haven't removed the references to grip.png because they are overwritten by the themes.

Where is [this one](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/editor-client/src/sass/jquery.scss#L193-L195) used? I couldn't find it.

**Comment by bonanitech** [comment]
Closing this since everything seems to be working fine.
