### ISSUE TITLE
Shared resource includes conflict across nodes

### ISSUE THREAD

**Issue by ESF-B8ZS** [node-red/node-red#3127]
### Current Behavior

When developing nodes, if two different NPM packages have a shared resource with the same name, one will be loaded over the other.  For instance, given the scenario:

Package [node-red-contrib-nodeA] has a file: "\resources\ui.js"
File is included in node HTML as "resources/node-red-contrib-nodeA/ui.js"

and 

Package [node-red-contrib-nodeB] has a file:  "\resources\ui.js"
File is included in node HTML as "resources/node-red-contrib-nodeB/ui.js"

One file will overwrite the contents in memory of the other.  Similarly named functions will overwrite the previous. Additionally, any similarly named variables or constants will generate a warning about an existing declaration.

### Expected Behavior

I would expect the files to be dedicated and available only to the node package they're configured with.   Although deep testing was not done, I believe this would allow communication between nodes outside of the Node-RED API and potentially cause security issues.

Workaround is to simply give the share resource files different names across packages.

### Steps To Reproduce

This is detailed in the current behavior section.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 1.3.5
- Node.js version: 12.16.1
- npm version:
- Platform/OS: OSX, Linux
- Browser: Brave

**Comment by knolleary** [comment]
If you are loading the resource into the browser as a regular script then everything you declare in that file will get added to the global namespace - and overwrite anything that already exists.

If you don't want it to do that, then you could structure your js as a module and load it that way - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by knolleary** [comment]
I'm going to close this issue given my previous response. If you'd like to discuss further, happy to do so.
