### ISSUE TITLE
Store data in the context store

### ISSUE THREAD

**Issue by softy2k** [node-red/node-red#3141]
### Current Behavior

The data from context store is altered / modified without a **set** command.
Same issue with **flow** and **global** store.

I understand that variables are addressed by reference, but without the **flow.set** or **global.set** command, the **test** variable should not be changed. 

![Context](https://user-images.githubusercontent.com/37790195/132878604-4efd017e-64ae-4890-8693-87d94d1db783.png)
 

### Example flow

[{"id":"8c9b67924e83909b","type":"inject","z":"a3c8de35e217836c","name":"Go","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":420,"y":1740,"wires":[["bd151de0383d6a11"]]},{"id":"bd151de0383d6a11","type":"function","z":"a3c8de35e217836c","name":"Set","func":"global.set('test', [123]);\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":550,"y":1740,"wires":[["e769c005a5323ebc"]]},{"id":"e769c005a5323ebc","type":"function","z":"a3c8de35e217836c","name":"Get Value","func":"let value = global.get('test')\n\nvalue[0] = 777\n\nmsg.payload = global.get('test')        // should be 123 but is 777\n\n\nreturn msg","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":700,"y":1740,"wires":[["655398db29d92ccb"]]},{"id":"655398db29d92ccb","type":"debug","z":"a3c8de35e217836c","name":"Flow","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":840,"y":1740,"wires":[]}]

### Environment

- Node-RED version: 2.0.6
- Node.js version: 14.17.6 LTS
- npm version: 7.22.0
- Platform/OS: Windows 10 x64 , Ubuntu
- Browser: Firefox

**Comment by knolleary** [comment]
> I understand that variables are addressed by reference, but without the flow.set or global.set command, the test variable should not be changed.

No. Because the variables are addressed by reference, they can be modified without the call to `set`. That is how it has always been. 

But without the call to set, any modification to the object will not get saved if you are using a persistent store.

**Comment by softy2k** [comment]
I understand and I can accept this.
It's just that I didn't see anywhere mentioned in the documentation that the value of the variable can be changed without an explicit command.
