### ISSUE TITLE
wrong version reported by github api to get last release

### ISSUE THREAD

**Issue by zen2** [node-red/node-red#3150]
### Current Behavior

$ curl -sL https://api.github.com/repos/node-red/node-red/releases/latest | jq -r .tag_name
1.3.7

### Expected Behavior

$ curl -sL https://api.github.com/repos/node-red/node-red/releases/latest | jq -r .tag_name
2.0.6

Sorry if it's a dumb question but I really do not understand this behaviour.
Is it node-red github workflow related or is it a pure github side problem ?
My home automation system use node-red and I use this url to show that there is a new version of node-red.
That have always works perfectly until the 1.3.7/2.0.6  release.

**Comment by hardillb** [comment]
GitHub just returns the last cut release, this might be from the 1.3.x stream or the 2.x stream.

This is behaving as expected. You should be using npm versioning not GitHub releases.

**Comment by zen2** [comment]
> GitHub just returns the last cut release, this might be from the 1.3.x stream or the 2.x stream.
> 
> This is behaving as expected. You should be using npm versioning not GitHub releases to track the release stream you are interested in.

Thanks for the quick reply. I will use npm to get latest version so.
I'm surprised that is not possible to tell to github on will branch the latest release depends.
