### ISSUE TITLE
Problem with context variables

### ISSUE THREAD

**Issue by JorgeAlberto91MS** [node-red/node-red#3240]
### Current Behavior

When changing project the global context variables are kept for the new project.

### Expected Behavior

Delete the context variables from another project.

### Steps To Reproduce

1. Create a project.
2. Define global context variables.
3. Create another project.
4. Update the global context.

The context variables of the previous project are maintained.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: v12.22.6
- npm version: 6.14.15
- Platform/OS: Rasperry Pi/Raspbian
- Browser: Chrome

**Comment by mannharleen** [comment]
@knolleary I watching your live stream recording and typing this. 
bouncing my thoughts here- should we be deleting global contexts while switching projects? With persistence stores we would like to keep the global context across project switches won’t we?

**Comment by knolleary** [comment]
@mannharleen why would you want to keep state from one project polluting the state of a different project?

Have you got a example where you would want to keep global context when switching projects?

I hadn't consider anyone would depend on this behaviour as it sounds like a bug to me. But if it is something that people use, then we'll have to save the change until 2.2.

**Comment by Steve-Mcl** [comment]
Nick, I had a similar thought. Suppose the project you are loading is a bug fix version of the existing flow, you could reasonably argue that you'd want to keep all context. 

Should this feature/fix perhaps be an option presented on the project switching dialog that defaults to current condition until V3?

**Comment by mannharleen** [comment]
> @mannharleen why would you want to keep state from one project polluting the state of a different project?
> 
> Have you got a example where you would want to keep global context when switching projects?
> 
> I hadn't consider anyone would depend on this behaviour as it sounds like a bug to me. But if it is something that people use, then we'll have to save the change until 2.2.

We use the global context to store some meta data that holds true for the running NR process regardless of the project being used. e.g. servicename, version, features enabled etc. These items are set when the NR process is started (not using functionGlobalContext in settings.js)

I decided to use the global context for such information on the basis that - a project is after all a set of flows (flow.json), project dependencies (package.json) and the encryption key (flow_cred.json). flow.json concerns with flows, subflow and nodes; implying that the project concerns with flow context and node context. The global context in my mind belongs to the NR process and should live across projects.

**Comment by knolleary** [comment]
Okay - that all sounds reasonable. There are good arguments for both clearing context and *not* clearing context.

We will need to make this an option when you switch projects - and thus a new feature for 2.2.

**Comment by knolleary** [comment]
Have now added a checkbox to the Open Project dialog to choose whether to clear context or not.

By default it is checked (clear context).

**Comment by knolleary** [comment]
>  should the default not be same as existing functionality

That is certainly a point of discussion.

The general consensus in this issue and the PR is the expected default behaviour is to clear context if you are switching projects as you don't want one project to interfere with another. But you made the valid point that there are use cases that would choose otherwise.

This is why we haven't treated this as a bug fix, rather as a new feature where we provide an option on the behaviour.

The question of backward compatibility isn't quite the same here as it would if we changed the behaviour of a node in a flow.
