### ISSUE TITLE
Function node not resolve "new RegExp()" method

### ISSUE THREAD

**Issue by danielelopez1** [node-red/node-red#3245]
### Current Behavior

Hello, i'm usign the function node.
I want transform a string in a regex. 
To make it simple  i wrote a simple code:
```
var asd='d(b+)d+';
var myRe = new RegExp(asd);
msg.debug=myRe;
return msg;
```

I have a debug in the end of this simple function but it return to me msg.debug as an empty object. 
I'm wondering why it don't get me the regex i espect

### Expected Behavior

I expect msg.debug is evaluated with /d(b+)d+/

### Steps To Reproduce

Create a funcion node and isert the code above

### Example flow

```
[{"id":"8cd32cd6d9e7af5e","type":"function","z":"11a5b37a8e32f9b5","name":"","func":"var asd='d(b+)d+';\nvar myRe = new RegExp(asd);\nmsg.debug=myRe;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1620,"y":2760,"wires":[["614062c4e48bb49c"]]},{"id":"d9e8223b4bc37d9d","type":"inject","z":"11a5b37a8e32f9b5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1470,"y":2760,"wires":[["8cd32cd6d9e7af5e"]]},{"id":"614062c4e48bb49c","type":"debug","z":"11a5b37a8e32f9b5","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1780,"y":2760,"wires":[]}]
```

### Environment

- Node-RED version: 2.0.6
- Node.js version: v14.17.6
- npm version: 6.14.15
- Platform/OS: Alpine Linux v3.11
- Browser: chrome
- Node-red is running in a docker container

**Comment by hardillb** [comment]
I'm not sure what you are trying to actually achieve here.

If you add a second function node with the following after your function node with the following and wire it up to a debug node

```
var string = "dbbbbbdddddd";
msg.payload = string.match(msg.debug)
return msg;
```

The second debug node gives the correct output of the evaluated regex.

In your example there is nothing to output because the regex has not been applied to any input string. It's rendered as an empty object in the debug sidebar because it has no keys to show.


```
[{"id":"8cd32cd6d9e7af5e","type":"function","z":"11a5b37a8e32f9b5","name":"","func":"var asd='d(b+)d+';\nvar myRe = new RegExp(asd);\nmsg.debug=myRe;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1620,"y":2760,"wires":[["614062c4e48bb49c"]]},{"id":"d9e8223b4bc37d9d","type":"inject","z":"11a5b37a8e32f9b5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1470,"y":2760,"wires":[["8cd32cd6d9e7af5e"]]},{"id":"614062c4e48bb49c","type":"debug","z":"11a5b37a8e32f9b5","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1780,"y":2760,"wires":[]}]
```

**Comment by knolleary** [comment]
The issue is that Debug doesn't have any special handling of RegExp type objects, so they are handled as regular objects and don't have any enumerable properties.

The question then is whether we should add RegExp as a supported type in debug.
