### ISSUE TITLE
Git SSH-Key based authentication failes, if username contains "AT" character

### ISSUE THREAD

**Issue by crackytsi** [node-red/node-red#3246]
### Current Behavior

Hello,
Short: Access to a GIT system using ssh-key based authentication seems to fail because the username contains the "@" character.

I use Header based authentication on node-red and my usernames have the format of an email adress (e.g. firstname-secondname.lastname@example.com).
If we try to authenticate using ssh-key based authentication it failes.

### Expected Behavior

Expected behaviour is, that ssh-key authentication works.

### Steps To Reproduce

Set username (e.g. using reverse-proxy header variable to an email adress and try to fetch branches of a GIT system (e.g. gitea).
Configure in the project an ssh based git access ssh://git@... or git@...
Set User Email and Name, generate a key.
Try to push to the git repo (or first fetch branches). It will fail.

There are only these log messages:
```
4 Nov 16:13:26 - [trace] runGitCommandWithAuth {}
4 Nov 16:13:26 - [trace] git["fetch","origin"]

```

What I tried:
a) Manually try an ssh:
```

 ssh -i /home/nodered/.node-red/projects/.sshkeys/Firstname-secondname.lastname\@example.com_gitea_key git@gitea.example.com
LDAP Login enabled
PTY allocation request failed on channel 0
Hi there, Firstname-secondname.lastname_example.com! You've successfully authenticated with the key named TheHiveWorkflow, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
Connection to gitea@example.com closed.
```

b) Copied private-key /home/nodered/.node-red/projects/.sshkeys/Firstname-secondname.lastname\@example.com_gitea_key to /home/nodered/.ssh/id_rsa
==> Everything works

c) I tried to output auth.key_path arround line 577 in:
/usr/lib/node-red/node_modules/\@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js
but it was not set (even it was configured):

### Example flow

n.a.

### Environment

- Node-RED version: 2.1.3
- Node.js version:  v14.17.6
- npm version: 6.14.15
- Platform/OS: RHEL7
- Browser: Chrome
- git version: git version 2.31.1

**Comment by crackytsi** [comment]
@knolleary : Do you have any hint for debugging this? E.g. print out the used path / shell command?

**Comment by hardillb** [comment]
Please give more details about what you mean by:

> I use Header based authentication on node-red 

Do you mean you have configured adminAuth? If so how?

**Comment by crackytsi** [comment]
@hardillb : I use an admin-auth module (using reverse-proxy header) that returns a user-name in form of "Firstname.SecondName@Example.com". 
Everything works fine and as expected, so I'm pretty sure that NodeRed only has some issues to access git with the "@" character in username to obtain the keys.

**Comment by hardillb** [comment]
That really doesn't help, show us what you changed in the `settings.js` file to enable adminAuth

**Comment by knolleary** [comment]
I did start looking at this issue a little while ago, but got sidetracked.

I guessed there may have been an issue with escaping the `@` symbol when we invoke the various git commands. I hadn't got around to a full end-to-end test, but I manually ran the commands we use with an `@` in the username and it all appeared to work.

I don't think the specifics of how `adminAuth` is going to be too relevant here. What matters is the username has an `@` in it - which could be set manually.

**Comment by crackytsi** [comment]
I was able to reproduce it using this example stance in settings.js:
```
    type: "credentials",
    users: [
        {
            username: "Firstname.Lastname@Example.com",
            password: "$...",
            permissions: "*"
        }
    ]
    },
```

**Comment by crackytsi** [comment]
> I did start looking at this issue a little while ago, but got sidetracked.
> 
> I guessed there may have been an issue with escaping the `@` symbol when we invoke the various git commands. I hadn't got around to a full end-to-end test, but I manually ran the commands we use with an `@` in the username and it all appeared to work.
> 
> I don't think the specifics of how `adminAuth` is going to be too relevant here. What matters is the username has an `@` in it - which could be set manually.

Thank you :) 
The filename leading to the user-key contains the username and therefore an @ char. I assume that there is an issue to reach this filename. As written in my first post, it seems that exactly this file can't be reached. If I put the key in .ssh directory manually everything works.

**Comment by crackytsi** [comment]
> And if you have no adminAuth does the git problem still happen?
> 
> If you enable the trace log it should print out the git commands it using. You need to change the "level" entry in the logging -> console section of the settings.js

Thanks for your idear so far :) Unfortunately I don't understand what you mean with this suggestion. AdminAuth defines in my case the username that is later taken for choosing the key. 
I already enabled the trace logs. Even the first git command does not work. See my first post. Unfortunately trace does not log so much here, e.g. full executed command incl. all parameters.

**Comment by knolleary** [comment]
Ahh, sorry, I missed you had shared the trace log already:
```
4 Nov 16:13:26 - [trace] runGitCommandWithAuth {}
```

Okay - so that *does* tell us something isn't working. If you compare it to the example I shared:
```
7 Dec 10:22:31 - [trace] runGitCommandWithSSHCommand {"key_path":"/Users/nol/.node-red/projects/.sshkeys/first.last@example.com_test-at-symbol","passphrase":""}
```

you can see it isn't even trying to use the key for some reason. The question is why not...

It is also important to note you were trying to fetch remote branches, rather than clone a project. GIven that is a different code path, I should retest with that scenario.

**Comment by crackytsi** [comment]
I can't see which file NR tried to use for authentication.

```
7 Dec 11:30:54 - [trace] git["push","origin","HEAD:master","--porcelain"]
7 Dec 11:30:54 - [debug] git -c credential.helper= push origin HEAD:master --porcelain
7 Dec 11:30:54 - [debug] [err] LDAP Login enabled
7 Dec 11:30:54 - [debug] [err] Permission denied, please try again.
7 Dec 11:30:54 - [debug] [err] Permission denied, please try again.
7 Dec 11:30:54 - [debug] [err] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
7 Dec 11:30:54 - [debug] [err] fatal: Could not read from remote repository.
7 Dec 11:30:54 - [debug] [err]
7 Dec 11:30:54 - [debug] [err] Please make sure you have the correct access rights
7 Dec 11:30:54 - [debug] [err] and the repository exists.
7 Dec 11:30:54 - [debug] rc=128
7 Dec 11:31:14 - [trace] runGitCommandWithAuth {}
7 Dec 11:31:14 - [trace] git["push","origin","HEAD:master","--porcelain"]
7 Dec 11:31:14 - [debug] git -c credential.helper= push origin HEAD:master --porcelain
7 Dec 11:31:14 - [debug] [err] LDAP Login enabled
7 Dec 11:31:14 - [debug] [err] Permission denied, please try again.
7 Dec 11:31:14 - [debug] [err] Permission denied, please try again.
7 Dec 11:31:14 - [debug] [err] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
7 Dec 11:31:14 - [debug] [err] fatal: Could not read from remote repository.
7 Dec 11:31:14 - [debug] [err]
7 Dec 11:31:14 - [debug] [err] Please make sure you have the correct access rights
7 Dec 11:31:14 - [debug] [err] and the repository exists.
7 Dec 11:31:14 - [debug] rc=128
```

Using e.g. repo:

- git@XXXXXX:path/test2.git

Key files are located at:

- /opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key
- /opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key.pub
-

**Comment by crackytsi** [comment]
I wonder why "runGitCommandWithSSHCommand" is not used here. 
![image](https://user-images.githubusercontent.com/11610825/145014167-c1dea18f-8011-40d9-bcae-13a27cb04519.png)

**Comment by knolleary** [comment]
> I wonder why "runGitCommandWithSSHCommand" is not used here.

I was just about to ask about that. What is the exact format of the remote git repo url you are using?

**Comment by crackytsi** [comment]
I tried "ssh://git@XXXXXX:path/test2.git" or just simple "git@XXXXXX:path/test2.git" (this was the example here).
Actually it does both work (If I do the hack with a manually provided key via ssh-pubkey auth) or using user/password.

**Comment by knolleary** [comment]
On a newly restarted Node-RED (to flush all the information it thinks it knows about what auth methods are needed), when you try to push to the remote, do you get the authentication required prompt? If so, is it the ssh key or username/password prompt?

It ought to be a prompt like this:

![image](https://user-images.githubusercontent.com/51083/145015444-e3981d93-741b-4256-a72c-2133819ffdec.png)

**Comment by crackytsi** [comment]
![image](https://user-images.githubusercontent.com/11610825/145015746-0c7cf4c3-ae17-4ee8-8ec8-f2bf094ab834.png)

**Comment by knolleary** [comment]
In the browser dev tools, you should see a network request to `push` when you click the push button. Can you check what response that request gets?

It should be a JSON object with `code` set to `git_auth_failed`. The `message` property will be something different.

```
{"code":"git_auth_failed","message":"git@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"}
```

**Comment by crackytsi** [comment]
Ok, I changed the git repo to ssh://...
Now I can see:
```
7 Dec 11:54:43 - [trace] runGitCommandWithSSHCommand {"keyFile":"gitea_key","passphrase":"[hidden]"key_path":"/opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key"}
7 Dec 11:54:43 - [trace] git["fetch","origin"]
7 Dec 11:54:55 - [trace] runGitCommandWithSSHCommand {"keyFile":"gitea_key","passphrase":"[hidden]"key_path":"/opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key"}
7 Dec 11:54:55 - [trace] git["fetch","origin"]
7 Dec 11:55:10 - [trace] runGitCommandWithSSHCommand {"keyFile":"gitea_key","passphrase":"[hidden]"key_path":"/opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key"}
7 Dec 11:55:10 - [trace] git["fetch","origin"]
7 Dec 11:55:14 - [trace] runGitCommandWithSSHCommand {"keyFile":"second","passphrase":"[hidden]"key_path":"/opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_second"}
7 Dec 11:55:14 - [trace] git["fetch","origin"]
```

**Comment by crackytsi** [comment]
> In the browser dev tools, you should see a network request to `push` when you click the push button. Can you check what response that request gets?
> 
> It should be a JSON object with `code` set to `git_auth_failed`. The `message` property will be something different.
> 
> ```
> {"code":"git_auth_failed","message":"git@github.com: Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"}
> ```

Thats indeed new:
Response is strange:
`{"code":"git_auth_failed","message":"ssh: Could not resolve hostname nodered.example.com:firstname.lastname_example.com: Name or service not known\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","remote":"origin"`

Actually remote repo is now:
git@nodered.example.com:firstname.lastname_example.com/TheHiveFlow.git

**Comment by knolleary** [comment]
In the browser console, what does `RED.projects.getActiveProject().git.remotes['origin'].fetch` return ?

The fact the auth-failed dialog you see has neither SSH keys or username/password details means we haven't recognised what type of git url you are using.

The command above will give you the url we're testing. I can then check that manually to see why it is failing the checks.

**Comment by crackytsi** [comment]
Result is: 'ssh://git@nodered.example.com:firstname.lastname_example.com/example.git'

**Comment by knolleary** [comment]
That url passes the regex check for an ssh repo - so it should have prompted you for the ssh key to use. I'm confused now.

**Comment by crackytsi** [comment]
Would it be possible, that a "/" is expected between hostname and GIT-Repo-Path? Actually the URL is a Strg+C / Strg+V copy of the Git-system (gitea). But the message from browser-console seems to resolve the hostname WITH the repo-Path. !?

**Comment by knolleary** [comment]
I don't understand why it would be saying could not resolve hostname if, as you say, it works fine with the ssh key copied to `/home/nodered/.ssh/id_rsa`. The location of the keyfile has nothing to do with dns resolution.

That format of git url isn't particular different. GitHub urls don't have the `/` separator either: `git@github.com:knolleary/node-red-workshop-photobooth-project.git`

I wonder if the presence of `.` in the repo path (and `.com`) is confusing things somewhere... but really hard to see where as we don't do any parsing of the url (other than to decide if we are doing https or ssh based auth).

**Comment by crackytsi** [comment]
> That url passes the regex check for an ssh repo - so it should have prompted you for the ssh key to use. I'm confused now.

Sorry I changed the git URL to ssh://git@nodered.example.com:firstname.lastname_example.com/example.git 23 minutes ago. After that time there was the dialog: 
![image](https://user-images.githubusercontent.com/11610825/145020346-8addb706-b4d0-4486-83ce-7e4edee114b4.png)

See logs 24 minutes ago.

**Comment by knolleary** [comment]
Okay. So the dns error has started happening after you changed the git url to that other format?

What exact format of url were you using before changing it?

**Comment by crackytsi** [comment]
I only added the prefix ssh:// and I manually compared character by character with the Gitlab Repo-URL. It's the same.
Before: git@nodered.example.com:firstname.lastname_example.com/example.git  
After: ssh://git@nodered.example.com:firstname.lastname_example.com/example.git

**Comment by crackytsi** [comment]
> Okay. So the dns error has started happening after you changed the git url

I don't know to be honest. I don't have it in my browser history. So I only could reconfigure it back to "without the prefix"

**Comment by knolleary** [comment]
> Before: git@nodered.example.com:firstname.lastname_example.com/example.git
> After: ssh://git@nodered.example.com:firstname.lastname_example.com/example.git

Both of those urls pass the 'is it an ssh url' test we have - so you should have been prompted for ssh key choice in both cases.

**Comment by crackytsi** [comment]
ok, that was also my impression before these tests.
What about the Resolve Hostname issue? Is the hostname wrongly extracted here or is it just a little confusing message?
Is it possible to "manually" do run the GIT-Command or output it exactly as it is executed in the source-code?

**Comment by knolleary** [comment]
Manually reproducing the exact command is a little tricky due to the way git and ssh interact.

If you're able to edit the source code, have a look in `/usr/lib/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js`, line 96 is where `runGitCommandWithSSHCommand` is. You'll see we set a bunch of environment variables under `commandEnv`.

Add a `console.log(commandEnv)` to see exactly what is being set

**Comment by crackytsi** [comment]
Output:

How can I identify if askpass.sh is used?
```
7 Dec 12:45:01 - [trace] runGitCommandWithSSHCommand {"keyFile":"gitea_key","passphrase":"[hidden]"key_path":"/opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key"}
{
  NODE_EXTRA_CA_CERTS: '/etc/npmcacert.crt',
  SHELL: '/bin/bash',
  NODE_OPTIONS: '--max_old_space_size=256',
  USER: 'workflow',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin',
  PWD: '/opt/workflow',
  LANG: 'en_US.UTF-8',
  SHLVL: '1',
  HOME: '/opt/workflow',
  LOGNAME: 'workflow',
  _: '/usr/bin/env',
  NODE_RED_HOME: '/usr/lib/node_modules/node-red',
  SSH_ASKPASS: '/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/node-red-ask-pass.sh',
  DISPLAY: 'dummy:0',
  NODE_RED_GIT_NODE_PATH: '/usr/bin/node',
  NODE_RED_GIT_SOCK_PATH: '/tmp/node-red-git-askpass-bdfc573cb4d54ebc-sock',
  NODE_RED_GIT_ASKPASS_PATH: '/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/authWriter.js',
  GIT_SSH: '/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/node-red-ssh.sh',
  NODE_RED_KEY_FILE: '/opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key',
  GIT_SSH_COMMAND: 'ssh -i /opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key -F /dev/null'
}
7 Dec 12:45:01 - [trace] git["fetch","origin"]
```

I forgot that there is a "-" in the username as well.
Could you please also very if the regex works with username like "Firstname-Secondname.Lastname@example.com" (with- char).

**Comment by knolleary** [comment]
```
var url="ssh://git@nodered.example.com:firstname-secondname.lastname_example.com/example.git"
console.log(/^(?:ssh|[\d\w\.\-_]+@[\w\.]+):(?:\/\/)?/.test(url))

true
```


`SSH_ASKPASS` only kicks in if the ssh key has a passphrase.

If you are on git 2.3.0 or newer then try the following inside the project's directory:

```
export GIT_SSH_COMMAND=ssh -i /opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key -F /dev/null
git -c credential.helper= fetch origin
```

**Comment by crackytsi** [comment]
I get the following result:
```

-bash-4.2$ export GIT_SSH_COMMAND="ssh -i /opt/workflow/.node-red/projects/.sshkeys/Firstname.Lastname@example.com_gitea_key"
-bash-4.2$ git -c credential.helper= fetch origin
LDAP Login enabled
-bash-4.2$ pwd
/opt/workflow/.node-red/projects/NewProject/.git
-bash-4.2$ vim config
-bash-4.2$ git -c credential.helper= fetch origin
ssh: hostname nodered.example.com:firstname.lastname_example.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Then I replaced in the config file:
url = ssh://git@nodered.example.com:firstname-secondname.lastname_example.com/example.git
by
ssh://git@nodered.example.com**/**firstname-secondname.lastname_example.com/example.git

After that it worked on console :) :) :)
```
-bash-4.2$ git -c credential.helper= fetch origin
LDAP Login enabled
```

I also restart nodered, there it works now also.

@knolleary The question is what is wrong:

- Bug in Gitea
- Bug in Git
- Bug in NodeRed

**Comment by knolleary** [comment]
> The question is what is wrong:
>  - Bug in Gitea
>  - Bug in Git
>  - Bug in NodeRed

So have we narrowed this down to a git url with a `-` in the path path? Because I can use a git repo url with the `:` separate without issue.

I cannot easily setup a test for a repo with `-` in the organisation name part of the path.

**Comment by crackytsi** [comment]
No, the separator between GIT Hostname and Path is the issue.
Nothing about - or @ char.

There are the formats:
( ssh:// ) hostname.fqdn : path/to/-/git
( ssh:// ) hostname.fqdn / path/to/-/git

I don't know why, but if I replace the first one by the second one character it works

**Comment by knolleary** [comment]
The only reason I asked about the `-` was because having a `:` in the path works fine for me as its the standard format. `git@github.com:knolleary/node-red-workshop-photobooth-project.git`

So I was wondering if there was a combination of things - having the `:` *and* the `-`.

**Comment by knolleary** [comment]
Also worth noting that your urls have both `.` and `com` in the repo name - `firstname.lastname_example.com` - which could be tripping up some url parsing somewhere in the stack.

But that is all in the git/ssh layer - node-red doesn't do any parsing of the repo url at that level.

**Comment by crackytsi** [comment]
Ok. In this case I want to say you a warn and very big: THANK YOU!!!
I have learned a lot about NR today and unfortunately consumed a lot of time.
Thanks, next time I know how to debug ;)

**Comment by crackytsi** [comment]
Gitea offers SSH URLs separating Hostname and git-path by ":", meanwhile there the underlying GIT (2.31.1) seems to work together only with the URL if you replace the ":" by "/". 

Reason is unclear, but definitively not a Node-Red issue.

**Comment by knolleary** [comment]
Glad we got some sort of resolution.

👍🏻
