### ISSUE TITLE
Copy more then one node and try past in a group don't work properly

### ISSUE THREAD

**Issue by Mitaro-BR** [node-red/node-red#3247]
### Current Behavior

When you select one node, copy it and paste and you point the mouse over a node group, it's highlight and when you click over it, the pasted node automatically was pasted in the hovered group. But when you select more than one node in same time, copy it and past and try to paste in a group, the group hovered do not highlight and  we cannot past directly in a group like occur with one node.

### Expected Behavior

When you select more then one node, copy it and paste hovering a group, it's need to be highlighted and if you click over it, the nodes needs to pasted inside the group.

### Steps To Reproduce

create a group of nodes;
select more than one node (in this group or not);
copy it;
try to paste it inside a group.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: 12.22.7
- npm version: 6.14.15
- Platform/OS: Debian
- Browser: Chrome

**Comment by knolleary** [comment]
Group handling was overhauled in 3.1.0. You can now copy/paste and drag/drop multiple nodes into a group in one go.
