### ISSUE TITLE
Link Call node inside a subflow - cannot call links outside the subflow

### ISSUE THREAD

**Issue by krambriw** [node-red/node-red#3248]
### Current Behavior

When I put a Link Call node inside a subflow, it cannot call Link In nodes to subroutines outside and receive the result back. This is in my case preventing me to efficently optimize my flows by using the concept of subroutines while still keeping the concept of subflows

  

### Expected Behavior

Link Call nodes in subflows shall be able to call Link In nodes to subroutines outside in the flow and receive the requested result back in the same way as it would if placed anywhere else in the flow 

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/20238676/140684860-c22b21c8-8d6b-4601-9b54-466432a5daa3.png)

See flow below

### Example flow

```
[{"id":"51dabc17cfa067e9","type":"subflow","name":"say hello","info":"","category":"","in":[{"x":140,"y":80,"wires":[{"id":"7178cf56594ffd72"}]}],"out":[{"x":360,"y":80,"wires":[{"id":"7178cf56594ffd72","port":0}]}],"env":[],"meta":{},"color":"#DDAA99"},{"id":"7178cf56594ffd72","type":"link call","z":"51dabc17cfa067e9","name":"","links":[],"timeout":"30","x":250,"y":80,"wires":[[]]},{"id":"d58c92191a7530d4","type":"link in","z":"c8ba88e10ee7881c","name":"say_hello_in","links":[],"x":365,"y":360,"wires":[["2f83ceace6d4feeb"]]},{"id":"2f83ceace6d4feeb","type":"change","z":"c8ba88e10ee7881c","name":"say hello","rules":[{"t":"set","p":"payload","pt":"msg","to":"hello","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":500,"y":360,"wires":[["c6b3b2f802326912"]]},{"id":"c6b3b2f802326912","type":"link out","z":"c8ba88e10ee7881c","name":"","mode":"return","links":[],"x":635,"y":360,"wires":[]},{"id":"a85706416900f173","type":"inject","z":"c8ba88e10ee7881c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":320,"y":440,"wires":[["a07284dd40cd96cd"]]},{"id":"8168685151bc5421","type":"debug","z":"c8ba88e10ee7881c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":690,"y":440,"wires":[]},{"id":"a07284dd40cd96cd","type":"subflow:51dabc17cfa067e9","z":"c8ba88e10ee7881c","name":"","env":[],"x":500,"y":440,"wires":[["8168685151bc5421"]]}]
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: v14.18.1
- npm version: 6.14.15
- Platform/OS: RPi4 Buster
- Browser: Chrome

**Comment by dceejay** [comment]
This is indeed a restriction of subflows. There is work going on to make subflows exportable as new nodes. Allowing them to call out would make it that much harder to include all the necessary parts.

**Comment by knolleary** [comment]
From a technical standpoint, there is less of a reason to disallow Link Call nodes inside a subflow being able to call a link node outside the subflow.

The real technical issue is being able to call *in* to a subflow, as we don't know which instance of the subflow to call in to. But in the case of the Link Call node calling *out* of the subflow, we'll have the right subflow instance id to be able to return the message to the right place.

It is true that this would make the exporting of subflows trickier if they including Link Call nodes... but that could be handled as warning/issue at export time in the rare occasions someone does that.

**Comment by krambriw** [comment]
The thing I runned into in this case was that inside the subflow I have a node for image analyzing that consumes "more memory", loading models etc, than what I assume nodes in general do. So in my case, it would, from a memory consumption perspective, be smarter to keep that node outside of the subflow to avoid multiple instances, multiple model loadings etc. A neater design would then be to create a subroution where this node is positioned and instead have a Link Call node in the subflow. Maybe this would be valid for other nodes consuming more memory than average

Just for the fun, I have tested another design, replacing the node in the subflow with a MQTT out/in node pair, pushing the data for analyze via a broker to the subroutine and then returning the result backvia the same broker. It works as expected but is a design not really in my favour since it would require the end user to have a MQTT broker installed in addition (somewhere). Another alternative would be to completely scrath the subflow design and instead put the whole content into a subroutine, replace the subflows with Link Call nodes. Unfortunately this would require end users to redo a lot of their configurations since it would break the backward compatibility

Besides, I like the concept of subflows, I think subflows, subroutines and Link Calls from subflows would work very nicely together, allowing the creation of compact, still understandable flow designs with efficient communication between them

**Comment by krambriw** [comment]
Hello, just wonder, any chance this will get incorporated at some stage? If so, any indication when?
Best regards, Walter

**Comment by krambriw** [comment]
Hi Stephen, sorry for late reply, was in Germany on a business trip this week
I have never runned from source so I do not even know how to

But I can try in some way, to build a simple test flow is easy for me

Best regards,
Walter Kraembring

***@***.*** ***@***.***>

**Comment by Steve-Mcl** [comment]
Hey Walter. 

I've updated my development environment with all of the latest additions. Could you provide a small flow that demonstrates your particular problem and I will test it.

**Comment by krambriw** [comment]
Hello Stephen, yes sure!

The flow below is a simple example. You would need to install the additional nodes unless you don't have them already ;)
- node-red-contrib-tfjs-coco-ssd
- node-red-contrib-image-tools

In each Go button, edit the path to a sample image (I think topic might be irrelevant). Then in the sub-flow, link the link call node to the "Object detection request” link in node (in current version of the link call node, link in nodes cannot be linked, not even seen in the list when placed in a sub-flow)

To test, click each go button, if it works you should see the result; annotated image and the corresponding returned result from the analyze in debug



Best regards,
Walter Kraembring

***@***.*** ***@***.***>

**Comment by Steve-Mcl** [comment]
Hi Walter, there is no flow in your reply however, I used your original posts flow.  

In a way, this can now be achieved...

![image](https://user-images.githubusercontent.com/44235289/162759698-805d80bc-a3b5-4f09-8d5a-a4c1dd3b2ca4.png)


However, to achieve this, the new dynamic mode has to be used...

![image](https://user-images.githubusercontent.com/44235289/162760177-39ef560c-d92e-41b9-8fa8-847a943bd8ca.png)


This is because the list is scoped to the subflow...
![image](https://user-images.githubusercontent.com/44235289/162760424-c8d7fc27-997d-4a66-9a58-37a5d059ec3c.png)


@knolleary @dceejay, I see 2 options...
1. Leave it as is (can work / does work)
2. Populate the list from both subflow and regular flows, allowing the user to chose both internal and external.

You thoughts would be appreciated before I head down one branch or another.

**Comment by Steve-Mcl** [comment]
> I'm not sure about your example, why you need a change node inside the subflow. 

Because the new feature (dynamic link call) needs `msg.target` to work.  But yes, it would work.

However, I have now (almost) finished modifying code to display link targets outside of the subflow (but not into a subflow as that was explicitly rejected in the design)

Here are some screenshots to (try to) make it clear...

![image](https://user-images.githubusercontent.com/44235289/163047036-bdda0602-516f-44f8-9864-04e81fa397d7.png)


![image](https://user-images.githubusercontent.com/44235289/163047384-e6482b3f-cccf-443f-bfa1-961175203d75.png)


![image](https://user-images.githubusercontent.com/44235289/163047546-1cb0ee6c-309d-4f9b-a27e-5200e76fb7f6.png)


![image](https://user-images.githubusercontent.com/44235289/163047950-33b1c601-826c-4ebb-8bef-d3d8d0d2b767.png)

**Comment by krambriw** [comment]
@Steve-Mcl very nice!!
