### ISSUE TITLE
Tour guide for the first flow doesn't work

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#3255]
### Current Behavior

While translating the first flow guide, I found that users cannot add wire to connect nodes.

![tourguide](https://user-images.githubusercontent.com/20310935/141251512-4a4748cf-c898-4707-a7b2-c0421c322094.gif)

As we can see on the console, `dimension` is not defined before the following code.
https://github.com/node-red/node-red/blob/2.1.3/packages/node_modules/%40node-red/editor-client/src/js/ui/tour/tourGuide.js#L367-L370

Therefore, we need to use [the code](https://github.com/node-red/node-red/blob/2.1.3/packages/node_modules/%40node-red/editor-client/src/js/ui/tour/tourGuide.js#L48-L49) to set the value to `dimension`. After fixing the problem, the handling works correctly and users can add wire.

### Expected Behavior

Users can connect the nodes by wire.

### Steps To Reproduce

1. Open Developer tool on Google Chrome.
2. Enter "RED.tourGuide.run("./tours/first-flow.js")" on console.
3. Create flow according to the tour guide.

### Environment

- Node-RED version: v2.1.3
- Node.js version: v16.1.0
- npm version: v7.18.1
- Platform/OS: Ubuntu 20.04.2 LTS on WSL2 in Windows 10
- Browser: Google Chrome 95.0.4638.69 (Official Build)(64 bit)

**Comment by knolleary** [comment]
The 'first-flow' tour isn't one we expose to end users and was created as an experiment to help build the features and APIs of the tour-guide. As 2.1 got nearer, I focussed more on the Welcome Tour as that is the one we show users - and the first-flow tour was forgotten about.

Thanks for investigating and finding the fix.

**Comment by kazuhitoyokoi** [comment]
Thank you for explaining the background. The tour functionality will be useful for beginner users.

**Comment by gazoscalvertos** [comment]
This is a great idea. How can we trigger this custom nodes?
