### ISSUE TITLE
Installing Node red on K3S - Raspberry Pi Cluster

### ISSUE THREAD

**Issue by hitenlulla** [node-red/node-red#3259]
Hello sir, I am trying to create a server using a Raspberry Pi Cluster to use node red. Can you help me how to install node red on K3S Kubernetes by creating a YAML file? I need to install using yaml because I want load balancing. I am unable to find the script in the documentation.

**Comment by hardillb** [comment]
As mentioned in the template, please ask how to questions on the forum or in slack where the whole community can help not just the core contributors, Issues are only used for defects in the code.
