### ISSUE TITLE
Auto-complete feature issue

### ISSUE THREAD

**Issue by unborn-andy** [node-red/node-red#3271]
### Current Behavior

When typing some characters in the typedInput field of some nodes (like the HTML, JSON nodes)
and selecting a recommendation of the auto-complete. The selection is not retained but just the typed in letters.

A picture is a thousand words

![Animation](https://user-images.githubusercontent.com/93290787/142965251-93ec88f0-f055-4f08-a831-de1104e7f81c.gif)

### Expected Behavior

The TypedInput field to retain the selected autocomplete.

### Environment

- Node-RED version: 2.1.3
- Node.js version: v14.18.1
- npm version: 6.14.15
- Platform/OS: Windows 10
- Browser: Firefox 94, Chrome 96

**Comment by knolleary** [comment]
This only appears to happen if you click on the completion. If you use the keyboard cursor keys/enter to select the completion it works as expected.
