### ISSUE TITLE
the dashboard do not show icon when install nodes in user directory 

### ISSUE THREAD

**Issue by yuql** [node-red/node-red#3283]
### Current Behavior

the dashboard do not show icon when install nodes in user directory 
I install this nodes:https://github.com/node-red/node-red-nodes/tree/master/utility/annotate-image

I found, if the js code used require function, the dashboard always do not show this node.

### Expected Behavior

show what i installed node.

### Steps To Reproduce

1. git clone https://github.com/node-red/node-red-nodes.git to  E:\node-red-library\node-red-nodes
2. cd C:\Users\Administrator\.node-red
3. install annotate-image node
npm install E:\node-red-library\node-red-nodes\utility\annotate-image
4. restart node-red

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:v2.1.3
- Node.js version: v14.17.0
- npm version: v6.14.13
- Platform/OS:Windows_NT 10.0.19043 ia32 LE
- Browser: Google Chrome 95.0.4638.69

**Comment by hardillb** [comment]
Please supply the Node-RED logs from when you started Node-RED after the install. It should log why it failed to load a node

**Comment by knolleary** [comment]
I'm not able to reproduce this issue. I have the node-red-nodes repository checked out locally. I ran the npm install of the annotate-image node to `~/.node-red`. I then restarted Node-RED is loaded with the current icon:

![image](https://user-images.githubusercontent.com/51083/144391676-3e100dbd-710f-4d98-b8a3-51293d00c447.png)


> I found, if the js code used require function, the dashboard always do not show this node.

Can you explain what you mean?

**Comment by hardillb** [comment]
Assuming I've understood the problem properly (please supply the logs I asked for)

This looks like something strange with npm.

I've just checked out a totally clean copyof the node-red-nodes and if I just try and use npm to install it in a userDir it doesn't appear to install the dependencies (pureimage)

```
2 Dec 09:12:59 - [warn] ------------------------------------------------------
2 Dec 09:12:59 - [warn] [node-red-node-annotate-image/annotate] Error: Cannot find module 'pureimage'
Require stack:
- /opt/share/playing/node-red/node-red-nodes/utility/annotate-image/annotate.js
- /opt/share/playing/node-red/test/node_modules/@node-red/registry/lib/loader.js
- /opt/share/playing/node-red/test/node_modules/@node-red/registry/lib/index.js
- /opt/share/playing/node-red/test/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/share/playing/node-red/test/node_modules/@node-red/runtime/lib/index.js
- /opt/share/playing/node-red/test/node_modules/node-red/lib/red.js
- /opt/share/playing/node-red/test/node_modules/node-red/red.js
2 Dec 09:12:59 - [warn] ------------------------------------------------------
```

running `npm install` in the `node-red-nodes/utility/annotate-image/` directory fixes the problem

**Comment by yuql** [comment]
My step 

1、start node-red

`C:\Users\Administrator>node-red
2 Dec 18:11:33 - [info]

Welcome to Node-RED
===================

2 Dec 18:11:33 - [info] Node-RED version: v2.1.3
2 Dec 18:11:33 - [info] Node.js  version: v14.17.0
2 Dec 18:11:33 - [info] Windows_NT 10.0.19043 ia32 LE
2 Dec 18:11:34 - [info] Loading palette nodes
2 Dec 18:11:35 - [warn] Missing node modules:
2 Dec 18:11:35 - [warn]  - node-red-node-annotate-image (0.1.2): annotate-image
2 Dec 18:11:35 - [info] Removing modules from config
2 Dec 18:11:35 - [info] Settings file  : C:\Users\Administrator\.node-red\settings.js
2 Dec 18:11:35 - [info] Context store  : 'default' [module=memory]
2 Dec 18:11:35 - [info] User directory : \Users\Administrator\.node-red
2 Dec 18:11:35 - [warn] Projects disabled : editorTheme.projects.enabled=false
2 Dec 18:11:35 - [info] Flows file     : \Users\Administrator\.node-red\flows.json
2 Dec 18:11:36 - [info] Server now running at http://127.0.0.1:1880/
2 Dec 18:11:36 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

2 Dec 18:11:36 - [info] Starting flows
2 Dec 18:11:36 - [info] Started flows

`

2、check nodes
![1](https://user-images.githubusercontent.com/10626353/144402103-3560a407-8717-494e-9e75-6b587fb34112.jpg)

C:\Users\Administrator\.node-red>npm list
node-red-project@0.0.1 C:\Users\Administrator\.node-red
`-- node-red-node-base64@0.3.0

3、Install nodes
`
C:\Users\Administrator\.node-red>npm install E:\node-red-library\node-red-nodes\utility\annotate-image
+ node-red-node-annotate-image@0.1.2
added 5 packages from 27 contributors and audited 6 packages in 3.295s
found 0 vulnerabilities
`

4、restart node-red
`
C:\Users\Administrator>node-red
2 Dec 18:14:59 - [info]

Welcome to Node-RED
===================

2 Dec 18:14:59 - [info] Node-RED version: v2.1.3
2 Dec 18:14:59 - [info] Node.js  version: v14.17.0
2 Dec 18:14:59 - [info] Windows_NT 10.0.19043 ia32 LE
2 Dec 18:15:00 - [info] Loading palette nodes
2 Dec 18:15:01 - [warn] ------------------------------------------------------
2 Dec 18:15:01 - [warn] [node-red-node-annotate-image/annotate] Error: Cannot find module 'pureimage'
Require stack:
- E:\node-red-library\node-red-nodes\utility\annotate-image\annotate.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\loader.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red\lib\red.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red\red.js
2 Dec 18:15:01 - [warn] ------------------------------------------------------
2 Dec 18:15:01 - [info] Settings file  : C:\Users\Administrator\.node-red\settings.js
2 Dec 18:15:01 - [info] Context store  : 'default' [module=memory]
2 Dec 18:15:01 - [info] User directory : \Users\Administrator\.node-red
2 Dec 18:15:01 - [warn] Projects disabled : editorTheme.projects.enabled=false
2 Dec 18:15:01 - [info] Flows file     : \Users\Administrator\.node-red\flows.json
2 Dec 18:15:01 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

2 Dec 18:15:01 - [info] Server now running at http://127.0.0.1:1880/
2 Dec 18:15:01 - [info] Starting flows
2 Dec 18:15:01 - [info] Started flows

`
![1](https://user-images.githubusercontent.com/10626353/144402872-981089fb-35e4-46fb-94db-f9c7b29968ca.jpg)

**Comment by yuql** [comment]
> Assuming I've understood the problem properly (please supply the logs I asked for)
> 
> This looks like something strange with npm.
> 
> I've just checked out a totally clean clone of the node-red-nodes and if I just try and use npm to install it in a userDir it doesn't appear to install the dependencies (pureimage)
> 
> ```
> 2 Dec 09:12:59 - [warn] ------------------------------------------------------
> 2 Dec 09:12:59 - [warn] [node-red-node-annotate-image/annotate] Error: Cannot find module 'pureimage'
> Require stack:
> - /opt/share/playing/node-red/node-red-nodes/utility/annotate-image/annotate.js
> - /opt/share/playing/node-red/test/node_modules/@node-red/registry/lib/loader.js
> - /opt/share/playing/node-red/test/node_modules/@node-red/registry/lib/index.js
> - /opt/share/playing/node-red/test/node_modules/@node-red/runtime/lib/nodes/index.js
> - /opt/share/playing/node-red/test/node_modules/@node-red/runtime/lib/index.js
> - /opt/share/playing/node-red/test/node_modules/node-red/lib/red.js
> - /opt/share/playing/node-red/test/node_modules/node-red/red.js
> 2 Dec 09:12:59 - [warn] ------------------------------------------------------
> ```
> 
> running `npm install` in the `node-red-nodes/utility/annotate-image/` directory fixes the problem

so right operation step , I should first run npm install in  `node-red-nodes/utility/annotate-image/` directory ?

**Comment by hardillb** [comment]
Previously I would have said no, you don't have to do that. But it's possible something has changed in npm.

But I would ask why you are installing it this way and not just via the palette manager or direct from npm? If you are looking to make local changes then I probably would expect you to have run npm in the src directory first.

**Comment by yuql** [comment]
> Previously I would have said no, you don't have to do that. But it's possible something has changed in npm.
> 
> But I would ask why you are installing it this way and not just via the palette manager or direct from npm? If you are looking to make local changes then I probably would expect you to have run npm in the src directory first.

yes, I has another self project , I want to test it before publish. 
Except this method（run npm install in `node-red-nodes/utility/annotate-image/` directory）, Do I have another method to fix this problem?
I just want install my local nodes in one line command

**Comment by yuql** [comment]
What should I do to automatically install dependencies at the same time when installing local nodes?

**Comment by dceejay** [comment]
If you use `npm pack` in your local directory it should produce a tgz file that you can then install with  `npm i path-to/myfile.tgz`
