### ISSUE TITLE
When deploy, msg.payload send the last value even if a node is disconnected

### ISSUE THREAD

**Issue by Ahriman** [node-red/node-red#3285]
### Current Behavior

![image](https://user-images.githubusercontent.com/238355/144721441-af8c0bfc-3cb7-46e7-8d22-b2466abbe95d.png)
ESPURNA node is a plug and is disconnected, but when I press deploy, sends 899 (watts) to the influxdb node and is a big problem when the points join:

### Environment

- Node-RED version: 2.1.4
- Node.js version: 14.18.2
- npm version: 6.14.15
- Platform/OS: Docker in Linux Fedora 35
- Browser: Firefox 94.0

**Comment by hardillb** [comment]
This sounds like the ESPURNA device is publishing messages with the retained bit set so as such any client that subscribes to that topic will always receive the last message. (see [here](https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/) for detailed explanation).

This is most likely not a problem with Node-RED and the MQTT-in node is working as expected.

**Comment by Ahriman** [comment]
Then the problem is MQTT. I have the same problem with Tasmota devices, always keeps the last value. I have the plug disconnected and every time I deploy it resends the value 899. I will see your link now, thank you very much.

**Comment by Ahriman** [comment]
@hardillb thanks for your answer, It's because of what you were saying about the retained messages. Thanks you very much! :)

**Comment by hardillb** [comment]
You can clear a retained message by publishing another message with the retained bit set to the same topic with a null payload.

**Comment by kuema** [comment]
I'd recommend a switch node that filters messages with the `msg.retained` flag set. At least for flows that perform data insertions into databases. That way you can be sure to log "live" data only.
