### ISSUE TITLE
Github Key Verification Failed

### ISSUE THREAD

**Issue by kevinsynnott** [node-red/node-red#3287]
**Current Behavior**
I updated my node-red docker container to 2,1,4. Following this, github key verification fails when trying to push my project to github.
Error
Host key verification failed.
The repository host key could not be verified. Please update your known_hosts file and try again.

**Expected Behavior**
Was working to push project to github before updating. Known hosts file is mapped to the container. Rolling back to nodered/node-red:2.1.3 fixes the issue and problem returns after changing back to nodered/node-red:latest

**Steps To Reproduce**
Using node-red 2.1.4

**Example flow**
paste your flow here

**Environment**
Node-RED version: 2.1.4
Node.js version: (in container v14.18.2)
npm version: (in container 6.14.15)
Platform/OS: Docker/Ubuntu 20.04
Docker version 20.10.11
Browser: Chrome

**Comment by hardillb** [comment]
As this is a issue against the docker container it should really have been raised against the Docker project (github.com/node-red/node-red-docker).

Recently github added 2  new elliptic curve keys so you will need to update your `known_hosts` file or just not map the file into the container as it already ships with a `known_hosts` file that contains all of github's keys from 2.1.3

**Comment by kevinsynnott** [comment]
Apologies for raising in the wrong place. Tried this and working as you explain. Thanks for your time.
