### ISSUE TITLE
Time displayed incorrectly (i.e. 24:59 instead of 00:59)

### ISSUE THREAD

**Issue by krisiasty** [node-red/node-red#3291]
### Current Behavior

Time displayed in node status is incorrect - i.e. 24:59 instead of 00:59
![node-red-time](https://user-images.githubusercontent.com/6045259/144941883-668f4459-ed2a-4ed1-87b5-0ee4683fbdd8.png)

### Expected Behavior

The time should be formatted as 00:59 instead of 24:59

### Environment

- Node-RED version: 2.1.4
- Platform/OS: Home Assistant OS (HAOS) 6.6 on Raspberry Pi 4
- Browser: Chrome 96 on Mac
- Time Zone: Europe/Warsaw

**Comment by hardillb** [comment]
You should raise this with the author of the node in question (Home Assistant?), it is not a problem with Node-RED.

**Comment by krisiasty** [comment]
I'm not familiar with internal working of Node-RED and haven't thought the status is actually generated by the node itself. Thanks for pointing that out. 
I have opened a new issue here: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/524
