### ISSUE TITLE
running nodejs with --stack_trace_limit smaller than 2 causes crash by event deprecation warning

### ISSUE THREAD

**Issue by fmsy** [node-red/node-red#3292]
https://github.com/node-red/node-red/blob/173e75175eb1c40e7b11c8da4bccba8f2eb22937/packages/node_modules/%40node-red/util/lib/events.js#L35

TypeError: Cannot read properties of undefined (reading 'split')
    at EventEmitter.<anonymous> (.../node_modules/@node-red/util/lib/events.js:35:61)

1. please fix your stack parsing
2. shouldnt this event deprecation warning be optional?

**Comment by fmsy** [comment]
@knolleary
Maybe use `Error.captureStackTrace()` and [`Error.stackTraceLimit`](https://nodejs.org/api/errors.html#errorstacktracelimit)

**Comment by knolleary** [comment]
> shouldnt this event deprecation warning be optional?

What event deprecation warning are you referring to?

**Comment by fmsy** [comment]
> > shouldnt this event deprecation warning be optional?
> 
> What event deprecation warning are you referring to?

https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/util/lib/events.js#L25

**Comment by knolleary** [comment]
> shouldnt this event deprecation warning be optional?

Those events are deprecated - continued use of them will break in the future. We need to make use anyone using those events update their code.

We don't have any established pattern for making such warnings optional - so it wasn't something considered.

Out of interest, why do you run with the limit on stack frames? It wasn't a setting I'd come across before and would be interested to know what benefit you get by limiting the debug information you get in the case of an error.
