### ISSUE TITLE
can not catch nodes error

### ISSUE THREAD

**Issue by yuql** [node-red/node-red#3293]
### Current Behavior

1、I use node-red-contrib-puppeteer-core-chromium to get some info from website.
My step is：
launch -> new page -> goto -> click

2、But sometimes the website html is changed, I mock this change, and at node-red-contrib-puppeteer-core-chromium click node, input a error selector(what dom is not exist).

3、The node will show me the error，But I want to retry 3 times when catch this error.

![image](https://user-images.githubusercontent.com/10626353/144961237-29e56289-9aa2-489e-9418-e7edfe301343.png)

4、I drag a catch node, and set it to catach all. But nothing happened.
I found some discuss from forum,  may be use `node.error(err, msg)` will fix this problem, But this  contrib is not active.

5、So, I want to know how to catch all error, Use node-red existing functions to solve this problem？Instead of looking for a third party

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:v2.1.3
- Node.js version: v14.17.0
- npm version:6.14.13
- Platform/OS:Windows_NT 10.0.19043 ia32 LE
- Browser:chrome v95.0.4638.69

**Comment by knolleary** [comment]
If the node doesn't log the error properly, then you cannot catch it.

Raise an issue against the node to get it updated.

For general how-to questions, please use the forum.
