### ISSUE TITLE
Cannot access Group environment variables inside function node

### ISSUE THREAD

**Issue by mikelebon** [node-red/node-red#3299]
### Current Behavior

Step 1 - Create a node Group environment variable `MY_ENV_VAR` with a value of "hello".

Step 2 - Inside a function node within the Group, `env.get("MY_ENV_VAR")` returns `undefined`

### Expected Behavior

`env.get("MY_ENV_VAR")` should return the variable's value ("hello").

### Steps To Reproduce

See the example flow.

### Example flow

```
[{"id":"5f365e1f0d126a64","type":"tab","label":"Group ENV var Example","disabled":false,"info":"","env":[]},{"id":"49320e1a34d79d7a","type":"group","z":"5f365e1f0d126a64","name":"","style":{"label":true},"nodes":["e4ce71cac84a8b42","03b51c21aca00702","c4b0ca9442f89ef4"],"env":[{"name":"MY_ENV_VAR","value":"hello","type":"str"}],"x":114,"y":79,"w":692,"h":82},{"id":"e4ce71cac84a8b42","type":"inject","z":"5f365e1f0d126a64","g":"49320e1a34d79d7a","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":220,"y":120,"wires":[["03b51c21aca00702"]]},{"id":"03b51c21aca00702","type":"function","z":"5f365e1f0d126a64","g":"49320e1a34d79d7a","name":"Get MY_ENV_VAR","func":"let myVal = env.get(\"MY_ENV_VAR\");\n\nmsg.payload = myVal;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":470,"y":120,"wires":[["c4b0ca9442f89ef4"]]},{"id":"c4b0ca9442f89ef4","type":"debug","z":"5f365e1f0d126a64","g":"49320e1a34d79d7a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":690,"y":120,"wires":[]}]
```

### Environment

- Node-RED version: 2.1.4
- Node.js version: 14.18.1
- npm version: 6.14.15
- Platform/OS: Linux 5.10.43-yocto-standard x64 LE (Docker image)
- Browser: Chrome 96.0.4664.93 (Official Build) (arm64)

**Comment by knolleary** [comment]
The Function node wasn't using the right utility function to access env vars, so was missing the ability to get Group level env vars. Will be fixed in the next maintenance release.
