### ISSUE TITLE
Node parameters still overridden by previous node?

### ISSUE THREAD

**Issue by TheGroundZero** [node-red/node-red#3303]
### Current Behavior

I'm using Node-RED in Home Assistant.

In a recent update, the behaviour of nodes and flows seems to have changed.
The output of previous nodes now overrides the parameters of laters nodes, a direct contradication of #399.

For example:
I have a flow that first turns lights 'off' by setting their colour to black.
Then I have a flow setting up some parameters and finally turn the lights on with a certain effect.
Since this flow is started by a node setting the colour to black, this value is carried al the way to the call_svc node turning the lights on, causing them to turn on in black instead of following the setup I did prior to that.

### Expected Behavior

Output of debug node should be

```json
{"domain":"light","service":"turn_on","data": {"entity_id":"light.wled_f6dafd_segment_1","effect":"Solid"}}
```

Thus, not containing `color_name`; `brightness_pct` or `transition`

```json
{"domain":"light","service":"turn_on","data":{"entity_id":"light.wled_f6dafd_segment_1","color_name":"Black","effect":"Solid","brightness_pct":25,"transition":5}}
```

### Example flow

```json
[{"id":"93bb35639f7893ff","type":"inject","z":"a84dd1437dd5ab38","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":1580,"wires":[["340d4bb0444bc2a7"]]},{"id":"4bb1714036d931dd","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Intensity","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"number","service":"set_value","entityId":"number.wled_f6dafd_segment_1_intensity","data":"5","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":360,"y":1660,"wires":[["67a64e96f5adcddc"]]},{"id":"67a64e96f5adcddc","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Speed","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"number","service":"set_value","entityId":"number.wled_f6dafd_segment_1_speed","data":"5","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":470,"y":1700,"wires":[["e6f4a827e8c7c283"]]},{"id":"e6f4a827e8c7c283","type":"api-call-service","z":"a84dd1437dd5ab38","name":"Sunrise","server":"2ce15169.23b9de","version":3,"debugenabled":true,"service_domain":"light","service":"turn_on","entityId":"light.wled_f6dafd_segment_1","data":"{\"effect\":\"Sunrise\"}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":580,"y":1740,"wires":[["2c3a9672d9c0ad7f"]]},{"id":"2c3a9672d9c0ad7f","type":"debug","z":"a84dd1437dd5ab38","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":770,"y":1580,"wires":[]},{"id":"340d4bb0444bc2a7","type":"api-call-service","z":"a84dd1437dd5ab38","name":"WLED toggle","server":"2ce15169.23b9de","version":3,"debugenabled":false,"service_domain":"light","service":"turn_on","entityId":"light.wled_f6dafd_segment_1","data":"{\"entity_id\":null,\"color_name\":null,\"effect\":null,\"brightness_pct\":0,\"transition\":1}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"data"}],"queue":"none","x":250,"y":1620,"wires":[["4bb1714036d931dd"]]},{"id":"2ce15169.23b9de","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

![image](https://user-images.githubusercontent.com/2406013/146804126-c561dcbc-b905-468a-b425-a4a7e4180d1b.png)
^ Snippet of my flow showing `Action` node calling a subroutine that sets the WLED to black (which outputs the _unwanted_ parameters), nodes setting intensity and speed in WLED, and finally a call_svc node that calls the `light.turn_on` service with an effect specified.

![image](https://user-images.githubusercontent.com/2406013/146804410-a260ef4d-aa1f-4ab4-9637-86653c8e0562.png)

![image](https://user-images.githubusercontent.com/2406013/146804943-5570bb5a-fb33-469e-9da6-08e7bc08e944.png)
![image](https://user-images.githubusercontent.com/2406013/146805029-57636015-01e6-4f16-a08d-7458fbd74361.png)
(debug node attached to call_svc node)

Note: yes this flow will set the colour to black and then call an effect (thus not visible when viewing the LEDs) but I'm confirming the actions of the flow in the WLED dashboard.
The reason for this is another issue I'm experiencing with NR+HA: https://github.com/hassio-addons/addon-node-red/issues/1220

### Environment

- Node-RED version: 2.1.4
- Node.js version: ?
- npm version: ?
- Platform/OS: Home Assistant add-on v10.2.1
- Browser: Firefox

**Comment by dceejay** [comment]
This sounds like a question for the authors of the HA nodes you mention... 
Yes - as per #399 - the basic rule to follow should be if a config of a node specifies something then that is what the user wants - of blank then it can be overridden.

**Comment by TheGroundZero** [comment]
I just noticed this is even impacting more of my flow

After turning the light on, I call a 30min delay (wait for the effect to complete + some extra time) and then turn an input_boolean off. This is so that multiple triggers don't cause the whole flow to reset.

![image](https://user-images.githubusercontent.com/2406013/146807122-db34d707-01ef-48ff-aef9-2de632a39829.png)

But now it appears that instead of calling0 `input_boolean.turn_off`, `light.turn_on` was called

![image](https://user-images.githubusercontent.com/2406013/146807165-efd063b3-61c1-4a81-b547-12064e10a0f9.png)
![image](https://user-images.githubusercontent.com/2406013/146807188-8088f1da-dcf0-41ae-a000-768cfcf884d2.png)

**Comment by hardillb** [comment]
As Dave mentioned how nodes react to input messages will be down to how they have been implemented, it's not something the core of Node-RED has any influence over.

If the behaviour has changed the first place to look will be the Home Assistant nodes.

**Comment by TheGroundZero** [comment]
Hi @dceejay and @hardillb 

I didn't realize these nodes where 3rd party.
I'll track down the correct repo and raise a ticket there.
