### ISSUE TITLE
fix for missing russian (RU) translation

### ISSUE THREAD

**Issue by dev-k361** [node-red/node-red#3308]
### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by dceejay** [comment]
If a native Russian user would like to step up please...

Where in particular are you seeing missing translations ? A bit more detail would be useful to help someone who does volunteer.

**Comment by knolleary** [comment]
Hi @dev-k361 - I'm closing this issue as it is not clear what you are asking.

If there is an issue you'd like to raise, please use the full template and describe the problem so we are able to help.
