### ISSUE TITLE
Opening a link out node settings triggers a change in the flow

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3315]
### Current Behavior

If you have a link out node in a flow, simply opening and closing the node settings triggers a change in the flow.

It's similar to #3306 

### Steps To Reproduce

Double-click on a link out node to see its settings and click Done

### Environment

- Node-RED version: 2.1.4
- Node.js version: v14.18.2
- npm version: 6.14.15
- Platform/OS: Docker image running on Debian
- Browser: Chrome and Safari

**Comment by knolleary** [comment]
We need to identify what property is being changed to understand what is happening.

When you edit a link node, it tidies up its list of nodes it is linked to in case it still has a non-existent node listed (which can happen if you delete a node).

Can you expand the node properties table in the Info sidebar and compare the full configuration before and after opening the edit dialog? My guess is the `links` property will be changing as part of the tidy up.

![image](https://user-images.githubusercontent.com/51083/147683671-3e140552-7f3d-420c-b0ea-46ada4e54496.png)

**Comment by bonanitech** [comment]
For some weird reason, most of my link-out nodes show mode as undefined. 🤨

After "editing" them, mode is changed to link.

**Comment by bonanitech** [comment]
Before:

<img width="320" alt="Screen Shot 2021-12-29 at 11 51 23 AM" src="https://user-images.githubusercontent.com/29807944/147685495-bb474e23-6e61-4499-a519-6e7a0f1bf5ee.png">

After:

<img width="320" alt="Screen Shot 2021-12-29 at 11 51 31 AM" src="https://user-images.githubusercontent.com/29807944/147685503-34637a63-68aa-47cf-88d7-76aa5c59b42f.png">

**Comment by knolleary** [comment]
In this instance you are editing a pre-2.1 node in 2.1. In 2.1 the `mode` property was introduced as part of the `link call` node work. So when you edit the node, it gains the new property which is a change. That is working as designed.

**Comment by bonanitech** [comment]
Thanks for the info. I'll update them.

**Comment by bonanitech** [comment]
May I suggest the creation of a "node updater" for situations like above?

[node-red-contrib-home-assistant-websocket](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) has something like that.

<img width="460" alt="Screen Shot 2022-01-04 at 7 15 00 AM" src="https://user-images.githubusercontent.com/29807944/148070552-76dd5155-f3ac-4f2a-8944-9296a2180485.png">

P.S. Please forgive me for commenting on a closed issue.

**Comment by knolleary** [comment]
What does that updater actually do?

One of the key things we try to ensure is that nodes keep working and should never *require* an update in its configuration. That is why the nodes only modify their configuration when it gets edited.

**Comment by bonanitech** [comment]
It basically updates nodes' configuration all at once, saving a lot of time on large flows.

**Comment by hardillb** [comment]
But unless they are making breaking changes (which is a bad thing) to those nodes it really shouldn't be required.  Nodes should be written to fill in sensible defaults for missing values and to add them at the next time they are edited (how we started this whole thing)

**Comment by bonanitech** [comment]
> and to add them at the next time they are edited

That's what the updater does but in bulk.

**Comment by hardillb** [comment]
But the point is that it is redundant, there should be no need for it.

Everything should just work without it and it's something extra that has to be maintained.

The fact that it marks a node dirty when you just open and close it is the only side effect (but still valid as it has explicitly set the default for a "new" option)
