### ISSUE TITLE
Opening an inject node settings triggers a change in the flow

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3316]
### Current Behavior

If you have an inject node in a flow, simply opening and closing the node settings triggers a change in the flow.

It's similar to #3306

### Steps To Reproduce

Double-click on an inject node to see its settings and click Done

### Environment

- Node-RED version: 2.1.4
- Node.js version: v14.18.2
- npm version: 6.14.15
- Platform/OS: Docker image running on Debian
- Browser: Chrome and Safari

**Comment by bonanitech** [comment]
Before:

<img width="320" alt="Screen Shot 2021-12-29 at 11 48 06 AM" src="https://user-images.githubusercontent.com/29807944/147685269-e6bafcce-177a-499c-af86-4cafc63c80f8.png">

After:

<img width="320" alt="Screen Shot 2021-12-29 at 11 48 15 AM" src="https://user-images.githubusercontent.com/29807944/147685290-97468288-e71e-46b7-bd94-23fe963b3340.png">

**Comment by knolleary** [comment]
Please expand the 'props' properties so we can see if anything has changed under there.

**Comment by bonanitech** [comment]
Oops, sorry

Before:

<img width="320" alt="Screen Shot 2021-12-29 at 11 58 18 AM" src="https://user-images.githubusercontent.com/29807944/147686104-66bd33cf-3c47-4240-9406-2bad470b7e14.png">

After:

<img width="320" alt="Screen Shot 2021-12-29 at 11 58 29 AM" src="https://user-images.githubusercontent.com/29807944/147686111-56655d86-76b3-44b7-b89b-6f3eecc44f7d.png">

**Comment by bonanitech** [comment]
This only seems to happen with newly added / unedited inject nodes.
