### ISSUE TITLE
New behavior of wires

### ISSUE THREAD

**Issue by uli-rpi** [node-red/node-red#3317]
An idea for the behavior of connections. 

A connection between nodes can have a color depending on one or more properties. e.g. msg.payload = true -> color = green, msg.payload = false -> color = red, .....
The color and properties should be freely configurable. The property should also be able to be displayed as a status to each wire.
A wire changes its appearance with each forwarded message.

**Comment by knolleary** [comment]
As described by the issue templates, feature suggestions should be posted to the forum, not the issue tracker that is used for bugs.
