### ISSUE TITLE
Error with library (moment) when I enlarge monaco editor

### ISSUE THREAD

**Issue by ThomasAndreini** [node-red/node-red#3319]
As reported on the forum when I extend the monaco editor window in the function node on node red 2.1.4 using the moment library I get the error "Cannot find name 'moment'. (2304)".
I haven't had the opportunity to test other libraries but I don't think it depends on moment.
Resizing the window and going to setup the error disappears, if instead I click on the done button the node continues to report the error. I attach the screenshoots.
![Screenshot 2022-01-01 23 35 01](https://user-images.githubusercontent.com/17955700/147861696-d6a4f2bf-e72c-4b28-a2cc-ab03c71e7c2b.png)
![Screenshot 2022-01-01 23 35 24](https://user-images.githubusercontent.com/17955700/147861698-08544f3e-34e3-421e-ab68-9f58a6557a2e.png)
![Screenshot 2022-01-01 23 35 39](https://user-images.githubusercontent.com/17955700/147861699-9e46783d-62ff-454e-8156-3c1d9935d698.png)

**Comment by Steve-Mcl** [comment]
@knolleary I've fixed this issue in my fork (branch `fix-monaco-expanded`) 

Shall I raise a PR against master?

**Comment by knolleary** [comment]
@Steve-Mcl yes please
