### ISSUE TITLE
Investigate migrating to Express 4.x

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#333]
See https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x

**Comment by mlasak** [comment]
Please bear in mind that official support for express 3.x is ending soon. Security and other bug fixes will not be provided by then: http://expressjs.com/3x/api.html

**Comment by knolleary** [comment]
Have made the changes needed to support Express 4 in this branch:
   https://github.com/node-red/node-red/tree/exp4

Whilst this change should be transparent to 'regular' users of node-red, this will be a breaking change to anyone embedding us.

Because of the disruption, don't have a firm plan for when this will get into a release - but having the changes ready is certainly a prereq to it happening at all...

**Comment by knolleary** [comment]
Move made in 0.12
