### ISSUE TITLE
Memorize the width of the right sidebar or make the default width configurable

### ISSUE THREAD

**Issue by uncle-fed** [node-red/node-red#3350]
This is about the default width of the element `#red-ui-sidebar` that is applied on the initial Node Red interface reload.

After reading the discussion here:
https://discourse.nodered.org/t/is-there-a-way-to-set-a-minimum-size-for-the-sidebar/41320

it comes to these two points:

1) It is somehow "accepted" that the "open width of the sidebar is stored in the users browser local storage" - wrong, it is reset to a default setting every time browser window with Node Red main UI is reloaded and that "default setting" is too narrow for most modern desktop display resolutions.

2) it has been suggested that it should be "ok to resize the side bar manually whenever needed" - clearly written by those who don't use the Node Red for what it has been actually designed for (developing your own flows and dashboards). 

It quickly becomes a chore to resize the right side bar from it's default width and make it bigger every single time because by default it is too narrow to contain the essential buttons such as "Context Data" and "Dashboard" that lead to the relevant tabs directly (with a single click).

I understand that user screens and viewports can be very different depending on the device and the use case, but for those with reasonably wide desktop monitors (pretty much a standard on a desktop these days) the constant manual resizing becomes total nuisance very quickly.

Proposal: either memorize the width of the right sidebar properly in a browser local storage, so that it is applied on the next UI reload, or make it possible to set a default min-width for the sidebar easily (at the moment it is set dynamically because of the drag event for the red-ui-sidebar-separator element).

**Comment by Steve-Mcl** [comment]
Closing in favour of #3431
