### ISSUE TITLE
Bug while merging updates from server.

### ISSUE THREAD

**Issue by MykhailKacha** [node-red/node-red#3354]
### Current Behavior

Node-RED creates empty flows while merging updates from server.

### Expected Behavior

Node-RED does not create empty flows

### Steps To Reproduce

1. Open 2 **Node-RED**s. 
![image](https://user-images.githubusercontent.com/48906060/149526370-71ae78c6-5e0f-4918-8e5b-08e4a7ec8f6d.png)
2. Make changes in one of them and deploy.
 2.1 
![image](https://user-images.githubusercontent.com/48906060/149526636-2953f06d-5b4b-449c-a693-390b54f55491.png)
 2.2 
![image](https://user-images.githubusercontent.com/48906060/149526695-afe266d8-2f9d-43e1-9c17-21c10b274bb0.png)
3. Open another **Node-RED** tab and pay attention to "Update" alert.
 3.1
![image](https://user-images.githubusercontent.com/48906060/149527170-0a04d528-9050-428a-ac66-272324f2338c.png)
 3.2
![image](https://user-images.githubusercontent.com/48906060/149527203-f40eeef6-7683-4ce9-bcae-c73780a3439b.png)
4. Click "Review changes" and than "Merge"
5. Node-RED creates an empty flow **(only visual)** 
![image](https://user-images.githubusercontent.com/48906060/149527438-34b3ea61-583a-4e13-a994-18fec0097ec0.png)
6. If we click on another flow and turn back code will create a duplicate **(only visual)**
![image](https://user-images.githubusercontent.com/48906060/149527921-f24ea99b-a18d-4d75-bcf2-eaacea964571.png)

### Example flow

```
paste your flow here
```
--

### Environment

- Node-RED version: 2.1.4
- Node.js version: latest
- npm version: latest
- Platform/OS: MasOS
- Browser: Chrome

**Comment by knolleary** [comment]
Can you check the browser's JavaScript console for any errors?

**Comment by MykhailKacha** [comment]
> Can you check the browser's JavaScript console for any errors?

No, nothing there

**Comment by Steve-Mcl** [comment]
related to #3364

**Comment by Steve-Mcl** [comment]
Closing in favour of #3364 - please track this issue there.
