### ISSUE TITLE
copy path and copy value buttons not working

### ISSUE THREAD

**Issue by x140x1n** [node-red/node-red#3357]
### Current Behavior

the copy path and copy value buttons in the debug tab are not working anymore.
Going back to version 2.1.4 makes the buttons work again.

### Expected Behavior

copy the path or value from the debug tab to clipboard

### Steps To Reproduce

Click the copy path or copy value button on any message in the debug tab

### Environment

- Node-RED version: 2.1.5
- Node.js version: 14.18.3
- npm version: 6.14.15
- Platform/OS: Debian Bullseye
- Browser: Firefox 95.0.2 and Microsoft Edge 97.0.1072.55

**Comment by knolleary** [comment]
#3331 introduced this regression when using http to access the editor (and not using localhost)

**Comment by bigfeetneedbigboots** [comment]
Same issue in Chrome for Mac Version 97.0.4692.71 (Official Build) (x86_64) and Safari Version 15.1 (17612.2.9.1.20)

**Comment by geotibi** [comment]
Same issue for me. I just updated to v2.1.5 and I cannot copy anymore the path and values. Buttons are present but are not copy. Any solution?

**Comment by knolleary** [comment]
We don't need any more "me too" comments in this issue. We know exactly what is wrong and will release a fix next week.

If you read the pr I linked to, you'll see it happens if you are not using https or localhost to access the editor.

**Comment by knolleary** [comment]
Fixed in 2.1.6 via #3363

**Comment by kazuhitoyokoi** [comment]
@knolleary Thank you for fixing it. I checked that v2.1.6 works correctly on other PC (not localhost) via HTTP.
