### ISSUE TITLE
Flow tab shows up twice after merge

### ISSUE THREAD

**Issue by hfedcba** [node-red/node-red#3364]
# Current Behavior / steps to reproduce

1. Make sure there is only one flow
2. Open Node-RED in two different browser tabs
3. Change the flow and deploy it
4. Open the second browser tab
5. Click on `Review changes` in the update notification

![grafik](https://user-images.githubusercontent.com/1392015/150003184-207a8e5f-4504-4e93-8c32-599abe7072e7.png)

6. Click on `Merge`

![grafik](https://user-images.githubusercontent.com/1392015/150003251-2699d433-910a-45f7-b52c-74a2910035f8.png)

Now the Flow tab is displayed twice and the tab currently selected is empty:

![grafik](https://user-images.githubusercontent.com/1392015/150003286-c8390b5d-2d36-453f-97cf-ecd9ce273c45.png)

When clicking on the second tab, the flow is displayed correctly. Now when clicking on the fist tab, the flow is displayed correctly as well.

Reloading the page solves the issue.

When multiple flows exist, similar issues occur on merge.

# Expected behaviour

After the click on `Merge` the Flow tab should only be visible once.

![grafik](https://user-images.githubusercontent.com/1392015/150004333-c1ae72bc-486b-44ca-b71a-d98fe5e32391.png)

# Example flow

The issue occurs with all flows.

# Environment

* Node-RED v2.2.0-beta1 and commit 211a5eb2bbb64f3c00c30427808ed0f56db9ec97
* Node.js v16.13.1
* npm v8.1.2
* Host operating system: Ubuntu Focal with Kernel 5.4.0
* Operating system running the browser: Windows 11 Version 21H2 Build 22000.434
* Browsers: Microsoft Edge v97.0.1072.62 and Mozilla Firefox v96.0.1

**Comment by Steve-Mcl** [comment]
Hi @hfedcba I can confirm the same issue on ubuntu 20.04 with Node-RED v2.2.0-beta1, nodejs 16

![image](https://user-images.githubusercontent.com/44235289/150759134-e30e7385-b334-412c-9b74-ac7f539992cb.png)


and when running on windows...
![image](https://user-images.githubusercontent.com/44235289/150759194-a5e347ab-5c49-45e6-abce-ed3c4f2c0b06.png)
