### ISSUE TITLE
Duplicate MQTT In nodes having the same topic interfere with each other

### ISSUE THREAD

**Issue by gsbn** [node-red/node-red#3387]
### Current Behavior

I have two "MQTT In" nodes on different flows, that subscribe to the same topic.
Each subscription is the same, except one has the setting:
"Retained message handling" = "Send Retained Messages"
   and the other
"Retained message handling" = "Do not send"

Upon restarting the NodeRed service, no retained values are sent through on either node.

Messages are sent through on both if I change the second node's setting from "Do not send" to "Send Retained Messages"

### Expected Behavior

I would expect both node's subscriptions to operate independently

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.2.0
- Node.js version: 14.15.0
- npm version: 8.4.0
- Platform/OS: Ubuntu 18.04.6 LTS
- Browser: Microsoft Edge Version 97.0.1072.76

**Comment by knolleary** [comment]
That is not how it works. If the nodes using the same broker connection, then there is one subscription. When a message arrives at NR we have no way of knowing if it arrived due to a retained flag or not, so we wouldn't be able to deliver to just one of those nodes.

**Comment by gsbn** [comment]
No problem, I'll put in a work-around
