### ISSUE TITLE
Deploy generates an error message "...some nodes are not properly configured"

### ISSUE THREAD

**Issue by emgecgn** [node-red/node-red#3398]
### Current Behavior

Whenever new objects are being generated "automatically" (flows, tabs, groups, spacers) there will be an error message when the Deploy button is klicked.
![Node-Red-Bug_Deploy_2022-02-06](https://user-images.githubusercontent.com/79519574/152708858-8ab25d2d-630c-4029-8e80-8965200cb98e.png)

Error message: "The workspace contains some nodes that are not properly configured" - followed by a list of nodes that were newly created.

This does not happen with any new nodes that are dropped into a flow.
It happens only with items that are generated either automatically (e.g. spacers within a layout form) or when adding a new flow or a new tab, group in the layout listing.

When an item out of that error list is being edited (e.g. rename), it will disappear from the error list (means: its configuration is then ok).
Another workaround to empty the error list: reload the browser window.
Also, when node-red is being restarted, the next deploy works without causing any errors.
So it seems to be a refresh-issue.

It happens on a completely newly installed Raspberry Pi 4 2GB.
Fresh installation ("Buster"), fresh setup, only Node-Red v.2.2.0 as main application.

### Expected Behavior

No error messages, because the listed items/nodes are generated by NodeRed automatically.

### Steps To Reproduce

Upgrade to v.2.2.0

Add a new flow => this will then be listed as "not properly configured" when deploy is klicked
Add a new tab => this will be listed as "not properly configured" when deploy is klicked
Add a new group => this will be listed as "not properly configured" when deploy is klicked
Place some dashboard nodes into the group layout grid so that spacers are generated => these will be listed as "not properly configured" when deploy is klicked

(no problems with previous NodeRed versions since years)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v2.2.0
- Node.js version: v14.19.0
- npm version: v6.14.16
- Platform/OS: RaspiOS Buster (downloaded from official site 28th Jan 2022)
- Browser: Win10 + Firefox 95.0.2 (64-Bit) / Edge 98.0.1108.43
- "npm list" => output in this file: [Node-Red-Modules-installed_2022-02-06.txt](https://github.com/node-red/node-red/files/8011688/Node-Red-Modules-installed_2022-02-06.txt)

**Comment by Steve-Mcl** [comment]
@emgecgn can you share your full flow from before you fixed it.

If you dont wish to share publicly, you can DM me on the forum as @steve-mcl

**Comment by knolleary** [comment]
For context, in 2.2.0 we added a check for misconfigured config nodes at deploy time - #3304. Although that PR was intended to primarily to identify missing config nodes, it also picks up misconfigured nodes.

So you have always had this misconfigured nodes - just nothing has warned you about it.

The question is why are there so many ui_spacer nodes and why are they misconfigured. That will be a question for node-red/node-red-dashboard - so we should transfer the issue to that repo.

**Comment by emgecgn** [comment]
@Steve-Mcl sure, no problem (see the attached).
I can not share the flow from yesterday but I can reproduce as many errors as you like in any order you like.
Flows, tabs, groups, spacers - anything.

Since this new Node-Red installation is supposed to be a test environment only, the full flow is very short - thus very easy to reproduce and investigate.

I have created 3 files:
a) the full flow without errors
b) the full flow after having added a new empty flow, a new tab, a new group within that tab and after having moved one dashboard button within a dashboard group (within the TEST-flow) which caused it to generate a bunch of misconfigured spacers
c) the full flow after having reloaded the browser window which "fixes" the problem temporarily until the next modifications are made

@knolleary it is definitely not only a dashboard related issue. Yes, the spacers are the most disturbing thing as every little change on a dashboard group layout creates a long list of errors. But the errors come up also when a new flow is being added.

I do appreciate your very quick response and please let me tell you how much I love working with Node-Red. Still ;-)

If you need more info from my side - please let me know.

[flows_NodeRed_2022-02-07_FULL-1_before-error.json.txt](https://github.com/node-red/node-red/files/8016210/flows_NodeRed_2022-02-07_FULL-1_before-error.json.txt)
[flows_NodeRed_2022-02-07_FULL-2_error.json.txt](https://github.com/node-red/node-red/files/8016214/flows_NodeRed_2022-02-07_FULL-2_error.json.txt)
[flows_NodeRed_2022-02-07_FULL-3_error-removed-after-browser-reload.json.txt](https://github.com/node-red/node-red/files/8016216/flows_NodeRed_2022-02-07_FULL-3_error-removed-after-browser-reload.json.txt)

**Comment by Steve-Mcl** [comment]
> So you have always had this misconfigured nodes - just nothing has warned you about it.
@knolleary Nick, this is potentially a node-red-dashboard issue

I have finally manged to consistently re-create this...

### Steps to recreate the problem
* On a flow with dashboard nodes add spaces
  * Deploy - ok
* go to the dashboard sidebar tab
  * open the layout editor and move one ui node
  * deploy - error
 
Now you get the notification about misconfigured nodes.

### Info
I have also confirmed PR #3397 "handles this" however I suspect this is containment & not a fix for the missing `valid` property. Please advise otherwise.

**Comment by HiroyasuNishiyama** [comment]
As I understand it, this issue relates to how `RED.editor.validateNode` is called.  

For `ui_spacer`, `validateNode` is called when added from layout list but not called when added from layout editor.  Also, `validateNode` is not called when `ui_base` is added.

This may be a dashboard issue, but considering compatibility issues, I think it's better to fix the Node-RED editor side.

**Comment by knolleary** [comment]
@HiroyasuNishiyama I agree. Your pr is good and we should consider a 2.2.1 release that includes it.

Separately we should also look at what dashboard is doing to generate all this nodes.
