### ISSUE TITLE
RED.hooks.add provokes error "TypeError: Cannot read property 'slice' of undefined" if called from within callback

### ISSUE THREAD

**Issue by cdmahoney** [node-red/node-red#3401]
### Current Behavior

I am calling RED.hooks.add from within a callback function:
```
events.forEach(
	function(eventName)
	{
		RED.hooks.add(eventName, 
			function(payload, done)
			{
				// ...
				done();
			});
	});
```

The calling module fails to load, in the node-red log the following message appears:
[Module name] TypeError: Cannot read property 'slice' of undefined

### Expected Behavior

The hook callback should be registered without an error.

### Steps To Reproduce

See section current behaviour. Registering a hook callback from a callback in the module code causes the module to fail to load and an error to be logged in the node-red log.

The problem is caused by lines 79-71 in [hooks.js](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/util/lib/hooks.js):
```
    // Get location of calling code
    const stack = new Error().stack;
    const callModule = stack.split("\n")[2].split("(")[1].slice(0,-1);
```

The call `split("(")` returns an array containing a single element, hence the error on calling slice for element [1].

### Environment

- Node-RED version: 1.2.3 (but code in hooks.js has not changed, so error will still occur)
- Node.js version: 13.12.0
- npm version: 6.14.8
- Platform/OS: Ubuntu 18.04.3 LTS
- Browser: Firefox

**Comment by knolleary** [comment]
We try to capture the call stack so we can log where the hook was added. Evidently that doesn't go to plan when doing so from such a callback with an unexpectedly short call stack.

**Comment by cdmahoney** [comment]
@knolleary Not quite - the call stack is long enough, the problem is the format of the stack entry at index 2. Hook code expects a format like:
`    at module.exports (/path/to/javascript/file.js::LL:CC)`

But what it gets is:
`    at /path/to/javascript/file.js::LL:CC`

In this case (no parenthesis in stack element) the call to split on the parenthesis returns a single element array with just the module name.
