### ISSUE TITLE
Link call doesn't work inside subflow

### ISSUE THREAD

**Issue by Timmiej93** [node-red/node-red#3404]
### Current Behavior

A link call outside a subflow works as expected. Placing that same link call inside a subflow makes it time out and not do anything. See example in 'Steps To Reproduce'.

### Expected Behavior

I would expect a link call to behave exactly the same inside a subflow as it does in a regular flow.
If this behavior is by design, I would at least expect an error to come up that mentions that a link call doesn't work inside a subflow. 

### Steps To Reproduce

See example:
```
[{"id":"eba3f6f1ec133a59","type":"subflow","name":"Subflow 1","info":"","in":[{"x":80,"y":80,"wires":[{"id":"aa62622a2b62fd65"}]}],"out":[]},{"id":"aa62622a2b62fd65","type":"link call","z":"eba3f6f1ec133a59","name":"","links":["11289a75e4ad5fca"],"timeout":"30","x":200,"y":80,"wires":[["2dd0b7b623e38c85"]]},{"id":"2dd0b7b623e38c85","type":"debug","z":"eba3f6f1ec133a59","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":330,"y":80,"wires":[]},{"id":"11289a75e4ad5fca","type":"link in","z":"eba3f6f1ec133a59","name":"test in","links":[],"x":215,"y":220,"wires":[["c8c90c89df0e8294","89f82393194c0202"]]},{"id":"c8c90c89df0e8294","type":"link out","z":"eba3f6f1ec133a59","name":"","mode":"return","links":[],"x":305,"y":220,"wires":[]},{"id":"89f82393194c0202","type":"debug","z":"eba3f6f1ec133a59","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":340,"y":180,"wires":[]},{"id":"75e3bc6be36d21a2","type":"inject","z":"b88d0ccd9c6c63d6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":650,"y":380,"wires":[["fa6ec1460912454b"]]},{"id":"fa6ec1460912454b","type":"link call","z":"b88d0ccd9c6c63d6","name":"","links":["5af86a1f95f37aff"],"timeout":"30","x":790,"y":380,"wires":[["eb51ce6970fa1df9"]]},{"id":"eb51ce6970fa1df9","type":"debug","z":"b88d0ccd9c6c63d6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":920,"y":380,"wires":[]},{"id":"5af86a1f95f37aff","type":"link in","z":"b88d0ccd9c6c63d6","name":"test in","links":[],"x":805,"y":520,"wires":[["92fb9ee5c7624fb2","fa9e715dabd6efb9"]]},{"id":"92fb9ee5c7624fb2","type":"link out","z":"b88d0ccd9c6c63d6","name":"","mode":"return","links":[],"x":895,"y":520,"wires":[]},{"id":"fa9e715dabd6efb9","type":"debug","z":"b88d0ccd9c6c63d6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":930,"y":480,"wires":[]},{"id":"88fc2da08203ac7d","type":"inject","z":"b88d0ccd9c6c63d6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":660,"y":680,"wires":[["7bbcc883ab5c3eb4"]]},{"id":"7bbcc883ab5c3eb4","type":"subflow:eba3f6f1ec133a59","z":"b88d0ccd9c6c63d6","x":840,"y":680,"wires":[]}]
```

Subflow 1 is created by selecting everything above, except for the inject node. If you want to make sure while testing that the contents are exactly the same, remove the bottom inject node and the subflow, duplicate everything left, select everything except the inject node, and use the convert to subflow action.

Click the inject node that is not connected to the subflow. You get two messages in the debug log, once from inside the link call, once from after it was done.

Click the inject node connected to the subflow. After 30 seconds you get a timeout.

### Example flow

See Steps To Reproduce

### Environment

Docker: nodered/node-red:2.2.0

- Node-RED version: v2.2.0
- Node.js version: v14.18.2
- npm version: 6.14.15
- Platform/OS: Windows 10
- Browser: Vivaldi / Chrome

**Comment by dceejay** [comment]
one comment - you wont get output from debug nodes inside a subflow - so you need to give your subflow an output and connect that to a debug outside...   but having said that - it still doesn't work :-)

```
[{"id":"eba3f6f1ec133a59","type":"subflow","name":"Subflow 1","info":"","in":[{"x":115,"y":75,"wires":[{"id":"aa62622a2b62fd65"}]}],"out":[{"x":380,"y":75,"wires":[{"id":"aa62622a2b62fd65","port":0}]},{"x":310,"y":270,"wires":[{"id":"11289a75e4ad5fca","port":0}]}]},{"id":"aa62622a2b62fd65","type":"link call","z":"eba3f6f1ec133a59","name":"","links":["11289a75e4ad5fca"],"timeout":"30","x":235,"y":75,"wires":[[]]},{"id":"11289a75e4ad5fca","type":"link in","z":"eba3f6f1ec133a59","name":"test in","links":[],"x":165,"y":210,"wires":[["c8c90c89df0e8294"]]},{"id":"c8c90c89df0e8294","type":"link out","z":"eba3f6f1ec133a59","name":"","mode":"return","links":[],"x":450,"y":210,"wires":[]},{"id":"88fc2da08203ac7d","type":"inject","z":"9a66423268ae47c4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":280,"y":885,"wires":[["7bbcc883ab5c3eb4"]]},{"id":"7bbcc883ab5c3eb4","type":"subflow:eba3f6f1ec133a59","z":"9a66423268ae47c4","name":"","x":460,"y":885,"wires":[["f296780702f369d2"],["090d59d5435a823b"]]},{"id":"f296780702f369d2","type":"debug","z":"9a66423268ae47c4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":635,"y":870,"wires":[]},{"id":"090d59d5435a823b","type":"debug","z":"9a66423268ae47c4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":640,"y":915,"wires":[]}]
```

**Comment by Timmiej93** [comment]
I don't know man, this example says otherwise:
```
[{"id":"c69ade348cbac61c","type":"subflow","name":"Subflow 1","info":"","in":[{"x":60,"y":80,"wires":[{"id":"b6e92770238482d4"}]}],"out":[]},{"id":"b6e92770238482d4","type":"debug","z":"c69ade348cbac61c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":200,"y":80,"wires":[]},{"id":"0892087d430bef41","type":"inject","z":"4d177dfea3653f94","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":310,"y":260,"wires":[["436fb36c116fb4ab"]]},{"id":"436fb36c116fb4ab","type":"subflow:c69ade348cbac61c","z":"4d177dfea3653f94","name":"","x":580,"y":260,"wires":[]}]
```

I know you can't enable/disable debug outputs inside subflows (god only knows why...), but they sure seem to output to the console just fine.

**Comment by knolleary** [comment]
> god only knows why

Well, a few of us know why.

When you're editing a subflow template, you are editing the template, not an individual instance. When you click a node button (eg inject or debug) the editor doesn't know which instance of the subflow you want the action to apply to.

That aside, ad you say, you can use debug nodes inside a subflow.

**Comment by Timmiej93** [comment]
Personally, coming from regular coding, that doesn't make sense to me. I view a subflow as a function in regular code. Write once, use many times. In a regular function if you comment out a `console.log()`, it doesn't print, no matter from where it's called. If you uncomment it, it prints, no matter from where it's called.
I honestly don't see the difference between removing the wire that runs to the debug node (which disables all logging, no matter where the subflow is used), or disabling it the node, yet one is possible, the other isn't. 

It's not really the topic of this issue though.

**Comment by Steve-Mcl** [comment]
@knolleary @dceejay 

I also confirm link call (inside subflow) does not work.

Is this a missing feature, never intended, or a bug?
* If a missing feature,  please let me know and I will look at implementation & will target `dev`
* If never intended, we probably shouldn't permit link call nodes inside a subflow? 
* If this is a bug, please let me know and I will begin debugging & will target `master`.

**Comment by dceejay** [comment]
I would think just a missing feature as link call capability was only added a release (or two) ago. I would only expect it to be when 100% inside a subflow - ie both the call and return are within the subflow. No crossing the subflow boundary from outside to in or inside to out.

**Comment by Steve-Mcl** [comment]
Fixed in https://github.com/node-red/node-red/pull/3463
