### ISSUE TITLE
Comment node (NR v2.1.6) not fitting text - was fine in v2.1.4

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red#3406]
### Which node are you reporting an issue on?
Comment
### What are the steps to reproduce?
1) add a comment node to a flow
2) edit the comment node and add a string over 32 characters in the "Name"
### What happens?
A string over 32 characters starts to spill outside the border of the node box
### What do you expect to happen?
The comment box should expand to contain the name of the comment node
NOTE: this was not a problem in v2.1.4
### Please tell us about your environment:

- [ ] Node-RED version: v2.1.6
- [ ] node.js version: v14.18.1
- [ ] npm version:
- [ ] Platform/OS: Pi 3 Model B Rev 1.2 / Buster
- [ ] Browser: Safari on macOS

**Comment by Steve-Mcl** [comment]
This issue is not present on 2.2.0 when viewed in Chrome or Edge on Windows
![image](https://user-images.githubusercontent.com/44235289/153197175-f00e4673-24ad-4d86-8b6a-89f5bd1ee50a.png)

@juggledad Paul, can you try this in Chrome or FF please?

Also, can you post an export of the comment node so we can accurately re-create the scenario.

**Comment by juggledad** [comment]
Ok, it's fine in Firefox and Chrome (draws I shuould have tested that!), but an issue in Safari.
Here is a comment node:
`[{"id":"c934b64c919d733c","type":"comment","z":"0c4c68fb351df5f5","g":"c8df16c40934eec9","name":"Parse the results returned from MQTT and store ther results in some flow variables","info":"","x":510,"y":680,"wires":[]}]`

**Comment by knolleary** [comment]
I haven't been able to reproduce this with 2.1.6 and 2.2.0 in Safari. I've imported the node you've shared and also tried starting with a blank comment node. Nothing I do causes the width of the node to get miscalculated. Not sure what step to take next.

**Comment by dceejay** [comment]
Is/was the page zoom set to 100% ? (clutching at straws)

**Comment by juggledad** [comment]
So now I can't recreate it eithor...sigh... 

close this and if I ever hit it again, I will make detailed notes and a full flow backup

**Comment by Steve-Mcl** [comment]
Thanks Paul.
