### ISSUE TITLE
Delay nodes mis-configured after upgrade to 2.2.0

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#3407]
### Which node are you reporting an issue on?
Delay node

### What are the steps to reproduce?
Import this node config (which is an export from an earlier version) into node red 2.2.0
```
[
    {
        "id": "90e9c97c.3d1ee",
        "type": "delay",
        "z": "e2d1e6af.819db8",
        "name": "",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "outputs": 1,
        "x": 146.5,
        "y": 216,
        "wires": [
            [
                "fa458ca8.723308"
            ]
        ]
    }
]
```
### What happens?
The node shows with a red triangle.

### What do you expect to happen?
It should be imported without issue.

### Please tell us about your environment:

- [ ] Node-RED version: 2.2.0
- [ ] node.js version: 16.14.0
- [ ] npm version: 8.3.1
- [ ] Platform/OS: Ubuntu 20.04
- [ ] Browser: Chrome

### Further info

Adding 
`"nbRateUnits": ""`
in at the time of export appears to fix it.

**Comment by knolleary** [comment]
PR #3351  modified the validation of the delay node properties. As you can see in the discussion of that PR, it did mean that *very* old nodes would get flagged as invalid until they were edited. We took the judgement that this would be quite a small minority of users - as it would mean its a Delay node that hasn't been edited in a number of years.

So the question is whether we want to stand by that assessment, or revisit it in light of this issue

**Comment by colinl** [comment]
The nodes affected *are* in an old section of the flow that has probably not been touched for a few years.  The flow is also present in an example in the flows library, so I presume that will no longer import without error.  There may be a number of other flows in the library that will be affected.

**Comment by colinl** [comment]
Why is that property required, if an empty string is valid?
