### ISSUE TITLE
feature: HTTP Request: Add options for common response headers

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#3428]
### Description

Saves the user having to set msg.headers for common use cases.

**Comment by Steve-Mcl** [comment]
## Proposal...
Add `editableList` similar to the HTTP Response node with 2 fields - both `typedInput`s

### Rules...
* If header FOO is sent in `msg.headers["FOO"]`, but it is defined in the UI Headers `editableList`, the entry in the UI is used.

### Mock up...

![image](https://user-images.githubusercontent.com/44235289/156458770-faa00568-7de6-47ef-af44-24f215d1517b.png)

### HEADER (Left hand side options)...

A `typedInput` that has `msg.` and the following static choices...

Header | Comment
-- | --
`msg.` | Allow user to automate via msg.xxx
Accept |  
Accept-Encoding |  
Accept-Language |  
Authorization |  
Accept-Encoding |  
Content-Type |  
Cache-Control |  
User-Agent |  
Custom | Allow user to enter a fixed custom header

### HEADER OPITIONS (Right hand side options)...

A `typedInput` that has `msg.` and the below static choices

NOTE: The default / built-in options are a 1st stab / not definitive (open to suggestions)

Header | Options... |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
`msg.` | `msg.` |   |   |   |   |  
Accept | `msg.` | text/plain | text/html | application/json | application/xml |  
Accept-Encoding | `msg.` | gzip | deflate | gzip, deflate | gzip, deflate, br |  
Accept-Language | `msg.` | * | en-GB, en-US, en;q=0.9 | de-AT, de-DE;q=0.9, en;q=0.5 | fr-CH, fr;q=0.9, en;q=0.8, | other ones? jp, ko, ch?
Authorization | `msg.` |   |   |   |   |  
Accept-Encoding | `msg.` |   |   |   |   |  
Content-Type | `msg.` |   |   |   |   |  
Cache-Control | `msg.` | max-age=0 | max-age=86400 | no-cache |   |  
User-Agent | `msg.` | Mozilla/5.0 |   |   |   |  
Custom | `msg.` |   |   |   |   |  



Registry | Content-Types
-- | --
text | text/css
  | text/html
  | text/plain
  | text/html
application | application/octet-stream
  | application/json
  | application/pdf
  | application/xml
  | application/zip
audio | audio/aac
  | audio/ac3
  | audio/basic
  | audio/mp4
  | audio/ogg
image | image/bmp
  | image/gif
  | image/jpeg
  | image/tiff
  | image/png
