### ISSUE TITLE
udp out broadcast

### ISSUE THREAD

**Issue by TheGiolly** [node-red/node-red#3432]
### Current Behavior

I'm trying to send a broadcast UDP packet (a WoL Magic Packet) using the `udp out` node but I'm receiving a non-broadcast UDP packet.

When I select `broadcast message` in the node properties I get this packet
![image](https://user-images.githubusercontent.com/9699045/153254745-b7c42239-730b-41e6-9f4c-685cb77c1bfa.png)

that is exaclty the same as if I select `udp message` in the node properties
![image](https://user-images.githubusercontent.com/9699045/153255351-d7efd6af-566e-4079-b1b8-48deebfec399.png)

I read from the node help
`[...] Note: On some systems you may need to be root to use ports below 1024 and/or broadcast.`
so I changed the user from `node-red` to `root` in the Portainer container user field but nothing changed.

I also tried setting the address field in the node properties to 192.168.1.255 but, in that case, I don't receive any packet at all.

There are no errors in the container log.

### Expected Behavior

Receive a broadcast UDP packet like this one (sent with the Android app WolOn)
![image](https://user-images.githubusercontent.com/9699045/153255999-ca65d784-90db-4242-9ab4-8790f3a46583.png)

### Steps To Reproduce

Use the provided example flow or set up a simple `udp out` node.

### Example flow

```
[
    {
        "id": "3dd7c188a1064005",
        "type": "tab",
        "label": "Flow 2",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "01f3524c7c5ce4c0",
        "type": "inject",
        "z": "3dd7c188a1064005",
        "name": "WOL",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 150,
        "y": 80,
        "wires": [
            [
                "4724a013d6ba2020"
            ]
        ]
    },
    {
        "id": "4724a013d6ba2020",
        "type": "function",
        "z": "3dd7c188a1064005",
        "name": "",
        "func": "msg.payload = new Buffer(\"ffffffffffffd43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7\",\"hex\");\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 280,
        "y": 80,
        "wires": [
            [
                "4258a162137d0854"
            ]
        ]
    },
    {
        "id": "4258a162137d0854",
        "type": "udp out",
        "z": "3dd7c188a1064005",
        "name": "WOL",
        "addr": "192.168.1.100",
        "iface": "",
        "port": "9",
        "ipv": "udp4",
        "outport": "9",
        "base64": false,
        "multicast": "broad",
        "x": 410,
        "y": 80,
        "wires": []
    }
]
```

### Environment

- Node-RED version: 2.2.0
- Node.js version: 14.18.2
- npm version: 6.14.15
- Platform/OS: Docker (nodered/node-red)
- Browser: Google Chrome 98.0.4758.82

**Comment by dceejay** [comment]
While we look at this - did you try the actual wol node ? https://flows.nodered.org/node/node-red-node-wol

**Comment by TheGiolly** [comment]
Yes, before using the `udp out` node I tried the `wol` node but it didn't send a broadcast packet neither

**Comment by hardillb** [comment]
How have you configured the network in Docker?

**Comment by dceejay** [comment]
this works for me (not using docker)
```
[{"id":"01f3524c7c5ce4c0","type":"inject","z":"3dd7c188a1064005","name":"WOL","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":150,"y":80,"wires":[["4724a013d6ba2020"]]},{"id":"4724a013d6ba2020","type":"function","z":"3dd7c188a1064005","name":"","func":"msg.payload = new Buffer(\"ffffffffffffd43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7d43d7ebdf8b7\",\"hex\");\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":280,"y":80,"wires":[["4258a162137d0854"]]},{"id":"4258a162137d0854","type":"udp out","z":"3dd7c188a1064005","name":"WOL","addr":"255.255.255.255","iface":"","port":"9","ipv":"udp4","outport":"","base64":false,"multicast":"broad","x":440,"y":90,"wires":[]}]
```
I suspect it's more to do with your docker network (as Ben is suggesting)

**Comment by TheGiolly** [comment]
The container network was set to bridge (default).
I tried @dceejay flow in bridge and it didn't work.

Now I switched to host and, using IP address 192.168.1.255 or 255.255.255.255 in the node properties, I get a broadcast packet.
However if I enter an IP that's not the broadcast one (for example 192.168.1.100) it still sends a standard packet.

So, what's the difference between `udp message` and `broadcast message` modes?
If I send a packet in `udp message` mode with IP 192.168.1.255 that's still a broadcast packet..

**Comment by dceejay** [comment]
So ok to close this issue as it's not a Node-RED problem ?

**Comment by TheGiolly** [comment]
Yes :)
Could you explain me what's the difference between udp message and broadcast message modes before closing?
Thanks!

**Comment by dceejay** [comment]
setting it to broadcast turns on the socket SO_BROADCAST flag which in theory allows (or disallows) sending to the local broadcast address. EG see - https://stackoverflow.com/questions/16217958/why-do-we-need-socketoptions-so-broadcast-to-enable-broadcast
