### ISSUE TITLE
Duplicate wires between nodes with 2.2.0

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#3433]
### Current Behavior

There have been two cases reported on the forum where nodes have been dropped onto the flow and two messages have been received at the output for each one on the input. Looking at the exported flow it can be seen that there are two wires between the two nodes.

https://discourse.nodered.org/t/possible-bug-ui-dashboard-switch-node-or-function-switch-node/58043
https://discourse.nodered.org/t/msg-duplication-because-of-link-out-and-link-in/58127

The example flow below is from the former post, where it can be seen that there are two identical wires with the ui_switch node.

When an attempt is made to delete the duplicated wire the first one deletes, but then the second one refuses to be selected.  This is possibly just a side effect of having the duplicated wire.

### Steps To Reproduce

It has not been possible to reproduce consistently, apparently.

### Example flow

```
[
    {
        "id": "722804950b4b4251",
        "type": "switch",
        "z": "77f64d9d09139432",
        "name": "Mode",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 730,
        "y": 220,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "e6f5d2c9e6d468c2",
        "type": "debug",
        "z": "77f64d9d09139432",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 710,
        "y": 180,
        "wires": []
    },
    {
        "id": "aad3e59254f825af",
        "type": "ui_switch",
        "z": "77f64d9d09139432",
        "name": "",
        "label": "Thermo Enable",
        "tooltip": "",
        "group": "e95113d77e51b515",
        "order": 1,
        "width": 0,
        "height": 0,
        "passthru": true,
        "decouple": "false",
        "topic": "topic",
        "topicType": "msg",
        "style": "",
        "onvalue": "true",
        "onvalueType": "bool",
        "onicon": "fa-power-off fa-2x",
        "oncolor": "green",
        "offvalue": "false",
        "offvalueType": "bool",
        "officon": "fa-power-off fa-2x",
        "offcolor": "grey",
        "animate": true,
        "className": "",
        "x": 420,
        "y": 220,
        "wires": [
            [
                "722804950b4b4251",
                "722804950b4b4251",
                "e6f5d2c9e6d468c2"
            ]
        ]
    },
    {
        "id": "e95113d77e51b515",
        "type": "ui_group",
        "name": "Thermal Mode",
        "tab": "2bf55b350517e8d4",
        "order": 2,
        "disp": true,
        "width": 6,
        "collapse": false,
        "className": ""
    },
    {
        "id": "2bf55b350517e8d4",
        "type": "ui_tab",
        "name": "PTZ",
        "icon": "camera",
        "order": 1,
        "disabled": false,
        "hidden": false
    }
]
```

```


### Environment

These are from the first forum post, the details from the second are not yet known (apart from being nr 2.2.0)
- Node-RED version: 2.2.0
- Node.js version: 14.19.0
- npm version: 6.14.16
- Platform/OS: Linux Mint
- Browser: ?

**Comment by unborn-andy** [comment]
It happened to me also but i wasn't sure how to replicate this in order to report it.
In my case duplicate wires appeared in the flow after a History undo.

![Animation](https://user-images.githubusercontent.com/93290787/153589934-b2dbcd64-78aa-4f8d-9330-7781ce4fcbfc.gif)

( Ctrl-Z between Deploys)

**Comment by Steve-Mcl** [comment]
thanks @unborn-andy I can confirm 

## Steps to replicate
1. Add inject and wire to a debug
2. Deploy 
3. Press inject - confirm 1 msg
3. Draw selection box around both nodes and delete
4. Deploy
5. Undo
6. Deploy
7. Press inject - confirm 2 msgs


## Steps to replicate 2 (slight variation)
1. Add inject and wire to a debug
2. Deploy 
3. Press inject - confirm 1 msg
3. Draw selection box around both nodes and delete
5. Undo
6. Move 1 node
6. Deploy
7. Press inject - confirm 2 msgs

**Comment by Steve-Mcl** [comment]
A quick step through the code reveals that `removedLinks` contains 2 links in the set.

(A) One entry is added here: https://github.com/node-red/node-red/blob/42358419ad67ae38570754535e3a654b21c5232d/packages/node_modules/@node-red/editor-client/src/js/ui/view.js#L2380-L2381 

(B) the other is added here: https://github.com/node-red/node-red/blob/42358419ad67ae38570754535e3a654b21c5232d/packages/node_modules/@node-red/editor-client/src/js/ui/view.js#L2472 

↑ This line is reached because `selectedLinks` has items in its set.

As the undo buffer now has 2 entries for removed links, it creates 2 wires upon undo.
 
I suspect this is a regression due to PR #3294 

### Possible Fix ideas
1. Dont add link to `removedLinks` at (A) and allow the code at (B) to add to `removedLinks`
or
2. call `selectedLinks.remove(link)` after adding to `removedLinks` at (A)

### ADDITIONAL...
Should there be some other containment to check / prevent this from occurring at the server side?
