### ISSUE TITLE
new install of nodered flapping "Failed at the node-red-docker@2.2.1 start script."

### ISSUE THREAD

**Issue by gawainXX** [node-red/node-red#3448]
### Current Behavior

I'm trying to deploy HomeAssistant and it appears to be breaking due to nodered.
Nodered is not getting an IP, displaying port mapping and is continuously restarting according to portainer.

Here is a snippet of some of the logs .
`8c04bb4edb010c024a55e0c9aca7c120917a51d1a21ab8323db065ce4abfa7a4-json.log
{"log":"    at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:56:25)\n","stream":"stderr","time":"2022-02-15T20:47:31.99633984Z"}
{"log":"    at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)\n","stream":"stderr","time":"2022-02-15T20:47:31.996347876Z"}
{"log":"    at handleFilterAndCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)\n","stream":"stderr","time":"2022-02-15T20:47:31.996355845Z"}
 Failed at the node-red-docker@2.2.1 start script.Failed at the node-red-docker@ This is probably not a problem with npm. There is likely additional This is probably not a problem with npm.{"log":"    at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)\n","stream":"stderr","time":"2022-02-15T20:47:31.996363818Z"}
{"log":"    at Object.\u003canonymous\u003e (/usr/src/node-red/node_modules/node-red/red.js:125:20)\n","stream":"stderr","time":"2022-02-15T20:47:31.996372037Z"}
{"log":"    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n","stream":"stderr","time":"2022-02-15T20:47:31.996380567Z"}
{"log":"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n","stream":"stderr","time":"2022-02-15T20:47:31.996388403Z"}
{"log":"    at Module.load (internal/modules/cjs/loader.js:950:32) {\n","stream":"stderr","time":"2022-02-15T20:47:31.996396268Z"}
{"log":"  errno: -13,\n","stream":"stderr","time":"2022-02-15T20:47:31.996404214Z"}
{"log":"  syscall: 'copyfile',\n","stream":"stderr","time":"2022-02-15T20:47:31.996411823Z"}
{"log":"  code: 'EACCES',\n","stream":"stderr","time":"2022-02-15T20:47:31.996419495Z"}
{"log":"  path: '/usr/src/node-red/node_modules/node-red/settings.js',\n","stream":"stderr","time":"2022-02-15T20:47:31.996427161Z"}
{"log":"  dest: '/data/settings.js'\n","stream":"stderr","time":"2022-02-15T20:47:31.996434993Z"}
{"log":"}\n","stream":"stderr","time":"2022-02-15T20:47:31.996442686Z"}
{"log":"npm ERR! code ELIFECYCLE\n","stream":"stderr","time":"2022-02-15T20:47:32.01220068Z"}
{"log":"npm ERR! errno 1\n","stream":"stderr","time":"2022-02-15T20:47:32.012475449Z"}
{"log":"npm ERR! node-red-docker@2.2.1 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS \"--userDir\" \"/data\"`\n","stream":"stderr","time":"2022-02-15T20:47:32.023865608Z"}
{"log":"npm ERR! Exit status 1\n","stream":"stderr","time":"2022-02-15T20:47:32.023997381Z"}
{"log":"npm ERR! \n","stream":"stderr","time":"2022-02-15T20:47:32.024009912Z"}
{"log":"npm ERR! Failed at the node-red-docker@2.2.1 start script.\n","stream":"stderr","time":"2022-02-15T20:47:32.024075215Z"}
{"log":"npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n","stream":"stderr","time":"2022-02-15T20:47:32.024109727Z"}
`

### Expected Behavior

Container doesn't continuously restart.

### Steps To Reproduce

Provision container with the following configuration
  # NodeRed
  nodered:
    # container_name: homeassistant-nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - /srv/HomeAssistant/nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "America/Los_Angeles"
    restart: unless-stopped

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: latest
- Node.js version:
- npm version:
- Platform/OS: AlmaLinux 8.5 (Docker)
- Browser:

**Comment by hardillb** [comment]
Please raise this with Home Assistant, they build and ship their own Docker container and the Node-RED project has no input into this.

**Comment by hardillb** [comment]
Those it looks like you have a permissions problem with the volume mounted on `/data` not being writeable by the Node-RED user

**Comment by gawainXX** [comment]
> 

This appears to be the case
as I omitted the volume and it stays running, probably an issue with the guide I was following. Thanks!

**Comment by gawainXX** [comment]
> Though it looks like you have a permissions problem with the volume mounted on `/data` not being writeable by the Node-RED user

Actually i take that back, it seems that any file system mount to /data breaks things whereas a volume container seems to work?

**Comment by hardillb** [comment]
We can't answer that, we have no idea what permissions what ever directory you are mounting has, but it needs to be writable by the node-red user inside the container. But as you said, this is problem with the Home Assistant doc you are following, not Node-RED

**Comment by gawainXX** [comment]
> We can't answer that, we have no idea what permissions what ever directory you are mounting has, but it needs to be writable by the node-red user inside the container. But as you said, this is problem with the Home Assistant doc you are following, not Node-RED

Thanks, It turned out to be a permission issue as you had suggested, worked fine after I used chmod 777 on the folder I was mapping nodered to.

Cheers
