### ISSUE TITLE
Referencing common entries from message catalog for packages with scoped name

### ISSUE THREAD

**Issue by jensrossbach** [node-red/node-red#3453]
### Current Behavior

Node-RED seems to have problems referencing common entries from the message catalog for status messages. With common entries I mean entries which are not specific for a certain node, but used for multiple nodes. I use the form

`"myPackage/myNode:common.example.label"`

for such kind of content (where `myPackage` is the name of the package and `myNode` is the name of the node containing the message catalog entry `common.example.label`) and this works fine for packages without scoped name in all areas (status messages, error messages, editor UI). But when the package has a scoped name, it still works fine with error messages and in the editor UI but it stopps working for status messages (it shows the text of the reference like above, not the actual translated text from the message catalog).

### Expected Behavior

The translated text from the message catalog should be displayed in all areas (status messages, error messages, editor UI).

### Steps To Reproduce

Create a node package with scoped name, create at least two nodes and add internationalization support, i.e., a message catalog for each node. Then reference a message from node A in node B inside a status message.

### Example flow

N/A (needs custom node package)

### Environment

- Node-RED version: 2.1.4
- Node.js version: 16.13.1
- npm version: 8.1.2
- Platform/OS: Windows (but also reproduced on Linux/Ubuntu)
- Browser: Microsoft Edge

**Comment by knolleary** [comment]
Is your node somewhere we can look at it, rather than have a build a test case from scratch?

**Comment by jensrossbach** [comment]
Hi, as it's a new package I'm working on, it is not yet available, but I plan to release it in two days. Although I've for now implemented a workaround in order to circumvent the problem (by duplicating the common messaga catalog entries for each node), I can create a branch with the original code. I will send you the link as soon as I've published the code.

**Comment by dceejay** [comment]
when you release it - maybe don't add the node-red tag and maybe don't add it to the flows site until we have sorted out this issue ?  You can still install manually from npm to test.

**Comment by jensrossbach** [comment]
Sorry @dceejay, I read this too late and have already published the new node package. But as mentioned above, I've implemented a workaround so that the problem isn't visible in the official package.

I created the branch [nodered-3453](https://github.com/jensrossbach/node-red-sony-audio/tree/nodered-3453) where I reverted the workaround so that you can test it with this code.
