### ISSUE TITLE
On editor load the first flow tab is being shown even when it's meant to be hidden

### ISSUE THREAD

**Issue by My-Random-Thoughts** [node-red/node-red#3455]
### Current Behavior

When opening a new browser window and navigating to http://x.x.x.x:1880/ the first flow tab is always shown even though it has been hidden by clicking icon on the tab

Additionally (although may be related), when hiding all flow tabs (silly I know), the first flow reappears, but there is no tab shown at the top of the editor window.

### Expected Behavior

Expected to show the next available visible tab

If all flow tabs are hidden either a blank editor window or the first flow with tab shown.

### Steps To Reproduce

- Create several tabs.
- Hide the first one.
- Reload the site, ensuring you remove the extra `#flow/...` part from the URL

### Example flow

N/A

### Environment

- Node-RED version: node-red-docker@2.2.1
- Node.js version: 14.18.2
- npm version: 6.14.15
- Platform/OS: Linux 5.13.0-28-generic x86_64
- Browser: Firefox 97

**Comment by youngkzy** [comment]
Steve or Nick, 
  How can I get the merged files?  I just downloaded the 2.2.2 and it's still doing this bug.  I installed 2.2.2 and "closed" or "hid" all the tabs.  Then I opened up Node-RED and it shows first flow with no tab at all, still.  I apparently still have the old version.
