### ISSUE TITLE
Bypass “Sign In” popup when user has a valid SSO session

### ISSUE THREAD

**Issue by fabiobeoni** [node-red/node-red#3467]
### Current Behavior

When an editor-user access the admin dashboard protected by a third-party auth provider (Keycloak/OKTA/etc) NodeRED displays the Sign-In dialog even if the use has a valid SSO session.

### Expected Behavior

When editor-user has a valid token issued, the Sign-In dialog should not appear, and the editor-user should go directly to the admin dashboard. 

### Steps To Reproduce

1. Protect the admin dashboard by enabling auth with an Open ID provider (Keycloak, OKTA, etc)
2. Login to the auth provider login view
3. Navigate to NodeRED
4. Sign-In dialog appears

### Example flow

First discussion on forum: https://discourse.nodered.org/t/bypass-sign-in-popup-with-sso-openid-valid-session/59295 

### Environment

- Node-RED version: 2.0.6
- Node.js version: 14.17.6
- Platform/OS: Ubuntu 20
- Browser: Brave/Chrome/Firefox latest.

**Comment by knolleary** [comment]
There are some features of `adminAuth` that help with this - but not for this specific scenario.

If the url includes `?access_token=XYZ` then the editor will use `XYZ` as the auth token with the runtime. That allows for accessing the editor without being prompted *if* your adminAuth setup allows custom tokens. That doesn't work with `adminAuth` setup to do SSO flows.

So I think the requirement here would be a suitable flag in `adminAuth` that gets passed to the editor to tell it to attempt the SSO flow automatically without waiting for the user to click the button.

**Comment by sammachin** [comment]
What does logging out of Node-RED then send the user too?

**Comment by knolleary** [comment]
There was a separate question about being able to specify a url to redirect to on logout. I can't find it at the moment, but should be looked at along side this item.

We certainly need to be careful to avoid redirect loops when auth fails.
