### ISSUE TITLE
deleting persistent context in the side-panel doesn't persist

### ISSUE THREAD

**Issue by tve** [node-red/node-red#3469]
### Current Behavior

Deleting persistent data in the context side panel of the editor does not actually delete it from the persistent json file.

### Expected Behavior

I expect the data to be deleted from the persistent store

### Steps To Reproduce

Steps to reproduce:
- Ensure you have a persistent context store
- Create some global context data in a persistent store
- Look in `data/context/global/global.json` to verify that the data got saved
- Open the context side-panel and delete some of the data
- Look again in the above file and observe that the data is still there
- Restart node-RED, open the context side-panel and observe that the data has reappeared

### Environment

- Node-RED version: 2.2.2
- Node.js version: 16
- npm version: ?
- Platform/OS: linux
- Browser: firefox

**Comment by knolleary** [comment]
How is your persistent context configured?

If you are using the default file persistence settings, then it only flushes changes every 30 seconds. It should flush when you stop Node-RED, as long as you are letting it shutdown cleanly rather than forceable killing it.

**Comment by tve** [comment]
Yup, that's the issue. I should have known, sorry for the noise! I'm using systemd+docker, so NR isn't shut down cleanly.
