### ISSUE TITLE
NodeRed boot-loops if a Xiaomi MIIO device not present

### ISSUE THREAD

**Issue by lockheed** [node-red/node-red#3474]
I discovered yesterday, that NodeRed (in HA installation) will not start if xiaomi.miio module cannot connect to an IP of one of the devices (humidifier in my case), either because it was unplugged or its IP has changed. NodeRed will bootloop perpetually. I wasted a day of restoring backups and snapshots of the Home Assistant VM to finally identify why my whole home automation didn't work.

I think this is a pretty grave bug if absence of one device renders the entire home automation dead.

NodeRed: 11.0.3 & 11.0.4

**Comment by hardillb** [comment]
Please fill out the FULL template presented when opening an issue, it gathers all the information we need to look at a problem.

Also 11.0.3 and 11.0.4 are not Node-RED versions, latest is 2.2.1, I suspect you are using Home Assistant plugin versions which we have no knowledge of.

**Comment by knolleary** [comment]
Hi @lockheed 

This repo is for the core of Node-RED. We don't maintain either the Home Assistant plugin or anything to do wit the xiaomi.miio module.

As the issue template that you haven't used says, for issues relating to contrib modules, please raise them against their own repository. 

As you don't say which xiaomi set of nodes you are using, I can't point you in the right direction - but you should be able to find it in the flow library - https://flows.nodered.org/search?term=xiaomi

**Comment by knolleary** [comment]
Without any information about what the actual error is, then I can't say if its something Node-RED can/should handle or not.

There are a certain class of error that the *only* safe thing to do is to restart Node-RED because the plugin has left things in an indeterminate state. This is what the node.js runtime recommends:

> The correct use of 'uncaughtException' is to perform synchronous cleanup of allocated resources (e.g. file descriptors, handles, etc) before shutting down the process. It is not safe to resume normal operation after 'uncaughtException'.

https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly

This is why we have to push these issues out to the nodes that are causing them - only they can add the error handling they are missing for the asynchronous events they are using.

**Comment by Steve-Mcl** [comment]
@lockheed can you please tell us which of the xiaomi nodes is causing this error? A stack trace from the node-red log would be even better.

**Comment by lockheed** [comment]
This is the offender: https://flows.nodered.org/node/node-red-contrib-miio-humidifier
As soon as the Humidifier is unplugged from power, entire NodeRed stack goes down into a bootloop.

Here's the log: https://pastebin.com/raw/KVANLJZn

Second after plugging humidifier back on, NodeRed start normally and works.

**Comment by lockheed** [comment]
Why don't you reopen it? It is NodeRed's bug that it crashes.

**Comment by lockheed** [comment]
How is bringing the entire instance down PERMANENTLY and thus disabling ALL automations indefinitely a "safe option"?

**Comment by hardillb** [comment]
When a node throws an uncaught exception from asynchronous code Node-RED has no idea what state the node has been left in, so the only safe thing to do is exit.

I see you have raised an issue against the Miio node that has not been responded to. This leaves you with 2 options:

1. Raise Pull request against the node to fix the problem
2. Don't use the Miio node.

This issue will not be reopened, for the reasons already stated, especially in Nick's [comment](https://github.com/node-red/node-red/issues/3474#issuecomment-1060592552) linking to the NodeJS doc.

**Comment by hardillb** [comment]
But it is worth noting that the Miio node does appear to have been abandoned
https://github.com/andreyoshev/node-red-contrib-miio-humidifier/issues/11#issuecomment-1090812779

**Comment by hardillb** [comment]
After a very quick (i didn't dig deep) I think changing the following lines

https://github.com/andreyoshev/node-red-contrib-miio-humidifier/blob/7645f441220c91d5bb94d17e2ce7a212c7e25f50/nodes/server.js#L19-L23

to

```javascript
           node.connect().then(result => {
                node.getStatus(true).then(result => {
                    node.emit("onInitEnd", result);
                });
            })
            .catch(err => {});
```

May stop it crashing, but that is just a guess as I don't have any of the hardware to test this lot with.
