### ISSUE TITLE
Input `autoComplete` does not allow searching when value is empty

### ISSUE THREAD

**Issue by zettca** [node-red/node-red#3479]
### Current Behavior

Node-RED [`autoComplete` input widget](https://nodered.org/docs/api/ui/autoComplete/) has a [`search`](https://nodered.org/docs/api/ui/autoComplete/#options-search) option defines a callback when searching for a value.

If the search `value` [is empty](https://github.com/node-red/node-red/blob/master/packages%2Fnode_modules%2F%40node-red%2Feditor-client%2Fsrc%2Fjs%2Fui%2Fcommon%2FautoComplete.js#L75-L80), **search is never called**, making it impossible to display some kind of default value

### Expected Behavior

User has control over search when search `value` is empty when pressing a submit key (`Enter`).

### Steps To Reproduce

1. Go to Node-RED [autoComplete](https://nodered.org/docs/api/ui/autoComplete/#examples) widget examples
2. Focus the autoComplete input, or press `Enter`
3. Notice that no options appear (and there is no way for them to show)

### Environment

- Node-RED version: 2.2
- Node.js version: 16
- npm version: 6.14
- Platform/OS: MacOS
- Browser: Chrome 99

**Comment by knolleary** [comment]
This was a deliberate design choice, but can of course be revisited.
