### ISSUE TITLE
Parent context variable accessed in subflow’s first function node yields undefined

### ISSUE THREAD

**Issue by r0ller** [node-red/node-red#3485]
### Current Behavior

Please, refer to the [thread created in the node-red forum](https://discourse.nodered.org/t/part-2-parent-context-variable-accessed-in-subflow-s-first-function-node-yields-undefined/59362). You'll find there a video attached, the issue described and a minimal flow.

### Expected Behavior

The expected behaviour is that the parent context variable can be accessed reliably.

### Steps To Reproduce

This is the difficult part, as even with the minimal flow, it happens only occassionally.

### Example flow

```
[
    {
        "id": "f70d4fc3.c71c38",
        "type": "subflow",
        "name": "Subflow 2",
        "info": "",
        "in": [
            {
                "x": 80,
                "y": 80,
                "wires": [
                    {
                        "id": "e7a1deed.3d9288"
                    }
                ]
            }
        ],
        "out": [
            {
                "x": 320,
                "y": 80,
                "wires": [
                    {
                        "id": "e7a1deed.3d9288",
                        "port": 0
                    }
                ]
            }
        ]
    },
    {
        "id": "e7a1deed.3d9288",
        "type": "function",
        "z": "f70d4fc3.c71c38",
        "name": "",
        "func": "let a=1;\nnode.warn(flow.get(\"$parent.test\"));\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 200,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "70f7ac75.ea8e34",
        "type": "subflow",
        "name": "Subflow 1",
        "info": "",
        "in": [
            {
                "x": 80,
                "y": 80,
                "wires": [
                    {
                        "id": "48517af6.d85314"
                    }
                ]
            }
        ],
        "out": [
            {
                "x": 480,
                "y": 80,
                "wires": [
                    {
                        "id": "ab5276b6.32ea1",
                        "port": 0
                    }
                ]
            }
        ]
    },
    {
        "id": "48517af6.d85314",
        "type": "function",
        "z": "70f7ac75.ea8e34",
        "name": "",
        "func": "let b=0;\nnode.warn(msg.payload);\nflow.set(\"test\",msg.payload);\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "x": 190,
        "y": 80,
        "wires": [
            [
                "ab5276b6.32ea1"
            ]
        ]
    },
    {
        "id": "ab5276b6.32ea1",
        "type": "subflow:f70d4fc3.c71c38",
        "z": "70f7ac75.ea8e34",
        "name": "",
        "env": [],
        "x": 360,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "aa2b5804.9cad4",
        "type": "subflow:70f7ac75.ea8e34",
        "z": "fb075204.b32578",
        "name": "",
        "env": [],
        "x": 340,
        "y": 540,
        "wires": [
            []
        ]
    },
    {
        "id": "ec2e7096.f0e618",
        "type": "inject",
        "z": "fb075204.b32578",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": "0",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 170,
        "y": 540,
        "wires": [
            [
                "aa2b5804.9cad4"
            ]
        ]
    }
]
```

### Environment

- Node-RED version: 2.2.2
- Node.js version: 14.17.0
- npm version: 6.14.13
- Platform/OS: raspberry pi 4
- Browser: Firefox 98

**Comment by Steve-Mcl** [comment]
I cannot re-create this.

Are you using file context? memory context?

Can you try this flow & show me the results...

```
[{"id":"f70d4fc3.c71c38","type":"subflow","name":"Subflow 2","info":"","in":[{"x":80,"y":80,"wires":[{"id":"e7a1deed.3d9288"}]}],"out":[{"x":320,"y":80,"wires":[{"id":"e7a1deed.3d9288","port":0}]}]},{"id":"e7a1deed.3d9288","type":"function","z":"f70d4fc3.c71c38","name":"","func":"let a=1;\n\nvar fv = flow.get(\"$parent.test\");\nnode.warn([\"flow.get $parent.test:\", fv]);\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":200,"y":80,"wires":[[]]},{"id":"70f7ac75.ea8e34","type":"subflow","name":"Subflow 1","info":"","in":[{"x":80,"y":80,"wires":[{"id":"48517af6.d85314"}]}],"out":[{"x":480,"y":80,"wires":[{"id":"ab5276b6.32ea1","port":0}]}]},{"id":"48517af6.d85314","type":"function","z":"70f7ac75.ea8e34","name":"","func":"let b=0;\nnode.warn([\"payload in subflow 1\",msg.payload, \"setting flow.test\"]);\nflow.set(\"test\", msg.payload);\n\nvar fv = flow.get(\"test\");\n\nnode.warn([\"flow.get test:\", fv]);\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":190,"y":80,"wires":[["ab5276b6.32ea1"]]},{"id":"ab5276b6.32ea1","type":"subflow:f70d4fc3.c71c38","z":"70f7ac75.ea8e34","name":"","env":[],"x":360,"y":80,"wires":[[]]},{"id":"aa2b5804.9cad4","type":"subflow:70f7ac75.ea8e34","z":"c2233fc1d8cc5c3b","name":"","env":[],"x":1960,"y":620,"wires":[["15f615107cfce2bd"]]},{"id":"ec2e7096.f0e618","type":"inject","z":"c2233fc1d8cc5c3b","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":"0","topic":"","payload":"true","payloadType":"bool","x":1790,"y":620,"wires":[["aa2b5804.9cad4"]]},{"id":"15f615107cfce2bd","type":"debug","z":"c2233fc1d8cc5c3b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":2120,"y":620,"wires":[]},{"id":"751517c2a4283555","type":"inject","z":"c2233fc1d8cc5c3b","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":"0","topic":"","payload":"false","payloadType":"bool","x":1790,"y":660,"wires":[["aa2b5804.9cad4"]]}]
```

**Comment by r0ller** [comment]
Sorry for the delay, I had a few days off. I'm using memory context. Just tested the flow you sent on the system where I managed to capture the video. Here is the screenshot taken:

![Screenshot 2022-03-18 at 11-04-31 Node-RED a9zxf23cny5m6d p50 rt3 io](https://user-images.githubusercontent.com/825982/158983698-3c5f9b05-77a2-4c10-9ec1-d93fa144af71.png)

**Comment by Steve-Mcl** [comment]
@r0ller so that was essentially your flow with extra node.warn messages. As I said before, I cannot reproduce it looks like you don't get the issue with my version.  That suggestions something else in your flows are affecting your first version.

**Comment by r0ller** [comment]
I agree that it's difficult to reproduce but I doubt that any other flow could affect that minimal flow as it uses only one flow context variable which is not used anywhere else.
Anyhow, could you please give me some hints where exactly in the node-red code shall I put some console.log() calls (or whatever) that could record in the syslog (or anywhere else) when such an issue happens again? I skimmed through the node-red source files and of course I could identify some places but I'd like to put these log points to places where they help you the best to be able to identify what the problem is.

**Comment by r0ller** [comment]
It seems I've got something for you :)

As I did not have any hint where to put console.log() calls, I actually just uncommented some of yours (and added a 'debug:' prefix) in these two files:

/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Subflow.js
[Subflow.txt](https://github.com/node-red/node-red/files/8676843/Subflow.txt)

/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js
[index.txt](https://github.com/node-red/node-red/files/8676845/index.txt)

Here is today's syslog till now:

[syslog.txt](https://github.com/node-red/node-red/files/8677150/syslog.txt)

The log message you'll see when the issue started happening today (at 10:53:15 and 10:54:04) is:

No flowContext - This *does not happen* in normal node-red operation

That comes from the index.js code.  After that you'll see our app complaining about not being able to access the parent context:

[error] [function:calculate channel sum] TypeError: Cannot read property 'spectrum' of undefined

Earlier I assumed that this issue is triggered by deploy which turns out to be wrong as the preceding deploy happened two days ago. However, the previous experience with the deploy helped, as after adding just a comment to the function where the error happened and hitting deploy, the error vanished. Even though after the deploy (based on the syslog after 11:17:41), I can see still some node-red messages like

No flowContext - This *does not happen* in normal node-red operation

but somehow our app does not complain any more and it seems it can indeed access the parent context.

**Comment by r0ller** [comment]
@Steve-Mcl Any ideas?

**Comment by Steve-Mcl** [comment]
@r0ller sorry I have not had time to dig into this yet. I will try to get to it in the next few days.

**Comment by r0ller** [comment]
@Steve-Mcl Did you manage to figure it out?

**Comment by r0ller** [comment]
Hi there,

Will this get fixed in the new (3.0) release?

**Comment by knolleary** [comment]
Hi @r0ller 

Hard to say. Given we cannot reproduce it, there is not a lot for us to go on to figure out what is happening. I've looked at the files you've shared - its hard to piece everything together at the moment.

Either it's looking for the wrong context, or something has made the flow context go away. Some additional debug would be very helpful if you're able to provide it.

 - adding in the value of `contextId` to the `debug:No flowContext - This *does not happen* in normal node-red operation` statement
 - It would also be helpful to add a debug statement alongside any call to `delete contexts[...]`, including the id of the context being deleted.

**Comment by r0ller** [comment]
Ok, added the mentioned debug logging to /lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js

I'll let you know once I have something.

**Comment by r0ller** [comment]
So, here is today's relevant syslog part, containing the contextIds added to the debug logging:

[subflow_issue_syslog.txt](https://github.com/node-red/node-red/files/9046742/subflow_issue_syslog.txt)

Some hints what I observed:

- This time the issue happened to a different subflow which happens to be the one within the example flow called 'Subflow 2' with id f70d4fc3.c71c38 It simply could not get a context variable from its parent called 'Subflow 1'.
- I uploaded only the relevant part of the syslog where the story began and where it ended but in between you'll see some other logs from our app.
- What I observed was that when I clicked the inject button of the example subflow, the output was 'true' produced by Subflow 1 but 'undefined' came from Subflow 2 which actually just prints the flow context variable of Subflow 1 via a node.warn(). That's the following part in syslog:
Jul  5 14:32:44 raspberrypi Node-RED[25532]: 5 Jul 14:32:44 - [warn] [function:fd68d59d4f6ca453] true
Jul  5 14:32:44 raspberrypi Node-RED[25532]: debug:No flowContext for contextId:e7a1deed.3d9288:31a14d0ff82ce78e - This *does not happen* in normal node-red operation
Jul  5 14:32:44 raspberrypi Node-RED[25532]: 5 Jul 14:32:44 - [warn] [function:7ae1627ff19e7efc] undefined

Probably, the context got deleted earlier so you'll need to go backwards to find that.
- Then I tried to get the lightlog subflow running by logging in and clicking some buttons. This what you see happening between 14:34:48 and 14:35:54. However, this time that subflow does not seem to be affected.
- After logging out I clicked again the inject button of the example flow and it produced the same result as previously:
Jul  5 14:36:04 raspberrypi Node-RED[25532]: 5 Jul 14:36:04 - [warn] [function:fd68d59d4f6ca453] true
Jul  5 14:36:04 raspberrypi Node-RED[25532]: 5 Jul 14:36:04 - [warn] [function:7ae1627ff19e7efc] undefined
- Then I hit the deploy button as there were some pending changes done by me earlier (before I first checked if the example flow works) and clicked the inject button again but the result was the same:
Jul  5 14:36:42 raspberrypi Node-RED[25532]: 5 Jul 14:36:41 - [info] Started modified nodes
Jul  5 14:36:45 raspberrypi Node-RED[25532]: 5 Jul 14:36:45 - [warn] [function:fd68d59d4f6ca453] true
Jul  5 14:36:45 raspberrypi Node-RED[25532]: 5 Jul 14:36:45 - [warn] [function:7ae1627ff19e7efc] undefined
- After that I changed the function codes in both subflows 'Subflow 1' and 'Subflow 2'. Simply set a new value to an unused variable in each (changed a=0 to a=1 in Subflow 2 and b=0 to b=1 in Subflow 1) to be able to trigger a deploy. The deploy solved the issue, as when I clicked the inject node of the example flow I got:
Jul  5 14:37:26 raspberrypi Node-RED[25532]: 5 Jul 14:37:25 - [info] Started modified nodes
Jul  5 14:37:35 raspberrypi Node-RED[25532]: 5 Jul 14:37:35 - [warn] [function:473a395b7efb2d6f] true
Jul  5 14:37:35 raspberrypi Node-RED[25532]: 5 Jul 14:37:35 - [warn] [function:289a1f6f3c0cada7] true

I hope this helps you guys :)

**Comment by r0ller** [comment]
By the way, I forgot to mention in the previous comment that I can provide you with yesterdays syslog if today's does not help. The context in question may have got deleted even yesterday. Earlier syslogs we have too as the raspberry keeps them for 7 rolling days but as those do not contain the contextIds in the debug logs they are probably not helpful at all.

**Comment by r0ller** [comment]
Hi there,

Did you manage to figure out what goes wrong?

**Comment by knolleary** [comment]
@r0ller I would have commented here if there was news to share. I haven't had time to wade through the 21k lines of log you've shared.

You've provided a lot of information and a lot of events to pick apart.

Looking at `Jul 5 14:32:44 raspberrypi Node-RED[25532]: debug:No flowContext for contextId:e7a1deed.3d9288:31a14d0ff82ce78e - This does not happen in normal node-red operation` specifically, if we search for that context ID in the log (`e7a1deed.3d9288:31a14d0ff82ce78e`) we can see it was deleted as part of the modified nodes deploy at `14:37:35`.

The question is then *why*. That will require further digging through the code.

**Comment by r0ller** [comment]
Sorry for pushing this, I know how it feels when there's a ton to fix/develop. However, the current situation is that whenever I deploy, I just cannot trust the framework about that it does not break some running flows. For me, it's already a good thing that after half a year the scope got narrowed down so that the bug could be identified. Solving it of course is another beast altogether.

**Comment by r0ller** [comment]
Any news about this? The label 'needs-info' is also misleading due to which this can get easily forgotten.

**Comment by Steve-Mcl** [comment]
See  https://github.com/node-red/node-red/issues/3889#issuecomment-1453961495

Should probably close one of these 2 issues

**Comment by r0ller** [comment]
Sounds good :) However, I cannot justify it since I don't have access to that system any more and we stopped using node-red due to this bug for other projects.
