### ISSUE TITLE
Unable to add unit tests to node-red for `http in` / `http response`  (404 errors)

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#3486]
### Current Behavior

I am looking at adding unit tests for the HTTP-In and HTTP-Response nodes (before I add a new feature).
I have the bones of it working but the HTTP-In Node never gets called (the test always errors with a 404)

REF: https://node-red.slack.com/archives/C9RSU6S56/p1646839765269019

### Expected Behavior

To be able to call Endpoint so that HTTP In Node Unit Tests can be added to node-red

### Steps To Reproduce

Add test flow with `http in` node
Call endpoint with got or fetch or browser - instant 404

### Environment

- Node-RED version: 2.2.2
- Node.js version: 14
- npm version: na
- Platform/OS: na
- Browser: na

**Comment by knolleary** [comment]
I think this will be an issue with https://github.com/node-red/node-red-node-test-helper rather than the core.

**Comment by Steve-Mcl** [comment]
Raised in [node-red-node-test-helper/53](https://github.com/node-red/node-red-node-test-helper/issues/53)
