### ISSUE TITLE
Invalid Encrypted Credentials object does not error

### ISSUE THREAD

**Issue by sammachin** [node-red/node-red#3496]
### Current Behavior

If Node-RED is using encrypted credentials (either system generated or user generated) but for whatever reason the creds object does not contain the $ key the credentials will not be loaded but no error is shown in the logs.

For example https://github.com/flowforge/flowforge/issues/397

### Expected Behavior

A warning should be shown in the Node-RED log that encrypted credentials were not found.

### Steps To Reproduce

Setup Node-RED with a credentialSecret and create a simple flow that has some credentials in it, for example HTTP Request node with basic auth.

Deploy the flow and then stop node-red

Edit the flows_cred.json file to invalidate the object, eg change the key from `$` to `foo`

Start Node-RED and observe that there are no warnings in the log, 
Check the HTTP request node and the credentials values will be missing

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.2.2
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: MacOS
- Browser: Chrome

**Comment by sammachin** [comment]
I have a fix for this, will raise a PR

**Comment by knolleary** [comment]
There are two valid scenarios where the credentials object may not contain a `$` key:

1. The user is moving from unencrypted to encrypted
2. This is the very first time NR has been run, so the credentials object is empty.

We should not log an error for either of these cases; but I'm not entirely sure how you'd detect the first-run case.
