### ISSUE TITLE
Wiring junctions in a way a msg is not transmitted

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#3506]
### Current Behavior

* Possible to wire odd arrangement where no `msg` gets through (DEMO 1)

* Deleting a "good wire" then replacing it causes odd wiring and `msg` does not make it through the flow. (DEMO 2)

### Expected Behavior

Prevent joining if not valid

### Steps To Reproduce

Import (or replicate) the flows below.

#### Demo 1...
![chrome_sylyI0UtiN](https://user-images.githubusercontent.com/44235289/159871706-9bf10689-81ef-4516-8c11-23d9d3f5e82d.gif)

```
[{"id":"83a067d8d7767cf5","type":"inject","z":"a8f2fd5e9bb60bcf","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"fred","payloadType":"str","x":1330,"y":380,"wires":[["9a0438fb36dbd9ea"]]},{"id":"a1dc381d92309c80","type":"debug","z":"a8f2fd5e9bb60bcf","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"\"fred \" & payload","statusType":"jsonata","x":1300,"y":440,"wires":[]},{"id":"7fbe3faf3bb4e7f8","type":"junction","z":"a8f2fd5e9bb60bcf","x":1160,"y":440,"wires":[["a1dc381d92309c80"]]},{"id":"d50f402dffed4939","type":"junction","z":"a8f2fd5e9bb60bcf","x":1460,"y":380,"wires":[["7fbe3faf3bb4e7f8","9a0438fb36dbd9ea"]]},{"id":"9a0438fb36dbd9ea","type":"junction","z":"a8f2fd5e9bb60bcf","x":1520,"y":500,"wires":[[]]}]
```

#### Demo 2
![chrome_G6RuClVmuJ](https://user-images.githubusercontent.com/44235289/159872397-356921c0-8612-450a-bb1e-02cacfb00a90.gif)

```
[{"id":"c002f56b02ae7c32","type":"debug","z":"a8f2fd5e9bb60bcf","name":"debug 2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1347.999997317791,"y":159.99999886751175,"wires":[]},{"id":"a32c97b613303016","type":"inject","z":"a8f2fd5e9bb60bcf","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1340,"y":100,"wires":[["5b0dff4c80021945"]]},{"id":"d6b44c2c93c77454","type":"junction","z":"a8f2fd5e9bb60bcf","x":1480,"y":180,"wires":[["ad382084c106decc"]]},{"id":"5d4b29c28d9152d9","type":"junction","z":"a8f2fd5e9bb60bcf","x":1520,"y":160,"wires":[["d6b44c2c93c77454"]]},{"id":"ad382084c106decc","type":"junction","z":"a8f2fd5e9bb60bcf","x":1420,"y":260,"wires":[[]]},{"id":"bf134fcd2c0ea7ba","type":"junction","z":"a8f2fd5e9bb60bcf","x":1260,"y":260,"wires":[["f10bdcd36f35efd7","ad382084c106decc"]]},{"id":"f10bdcd36f35efd7","type":"junction","z":"a8f2fd5e9bb60bcf","x":1227.999997317791,"y":159.99999886751175,"wires":[["c002f56b02ae7c32"]]},{"id":"5b0dff4c80021945","type":"junction","z":"a8f2fd5e9bb60bcf","x":1480,"y":100,"wires":[["5d4b29c28d9152d9"]]}]
```

### Environment

- Node-RED version: 2.2.2 on `dev` branch 
- Node.js version: 16
- npm version: NA
- Platform/OS: Windows 11
- Browser: Chrome 99.0.4844.74

**Comment by knolleary** [comment]
We explored this on this week's livestream (which I haven't put on youtube yet... now reminded to do so)

When wiring from a junction, the key thing is you are creating the wire in the direction you want messages to flow.

On the live stream I showed a quick move around of the nodes above showed perfectly valid flows where you'd want the wires in the directions shown (once a couple more nodes were added).

I reached the conclusion this was working as intended and no amount of logic would be able to identify you wanted something different and reverse the wire.

Arrowheads (#3318 ) were looked at... but that then got very messy when you have lots of junctions. But as arrowheads were going to be an optional thing anyway, then I wouldn't lose sleep over it.

So I think the net conclusion is this is working as designed - we just need to make sure the docs make it clear that when you wire from a junction, you must be wiring in the direction of message flow.

**Comment by Supergiovane** [comment]
Hi knolleary
it could be helpful to replace the last join line circle icon, with an arrow indicating the msg direction. 
Instead of: o——o
Something like: o———>

**Comment by Steve-Mcl** [comment]
Perhaps on `:hover` of a junction, it morphs into an arrow head? 
i.e. as you drag a wire from / approach a junction to drop a wire, the junctions shape indicates direction of flow? 
![chrome_BDBCldG8F0](https://user-images.githubusercontent.com/44235289/161524609-fab4cc5f-ca76-4266-aa9c-7022ed483e48.gif)


Otherwise, we can just close this issue since it is not actually a bug but merely an "understanding" thing?

**Comment by dceejay** [comment]
I think I would find that distracting - wondering what it was about to do. But maybe a smaller arrow ?
<img width="38" alt="image" src="https://user-images.githubusercontent.com/5375409/161628340-2a6411bf-b8e3-4772-b20d-59099a900b9d.png"><img width="29" alt="image" src="https://user-images.githubusercontent.com/5375409/161628213-a8c0d7d3-3a22-41e6-ba4f-cabd9f80e567.png">

**Comment by Steve-Mcl** [comment]
@dceejay yes the arrow inside looks much better (my CSS animation was a quick and dirty copy/paste affair for demonstration purposes entirely)

If it's an accepted approach, I (someone) will do a much better job of it 😉

**Comment by Steve-Mcl** [comment]
Added the label `wont fix` since it is functionally correct. 
However if desired, we can explore the `on hover` animated arrow (inside the bullet to indicate flow direction)
Closing issue for now.
