### ISSUE TITLE
No custom style for borders on jQuery ui widgets

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3518]
### Current Behavior

The [jquery.scss](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/editor-client/src/sass/jquery.scss) file seems to be missing custom styles for the borders on UI widgets. This is an issue when using themes.

<img width="1728" alt="Screen Shot 2022-04-04 at 10 25 59 AM" src="https://user-images.githubusercontent.com/29807944/161602279-8b2a5778-d5e1-4ebd-be87-1e6b2857220f.png">

### Environment

- Node-RED version: 2.2.2
- Node.js version: v16.14.2
- npm version: 8.5.0
- Platform/OS: macOS Monterey
- Browser: Chrome, Safari, and Firefox

**Comment by bonanitech** [comment]
I can create a PR to fix this, but I don't know which SASS variable to use in this case. Maybe `$secondary-border-color`?

**Comment by knolleary** [comment]
Please do PR something.
