### ISSUE TITLE
SSL Routines bad write retry

### ISSUE THREAD

**Issue by adnorman** [node-red/node-red#352]
Running 0.8.1.git on a std Raspberry Pi using Twitter Sentiment node

Node Red had been happily gathering Tweets for last 7 days then this evening the following error occurred 

3065287792:error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry:s3_pkt.c:872:

this stopped the flow and now will not respond even when re-deploying to Node Red

**Comment by knolleary** [comment]
Closing this issue - it isn't something we've had any further reports of and is tied to the node/ssl versions. Given how far they have moved on, there is no value having this issue open.
