### ISSUE TITLE
Error Unknown library: _examples_

### ISSUE THREAD

**Issue by E1cid** [node-red/node-red#3525]
### Current Behavior

when importing flows I get the error in debug "Error: Unknown library: _examples_". I can import and export no issue. It seems the example libray can not be found.
I just upgraded from 1.29 to 1.3.7 on  this device.
I did not upgrade to 2 for compatibility issues.
The error causes no issues but i can not access the examples library.

### Expected Behavior

not to show error

### Steps To Reproduce

not sure i can add anything helpful here

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 1.3.7
- Node.js version: 12.13
- npm version: 6.12
- Platform/OS: android 
- Browser: firefox and chrome

**Comment by Steve-Mcl** [comment]
Hi. It's there any additional info in node red log (a stack trace would be useful)

Additionally, could you check the browser console for errors. 


Thanks. 

Ps, out of interest what compatibility issues do you refer to?

**Comment by E1cid** [comment]
Sorry nothing has been logged.
Nothing in developer console either.

Sorry while looking the issue has resolved, I suspect a cache issue, sorry to trouble you all. I did refresh, but issue vanished after force stop and clear cache.

The compatibility issue is not with node red, but termux, this is an old device and still running a play store termux, I need to update to non play store termux to get updated linux and node.js plus some other modules
