### ISSUE TITLE
Settings location must be specified with argument to start node-red on Proxmox Debian11 LXC

### ISSUE THREAD

**Issue by Kamoool** [node-red/node-red#3539]
### Current Behavior

After installation of Node-red with script for Raspberry PI it cannot start neither by typing node-red command nor by systemctl start nodered.service. It throws error on parsing "path" argument with message:
`Starting as root systemd service.
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at Object.<anonymous> (/usr/lib/node_modules/node-red/red.js:115:50)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.`

It starts just fine with either of:
- `node-red --settings /usr/lib/node_modules/node-red/settings.js`
- Editing nodered.service and adding `--settings /usr/lib/node_modules/node-red/settings.js` in ExecStart line, then reloading systemctl and starting.

Apart from that if one would like to run non-pi version of node-red ExecStart for that one must also be changed from node to node-red.
What is more when I'm trying to run node-red admin init I also get error about "path" argument. I haven't found solution yet.

### Expected Behavior

Node-red starts fine with default settings.js location.

### Steps To Reproduce

1. Setup Proxmox Debian11 LXC container with 1GB of RAM, 8GB of disk space.
2. Run: `apt update && apt upgrade -y`
3. Run: `apt install sudo curl build-essential git curl`
4. Run: `bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)`
5. After successful try to startup node-red by `node-red` or `systemctl start nodered.service`

### Example flow

IRRELEVANT

### Environment

- Node-RED version: 2.2.2
- Node.js version: v14.19.1
- npm version: 6.14.16
- Platform/OS: Proxmox with Debian11 LXC 1GB RAM, 8GB disk space

**Comment by hardillb** [comment]
But `/usr/lib/node_modules/node-red/settings.js` is not the default location for the `settings.js`. 

That is the location of the template `settings.js` that will be copied to the `userDir` on first execution. The default `userDir` is the in the the `.node-red` directory in the current users home directory.

So the question is, what user is the service running as and what is it's home dir?

**Comment by hardillb** [comment]
Also please supply a link to instructions for setting up a "Proxmox Debian11 LXC container"

**Comment by Kamoool** [comment]
I'm on root user, so it should run as root. I figured that starting with `sudo node-red` even being on root works. Also in service file changing user to root is sufficient. 
Setting that container through Proxmox GUI is task I don't have instructions for.

**Comment by hardillb** [comment]
The error implies that the environment for the user (root) doesn't have a `HOME` environment variable. So Node-RED can not determine the default `userDir` location.

https://github.com/node-red/node-red/blob/3a26c5cd651224f5c0a0366d184db050d7dc8ebd/packages/node_modules/node-red/red.js#L115

We should probably add a try/catch block in that code to give a meaningful error message rather than that stack trace, but I'm tempted to say this is a problem with the environment (not having a `HOME` env var set for the user) not Node-RED.

The correct solution is to add the `-u /path/to/node-red/userDir` not to set the path to the settings.js file.
