### ISSUE TITLE
MQTT Node: verify server certificate checkbox ambiguous 

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#3545]
### Current Behavior

In the MQTT configuration node, when set to use TLS and the verify server certificate checkbox is checked, the broker still connects which is confusing.
If a CA certificate is provided then the node behaves correctly and won't connected if it can't validate.

### Expected Behavior

I would expect the checkbox to be greyed out if no files have been uploaded.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.2.2
- Node.js version: 16
- npm version:
- Platform/OS: Mac
- Browser: Safari

**Comment by knolleary** [comment]
I believe it is a valid option to tick the verify box without providing your own CA cert - it will validate against the default CAs.

> Default is to trust the well-known CAs curated by Mozilla

(from `options.ca` - https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions)

**Comment by natcl** [comment]
And is it normal that Let's Encrypt root CAs aren't part of NodeJS ?

**Comment by hardillb** [comment]
Which version of nodejs and which of the 2 possible intermediate CA certs...

**Comment by natcl** [comment]
Ahhh, sorry been a tough morning, so basically Node.JS uses it's own internal list of CAs and the verify server certificate toggle actually work. Closing this now, sorry for the noise.
