### ISSUE TITLE
Http Node Post - Credentials

### ISSUE THREAD

**Issue by ImTheDeveloper** [node-red/node-red#355]
Hi,

I send a  HTTP post to a number of webservers some that require basic authentication and some that dont. In order to do this I have used multiple HTTP Post nodes which fire when an input comes in.

I've noticed that when I edit my HTTP Post nodes with the basic auth tickbox unticked, deploy and then go back in to the same node I see the credentials are being shown. I'm unsure whether this is an issue with the tick box not working or not but its happened a few times. If this is unclear I can run a few screenshots if needed.

**Comment by aihysp** [comment]
Hi Five years later is this been resolved? :)

its killing me, sometimes i want to do a simple change and dont even notice that he inputted user

**Comment by knolleary** [comment]
Nothing has changed - chrome will auto-fill forms if you have the option enabled in your chrome settings. It doesn't provide a way to disable it on per-site basis.

**Comment by aihysp** [comment]
Thanks !
