### ISSUE TITLE
Shift-RightClick-Drag doesn't work on Firefox (v3 beta)

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3582]
### Current Behavior

If you Shift-RightClick-Drag on Firefox, it will show the browser context menu.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.0-beta.1
- Node.js version: v16.15.0
- npm version: 8.5.5
- Platform/OS: macOS
- Browser: Firefox

**Comment by knolleary** [comment]
It appears that FF does not allow shift-right-click to be hijacked and will always display the context menu.

https://bugzilla.mozilla.org/show_bug.cgi?id=897379

This has kicked off a discussion around our mouse actions in general - and whether we should move away from right-click actions all together.

There is a proposal here: https://github.com/node-red/designs/discussions/73 (which at the time of writing I've not reviewed yet...).

**Comment by jdotbdot** [comment]
On Windows at least, FF v100 shows the context menu when you _release_ the right mouse button, so it's still possible to do right click-drag operations. 
However, holding down a key and either mouse button while dragging is a pain with a laptop touchpad or on a tablet.
