### ISSUE TITLE
Block diagram as graphs and adta-structures on Node-RED

### ISSUE THREAD

**Issue by brunolnetto** [node-red/node-red#3601]
Hi,

I have a library with multiple data-structures called dot-quiver. In special, the data-structure GRAPH may suit you well for the modelling of path finding, testing and set handling. The functionalities I have in mind are:

1. Trails, circuits and paths on diagrams: [here](https://github.com/dot-quiver/dot-quiver-api/blob/d85bbe01f13f2885e5bf88638159b5cd64676d28/data-structures/graph/Graph.js#L2173);
2. Venn diagram for more than 3 sets: [here](https://github.com/dot-quiver/dot-quiver-api/blob/d85bbe01f13f2885e5bf88638159b5cd64676d28/utils/arrays/arrays.js#L500);

I was able to utilize in a similar fashion developed diagrams for the tool [FlowBuild](https://flow-build.github.io/). You can find respective parsers [here](https://github.com/dot-quiver/dot-quiver-api/blob/main/utils/workflow/parsers.js).

That is it! Enjoy.

**Comment by knolleary** [comment]
Thanks for sharing. Not sure what you would like us to do with this, but as it isn't an actual code issue with Node-RED, well close this.

**Comment by brunolnetto** [comment]
I do not know how do you store diagram entities in node-RED. In FLowBuild, it is of json type. Hence, it is easy to parse them and convert to graphs. From a graph, one may extract many useful information, for example, its connectivity, number of end and start nodes, paths, circuits, among others. Since node-RED relies on expertise of developers already familiar with the tool-set, it may look like it underestimate users' mind. However, the automated manner to extract these information is the interesting part of the library.

**Comment by dceejay** [comment]
Node-RED flows are also stored as json files - so you may also extract info in a similar (but not the same) way./

**Comment by brunolnetto** [comment]
Oohh, great. I would still require some instructions about the json file structure, types and some Node-RED samples to give some MVP use cases of the library. May you assemble some for me?

**Comment by dceejay** [comment]
If you look at a flow file you will see that it is an array of objects (nodes). Each has a unique id, a type, and a wires property that list the other ids (nodes) that it is linked to. You should be able to work from there

**Comment by brunolnetto** [comment]
May you copy-paste here the url of flow files available publicly?

**Comment by dceejay** [comment]
See the flows.nodered.org site and search for example flows. Or create some yourself.

**Comment by brunolnetto** [comment]
Awesome!
