### ISSUE TITLE
ACE editor worker `this.options[xxx]` are set `undefined` regardless of value set in `options[xxx]`

### ISSUE THREAD

**Issue by adiljouahri** [node-red/node-red#3610]
### This code in editor-client, node-red version 2.1.4
* So this function setOptions set the options, if the options argument is valid you enter a loop and you set the (this.options) properties to the new value provided.
https://github.com/node-red/node-red/blob/03e9e8955855bbb3e1f71cc74a76489f588754f8/packages/node_modules/%40node-red/editor-client/src/ace/mode/nrjavascript_worker.js#L101

### Expected Behavior

* **The issue** is in "options.opt", opt is a variable isn't a property of the options object, so it should be:
this.options[opt] = options[opt];

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
No. That is intended. 
`tgis.options` is declared immediately before that line and the like you have linked to is simply populating `this.options` from `options` argument.

**Comment by Steve-Mcl** [comment]
Sorry. I had to double check. Yes. It may well be a bug. I will look later. Thanks.

**Comment by adiljouahri** [comment]
Ok, but options.opt give undefined, so any options property you provide it set the this.options[opt] to undefined

**Comment by adiljouahri** [comment]
Sure,

**Comment by Steve-Mcl** [comment]
Yes. I read & responded too soon (see post above)

Thanks for raising.

**Comment by adiljouahri** [comment]
Yes, I responded before you double check, thanks too.
