### ISSUE TITLE
HTTP Request error with multiple request

### ISSUE THREAD

**Issue by barissecen** [node-red/node-red#3613]
We are facing an issue when we are doing a lot of requests using HTTP Request on our NodeRED flow which is installed as docker. 

By the way we have a another installation on my windows laptop not docker, we are not facing any error. Is this beacuse of docker resource limitaion or this paramters (http.globalAgent.maxSockets = 100;) should be added to setting.js if so, how to write this parameter to setting.js?
 Thanks

Here is the error:

error:
[error] [http request:f80d07d67d7521e5] RequestError: connect ECONNREFUSED 192.168.168.25:9997

**Comment by hardillb** [comment]
Please fill out the FULL template you were shown when opening this issue, it collects information we need before we can offer any help.

**Comment by knolleary** [comment]
Hi @barissecen 

Since Node.js 0.12, the default value of `maxSockets` is `Infinity` - so that is not the limiting factor you are hitting here.

https://nodejs.org/api/http.html#agentmaxsockets

It is hard to say if this is a docker restriction - you'd have to check the docker docs for that, it isn't something we limit in Node-RED.

**Comment by barissecen** [comment]
> 

Thanks for your answer, I mean, maybe I should limit maxSockets by adding this paramater; http.globalAgent.maxSockets = 100 but not sure where (maybe setting.js) and how to write it. Do you have any example or info? Thanks.

**Comment by knolleary** [comment]
I have no idea if this will work, but if you want to set that value, then do so in your settings.js file. You'd have to modify both the http and https global agents:

```
const http = require('http')
http.globalAgent.maxSockets = 100
const http = require('https')
https.globalAgent.maxSockets = 100
```

We don't use the global agent if you have an http proxy configured. I do not know if the proxy agent would pickup that value - you'd have to test it to see.

**Comment by barissecen** [comment]
> 
When I paste like you shared, it is getting an error and the nodered does not run.  I think you had another similar issue before and it worked before but how should be add this paramater. (https://github.com/node-red/node-red/issues/959)  

![image](https://user-images.githubusercontent.com/53810736/168774278-30d8530a-12d4-4f73-a533-cc6edf1453aa.png)

**Comment by knolleary** [comment]
You have pasted in the middle of the `module.exports = { } ` object. That is incorrect. Add it to the very top of the file, outside of the `module.exports` block.

**Comment by barissecen** [comment]
> odule.exports = { }

You mean like this? But result is same. still not working :(.
![image](https://user-images.githubusercontent.com/53810736/168775934-9d8ffae6-d31e-41e5-a859-c502d976790a.png)

**Comment by barissecen** [comment]
> > odule.exports = { }
> 
> You mean like this? But result is same. still not working :(. ![image](https://user-images.githubusercontent.com/53810736/168775934-9d8ffae6-d31e-41e5-a859-c502d976790a.png)

Sorry there was a type error, I have fixed it now it is working;
![image](https://user-images.githubusercontent.com/53810736/168776718-b3763c57-01f6-4e55-83b8-0411a66088b4.png)

**Comment by barissecen** [comment]
> You have pasted in the middle of the `module.exports = { } ` object. That is incorrect. Add it to the very top of the file, outside of the `module.exports` block.

Thank you for you support, the problem was solved. we can close the issue.
