### ISSUE TITLE
Flow Title cannot be changed

### ISSUE THREAD

**Issue by RealFlachmann** [node-red/node-red#3617]
### Current Behavior

In 3.0.0 beta the flow title / name / label cannot be changed any more. The appropriate field does not exist.

Also the comment or documentation tab is not available any more.

### Expected Behavior

Flow label can be changed.

### Steps To Reproduce

![grafik](https://user-images.githubusercontent.com/30465884/169282353-d1134647-f8ad-4d14-ab15-956ae4ecdd23.png)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0 beta
- Node.js version: 16.15
- npm version: 8.10
- Platform/OS: Windows
- Browser: FF

**Comment by Steve-Mcl** [comment]
This was resolved along with many other niggles in beta.2 

REF: #3577

**Comment by RealFlachmann** [comment]
Ok, didn't found this upfront! Cheers!

**Comment by knolleary** [comment]
As mentioned on the beta forum post - if you find issues with the beta, please add comments to the forum post rather than raise issues.
