### ISSUE TITLE
Dummy Names for Functions and Links clashes nrLint Check

### ISSUE THREAD

**Issue by RealFlachmann** [node-red/node-red#3618]
### Current Behavior

As discussed in [https://discourse.nodered.org/t/node-red-3-0-0-beta-2-released/62698/28](https://discourse.nodered.org/t/node-red-3-0-0-beta-2-released/62698/28), so that this doesn't get missed.

### Expected Behavior

**nrLint** keeps its functionality to detect unnamed functions and links.

Even if a nodes now get dummy namen, these are still considered to be unnamed, because "function 1" is as meaningless as "function".

### Environment

- Node-RED version: 3.0 beta
- Node.js version: v16.15
- npm version: 8.10
- Platform/OS: Windows
- Browser: FF

**Comment by knolleary** [comment]
This is a nrlint issue. As you have raised an issue on the nrlint repo already, there's no need to have one on the core as well.

**Comment by Steve-Mcl** [comment]
@knolleary my bad, I suggested this repo to the OP because I read your "We could certainly add an option to ...." post as "we could add an option to enable / disable auto naming of nodes in the NR core" 😊
