### ISSUE TITLE
TCP sockets crashing when a client disconnect unexpectedly

### ISSUE THREAD

**Issue by b10up** [node-red/node-red#3619]
### Current Behavior

TCP out node in listening mode not working properly, if a client disconnects unexpectedly, it throws a socket error and some of the still active clients stop receiving data.

### Expected Behavior

1:Configure a tcp-out node in listen mode (in my example, write timestamp every 1 seconds)
2:Connect with multiple clients ( putty, telnet, localhost in my case, but i tested also from multiple external clients)
3:Kill a terminal from task manager or plug off the ethernet from a remote client
4:The rest of the clients still receiving the data

### Steps To Reproduce

1:Configure a tcp-out node in listen mode (in my example, write timestamp every 1 seconds)
2:Connect with multiple clients ( putty, telnet, localhost in my case, but i tested also from multiple external clients)
3:Kill a terminal from task manager or plug off the ethernet from a remote client
4:The node red console writes socket error, the other clients randomly stops receiving data

### Example flow
```json
[
    {
        "id": "69b8f80db494f181",
        "type": "tcp out",
        "z": "360d032be0511281",
        "name": "",
        "host": "",
        "port": "50000",
        "beserver": "server",
        "base64": false,
        "end": false,
        "tls": "",
        "x": 520,
        "y": 120,
        "wires": []
    },
    {
        "id": "d8083637a25dd4a4",
        "type": "trigger",
        "z": "360d032be0511281",
        "name": "",
        "op1": "",
        "op2": "0",
        "op1type": "date",
        "op2type": "str",
        "duration": "-250",
        "extend": false,
        "overrideDelay": false,
        "units": "ms",
        "reset": "",
        "bytopic": "all",
        "topic": "topic",
        "outputs": 1,
        "x": 280,
        "y": 120,
        "wires": [
            [
                "69b8f80db494f181"
            ]
        ]
    },
    {
        "id": "50c6bd3df2d0fe6e",
        "type": "inject",
        "z": "360d032be0511281",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 140,
        "y": 40,
        "wires": [
            [
                "d8083637a25dd4a4"
            ]
        ]
    }
]
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by b10up** [comment]
Hi, of course:
19 May 14:43:22 - [info] Node-RED version: v3.0.0-beta.2
19 May 14:43:22 - [info] Node.js  version: v16.15.0
19 May 14:43:22 - [info] Windows_NT 10.0.22000 x64 LE
npm@8.10.0,
Browser: Google Chrome 101.0.4951.67

**Comment by b10up** [comment]
Successfully reproduced on Raspberry Pi 3b+
NPM 8.5.5 
Node-RED v1.3.5
NodeJS v16.15.0
Raspbian 10 Buster 5.15.40-v7+ armv7l

**Comment by Steve-Mcl** [comment]
> Node-RED v1.3.5

So this is an existing issue 🤔 

Do you happen to have a node-red V2.2.0 you could test on (would be much appreciated)

**Comment by b10up** [comment]
Tested on v2.2.2, same issue can be reproduced.
npm 6.14.4
Ubuntu 20.04.4 LTS 5.4.0-105-generic x86_64
NodeJS v10.19.0

**Comment by b10up** [comment]
I think i found the solution:
node-red/packages/node_modules/@node-red/nodes/core/network/31-tcpin.js

The sockets are created with "autoDestroy":true, but from line 462. the socket.on('error'...  function has a connectedSockets.splice().  
I removed this line, so the code snippet looks like this now:

`
socket.on('error',function() {
                    node.log(RED._("tcpin.errors.socket-error",{host:socket.remoteAddress, port:socket.remotePort}));
                    node.status({text:RED._("tcpin.status.connections",{count:connectedSockets.length})});
                });
`

If i kill some of the active clients, the others are not failing anymore.

**Comment by Steve-Mcl** [comment]
@b10up while that might work, its problematic as the array `` still has its entry. 

Would you be willing to test the following modification? ...

### Original Code
```javascript
                socket.on('error',function() {
                    node.log(RED._("tcpin.errors.socket-error",{host:socket.remoteAddress, port:socket.remotePort}));
                    connectedSockets.splice(connectedSockets.indexOf(socket),1);
                    node.status({text:RED._("tcpin.status.connections",{count:connectedSockets.length})});
                });
```

### Trial Modification
```javascript
                socket.on('error',function() {
                    node.log(RED._("tcpin.errors.socket-error",{host:socket.remoteAddress, port:socket.remotePort}));
                    setImmediate(() => {
                        connectedSockets.splice(connectedSockets.indexOf(socket),1);
                        node.status({text:RED._("tcpin.status.connections",{count:connectedSockets.length})});    
                    })
                });
```

**Comment by b10up** [comment]
> while that might work, its problematic as the array `` still has its entry.

If I understand what is happening, this is the source of the problem. When a socket throws an error and the onError event is triggered, the connectedSockets.length is already decreased by one (or by the number of killed sockets), so it seems, it is already wiped and not needed to delete it manually [fixme]. I don't know, it is possible or is there something else that must be cleared.
As i see, when we keep the `connectedSockets.splice(connectedSockets.indexOf(socket),1);` , this deletes an another active socket, because the failed one is not in the array anymore. 

Meanwhile the status node also shows the correct value of the remaining active clients, if i  remove the splice() from the code. 


> Would you be willing to test the following modification? ...

I tested it, but unfortunately, this makes exactly the same bug.

**Comment by Steve-Mcl** [comment]
ok, I cannot recreate this (in my current setup) however based on what you are saying, my guess is the item is being removed in `on('close'...` first then in `on('error'...`.  

I have done a test at my side using a `Set` (A set only permits one entry & has helper functions to better manage the connections than array.splice)

Would you be willing to try and break this please?

New code - replaces [this code](https://github.com/node-red/node-red/blob/8a4062281504e769e8348c793b6bcf460eacca28/packages/node_modules/%40node-red/nodes/core/network/31-tcpin.js#L437-L512)
```js
        else {
            const connectedSockets = new Set(); // << changed
            node.status({text:RED._("tcpin.status.connections",{count:0})});
            let srv = net;
            let connOpts;
            if (n.tls) {
                srv = tls;
                connOpts = tlsNode.addTLSOptions({});
            }
            var server = srv.createServer(connOpts, function (socket) {
                socket.setKeepAlive(true,120000);
                if (socketTimeout !== null) { socket.setTimeout(socketTimeout); }
                node.log(RED._("tcpin.status.connection-from",{host:socket.remoteAddress, port:socket.remotePort}));
                socket.on('timeout', function() {
                    node.log(RED._("tcpin.errors.timeout",{port:node.port}));
                    socket.end();
                });
                socket.on('data', function(d) {
                    // console.log("DATA",d)
                });
                socket.on('close',function() {
                    node.log(RED._("tcpin.status.connection-closed",{host:socket.remoteAddress, port:socket.remotePort}));
                    connectedSockets.delete(socket); // << changed
                    node.status({text:RED._("tcpin.status.connections",{count:connectedSockets.size})});
                });
                socket.on('error',function() {
                    node.log(RED._("tcpin.errors.socket-error",{host:socket.remoteAddress, port:socket.remotePort}));
                    connectedSockets.delete(socket); // << changed
                    node.status({text:RED._("tcpin.status.connections",{count:connectedSockets.size})});
                });
                connectedSockets.add(socket); // << changed
                node.status({text:RED._("tcpin.status.connections",{count:connectedSockets.size})});
            });

            node.on("input", function(msg, nodeSend, nodeDone) {
                if (msg.payload != null) {
                    var buffer;
                    if (Buffer.isBuffer(msg.payload)) {
                        buffer = msg.payload;
                    } else if (typeof msg.payload === "string" && node.base64) {
                        buffer = Buffer.from(msg.payload,'base64');
                    } else {
                        buffer = Buffer.from(""+msg.payload);
                    }
                    // changed ...
                    connectedSockets.forEach(soc => {
                        if (node.doend === true) { soc.end(buffer); }
                        else { soc.write(buffer); }
                    })
                }
                nodeDone();
            });

            server.on('error', function(err) {
                if (err) {
                    node.error(RED._("tcpin.errors.cannot-listen",{port:node.port,error:err.toString()}));
                }
            });

            server.listen(node.port, function(err) {
                if (err) {
                    node.error(RED._("tcpin.errors.cannot-listen",{port:node.port,error:err.toString()}));
                } else {
                    node.log(RED._("tcpin.status.listening-port",{port:node.port}));
                    node.on('close', function() {
                        // changed ...
                        connectedSockets.forEach(soc => {
                            soc.end();
                            soc.unref();
                        })
                        server.close();
                        node.log(RED._("tcpin.status.stopped-listening",{port:node.port}));
                    });
                }
            });
        }
```

**Comment by b10up** [comment]
Thank you, this last test code is working well, i cannot reproduce the bug with this.

**Comment by Steve-Mcl** [comment]
Thanks for that. 

Can I ask you to keep an eye on it for 24h and I will raise a PR to get this fixed?

Feedback success or failure please.

**Comment by b10up** [comment]
Of course, i'll keep using this and report tomorrow.

Thanks for your help!

**Comment by b10up** [comment]
Tested it all day long with random manual kills, it is working like a charm now.
Thanks again!
