### ISSUE TITLE
Bug: Cut-paste a link-in node resets link-call nodes

### ISSUE THREAD

**Issue by alexk111** [node-red/node-red#3629]
### Current Behavior

When I cut & paste a `link-in` node targeted by `link-call` nodes, the latter lose the targets (due to the link-in node id change?)

### Expected Behavior

`Link-call` nodes should auto-update the target `link-in` node with the new instance.

### Steps To Reproduce

1. Add `link-in` node
2. Add `link-call` node and set the `link-in` node as its target
3. Cut the `link-in` and paste it

### Environment

- Node-RED version: 3.0.0-beta.2

**Comment by knolleary** [comment]
This is a slightly tricky one to get right - we can't always know what the user intends when it comes to side-effects like this.

If you *copy* then paste the `link-in` node, you have made a copy so you would *not* expect `link-call` nodes to be updated.

In the code, the `paste` action doesn't know if the clipboard came from a copy or a cut - so doesn't currently do anything differently.

We'd want to look at other nodes that have similar relationships - Catch/Complete/Status/Link etc.
