### ISSUE TITLE
Deleting a node then performing undo does not return link

### ISSUE THREAD

**Issue by My-Random-Thoughts** [node-red/node-red#3634]
### Current Behavior

When two nodes are joined by a link and one is deleted then brought back with an undo action, the link wire is not returned.
This does not happen in v3-beta

### Expected Behavior

The link wire should return also

### Steps To Reproduce

Have a flow with two any nodes joined with a link wire.
Delete one of the nodes
Perform an undo action (CTRL+Z, etc)

You will see the deleted node returns, but not the link

### Example flow

Not required

### Environment

Node-RED version: 3.0.0 b2 (also happens in v2.2.2 so not a newly created bug)
Node.js version: 18.1
npm version: 8.8.0
Platform/OS: Linux 5.13.0-41-generic x86_64
Browser: Firefox 100

**Comment by Steve-Mcl** [comment]
> This does not happen in v3-beta

> Node-RED version: 3.0.0 b2 (also happens in v2.2.2 so not a newly created bug) 

These 2 statements are contradictory 🤔 

Any how, this is fixed in SRC and will be present in V3 ([Link to PR that fixed this](https://github.com/node-red/node-red/pull/3547)) and is tagged for backport to v2.x

Thank you for raising the issue.
