### ISSUE TITLE
Node disappeared on workspace after specific operations

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#3639]
### Current Behavior

After users did specific operations on the flow editor, it doesn't draw the node rectangle correctly as in the following video.

![cap](https://user-images.githubusercontent.com/20310935/172628297-5057cb72-8234-40af-93f9-b0152db65898.gif)

It lost the width and height information of the `<rect>` which shows the node rectangle. But I was not able to fix the bug.

### Expected Behavior

The flow editor shows the node correctly.

### Steps To Reproduce

1. Add a new tab
2. Drag a node to the other area of the workspace (For example, tab)
3. Click another tab
4. Return to the previous tab

### Environment

- Node-RED version: 2.2.2 and 3.0.0-beta.2
- Node.js version: 18.0.0
- npm version: 8.6.0
- Platform/OS: Ubuntu 20.04 on WSL2/ Windows 11
- Browser: Google Chrome 102.0.5005.63 (Official Build) (64 bit)

**Comment by Steve-Mcl** [comment]
I can verify the issue in 2.x and 3.x



1. Drag any node to an area outside of workspace (e.g. hovering over a tab) and release (or hold) mouse button
2. Move mouse to another TAB & click to select it.

_To get back to normal, click anywhere in grid workspace then switch tab_

![chrome_T1CjXz5Pfa](https://user-images.githubusercontent.com/44235289/172822518-5f3cbfb9-60f1-4f90-8c01-10ada00a6e27.gif)

**Comment by kazuhitoyokoi** [comment]
Thank you for your trying this. I remember that there was the issue before v1.0.

**Comment by knolleary** [comment]
Fixed via #3643
