### ISSUE TITLE
If a custom property with a default value is added to a node properties' defaults object, the node that is already on a flow will output a wrong value for that property.

### ISSUE THREAD

**Issue by JohnEvansSolachuk** [node-red/node-red#3640]
### Current Behavior

When I add a new property in the `default` object of a node's properties and set it to `true` by default, it will show `false` when the new property of a node that already exists on a flow is checked. This issue doesn't happen if that node is taken fresh from the palette instead.

### Expected Behavior

When I add a new property in the `default` object of a node's properties and set it to `true` by default, it should also be `true` for that node(s)'s that already exists on a flow.

### Steps To Reproduce

1. Create a custom node and use `.registerType` to register it in code.
2. Start node-red.
3. Add the custom node to a flow.
4. Stop node-red.
5. Modify the code to add a custom property with value set to `true` to the` defaults` object of the node's properties e.g. `defaults: { customProp: {value: true} }`.
6. Start node-red.
7. Export the flow, or make the custom node output its custom property's value.
8. Custom property's value shows `false` instead of expected `true`.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.0.6
- Node.js version: 14.17.2
- npm version: 6.14.13
- Platform/OS: Windows
- Browser: Chrome

**Comment by Steve-Mcl** [comment]
The flow file is not modified just because to modified the custom node. You would have to handle any in-place upgrades in `oneditprepare`. This is normal behaviour as far as I can see.

**Comment by JohnEvansSolachuk** [comment]
@Steve-Mcl Do you mind to provide some hints on how to do that in `oneditprepare`? I'm thinking maybe I could access the custom property in the `config` object there, but I'm not sure how to get the `config` object.
