### ISSUE TITLE
Create sponsoring and contribution layers for the Node-RED project

### ISSUE THREAD

**Issue by orwa84** [node-red/node-red#3667]
### Current Behavior

I cannot sponsor @knolleary if I wanted to on GitHub (GitHub Sponsor) and the project has no Open Collective (https://opencollective.com/).

### Expected Behavior

I would like myself and others to be able to reciprocate to this project.

### Steps To Reproduce

Stop it.

### Example flow

`💰!= 🤗 ` ... but it is still needed

### Environment

- Node-RED version: NA
- Node.js version: NA
- npm version: NA
- Platform/OS: NA
- Browser: NA

**Comment by knolleary** [comment]
Thanks for the interest in supporting the project. As you note, we don't have an OpenCollective, and it's up to individuals whether they use GH Sponsors or not - something I have chosen not to use.

I appreciate the intent of the issue, but I'm going to close it off.

**Comment by odiraneyya** [comment]
NodeRED had been an instrumental tool in my teaching for the last 3 years. It had created plenty of Aha moments for my students. What gets you going and how can I express my gratitude to the project you started.

I can show up at your door with flowers 🌹 But there's no guarantee it would be something you'd appreciate.
