### ISSUE TITLE
v3 Beta file node typed input defaults to msg. rather than string type

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#3668]
### Current Behavior

from - https://discourse.nodered.org/t/node-red-3-0-0-beta-2-released/62698/85?u=dceejay

The v3beta2 latest file node(s) have now moved to a have the filename as a typed input (Good).
BUT they currently default to `msg.filename`  . I think this is much less intuitive for a naive user who would expect to enter a string filename by default.... once they are "more expert" and ask - how can I pass in a filename then they could discover the dropdown to set msg.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/5375409/173616192-ff17354b-b16f-4e12-9c67-71ceef07846c.png">

### Expected Behavior

I think the default should be string type (maybe with the icon replaced by the word **file** or something really obvious ) - and if the name is indeed left blank it should default to the old behaviour of looking for msg.filename under the covers. 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/5375409/173616273-bb1d5282-b270-4974-a2a9-5f8a40bd0484.png">

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:  v3 Beta 2
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
I would hesitate to use `filename` again as the label - perhaps `path` would be benefit from being shorter and using less space.

**Comment by dceejay** [comment]
Or maybe an icon of a file to save i18n. But not the az icon

**Comment by Steve-Mcl** [comment]
@dceejay @knolleary 

Please spare 1 minute to watch the below GIF and cast your vote :) 

![file-node-typed-input](https://user-images.githubusercontent.com/44235289/174021598-c96dea03-d6ee-4e4a-a98e-c7f307db14aa.gif)

NOTES:
* No fixed text anywhere (uses existing i18n where text is shown)
* Option 1 - no text (icons only)
* Option 2 - text always visible
* Option 3 - text in drop down only (icon only when drop down is not hidden)
* Option 4 (your alternative suggestion :) )

**Comment by dceejay** [comment]
Either 1 or 4 (maybe try "path" as Nick suggested)

**Comment by Steve-Mcl** [comment]
ok, Option 4 incoming 👍

**Comment by Steve-Mcl** [comment]
@dceejay why is are you and Nick always right dammit 🤣 

![image](https://user-images.githubusercontent.com/44235289/174051513-34d05996-8be7-4f0a-bdc0-17ea0c7de30a.png)

Does look better!

**Comment by knolleary** [comment]
make it so
