### ISSUE TITLE
Can't add spaces to a string in the visual editor

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3682]
### Current Behavior

As mentioned in this video, it is not possible to add spaces to a string when using the visual editor.

https://youtu.be/wBUAUdLkYJM?t=526

I don't know exactly which version of Node-RED he is running. I'm assuming it's 2.2.2 because he's using the Node-RED add-on for Home Assistant.

I just tested it on beta 3 and noticed the same behavior.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Confirmed in V3 also...

![image](https://user-images.githubusercontent.com/44235289/174150846-cb2c25d1-a7d5-4af6-824e-deb6088aada5.png)
