### ISSUE TITLE
Glitch in context menus

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3683]
### Current Behavior

As shown in https://discourse.nodered.org/t/node-red-3-0-0-beta-3-released/64027/23 and https://discourse.nodered.org/t/node-red-3-0-0-beta-3-released/64027/24, there's a glitch in the context menus.

![2385a30aa56fbe41c4804f4d2eb100e1d05064d7](https://user-images.githubusercontent.com/29807944/174155842-99dbb979-c935-48ab-8178-0c5f0a513e4c.jpeg)

![73673b571b270f71adeef33dd3f9de7f0a5a2eed](https://user-images.githubusercontent.com/29807944/174155872-e7b3352f-f6b5-42d2-a1b8-b6f2e1fb959f.png)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.0-beta.3
- Node.js version: v16.15.1
- npm version: 8.11.0
- Platform/OS: macOS
- Browser: Chrome, Safari, and Firefox

**Comment by knolleary** [comment]
The changes introduced by #3678 modified the menu CSS to support submenus that pull to the right.

Those changes have broken these menus.
