### ISSUE TITLE
Undoing a newly added node keeps the workspace dirty

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3701]
### Current Behavior

If you add a node (dragging from the palette or using the quick add dialog) and press ctrl-z, that node will be removed, but the workspace will remain marked as dirty.

### Environment

- Node-RED version: 3.0.0-beta.3
- Node.js version: v16.15.1
- npm version: 8.11.0
- Platform/OS: macOS
- Browser: Chrome

**Comment by bonanitech** [comment]
I just noticed it doesn't happen with all types of nodes.

I tested with all nodes from common and function categories, and the issue happened with the following nodes:

- debug
- link in
- link out
- function

**Comment by Steve-Mcl** [comment]
That is a good clue. Possibly linked to auto naming. Thanks Mauricio
