### ISSUE TITLE
[List x hidden flows] option not working correctly

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [node-red/node-red#3707]
### Current Behavior

The 'List x Hidden Flows' options is not showing correct details, for a combination of flows and sub-flows in node-red.
This error can be reproduced in latest version of node-red i.e. 2.2.2

### Expected Behavior

The 'List x Hidden Flows' should either exclude count of Subflows or otherwise should list closed Subflows.

### Steps To Reproduce

1. Create a flow, say 'Flow 1'
2. Create a sub-flow, say 'Subflow 1'
3. hide 'Flow 1'
4. Open 'Subflow 1' and then close it.
5. The 'List 2 Hidden Flows' will be shown in the menu.
6. On Clicking the option, only 1 hidden flow will be visible.
7. On Clicking 'Show all flows', only Flow 1 will open.
8. Subsequently, 'List 1 Hidden Flow' will be shown in the menu.
9. Refresh the node-red window and the option 'List x Hidden Flow' will not be visible anymore.
10. This problem goes bigger, if more Subflows are added to the project/flow file.

### Environment

- Node-RED version: 2.2.2
- Node.js version: 16.15.0
- npm version: 8.8.0
- Platform/OS: Windows 10
- Browser: Chrome

**Comment by ralphwetzel** [comment]
I noticed this effect as well in 3.0-beta.

**Comment by Steve-Mcl** [comment]
I can confirm issue exists in V2.x and V3.x-beta.x
