### ISSUE TITLE
After installing most current Node-RED version on must current Debian 11.x with NodeJS LTS 16.x i just got error

### ISSUE THREAD

**Issue by jayjupdhig** [node-red/node-red#3712]
### Current Behavior

After

systemctl enable node-red.service
AND
systemctl start node-red.service
AND
systemctl status node-red.service

i get the error that the screenshot shows.

### Expected Behavior

No errors

### Steps To Reproduce

Install NodeJS 16.x on Debian 11 like that:  https://www.linuxcapable.com/how-to-install-node-js-14-lts-16-npm-on-debian-11-bullseye/

Enter npm install -g --unsafe-perm node-red

systemctl enable node-red.service
AND
systemctl start node-red.service
AND
systemctl status node-red.service

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v2.2.2
- Node.js version:  v16.15.1
- npm version: 8.11.0 
- Platform/OS: Debian 11 most current on 2022-06-27
- Browser: Most current chrome

**Comment by jayjupdhig** [comment]
Where can i get a service unit file that works!?

**Comment by knolleary** [comment]
There is no screenshot so we don't know what error you are hitting.

To install on a Debian based system, you can use the install script we provide that includes the service file:

https://nodered.org/docs/getting-started/raspberrypi

**Comment by jayjupdhig** [comment]
same issue as before:

`root@debian-influx:~# sudo systemctl enable nodered.service
Created symlink /etc/systemd/system/multi-user.target.wants/nodered.service → /lib/systemd/system/nodered.service.
root@debian-influx:~# sudo systemctl disable nodered.service
Removed /etc/systemd/system/multi-user.target.wants/nodered.service.
root@debian-influx:~#
root@debian-influx:~#
root@debian-influx:~# systemctl status node-red
● node-red.service
     Loaded: not-found (Reason: Unit node-red.service not found.)
     Active: failed (Result: exit-code) since Mon 2022-06-27 16:50:18 CEST; 10min ago
   Main PID: 742 (code=exited, status=203/EXEC)
        CPU: 763us

Jun 27 16:50:18 debian-influx systemd[1]: node-red.service: Scheduled restart job, restart counter is at 5.
Jun 27 16:50:18 debian-influx systemd[1]: Stopped Node-RED is a tool for wiring together hardware devices, APIs and online services in new and interesting ways..
Jun 27 16:50:18 debian-influx systemd[1]: node-red.service: Start request repeated too quickly.
Jun 27 16:50:18 debian-influx systemd[1]: node-red.service: Failed with result 'exit-code'.
Jun 27 16:50:18 debian-influx systemd[1]: Failed to start Node-RED is a tool for wiring together hardware devices, APIs and online services in new and interesting ways..
root@debian-influx:~#`

**Comment by jayjupdhig** [comment]
Maybe incompatioble to NodeJS v16?!?

**Comment by jayjupdhig** [comment]
I was never able to start the service, always erros with "status", but in background the port 1880 was binded - makes no sense, but after a restart it works.

**Comment by jayjupdhig** [comment]
thx!! :-)
