### ISSUE TITLE
Issue with dialog offset when Right clicking --> Insert --> Node (v3.0.0-beta.4)

### ISSUE THREAD

**Issue by unborn-andy** [node-red/node-red#3725]
### Current Behavior

There was the PR for fixing the Ctrl+click quick-add of a node
[Include scroll offset when positioning quick-add dialog #3685](https://github.com/node-red/node-red/pull/3685)

but it seems there is also an issue with the offset when Right clicking --> Insert --> Node
when the flow is scrolled a bit down .. the dialog doesnt show at the place of right-clicking .. 
I notice that it shows a part of the dialog further up the flow but not a complete dialog box  .. let me do a screengrab

https://user-images.githubusercontent.com/93290787/176779985-848706aa-a9b5-4e4d-a495-acae456fc4aa.MP4

  

### Expected Behavior

To show the quick-add dialog in the right place

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v3.0.0-beta.4
- Node.js version: v16.14.0
- npm version:
- Platform/OS: Windows 11
- Browser: Firefox / Chrome

**Comment by knolleary** [comment]
Fixed by #3727
