### ISSUE TITLE
Unexpected error when trying to change, create or delete key on flow_cred in project settings

### ISSUE THREAD

**Issue by gilmiz** [node-red/node-red#3726]
### Current Behavior

Change, create or delete operations on the credentials key in the Project Settings>Settings>Files>Credentials results in an 'Unexpected error' message.
<img width="256" alt="Firefox_Screenshot_2022-07-01T06-37-57 563Z" src="https://user-images.githubusercontent.com/16917848/176849445-0101132d-4852-4d35-924b-987058fd6452.png">
 

### Expected Behavior

I would expect that keys can be crated, changed erased, or a clear error message with why this is not possible.

### Steps To Reproduce

![nodered-cred-error](https://user-images.githubusercontent.com/16917848/176854249-65d7afcb-6bff-4740-953c-269bdf374d83.gif)

### Example flow

```
paste your flow here
```
N/A

### Environment

- Node-RED version: 3.0 Beta 4
- Node.js version: 16.14
- npm version: 8.13.2
- Platform/OS: Debian 11
- Browser: Firefox

**Comment by knolleary** [comment]
Are there any errors in the node-red runtime log?

**Comment by gilmiz** [comment]
The terminal output is below (via pm2 monit):
node-red-1880 > 1 Jul 11:24:47 - [info] Setting active project : test6 
node-red-1880 > 1 Jul 11:24:47 - [info] Flows file  : /sw/current/node-red/projects
node-red-1880 > 1 Jul 11:24:47 - [info] Stopping flows
node-red-1880 > 1 Jul 11:24:47 - [info] Stopped flows
node-red-1880 > 1 Jul 11:24:47 - [warn] Using unencrypted credentials
node-red-1880 > 1 Jul 11:24:47 - [info] Starting flows
node-red-1880 > 1 Jul 11:24:47 - [info] Started flows
node-red-1880 > 1 Jul 11:25:25 - [error] Error 

The last line [error] comes when trying to save the credentials key

**Comment by gilmiz** [comment]
I tried again, both clean installation as well as installation on top of beta.3, with PM2 and directly from terminal - I cannot re-create the problem.

**Comment by Steve-Mcl** [comment]
I think we can close this for now & reopen it if you manage to recreate it?

**Comment by gilmiz** [comment]
Her is the terminal output:

node-red-1880 > 1 Jul 11:24:47 - [info] Setting active project : test6

node-red-1880 > 1 Jul 11:24:47 - [info] Flows file  :
/sw/current/node-red/projects

node-red-1880 > 1 Jul 11:24:47 - [info] Stopping flows

node-red-1880 > 1 Jul 11:24:47 - [info] Stopped flows

node-red-1880 > 1 Jul 11:24:47 - [warn] Using unencrypted credentials

node-red-1880 > 1 Jul 11:24:47 - [info] Starting flows

node-red-1880 > 1 Jul 11:24:47 - [info] Started flows

node-red-1880 > 1 Jul 11:25:25 - [error] Error


Started via mp2


/Gilad
