### ISSUE TITLE
Custom theme build script not generating all the CSS

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#3738]
### Current Behavior

It took me a while to realize that the issue was in the script and not on my files.

When running the command below to generate the CSS for a custom theme, I noticed that not all the CSS variables were in the `cobalt2.min.css` file.

	node node-red/scripts/build-custom-theme.js --in themes/cobalt2/cobalt2.scss --out themes/cobalt2/cobalt2.min.css

Since the variables below don't match any of the rules in [this part](https://github.com/node-red/node-red/blob/master/scripts/build-custom-theme.js#L97-L112) of the script, they end up in the nonColors array. Therefore, they don't get saved to the output file.

```
$primary-font
$primary-font-size
$monospace-font
$shadow
$diff-state-added
$diff-state-deleted
$diff-state-changed
$diff-state-unchanged
$diff-state-conflicted
$diff-state-moved
$diff-state-conflict
$menuBackground
$menuDivider
$menuColor
$menuActiveColor
$menuActiveBackground
$menuDisabledColor
$menuHoverColor
$menuHoverBackground
$menuCaret
$header-menu-item-hover
$headerMenuItemDivider
$headerMenuCaret
$vcCommitShaColor
```

~This issue is also present in v2.x.~
EDIT: I was wrong. It seems to affect only the creation of the CSS variables.

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by bonanitech** [comment]
In case v1.x is still maintained, the issue is also present there.

**Comment by dceejay** [comment]
sorry - didn't spot it against flowforge. Assumed it had gone into 3.0
