### ISSUE TITLE
After upgrade to HA 2022.7.0, Node-Red disconnects

### ISSUE THREAD

**Issue by ThomasPrior** [node-red/node-red#3753]
### Current Behavior

Behavior with HomeAssistant 2022.7.0 or later:

HomeAssistant starts
NodeRed connects
After a short period of time, the following lines are displayed in the log:

```11 Jul 14:04:39 - [debug] [api-call-service:Turn Off Light Seg1] Calling Service: light:turn_off -- {"entity_id":"light.tom_meeting_lights"}
11 Jul 14:04:39 - [debug] [api-call-service:Turn On Working Lights Seg0] Calling Service: light:turn_on -- {"entity_id":"light.hannah_meeting_lights","effect":"Solid","brightness":"100","color_name":"green"}
11 Jul 14:04:52 - [debug] [api-call-service:Turn On Meeting Lights Seg1] Calling Service: light:turn_on -- {"entity_id":"light.tom_meeting_lights","effect":"Solid","brightness":"25","color_name":"blue"}
11 Jul 14:04:54 - [debug] [api-call-service:Turn Off Light Seg1] Calling Service: light:turn_off -- {"entity_id":"light.tom_meeting_lights"}
11 Jul 14:05:08 - [debug] [inject:4AM] repeat = 3600000
11 Jul 14:05:08 - [debug] [api-call-service:ecce1285.45fd9] Calling Service: shell_command:google_token -- {}
Received event for unknown subscription 18. Unsubscribing.
Received event for unknown subscription 9. Unsubscribing.
```

No further state changes are passed from HomeAssistant to Node-Red

Issue is not present before HomeAssistant 2022.7 and I'm aware that this is likely an issue I need to raise on that project, however I can't work out what flows or subscriptions are causing the issue. Any pointers in the right direction would be appreciated.

### Expected Behavior

HA starts
NodeRed connects
State changes are passed from HomeAssistant to Node-Red

### Steps To Reproduce

Start Node-Red container or restart flows

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.2.2
- Node.js version: 14.18.2
- npm version: 6.14.15
- Platform/OS: Docker (nodered/node-red:latest)
- Browser: Chrome 103.0.5060.114 (Official Build) (64-bit)
- Docker network: host

**Comment by hardillb** [comment]
You will need to raise this with the HA plugin folks, there is nothing here that points to it being a problem with core Node-RED and the core Node-RED team don't use HA so are unlikely to be able to help you debug flows/nodes that interact with it.

**Comment by ThomasPrior** [comment]
My apologies. Thanks for your response.
