### ISSUE TITLE
Right-click menu not showing disabled entries when using non-default theme

### ISSUE THREAD

**Issue by My-Random-Thoughts** [node-red/node-red#3761]
### Current Behavior

When using the "solarized-light" theme, it's impossible to distinguish between disabled items on the right click menu.

Default Theme:
![default](https://user-images.githubusercontent.com/21334396/178331332-3813372f-6b7a-46a5-a4ee-c27544e96e40.png)

Solarized-Light
![solarized-light](https://user-images.githubusercontent.com/21334396/178331334-143711d5-3673-4f37-a250-0069d6db70ae.png)

### Expected Behavior

Theme should not matter to display items disabled

### Example flow

N/A

### Environment

- Node-RED version: 3.0.0-beta.4
- Node.js version: v18.4.0
- npm version: 8.12.1
- Platform/OS: Linux 5.13.0-52-generic x86_64
- Browser: Firefox 102

**Comment by knolleary** [comment]
This will be an issue with the theme. It will need to be updated to include the appropriate style to indicate disabled items.

**Comment by bonanitech** [comment]
I just released version 3.0.0-beta.2 of the theme collection. It includes updates that fix this issue.

@My-Random-Thoughts, please give it a try

```shell
npm install @node-red-contrib-themes/theme-collection@next
```

If you encounter any issues, please file a bug report in the [theme collection repository](https://github.com/node-red-contrib-themes/theme-collection).

**Comment by My-Random-Thoughts** [comment]
Much better, thank you very much @bonanitech 

![newVersion](https://user-images.githubusercontent.com/21334396/178728923-b8f5257b-2de1-4cdb-9696-80f079b5eaf3.png)
