### ISSUE TITLE
Mode is now a required option for createEditor in 3.0 or a TypeError is thrown

### ISSUE THREAD

**Issue by zachowj** [node-red/node-red#3774]
### Current Behavior

If `mode` is undefined in the options object for `createEditor` it will default to text. This now throws an error in 3.0.
```
TypeError: Cannot read properties of undefined (reading 'split')
```
https://github.com/node-red/node-red/blob/1b94cc3ac027bfc38a300867a0b0fd635bf273b8/packages/node_modules/%40node-red/editor-client/src/js/ui/editors/code-editors/monaco.js#L736-L740

This error occurs with both editors. As both `mode` and `title` could be undefined.

https://github.com/node-red/node-red/blob/1b94cc3ac027bfc38a300867a0b0fd635bf273b8/packages/node_modules/%40node-red/editor-client/src/js/ui/editors/code-editors/monaco.js#L767

https://github.com/node-red/node-red/blob/1b94cc3ac027bfc38a300867a0b0fd635bf273b8/packages/node_modules/%40node-red/editor-client/src/js/ui/editors/code-editors/ace.js#L84

If `mode` is now a required option property. Maybe a check and a nice error message are needed.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0
- Node.js version: 16
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
> If mode is undefined in the options object for createEditor it will default to text. This now throws an error in 3.0.
> 
> TypeError: Cannot read properties of undefined (reading 'split')
> ```js
>  if (mode) { 
>      mode = mode.replace("ace/mode/", ""); 
>  } else { 
>      mode = "text"; 
>  }
> ```

This is a bit confusing. If you dont provide `mode` then it will default to `"text"` as per the snippet you highlighted?



<br>

> If mode is now a required option property. Maybe a check and a nice error message are needed.

That was was not the intention - we just need to better handle this. I suggest we generate sane defaults for the options object to ensure `options` is an object and `options.mode` has a value.

**Comment by zachowj** [comment]
> This is a bit confusing. If you dont provide `mode` then it will default to `"text"` as per the snippet you highlighted?

I was just trying to point out that `mode` was not required before 3.0.
