### ISSUE TITLE
Function editor now validating JS as typescript but doesn't allow type annotations

### ISSUE THREAD

**Issue by carlos-sarmiento** [node-red/node-red#3775]
### Current Behavior

After upgrading to Node-Red 3 I enabled the Monaco editor and now get typing information for the code. The issue I have is that the typescript compiler monaco seems to be using behind the scenes is making the wrong inferences on type, but it does not accept any type annotations to try to correct the problem. This forces me to use ignore directives which ends up being a nuisance.

### Expected Behavior

Either the editor does not do JS validation using the typescript compiler or it allows the right type annotations into code

### Steps To Reproduce

Put this on a function node in Node-Red 3:
```
// TS will complain about this with a  "Type annotations can only be used in TypeScript files. (8010)"
let someNumber : number = 2;

// Problem shows up when trying to do things like this, which is perfectly valid JS
let someArray = [["A",2],["B",3];
let sum = 0;

for (var i = 0; i < someArray.length; i++) {
    sum += someArray[i]; // Error: Operator '+=' cannot be applied to types 'number' and 'string | number'.(2365)
}
```

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3 using Latest docker container
- Browser: Chrome

**Comment by Steve-Mcl** [comment]
Hi @carlos-sarmiento - i will try to answer your issues...


>  is making the wrong inferences on type, but it does not accept any type annotations to try to correct the problem.

Can you provide some examples? It seems to be working fine for me...

![chrome_SFB7zMjxr6](https://user-images.githubusercontent.com/44235289/179347585-6035cce2-37bb-4f81-a861-6556675c759b.gif)

<br>


> // TS will complain about this with a  "Type annotations can only be used in TypeScript files. (8010)"
> `let someNumber : number = 2;`

And rightly so since type decoration is TypeScript not JavaScript

If you want to be explicit with type annotations in JavaScript + monaco, you can use **JSDoc** style annotations...
![image](https://user-images.githubusercontent.com/44235289/179345002-47635aef-ad6e-467d-a292-599cb05c6112.png)

<br>

> // Problem shows up when trying to do things like this, which is perfectly valid JS
> ```
> let someArray = [["A",2],["B",3];
> let sum = 0;
> 
> for (var i = 0; i < someArray.length; i++) {
>     sum += someArray[i]; // Error: Operator '+=' cannot be applied to types 'number' and 'string | number'.(2365)
> }
> ```

While what you have written here ↑ works (results in `"0A,2B,3"`) it is not _ideal_ code but if that is what you want, you have a few choices...

1. be more explicit with intent in your code
    1.  e.g. use `.toString()` or `.join()`
    ```
        // Problem shows up when trying to do things like this, which is perfectly valid JS
        let someArray = [["A", 2], ["B", 3]];
        let sum = 0;
        for (let i = 0; i < someArray.length; i++) {
            // @ts-ignore
            sum += someArray[i]; // Error: Operator '+=' cannot be applied to types 'number' and 'string | number'.(2365)
        }


        let someArray2 = [["A",2],["B",3]];
        let sum2 = 0;
        for (let i = 0; i < someArray2.length; i++) {
            sum2 += someArray2[i].toString(); 
        }


        let someArray3 = [["A", 2], ["B", 3]]
        let sum3 = 0;
        for (let i = 0; i < someArray3.length; i++) {
            sum3 += someArray3[i].join(","); 
        }

        let someArray4 = [["A", 2], ["B", 3]]
        let sum4 = "0" + someArray4.map(e => e.toString()).join("")

        msg.payload = { sum, sum2, sum3, sum4 }

        return msg;
    ```
    ![image](https://user-images.githubusercontent.com/44235289/179346981-a2048e91-ef90-4801-bec7-9b8e2365aa8f.png)
3. ignore single lines
    1.  use `// @ts-ignore` ![chrome_F5TVyhf30y](https://user-images.githubusercontent.com/44235289/179347026-a8ef1322-496c-45c2-a02a-1e871cd8047e.gif)
4. Disable error checking number `2365` by adding it to `editorTheme.codeEditor.monaco.languages.typescript.javascriptDefaults.diagnosticsOptions.diagnosticCodesToIgnore[]` in the settings.js file ...
     ``` 
        codeEditor: {
            lib: "monaco", //can be "monaco" or "ace"
            options: {
                theme: "vs",
                fontSize: 14,
                fontLigatures: true,
                fontFamily: "Cascadia Code, Fira Code, Consolas, 'Courier New', monospace",
                fontWeight: "300",
                colorDecorators: true,
                dragAndDrop: true,
                linkedEditing: true,
                showFoldingControls: 'always',
                "bracketPairColorization.enabled": true,
            },
            monaco: {
                languages: {
                     typescript: {
                         javascriptDefaults: {
                             /** @see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.typescript.languageservicedefaults.html#setdiagnosticsoptions */
                             diagnosticsOptions: {
                                diagnosticCodesToIgnore:  [
                                    1108,  //return not inside function
                                    2304,  //Cannot find name 
                                    2307,  //Cannot find module 'xxx' or its corresponding type declarations 
                                    2322,  //Type 'unknown' is not assignable to type 'string'
                                    2339,  //property does not exist on 
                                    2365,  //Operator '+=' cannot be applied to types 'number' and '(string | number)[]'
                                    7043,  //i forget what this one is,
                                    80001, //Convert to ES6 module  
                                    80004, //JSDoc types may be moved to TypeScript types.
                                ]
                            }
                        },
                    }
                },
            },
        } 
    ```

**Comment by Steve-Mcl** [comment]
@carlos-sarmiento I will close this issue but if you believe there to be an issue, please feel free to re-open.
