### ISSUE TITLE
TCP Timeout Error - node-red-contrib-tplink

### ISSUE THREAD

**Issue by Jaddache** [node-red/node-red#3782]
### Current Behavior

I am using the "node-red-contrib-tplink" node to control some kasa smart devices.  The node stops responding regularly and the following error is reported.  I am raising the issue as requested in the error report.
********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: TCP Timeout after 1000ms
192.168.11.204:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/home/pi/.node-red/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Please report this issue, including the information logged above:
https://github.com/node-red/node-red/issues/
********************************************************************

### Expected Behavior

Continuous response from the kasa devices.

### Steps To Reproduce

Within my flows, this error happens daily.  

### Example flow

```
[
    {
        "id": "f79ddbd6.adfea8",
        "type": "kasa",
        "z": "f3e3af2d.25add",
        "name": "Power Indicating Lamp - KL130B",
        "device": "192.168.11.204",
        "interval": "10000",
        "eventInterval": "5000",
        "payload": "getInfo",
        "payloadType": "info",
        "debug": false,
        "x": 540,
        "y": 180,
        "wires": [
            [
                "cd97f7a5.3e2078",
                "67366ad7ce20302e"
            ]
        ]
    },
    {
        "id": "cd97f7a5.3e2078",
        "type": "debug",
        "z": "f3e3af2d.25add",
        "name": "KL130 Return Message",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 870,
        "y": 180,
        "wires": []
    },
    {
        "id": "ef38489e.e4e6f8",
        "type": "inject",
        "z": "f3e3af2d.25add",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "getInfo",
        "payloadType": "str",
        "x": 490,
        "y": 60,
        "wires": [
            [
                "f79ddbd6.adfea8"
            ]
        ]
    }
]
```

### Environment

- Node-RED version: 3.0.0
- Node.js version: 18.6.0
- npm version: 8.13.2
- Platform/OS: raspberry pi / debian
- Browser: chrome

**Comment by Steve-Mcl** [comment]
Hi @Jaddache this is a problem you should report on the `node-red-contrib-tplink` repo. 

As you can see, it has been raised several times: https://github.com/caseyjhol/node-red-contrib-tplink/issues?q=TCP+Timeout

The developer needs to catch the tcp error in its own code and if necessary, pass it on to node red via a call to `node.error(...)`.
