### ISSUE TITLE
When working with an env variable, notify that there is an error in the function 

### ISSUE THREAD

**Issue by temkagordin** [node-red/node-red#3792]
### Current Behavior

When working with an env variable, notify that there is an error in the function and notifies "When working with an env variable
<img width="760" alt="image" src="https://user-images.githubusercontent.com/12200392/180006565-b0cbd78d-f4c1-4435-8bbc-7f32b6cb0a72.png">
 notifies "Cannot redeclare block-scoped variable 'env'.".
<img width="545" alt="image" src="https://user-images.githubusercontent.com/12200392/180008312-cb88b318-376a-45c5-85e5-74ddbe4d7a7e.png">

And when click deploy, i have error message
<img width="520" alt="image" src="https://user-images.githubusercontent.com/12200392/180007990-f23cd3cd-f3ce-4d7f-bd15-39ee8b80d8c7.png">

### Expected Behavior

No errors, everything was ok in version 2.2.0

### Steps To Reproduce

Create function 
in function writing "let env = global.get('env');"
click done

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- 3.0.0
- Node.js version:
-  v 8
- npm version:
- 
- Platform/OS:Chrome
- Browser:Chrome

**Comment by knolleary** [comment]
The error is 100% correct. `env` is a predefined variable within the Function node and you cannot redefined `env`.

https://nodered.org/docs/user-guide/writing-functions#env

**Comment by Steve-Mcl** [comment]
env is a known (already declared) variable (declared under the hood) 

change it to something like `let _env` or `let environ`

> No errors, everything was ok in version 2.2.0

No, it was the same but now NR V3 uses monaco - it actually gets highlighted as an issue in your function code

**Comment by temkagordin** [comment]
I will have to rewrite a lot of code (

**Comment by DmitrySidorow** [comment]
> I will have to rewrite a lot of code (

you can edit flow json and replace all variables by one action

**Comment by Steve-Mcl** [comment]
> I will have to rewrite a lot of code (

In Monaco, you can highlight the word env, Press f2, 
Enter a new name, All instances will be replaced in that function node.

**Comment by knolleary** [comment]
@dceejay Monaco is smart enough to do the right thing when you ask it to rename a variable... It isn't plain search/replace of text.

**Comment by dceejay** [comment]
sweet - everyday a schoolday

**Comment by ewrayjohnson** [comment]
So there is still obsolete documentation that gives an example thats show how to declare env in a FUNCTION that apparently is now wrong.  When makig a sweeping change like this, please ensure all documentation is also updated.

https://flows.nodered.org/flow/8a13d11dfe80e279df83341e3e17bcc1
