### ISSUE TITLE
New "Junction" feature introduces accidental infinite loops

### ISSUE THREAD

**Issue by ahakobyan79** [node-red/node-red#3799]
### Current Behavior

Currently every connection containing Junction between nodes allows adding another connection, and as many as you want as long as the previous ones have at least 1 Junction added.
It also allows connecting junctions to each other from the same connection between the same nodes

Please see the screenshot here: https://i.imgur.com/wY5ITmd.png

### Expected Behavior

Node connections should be recognized and not allowed to be more than 1 between the same nodes.

### Steps To Reproduce

- Add 2 nodes to the flow
- connect them together
- add a junction on the connection
- move the junction a step or two away
- add another connection between the same nodes
- add junction to the second connection
- move the 2nd junction to a different place
- add 3rd connection between the same two nodes (and so on...)

this can be done as many times as wished.

### Example flow

[
    {
        "id": "8fec92caa4f869a2",
        "type": "function",
        "z": "f6f2187d.f17ca8",
        "name": "function 1",
        "func": "\n\nvar today = new Date();\n\nmsg.min = today.getMinutes();\nmsg.month = today.getMonth();\nmsg.hour = today.getHours();\nmsg.day = today.getDate();\nmsg.year = today.getFullYear();\nmsg.milisec = today.getMilliseconds();\nmsg.sec = today.getSeconds();\n\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 480,
        "y": 380,
        "wires": [
            []
        ]
    },
    {
        "id": "0dc86783b1da71e2",
        "type": "inject",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 160,
        "y": 380,
        "wires": [
            [
                "56a57af79ff095ef",
                "e2aa086d8bcbed9e"
            ]
        ]
    },
    {
        "id": "56a57af79ff095ef",
        "type": "junction",
        "z": "f6f2187d.f17ca8",
        "x": 320,
        "y": 260,
        "wires": [
            [
                "8fec92caa4f869a2",
                "7c1e80617dd200f1",
                "e2aa086d8bcbed9e"
            ]
        ]
    },
    {
        "id": "7c1e80617dd200f1",
        "type": "junction",
        "z": "f6f2187d.f17ca8",
        "x": 320,
        "y": 380,
        "wires": [
            [
                "e2aa086d8bcbed9e",
                "56a57af79ff095ef"
            ]
        ]
    },
    {
        "id": "e2aa086d8bcbed9e",
        "type": "junction",
        "z": "f6f2187d.f17ca8",
        "x": 320,
        "y": 500,
        "wires": [
            [
                "8fec92caa4f869a2",
                "7c1e80617dd200f1",
                "56a57af79ff095ef"
            ]
        ]
    }
]

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by dceejay** [comment]
You have always been able to do this with any other type of node, for example a function node. I don't see why this is more likely to occur just because of junctions being rendered differently.

**Comment by knolleary** [comment]
It is true to say these types of loops have always been possible with nodes:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/51083/182239040-8eae630b-cb3c-418b-bc5e-44556bb740f9.png">

A key difference is that those nodes can contain logic that break the loop as needed - whereas the junctions don't provide any way of doing that.

The lint tool does have a rule for detecting loops that does flag up Junction loops. But I do wonder if the editor could detect and prevent loops that just involve Junction nodes - as there is no valid reason for that to exist.

**Comment by knolleary** [comment]
Fixed via #4087 - will be in 3.1
