### ISSUE TITLE
Persistent MQTT Session not working as expected with Mosquitto

### ISSUE THREAD

**Issue by max-wa** [node-red/node-red#3838]
### Current Behavior

As mentioned in my [Node-RED forum post](https://discourse.nodered.org/t/persistent-client-with-mosquitto-not-working-as-intended/66278) i'm having issues getting persistent MQTT sessions to work with Mosquitto.

I have a MQTT broker node in Node-RED that is connecting to my Mosquitto broker. I'm using MQTT v5 and a selfsigned OpenSSL certificate that I don't check on my client.

The connection, birth message, last will, subscriptions and publishes all are working perfectly fine. Also i have disabled "Use clean start" and i have set a `session expiry` of 2592000 seconds (=30 days).

When i check my Mosquitto persistence file, the client is indeed stored in that file, but the `Session Expiry Interval` is set to 0 instead of 2592000. When i configure a mqtt.js-Client, set `clean: false` and give that client a `sessionExpiryInterval: 2592000`, that client is persisted correctly.

The problem with this is, that if my Raspberry Pi running Node-RED is getting disconnected for a time longer than the keep alive for whatever reason, all messages sent to my Node-RED are lost even though they are sent with `qos: 2`. I think the reason is, that Mosquitto deletes the session of the client, since its set to persist for 0 seconds.

### Expected Behavior

The expected behavior would be, that the client gets persisted in Mosquitto with the correct `Session Expiry Interval` of 2592000.

### Steps To Reproduce

Set up a Mosquitto broker. The important settings for reproduction of the issue should be the following:
```
persistence true
persistence_location /var/lib/mosquitto/
persistent_client_expiration 14d
autosave_interval 300

log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_type debug
log_type subscribe
log_type unsubscribe

listener 8883 0.0.0.0
require_certificate false
```

Now use my example flow and let Node-RED connect to Mosquitto. The node should subscribe just fine, everything works as expected and the birth message should be sent.

If you check the Mosquitto persistence file in the `persistence location` the client should be registered with `Session Expiry Interval: 0`, even tho it is set to 2592000 in Node-RED. Also you should see that the subscription of the client to that topic is also stored there, which is as expected.

Now open the Mosquitto log file with `tail -f` or similar.

Next you want to disconnect the Node-RED client from Mosquitto. Depending on how you disconnect you should see the last will or the disconnection message sent. Also there should be a `Client closed connection` and unsubscribes in the log file.

Now send a message with `qos: 2` to the Topic that Node-RED was subscribed to and reconnect Node-RED afterwards. You should see in the log file, that the client is getting subscribed to the topic again, but no message is sent. Also the debug node in Node-RED doesn't receive anything.

### Example flow

```
[
    {
        "id": "66665620ee0f942d",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "10e93a9230f786ee",
        "type": "mqtt in",
        "z": "66665620ee0f942d",
        "name": "Subscribe",
        "topic": "",
        "qos": "2",
        "datatype": "auto",
        "broker": "652b515d2702868a",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 1,
        "x": 680,
        "y": 480,
        "wires": [
            [
                "6077501aadbc3fd5"
            ]
        ]
    },
    {
        "id": "6ddf714390eb2e63",
        "type": "inject",
        "z": "66665620ee0f942d",
        "name": "inject",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": "0.1",
        "topic": "",
        "x": 370,
        "y": 480,
        "wires": [
            [
                "cc85799bd023dbb2"
            ]
        ]
    },
    {
        "id": "cc85799bd023dbb2",
        "type": "function",
        "z": "66665620ee0f942d",
        "name": "Set MQTT Topic",
        "func": "msg.action = \"subscribe\";\nmsg.topic = {topic:\"some/random/topic\", qos:2, nl:false, rap:true, rh:true};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 520,
        "y": 480,
        "wires": [
            [
                "10e93a9230f786ee"
            ]
        ]
    },
    {
        "id": "6077501aadbc3fd5",
        "type": "debug",
        "z": "66665620ee0f942d",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 830,
        "y": 480,
        "wires": []
    },
    {
        "id": "652b515d2702868a",
        "type": "mqtt-broker",
        "name": "",
        "broker": "",
        "port": "8883",
        "tls": "12e956d8a888d3bb",
        "clientid": "clientid",
        "autoConnect": true,
        "usetls": true,
        "protocolVersion": "5",
        "keepalive": "60",
        "cleansession": false,
        "birthTopic": "some/other/topic",
        "birthQos": "2",
        "birthRetain": "true",
        "birthPayload": "Client online",
        "birthMsg": {},
        "closeTopic": "some/other/topic",
        "closeQos": "2",
        "closeRetain": "true",
        "closePayload": "Client offline",
        "closeMsg": {},
        "willTopic": "some/other/topic",
        "willQos": "2",
        "willRetain": "true",
        "willPayload": "Client offline",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": "2592000",
        "credentials": {
            "user": "",
            "password": ""
        }
    },
    {
        "id": "12e956d8a888d3bb",
        "type": "tls-config",
        "name": "",
        "cert": "",
        "key": "",
        "ca": "",
        "certname": "",
        "keyname": "",
        "caname": "",
        "servername": "",
        "verifyservercert": false,
        "alpnprotocol": "",
        "credentials": {}
    }
]
```

### Environment

- Node-RED version: v2.2.3
- Node.js version: v14.19.1
- npm version: v6.14.16
- Platform/OS: Raspberry Pi -> Raspbian Lite 
- Browser: Google Chrome

**Comment by Steve-Mcl** [comment]
Hi @max-wa I beleive I have found the problem.  Below is a screenshot of the mosquitto.db before and after my (local) modifications...

![image](https://user-images.githubusercontent.com/44235289/184374645-9b016733-fa55-4dd0-bf53-afaa4ee5346e.png)


👆 can see the `Session expiry` has both a `time` and `interval` 

I have yet to work through your steps but it looks promising so far.

**Comment by max-wa** [comment]
Hi @Steve-Mcl awesome, I didn't expect an update that quick 😲 That looks really promising!

**Comment by Steve-Mcl** [comment]
@max-wa if you are in a position to do so, can I request that you apply this fix locally in your node-red?
Although this is working fine on my systems, some one else testing it would improve confidence and chances of being merged.
Also, it is very unlikely a 3.0.3 release will be made in the next 3 weeks.

### Instructions to patch your system...

1. locate node-red source directory (likely in your `npm global` directory)
2. locate the file `../packages/node_modules/@node-red/nodes/core/network/10-mqtt.js`
3. Open it in an editor and scroll to around line `476` 
4. overwrite the following lines
```js
            setIfHasProperty(opts, node, "cleansession", init);
            setIfHasProperty(opts, node, "sessionExpiry", init);
            setIfHasProperty(opts, node, "topicAliasMaximum", init);
            setIfHasProperty(opts, node, "maximumPacketSize", init);
            setIfHasProperty(opts, node, "receiveMaximum", init);
	@@ -484,6 +483,11 @@ module.exports = function(RED) {
            } else if (hasProperty(opts, "userProps")) {
                node.userProperties = opts.userProps;
            }
```

with these lines...
```js
            setIfHasProperty(opts, node, "cleansession", init);
            setIfHasProperty(opts, node, "topicAliasMaximum", init);
            setIfHasProperty(opts, node, "maximumPacketSize", init);
            setIfHasProperty(opts, node, "receiveMaximum", init);
	@@ -484,6 +483,11 @@ module.exports = function(RED) {
            } else if (hasProperty(opts, "userProps")) {
                node.userProperties = opts.userProps;
            }
            if (hasProperty(opts, "sessionExpiry")) {
                node.sessionExpiryInterval = opts.sessionExpiry;
            } else if (hasProperty(opts, "sessionExpiryInterval")) {
                node.sessionExpiryInterval = opts.sessionExpiryInterval
            }
```
5. Restart node-red
6. Re-do your tests


Let me know if that is unclear or if you need a hand.

Thanks for your support

**Comment by max-wa** [comment]
Hey Steve, thank you very much for your quick help! 

I've applied your fix locally and so far it's working perfectly. The client is stored correctly in the mosquitto.db and the missed messages are resent by the broker when the client reconnects. I'll do some more testing but I believe this solved the issue.

**Comment by Steve-Mcl** [comment]
Hi @max-wa - I assume your extended testing was satisfactory since you closed this?

Please let me know.

Also, please leave this issue open (I will close it when the fix is merged into the master branch.

**Comment by max-wa** [comment]
Hi @Steve-Mcl sorry, yeah I should have mentioned that my extended testing went without any problems. Everything is working as it is supposed to.
