### ISSUE TITLE
Unable to set property using setMessageProperty when parent is null

### ISSUE THREAD

**Issue by GerwinvBeek** [node-red/node-red#3839]
### Current Behavior

When using setMessageProperty(), you are unable to set properties when the parent property is null or undefined.
For example, when `msg.payload = {}`. You can set `msg.payload.test` using setMessageProperty no problem.

when `msg.payload = null`. You are unable to set the property.

### Expected Behavior

When the parent property is null or undefined the `createMissing` logic will create an empty object.

Proposed solution:
https://github.com/GerwinvBeek/node-red/commit/bb646698f69f206d5336930ac5b80a03633d0e97

(I can open a pr in case this is a accepted solution, didn't open it right away in case this was created like this on purpose)

### Steps To Reproduce

Set msg.payload to null/undefined, try to set a child property on msg.payload

### Example flow

```json
[{"id":"fad0babd9b5e0a5c","type":"function","z":"aa1a42b20cd3fbee","name":"","func":"this.RED.util.setMessageProperty(msg, \"payload.test\", \"test\");\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":560,"y":40,"wires":[["b747ef5d6566e8e1"]]},{"id":"212fb40e35d2d5de","type":"inject","z":"aa1a42b20cd3fbee","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":190,"y":40,"wires":[["19cd04612557a8a2"]]},{"id":"b747ef5d6566e8e1","type":"debug","z":"aa1a42b20cd3fbee","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":730,"y":40,"wires":[]},{"id":"19cd04612557a8a2","type":"function","z":"aa1a42b20cd3fbee","name":"","func":"msg.payload = undefined;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":40,"wires":[["fad0babd9b5e0a5c"]]}]
```

### Environment

- Node-RED version: 3.0.0.beta-2
- Node.js version: 16.14.0
- npm version: 7.11.1
- Platform/OS: Windows 10
- Browser: Chrome

**Comment by knolleary** [comment]
This is not a bug. It is the behaviour we've had since very early days of Node-RED.

So we can't just treat this as a bug fix. We need to consider what impact this will have if we were to change the behaviour - and whether we want to.
