### ISSUE TITLE
Delay node progate control message

### ISSUE THREAD

**Issue by ghedolo** [node-red/node-red#3846]
I have configure delay node action to Rate limit, applied to all message
the rate is 1mas per 20 minutes
and i checked "allow msg.rate to override rate"

then a modify the rate during the day using cronplus  sending to delay node messages like

{"cronplus":{"triggerTimestamp":1660727700000,"status":{"type":"static","modified":false,"isRunning":true,"count":1,"limit":0,"nextDescription":"in 23 hours 59 minutes 59 seconds","nextDate":"2022-08-18T09:15:00.000Z","nextDateTZ":"Aug 18, 2022, 11:15:00 GMT+2","timeZone":"Europe/Rome","serverTime":"2022-08-17T09:15:00.007Z","serverTimeZone":"Europe/Rome","description":"At 11:15"},"config":{"topic":"giorno","name":"schedule2","payloadType":"num","payload":"1200000","limit":null,"expressionType":"cron","expression":"0 15 11 * * *"}},"topic":"giorno","scheduledEvent":true,"rate":1200000,"_msgid":"ea6244a7a2ec1cec"}

all works fine, but the delay component send to the output also this control message.

perhaps it would be useful if node Delay ignores this (control) message.

**Comment by knolleary** [comment]
This issue tracker is for reporting bugs and we provide a template that should be used to gather all the relevant details.

What you describe is working as designed. If you'd like to suggest a change in behaviour or a new feature, please use the forum as we don't accepted feature requests here which haven't been discussed in the forum.

**Comment by ghedolo** [comment]
thanks for the clarification
