### ISSUE TITLE
FR: Remember compact/formatted flow export choice per user

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#3849]
### Current Behavior

When installing node-red, the pretty flow format is on by default. 

Often this is fine but it makes posts on the forum rather large.

### Expected Behavior

When choosing compact, I would like it to remain set (between sessions) until I change it back.

Alternatively, add the compact/formatted choice onto the default export view for easier access 

### Steps To Reproduce

select nodes > export > set compact > export

Then repeat - export format is choice is not remembered.

### Environment

- Node-RED version: 3.x

**Comment by Steve-Mcl** [comment]
This is a personal pet peeve (not a bug) :)

**Comment by dceejay** [comment]
^^^ agreed !

**Comment by Steve-Mcl** [comment]
I propose the following behaviour as of NR V3.1...

1. "Pretty Flow" format ON by default for flows files (same as V3.0) 
1. Export defaults to Compact mode in Export Dialog
1. Users choice of Export format is remembered across sessions

Thoughts please?

**Comment by dceejay** [comment]
Agree - compact for export please. (but pretty for storage :-)
