### ISSUE TITLE
Monaco editor does not recognize built-in util module

### ISSUE THREAD

**Issue by pauldeng** [node-red/node-red#3851]
### Current Behavior

Monaco editor raises error on util module.

![image](https://user-images.githubusercontent.com/341848/186624086-88bea038-b7b9-4fdd-9c06-f39697d8b824.png)

Deploy it by force, you will notice the code actually works.

### Expected Behavior

Ace editor does not show the same error.

![image](https://user-images.githubusercontent.com/341848/186625527-652099cf-f40a-4f20-aec2-b0afdc2ce94c.png)

According to [doc](https://nodered.org/docs/user-guide/writing-functions), util is available for function node.

### Example flow

```
[{"id":"c6aa1fb9b985ec0c","type":"inject","z":"2c71e369871e1bf1","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":300,"y":200,"wires":[["f3c126edd67f2eab"]]},{"id":"f3c126edd67f2eab","type":"function","z":"2c71e369871e1bf1","name":"function 1","func":"msg.payload = util.format('%s:%s', 'foo', 'bar');\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"sprintfJs","module":"sprintf-js"}],"x":520,"y":200,"wires":[["f13d7e94ed4589f2"]]},{"id":"f13d7e94ed4589f2","type":"debug","z":"2c71e369871e1bf1","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":720,"y":200,"wires":[]}]
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 16.17
- npm version: 
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Hi @pauldeng - you are correct.  That was missed.

There are 2 work arounds until this is fixed...

1. import `util` as `nodeUtil` in the setup tab
![chrome_6A6tbwgCvy](https://user-images.githubusercontent.com/44235289/186653209-ea1ea497-5496-4678-8e09-8f212d4ef5b6.gif)



2. modify your source code...

&nbsp; &nbsp; &nbsp; &nbsp; a. Locate the file `@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js` (probably in your NPM Global dir)

&nbsp; &nbsp; &nbsp; &nbsp;  b. Change [line 103](https://github.com/node-red/node-red/blob/master/packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js#L103) to 
```js
    const defaultServerSideTypes = [ knownModules["node-red-util"], knownModules["node-red-func"], knownModules["globals"], knownModules["console"], knownModules["buffer"] ];
```

&nbsp; &nbsp; &nbsp; &nbsp;  c. Add the following 2 lines below [line 892](https://github.com/node-red/node-red/blob/master/packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js#L892) line
```js
    editorOptions.extraLibs = editorOptions.extraLibs || []
    editorOptions.extraLibs.push({var: 'util', package: "node", module: "util"})
```
