### ISSUE TITLE
UTC Time Zone in table

### ISSUE THREAD

**Issue by guimeca** [node-red/node-red#3853]
### Current Behavior

Hello all,

Im trying to show a select from mysql using the table dashboard, my current time is UTC -3 and the data is saved like that, so when I try to show this data using the table dashboard the Time zone is UTC by default and i cant change it.

I've tried to change TZ in to settings.js, but didnt work.

![settingsnodered](https://user-images.githubusercontent.com/112285298/187050243-30179997-7aac-49f8-a7eb-27ac43b80da8.jpg)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Hi, we use the issue tracker in this repository primarily for reporting issues and bugs. 

As the template says, ❓questions should be asked on the [Node-RED forum](https://discourse.nodered.org/)

There are many helpful community members and a lot of existing database/dashboard timezone threads to find an answer.
