### ISSUE TITLE
Out Of Memory exception shuts down my NR instance

### ISSUE THREAD

**Issue by Aaroneisele55** [node-red/node-red#3854]
Hello,
I recently noticed that my Node Red instance (Raspberry Pi 4b, Raspbian Bullseye with everything up-to-date) is offline.
I ran the node-red-log commmand and it gave me:

> <--- Last few GCs --->
>[90535:0x41352cd0]  1794594 ms: Mark-sweep 509.0 (524.0) -> 506.5 (523.8) MB, 216.9 / 0.1 ms  (average mu = 0.674, current mu >= 0.709) allocation failure; scavenge might not succeed
>[90535:0x41352cd0]  1795223 ms: Mark-sweep (reduce) 509.9 (526.5) -> 509.3 (523.3) MB, 439.1 / 0.0 ms  (+ 2.7 ms in 1 steps since >start of marking, biggest step 2.7 ms, walltime since start of marking 502 ms) (average mu = 0.507, current mu = 0.298) alloc
><--- JS stacktrace --->
>FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
> 1: 0xb5df64 node::Abort() [node-red]
> 2: 0xa7f3cc void node::FPrintF<>(_IO_FILE*, char const*) [node-red]
> 3: 0xd1baf0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node-red]
> 4: 0xd1bcc0 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node-red]
> 5: 0xef9fbc  [node-red]
> 6: 0xf0bf5c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) >[node-red]
> 7: 0xee80d0 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, >v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node-red]
> 8: 0xee90a8 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, >v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node-red]
> 9: 0xecb25c v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node-red]
>10: 0xec24d4 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, >v8::internal::Map, v8::internal::AllocationAlignment) [node-red]
>11: 0xec4970 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [node-red]
>12: 0xece2ac v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [node-red]
>13: 0xd2c60c v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node-red]
>14: 0xc2ece4  [node-red]
>15: 0xb39168  [node-red]
>16: 0x15e4694  [node-red]
>nodered.service: Main process exited, code=killed, status=6/ABRT
>nodered.service: State 'stop-sigterm' timed out. Killing.
>nodered.service: Killing process 95870 (sudo) with signal SIGKILL.
>nodered.service: Killing process 95871 (python) with signal SIGKILL.
>nodered.service: Failed with result 'signal'.

How can i fix this? This has been happening occasionally at night or at random other times, but this was the first time i was fast enough to see it and get the logs out

**Comment by knolleary** [comment]
Hi @Aaroneisele55 

You need to identify what about your flows is consuming the memory.

Without any information your flows, it's hard to suggest where you can should start looking. This is why we provide issue templates - to try to make sure enough information is provided so we can help.

Is this a recent change in behaviour? If so, what changes have you made recently that could be related?

Are you handling 'large' messages in your flows? Or maybe handling a lot of small messages at a high rate?


For this type of thing (an issue with your flows, rather than a bug in Node-RED) we'd usually direct you to the community forum for help.

**Comment by Aaroneisele55** [comment]
Thanks for the quick reply, i'll post this in the community Forum later

**Comment by Aaroneisele55** [comment]
Moved to the Node Red community forum:
https://discourse.nodered.org/t/out-of-memory-exception-interrupts-my-flows/67025
