### ISSUE TITLE
Limitations of standard human anatomy preventing completion of documented keyboard/mouse combination.

### ISSUE THREAD

**Issue by andyg2** [node-red/node-red#3856]
### Current Behavior

My standard human anatomy is unable to make this keyboard/mouse combination.

> Junctions can be added to wires by holding both the Alt key and the Shift key then click and drag the mouse across the wires.

![image](https://user-images.githubusercontent.com/1462766/187133774-25c8355e-abd8-4969-96e1-7925b5a6b94b.png)

### Expected Behavior

A keyboard/mouse combination which is achievable with standard human anatomy. e.g. ALT+Shift + Drag

### Steps To Reproduce

Place fingers on SHIFT + Left ALT + Right ALT, then hold left mouse button down and drag mouse over connector line.

### Example flow

N/A

### Environment

- Node-RED version: 3.0.2
- Node.js version: v14.17.4
- npm version: 6.14.14
- Platform/OS: Windows / 10.0.19043.1889
- Browser: Firefox 104.0

**Comment by knolleary** [comment]
The action doesn't require both of the alt keys to be pressed. The word 'both' is referring to holding the alt and shift keys... Not both alt keys.

**Comment by andyg2** [comment]
> The action doesn't require both of the alt keys to be pressed. The word 'both' is referring to holding the alt and shift keys... Not both alt keys.

Suggested change to clarify that.

_Junctions can be added to wires by holding Alt+Shift while dragging the mouse across the wires._

If the featurette of using either ALT keys must to be emphasesed, I suggest exchanging the word 'both' (implying 'and') for the word 'either' (implying 'or').

_Junctions can be added to wires by holding either Alt + either Shift keys while dragging the mouse across the wires._

**Comment by knolleary** [comment]
Where exactly is that text you're quoting from?

**Comment by andyg2** [comment]
> Where exactly is that text you're quoting from?

This is from the first-run tutorial popup that starts automatically upon opening the browser from a fresh installation, I believe it's the second or third card in a sequence of around five.

**Comment by FabsMuller** [comment]
Sorry @Andyg2, but to me was quite clear both ALT+CTRL and not both "CTRL Keys" or "ALT Keys".  Wouldn't change that.
