### ISSUE TITLE
Unexpected Node Error in "node-red-contrib-tplink" node

### ISSUE THREAD

**Issue by SDupuie** [node-red/node-red#3864]
Happens a few times a day on average.

2 Sep 13:29:48 - [error] 
********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/Users/Scott/.node-red/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at TCP.<anonymous> (node:net:709:12)

**Comment by knolleary** [comment]
You will need to report that error against the nodes own repository. It isn't one we maintain on the core of Node-RED.

You'll find a link to it's GitHub page on https://flows.nodered.org/node/node-red-contrib-tplink

**Comment by Steve-Mcl** [comment]
Also, when you report the error, inform the author that calling `node.error` in a catch call back causes this error e.g. https://github.com/caseyjhol/node-red-contrib-tplink/blob/15aae36380263a40977a2634e8d340af49310610/nodes/kasa.js#L335

**Comment by SDupuie** [comment]
OK, I reported it to the author's repository.

**Comment by Steve-Mcl** [comment]
For reference: https://github.com/caseyjhol/node-red-contrib-tplink/issues/62
