### ISSUE TITLE
Node's sendEvents object canb contain invalid cloneMessage info.

### ISSUE THREAD

**Issue by TLacke** [node-red/node-red#3875]
### Current Behavior

In the runtime library, the Node.js contains a blurp:

When two or more messages are sent through the `Node.send([{payload:'msg1'}, {payload:'msg2'}, {payload:'msg3'}])`, the `sendEvents` object in the runtime library _(@node-red/runtime/lib/nodes/Node.js::~446)_ is filled with source and destination information and sent to the flow.
However, there's a field called, `cloneMessage`, that is set to true (by the `msgSent` variable) as soon as the first message has been handled.

This works if you have only one message, but when sending in multiple messages, the following messages 'msg2' and 'msg3' _(in this case)_ will be flagged as cloned and then in _(@node-red/runtime/lib/flows/Flow.js::~813)_ the flag is checked and cloning all initial messages.

### Expected Behavior

I would've guessed that each message is its own and the clone is used to clone individual messages _(The msgs, and not the sendEvents)_.
If this is the case, the `msgSent` shouldn't be used for the `sendEvents.cloneMessage` field.

### Steps To Reproduce

Execute:
Node.send([{payload:'msg1'}, {payload:'msg2'}, {payload:'msg3'}])

Put a breakpoint or log in Flow.js::handlePreRoute of the @runtime library.
The 'msg2' and 'msg3' is cloned even though they're the initials. 'msg1' however isn't cloned.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.4.0
- @runtime library bug

**Comment by knolleary** [comment]
In you example, `msg2` and `msg3` are not guaranteed to be 'initials' as you call them and must get cloned.

Instead of:
```
Node.send([{payload:'msg1'}, {payload:'msg2'}, {payload:'msg3'}])
```

Consider the code:
```
const msg = { payload: 'msg1' }
Node.send([msg, msg, msg])
```

Here the same object is passed multiple times. The first instance can be passed through uncloned. The others must get cloned to break the link.

**Comment by TLacke** [comment]
That is completely true.
You could do something like this:
  `if (sendEvents.find(e=>e===curentMessage).length == 1) // not cloned (on top level).`

But it could be a subobject used in both objects.
I back down. Continue as is "Great job"
