### ISSUE TITLE
Sending 'false' as message fails in Node.js::receive method.

### ISSUE THREAD

**Issue by TLacke** [node-red/node-red#3876]
### Current Behavior

There's currently a possibility to send native values like booleans, numbers and strings directly into the `Node.send(true, 11)` method.
However, the `false` boolean value is not allowed as the `Node.js::receive` method in the **@runtime library** implements an invalid type check.
`if (!msg) msg = {}` will cause the `false` message value to be converted to an empty object.

### Expected Behavior

If native values are supported _(as it looks in the code, except this place)_ the `if`-statement should be changed to `if (typeof msg === 'undefined')`.

### Steps To Reproduce

`Node.send(false)`

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.4.0
- @runtime library issue: @node-red/runtime/lib/nodes/Node.js

**Comment by hardillb** [comment]
Native values should not be supported

**Comment by TLacke** [comment]
I totally agree that this should be the case. But unfortunately there's no type check on it which allows the natives to be sent correctly to the next node _(though the `_msgid` tag is assigned as a field onto the native value, which is not correct)_.

Would be nice with a typecheck to ensure that a non-native value is being sent.
