### ISSUE TITLE
Hanging flow editor when creating many ports

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#3885]
### Current Behavior

I found that the flow editor hangs up when creating many ports of a node. For example, after inputting 1000000 as the number of ports in the function node, the flow editor will crash.

![numberofport](https://user-images.githubusercontent.com/20310935/190665254-3474d2d7-048f-4db4-9b03-dc356d4b2a25.gif)

### Expected Behavior

I think that editor needs to limit the number of ports to prevent the issue. In my opinion, 10 is enough in a general case.

### Steps To Reproduce

1. Place function node
2. Input the large number for ports

### Environment

- Node-RED version: v3.0.2
- Node.js version: v18.7.0
- npm version: v8.15.0
- Platform/OS: macOS Monterey 12.6 on MacBook Air (M1, 2020)
- Browser: Google Chrome 105.0.5195.125 (Official Build) (arm64)

**Comment by knolleary** [comment]
I agree we should protect against very large numbers, but I do not think 10 is large enough. We do sometimes get users who have a much larger number of ports that you would expect sensible. We have to pick a value that is *very* unlikely to be in use by any existing flow today.

**Comment by dceejay** [comment]
Default canvas height is 5000px ? And port is 10px  (with gaps) so maybe 500 ?
