### ISSUE TITLE
All links in API.md are broken

### ISSUE THREAD

**Issue by guyluz11** [node-red/node-red#3887]
### Current Behavior

Links in the file API.md are broken 

https://github.com/node-red/node-red/blob/master/API.md

### Environment

main branch

**Comment by guyluz11** [comment]
I can open pr for that

It is this folder 
https://github.com/node-red/node-red/tree/master/packages/node_modules/node-red

Plus the folders from here  
https://github.com/node-red/node-red/tree/master/packages/node_modules/%40node-red

**Comment by dceejay** [comment]
Yes please go ahead.

**Comment by guyluz11** [comment]
@dceejay Will this repo support [Hacktoberfest](https://hacktoberfest.com/)?.

**Comment by knolleary** [comment]
The links are correct for how this file is used. We generate API documentation using jsdoc. This file is included as the index page of those docs as you can see here: https://nodered.org/docs/api/modules/v/1.3/

In that context, the links are correct. But I can certainly see how someone viewing the raw file in GH would see the links as broken.

Not sure the best approach to address that - but just changing the links isn't going to be the right answer as it will break the generated docs.

Regarding Hacktoberfest - we've had mixed experiences with that in the past with an influx of trivial, incorrect and inappropriate PRs. I hadn't realised it was starting so soon (October is a week away!) - we'll discuss it internally before making a decision.

**Comment by guyluz11** [comment]
Should I close this issue?.

**Comment by knolleary** [comment]
I'm going to close this as I'm not sure what else we'll do with it. The whole area of the API docs needs looking at, but that's a broader topic than just this issue.

Thank you for flagging it up regardless :)
