### ISSUE TITLE
Is  there  an API  or interface that  can  call  the  Deploy Button

### ISSUE THREAD

**Issue by mcjqwer** [node-red/node-red#3888]
I want to run a program in my software instead of the deploy button function. Is there an API to use it? I couldn't find it.

**Comment by dceejay** [comment]
Pleas use the discourse forum or slack channel for general how to questions. But yes see the API docs https://nodered.org/docs/api/admin/methods/post/flows/

**Comment by mcjqwer** [comment]
> Pleas use the discourse forum or slack channel for general how to questions. But yes see the API docs https://nodered.org/docs/api/admin/methods/post/flows/
Sorry,i can't find the official interface for the deploy button.

**Comment by dceejay** [comment]
That is the interface. When you click the deploy button it posts the flow json to the runtime using that call.
