### ISSUE TITLE
patching /nodes/core/network/21-httpin: add Number()

### ISSUE THREAD

**Issue by jfalch** [node-red/node-red#3893]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@node-red/nodes@3.0.2` for the project I'm working on.

When running an embedded node-red, I get a warning on STDERR `express deprecated res.status("200"): use res.status(200) instead at node_modules\@node-red\nodes\core\network\21-httpin.js:328:34`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@node-red/nodes/core/network/21-httpin.js b/node_modules/@node-red/nodes/core/network/21-httpin.js
index b458a45..3b6f87c 100644
--- a/node_modules/@node-red/nodes/core/network/21-httpin.js
+++ b/node_modules/@node-red/nodes/core/network/21-httpin.js
@@ -325,7 +325,7 @@ module.exports = function(RED) {
                 }
                 var statusCode = node.statusCode || msg.statusCode || 200;
                 if (typeof msg.payload == "object" && !Buffer.isBuffer(msg.payload)) {
-                    msg.res._res.status(statusCode).jsonp(msg.payload);
+                    msg.res._res.status(Number(statusCode)).jsonp(msg.payload);
                 } else {
                     if (msg.res._res.get('content-length') == null) {
                         var len;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by hardillb** [comment]
Thank you for raising this, we can't normally accept code that is not a Pull Request with a signed CLA.

In this case I have fixed it in different way (because patch fix would allow `statusCode` = `200.5`)
