### ISSUE TITLE
Arduino Input Node - State change for digital not working?

### ISSUE THREAD

**Issue by Hardware-Hacks** [node-red/node-red#39]
Hi,

When running the following:

![image](https://f.cloud.github.com/assets/1431348/1322459/4fe5f82a-342f-11e3-8cb0-33a727da5b98.png)

```
[{"id":"71664c2f.8e99b4","type":"arduino-board","repeat":"1000","device":"/dev/ttyACM0"},{"id":"54431023.abbcf","type":"arduino in","name":"","pin":"4","state":"INPUT","arduino":"71664c2f.8e99b4","x":251,"y":200,"wires":[["ce99b356.31665"]]},{"id":"254c9827.dab368","type":"arduino out","name":"","pin":"4","state":"OUTPUT","arduino":"71664c2f.8e99b4","x":403,"y":338,"wires":[]},{"id":"9adaa94d.652558","type":"inject","name":"","topic":"","payload":"1","repeat":"","crontab":"","once":false,"x":162,"y":312,"wires":[["254c9827.dab368"]]},{"id":"c68ba83.f397458","type":"inject","name":"","topic":"","payload":"0","repeat":"","crontab":"","once":false,"x":171,"y":377,"wires":[["254c9827.dab368"]]},{"id":"ce99b356.31665","type":"debug","name":"","active":true,"complete":"true","x":481,"y":189,"wires":[]}]
```

I do not see anything in the debug window when clicking the inject nodes. I am running an LED from the pin which is turning off and on but the arduino input node is not giving me a value in the debug window.

This seems to only be affecting digital as reading values to the debug window on analogue pins works fine for me.

I would expect to be seeing 1's and 0's depending if the pin is going high or low.

**Comment by dceejay** [comment]
Node has been re-written several times since original problem - nor re-reports. Closing for now.
