### ISSUE TITLE
[hint needed] Node-Red on readonly-system

### ISSUE THREAD

**Issue by jhaake2308** [node-red/node-red#3914]
Hi, 
I recently migrated my Node-Red setup to a standard raspberry-pi, from [https://github.com/rdmtc/RedMatic]. My "special" use-case is the challenge that in a normal situation I would like to run the Pi read-only to protect the SD card.

So I have to change/update my flows from time to time, which of course requires write access to save the changes (what a surprise :) ). Can you give me a hint / step in the right direction as to whether this can be implemented in any way in Node-Red or where I should look for this? Not to mention the fact that using context-storage will also need consideration.

As an example: For system updates via APT, I found the possibility to add the appropriate remount commands to the APT-Update-Script so that the updates can be installed (simplified: pre: remount RW, post: remount RO). 

Would this approach be an idea to add this option to the Node-Red scripts as well, or is the checkin of changes in the flows mapped somewhere in a binary which cannot be manipulated?

Of course I also thought of moving the node-red-directory to a mounted USB-storage, but I am currently looking for alternatives.

Thank you & best regards
Julius

**Comment by knolleary** [comment]
Hi @jhaake2308 - as our issue templates point out, we prefer general how-to type questions/discussions to happen over on the forum - discourse.nodered.org. There is a much larger user-community over there who can help with this type of question, rather than rely on the small group who manage the issues on the core repo.

**Comment by Steve-Mcl** [comment]
Hi @jhaake2308 please take your question to https://discourse.nodered.org/ 

Please note, the guys on the forum are super helpful but since this is probably more of a OS / File System type question their may not be too many answers.

**Comment by jhaake2308** [comment]
sorry for botherin you,.. :) my thought concerning asking the question here was due to the specific issue of checking in changes in the flows which for me is the core-thing of NR. So no offence, will go to the forum :). BR Julius
