### ISSUE TITLE
Log has "Unexpected Node Error"

### ISSUE THREAD

**Issue by KDYR** [node-red/node-red#3918]
### Current Behavior

Log has error and suggests that it be reported, so here you are:

```
14 Oct 22:19:23 - [info] 
Welcome to Node-RED
===================
14 Oct 22:19:23 - [info] Node-RED version: v3.0.2
14 Oct 22:19:23 - [info] Node.js  version: v16.16.0
14 Oct 22:19:23 - [info] Linux 5.15.32-v8 arm64 LE
14 Oct 22:19:25 - [info] Loading palette nodes
14 Oct 22:19:31 - [info] Dashboard version 3.2.0 started at /endpoint/ui
14 Oct 22:19:32 - [info] Settings file  : /etc/node-red/config.js
14 Oct 22:19:32 - [info] Context store  : 'default' [module=memory]
14 Oct 22:19:32 - [info] User directory : /config/node-red/
14 Oct 22:19:32 - [warn] Projects disabled : editorTheme.projects.enabled=false
14 Oct 22:19:32 - [info] Flows file     : /config/node-red/flows.json
14 Oct 22:19:32 - [info] Server now running at http://127.0.0.1:46836/
14 Oct 22:19:32 - [info] Starting flows
14 Oct 22:19:32 - [error] 
********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: Initializing...
    at log_helper (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:512:20)
    at DenonConnectionNodeConstructor.Node.log (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:531:5)
    at new DenonConnectionNodeConstructor (/config/node-red/node_modules/@chaws/node-red-denon/src/denon-connection.ts:28:8)
    at Object.createNode (/opt/node_modules/@node-red/runtime/lib/flows/util.js:90:27)
    at Flow.start (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:180:44)
    at Object.start [as startFlows] (/opt/node_modules/@node-red/runtime/lib/flows/index.js:394:33)
Please report this issue, including the information logged above:
https://github.com/node-red/node-red/issues/
********************************************************************
14 Oct 22:19:32 - [info] Started flows
[22:19:33] INFO: Starting NGinx...
```

### Expected Behavior

No errors

### Steps To Reproduce

Restartinjg Node-Red

### Example flow

```
paste your flow here
```

### Environment

Node-RED version: v3.0.2
Node.js version: v16.16.0

Home Assistant 2022.9.5
Supervisor 2022.10.0
Operating System 8.5
Frontend 20220907.2 - latest

[info] Linux 5.15.32-v8 arm64 LE

**Comment by hardillb** [comment]
This will be something you need to raise against the `@chaws/node-red-denon` node [here](https://github.com/ChristopherHaws/node-red-denon).

The problem is that they can not call the log function here:

https://github.com/ChristopherHaws/node-red-denon/blob/2b6b0c3a6d4e50db5340cec255a9ba19ae9e0d0e/src/denon-connection.ts#L28

It can not be called before

https://github.com/ChristopherHaws/node-red-denon/blob/2b6b0c3a6d4e50db5340cec255a9ba19ae9e0d0e/src/denon-connection.ts#L36

**Comment by knolleary** [comment]
Just for context, the log asks you to raise the issue here so we can examine the node hitting the problem and advise on what the actual issue is - as it may not be obvious to the node's author.

Thanks @hardillb for digging into it and providing the links.

**Comment by Steve-Mcl** [comment]
@KDYR there is an unresolved issue around the same thing - the thread also provides a temporary workaround...

https://github.com/ChristopherHaws/node-red-denon/issues/4
