### ISSUE TITLE
Feature Request: Add support for POST responses from OIDC identity provider

### ISSUE THREAD

**Issue by sg26565** [node-red/node-red#3924]
Node-RED supports OAuth/OpenID based authentication via the passport library. However, currently, Node-RED only listens for GET requests on the callback URL /auth/strategy/callback, which limits the possible response modes of OIDC to just "query". As queries are sent via HTTP GET requests, sensitive information may be exposed as the query string is visible in the browser history and may also be logged to a file. Therefore, identity and access tokens should not be used as response type with OIDC for security reasons. Instead, an authorization code should be used.

For improved security, Node-RED should listen to POST requests on /auth/strategy/callback as well. This would enable the "post_method" response mode for OIDC where all sensitive information is sent with the body of the POST message and are encrypted with TLS. With this enhancement, identity and access token can be used without the risk to expose them to third parties.

**Comment by knolleary** [comment]
Hi @sg26565 

Apologies for the slow response.

I believe this is already supported, albeit not documented, by setting `callbackMethod` to `POST` in your `adminAuth.strategy.options` object.

I'll update the docs to mention this.

**Comment by sg26565** [comment]
Hi @knolleary 

Yes, I can confirm that it works this way. In case you want to include it into your documentation, here is my working configuration:

    adminAuth: {
        type:"strategy",
        strategy: {
            name: "azuread-openidconnect",
            label: 'Sign in with Azure',
            icon: "fa-windows",
            strategy: require("passport-azure-ad").OIDCStrategy,
            options: {
                identityMetadata: "https://login.microsoftonline.com/<our tenant id>/v2.0/.well-known/openid-configuration",
                clientID: "<your client id>",
                callbackMethod: "POST",
                responseType: "id_token",
                responseMode: "form_post",
                redirectUrl: "https://localhost:1880/auth/strategy/callback",
                issuer: "https://login.microsoftonline.com/<your tenant id>/v2.0",
                scope: ['openid', 'profile'],
                verify: function(token, tokenSecret, profile, done) {
                    profile.username = profile.displayName; // could be any unique claim from the id token (e.g. email)
                    done(null, profile);
                }
            }
        },
        users: [
            {
                username: "<value of the id token claim chosen above>",
                permissions: "*"
            }
        ]

**Comment by spady7** [comment]
Hi, can someone point me why nodered still telling me there is an error in settings.js? I used same code. Below code used (as @sg26565 posted)

`adminAuth: {
    type:"strategy",
    strategy: {
        name: "azuread-openidconnect",
        label: 'Sign in with Azure',
        icon: "fa-windows",
        strategy: require("passport-azure-ad").OIDCStrategy,
        options: {
            identityMetadata: 'https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxx/v2.0/.well-known/openid-configuration',
            clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            callbackMethod: "POST",
            responseType: "id_token",
            responseMode: "form_post",
            redirectUrl: "https://localhost:1880/auth/strategy/callback",
            issuer: "https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/v2.0",
            scope: ['openid', 'profile'],
            verify: function(token, tokenSecret, profile, done) {
                profile.username = profile.displayName; // could be any unique claim from the id token (e.g. email)
                done(null, profile);
            }
        },
    },
    users: [
        {
            username: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            permissions: "*"
        }
    ]
},`

**Comment by knolleary** [comment]
@spady7 I can't see anything obvious in that excerpt of your file. One trick to locating errors to is try running the file directly:

```
node settings.js
```

That should give you better clues as to what is wrong.

**Comment by spady7** [comment]
@knolleary thank you!. I tested and passport module was installed not in a correct directory. Now seams to work. Anyway when i try to connect, inserting Azure id user credential i get "unsupported_response_type".
How can i investigate it?
