### ISSUE TITLE
Feature Request: Expandable Comment or Comment Box in Node-Red Flows

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [node-red/node-red#3925]
### Current Behavior

Comment Node is being used to document the flows and make them easier to under stand. However, user must open them to read the comments.

### Expected Behavior

Request is to either make a expandable/accordion style comment node in which comment can be displayed by clicking (e.g. an arrow) or else a comment box that shows text content.

### Steps To Reproduce

This is a feature request.

### Example flow

This is a feature request.

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Hi @kaushalkumarjoshi 

as described in the issue template, we don't handle feature requests via the issue tracker.

Please start a discussion on https://discourse.nodered.org
