### ISSUE TITLE
Error updating nodes.

### ISSUE THREAD

**Issue by leojcs2021** [node-red/node-red#3926]
### Current Behavior

How to go about fixing this problem, I can't update my nodes?

I have node-red integrated into my home assistant!

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
For general help, as the issue templates describe, please us the forum at https://discourse.nodered.org - where there is a large community of users who'll be able to help.

**Comment by leojcs2021** [comment]
Sorry, I'm not good with the forum, I'll put the error screen that appears in the log.

**Comment by hardillb** [comment]
Please post this to the forum as asked

**Comment by Steve-Mcl** [comment]
Raised on forum here: https://discourse.nodered.org/t/error-updating-nodes/69408
