### ISSUE TITLE
Missing "input-error" class on typed (wrapped) input field.

### ISSUE THREAD

**Issue by Steveorevo** [node-red/node-red#3939]
### Current Behavior

When creating a field and supplying default property as "required: true"; a red border appears around the input field giving the user instant feedback as to which field needs to be filled out. However, this behavior is missing if the input is designated with a type such as "str". The required behavior is otherwise enforced but the input-error class is missing from the wrapped input field. 

### Expected Behavior

Suggest applying the "input-error" class to the outer div that wraps the input elm. Otherwise the behavior enforces the field as required, but no user feedback as to which field is required leads to user confusion. If I can locate and fix the issue; I will submit a pull request. Screenshot attached: 

<img width="532" alt="screen_shot_2022-10-27_at_4 00 03_pm" src="https://user-images.githubusercontent.com/635399/199312847-fa4de17c-07dc-4806-b1be-2128bef4d4ee.png">
<img width="532" alt="screen_shot_2022-10-27_at_4 03 15_pm" src="https://user-images.githubusercontent.com/635399/199312858-f04ab958-9202-4157-a0a3-4021595b9b95.png">

### Steps To Reproduce

When creating a field and supplying default property as "required: true" and type of 'str'. 

### Environment

- Node-RED version: 3.0.2
- Node.js version: 16.17.0
- npm version: 8.15.0
- Platform/OS: Windows, Mac, Linux
- Browser: Safari, Firefox, and Chrome

**Comment by Steve-Mcl** [comment]
@Steveorevo 

Would you be kind enough to share a minimal example of the HTML and SCRIPT to recreate this please?

Ta.

**Comment by Steveorevo** [comment]
Pull request submitted https://github.com/node-red/node-red/pull/3949
