### ISSUE TITLE
error when i want to enter in log

### ISSUE THREAD

**Issue by gedas07** [node-red/node-red#3950]
### Current Behavior

I have a docker version 3.0.2 in raspberry 4 with projects,
When I want to enter in th log of docker nodered in portainer I see this message 

Expected property name or '}' in JSON at position 1 

and I can't see the log  

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Please use the community forum for general help questions: https://discourse.nodered.org

Youll need to provide more information, such as exactly what you are doing and where you see that error
