### ISSUE TITLE
Credentials are visible through http://127.0.0.1:1880/flow/global after Deploying some updates on Configuration Node

### ISSUE THREAD

**Issue by A-Ghorab** [node-red/node-red#3953]
### Current Behavior

During the tests the team found that in Configuration Nodes that has a credentials fields like (user name and password in mysql node) the credentials are visible after clicking on Deploy button and remains visible until Node Red Server is restarted when visiting the url http://127.0.0.1:1880/flow/global.

the output would be like this
```json
{
   "id":"global",
   "configs":[
      {
         "id":"334d02401e4b6f64",
         "type":"MySQLdatabase",
         "name":"",
         "host":"127.0.0.1",
         "port":"3306",
         "db":"123123",
         "tz":"",
         "charset":"UTF8",
         "credentials":{
            "user":"test",
            "password":"test"
         },
         "_users":[
            "a15967098039ec8d"
         ]
      }
   ]
}
```

### Expected Behavior

when calling the http://127.0.0.1:1880/flow/global url it shouldn't show the credentials section. 

### Steps To Reproduce

1. Install NodeRed
2. Install any Configuration Node (ex node-red-node-mysql)
3. Start NodeRed
4. Add mySql Node
5. Open Node Properties and Fill all Fields
6. Deploy Flow
7. visit http://127.0.0.1:1880/flow/global and check the configuration.

### Example flow

this is my test example with mysql node (as the configuration with credentials node) https://stackblitz.com/edit/node-sza3la?file=package.json 

### Environment

This issue was visible on both Node-Red 2 and 3

- Node-RED version: 3.0.2
- Node.js version: 18.7.0
- npm version: 8.15.0
- Platform/OS: Ubuntu
- Browser: Firefox

**Comment by A-Ghorab** [comment]
i recorded a video with the issue, this is a clean setup online to try to reproduce the issue

if this can help
https://1drv.ms/u/s!Aiahuky40MlRgQKuiAApXGkgZYr1?e=a5LOPq

**Comment by A-Ghorab** [comment]
i dived into the code as well and the found that it does only return the values, i still couldn't find the fill credentials part yet as well.

**Comment by knolleary** [comment]
I misunderstood your original issue report and was looking in the wrong place. We can recreate this.

For future reference, anything security related should be disclosed via our security policy documented here: https://github.com/node-red/node-red/blob/master/SECURITY.md - this allows us to assess the impact and prepare fixes before issues are publicly disclosed.

**Comment by A-Ghorab** [comment]
@knolleary just to be sure i can provide a pull request with a simple fix to hide "credentials" section when calling the flow api. would that be sufficient ? i don't know how it would affect the other api's so wanted your confirmation if that is sufficient.

**Comment by knolleary** [comment]
The `credentials` property is meant to get removed as part of the internal processing. We need to track down why that isn't happening as there could be other places that are able to access them unexpectedly.
