### ISSUE TITLE
trigger: state node debug output does not respect debug output current flow

### ISSUE THREAD

**Issue by masman69** [node-red/node-red#3973]
### Current Behavior

When a **trigger: state** node has its **Output debug information** option turned on, it outputs debug information in the **Debug messages** pane, even when a different flow is selected and the filter current flow is selected.

### Expected Behavior

This node should respected the debug messages pane filter.

### Steps To Reproduce

Utilize a trigger:state node on 1 tab and disable it with payload.disable message.  Navigate to a different flow and choose filter **current flow**.  As the trigger:state node is triggered you will see:

```
sent data : msg :
"incoming: node is currently disabled, ignoring received event"
```

in debug pane.  There is no link to take you to that node as there are with other nodes' debug messages.  Note the trigger has to occur while you are on a different tab.  Unlike other nodes that populate the debug pane when you switch flows based on filter, this does not seem to.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:  13.5.3 (in Homeassistant)
- Node.js version: version packaged with Homeassistant Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
- npm version:
- Platform/OS: Homeassistant
- Browser: Chrome current

**Comment by dceejay** [comment]
This is a Home Assistant node and not a core Node-RED node so needs to be raised against that project instead.
