### ISSUE TITLE
`reset` flag in `parser/CSV.js` not handled as boolean

### ISSUE THREAD

**Issue by wolframkriesing** [node-red/node-red#3976]
### Current Behavior

Passing the (undocumented) `reset` flag to a csv node is always interpreted as `true`.
The code only checks for the existence of the prop: https://github.com/node-red/node-red/blob/bccfd21cf46da7dfdde9653466f218fb3459ad7d/packages/node_modules/%40node-red/nodes/core/parsers/70-CSV.js#L60

### Expected Behavior

I would expect:
1) the flag to be a boolean
2) to find it in the documentation

### Environment

- Node-RED version: v3.0.2
- Node.js version: docker `FROM node:latest`
- npm version: as above
- Platform/OS: docker `FROM node:latest`
- Browser: Chrome 108

**Comment by dceejay** [comment]
The option where it is used does show it. 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/5375409/206294581-f94d9bae-c2c9-4b84-b7d8-642ecfaa5078.png">
The use of reset is consistent with how it is used  in the trigger nodes and elsewhere.

**Comment by wolframkriesing** [comment]
It feels strange. But if it is consistent, it might just need a bit of docs and this issue can be closed, right? Thanks for the super fast response.
