### ISSUE TITLE
Nodered behind reverse proxy

### ISSUE THREAD

**Issue by EnricoBeltramo** [node-red/node-red#3978]
### Current Behavior

I have a configuration where the nodered is behind a reverse proxy.  The node red is running inside a docker and its root url is configured with port 1880 and a subpath node-red (i.e. localhost:1800/node-red). In another docker I have a ngnix running a reverse proxing that foward the node red in same path /node-red

here the configuration of ngnix:

    client_max_body_size        2000M;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
    
    listen 80;
    location  /node-red  {
        proxy_pass http://node-red:1880;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

With node-red till version 2.x everything work well and I'm able to see the node-red in fowarded path of ngnix (i.e. localhost:80/node-red), but if I switch to version 3.x it says "cannot get /node-red". It's changed something about the strategy in 3.x version?

### Expected Behavior

node-red ver 3.x that run as 2.x

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 16
- npm version: 7.16.0
- Platform/OS: win11
- Browser: chrome

**Comment by EnricoBeltramo** [comment]
At moment both versions have same configuration and in both versions I set httpAdminRoot as /node-red. The ngnix has same configuration, so the only thing that change is the version of node-red. I don't understand why in 2.x the foward works and in 3.x not.

**Comment by hardillb** [comment]
I've just tested this locally and it's working just fine.

docker run --rm -v $(pwd)/data:/data --name node-red --network test nodered/node-red:2.2.2

or

docker run --rm -v $(pwd)/data:/data --name node-red --network test nodered/node-red:3.0.2

`$(pwd)/data/settings.js` is the same for both containers with `httpAdminRoot` set to `/node-red`

and the followin in the nginx config:

```
 location /node-red {
    proxy_pass http://node-red:1880;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

Are you sure you have bound both node-red instances to the same docker network (docker-compose will do this automatically)

**Comment by EnricoBeltramo** [comment]
Thank you for support. Yes you are rigth: the path forward works correctly. 
I found the issue: in my configuration I had to customize the entry point of node-red docker, but I found that in docker from 2.x to 3.x the entry point was changed:
# ENTRYPOINT ["npm", "start", "--cache", "/data/.npm", "--", "--userDir", "/data"]
ENTRYPOINT ["./entrypoint.sh"]
so using the 3.x with old entrypoint style, the changes like http path was not applied. 
I fixed updating to the new entrypoint
