### ISSUE TITLE
TCP nodes do incomplete replacements on newline

### ISSUE THREAD

**Issue by phoddie** [node-red/node-red#3989]
### Current Behavior

In 31-tcpin.js, the following is used to unescape carriage returns, linefeeds, and tabs for "tcp in" and "tcp request" nodes:

```js
this.newline = (n.newline||"").replace("\\n","\n").replace("\\r","\r").replace("\\t","\t");
```

The replace function only replaces the first occurrence when the first argument is a string. If `newline` contains more than one carriage return, linefeed, or tab, the result will not match the user's expectation.  This isn't a big deal, as most `newline` values won't have multiple of these.

Most places Node-RED uses `replace` the first argument is a regular expression with the `g` flag, which does replace all occurrences. That could be done here too. A simpler fix could be to use `replaceAll` instead, which was added in ES2020 (assuming your minimum supported version of Node.js includes this).

FWIW – there is similar code in the CSV node.

### Environment

- Node-RED version: v3.0.2
- Node.js version: v19.2.0
- npm version: 8.19.3
- Platform/OS: Darwin 21.6.0 arm64 LE
- Browser: Chrome Version 108.0.5359.98

**Comment by knolleary** [comment]
@dceejay was there a reason you only fixed this in the CSV node?

**Comment by dceejay** [comment]
Yes - @Steve-Mcl was doing some other fixes to the tcp node so I left it to him to roll this in.

**Comment by dceejay** [comment]
PR now raised

**Comment by phoddie** [comment]
Thank you!
