### ISSUE TITLE
msg.filename override for file nodes can cause confusing side effects

### ISSUE THREAD

**Issue by hootonp** [node-red/node-red#399]
In the file read/ file write nodes, the filename supplied as part of node can be overridden by setting the msg.filename property. The rationale for this is not clear.

This has an undesirable side affect that took me a long while to debug what was going on.

Assume a flow where Node 1 reads file A, Node 2 does some stuff, Node 3 reads file B...

In this scenario Node 3 ends up actually reading file A NOT file B. this is becuase the "msg.filename" property is still set to file A from Node 1.

It does not seem intuitive in this case that the user is expected to clear the msg.filename field if they do not want it used?

**Comment by brybad** [comment]
It would be nice to get rid of the message as it fills up the debug window with all the repeated garbage. Some times it is a necessity to set a property before. I have to create custom url's with variables to send to http-request and even if I leave the node's input blank, the warning still pollutes the debug window. My option is to hope I don't run out of memory and can capture a debug output in between the noise, or create hundreds of http-request nodes, 1 for each possibility of every device with every data item, and then hire people to constantly modify the ones with time filters to adjust for clock ranges in epoch time...

My other alternative is to delete the nooverride lines in the httprequest.js file...which makes this a custom file that constantly needs to be maintained with every update...

**Comment by knolleary** [comment]
@brybad as this is a 10 year old closed issue, can I ask you raise a new issue describing the problem and we can consider it there.

**Comment by brybad** [comment]
Sure, but is going to be this same one regurgitated again as the fix was released as absolute without consideration of implications and usage.
