### ISSUE TITLE
Host the editor elsewhere

### ISSUE THREAD

**Issue by ecrode** [node-red/node-red#4002]
I know Node.Red supports running without an editor, but would it be possible to host the editor elsewhere and connect to node.red instance remotely? For example, having installed node.red on raspberry pi, I would like to install same version on the docker. Tell pi to run without the editor, and configure node.red on the docker to connect to the pi, rather than the local instance.

**Comment by knolleary** [comment]
Closing as this is not an issue to be fixed.
