### ISSUE TITLE
No connection to home assistant

### ISSUE THREAD

**Issue by guido-52** [node-red/node-red#4008]
### Current Behavior

node red loses connection with Home Assistant.
Sometimes the connection spontaneously recovers.
Sometimes I have to restart Node red and Node-red companion

[LOG.TXT](https://github.com/node-red/node-red/files/10366087/LOG.TXT)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:  14.0.1 
- Node.js version: 
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Hi, this is probably better raised against whatever home assistant nodes you are using.

We do not maintain the home assistant nodes, so not going to be able to help solve this issue.
