### ISSUE TITLE
request to https://registry.npmjs.org/node-red failed, reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by ArvindGundimajalu** [node-red/node-red#4016]
### Current Behavior

While trying to install node red using the command npm install -g --unsafe-perm node-red I get the following error.

### Steps To Reproduce

run npm install -g --unsafe-perm node-red in a secure machine.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
Please fill out the full template (especially the version numbers)

Also supply the full error message from the Node-RED logs and a detailed description of your network environment. It sounds like you have a HTTP Proxy in place that is man in the middle breaking TLS.

**Comment by hardillb** [comment]
It sounds like you are behind a bad HTTPS proxy, you can tell npm to not check SSL certificates with

https://docs.npmjs.com/cli/v8/using-npm/config#strict-ssl

```
npm config set strict-ssl false
```
