### ISSUE TITLE
"package" is a reserved word in strict mode

### ISSUE THREAD

**Issue by sethhall** [node-red/node-red#4017]
### Current Behavior

I'm trying to package an application that includes node-red with rollup and I'm getting this error...

```
[!] (plugin commonjs--resolver) SyntaxError: The keyword 'package' is reserved (109:14) in /workspaces/tikha/.yarn/cache/@node-red-registry-npm-3.0.2-d64265e3f5-324975ab85.zip/node_modules/@node-red/registry/lib/localfilesystem.js
```

### Expected Behavior

The bundling to work.

### Steps To Reproduce

You can reproduce easily with the repo located here: [node-red-ticket-example](https://github.com/sethhall/node-red-ticket-example)

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.13.0
- npm version: 8.19.3
- Platform/OS: Mac OS 13.1

**Comment by knolleary** [comment]
Fixed via #4020
