### ISSUE TITLE
Right-click on context menu opens browser's context menu (3.1.0-beta.1)

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#4045]
### Current Behavior

Right clicking on the workspace context menu opens the browser's regular context menu.

### Expected Behavior

Not to open the menu

### Environment

- Node-RED version: 3.1.0-beta.1
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by PizzaProgram** [comment]
IMHO this is good this way. What if someone **wants** to open the browsers menu? It would be easy this way.

**Comment by knolleary** [comment]
We had some additional comments in the forum on this subject. On balance, being able to still access the browser's native context menu is a feature not a bug.
