### ISSUE TITLE
Twitter In node question

### ISSUE THREAD

**Issue by maiorfi** [node-red/node-red#406]
Hi.

I'm using twitter in node for the first time and probably there's something I haven't fully got about receiving tweets coming from user I follow filtered by expression.

Indeed, it seems that despite specifying something like "@user,#hashtag" in filter expression while using "tweets from users I follow" option, I get a message for every message in timeline.

Is there any explanation for this behavior?

Thanks!

**Comment by knolleary** [comment]
Hi,

sorry this has sat unanswered for so long. The mailing list is often a better starting point for this sort of question.

The twitter api docs for what is possible to filter is [here](https://dev.twitter.com/streaming/overview/request-parameters#track).

In short, if you want to restrict to the tweets of a specific user, you will need to pick the 'tweets of a specific user' option, and then filter the content in your flow.
