### ISSUE TITLE
Partial deploys are sending full payload

### ISSUE THREAD

**Issue by maurimuchico-work** [node-red/node-red#4063]
### Current Behavior

Despite of deploying using "Modified Flows" or "Modified Nodes" 
![image](https://user-images.githubusercontent.com/123373946/219651418-bb47175a-6c65-4466-be90-83b5fcabf208.png)
the full payload is sent from the frontend to the backend as you can see in the following picture:
![image](https://user-images.githubusercontent.com/123373946/219677822-1c580e93-82c2-464c-b0a1-e1eb4d08d292.png)

### Expected Behavior

We expect the full payload to be sent only when the deploy mode is full

### Steps To Reproduce

1. Start node-red 3.0.2 environment 
2. Create two flows as you can see in example flow
3. Use the different deploy modes and observe with a custom http middleware the payload size of the request
`httpAdminMiddleware: function(req,res,next) {

        if(req.url  === '/flows' ) {

                const flowSizeInBytes = req.headers["content-length"];

	        console.log(flowSizeInBytes / 1048576);

        }

        next();        

}`

### Example flow

Flow 1 (we inserted here a string blob 4 of megabytes)
![image](https://user-images.githubusercontent.com/123373946/219677275-5616f2a4-279b-4155-b924-8c32cc7d6158.png)
Flow 2
![image](https://user-images.githubusercontent.com/123373946/219677328-cee864de-c1a2-447c-8c9f-27c649ad852b.png)

Here you have the json with all flows to reproduce
[TEST FLOWS.zip](https://github.com/node-red/node-red/files/10767587/TEST.FLOWS.zip)

### Environment

- Node-RED version: 3.0.2
- Node.js version: 16.19.0
- npm version: 8.19.3
- Platform/OS: Ubuntu 20.04.5 LTS
- Browser: Google Chrome 110.0.5481.100

**Comment by hardillb** [comment]
This is expected behaviour, the work to determine what has changed and needs updating/restarting is done on the backend. The full flow will always be posted, not just the diff

**Comment by knolleary** [comment]
As @hardillb says, this is expected behaviour. All of the calculation of what needs to be restarted is done in the runtime.
