### ISSUE TITLE
Using "require" inside function nodes

### ISSUE THREAD

**Issue by maiorfi** [node-red/node-red#41]
Hi. Is it possible to import/require external modules within a function node?

Thanks!

**Comment by gbrian** [comment]
Just in case, this works for me:
```
functionGlobalContext: {
    require:require
}
```
Then in my function:
```
var require = global.get('require');
var request = require('request');
```
Node-RED version: v0.17.5

**Comment by carlosgonzalez** [comment]
Hey @gbrian ,
I've tried your suggestion but it doesn't work,

This is what I'm getting:
`"TypeError: require is not a function"
`

Any suggestion?

**Comment by dceejay** [comment]
Read @knolleary post first, including the links, then @gbrian

**Comment by gbrian** [comment]
@carlosgonzalez 
Testing with latest: node-red@0.17.5
Nodejs: v8.1.0

**Ok, this time is a bit tricky so there should be a reason for it and maybe this way must be discouraged.**

Answering your question, I managed by:

 * Adding this to `functionGlobalContext`

`module_require: require('./require.js')`

 * Creating a module `require.js` at the same place at the settings file:

`module.exports = {require:require}`

Usage:
`global.get("module_require").require('os')` 

I have to encourage you all to follow the official documentation as this way is totally unsupported.

**Comment by arobinsongit** [comment]
For those still following this you can use this node written by an old colleague

https://github.com/ntsaini/node-red-contrib-function-npm

I've used it extensively and it works very well.  Best recommendation is to put all of your requires in a single node then save off to the global context and pull them back down when you need them.  Otherwise, if you place requires any multiple nodes in your flow it will execute multiple downloads.

**Comment by akhilendharreddy** [comment]
> @carlosgonzalez
> I got the same error as you ("TypeError: require is not a function"), but then succeeded by just restart node-red after changing the setting.js file:
> functionGlobalContext: add this line:
> moment:require('moment'),
> 
> In my function node:
> var moment = global.get('moment');

I am facing issue after adding moment:require('moment'), in setting.js file, error: cannot find module 'moment', i have installed moment npm

**Comment by knolleary** [comment]
@akhilendharreddy that suggests you didn't install the moment module in the right location.

**Comment by akhilendharreddy** [comment]
> You cannot use `require` itself inside a function node, but you can add external modules to the sandbox used to run functions. This is done using the `functionGlobalContext` setting - have a look at the Global Context section of [this page](http://nodered.org/docs/writing-functions.html) to see an example of adding the `os` module.
> 
> (Technically, using this same technique I think you could add the `require` function to the sandbox and thereby use it as you wish... but I've not tried that)



> @akhilendharreddy that suggests you didn't install the moment module in the right location.
i have installed in my node-red project folder, can you suggest where do you want me to install

**Comment by hardillb** [comment]
The page linked to in that quote has the correct location. The Node-RED user dir -> `~/. node-red`

**Comment by etawyy** [comment]
Hi, 
I have the same issue but with a little difference. I need to have not just a require but also with variables (? beginner):
var ovh = require('ovh')({
  appKey: 'your_app_key',
  appSecret: 'your_app_secret',
  consumerKey: 'your_consumer_key'
});

This works perfectly fine on a local instance of node.js

With bluemix, I have added in bluemixsettings: 
functionGlobalContext: {
        ovh:require('ovh')({
            endpoint: 'ovh-eu',
            appKey: 'key',
            appSecret: 'key',
            consumerKey: 'key'
            })
    },

and in my function node I call: 
var ovh = global.get('ovh');
ovh.request('GET', '/sms', function (err, serviceName) (... etc etc )

when injecting, the node says: "TypeError: Cannot read property 'request' of undefined"
So ovh doesn't get defined properly, I guess.
I have tried to put the variable in the function node, no more success. "not a function"

Can anyone help? Thanks in advance.

**Comment by knolleary** [comment]
Hi @etawyy - please use the forum: https://discourse.nodered.org where the wider community will be able to help.

**Comment by etawyy** [comment]
Done here: https://discourse.nodered.org/t/using-require-in-bluemix-function-nodes/8005
Sorry and thanks.

**Comment by belbirdtech** [comment]
@gbrian Hi Gustavo your way of specifying the require in the settings.js file worked for me !! Thanks!
