### ISSUE TITLE
group env vars are lost after action "merge selection to group"

### ISSUE THREAD

**Issue by nixilb** [node-red/node-red#4101]
### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
I'm going to close this as it doesn't contain any useful information, without the details (e.g. what version of Node-RED you are using, or a proper description of the problem and how to reproduce it) there is nothing we can do to solve the problem.

Please open a new issue and complete all the values in the template.

**Comment by nixilb** [comment]
Of course you can close! Close all you want! you just makes the community miss the opportunity to get a bug fixed. And you're saying me not to spend some time to fill the issue next time.
The title is self explaining: make a group, add env vars to it. Add a node outside the group. Select both and choose "merge selection to group": all env vars are lots in the newly created group.

**Comment by nixilb** [comment]
I know. As I am a Redmine / Bugzilla / Jira user I know the usual questions. But the more you ask, the less bug reports you'll get....
