### ISSUE TITLE
Documentation for how to set environment eariables is wholy since version 3x 

### ISSUE THREAD

**Issue by ewrayjohnson** [node-red/node-red#4107]
### Current Behavior

All documentation on how to set environment variables is OBE as of version 3.x.  
For example see:  https://flows.nodered.org/flow/8a13d11dfe80e279df83341e3e17bcc1

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.x

**Comment by knolleary** [comment]
Sorry, what do you mean by OBE?

The actual documentation for working with environment variables is here: https://nodered.org/docs/user-guide/environment-variables

**Comment by knolleary** [comment]
I've just seen your comment on the other issue.

You are looking to community generated content, not documentation we

**Comment by ewrayjohnson** [comment]
OBE = Abbreviation for Overcome By Events or Overtaken By Events.

**Comment by ewrayjohnson** [comment]
Since version 3 I can't set environment variables via node startup using VSCode launch.json via env property.  This worked in version 2.2
