### ISSUE TITLE
Improve: separete flows.json

### ISSUE THREAD

**Issue by temkagordin** [node-red/node-red#4116]
I have a problem related to the size of the flows.json file. It contains 165k lines of source code, and it's becoming difficult to check changes. Do you think it's possible to split this file into flows (possibly subflows) to avoid keeping all sources in one file?

**Comment by knolleary** [comment]
Hi @temkagordin 

As per the issue template, please use the discussion forum for feature requests/questions.

We have an item on the backlog for being able to split the flow file. I do not have an outlook for when that will be done.
