### ISSUE TITLE
write file node writes an incorrect number of bytes

### ISSUE THREAD

**Issue by 99TonyStark99** [node-red/node-red#4117]
When using the write file node to write a binary file, not all the bytes get written. I'm using this to save icons that a user uploads through the dashboard. The number of bytes lost seems to be somewhat random.  

Here is a pared-down set of nodes that will reproduce the issue.

`[
    {
        "id": "37acd7468446dffc",
        "type": "file",
        "z": "031b019836f1d159",
        "name": "",
        "filename": "filename",
        "filenameType": "msg",
        "appendNewline": false,
        "createDir": false,
        "overwriteFile": "true",
        "encoding": "binary",
        "x": 880,
        "y": 1440,
        "wires": [
            []
        ]
    },
    {
        "id": "e3c2cae708e4ddc5",
        "type": "debug",
        "z": "031b019836f1d159",
        "name": "debug 8",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 880,
        "y": 1400,
        "wires": []
    },
    {
        "id": "46915de216d4d19b",
        "type": "function",
        "z": "031b019836f1d159",
        "name": "make file",
        "func": "\nvar i=0;\nconst buff =Buffer.alloc(1024);\n\n    for(i=0; i<1024; i++)\n    {\n        buff[i]=Math.floor(Math.random() * 256);\n    }\n\nmsg.payload=buff;\n\nmsg.filename = \"/home/pi/\" + msg.filename;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 660,
        "y": 1440,
        "wires": [
            [
                "37acd7468446dffc",
                "e3c2cae708e4ddc5"
            ]
        ]
    },
    {
        "id": "4cd3df66eb75ebad",
        "type": "inject",
        "z": "031b019836f1d159",
        "name": "",
        "props": [
            {
                "p": "filename",
                "v": "testfile.bin",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 470,
        "y": 1440,
        "wires": [
            [
                "46915de216d4d19b"
            ]
        ]
    }
]`

As you can see, I'm creating a buffer with 1024 random values.  You can see in the debugging window that there are 1024 bytes in it when you press the inject node:

![Screenshot from 2023-03-28 12-31-20](https://user-images.githubusercontent.com/34138790/228307523-80a119a6-ca87-4b05-9f80-42aeba4f5c9e.png)

here is a listing of the file ( 5 times)
```-rw-r--r--. 1 pi pi 975 Mar 28 12:20 testfile.bin
[pi@localhost ~]$ ls -la t*
-rw-r--r--. 1 pi pi 963 Mar 28 12:28 testfile.bin
[pi@localhost ~]$ ls -la t*
-rw-r--r--. 1 pi pi 978 Mar 28 12:28 testfile.bin
[pi@localhost ~]$ ls -la t*
-rw-r--r--. 1 pi pi 972 Mar 28 12:28 testfile.bin
[pi@localhost ~]$ ls -la t*
-rw-r--r--. 1 pi pi 975 Mar 28 12:28 testfile.bin
[pi@localhost ~]$ 
```
as you can see, something is clearly wrong (and quite possibly it's me)

**Comment by dceejay** [comment]
The node should do the right the thing with a buffer... if the encoding is set to default... does it ???

**Comment by 99TonyStark99** [comment]
Thanks for taking the time to look at this.  I'm sure you've got lots better things to work on.

I switched it to default and it's working!  

So, out of curiosity just what is binary mode for?

Thanks,
Bart
