### ISSUE TITLE
http request node: connect ECONNREFUSED

### ISSUE THREAD

**Issue by normanth** [node-red/node-red#4118]
### Current Behavior

I get a connection refused error if I make a simple local GET-call with the "http request" node. Call from shell or browser are working. Other URLs are working.

Url: http://ds.fritz.box:8080 (another server in local network with docker image from webdevops/php-apache-dev)
If I call the url from my browser on my PC: everything ok (returns string "Code:")
If I call the url from the node-red Raspberry with curl from the shell: everything ok (returns string "Code:")
```
ha2:~ $ curl http://ds.fritz.box:8080
Code:
```

If I call the url from "http request" node:
`RequestError: connect ECONNREFUSED 2003:d5:b709:xxxxxxxxx:fe26:79ad:8080`

Call with IP ist working. Is this a problem with IPv6?
My other Raspberry with an older version works correct.

### Expected Behavior

I expect my connection will not be rejected.

### Steps To Reproduce

I can't say exactly because other url calls and the call from the shell are working.

### Example flow

```
[
    {
        "id": "b0158853c424fe9e",
        "type": "inject",
        "z": "9892f29b83a551de",
        "name": "",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 170,
        "y": 280,
        "wires": [
            [
                "380c9f9555d1b26e"
            ]
        ]
    },
    {
        "id": "380c9f9555d1b26e",
        "type": "http request",
        "z": "9892f29b83a551de",
        "name": "",
        "method": "GET",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://ds.fritz.box:8080",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers": [],
        "x": 390,
        "y": 280,
        "wires": [
            []
        ]
    }
]
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.15.0
- npm version: 9.5.0
- Platform/OS: Raspberry Pi 4 (Raspberry Pi OS Lite (64-bit) Debian Bullseye)
- Browser: Chrome

- Server to call: Docker Image from webdevops/php-apache-dev

**Comment by hardillb** [comment]
You can test with curl by adding `-6` to the command line

**Comment by normanth** [comment]
Thanks you for your input!

curl -v6 http://ds.fritz.box:8080 doesn't work - Connection refused

Ok - it's a v6 problem - maybe related to docker...

But why use the "http request" node v6? Is it possible to use v4?

Thanks, Norman

**Comment by hardillb** [comment]
Most likely you have changed NodeJS version to v18 https://github.com/nodejs/node/pull/39987 which now will always use IP addresses in order returned by the DNS, where as the older versions used to sort the IPv4 addresses first.

The correct solution is to update your docker configuration to ensure that ports are forwarded for both IPv4 and IPv6
