### ISSUE TITLE
Websocket holding configs from deleted flows

### ISSUE THREAD

**Issue by anupam19** [node-red/node-red#412]
Started exploring websocket and seen if one websocket is configured previously and deleted after deploy, then again click deploy, then actually it holds configurations in websocket nodes. Even after closing node red it holds previous configurations from deleted flows. I am not sure it is bug or not but felt like it should not be like that.

**Comment by knolleary** [comment]
The latest release, 0.10.10, now includes a warning if you are deploying with an unused config node, so I think we can finally close this issue.
