### ISSUE TITLE
Incorrectly reporting times in Mexico (still thinks we use daylight savings time)

### ISSUE THREAD

**Issue by AlmostInteractive** [node-red/node-red#4123]
### Current Behavior

NR is reporting Mexico time one hour off than the real time.  Both HA web interface and SSH show the time (currently) as 22:53:58, for example, but NR is recording events at 23:53:58 instead.

This is the first year we did not switch to DST but NR is acting like we did.  Perhaps it's using an old package for managing time that has the incorrect information.

### Expected Behavior

NR date and time match system/HA date and time.

### Steps To Reproduce

Set your system to "America/Mexico_City" time zone and see the discrepancy. 

### Example flow

N/A

### Environment

- Node-RED version: 14.1.3

**Comment by bonanitech** [comment]
By the version number, I believe you're using the Node-RED add-on for Home Assistant. Its documentation has a section about time zone configuration (link below).

https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#time-zone-configuration

**Comment by Steve-Mcl** [comment]
This will likely be because your Linux OS (the one running inside docker, that was setup by home assistant) will have outdated `tzdata`

This has nothing to do with node-red itself (more of an operating system thing).

**Comment by AlmostInteractive** [comment]
I think either I didn't understand or that evaluation is not correct.  NR has been running in sync with the OS clock up until just recently (when Mexico _would have_ changed to DST but, as we don't do that anymore, we didn't).

I had already applied the "timezone fix" and it did not change Node Red's time reckoning:
![image](https://user-images.githubusercontent.com/3893631/230437984-1f21394d-dc78-4452-accd-d6920effb1b0.png)
It didn't change the time that NR was reporting, which is actually a good thing.

Checking `date ` on the linux host gives the correct time:
![image](https://user-images.githubusercontent.com/3893631/230439627-64f14637-d8bf-401e-9382-47a14c27267d.png)

Checking the date in HA logs gives the correct time:
![image](https://user-images.githubusercontent.com/3893631/230440069-27aa70cb-ed1f-4a0d-a51b-0a21415c8c3c.png)

Node Red (and no other addon) gives the incorrect time (ie: what the time would have been exactly one year ago before Mexico stopped using DST):
![image](https://user-images.githubusercontent.com/3893631/230439946-546fbbb8-0d25-40bf-9321-3b20e2d833a6.png)

**Comment by hardillb** [comment]
All of the timezone information comes from the environment Node-RED runs in, most HA users run in NR is a container provided by HA not the host OS.

Assuming you are running the container then that will need to have the latest timezone database, the NR team have no input into that container.

As such the correct place to get help is the HA Node-RED plugin project

**Comment by AlmostInteractive** [comment]
Okay.  I understand.  Thanks.
