### ISSUE TITLE
Safari doesn't show every setting in property Editor

### ISSUE THREAD

**Issue by FlorianRueb** [node-red/node-red#4136]
### Current Behavior

Opening the property dialog of a random node doesn't show every settings field.

### Expected Behavior

Open a property dialog, edit the settings fields, reopen the dialog > see what you've done.

### Steps To Reproduce

Take a new flow, take a HTTP request node, open the property dialog, set up "GET" and "a UTF-string" as return, confirm the dialog.
Then open up the dialog again and see: no method and no return to see!

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 19.9.0
- npm version: 9.6.3
- Platform/OS: DietPi v8.16.2 (Node-RED Host) / macOS 13.3.1 (Client)
- Browser: Safari Version 16.4 (18615.1.26.11.23)

**Comment by marcus-j-davies** [comment]
I can confirm I have the same behaviour (have tested File Write, and the HTTP Request Node)

Node RED: 3.0.0
Safari 16.4 (18615.1.26.11.23)

File Write Demo
![dc417d47e37f40c60e3f696703af4838488f574a](https://user-images.githubusercontent.com/55892693/231251530-35c6e630-0462-4f7d-8f9c-8c1fdc732cde.gif)

**Comment by Steve-Mcl** [comment]
@marcus-j-davies are you also running node v19?
Also, I note you are on safari 16.4. Isn't that in beta? (I'm not an apple user but I have a recollection that 16.3 is current version?)

@FlorianRueb can I ask why you are running a non LTS version of NODE please?  Typically we recommend the LTS version of node (we do not test against odd numbered versions of node)

**Comment by marcus-j-davies** [comment]
Sorry, should have put Node version.

Node V - v16.15.1

Safari 16.4 is stable/current (comes with OSX)
16.5 is the BETA at this stage.

**Comment by FlorianRueb** [comment]
But it must be more nodes.
I can find the problem also in the file read node and the edit json node for example... and the delay node.

**Comment by ralphwetzel** [comment]
Lots of speculation here; I'll add another one - which is as well visible in the example Marcus posted: **The focus is jumping around wildly.**

When double clicking on the node, initially 'Nodes filtern' at the top of the left hand palette is focused, then the focus jumps on the incoming property window ... and thus eliminates - sometimes !! - the selection: The third time (in the example below) the value **is** displayed in the select element.


![FocusIssue4](https://user-images.githubusercontent.com/16342003/231284534-acaeaef9-f252-4d9c-bb02-a0800a62ed1e.gif)

@marcus-j-davies 
> boom! it become blank when opening it up again.

No really. With a sharp eye on your screen cast, you can see that the values are present, when the window is incoming ... but then changed!

**Comment by ralphwetzel** [comment]
I see the exactly same behavior with the `beta.1` & `beta.2`.
Safari @ 16.4

**Comment by Steve-Mcl** [comment]
> Has this been an issue since Safari 16.4 🤷‍♂️.
> 
> Have only just noticed it - since its orginal report

My thoughts entirely. Would be good if someone still on 16.3 could check.

**Comment by FlorianRueb** [comment]
> Lots of speculation here; I'll add another one - which is as well visible in the example Marcus posted: **The focus is jumping around wildly.**
> 
> When double clicking on the node, initially 'Nodes filtern' at the top of the left hand palette is focused, then the focus jumps on the incoming property window ... and thus eliminates - sometimes !! - the selection: The third time (in the example below) the value **is** displayed in the select element.
> 
> ![FocusIssue4](https://user-images.githubusercontent.com/16342003/231284534-acaeaef9-f252-4d9c-bb02-a0800a62ed1e.gif) [ ![FocusIssue4](https://user-images.githubusercontent.com/16342003/231284534-acaeaef9-f252-4d9c-bb02-a0800a62ed1e.gif) ](https://user-images.githubusercontent.com/16342003/231284534-acaeaef9-f252-4d9c-bb02-a0800a62ed1e.gif) [ ](https://user-images.githubusercontent.com/16342003/231284534-acaeaef9-f252-4d9c-bb02-a0800a62ed1e.gif)
> 
> @marcus-j-davies
> 
> > boom! it become blank when opening it up again.
> 
> No really. With a sharp eye on your screen cast, you can see that the values are present, when the window is incoming ... but then changed!

Oh, maybe it has something to do with that thing, where you open a function node, click inside the code and get many lines selected. I'll try to make a screen capture...


https://user-images.githubusercontent.com/92776919/231294197-8f9d418b-d348-4e4f-8268-8a30550cb7f3.mov

**Comment by marcus-j-davies** [comment]
> > Has this been an issue since Safari 16.4 🤷‍♂️.
> > Have only just noticed it - since its orginal report
> 
> My thoughts entirely. Would be good if someone still on 16.3 could check.

Safari 15.6.1  : The problem **does not** appear to be apparent.

It maybe note worthy, my 15.6.1 safari is on an x86 processor (its a fairly dated Mac), and my 16.4 safari is using Apple Silicon.

Unless there are some `wasm` modules in use with all this? - I can't imagine that will make any difference, but thought I'd mention it

**Comment by marcus-j-davies** [comment]
And with that.

Here are the change logs for Safari 16.4
https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes <- Needle in here somewhere

**Comment by deqw** [comment]
When I have the node properties open and then change MacOS to Dark Mode (or to Light from Dark) the captions reappear, but not the properties itself. After closing and opening the properties again the captions are gone again.

**Comment by kremik** [comment]
Having the same problem with Node-red 3.0.2 and Safari 16.4. If I open Node Red in Brave/chrome Browser then it works fine

**Comment by Steve-Mcl** [comment]
It seems this issue may be resolved with safari 16.5. Can one other person please confirm?

**Comment by marcus-j-davies** [comment]
I cant test right now, as haven't updated to latest OS

But!
https://developer.apple.com/documentation/safari-release-notes/safari-16_5-release-notes



![Screenshot 2023-05-22 at 21 48 28](https://github.com/node-red/node-red/assets/55892693/6563a10a-a90b-43ba-a1ab-27d01006414b)

Could be related 🤷‍♂️

**Comment by dceejay** [comment]
Yes - 16.5 fixes it for me.

**Comment by Steve-Mcl** [comment]
Thank for confirming. Closing this issue.

**Comment by deqw** [comment]
But not for me. Still empty properties in the forms. Running maxOS Ventura 13.4 (22F66) on Apple M2 Pro.

![Screenshot 2023-05-25 at 15 22 42](https://github.com/node-red/node-red/assets/65849349/1046d016-3384-4e39-b390-c9c30d39b03f)
![Screenshot 2023-05-25 at 15 23 51](https://github.com/node-red/node-red/assets/65849349/20b3247f-ded4-46d3-bfd4-2f7e38c55487)
