### ISSUE TITLE
TCP in Node auto respons [72,67,202,1,1,...]

### ISSUE THREAD

**Issue by bjdaijun** [node-red/node-red#4139]
### Current Behavior

And if I connect to tcp in node, It‘s will send back some bytes to client. But these data not from my configs.

### Expected Behavior

Client do not receive any data when not send data by hand.

### Steps To Reproduce

use this config, and node debug68 will receive these bytes  repeatedly.

### Example flow

```
[
    {
        "id": "19d8c6fadea93ef9",
        "type": "tab",
        "label": "tcp-test",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "1787daf384b3888d",
        "type": "tcp in",
        "z": "19d8c6fadea93ef9",
        "name": "",
        "server": "server",
        "host": "",
        "port": "28001",
        "datamode": "stream",
        "datatype": "buffer",
        "newline": "",
        "topic": "",
        "trim": false,
        "base64": false,
        "tls": "",
        "x": 240,
        "y": 160,
        "wires": [
            [
                "741ee8031febd4d5"
            ]
        ]
    },
    {
        "id": "ace10560e9081352",
        "type": "debug",
        "z": "19d8c6fadea93ef9",
        "name": "debug 67",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 420,
        "y": 160,
        "wires": []
    },
    {
        "id": "566014e0c80e8a46",
        "type": "tcp out",
        "z": "19d8c6fadea93ef9",
        "name": "",
        "host": "",
        "port": "",
        "beserver": "reply",
        "base64": true,
        "end": false,
        "tls": "",
        "x": 510,
        "y": 260,
        "wires": []
    },
    {
        "id": "741ee8031febd4d5",
        "type": "function",
        "z": "19d8c6fadea93ef9",
        "name": "function 21",
        "func": "",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 330,
        "y": 240,
        "wires": [
            [
                "566014e0c80e8a46"
            ]
        ]
    },
    {
        "id": "540233ccc27276ee",
        "type": "tcp in",
        "z": "19d8c6fadea93ef9",
        "name": "",
        "server": "client",
        "host": "iot.mapchang.com",
        "port": "28001",
        "datamode": "stream",
        "datatype": "buffer",
        "newline": "",
        "topic": "",
        "trim": false,
        "base64": false,
        "tls": "",
        "x": 280,
        "y": 380,
        "wires": [
            [
                "ccaa2e6ab665534b"
            ]
        ]
    },
    {
        "id": "ccaa2e6ab665534b",
        "type": "debug",
        "z": "19d8c6fadea93ef9",
        "name": "debug 68",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 560,
        "y": 380,
        "wires": []
    }
]

```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 
- npm version:
- Platform/OS: ubuntu
- Browser: chrome

**Comment by Steve-Mcl** [comment]
> And if I connect to tcp in node, It‘s will send back some bytes to client. But these data not from my configs.

Whatever device is on the end of `iot.mapchang.com:28001`, it is clearly sending this data: 

![image](https://user-images.githubusercontent.com/44235289/232455253-0add89e2-a300-436c-b462-28252647b10a.png)


Therefore the TCP node is working as expected.

<br> 

If you need help using node-red, please head to the forum. The issue board is for reporting bugs.

Thanks, Steve.

**Comment by Steve-Mcl** [comment]
Closing issue. Please re-open or comment if you still believe this to be a Node-RED problem.

**Comment by bjdaijun** [comment]
> Closing issue. Please re-open or comment if you still believe this to be a Node-RED problem.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/1940592/232644425-91b3fe22-4b46-4344-b3e6-5fdc4c34faa8.png">

Thank you for your reply. But I still can't got the point. As you see, The node TCP:28081  IS  the device that the next node tcp:iot.mapchant.com:28081  connected to. And the data is send out by  the tcp in node (TCP:28081) . But as you see, The Node TCP:28081 send nothing  in the function node. But  the Node(tcp:iot.mapchang.com:28081) received these data.

So why TCP:28081  send these data internally?

**Comment by hardillb** [comment]
But the tcp node that is only connected to the debug node is NOT connecting to the tcp-in -> function -> tcp-out flow. This can be seen because there is not "connected 1" status under the tcp-in node.

This means that `iot.mapchang.com` is not resolving to the machine that Node-RED is running on. So what ever is listening on port 28001 on that machine is sending the data, not Node-RED.

If you change the hostname in the bottom tcp node to localhost you should see the connection and no data being sent

**Comment by bjdaijun** [comment]
It turns out that in other flow ,there is a tcp-out-response  node ,timerly activated and it send that data.
Like these 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1940592/232733118-28e9fe24-00ac-4d74-b164-c385095ded33.png">

After remove it, all tcp nodes return clean status.

Thanks for help.
