### ISSUE TITLE
MQTT: Last Will massage from payload

### ISSUE THREAD

**Issue by mjan-pxcd** [node-red/node-red#4144]
### Current Behavior

mqtt messages for unexpected disconnection cannot be written from a payload. Only text messages can be entered in the message field in the mqtt server configuration. 

A payload can be transferred when a connection is established. When the connection is terminated, only the string from the config is transferred.

### Expected Behavior

I would like to be able to describe the mqtt messages for unexpected disconnection from a payload. 

### Steps To Reproduce

Try to send a last will message from payload with mqtt. 

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by dceejay** [comment]
The LWT is setup as part of the connect message. So the payload can’t be used for both the connect “birth” message and set the lwt.

**Comment by knolleary** [comment]
If the node is set for dynamic configuration - where you pass it a message to give it all of the connection details, then it is possible to dynamically set the will message. A message something like this... @Steve-Mcl may need to dbl check the fine details...
```
{
   action: 'connect',
   broker: {
      willTopic: 'a topic',
      willPayload: 'a payload',
      willQos: 0
   }
}
```

**Comment by knolleary** [comment]
@mjan-pxcd does my comment about help?

Given this isn't a bug with the node, I'm going to close the issue. For future reference, please use the forum as discourse.nodered.org to raise any feature requests you may have.

**Comment by mjan-pxcd** [comment]
@knolleary yes it's help. Thanks for that.
