### ISSUE TITLE
Error: node not deployed. marantz avr in node-red.

### ISSUE THREAD

**Issue by manishsuperhome** [node-red/node-red#4160]
I have configured a flow for marantz. But, whenever I inject the node, it shows the Error: node not deployed.

![image](https://user-images.githubusercontent.com/118502228/236108560-6e041e55-8ae0-42cc-b68d-0abf1028adc8.png)

**Comment by knolleary** [comment]
Hi @manishsuperhome 

That is not a core Node-RED node, so not something we provide support for on this issue list.

What module did you install to get that node?

**Comment by knolleary** [comment]
Closing as this isn't a core Node-RED node. We can point you in the right direction if you provide more information on what nodes you are using.
