### ISSUE TITLE
Incorrect file extension when downloading flow on iPad

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#4161]
### Current Behavior

When users download the "flows.json" file on their iPad, the file has an incorrect file extension like "flows.json.txt".

![IMG_2866](https://user-images.githubusercontent.com/20310935/236620441-8ce3060c-570a-47e2-8dc5-8ec3f7e934ec.PNG)

As a result, downloaded flow files cannot be uploaded using the "select a file to import" button in the Import nodes dialog on the iPad.

### Expected Behavior

The file name should also be "flows.json" on iPad.

### Steps To Reproduce

1. Create a flow
2. Select "Export" from the menu
3. Click the "Download" button

### Environment

- Node-RED version: v3.0.2
- Node.js version: v18.12.1
- npm version: v8.19.2
- Platform/OS: macOS Ventura 13.3.1 (a) on MacBook Air (M1, 2020)
- Browser: Safari on iOS 16.4.1 (a), iPad (7th generation)

**Comment by andesse** [comment]
I habe an iPad as well. I think it’s more likely an iPadOS related thing. The System probably wants a file extension that it knows, it identifies the .json context as text and add the .txt

It will still open the file in Pages, you’re just not able to import the file directly. You need to copy paste the text. 

I wouldn’t consider as a Node-RED problem.
