### ISSUE TITLE
Connection not working:  Connection closed to http://supervisor/core

### ISSUE THREAD

**Issue by xteaun** [node-red/node-red#4167]
I cannot get Node-RED to work. 

>10 May 18:28:52 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
>10 May 18:28:52 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
>10 May 18:28:57 - [info] [server:Home Assistant] Connecting to http://supervisor/core
>10 May 18:28:57 - [info] [server:Home Assistant] Connected to http://supervisor/core

What can the problem be? I tried reinstalling Node-RED and rebooting Home Assistant. No change.

Christian

**Comment by knolleary** [comment]
Hi,

We do not maintain the home assistant nodes so cannot help with this question.

Please ask on either the HA forum or Node-RED forum.
