### ISSUE TITLE
Version disclosed in /theme response

### ISSUE THREAD

**Issue by rekcaiot** [node-red/node-red#4170]
### Current Behavior

When doing requests to the /theme path, the payload discloses the current Node-RED version.

Requested URL:
https://localhost:1880/theme

Response payload:
"version":"3.0.2"

`{"page":{"title":"Node-RED","favicon":"favicon.ico","tabicon":{"icon":"red/images/node-red-icon-black.svg","colour":"#8f0000"},"version":"3.0.2"},"header":{"title":"","image":"red/images/node-red.svg","url":""},"asset":{"red":"red/red.min.js","main":"red/main.min.js","vendorMonaco":"vendor/monaco/monaco-bootstrap.js"},"themes":[]}`

### Expected Behavior

The disclosure of version or system information allows attackers to conduct a selective search in
vulnerability databases. The obtained information can then be used as a basis for attacks.
It is recommended not to disclose any information about the system or available services. 

Is it possible for you to remove the version?

### Steps To Reproduce

Call the given url and look at the response payload.

### Environment

- Node-RED version: v3.0.2
- Node.js version: v16.20.0
- npm version: -
- Platform/OS: Linux / Docker
- Browser: Edge / Firefox

**Comment by knolleary** [comment]
I cannot immediately find anything that makes use of the `version` value returned by the `/theme` endpoint - so it should be safe to remove.

We also include it in the `/settings` endpoint - but you have to be authenticated to access that (if you have `adminAuth` enabled). We use that value in multiple places within the editor, so it is required there.

**Comment by knolleary** [comment]
> I cannot immediately find anything that makes use of the version value returned by the /theme endpoint - so it should be safe to remove.

Took 7 months, but I found what was using that value; it is used as part of the cache-busting logic to ensure the browser loads the new version of our assets.

It gets appended to the urls here: https://github.com/node-red/node-red/blob/f0a9b0cf69646177755203a11415982dfa83b87e/packages/node_modules/%40node-red/editor-client/templates/index.mst#L43 which is part of the initial page load that is not authenticated.

The idea is each new release causes the url to change so the browser is forced to reload the assets and not use cached versions. We've now had users impacted by this change - see #4503

We could hash the value to provide some obscurity - but the whole purpose of this is to have a static value that only changes on a new release. So there would always be a 1:1 mapping of `?v=` value to a version - so a determined attacked would simply need to know what value maps to what version and you're no better off.

To be frank, the cache-busting functionality is more important here, so perhaps a bit of obscurity is better than nothing.
