### ISSUE TITLE
Can't go fullscreen using keyboard shortcut on a Mac

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#4204]
### Current Behavior

On a Mac, the keyboard shortcut for "Enter Full Screen" is ctrl-cmd-f.

On Node-RED, this triggers Search. So we need to use the shortcut twice to bring the browser to full screen.

### Expected Behavior

"Enter Full Screen" using the keyboard shortcut.

### Steps To Reproduce

Open Node-RED and press ctrl-cmd-f

### Environment

- Node-RED version: 3.0.2
- Node.js version: v16.16.0
- npm version: 8.11.0
- Platform/OS: macOS Ventura 13.4
- Browser: Chrome, Safari, and Firefox

**Comment by Steve-Mcl** [comment]
Hi @bonanitech I cannot confirm this by testing (since I do not own any apple products) but looking at the code, I can not see why that particular shortcut is not working. It is specifically handled.

https://github.com/node-red/node-red/blob/5d698d66d0857e65b08be41b212b7bcafe5f8261/packages/node_modules/%40node-red/editor-client/src/js/ui/keyboard.js#L245-L254


Perhaps you could add some console logs to `packages/node_modules/@node-red/editor-client/src/js/ui/keyboard.js` around line 244:

```
    function resolveKeyEvent(evt) {
        console.log('resolveKeyEvent', evt) // << add logging
        var slot = partialState||handlers;
```

and show us what you see when operating this shortcut?

**Comment by bonanitech** [comment]
First use of the shortcut.

![SCR-20230529-papl](https://github.com/node-red/node-red/assets/29807944/b85d3b80-35c2-44a7-9ca1-70604c9100ca)

If I use the shortcut again, the browser goes full screen.

![image](https://github.com/node-red/node-red/assets/29807944/60f8aac6-0926-4727-af8e-bc00f5f56e05)

**Comment by bonanitech** [comment]
I just noticed that it works as expected if I click the palette or the sidebar first and then use the shortcut.

![image](https://github.com/node-red/node-red/assets/29807944/9ea81f19-8cc5-4c05-9c16-2a400d56e9c5)

**Comment by Steve-Mcl** [comment]
@bonanitech would you be able to perform a test for me?

add the blow code to `function resolveKeyEvent`

```js
        if (evt.ctrlKey && evt.metaKey) {
            return null;
        }
```

Should look like this:
![image](https://github.com/node-red/node-red/assets/44235289/72c62a93-6564-49ce-945f-a2206be8c930)


Restart node-red, refresh browser, test shortcuts with both CMD+CTRL

I suspect there is no "escape route" for when both CMD+CTRL are pressed, so the code not setting any `slot` and is therefore returning the handler for `"f"` (find next by default)

**Comment by bonanitech** [comment]
@Steve-Mcl, thanks for taking the time to investigate this issue further. That code seems to have fixed it.

**Comment by Steve-Mcl** [comment]
Thank you @bonanitech
