### ISSUE TITLE
Timestamp option in output properties doesn't use predefined timezone

### ISSUE THREAD

**Issue by cniry** [node-red/node-red#4211]
### Current Behavior

I'm using Node-RED in Home Assistant from official add-ons. Node-RED displays correct times in flows (under nodes), but when I choose to fill some output value by timestamp in  `Current state` node, it didn't respect my timezone, so it returns incorrect timestamp.

![image](https://github.com/node-red/node-red/assets/2609142/1398495e-1dea-4fd6-bf88-cc36499f4f14)

### Expected Behavior

Option `Timestamp` should use the same timezone as other parts of Node-RED.

### Environment

- Node-RED version: 3.0.2
- Node.js version: I don't know
- npm version: I don't know
- Platform/OS: Home Assistant official add-on

**Comment by Steve-Mcl** [comment]
This node screenshot is not a Node-RED core node and we do not maintain it. 

You will need to raise this with the HA team.

**Comment by cniry** [comment]
Ah, sorry, I didn't know that. I will crate it in HA, thank you.
