### ISSUE TITLE
MQTT in ignores msg.url and msg.broker parameters

### ISSUE THREAD

**Issue by andrea-tomassi** [node-red/node-red#4214]
### Current Behavior

An MQTT In node works well if configured by web gui properties panel.
If you disable automatic connection and uses an msg.action=connect input, passing msg.broker & msg.port OR msg.url (with the same parameters from the panel) is not going to connect.

### Expected Behavior

the url should be passed by msg params

### Steps To Reproduce

just disable "connect automatically" and trigger the "connect" by inject node.
Pass to the MQTT In node the following:

msg.action=connect
msg.url=< - a valid broker - >:< - a valid port - >

OR

msg.action=connect
msg.broker=< - a valid broker ->
msg.port=< - a valid port - >

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 
- npm version: 
- Platform/OS: ubuntu 22
- Browser: Chrome / Firefox

**Comment by Steve-Mcl** [comment]
Hi @andrea-tomassi it seems you have interpreted the built in help incorrectly. Please head to the Node-RED forum where there are several working examples of how to do this correctly.

Here is one such example: https://discourse.nodered.org/t/dynamic-mqtt-nodes-actions-connect-guidance-needed/58878/2?u=steve-mcl

**Comment by andrea-tomassi** [comment]
Hi @Steve-Mcl,

thanks a lot! Looking at your example I could understand my mistake.
The "broker" title from inline docs is actually not a title, but an actual root path for the properties.

![image](https://github.com/node-red/node-red/assets/4680279/8c42c7d1-6fe0-4be3-82db-dc6cb8f928e3)

The CORRECT keys should be in the following form instead:

`msg.broker.broker=< - a valid broker - > `
instead of mine (WRONG): 
`msg.broker=< - a valid broker - > `


And this is very clear if you look at the example you linked to me:
![image](https://github.com/node-red/node-red/assets/4680279/1261f3a5-664e-481b-9ba0-bcce82c433b1)

I couldn't catch this from docs, on the other hand your example has been great!

Not sure if adding a one-liner example in the doc could be helpful for other peolple, however this is definitely not a runtime issue.

I'm closing it, ty so much.
