### ISSUE TITLE
Can't make requests to Node-RED with nc since 3.0

### ISSUE THREAD

**Issue by ilya-fedin** [node-red/node-red#4216]
### Current Behavior

```
     echo -e "GET /usbip-attach/192.168.1.118/1-1 HTTP/1.1\n" | nc 192.168.1.254 1880
HTTP/1.1 400 Bad Request
Connection: close
Date: Sat, 10 Jun 2023 07:45:48 GMT
Transfer-Encoding: chunked

0
```

### Expected Behavior

Success

### Steps To Reproduce

See current behavior.

I make requests from a device with 4 MB ROM, so I can't install full-featured http client like curl or wget.

### Example flow

```
[
    {
        "id": "30f79fb83f339c9b",
        "type": "http in",
        "z": "bddb751fe2c7781a",
        "name": "",
        "url": "/usbip-attach/:ip/:busid",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 140,
        "y": 260,
        "wires": [
            [
                "0209019e3e06d412"
            ]
        ]
    },
    {
        "id": "0209019e3e06d412",
        "type": "function",
        "z": "bddb751fe2c7781a",
        "name": "",
        "func": "msg.payload = `-r ${msg.req.params.ip} -b ${msg.req.params.busid}`;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 340,
        "y": 260,
        "wires": [
            [
                "2c1ff0ddc2268206"
            ]
        ]
    },
    {
        "id": "2c1ff0ddc2268206",
        "type": "exec",
        "z": "bddb751fe2c7781a",
        "command": "sudo systemd-run usbip attach",
        "addpay": "payload",
        "append": "",
        "useSpawn": "false",
        "timer": "",
        "winHide": false,
        "oldrc": false,
        "name": "",
        "x": 550,
        "y": 260,
        "wires": [
            [],
            [
                "0b2b57209ddbefeb"
            ],
            []
        ]
    },
    {
        "id": "0b2b57209ddbefeb",
        "type": "http response",
        "z": "bddb751fe2c7781a",
        "name": "",
        "statusCode": "",
        "headers": {},
        "x": 750,
        "y": 260,
        "wires": []
    }
]
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 20.2.0
- npm version: 8.19.2
- Platform/OS: Arch Linux
- Browser: nc

**Comment by Steve-Mcl** [comment]
I don't think this is a big with node-red v3.x but perhaps something is a bit more strict. 

Typically, a valid http request must end with 2 blank lines. 

Try adding `\n\n` to the end of the instead of one like you currently have.

**Comment by ilya-fedin** [comment]
> Try adding `\n\n` to the end of the instead of one like you currently have.

Doesn't help :(

**Comment by hardillb** [comment]
Also what is the output of the exec node, since we are unlikely to have the usbip service or the hardware to test this with locally.

And to expand on @Steve-Mcl's point valid HTTP requests should end with `\r\n\r\n`

**Comment by ilya-fedin** [comment]
Well, you can replace it with random command, the problem is node-red doesn't accept the request

**Comment by ilya-fedin** [comment]
> And to expand on @Steve-Mcl's point valid HTTP requests should end with `\r\n\r\n`

This doesn't help either :(

**Comment by ilya-fedin** [comment]
Note that echo adds a `\n` automatically unless `-n` is specified, so the output of the echo in initial command ends with `\n\n` actually.

**Comment by hardillb** [comment]
```
[
    {
        "id": "93c3368d800a0ec7",
        "type": "http in",
        "z": "c65b467adae4a92e",
        "name": "",
        "url": "/foo/:ip",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 170,
        "y": 440,
        "wires": [
            [
                "d0f60ded5e0209cf"
            ]
        ]
    },
    {
        "id": "e8ca3bd33bade3ed",
        "type": "http response",
        "z": "c65b467adae4a92e",
        "name": "",
        "statusCode": "",
        "headers": {},
        "x": 490,
        "y": 440,
        "wires": []
    },
    {
        "id": "d0f60ded5e0209cf",
        "type": "function",
        "z": "c65b467adae4a92e",
        "name": "function 1",
        "func": "msg.payload = `test ${msg.req.params.ip}`\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 340,
        "y": 440,
        "wires": [
            [
                "e8ca3bd33bade3ed",
                "2939a8475db43b49"
            ]
        ]
    },
    {
        "id": "2939a8475db43b49",
        "type": "debug",
        "z": "c65b467adae4a92e",
        "name": "debug 2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 500,
        "y": 500,
        "wires": []
    }
]
```

with `echo -e "GET /foo/192.168.1.1 HTTP/1.1\n" | nc localhost 1880` works just fine, which implies its something specific with the exec node.

**Comment by Steve-Mcl** [comment]
Have you tried adding `Host` line?

**Comment by ilya-fedin** [comment]
> Have you tried adding `Host` line?

Yeah.

**Comment by hardillb** [comment]
Infact if I delete the exec node and just wire straight through your example works as well.

**Comment by Steve-Mcl** [comment]
What about using printf instead of echo...

```
printf "%s\r\n" \
    "GET /usbip-attach/192.168.1.118/1-1 HTTP/1.1" \
    "Host: xxxxx" \
    "" |
nc - 192.168.1.254 1880
```

**Comment by Steve-Mcl** [comment]
> Infact if I delete the exec node and just wire straight through your example works as well.

Ah ok, so the issue is not with http but the execution part

**Comment by ilya-fedin** [comment]
> What about using printf instead of echo...

This works. Looks like the answer was to combine host + `\r`, i.e. `echo -e "GET /usbip-attach/192.168.1.118/1-1 HTTP/1.1\r\nHost: 192.168.1.254:1880\r\n\r" | nc 192.168.1.254 1880`

**Comment by ilya-fedin** [comment]
Thank you

**Comment by Steve-Mcl** [comment]
So it is 3.x being more strict to the http specification. 

I think we can close this then.

**Comment by hardillb** [comment]
More likely NodeJS 20 (like 18) being more strict with HTTP headers out of the box

**Comment by ilya-fedin** [comment]
Looks like it's not actually solved. The device has nc from busybox and doing the same with busybox nc leads to no answer from Node-RED for some reason
```
   echo -e "GET /usbip-attach/1/2 HTTP/1.1\r\nHost: 192.168.1.254:1880\r\n\r" | busybox nc 192.168.1.254 1880
   
```

If I remove the `\r`s after the last line, it starts to answer with 400 again, but once I return them I get no answer...

**Comment by Steve-Mcl** [comment]
If you can TCPdump or wireshark I suspect you will find the issue/differences.

**Comment by Steve-Mcl** [comment]
Please also try the printf version. There is less ambiguity with regards newlines.

**Comment by ilya-fedin** [comment]
printf has the same problem

**Comment by Steve-Mcl** [comment]
> printf has the same problem

Please show us the command line you issued.

**Comment by ilya-fedin** [comment]
`printf "%s\r\n"     "GET /usbip-attach/192.168.1.118/1-1 HTTP/1.1"     "Host: xxxxx"     "" | busybox nc 192.168.1.254 1880`
Once I remove `busybox` from it, it works.

**Comment by Steve-Mcl** [comment]
Then I suspect somehow busybox is the issue - if can you run tcpdump or wireshark or similar - it is likely you will spot a formatting issue.

Ultimately though, I am confident this is not a node-red issue and as such, you should head over to the node-red forum where there are many more very helpful folk able to give you tips and help.

**Comment by ilya-fedin** [comment]
Can't node-red workaround this somehow? Apply some flag for nodejs to be more permissive or replace the http library...

**Comment by ilya-fedin** [comment]
busybox nc:
```
0000   dc a6 32 0d ee d6 d8 c0 a6 77 d0 5d 08 00 45 00   ..2......w.]..E.
0010   00 70 75 36 40 00 40 06 40 9f c0 a8 01 64 c0 a8   .pu6@.@.@....d..
0020   01 fe 8d 1d 07 58 9f b5 f5 76 47 d4 89 f8 80 18   .....X...vG.....
0030   01 f8 85 15 00 00 01 01 08 0a e7 a3 7c 27 50 3e   ............|'P>
0040   66 9d 47 45 54 20 2f 75 73 62 69 70 2d 61 74 74   f.GET /usbip-att
0050   61 63 68 2f 31 2f 32 20 48 54 54 50 2f 31 2e 31   ach/1/2 HTTP/1.1
0060   0d 0a 48 6f 73 74 3a 20 31 39 32 2e 31 36 38 2e   ..Host: 192.168.
0070   31 2e 32 35 34 3a 31 38 38 30 0d 0a 0d 0a         1.254:1880....
```
GNU nc:
```
0000   dc a6 32 0d ee d6 d8 c0 a6 77 d0 5d 08 00 45 00   ..2......w.]..E.
0010   00 70 6d 3e 40 00 40 06 48 97 c0 a8 01 64 c0 a8   .pm>@.@.H....d..
0020   01 fe da ac 07 58 19 9a 95 49 11 63 6f c6 80 18   .....X...I.co...
0030   01 f8 85 15 00 00 01 01 08 0a e7 a6 76 b7 50 41   ............v.PA
0040   61 2e 47 45 54 20 2f 75 73 62 69 70 2d 61 74 74   a.GET /usbip-att
0050   61 63 68 2f 31 2f 32 20 48 54 54 50 2f 31 2e 31   ach/1/2 HTTP/1.1
0060   0d 0a 48 6f 73 74 3a 20 31 39 32 2e 31 36 38 2e   ..Host: 192.168.
0070   31 2e 32 35 34 3a 31 38 38 30 0d 0a 0d 0a         1.254:1880....
```

**Comment by Steve-Mcl** [comment]
busybox works for me:

![image](https://github.com/node-red/node-red/assets/44235289/a772b3c7-a2a9-4184-b255-7d5a66200844)

Though I dont get any stdout back - it does work.

**Comment by ilya-fedin** [comment]
Hmm. Indeed, you seem to be right. I thought a repeat call would duplicate the device in lsusb, apparently it's not. Sorry for the noise.
