### ISSUE TITLE
Http-request-node “Enable connection keep-alive” seems not to work

### ISSUE THREAD

**Issue by AloisKlingler** [node-red/node-red#4223]
### Current Behavior

http request node closes connection after each request, although "enable connection keep-alive" is ticked. there are no nodes in front of the http request node, only a inject node for periodically firing.

![image](https://github.com/node-red/node-red/assets/11095760/3ea0a9fe-69de-4711-87df-471a26acab60)

with tcpdump I can see, that the client request hast set "Connection: close". Also The complete TCP connection is always started from the beginning.
Shouldn't the HTTP request node set "Connection: keep-alive" instead to leave the connection open for the next request?

![image](https://github.com/node-red/node-red/assets/11095760/39f3c28f-e749-416c-b184-794b1db7c3e3)

### Expected Behavior

set HTTP header "Connection" to "keep-alive" to let the server decide if the connection is terminated.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: v18.6.0
- npm version: 8.13.2
- Platform/OS: linux raspbian, debian version 10.13
- Browser: chrome

**Comment by knolleary** [comment]
Fixed via #4228
