### ISSUE TITLE
增加给国际化配置

### ISSUE THREAD

**Issue by wsxe9988** [node-red/node-red#4236]
### Current Behavior

增加给国际化配置

### Expected Behavior

增加给国际化配置

### Steps To Reproduce

增加给国际化配置

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Hi. If you have an issue, please fill out the entire form.

If you need assistance, please visit the forum or slack.

**Comment by dceejay** [comment]
Pull requests to add additional languages would be gladly accepted as long as someone can check them for accuracy.
