### ISSUE TITLE
Node Red Custom Token issue

### ISSUE THREAD

**Issue by shaharzoo93** [node-red/node-red#4237]
### Current Behavior

We have successfully integrated and launched the Node-RED application as an embedded component within our existing system using an iframe. However, we encountered an issue where all the child requests are being denied due to unauthorized access.

Here is an improved version of the provided code:
```
<iframe id="pwi_smv_app_iframe" name="pwi_smv_app_iframe" frameborder="0"
  src="${baseUri}/api/nginx/api/ui/?jwt=${window.localStorage.getItem('credentials')}"
  style="width: 100%; height: calc(100vh - 101px); position: fixed;"></iframe>
```
![image](https://github.com/node-red/node-red/assets/98393862/80e112e1-a7ac-4669-b7a2-a7b89890219f)
![image (1)](https://github.com/node-red/node-red/assets/98393862/a929f423-0adf-4d20-8d70-74af5e6018ba)

it seems that the child requests are failing because the authentication token is not being set for the Node-RED resources/ child requests.
![image (2)](https://github.com/node-red/node-red/assets/98393862/fb868961-dfe8-4d83-8621-b6ed651e348d)

### Expected Behavior

All the subsequent node-red child/resources requests add a token if the initiator request has a token and UI should load.

### Steps To Reproduce

- Up the node-red as embedded using express node.js.
- Create custom authentication gateway 
- Request node-red ui request from your existing application 

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
You mention Node-RED UI. Do you mean the editor or a dashboard created by `node-red-dashboard`? The urls involved suggest the latter - but wanted to be certain.

What is your expectation here? That node-red-dashboard should know to include your tokens in all requests it makes?

**Comment by shaharzoo93** [comment]
Yes. 
It's for both Node-red UI and Editor.
Suppose I create one node.js project called nginx and embedded the node-red.
so I will access node-red UI via the below path  

- https://127.0.0.1/nginx/api/ui -- ui
- https://127.0.0.1/nginx/red -- editor

When we called ui it also loads more resources like app.min.js, socket.io.js, etc.
I need to add the token in all the resources which is load by node-red

**Comment by knolleary** [comment]
There are two separate things there.

The editor is secured via the `adminAuth` settings. It can deal with custom auth tokens. I assume that is working okay for you?

The dashboard (and any routes served by HTTP In nodes) are handled entirely separately. They are end points created by the deployed flows. There isn't a built-in authentication mechanism for them; it is left to the flows to apply whatever security is needed. There are options such as `httpNodeMiddleware` that allows you to set server-side authentication on those routes.

Node-RED Dashboard is a separate project [here](https://github.com/node-red/node-red-dashboard) - any discussion around changing what it does should be held there; it isn't a core Node-RED issue.

**Comment by shaharzoo93** [comment]
Since authentication is already integrated into the existing application, there is no need to perform any authentication checks on the Node-RED side. However, to ensure that all subsequent requests include a token, we need to make some configuration changes in the Node-RED core.

![image](https://github.com/node-red/node-red/assets/98393862/3e683e42-dc80-43ad-9e14-3e38fc4281ff)

In our current structure, the Node-RED UI path is accessed from the UI with a JWT token, and it successfully executes and returns the Node-RED UI dashboard. However, the dashboard also requires additional resource files such as app.min.js and socket.io. Unfortunately, these resource files do not automatically include the token, resulting in authentication errors from the Kong gateway.

**Comment by knolleary** [comment]
As this is not a core Node-RED issue, I'm going to close this issue for now.
