### ISSUE TITLE
Subflows name cannot be used from a function inside the subflow

### ISSUE THREAD

**Issue by dirkjanfaber** [node-red/node-red#4239]
### Current Behavior

The subflows name cannot be used form a function inside the subflow. Also see [this](https://stackoverflow.com/questions/62683904/is-it-possible-to-get-a-subflow-name-inside-one-of-its-functions-on-node-red) stackoverflow question. Nick asked me in the #creating-nodes Slack channel to raise an issue for this. 

### Expected Behavior

The subflows name can be used from a function inside the subflow.

### Steps To Reproduce

1. Create a subflow containing a function.
2. Try to get set the name of the subflow as `msg.topic` in that function.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.14.0
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
I think it would be entirely reasonable to expose this as `NR_SUBFLOW_NAME` - in the same way we do `NR_FLOW_NAME` and `NR_GROUP_NAME`.

The refactoring happening in #4230 will make this super simple to do - I'll include this there, all things being equal.
