### ISSUE TITLE
Add mouse-over pop-ups to menus items?

### ISSUE THREAD

**Issue by Humancell** [node-red/node-red#424]
It would be nice to display some "tool tip" mouse-over pop-ups to the menu items - or some of them - that explain what they do.  e.g. Node Status and Configuration Nodes...

**Comment by knolleary** [comment]
0.20 introduces tooltips to a variety of the editor ui elements - albeit not for the menu items. I'm going to close this issue as it has been around for 4 years and isn't an issue as such. Always welcome feedback on the usability of the UI via the forum or slack.
