### ISSUE TITLE
tgz file isn't always installing latest uploaded file

### ISSUE THREAD

**Issue by gitmacer** [node-red/node-red#4240]
### Current Behavior

if you install a tgz file then removing it and uploading a new one with code changes it will install the previous uploaded file insted of the latest one. Untill I restart node-red.

### Expected Behavior

Always install latest uploaded file.

### Steps To Reproduce

- upload file 
- remove nodes
- upload new file

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: v16.20.0
- npm version: 8.19.4
- Platform/OS: debian Bullseye
- Browser: firefox 114.0.2 (64-Bit)

**Comment by knolleary** [comment]
Are you restarting Node-RED after removing the node? As the dialog says in the editor, a restart is required to fully flush out the old version. Same is true when you trigger an upgrade of a module.

**Comment by gitmacer** [comment]
Ok overlooked that notice. Sad to hear that I need to restart. It always takes some time.

**Comment by JoshuaCWebDeveloper** [comment]
In addition to restarting the Node-RED process (as explained above and noted by the dialog), **the web page in the browser must also be refreshed in order for UI changes to take effect**.

Until the page is refreshed, the old UI will be rendered *even after* an uninstall, process restart, and fresh install of the module.
