### ISSUE TITLE
`$clone` has no document in JSONata expression editor

### ISSUE THREAD

**Issue by kazuhitoyokoi** [node-red/node-red#4268]
### Current Behavior

In Node-RED 3.1.0-beta.4, `$clone` has been added to the list on the JSONata expression editor but there is no documentation about this function.

<img width="1440" alt="Screenshot 2023-08-06 at 21 51 10" src="https://github.com/node-red/node-red/assets/20310935/79c7250f-74df-4a3a-960c-79f52224a047">

After the English documentation is added, I will update the Japanese message catalog.

### Expected Behavior

`$clone` has a document on how to use this function.

### Environment

- Node-RED version: v3.1.0-beta.4
- Node.js version: v20.2.0
- npm version: v9.6.6
- Platform/OS: macOS Ventura 13.4.1 (c) on MacBook Air (M1, 2020)
- Browser: 115.0.5790.170 (Official Build) (arm64)

**Comment by knolleary** [comment]
Fixed by https://github.com/node-red/node-red/pull/4284

**Comment by kazuhitoyokoi** [comment]
Thank you. I updated the Japanese document in https://github.com/node-red/node-red/pull/4287.
