### ISSUE TITLE
MQTT in node overwrites complete msg object in dynamic subscription mode

### ISSUE THREAD

**Issue by tmartini** [node-red/node-red#4269]
### Current Behavior

When using the mqtt in node with Action: "dynamic subscription" it overwrites the complete msg object with the received message and all information gathered before the node is gone. 

Is this a remnant of it being originally designed as a start node of a flow with no input?

Workaround at the moment: Storing the incoming msg to the mqtt in node in the flow variables. But this does not work when the mqtt node is part of a split. Especially, the "parts" information is lost, so no join is possible afterwards.

### Expected Behavior

When the mqtt in node is used within a flow (not at the beginning), the msg object delivered to it should not be overwritten completely. This is especially crucial after a split.

### Steps To Reproduce

- split a flow containing an Array of mqtt Topics
- within the split, use each entry of the Array as the topic for a dynamically subscribed mqtt node
- > msg object is overwritten

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v3.0.2
- Node.js version: v18.16.1
- Platform/OS: Windows_NT 10.0.19045 x64 LE
- Browser: Microsoft Edge

**Comment by hardillb** [comment]
Input messages are not overwritten, they are just not output at all.

When the MQTT-in node receives a new MQTT message it will output a new message.

This is working as intended.

**Comment by tmartini** [comment]
But this renders the mqtt in node not suitable for use within a flow, doesn't it?

If the whole msg object of the flow is not an output at all anymore I cannot use its contents anymore.

Especially in my example within the split, all information about the parts is lost or am I missing something?

**Comment by hardillb** [comment]
Just to be clear, I don't think what you are doing will work anyway.

If you are feeding an array of topics into a split node then to the MQTT-in node, then to a join to gather published values, what happens if nothing publishes a message before the next topic from the array arrives at the MQTT-in node? 

What you describe would only work to gather retained messages.

**Comment by hardillb** [comment]
The point is to change the topic of the MQTT-in going forward, not to retrieve a single message on a given topic (the MQTT-in node has no concept of waiting for the "next" message.

**Comment by tmartini** [comment]
there is no "next topic". The flow is injected once, requests some info per a HTTP request (containing the a priori unknown topics as a list) and sets up mqtt listeners for said topics in a split (I do not neccessarily know how many topics the request yields).

**Comment by hardillb** [comment]
Also given the MQTT-in node is now subscribed to your list to topics, it would the proceed to output all these into the join node again, which wouldn't know what to do with them as they would still be carrying the split data, which wouldn't make sense if one of the topics outputs more messages than the others.

This would also mean that the MQTT-in node would need to keep track of every control input message so it could match topics and use the right one as the base for the incoming MQTT message.

**Comment by tmartini** [comment]
okay, forget the join. That is not my point here...

Assume I have some form of information stored in the message object, let's say msg.info='I am important', before the mqtt in node. Since this is not part of the output anymore, I cannot use it. My workaround was to store it in a flow variable. But this does not work if the mqtt in node is after the split because the flow variable does not "split" but msg.info could be different for each split (as is msg.parts, hence I used this as an example).

**Comment by hardillb** [comment]
The important point is that the control messages are not passed through at all, because configuring the node is totally independant of a new MQTT message arriving from the broker.

This comes back to the last sentence in my last update.

Which control msg object should it use as the base for the message output on a new MQTT message? If you stream in 20 different control messages that subscribe to different topics, how do we pick one to use as the basis, how many do we store?

**Comment by hardillb** [comment]
A possible option (I'm just thinking out loud here) could be to add a second output to the MQTT-in node that only gets enabled when dynamic configuration and the input is enabled.

In that case the control message could be output on the second output, maybe with some status on the command result (success/failure of the subscription) that would pass the message through, but it would not be attached to the messages triggered by incoming MQTT messages.

**Comment by tmartini** [comment]
Thank you, this sounds like something I had in mind.

**Comment by hardillb** [comment]
The easier option is just to have 2 wires out of the split node, one to MQTT-in node and one on to the join node.

**Comment by tmartini** [comment]
> The easier option is just to have 2 wires out of the split node, one to MQTT-in node and one on to the join node.

with this solution the neede association between a received mqtt message and the part of the split would not be tractable.

Point is, I need to know which mqtt listener in the split received which message.

Thanks for your help so far!

**Comment by Steve-Mcl** [comment]
> Is this a remnant of it being originally designed as a start node of a flow with no input?

No, this is not a remnant. The MQTT In node is for receiving subscriptions. It was not designed to hold the dynamic `msg` and re-use it upon receiving a packet. 

What you are asking is not an unfamiliar pattern (just a bit different).  For example, the node-red-ping node will keep the msg and return the ping result in the original msg. Same as many other nodes however, MQTT is different. Once a subscription if set, multiple messages arrive at the will of the broker (or rather upon a publish by ANY client).  That is why this scenario differs. Additionally, I did not want references (or clones) of potentially large messages hanging in memory.  For example, suppose the subscription detail comes from a `http-in` node, we would be holding onto the request data and other response bound info for ever, unnecessarily snf more importantly, wrongly.  We will be hit with questions like "how do I delete all these extra properties from the msg` etc etc.

On the other hand, (assuming I am reading your requirement correctly), what you are asking for is easily achievable using context.  e.g.:

```
[{"id":"4069ddc662f50654","type":"inject","z":"fe471bfa726693b8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"topic\":\"smac/machine/1/partlevel/a12b34\",\"routing\":{\"source\":\"10.176.5.1\",\"dest\":\"172.17.12.1\",\"desc\":\"route partlevel info to supplier 1\"}},{\"topic\":\"smac/machine/1/count\",\"routing\":{\"source\":\"10.176.5.1\",\"dest\":[\"172.17.12.2\",\"10.176.2.5\"],\"desc\":\"route machine count to ERP and Supervisor Display\"}},{\"topic\":\"smac/machine/1/state\",\"routing\":{\"source\":\"10.176.5.1\",\"dest\":\"10.176.2.5\",\"desc\":\"route machine state Supervisor Display\"}}]","payloadType":"json","x":1160,"y":280,"wires":[["7c381911c81d544f","4fbd8bfb68e0fbfb"]]},{"id":"7c381911c81d544f","type":"split","z":"fe471bfa726693b8","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":1310,"y":280,"wires":[["7850f41039ac67da"]]},{"id":"7850f41039ac67da","type":"change","z":"fe471bfa726693b8","name":"update store","rules":[{"t":"set","p":"action","pt":"msg","to":"subscribe","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"payload.topic","tot":"msg"},{"t":"set","p":"routingInfo[msg.topic]","pt":"flow","to":"payload.routing","tot":"msg","dc":true}],"action":"","property":"","from":"","to":"","reg":false,"x":1470,"y":280,"wires":[["3a2ec2bd365b3cc7"]]},{"id":"3a2ec2bd365b3cc7","type":"mqtt in","z":"fe471bfa726693b8","name":"","topic":"","qos":"2","datatype":"auto-detect","broker":"33d54b0c06d035ce","nl":false,"rap":true,"rh":0,"inputs":1,"x":1170,"y":340,"wires":[["9b1a6cc008128738"]]},{"id":"9b1a6cc008128738","type":"change","z":"fe471bfa726693b8","name":"get from store","rules":[{"t":"set","p":"routingInfo","pt":"msg","to":"routingInfo[msg.topic]","tot":"flow","dc":true}],"action":"","property":"","from":"","to":"","reg":false,"x":1370,"y":340,"wires":[["8cea2b42d0876c6d"]]},{"id":"8cea2b42d0876c6d","type":"debug","z":"fe471bfa726693b8","name":"full msg","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1560,"y":340,"wires":[]},{"id":"416fe9e004ec5290","type":"inject","z":"fe471bfa726693b8","name":"smac/machine/1/partlevel/a12b34: 3","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"smac/machine/1/partlevel/a12b34","payload":"3","payloadType":"num","x":1260,"y":460,"wires":[["1c79185268606687"]]},{"id":"1c79185268606687","type":"mqtt out","z":"fe471bfa726693b8","name":"","topic":"","qos":"","retain":"","respTopic":"","contentType":"","userProps":"","correl":"","expiry":"","broker":"33d54b0c06d035ce","x":1530,"y":500,"wires":[]},{"id":"1014beddec47c159","type":"inject","z":"fe471bfa726693b8","name":" smac/machine/1/count: 322","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"smac/machine/1/count","payload":"322","payloadType":"num","x":1240,"y":500,"wires":[["1c79185268606687"]]},{"id":"229cf860614e609b","type":"inject","z":"fe471bfa726693b8","name":"smac/machine/1/state: STOPPED","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"smac/machine/1/state","payload":"STOPPED","payloadType":"str","x":1260,"y":540,"wires":[["1c79185268606687"]]},{"id":"4fbd8bfb68e0fbfb","type":"debug","z":"fe471bfa726693b8","name":"data from \"somewhere\", containing subscriptions & extra data","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1460,"y":240,"wires":[]},{"id":"33d54b0c06d035ce","type":"mqtt-broker","name":"smac-emqx-mqtt-v5-conn1","broker":"broker.emqx.io","port":"1883","clientid":"smac-emqx-mqtt-v5-conn1x","autoConnect":true,"usetls":false,"protocolVersion":"5","keepalive":"60","cleansession":false,"autoUnsubscribe":true,"birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"0","closeRetain":"false","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willRetain":"false","willPayload":"","willMsg":{},"userProps":"","sessionExpiry":"30"}]
```

https://github.com/node-red/node-red/assets/44235289/53790355-0452-4bb1-8ea8-3ab78b7121cf

You could easily make a subroutine (via link call) or a subflow out of this to make it a re-usable pattern.

For those reasons, my vote goes to "no change".

**Comment by tmartini** [comment]
thank you very much! I had not thought about using the topic as an key for the store in the flow variable. I used the parts.index from the split, which was gone after the mqtt, while the topic is not. This could be the solution to my problem. Thanks. I will close the issue.
