### ISSUE TITLE
Can't load Mermaid dark theme unless the load is delayed

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#4274]
### Current Behavior

As described in [this issue](https://github.com/node-red-contrib-themes/theme-collection/issues/292) on the theme collection repo, Mermaid's default theme doesn't play well with Node-RED dark themes.

I tried adding the following to a Node-RED dark theme to load Mermaid's dark theme. It didn't work.

```javascript
mermaid.initialize({
    theme: 'dark',
});
```

<img width="323" alt="SCR-20230814-gola" src="https://github.com/node-red/node-red/assets/29807944/181aa13f-d202-44af-b18a-8dd2916cd8e9">

If I add a "delay", the dark theme is loaded after that "delay". This kind of fixes the issue. But it feels weird having the wait to have Mermaid's dark theme loaded.

```javascript
setTimeout(() => {
    mermaid.initialize({
        theme: 'dark',
    });
}, 5000);
```

<img width="323" alt="SCR-20230814-goit" src="https://github.com/node-red/node-red/assets/29807944/227983ba-b86b-46e3-98dd-398c7da158d7">

Is there a way to load the theme without a delay?

### Example flow

```
[{"id":"55d54d1c275c150f","type":"function","z":"bdd7be38.d3b55","name":"Test mermaid markdown","func":"\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":810,"y":60,"wires":[[]],"info":"```mermaid\nstateDiagram-v2\nState_1 --> State_2: Transition 1\nState_2 --> State_3: Another transition\nState_3 --> State_1: Back to \\nthe start\n```"}]
```

### Environment

- Node-RED version: 3.1.0-beta.4
- Node.js version: v18.17.1
- npm version: 9.6.7
- Platform/OS: macOS Ventura
- Browser: Google Chrome

**Comment by bonanitech** [comment]
Maybe we could have something similar to what was introduced in #3084. A theme plugin can select a core theme or provide a custom theme for the Monaco Editor.

**Comment by bonanitech** [comment]
How can we load mermaid's dark theme after the changes in #4364?

**Comment by knolleary** [comment]
Figuring out theming is on my list before 3.1.1 ships. The new approach in #4364 should make it easier to inject a custom theme... just need to settle on the details
