### ISSUE TITLE
Multipart form-data stringification fails for some payloads

### ISSUE THREAD

**Issue by AndreKR** [node-red/node-red#4279]
This is a regression from 3.0.2 to 3.1.0-beta.4.

### Current Behavior

See below.

### Expected Behavior

See below.

### Steps To Reproduce

- Create a flow: `[inject] -> [http request]`
- For the _http request_ node, set a header: `Content-Type: multipart/form-data`
- For full reproduction set the URL to [a request bin](https://pipedream.com/requestbin) or something where you can see the request.
- Now set *payload* in the _inject_ node to various values and submit the request.

-----
Payload:
```json
{
  "foo":"bar",
  "baz":"qux"
}
```
This payload works as expected in both Node-RED 3.0.2 and in Node-RED 3.1.0-beta.4.

The request body contains:
```plain
----------------------------365977468701525343326806
Content-Disposition: form-data; name="foo"

bar
----------------------------365977468701525343326806
Content-Disposition: form-data; name="baz"

qux
----------------------------365977468701525343326806--
```

-----

Payload:
```json
{
  "foo":"bar",
  "baz":[]
}
```

Request body in Node-RED 3.0.2:
```plain
----------------------------449536020369503585684193
Content-Disposition: form-data; name="foo"

bar
----------------------------449536020369503585684193
Content-Disposition: form-data; name="baz"

[]
----------------------------449536020369503585684193--
```

Request body in Node-RED 3.1.0-beta.4:
```plain
----------------------------912001661452958003640404
Content-Disposition: form-data; name="foo"

bar
----------------------------912001661452958003640404--
```
(The key `baz` is missing.)

-----

Payload:
```json
{
  "foo": "bar",
  "baz": {
    "qux": "quux"
  }
}
```

This payload works as expected in Node-RED 3.0.2 and in Node-RED 3.1.0-beta.4. The request body contains:
```plain
----------------------------750817547098147905511659
Content-Disposition: form-data; name="foo"

bar
----------------------------750817547098147905511659
Content-Disposition: form-data; name="baz"

{"qux":"quux"}
----------------------------750817547098147905511659--
```

-----
Payload:
```json
{
  "foo": "bar",
  "baz": [{
    "qux": "quux"
  }]
}
```

Request body in Node-RED 3.0.2:
```plain
----------------------------278360827167686938434020
Content-Disposition: form-data; name="foo"

bar
----------------------------278360827167686938434020
Content-Disposition: form-data; name="baz"

[{"qux":"quux"}]
----------------------------278360827167686938434020--
```

In Node-RED 3.1.0-beta.4 this request is not sent, instead an error is generated:
```plain
TypeError: source.on is not a function
```

### Example flow

```
[
    {
        "id": "6e90cb67d98afd6a",
        "type": "inject",
        "z": "3cf45e2a5eb79663",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"foo\":\"bar\",\"baz\":[{\"qux\":\"quux\"}]}",
        "payloadType": "json",
        "x": 430,
        "y": 420,
        "wires": [
            [
                "5b4d494fcc8f532a"
            ]
        ]
    },
    {
        "id": "5b4d494fcc8f532a",
        "type": "http request",
        "z": "3cf45e2a5eb79663",
        "name": "",
        "method": "POST",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://example.com",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers": [
            {
                "keyType": "Content-Type",
                "keyValue": "",
                "valueType": "other",
                "valueValue": "multipart/form-data"
            }
        ],
        "credentials": {},
        "x": 570,
        "y": 420,
        "wires": [
            []
        ]
    }
]
```

### Environment

- Node-RED version: Regression from 3.0.2 vs 3.1.0-beta.4
- Node.js version: 16 I believe (I'm using the official Docker image.)
- npm version: I don't know.
- Platform/OS: Linux
- Browser: Chrome

### Possible workaround

If the form fields are known in advance, a workaround is possible using a JSONata expression:

```jsonata
{
  "foo": "bar",
  "baz": $string([{
    "qux": "quux"
  }])
}
```

**Comment by knolleary** [comment]
It looks like the handling of arrays inside payloads to be sent via form-data was changed in https://github.com/node-red/node-red/pull/3991

So some of this is an expected change in behaviour - I think.

The `source.on` error is certainly something that needs looking at.

**Comment by AndreKR** [comment]
I see, so the expected result for the payload from the last example would be something like:
```
----------------------------boundary
Content-Disposition: form-data; name="foo"

bar
----------------------------boundary
Content-Disposition: form-data; name="baz"

{"qux":"quux"}
----------------------------boundary--
```

I.e. a single `baz` field (because the array has one element) which is the `{"qux":"quux"}` object.

This is the *second* "magic" behavior related to form-data transformation, the first being the conversion of `"value":` into a "file upload".

Since we're allowing a breaking change, maybe it would make sense to do away completely with implicit stringification and require that the payload is an object whose elements are either strings, or an object with `{value: ...}`, or an array of strings, or an array of objects with `{value: ...}`. Anything else would raise an error.

**Comment by knolleary** [comment]
@AndreKR I'm in two minds whether to revert the original PR to avoid this breakage and find a different way to support the scenario it was intended to add support for.

**Comment by knolleary** [comment]
I have reverted the PR that changed this behaviour. We'll look again at how best to support array form properties in a way that won't break existing flows.
