### ISSUE TITLE
Undoing a junction added using the Quick-Add dialog keeps the workspace dirty

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#4282]
### Current Behavior

If you add a junction using the Quick-Add dialog and press ctrl-z, that junction will be removed, but the workspace will remain marked as dirty.

### Environment

- Node-RED version: 3.0.2
- Node.js version: v18.17.1
- npm version: 9.6.7
- Platform/OS: macOS Ventura
- Browser: Tested on Chrome and Safari

**Comment by knolleary** [comment]
Fixed by https://github.com/node-red/node-red/pull/4283
