### ISSUE TITLE
Mermaid diagram in node information sometimes shows syntax error

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#4323]
### Current Behavior

With the function node in the flow below, following the instructions in the Steps To Reproduce section, the information tab shows a syntax error instead of the chart

### Expected Behavior

It should always show the chart.

### Steps To Reproduce

Import the Function node included below and Deploy. Select the Debug tab, then select the Function node and the Information tab, and instead of the diagram it shows

![image](https://github.com/node-red/node-red/assets/38307/b46b1baa-1b76-423c-a2f6-fc9e34e5ddd0)

If you then click away from the node and then select it again it shows correctly

![image](https://github.com/node-red/node-red/assets/38307/a2b9dd9a-6e44-4a06-a8ec-7a0c27106f76)

### Example flow

```
[{"id":"55d54d1c275c150f","type":"function","z":"bdd7be38.d3b55","name":"Test mermaid markdown","func":"\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":810,"y":60,"wires":[[]],"info":"```mermaid\nstateDiagram-v2\nState_1 --> State_2: Transition 1\nState_2 --> State_3: Another transition\nState_3 --> State_1: Back to \\nthe start\n```"}]
```

### Environment

- Node-RED version: 3.1.0
- nodejs version: 20 and 18
- npm version: 9.8.0
- Platform/OS: Ubuntu 22.04 and Pi OS Bullseye
- Browser: Edge and FF

**Comment by knolleary** [comment]
Having dug into this issue, it appears to be the fact that mermaid always tries to insert itself into the DOM. If the element being evaluated isn't in the dom, it generates an error.

Related upstream issue: https://github.com/mermaid-js/mermaid/issues/4358

Hmm, we need to figure out a way around this as it isn't acceptable behaviour for us.
