### ISSUE TITLE
"http request" node "RequestError: connect ECONNREFUSED 127.0.0.1:443"

### ISSUE THREAD

**Issue by russdan** [node-red/node-red#4324]
### Current Behavior

With `latest` image pushed today http request node functionality in Docker seems to break.  

I have two scenarios which now have stopped working: 
1. A function node which formats the URL and passes it as `msg.url`, e.g.
```
msg.url = "https://api.octopus.energy/v1/gas-meter-points/9999999999/meters/E6E00000000000/consumption/?period_from=2023-08-30T00:00:00.000Z&period_to=2023-09-08T00:00:00.000Z&page_size=1000&group_by=day"
```
2. A node which passed `msg.payload`  as `{"username":"user@email.com","password":"secretPassw0rd"}` and the http request node containing the url as a POST `https://api.pod-point.com/v5/auth`

both scenarios return `RequestError: connect ECONNREFUSED 127.0.0.1:443`

I have rolled-back to `3.0.2-14` and the functions work again.

I do have a custom dockerfile as I need fabric installing also.

I notice in the logs for latest 

```
6 Sep 17:36:03 - [info] Node-RED version: v3.1.0
6 Sep 17:36:03 - [info] Node.js  version: v16.20.2
6 Sep 17:36:03 - [info] Linux 6.4.0-0.deb12.2-amd64 x64 LE
6 Sep 17:36:03 - [info] Loading palette nodes
6 Sep 17:36:05 - [info] Dashboard version 3.4.0 started at /ui
(node:7) V8: /data/node_modules/@throneless/libsignal-protocol/build/curve25519_concat.js:20225 Invalid asm.js: Expected shift of word size
```

which doesn't get logged when I use 3.0.2-14. however 3.0.2-14 shows the following which latest doesn't:
```
Patched https.request function detected. This will break the
HTTP Request node. The original code has now been restored.
This is likely caused by a contrib node including an old version of
the 'agent-base@<5.0.0' module.
```
which is ironic as 3.0.2-14 http works and latest doesn't!

### Expected Behavior

http request nodes correctly route the http request to the specified service.

### Steps To Reproduce

1. Build node-red with following dockerfile
```
FROM nodered/node-red
USER root
RUN apk add py3-pip curl busybox-extras
RUN pip3 install fabric
```
2. Create a http request node for an API service, either passing `msg.url` or passing `msg.payload` credentials, and deploy the flow

### Example flow

```
[
    {
        "id": "2e6a4fbc7fefd8de",
        "type": "http request",
        "z": "04d310a7ec5c4cb0",
        "name": "",
        "method": "GET",
        "ret": "obj",
        "paytoqs": "ignore",
        "url": "",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers": [],
        "x": 930,
        "y": 220,
        "wires": [
            [
                "fbba3e72e87b0d51"
            ]
        ]
    },
    {
        "id": "62517e98fb262d7d",
        "type": "inject",
        "z": "04d310a7ec5c4cb0",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 500,
        "y": 220,
        "wires": [
            [
                "8d6cc960f014c193"
            ]
        ]
    },
    {
        "id": "fbba3e72e87b0d51",
        "type": "debug",
        "z": "04d310a7ec5c4cb0",
        "name": "debug 115",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 1150,
        "y": 220,
        "wires": []
    },
    {
        "id": "8d6cc960f014c193",
        "type": "function",
        "z": "04d310a7ec5c4cb0",
        "name": "get_price_data",
        "func": "var oct_url = \"https://api.octopus.energy/v1/products/SILVER-2017-1/gas-tariffs/G-1R-SILVER-2017-1-H/standard-unit-rates/?period_from=2023-09-03T00:00:00Z&period_to=2023-09-08T00:00:00Z\"\n\nmsg.url = oct_url;\n\nreturn msg;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 720,
        "y": 220,
        "wires": [
            [
                "2e6a4fbc7fefd8de"
            ]
        ]
    }
]
```

### Environment

- Node-RED version:  v3.1.0
- Node.js version: v16.20.2
- npm version:
- Platform/OS: Linux 6.4.0-0.deb12.2-amd64 x64 LE  ( = latest  linux/amd64  dockerfile image)
- Browser: Firefox 116.0.3 (64-bit) Windows 11

**Comment by knolleary** [comment]
Hi @russdan - thanks for the issue report.

Your provided flow is working for me in a local install of Node-RED - as is the scenario of passing in a `msg.url` url.

I will see if I can reproduce via the docker approach you describe.

**Comment by knolleary** [comment]
A vanilla `nodered:node-red` container runs your provided flow without any issues as well.

I cannot get your Dockerfile to build:

```
6 9.644 Building wheels for collected packages: cffi
#6 9.645   Building wheel for cffi (pyproject.toml): started
#6 9.786   Building wheel for cffi (pyproject.toml): finished with status 'error'
#6 9.790   error: subprocess-exited-with-error
#6 9.790
#6 9.790   × Building wheel for cffi (pyproject.toml) did not run successfully.
#6 9.790   │ exit code: 1
#6 9.790   ╰─> [50 lines of output]
#6 9.790       /tmp/pip-build-env-l41ute44/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
#6 9.790       !!
#6 9.790
#6 9.790               ********************************************************************************
#6 9.790               The license_file parameter is deprecated, use license_files instead.
#6 9.790
#6 9.790               By 2023-Oct-30, you need to update your project and remove deprecated calls
#6 9.790               or your builds will no longer be supported.
#6 9.790
#6 9.790               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
#6 9.790               ********************************************************************************
#6 9.790
#6 9.790       !!
#6 9.790         parsed = self.parsers.get(option_name, lambda x: x)(value)
#6 9.790       running bdist_wheel
#6 9.790       running build
#6 9.790       running build_py
#6 9.790       creating build
#6 9.790       creating build/lib.linux-aarch64-cpython-311
#6 9.790       creating build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/vengine_gen.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/pkgconfig.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/model.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/error.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/recompiler.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/commontypes.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/lock.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/__init__.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/api.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/verifier.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/ffiplatform.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/cparser.py -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/_cffi_include.h -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/parse_c_type.h -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/_embedding.h -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-cpython-311/cffi
#6 9.790       running build_ext
#6 9.790       building '_cffi_backend' extension
#6 9.790       creating build/temp.linux-aarch64-cpython-311
#6 9.790       creating build/temp.linux-aarch64-cpython-311/c
#6 9.790       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.11 -c c/_cffi_backend.c -o build/temp.linux-aarch64-cpython-311/c/_cffi_backend.o
#6 9.790       c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
#6 9.790           2 | #include <Python.h>
#6 9.790             |          ^~~~~~~~~~
#6 9.790       compilation terminated.
#6 9.790       error: command '/usr/bin/gcc' failed with exit code 1
#6 9.790       [end of output]
#6 9.790
#6 9.790   note: This error originates from a subprocess, and is likely not a problem with pip.
#6 9.790   ERROR: Failed building wheel for cffi
```

I'm not familiar enough with pip etc to figure that out.

**Comment by russdan** [comment]
Hi Nick, thanks for looking at this so quickly, I'm stumped then as building for me works OK
```
docker build . --no-cache
Sending build context to Docker daemon  229.5MB
Step 1/5 : FROM nodered/node-red:latest
 ---> aad8a8d13b50
Step 2/5 : USER root
 ---> Running in 5192fc4bee9a
Removing intermediate container 5192fc4bee9a
 ---> 44ea7186bfae
Step 3/5 : RUN apk add py3-pip curl busybox-extras
 ---> Running in dfe61bfc4109
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/9) Installing busybox-extras (1.36.1-r2)
Executing busybox-extras-1.36.1-r2.post-install
(2/9) Installing py3-parsing (3.0.9-r2)
(3/9) Installing py3-parsing-pyc (3.0.9-r2)
(4/9) Installing py3-packaging (23.1-r1)
(5/9) Installing py3-packaging-pyc (23.1-r1)
(6/9) Installing py3-setuptools (67.7.2-r0)
(7/9) Installing py3-setuptools-pyc (67.7.2-r0)
(8/9) Installing py3-pip (23.1.2-r0)
(9/9) Installing py3-pip-pyc (23.1.2-r0)
Executing busybox-1.36.1-r2.trigger
OK: 339 MiB in 90 packages
Removing intermediate container dfe61bfc4109
 ---> da8a69a11dc2
Step 4/5 : RUN pip3 install fabric
 ---> Running in 0148a5a32b67
Collecting fabric
  Downloading fabric-3.2.2-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 kB 2.0 MB/s eta 0:00:00
Collecting invoke>=2.0 (from fabric)
  Downloading invoke-2.2.0-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.3/160.3 kB 5.6 MB/s eta 0:00:00
Collecting paramiko>=2.4 (from fabric)
  Downloading paramiko-3.3.1-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.8/224.8 kB 23.7 MB/s eta 0:00:00
Collecting decorator>=5 (from fabric)
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting deprecated>=1.2 (from fabric)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Collecting wrapt<2,>=1.10 (from deprecated>=1.2->fabric)
  Downloading wrapt-1.15.0-cp311-cp311-musllinux_1_1_x86_64.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.8/83.8 kB 11.7 MB/s eta 0:00:00
Collecting bcrypt>=3.2 (from paramiko>=2.4->fabric)
  Downloading bcrypt-4.0.1-cp36-abi3-musllinux_1_1_x86_64.whl (624 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 624.3/624.3 kB 9.9 MB/s eta 0:00:00
Collecting cryptography>=3.3 (from paramiko>=2.4->fabric)
  Downloading cryptography-41.0.3-cp37-abi3-musllinux_1_1_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 11.1 MB/s eta 0:00:00
Collecting pynacl>=1.5 (from paramiko>=2.4->fabric)
  Downloading PyNaCl-1.5.0-cp36-abi3-musllinux_1_1_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 10.9 MB/s eta 0:00:00
Collecting cffi>=1.12 (from cryptography>=3.3->paramiko>=2.4->fabric)
  Downloading cffi-1.15.1-cp311-cp311-musllinux_1_1_x86_64.whl (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.3/474.3 kB 11.3 MB/s eta 0:00:00
Collecting pycparser (from cffi>=1.12->cryptography>=3.3->paramiko>=2.4->fabric)
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 8.8 MB/s eta 0:00:00
Installing collected packages: wrapt, pycparser, invoke, decorator, bcrypt, deprecated, cffi, pynacl, cryptography, paramiko, fabric
Successfully installed bcrypt-4.0.1 cffi-1.15.1 cryptography-41.0.3 decorator-5.1.1 deprecated-1.2.14 fabric-3.2.2 invoke-2.2.0 paramiko-3.3.1 pycparser-2.21 pynacl-1.5.0 wrapt-1.15.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 0148a5a32b67
 ---> 34b4197c05fb
Step 5/5 : RUN git config --global --add safe.directory /data/projects/Home_Automation
 ---> Running in 37a3e23e6752
Removing intermediate container 37a3e23e6752
 ---> 15753264304f
Successfully built 15753264304f
```
that's using the following `dockerfile`
```
FROM nodered/node-red:latest
USER root
RUN apk add py3-pip curl busybox-extras
RUN pip3 install fabric
```
Not sure where to go from here.....

**Comment by russdan** [comment]
oh, I can see a difference, you're on `aarch64` and I'm on `x86_64`...

Russ

**Comment by hardillb** [comment]
Which is causing extra build steps (since the python native binaries are pre-compiled for x86_64).

There will be some extra packages needed to allow rebuilding from scratch of the python native binaries

**Comment by mmattice** [comment]
I upgraded from nodered/node-red:3.0.0 to nodered/node-red:3.1.0 today on x86_64 and am having the same issues with dynamic URLs presented with `.msg`.  Reverting to 3.0.0 works just fine.

docker image inspect gives the following reduced output.
        "Id": "sha256:aad8a8d13b50d89c06f1cf544013ef05e2d5c14b56a0552cb66e3d62f2d6ecc1",
        "RepoTags": [
            "nodered/node-red:3.1.0"
        ],

**Comment by hardillb** [comment]
@mmattice What nodes do you have installed? This is most likely to be one of the nodes messing with the low level  agent-base module.

Did you see the log message mentioned with 3.0.2

**Comment by matteobogoni** [comment]
Hi, I have the same problem updating to v3.1.0. So the solution is to rollback to previous version of nodered? I'm running it on Docker, how can I return to the old version?

**Comment by mmattice** [comment]
@hardillb 

> Did you see the log message mentioned with 3.0.2

I don't have this problem with 3.0.2 either.

> @mmattice What nodes do you have installed? This is most likely to be one of the nodes messing with the low level agent-base module.

    "dependencies": {
        "@node-red-contrib-themes/midnight-red": "^1.1.0",
        "node-red-contrib-cheerio-function": "~1.0.0-rc.9",
        "node-red-contrib-deadmanswitch": "~1.0.1",
        "node-red-contrib-deglitch": "~1.0.2",
        "node-red-contrib-feedparser-2": "~0.1.1",
        "node-red-contrib-google-oauth2": "~0.3.2",
        "node-red-contrib-gpsd": "~1.0.4",
        "node-red-contrib-holiday": "~1.0.0",
        "node-red-contrib-http-logger": "~2.0.1",
        "node-red-contrib-moment": "~4.0.0",
        "node-red-contrib-os": "~0.2.1",
        "node-red-contrib-pid": "~1.1.7",
        "node-red-contrib-pushover": "~0.2.0",
        "node-red-contrib-simple-gate": "~0.5.2",
        "node-red-contrib-sunevents": "~3.0.3",
        "node-red-contrib-tasmota": "~0.9.12",
        "node-red-contrib-timerswitch": "~1.4.0",
        "node-red-contrib-weekday": "~0.1.0",
        "node-red-dashboard": "~3.1.6",
        "node-red-node-base64": "~0.3.0",
        "node-red-node-discord": "~2.2.0",
        "node-red-node-smooth": "~0.1.2"
    }

**Comment by 3web** [comment]
I have the same error with the version **3.1**. I down grade to the Version **3.0.2**. And now it works. I hope it wud by fixed in the next version.

**Comment by hardillb** [comment]
I'm trying to reproduce this, I've installed all the nodes that @mmattice listed with the exception of `node-red-contrib-feedparser-2` which has been deleted from npmjs.org

Can everybody comment if they have the that node installed?

**Comment by 3web** [comment]
I have this setup:

- node-red: 3.0.2
- node-red-contrib-digitaloak-mqtt: 1.0.5
- node-red-contrib-homekit-bridged: 1.5.0
- node-red-contrib-join-wait: 0.5.2
- node-red-contrib-netatmo-dashboard: 1.0.0
- node-red-contrib-smartthings: 0.0.43
- node-red-contrib-virtual-smart-home: 3.0.9
- node-red-dashboard: 3.6.0 
- node-red-node-openweathermap: 0.5.1
- node-red-node-suncalc: 1.1.0

**Comment by russdan** [comment]
Hi Ben, I have the issue and don't have that node installed. How do I easily list the nodes I have installed and I'll add them to the issue?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by hardillb** [comment]
@russdan the quickest way is to grab the `dependencies` section from the `/data/package.json` (you should have a volume mounted on `/data` to ensure your flows are persisted.

**Comment by russdan** [comment]
Here are my packages...
```
        "node-red-contrib-1wire": "~0.0.2",
        "node-red-contrib-bigssh": "~1.2.9",
        "node-red-contrib-calc": "~1.0.5",
        "node-red-contrib-credentials": "~0.2.2",
        "node-red-contrib-email": "~0.2.1",
        "node-red-contrib-filesystem": "~1.0.0",
        "node-red-contrib-flogger": "~1.2.2",
        "node-red-contrib-ha-entity-selector": "~0.0.2",
        "node-red-contrib-homeconnect": "~0.6.6",
        "node-red-contrib-modbus": "~5.26.0",
        "node-red-contrib-moment": "~4.0.0",
        "node-red-contrib-oauth2": "~5.0.4",
        "node-red-contrib-persist": "~1.1.1",
        "node-red-contrib-pythonshell": "~1.5.4",
        "node-red-contrib-string": "~1.0.0",
        "node-red-contrib-syslog-input": "~1.0.1",
        "node-red-contrib-ui-etable": "~4.6.3",
        "node-red-contrib-ui-led": "~0.4.11",
        "node-red-contrib-uibuilder": "~6.3.1",
        "node-red-dashboard": "~3.4.0",
        "node-red-node-email": "~2.0.1",
        "node-red-node-mysql": "~1.0.3",
        "node-red-node-ping": "~0.3.3",
        "node-red-node-tail": "~0.4.0",
        "node-red-node-ui-table": "~0.4.3",
        "nodered-contrib-signal-client": "~2.4.2"
```

**Comment by obilginer** [comment]
I have same problem. Is there a workaround for it?

**Comment by hardillb** [comment]
@obilginer What is `superagent-proxy` doing for you?

Also what happens if you run outside docker on the same network?

**Comment by hardillb** [comment]
Also to all, are you using a proxy at all? Either setting the HTTP_PROXY or HTTPS_PROXY env var?

**Comment by obilginer** [comment]
I have found a solution by myself. I have downgraded Node-Red version from addon_a0d7b954_nodered_14.4.5 to addon_a0d7b954_nodered_14.4.**4**
my nodes are working now. I suppose new version has bug for docker installations

**Comment by hardillb** [comment]
@obilginer That version is not a Node-RED version, I suggest you should open an issue with who ever is packaging that addon as I suspect this is to do with the packaging/environment it is running in as we can not reproduce this issue with a clean install.

**Comment by mmattice** [comment]
> Also to all, are you using a proxy at all? Either setting the HTTP_PROXY or HTTPS_PROXY env var?

Nope.
`  nodered:
    container_name: nodered
    ports:
      - "::1:1880:1880"
      - "local_ip:1880:1880"
      - "vpn_ip:1880:1880"
    image: nodered/node-red:3.0.2
    volumes:
      - /var/local/dockervols/nodereddata/:/data
    restart: always`

**Comment by 3web** [comment]
I do not use a Proxy. Only basic auth, for access to a api in the Internet.There i can’t see the request in the apache logs. With the Version 3.1. and with the version 3.0.2 i can see it.

**Comment by russdan** [comment]
> I do not use a Proxy. Only basic auth, for access to a api in the Internet.There i can’t see the request in the apache logs. With the Version 3.1. and with the version 3.0.2 i can see it.

Same here, I'm using a combination of basic auth and Bearer auth, no proxies.

I'm confused by @obilginer's comment about downgrading addon_a0d7b954_nodered_14.4.5 to addon_a0d7b954_nodered_14.4.4 - I'm using the official node-red docker container, so is this part of that container? I'm not even sure how to check what version I'm running of that component - I don't see it when doing an `npm list` having `exec`d into the container so how do I even verify if that's a common component?

Sort of stumped at present how to resolve, as we have at least 5 with the same problem, doesn't look like any common packages between our configs, so seems unlikely it's a specific package unless there is something more deep rooted in one of them at the nodejs level......  

Let me see if I can get a clean node-red docker instance running to experiment some more......

**Comment by russdan** [comment]
OK, so I can confirm a clean docker container from image `nodered/node-red:latest` doesn't have any issues that I can see, if I start completely fresh (ie just stock packages) - I did a standard no auth http request using my example flow from post 1, and also a Bearer Auth request, both successful.... 

So now to work out what IS causing the issue........  clearly some baggage somewhere which is messing things up!

**Comment by 3web** [comment]
I see the follow error message:

18.9.2023, 19:17:31node: debug 3
msg.payload : string[109]
**"RequestError: connect ECONNREFUSED 127.0.0.1:443 : https://api.host.com/resource"**

--> The request is over http**S**

With the tcpdump, i can't see the request from the version 3.1. 

`tcpdump dst host xxx.xxx.xxx.xxx and port 443`

With the version 3.0.2 i can see the request with the tcpdump.

**Comment by Jeoffreybauvin** [comment]
Same issue here...

**Comment by hardillb** [comment]
Please everybody, rather than just "me too" messages please include useful details to try and help us determine a pattern here.

- Exactly which container you are using (which tag/nodejs version and which architecture you are running on)
- Are you using a 3rd party container e.g. the Home Assistant packages
- What Nodes you have installed
- What container system and version you are using (Docker, Proxmox) and what the host OS is.
- If possible what URL you are trying to access

**Comment by 3web** [comment]
I have test it with a other installation. There it works fine. I will test it tomorrow with the full "palette". The different what i see in the moment is, it dose not work in a container with a raspberry pi host. The other installation is on a vServer. But that shouldn't matter.

**Comment by Jeoffreybauvin** [comment]
@3web  I'm able to reproduce it with a fresh Node-red instance on Docker with these full packages : 

```
        "@node-red-contrib-themes/midnight-red": "^1.4.5",
        "node-red-contrib-bigtimer": "~2.8.5",
        "node-red-contrib-boolean-logic-ultimate": "~1.0.63",
        "node-red-contrib-chatbot": "~1.2.4",
        "node-red-contrib-chatbot-discord": "~1.0.2",
        "node-red-contrib-config": "~1.2.1",
        "node-red-contrib-credentials": "~0.2.2",
        "node-red-contrib-cron-plus": "~2.1.0",
        "node-red-contrib-google-oauth-calendar": "~0.1.1",
        "node-red-contrib-google-smarthome": "~0.4.4",
        "node-red-contrib-googlehome": "~0.0.15",
        "node-red-contrib-home-assistant-websocket": "~0.56.1",
        "node-red-contrib-hourglass": "~1.5.0",
        "node-red-contrib-influxdb": "~0.6.1",
        "node-red-contrib-mqtt-dynamicsub": "0.0.9",
        "node-red-contrib-plex-ws": "~0.2.4",
        "node-red-contrib-stoptimer-varidelay": "~0.5.3",
        "node-red-contrib-string": "~1.0.0",
        "node-red-contrib-suncron": "~1.6.2",
        "node-red-contrib-tesla": "~2.0.0",
        "node-red-contrib-unit-converter": "~0.0.3",
        "node-red-contrib-zigbee2mqtt": "~2.7.1",
        "node-red-node-base64": "~0.3.0",
        "node-red-node-email": "~2.0.1"
```

After testing one by one, it seems to be **node-red-contrib-mqtt-dynamicsub**. I deleted it from my empty Node-red, and it's working again.

I will do it on my prod server tomorrow.

**Comment by Jeoffreybauvin** [comment]
node-red-contrib-mqtt-dynamicsub deleted from my prod Node-red, and now everything is working fine.

**Comment by 3web** [comment]
@Jeoffreybauvin Thanks for this hint. The restart was important.

In my setup is node-red-contrib-digitaloak-mqtt the black sheep. I will search and find alternative way.

Best regards
Markus

**Comment by hardillb** [comment]
Now we know which packages we can look for common dependencies and see if we can get them fixed.

**Comment by hardillb** [comment]
Both of those nodes should now be redundant as dynamic subscription has been added to the default MQTT nodes.

`node-red-contrib-digitaloak-mqtt` includes the `https-proxy-agent` node which is likely the problem, but I can't immediately see what `node-red-contrib-mqtt-dynamicsub` is doing, but those 2 nodes are forks of each other so likely it's the same root cause.

**Comment by bogorad** [comment]
Same problem here - tries to connect to `127.0.0.1:443` instead of the requested URL.

Running inside Docker on a Raspberry pi4/Ubuntu:

`Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`

Node-red version:

```
            "Env": [
                "PATH=/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=16.20.2",
                "YARN_VERSION=1.22.19",
                "NODE_RED_VERSION=v3.1.0",
                "NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules",
                "FLOWS=flows.json"
            ],
```

Packages installed:

```
    "dependencies": {
        "@mschaeffler/node-red-asterisk-ami-manager": "~1.1.3",
        "node-red-contrib-alexa-remote2-applestrudel": "~5.0.42",
        "node-red-contrib-chronos": "~1.19.0",
        "node-red-contrib-custom-chatgpt": "~1.2.11",
        "node-red-contrib-google-oauth2": "~0.3.2",
        "node-red-contrib-home-assistant-websocket": "~0.56.1",
        "node-red-contrib-influxdb": "~0.6.1",
        "node-red-contrib-kraken": "~0.1.1",
        "node-red-contrib-mytimeout": "~3.2.2",
        "node-red-contrib-obs-ws": "~0.2.10",
        "node-red-contrib-pocket-api": "~0.0.12",
        "node-red-contrib-power-monitor": "~1.2.1",
        "node-red-contrib-presence-faker": "~1.8.6",
        "node-red-contrib-qrdecode": "0.0.2",
        "node-red-contrib-redis": "~1.3.9",
        "node-red-contrib-smartnora": "~1.20.0",
        "node-red-contrib-sunpos": "~1.4.1",
        "node-red-contrib-syslog": "~1.1.0",
        "node-red-contrib-telegrambot": "~15.1.6",
        "node-red-contrib-ui-led": "~0.4.11",
        "node-red-dashboard": "~3.6.0",
        "node-red-node-pushbullet": "~0.0.19",
        "node-red-node-rbe": "~0.5.0",
        "nodered-contrib-asterisk-ari": "~0.0.3"
    }
```

**Comment by hardillb** [comment]
@bogorad the problem node for you is: node-red-contrib-google-oauth2

removing the fixes things. There is also an issue open with the author since July 2021 to fix it, but the node appears abandoned

https://github.com/pckhib/node-red-contrib-google-oauth2/issues/14

**Comment by russdan** [comment]
Ok, I have `node-red-contrib-oauth2` installed so will see if removing it allows me to upgrade to latest.....

**Comment by hardillb** [comment]
@obilginer You will also need to find a replacement for `node-red-contrib-oauth2` before upgrading to Node-RED 3.1

**Comment by bogorad** [comment]
> the problem node for you is: node-red-contrib-google-oauth2
> 
> removing the fixes things

thank you! I'll need some other way of exporting contacts from Google then.

**Comment by russdan** [comment]
I just wanted to confirm that removing `node-red-contrib-oauth2` resolved the issues for me, so I think this can be closed?

**Comment by eddiewebb** [comment]
For folks that can't use `node-red-contrib-google-oauth2`, there is an updated library (with never reviewed PR to upstream) that fixes this, `https://flows.nodered.org/node/@dennip/node-red-google-apis`

**Comment by hardillb** [comment]
@eddiewebb please do not use closed issues to ask questions, please post to the forum or slack

**Comment by eddiewebb** [comment]
@hardillb  - I updated my comment.  You said previously 
> Thanks, we can close this and direct anybody who hits the same issue this way if needed in the future.

But it felt incomplete to direct folks to an issue that just says "dont use these things" without some pointer of replacement or action forward.

**Comment by hardillb** [comment]
The issue it to explain why it's broken (and not something Node-RED can fix), The best place to get suggestions for alternatives is the Node-RED forum, where you can discuss your use case, not here.
