### ISSUE TITLE
Expose `serialReconnectTime` to client side so that node-red-node-serialport can present value to user

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#4338]
A PR is sitting in the wings for the serial port nodes to have a settable timeout. However, there is no way for the user to know what the settings.js `serialReconnectTime` value is currently set to.  This request is to expose `serialReconnectTime` to client side via RED.settings so it can be used to inform the user of the current timeout setting when no explicit timeout is set on the node.

See item 3 in this PR comment: https://github.com/node-red/node-red-nodes/pull/1012#issuecomment-1712528977

**Comment by knolleary** [comment]
The serial port node should be updated to expose the setting as described here: https://nodered.org/docs/creating-nodes/node-js#exposing-settings-to-the-editor
