### ISSUE TITLE
Updating from v3.0.2 to v3.1.0 marked all 'link call' nodes as invalid

### ISSUE THREAD

**Issue by dudleyjosh** [node-red/node-red#4339]
### Current Behavior

Updated from v3.0.2 to v3.1.0 and the install went find and Node-RED ran fine and worked as expected but every single 'link call' node had the little red triangle marker for 'invalid node configuration' and I would get the 'The workspace contains some nodes that are not properly configured' message upon a deploy. Even though the 'link call' nodes worked as expected, I had to manually open each one, change selection and then reselect what it was, and then deploy again for the marker and the message to go away.

### Expected Behavior

I expected to update Node-RED without it marking already working nodes as 'invalid configuration'.

### Steps To Reproduce

I only had the one install to update so I haven't reproduced this issue.

### Example flow

N/A

### Environment

- Node-RED version: v3.0.2 -> v3.1.0
- Node.js version: v18.14.0
- npm version: v9.3.1
- Platform/OS: Windows Server 2012
- Browser: Chrome v116.0.5845.187 (MacOS arm64)

**Comment by knolleary** [comment]
Hi - this will be fixed by https://github.com/node-red/node-red/pull/4331
