### ISSUE TITLE
Optional chaining operator (?.)

### ISSUE THREAD

**Issue by fernando974** [node-red/node-red#4374]
### Current Behavior

The code is working as expected but i have a warning in the function node :

![image](https://github.com/node-red/node-red/assets/41994804/a953b2ee-5207-4850-b241-49ec314e2824)

### Expected Behavior

No warning displayed

### Steps To Reproduce

this code works as expected but it throw the warning
var p2 = msg.payload.event?.device_id || "empty";

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.0
- Node.js version: 16.20.2
- npm version:
- Platform/OS: Docker
- Browser: Chrome

**Comment by Steve-Mcl** [comment]
It looks like you might be using the old ACE editor. 

This is fully supported in the monaco editor.

![image](https://github.com/node-red/node-red/assets/44235289/85dfd6c7-d2bd-45f2-97bc-1efef411ac8d)

If you can access settings.js can you see what is set for the `editorTheme.codeEditor.lib`?

**Comment by fernando974** [comment]
Nothing has been set, so I suppose I am using the default editor, whatever that may be.

editorTheme: {
        /** The following property can be used to set a custom theme for the editor.
         * See https://github.com/node-red-contrib-themes/theme-collection for
         * a collection of themes to chose from.
         */
        //theme: "",
