### ISSUE TITLE
nodered 3.1 RED.hooks  is null

### ISSUE THREAD

**Issue by toplinuxsir** [node-red/node-red#4383]
### Current Behavior

RED.hooks when called in function node , RED.hooks is null

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Hooks are not available in the Function node. That is a deliberate choice.

**Comment by knolleary** [comment]
The APIs available to the function node are documented here: https://nodered.org/docs/user-guide/writing-functions#api-reference

**Comment by toplinuxsir** [comment]
@knolleary where is availabe for hooks ?
Thanks!

**Comment by knolleary** [comment]
The hooks are a runtime api. They are available to the runtime-side of nodes/plugins. They are not available in the editor.
