### ISSUE TITLE
HTTP Request node : RequestError for HTTPS links

### ISSUE THREAD

**Issue by Webbeh** [node-red/node-red#4389]
### Current Behavior

First of all, thanks for everyone contributing to this fantastic piece of software!

The `http request` node stopped working entirely for HTTPS links (whether accessed directly or through a redirect).
HTTP links that do not redirect to HTTPS work as intended.

Stack trace : 
```
RequestError: The "listener" argument must be of type function. Received an instance of Object
    at Request._beforeError (file:///usr/lib/node_modules/node-red/node_modules/got/dist/source/core/index.js:310:21)
    at Request.flush (file:///usr/lib/node_modules/node-red/node_modules/got/dist/source/core/index.js:299:18)
    at checkListener (node:events:274:3)
    at ClientRequest.once (node:events:648:3)
    at new ClientRequest (node:_http_client:239:10)
    at Object.request (node:https:378:10)
    at /var/lib/nodejs-node-red/.node-red/node_modules/agent-base/patch-core.js:25:22
    at Request._makeRequest (file:///usr/lib/node_modules/node-red/node_modules/got/dist/source/core/index.js:963:37)
    at async Request.flush (file:///usr/lib/node_modules/node-red/node_modules/got/dist/source/core/index.js:285:13)
```

### Expected Behavior

I expect the HTTPS requests to not fail.

### Steps To Reproduce

- Place a `HTTP Request` node in a flow
- Set the URL to any HTTPS:// address
- Watch it fail with
![image](https://github.com/node-red/node-red/assets/1530837/56705186-1d71-4888-b16e-69df7a1a0796)

### Example flow

```
[{"id":"baee9ee129d73bc2","type":"tab","label":"Flow 2","disabled":false,"info":"","env":[]},{"id":"404e5de5a28e8b82","type":"http request","z":"baee9ee129d73bc2","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"http://www.httpvshttps.com/check.png?1234","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":510,"y":160,"wires":[["ce38ed0de293c386"]]},{"id":"0103d210a29fe545","type":"http request","z":"baee9ee129d73bc2","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"https://www.httpvshttps.com/check.png?5678","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":510,"y":220,"wires":[["387f6b60222edd8a"]]},{"id":"112085635461616d","type":"inject","z":"baee9ee129d73bc2","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":290,"y":160,"wires":[["404e5de5a28e8b82","0103d210a29fe545"]]},{"id":"ce38ed0de293c386","type":"debug","z":"baee9ee129d73bc2","name":"debug 23","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":160,"wires":[]},{"id":"387f6b60222edd8a","type":"debug","z":"baee9ee129d73bc2","name":"debug 24","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":220,"wires":[]},{"id":"c8704c6e5d954153","type":"catch","z":"baee9ee129d73bc2","name":"","scope":null,"uncaught":false,"x":500,"y":300,"wires":[["9e4ed109447803bd"]]},{"id":"9e4ed109447803bd","type":"debug","z":"baee9ee129d73bc2","name":"debug 25","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":300,"wires":[]}]
```

### Environment

- Node-RED version: 3.1.0
- Node.js version: 20.8.1
- npm version: 10.2.0
- got version: 13.0.0
- Platform/OS: ArchLinux @ latest everything
- Browser: Firefox-developer

Modules installed both globally and inside node-red's path - which does not include `got` - are at the same version.

I keep an incremental update of my ArchLinux server, but I never really double-check if everything in Node-Red works properly or not afterwards. I am therefore unable to ascertain when exactly this bug happened. 

The only thing I am certain of is that everything worked perfectly with the latest possible version of NodeJS, Node-Red and NPM as of the end of the first week of June 2023. This is when I created a few flows that were working then but no longer working now.

Thank you for your time

**Comment by hardillb** [comment]
OK, quick test with Node 16 works correctly

**Comment by hardillb** [comment]
and with Node 18

**Comment by Webbeh** [comment]
Hello.

I do have the digitaloak-mqtt. 

Will try to disable it

**Comment by Webbeh** [comment]
Very well spotted.

Deleted node-red-contrib-digitaloak-mqtt, Uninstalled agent-base and reinstalled the nodejs-node-red package to be sure to have the right versions of everything, and it now works well again.

Thank you very much !
