### ISSUE TITLE
Monaco code editor is not closing on ⌘Enter

### ISSUE THREAD

**Issue by mu3** [node-red/node-red#4400]
### Current Behavior

Pressing ⌘Enter creates a new line instead of closing the drawer.
Ace code editor works just fine.
This is degradation as it worked in Node-RED v2 as expected.

### Expected Behavior

Close the drawer

### Steps To Reproduce

Use default settings or force to use monaco:

    {
      editorTheme: {
        codeEditor: { lib: "monaco" }
      }
    }

### Environment

- Node-RED version: 3.1.0
- Node.js version: 16.20.2
- npm version: 8.19.4
- Platform/OS: macOS / NR is running in Docker in the cloud
- Browser: Chrome

---

On a side note, the docs seem to be outdated - https://nodered.org/docs/user-guide/runtime/configuration#editor-themes

**Comment by knolleary** [comment]
Fixed via #4382 - will be in 3.1.1
