### ISSUE TITLE
Separate debug window not showing nodes in "selected nodes" filter

### ISSUE THREAD

**Issue by evazzoler** [node-red/node-red#4401]
### Current Behavior

Nothing to say more than the title

### Expected Behavior

To see a tree structure list as in embedded debug tab

### Steps To Reproduce

Open debug in a separate window and try to use filters ("selected node" not working properly, too)

### Example flow

not necessary...

### Environment

- Node-RED version: 3.1.0
- Node.js version: 18.17.1
- npm version: 9.6.7
- Platform/OS: Linux Debian (server) / Linux Ubuntu (client)
- Browser: Chrome latest, Firefox latest, make no difference.

**Comment by knolleary** [comment]
Fixed since NR 3.1.1
