### ISSUE TITLE
No topic causes all MQTT nodes to disconnect

### ISSUE THREAD

**Issue by smcgann99** [node-red/node-red#4414]
### Current Behavior

I noticed that injecting a message into MQTT out node without setting a topic causes all MQTT nodes to disconnect for a few seconds.

I realise it should have a topic, but the node should really handle this more gracefully

### Expected Behavior

The node should just show an error and the message should not be passed on to the broker, since this then affects all flows.

### Steps To Reproduce

Just inject a msg without any topic set into an MQTT node configured without a topic.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.0
- Node.js version: 18.17.1
- npm version: 9.6.7
- Platform/OS: RPi Bullseye
- Browser: Chrome

**Comment by smcgann99** [comment]
Also it should probably check for wild cards in the topic see [here](https://discourse.nodered.org/t/publishing-to-a-wildcard-mqtt-topic-disconnects-all-mqtt-nodes/23244l)

**Comment by dceejay** [comment]
It does already test for wildcards...
