### ISSUE TITLE
Nodered workspace freezes when placeholder node appears when only custom nodes are enabled

### ISSUE THREAD

**Issue by chiru091096** [node-red/node-red#4415]
### Current Behavior

When nodes in nodered are disabled (except custom nodes) keeping only custom nodes (tested 5 different  kinds of custom nodes) by adding the nodes in _nodesExcludes_ list in settings.js  and then, when I press on the output port of a custom node in workspace and drag and drop on the workspace, a placeholder node appears. However, search bar and list of nodes doesn't appear as shown in below representation purpose only image) and workspace freezes and no more actions can be performed

![custom-node](https://github.com/node-red/node-red/assets/17933053/dea65265-0aed-487f-a8f0-e0f081938de2)

**Pleae refer below thread for detailed description :**
https://discourse.nodered.org/t/nodered-workspace-freezes-when-placeholder-node-appears-when-only-custom-nodes-are-enabled/82550

### Expected Behavior

When I press on the output port of a custom node and drag and drop on the workspace,  placeholder node should appear. Along with that a search bar and list of my available custom nodes should appear as shown in below image.

![catch-node](https://github.com/node-red/node-red/assets/17933053/f52b0051-c03b-4dab-a8b5-7b186eb3a7a1)

### Steps To Reproduce

1. Add few different types of custom nodes to Node RED.
2. Disable default nodes in Node RED by adding them to nodesExcludes list
`nodesExcludes: ['05-junction.js', '24-complete.js', '20-inject.js', '21-debug.js', '25-catch.js', '25-status.js', '60-link.js', '90-comment.js', '98-unknown.js', '10-function.js', '10-switch.js', '15-change.js', '16-range.js', '80-template.js', '89-delay.js', '89-trigger.js', '90-exec.js', 'rbe.js', '05-tls.js', '06-httpproxy.js', '31-tcpin.js', '32-udp.js', '10-mqtt.js', '21-httpin.js', '22-websocket.js', '21-httprequest.js', '70-CSV.js', '70-HTML.js', '70-JSON.js', '70-XML.js', '70-YAML.js', '17-split.js', '18-sort.js', '19-batch.js', '10-file.js', '23-watch.js']`
3. Drag and drop a custom node to workspace.
4. Press on the output port of a custom node in workspace and drag and drop on the workspace, a placeholder node appears. However, search bar and list of nodes doesn't appear.

### Environment

- Node-RED version: 3.1.0
- Node.js version: 16.17.0
- npm version: 8.15.0
- Platform/OS: Ubuntu 20.04.6
- Browser: Chrome

**Comment by marcus-j-davies** [comment]
Reproducible.

**Browser** : Safari
**Node RED** : 3.1.0
**Node** : 18.18.0


![Nov-03-2023 06-29-54](https://github.com/node-red/node-red/assets/55892693/ea3c492c-7086-4ba9-b7ea-7e4b2e888883)

**Browser Log**
![Screenshot 2023-11-03 at 06 35 15](https://github.com/node-red/node-red/assets/55892693/a4741603-83f0-4535-b83f-7803fccb060b)

**Comment by knolleary** [comment]
The quick-add dialog makes some assumptions about the presence of some core nodes so they get shown at the top of the list. We need to add some guards in case those nodes have been disabled.
