### ISSUE TITLE
Status background persisting

### ISSUE THREAD

**Issue by malee1975** [node-red/node-red#4418]
### Current Behavior

Since version 3.1.0 there seems to be the addition of node-status-background to the UI. After a flow has been executed this component appears to persist with a width of 6px and a height of 13px. Applying a CSS rule of width: auto appears to resolve the issue. Is it a known bug?
![Screenshot 2023-11-03 155547](https://github.com/node-red/node-red/assets/140089412/c0b2b7ab-a5f0-4e90-8cbd-aaab55cf0404)
 

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.0
- Node.js version: 18
- npm version:
- Platform/OS: Windows 11/Windows Server 2022
- Browser: Chrome/Edge/Firefox

**Comment by knolleary** [comment]
Fixed by #4425
