### ISSUE TITLE
Click behaviour of groups is very distracting

### ISSUE THREAD

**Issue by jankokert** [node-red/node-red#4419]
### Current Behavior

Prerequisites:
Select some nodes and group them with: 'Groups' -> 'Group selection'.
1. Click on an empty spot within the group -> nothing is selected.
2. Click on one node within the group -> the group is selected.
3. Click again one node within the group -> the node is selected

This is so confusing!

### Expected Behavior

1. Click on an empty spot within the group -> the group is selected.
2. Click on one node within the group -> the node is selected.

I know this is probably more a change request (?). But from the usability point of view, this is a bug.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
What version of Node-RED are you using? The way of interacting with groups was completely overhauled in the recent 3.1 release and I believe it addresses most of your feedback.

**Comment by jankokert** [comment]
Dear Nick O'Lear,

thank you very much for your fast support.
You are right! I've been using an old version. 
Now with 3.1 it is the perfect behaviour!
Thank you very much overall for this great tool and the long development over the year!

You can close the ticket.
