### ISSUE TITLE
Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback

### ISSUE THREAD

**Issue by stain3565** [node-red/node-red#4420]
### Current Behavior

Using Node Red addon, not Docker.

Debug containing following messages:

`msg : string[270]
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."
04/11/2023, 14:30:03
msg : string[1836]
"Error: ↵    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)↵    at JSONataService.evaluate (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)↵    at TypedInputService.getValue (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)↵    at EventsAll.getTypedInputValue (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:134:39)↵    at /config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:138:32↵    at Array.forEach (<anonymous>)↵    at EventsAll.setCustomOutputs (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:137:20)↵    at EventsAll.onHaEventsAll (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/events-all/controller.js:57:18)↵    at EventEmitter.<an..."
04/11/2023, 14:30:03
msg : string[270]
`

### Expected Behavior

Only debug messages for flow being run should be displayed. Debug unusable as flooded with "Deprecated" messages.

I realise that back in September, there were workarounds. However, I have not had to debug anything until today and versions have changed so wary of attempting any of the workarounds suggested, given later code changes in Node Red. Also, many suggestions suggested files in opt and usr folders.

Examples are: 
/opt/node_modules/@node-red/util/lib/util.js
/usr/share/hassio/addons.json

folders hassio and node-modules do not even exist when I navigate in terminal. I m not aware that I have hidden folders although am happy to check if required (may need guidance).

Given the time passed and the numerous other changes I have made in HA since September, as full restore is not suitable and any partial restore of addons would need to reflect any other software code changes that have occurred.

Ideally, a permanent solution, if available now, would be ideal. If not, a workaround that i can carry out and at least a confirmation that others still have this issue so that I know a full fix will be looked at in the future. If it is just me still getting these, I could be up a creek regarding any Node Red debugging in the future.

### Steps To Reproduce

Just open node red and a debug window

### Example flow

```
paste your flow here
```

Not applicable

### Environment

- Node-RED version: 3.1.0
- Node.js version: using supervisor
- npm version: using supervisor
- Platform/OS: Core 2023.11.0  Supervisor 2023.10.1  Operating System 11.1  Frontend 20231030.1
- Browser: Chrome
- NodeRedCompanion version: 3.0.1

**Comment by knolleary** [comment]
This is an issue with `node-red-contrib-home-assistant-websocket` using a deprecated API. That had been fixed in their 0.57.0 release of that module.

Upgrading to that version should resolve it for you.

**Comment by stain3565** [comment]
Thanks. I lost that info in all of the suggestions in previous issues. Yes, that worked.
