### ISSUE TITLE
Errorcode 11 on Startup

### ISSUE THREAD

**Issue by derrobin154** [node-red/node-red#4430]
### Current Behavior

Node-RED crashes after startup with error code 11

Error on node-red-log:
Started Node-RED graphical event wiring tool.
nodered.service: Main process exited, code=killed, status=11/SEGV
nodered.service: Failed with result 'signal'.
nodered.service: Consumed 1.892s CPU time.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: current via apt
- Node.js version: 18.18.0
- npm version: 9.8.1
- Platform/OS: Raspbian
- Browser: Firefox

**Comment by hardillb** [comment]
What type of pi are you running on?

**Comment by derrobin154** [comment]
> What type of pi are you running on?

3B

**Comment by hardillb** [comment]
Please provide the following output

- `node -version`
- `uname -a`
- `node-red`

**Comment by derrobin154** [comment]
- v18.18.0
- Linux pi01 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
- Speicherzugriffsfehler

**Comment by hardillb** [comment]
There is no other output than `Speicherzugriffsfehler` when you run `node-red`?

What do you get if you just run `node`?

**Comment by derrobin154** [comment]
> There is no other output than `Speicherzugriffsfehler` when you run `node-red`?
> 
> What do you get if you just run `node`?

No it's only this.

Node:
Welcome to Node.js v18.18.0.
Type ".help" for more information.

**Comment by hardillb** [comment]
Best guess is that there is miss match between one of the native modules Node-RED uses and the version of NodeJS you are running.

I suggest you run the install script from [here](https://nodered.org/docs/getting-started/raspberrypi) to do a clean install and it will ensure all the modules are built against the right NodeJS level.

**Comment by derrobin154** [comment]
But it worked until day X without any problems. And I haven't added any modules or anything like that since then.

**Comment by hardillb** [comment]
But have you updated other things or upgraded NodeJS if so from what version?

How exactly did you install NodeJS? 

What exact version of Raspberry Pi OS are you running on?

What is the output of `dpkg -s node-red | grep '^Version:'`

The apt packaged version of Node-RED will ONLY work with the version of NodeJS packaged and shipped in the same apt repository (and even then I'd have to check to see if the packages were actually updated with the latest bookworm build)

The other option is that the SD card is now corrupt.

**Comment by dceejay** [comment]
fyi - apt version was def not built against bookworm. Use our install script instead.

**Comment by derrobin154** [comment]
> dpkg -s node-red | grep '^Version:'

Version: 2.2.3-2

**Comment by derrobin154** [comment]
After apt-get remove nodered and apt-get install nodered i will get this. 

sudo apt-get install nodered -f
Paketlisten werden gelesen... Fertig
Abh�ngigkeitsbaum wird aufgebaut... Fertig
Statusinformationen werden eingelesen... Fertig
Die folgenden NEUEN Pakete werden installiert:
  nodered
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 170 nicht aktualisiert.
Es m�ssen noch 0 B von 8.348 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 69,9 MB Plattenplatz zus�tzlich benutzt.
(Lese Datenbank ... 49567 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../nodered_2.2.3-2_armhf.deb ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/nodered_2.2.3-2_armhf.deb (--unpack):
 �neues nodered-Skript des Paketes pre-installation�-Unterprozess gab den Fehlerwert 5 zur�ck
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/nodered_2.2.3-2_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by hardillb** [comment]
OK Node-RED 2.2.3 is 2 major versions behind (and version 4.0 will ship real soon now).

As previously mentioned please use the install script from here: https://nodered.org/docs/getting-started/raspberrypi this will install a version that will work with NodeJS 18.

@dceejay we need to get that apk either updated or removed because it should not be still installing 2.2.3 for anybody

**Comment by derrobin154** [comment]
> OK Node-RED 2.2.3 is 2 major versions behind (and version 4.0 will ship real soon now).
> 
> As previously mentioned please use the install script from here: https://nodered.org/docs/getting-started/raspberrypi this will install a version that will work with NodeJS 18.
> 
> @dceejay we need to get that apk either updated or removed because it should not be still installing 2.2.3 for anybody

Thanks for your help. But with the Install on the Script and node-red-start i become this error

Started Node-RED graphical event wiring tool.
/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:797
    if (sendEvent?.destination?.node) {
                  ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 2.703s CPU time.

**Comment by hardillb** [comment]
That error implies that Node-RED is not running NodeJS 18 as the error is complaining about the `?.`  syntax which is was not introduced until NodeJS 14.

How exactly did you run the install script and how did you install NodeJS 18? Are you using a tool like `nvm`?

I'm going to guess that the error is coming from running Node-RED as a service and as a result is running with the system version of NodeJS which is probably NodeJS v12. You never did answer what version of Rapberry Pi OS you are running on?

**Comment by derrobin154** [comment]
I recognized the Problem with NodeJS. I uninstall NodeJS and let run the Installer again. 

Now i can't start node-red with node-red-start, i become this message:

Node-RED is not yet fully installed. Please re-run the install script again manually.
 
   bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
 
then retry  node-red-start

Installer Output:

This can take 20-30 minutes on the slower Pi versions - please wait.

  Stop Node-RED                       \u2714
  Remove old version of Node-RED      \u2714
  Using NVM to manage Node.js         +   please run   nvm use lts   before running Node-RED
  NOTE: Using nvm is NOT RECOMMENDED.     Node-RED will not run as a service under nvm.
  Update Node.js 18                   \u2714   v18.18.2   Npm 9.8.1
  Clean npm cache                     \u2714
  Install Node-RED core               \u2714   3.1.0
  Move global nodes to local          -
  Npm rebuild existing nodes          \u2714
  Install extra Pi nodes              \u2714
  Add shortcut commands               \u2714
  Update systemd script               \u2714

**Comment by hardillb** [comment]
```
Using NVM to manage Node.js + please run nvm use lts before running Node-RED
NOTE: Using nvm is NOT RECOMMENDED. Node-RED will not run as a service under nvm.
```
The installer did say that it would not work as a service (which is what `node-red-start` does).

If you want to run Node-RED as a service you should also uninstall nvm.

**Comment by hardillb** [comment]
You can try running `node-red` which will run Node-RED in the foreground to see if it starts properly with the nvm installed NodeJS 18.

**Comment by derrobin154** [comment]
> ```
> Using NVM to manage Node.js + please run nvm use lts before running Node-RED
> NOTE: Using nvm is NOT RECOMMENDED. Node-RED will not run as a service under nvm.
> ```
> 
> The installer did say that it would not work as a service (which is what `node-red-start` does).
> 
> If you want to run Node-RED as a service you should also uninstall nvm.

I can't remember installing nvm. When I unload nvm, the same message still appears in the installer. When I do nvm deactivate I get nvm command not found.

**Comment by hardillb** [comment]
You want nvm totally removed, then run the installer again, it should upgrade the OS version of NodeJS and install Node-RED 3.1.

And Please answer the question about what version of Raspberry Pi OS you are running.

**Comment by derrobin154** [comment]
> You want nvm totally removed, then run the installer again (probably with `--node18` passed as an argument), it should upgrade the OS version of NodeJS and install Node-RED 3.1.
> 
> ```
> bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --node18
> ```
> 
> And Please answer the question about what version of Raspberry Pi OS you are running.
OS: Linux pi01 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux


When i execute the Command that you wrote, i become the same message with nvm

**Comment by hardillb** [comment]
That is just the kernel version not the OS version. Please run  `lsb_release -a`

**Comment by derrobin154** [comment]
Okay. I found the Problem. nvm was uninstalled but not in .bashrc Now it works without any Problems. Thank you! @hardillb
