### ISSUE TITLE
Uncaught Exception: Date in past. Will never be fired.

### ISSUE THREAD

**Issue by m-schaeffler** [node-red/node-red#4434]
### Current Behavior

NodeRed crashed with this output:
`11 Nov 09:09:01 - [red] Uncaught Exception:
11 Nov 09:09:01 - [error] Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/srv/node-red/.node-red/node_modules/cron/dist/time.js:93:23)
    at CronTime.getTimeout (/srv/node-red/.node-red/node_modules/cron/dist/time.js:110:34)
    at Timeout.callbackWrapper [as _onTimeout] (/srv/node-red/.node-red/node_modules/cron/dist/job.js:119:48)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 30min 39.255s CPU time.
nodered.service: Scheduled restart job, restart counter is at 2.
Stopped nodered.service - Node-RED graphical event wiring tool.
nodered.service: Consumed 30min 39.255s CPU time.
Starting nodered.service - Node-RED graphical event wiring tool...
Started nodered.service - Node-RED graphical event wiring tool.
11 Nov 09:09:24 - [info]
Willkommen bei Node-RED
===================
11 Nov 09:09:24 - [info] Node-RED Version: v3.1.0
11 Nov 09:09:24 - [info] Node.js  Version: v20.5.1
11 Nov 09:09:24 - [info] Linux 6.1.0-rpi4-rpi-v7l arm LE
11 Nov 09:09:27 - [info] Paletten-Nodes werden geladen
11 Nov 09:09:30 - [info] Dashboard version 3.6.1 started at /ui`
and was automatically restarted

### Expected Behavior

no crash

### Steps To Reproduce

unknown

### Environment

- Node-RED version: 3.1.0
- Node.js version: 20.5.1
- npm version:
- Platform/OS: Raspberry OS bookworm
- Browser: no connection at this time

**Comment by m-schaeffler** [comment]
at also happened yesterday:
`10 Nov 20:03:04 - [red] Uncaught Exception:
10 Nov 20:03:04 - [error] Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/srv/node-red/.node-red/node_modules/cron/dist/time.js:93:23)
    at CronTime.getTimeout (/srv/node-red/.node-red/node_modules/cron/dist/time.js:110:34)
    at Timeout.callbackWrapper [as _onTimeout] (/srv/node-red/.node-red/node_modules/cron/dist/job.js:119:48)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 5h 32min 30.470s CPU time.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped nodered.service - Node-RED graphical event wiring tool.
nodered.service: Consumed 5h 32min 30.470s CPU time.
Starting nodered.service - Node-RED graphical event wiring tool...
Started nodered.service - Node-RED graphical event wiring tool.
`

**Comment by hardillb** [comment]
What nodes are you using in your flow that make use of times

**Comment by m-schaeffler** [comment]
inject, cron-plus

**Comment by m-schaeffler** [comment]
could this be caused by this construction:
![Bildschirmfoto vom 2023-11-11 10-27-01](https://github.com/node-red/node-red/assets/31366299/8489bba8-7cb5-4eab-adab-b77211c7e1b7)
`[{"id":"2db6579cd0f577f4","type":"cronplus","z":"3c59326457645408","name":"cyclic","outputField":"payload","timeZone":"","storeName":"storeInFile","commandResponseMsgOutput":"output1","defaultLocation":"position","defaultLocationType":"env","outputs":1,"options":[{"name":"schedule1","topic":"cyclic","payloadType":"default","payload":"","expressionType":"cron","expression":"0 */10 * * * * *","location":"","offset":"0","solarType":"all","solarEvents":"sunrise,sunset"}],"x":370,"y":1220,"wires":[["36310bb25d3a61c2"]]},{"id":"32b2a623b9986069","type":"cronplus","z":"3c59326457645408","name":"active","outputField":"payload","timeZone":"","storeName":"","commandResponseMsgOutput":"output1","defaultLocation":"position","defaultLocationType":"env","outputs":1,"options":[{"name":"schedule2","topic":"start-all","payloadType":"default","payload":"","expressionType":"solar","expression":"0 * * * * * *","location":"","offset":"0","solarType":"selected","solarEvents":"sunriseEnd"},{"name":"schedule3","topic":"stop-all","payloadType":"default","payload":"","expressionType":"solar","expression":"0 * * * * * *","location":"","offset":"0","solarType":"selected","solarEvents":"sunsetStart"}],"x":210,"y":1240,"wires":[["2db6579cd0f577f4"]]}]`

**Comment by hardillb** [comment]
Yes it could be the cause, but it may also be that the time on your device is changing.

I haven't played with Bookworm yet, but I know the new Raspberry Pi 5 has a built in RTC so how Raspberry Pi OS keeps time will definitely have changed.

I suggest you raise this with the cron-plus node but also look in the `journalctl` logs to see if the time had been updated by something like ntpd around the time of the failure.

**Comment by knolleary** [comment]
@m-schaeffler if you are seeing an issue with the `cron-plus` node, then please raise it in its repository - that is not a node the code Node-RED project maintains: https://github.com/Steve-Mcl/node-red-contrib-cron-plus
