### ISSUE TITLE
Change node changing flow vars instead of node  messages

### ISSUE THREAD

**Issue by jj-uk** [node-red/node-red#4444]
### Current Behavior

A function is used to retrieve flow variables into a message.
A change node is used to change that message.
The flow variables are changed erroneously instead of the node message.

### Expected Behavior

The node message is changed.
The flow variables remain unchanged

### Steps To Reproduce

![image](https://github.com/node-red/node-red/assets/10943625/8bb2df78-12c8-43f5-8636-deafbcda846a)

Using the example flow:

Click the trigger. Flow vars are created.

Click the timestamp (middle row) to output the flow vars to the debug console.
The flow vars are displayed.

![image](https://github.com/node-red/node-red/assets/10943625/5785fe4e-a543-491d-87f2-47ad4c257ff1)

Click the timestamp (bottom row) to change the node message and output to the debug console.
The node message is changed (correct).

Click the timestamp (middle row) to output the flow vars to the debug console.
The flow vars are displayed and they have been changed, which is incorrect.

![image](https://github.com/node-red/node-red/assets/10943625/6dc48634-69f1-4269-9b5a-6ab79cf273f1)

Change node should change node messages, not flow variables.

Here is the debug output:

![image](https://github.com/node-red/node-red/assets/10943625/ec8cc2c1-fd7f-4500-912e-973f1caced20)

### Example flow

[{"id":"9499af8a9934ed3a","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"d76b2c4a80142f8e","type":"debug","z":"9499af8a9934ed3a","name":"debug 93","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1060,"y":460,"wires":[]},{"id":"d378c1e2c55a70b6","type":"function","z":"9499af8a9934ed3a","name":"get flow vars","func":"var msgs = flow.get('heater_switch_and_valve_pairs');\nreturn [msgs];\n\n\n","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":610,"y":460,"wires":[["d76b2c4a80142f8e"]]},{"id":"03bc1925b5459beb","type":"inject","z":"9499af8a9934ed3a","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":420,"y":460,"wires":[["d378c1e2c55a70b6"]]},{"id":"4593ec66120dfaea","type":"change","z":"9499af8a9934ed3a","name":"send keep alive msg","rules":[{"t":"set","p":"topic","pt":"msg","to":"valve_keepalive_topic","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"valve_keepalive_payload","tot":"msg"},{"t":"delete","p":"heater_id","pt":"msg"},{"t":"delete","p":"valve_id","pt":"msg"},{"t":"delete","p":"valve_keepalive_topic","pt":"msg"},{"t":"delete","p":"valve_keepalive_payload","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":840,"y":560,"wires":[["65439a6bcca276b9"]]},{"id":"b7f5aea765808ef6","type":"inject","z":"9499af8a9934ed3a","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":420,"y":560,"wires":[["54153a11e80a4559"]]},{"id":"54153a11e80a4559","type":"function","z":"9499af8a9934ed3a","name":"get flow vars","func":"var msgs = flow.get('heater_switch_and_valve_pairs');\nreturn [msgs];\n\n\n","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":610,"y":560,"wires":[["4593ec66120dfaea"]]},{"id":"121e8649d11acbd0","type":"function","z":"9499af8a9934ed3a","name":"Configure Home Assistant Entities","func":"flow.set(\"heater_switch_and_valve_pairs\", \n    [\n        {\n            heater_id: \"my-heater-id-1\",\n            valve_id: \"my-valve-id-1\",\n            valve_keepalive_topic: \"my-topic-1\",\n            valve_keepalive_payload: \"my-payload-1\"\n        }\n        // {\n        //     heater_id: \"input_boolean.heating_system_backroom_heater\",\n        //     valve_id: \"climate.heating_system_backroom_rad_valve\",\n        //     valve_keepalive_topic: \"Backroom Rad valve/set/\",\n        //     valve_keepalive_payload: \"{\\\"eco_temperature\\\":20, \\\"preset\\\":\\\"manual\\\", \\\"child_lock\\\":\\\"LOCK\\\"}\"\n        // }\n    ]\n);\n\n\n","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":660,"y":360,"wires":[[]]},{"id":"437646539cf12bd4","type":"inject","z":"9499af8a9934ed3a","name":"trigger","props":[],"repeat":"","crontab":"","once":true,"onceDelay":"0.1","topic":"","x":410,"y":360,"wires":[["121e8649d11acbd0"]]},{"id":"65439a6bcca276b9","type":"debug","z":"9499af8a9934ed3a","name":"debug 94","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1060,"y":560,"wires":[]}]

### Environment

- Node-RED version: 3.1.0
- Node.js version:v18.18.2
- npm version:
- Platform/OS:
- Browser: Google Chrome 119.0.6045.160 running on Win10.

Node red is running as an add-on in home assistant, node red startup log:

15 Nov 18:01:59 - [info] Node-RED version: v3.1.0
15 Nov 18:01:59 - [info] Node.js  version: v18.18.2
15 Nov 18:01:59 - [info] Linux 6.1.59 x64 LE
15 Nov 18:01:59 - [info] Loading palette nodes
15 Nov 18:02:01 - [info] Dashboard version 3.6.1 started at /endpoint/ui
15 Nov 18:02:01 - [info] Settings file  : /etc/node-red/config.js
15 Nov 18:02:01 - [info] Context store  : 'default' [module=memory]
15 Nov 18:02:01 - [info] User directory : /config/
15 Nov 18:02:01 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Nov 18:02:01 - [info] Flows file     : /config/flows.json
15 Nov 18:02:01 - [info] Server now running at http://127.0.0.1:46836/
15 Nov 18:02:01 - [info] Starting flows
15 Nov 18:02:01 - [info] Started flows

Node red for Home Assistant:
https://github.com/hassio-addons/addon-node-red/tree/v16.0.2

**Comment by hardillb** [comment]
This is because nodejs is a pass by reference language.

Which means when you assign the flow var to the message all you are doing is adding a reference to the flow var to the message.

If you don't want to do that you will need to take a copy in the function node.

This is working as intended

**Comment by jj-uk** [comment]
Thanks for the reply. The function node does take a copy (var msgs) :

var msgs = flow.get('heater_switch_and_valve_pairs');
return [msgs];

**Comment by hardillb** [comment]
That is not copying the value, it is just assigning a reference

**Comment by jj-uk** [comment]
Thank you. This is now doing what I expected it to do.
