### ISSUE TITLE
Nested Environment Variables Not Working in Subflows in 3.1.0  but were working fine in 3.0.2

### ISSUE THREAD

**Issue by iilievdev** [node-red/node-red#4458]
### Current Behavior

Two Subflow variables, 2nd one references the 1st. At subflow instantiation time (debug node connected to input), as well as MQTT node listening using the 2nd variable we can see that the 1st variable was evaluated as empty, but it is not.

### Expected Behavior

Both variables can be resolved and printed when the subflow starts

### Steps To Reproduce

Scenario:
1) We have a Flow environment variable named FLOW_VAR
2) Inside the Flow we have Subflow which is instantiated 
3) Subflow has two variables, PREFIX and TOPIC, TOPIC reference PREFIX
4) Printing both variables in a debug node connected to the subflow Input - PREFIX has value, and TOPIC has replaced the ${PREFIX} reference with an empty string
5) Same exact configuration works perfectly fine in 3.0.2

![image](https://github.com/node-red/node-red/assets/129042499/cebb3e9f-5967-4a78-9d98-96c053141ec7)

I added an example flow created in 3.1.0 - interesting this is I can't import it back to 3.0.2 but I can create the same flow in 3.0.2 which works fine there and once I import it to 3.1.0 it has the bug.

### Example flow

```
[{"id":"23fcd9899514ad3b","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":360,"y":160,"wires":[{"id":"9c67a5a9351b7968"}]}],"out":[],"env":[{"name":"PREFIX","type":"env","value":"HELLO/${FLOW_VAR}"},{"name":"TOPIC","type":"env","value":"${PREFIX}/GOODBYE"}],"meta":{},"color":"#DDAA99"},{"id":"9c67a5a9351b7968","type":"debug","z":"23fcd9899514ad3b","name":"debug 26","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"\"TEST FLOW ENV VARS: PREFIX:\" & $env('PREFIX') &\" | TOPIC: \" & $env('TOPIC')","targetType":"jsonata","statusVal":"","statusType":"auto","x":500,"y":160,"wires":[]},{"id":"f2529df9d0f5f45c","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[{"name":"FLOW_VAR","value":"STRING1","type":"str"}]},{"id":"bfa772d116863756","type":"inject","z":"f2529df9d0f5f45c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":710,"y":140,"wires":[["72f60314bb7bd11a"]]},{"id":"72f60314bb7bd11a","type":"subflow:23fcd9899514ad3b","z":"f2529df9d0f5f45c","name":"","x":900,"y":120,"wires":[]}]
```

### Environment

- Node-RED version: 3.1.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
I think this has already been fixed in git ahead of the 3.1.1 release. Ill double check tomorrow when I'm near my laptop.
