### ISSUE TITLE
Subflow issue when deleting part of a payload after its seconds use

### ISSUE THREAD

**Issue by philosoma** [node-red/node-red#4479]
### Current Behavior

First function block in the subflow pulls a msg from an environment variable. Second function node does a node.send for msg.payload.scene_recall only. It then deletes msg.payload.scene_recall and sends the remaining msg.

After a deploy, msg.payload.scene_recall is 1 after pressing the inject which is what I am expecting, but all subsequent values after pressing inject again are _undefined_. Redeploying again fixes the first use of it, then continues to return _undefined_.

Removing the delete function works, but I don't want msg.payload.scene_recall in the second output message.

### Expected Behavior

Every press of the inject should result in msg.payload.scene_recall having the value of 1, as it is defined in the environment variable. In Node-RED 3.0.2 which I have running at work, importing this flow works as expected. 

### Steps To Reproduce

On a fresh install using the Pi script for 3.1.3, importing the example flow shows the unexpected behavior. 

### Example flow

```
[
    {
        "id": "e65d31bfdddd6304",
        "type": "subflow",
        "name": "Subflow",
        "info": "",
        "category": "",
        "in": [
            {
                "x": 50,
                "y": 30,
                "wires": [
                    {
                        "id": "a1406e94a89f74f0"
                    }
                ]
            }
        ],
        "out": [
            {
                "x": 410,
                "y": 30,
                "wires": [
                    {
                        "id": "25253845f3c71d51",
                        "port": 0
                    }
                ]
            }
        ],
        "env": [
            {
                "name": "on_press_release",
                "type": "json",
                "value": "{}"
            }
        ],
        "meta": {},
        "color": "#DDAA99"
    },
    {
        "id": "25253845f3c71d51",
        "type": "function",
        "z": "e65d31bfdddd6304",
        "name": "Send",
        "func": "node.send({ payload: { scene_recall: msg.payload.scene_recall} });\ndelete msg.payload.scene_recall;\nnode.send(msg);",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 300,
        "y": 30,
        "wires": [
            []
        ]
    },
    {
        "id": "a1406e94a89f74f0",
        "type": "function",
        "z": "e65d31bfdddd6304",
        "name": "Get",
        "func": "msg = env.get(\"on_press_release\");\nreturn msg;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 160,
        "y": 30,
        "wires": [
            [
                "25253845f3c71d51"
            ]
        ]
    },
    {
        "id": "84938341927d6224",
        "type": "inject",
        "z": "33871f41.a966a",
        "name": "Inject",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 330,
        "y": 3500,
        "wires": [
            [
                "6886a99e68258e66"
            ]
        ]
    },
    {
        "id": "3a48d53a659dc67f",
        "type": "debug",
        "z": "33871f41.a966a",
        "name": "Output",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 650,
        "y": 3500,
        "wires": []
    },
    {
        "id": "6886a99e68258e66",
        "type": "subflow:e65d31bfdddd6304",
        "z": "33871f41.a966a",
        "name": "",
        "env": [
            {
                "name": "on_press_release",
                "value": "{\"payload\":{\"state\":\"ON\",\"brightness\":52,\"transition\":1.6,\"scene_recall\":1}}",
                "type": "json"
            }
        ],
        "x": 490,
        "y": 3500,
        "wires": [
            [
                "3a48d53a659dc67f"
            ]
        ]
    }
]
```

### Environment

- Node-RED version: 3.1.3
- Node.js version: 18.19.0
- npm version: 10.2.3
- Platform/OS: Debian 12.3
- Browser: Chrome 120.0.6099.71

**Comment by knolleary** [comment]
Env properties are intended to be read-only values that should not be updated by flows.

You've found an edge case where using a JSON type env gives you an object that you have been able to modify. That is not intended behaviour.

In 3.1 we changed how env vars are evaluated - they get evaluated at start rather than on-demand. This likely explains the change in behaviour you've seen.


If you want to store values that can be modified by the flows you should use context.

**Comment by philosoma** [comment]
Hi Nick, thanks for the reply!

Forgive my basic understanding, but I am just reading the env var to a msg and then changing the msg? The msg should be temporary, gone as soon as the subflow is finished? I don't understand why it is changing the env var, I'm not intending to change it. Like with context I have to flow.set and there is no env.set.

But if I add msg.payload.scene back after my second message it works as I intend so thank you!

**Comment by knolleary** [comment]
Ah okay. I can see what's happening - will sort out a fix to avoid the (unintended) downstream modification of the env var.
