### ISSUE TITLE
Unable to use a database for adminAuth

### ISSUE THREAD

**Issue by YeeYiFeng** [node-red/node-red#4481]
settings.js
![image](https://github.com/node-red/node-red/assets/104192029/3d255034-f233-4628-9cd9-861fc6574b9e)

db.js
![image](https://github.com/node-red/node-red/assets/104192029/f7f0c063-71bf-4e2d-b552-163b0704040f)

sql database
![Uploading image.png…]()

I have been trying to use a sql database as the login for node-red. However, I have come across the issue where the function runs last and thus does not overwrite the users in adminAuth.

**Comment by hardillb** [comment]
Please ask "how to" questions on the Node-RED discourse forum or the Node-RED slack then everybody can help to answer them. Links to both can be found on the Node-RED homepage.

The documentation on how to do custom authentication is here: https://nodered.org/docs/user-guide/runtime/securing-node-red#custom-user-authentication

When asking please do not post images of code, attach the whole `settings.js` so we can see how you have set everything.
