### ISSUE TITLE
"import" should be "require"

### ISSUE THREAD

**Issue by lucianohsmelo** [node-red/node-red#4482]
### Current Behavior

![image](https://github.com/node-red/node-red/assets/25434788/a44dd0ef-8699-4c08-87af-9634d2ddd336)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
The latest version of the got module does not support `require` and can only be imported via dynamic import. We have had this code in place for quite some time and works well.

Your issue contains to details as to what problem you are hitting that has led you to raise this.

Can you share any more details?

**Comment by hardillb** [comment]
That is something you should take up with the pkg, it needs to support modules that use import

**Comment by hardillb** [comment]
Having looked at some issue on the pkg repo, it looks like they don't support ES6 modules, so this is a problem with pkg and you'll have to those threads to see if any of the proposed solutions will work for you, but this is not a problem with Node-RED

https://github.com/vercel/pkg/issues/1291

https://github.com/vercel/pkg/pull/1323
