### ISSUE TITLE
Flows stopped due to missing node types

### ISSUE THREAD

**Issue by DL4DP** [node-red/node-red#4486]
### Current Behavior

Hello everyone,

Now my automation ran for a few days, but now after the next update some things no longer work.

Sometimes the functions are there for a short time and then they are gone again.

Is there a solution?

Flows stopped due to missing node types

server
ha-entity-config
ha-device-config
ha binary sensor
ha sensor
ha-update-config
ha button
api call service
server-state-changed
api-current-state

Dirk wishes you a good start to the weekend

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
As stated in the template, please ask questions on the Node-RED Discourse Forum or the Node-RED Slack so the whole community can assist. Links to both can be found on the Node-RED home page.

But as this appears to be a Home Assistant problem you will probably do better raising this with the team that look after the Home Assistant integration as the core Node-RED team do not use Home Assistant.

**Comment by magiva** [comment]
@DL4DP did you find a fix for this ?
