### ISSUE TITLE
Respect `.npmrc` for package registry

### ISSUE THREAD

**Issue by sachaw** [node-red/node-red#4496]
### Current Behavior

When installing a package that relies on the presence of a `.npmrc` file for accessing a dependency from an alternate package registry, currently the install fails.
an example of this is: https://github.com/meshtastic/node-red-contrib-meshtastic

### Expected Behavior

During install, the `.npmrc` file should be found and used.

### Steps To Reproduce

install `node-red-contrib-meshtastic`

### Environment

- Node-RED version: 3.1.3
- Node.js version: bundled with node-red docker
- npm version: bundled with node-red docker
- Platform/OS: bundled with node-red docker
- Browser: Chrome

**Comment by hardillb** [comment]
Can you supply more information, as I believe this works as expected currently.

Where have you placed the `.npmrc` file in the docker container? and what have you placed in in the file?

**Comment by hardillb** [comment]
Also please provide the Node-RED log output when attempting the install.

**Comment by dceejay** [comment]
If I run
`npm i --dry-run --verbose @meshtastic/node-red-contrib-meshtastic`
just on a command line (not in Node-RED) - I get....

```
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@10.2.3
npm info using node@v20.10.0
npm verb title npm i @meshtastic/node-red-contrib-meshtastic
npm verb argv "i" "--dry-run" "--loglevel" "verbose" "@meshtastic/node-red-contrib-meshtastic"
npm verb logfile logs-max:10 dir:/home/pi/.npm/_logs/2023-12-26T12_17_21_717Z-
npm verb logfile /home/pi/.npm/_logs/2023-12-26T12_17_21_717Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@meshtastic%2fnode-red-contrib-meshtastic 1477ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@bufbuild%2fprotobuf 1496ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@meshtastic%2fmeshtasticjs 2140ms (cache miss)
npm http fetch GET 404 https://registry.npmjs.org/@buf%2fmeshtastic_protobufs.bufbuild_es 673ms (cache skip)
npm http fetch GET 200 https://registry.npmjs.org/crc 758ms (cache miss)
npm http fetch GET 404 https://registry.npmjs.org/@buf%2fmeshtastic_protobufs.bufbuild_es 207ms (cache skip)
npm http fetch GET 200 https://registry.npmjs.org/tslog 886ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/sub-events 1349ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/buffer 152ms (cache revalidated)
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@buf%2fmeshtastic_protobufs.bufbuild_es - Not found
```

As you can see it doesn't try to pull the .npmrc file at all - so no way can we make use of it. I guess it's a packaging problem at their end or a node/npm issue.

**Comment by hardillb** [comment]
@dceejay `.npmrc` files work just fine (having implemented support in FlowFuse recently, I know because I've tested it).

We need to know where @sachaw placed their `.npmrc` file inside the container and what values they included in the file (to point to the private npm registery).

**Comment by sachaw** [comment]
It's on the root of the package, it can be viewed here https://www.npmjs.com/package/@meshtastic/node-red-contrib-meshtastic?activeTab=code
@hardillb if you've had success in the past, id love your too see your package of you don't mind. Thanks.

**Comment by hardillb** [comment]
`.npmrc` files don't work that way, you can't bundle one into a package. This would be a horrific security problem if they did.

The `.npmrc` file needs to be on the machine where the `npm install` command is run.

**Comment by sachaw** [comment]
Do you know of any workarounds? alternate registries are getting more and more common. We want to be able to provide out users an out of the box experience.

**Comment by dceejay** [comment]
Not sure what exactly you are trying to achieve - for example you can use bundlfedependecies to actually include all dependencies within the package so that they don't have to be pulled separately from somewhere else (and lets you pin them more exactly if needed)

Either way that still sounds like a nodejs npm discussion so I think we can close this issue ?
