### ISSUE TITLE
3.1.3 - stale cache causing "change node: RED.utils.validateTypedProperty is not a function"

### ISSUE THREAD

**Issue by christf** [node-red/node-red#4503]
### Current Behavior

Since one of the recent upgrades ( I was running 3.1.0 without the symptom, the symptom occurs with 3.1.3), the "change" and "filter"-nodes are marked with a red triangle in the editor. I have not been able to observe other side-effects.

This looks related: https://github.com/node-red/node-red/pull/4368

### Steps To Reproduce

add a change node to a new flow, observe the error message "RED.utils.validateTypedProperty is not a function"

### Example flow

```
paste your flow here
[
    {
        "id": "e8390a6a0ba978e8",
        "type": "change",
        "z": "412362beaf88c86c",
        "name": "block input from rkueche",
        "rules": [
            {
                "t": "set",
                "p": "block_rkueche",
                "pt": "flow",
                "to": "true",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 850,
        "y": 3160,
        "wires": [
            [
                "d1a2a8a508cf7509"
            ]
        ]
    }
]
```

### Environment

- Node-RED version: 3.1.3
- Node.js version: 
- npm version: 
- Platform/OS:  docker.io/nodered/node-red:3.1.3
- Browser: firefox

**Comment by GogoVega** [comment]
Hi @christf,
I can't reproduce this behavior, please could you give us more information.
Could you also export your `change` node and paste the content here.

Are you able to recreate this behavior after restarting NR and reloading your browser?

> are marked with a red triangle

What are invalid properties/messages?

> observe the error message "RED.utils.validateTypedProperty is not a function"

Comes from your browser console?

**Comment by christf** [comment]
I edited the original post to contain the node definition that shows the error.

![errormessage](https://github.com/node-red/node-red/assets/4321652/4fe869bb-088d-47d3-ad32-44fd7123991d)

This is what the error looks like I do not think this comes from  the browser console.

**Comment by GogoVega** [comment]
I still can't reproduce your behavior.
I'm starting to think it's an update issue. Can you confirm that you have the v3.1.3 and check your docker image.

**Comment by christf** [comment]
interesting. So this is what docker describe says, I am running:

`
Name:             node-red-6ff7588cfd-lqgz2
Namespace:        default
Priority:         0
Service Account:  node-red
Node:             nas/192.168.44.50
Start Time:       Mon, 01 Jan 2024 19:24:13 +0100
Labels:           app.kubernetes.io/instance=node-red
                  app.kubernetes.io/name=node-red
                  pod-template-hash=6ff7588cfd
Annotations:      <none>
Status:           Running
IP:               10.42.0.136
IPs:
  IP:           10.42.0.136
Controlled By:  ReplicaSet/node-red-6ff7588cfd
Containers:
  node-red:
    Container ID:    containerd://002f7a7ecedc8a119abfe33056e8c4470c70ddd0c74469cf2e50b2d5c5499420
    Image:           docker.io/nodered/node-red:3.1.3
    Image ID:        docker.io/nodered/node-red@sha256:f72381be70e1e1f06ae31fa28fc322fbf806184a2a4b97df765e6916f9204d47
    Port:            1880/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    State:           Running
      Started:       Mon, 01 Jan 2024 19:24:16 +0100
    Ready:           True
    Restart Count:   0
    Limits:
      cpu:     500m
      memory:  5123Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Liveness:     http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-79p82 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  node-red
    ReadOnly:   false
  kube-api-access-79p82:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
`

**Comment by knolleary** [comment]
@christf can you also check what version is reported in the editor itself - it will be at the bottom of the main menu, as well as logged to the JavaScript console when you load the editor.

**Comment by christf** [comment]
> @christf can you also check what version is reported in the editor itself - it will be at the bottom of the main menu, as well as logged to the JavaScript console when you load the editor.

good point, so here it comes:

the menu shows 3.1.3
![nr-version-menu](https://github.com/node-red/node-red/assets/4321652/5c68c0ff-8dfa-4f71-ac8d-5c958bfd9fe2)

When obtaining the version number from the js console, I again requested the browser to purge all caches to obtain a full reload. 
After this, the symptom was gone - naturally the log revealed
 `Node-RED: 3.1.3`

With that I would conclude that the initial analysis was spot on - parts of the application being executed from an old version. Apparently this was a somewhat stale cache in the browser. 

Now, before closing this as "invalid", can we please consider that even though the fix seems simple enough ("purge caches, reload"), I do think this fix should be required and the symptom hints at something not correctly being done by the caching subsystem. I am no web technology expert but I am aware of programming patterns that should simplify cache handling. One way is to make URI aware of versions by using a hash of the content of the resource as (part of the) name of the identifier. As such the URIs change if updates happen and cache can simply be allowed to time out, which will then lead to both: smooth upgrades and good cache hit ratio.

Is there a way the NR can avoid this situation?

**Comment by knolleary** [comment]
We do already apply cache-busting techniques on some of the resources that get loaded - but I can't immediately recall if that applies to the main library. Will take a look.

**Comment by GogoVega** [comment]
It seems that Firefox stores scripts in cache unlike Safari and Chrome which stores them in memory.

Firefox:
<img width="930" alt="Capture d’écran 2024-01-04 à 12 54 11" src="https://github.com/node-red/node-red/assets/92022724/0d4f316d-3f4f-46a2-8eba-6a7196f842b2">

Chrome:
<img width="559" alt="Capture d’écran 2024-01-04 à 12 59 29" src="https://github.com/node-red/node-red/assets/92022724/045ce51b-a3d3-47ee-a18e-5de4a1d61e77">

Safari:
<img width="985" alt="Capture d’écran 2024-01-04 à 13 05 08" src="https://github.com/node-red/node-red/assets/92022724/40ebcd25-1f38-4276-8b26-6c3d7ff84256">

It is therefore not linked to NR but to the Browser.

**Comment by christf** [comment]
Is it? Shouldn't the use of cache busting resolve that?

**Comment by knolleary** [comment]
The cache busting got broken in 3.1.0. You can see the `?v=` query parameter in the screenshot from @GogoVega is missing a value:

<img width="192" alt="image" src="https://github.com/node-red/node-red/assets/51083/35d27ec1-16ca-49d9-9d7a-81f46b644973">


That is meant to contain the version number being loaded.

**Comment by knolleary** [comment]
This was broken by #4170 - see my comment https://github.com/node-red/node-red/issues/4170#issuecomment-1879275865

**Comment by MrLight** [comment]
as an Update: 
Had the same behavior. A page reload with clearing local cache solved the issue. 
I'm running v3.1.3 under Chrome Version 120.0.6099.129.

**Comment by danie1kr** [comment]
I am running v3.1.6 and have this behavior even in browsers where I never opened node-red before:
![image](https://github.com/node-red/node-red/assets/37019555/12116228-2229-4280-b2d8-a466b62c1dc2)
![image](https://github.com/node-red/node-red/assets/37019555/c4453fdc-5295-4976-9af4-59ec1f160d08)
What can I do to make it work properly again?
