### ISSUE TITLE
Flow Properties tab missing (3.13) Can't rename a flow

### ISSUE THREAD

**Issue by goldriver2** [node-red/node-red#4507]
### Current Behavior

Double clicking on t a Flow open's a pane but there is no properties pane 

### Expected Behavior

Should show a properties Pane so I can rename a flow

### Steps To Reproduce

Double clicking on a Flow, this opens a pane but we can't rename a flow

<img width="635" alt="2024-01-01 162025" src="https://github.com/node-red/node-red/assets/7215561/e967e1a2-177a-4366-9b2d-47abd1706672">

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.13
- Node.js version: 18.16.1
- npm version: 8.3.0
- Platform/OS: Windows
- Browser: Chrome

**Comment by knolleary** [comment]
Also discussed here: https://discourse.nodered.org/t/flow-properties-tab-missing-3-13-cant-rename-a-flow/84186/2

@goldriver2 can you check the browser's JavaScript console for any error messages when you open the flow edit dialog?

**Comment by goldriver2** [comment]
as I mentionned on that forum, I upgraded node.js from 18.6 to 20.10 and after everything was working, I doubdt that this was the issue but anyway now it is working
