### ISSUE TITLE
21-httprequest.js: toLowercase --> toLowerCase

### ISSUE THREAD

**Issue by gorenje** [node-red/node-red#4521]
[this line](https://github.com/node-red/node-red/blob/ce5b6a8024533958f9ba68eb4df464e61c775bce/packages/node_modules/%40node-red/nodes/core/network/21-httprequest.js#L150) uses `toLowercase`, should be `toLowerCase` but the code is probably no longer used?

**Comment by hardillb** [comment]
That function does appear to be now unused.

Please feel free to submit a pr to remove it

**Comment by gorenje** [comment]
Done! PR #4522
