### ISSUE TITLE
Save UI settings in localStorage

### ISSUE THREAD

**Issue by Belphemur** [node-red/node-red#453]
Hi,

It would be nice that the UI would keep it's state through different session. I mean the activation of the Node Status, which workspace was the last open, if the sidebar was displayed or not, etc ...

I'm willing to work on this, if @knolleary & @dceejay are interested into this.
My idea would be to use the localStorage in the browser or the cookie if the feature is not supported.

**Comment by knolleary** [comment]
Closing as editor settings are now stored in the runtime settings on a per-user basis.
