### ISSUE TITLE
WebSocket connection to 'wss://subdomain.domain.com/comms' failed:  r @ red.min.js?v=:16

### ISSUE THREAD

**Issue by Yusseiin** [node-red/node-red#4547]
### Current Behavior

Hi,
i have enabled https and i am able to connect correctly to my nodered with https://ipaddress:1880.
Than i have added an reversed proxy with nginx:
```
server {
    listen 443 ssl;
    server_name nodered.example.com;

    ssl_certificate /path/to/certificate.crt;
    ssl_certificate_key /path/to/private_key.key;

    location / {
        proxy_pass https://localhost:1880;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```
I can connect to node-red and pass the login but then i got 
"WebSocket connection to 'wss://subdomain.domain.com/comms' failed:  r @ red.min.js?v=:16"
Why i am getting this error ? Someone can help me?

### Expected Behavior

Reverse proxy working like ipaddress

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v3.1.3
- Node.js version: v20.11.0
- npm version: 10.4.0
- Platform/OS: Ubuntu VPS
- Browser: Everyone

**Comment by knolleary** [comment]
Hi @Yusseiin 

You need to modify your nginx configuration to proxy websocket connections as well.

https://www.nginx.com/blog/websocket-nginx/

**Comment by hardillb** [comment]
Add this to the location section

```
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

**Comment by hardillb** [comment]
As to the why, it's because the editor uses a websocket connection to pass the entries in the debug sidebar.

**Comment by Yusseiin** [comment]
> proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";

Thanks a lot, working flawless
