### ISSUE TITLE
RED.view.select doesn't handle links

### ISSUE THREAD

**Issue by lgrkvst** [node-red/node-red#4551]
The editor API's `RED.view.select()` selects a `node.id` or an array of `node` objects whose interconnecting links are selected _implicitly_.

Accordingly, `RED.view.selection()` returns the currently selected nodes and links, however there is no way to _explicitly_ select one or multiple links programatically.

A use-case would be to highlight a specific link to the user.

**Comment by knolleary** [comment]
(this has been discussed in slack)
