### ISSUE TITLE
Get [obj] bad pattern in my user-interface

### ISSUE THREAD

**Issue by alexduca** [node-red/node-red#4555]
### Current Behavior

I am using node-red on my Ubuntu 22.04 server.
If I run from the terminal and try to access it with my browser I get all these [obj] repeated in my user-interface.<br>
<br><img width="1150" alt="Schermata 2024-02-02 alle 17 01 40" src="https://github.com/node-red/node-red/assets/67121465/8dca1bf8-ee7e-412f-9db6-d0126f7b8617">

**Comment by Steve-Mcl** [comment]
please include all the requested fields


- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Hi @alexduca 

that is very strange - never seen anything like that.

What version of Node-RED are you using? Is this a change in behaviour or something that has always happened?

Can you check your browser's javascript console for any error messages?

Can you share what 3rd party nodes you have installed?

**Comment by alexduca** [comment]
Node-RED version: `v3.0.2`
Node.js version: `v18.16.0`
npm version: `v.9.5.1`
Platform/OS: `Ubuntu 22.04`
Browser: `Google Chrome 121.0.6167.139`

**These are my Chrome debug logs when i load the UI:**
<img width="786" alt="Schermata 2024-02-02 alle 17 25 15" src="https://github.com/node-red/node-red/assets/67121465/cb5efc5a-2898-426e-b833-f101e12fa2f8">

**These are my dependencies/palettes installed:**
`node-red-contrib-buffer-parser => v.3.2.2`
`node-red-contrib-cron-plus => v.1.5.7`
`node-red-contrib-email => v.0.2.1 (unused)`
`node-red-contrib-filemaker => v.2.3.1`
`node-red-contrib-ftp => v.0.0.6 (unused)`
`node-red-contrib-isonline => v1.1.5 (unused)`
`node-red-contrib-loop => v.1.0.1`
`node-red-contrib-loop-processing => v0.5.1 (unused)`
`node-red-contrib-xterm => v1.0.1`
`node-red-dashboard => v.3.6.1`
`node-red-node-email => v.2.0.1`

**Comment by knolleary** [comment]
Is this a change in behaviour or something that has always happened?

If this is a change in behaviour, can you think of any changes or updates you've made recently?

**Comment by Steve-Mcl** [comment]
Can you inspect the SVG?

I have a vague memory of seeing these `OBJ` things in am SVG when they have (badly formed) fragments like iFrames or other non native SVG objects.  And since they are all over your workspace, it suggests it _might_ be in an svg `def`.

**Comment by alexduca** [comment]
Premise that I'm working on this linux server with other contributors on various branches/utilities.
Today i got back on my NodeRED and the `[obj]` bug is fixed. I don't know what's the solution...
I'm gonna talk with my mates and i try to post a solution if someone need it in the future!
Thanks to all for the support!
