### ISSUE TITLE
httpStatic settings expect string or undefined but resolve a Array

### ISSUE THREAD

**Issue by lucianohsmelo** [node-red/node-red#4559]
### Current Behavior

"node-red": "~3.1.4"

"@types/node-red": "~1.3.4",

![image](https://github.com/node-red/node-red/assets/25434788/e48a49c8-3366-4ef5-84f4-e0094ca003cc)

![image](https://github.com/node-red/node-red/assets/25434788/5d70cdfc-c51c-4ad7-905d-0ed46bb6753c)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.4
- Node.js version: 18.19.0
- npm version: 
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
`types/nodered` is not maintained by the node-red project

**Comment by lucianohsmelo** [comment]
Is there another alternative ?
