### ISSUE TITLE
Node red call service "sent data" 

### ISSUE THREAD

**Issue by skylarv** [node-red/node-red#4566]
### Current Behavior

In node-red 17.0.7, call service node no longer outputs sent data.

### Expected Behavior

"sent data" output should exist

### Steps To Reproduce

Create call service node for home assistant, add output property of msg.sent = sent data, and link to debug node with complete msg object. You'll see that the msg.sent object is missing in debug output (older version would output correctly).

### Environment
- Node-RED version: 17.0.7

**Comment by knolleary** [comment]
Hi,

We do not maintain the Home Assistant nodes. You'll need to raise this in their forum for help.
