### ISSUE TITLE
Missing node-red-3.1.5.zip asset on the latest release

### ISSUE THREAD

**Issue by OniriCorpe** [node-red/node-red#4576]
### Steps To Reproduce

- go to the release page
- you can found the node-red-*.zip asset on each released vertsion, but the latest 3.1.5

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Do you have a particular need for that zip file? The release is published to npm and is the standard way of installing.

**Comment by OniriCorpe** [comment]
yes, it is needed for the yunohost package: https://github.com/YunoHost-Apps/nodered_ynh

**Comment by knolleary** [comment]
Will generate the zip and add to the release tomorrow.

**Comment by OniriCorpe** [comment]
thank you very much <3

**Comment by knolleary** [comment]
I've attached the release zip to release. Sorry for the delay.
