### ISSUE TITLE
Safari: Nodes containing emoji in their names shift position

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#4583]
### Current Behavior

I use an emoji 📄 to indicate that a node, group, or flow has content in its description. Recently, I moved from Chrome to Safari as my default browser.

When opening my flows in Safari, I noticed that nodes containing emoji in their names shifted their position.

These screenshots from my test instance show the same flow in Chrome and Safari.

<img width="1602" alt="SCR-20240228-igvd" src="https://github.com/node-red/node-red/assets/29807944/73c9093a-e2a0-490b-a63b-1bd13c9c8a39">

<img width="1602" alt="SCR-20240228-igwt" src="https://github.com/node-red/node-red/assets/29807944/f797f261-a774-446e-b329-b8b437f6bdfe">

### Expected Behavior

Nodes to stay in their position.

### Steps To Reproduce

- Add a node in Chrome (or another browser)
- Align it to the grid
- Add some text and an emoji to the node's name
- Deploy
- Open Node-RED in Safari.

Or import the flow below in Safari. It's the same flow from the screenshots above.

### Example flow

```
[{"id":"07f41918a09bdb36","type":"tab","label":"Test Flow","disabled":false,"info":"","env":[]},{"id":"96670ecd70c9be9d","type":"comment","z":"07f41918a09bdb36","name":"Test 01","info":"","x":170,"y":100,"wires":[]},{"id":"9ea54e11469515b5","type":"comment","z":"07f41918a09bdb36","name":"Test 123","info":"","x":180,"y":160,"wires":[]},{"id":"c5315543d5deb6e1","type":"comment","z":"07f41918a09bdb36","name":"Test with a relativelly long name","info":"","x":250,"y":220,"wires":[]},{"id":"1609c424f0acf830","type":"comment","z":"07f41918a09bdb36","name":"Test with text and emoji 📄","info":"","x":230,"y":280,"wires":[]}]
```

### Environment

- Node-RED version: 3.1.5
- Node.js version: v18.19.0
- npm version: 10.2.3
- Platform/OS: macOS Sonoma 14.3.1
- Browser: Safari

**Comment by knolleary** [comment]
Nodes are positioned based on their `x` and `y` values that are their centre point.

It appears that emoji are wider in Safari than in other browsers - this makes the node grow as the width is determined by the label.

I'm not sure we can do anything about this.

**Comment by bonanitech** [comment]
Is it possible to add a Font Awesome icon instead of the emoji?

**Comment by knolleary** [comment]
No, only text
