### ISSUE TITLE
Context Menu - no paste - very minor

### ISSUE THREAD

**Issue by s1nbad** [node-red/node-red#4588]
### Current Behavior

In the context menu (right click) when editing a text field (function node) there is no 'paste' (cut & copy are present)

### Expected Behavior

It is usual to have a 'paste' option once the clipboard has been populated.

### Steps To Reproduce

highlight text, right click, copy, move cursor, right click - NO PASTE 

### Example flow

all flows - every function node when editing

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by knolleary** [comment]
Hi @s1nbad 

Can you confirm what version of Node-RED you are using?

And which text field exactly are you referring to? If you mean the main code editor of the Function node, I have a paste option:

<img width="662" alt="image" src="https://github.com/node-red/node-red/assets/51083/8461eb16-936f-4659-9d47-7704d0e368f7">

**Comment by s1nbad** [comment]
![Screenshot 2024-03-06 211922](https://github.com/node-red/node-red/assets/8650739/522eecb0-72ce-49a4-a31f-cdc4966a5063)

I am running v3.02 - a number of node(20.11) servers hosted on both Windows (10) and Ubuntu (20.04) OS - I am using chrome on windows as the client

Are there different editor versions ?

**Comment by knolleary** [comment]
Certainly the version of the editor widget in 3.0.2 is older than the one in the latest 3.1.6 release.

That said, I think this will be a browser security restriction. We did have a previous report of this here: https://github.com/node-red/node-red-nodes/issues/946 - which led us to that conclusion.

**Comment by s1nbad** [comment]
Yes, I do mean main editor area - i have confirmed my clipboard is full as ctrl V does paste

I see you are using Mac as a client - could this be a difference

**Comment by s1nbad** [comment]
I can confirm this is a security issue and works using localhost or https, thanks for your help
