### ISSUE TITLE
TCP In node gives warning with environment variables

### ISSUE THREAD

**Issue by millosolomillo** [node-red/node-red#4591]
### Current Behavior

When writing a variable name on the TCP In node port, it works as expected but the node shows the little red triangle and a warning is displayed when deploying the flow.
![image](https://github.com/node-red/node-red/assets/4713166/ed2cea3b-3780-4d4b-a70f-bf004b1323a9)
![image](https://github.com/node-red/node-red/assets/4713166/3e1e1522-6e2e-42d0-b5bf-cdd53d85b8e3)

### Expected Behavior

No warnings or errors when using environment variable as port value.

### Steps To Reproduce

1. Bring in the flow a TCP In node.
2. Configure it as "Listen on".
3. Type an environment variable name in the port field.

### Environment

- Node-RED version: v3.1.0
- Node.js version: v20.8.0
- npm version: v10.1.0
- Platform/OS: Windows
- Browser: Chrome

**Comment by Steve-Mcl** [comment]
> * Node-RED version: v3.1.0

I have just checked this out on my dev machine:
Node-RED version: v3.1.5
Node.js version: v18
Platform/OS: Windows
Browser: Chrome

![chrome_exi6nAt0lM](https://github.com/node-red/node-red/assets/44235289/9c2e0556-2044-450a-aad2-6b27212c2624)

As you can see it works as expected.

Can I ask your to upgrade and try again please?  (Note: V3.1.6 is current latest version)

**Comment by millosolomillo** [comment]
Confirmed.
Works correctly in 3.1.6
