### ISSUE TITLE
Flow number counts are not separated for multiple projects when Projects feature is turned on.

### ISSUE THREAD

**Issue by mshioji** [node-red/node-red#4600]
### Current Behavior

create multiple flow tabs on project1, then create new project2.  (now I'm in the flow 1 on new project2) 
then create new flow tab here, I expect new flow tab number will be "flow 2" 
but number is the next number after the project 1 flow number.

### Expected Behavior

create multiple flow tabs on project1, then create new project2.
in "project2 - flow 1", create new flow tab then created new flow tab number should be "flow 2".

### Steps To Reproduce

turn on workspace, then create multiple flow tabs on project1, then create and move to new project2 and create new flow tab. 

### Example flow

```
none
```

### Environment

- Node-RED version: 3.1.6
- Node.js version: 18.14.6
- npm version: 9.3.1
- Platform/OS: Windows 10
- Browser: chrome

**Comment by mshioji** [comment]
Opened Pull Request #4601.
Thank you,

**Comment by mshioji** [comment]
Hello,
Thank you for new releases, I've tried following environment but it seems situation are the same.
I am sorry, previous title for this was not correct, so I update the title for this.

Environment
Node-RED version: 3.1.7
Node.js version: 20.11.1
npm version: 10.5.1
Platform/OS: Ubuntu
Browser: chrome

Environment
Node-RED version: 4.0.0 beta.1
Node.js version: 20.11.1
npm version: 10.5.1
Platform/OS: Linux Mint
Browser: chrome

Thank you,

**Comment by mshioji** [comment]
Hello, I found one more thing. hope this could be some help for investigation.
This phenomenon is also affecting on Node-RED MCU Plug-in Flow selector as follows,
however after reload the browser, flow selector list matches to flows on current project.

![issue](https://github.com/node-red/node-red/assets/59914628/c4b82a7d-6109-4c85-b5f4-1553cc2b8ce4)

Thank you,

**Comment by knolleary** [comment]
Hi @mshioji 

We haven't merged your PR yet, so nothing has changed. I did have a quick look at your proposed change and I saw it would change behaviour for more than just when switching projects.

Previously, if you have `Flow 1`, `Flow 2`, `Flow 3`, then deleted `Flow 2`, the next flow created would be `Flow 4`. With you change, it is created as `Flow 2`.

I'm not sure we want to change that behaviour here. We only want to reset the count when clearing the workspace.

As for MCU Plugin behaviour - that isn't something we maintain, so I cannot comment on that. You'd have to raise a separate issue against that plugin.

**Comment by mshioji** [comment]
Hello @knolleary 

Thank you for your detailed comment, I understand well which point you are concerned about.
I agree "just reset the count when changing projects" is the best, so it's OK please ignore the pull request I mentioned.

then, Yes, I understand MCU Plugin is a different story, but I thought this behavior could be some hint for this.
if this plugin behavior is not related to this issue, I will raise a separate issue for mcu-plugin repo.

Thank you very much for your kind explanation,
