### ISSUE TITLE
Performance verification

### ISSUE THREAD

**Issue by linlinaifeifei** [node-red/node-red#4609]
### Current Behavior

the Internet of Things environment uses nodered, and has written a lot of common code and nodes in nodered nodejs, every time you create an event, it will call the interface corresponding to the nodered tab page to create an event, which will generate many tab pages corresponding to the event. This will result in the nodered tab page corresponding to the interface 408, if multiple shutdown events are triggered, the server will keep restarting. I would like to confirm whether we have problems using nodered in this scenario, or does nodered have records on its performance in this regard

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
Hi. As explained when opening an issue, this issue tracker is for bugs. Questions should be directed to the forum: https://discourse.nodered.org/. 

Thank you.
