### ISSUE TITLE
 email fail / error: self_signed_cert_in_chain

### ISSUE THREAD

**Issue by aco7342** [node-red/node-red#464]
I needed some help, i try create a flow to send email, and receipt this
- node-red v.9.0.0
-to: vs01dd@gmail.com
-server:smtp.gmail.com
-port:465
-userid:vs01dd@gmail.com
-password:********

flow:[{"id":"4f272029.b0d8e","type":"inject","name":"","topic":"","payload":"","payloadType":"date","repeat":"60","crontab":"","once":false,"x":89,"y":61,"z":"55acd304.aa532c","wires":[["6ec54b17.913ab4"]]},{"id":"dca762bc.2358a","type":"debug","name":"","active":true,"console":"false","complete":"false","x":554,"y":58,"z":"55acd304.aa532c","wires":[]},{"id":"88de8af2.772178","type":"switch","name":"","property":"tipo","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","outputs":2,"x":397,"y":58,"z":"55acd304.aa532c","wires":[["160cfd06.e9f303"],["dca762bc.2358a"]]},{"id":"6ec54b17.913ab4","type":"async","name":"Verifica Servidor","async":"msg.tipo = true;\n//console.log('1.');\nasync.parallel({\n  one: function(join){\n //\t\tconsole.log('2.');\n\t\tvar _os = { hostname : context.global.os.hostname(),\n\t\ttype : context.global.os.type(), \n\t\tplatform : context.global.os.platform(),\n\t\trelease : context.global.os.release(),\n\t\tuptime : context.global.os.uptime(),\n\t\ttotalmem : context.global.os.totalmem(),\n\t\tfreemem: context.global.os.freemem(),\n\t\tloadavg: context.global.os.loadavg(),\n\t\tcpus : context.global.os.cpus() };\n\t\tmsg.isWin = (context.global.os.platform() == 'win32');\n\t\tjoin(null, _os);\n  },\n  two: function(join){\n  \t console.log('3.msg.isWin:' + msg.isWin);\n  \t if (msg.isWin) {\n\t \t context.global.diskspace.check('C', function (err, total, free, status)\n\t\t {\n\t\t    if (!err){\n\t\t  //  \tconsole.log('3.1');\n\t\t    \tvar _data = { total : total , free : free , status : status };\n\t\t    \t//console.dir(data);\n\t\t    } else {\n\t\t    //\tconsole.log('3.2');\n\t\t        var _data = { err : err };\n\t\t        //console.dir(data);\n\t\t    }\n\t\t    join(null, _data);\n\t\t });\n\t } else {\n\t\t// console.log('4.');\n\t\t context.global.njds.drives(\n\t\t\tfunction (err, drives) {\n\t\t\t\tnjds.drivesDetail(\n\t\t\t\t\tdrives,\n\t\t\t\t\tfunction (err, data) {\n\t\t\t\t\t\tfor(var i = 0; i<data.length; i++)\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t// Get drive mount point \n\t\t\t\t\t\t\tconsole.log(data[i].mountpoint);\n\t\t\t\t\t\t\t// Get drive total space \n\t\t\t\t\t\t\tconsole.log(data[i].total);\n\t\t\t\t\t\t\t// Get drive used space \n\t\t\t\t\t\t\tconsole.log(data[i].used);\n\t\t\t\t\t\t\t// Get drive available space \n\t\t\t\t\t\t\tconsole.log(data[i].available);\n\t\t\t\t\t\t\t// Get drive name \n\t\t\t\t\t\t\tconsole.log(data[i].drive);\n\t\t\t\t\t\t\t// Get drive used percentage \n\t\t\t\t\t\t\tconsole.log(data[i].usedPer);\n\t\t\t\t\t\t\t// Get drive free percentage \n\t\t\t\t\t\t\tconsole.log(data[i].freePer);\n\t\t\t\t\t\t}\n\t\t\t\t\t\tjoin(null, data);\n\t\t\t\t\t}\n\t\t\t\t);\n\t\t\t}\n\t\t)\n\t}\n  }\n}, function(err, results) {\n  // results is now equals to: {one: \"Hello\", two: \"World\"}\n  msg.payload = { os : results.one , disk : results.two};\n  console.dir( msg.payload );\n  cb(msg);\n});","outputs":1,"x":237,"y":61,"z":"55acd304.aa532c","wires":[["88de8af2.772178","dca762bc.2358a"]]},{"id":"c1ce0ad0.3e31f8","type":"e-mail","server":"smtp.gmail.com","port":"465","name":"vs01dd@gmail.com","dname":"","x":571,"y":159,"z":"55acd304.aa532c","wires":[]},{"id":"160cfd06.e9f303","type":"change","action":"replace","property":"topic","from":"","to":"teste de email","reg":false,"name":"","x":257,"y":189,"z":"55acd304.aa532c","wires":[["c1ce0ad0.3e31f8"]]}]

**Comment by knolleary** [comment]
As we've not had any updates, or other reports of this type of issue, I'm going to close this.

If you are still hitting it, or able to provide any further information, please reopen.
