### ISSUE TITLE
The username/password form does not show up when using passport-ldapauth

### ISSUE THREAD

**Issue by joelgriffiths** [node-red/node-red#4647]
### Current Behavior

When I change adminAuth to use the passport-ldapauth strategy, I get the following login screen:
![Screen Shot 2024-04-04 at 4 46 18 PM](https://github.com/node-red/node-red/assets/4323417/0ef4d6b2-912f-463f-8666-7d9f28f0bb58)

Switching back 
![Screen Shot 2024-04-04 at 4 49 16 PM](https://github.com/node-red/node-red/assets/4323417/85484d8f-9938-4407-bc34-1bb49d10503f)
to normal user credentials, I get this screen:

### Expected Behavior

I was expecting the second image with the ability to type in usernames and password.

### Steps To Reproduce

I'm compiling this using node-red-docker. I've tried the alpine and debian builds and node 14/16/18. I get the same results on Firefox, Brave, and Chrome.

In the example below, I've tried it without the `users` section, ldap, ldaps, with and without ports.

All seem to cause the same issue. The passport strategy looks like this:
```
           adminAuth: {
                type: "strategy",
                strategy: {
                    strategy: require("passport-ldapauth").Strategy,
                    options: {
                        server: {
                            url: 'ldaps://ldap.jumpcloud.com',
                            bindDN: 'uid=search,ou=Users,o=redactedoid,dc=jumpcloud,dc=com',
                            bindCredentials: 'UWj7~os94t4@KKy7vMmYSF',
                            searchBase: 'ou=Users,o=redactedoid,dc=jumpcloud,dc=com',
                            searchFilter: '(&(objectClass=inetOrgPerson)(uid={{username}})(memberOf=cn=node-red,ou=Users,o=redactedoid,dc=jumpcloud,dc=com))'
                        }
                    }
               },
                 users: [
                   { username: "myname",permissions: ["*"]}
                 ]
            },
 ```

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.7/3.1.8
- Node.js version: 14, 16, and 18
- npm version:
- Platform/OS: debian/alpine
- Browser: Firefox, Chrome, and Brave

Most recent build looks like this:
```
{
  'node-red-docker': '3.1.8',
  npm: '8.19.4',
  node: '16.20.2',
  v8: '9.4.146.26-node.26',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.19.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.11',
  openssl: '1.1.1v+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022f',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
```

**Comment by knolleary** [comment]
We only support OpenId/Oauth based passport strategies - which `password-ldapauth` is not.

To use ldap based auth, you'll need to still use `credentials` type `adminAuth`, with a custom `authenticate` function that will receive the username/password credentials and allow you to verify them against your ldap server. See https://nodered.org/docs/user-guide/runtime/securing-node-red#custom-user-authentication for high level details.

**Comment by hardillb** [comment]
There is also my ldap auth plugin

https://github.com/hardillb/node-red-contrib-ldap-auth

**Comment by knolleary** [comment]
Going to close this one as it is working as designed.
