### ISSUE TITLE
Outdated node checks and polyfills

### ISSUE THREAD

**Issue by Rotzbua** [node-red/node-red#4687]
### Current Behavior

There are old and outdated node version checks which are not supported anymore. Also some polyfills for the unsupported node.

### Expected Behavior

Remove outdated code.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v4-dev
- Node.js version: 18+

**Comment by knolleary** [comment]
@Rotzbua thanks for all the PRs. I think this issue is complete now?
