### ISSUE TITLE
Home Connect Integration not working

### ISSUE THREAD

**Issue by sewo-x** [node-red/node-red#4691]
### Current Behavior

API connection is working properly

### Expected Behavior

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized"
}

### Steps To Reproduce

![image](https://github.com/node-red/node-red/assets/73949083/95138be0-0bf7-4522-8523-1d18ba4102f6)

![image](https://github.com/node-red/node-red/assets/73949083/050fdf32-74ef-461b-9591-7a3261b1d878)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.9
- Node.js version: 18
- npm version:
- Platform/OS: raspberry pi 5
- Browser: Chromium

**Comment by hardillb** [comment]
Please raise this with the home connect team, this repo is only for issues with core Node-RED
