### ISSUE TITLE
Merging changes causes unchanged flows to be marked as if they were changed

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red#4696]
### Current Behavior

After merging changes, unchanged flows are marked as if they were changed, even though they were not.

<img width="1602" alt="image" src="https://github.com/node-red/node-red/assets/29807944/1de8a956-0024-4094-adfd-0957359572b1">

### Steps To Reproduce

- Open a Node-RED instance with multiple flows in two different browser windows
- In one of the browser windows, make changes to one of the flows and deploy
- In the other browser window, review changes and merge

### Environment

- Node-RED version: 4.0.0-beta.2
- Node.js version: 20.13.1
- npm version: 10.5.2
- Platform/OS: macOS
- Browser: Safari, Firefox

**Comment by knolleary** [comment]
This is already fixed as part of #4692
