### ISSUE TITLE
Msg properties cannot override node properties

### ISSUE THREAD

**Issue by brybad** [node-red/node-red#4699]
### Current Behavior

When issue [399](https://github.com/node-red/node-red/issues/399#issuecomment-2110704401) was closed, the fix was to generate warnings for everything that a property can be set in previous nodes. This behavior is not necessary and really bogs down the debug window with these nuisance warnings that cannot be suppressed. Right now my only recourse is to delete/comment out "node.warn(RED._("common.errors.nooverride"));" from the  httprequest.js file. Or use a very old http-multipart node that doesn't have this.

### Expected Behavior

When the url in the http-request node is left blank, and a msg.url is supplied, there should be no warning message as there is no mismatch as indicated by the previous concern. When url's need created dynamically, there should be no warning message. For the method type there is a way to select "set by msg method" (which has no actual effect...) but nothing for url. There should be a way to suppress these warnings, or remove completely. Maybe in settings.js?

### Steps To Reproduce

Inject node with msg.url set to some value, and a blank http-request node will generated this.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.0 (snap)
- Node.js version: 
- npm version:
- Platform/OS: Ubuntu Core
- Browser: Chrome

**Comment by brybad** [comment]
Switching settings.js to "fatal" for debug still generates these warning messages.

**Comment by knolleary** [comment]
Hi @brybad 

> When the url in the http-request node is left blank, and a msg.url is supplied, there should be no warning message

That is exactly the behaviour I see. Here is an example flow that passes `msg.url` to an `http-request` node - and I don't get the override warning message.

```
[{"id":"90ba44c59bde456c","type":"inject","z":"98ff6cf1928b251c","name":"","props":[{"p":"payload"},{"p":"url","v":"https://nodered.org","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":130,"y":140,"wires":[["621085765cfec22c"]]},{"id":"621085765cfec22c","type":"http request","z":"98ff6cf1928b251c","name":"","method":"GET","ret":"txt","paytoqs":false,"url":"","persist":false,"insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":330,"y":140,"wires":[["dc3f4b0fd316d53a"]]},{"id":"dc3f4b0fd316d53a","type":"debug","z":"98ff6cf1928b251c","name":"debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":510,"y":140,"wires":[]}]
```

Am I misunderstanding the scenario you are reporting? Can you provide a simple flow that demonstrates the scenario for you?

**Comment by brybad** [comment]
It appears that the snap version does not refresh the changes settings.js when restarting the first time but does on the second restart. The Windows version (3.1.5) works only when set by msg.method despite the methods matching. 

This shows the issue is with the snap confinement and not the NR files. It could have been handled slightly different but it works as intended currently. Closing this issue.
