### ISSUE TITLE
Link In/LinkOut Undo Not Working Correctly

### ISSUE THREAD

**Issue by My-Random-Thoughts** [node-red/node-red#4704]
### Current Behavior

When performing an undo after changing link in/link out connections, the connections are not set correctly.

### Expected Behavior

Undo should work correctly

### Steps To Reproduce

- Two or more Link Out nodes (labelled "Out1", "Out2", ...)
- Only one Link In node (labelled "In")

- Connect "Out1" to "In" and see that a dotted line connects them
- Select each node in turn ensuring that all nodes show the correct connections

- Open properties of "In"
- Untick "Out1" and tick "Out2"
- Select each node in turn ensuring that all nodes show the correct connections

- Press CTRL+Z once to undo the above change
- Select each node in turn show the wrong connections are shown

- Open properties of "In"
- Ticks are shown for both "Out1" and "Out2"
- Selecting "Out1" also shows no connection

### Example flow

```
[{"id":"3f13efa6cd3adaee","type":"link out","z":"ecce9a260798dab7","name":"1","mode":"link","links":[],"x":315,"y":320,"wires":[]},{"id":"a6e8b21a3e0d56d4","type":"link out","z":"ecce9a260798dab7","name":"2","mode":"link","links":[],"x":315,"y":360,"wires":[]},{"id":"2fd90e621d364265","type":"link in","z":"ecce9a260798dab7","name":"Output","links":[],"x":415,"y":340,"wires":[[]]}]
```

### Environment

- Node-RED version:  Docker - 3.1.9 (also affects 4.0.0-beta-3)
- Node.js version: v18.20.2
- npm version: 10.5.0
- Platform/OS: Linux 6.1.0-18-amd64 x86_64
- Browser: Firefox 123

**Comment by knolleary** [comment]
Thanks for such a clear set of steps to reproduce this issue - that always makes our life easier.

Will investigate.
