### ISSUE TITLE
node red does not start

### ISSUE THREAD

**Issue by AsieduY** [node-red/node-red#4708]
### Current Behavior

> node-red-tensorflowjs@1.0.0 start
> node-red

18 May 17:24:31 - [info] 

Welcome to Node-RED
===================

18 May 17:24:31 - [info] Node-RED version: v3.1.9-git
18 May 17:24:31 - [info] Node.js  version: v20.13.1
18 May 17:24:31 - [info] Linux 6.6.28+rpt-rpi-v8 arm LE
18 May 17:24:32 - [info] Loading palette nodes
18 May 17:24:35 - [info] Dashboard version 3.6.5 started at /ui
18 May 17:24:36 - [warn] ------------------------------------------------------
18 May 17:24:36 - [warn] [node-red-node-rbe/rbe] 'rbe' already registered by module node-red
18 May 17:24:36 - [warn] ------------------------------------------------------
18 May 17:24:36 - [info] Settings file  : /home/yh/.node-red/settings.js
18 May 17:24:36 - [info] Context store  : 'default' [module=memory]
18 May 17:24:36 - [info] User directory : /home/yh/.node-red
18 May 17:24:36 - [warn] Projects disabled : editorTheme.projects.enabled=false
18 May 17:24:36 - [info] Flows file     : /home/yh/.node-red/flows.json
18 May 17:24:36 - [info] Server now running at http://127.0.0.1:1880/
18 May 17:24:36 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

18 May 17:24:36 - [info] Starting flows
Platform node has already been set. Overwriting the platform with [object Object].
18 May 17:24:38 - [error] 
********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: Loaded TensorFlow.js v2.8.6
    at log_helper (/home/yh/project/node-red-tensorflowjs/node_modules/@node-red/runtime/lib/nodes/Node.js:526:20)
    at Node.log (/home/yh/project/node-red-tensorflowjs/node_modules/@node-red/runtime/lib/nodes/Node.js:545:5)
    at initTfjs (/home/yh/project/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node/tfjs-object-detection.js:15:12)
    at new TFJSObjectDetection (/home/yh/project/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node/tfjs-object-detection.js:22:5)
    at Object.createNode (/home/yh/project/node-red-tensorflowjs/node_modules/@node-red/runtime/lib/flows/util.js:190:27)
    at Flow.start (/home/yh/project/node-red-tensorflowjs/node_modules/@node-red/runtime/lib/flows/Flow.js:261:54)
    at async Object.start [as startFlows] (/home/yh/project/node-red-tensorflowjs/node_modules/@node-red/runtime/lib/flows/index.js:403:17)

### Expected Behavior

node red should have started 

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Steve-Mcl** [comment]
> node-red-contrib-tfjs-object-detection

I hope you really do noy have that installed - it was removed from NPM as malicious:  https://www.npmjs.com/package/node-red-contrib-tfjs-object-detection

As for your problem - since Node-RED starts and it is being crashed by a contrib node, you ned to either contact the author, raise an issue on the repository or start a thread on the Node-RED forum.

Closing issue for now.

Please re-open if you believe this is a problem with Node-RED

**Comment by AsieduY** [comment]
Okay, thanks
