### ISSUE TITLE
Configure admin cookie options for authentication callbacks

### ISSUE THREAD

**Issue by cstns** [node-red/node-red#4717]
Session cookie attributes should be able to be configured similarly as `httpAdminMiddleware`, via a `httpAdminCookieOptions` configuration that will make session cookie attributes configurable at runtime in `packages/node_modules/@node-red/editor-api/lib/auth/index.js:167`
```js
adminApp.use(session({
      // As the session is only used across the life-span of an auth
      // hand-shake, we can use a instance specific random string
      secret: crypto.randomBytes(20).toString('hex'),
      resave: false,
      saveUninitialized: false,
      cookie: {
        sameSite: 'None',
        secure: true,
        ...httpAdminCookieOptions
      },
      store: new MemoryStore({
        checkPeriod: 86400000 // prune expired entries every 24h
      })
    }));
```

This will allow NR to be configured to run embedded while authenticated in cross domain setups and will pave the way for Google's paradigm shift when it comes to [3'rd party cookies deprecation](https://developers.google.com/privacy-sandbox/3pcd).

This change would play nicely with 3rd Party Cookie [CHIPS](https://developers.google.com/privacy-sandbox/3pcd/chips) and would allow setting a `partitioned` attribute when needed.

@knolleary

**Comment by knolleary** [comment]
Thanks @cstns - we'll get this added
