### ISSUE TITLE
Grunt: build script does not fail if source files are missing

### ISSUE THREAD

**Issue by Rotzbua** [node-red/node-red#4738]
### Current Behavior

Builds without any warning or error.

### Expected Behavior

Build should warn or fail.

### Steps To Reproduce

Delete random required file.

### Environment

- Node-RED version: 4-dev

**Comment by knolleary** [comment]
@Rotzbua I'd love to get some insight into how you are identifying these issues? We've never had a problem with the grunt file and your description doesn't really give any insight into the full scenario.

We are also trying to finalise the 4.0 release - whilst we certainly appreciate all of the prs you are raising, it would be good to get a better idea of what you are doing more generally as the areas you are raising against are jumping all over the project.
