### ISSUE TITLE
Delay node documentation - 'flush' property is missing some details in the german translation

### ISSUE THREAD

**Issue by aikitori** [node-red/node-red#4748]
As discussed here:
https://discourse.nodered.org/t/on-demand-delay-node/88466/10?u=kitori

In the german translation there is missing some details what you can do with the msg property `flush`

English:

`If the received message has this property set to a numeric value then that many messages will be released immediately`. If set to any 
other type (e.g. boolean), then all outstanding messages held by the node are sent immediately.

German:
Wenn bei der empfangenen Nachricht diese Eigenschaft auf einen beliebigen Wert gesetzt ist, werden alle im Node gepufferten Nachrichten sofort gesendet.

The highlighted part is missing in the German translation

![grafik](https://github.com/node-red/node-red/assets/88290076/65692cff-1ee3-4129-b408-26bf3178ad2b)
![grafik](https://github.com/node-red/node-red/assets/88290076/77c0c2b4-efb9-4112-b1c9-bb5ef530ec87)

---

This sentence describe the same like the english one:

German:
Wenn bei der empfangenen Nachricht diese Eigenschaft auf einen numerischen Wert gesetzt ist, wird diese Anzahl an Nachrichten sofort gesendet. Wenn ein anderer Typ gesetzt ist (z.B. Boolean), werden alle in der Node gepufferten Nachrichten gesendet.

Edit:

And `rate` is missing:

rate
Setzt die Verzögerung in Millisekunden zwischen den Nachrichten. Diese Node überschreibt die bestehende Verzögerung die in der Node konfiguration, wenn die empfangende Nachricht msg.rate in Millisekunden enthält. Dies trifft nur zu, wenn in der Node konfiguriert ist, das empfangene Nachrichten den konfigurierten Wert überschreiben können.

**Comment by GogoVega** [comment]
Hi,
Could you make a PR to include this changes? The file is [here](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/locales/de/function/89-delay.html).
Thank you.
