### ISSUE TITLE
Rewired nodes not restarted when doing a modified flows deployment

### ISSUE THREAD

**Issue by Ahmad44452** [node-red/node-red#4752]
### Current Behavior

From [this](https://github.com/node-red/node-red/blob/3fd2d07c759be11395615f7b1d4c97190321021d/packages/node_modules/%40node-red/runtime/lib/flows/index.js#L465C1-L465C74 ) line of code, it is visible that when a `modified flows` deployment is done, only the `changed`, `removed` and `linked` nodes are stopped and later started. This causes the whole flow to restart except the `rewired` nodes.

### Expected Behavior

When a `modified flows` deployment is done, it should also restart the nodes that were `rewired` and not only the `changed`, `removed` and `linked` nodes.

### Environment

- Node-RED version: v3.1.9
- Node.js version: v20.12.2
- npm version: v10.5.0
- Platform/OS: Ubuntu
- Browser: Chrome

**Comment by knolleary** [comment]
Have dug into this and I agree we should be including rewired nodes in the stop list. Have raised #4754 including another scenario this was causing which was incorrect.

Will have a 3.1.10 release this week.
