### ISSUE TITLE
Hi from JSON Schema! We'd like to add node-red to the JSON Schema Landscape

### ISSUE THREAD

**Issue by benjagm** [node-red/node-red#4758]
Hi node-red Community!

This is Benjamin from the JSON Schema Community. First of all congrats for the amazing work with node-red! We recently discovered that node-red uses JSON Schema and we'd like to make sure we offer our support here!

We'd like also to add node-red to the adopters section of the JSON Schema Landscape: https://landscape.json-schema.org/ Could this be possible?

Thanks a lot!

**Comment by knolleary** [comment]
Hi @benjagm 

We'd be happy to be included on the landscape. What do you need from us to make it so?
