### ISSUE TITLE
False Positive Syntax Error: 'document' Not Recognized in Puppeteer Page.evaluate Context

### ISSUE THREAD

**Issue by gmag11** [node-red/node-red#4783]
### Current Behavior

When writing JavaScript code for Puppeteer within a Node-Red function node, the syntax checker incorrectly marks the usage of document inside page.evaluate as an error. This results in false positive syntax errors, even though this code runs correctly in the Puppeteer context within a browser.

When triggering deploy this message is shown:

![image](https://github.com/node-red/node-red/assets/6190183/9d5653d1-055e-43be-a9a8-53afe71bb89a)

But code runs fine

### Expected Behavior

The syntax checker should recognize that document is valid within the context of page.evaluate in Puppeteer. It should not flag this as an error, allowing users to write and validate their Puppeteer scripts without false syntax error warnings.

### Steps To Reproduce

1. Create a new Node-Red flow.
2. Add a function node and write the following Puppeteer code inside:
```javascript
const data = await page.evaluate(() => {
  let element = document.querySelector('article');
  let text = element ? element.innerText : null;

  if (!element) {
    element = document.querySelector('body');
    text = element ? element.innerText : null;
  }

  return text;
});
```
3. Observe that the syntax checker flags the usage of document as an error, even though this is valid in the Puppeteer context.

These steps should reproduce the issue where document is incorrectly marked as a syntax error in Node-Red's function node when used inside page.evaluate.

### Example flow

```json
[
    {
        "id": "2db2b01bd031bb8f",
        "type": "function",
        "z": "c270535f7828a461",
        "name": "Get Content",
        "func": "\nconst browserURL = `http://${flow.get(\"CHROME_IP\") || '127.0.0.1'}:${env.get(\"CHROME_PORT\") || '9222'}`;\nnode.status({fill:\"yellow\",shape:\"ring\",text:\"Connecting browser\"});\nconst browser = await puppeteer.connect({\n  browserURL: browserURL,\n});\nconst url = msg.payload;\nconst page = await browser.newPage();\nawait page.setViewport({ width: 1920, height: 1080 });\nnode.status({ fill: \"yellow\", shape: \"dot\", text: \"Loading site\" });\nawait page.goto(url, { waitUntil: 'networkidle2' });\nnode.status({ fill: \"blue\", shape: \"dot\", text: \"Saving screenshot\" });\nconst screenshot = await page.screenshot();\nnode.status({ fill: \"green\", shape:\"dot\",text:\"Getting content\"});\n//const content = await page.content();\n\nconst data = await page.evaluate(() => {\n  //let element = document.querySelector('article');\n  //let text = element ? element.innerText : null;\n\n  //if (!element) {\n    element = document.querySelector('body');\n    text = element ? element.innerText : null;\n  //}\n\n  return text;\n});\n\n// Buscar la imagen más grande\nconst largestImageUrl = await page.evaluate(() => {\n  const images = document.querySelectorAll('img');\n  let largestImage = null;\n  let largestArea = 0;\n\n  images.forEach(img => {\n    const src = img.src.toLowerCase();\n    // Verificar si la imagen es jpg o png ignorando los parámetros de la URL\n    if (src.match(/\\.(jpg|jpeg|png)(\\?.*)?$/)) {\n      const width = img.naturalWidth;\n      const height = img.naturalHeight;\n      const area = width * height;\n\n      if (width >= 100 && height >= 100 && area > largestArea) {\n        largestArea = area;\n        largestImage = img;\n      }\n    }\n  });\n\n  return largestImage ? largestImage.src : null;\n});\n\nif (largestImageUrl) {\n  node.warn(`URL de la imagen más grande: ${largestImageUrl}`);\n} else {\n  node.warn('No se encontraron imágenes.');\n}\n\nnode.status({ fill: \"green\", shape:\"dot\",text:\"OK\"});;\nmsg.payload = {\n    text: data,\n    imageURLs: largestImageUrl ? [largestImageUrl] : [],\n    url: url,\n    //html: content,\n    screenshot: screenshot\n  };\n\nawait page.close();\nawait browser.disconnect();\nreturn msg;\n",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [
            {
                "var": "puppeteer",
                "module": "puppeteer"
            }
        ],
        "x": 410,
        "y": 80,
        "wires": [
            []
        ]
    }
]
```

### Environment

- Node-RED version: 4.0.0
- Node.js version: 18.20.3
- npm version: 10.7.0
- Platform/OS: NodeRed is running in Docker/Debian
- Browser: Firefox/Windows

**Comment by Steve-Mcl** [comment]
This behaviour is correct. The function node runs server side (node runtime, not the browser) and `document` is not a global variable.  You can likely get the document object from the page object but it is not in global scope like it would be in a browser

**Comment by knolleary** [comment]
@Steve-Mcl but in the context of the puppeteer module, you *do* have a `document` object in scope of that function.

I can't remember if we load types dynamically for the added modules? Also not sure if that would be sufficient to resolve this particular issue. We aren't going to hardcode puppeteer awareness into the core of the editor otherwise.

This may just need documenting as a limitation and the appropriate inline ts comment adding to tell Monaco what's in scope.

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl but in the context of the puppeteer module, you _do_ have a `document` object in scope of that function.

Oh my. It didn't even register that the scope in which it executed was that of the browser (puppeteer) 

Any how, as it stands, Monaco has no awareness that the callback is executed with a document object in scope & I am not sure we can handle this - even with typing's avaiable. 

What you can to is one of the following:
1. Use `globalThis` to avoid undeclared variables 
   ![chrome_SlgrecvtCF](https://github.com/node-red/node-red/assets/44235289/e6eb76e7-c428-4fd0-b4a9-dae0ba78ca39)

2. Add `// @ts-ignore` above places where you use `document` (or create a local `doc` variable and assign `document` to it to avoid having it littered through out your code)
   ![chrome_z8vbhtn5V4](https://github.com/node-red/node-red/assets/44235289/2752b3ee-b965-4b33-80d1-736087b6cce3)

3. Just declare `document` out of scope
   ![chrome_gk04rgmwlx](https://github.com/node-red/node-red/assets/44235289/2999ea20-1a5e-467e-88ce-5b1b74ae6c53)

And as an alterative, don't use `document` at all (that seems to be the popular opinion in places i've looked) Instead, use the `element.evaluate` API provided by puppeteer:

```js
const browser = await puppeteer.launch({
  executablePath: '/usr/bin/chromium-browser'
})
const page = await browser.newPage();
await page.goto('https://developer.chrome.com/');
let element = await page.waitForSelector('article'); // select the article
if (!element) {
    element = await page.waitForSelector('body'); // select the body
}
const value = await element.evaluate(el => el.innerText); // grab the innerText from the element
msg.payload = value
return msg
```

<br>
<br>

#### Additional context on why `document` is "not a thing" in the function node.

Monaco does have built in awareness of the browser environment.  This can be witnessed if you add a `template` node to the workspace and chose `JavaScript` mode:
![chrome_9PQQn65G2T](https://github.com/node-red/node-red/assets/44235289/23107ccb-1011-4b4c-9841-d8cb1da4f886)

This is achieved at instantiation time and is deliberately NOT included in the function node as it is (primarily) a Node context. It would be confusing to users to be presented with `window` and `document` etc.


<br>

> I can't remember if we load types dynamically for the added modules? 

No, not something we have gotten done yet (there is an issue floating around and a few threads on the forum)


> Also not sure if that would be sufficient to resolve this particular issue. We aren't going to hardcode puppeteer awareness into the core of the editor otherwise.

Agreed, i dont think the editor would understand the differing context. However, if we did have a means of adding types, in theory, the user would have to add a reference and JSDoc to get type hints and autocomplete support
![image](https://github.com/node-red/node-red/assets/44235289/e7afc21e-fcb6-4ac0-a809-14f65271a410)

**Comment by gmag11** [comment]
I think it's enough to mark this closed. Thank you very much for the `document` advise.
