### ISSUE TITLE
Stop support nodered on pi4?

### ISSUE THREAD

**Issue by duycop** [node-red/node-red#4784]
I can not pull for linux/arm/v8
```
sudo docker pull nodered/node-red
Using default tag: latest                          
latest: Pulling from nodered/node-red
no matching manifest for linux/arm/v8 in the manifest list entries
```

**Comment by hardillb** [comment]
This should have been raised on https://github.com/node-red/node-red-docker

But we have never built containers tagged as `linux/arm/v8` (https://hub.docker.com/r/nodered/node-red/tags?page=&page_size=&ordering=&name=3.1.11)

For Node-RED v4.0.0 we dropped `linux/arm/v6` and `linux/s390x`

Also there has never been a `linux/arm/v8` base build (https://hub.docker.com/_/node/tags?page=&page_size=&ordering=&name=alpine)

**Comment by hardillb** [comment]
Did you install the 32bit version of the OS on a Pi4?

**Comment by SuiKaSan** [comment]
@hardillb 
Hi, Hardillb.
What about linux/arm/v7?
The latest tag of node-red image seem droped the support of linux/arm/v7.
I can't pull it from my armv7 machine.

**Comment by hardillb** [comment]
@SuiKaSan I can see I disabled it back in March because it was hanging during the build as well.

I will re-enable it and see if I can get it to build.

**Comment by hardillb** [comment]
Yep, I've tested again and the NodeJS 20 and 22 builds just never finish on ARMv7 (same as s390x and ARMv6).

The NodeJS 18 build works, but that's not helpful when we want the default build to be NodeJS 20.

They end up in a spinning in recvfrom().

I opened an issue with NodeJS and didn't get any traction apart from others with the same problem or saying they couldn't reproduce the problem.  https://github.com/nodejs/node/issues/50339

**Comment by SuiKaSan** [comment]
OK.
Thanks for your reply.
I'll keep an eys and see where it goes.

**Comment by cherjr** [comment]
@duycop any solution? got the same on my osmc installation

**Comment by hardillb** [comment]
The next build should have a 32bit ARMv7 build

**Comment by cherjr** [comment]
> The next build should have a 32bit ARMv7 build

... but my problem is that it started to search for v8 somehow ...

**Comment by hardillb** [comment]
We have never build ARMv8 32bit containers (and there are no nodejs base containers with that tag https://hub.docker.com/_/node/tags).

**Comment by cherjr** [comment]
> We have never build ARMv8 32bit containers (and there are no nodejs base containers with that tag https://hub.docker.com/_/node/tags).

I believe you ;) The problem is that my installation (osmc) unexpectedly starts searching this, and I'm trying to find the solution...

**Comment by hardillb** [comment]
You need to either build the containers yourself or wait for the next spin (most likely 4.0.3)

**Comment by cherjr** [comment]
> You need to:
> 
> * build the containers yourself
> * Stick at 3.1.x version
> * Use the debian based build
> * Wait for the next spin (most likely 4.0.3)

Thanks! Will be waiting

**Comment by SuiKaSan** [comment]
> You need to:
> 
> * build the containers yourself
> * Stick at 3.1.x version
> * Use the debian based build
> * Wait for the next spin (most likely 4.0.3)

May I ask when will 4.0.3 be released?

**Comment by hardillb** [comment]
I have respun the 4.0.2 builds today. There should now be ARMv7 containers in the manifest

**Comment by cherjr** [comment]
> I have respun the 4.0.2 builds today. There should now be ARMv7 containers in the manifest

solved it for me. thanks for you work!
