### ISSUE TITLE
Node-red docker synology crash after delay module

### ISSUE THREAD

**Issue by Ssyleric** [node-red/node-red#4790]
### Current Behavior

upgrading to 4.0
<img width="697" alt="Screenshot 2024-06-24 at 11 02 40" src="https://github.com/node-red/node-red/assets/47066760/63b6db04-741a-497d-87ec-28e5df01720c">

after cast voice, sound and a delay of 5s nodered crashed and restart

### Expected Behavior

No crash and continuous the following flows

### Steps To Reproduce

After i pushed the inject button
<img width="1300" alt="Screenshot 2024-06-24 at 10 55 13" src="https://github.com/node-red/node-red/assets/47066760/b3b0c811-9ae1-44b8-a088-c8073130ea85">
<img width="353" alt="Screenshot 2024-06-24 at 11 14 28" src="https://github.com/node-red/node-red/assets/47066760/4c8549d9-7085-4b63-88c6-1aa20ac207cb">
<img width="513" alt="Screenshot 2024-06-24 at 11 14 48" src="https://github.com/node-red/node-red/assets/47066760/5615d074-dba4-456e-9311-75b678b9f6dc">

[_ndrd_logs_24062024.txt](https://github.com/user-attachments/files/15952666/_ndrd_logs_24062024.txt)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 4.0
- Node.js version:
- npm version:
- Platform/OS: Synology 7.2
- Browser: Brave

**Comment by knolleary** [comment]
From your logs, the Node-RED crash is a bug in the `node-red-contrib-cast` node; 

```
24 Jun 10:31:16 - [error] TypeError: node.error is not a function
    at errorHandler (/data/node_modules/node-red-contrib-cast/cast-to-client.js:52:10)
    at getSpeechUrl (/data/node_modules/node-red-contrib-cast/cast-to-client.js:192:9)
    at Timeout._onTimeout (/data/node_modules/node-red-contrib-cast/cast-to-client.js:836:33)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

Which has already been reported here: https://github.com/Hypnos3/node-red-contrib-cast/issues/416

**Comment by Ssyleric** [comment]
Ok, i understands that, but why node-red crashed?

**Comment by hardillb** [comment]
Because that is correct thing to do with a unhandled error, we do not know what state anything has been left in if the node does not handle the error.

**Comment by Ssyleric** [comment]
I have to disable it?

**Comment by hardillb** [comment]
The issue Nick linked to was raised back in April and it's not even been acknowledged, that and given that the node in question has not been updated in 4 years I think it is unlikely it will get fixed.

You may need to either sick with NR 3.1.x for now or look for a different cast node.

**Comment by Ssyleric** [comment]
Thanks a lot. 🙏

**Comment by knolleary** [comment]
Closing as this appears to be a node-specific issue
