### ISSUE TITLE
removing TLS Config in http request node does not work

### ISSUE THREAD

**Issue by superbreadi** [node-red/node-red#4799]
### Current Behavior

http node with activated TLS requests https.
if i want http, and deactivate TLS, the setting persists.
![image](https://github.com/node-red/node-red/assets/83004561/cdad1a24-b85f-419e-80d7-8fb18b1cd057)
if i disable "Enable secure (SSL/TLS) connection" and hit deploy, open the settings again, it is enabled again.

### Expected Behavior

if i disable tls, it should be disabled after deploy and use http

### Steps To Reproduce

create http request node, set tls config to an empty config , deploy und than remove it and hit deploy.

### Example flow

```
[{"id":"eaf2ebcb925b22da","type":"http request","z":"76aa9e267250ce29","name":"","method":"GET","ret":"txt","paytoqs":"ignore","url":"google.de","tls":"27a69a679c22bf93","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":610,"y":380,"wires":[["b470396807a92398"]]},{"id":"aec00b9fa6135e5e","type":"inject","z":"76aa9e267250ce29","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":390,"y":380,"wires":[["eaf2ebcb925b22da"]]},{"id":"b470396807a92398","type":"debug","z":"76aa9e267250ce29","name":"debug 17","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":870,"y":380,"wires":[]},{"id":"27a69a679c22bf93","type":"tls-config","name":"","cert":"","key":"","ca":"","certname":"","keyname":"","caname":"","servername":"","verifyservercert":false,"alpnprotocol":""}]
```

### Environment

- Node-RED version: 4.0 (nodered/node-red:latest)
- Node.js version:
- npm version:
- Platform/OS: docker container with docker compose on debian
- Browser: chrome

**Comment by hardillb** [comment]
I have seen similar with the proxy settings

**Comment by Steve-Mcl** [comment]
> if i disable "Enable secure (SSL/TLS) connection" and hit deploy, open the settings again, it is enabled again.



I suspect this will may be related to #4788 and _might be resolved_

Gonna pull and test.


> I have seen similar with the proxy settings

Just witnessed that too.

**Comment by GogoVega** [comment]
Yeah it's related to 4788.

In `oneditsave`:
```js
if (!$("#node-input-usetls").is(':checked')) {
  $("#node-input-tls").val("_ADD_");
}
```
So the node value after that for `node.tls` is `""` and the related problem will retrieve another node instead of the `none` option.

**Comment by Steve-Mcl** [comment]
Unfortunately, while https://github.com/node-red/node-red/pull/4788 fixes the selection of a config, it does not fix the places where a tickbox is used to deselect a config.

**Comment by Steve-Mcl** [comment]
> Yeah it's related to 4788.
> 
> In `oneditsave`:
> 
> ```js
> if (!$("#node-input-usetls").is(':checked')) {
>   $("#node-input-tls").val("_ADD_");
> }
> ```
> 
> So the node value after that for `node.tls` is `""` and the related problem will retrieve another node instead of the `none` option.

So this there still a PR required to fix this?

I mean i pulled master (where 4788 was merged to) and the issue of clearing the check box on TLS and PROXY is still present.

**Comment by GogoVega** [comment]
It seems that in `oneditprepare` it does not like the value `"_ADD_"` - I will investigate why.
So quick fix, change `"_ADD_"` by `""`

**Comment by knolleary** [comment]
> So quick fix, change "_ADD_" by ""

No - there could be lots of 3rd party nodes that have copied this code - we cannot require them all to apply a fix.

The fix must be in the core of the editor; using `_ADD_` consistently and *not* `""` for the value of the 'none' selection.

**Comment by Steve-Mcl** [comment]
> if i disable "Enable secure (SSL/TLS) connection" and hit deploy, open the settings again, it is enabled again

@superbreadi as a temporary means of getting past this, you can chose "none" and it will be remembered...


![chrome_EYzIWiaiB8](https://github.com/node-red/node-red/assets/44235289/dc7235f1-4de8-48dd-945d-134f73fbbfbf)

**Comment by GogoVega** [comment]
Putting `_ADD_` as a value in `oneditsave` causes the input value to be null in the pane properties.

**Comment by GogoVega** [comment]
Ok I revisited #4627 and replaced the `""` option by `"_ADD_"`, I will push the fix soon.
