### ISSUE TITLE
Function node code editor not working after upgrade to 4.x

### ISSUE THREAD

**Issue by Igloczek** [node-red/node-red#4813]
### Current Behavior

After the update to 4.x I can't edit function nodes anymore, because the code editor is not starting.

I see just an empty box and a bunch of errors in the browser console, all seem to be pointing to `parseHex` function from the Monaco editor (`vendor/monaco/dist/editor.js`).
No errors on the backend side.

```
editor-tab-description 
TypeError: Cannot read properties of null (reading 'length')
    at t.parseHex (editor.js:2:645497)
    at a.fromHex (editor.js:2:641764)
    at P.getColors (editor.js:2:3519708)
    at P.getColor (editor.js:2:3519929)
    at En.getColor (editor.js:2:1630678)
    at new Zi (editor.js:2:1590677)
    ...
```

This is thrown after closing the sidebar containing the broken editor, I believe it's trying to destroy the editor instance:
```
Error: Model is disposed!
    at yt._assertNotDisposed (editor.js:2:2388688)
    at yt.getOptions (editor.js:2:2391844)
    at dt.onConfigurationChanged (editor.js:2:1473698)
    at dt.handleEvents (editor.js:2:1418864)
    at Po._doConsumeQueue (editor.js:2:1668408)
    at Po._consumeViewEventQueue (editor.js:2:1668189)
    ...
```

I'm not 100% sure if this is the right place to report the issue, but the Home Assistant add-on is so thin, I don't think the bug can be introduced there, while reporting this straight away to Monaco editor seems like going a step too far with allegations.

### Expected Behavior

Build-it Monaco code editor working as before.

### Steps To Reproduce

1. Add a function node to the flow
2. Double click to open
3. Navigate to "On message" or "On start" tabs.

### Example flow

Any flow with function node is affected, that's why I'm dropping an empty one.

```
[{"id":"a59695e3692d2dd9","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"2c47026c82b16699","type":"function","z":"a59695e3692d2dd9","name":"function 3","func":"\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":480,"y":220,"wires":[[]]}]
```

### Environment

- Node-RED version: 4.0.1
- Node.js version: 18.20.3
- npm version: 10.7.0
- Platform/OS: Home Assistant OS 12.4  (amd64 / qemux86-64)
- Browser: Brave / Safari / Firefox - all behaves the same

**Comment by GogoVega** [comment]
This may seem ridiculous but have you tried clearing the cache and force reloading the browser?

**Comment by Igloczek** [comment]
@GogoVega yeah, I've tested it also on multiple browsers, and on multiple devices, web, mobile app, desktop app, restarted the server etc.

**Comment by Steve-Mcl** [comment]
@Igloczek 

Some years back we seen issues with misbehaving nodes that were causing prototype pollution (see [here](https://discourse.nodered.org/t/node-red-2-0-released/48647/43)) 

Could you provide a list of installed nodes please.

To get this, press <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and type **system info** then hit <kbd>Enter</kbd>.  Copy the `node_modules`  list into a reply

**Comment by Igloczek** [comment]
@Steve-Mcl unfortunately opening the system info is broken too, the same error as originally posted, but I'm running a clean install of Home Assistant add-on, nothing installed on top of it, so this list should offer the same set of informations - https://github.com/hassio-addons/addon-node-red/blob/main/node-red/package.json

I've tried to manually disable all the modules using Settings -> Palette -> Nodes -> Disable all on every node, but there was no difference.

**Comment by Steve-Mcl** [comment]
I don't use HA so cannot check this for my self but I imagine if this were an issue (as opposed to a one off issue) then all HA users would be seeing the same thing?  Have you seen similar reports on HA forum?

**Comment by Igloczek** [comment]
Nope, that's why reported it here.
But since this problem doesn't look like something obvious and easy to fix, I'm just downgrading back to working perfectly fine 3.x, as I don't want to put detective hat and debug this across multiple packages on my own.

**Comment by chenyu614** [comment]
I'm having a similar issue, but I can edit the process in my computer browser.
I can only see an empty box on my phone after the update to 4.0.1


Node-RED version: 4.0.1
Node.js  version: v18.20.3
Platform/OS: HAOS 12.4 (amd64 / qemux86-64)）
Supervisor: 2024.06.2
Core: 2024.6.4
Browser: Chrome / Safari /Home Assistant App- all behaves the same
