### ISSUE TITLE
Palette Manager doesn't reflect successful update of plugins

### ISSUE THREAD

**Issue by rvangeijtenbeek** [node-red/node-red#4831]
### Current Behavior

Since 4.0, the Palette Manager lists installed plugins alongside the nodes, for example for `node-red-contrib-themes/theme-collection`. This makes it easier to upgrade them.

When an update is available and I click 'update to 4.0.5', the update is performed successfully. I get a popup telling me to restart Node-RED. But in the Palette Manager it looks like the update wasn't done, the button 'update' is still showing.

This is different for normal node packages. For those, after an update the 'update' button gets grayed out, and an arrow is pointing from the old to the new version number.

The screenshot below shows how this looks when I upgraded a nodes and plugin package:
<img width="764" alt="NR-plugins-upgrade" src="https://github.com/user-attachments/assets/7906f9f4-7068-44a3-aeee-f3dc36704dad">

### Expected Behavior

The Palette Manager should indicate that a plugin update has been performed, with the same UI as for nodes packages.

### Environment

- Node-RED version: 4.0.2
- Node.js version: 18.20.3
- npm version: 10.7.0
- Platform/OS: Docker on Windows, nodered/node-red:latest-18, with a mounted /data folder on the Windows system
- Platform/OS: Windows 11
- Browser: MS Edge

**Comment by My-Random-Thoughts** [comment]
Can confirm, as I was going to log the same thing.

**Comment by GogoVega** [comment]
The problem is that `moduleList` does not contain the plugin.

@knolleary, How to solve this? Check if `RED.plugins` contains it?

https://github.com/node-red/node-red/blob/42382e1a03c0ab5a58fdb5b0eed7f539686b35a5/packages/node_modules/%40node-red/editor-client/src/js/nodes.js#L75-L78

**Comment by My-Random-Thoughts** [comment]
It may already be fixed.  On 4.0.5 the update button no longer shows

![image](https://github.com/user-attachments/assets/0db88b92-677f-4a33-98f3-9b22268452d7)

However, the `Remove` button is enabled even when the theme is in use.

**Comment by GogoVega** [comment]
Because you use the latest version of the plugin.

I don't think plugins have an "in use" logic.
