### ISSUE TITLE
"Context Data" tab is hidden by default in sidebar

### ISSUE THREAD

**Issue by ghost** [node-red/node-red#4840]
### Current Behavior

The "Context Data" tab is hidden by default in side bar unless the sidebar is manually resized or user click on caret down button.
![image](https://github.com/user-attachments/assets/2b160816-629f-4e9e-8631-0b47a0716b42)

### Expected Behavior

The "Context Data" tab should be visible by default, as shown in screenshot below:
![image](https://github.com/user-attachments/assets/847ac544-d37d-4b8b-a85f-5b10f8c45fa6)

### Steps To Reproduce

Open node-red, by default the sidebar is openned and one cannot see "Context Data" tab.

### Example flow

N/A

### Environment

- Node-RED version: 4.0.2
- Node.js version: N/A
- npm version: N/A
- Platform/OS: Mac OS X 10_15_7
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
- Docker image: nodered/node-red:latest             ac586c061df4

**Comment by dceejay** [comment]
Why should it be visible by default ? There has to be a cutoff somewhere as other items can also be added (eg dashboard) and the order can be rearranged. Has this idea been discussed on the forum and been decided it is an issue to be fixed ?
