### ISSUE TITLE
Node-red is using the wrong version of nodejs and failing to start.  If it is a bug, it is an installer bug.

### ISSUE THREAD

**Issue by ddirector51** [node-red/node-red#4846]
### Current Behavior

A newly installed version of node-red won't start from "node-red-start," complaining that the version of node js is too old.
node-red-start

```
dennis@raspberrypi:~ $ node -v
v18.20.4
dennis@raspberrypi:~ $ nodejs -v
v18.20.4
 
```

```Start Node-RED
 
Once Node-RED has started, point a browser at http://192.168.10.112:1880
On Pi Node-RED works better with the Firefox or Chrome browser
 
Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot
 
To find more nodes and example flows - go to http://flows.nodered.org
 
Starting as a systemd service.
Unsupported version of Node.js: v12.22.12
Node-RED requires Node.js v18 or later
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Scheduled restart job, restart counter is at 2559.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
Unsupported version of Node.js: v12.22.12
Node-RED requires Node.js v18 or later
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
```

There were no complaints visible during the install of node-red.
Also, nvm list shows
```
 nvm list
       v12.14.1
      v12.22.12
->     v18.20.4
         system
default -> 18.20.4 (-> v18.20.4)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v18.20.4) (default)
stable -> 18.20 (-> v18.20.4) (default)
lts/* -> lts/iron (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12
lts/fermium -> v14.21.3 (-> N/A)
lts/gallium -> v16.20.2 (-> N/A)
lts/hydrogen -> v18.20.4
lts/iron -> v20.16.0 (-> N/A)
```
I have been looking at this for hours. Any help is greatly appreciated.

### Expected Behavior

The newest version of nodejs that node-red wants is installed.  I would expect it to start.  On the previous version of node-red, I started it with systemctl all the time, no isses.

### Steps To Reproduce

I am not sure what is needed to reproduce the problem.  I had a previous version of node-red and updated using the suggested command "bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/d
eb/update-nodejs-and-nodered)".

### Example flow

```
N/A
```

### Environment

- Node-RED version: 4.0.2
- Node.js version: 18.20.4
- npm version: 10.7.0
- Platform/OS: Linux raspberrypi 5.10.92-v7l+ 
- Browser: Chrome  on Ubuntu Version 127.0.6533.88 (Official Build) (64-bit)
- 
Node-red works when started from the command line.
```
Node-RED version: v4.0.2
8 Aug 13:09:35 - [info] Node.js  version: v18.20.4
8 Aug 13:09:35 - [info] Linux 5.10.92-v7l+ arm LE
8 Aug 13:09:35 - [info] Loading palette nodes
8 Aug 13:09:38 - [info] Dashboard version 3.6.5 started at /ui
8 Aug 13:09:38 - [info] Settings file  : /home/dennis/.node-red/settings.js
8 Aug 13:09:38 - [info] Context store  : 'default' [module=memory]
8 Aug 13:09:38 - [info] User directory : /home/dennis/.node-red
8 Aug 13:09:38 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 Aug 13:09:38 - [info] Flows file     : /home/dennis/.node-red/flows.json
8 Aug 13:09:39 - [info] Server now running at http://127.0.0.1:1880/
```

**Comment by ddirector51** [comment]
I believe I have it working now, thanks to Stackoverflow.
This seems to have fixed the problem.
```
Install npm using curl (or wget)
curl http://npmjs.org/install.sh | sh
Install n using npm
npm install -g n
Install the latest version of node using n
n latest
```
Does that look like the right thing to do?  Why is this not in the install script?  Thanks

**Comment by hardillb** [comment]
Did you install nvm for your user?

**Comment by ddirector51** [comment]
Yes, I did install nvm for the user, and 
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
See above, I found a solution, I don't know if it is THE solution.

**Comment by hardillb** [comment]
Ok, that's the real problem, Node-Red running as a service will not load .bashrc/.profile so will not use nvm

**Comment by dceejay** [comment]
Well - not a problem - that is just the way nvm works. The real answer is to uninstall n and/or nvm and install nodejs.

**Comment by ddirector51** [comment]
I have nodejs installed.  At least I think I do.  This is quite confusing.
I don't even know
what n and nvm do, I just know that someone suggested installing n and then
it fixed the problem.
As to nodejs, I have a /usr/bin/nodejs which is a link to node installed in
.nvm subdirectory of
the user account.  Doesn't that mean I have nodejs installed?  And I still
don't understand why extra
steps are needed.  Why didn't the install script work for me?

Thanks.

**Comment by hardillb** [comment]
`n` and `nvm` are tools which allow the installing and managing of multiple versions of NodeJS, they install different versions under the users home directory and do not change any "system" wide installed version of NodeJS. They are intended for use mainly by developers who want/need to test on multiple different versions of NodeJS. They also allow none admin users to install a version of NodeJS just for themselves. They do all this by manipulating the PATH variable for the local user (e.g. by modifying the `.bashrc`or `.profile` file of the user in question.

While this is very useful it does rely on the user logging in, to trigger reading the `.bashrc` file.

When Node-RED runs as a service the system starts Node-RED as the given user, but does not log in and hence does not read the `.bashrc` file, so it picks up the default PATH variable and uses the System installed version of NodeJS.

The script does it's best ensure that the correct version of NodeJS is installed correctly, but can't always detect all situations. Without the installer log file, it is impossible to say what has happened in this case, but I will guess that it found a local copy of NodeJS on the PATH setup by `nvm` and hence did not install the new version system wide.

**Comment by ddirector51** [comment]
Got it, thanks for the details.
