### ISSUE TITLE
Unexpected Node Error (node object is not a node-red Node) reported by @chaws/node-red-denon

### ISSUE THREAD

**Issue by meehab** [node-red/node-red#4847]
### Current Behavior

The configuration of this node generates the following error on deployment., though the node continues to function as expected.

Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: Initializing...
    at log_helper (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:526:20)
    at Node.log (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:545:5)
    at new DenonConnectionNodeConstructor (/data/node_modules/@chaws/node-red-denon/dist/denon-connection.js:43:14)
    at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/util.js:190:27)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:235:50)
    at async start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/index.js:403:17)

Please report this issue, including the information logged above:
https://github.com/node-red/node-red/issues/
**************************************************************...

### Expected Behavior

The node should not generate this error. It did not do so in v3.0.6

### Steps To Reproduce

Add the Denon-In node to a flow.
Add a configuration for a Denon device
Deploy 
Observe that the attached 'Unexpected Node Error' is generated

### Example flow

```
[
    {
        "id": "618ce9573096ce28",
        "type": "debug",
        "z": "53c585ed1ab9fe07",
        "name": "Marantz AV8805",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1420,
        "y": 520,
        "wires": []
    },
    {
        "id": "ab97c9cf6674ffd3",
        "type": "switch",
        "z": "53c585ed1ab9fe07",
        "name": "filter events",
        "property": "payload.event",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "mainZoneOn",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "mainZoneOff",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 1230,
        "y": 680,
        "wires": [
            [
                "531c4e3581b3fa01"
            ],
            [
                "20a6a6b291164ef6"
            ]
        ]
    },
    {
        "id": "20a6a6b291164ef6",
        "type": "function",
        "z": "53c585ed1ab9fe07",
        "name": "Power Off",
        "func": "msg.payload = {\"cmd\": \"power\", \"value\": \"off\"}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "x": 1420,
        "y": 700,
        "wires": [
            []
        ]
    },
    {
        "id": "531c4e3581b3fa01",
        "type": "function",
        "z": "53c585ed1ab9fe07",
        "name": "Power On",
        "func": "msg.payload = {\"cmd\": \"power\", \"value\": \"on\"}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1420,
        "y": 660,
        "wires": [
            []
        ]
    },
    {
        "id": "efb22254bf6a6958",
        "type": "switch",
        "z": "53c585ed1ab9fe07",
        "name": "filter 'raw'",
        "property": "payload.event",
        "propertyType": "msg",
        "rules": [
            {
                "t": "neq",
                "v": "raw",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 1200,
        "y": 600,
        "wires": [
            [
                "618ce9573096ce28"
            ]
        ]
    },
    {
        "id": "767cf3dd4379842a",
        "type": "denon-in",
        "z": "53c585ed1ab9fe07",
        "name": "Marantz8805",
        "connection": "a4cc92c461ecc025",
        "x": 1030,
        "y": 640,
        "wires": [
            [
                "efb22254bf6a6958",
                "ab97c9cf6674ffd3"
            ]
        ]
    },
    {
        "id": "a4cc92c461ecc025",
        "type": "denon-connection",
        "name": "Marantz8805",
        "address": "192.168.1.185",
        "port": "23"
    }
]
```

### Environment

- Node-RED version: 4.0.2
- Node.js version: 2.15.1
- npm version: 10.7.0
- Platform/OS: unRaid docker
- Browser: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)

**Comment by knolleary** [comment]
Thanks for reporting.

The reason the errors you to report these sorts of errors here is because they can sometimes be hard for end-users to track down the node causing the problem based just on the error message. We can help do that, and then direct the issue to the node author to resolve the issue in their code - rather than it being something we can fix in the core of Node-RED.

In this instance, as you rightly identify, this is a problem with the `@chaws/node-red-denon` module. Unfortunately, it appears that module has been abandoned by its owner. It doesn't appear on flows.nodered.org and its source code repository (https://github.com/ChristopherHaws/node-red-denon) has been archived.

Given those circumstances, there is nothing we in the core project can do about this matter.
