### ISSUE TITLE
E-mail node missing TLS option when Auth Type = None

### ISSUE THREAD

**Issue by JohnnyPicnic** [node-red/node-red#4860]
### Current Behavior

TLS option disappears when Auth Type = None
![2024-08-30_9-32-04](https://github.com/user-attachments/assets/d488d171-9edd-43de-8718-ff78c6a7ea3a)

### Expected Behavior

Show TLS option when Auth Type = None
![2024-08-30_9-31-51](https://github.com/user-attachments/assets/c9e8e7de-b91b-4069-a9b2-1b7added583a)

### Example flow

```
paste your flow here
```

### Environment

Node-RED version: v4.0.2
Node.js  version: v22.7.0
Windows_NT 10.0.17763 x64 LE

**Comment by hardillb** [comment]
What version of the email node are you using?

Also we will need to move this to https://github.com/node-red/node-red-nodes as the email node is not a core node.

**Comment by JohnnyPicnic** [comment]
version 3.0.1

**Comment by dceejay** [comment]
published as v3.0.2
