### ISSUE TITLE
Unable to select which subflow config property to use when more than one configured

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#4863]
### Current Behavior

With the subflow flow below, which has two config type properties configured, it is only possible to select the first one for the mqtt broker.  If the second one is selected the node is not marked as modified and on re-opening it has reverted to the first one.

I don't know if this is a problem in general or if there is an issue with just this subflow.

See also this forum post https://discourse.nodered.org/t/unable-to-save-the-second-customising-config-nodes-in-subflows/90701

### Expected Behavior

It should be possible to select any of the config nodes

### Steps To Reproduce

Import the subflow below, and Deploy
Open the MQTT node and select the second config property (`tow`).
Close the dialog. The node is not marked as modified and on re-opening it has reverted to `one`

### Example flow

```
[
    {
        "id": "e54169906b92fd0f",
        "type": "subflow",
        "name": "Subflow 3",
        "info": "",
        "category": "",
        "in": [],
        "out": [],
        "env": [
            {
                "name": "one",
                "type": "mqtt-broker",
                "value": "",
                "ui": {
                    "type": "conf-types"
                }
            },
            {
                "name": "tow",
                "type": "mqtt-broker",
                "value": "",
                "ui": {
                    "type": "conf-types"
                }
            }
        ],
        "meta": {},
        "color": "#DDAA99"
    },
    {
        "id": "4a7c38167d88f367",
        "type": "mqtt out",
        "z": "e54169906b92fd0f",
        "name": "",
        "topic": "",
        "qos": "",
        "retain": "",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "${one}",
        "x": 130,
        "y": 120,
        "wires": []
    }
]
```

### Environment

- Node-RED version: 4.0.2
- Node.js version: 20.5.1
- npm version:
- Platform/OS: Ubuntu
- Browser: Edge

**Comment by Steve-Mcl** [comment]
confirmed (on 4.0.2)

> Import the subflow below, and Deploy
> Open the MQTT node and select the second config property (tow).
> Close the dialog. The node is not marked as modified and on re-opening it has reverted to one
