### ISSUE TITLE
Still can add flow after hiding unwanted menu items by id. 

### ISSUE THREAD

**Issue by Lau-Yx** [node-red/node-red#4864]
### Current Behavior

> setting.js
```   
editorTheme: {
        menu: { 
            "menu-item-workspace-add": false,
            "menu-item-workspace-delete": false
        }
}
```

### Expected Behavior

![image](https://github.com/user-attachments/assets/ee7c0768-0dcf-4500-a718-2d92963df040)

### Environment

- Node-RED version: v4.0.2
- Node.js version: v20.9.0

**Comment by knolleary** [comment]
Fixed via #4869 - will be in next maintenance release
