### ISSUE TITLE
Hide Show-action-list options when disabled via editorTheme

### ISSUE THREAD

**Issue by Lau-Yx** [node-red/node-red#4870]
### Current Behavior

> settings.js
```
editorTheme: {
        menu: { 
             "menu-item-action-list": false
        }
}
```

### Expected Behavior

Need to hide Show-action-list options and disable [ctrl+shift p] shortcut key.
![image](https://github.com/user-attachments/assets/6a386cb0-f08a-4451-b5cb-18097be85c8f)

### Environment

- Node-RED version: v4.0.2
- Node.js version: v20.9.0

**Comment by knolleary** [comment]
Thanks for highlighting. I'll review all the menu actions and see what else needs handling.

**Comment by knolleary** [comment]
I've updated PR #4869 to include a fix for this one.
