### ISSUE TITLE
node-red - node name with accented characters not displayed correctly - lead to deployment issue 

### ISSUE THREAD

**Issue by gpr7700** [node-red/node-red#4871]
### Current Behavior

I recently did the upgrade to node-red 4.
I live in belgium and I have a lot of node name containing accented characters. Those nodes are not displayed correctly (encoding issue ?) and that leads to an issue when I do the deployment (homekit bridge).

Previous version 2 did not have this issue.

### Expected Behavior

node name containing accented characters are displayed correctly

### Steps To Reproduce

create a node with accented character, deploy it.
when you then do a refresh of the page, the name is not displayed correctly

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: nodered/node-red:latest-22
- Node.js version:
- npm version:
- Platform/OS: docker
- Browser: Chrome / Safari

![image](https://github.com/user-attachments/assets/7cb88aba-d62e-4d56-a65e-2ae1770c22d8)

**Comment by knolleary** [comment]
Can you export an example node that demonstrates the issue and share the JSON here?

**Comment by gpr7700** [comment]
sure herefater an export performed from the node-red dashboard - you can see the encoding issue

[{"id":"d9721bad.3ca858","type":"subflow","name":"OH State changed","info":"","category":"","in":[],"out":[{"x":920,"y":140,"wires":[{"id":"bd1ad28e.739b1","port":0}]}],"env":[],"meta":{},"color":"#DDAA99"},{"id":"9023a5d0.72dc28","type":"switch","z":"d9721bad.3ca858","name":"OnOff","property":"payload.type","propertyType":"msg","rules":[{"t":"eq","v":"OnOff","vt":"str"},{"t":"eq","v":"Percent","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":530,"y":100,"wires":[["bd1ad28e.739b1"],[]]},{"id":"6a2150b7.39ff5","type":"switch","z":"d9721bad.3ca858","name":"ItemStateChangedEvent","property":"type","propertyType":"msg","rules":[{"t":"eq","v":"ItemStateChangedEvent","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":330,"y":60,"wires":[["9023a5d0.72dc28"]]},{"id":"bd1ad28e.739b1","type":"switch","z":"d9721bad.3ca858","name":"StateChanged","property":"payload.value","propertyType":"msg","rules":[{"t":"neq","v":"payload.oldValue","vt":"msg"}],"checkall":"true","repair":false,"outputs":1,"x":760,"y":140,"wires":[["b18bbc81740885fb"]]},{"id":"d3f0397d70df8d01","type":"openhab2-events2","z":"d9721bad.3ca858","name":"","controller":"b3a23998cda0088c","itemname":"","x":130,"y":400,"wires":[["6a2150b7.39ff5"]]},{"id":"b18bbc81740885fb","type":"debug","z":"d9721bad.3ca858","name":"OH 'switch' event occured","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1020,"y":200,"wires":[]},{"id":"b3a23998cda0088c","type":"openhab2-controller2","z":"d9721bad.3ca858","name":"CMLK-V3","protocol":"http","host":"192.168.1.100","port":"8080","path":"","username":"","password":"","ohversion":"v3","token":""},{"id":"584796d7.0845f8","type":"subflow","name":"OH Switch state changed","info":"","category":"","in":[],"out":[{"x":680,"y":120,"wires":[{"id":"981e0a66.4e4218","port":0}]},{"x":680,"y":180,"wires":[{"id":"c015303b.46f5d","port":0}]}],"env":[],"color":"#DDAA99"},{"id":"52c0e850.d0d888","type":"subflow:d9721bad.3ca858","z":"584796d7.0845f8","name":"","env":[],"x":140,"y":60,"wires":[["c015303b.46f5d"]]},{"id":"c015303b.46f5d","type":"change","z":"584796d7.0845f8","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.value","tot":"msg"},{"t":"set","p":"topic","pt":"msg","to":"$split(msg.topic, \"/\", 4)[2]","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":80,"wires":[["981e0a66.4e4218"]]},{"id":"981e0a66.4e4218","type":"function","z":"584796d7.0845f8","name":"OH2HK_switch","func":"if (msg.payload == \"ON\") {\n    msg.payload = {\n        \"On\": true\n    };\n} else {\n    msg.payload = {\n        \"On\": false\n    };\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":540,"y":100,"wires":[[]],"info":"openhab2-in"},{"id":"fae402b9.436ba","type":"tab","label":"exterior switch","disabled":false,"info":""},{"id":"5eda0fb.a8131f","type":"homekit-service","z":"fae402b9.436ba","isParent":true,"hostType":"0","bridge":"de31e0ee.c7354","accessoryId":"","parentService":"","name":"Entr�e","serviceName":"Lightbulb","topic":"","filter":false,"manufacturer":"NRCHKB","model":"1.2.0","serialNo":"Default Serial Number","firmwareRev":"1.2.0","hardwareRev":"1.2.0","softwareRev":"1.2.0","cameraConfigVideoProcessor":"ffmpeg","cameraConfigSource":"","cameraConfigStillImageSource":"","cameraConfigMaxStreams":2,"cameraConfigMaxWidth":1280,"cameraConfigMaxHeight":720,"cameraConfigMaxFPS":10,"cameraConfigMaxBitrate":300,"cameraConfigVideoCodec":"libx264","cameraConfigAudioCodec":"libfdk_aac","cameraConfigAudio":false,"cameraConfigPacketSize":1316,"cameraConfigVerticalFlip":false,"cameraConfigHorizontalFlip":false,"cameraConfigMapVideo":"0:0","cameraConfigMapAudio":"0:1","cameraConfigVideoFilter":"scale=1280:720","cameraConfigAdditionalCommandLine":"-tune zerolatency","cameraConfigDebug":false,"cameraConfigSnapshotOutput":"disabled","cameraConfigInterfaceName":"","characteristicProperties":"{}","waitForSetupMsg":false,"outputs":2,"x":510,"y":40,"wires":[["b5fe1e6f.f9086"],[]],"icon":"node-red/light.svg"},{"id":"b84cd1ad.5ca6b","type":"homekit-service","z":"fae402b9.436ba","isParent":true,"bridge":"de31e0ee.c7354","parentService":"","name":"Terrasse","serviceName":"Lightbulb","topic":"","filter":false,"manufacturer":"NRCHKB","model":"1.2.0","serialNo":"Default Serial Number","firmwareRev":"1.2.0","hardwareRev":"1.2.0","softwareRev":"1.2.0","cameraConfigVideoProcessor":"ffmpeg","cameraConfigSource":"","cameraConfigStillImageSource":"","cameraConfigMaxStreams":2,"cameraConfigMaxWidth":1280,"cameraConfigMaxHeight":720,"cameraConfigMaxFPS":10,"cameraConfigMaxBitrate":300,"cameraConfigVideoCodec":"libx264","cameraConfigAudioCodec":"libfdk_aac","cameraConfigAudio":false,"cameraConfigPacketSize":1316,"cameraConfigVerticalFlip":false,"cameraConfigHorizontalFlip":false,"cameraConfigMapVideo":"0:0","cameraConfigMapAudio":"0:1","cameraConfigVideoFilter":"scale=1280:720","cameraConfigAdditionalCommandLine":"-tune zerolatency","cameraConfigDebug":false,"cameraConfigSnapshotOutput":"disabled","cameraConfigInterfaceName":"","characteristicProperties":"{}","waitForSetupMsg":false,"outputs":2,"x":540,"y":160,"wires":[["5bd51563.fa0abc"],[]],"icon":"node-red/light.svg"},{"id":"b5fe1e6f.f9086","type":"function","z":"fae402b9.436ba","name":"HK2OH_switch","func":"if (msg.hap.context !== undefined ) {\n    if(msg.payload.On === false) {\n        msg.payload = \"OFF\";\n    }\n    else {\n        if(msg.payload.On === true) {\n            msg.payload = \"ON\";\n        }\n    }\n    return msg;\n}","outputs":1,"noerr":0,"initialize":"","finalize":"","x":800,"y":40,"wires":[["276d6183.09239e"]]},{"id":"5bd51563.fa0abc","type":"function","z":"fae402b9.436ba","name":"HK2OH_switch","func":"if (msg.hap.context !== undefined ) {\n    if(msg.payload.On === false) {\n        msg.payload = \"OFF\";\n    }\n    else {\n        if(msg.payload.On === true) {\n            msg.payload = \"ON\";\n        }\n    }\n    return msg;\n}","outputs":1,"noerr":0,"initialize":"","finalize":"","x":800,"y":160,"wires":[["6faa6766.45e828"]]},{"id":"276d6183.09239e","type":"openhab2-out","z":"fae402b9.436ba","name":"","controller":"cc6a2e2f.c5c25","itemname":"light_entryway_ext","topic":"ItemCommand","payload":"","x":1030,"y":40,"wires":[[]],"icon":"node-red/light.svg"},{"id":"6faa6766.45e828","type":"openhab2-out","z":"fae402b9.436ba","name":"","controller":"cc6a2e2f.c5c25","itemname":"light_terrace","topic":"ItemCommand","payload":"","x":1010,"y":160,"wires":[[]],"icon":"node-red/light.svg"},{"id":"1fa627f57d6d1e7b","type":"homekit-service","z":"fae402b9.436ba","isParent":true,"hostType":"0","bridge":"de31e0ee.c7354","accessoryId":"","parentService":"","name":"Ext�rieur buanderie","serviceName":"Lightbulb","topic":"","filter":false,"manufacturer":"NRCHKB","model":"1.2.0","serialNo":"Default Serial Number","firmwareRev":"1.2.0","hardwareRev":"1.2.0","softwareRev":"1.2.0","cameraConfigVideoProcessor":"ffmpeg","cameraConfigSource":"","cameraConfigStillImageSource":"","cameraConfigMaxStreams":2,"cameraConfigMaxWidth":1280,"cameraConfigMaxHeight":720,"cameraConfigMaxFPS":10,"cameraConfigMaxBitrate":300,"cameraConfigVideoCodec":"libx264","cameraConfigAudioCodec":"libfdk_aac","cameraConfigAudio":false,"cameraConfigPacketSize":1316,"cameraConfigVerticalFlip":false,"cameraConfigHorizontalFlip":false,"cameraConfigMapVideo":"0:0","cameraConfigMapAudio":"0:1","cameraConfigVideoFilter":"scale=1280:720","cameraConfigAdditionalCommandLine":"-tune zerolatency","cameraConfigDebug":false,"cameraConfigSnapshotOutput":"disabled","cameraConfigInterfaceName":"","characteristicProperties":"{}","waitForSetupMsg":false,"outputs":2,"x":550,"y":100,"wires":[["aa3e2acac02e89b9"],[]],"icon":"node-red/light.svg"},{"id":"aa3e2acac02e89b9","type":"function","z":"fae402b9.436ba","name":"HK2OH_switch","func":"if (msg.hap.context !== undefined ) {\n    if(msg.payload.On === false) {\n        msg.payload = \"OFF\";\n    }\n    else {\n        if(msg.payload.On === true) {\n            msg.payload = \"ON\";\n        }\n    }\n    return msg;\n}","outputs":1,"noerr":0,"initialize":"","finalize":"","x":800,"y":100,"wires":[["ab2cd2bcff21c715"]]},{"id":"ab2cd2bcff21c715","type":"openhab2-out","z":"fae402b9.436ba","name":"","controller":"cc6a2e2f.c5c25","itemname":"light_laundry_ext","topic":"ItemCommand","payload":"","x":1030,"y":100,"wires":[[]],"icon":"node-red/light.svg"},{"id":"a3487e04a8e7ea29","type":"link in","z":"fae402b9.436ba","name":"li_light_laundry_ext","links":[],"x":915,"y":140,"wires":[["ab2cd2bcff21c715"]]},{"id":"c45c78a5d7bf678b","type":"switch","z":"fae402b9.436ba","name":"EXT Switch","property":"topic","propertyType":"msg","rules":[{"t":"eq","v":"light_entryway_ext","vt":"str"},{"t":"eq","v":"light_laundry_ext","vt":"str"},{"t":"eq","v":"light_terrace","vt":"str"}],"checkall":"false","repair":false,"outputs":3,"x":330,"y":120,"wires":[["5eda0fb.a8131f"],["1fa627f57d6d1e7b"],["b84cd1ad.5ca6b"]]},{"id":"7bd0933656c9f423","type":"subflow:584796d7.0845f8","z":"fae402b9.436ba","name":"","env":[],"x":110,"y":40,"wires":[["c45c78a5d7bf678b"],[]]},{"id":"de31e0ee.c7354","type":"homekit-bridge","bridgeName":"CMLK Node-red","pinCode":"111-11-111","port":"","allowInsecureRequest":false,"manufacturer":"NRCHKB","model":"1.2.0","serialNo":"Default Serial Number","firmwareRev":"1.2.0","hardwareRev":"1.2.0","softwareRev":"1.2.0","customMdnsConfig":false,"mdnsMulticast":true,"mdnsInterface":"","mdnsPort":"","mdnsIp":"","mdnsTtl":"","mdnsLoopback":true,"mdnsReuseAddr":true,"allowMessagePassthrough":true},{"id":"cc6a2e2f.c5c25","type":"openhab2-controller","name":"CMLK","protocol":"http","host":"192.168.1.100","port":"8080","path":"","username":"","password":""}]

Hereafter an extract from the flows.json (located on ny NAS), no encoding issue

{
    "id": "1fa627f57d6d1e7b",
    "type": "homekit-service",
    "z": "fae402b9.436ba",
    "isParent": true,
    "hostType": "0",
    "bridge": "de31e0ee.c7354",
    "accessoryId": "",
    "parentService": "",
    "name": "Extérieur buanderie",
    "serviceName": "Lightbulb",
    "topic": "",
    "filter": false,
    "manufacturer": "NRCHKB",
    "model": "1.2.0",
    "serialNo": "Default Serial Number",
    "firmwareRev": "1.2.0",
    "hardwareRev": "1.2.0",
    "softwareRev": "1.2.0",
    "cameraConfigVideoProcessor": "ffmpeg",
    "cameraConfigSource": "",
    "cameraConfigStillImageSource": "",
    "cameraConfigMaxStreams": 2,
    "cameraConfigMaxWidth": 1280,
    "cameraConfigMaxHeight": 720,
    "cameraConfigMaxFPS": 10,
    "cameraConfigMaxBitrate": 300,
    "cameraConfigVideoCodec": "libx264",
    "cameraConfigAudioCodec": "libfdk_aac",
    "cameraConfigAudio": false,
    "cameraConfigPacketSize": 1316,
    "cameraConfigVerticalFlip": false,
    "cameraConfigHorizontalFlip": false,
    "cameraConfigMapVideo": "0:0",
    "cameraConfigMapAudio": "0:1",
    "cameraConfigVideoFilter": "scale=1280:720",
    "cameraConfigAdditionalCommandLine": "-tune zerolatency",
    "cameraConfigDebug": false,
    "cameraConfigSnapshotOutput": "disabled",
    "cameraConfigInterfaceName": "",
    "characteristicProperties": "{}",
    "waitForSetupMsg": false,
    "outputs": 2,
    "x": 550,
    "y": 100,
    "wires": [
      [
        "aa3e2acac02e89b9"
      ],
      []
    ],
    "icon": "node-red/light.svg"
  }

**Comment by GogoVega** [comment]
I don't have this problem. I use an AZERTY keyboard.

Maybe you use a Swiss QWERTZ keyboard?

Example with some characters (my keyboard):
```json
[
    {
        "id": "3b4e2f6ded81ed2e",
        "type": "inject",
        "z": "15cdbf1d258ebb57",
        "name": "éèê-aà-ç-ù",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 240,
        "y": 600,
        "wires": [
            []
        ]
    }
]
```

**Comment by gpr7700** [comment]
I am using an azerty keyboard.
in the file flows.json : "Extérieur buanderie" is correctly encoded however the dashboard shows 
![image](https://github.com/user-attachments/assets/7852f7c6-4ef8-43c0-a0c2-a14dcf2997aa)

I had no issue with the previous of the docker image

**Comment by gpr7700** [comment]
it is coming from the back-end. If i do a get on http://192.168.1.100:1880/flows?_=1725978802740 I can see that the result already contains the encoding issue

**Comment by gpr7700** [comment]
from inside docker container the file encoding is correct 

black-pearl:/data$ file -bi flows.json
application/json; charset=utf-8
black-pearl:/data$

**Comment by unclej84** [comment]
seems to be an issue with Node.js 22 - I had it running with 4.0.2-20 (Docker / everything was fine) but after switching to 4.0.2-22 (Docker) I had a similar issue with German Umlauts

**Comment by knolleary** [comment]
I've just tested with Node 22 (both in docker image and running locally) and the accented characters appear fine. There must be some other factor we're overlooking here.

**Comment by unclej84** [comment]
for me it appeared first after I reloaded the editor / dashboard

**Comment by gpr7700** [comment]
do not know whether it can help to investigate or not

1/ 12/sept 13:45 : I fixed the encdoding issue in the name
2/ 12/sept 13:46 : deploy the changes
3/ 12/sept 13:47 : refresh the dashboard - names are still displayed correctly
4/ 12/sept 13:49 : restart docker container
5/ 12/sept 13:51 : refresh the dashboard - names are still displayed correctly 
6/ 12/sept 14:05 : refresh the dashboard - names **no more displayed correctly** !!!!

**Comment by unclej84** [comment]
I updated to 4.0.3-22 a few minutes ago and until now everything looks fine again

**Comment by gpr7700** [comment]
I did the upgrade this morning and indeed until now the problem is gone

**Comment by knolleary** [comment]
Odd - not sure what cause this, or caused it to start working again in the 4.0.3 rebuild. Given no other reports of this behaviour have been reported, I'm going to close off.
