### ISSUE TITLE
MQTT security problem - connection even without verification

### ISSUE THREAD

**Issue by Eldarion85** [node-red/node-red#4877]
### Which node are you reporting an issue on?
mqtt in

### What are the steps to reproduce?
Mosquitto-Broker sends a trust chain to the client (Node-RED mqqt in) and the certificate should be checked by the client (checkbox "Check server certificate" in the tls-config).
Switch to "Use keys and certificates from local files" and write anything you can think of in the "CA certificate" field. 

### What happens?
The connection works, nothing is checked!

### What do you expect to happen?
That no connection is possible because the server certificate cannot be verified by the client without a CA certificate! So the same thing should happen as if I leave the "CA certificate" field empty.

### Please tell us about your environment:
- [ ] Node-RED version: v5.2.1
- [ ] node.js version: v20.15.0
- [ ] npm version: 10.7.0
- [ ] Platform/OS: Proxmox/Debian 12
- [ ] Browser: Google Chrome

###
Our MQTT broker is a Mosquitto under Debian. This has two listeners. One on port 1883 for unencrypted connections and one on port 8883 for encrypted connections. If a client connects on port 8883, the server sends its certificate in the form of a certificate chain (server certificate, intermediate CA and root CA).

Since the server sends the entire chain and not just its own certificate, you only need the root CA on the client to check the trust chain. This works wonderfully with all of our clients.

Unfortunately, with the standard MQTT node from Node-RED it works even when it shouldn't. If I don't store any certificates, the encrypted connection works and that's OK.

As soon as I check the box for "Check server certificate" in Node-RED and haven't stored any certificates yet, a connection is no longer possible. That's correct, because the certificate sent by the server can no longer be checked.
To change that, I entered the path to the shared root CA and everything worked. But then I noticed that I had made a mistake with the path and that was reported to me in the debug (path not found). Despite that, the connection was established and I received data. I then deleted the path again and then no connection was possible. However, it doesn't matter what I enter in the "CA certificate" field, the certificate from the server is trusted and the connection is online, even if the debug reports that the path doesn't exist when establishing it.

How can that be?

This doesn't work!
![Nur_Haken](https://github.com/user-attachments/assets/f058bdfd-0d3e-4047-b585-c814f2f1e667)

This shouldn't work either, but it does!
![Irgendwas](https://github.com/user-attachments/assets/3bc29b5b-9d9a-4eb5-be7a-806d49a323c6)

**Comment by Eldarion85** [comment]
Hello, please excuse the late reply.
I tested it with a new container (Debian 12 template) under Proxmox and a new installation of Node-RED 4.0.2 (stand-alone).
The problem is identical. If the require_certificate option is not enabled in the Mosquitto broker configuration, Node-RED does not check the server certificate, even if "Check server certificate" is enabled.

**Comment by hardillb** [comment]
OK, I know why this happens.

If the path for any of the certs or keys is invalid then the TLS node sets the `valid` flag to false and doesn't copy any settings into the broker options object by the `addTLSOptions()` function. This includes not setting the verify server cert flag so it defaults to false.

We need to decide if this is correct behaviour.

My gut feel is that even if the cert paths are not valid, then the verify server cert flag should still be set according to the TLS node. This way the connection will fail if the broker cert doesn't validate against a well known CA (as the provided CA failed to load) so triggering the user that something is definitely wrong (rather than just a none fatal error saying the path is wrong)

**Comment by hardillb** [comment]
I suggest we move setting the rejectUnauthorized out side the if check

https://github.com/node-red/node-red/blob/674eb36e15162ec62459784d023304c3fdf960b0/packages/node_modules/%40node-red/nodes/core/network/05-tls.js#L113

**Comment by Eldarion85** [comment]
Aaah OK, I understand. The setting "Check server certificate" is not used because the path is not valid. I can see in the debug that the path is not valid, but I cannot see that my setting to check the server certificate is not active. The problem is that the checkbox for "Check server certificate" remains in the settings and you cannot see that it is not checked anyway.

One option would be to automatically deactivate the checkbox if the path is not valid or at least display a message that the setting is not being used.
The better option is of course yours, to always check the server certificate if the checkbox is set. If the path is not correct, the certificate cannot be validated and therefore no connection is established.

**Comment by Eldarion85** [comment]
But I'm fairly sure that I couldn't reproduce it if the "require_certificate" parameter was set in Mosquitto.

Why that is the case would still not be clear, would it?

As you described it, the server certificate should never be checked if the path for the CA does not exist. But I think if "require_certificate" was active in the broker, the server certificate had to be validatable in any case. If the path was wrong, I couldn't establish a connection. I'll test it again tomorrow.

**Comment by hardillb** [comment]
> One option would be to automatically deactivate the checkbox if the path is not valid or at least display a message that the setting is not being used.

A flow can not modify it's own settings like this.

> But I'm fairly sure that I couldn't reproduce it if the "require_certificate" parameter was set in Mosquitto.

This is because mosquitto is refusing the connection if the initial handshake doesn't container a client cert, it doesn't mater that the broker server cert is not checked in this case, because it's never returned, the broker has already refused the connection.

**Comment by Eldarion85** [comment]
No, of course I entered the client certificate and the client key correctly in the test and stored the root CA in the Mosquitto CA folder. The server can validate the client certificate perfectly. Only the path for the CA in the client was wrong again, so the client cannot check the server. Despite this, no connection was possible and the client must have rejected it. Because as soon as I corrected the path for the CA in the client, the connection was established immediately.
I will test it again tomorrow morning to see if the behavior is actually related to the setting in the mosquitto broker.

**Comment by Eldarion85** [comment]
Good morning,
I tested the behavior again this morning. However, with version 3.1.9. But I will test it again at home with 4.0.2.

Here it is exactly as I described above, that the behavior is definitely different if I activate "require_certificate" in the Mosquitto configuration.
![Mosquitto_Settings](https://github.com/user-attachments/assets/be2fbfde-d726-4208-8010-545f1eca7bf5)


**I did the following:**
**1.**
The client (Node-RED) and the server (Mosquitto) have each stored their certificate and associated key. In addition, both know the common root CA. The "require_certificate" option in the Mosquitto configuration is activated and the connection is established on port 8883. In addition, a user name and password are of course assigned. So the highest possible security on both sides. The connection can then be established immediately.
![Secure_OK](https://github.com/user-attachments/assets/be02c721-2684-4ea1-ae7b-3be05881e70a)


**2.**
To test whether the server really checks the client's certificate, I swapped the root CA for a false one. After that, the server rejects the connection from the client. If I then deactivate "require_certificate", the connection is immediately re-established because the server no longer checks the client's certificate. So everything is as it should be and we can be sure that the client certificates are OK and that they are checked by the server even when "require_certificate" is activated.


**3.**
All settings set back to standard, as described in point 1. Now I entered an incorrect path to the root CA on the client and after that no connection could be established. The client reports in the debug that the path to the root CA does not exist. Therefore, the verification of the server certificate, as you described above, must be deactivated. But even after restarting Mosquitto, no connection could be established. So everything is fine.
![No_Connection_with_true](https://github.com/user-attachments/assets/335c218f-4ee5-4e61-b15b-5d55d9723d41)


**4.**
After that, I just deactivated the "require_certificate" option in Mosquitto and restarted the service. I didn't change anything in the client (still the wrong path to the root CA). A connection was established immediately. I then reactivated "require_certificate" and was no longer able to establish a connection.
![Connection_with_false](https://github.com/user-attachments/assets/a0d33aa0-04f0-43d0-9e01-3e55239b67db)


So it is definitely the case that the error can only be reproduced if "require_certificate" is deactivated in the broker. Otherwise the client does not allow a connection if the path to the CA does not exist.

**Comment by Eldarion85** [comment]
Is it possible that when the server requests a certificate (with "require_certificate" activated in the broker), the client itself uses the stored root CA to validate its own certificate? I use the certificate chain as the client certificate, so the root CA is also in the client certificate file. But some applications still check, via the CA certificate store, whether their own certificate chain is also valid.

I had this idea when I completely deactivated the "Check server certificate" option in the client. Because even then I cannot establish a connection. So it could be that I cannot reproduce the error for this reason and it has nothing to do with checking the server certificate.
![No_check](https://github.com/user-attachments/assets/bbdd0db1-d333-4ac0-92b4-1a6ba68e3648)

**Comment by hardillb** [comment]
If **ANY** one of the client cert, client key or ca cert is invalid in the Node-RED TLS config node then **NONE** of those values are used and the check server cert flag is ignored.

The behaviour I described yesterday covers all this.

**Comment by Eldarion85** [comment]
Ah OK, I just thought that the server certificate check would be deactivated.
If the CA certificate is incorrect, the client will not send its own certificate to the server, even if it is correctly stored. Then the server will of course reject it. That explains the behavior, but it should be changed.
Thanks for your support!
