### ISSUE TITLE
nodered/node-red:latest-debian pulls old version 3.1.12

### ISSUE THREAD

**Issue by AndrewBarfield** [node-red/node-red#4886]
### Current Behavior

Tried to upgrade from v4.0.2 to v4.0.3 and now things are in an inconsistent state. Here's my update script:

```bash
#!/bin/bash
reset

image="nodered/node-red:latest-debian"

echo -e "Compose down:"
sudo docker-compose down

echo -e "\nRemove $image image:"
sudo docker rmi $image

echo -e "Compose up:"
sudo docker-compose up -d
```

### Expected Behavior

I expected to be upgraded to 4.0.3

### Steps To Reproduce

Run the script above or simply: `docker pull nodered/node-red:latest-debian`

### Environment

- Node-RED version: 4.0.2 (now 3.1.12)
- Node.js version: 17.5.0
- npm version: 8.10.0
- Platform/OS: Ubuntu 22.04.5 LTS
- Browser: Chrome Version 128.0.6613.137 (Official Build) (64-bit)

**Comment by hardillb** [comment]
Thanks, I thought we'd caught all of those last time.

I'll respin the 4.0.3 build which will fix that and then look at the build scripts again

**Comment by hardillb** [comment]
closed by https://github.com/node-red/node-red-docker/pull/454

**Comment by hardillb** [comment]
tags should be right now
