### ISSUE TITLE
Join node change in behaviour with 4.0 (resubmit of 4822)

### ISSUE THREAD

**Issue by chrish987** [node-red/node-red#4897]
### Current Behavior

Please see #4822 

Hi,
I have re-raised this as a new issue as the previous has had no updates. It still had a needs-info tag and I am not sure my updates have been seen, or what I need to do to make them visible.

If this is not going to be changed/fixed then I would appreciate it if you can let me know.
Thanks

### Expected Behavior

Please see #4822 

### Steps To Reproduce

Please see #4822 

### Example flow

Please see #4822 

### Environment

Please see #4822

**Comment by knolleary** [comment]
No need to open new issues to get attention on another issue
