### ISSUE TITLE
(HA) Snapshop issue after upgrading to 18.1.1

### ISSUE THREAD

**Issue by gregolin** [node-red/node-red#4901]
### Current Behavior

I having some nodes working fine for a long time, that take some snapshot from internal cams.
Snapshop from Intelbras (a Brazilian brand) is still working fine, but from Tapo cameras isn't working anymore.
I receive this error message:

`02/10/2024, 13:40:49[node: Camera Sala](http://192.168.86.53:8123/api/hassio_ingress/YWrMJ4mAIekknWfo8Y56Xg3c7ZQXr9lDdlbcUBhyzjM/#)
msg : error
"InputError: Invalid action format: lock"
02/10/2024, 13:40:49[node: Camera Sala](http://192.168.86.53:8123/api/hassio_ingress/YWrMJ4mAIekknWfo8Y56Xg3c7ZQXr9lDdlbcUBhyzjM/#)
msg : error
"ValidationError: "action" is not allowed to be empty"
02/10/2024, 13:40:49[node: Camera Sala](http://192.168.86.53:8123/api/hassio_ingress/YWrMJ4mAIekknWfo8Y56Xg3c7ZQXr9lDdlbcUBhyzjM/#)
msg : error
"ValidationError: "action" must be a string"`

### Expected Behavior

Snapshop from Tapo cameras

### Example flow

```
[{"id":"f477e916550abb8e","type":"inject","z":"cb3dfec3a4ef7404","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":800,"y":820,"wires":[["9e476d8d0c19338b"]]},{"id":"9e476d8d0c19338b","type":"api-call-service","z":"cb3dfec3a4ef7404","name":"Camera Sala","server":"fad61953.26ffa8","version":7,"debugenabled":false,"action":"camera.snapshot","floorId":[],"areaId":[],"deviceId":[],"entityId":["camera.camera_sala_sd_stream"],"labelId":[],"data":"{\"filename\": \"/config/www/imgs/cameras/sala.jpg\"}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"camera","service":"snapshot","x":1050,"y":820,"wires":[[]]},{"id":"fad61953.26ffa8","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
```

### Environment

- Node-RED version: 18.1.1
- Node.js version:
- npm version:
- Platform/OS: HA 2024.9.3
- Browser: Chrome

**Comment by knolleary** [comment]
Hi @gregolin 

We don't maintain the HA nodes,.so cannot help here.

Please raise an issue against the HA plugin, or the specific nodes you are having problems with

**Comment by GogoVega** [comment]
It's the https://flows.nodered.org/node/node-red-contrib-home-assistant palette which has not been updated for 6 years. The recommended palette is https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket.

**Comment by gregolin** [comment]
Ok, thanks.
