### ISSUE TITLE
Core Trigger Node does not send epoch

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#4914]
### Current Behavior

Reported on forum, here: https://discourse.nodered.org/t/trigger-node-output-bug-or-pebkac/92335

> One seems to send a legit timestamp, the other is just sending "1". Have they always been like this? I only noticed when one of my flows broke after updating to 4.0.4 and it is still behaving this way on 4.0.5.

Trigger node does not send epoch - it sends "1"

![image](https://github.com/user-attachments/assets/66d8c2a3-870c-417a-ae94-4f65b0a6ace3)

At a guess, this is related to the introduction of additional timestamp options since the trigger node has not had any changes for ~4y.

### Expected Behavior

Should send epoch

### Steps To Reproduce

import the below flow and inject

### Example flow

```
[{"id":"de7b0ee8ecb2e5ee","type":"group","z":"0f909bac596182b4","name":"Doesnt send epoch - GH issue #4914","style":{"stroke":"#2b2b2b","fill":"#181818","label":true,"color":"#ff0000","fill-opacity":"0.22"},"nodes":["36e5f0ca2a0f5cfc","9a9a4e8234f9f6f2","11068274249f5b33","4250ea710b0d6ffb","d24269b36bf9e864"],"x":984,"y":119,"w":532,"h":162},{"id":"36e5f0ca2a0f5cfc","type":"inject","z":"0f909bac596182b4","g":"de7b0ee8ecb2e5ee","name":"","props":[{"p":"topic","vt":"str"},{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1045,"y":200,"wires":[["9a9a4e8234f9f6f2","4250ea710b0d6ffb"]],"l":false},{"id":"9a9a4e8234f9f6f2","type":"trigger","z":"0f909bac596182b4","g":"de7b0ee8ecb2e5ee","name":"2 Seconds","op1":"","op2":"","op1type":"date","op2type":"nul","duration":"2","extend":false,"overrideDelay":false,"units":"s","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":1180,"y":160,"wires":[["11068274249f5b33"]]},{"id":"11068274249f5b33","type":"debug","z":"0f909bac596182b4","g":"de7b0ee8ecb2e5ee","name":"should send epoch","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":1380,"y":160,"wires":[]},{"id":"4250ea710b0d6ffb","type":"trigger","z":"0f909bac596182b4","g":"de7b0ee8ecb2e5ee","name":"2 Seconds","op1":"","op2":"","op1type":"pay","op2type":"nul","duration":"2","extend":false,"overrideDelay":false,"units":"s","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":1180,"y":240,"wires":[["d24269b36bf9e864"]]},{"id":"d24269b36bf9e864","type":"debug","z":"0f909bac596182b4","g":"de7b0ee8ecb2e5ee","name":"send the msg","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":1370,"y":240,"wires":[]}]
```

### Environment

- Node-RED version: 4.0.3, 4.0.4, 4.0.5
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by dceejay** [comment]
I think this is a consequence of the change to the date input type for typed inputs (that came with the inject node) - you now get the dropdown option for the three date types and the return from that is messing this up... for some reason :-) - if you pick iso or object format it works OK...

**Comment by Steve-Mcl** [comment]
> I think this is a consequence of the change to the date input type for typed inputs (that came with the inject node)

Agreed - my comment in the OP ☝️

> At a guess, this is related to the introduction of additional timestamp options since the trigger node has not had any changes for ~4y.

**Comment by dceejay** [comment]
so the question is do we fix the trigger node to handle this... or could this also affect other nodes that use the typed input in which case the core needs fixing... @knolleary ?

**Comment by dceejay** [comment]
I've gone ahead and fixed it here anyway - but yeah - may need more thought for other nodes...
