### ISSUE TITLE
ws error! Error: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by qq547176052** [node-red/node-red#4918]
### Current Behavior

![image](https://github.com/user-attachments/assets/b7bc8392-35e8-4210-b2b3-1ca3e516d9a7)

### Steps To Reproduce

4.0.5: Maintenance Release 
docker install

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
OK, so what do you think is listening on localhost `127.0.0.1` on port 443 inside the Node-RED docker container? (Remember that `127.0.0.1` points to the container Node-RED is running in, not the host machine)

Please fill out the full template and include a LOT more details.

Questions should be asked on the Node-RED Discourse forum or Slack, not in Issues.

**Comment by qq547176052** [comment]
Using Docker to install and start up will do this. I don't know why this is happening

**Comment by hardillb** [comment]
It will only do that if you have a flow (or a 3rd party node in the flow) deployed that is trying to open a connection to `wss://127.0.0.1/services/ws`

This is not something Node-RED is doing on it's own

**Comment by qq547176052** [comment]
Thank you very much. Delete all streams and it won't
