### ISSUE TITLE
process.env variables are accessible in function node despite excluding

### ISSUE THREAD

**Issue by Bulduper** [node-red/node-red#4923]
### Current Behavior

I disabled the environment variable `FOO` using `envVarExcludes: ['FOO']` within `settings.js`.

In the function node:
1. this does not expose the variable (ok)
```js
msg.payload = env.get("FOO"); // undefined
```
2. this DOES expose the variable (nok)
```js
msg.payload = RED.util.getSetting(null, "FOO"); // bar
```

### Expected Behavior

```js
msg.payload = RED.util.getSetting(null, "FOO"); // undefined
```
The `RED.util.getSetting` (*@node-red\util\lib\util.js*) should not take environment directly from process.env but it should respect the `envVarExcludes` setting.

### Steps To Reproduce

1. In `settings.js` add `envVarExcludes: ['PATH']` property to exclude the env from node-red enviroment.
2. Make a flow with function node 
```
msg.payload = RED.util.getSetting(null, "PATH");
return msg;
```
3. Observe the output

### Example flow

```
[{"id":"437d7fcb472a20f9","type":"inject","z":"eeaed20f6ed20cad","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":700,"y":920,"wires":[["5994a3487bce08b5"]]},{"id":"5994a3487bce08b5","type":"function","z":"eeaed20f6ed20cad","name":"function 7","func":"msg.payload = RED.util.getSetting(null, \"PATH\");\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":860,"y":920,"wires":[["1d4e8e1e18a7c9db"]]},{"id":"1d4e8e1e18a7c9db","type":"debug","z":"eeaed20f6ed20cad","name":"debug 40","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1020,"y":920,"wires":[]}]
```

### Environment

- Node-RED version: 4.0.5
- Node.js version: v20.18.0
- npm version: 10.8.2
- Platform/OS: debian
- Browser: any

**Comment by GogoVega** [comment]
The `RED.util.getSetting` function doesn't have access to the exclusion list. So it's not possible to exclude the variable when you set `node` to null.

Unless I am mistaken this function should not be exposed to the function node. Or have to modify it in the function node. @knolleary?

**Comment by GogoVega** [comment]
I did https://github.com/GogoVega/node-red/commit/7555e0644f3bc78cfa87f930ecbe9f7e99d3cb6c, if it's ok for you I'll open a PR.

**Comment by Bulduper** [comment]
Thank you @GogoVega . That seems to solve the problem. Please open a PR.
