### ISSUE TITLE
Add documentation for "autoLogin" functionality

### ISSUE THREAD

**Issue by pReya** [node-red/node-red#4952]
### Current Behavior

In the [documentation](https://nodered.org/docs/user-guide/runtime/securing-node-red) there is no mention of the "autoLogin" feature.

### Expected Behavior

However, the `autoLogin` feature seems to be available. It was developed in a [live stream](https://www.youtube.com/watch?v=X7E1_wPTUhk) and in May, there was a [bugfix](https://github.com/node-red/node-red/pull/4684) which was related to this feature.

However I can't find any reference in the codebase to the word `autoLogin`. So I'm very confused. Is this deprecated? Is it still available? What does it do?

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 4.0.5
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
https://github.com/node-red/node-red/pull/3519
