### ISSUE TITLE
Drag&Drop handling of JSON string that isn’t an array of nodes

### ISSUE THREAD

**Issue by gorenje** [node-red/node-red#4962]
### Current Behavior

When I drag and drop the string "[0]" (with or without the quotes) onto Node-RED workspace, I get this error:

![img](https://cdn.openmindmap.org/content/1731860827824_Screenshot_2024-11-17_at_16.17.43.png)

(or e.type is undefined depending on the minification of the .js.)

What is happening is that the drag&drop behaviour assumes that if the content can be parsed as valid JSON then it must be an array of nodes.

I as a user have no idea why that is happening nor does the error message help me, all I did was drag JSON content onto the workspace.

The cause of the error is this [line](https://github.com/node-red/node-red/blob/e48607c74317f047f09035872c9879816a3a0ed3/packages/node_modules/%40node-red/editor-client/src/js/nodes.js#L1917) in RED.node.import and this [code](https://github.com/node-red/node-red/blob/e48607c74317f047f09035872c9879816a3a0ed3/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L5935-L5937) is displaying the error message.

It might be better to ignore that error and not display it to the user. Drops that aren't handled are also silently ignored, i.e., the user won't necessarily expect feedback to be generated from their drop.

### Expected Behavior

Sensible error message or no error message.

### Steps To Reproduce

Drag "[0]" onto the workspace of the editor.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 4.0.5
- Node.js version: 22
- npm version: 
- Platform/OS: Docker Image 
- Browser: Firefox

**Comment by gorenje** [comment]
Initial discussion @ [Forum](https://discourse.nodered.org/t/drag-drop-handling-of-json-string-that-isnt-an-array-of-nodes/93206)

**Comment by knolleary** [comment]
Fixed via #4964
