### ISSUE TITLE
Inserting A Junction Issues

### ISSUE THREAD

**Issue by Buckskin-Cowboy** [node-red/node-red#4969]
ref https://discourse.nodered.org/t/how-to-find-a-junction/93461/18
### Current Behavior

Inserting a link into a wire defaults to placing the junction at the mid-point of the wire, rather than where the user clicked.
If the workspace is zoomed, the insert position is not calculated correctly

### Expected Behavior

When inserting a Junction when workspace is zoomed or when inserting a Junction into a wire the Junction should be located at the insertion point

### Steps To Reproduce

Zoom workspace and right click to insert a Junction. 
Select a wire and right click to insert a Junction

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 4.05
- Node.js version: 20
- npm version: 10
- Platform/OS: PiOS
- Browser: Edge

**Comment by gemini86** [comment]
I thought it might be relevant to add that using the alt+shift+lasso method does put the junction somewhat in a relative location to the mouse drag, BUT this is also affected by the zoomed workspace issue.
