### ISSUE TITLE
Http in node not saving request body in docs for POST request

### ISSUE THREAD

**Issue by DianaStefan5Minds** [node-red/node-red#4971]
### Current Behavior

When I edit the Docs Attribute at the bottom of the http in node, go to the tab request body and make any changes there, regarding the request body information, and try to save it, it will disappear with the next time opening it. 
Also, can I only provide a JSON Schema or, would a XML work just as well?
![image](https://github.com/user-attachments/assets/5fe5be0b-6db4-4976-9230-1c71ea04cd6b)

### Expected Behavior

When I reopen this tab, the previosly deployed changes should still be there.

### Steps To Reproduce

1. Add a http in node
2. provide an url
3. Do to edit Docs
4. Open the request body tab
5. Add any kind of information
6. Deploy
7. Reopen the request body doc.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v.4.0.5
- Node.js version: 22.8.0
- npm version: 10.8.2
- Platform/OS: Windows
- Browser: Chrome

**Comment by knolleary** [comment]
This will be a bug with https://flows.nodered.org/node/node-red-node-swagger rather than the core of Node-RED.

**Comment by DianaStefan5Minds** [comment]
In case someone else finds this issue. 
Adding {} in the request Body JSON Schema field, fixes the issue of not saving.
