### ISSUE TITLE
CSV Node Separator Issue: Headers and Body Misalignment

### ISSUE THREAD

**Issue by andrea-tomassi** [node-red/node-red#4977]
### Current Behavior

The CSV node has an error in the column headers separator character. When using the `;` (semicolon) as a separator, the output has headers using `,` (comma) and the body using`;` (semicolon).

![image](https://github.com/user-attachments/assets/2219806e-984f-4c69-aeb8-eaed06c771bc)

**N.B. Legacy mode is not affected**

### Expected Behavior

The CSV node should use the selected separator (`;` in this case) for both the headers and the body of the CSV.

### Steps To Reproduce

Configure the CSV node to use `;` (semicolon) as the separator.

Use the RFC4180 mode in the CSV node.

Inject a message with a CSV payload.

![image](https://github.com/user-attachments/assets/c4ce93ae-6e63-42ce-9cef-bc8d006cb11b)

### Example flow

```[{"id":"8c44ba9e59b84a84","type":"inject","z":"a9796cb084e3b87e","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"foo\":12,\"bar\":\"Hello\"}","payloadType":"json","x":110,"y":80,"wires":[["506a7cf138283d0a","1b1e6a11d42b2c02"]]},{"id":"e9616867afc47686","type":"debug","z":"a9796cb084e3b87e","name":"output csv","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":630,"y":80,"wires":[]},{"id":"506a7cf138283d0a","type":"csv","z":"a9796cb084e3b87e","name":"","spec":"rfc","sep":";","hdrin":"","hdrout":"all","multi":"one","ret":"\\r\\n","temp":"","skip":"0","strings":true,"include_empty_strings":"","include_null_values":"","x":390,"y":80,"wires":[["e9616867afc47686"]]},{"id":"1b1e6a11d42b2c02","type":"debug","z":"a9796cb084e3b87e","name":"input json","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":280,"y":160,"wires":[]}]```

### Environment

- Node-RED version: 4.0.5
- Node.js version: both and 20 / 22
- npm version:
- Platform/OS:
- Browser: Chrome

**Comment by knolleary** [comment]
Think I need @Steve-Mcl's input on this. The recent rewrite of the node has introduced lots of places where `,` is hardcoded as the separator and it ignores what the user has selected. There may be cases where that is valid because of the new 'strict' mode - but I'm not sure.

I have found a change that fixes the immediate issue - PR #4982 - but need to make sure it doesn't have any unexpected side effects in other scenarios.

**Comment by andrea-tomassi** [comment]
I see, Thank you for the follow-up, I'll wait for updates on that. Fortunately, the legacy mode seems to be working
