### ISSUE TITLE
Error loading settings file due to missing binary-parser-encoder

### ISSUE THREAD

**Issue by pekka-28** [node-red/node-red#4979]
### Current Behavior

After an uneventful installation, when trying to start node-red for the first time I received the message Error loading settings file: \Users\<User>\.node-red\settings.js.

I ran the node-red command in the folder that I had used to install the application. The file was present in the \users\<user>\.node-red folder. I initially tried to remove it as the documentation said a new one would be automatically copied. The error remained, and a new file was not copied.

I then looked in the node-red script and saw the location when the settings file was loaded and added a line to always print the contents of the error object. 

The missing dependency is odd and may be an installation issue.

The filtering of the reasonable error message is curious as without changing the script to display the raw message diagnosing this would have been extremely unlikely.

### Expected Behavior

Starting node-red successfully or receiving a sufficiently clear message to correct the problem and try again.

### Steps To Reproduce

Install node.js, Node-RED, run node-red to receive error
Install binary-parser-encoder, run node-red to successfully start

### Example flow

PS C:\Users\Pekka\Node-RED> node-red
Error loading settings file: \Users\Pekka\.node-red\settings.js
Error: Cannot find module 'binary-parser-encoder'
Require stack:
- C:\Users\Pekka\.node-red\settings.js
- C:\Users\Pekka\AppData\Roaming\npm\node_modules\node-red\red.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (C:\Users\Pekka\.node-red\settings.js:220:23)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Pekka\\.node-red\\settings.js',
    'C:\\Users\\Pekka\\AppData\\Roaming\\npm\\node_modules\\node-red\\red.js'
  ]
}

PS C:\Users\Pekka\Node-RED> npm install binary-parser-encoder

added 3 packages, and audited 4 packages in 4s

found 0 vulnerabilities
PS C:\Users\Pekka\Node-RED> node-red
5 Dec 14:10:52 - [info]

### Environment

- Node-RED version:  v4.0.5
- Node.js version: v22.12.0
- npm version: 10.9.0
- Platform/OS: Windows_NT 10.0.22621 x64 LE
- Browser: Edge

**Comment by knolleary** [comment]
From the error stack, the interesting line is:

```
at Object. (C:\Users\Pekka.node-red\settings.js:220:23)
```

Can you share your settings file - in particular around line 220?

**Comment by pekka-28** [comment]
[settings.txt](https://github.com/user-attachments/files/18023810/settings.txt)

Well caught. The settings file is attached. It directly references the errant parser. The date stamp on the file is 7 May 2019 18:02 and unchanged from the one copied by the installed. I had wondered by the dependency manager had allowed this to happen, but explicitly instantiating the library would bypass the check.

As a neophyte Node-RED user, I would not have thought to add this to the context so do not know how it ended up there.

**Comment by knolleary** [comment]
@pekka-28 thanks for sharing.

That isn't our current default settings file - but even then, we've never had that module included by default.

https://github.com/node-red/node-red/blob/84a2fbed2edee12c80b5a0b4ed9575ea90158940/packages/node_modules/node-red/settings.js#L512-L514

Not sure there's much else we can do here.

**Comment by pekka-28** [comment]
I looked more carefully at the startup messages and see that I have had Node-RED installed on the machine previously. This likely introduced this dependency. A subsequent uninstall-reinstall deleted the library causing the error.

I see in another similar issue #727 that you resolved by requesting the poster to move the required dependency to a searched folder.

I would agree that the message could be improved to indicate something wrong with accessing the settings file, or in executing its contents. This could then identify the dependency faults noted.

You've been most helpful and pointed me back to myself. No further action expected.
