### ISSUE TITLE
Since 4.0.6 update, all dashboard (v1) ui_tabs are marked as unused

### ISSUE THREAD

**Issue by My-Random-Thoughts** [node-red/node-red#4994]
### What are the steps to reproduce?
Have a v1 Dashboard with one or more ui_tabs

### What happens?
When clicking `Deploy` for changes, all ui_tabs are marked as unused nodes

![image](https://github.com/user-attachments/assets/0ef9e997-9a7e-4601-bc0f-176465c9aa0a)
![image](https://github.com/user-attachments/assets/66c86e91-5768-4ecf-baf3-a1fa0d616527)

### What do you expect to happen?
ui_tabs not being marked as unused unless they actually are

### Please tell us about your environment:
- Node-RED : node-red-docker@4.0.6 /usr/src/node-red
- Node.js  : v22.12.0
- npm      : 10.9.0
- Platform : Linux 6.1.0-18-amd64 x86_64
- Browser  : FireFox 133

**Comment by knolleary** [comment]
This is a bug related to tracking users of a config node that are themselves config nodes.

Can reproduce by;

1. Add MQTT In node
2. Add MQTT broker node
3. In broker node, tick 'use tls' and add a TLS config node
4. Deploy then reload the editor

The TLS config node shows as having 0 users.

**Comment by m-schaeffler** [comment]
@GogoVega I still have this issue with nodered 4.0.7 anmd dashboard 2.0 v1.20.1
