### ISSUE TITLE
NodeRed unexpeczed stopps running after starting, after update to 4.0.6

### ISSUE THREAD

**Issue by Fr3d3rick83** [node-red/node-red#4996]
### Current Behavior

The NR container keeps on restarting after update to the latest version.

### Expected Behavior

Start like it used to.

### Steps To Reproduce

Updated voa Synology Docker

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: v4.0.6
- Node.js version: v20.18.1
- npm version:
- Platform/OS: Synology DSM Docker Container
[nodered.csv](https://github.com/user-attachments/files/18168758/nodered.csv)

- Browser: Latest Firefox on macOS

**Comment by knolleary** [comment]
From the logs you've shared this is the error:
```
2024/12/17 17:36:53,stdout,17 Dec 16:36:53 - [red] Uncaught Exception:
2024/12/17 17:36:53,stdout,17 Dec 16:36:53 - [error] TypeError: Cannot read properties of undefined (reading 'company')
2024/12/17 17:36:53,stdout,    at EcovacsAPI.getVacBot (/data/node_modules/ecovacs-deebot/index.js:470:62)
2024/12/17 17:36:53,stdout,    at /data/node_modules/node-red-contrib-ecovacs-deebot/nodes/ecovacs-deebot.js:31:35
2024/12/17 17:36:53,stdout,    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

This is a problem with the `node-red-contrib-ecovacs-deebot` - not the core of Node-RED.

**Comment by Fr3d3rick83** [comment]
Thanks for the quick response. This is a Pallet I installed, and it worked well. But how can I deactivate or deinstall this pallet without the UI?

**Comment by Fr3d3rick83** [comment]
Thanks, now its working

**Comment by hardillb** [comment]
@Fr3d3rick83 remember to remove the env var next restart or the flows won't start until a deploy
