### ISSUE TITLE
Use of URL fragments in Node-RED (eg to support deep-linking)

### ISSUE THREAD

**Issue by njh** [node-red/node-red#506]
It may be useful to make use of URL fragments (the bit after the #) in Node-RED:
1. To allow deep linking into NodeRED, for example to allow an external app to allow people to jump straight to editing a node. This could be done using a link, something like this: http://127.0.0.1:1880/#nodes/26b06d1a.d94f92/edit
2. Make use of URL fragments to keep track of state, which navigating to different sections of the app. This would allow people, for example, to bookmark a specific Sheet and then return to it.

I have prototyped some of this in a fork.
1. Deep link directly to an edit dialog: 604bae2a1be38c0fe2cf3c611e7ea52bb1caea30
2. Changing the URL in the browser when opening/closing edit dialogs: 47fe5a39acc0eb9c432cd16f7e0a28f4e740cabb

**Comment by TotallyInformation** [comment]
This would be useful.

**Comment by knolleary** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use URL-fragments to support deep-linking to editor features](https://trello.com/c/ary9xnFX/176-use-url-fragments-to-support-deep-linking-to-editor-features)

**Comment by knolleary** [comment]
Moved to trello otherwise it'll get lost at the bottom of the issue list
