### ISSUE TITLE
rendering in firefox 34.0

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#508]
latest version of firefox (34.0) seems to have broken the rendering a bit... if you drag the scroll bar and a node on the edge of the canvas moves left, it stretches (see pic).
After 3 seconds, of inactivity, it redraws and corrects itself!
![stretchred](https://cloud.githubusercontent.com/assets/2693674/5332081/ff911bbe-7e3f-11e4-9941-64bfc71a0642.png)

**Comment by knolleary** [comment]
I'm going to close this; scrolling the pane doesn't invoke any node-red code - it's all the browser's doing.
