### ISSUE TITLE
Add output to file node

### ISSUE THREAD

**Issue by NicSil** [node-red/node-red#510]
file node (that writes a file) should have an output(simple node.send(msg)) to allow the flow to continue after the file is written.

**Comment by TotallyInformation** [comment]
I can see a benefit from knowing if the write worked or failed? But I think that could also be handled by using the Watch node type?

**Comment by knolleary** [comment]
We're about to think about approaches to have more generic ways to catch errors that nodes throw that would otherwise halt a flow. This would apply just as much to nodes that otherwise end a flow. Hopefully have some more concrete thoughts next week.

**Comment by knolleary** [comment]
We have now added the Catch node that can be used to handle any errors raised by certain nodes - including the File node. This satisfies one set of use cases for having an output on the File Out node.

We're constantly trying to keep a balance between keeping things simple to use and ensuring the right amount of functionality is exposed. All of our Output nodes could arguably have an output so the flows can continue... but that isn't a design approach we've chosen to take.

As some of the other commenter on this thread have said, there are alternative approaches available.

**Comment by jotadepicas** [comment]
Hi everyone,
I'm facing a similar need her. I want a node to save an ogg file downloaded from Telegram API, and the a subsequent node to decode it (ie. execute a decode command AFTER the file was saved). 

So, how could this be achieved in node red? Is there a node that can wait for a file to exist? Or should I simply put a delay node before trying to decode the file, so I give it time to be written (not very elegant).

Thanks!

**Comment by dceejay** [comment]
Look at the watch node. It reports changes to a file or directory.

**Comment by jotadepicas** [comment]
@dceejay yes, thank you for your response. But the thing is, this flow originates on an http request (telegram, but it could be anything), so I would need to do it within that flow, to produce the http response. If I do it with the watch node in another flow, I cannot produce a response to the http request. I need to wait for it or sync it somehow in the http flow, similar to what @NicSil and @nisjunk mentioned.

**Comment by dceejay** [comment]
You can use context.global.{something} to store objects in that are accessible globally (in another flow) - so can either use that to release the response... or pass the response object from one to another.

**Comment by thechane** [comment]
You can use the watcher node as previously suggested and then merge the two contexts so that you have both the file payload (or whatever) as well as the msg.req and msg.res. 

More info on this technique here - http://flows.nodered.org/flow/8ba7f90f3ea8d92b1e01

**Comment by dvv** [comment]
0. To dump payload to a file and further pass a filename to the tool expecting existing file is a common pattern.
1. WriteStream emits `"finish"` event when write is done, why not to use it for `node.send(msg);` to the output? Write is async, `node.send` is exactly suited for async message passing, no need to wait for completion.
2. Otherwise, watcher node info reads: `Note: The directory or file must exist in order to be watched.`
I wonder how then to watch for a non-yet-existing file? May we have a real copy-pasteable example flow for the technique mentioned by @dceejay and others?
TIA
