### ISSUE TITLE
Subflow - credentials not stored correctly

### ISSUE THREAD

**Issue by madeddie** [node-red/node-red#513]
When using a node that stores credentials within a subflow, its credentials aren't stored correctly.

To reproduce:

1) create subflow
2) enter subflow edit and add NMA node
3) edit NMA node and add API key
- the flow credentials file now contains the right json entry with api key

4) press deploy
- the json entry with api key has disappeared from the credentials file

On a related note, when I keep the subflow tab open and edit the credential field, the deploy button doesn't become pushable (red).

**Comment by knolleary** [comment]
Fixed by #533
