### ISSUE TITLE
Info tab for connectors

### ISSUE THREAD

**Issue by gillerman** [node-red/node-red#527]
It is possible to select a connector in the workspace, but the info tab is blank if you do.  Would it be possible to add metadata for connectors such as a type name?  Connector type names could be optionally displayed in the workspace.

**Comment by knolleary** [comment]
By 'connector' I assume you mean the wire between two nodes?

Wires don't have any properties that can be displayed.

What is your use case for adding metadata to links?
You mention adding type information, could you expand on that with an example?

**Comment by gillerman** [comment]
Yes, I am referring to the wire between nodes.  So that you can better document flows.

**Comment by dceejay** [comment]
Connections are just that - just a link between two nodes. As such they don't have any type or metadata - so there is nothing to display or document. All the connection information is exported when you export a group of nodes. Select several nodes then  - ctrl-e

**Comment by TotallyInformation** [comment]
There is a suggestion in the newsgroup regarding the possibility of adding additional metadata to the outputs of a node that I think would probably meet this requirement. Adding a name and possibly a description that would show up when hovering I think was the idea. Probably not much more effort to extend that to showing in the info tab when the connector is selected? So the metadata is still within the source node and not attached to the connector at all.

**Comment by emiloberg** [comment]
Related issue: Linking issues is also suggested (except from me in the News Group) in issue #46

**Comment by knolleary** [comment]
We continue to have no plans to add additional meta-data to the links between nodes. As noted, we do now support labels being added to the individual ports of a node.

I'm going to close this item as there's no prospect of us doing anything with it.
