### ISSUE TITLE
[0.9.1] IRC connection sharing problems between "IRC in" and "IRC out" nodes

### ISSUE THREAD

**Issue by stephanel** [node-red/node-red#534]
In version 0.9.1, when building an IRC bot that responds to commands (for example), adding an "IRC In" node first and then an "IRC Out" node does not work : after deployment, the command line output is stuck on "connecting to <irc server address>" and crashes after 30 seconds.

However, if I add an "IRC Out" node first and then an "IRC In" node, the connection works ("<nickname> ONLINE").

**Comment by stephanel** [comment]
Duplicate of #362

**Comment by dceejay** [comment]
Is this the released 0.9.1 or the master version on github ? There have been several fixes since 0.9.1 release. Is there a particular irc server to test against ?

**Comment by stephanel** [comment]
This is the released 0.9.1 archive downloaded from the website. I'm using
irc.freenode.net in my graph.
I'll test the master version tomorrow to see if the issue is still present.

2015-01-15 20:37 GMT+01:00 Dave Conway-Jones <notifications@github.com>:

**Comment by dceejay** [comment]
Hi @stephanel . Any update on this issue ?
