### ISSUE TITLE
Node-red-node encoding / charset issue

### ISSUE THREAD

**Issue by firsttris** [node-red/node-red#535]
Hello,

i'm currently creating a node-red-node and im facing a problem with charset/encoding from client to server.

I want to read "commands" from a input field - create a binary buffer from the provided value - and send it via tcp.

if im doing this server-side everything works perfectly
var command = "/x22/x23/x33";
var buffer = new buffer(command);
msg.payload = buffer;
debug output: buffer(222333)

but if im getting the value from the client (input field):
var command = node.command;
var buffer = new buffer(command);
msg.payload = buffer;
debug output: buffer(87987987987974654987);
=> im getting a total different value in the buffer

both commands are exactly the same string..
is this because of charset encoding?  (i have read the browser uses windows-1250 while nodejs uses utf8)
.
What can i do to overcome this issue?

regards
Tristan

**Comment by knolleary** [comment]
Hi,

the text entered into a input field within the browser does not handle escaped characters such as the `\x22`. Instead you get the literal string entered into the field.

This means the `\x22` which normally gets interpreted as the binary value `22`, when entered via an input field gets treated as the series of characters: `\` `x` `2` `2`.

Our Serial node faced this issue - where we allow the user to specify what character sequence to split input on. For example `\n` for newlines. We had to unescape these sequences in the runtime side so they get handled properly - https://github.com/node-red/node-red/blob/master/nodes/core/io/25-serial.js#L56

As this is not a node-red issue, I'm going to close this issue. Happy to continue the discussion here, but taking it off the 'open' issue list.

**Comment by firsttris** [comment]
Hey Nick,

really appreciate your reply.

i got your point, my understandig is now:
- \x -> special javascript literal for escaping hexas. (only works in a javascript string)
- string received from input field is a series of characters

unfortunatley i have not found a way to replace or to split the characters to create a escaped hexa digit .e.g -> 22 (\x22}

What i tried:

Possible Input from User: #cc#23#33
node.command = node.command.replace(/#/g, "\\x"); 
console.log(node.command);

LOG => red-1 (out): \xcc\x23\x33

var buffer = new Buffer(node.command, 'binary');

DEBUG-OUT => (Buffer) 5c7863635c7832335c783333

(My expected result would be cc2333)

i think thats because i replace with \\x not \x (so i explicitly say its not the hexa escaper)

if i try:
replace(/#/g, "\x"); 
i get: SyntaxError: malformed hexadecimal character escape sequence


furthermore its not possible to split the string at each "#" and do something like:

"\x"+str1+"\x"+str2+"\x" => javascript error.

any further ideas?

**Comment by firsttris** [comment]
Hi,

thanks for your reply, really appreciate your help.

you gave me the correct path.. i found an elegant way to overcome it:

                                var cmds = [];
				var input = node.custom.split(" ");
				var index;
				for (index = 0; index < input.length; ++index) {
					var value = "0x" + input[index];
					cmds.push(value);
				}
                                var buffer = new Buffer(cmds, 'hex');
regards
Tristan
