### ISSUE TITLE
Use of external libraries in the client-side html file

### ISSUE THREAD

**Issue by firsttris** [node-red/node-red#536]
Hello,

please close this issue because its no issue, i just want to ask a question since i found no other plattform or forum to do this. sorry.

im currentcly working on a node-red-node and i would like to use external jQuery or javaScript libraries in the clientside html file.

I managed it to use external libraries by copying their content into the html file.
![image](https://cloud.githubusercontent.com/assets/1709260/5788161/6f9968ec-9e27-11e4-9c1c-c2f078de13e1.png)

But the question is:
Is it possible to do external script inclusion?

```
<script src="js/customlib.js" type="text/javascript"></script>
<link rel="stylesheet" href="css/custom.css" type="text/css"/>
```

Regards
Tristan

**Comment by hardillb** [comment]
Have a look at. My geofence node for an example. 

https://github.com/hardillb/node-red-node-geofence

Rather than open issues you can ask questions like this on the mailing list:

https://groups.google.com/forum/#!forum/node-red

**Comment by firsttris** [comment]
perfectly thanks!

**Comment by adadgio** [comment]
Not really an answer... too bad ! What should we look at in the geofence node ?

**Comment by dceejay** [comment]
Line 188 onwards

**Comment by adadgio** [comment]
Cool ! Thanks. Though, i think this is even more simple... (in your geofence.js). Am I correct ?

RED.httpAdmin.get('/geofence/js/*', function(req, res){
        var options = {
            root: __dirname + '/static/',
            dotfiles: 'deny'
        };

        res.sendFile(req.params[0], options);

        // var filename = path.join(__dirname , 'static', req.params[0]);
        // res.sendfile(filename);
    });

**Comment by hardillb** [comment]
You need both, the route in the geofence.js file to serve up the files and the section @dceejay pointed at to actually load them into the editor

**Comment by adadgio** [comment]
Hm, it does not seem we need both. Trying it right now and it works just to include any JS library client side...
