### ISSUE TITLE
Page connectors

### ISSUE THREAD

**Issue by jbunyan** [node-red/node-red#538]
Anybody looked at creating a method to link connectors between pages? (or even on the same page to increase readability).

**Comment by knolleary** [comment]
Hi,

for general questions, please use the google group - https://groups.google.com/forum/#!forum/node-red

On this particular topic, it is on the todo list. I have a prototype lying around somewhere, but needs work on the UI side.

As this isn't an issue, I'm going to close it, but happy (in this instance) to continue the conversation here.

Nick
