### ISSUE TITLE
Logging of successful and unsuccessful login attempts

### ISSUE THREAD

**Issue by Humancell** [node-red/node-red#539]
In looking through my logs, I'm not seeing anyplace that Node-RED logs a successful login to the Web UI (e.g. User {name} logged in successfully from {ip address} or Failed login attempt from {ip address} by user {name})

This would be helpful information know, and also would allow the use of tools like fail2ban to lockout attacking addresses.

**Comment by knolleary** [comment]
Just for the record (to carry over the conversation from the google group), the work I'm doing at the moment is an overhaul of authentication for the admin side of things. This will include logging as requested here.
