### ISSUE TITLE
Add markdown support when rendering Comment node description in info sidebar

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#544]
The Comment node can be configured with a name and a description. The name is used as the label of the node. To see the description however, you have to open the node's edit dialog. That isn't very useful. It is also restricted to plain text.

The proposal is to:

 - make use of the new `.info` property of the node's definition to allow the comment node to contribute its content to the Info sidebar when the node is selected. We should remove the existing html help content.
 - add the [marked](https://github.com/chjj/marked) library so the content can be rendered as markdown

**Comment by TotallyInformation** [comment]
Good call on the library. Supports Github flavour by default which means that tables can be produced among other things.
It would probably be nice for newcomers to at least have a link to the Github Markdown syntax pages: https://help.github.com/articles/github-flavored-markdown/
Of course, even nicer to have some input buttons to insert some standard formats much as with the Stack Exchange sites. :) Maybe in v2?

**Comment by dceejay** [comment]
Added markdown capability to Comment node - via Commit 0ed8d28342853bb2454106e78a13c45713e301fe

Includes link to markdown help doc.
