### ISSUE TITLE
Make some of settings.js global settings available to nodes

### ISSUE THREAD

**Issue by zobalogh** [node-red/node-red#548]
I think making some of the global settings available to nodes (similarly to how nodes can have access to their ID and type) would be a useful feature.

An use case that I can think of for this is related to instrumentation. Currently if I would like to instrument a node with the new metrics system, I need to always set <code>node.metric</code>. However if I could tell if the metrics collection is disabled, I wouldn't bother configuring the object.

Thoughts?

**Comment by knolleary** [comment]
Nodes already have access to the global settings, for example: https://github.com/node-red/node-red/blob/master/nodes/core/core/58-debug.js#L20
