### ISSUE TITLE
UUID is not assigned when emitting a message to multiple nodes

### ISSUE THREAD

**Issue by vramdal** [node-red/node-red#551]
When a message is sent to a single node, it is assigned a UUID. From red/nodes/Node.js#99:

    if (!msg._messageUuid) {
       msg._messageUuid = constructUniqueIdentifier();
    }

However, when there are multiple output wires, line#144:

    if (msgs[k]._messageUuid === null) {
        msgs[k]._messageUuid = constructUniqueIdentifier();
    }

Unless I am mistaken, the condition `msgs[k]._messageUuid === null` is never true. Should this be `!msg._messageUuid` instead?

This bug causes the message to be logged with `msguuid == undefined`.

The message _is_ assigned a uuid upon `receive`, Node.js#168:

    if (!msg._messageUuid) {
        msg._messageUuid = constructUniqueIdentifier();
    }

However, at this point, the message has already been logged.

I have raised a pull request with a fix and testcase: #552 .

**Comment by knolleary** [comment]
Hi,

thanks for raising this.

This code is under active development at the moment (literally, I'm working on it right now) and subject to change.

As per our contribution guidelines, we cannot accept pull requests without a signed CLA in place. 

These two facts combined means, I'll make sure this gets fixed as part of the work I'm doing at the moment, but I won't be able to accept your PR.

Thanks,
Nick

**Comment by hbeeken** [comment]
I believe I've put a fix for this in the latest pull request for #546.
