### ISSUE TITLE
Dynamically change tag value for Twitter node

### ISSUE THREAD

**Issue by prakashtrivedi** [node-red/node-red#556]
Twitter node allows one to enter tags. Can it be changed dynamically may be from another flow? What I was thinking is have a flow that only pulls trending tags and then change the tags in main flow to get all tweets for the new tags. It would also be good to do the same in MongoDB node to change the collection name to the new tag.

Thank you,

**Comment by knolleary** [comment]
Hi,

the existing Twitter node is an Input node - it sits at the start of a flow and has to be preconfigured. That doesn't make it suitable for being reconfigured at runtime.

There is a separate piece of work looking at creating a twitter query node where the search terms can be configured at runtime - not sure when/where that will appear.

Nick

**Comment by JTLR** [comment]
@knolleary in the meantime, is it possible to query the twitter API from a function node to create the same result?
