### ISSUE TITLE
Required properties not validated in configation nodes

### ISSUE THREAD

**Issue by emiloberg** [node-red/node-red#557]
Configuration nodes (such as the _mqtt-broker_, _websocket-listener config node_, etc) which have required properties (`required: true`) are not validated. The input field itself gets the red `input-error`-class, but it's still possible to create a new configuration or save an already existing one.

**Comment by knolleary** [comment]
Right now, for both regular and config nodes, we don't stop the user from hitting 'okay' on the dialog even if there are validation errors.

In the case of regular nodes, we can display the warning triangle against the node to indicate the issue. We also warn on deploy that some nodes are not properly configured.

In the case of config nodes, they don't have a visual representation on the screen which can be used to highlight they have an error. Currently (not sure intentionally) we do not warn when deploying misconfigured config nodes.

So, the question is what can we do to improve this.

 - Warn-on-deploy would be a start, but with no visual indication as to what nodes have an error, it wouldn't help the user find the error.

 - the validation of a regular node should take into account the validation of any config nodes it is set to use. That would give somewhere on the workspace to highlight the error. It would mean any misconfigured config nodes that were unused would not get highlighted - but that feels okay as they are unused.

Any other suggestions?

**Comment by emiloberg** [comment]
Oh yeah, obviously I've seen the orange triangle but for some reason I didn't put two and two together.

Today a normal node which has a required config node bound to it will give a warning on deploy if the configuration is not set, this is a good balance.

Wouldn't the most straight forward way be to prevent the user from saving a configuration if it doesn't validate. That way it'll never be selectable in the normal node and the normal node will trigger a warning on deploy if the configuration select is not set. Similar, when editing a configuration node, prevent the user from saving it. Forcing the user to correct the non-validating fields or click cancel.

Off the top of my head, I can't really come to think of a use case where a user would want/need to save a non-validating.

**Comment by dceejay** [comment]
I quite often use not quite configured nodes. Either during development where I haven't actually got the credentials yet. Or if I don't want to actually run some part of a flow while working on another part. (Mainly twitter inputs it must be said). Or when I move a for from one device to another and that doesn't have a serial port for example but the rest of the low is OK.

The other one (which is more just the kind of user I am) is for demo use, where doing live demo in front of an audience its nice to have a for that "works" but I just want to show how the oauth works for example.

I could be forced to correct all of these I admit but it feels overly restrictive.

My 2c

**Comment by emiloberg** [comment]
Fair enough!

With my proposed solution you'd still be able to set the configuration in the normal node to "no config" (by selecting the _add new config-node-name..._, a blank option should maybe be added? But that's another question) in the normal node, as you can do today. Does this work for the needs described?

If I'm not missing anything, today there's two ways of doing what you're doing:

1. Remove values in the config node
2. Setting the normal node configuration to "none".

My suggestion will remove the number 1 way of doing it (as it will prevent a user from saving a non-validating configuration). Granted, the downside is that you'll always get the warning-on-deploy with the number 2 way whereas you won't get the warning with the number 1 way. But then - don't we want this warning?

**Comment by knolleary** [comment]
I've double checked our behaviour.

- If a node uses an invalid config-node, the node is marked as invalid. This triggers the warning on deploy and ensures there are the necessary visual cues as to where the error is.

- If an invalid config-node has no users, we do not currently warn on deploy - the reasoning being its an unused node so shouldn't matter it is invalid. As soon as it gets used, it will cause the user to marked as invalid.

- Before a recent commit, it was always assumed that if a node had a property linking it to a config-node, it required that config-node to be specified. It is now possible to mark the property as `required:false` so you don't have to provide a config-node for the node to be valid.

- If you edit a config node and make it invalid, we were only marking the node you were editing as invalid. As of a commit just pushed, we now revalidate all users of the config node. This ensures the valid flag is properly represented in the workspace.

As Dave says, on balance, we don't want to start preventing the user from saving an invalid config as there are valid reasons for wanting to do so. I don't think there is anything else for us to do here, so I'm going to close this issue.
