### ISSUE TITLE
Raspberry pi GPIO: Status of multiple nodes doesn't follow

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#559]
I have several instances of the same GPIO output pin across my flow, I noticed that if I set one instance to 1, the status of the other instances isn't updated.  Would be nice if it would follow !

Thanks.

**Comment by dceejay** [comment]
They are indeed separate instances - so don't actually know about each other - so they can't track each other. It only happens to work as they are both outputs - mixing types will lead to unpredictable behaviour - so I am actually going to try to warn on selecting the same pin twice.

**Comment by natcl** [comment]
When you say mix types is if I have both an input and output set on the same pin ?
I found having multiple instances is useful to avoid having wires everywhere in the patch (which is quite complex)
Perhaps having some sort of proxy object that would reflect a given object could help with this ?

**Comment by dceejay** [comment]
Yes - or an out and pwm , or two pwms. 
I'm afraid due to the use of the underlying python library each invocation sets the mode of operation of the pin independently - even if there was a proxy it would have to choose which mode to use.
