### ISSUE TITLE
Closing dialog by upper right hand X icon does not count as oneditcancel

### ISSUE THREAD

**Issue by emiloberg** [node-red/node-red#561]
We have two listeners for when a node dialog is closed available, the `oneditsave` and the `oneditcancel`. However, clicking the upper right hand (jQuery UI Dialog, `.ui-dialog-titlebar-close`) **X** _does not_ trigger the `oneditcancel` (or the save for that matter)

Example: 
The _twitter_ node clears a `setTimeout` when closed by save/cancel button. But the bugger keeps on going if closed by X button.

```
        oneditsave: function() {
            if (twitterConfigNodeIntervalId) {
                window.clearTimeout(twitterConfigNodeIntervalId);
            }
        },
        oneditcancel: function(adding) {
            if (twitterConfigNodeIntervalId) {
                window.clearTimeout(twitterConfigNodeIntervalId);
            }
        }
```

Verified in master from yesterday.

**Comment by knolleary** [comment]
Hi, thanks for pointing this out. Having discussed with @dceejay we decided to remove the X button. It isn't obvious to the user if clicking it cancels or saves - so to remove ambiguity, we've removed the button.

Also, spotted that oneditcancel was only being honoured for config nodes, not regular nodes (we've only had cause to use it with config nodes... but still...).

Thanks!

**Comment by emiloberg** [comment]
Fast going! Agree on removing the X.

Related to this, I _just_ realized that the Delete button on Config nodes does not have a listener assigned to it. Probably should have its own `ondelete` if people want to do magic when a config is removed. And/or a catch all `onunload`/`onclose`. The latter is suitable for both config and normal nodes and might be a good idea for things such as clearing intervals, closing connections etc.

**Comment by knolleary** [comment]
It isn't documented, but config nodes *can* define an `ondelete` function and it will get called at the right time. In fact, I now realise `oneditcancel` isn't [documented either](http://nodered.org/docs/creating-nodes/properties.html#custom-edit-behaviour).

Less sure about the catch-all - I think it'll be a relatively infrequent used function that can be easily achieved by a node calling a common function from both of their `oneditsave` and `oneditcancel` functions.

**Comment by emiloberg** [comment]
Oh, `ondelete` works like intended! Thanks!

As we have all three cases, there's no real need for a catch all. You're probably right about the infrequently thing. It looks like no core node uses the ondelete ;)

**Comment by knolleary** [comment]
@emiloberg  they used to before we added the credentials API.

**Comment by knolleary** [comment]
@emiloberg should we change it to `oneditdelete` to be consistent in naming... I think so. Will leave support for `ondelete` in place, but with a deprecation warning and will not otherwise document it.

**Comment by emiloberg** [comment]
Yup.

+ it makes it more clear as to when it will trigger. It's not when the node is deleted from  a sheet or anything else.
