### ISSUE TITLE
Bug prevents unsubscribing from WebSockets, browser side.

### ISSUE THREAD

**Issue by emiloberg** [node-red/node-red#562]
The (browser side) `RED.comms` object has a `unsubscribe` method (defined in `public/red/comms.js`). However, it's a bit mistyped which prevents us from unsubscribing from WebSocket events.

I'll send a PR in a jiffy.

Side note: Currently, the only out of the box node which uses the unsubscribe method is the debug node:
```
onpaletteremove: function() {
    RED.comms.unsubscribe("debug",this.handleDebugMessage);
    RED.sidebar.removeTab("debug");
    delete RED._debug;
},
```

**Comment by knolleary** [comment]
Thanks for this.

It is worth noting the server side doesn't currently honour subscribe/unsubscribe requests at all - we cheat and send all messages to all clients connected.

The only thing that sending the subscribe to the server triggers is it sending back any matching retained message. Unsubscribes don't do anything.

We will add support for the sub/unsub messages in the runtime at some point... although we dont currently have a overwhelming need for it.
