### ISSUE TITLE
Make Context a more widely available concept

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#567]
Currently within a Function node, the `context` variable can be used to store, in memory, values between invocations of the node. Equally, `context.global` can be used to access variables shared across all Function nodes.

There are occasions when it is useful to store a bit of state and refer to it elsewhere. Relying on Function nodes to do this is an over-complication when the common use cases involve getting/setting values.

If the concept of 'context' was more widely available, then we could remove the need to do this via Function nodes, as well as some other potentially interesting use cases.

The proposal is to update the Switch and Change nodes so that rather than assume you want to set a property of `msg`, provide a select box for the options:
 -  `msg` : default, referencing a property of the message passing through the node,
 - `context.global` the same object as the Function node already accesses,
 - `context.local`  (whose name I'm still trying to decide on) is a new context object that is scoped to the tab/subflow the nodes are on. This would also be available to the Function node.

The user still picks the property name beneath this option (ie `msg.payload` or `context.global.foo`).

This will allow flow routing (using the Switch node) based on some global property, rather than have to pass such a property around on every message in the flow.

We should also review any other nodes that would benefit from this being added - eg Template node.

**Comment by TotallyInformation** [comment]
+1 nice!

**Comment by garnold** [comment]
:+1: 

Semi-related, it would be nice to be able to support `require`s on the context without resorting to modifying `settings.js`, ie. move:

```
    functionGlobalContext: {
        net:require('net')
    },
```

... to some sort of node.

**Comment by dceejay** [comment]
Individual nodes can "require" whatever they need to work. The function node runs in a sandbox, and we don't really want to have it wide open so you can require anything inside it - otherwise it's not much of a sandbox :-) We want to make sure users know that they are allowing something potentially dangerous to occur rather than just allowing importing random functions from the web etc.

**Comment by garnold** [comment]
@dceejay That's what I originally thought, too, but I am getting this error:

```
node-red-0 (out): 31 Mar 08:28:12 - [error] [function:require('net')] ReferenceError: require is not defined (line 1, col 11)
```

... when attempting to `require('net')` within a function node with the following code:

```
var net = require('net');
return msg;
```

![](https://www.dropbox.com/s/l0n6xtbttqxja2l/Screenshot%202015-03-31%2009.28.29.png?dl=1)

**Comment by hardillb** [comment]
Yes, require will not work in the function node, you have to put the require in the settings.js and access the returned object via the context.

settings.js
```javascript
...
functionGlobalContext: {
            os:require('os')
},
...
```

function node:
```
context.global.os
```

**Comment by dceejay** [comment]
indeed - that won't work... as require is not available within the sandbox (on purpose).

**Comment by garnold** [comment]
Thanks @dceejay, hence my original request :)

**Comment by scargill** [comment]
Hi
As I start to understand nodes (only this morning fixing minor issues in my new scheduler (timer) node I'm immediately hitting this problem. I would like to store some values which are common to all nodes (current temperature in various rooms etc) and of course the context variable and global context variables that work so well in functions, are not available in the node js files. Is there any way this can be fixed. Adding this would not raise compatibility issues and would make life a lot easier.

**Comment by dceejay** [comment]
Nick, some clarification needed... is the proposal ?...
 -  only for the switch and change node  ? May also be useful for template and potentially others
 - for the switch node - are you thinking to allow context on both sides of the operator ? eg - if msg.payload >= context.global.foo ?

**Comment by knolleary** [comment]
The proposal is the title - "to make context a more widely available concept".

The switch and change nodes are ones that would be obvious candidates to expose context within - but the underlying api this will require can be used by any node. If other nodes would benefit from it, then they can be updated once the API is in place. I agree that Template is an obvious one to include in this.

Roughly speaking, anywhere you can reference a message property, you ought to be able to specify a context variable - so yes, both 'sides' of an operator.

**Comment by philippe-gregoire** [comment]
Sound good. For templates, there may be collisions since the implicit root of the namespace is 'msg'. Probably the logic could be if-not-found in msg, try context.local and then context.global, but there's the risk of unintentionally hiding properties.
Could the mustache syntax be extended to allow for e.g. {{*some_global}} ?

**Comment by philippe-gregoire** [comment]
BTW, there's a bit of an inconsistency as to what is the implicit root namespace in general.
For templates, it's msg (I understand the convenience of that). For functions, it's above. for change nodes, there's a mandatory msg. prefix for set, but for get you have to specify it explicitly....

**Comment by KamalAman** [comment]
+1 context.local would make reusing complex subflows which rely on configuration data a lot cleaner. Right now I'm using multiple function nodes placed at strategic positions cache the data specific to that instance of a subflow. 

Any plans of this making it into the next release?

**Comment by mfeblowitz** [comment]
+1 (at least 1) 
Soon? :)

**Comment by knolleary** [comment]
soon

**Comment by Cancelor** [comment]
Is there a current work around?
e.g. With a home lighting system, what is the preferred way to store it's current state in such a way that it can be restored after an unplanned power cut?

**Comment by TotallyInformation** [comment]
You can either use MQTT with the retained flag or a db such as MongoDB. You can also write to a simple file instead of a DB. I think that most people use MQTT.

Send your commands to a topic on MQTT with the retain flag set rather than direct to the lights. Have a separate flow that listens to the topic and sends the command to the output device. When you restart, the MQTT broker will send out a copy of the retained messages when NR subscribes to the topic. That will automatically send out the last command.

**Comment by TotallyInformation** [comment]
By the way, best to ask those questions in the Google group rather than here.

**Comment by knolleary** [comment]
Landed in 0.13

**Comment by erikvg01** [comment]
I'm failing to find documentation on context.global being supported in the template node.  Has this behavior been implemented?

**Comment by knolleary** [comment]
@erikvg01 you can set properties under context using the template node, but you cannot (currently) reference context properties within the template itself. You would need to use a Change node prior to the Template node to attach any context properties you want to use to the message object passing through.

At some point we'll enable referencing context properties in the Template.
