### ISSUE TITLE
option for a sub-flow to be stored in a separate flow file

### ISSUE THREAD

**Issue by adm94222** [node-red/node-red#570]
Liking the sub-flows concept - nice job
The ability to store a sub-flow in its own flow file seems like a good idea for managing more complex node-red deployments - particularly where you want the core (the sub-flows) maintained by one entity but used within flows adapted by others
Does go somewhat into the whole configuration management theme as well so you may have other plans
Rich

**Comment by knolleary** [comment]
Hi @adm94222 ,

Thanks for the feedback. As you suggest, this is one small aspect of a much bigger topic of flow management.

For example, there was a recently discussion on the [mailing list](https://groups.google.com/forum/#!forum/node-red) around storing Function node config in their own file so they could be maintained outside of node-red.

We don't want to start undermining the philosophy that the flow/credential files contain everything needed to run the flow. At least, not until we have properly thought through what specific scenarios and use-cases this sort of thing would enable.

We also have the library system built into the editor that allows you to import/export useful flows. That gives you a mechanism for saving subflows externally to the running flows - although that (purposefully) doesn't allow you to edit a subflow externally and have the update automatically apply to your running flow.

So, there's lots to consider in this area and I'm not sure having this issue open on one small aspect of it is going to be helpful.

If you have other suggestions, please do share them - but I would point you at the mailing list in the first instance. We try to keep the issue list as known bugs or feature enhancements that are in our roapmap.

Thanks,
Nick
