### ISSUE TITLE
Error starting node-red as a service

### ISSUE THREAD

**Issue by Javierete** [node-red/node-red#575]
Hello!

First, I'm new to nodejs and node-red. I had node-red 0.10.3 working correctly as a service (with forever + init.d script).
Tonight I've updated to 0.10.4 and the service script is throwing me an error:
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.localfilesystem.init (/root/node_modules/node-red/red/storage/localfilesystem.js:154:43)
    at Object.storageModuleInterface.init (/root/node_modules/node-red/red/storage/index.js:51:34)
    at Object.start (/root/node_modules/node-red/red/server.js:53:13)
    at Object.<anonymous> (/root/node_modules/node-red/red.js:201:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I dig into the red.js file and see where is failing, I've tried to specify a config file on different location (-s argument) but no joy.
Please excuse me if this isn't related to node-red, simply trying to contribute with my 2 cents...

**Comment by knolleary** [comment]
Thanks for raising this.

To help identify what is going wrong we need a bit more information.


How exactly are you running node-red? How have you installed it and what command are you using to run it?

**Comment by knolleary** [comment]
I think I've spotted the issue.

The root user doesn't have $HOME set.

The workaround is to add the --userDir option to node-red so you have explicitly set the directory it should use to store flows.

Based on the output you provided, I think you should run with:

    red.js --userDir /root/node_modules/node-red

But check that directory is where for flows files and .config.json files are.

Will sort out a proper fix later this morning.

**Comment by Javierete** [comment]
Hello @knolleary 
I will test it this later this morning. BTW I'll paste my init.d script based on: 
https://www.exratione.com/2013/02/nodejs-and-forever-as-a-service-simple-upstart-and-init-scripts-for-ubuntu/

#!/bin/bash
NAME="Node-Red"
NODE_BIN_DIR="/usr/lib/"
NODE_PATH="/usr/lib/node_modules"
APPLICATION_PATH="/root/node_modules/node-red/red.js -s /root/noderedsettings.js"   // <-- Here I tested many settings / locations
PIDFILE="/var/run/node-red.pid"
LOGFILE="/var/log/node-red.log"
MIN_UPTIME="5000"
SPIN_SLEEP_TIME="2000"

PATH=$NODE_BIN_DIR:$PATH
export NODE_PATH=$NODE_PATH

start() {
forever \
      --pidFile $PIDFILE \
      -a \
      -l $LOGFILE \
      --minUptime $MIN_UPTIME \
      --spinSleepTime $SPIN_SLEEP_TIME \
      start $APPLICATION_PATH 2>&1 > /dev/null &
    RETVAL=$?
}
stop() {
    if [ -f $PIDFILE ]; then
        echo "Shutting down $NAME"
        # Tell Forever to stop the process.
        forever stop $APPLICATION_PATH 2>&1 > /dev/null
        # Get rid of the pidfile, since Forever won't do that.
        rm -f $PIDFILE
        RETVAL=$?
    else
        echo "$NAME is not running."
        RETVAL=0
    fi
}
 
restart() {
    stop
    start
}

status() {
    echo `forever list` | grep -q "$APPLICATION_PATH"
    if [ "$?" -eq "0" ]; then
        echo "$NAME is running."
        RETVAL=0
    else
        echo "$NAME is not running."
        RETVAL=3
    fi
}
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL

Best regards

**Comment by knolleary** [comment]
Thanks for sharing.

If you add "--userDir /root/node_modules/node-red/" to APPLICATION_PATH you should be running again.

**Comment by Javierete** [comment]
Hello @knolleary 

I'm now at computer and tested your suggestion and I confirm you It now works.
Instead of root I've installed globally and use the --userDir argument.

Thank you so much and best regards
