### ISSUE TITLE
Cannot install with npm..

### ISSUE THREAD

**Issue by elmor34** [node-red/node-red#579]
I 'm using OSX 10.10 and when try to install get the following messages :
Versions : current: {"node":"0.12.0","npm":"2.5.1"})

any idea?

Regards..

Log file is at the end

sudo npm install -g node-red
Password:

npm WARN engine node-red@0.10.4: wanted: {"node":">=0.8 <0.12"} (current: {"node":"0.12.0","npm":"2.5.1"})
 
> node-icu-charset-detector@0.0.7 install /usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/gokhanaykan/.node-gyp/0.12.0'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing node-icu-charset-detector@0.0.7
 
> bufferutil@1.0.1 install /usr/local/lib/node_modules/node-red/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/gokhanaykan/.node-gyp/0.12.0'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
 
> utf-8-validate@1.0.1 install /usr/local/lib/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/gokhanaykan/.node-gyp/0.12.0'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
 
> iconv@2.1.6 install /usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/iconv
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/gokhanaykan/.node-gyp/0.12.0'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/iconv
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> serialport@1.4.10 install /usr/local/lib/node_modules/node-red/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Command failed: /usr/local/bin/node --eval require('/usr/local/lib/node_modules/node-red/node_modules/serialport/build/serialport/v1.4.10/Release/node-v14-darwin-x64/serialport.node')
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/node-red/node_modules/serialport/build/serialport/v1.4.10/Release/node-v14-darwin-x64/serialport.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/node-red/node_modules/serialport/build/serialport/v1.4.10/Release/node-v14-darwin-x64/serialport.node
  Expected in: dynamic lookup

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile 
child_process: customFds option is deprecated, use stdio instead.
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/gokhanaykan/.node-gyp/0.12.0'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=serialport" "--configuration=Release" "--module_name=serialport" "--version=1.4.10" "--major=1" "--minor=4" "--patch=10" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./serialport" "--host=https://node-serialport.s3.amazonaws.com/" "--module_path=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/serialport/v1.4.10/Release/node-v14-darwin-x64" "--remote_path=./serialport/v1.4.10/Release/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/serialport/v1.4.10/Release/node-v14-darwin-x64.tar.gz" "--hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/" "--hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/serialport
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.4.10 --major=1 --minor=4 --patch=10 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/serialport/v1.4.10/Release/node-v14-darwin-x64 --remote_path=./serialport/v1.4.10/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/serialport/v1.4.10/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/node-red/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/serialport
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.4.10 --major=1 --minor=4 --patch=10 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/node-red/node_modules/serialport/build/serialport/v1.4.10/Release/node-v14-darwin-x64 --remote_path=./serialport/v1.4.10/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/serialport/v1.4.10/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.4.10/Release/node-v14-darwin-x64.tar.gz' (1)
npm WARN optional dep failed, continuing iconv@2.1.6
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "node-red"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.4.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.4.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gokhanaykan/npm-debug.log
Gokhans-MacBook-Pro-2:~ gokhanaykan$

**Comment by dceejay** [comment]
Currently we do NOT support node v.0.12.0. Please use node .v0.10.36 ax per the install instructions.

**Comment by elmor34** [comment]
Thanks for  prompt response..

Regards..
Gokhan

On Fri, Mar 6, 2015 at 9:07 AM, Dave Conway-Jones <notifications@github.com>
wrote:

> Currently we do NOT support node v.0.12.0. Please use node .v0.10.36 ax
> per the install instructions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-red/node-red/issues/579#issuecomment-77516349>.
>



-- 
Gokhan AYKAN

**Comment by dceejay** [comment]
Closing as already covered by Issue #565
