### ISSUE TITLE
Subflow name edition

### ISSUE THREAD

**Issue by Belphemur** [node-red/node-red#581]
Hello,

A little bug I discover when working with subflow. 
When editing the name of the flow in the subflow's creation tab, if you use the enter key to validate instead of clicking the OK button, you are redirected to the starting page and all your un-deployed changes are lost.

**Comment by Belphemur** [comment]
Should be closed by : 7bdb3181e2d6d349d3123f36319ac64c60d5c67e

**Comment by knolleary** [comment]
oh yes - forgot to tag it with the issue number.
