### ISSUE TITLE
Adding Subflow ports

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#584]
When editing a subflow I keep trying to drag on an output (or input) node from the top bar - rather than just click - and get a confusing (non-fatal) message about dropping flows . As we drag from the nodes on the palette the confusion is almost bound to happen. Can drag on be supported as well as click ?

**Comment by mblackstock** [comment]
Found this same behaviour when I was creating a sub flow and tried dragging the '+ input' button into the main pane.  I see a gray box dragged in with a URL in it tracked with the item appearing in the main pane. When I release the item, I get an error notification that says "Error: Invalid flow: Unexpected token h".

**Comment by knolleary** [comment]
The 0.11 (iirc) release tweaked the UI for adding/removing ports - hopefully should be more intuitive as buttons, not drag/n/drop.
