### ISSUE TITLE
partial deploys don't put a message on the console

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#588]
full deploy says stopping flows then starting flows.
I think it would be good for the partial redeploy options to put something on the console as well, just so it's "provable" that the message got there from the UI and that it was processed.

**Comment by knolleary** [comment]
Already done - will be in next release:

    13 Mar 10:28:41 - [info] Started modified nodes

or

    13 Mar 10:29:26 - [info] Started modified flows
