### ISSUE TITLE
Error: Serialport not open -  more details 

### ISSUE THREAD

**Issue by industrialinternet** [node-red/node-red#589]
I have a project with multiple serial ports and need to identify which is erroring
Error: Serialport /dev/ttyUSB0 not open.  
Would do the job.

Thanks

**Comment by dceejay** [comment]
Hi Lawrence,
sorry - we're going to nee a bit more detail. Currently we do report an error -
[error] serial port /dev/ttyUSB1 error Error: Cannot open /dev/ttyUSB1
for any error condition reported from the underlying package.
and we report
[info] serial port /dev/ttyUSB0 opened at 4800 baud 8N1
on success...
the /dev/ttyUSB0 is whatever you set in the serial port config - what that corresponds to hardware wise on your PC/Micro/device is down to how it allocates names to ports. 
So what is it you need ?

**Comment by industrialinternet** [comment]
Dave sorry about the brevity of request.
Main issue is when you have connected to a serial port and for some reason it goes away.
You get the msg: Error: Serialport not open.
I have one function handling 2 ports maybe I need to split code to handle ports separately.

**Comment by dceejay** [comment]
Is this for writes ? or reads ?
If I just unplug (the replug) a USB serial port I get
16 Mar 13:30:31 - [info] serial port /dev/ttyUSB0 opened at 2400 baud 8N1
16 Mar 13:30:52 - [error] serial port /dev/ttyUSB0 gone away
16 Mar 13:30:52 - [error] serial port /dev/ttyUSB0 closed unexpectedly
16 Mar 13:31:07 - [info] serial port /dev/ttyUSB0 opened at 2400 baud 8N1

**Comment by dceejay** [comment]
OK - got it... fix in progress

**Comment by industrialinternet** [comment]
Dave many thanks the issue is mine really. I'm not trapping the disconnects which I should be & then go and do a write....

**Comment by dceejay** [comment]
well - is an easy fix - and we are currently enhancing a load of the error things anyway (to work with the new catch node) - so will be swept into that.... probably later today.

**Comment by industrialinternet** [comment]
Thanks again.

**Comment by dceejay** [comment]
closed by commit be61cf6a885e3a93c1bc19fda8dd1f87cc7ad6da
