### ISSUE TITLE
file node reads from wrong file, when using more than one file node in the same flow

### ISSUE THREAD

**Issue by jotadepicas** [node-red/node-red#590]
Hi guys,
I think I found a bug related to [this issue](https://github.com/node-red/node-red/issues/399).
The same thing happened to me, but I'm not setting the msg.filename property in any way.

What I'm actually doing is using two or more file nodes to read from different files, and it seems that, internally, the msg.filename property is being set, causing an unwanted side effect.

I had to set msg.filename to null before every file read, in order to do it reliably. 

I think the issue 339 mentioned before refers to the scenario where the user is setting the msg.filename property, but like I said, I'm not doing that, I think the nodes are doing it and it doesn't seem right that the user should have to set it to null every time, just to prevent this.

what do you think? thanks!
-Juan

**Comment by knolleary** [comment]
Hi,

Yes thus

**Comment by knolleary** [comment]
Yes, this is exactly the sort of confusing side effect that #399 refers to.

Overriding the node property by the node has been deprecated and the behaviour will be removed in the next release.

Once it has been removed, this will no longer be an issue.

As this is covered by #399, closing this issue.

**Comment by jotadepicas** [comment]
Hi Nick,
I posted this issue because I am not setting the msg.filename property myself, I think the file node is doing it on its own, an causes the side effect covered in 399. Just so you know. Thanks!
