### ISSUE TITLE
MQTT in won't connect to connector configured as localhost

### ISSUE THREAD

**Issue by mfeblowitz** [node-red/node-red#591]
When the ActiveMQ connector is configured as mqtt://localhost:1883, as recommended in http://activemq.apache.org/mqtt.html, the MQTT in node will only work on localhost, with localhost as the broker host. Not the hostname (even fully qualified) and not the host IP address. This effectively limits its use to the activemq host. If, however, the MQTT connector is configured using the host IP or hostname, MQTT in can be configured with other than localhost and thus used remotely from the ActiveMQ host. A workaround, but not a very portable broker host specification.

Not sure if this is a bug or a feature, nor where the root cause might be.

**Comment by knolleary** [comment]
Hi, I'm not entirely clear what the issue is.

The MQTT config node allows you to specify a host and port that the broker is listening on - which is all you need.

Are you saying you would like it to also support providing this information as a single mqtt://host:port style uri?

**Comment by mfeblowitz** [comment]
No. I'm not asking at all for a different way to configure the MQTT node red node. The way it's currently done is just fine. 

 What I'm saying is that I have found that when I configure an activemq server "connection" specification for mqtt, in the activemq configuration file, and if I do so using "localhost", then when I configure the node-RED mqtt node using an IP address (since node-RED is running on a different host) the node-RED MQTT node won't connect to the remote MQTT activemq connector. 

If, however, I specify a host IP address (rather than "localhost") for the connector in the activemq configure, the MQTT node does connect. 

So, while that's not optimal it is a work-around. 

Now that I have the node red MQTT node connected, I'm  not seeing the activemq messages at all. Not with a debug node nor with a function node that writes to the console. Any suggestions as to how to debug?

Thanks

**Comment by knolleary** [comment]
Typically, if you configure something to listen on localhost, it will only accept connections from localhost. So what you describe sounds like entirely expected behaviour - and not an issue with Node-RED.

Have you tried connecting another MQTT client to verify the messages are being published as you expect? Have you verified the topic you are subscribed to is the one you expect messages to be on (you'd be amazed how often a typo in something as simple as that can lead to hours of fruitless debugging...)

**Comment by hardillb** [comment]
This sounds like your saying that when you tell activemq to only listen on localhost, it only listens on localhost.

If so then everything is working as expected. This really wouldn't be a node-red big, it wouldn't even be a activemq bug, except maybe a doc defect

**Comment by dceejay** [comment]
All the examples in their docs only mention localhost which isn't very useful if you need to allow external connections into the box.

**Comment by knolleary** [comment]
@mfeblowitz hi - any updates? This doesn't appear to be a node-red issue, rather a docs issue for the ActiveMQ connector. I'd like to close this off, but wanted to check where you had got to with your MQTT messages.

**Comment by mfeblowitz** [comment]
Sorry - busy week. Will work on in Monday.

**Comment by knolleary** [comment]
Hi @mfeblowitz, any update on this?

**Comment by mfeblowitz** [comment]
Hi, Nick - 
An ongoing saga. I just got a bit of time to dig into this and also into issues with using the stomp nodes.
You can ignore anything else you might have heard from me earlier :) Here's an update, with work in progress:

One major stumbling block with the mqtt nodes was to (eventually) recall that, regardless of what shows up on the console, topic names *are* case sensitive. Once that was sorted, I was able to make progress... to a point. 

The good part was that the nodes showed connectivity, and the activemq console reflected some activity due to the presence of the nodes. mqtt-in, when connected, showed up as a connection for the <topic_name> entry in the amq console, and dequeque counts reflected receipt to the mqtt-in node. But no data got through. Similarly with the mqtt-out node, I can publish to the server and there is evidence in the log that something was seen, but again, nothing made progress beyond that.

What I eventually discovered, by inspecting various debug logs, is message format incompatibility:  our java activemq subscribers are configured to expect/post messages in JMS TextMessage formats, not the JMS ByteMessage formats that the mqtt nodes produce and expect. I've seen evidence of this on the publish side and assume the same to be true on the subscribe side, although I've not net confirmed that. 

One option for the format incompatibility might be to extend the mqtt nodes to include a message format selector. Failing that, and as JMS TextMessage format is a project requirement, our local amq  person has recommended that I switch to node-red-node-stomp. Ok.

Before going there, I wanted to mention that halting node-red appears not to disconnect mqtt subscriber nodes; the activemq console <topic_name> connections count  does not decrease, and it increases upon a new node-red startup (and node connection). Is this as expected?

So, on to the stomp alternative. I have replaced the mqtt-in and -out nodes with the equivalent stomp nodes. So far, this situation is worse. The nodes appear to connect (green indicators) and, upon connection the amq console reports 2 enqueued messages for ActiveMQ.Advisory.Connection and 1 for ActiveMQ.Advisory.Consumer.Queue.<topic_name>, but no enqueued messages for ActiveMQ.Advisory.Consumer.Topic.<topic_name> (as there are when I start up my java amq publishers and subscribers). More concerning is that there is no increase in the number of consumers for  the <topic_name> entry, as there was with mqtt. Also, save for an increase in ActiveMQ.Advisory.Connection count, I see no evidence at all of messages being received.

My next task is to break open the trace=true logs for the stomp connector, to look for evidence of why nothing is happening.

I'll let you know, and would appreciate any guidance.

Thanks,
Mark

**Comment by knolleary** [comment]
Hi @mfeblowitz - thanks for the update. The fact MQTT messages appear as JMS BytesMessage in ActiveMQ is a feature/choice/issue/facility of ActiveMQ's MQTT support.

MQTT itself does not share the concept of payload types - its just a bucket of bytes; which means there is nothing we could do in the MQTT nodes to influence how they appear in ActiveMQ. There might be an option in ActiveMQ to customise this, but I'm not that familiar with it.

As for the node-red-node-stomp nodes - not used them myself. Maybe @dceejay has?

**Comment by dceejay** [comment]
Hi Mike,

at risk of "jumping in" too deep. The MQTT nodes try to do the sensible thing. Inbound it inspects the payload - if it only contains UTF-8 characters it returns a string otherwise a binary buffer. Outbound if you send a string then it should be a string - and if you send a buffer it sends the raw bytes.
So - if you think you are sending text into Node-RED - what does the debug node show ? (It should report the type) - and if it's a buffer then try putting it through  a function 
    msg.payload = msg.payload.toString(); return msg;
to try to reformat it...
Going the other way - if you are sending a text string payload (eg from an inject node) then I suspect there's not much we can do our side - as they are simple UTF8 - it must be an ActiveMQ setting/option as Nick says.

Re Stomp - they were developed in conjunction with this live service - http://nrodwiki.rockshore.net/index.php/Connecting_with_Stomp - but may well have missing capability. The library we are using is https://www.npmjs.com/package/stomp-client - Are there any connection options there that may help ?

**Comment by mfeblowitz** [comment]
Ok - so the real problem with using the mqtt node not the node but the [mqtt connector in activemq](http://activemq.apache.org/mqtt.html):

>**Message transformations**
> MQTT messages are transformed into an JMS ByteMessage. Conversely, the body of any JMS Message is converted to a byte buffer to be the payload of an MQTT message.

So I'd have to come up with another connector that doesn't transform to ByteMessage format.

But that still doesn't explain the behaviour of the subscription node. If it is as you suggest, the mqtt-in node should deliver something that's viewable using the debug node. Not seeing that, I have to assume that there *is* something deeper going wrong. So my next step has to be to turn on trace and dig into the logs. 

The same for the stomp nodes.

Thanks,
**Mark** :)

**Comment by dceejay** [comment]
Hi Mark,

so what kind of thing are you seeing in the debug node ? - If I just send "Hello World" as a Buffer I get
[msg.payload] : buffer
48656c6c6f20576f726c64

**Comment by mfeblowitz** [comment]
Ok - I'm abandoning mqtt, as I don't think it's going to work out for me. The problem is not a node issue, bur a problem with the activemq mqtt connector, as described above.

I might return to this issue again if I can't get to a satisfactory solution with stomp (which is looking better).

My first issue with stomp is now appropriately shifted to #617.
