### ISSUE TITLE
inject nodes do not work into a subflow

### ISSUE THREAD

**Issue by jotadepicas** [node-red/node-red#592]
Hi,
it seems that in the lastest v0.10.4, inject nodes cannot be deployed into a subflow.
The deployment itself does not throw any errors, but if you then try to click it to actually perform the inject, it says "Error: inject node not deployed".
Thanks!
-Juan

**Comment by knolleary** [comment]
Hi,

this is a limitation of subflows. When you are editing a subflow, you are editing the template for the flow, not a specific instance. When you click on the Inject button in that view, it doesn't not which instance you want to trigger.

You can have Inject nodes in a subflow to make use of their scheduling/repeating feature.

The resolution to this issue will be to disable the Inject button when viewing a subflow and make this clearer.

**Comment by hreimer** [comment]
Hi, i'm not sure if this is a different issue, it seems to deal with a very similar problem: [debug nodes action disabled in subflow](https://groups.google.com/forum/#!topic/node-red/3spyAphPf7U) - is this part of the design? It would be comfortable to be able to use the debug node the same way as in the normal flow.

**Comment by vertex-github** [comment]
That's really unhelpful though - since the only way to group/organize the more complex / repetitive stuff is with subflows, but then when I view it, I cant debug it / inject stuff.  Could we list the various instances and ask the user which specific instance we would want to inject in to?

**Comment by ckhmer1** [comment]
I created a subflow just to grouping the setup for some behavior, for example, the Google smart home integration. I have just one instance of the subflow, why I cannot use the debug node inside the single instance of it?
