### ISSUE TITLE
Feature request: allowing more fields to be "uncloned" in addition to req and res

### ISSUE THREAD

**Issue by ozomer** [node-red/node-red#593]
The current implementation clones the messages between the nodes, except for the req and res fields.
In some scenarios I need the message to contain a "reference" to an external object, which is not a part of the message.
Obviously, if some node modifies the external object, it will be modified across all messages that have a reference to it.
My suggestion is to have an optional object in msg.references, and that the values of this object will not be cloned.

Maybe msg.req and msg.res should be replaced in the future with msg.references.req and msg.references.res (might raise backward-compatability issues).

Thanks!

P.S. I am new to node-red, if a similar feature already exists please let me know.

**Comment by knolleary** [comment]
Hi, as per our contributing guidelines, feature requests should be discussed on the mailing list first.

As you've already cross posted this in both places, I'm going to close this issue whilst it is discussed on the list.
