### ISSUE TITLE
First time Raspberry Pi install fails to save flows; a workaround

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#594]
Following the instructions at http://nodered.org/docs/hardware/raspberrypi.html -

I got Node-RED running on a new Pi, but the first flow I created failed to deploy properly. The "Deploy" box in the upper right of the screen stayed red after I hit the button. It was a simple flow (just an inject connected to a debug), but it wouldn't save.

I was able to get it to work by creating an empty flows.json file, namely

```
cd ~/.node-red
touch flows_machinename.json
```

and then it worked fine. 

When I tried to replicate this process, I wasn't able to trigger the bug again; there is a line logged

```
[info] Creating new flows file
```

which can be found in red/storage/localfilesystem.js that looks like it's doing the right thing.

**Comment by knolleary** [comment]
Hi,

did you capture the console output for when it wouldn't save? That would hopefully give some indication as to why it failed to create the file. My guess would be a permissions issue - if .node-red got created by root for some reason, and then you run as a regular user.

**Comment by vielmetti** [comment]
I didn't catch the console output on the first try-and-fail, but I'll be doing another install shortly and will watch for same.

**Comment by knolleary** [comment]
Hi, did you ever manage to recreate this?

**Comment by vielmetti** [comment]
I have a system that I can do a fresh install on and will add this to my checklist for when I do that.

**Comment by ArgonLaser** [comment]
Just had this happen on a fresh pi install.  Your fix worked, thank you.

**Comment by knolleary** [comment]
Not had any further reports of this - not sure if there's anything to be done now. Going to close, but we can always reopen if needed.
