### ISSUE TITLE
Subflow status

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#597]
Nodes can report their status which gets reported in the editor beneath each node.

It should be possible to publish status for a subflow instance node.

The proposal is to add a subflow-specific status node, in a simliar style to the subflow input/output nodes, that can be wired into a flow to publish status for the subflow.

This would allow custom status message to be provided.

What it doesn't handle is propagating the status of nodes within the subflow to the subflow node. Need to decide if that is desirable, and if so, how it can be done. Should it be selective or cover all nodes? Should it be an option that can be toggled on/off.

**Comment by macedolfm** [comment]
Hi @knolleary, I support this enhancement, any node.status propagation would be great, the finer the control, the better.

**Comment by amir-arad** [comment]
regarding propagating the status of nodes, I think that hoisting statuses and configurations to nodes I/O level (meaning, node status change can be wired like an output, and node configuration like an input) can be a dangerously powerful thing.

**Comment by sandro-k** [comment]
Is this already implemented?

**Comment by knolleary** [comment]
@sandro-k the issue is still open

**Comment by sascha1337** [comment]
Any plans to implement this soon ?

**Comment by knolleary** [comment]
It is not in the current plan, no.

**Comment by niemyjski** [comment]
I could really really use this. It's really hard to see what sub flows are doing and to debug them..

**Comment by knolleary** [comment]
Hi @niemyjski  - as you can see in the issue description, there are a number of open questions about how exactly we'd do this. If you have any feedback on what sort of capabilities you'd like, it would certainly help.

**Comment by niemyjski** [comment]
Yes! I think sub flows (templates) are a great idea but fail pretty quickly when used in a flow. We lose status and debugging. What if the subflow had a unique id as well as the subflow (template id). Then you could do quite a few things like:

1. You could get the status of a subflow by the unique id of that instance, maybe even show that subflow in a popover or click into).
2. You could also easily create a subflow inside of a subflow and debug it because you'd be able to flow through this id.

I just want to be able to see status of a subflow node and when there is an issue I want to see what the subflow is doing..

**Comment by niemyjski** [comment]
Also, I'd love if flow state flowed through a subflow. This seems like a huge limitation and causes me to use extra function nodes to inject the state that's already stored in flow variables. Perhaps we could could introduce a new scope for flows called parent scope (which would merge all the parent flow scopes together)?

**Comment by SamJongenelen** [comment]
> I just want to be able to see status of a subflow node and when there is an issue I want to see what the subflow is doing..

I second this. I understand the problem but a simple visual solution/workaround would be very welcome

**Comment by knolleary** [comment]
In 0.20 the following will be true of subflows (much of this is already true in 0.19)

 - Any node inside a subflow can emit a status event
 - A Status node set to target all nodes that is on the same flow as the subflow instance node will receive that event from inside the subflow
 - (New in 0.20) A Status node set to target just the subflow instance will receive that event.
 - If the subflow contains a Status node, it will receive the event but it will not propagate outside of the subflow

The major new feature I've now pushed to the `dev` branch for 0.20 is a new subflow-status node:

<img width="499" alt="local_node-red" src="https://user-images.githubusercontent.com/51083/52156023-b0c55280-267d-11e9-87cc-18d4e259f392.png">

This can be toggled on and off inside the subflow template and appears like one of the subflow output ports. Any message passed to it will be emitted as a status event *of the subflow instance node*:

<img width="343" alt="local_node-red" src="https://user-images.githubusercontent.com/51083/52156113-292c1380-267e-11e9-8208-335814a63595.png">

If a subflow contains one of these Subflow-Status nodes, then any other status event from nodes inside the subflow will **not** automatically pass outside of the subflow. This means you can be more selective as to what status events to pass up - by using a 'normal' Status node inside the subflow and wiring it to the Subflow-Status node:

<img width="299" alt="local_node-red" src="https://user-images.githubusercontent.com/51083/52156158-79a37100-267e-11e9-9d4f-cb21857a7031.png">

Keep an eye out for the next 0.20 beta release that will contain this to try out.

**Comment by niemyjski** [comment]
Would you mind posting the source for the above examples. I've never used a status node so I'll need to read up more. It appears that your function has an extra output just to output a status node. Would it be possible to just do something like this.. `flow.setStatus(msg)`? and automatically output that or do we need to add a ton of outputs going to a single status node?
