### ISSUE TITLE
../node-icu-charset-detector.cpp:5:28: fatal error: unicode/ucsdet.h: No such file or directory

### ISSUE THREAD

**Issue by smartmouse** [node-red/node-red#599]
npm install node-red failed on Ubuntu OS
node version is 10.28

npm WARN package.json IDDE@1.0.0 No description
npm WARN package.json IDDE@1.0.0 No repository field.
npm WARN package.json IDDE@1.0.0 No README data

> node-icu-charset-detector@0.0.7 install /home/test/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

make: Entering directory `/home/test/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:5:28: fatal error: unicode/ucsdet.h: No such file or directory
 #include <unicode/ucsdet.h>
                            ^
compilation terminated.
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory `/home/ivyho/testIvy/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/svt/shared/IBMSVT32_10/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/svt/shared/IBMSVT32_10/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/test/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing node-icu-charset-detector@0.0.7

> utf-8-validate@1.0.1 install /home/test/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/test/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/test/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate/build'

**Comment by knolleary** [comment]
Hi,
thanks for raising this.

This is an **optional** dependency of the irc module we use failing to compile. Despite all the `ERR` messages, it is in fact only a warning.

This should not cause the overall node-red install to fail - if you think it is causing you problems, please do reopen.

We are looking to move the irc node to its own package - it doesn't really belong in the default install.

Nick

**Comment by smartmouse** [comment]
Thanks for confirming,

**Comment by vielmetti** [comment]
Thanks for noting this. I am trying to build Node-RED 0.10.6 on node.js 0.12.4 on Arch Linux on ARM for the Raspberry Pi 2, and ran into this error; good to know that it shouldn't be fatal (whew).

**Comment by vielmetti** [comment]
``apt-get install libicu-dev``` should solve this, can you try that @smartmouse ?
