### ISSUE TITLE
if write file node created parent dir chain instead of making an error

### ISSUE THREAD

**Issue by NicSil** [node-red/node-red#600]
Would be great if the write file node created parent dir chain instead of making an error.
Cf https://www.npmjs.com/package/mkdirp

**Comment by dceejay** [comment]
Given that you can pass in the filename on msg.filename - it would need to check for the existence of and potentially create a new directory on every incoming message... would this not hit the basic file write performance somewhat ? Hopefully unlikely - but the check would be necessary.

**Comment by knolleary** [comment]
It could assume the dir/file exists, try the write and only do the create if that fails.

But, I don't think this should be the default behaviour - a runaway flow could do a lot of unintended directory creation. **If** we add it, it should be an optional behaviour (default off).

**Comment by dceejay** [comment]
Yes - could do. Will have a look.

**Comment by knolleary** [comment]
The File node has an option to create the directory if needed. Can't remember when that was added, but this issue can be closed.
