### ISSUE TITLE
Node-RED build process

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#604]
We already have a grunt build that runs the code linting and unit tests.

We want to add a build step that must be run to get from the code in git and what you actually run.

In the first instance, this step allow us to minify the editor JavaScript to a single file, as well as move to sass for structuring the CSS.

The Grunt build will be updated to do this build, as well as provide a task that auto-builds the editor if any of its source is changed - minimising the developer workflow disruption this extra step would bring.

Releases published to npm will consist of built versions - so end users will not be affected.

This issue will be updated with details as they emerge.

---

Code in branch here: https://github.com/node-red/node-red/tree/build2

The `public` directory no longer exists in version control. It has been replaced by an `editor` directory that contains all of the editor parts. The build step creates the `public` directory from that.

The layout of this directory has also been improved - better separation of editor code from vendor libraries.

Adds a set of new tasks to the grunt build:

 - *build* - builds the editor content (creates the `public` directory)
 - *dev* - developer mode - builds the content, runs an instance of node-red, restarts if any relevant source file changes
 - *release* - builds a release zip file under `.dist/`

Node-RED now checks for the existence of `public/red/red.min.js` on start up. If it doesn't exist, it logs an error that the editor hasn't been built, and then exits.

**Comment by jmls** [comment]
I have created a pr (https://github.com/node-red/node-red/pull/605) but unfortunately the build / test system is failing

```html
316 passing (4s)
  1 failing0m
  1) Credentials "after each" hook:
     TypeError: Cannot call method 'clear' of undefined
      at Object.nodeInterface.clearRegistry (/home/travis/build/node-red/node-red/red/nodes/index.js:9:4264)
      at Context.storage.getCredentials.when.promise.resolve.a.b (/home/travis/build/node-red/node-red/test/red/nodes/credentials_spec.js:34:15)
      at callFn (/home/travis/build/node-red/node-red/node_modules/mocha/lib/runnable.js:251:21)
      at Hook.Runnable.run (/home/travis/build/node-red/node-red/node_modules/mocha/lib/runnable.js:244:7)
      at next (/home/travis/build/node-red/node-red/node_modules/mocha/lib/runner.js:259:10)
      at Runner.hook (/home/travis/build/node-red/node-red/node_modules/mocha/lib/runner.js:276:5)
      at process.startup.processNextTick.process._tickCallback (node.js:245:9)
```

I think that this is because in the afterEach(function() { .. }) of credentials_spec.js there is a call to the index.clearRegistry() - but without a call to the index:init() function (as I beleive that this is the only reason why registry is undefined at this point)

now, is this a bug in the tests ? (ie should index:init() be called at all times befiore any other method is called , or is it _not_ required that :init() be called ?

**Comment by knolleary** [comment]
This is because your PR changes the api so that it requires index.init to be called in order to initialise registry through the call to moduleSelector. Your PR would need to update the tests to account for this change.

If you have further questions about your tests, please ask them on your PR - this issue is about the new build system we're introducing.
