### ISSUE TITLE
"Modified Flow" deploy with mqtt listener

### ISSUE THREAD

**Issue by oliviergeslin** [node-red/node-red#609]
Hi,

It seems there is an issue when I have this type of flow 
mqttListener->function->XXX

If I deploy the flow after modifying the function with the "modified flow" option, the old mqtt subscription is still active and we have several times the same mqtt message (actually, as many as deploy :) )

http://thethingbox.io/ team

**Comment by knolleary** [comment]
Thanks for reporting - have confirmed the issue.
