### ISSUE TITLE
Info on connecting to GSM module

### ISSUE THREAD

**Issue by pops123** [node-red/node-red#613]
Hey. Ive a Telit GSM module and Im trying to send a small packet of data via node red to the cloud.

Now what I want to do is send the data via the the module.

Now as im inexperienced in this sphere I was wondering what input node should I be using?? I'm presuming the TCP input will work best. If so what configuration parameters will I put in the TCP node i.e type, output, topic name?? and what IP or address do I then use for sending too from my module??

Or am i better sending via a MQTT broker or through another input??

Thanks

**Comment by dceejay** [comment]
Hi - the Google group already has a discussion going about using Telit module - https://groups.google.com/forum/#!topic/node-red/MA_uXXLcF8c
We would prefer to keep the Issues list for actual problems with the code.

**Comment by knolleary** [comment]
@pops123 as @dceejay says, please use the mailing list for general questions.

**Comment by pops123** [comment]
sorry guys thanks anyway
