### ISSUE TITLE
Using Stomp node with activemq

### ISSUE THREAD

**Issue by mfeblowitz** [node-red/node-red#617]
In issue #591, I talked about difficulties with the mqtt nodes and activemq,  (due to our activemq setup being incompatible with the mqtt nodes).  #591 also describes how I shifted to stomp as an alternative. 

In order to make stomp work, I needed to configure our activemq instance to include a stomp connector, as documented on the [activemq stomp page](http://activemq.apache.org/stomp.html).

After setting up that connector, my stomp nodes were reported as being connected, but I couldn't get any data into or out from activemq.

It turns out that for **mqtt**, there is a **Topic** node parameter, but for stomp the corresponding parameter is **Destination**. Inferring from the stomp-client example, Destination could be entered as just a string: 

> queueName

or explicitly stated as a queue name

>/queue/queueName

or as a  topic name 

>/topic/topicName

The default interpretation is as a queue, and activemq (at least in my case) needs a **Topic**.

So I think all that's needed for this issue is documentation - either in the README.md or included in the html prompt for the field. Or a fancier approach would be to have a switch to indicate Queue versus Topic.

**Comment by knolleary** [comment]
As per the comment here: https://github.com/easternbloc/node-stomp-client#queue-names the /topic and /queue prefix is a convention of ActiveMQ and not of the stomp protocol. So at most this will be a note in the docs regarding this convention when using with AMQ.

**Comment by dceejay** [comment]
I'll enhance docs first thing tomorrow, and add in that fix.

**Comment by dceejay** [comment]
Closed by fix to node-red-nodes - 31318b03d769c388490f97eccca52b5850ef1261
