### ISSUE TITLE
Changed font size in edit function node

### ISSUE THREAD

**Issue by hallard** [node-red/node-red#619]
Hi there,

I noticed on my several red engine that the font size of the function node is now bigger than the previous version of red. I did not find the place where I could change this ? 

Here are two snapshot, the 1st one with the new version 
![image](https://cloud.githubusercontent.com/assets/2471931/7213298/4d708982-e579-11e4-8dfa-dbe02b31bd0f.png)

And as you can see much lower on old version.
![image](https://cloud.githubusercontent.com/assets/2471931/7213302/6763c7be-e579-11e4-99e1-ec325fa82633.png)

I'm pretty sure I missed an option somewhere but still can't find it.
Thank you for your help

**Comment by shemethy** [comment]
I noticed this too, font size seems too big in the new version.

**Comment by dceejay** [comment]
Hi,
The font should be the same size as all the others on the page (labels, debug panel etc). On larger res screens the small font was just too small - so keeping them all the same seemed sensible. Ctrl + and - will zoom the whole page of course including fonts.

**Comment by hallard** [comment]
dceejay
Thanks, that did the trick, I'm reducing the whole page then just increasing the dashboard with zoom + and - (bottom right)  like this, my node stay a good size and menus are still lower size, exactly what I needed ;-)

![image](https://cloud.githubusercontent.com/assets/2471931/7215241/d8e962ae-e5ce-11e4-8e0c-e6dce83dacf5.png)

**Comment by dceejay** [comment]
+1
