### ISSUE TITLE
SerialPort Out: "Add Split Character" broken

### ISSUE THREAD

**Issue by bramleyd** [node-red/node-red#622]
The serial-out node is no longer adding the separator character in 0.10.6.

Issue looks to be comparing boolean addchar to string "true".  Guessing this was introduced when the Add Separator to Output option was changed from Dropdown to checkbox.

The following change in serial.js has fixed the problem for me:

Change:
if (node.serialConfig.addchar == "true") {
   node.addCh = this.serialConfig.newline.replace("\\n","\n").replace("\\r","\r").replace("\\t","\t").replace("\\e","\e").replace("\\f","\f").replace("\\0","\0");
 }

to:

if (node.serialConfig.addchar == true) {
				
                node.addCh = this.serialConfig.newline.replace("\\n","\n").replace("\\r","\r").replace("\\t","\t").replace("\\e","\e").replace("\\f","\f").replace("\\0","\0");
 }

**Comment by knolleary** [comment]
Hmm, this appears like it was broken back in November, so all of the 0.10.x releases would have been similar affected.

Apologies - fix forthcoming.
