### ISSUE TITLE
Securing HTTP In end points

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#631]
We currently only support naive basic auth security against HTTP In node end points via the `httpNodeAuth` setting. We need a more flexible, secure solution to this.

We recently introduced `adminAuth` setting to improve the security of the admin api. This was done with credential based oauth initially, but with a mind to how it could be extended to other schemes.
We were able to benefit from being opionated as to how our own admin api should be secured. I don't think we can be as opionated when it comes to how users are able to secure the HTTP Apis they create within Node-RED.

I think there are two possible approaches:

1. be opinionated and define a settings object (like adminAuth) that encapsulates the configuration of some auth scheme for the http nodes.
2. allow the user to define their own middleware, via settings.js, that would apply to all http routes (not admin ones). This middleware would be inserted at the start of the HTTP route handlers (probably after parsers etc, but certainly before the node-defined middleware. The user can then write whatever authentication scheme they want.

I'm currently erring towards option 2

**Comment by cainjonm** [comment]
Would it be possible to support node-specific auth{entication,orization} settings? E.g. if you want one particular endpoint to allow X but another to allow Y,Z?

**Comment by knolleary** [comment]
The immediate requirement we have is to enable a single auth scheme to all http nodes - which this issue covers. The use case we have is also suited to doing this via settings.js rather than within the editor itself.

That doesn't mean we wouldn't extend it to support multiple schemes in the future - although that poses a number of design challenges, such as how each node gets configured to the appropriate auth scheme, how much is done via settings versus in the editor etc.

**Comment by deldrid1** [comment]
Could this middleware be used to address this issue with Node-Red on Bluemix:  https://github.com/node-red/node-red-bluemix/issues/7 ?

Perhaps httpNodeMiddleware should also be able to take an array of middlewares so that several can be added at a time?

**Comment by knolleary** [comment]
@deldrid1 the plan is to support an array of them, but I wanted to get the single-case in to satisfy an immediate need.

This could absolutely be used to enforce https to the http nodes - but wouldn't do it for the editor itself. I meant to ask, is your requirement to do this just for the nodes, or the whole thing?

**Comment by deldrid1** [comment]
I would like to support securing the whole thing.  Secure nodes with an insecure node/flow editor doesn't seem very secure :)

**Comment by knolleary** [comment]
We added the adminAuth option in 0.10:

http://blog.nodered.org/2015/02/08/version-0-10-1-released/

**Comment by deldrid1** [comment]
I have that turned on.  The issue is that I can't enforce HTTPS on Bluemix without some middleware on the express instance... (and since this is something that should be turned on by default IMHO, I don't want to fork https://github.com/node-red/node-red-bluemix, wrap Node-Red in an Express.JS app, and apply the middleware myself).

**Comment by knolleary** [comment]
Ah right, I see what you meant.

Being able to enforce https will be a separate (boolean) option. The custom node middleware is primarily for a different set of use cases.

**Comment by deldrid1** [comment]
That works for me!

I just saw your commit and it looked like it might be able to address my need.  I don't mind making the changes myself but not being too familiar with the Node-Red core (and not having the time) has led to me not getting there yet...
