### ISSUE TITLE
Focus view whilst in an iframe causes window to scroll

### ISSUE THREAD

**Issue by yehudita** [node-red/node-red#635]
Hi,
I took  your code and load it as am iframe in my application.
My node-red version is 0.10.6.
I have a problem on windows, chrome:
On click on the editor iframe, jump my window scrolling to the top of the canvas.
it is because focus code you add on 'Allow the main view hold keyboard focus':
https://github.com/node-red/node-red/commit/fabf01371437dc4af09293820036ab222f25bda8#diff-38fe95afd24aaea22b697b31f24751b8

Why did you add the focus code?
Do you have An idea how ignor the window to auto scroll on focuse?

Thanks,

**Comment by knolleary** [comment]
We had a similar thing reported recently here: https://groups.google.com/forum/#!topic/node-red/qbmdyjukjmk
The fix there was around the CSS of the containing page. Is that similar to what you're seeing?

**Comment by knolleary** [comment]
This may be relevant - http://code.google.com/p/chromium/issues/detail?id=437025

**Comment by yehudita** [comment]
I changed focusView function:
        parentWindow = window.parent.window;
    	var x = parentWindow.scrollX, y = parentWindow.scrollY;
        $("#chart svg").focus();
  	parentWindow.scrollTo(x, y);

**Comment by knolleary** [comment]
I saw this happen for myself recently. Will take another look at the change you made and see how we might apply it generically.

**Comment by knolleary** [comment]
Fixed in 0.14.0 - 7318a7b767c22846e0554357d6a7c24142665479
