### ISSUE TITLE
config node in config node

### ISSUE THREAD

**Issue by ToSa27** [node-red/node-red#636]
I'm trying to get a series of custom nodes created where one config node includes another config node. A simple less specific example could be if you want to have a "host" config node that defines your server providing a couple of services - then you have several "service" config nodes and they all should point to the "host" config node and provide additional configuration on top. This is quite beneficial if your "host" needs to change and you need to update only once...

The issue I'm running into is that the UI appears to support this setup when I use in the config node something like this (in this case the "parent" config node defines an IoT sub-network):

```html
    <div class="form-row">
        <label for="node-input-network"><i class="fa fa-globe"></i> Network</label>
        <input type="text" id="node-input-network">
    </div>
```

but the network information is not stored as part of the node config and therefore not accessible (or I don't know how). What I thought would be the correct setup is unfortunately not working. The UI just shows a simple textbox instead of the config node selection UI:

```html
    <div class="form-row">
        <label for="node-config-input-network"><i class="fa fa-globe"></i> Network</label>
        <input type="text" id="node-config-input-network">
    </div>
```

Not sure if this is an issue or actually a feature request (or I'm just not clever enough to get it to work).

**Comment by knolleary** [comment]
Hi, we don't support nested config nodes, which makes this a feature request. It isn't a small change to enable this due to various assumptions in the code, so not sure when well get around to addressing it.

**Comment by dceejay** [comment]
I know it's not the same - but could this discussion thread be an alternative way to solve the problem ? https://groups.google.com/forum/#!topic/node-red/qTlYWKF-Nrw - ie use environment to set some of the internal settings - in this case the server address inside the the config  node ?
(We currently don't support that either but fixing one thing may be better than fixing two...)

**Comment by ToSa27** [comment]
@dceejay using environment level settings could be an option - I would probably go ahead and have an entire JSON object with some structure to it stored there - the nodes could then pick the corresponding settings... 
With the answer from @knolleary I was actually looking at a different option where both config nodes end up on the first level (hiding the fact that one is nested). This would probably avoid issues with the assumptions in code as it reduces the complexity to a known scenario. Just the UI would need to be tweaked -> the lower level config node is picked and at that time the reference to the upper level config node is copied from the lower level config node to the base node...

**Comment by Shirk** [comment]
:+1: for this feature - I'm currently running into the same situation. 
In my case I'd like to use the existing `mqtt-broker` config (since the user might already have one in their flows) but also need to add additional information shareable across all of my projects nodes.

**Comment by marvinroger** [comment]
:+1: too, same use case a @Shirk

**Comment by knolleary** [comment]
The ability to have config nodes under config nodes will arrive in the 0.14.0 release.

**Comment by Roaders** [comment]
Looking forward to 0.14.0 release - this will solve an issue that I am having as well.

**Comment by sirockin** [comment]
I'm confused about the status of this issue. Since the issue is closed and we're now on 0.14.x I tried creating nested config nodes and it doesn't work for me. I also don't see in in the Current milestone even though I note knolleary moved it there on 18 May. 

If the issue has been resolved, is there any sample code showing it working?

**Comment by hardillb** [comment]
@sirockin the Dashboard UI makes use of nested configs, so it does work. Do you want to share the code you have that doesn't work on the google group and between us we can work out what needs tweaking?

**Comment by knolleary** [comment]
@sirockin as well as the dashboard UI nodes, the core `mqtt-broker` node (which is a config node) references the TLS config node here: https://github.com/node-red/node-red/blob/54036a2b4d0ea44ffc44e5f54e3e85c446f82de3/nodes/core/io/10-mqtt.html#L246

**Comment by sirockin** [comment]
thanks @hardillb and @knolleary for replying so quickly. I'll have a closer look at my code and the examples you gave me first and see if I can work it out.
