### ISSUE TITLE
Flows with unique ids or names

### ISSUE THREAD

**Issue by djensen47** [node-red/node-red#637]
When using the API, `GET /flows` returns everything and `POST /flows` replaces everything.

What I would like to see is some way to have a flow/graph have a unique id so that I can use the api to save a new flow to the server without replacing everything. As a corollary I would like to be able to delete a flow with a specific id.

From the point of view of the editor UI, this is a bit of a challenge. If you add two nodes, those would each be two unique graphs until they are combined, at that point which id wins?

**Comment by knolleary** [comment]
Hi @djensen47 

for feature requests, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red) in the first instance.

Being able to patch in a flow, without having to post the entire flow is something we've been talking around both amongst ourselves, but it has also been discussed on the list before. Can't immediately point you at a specific discussion as it hasn't been brought up quite as explicitly as this.

None of the discussions has come to any sort of conclusion as to where we want to go with this. The addition of the smarter deployment methods (only restart modified nodes etc), addressed some of our main use cases for partial deployments. But it doesn't address all of them.

In the current flow file definition, there is no concept of a flow ID. It is just a set of nodes, which are distributed over a number of tabs, that have wires connecting them. I don't think we're going to be changing that - so managing it via tabs may be the way to go.

But before getting too deep into design, we need to resolve the philosophical debate around whether we want to support this capability at all.


Thanks,
Nick

**Comment by knolleary** [comment]
Given #638 is a more fitting way to tackle the use cases for this (if we decide we want to tackle them...), I'm going to close this one. Flow IDs/Names isn't something we want to consider at this time.

**Comment by dceejay** [comment]
If you do a partial deploy where the bit you add is only on a new tab - then that tab can have a name, but obviously that then ties it to the tab level rather than the (bit of a) flow level.
