### ISSUE TITLE
API for workspaces/tabs

### ISSUE THREAD

**Issue by djensen47** [node-red/node-red#638]
Since #637 might be a bit of a challenge, having an API for workspaces might be a good stop gap.

`GET /workspaces` returns a list of workspaces
`POST /workspaces` creates a new workspace with the option to include nodes/graphs
`GET /workspaces/:id` returns the details of a specific workspace
`PUT /workspaces/:id` updates a workspace, again with the option to include nodes/graphs
`DELETE /workspaces/:id` deletes a workspace including all of its nodes
 
If this is acceptable, I can get started on it.

**Comment by knolleary** [comment]
As per comments in #637, right now the only object we have is the flow object - which contains everything. Tabs (workspaces is a deprecated term as far as the internals go), are the only unit of organisation we have. So there is some merit to this approach.

But before diving into the details of api and certainly before writing any code, there is a wider discussion to be had on what sort of functionality we want to enable.

Can I ask you to post this to the mailing list on this topic where we can have a discussion involving the community?

Thanks,
Nick

**Comment by djensen47** [comment]
Sure thing, I'll start the discussion on the mailing list.

**Comment by knolleary** [comment]
We added the `/flow` api in 0.13 - http://nodered.org/docs/api/admin/methods/
