### ISSUE TITLE
Export-Import with Config doesn't appear to preserve/active config on import

### ISSUE THREAD

**Issue by mfeblowitz** [node-red/node-red#639]
When a flow containing a node with a config (in this case, stomp-in, with a server config) is exported to library and imported into a clean flow-set (new flows file), the field set by a config node is not recognized. A nominal edit to the config node  (adding a space character to the name) and a redeploy cause the config'd field to be seen as having a value.

I believe the same happens with export/import via the clipboard.

It also appears that import of a node containing a config that's already known in the current flow set breaks the existing node.

Specific scenario: 

I have exported a simple, three-node flow containing a stomp-in node.

The stomp-in node with a server config is exported to the library and imported into a clean sheet. A property that is clearly set in the copied config and looks ok. There is no error reported, but the node does not connect. Changing the name of the config and re-deploying, I see no error and the node connects.

A similar condition occurs in an imported flow with a stomp out node in a subflow. On deployment I see the error

```[stomp out:a1773ced.5e88c] TypeError: Cannot read property 'server' of null```

I have confirmed this problem has being unrelated to the use of a subflow (removing the subflow and importing the full graph).

**Comment by dceejay** [comment]
hmm - I don't think this is stomp related...
What seems to be happening is that just pasting in the subflow / nodes and deploying does indeed just do that... It doesn't update the creds (credentials) file for the flow. Touching the actual node causes it to update and then it works normally...

**Comment by mfeblowitz** [comment]
Another side effect of this is that inject nodes don't fire (!?). Even ones in unrelated flows. The complaint is that they've not been deployed. Fixing the config makes that problem go away. 

I'm wondering whether this is a silent deploy fail.

**Comment by knolleary** [comment]
This is technically a bug with the stomp-server node. It assumes it always has credentials configured and attempts to reference `credentials.user` despite `credentials` being null.

When you import a flow, as credentials are never exported by node-red, no credentials object gets created when you deploy.

When you then edit the config node, it sets the credentials fields to empty strings, which when deployed means the credentials object exists, albeit empty.

Having said its a bug with the stomp node, we could do better to avoid it. If a node declares the presence of credentials, we can ensure `this.credentials` will exist, even if empty. That will prevent these references errors.
