### ISSUE TITLE
Email input issue / special EOL characters?

### ISSUE THREAD

**Issue by bbence84** [node-red/node-red#641]
There's a slight issue with the post processing of the emails that is fetched in node-red.

The original email (viewed as source in gmail):
A woman gets on a bus with her baby. The bus driver says: ''Ugh, that's the=
 ugliest baby I've ever seen!'' The woman walks to the rear of the bus and =
sits down, fuming. She says to a man next to her: ''The driver just insulte=
d me!'' The man says: ''You go up there and tell him off. Go on, I'll hold =
your monkey for you.''

The payload that node-red returns:

Content-Transfer-Encoding: quoted-printable A woman gets on a bus with her baby. The bus driver says: ''Ugh, that's the= ugliest baby I've ever seen!'' The woman walks to the rear of the bus and = sits down, fuming. She says to a man next to her: ''The driver just insulte= d me!'' The man says: ''You go up there and tell him off. Go on, I'll hold = your monkey for you.''

So the EOL characters (=) gets transfered and also the Content-Transfer-Encoding: quoted-printable appears in the text. This might be somewhat gmail specific, but it's an issue. I can use a change node but the problem is that simply replacing '= ' (with space) or '=' (without space) is not going to work because sometimes the words will be merged due to this. So the post processing around lines 203 in 61-email.js could be improved.

**Comment by dceejay** [comment]
Hi,
any chance you can send me such an email ?
direct to my test gmail account  - dcjhouse
Thanks

**Comment by knolleary** [comment]
Any news?

**Comment by nkolban** [comment]
In about a week there is a new pull-request coming in which completly re-works how parsing of emails is performed.  It hands off all email content processing to:

https://www.npmjs.com/package/mailparser
