### ISSUE TITLE
MQTT nodes reconnect repeatedly to broker

### ISSUE THREAD

**Issue by fabue** [node-red/node-red#642]
Hello,
I installed node-red freshly from master 913fdac67180c4d343d5e74321d9b6ddc70b5ad7 and made a simple flow:
![bildschirmfoto 2015-05-07 um 16 00 47](https://cloud.githubusercontent.com/assets/224478/7516987/bb2f1138-f4d2-11e4-89fa-1d71066c7ab5.png)

* the subscriptions node disconnects and reconnects repeatedly. 
* used broker: broker.mqtt-dashboard.com:1883. Same with other brokers.

**Comment by knolleary** [comment]
Have you tried without specifying a client id? It is possible that someone
else is already using the client id 'node-red' which would cause this
behaviour.

**Comment by fabue** [comment]
That's it, thanks a lot!

**Comment by boneskull** [comment]
How to get more info about disconnections?  Experiencing something similar.

**Comment by hardillb** [comment]
You need to look at the broker logs to be sure.

**Comment by boneskull** [comment]
@hardillb thanks.  too bad I don't own the broker. :smile:

**Comment by fab33** [comment]
I have same bug today. Watching my mosquitto logs and it tells client is already connect so it close new connection. I have this bug juste after a node-red update. restarting node-red and everything works fine.

**Comment by knolleary** [comment]
@boneskull @fab33 what version of node-red are you using?

**Comment by fab33** [comment]
Node-RED version: v0.13.4
Node.js  version: v4.4.0
mosquitto log : 
`1460552960: New client connected from 127.0.0.1 as mqtt_51923d95.ae6dc4 (c1, k15).
1460552960: Client mqtt_51923d95.ae6dc4 already connected, closing old connection.
1460552960: Client mqtt_51923d95.ae6dc4 disconnected.
1460552960: New client connected from 127.0.0.1 as mqtt_51923d95.ae6dc4 (c1, k15).
1460552960: Client mqtt_51923d95.ae6dc4 already connected, closing old connection.
1460552960: Client mqtt_51923d95.ae6dc4 disconnected.
1460552960: New client connected from 127.0.0.1 as mqtt_51923d95.ae6dc4 (c1, k15).
1460552960: Client mqtt_51923d95.ae6dc4 already connected, closing old connection.
1460552960: Client mqtt_51923d95.ae6dc4 disconnected.
1460552960: New client connected from 127.0.0.1 as mqtt_51923d95.ae6dc4 (c1, k15).
`

**Comment by boneskull** [comment]
v0.13.4, Node.js v5.10.1.

This *is* the problem I'm having actually--the broker reports that the client is already connected (I have that much information, at least).

**Comment by boneskull** [comment]
Monkeying with keepalive or "clean session" seems to have no effect.  I *am* using TLS

**Comment by boneskull** [comment]
If I had to make a WAG here, the disconnection isn't happening properly upon deploy, or the broker doesn't recognize the disconnection before the connection is made again by Node-Red.

**Comment by knolleary** [comment]
@boneskull is there any pattern as to when this starts to occur or any action you can correlate it to?

**Comment by boneskull** [comment]
I didn't try to set keepalive to 0.  This seems to happen every 60-70 seconds, and the keepalive time is 60.

**Comment by boneskull** [comment]
no effect

**Comment by boneskull** [comment]
disabling legacy support and clean sessions has no effect either.  I'm led to believe this is a problem with the broker

**Comment by boneskull** [comment]
related: [forum post](https://forums.getstructure.io/t/frequent-mqtt-disconnections-device-already-connected/96)

**Comment by boneskull** [comment]
Solved.  Reduced default MQTT reconnection period from `15000` ms to the [default](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L22) of `1000` ms, and I no longer experience the frequent disconnects.

**Comment by boneskull** [comment]
Out of curiosity, what's the necessity of the `15000` ms default?

**Comment by knolleary** [comment]
Because you've got to have some sort of default value... :)

**Comment by boneskull** [comment]
...*not* solved.  Still having problems.  Structure (now Losant) is looking into if the problem is on their end, in Node-Red, or in the mqtt lib.

**Comment by cogpt** [comment]
same problem with node-red. Must be a node-red problem as with a python client it runs with no problems.

**Comment by Fabiancrg** [comment]
I had the same issue problem was that I was using the mqqt node in several flows and each pointing to the same broker with the same ID. Now I am using one client ID per flow and I don't have disconnetion anymore.
