### ISSUE TITLE
Subflow wiring issue: cannot call push method 'push' of undefined

### ISSUE THREAD

**Issue by coderofsalvation** [node-red/node-red#645]
I had multiple occasions where I wasn't able to deploy.
The button would just stay red after pressing, and the browser console would throw the error mentioned in above.

At some point I was able to deploy after editing public/red/nodes.js at line 400:

    function convertNode(n, exportCreds) {
            
            ....
            
            var wires = links.filter(function(d){return d.source === n;});
            for (var j=0;j<wires.length;j++) {
                var w = wires[j];
                if (w.target.type != "subflow") {
         +         if( node.wires[w.sourcePort] != undefined )
                        node.wires[w.sourcePort].push(w.target.id);
                }
            }
            
            ....
            
    }

For some reason a wire with undefined sourcePort was added to the graph.
No idea why.
Anyways now it seems to deploy again.
Will do some more tests.

ps. unfortunately I cannot provide flows.json because of IP reasons

**Comment by knolleary** [comment]
I appreciate you cannot provide the flow file as-is, but can you provide any sort of description of the flow to help us recreate it? Or possible a minimal test case that recreates it?

**Comment by coderofsalvation** [comment]
Well my flow.json is over 1MB so its hard to pinpoint the exact problem.
I noticed that even adding 1 node (didnt matter which) threw the same error.
But here's my theory: subflows

I work mostly in subflows, and have one normal document which actually contains instances of each subflow.
When editing in these subflows, I noticed that sometimes I cannot delete individual wires.
Mostly this happens when : 

* adding a node (A) to an existing subflow
* wire it to a node which was already in the subflow
* then try deleting this wire

Sometimes deleting this wire doesnt work, it even doesn't select the wire.
However, by deleting node A the wire (and the node) do delete.

## Conclusion so far

Something weird might be going on with the wire-management/cleanup within subflows.

**Comment by coderofsalvation** [comment]
## update

I noticed one splitter node *not* having an output connection point drawn (its supposed to have an input- and output-connector). 
I remember updating/fixing the node-red-contrib-splitter node recently.
So another theory could be that zombiewires get introduced while saving a flows.json which contain some unresolved nodes (because of syntax errors during developing these nodes).

I'll let you know if I know more.

**Comment by knolleary** [comment]
We've had no further reports of this in almost a year, so I'm to tentatively close this. We can reopen if necessary.
