### ISSUE TITLE
Get a full support of working behind a Reverse Proxy

### ISSUE THREAD

**Issue by lunarok** [node-red/node-red#652]
Hi,

Is it possible to get a Node Red instance fully working behind a Reverse Proxy ?
In my case, it's nginx reverse proxy.
For http, it's ok. Using http_root.
But we experience a websocket connexion that is failing as it's not reverse proxied.
If I understand nodejs correctly, this must be explicitly says in the application that ws will be proxified behing a http connexion ?
How to success with that ?

Thanks,

Cédric

**Comment by knolleary** [comment]
Hi, 
A quick Google search found this guide to using nginx to proxy websockets: 
http://nginx.com/blog/websocket-nginx/

This isn't an issue with node-red so I'm going to close this issue. If you have any more questions, please use the mailing list, unless you think it is an actual issue for us to look at.

Nick
