### ISSUE TITLE
Hot to run a flow via command line?

### ISSUE THREAD

**Issue by mc007** [node-red/node-red#654]
Hi,
May be i am missing something but after reading the docs I can't figure out how to run a certain flow via command line. 
thank you!

**Comment by shemethy** [comment]
Use the mailing list for questions or feature requests: https://groups.google.com/forum/#!forum/node-red

**Comment by vielmetti** [comment]
The relevant documentation is here

http://nodered.org/docs/getting-started/running.html

Look under `command line usage`, invoke as 

```node-red my-new-flows.json```

Note that you may need to have -s (--settings) and -u (--userDir) to get the settings file and the user directory right as well.

I'd put this in as a documentation bug, the docs could stand to be a bit more comprehensive here.

**Comment by knolleary** [comment]
@mc007 does the reply from @vielmetti answer your question? Is that what you were trying to do?

**Comment by mc007** [comment]
Hi, sorry, was AFK. 
yes, that would answer the question, I really missed the 'flows.json' argument in the docs. Now assuming,  this node will runs forever, is there any chance to actually stop it the same way? 

Sorry getting offtopic now, I am developing authoring web software and my idea about node-red is to enable users to run red-node flows in my own VPL(visual block language). So I would need all sorts of controls, ie start/stop/resume/pause. Might it be possible to have a client-side run-time for node-red (similar as in noflow)? That would be great! 
thanks again!
