### ISSUE TITLE
npm WARN package.json node-red@0.10.6 license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#655]
This only affects builds using Node.JS 0.12.x and (especially) npm v2.10.0.  See

https://github.com/npm/npm/releases/tag/v2.10.0

```
THE IMPLICATIONS ARE MORE PROFOUND THAN THEY APPEAR
```

reads the warning; it has to do with encoding licensing into the package.json files, and it's said to have implications for automated license checkers.

Noted here so that https://github.com/node-red/node-red/issues/565 can keep track of it.

**Comment by knolleary** [comment]
There's no reason for us not to get ahead of the curve and update the license entry to the proper SPDX value - `Apache-2.0`.

@dceejay saw you'd done this in the top-level node-red-nodes file. Need to percolate it through alllll of our package.json files.

**Comment by dceejay** [comment]
Indeed - am doing so slowly.

**Comment by dceejay** [comment]
All node-red-nodes and node-red-web-nodes done. Also updated package.json in node-red-bluemix-nodes
