### ISSUE TITLE
"Fatal error: argument entity must be string, Buffer, or fs.Stats" in nodejs 0.12.x build

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#656]
The nodejs 0.12.x build fails with this error message.

It looks like a bug in the 0.16.x version of fs-extra which is solved in 0.18.4.

https://github.com/node-red/node-red/issues/565 is the original issue this was identified at, noted by @cainjonm . https://github.com/jprichardson/node-fs-extra/issues/120 is the bug in upstream which has been fixed by https://github.com/jprichardson/node-fs-extra/commit/931d409429818cbdfc30201b34572dddac2f3698 of April 17 2015.

**Comment by knolleary** [comment]
Hi,

as you know, we have an item open for node 0.12 support. Please add notes to that rather than raise individual issues for each thing you find. We'll be looking at 0.12 after we get the next release out of the way.

Nick

**Comment by vielmetti** [comment]
OK Nick, I'll focus on that other issue for now.

**Comment by knolleary** [comment]
I'm going to close this issue to keep it all under #565
