### ISSUE TITLE
Oneditsave Change icon

### ISSUE THREAD

**Issue by lemio** [node-red/node-red#658]
For some uses it could be usefull if the content of the node changes it also changes the icon in the node. I'm now working on communicating with hardware for education, and it would be nice if the students have a visual representation of the sensor/actuator in the node.

**Comment by hardillb** [comment]
One of the key tenents of Node-RED that it is not meant to be a dashboard.

Having said that there are status indicators for nodes that are typically used to show if a node is currently connected to it's remote backend resource. (http://nodered.org/docs/creating-nodes/status.html)

Also issues are really only being used to track actual defects, please raise questions/feature requests in the Mailing List/Forum (https://groups.google.com/forum/#!forum/node-red)

**Comment by knolleary** [comment]
If you want the icon to reflect a static configuration of the node, that is something we could do; other properties in the node definition can be defined as a function that gets evaluated - something we could extend to the icon property.

If you want the icon to reflect some runtime state of the node, that is not something we would do; as Ben says, the status api is there for that.

**Comment by knolleary** [comment]
Just pushed commit 871f764e981639bba94c97e86eefff12b0d68c07 that allows the icon definition to be a function. This will be available in the next release and documentation for it added [here](http://nodered.org/docs/creating-nodes/appearance.html).
