### ISSUE TITLE
Second-flow gives me an error on httprequest ENOTFOUND

### ISSUE THREAD

**Issue by wyattbiker** [node-red/node-red#659]
From tutorial: http://nodered.org/docs/getting-started/second-flow.html

@ #2. Add an HttpRequest node
http://realtimeweb-prod.nationalgrid.com/SystemData.aspx

The above node shows ENOTFOUND. However when i run link in my browser it works fine. 

Any ideas?
![s1](https://cloud.githubusercontent.com/assets/930478/7864906/04e8cac4-0533-11e5-97cf-f802179c5bb5.png)
![s2](https://cloud.githubusercontent.com/assets/930478/7864909/0d61bfc6-0533-11e5-99a7-d2efaf015a1b.png)

**Comment by wyattbiker** [comment]
It also seems any website gives me that message. Is there something I need to do if behind proxy?

**Comment by hardillb** [comment]
Proxy support has just been just fixed (you will need to pull from head, rather than use the packaged release to pick it up)

You should be able to set the HTTP_PROXY environment variable before starting node-red

**Comment by knolleary** [comment]
@wyattbiker as @hardillb says, support for running behind an http proxy arrives in the next release (due next week). We'll update the [documentation](http://nodered.org/docs) with details with the release.

You could grab the unreleased HTTP node files from here:
 - https://raw.githubusercontent.com/node-red/node-red/master/nodes/core/io/21-httpin.js
 - https://raw.githubusercontent.com/node-red/node-red/master/nodes/core/io/21-httpin.html

if you want to try it out. Be sure to set the HTTP_PROXY environment variable (quick google search, this looks like a good guide: http://docs.cloudfoundry.org/devguide/installcf/http-proxy.html)

**Comment by wyattbiker** [comment]
Tried  to use a config script for the proxy (e.g. http://proxyconfig.mydomain.com:80) . That did not work. I had to dump out the script with Chrome to figure out the actual proxy URLs. 

I then used SET HTTP_PROXY=http://proxypath.mydomain.com:8888 from the command line using SET before starting node-red. That worked fine. For now I stuffed it in node-red.cmd

Thanks for your help.

**Comment by Shai1436** [comment]
Hi,
This flow is stuck at requesting state. I am using node-red 0.16.0 and I have set HTTP_PROXY in environment variables and in terminal. I tried catching the error, but problem is still unclear.


 
![image](https://cloud.githubusercontent.com/assets/11535179/21960296/b6949780-db0b-11e6-90b9-17ead3544a20.png)

**Comment by knolleary** [comment]
@Shai1436 - that is a symptom of running with an unsupported version of node.js. the 0.16 release dropped support for node.js 0.10 and 0.12.
