### ISSUE TITLE
Build Partially failed due to  unicode/ucsdet.h: No such file or directory. But my first Hello World works

### ISSUE THREAD

**Issue by rsrini7** [node-red/node-red#662]
Thanks for the very good tool. Awesome.

i installed in my Ubuntu 14.10 and below is the error. When i first started my hello world, works :) The question is, is that issue or i can ignore and move on.

make: Entering directory '/usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:5:28: fatal error: unicode/ucsdet.h: No such file or directory
 #include <unicode/ucsdet.h>
                            ^
compilation terminated.
node-icu-charset-detector.target.mk:80: recipe for target 'Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o' failed
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing node-icu-charset-detector@0.0.7
 
> iconv@2.1.7 install /usr/local/lib/node_modules/node-red/node_modules/irc/node_modules/iconv
> node-gyp rebuild

**Comment by vielmetti** [comment]
The sources for that module are here

https://github.com/mooz/node-icu-charset-detector

and it says in the comments that there are additional build requirements for `libicu` which it provides this instruction for Debian / Ubuntu

```apt-get install libicu-dev```

which should presumably go into the dependency list somehow.

**Comment by vielmetti** [comment]
Also noted at #599, so one or the other of these is a duplicate. #599 was closed wtihout solving so I think we keep this one open to track it. @smartmouse had the same issue.

**Comment by knolleary** [comment]
The key thing to note that this is an optional dependency - it is not a fatal error with the install.

We're about to move irc out of the core nodes. We can add a note about the (optional) dependency to the nodes readme.

**Comment by dceejay** [comment]
We did add extra notes about this to the install doc - maybe we need to make them more explicit somehow. (As it's not just irc - though that is the main culprit)

**Comment by knolleary** [comment]
With 0.10.8 we've removed irc from the default install - this should reduce the confusion these messages cause new users who don't care about irc.
