### ISSUE TITLE
Hot to stop a flow via command line?

### ISSUE THREAD

**Issue by mc007** [node-red/node-red#666]
Hi,
is there any way to stop a flow from running via command line ? Pause/Resume is also missing.
Thanks!

**Comment by knolleary** [comment]
Hi, 

please can you use the [mailing list](groups.google.com/forum/#!forum/node-red) for general enquiries? 

There is no way to stop a flow. There's been some recent discussion on the mailing list about being able to disable nodes. That would provide something like stopping a flow.

Nick

**Comment by mc007** [comment]
sure, thanks. This is only required for embedding node-red somewhere else...
