### ISSUE TITLE
Road to 0.10.8

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#668]
Task list for getting 0.10.8 out of the door

### Node updates
- [x] catch node loop handling - in @dceejay branch, need to consider moving the logic into the core, not in the catch node itself
- [x] HTTP help text update - remove reference to directly calling msg.res
- [ ] Create plan for deprecating raw msg.req/res objects

### Core
- [x] provide prompt to clean up unused config nodes ?

### Node moves
 - [x] move non-core nodes to node-red-nodes - ensure adding them as package dependency 'Just Works'
    - Removed from default install:
      - [x] IRC -> node-red-node-irc
      - [x] Arduino -> node-red-node-arduino
      - [x] Redis -> node-red-node-redis
      - [x] Mongo -> node-red-node-mongodb
    - Moved to own package, included as dependencies of default install
      - [x] Twitter -> node-red-node-twitter
      - [x] Feedparse -> node-red-node-feedparser
      - [x] Email -> node-red-node-email
      - [x] Serialport -> node-red-node-serialport
      - [ ] RPI gpio (not now moving... - needs more testing in slow time)
 - [x] handle node type migration from core to external module
 - [x] add deprecation warning component to warn if to-be-moved core nodes are in use

### Doc updates
 - [x] node icon can be a function (ensure default when used in the palette)

### Release mechanics
 - [x] bump version number
 - [x] tag release
 - [x] run build and upload to GH
 - [x] Blog post

**Comment by dceejay** [comment]
moved (copied) IRC and Arduino into Node-Red-Nodes... so can both now be npm installed. Need to remove irc from package.json, and delete from core nodes... when you are happy. 
I've gone soft on moving / repackaging all the others right now... but we could pick on one as a test... feedparse ?
