### ISSUE TITLE
Node-red mongodb out: msg._id only works with payonly false; payonly true sends payload doc, not contents

### ISSUE THREAD

**Issue by mfeblowitz** [node-red/node-red#669]
*mongodb out* documentation says a document id can be specified by sending it in *msg._id*. This only seems to work with "payonly" set to false. If set to true, there seem to be no  means to set the _id.

Expected behaviours:
1. make the msg._id approach work regardless of payonly setting.
2. allow for the _id: key in the payload contents to set the id, when payonly is set.

Also, I would have expected  "payonly" mode to post the payload contents to mongo, not the payload element. One possibility is to retain the "payonly" setting and add a "contentsonly" parameter. That would retain backward compatibility.

More on the matter, is posted at [DW Answers](https://developer.ibm.com/answers/questions/194764/is-there-a-way-in-node-red-mongodb-to-put-only-pay.html)

**Comment by dceejay** [comment]
Yes - both points make sense.

Not sure I'm clear on your "also" comment - in payload only mode you "must" deliver a json object to be saved. So if it's not an object (ie is just a string  or number etc) then we wrap it into an object, that we happen to also call payload... so at least it has best chance of being saved. Mongo won't actually allow the saving of a non-object. http://docs.mongodb.org/manual/core/document/ 
Or is that not what you mean ?

**Comment by mfeblowitz** [comment]
Dave - 

The intent is for the payload content to be a json object. Should have been one. Now it is. The json node-red node is quite helpful that way. :)  I humbly request a note in the documentation that reflects your comment.

With that sorted, I was able to determine the root cause of my other problem. Being yet a novice, I hadn't realized that the _id must be at the top level. So, instead of 

    { "thing1" : { "_id : "idstring", ... } } 

I needed to represent it as 

    { "_id : "idstring", "thing1" : {...} }

So, no repair needed (save for my dignity).

Thanks again for the clarification.

Mark

**Comment by dceejay** [comment]
Ah - OK - yes - will "improve" the docs somehow :-)....  but indeed I still think your initial points is valid... - if the payload isn't an object - and we wrap it... - if msg.id is set, then to add that into the payload we generate such that you can update the existing one would be sensible ??? What do you think ?

**Comment by mfeblowitz** [comment]
Yes, I would agree. The challenge is to put it to mongo in such a way that it would be recognized as an id. I believe what you'd put would be { msg._id, payload: ... }. At least that's what it looks like proper json object : { msg._id, jsonObject : ... }

**Comment by dceejay** [comment]
implemented as described in my post above above.
