### ISSUE TITLE
 Issue after running the node-red in the Amazon ec2 server.

### ISSUE THREAD

**Issue by Kushi171987** [node-red/node-red#670]
Hi,

I Installed the node-red in my Amazon ec2 server with npm. I am using the nginx to redirect to the node-red server (http://127.0.0.1:1880). But when I launching the url, Its loading on the left hand side. It just showing a loading indicator thats it.

Please help me to start on node red.

Thanks In advance.

![screen shot 2015-06-04 at 11 11 54 pm](https://cloud.githubusercontent.com/assets/6594820/7992400/a8bbc6d0-0b1c-11e5-9985-cdc9ede5b837.png)

**Comment by mblackstock** [comment]
Hi @Kushi171987 - you should post your NR questions to the mailing list at https://groups.google.com/forum/#!forum/node-red
I'm sure many will be glad to help you there including me :-)

**Comment by knolleary** [comment]
What error messages are there in the browser console?

For future reference, for general support, we prefer to use the mailing list (linked from the bottom of nodered.org).

**Comment by mblackstock** [comment]
I suspect its an nginx proxy set up issue.  for web sockets you need to add

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

to your nginx configuration

**Comment by knolleary** [comment]
@Kushi171987 hi - any updates?

Whilst @mblackstock is quite right about needing to ensure websocket access is enabled, your screenshot suggests a different issue - the palette has failed to load which is not a websocket issue.

But unless you provide some more information, such as what error messages you are getting in the browser console, we cannot help.

**Comment by knolleary** [comment]
Hi @Kushi171987 , in the absence of any update I'm going to close this issue.

If you are still having problems, please contact the [mailing list](https://groups.google.com/forum/#!forum/node-red).

**Comment by knolleary** [comment]
IN fact, I see you did raise this on the mailing list, but your post got flagged as spam for some reason. I've approved your post to go to the list - if it doesn't appear shortly, can I ask you post again to the list? Sorry for the inconvenience.

Nick

**Comment by Kushi171987** [comment]
Sorry for the late I am on leave. Yes I added @mblackstock answer too. If I run red.blueapp.io this url, I got the errors in console. But if I run with port number (i.e http://red.blueapp.io:1880/)then it is fine. 
![screen shot 2015-06-16 at 4 43 59 pm](https://cloud.githubusercontent.com/assets/6594820/8181828/fb00b756-1446-11e5-8dbe-612f4e6d86ce.png)

here is my nginx configuration. 

'map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
upstream noderedserver {
    server 127.0.0.1:1880;
}
server {
    listen         80;
    server_name    red.blueapp.io;
    location / {
        proxy_pass  http://127.0.0.1:1880;
    }
    location /comms {
        proxy_pass http://noderedserver;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}'
