### ISSUE TITLE
If one node has an error,  how to break/stop the flow?

### ISSUE THREAD

**Issue by penzhan8451** [node-red/node-red#672]
Hi Dear,

I am a junior for node-red.  Can you please look at the question? 
In my flow,  If one node has an fatal error,  I want the flow stopped (or break).  How can I do it?

Thanks.

**Comment by knolleary** [comment]
Hi, please use the [mailing list](https://groups.google.com/forum/#!forum/node-red) for general questions.

Thanks.

**Comment by penzhan8451** [comment]
hi knolleary,

Thanks for your taking a look.  I want to open mailing list in the browser. but the site seems broken. (Or Maybe It is network issue of my location?).

Thanks.

**Comment by knolleary** [comment]
It's hosted on Google Groups so should be available.
