### ISSUE TITLE
Mqtt connection on node-red

### ISSUE THREAD

**Issue by suma1431** [node-red/node-red#674]
Hi, when I was using mqtt node on node-red as soon as I deply, mqtt client was connecting to broker.
But now the connection to mqtt broker is happening by itself.
How can I connect to mqtt broker on node-red

**Comment by hardillb** [comment]
This is working as intended, when you deploy the flow starts to run so will connect to any MQTT brokers defined in the flow.

If the connection gets dropped for some reason it will reconnect.

The MQTT connections are also pooled, so multiple nodes using the same broker will only result in 1 connection to the broker.

For general questions like this please use the mailing list/forum
https://groups.google.com/forum/#!forum/node-red

**Comment by suma1431** [comment]
The problem is it is not at all establishing the connection :(

**Comment by suma1431** [comment]
9 Jun 17:15:35 - [info] Node-RED version: v0.10.6
9 Jun 17:15:35 - [info] Node.js  version: v0.10.36
9 Jun 17:15:35 - [info] Loading palette nodes
9 Jun 17:15:36 - [warn] ------------------------------------------
9 Jun 17:15:36 - [warn] Failed to register 5 node types
9 Jun 17:15:36 - [warn] Run with -v for details
9 Jun 17:15:36 - [warn] ------------------------------------------
9 Jun 17:15:36 - [info] User Directory : /root/.node-red
9 Jun 17:15:36 - [info] Flows file     :
/root/.node-red/flows_sysadmin-OptiPlex-7010.json
9 Jun 17:15:36 - [info] Server now running at http://127.0.0.1:1880/
9 Jun 17:15:36 - [info] Starting flows
9 Jun 17:15:36 - [info] Waiting for missing types to be registered:
9 Jun 17:15:36 - [info]  - mongodb




---------------------------

see even here I cannot see mqtt connection log

**Comment by hardillb** [comment]
It is not starting the MQTT connection because it can not start the flow until the mongodb node can be found

**Comment by suma1431** [comment]
What if I dont want to add mongodb node ..

**Comment by hardillb** [comment]
Node-RED is waiting for it because it is being used in the flow. If you
don't want to install it you need to remove it from the flow.

**Comment by suma1431** [comment]
Sorry for troubling :( 
But I have deleted mongodb node from on flow manually on http://localhost:1880/#.. still when ever am restarting node-red Iam seeing the same error log

**Comment by suma1431** [comment]
Though I deleted the mongodb node from the flow manually on
http://localhost:1880/#, after restarting node-red same error log is
appearing :(

**Comment by hardillb** [comment]
If you click on the burger icon in the top right hand corner then on the "configuration nodes" item it should open a new tab in the debug area.

Do you have any mongodb config nodes in that list?

**Comment by knolleary** [comment]
@suma1431 one small clarification to what @hardillb has suggested: in the configuration nodes sidebar you may see a node called 'unknown' rather than mongodb. Double click on it and click the delete button, then deploy.

Alternatively, remove the node by hand editing your flow file: /root/.node-red/flows_sysadmin-OptiPlex-7010.json - just take a backup first!

**Comment by suma1431** [comment]
No I dont have

**Comment by suma1431** [comment]
Thanks aton :)
I deleted .. And now everything is working fine:)
