### ISSUE TITLE
mongodb node-red

### ISSUE THREAD

**Issue by suma1431** [node-red/node-red#675]
I even tried installing mongodb using npm install -g mongodb, but of no use.. 
The same is causing problem for me to connect with mqtt broker

Please help me out at earliest

Welcome to Node-RED
===================

9 Jun 17:15:35 - [info] Node-RED version: v0.10.6
9 Jun 17:15:35 - [info] Node.js  version: v0.10.36
9 Jun 17:15:35 - [info] Loading palette nodes
9 Jun 17:15:36 - [warn] ------------------------------------------
9 Jun 17:15:36 - [warn] Failed to register 5 node types
9 Jun 17:15:36 - [warn] Run with -v for details
9 Jun 17:15:36 - [warn] ------------------------------------------
9 Jun 17:15:36 - [info] User Directory : /root/.node-red
9 Jun 17:15:36 - [info] Flows file     : /root/.node-red/flows_sysadmin-OptiPlex-7010.json
9 Jun 17:15:36 - [info] Server now running at http://127.0.0.1:1880/
9 Jun 17:15:36 - [info] Starting flows
9 Jun 17:15:36 - [info] Waiting for missing types to be registered:
9 Jun 17:15:36 - [info]  - mongodb

**Comment by knolleary** [comment]
Hi, you have already opened issue #674 for the same thing. I'm going to close this one.

In future, please use the [mailing list](https://groups.google.com/forum/#!forum/node-red) for support questions.
