### ISSUE TITLE
arduino-board TypeError: Cannot call method 'indexOf' & Cannot read property 'board'

### ISSUE THREAD

**Issue by rsrini7** [node-red/node-red#678]
I tried using arduino with my node-red running in my Ubuntu desktop (same error in my Rpi 2)

http://nodered.org/docs/hardware/arduino.html

Welcome to Node-RED
===================

14 Jun 13:30:20 - [info] Node-RED version: v0.10.6
14 Jun 13:30:20 - [info] Node.js  version: v0.10.25
14 Jun 13:30:20 - [info] Loading palette nodes
14 Jun 13:30:20 - [warn] ------------------------------------------
14 Jun 13:30:20 - [warn] Failed to register 2 node types
14 Jun 13:30:20 - [warn] Run with -v for details
14 Jun 13:30:20 - [warn] ------------------------------------------
14 Jun 13:30:20 - [info] User Directory : /root/.node-red
14 Jun 13:30:20 - [info] Flows file     : /root/.node-red/flows_rsrini-desktop.json
14 Jun 13:30:20 - [info] Server now running at http://127.0.0.1:1880/
14 Jun 13:30:20 - [info] Starting flows
14 Jun 13:30:20 - [error] [arduino-board:d7663aaf.47194] TypeError: Cannot call method 'indexOf' of undefined
14 Jun 13:30:20 - [error] [arduino-board:d7663aaf.47194] TypeError: Cannot call method 'indexOf' of undefined
14 Jun 13:30:20 - [error] [arduino out:dd959280.226a7] TypeError: Cannot read property 'board' of null

Then i copied the Blink 2 from the same site: node-red crashed with below exception.
================================================================

14 Jun 13:56:32 - [red] Uncaught Exception:
14 Jun 13:56:32 - Error: Serialport not open.
    at SerialPortFactory.SerialPort.write (/usr/local/lib/node_modules/arduino-firmata/node_modules/serialport/serialport.js:288:17)
    at ArduinoFirmata.module.exports.ArduinoFirmata.write (/usr/local/lib/node_modules/arduino-firmata/lib/arduino-firmata.js:170:30)
    at null.<anonymous> (/usr/local/lib/node_modules/arduino-firmata/lib/arduino-firmata.js:135:26)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

I have seen the same issue in https://groups.google.com/forum/#!msg/node-red/VRSAwbn0EUs/XDsnlYWyyj4J

My Arduino : lsusb
Bus 003 Device 008: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter

I tested the same device with the Arduino IDE. Works well.

**Comment by knolleary** [comment]
As mentioned in that thread you link to, a fix for this has been pushes to git and will be in the next release available in the next couple days.

**Comment by rsrini7** [comment]
Thank you.
