### ISSUE TITLE
How do you stop deploying?

### ISSUE THREAD

**Issue by Blackvibes** [node-red/node-red#683]
Seriously, I've almost broken my keyboard and trackpad because I'm seriously getting crazy as I can't find a way to stop deploying my Node-Red workflow. Once you pressed the 'deploy' button there is no way back. Yes, by adjusting anything. Which sometimes I don't want to.

Is it really that strange that someone wants to stop deploying their workflow without a change?

**Comment by dceejay** [comment]
Hi, normally we prefer general questions on the mailing list.
Currently you can't stop a flow from the editor without deploying a blank flow.
Though you can ctrl-break in the console.- the browser can still then carry on editing - as long as you don't try to reload, and obviously you have to restart to then save/deploy the edited flow... so not recommended....

and yes... normally we find people want flows to keep running as long as possible without breaking :-)

**Comment by knolleary** [comment]
Hi @Blackvibes,  as @dceejay says, questions like this are best suited on the [mailing list](https://groups.google.com/forum/#!forum/node-red). Given this isn't an 'issue' for us to fix, I'm going to close.

If you do have any follow ups, please do post them on the list.

Cheers, Nick

**Comment by mcahornsirup** [comment]
I just started using node red and I love it! Really! Great work... but I was looking for a way to stop node red from executing my workflow, too. Something like a pause or a undeploy button : )

Maybe, this is something only node red first time users want, but it was exactly what I was looking for , too.

**Comment by RuRu92** [comment]
I also find it a bit stressful when I cant stop the flow from executing on a loop. Especially when prototyping and testing many different configurations for a custom project on Arduino. 
I end up needing to ctrl+c and then delete the file and start again. 

Would really appreciate the options to stop the flow, it also pollutes the console log/debugger.
Please take this into the consideration, I don't think it should be hard to implement. Would defiantly stop from going crazy. Also rather annoying that it start the flow on "node-red" command. Would have been good if it loads the flow, but requires the command to start.

**Comment by SalehAly** [comment]
+1

**Comment by kubark42** [comment]
Stopping node-red is an issue which many people seem to want, and the workarounds are non-obvious and, arguably, have undesirable side-effects. If I were interacting with the physical world I would always want to be able to stop my devices.

Since publishing a blank page "stops" the deployment, it would seem simple to have a stop button which automatically publishes a blank page. Not perhaps the sexiest solution, but a simple fix which could live on the deploy button, below the other deployment options.
<img width="460" alt="screen shot 2017-01-03 at 1 42 02 pm" src="https://cloud.githubusercontent.com/assets/1118185/21618739/6defc568-d1ba-11e6-91f4-e71ce76fae39.png">

@dceejay, @knolleary, could this issue be reopened?

**Comment by knolleary** [comment]
This issue won't be reopened. If you'd like to discuss the requirement in general, please head over to the mailing list to discuss.

**Comment by kubark42** [comment]
> If you'd like to discuss the requirement in general, please head over to the mailing list to discuss.

I appreciate the offer, but signing up for a mailing list probably isn't the right thing for my level of involvement. Best of luck!

**Comment by nguyetha0725** [comment]
Hi @Vilscon , I don't know if I have found the solution to stop Node red from debugging or not. However, I just deactivated the "debug" node. Then it'll stop sending messages.
Hope it helps.

**Comment by Lopatin-Viktor** [comment]
> Серьезно, я чуть не сломал клавиатуру и трекпад, потому что серьезно схожу с ума, поскольку не могу найти способ остановить развертывание рабочего процесса Node-Red. После того, как вы нажали кнопку «развернуть», пути назад нет. Да, подправив что-нибудь. Иногда я не хочу этого делать.
> 
> Неужели это действительно так странно, что кто-то хочет прекратить развертывание своего рабочего процесса без изменений?

node-red --safe

**Comment by bachphi** [comment]
Kubark answered is bit ... undesirable.
Where as githubwei's solution is appreciated.
