### ISSUE TITLE
Add arrow at the end of links

### ISSUE THREAD

**Issue by serramat** [node-red/node-red#691]
Hi, is it possible to add an arrow at the end of links that indicates the orientation of links?

Thanks.

**Comment by knolleary** [comment]
Hi, for general questions, please use the [mailing list](https://groups.google.com/forum/#!forum/node-red). We use this list to track issues.

All links flow in the same direction; from the right-hand edge of a node to the left-hand edge of the next node. I appreciate for some cultures that is not necessary the 'natural' direction of flow, but that's what we have.
