### ISSUE TITLE
Cannot deploy. Error on red.min.js

### ISSUE THREAD

**Issue by remedix** [node-red/node-red#692]
Hello,

I transferred my settings/flows/configs from version 0.9.3 or something to the latest build.

Now I am on the latest version but I can't deploy. I get the following js error on the browser:
red.min.js:16 Uncaught TypeError: Cannot read property 'type' of undefined

Also I noticed on the code that the red.min.js file is loaded like
<script src="red&#x2F;red.min.js"></script>

I know that doesn't matter and still gets loaded but I thought I'll let you guys know.

**Comment by knolleary** [comment]
Hi, can you provide the full stack trace of that error from the console?

(also your comment about how the file is loaded appears cut off...)

**Comment by remedix** [comment]
Hey, here it is (apologies for the screenshot)

![9he_vhcki8x9dvwk9la6qe2k0e66lhf-ngmxfxdnp9e](https://cloud.githubusercontent.com/assets/516076/8451965/f554dc7e-1fef-11e5-806c-39e71a5b8e1a.png)

Here the text that was cut off `<script src="red&#x2F;red.min.js"></script>`

**Comment by knolleary** [comment]
d'oh - of course with the minified version, that isn't very helpful.

If you backup your flows file, then delete it so it starts with a clean workspace, restart everything do you get any further?

**Comment by remedix** [comment]
Ok thanks, that did the trick. I copied to clipboard the flows, backed up my flows and then deleted the files. Restarted the service and then imported the flows from clipboard. You may close this issue :)

**Comment by knolleary** [comment]
If you have that backup, and happy to share, can you send it to me? nick.oleary@gmail.com - would be interested to understand what broke. No worries if not.

**Comment by remedix** [comment]
No sorry I deleted the backups once it worked. I'm guessing it's the config I had for the pubnub package.
