### ISSUE TITLE
creating a new node

### ISSUE THREAD

**Issue by tkb123** [node-red/node-red#693]
I want to create my own node (similar to sentiment node) which does some classification. My questions are : 

1. I want to do the processing in R. So how can I write the main logic of the node in R or Python.

2. I want to link my node to (allow access to) some Bluemix service. How to do that. e.g. the way sqldb node can be linked to a Database Service in Bluemix.

Any examples please refer me. I am new to this.

**Comment by hardillb** [comment]
Please use the mailing list for questions like this:
https://groups.google.com/forum/#!forum/node-red

The documentation for creating nodes can be found here:
http://nodered.org/docs/creating-nodes/

Issues are being used for actual defects.
