### ISSUE TITLE
Inject at specific time node is run twice instead of once

### ISSUE THREAD

**Issue by jpwsutton** [node-red/node-red#695]
I have an inject node that is set to trigger at 01:00 AM every morning to generate a report. I checked my database this morning and can see that the report was actually generated twice, once at 12:59:59 and again at 01:00:01.

I've exported the node config below if that helps:

```
[{"id":"7b9640a8.09254","type":"inject","name":"Trigger Report","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"00 01 * * *","once":false,"x":111.5,"y":100,"z":"b679d96.f498628","wires":[["8219c200.592608"]]}]
```

**Comment by knolleary** [comment]
Odd. Was it definitely last night this happened and not a couple nights
ago? Am wondering if this was an artifact of the leap second that was added.

**Comment by jpwsutton** [comment]
Ah possibly. It was definitely last night as I only implemented it yesterday morning. I'll watch it again tonight to see if it happens again.

**Comment by jpwsutton** [comment]
Strangely, this has resolved itself. The inject node ran twice on Saturday Morning, and twice on Sunday morning. But only once this morning.
