### ISSUE TITLE
Import external module

### ISSUE THREAD

**Issue by davidebene** [node-red/node-red#696]
Hi. I'm trying to import an external module, instantiating it in settings.js as follows:

functionGlobalContext: {
        node-telegram-bot-api:require('node-telegram-bot-api')
    },

but running node-red, I get the following error:

/usr/local/lib/node_modules/node-red/settings.js:151
        node-telegram-bot-api:require('node-telegram-bot-api')
            ^
[SyntaxError: Unexpected token -]

removing the dashes instead I get:

"Unable to load settings file: ./settings"

Thanks!

**Comment by hardillb** [comment]
The Syntax Error is definitely down to the hyphens as these are not allowed in object keys.

The second issue is most likely down to some other formatting error in settings.js.

Does it work if you take all of line 151 out again? 

Also can you paste in the functionGlobalContext block as it is now

**Comment by davidebene** [comment]
Yes, removing the line node-red works again (i.e. functionGlobalContext: { } ).

However if I remove the hyphens from the object, line 151 becomes for example:

telegram:require('node-telegram-bot-api')

but I get the error above ("Unable to load settings file: ./settings").

**Comment by knolleary** [comment]
Where have you npm installed the module you are trying to require? You should have run the install from the directory that contains your settings file.

**Comment by davidebene** [comment]
Yes, actually installing it in the same directory now the error disappears.

But now if I reference the module in the function (i.e. context.global.telegram) , I get the following error:

ReferenceError: TelegramBot is not defined (line 5, col 15)

where TelegramBot(...) is a class of the new module..

**Comment by davidebene** [comment]
No, sorry, my mistake. I should referencing in this way:

var TelegramBot = context.global.telegram;

Solved, thanks!
