### ISSUE TITLE
Deleting configuration nodes

### ISSUE THREAD

**Issue by Stwissel** [node-red/node-red#699]
Problem: left over configuration node.

Steps to reproduce:

-  create a page
- add nodes to it that have configuration nodes (e.g. mqlight)
- deploy once
- delete the page: all nodes get deleted, except the configuration nodes

Suggested solution: provide a delete button in the sidebar to be able to delete configuration nodes.

**Comment by knolleary** [comment]
Solution:
 - select `sidebar menu -> configuration nodes`
 - a list of all your config nodes appears in the sidebar
 - dbl click on each to open its edit dialog and click delete.

**Comment by Stwissel** [comment]
Ah... missed that one. Thx a lot!

**Comment by Babavali** [comment]
select sidebar menu -> configuration nodes
a list of all your config nodes appears in the sidebar
dbl click on each to open its edit dialog and click delete.

Thx a lot for this 
How this be done by command line 
like npm uninstall package-name

**Comment by knolleary** [comment]
@Babavali please use the mailing list for question rather than long-closed issues.
