### ISSUE TITLE
File node and numbers

### ISSUE THREAD

**Issue by drJeckyll** [node-red/node-red#700]
File node is inconsistent when msg.payload is integer. 
For example if I put msg.payload = 0 then it will never be written to disk. File is left intact.
But it works fine if msg.payload = "0". Sometimes it works with msg.payload = 1, sometimes not. 
I have couple of flows which stop to save files after upgrade to node-red 0.10.10. It worked before with old version which was pre 0.10.4, but I don't know which version it was exactly.

**Comment by hardillb** [comment]
When you say it's inconsistent how are you checking for the change to the file? Is it from in the same flow?

**Comment by dceejay** [comment]
Ben,
we (I) added a check to make sure there was a payload before proceeding... but it was a dumb check...
aka 0 will equate to false...  oops... 
will fix.

**Comment by drJeckyll** [comment]
ls file.name
timestamp is the same, content is the same as before ... it is just not written to disk

**Comment by drJeckyll** [comment]
Thanks

**Comment by dceejay** [comment]
... works for me... but.... please re-open if not... :-)
