### ISSUE TITLE
The serialport@1.7.4 failed installation for the NR 0.11.1 production - "npm install --production"

### ISSUE THREAD

**Issue by NNM11** [node-red/node-red#706]
I created a node-red embedded application for Windows UAP.  To flat down the node_modules folder for the Windows MAX_PATH problem, I used npm dedup and attempted to use "npm install --production" to reduce the bloat test code in node-red.  
1. download the latest node-red-0.11.1.zip and unzip to my project folder.
2. open a Admin command windows and run "npm install --production"
3. At the end, the npm@3.1 reported error on the serialport and ask to tell the author about the error.

Attached is the log view
![image](https://cloud.githubusercontent.com/assets/12702095/8809322/ce52458c-2f9c-11e5-944b-2cacbc62694c.png)

**Comment by knolleary** [comment]
Hi,

It's asking you to notify the maintainer of the 'serialport' module, not
the node-red-node-serial module. Not much we can do about it in our package.

Nick

**Comment by MarkHerhold** [comment]
Can the serialport package be decoupled from the core package?

The less things that require node-gyp the better.

**Comment by knolleary** [comment]
@MarkHerhold node-red pulls in node-red-node-serialport as an optional dependency - https://github.com/node-red/node-red/blob/master/package.json#L60 - specifically so that it won't cause the main node-red install to fail if it hits issues such as this.

We have not tested with npm 3 yet, so that may be causing some changes in behaviour here.

**Comment by NNM11** [comment]
I was under the impression that the "--production" option suppose to install only the essential packages for node-red.  I ran into the nested node_modules MAX_PATH compatibility issue with Windows and someone recommended that I should use the "--production" argument to strip out the testing and optional modules.  Which is mostly the cause of the deep nested node_modules.  

If the "--production" option produces a smaller node-red footprint; it will help with deploying node-red in the limited capability device.

**Comment by knolleary** [comment]
@NM11 `--production` skips the development dependencies (as [our documentation says to use](http://nodered.org/docs/getting-started/installation.html)), which does indeed help with the path length issues.

It does not skip the optional dependencies.

The changes in npm 3.0 to flatten the modue layout will be welcome.

**Comment by MarkHerhold** [comment]
@knolleary Thanks for pointing that out. My mistake.

**Comment by dceejay** [comment]
Fyi... The  --production flag only doesn't load the test deps of the main package.... Any required packages are still loaded in full..
 So in our case it doesn't actually make the path length any shorter as some of the deps like express, WS and serial port themselves have large numbers of sub dependencies, that add to the length of their paths....
