### ISSUE TITLE
Configuration nodes - Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by jeffdonthemic** [node-red/node-red#709]
I'm running node 0.12.2 and node-red 0.11.1 locally and on heroku and bluemix. My configuration node works fine locally, however on heroku and bluemix the new configuration modal fails to popup and Chrome console shows `Uncaught TypeError: Cannot read property 'set' of undefined`. See [this short video](http://screencast.com/t/mTCnysThd).

[Here's the offending code](https://github.com/jeffdonthemic/node-red-contrib-salesforce/blob/master/soql.html#L8). It seems to be only if the code is installed from npm?

**Comment by knolleary** [comment]
You haven't included `connection-config` in the declared nodes in your [package.json](https://github.com/jeffdonthemic/node-red-contrib-salesforce/blob/master/package.json#L19).

We don't tend to have config nodes declared in files separate to the nodes that use them, so not hit this particular scenario before. The editor should provide a better error message.

**Comment by jeffdonthemic** [comment]
Bingo! That did the trick!

I wasn't sure if I needed it in the package.json since it was a config node and I couldn't find any other nodes that included it.

 Thanks.

**Comment by knolleary** [comment]
As per my comment, the editor could provide a better message for this which is why the issue stayed open.
