### ISSUE TITLE
What is the format for settings.js?

### ISSUE THREAD

**Issue by dbarowy** [node-red/node-red#710]
Could you put a pointer to the [default `settings.js`](https://github.com/node-red/node-red/blob/master/settings.js) in the [configuration page](http://nodered.org/docs/configuration.html)?  The configuration page does not actually tell you what the `settings.js` format actually is.

I went through a dozen iterations of something JSON-like resulting in parser errors.   I even tried the snippet from the page about embedding node-red with no luck.  Eventually I found a mention on _somebody else's_ page about the "default `settings.js`" which prompted me to look in your git repository where I found the answer.  Alternately, a complete example of a valid `settings.js` would be helpful.

**Comment by knolleary** [comment]
There are actually a couple things we could do here.

1. absolutely agreed, the docs could be more helpful - it made more sense before we supported npm installing node-red, so the default settings file would be more obvious. But the docs haven't kept up in this area.

2. if a user doesn't specify their own settings file on startup, and we are creating their $HOME/.node-red directory (ie, its the first run), we could copy the default settings.js file over.

**Comment by dbarowy** [comment]
Option 2 is a good idea.  In fact, I sort of expected this to happen, because when you start up `node-red` with no arguments, it says:

```
Welcome to Node-RED
===================
30 Jul 17:33:58 - [info] Node-RED version: v0.10.10
30 Jul 17:33:58 - [info] Node.js  version: v0.10.39
30 Jul 17:33:58 - [info] Loading palette nodes
30 Jul 17:34:01 - [info] Settings file  : ./settings
...
```

But if you go looking for `settings` in the current directory, it is not there.

**Comment by knolleary** [comment]
Have updated the docs here: http://nodered.org/docs/configuration.html

The proposed code change is a bit more involved due the way we abstract the storage mechanism. Also need to make sure we only copy the file over when it makes sense to do so.

**Comment by dbarowy** [comment]
Fantastic.  Thanks!
