### ISSUE TITLE
Unable to start-up node-red

### ISSUE THREAD

**Issue by ProgramErgoSum** [node-red/node-red#712]
I have followed the instructions to install `node-red` on Ubuntu 64-bit, 14.04 VM. It has been installed with `npm` global install option. And yet, when I type `node-red` on command line, I do not see any console output. Nor do I see any response when browser is opened at `http://localhost:1880`.

What is missing?

**Comment by knolleary** [comment]
Do you get any output at all when you run the command?

**Comment by ProgramErgoSum** [comment]
No, I don't. Tried with the `sudo` command too. Nothing. BTW, did you want me to close this and open on Google Groups?

**Comment by knolleary** [comment]
so the command just returns instantly? Odd.

Yes, please use the mailing list for this sort of support question.

**Comment by ProgramErgoSum** [comment]
This worked. http://stackoverflow.com/a/25774929 

Closing this thread now.
