### ISSUE TITLE
prevent accidental drags of UI elements from triggering flow import

### ISSUE THREAD

**Issue by mblackstock** [node-red/node-red#713]
I tried dragging parts of the UI into the main pane: tabs, the info box tab, debug box tab, the deploy button. Some UI elements are not draggable in this way, while others that are don't show a grey box (e.g. the zoom controls), and cause different error messages such as "Error: Invalid flow: Unexpected token i" on drag release.

@knolleary - This is because we support drag and dropping a flow json straight into the editor. We need to find the right incantation to prevent accidental drags of ui elements from triggering the flow import.

**Comment by knolleary** [comment]
Doing some old-issue tidy up. I think we're pretty good for avoiding accidental drags now - most UI elements have text selection disabled.
