### ISSUE TITLE
JavaScript editor using Chrom browser on Mac OS has issue for editing.

### ISSUE THREAD

**Issue by ibmamnt** [node-red/node-red#718]
One of the user of Node-RED reported that JavaScript editor ( function node ) is not usable. There is a problem in cursor position. For example, put the mouse cursor among the code, and then try to edit goes to different place.

Env: Mac OS
Browser: Chrom

If you need additional details, I can ask the developer to report the detail.

**Comment by shemethy** [comment]
Function node editor seems to work fine for me on latest OSX / Chrome / Node-Red.

**Comment by knolleary** [comment]
Please provide lots more information, such as steps to recreate, versions of node-red, chrome etc.

I develop using chrome on osx and have never seen anything like this.

**Comment by dceejay** [comment]
@ibmamnt,
any more info on this ? or can we close ?

**Comment by ibmamnt** [comment]
Oh, sorry. I asked the user to input. But looks like he did not respond to write error. OK to close for now.

**Comment by PearceDuan** [comment]
My friend and I meet the same problem on Ubuntu system, I also try with firefox, but seems useless. 
Chrom Version: 51.0.2704.79 Ubuntu 15.10 (64-bit)
node-red version: 0.17.3

**Comment by t-oster** [comment]
I have the same problem. Chrome and Firefox on Arch-Linux. I suspect something with the ACE Editor not using a monospaced font like here: https://stackoverflow.com/questions/15183031/ace-editor-cursor-behaves-incorrectly.

**Comment by t-oster** [comment]
I found the culprit: It is a problem with monospaced fonts. However if I change the css to just `font-family: monospace` it does not work. The original line is: `Menlo, Consolas, 'DejaVu Sans Mono', Courier, monospace !important` and if I remove `Menlo, ` it works. Maybe there is a non-monospaced font named Menlo on Linux? If I use monospace in Inkscape it does not look monospace, so maybe my font configuration is messed up.

**Comment by dceejay** [comment]
good debugging. thanks
