### ISSUE TITLE
Node 4.0.x support

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#721]
Issue #565 was the epic task of bringing Node-RED up to Node.JS 0.12. But time has moved on, and now Node.JS is up to 4.0.0.

Here's a spot for issues identified and observed.

**Comment by vielmetti** [comment]
Travis now supports Node 4.0.0. I did a build here

https://travis-ci.org/vielmetti/node-red/jobs/79350053

(completely naively, to see if it would just work). The result has a lot of errors in it, many of which are from the "NAN" module. https://github.com/nodejs/nan which is used to compile native code dependencies. That module was recently upgraded & it stands to reason that anything that depends on it probably needs to be given a good look.

**Comment by knolleary** [comment]
Indeed - NAN is highlighted as one of the main migration issues - https://nodejs.org/en/blog/release/v4.0.0/

**Comment by vielmetti** [comment]
One of the modules that's dealing with this is node-serialport - see https://github.com/voodootikigod/node-serialport/issues/573 for an open upstream issue, which also affects the johnny-five folks.

**Comment by vielmetti** [comment]
This pull request for node-serialport https://github.com/voodootikigod/node-serialport/pull/566 illustrates some more of the issues, specifically with Travis - apparently the new V8 support requires gcc compiler features that aren't in the default gcc used by Travis.

@rvagg has a workaround here: https://github.com/voodootikigod/node-serialport/pull/566#issuecomment-138393439

**Comment by vielmetti** [comment]
One more note, that gcc 4.8 is going to be needed to build add-ons for Node.JS 4.x, per https://github.com/nodejs/hardware/issues/16#issuecomment-138708094 - this is notable because the Raspberry PI and Beaglebone ship with gcc 4.6.x

**Comment by rvagg** [comment]
ah, but raspbian wheezy ships an optional 4.8 you can easily install, `apt-get install gcc-4.8 g++-4.8` then update-alternatives to hook them in as the default

**Comment by vielmetti** [comment]
I'll also note that node-sass is dealing with its port to Node 4.x https://github.com/sass/node-sass and we'll end up waiting until that gets sorted. https://github.com/sass/node-sass/issues/1122 is the relevant issue upstream to track.

**Comment by xzyfer** [comment]
The node-sass team has backported the Node 4 binaries to v3.3.2.

**Comment by yosuke-furukawa** [comment]
We are listing Node v4.0 issues in this thread. If you find any other issues, please write the issue and add the following url.
https://github.com/nodejs/node/issues/2798

**Comment by vielmetti** [comment]
As noted in the previous item, Travis CI builds a lot of stuff at node 4.0.0, but errors out in the Trigger node with

Fatal error: Cannot assign to read only property '_onTimeout' of infinite

https://travis-ci.org/vielmetti/node-red/jobs/80156474 is the build log, for what it's worth.

**Comment by vielmetti** [comment]
Thanks @dceejay for the suggestion that turned into this commit

https://github.com/vielmetti/node-red/commit/e6997f639af2475a951c3bf55eea735cc74cfe37

which fixed that error in 89-trigger.js.

The tests continue on with this error:

```
   file in Node
  ✓ should be loaded
  ✓ should read in a file and output a buffer
  ✓ should warn if no filename set (152ms)
Fatal error: expected 'Error: ENOENT: no such file or directory, open \'badfile\'' to start with 'Error: ENOENT, open' 
```

**Comment by vielmetti** [comment]
Also, the patch to Travis that allows it to build at all (and that allows for errors if 4.0.0 doesn't build, so your build stays green) is 

https://github.com/vielmetti/node-red/commit/941cc7773a48af83b374e7af22ae06fc70f4a7d3

**Comment by vielmetti** [comment]
This PR https://github.com/node-red/node-red/pull/724 passes the whole test suite, I think it's ready to look at.

**Comment by vielmetti** [comment]
Just in time for Node to announce 4.1.0 !

https://nodejs.org/en/blog/release/v4.1.0/

Looks like only minor bug fix changes, when the Travis environment supports it, I'll add a test target.

**Comment by vielmetti** [comment]
https://github.com/travis-ci/travis-ci/issues/4818 is the Travis issue.

**Comment by ashi009** [comment]
Please update [document](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/).

**Comment by knolleary** [comment]
@ashi009 sorry, we're not the Travis-CI project so cannot update their documentation for them

**Comment by ashi009** [comment]
@knolleary Oops, sorry, I didn't pay much attention.

**Comment by knolleary** [comment]
I have updated the travis build to always test against the latest Node 4.x.x level - as that is the LTS level.

All tests now pass reliably, although there is still one unexpected log message to look at:

```
 api auth middleware
    ensureClientSecret
      ✓ leaves client_secret alone if not present
      ✓ applies a default client_secret if not present
    revoke
      ✓ revokes a token
Potentially unhandled rejection [1] TypeError: Cannot read property 'end' of undefined
    at /Users/nol/code/node-red/node-red/red/api/auth/index.js:98:24
    at tryCatchReject (/Users/nol/code/node-red/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/nol/code/node-red/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/nol/code/node-red/node-red/node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/Users/nol/code/node-red/node-red/node_modules/when/lib/makePromise.js:702:24)
    at Scheduler._drain (/Users/nol/code/node-red/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/nol/code/node-red/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

Once I've fixed that, we can close this issue.

**Comment by knolleary** [comment]
That unexpected log message occurs with all levels of node... so not going to blame 4.x for it.

@vielmetti thanks for your help getting this done.

**Comment by vielmetti** [comment]
Glad to help, @knolleary !
