### ISSUE TITLE
browser run-time?

### ISSUE THREAD

**Issue by gbaumgart** [node-red/node-red#722]
is there any chance to run flows in the browser only? 
thanks!

**Comment by knolleary** [comment]
Hi, for general questions we have the [mailing list](https://groups.google.com/forum/#!forum/node-red).

In this instance, there is no chance of browser only flows. Our nodes depend on the node.js runtime environment.

**Comment by gbaumgart** [comment]
ok, thanks. what a pity, it looked promising. did you checked out 'no-flow' ? it has a browser run-time...
