### ISSUE TITLE
Node (axis) - automated order/style/grid of the nodes in my flow

### ISSUE THREAD

**Issue by Discero** [node-red/node-red#723]
Is it possible to order my nodes in an automatic way? The flows i created are irritating me by the lack of (a symmetric/clear) visual structure. I assumed this would be possible by exporting and importing my code, but the x and y info of the nodes in my flow are included in the (default) exported code.

Example: [{"id":"22e3d2a0.dd1c2e","type":"inject","name":"","topic":"start","payload":"","payloadType":"none","repeat":"","crontab":"","once":true,"x":240,"y":61,"z":"ae000545.51fff8","wires":[["1b0cebf8.e4f314"]]},{"id":"1b0cebf8.e4f314","type":"change","name":"","rules":[{"t":"set","p":"payload","to":"test"}],"action":"","property":"","from":"","to":"","reg":false,"x":1154,"y":175,"z":"ae000545.51fff8","wires":[["405e93e4.bfa16c"]]},{"id":"405e93e4.bfa16c","type":"debug","name":"","active":true,"console":"false","complete":"payload","x":877,"y":404,"z":"ae000545.51fff8","wires":[]}]

**Comment by dceejay** [comment]
Hi,

we normally prefer more general discussions of this nature over on the Google group - https://groups.google.com/forum/m/#!forum/node-red .

There is already a thread on this topic here - https://groups.google.com/forum/m/#!search/rearrange$20nodes/node-red/g07guymloWQ
We currently have no plans to implement this ourselves, but if someone wants to write a flow preprocessor to rewrite the file before import that would be neat.

Note : you can align them manually by using drag/shift to click to a 10px boundary.
https://groups.google.com/forum/m/#!searchin/node-red/shift$20drag/node-red/qqOvPsDEznY

**Comment by Discero** [comment]
Much obliged. I never assumed the existence of a google group for node-red questions; a related search result never appeared while i was googling.

(The URLs towards the topics are broken; i can't open them. No problem though, i found those topics in the group).

**Comment by dceejay** [comment]
oops - have updated the links above correctly.
