### ISSUE TITLE
Arduino - johnny-five - Unable to load settings 

### ISSUE THREAD

**Issue by DarekLin** [node-red/node-red#727]
Hello,
I'm trying  to use  johnny-five library followed step by step on tutorial
http://nodered.org/docs/hardware/arduino.html
After settings update:

```
functionGlobalContext: {
        // os:require('os'),
        bonescript:require('bonescript'),
        jfive:require("johnny-five"),
        //j5board:require("johnny-five").Board({repl:false})
        j5board:require("johnny-five").Board({ port: "/dev/ttyACM0", repl:false })
  },
```

 install:
```

cd .node-red
npm install johnny-five

```

when I try  start the node-red i received:
```
root@beaglebone:~/.node-red# node-red-pi
##### Unable to load settings file: /usr/local/lib/node_modules/node-red/settings.js

```

I have installed :
Linux beaglebone 3.8.13-bone70
debian_version 7.9
 [info] Node-RED version: v0.11.1
 [info] Node.js  version: v0.10.38
 johnny-five@0.8.91

**Comment by dceejay** [comment]
do you also have the bonescript library installed ?

**Comment by DarekLin** [comment]
Yes, I have.

**Comment by dceejay** [comment]
If you revert the file / comment out those three lines... does it read and start ok ?
Add them back one at a time  (removing/adding trailing commas as necessary... should reveal which line is causing the breakage.
Does your user have permissions/access to /dev/ttyACM0 ?

**Comment by DarekLin** [comment]
So, each of the  uncommented  line:
```
 jfive:require("johnny-five"),
 j5board:require("johnny-five").Board({repl:false})
```
 
caused error:
##### Unable to load settings file.

I'm working as root. Also, I noticed that  johnny-five scripts running in the same directory (.node-red), are working when I running script without node-red.
e.g

```
var five = require('johnny-five');
var BeagleBone = require('beaglebone-io');
```
I tried install johnny-five module on windows computer and achieve the same problem with update setting.

**Comment by knolleary** [comment]
Resolved on the mailing list - https://groups.google.com/d/msg/node-red/Z_WfA6oqokE/EVj8fZq4BQAJ
