### ISSUE TITLE
Epic: add AWS IOT support for Node-RED

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#733]
Amazon has announced an AWS IOT service with an SDK that has a messaging layer based on MQTT. It would be useful to interface with this system either as a consumer or producer (or both).

This isn't a small task, and maybe not even a completely doable task, but there are pieces parts that probably can be done directly or worked around.

The first hurdle is that AWS uses certs for auth for MQTT, something that's been noted before (at #202 ). As an illustration of how this is done in other systems, this post http://lodge.glasgownet.com/2015/10/09/aws-iot-with-mosquitto/ describes how to configure Mosquitto to work. In a pinch I guess you could feed messages out of Node-RED into `mosquitto_pub` with an `exec` node, to get through the credential issue.

Beyond that there are surely more things to deal with, and this item might be a spot to start that list.

**Comment by knolleary** [comment]
@vielmetti the only outstanding item is the ability for the user to provide their own TLS certs. We have issue #202 open for TLS support in the MQTT node, which the next release gets closer to.

If there is a follow-up specific problem to resolve, we can raise an issue to track that. There are many IoT platforms out there that we could create nodes for - we don't track them individually on this list.
