### ISSUE TITLE
setting 'align' in registerType causes a bug

### ISSUE THREAD

**Issue by jesusofsuburbia** [node-red/node-red#734]
So let's say you have the second argument for `RED.nodes.registerType`, an options object like:

```
RED.nodes.registerType('foo',{
        category: 'bar',
        defaults: {
            foobar: {value:"barfoo"}
        },
        inputs:0,
        outputs:0,
        icon: "foo.png",
        align : "left"    // <-- this here
});
```

... with the intention to set the icon of the node UI thingy to the left or right.
(It's described this way [here in the documentation](http://nodered.org/docs/creating-nodes/node-html.html))

This will cause a misalignment of the `<text>`-tag in the UI!
If you set `align` to "left", the text will also be left-aligned, not right-aligned.
To be specific `text-anchor="end"` should be `text-anchor="start"`.

This error happens because the value `end` for `text-anchor` is set automatically if you set `align` to any value. Because the alignment is left by default (without overriding it), the coder might have expected `align` only to be set when you want to align to the right while writing the code for this.

Thus - It's a bug, and it happens
**[here](https://github.com/node-red/node-red/blob/master/editor/js/ui/view.js#L1362)**

Cheers

**Comment by knolleary** [comment]
Yes, well spotted. The default value is `left` and in our core nodes, we only set `align` when we want it set to `right`... hence the assumption in the code that has gone unnoticed.
