### ISSUE TITLE
/nodes api broken - RED undefined

### ISSUE THREAD

**Issue by ssadams11** [node-red/node-red#736]
localhost:1880/nodes 
 yields lots of
      Uncaught ReferenceError: RED is not defined
in the console and returns nothing

15 Oct 22:48:54 - [info] Node-RED version: v0.11.2
15 Oct 22:48:54 - [info] Node.js  version: v4.1.2

**Comment by knolleary** [comment]
We do not support node 4 yet. The next release will add it.
