### ISSUE TITLE
more modern editor for function node

### ISSUE THREAD

**Issue by nganani** [node-red/node-red#737]
I know this has been an ongoing effort - but it would be great to see auto complete and other expected modern features within NodeRED editor or possibly allow me to connect to my editor of choice when editing a function (or other) nodes that need the editor.

**Comment by knolleary** [comment]
What sort of thing do you mean by 'modern features'?

We currently use the [ACE editor](https://ace.c9.io/#nav=about) which has a lot of functionality included -  Equally, we're also looking at the Eclipse Orion editor as it continues to improve.

They are both very capable editor widgets - and I suspect we could do a better job of surfacing some of it.

Using an external editor isn't very feasible when running in the cloud. There is a node contributed by the community that uses external files for the Function nodes, so you can edit them externally - but that isn't a feature we plan to build into the core.

**Comment by knolleary** [comment]
Also, don't forget the [mailing list](https://groups.google.com/forum/#!forum/node-red) is there for this sort of discussion.

**Comment by dceejay** [comment]
control-space already does basic autocomplete...

**Comment by emiloberg** [comment]
If you want to connect it to your editor, may I suggest that you use [node-red-contrib-file-function](https://www.npmjs.com/package/node-red-contrib-file-function) which will read the function from a javascript file which you may edit in your favorite editor.

**Comment by nganani** [comment]
Thank you all! was not aware of the mailing list, will try to use it in the future. will have a look at node-red-contrib-file-function and the CTRL+Space

**Comment by knolleary** [comment]
In absence of concrete proposals, I'm going to close this issue; reopen if you think there's something more specific we should enable.

**Comment by nganani** [comment]
thanks again for your help and support
