### ISSUE TITLE
Websocket input node not unsubscribing properly

### ISSUE THREAD

**Issue by GSeva** [node-red/node-red#739]
This issue happens when you have a websocket input node, you make some changes on it and deploy it as "Modified Nodes" (Which only deploys modified nodes). Websocket server keeps sending messages to the previous node version, and to the new one as well.

UPD: here is a workaround for this one: https://github.com/GSeva/node-red/commit/c7fe5119c7342af7d0f7967811fde02c588d3dd1

UPD 2: another little bug i found is that websocket listener node emits "opened" event when socket is closed. Here is the fix: https://github.com/GSeva/node-red/commit/95c4355bdeab3b7f42d68e4f718e407a95f6d7da

**Comment by knolleary** [comment]
Thanks for spotting this.
