### ISSUE TITLE
RED.reset needed

### ISSUE THREAD

**Issue by kororo** [node-red/node-red#741]
Hi guys,

Under the hood of RED, you are able to init RED manually by:
var settings = {...};
RED.init(null, settings);
RED.start();
RED.stop();

But if you do another chain of commands:
RED.init(null, settings);
RED.start();
RED.stop();

Somehow the nodes inside are being executed twice. Is there any reason why? The situation is you have current same process with RED commands above being executed twice.

I am afraid I need to create another child process to have the RED commands above being called only once. Otherwise, a magical function RED.reset() would be great to have blank empty state.

Please let me know if anyone bumped to the same situation and issue i am having here.

Thanks
Rob

**Comment by knolleary** [comment]
Hi,

this is a whole area we need to work on. We've never formally documented the api for embedding node-red beyond that one example in the docs, and there are certainly some cases that won't work today such as this.

Rather than have issues for incremental api changes (see also #698), there is a broader item to consider what we want the API to look like as a whole and what capabilities it needs to expose.

Nick

**Comment by kororo** [comment]
Nice! Thanks for getting back so quick. I am still debugging what is the missing link here. Well the nature of JS making this difficult to track. Imagine, if one of the node implementation forgot to do clearTimeout, this will leave potential lost process. Hence, showing the symptom that I see here.

From my wild guess, I think it is best if RED is spin-ed up to another process so it can be killed as whole. But I will put some ideas if I have under the broader issue.

Thanks!

**Comment by knolleary** [comment]
Hi,

What are you trying to achieve by calling init/start/stop multiple times?

We cannot unload nodes that have been loaded without a complete restart of the node process, so it would not be possible to get to a completely blank state after it has been started.

I'd like to understand your requirements to see if they can be accommodated. But it may be your wrapping app would need to use child_process or similar to spawn the instances.

Nick

**Comment by kororo** [comment]
Hi knolleary,

I had been reading the codes, yep, there are lots of global variables which if we do multiple init/start/stop, RED will produce multiple duplicated nodes. As what you suggested, I have PM2 setup to have master and slave scheme. The RED will live in slave. The master will be responsible to stop and start the slaves.

The reason why I want to do multiple init/start/stop because I want to let my users to have RED as their logic application. I want to limit their logic to be run at specific time. Hence, I need a system to call init/start/stop multiple times.

I think to accomodate this functionalities, you may need to change lots of the codes. Maybe next major version? :)

Please feel free to close this ticket. Thanks!!
