### ISSUE TITLE
Unable to load i18n for external nodes

### ISSUE THREAD

**Issue by andrewsbrown** [node-red/node-red#742]
When nodes are added in `~/.node-red/nodes`, the i18n JSON file is never requested from the browser. I suspect that this is because the external node is named `node-red-some-feature` (and defined in files like `my-feature.js`) but registers a type like `sf in` when it calls `RED.nodes.registerType`. Is there a requirement that the file names and the type be the same? Is there a different behavior for nodes loaded from `~/.node-red/nodes`? Any help is appreciated, even just pointing me to which functions in `localfilesystem.js` happen when.

**Comment by knolleary** [comment]
There are two types of node:
 - 'local' nodes, which consist of the `.js`/`.html` files manually dropped into the nodes directory, and
 - 'packaged' nodes - which are properly packaged modules with a `package.json` and located under `.node-red/node_modules`

The i18n support doesn't extend to local files outside of the core set - it only supports those packaged as node modules with a package.json etc.

We don't plan to support i18n of local nodes as it is pretty trivial to package nodes - they just need the `package.json` creating and sticking under the `node_modules` directory. Packaging docs here: http://nodered.org/docs/creating-nodes/packaging.html

But do say if you think you've got a use case where going the packaged route isn't suitable - happy to discuss.

**Comment by andrewsbrown** [comment]
@knolleary, thanks for the quick reply. Quick clarification: by `.node-red/node_modules` you actually mean `node-red/node_modules`--i.e. the repo iself not the hidden file in the user's home directory?

**Comment by dceejay** [comment]
Either. You can npm install a packaged node either into your local .node-red directory or globally using npm install -g
I18n should work for both.

**Comment by dceejay** [comment]
Either. You can npm install a packaged node either into your local .node-red directory or globally using npm install -g
I18n should work for both.

**Comment by andrewsbrown** [comment]
Thanks!
