### ISSUE TITLE
function node proper cleanup

### ISSUE THREAD

**Issue by andrei-tatar** [node-red/node-red#744]
The function block sandbox exposes setTimeout to the function. The problem I'm having and I don't see treated in the code is that if the function node is deleted/changed/updated/etc., the timeout is not cleared automatically.

My suggestion is a wrapper around setTimeout that keeps the timer(s) internally and clears it on node close.

Also, why not also expose setInterval and clearInterval?

**Comment by hardillb** [comment]
Feature requests should be discussed on the mailing list (https://groups.google.com/forum/#!forum/node-red) where a bigger audience can participate, issues are being kept for actual defects.

setInterval work flows should probably be better done with a repeating inject node

**Comment by knolleary** [comment]
It is possible for a Function node to register its own 'on close' handler for clearing timers, but is easily overlooked - especially to novice users. It is one of the main reasons we didn't add setInterval - as that could easily lead to bad things.

But if the node could automatically clear such timers, it would a Good Thing. So fundamentally this is a good suggestion. So much so, I will get it into the imminent 0.12 release.

(Although Ben's comment still stands - we do prefer feature suggestions are raised on the mailing list in the first instance.... but I'll let this one go ;)

**Comment by andrei-tatar** [comment]
Great to hear that!
Sorry for the inconvenience but it seamed more like a bug, since the function was "leaking". Next time I'll pose on the mailing list.

**Comment by knolleary** [comment]
No problem - agreed this can be considered an issue when looked at from the right angle :eyeglasses: :bug:
