### ISSUE TITLE
Node-red Lost connection to server when i use a arduino output node

### ISSUE THREAD

**Issue by tangshuran** [node-red/node-red#746]
The node name is 'node-red-node-arduino'.
Whenever i use the node in the editor, node-red local server stop working automatically  without any warning after a while.
Anyone meet the same problem with me?

C:\Users\Shuran>node-red -v
7 Nov 16:57:02 - [warn]

Welcome to Node-RED
===================

7 Nov 16:57:02 - [info] Node-RED version: v0.11.2
7 Nov 16:57:02 - [info] Node.js  version: v0.12.7
7 Nov 16:57:02 - [info] Loading palette nodes
iotf-service-staging credentials not obtained...
neither iotf-service nor iotf-service-staging credentials were obtained...
7 Nov 16:57:04 - [warn] ------------------------------------------
7 Nov 16:57:04 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
7 Nov 16:57:04 - [warn] [tail] Not currently supported on Windows.
7 Nov 16:57:04 - [warn] ------------------------------------------
7 Nov 16:57:04 - [info] Settings file  : \Users\Shuran\.node-red\settings.js
7 Nov 16:57:04 - [info] User directory : \Users\Shuran\.node-red
7 Nov 16:57:04 - [info] Flows file : \Users\Shuran\.node-red\flows_tangshuran.js
on
7 Nov 16:57:04 - [info] Server now running at http://127.0.0.1:1880/
7 Nov 16:57:04 - [info] Starting flows
7 Nov 16:57:04 - [info] [inject:0.5s tick] repeat = 500
7 Nov 16:57:04 - [info] Started flows
7 Nov 16:57:10 - [info] [arduino-board:9f151e6d.60eae] connecting to COM7
7 Nov 16:57:15 - [info] [arduino-board:9f151e6d.60eae] connected to COM7
7 Nov 16:57:15 - [info] [arduino-board:9f151e6d.60eae] version 2.4

C:\Users\Shuran>

**Comment by knolleary** [comment]
Hi, sorry for not responding sooner.

No-one has reported this sort of behaviour before. Is it still an issue for you?

**Comment by knolleary** [comment]
With nothing to go on, am going to close. Please reopen if you are still having issues.
