### ISSUE TITLE
i18n - NLS messages are displayed incorrect

### ISSUE THREAD

**Issue by jwende** [node-red/node-red#747]
I've started to create a German version of the editor.json file and I recognized that German 'Umlaute' are displayed incorrectly.
How do you load the language files (I don't think that we need to add unicode numbers into the NLS files ?)
Cheers
Joerg

**Comment by knolleary** [comment]
Can you provide an example of a language file that doesn't get displayed correctly? It will probably be an file encoding issue - although we did a test with random (non-ASCII) UTF8 characters and it worked.
