### ISSUE TITLE
i18n - editor.json incomplete

### ISSUE THREAD

**Issue by jwende** [node-red/node-red#748]
Hi,
looks like that editor.json does not contain all properties of the UI elements:
- debug tab name
- debug tab selection
- confirm deploy dialog
- edit node properties dialog

Cheers
Joerg

**Comment by knolleary** [comment]
The debug tab is contributed by the Debug node, so its messages live in the node message catalog [here](https://github.com/node-red/node-red/blob/master/nodes/core/locales/en-US/messages.json#L113).

Confirm Deploy messages are [here](https://github.com/node-red/node-red/blob/master/locales/en-US/editor.json#L85).

Edit node properties dialog:
 - the generic dialog messages are [here](https://github.com/node-red/node-red/blob/master/locales/en-US/editor.json#L113)
 - nodes then contribute their own messages for the internal content of the dialog - the core nodes message catalog is [here](https://github.com/node-red/node-red/blob/master/nodes/core/locales/en-US/messages.json) (same as the Debug node link above)
