### ISSUE TITLE
node-red command won't work after npm install

### ISSUE THREAD

**Issue by dbaba** [node-red/node-red#749]
`node-red` command won't work by default when Node-RED is installed with `npm install -g node-red`.
Please fix the issue. The tested version is [0.12.1](https://github.com/node-red/node-red/releases/tag/0.12.1).
The detail is shown below.

As root user, I ran the following commands as the [guide](http://nodered.org/docs/getting-started/installation.html) showed me.
```
# npm install -g --unsafe-perm node-red
# node-red
```
And got the following message.
```
Node-RED has not been built. See README.md for details
```
Node-RED wouldn't start because [`red/red.js` looked for a file `../public/red/red.min.js`](https://github.com/node-red/node-red/blob/master/red%2Fred.js#L34), which was never generated unless `grunt ` was performed.

With the current [package.json](https://github.com/node-red/node-red/blob/master/package.json), `npm install` never generates such the file.

**Comment by knolleary** [comment]
Hi,

I'm not able to reproduce this - the package published to npm has been properly built and installs fine in our of our tests.

You would get this error if you simply cloned the git repository and ran npm install - as our docs say, you also need to run grunt to build the code - http://nodered.org/docs/getting-started/installation.html#for-development---from-github

Can you provide any more details to help us understand the scenario? What version of node.js/npm are you using?

**Comment by dbaba** [comment]
Thank you for the response!
After several trials, it worked in the end.

The cause was `npm`, which was too old, v1.4.8!
So,
```
# npm install npm -g
```
solved the issue.

I guess the old `npm` couldn't understand `devDependencies`, which is why `grunt` and other `devDependencies` were not installed.

The tested device is Intel's edison with their latest OS, poky-yocto. But its npm is too old.

**Comment by dceejay** [comment]
This is odd. I just re-check on my Galileo board.
root@galileo:~# node -v
v0.10.38
root@galileo:~# npm -v
1.4.28

root@galileo:~# npm install -g --unsafe-perm node-red
followed by 
root@galileo:~# node-red
seems to be working fine.

**Comment by dbaba** [comment]
@dceejay You're right. I re-flashed the yocto/edison image and it worked as if nothing had happened.
So I think some data in my edison had seemed to be corrupted.
Thank you for the verification. It helped me!
