### ISSUE TITLE
ZMQ adapter

### ISSUE THREAD

**Issue by reddec** [node-red/node-red#752]
Hello developers!

I would like to help you with new modules: zeromq input/output nodes. Is it interesting for core modules?
I could provide a pull request.

**Comment by hardillb** [comment]
New nodes don't need to be added to the core any more.

Nodes should be npm packaged as described here:
http://nodered.org/docs/creating-nodes/packaging.html 
and published to npmjs.org

For discussions about if there is any interest in a new node you should really ask on the mailing list here:

https://groups.google.com/forum/#!forum/node-red

**Comment by reddec** [comment]
Thanks

**Comment by dceejay** [comment]
But yes... A zmq node would be great !

**Comment by reddec** [comment]
For future readers: I realized basic ZMQ adapter: [node-red-contrib-zmq](http://flows.nodered.org/node/node-red-contrib-zmq)

[Pull requests](https://github.com/reddec/node-red-contrib-zmq) are welcome (Sorry, but I do not have enough time for detailed implementation, so any help  will be great)
