### ISSUE TITLE
setTimeout does not return anything

### ISSUE THREAD

**Issue by leodesigner** [node-red/node-red#753]
Hi,
I have strange issue with setTimeout inside function node:

`
var ti = setTimeout(function(){ ....}, 1000);
node.log('timer: ' + ti);
`

returns 'undefined'

**Comment by knolleary** [comment]
Ah - yes, my fault. In 0.12 we wrapped setTimeout in the function node so we would automatically clear any outstanding timeout (likewise with setInterval) when the node is restarted. But the wrapper doesn't return the timer id. Will get it fixed for 0.12.2 we'll be releasing next week.

**Comment by leodesigner** [comment]
Thanks, meanwhile I will somehow rewrite a logic of the function.

**Comment by knolleary** [comment]
Fix pushed - you could patch your local copy by grabbing this file: https://raw.githubusercontent.com/node-red/node-red/master/nodes/core/core/80-function.js

Apologies for the inconvenience.

**Comment by leodesigner** [comment]
Wow, you are really fast :)
Thanks, I will do it right now.

**Comment by leodesigner** [comment]
Just tested, now it's working as it should.
Thanks again for excellent software.
