### ISSUE TITLE
mod_proxy websocket question

### ISSUE THREAD

**Issue by drJeckyll** [node-red/node-red#754]
I have a little stupid question: Except /comms which paths also Node-red websocket use?

I'm trying to put Node-red behind web server lighttpd with mod_proxy. I already setup websocket server and redirect /comms. Now in browser console it not longer says that /comms is 404, but I don't receive anything in debug tab of Node-red. So what I'm missing?

**Comment by knolleary** [comment]
Hi,

`/comms` is the only websocket end-point node-red uses. Not sure what else to suggest - not used mod_proxy before.

You will be better off asking this on the [mailing list](https://groups.google.com/forum/#!forum/node-red) as it will reach the wider community. As it isn't a bug with node-red, I'm going to close this issue.
