### ISSUE TITLE
Ledborg node

### ISSUE THREAD

**Issue by DrLucyRogers** [node-red/node-red#755]
Hello,

There's a problem when two or more ledborg nodes are on any flows on one pi - even if all but one node are disconnected. The PWM "fights" with itself and makes the brightness vary.

Also can't use the ledborg pins (11,13 and 15) (https://www.piborg.org/ledborg/specs) for anything else in other flows.

Can this be put in the "info" tab please?

Thanks

Lucy

**Comment by bigmonkeyboy** [comment]
Hi Lucy,
yes will do. 
PS - this issue should really be against the the node-red-node project - but hey :-)

**Comment by dceejay** [comment]
Hi Lucy,
yes will do. 

version 0.0.10 published to npm

PS - this issue should really be against the the node-red-node project - but hey :-)
