### ISSUE TITLE
node tcpget can't reconnect

### ISSUE THREAD

**Issue by fab33** [node-red/node-red#759]
If I physicaly disconnect my server, after socketTimeout, the timeout event raise and it try to reconnect after 10s (is it normal ?). If it's possible it works. But if connection come back later and you try to connect (by sending a new message), an error raise.
I'm not javascript expert but when you call client.end(), it doesn't raise "end" event. So when you hav a timeout, it raise only "timeout" and "error". But at the end, node.connected is always true !
I don't know if this bug is in others node (tcp-in tcp-out)
I'm patching my node with ugly code (adding node.connected = false in timeout and error event) so I let someone else to provide an "official" patch.
It will be fine to have a timeout event for tcp-in node with a paramter in ms to try to reconnect.
Hope you understand my bad english !

**Comment by natcl** [comment]
I'm getting a similar issue with the TCP Request node.  If I disconnect and reconnect the device I'm talking to, Node-RED will stop communicating with the device until I restart Node-RED.

**Comment by dceejay** [comment]
confirmed it's not working correctly. I can't recreate Nat's failure exactly but I suspect the not closing properly would also cause that.

**Comment by natcl** [comment]
Just tested the new code.
Seems to work better but it's still a bit strange.
If I disconnect my device, Node-RED still says it's connected and sending data doesn't seem to trigger any error.
If I reconnect my device, It won't work for a few seconds, then I'll get a connect failed message and it'll start working again.

**Comment by dceejay** [comment]
odd - for me - it stays "connected" - as it can't know otherwise until the main underlying tcp timeout. But as soon as I try to send data I get an error. I'll try another device tomorrow.

**Comment by fab33** [comment]
I think you have to remove L-501 -> L-506 or it have to be optional (checkbox config in node for example).

**Comment by dceejay** [comment]
ok - the reconnect is now immediate... (it has already waited for the tcp timeout already...)

**Comment by natcl** [comment]
Thanks !
Works great !
Still no error here when the device is disconnected but perhaps it's related to my network ?
Good news is that it reconnects fine.

**Comment by dceejay** [comment]
I think it's just the way TCP works... it waits for a timeout before it declares the packet lost... 
you can change the timeout in settings.js - default is null - which means do whatever the operating system does.
