### ISSUE TITLE
force deploy

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#76]
Sometimes, when a deploy fails, or the run-time crashes, you want to "re" deploy the current set of flows, even though the UI thinks it hasn't been edited.
Current "best practice" is to drag a debug node onto the palette, but a "force deploy" button, or rightmouse pull-down on the greyed out deploy button, or something, would be helpful.

**Comment by knolleary** [comment]
You can now nudge a node to enable the deploy button. There is also an Admin REST api end point for triggering a reload of the flows without having to post the full flow config back.
