### ISSUE TITLE
How to add node-config-type to a node programmatically?

### ISSUE THREAD

**Issue by kororo** [node-red/node-red#760]
Hi guys,

I would like to have extra config for my node. This config is used to keep tracking on the node operation logic. For example, I would like to track when was the node executed.

The only way that I can think of is to add another type of node-config-type/credential. As per document in here, http://nodered.org/docs/creating-nodes/config-nodes.html

I added a new config called "my-session" then manually create it from the dialog and finally I can do my get/update session from my JS by doing

```
// get session
this.session_node = RED.nodes.getNode(this.session);

// update session
RED.nodes.addCredentials(this.session, this.session_node.credentials);
```

From my understanding, the session node ID is only attached to the node when the Deploy button is pressed from the admin editor. Is there any way to add this by doing

```
// session_id is random ID if new, otherwise grab from the n object
// session_credential is the session object value
// existing_node_id is the node object which we should attach the session (credential) object to
RED.nodes.addCredentials(session_id, session_credentials, existing_node_id);
```

Thanks!!

**Comment by knolleary** [comment]
Hi, for general how-to... type questions, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red) and keep the issues list for things that need fixing.

Can you expand a bit more about what you want the session node to do? Do you expect it to store information across restarts for example? Do you have a concrete example to help us understand what you want to do.

Credentials is not intended to be used as a general store of session information.

**Comment by kororo** [comment]
Hi knolleary,

I will close and comment into the mailing list.

Thanks!!
