### ISSUE TITLE
integrating with loopback from strongloop

### ISSUE THREAD

**Issue by masalinas** [node-red/node-red#763]
I created a boot script to start node-red from loopback project, here is the script (node-red.js) situated on boot folder from loopback. The loopback app, is a expressJS extension (loopback documentation):

'use strict';
module.exports = function(app) {
  var RED;
  try {
    RED = require('node-red');
  } catch(err) {
    // Print the message only when the app was started via `server.listen()`.
    // Do not print any message when the project is used as a component.
    server.once('started', function(baseUrl) {
      console.log(
        'Run `npm install node-red` to enable the node-red back-end'
      );
    });
    return;
  }

  // Create the settings object - see default settings.js file for other options
  var settings = {
    httpAdminRoot:"/red",
    httpNodeRoot: "/api",
    userDir:".nodered/",
    functionGlobalContext: { }    // enables global context
  };

  // Initialise the runtime with a server and settings
  RED.init(app, settings);

  // Serve the editor UI from /red
  app.use(settings.httpAdminRoot, RED.httpAdmin);

  // Serve the http nodes UI from /api
  app.use(settings.httpNodeRoot, RED.httpNode);

  // Start the runtime
  RED.start();
}

Everything looks ok, strong loop start on default port 3000 I have access to:

   localhost:3000/explorer -> loopback JSON api
   localhost:3000/red -> node-red web editor

But when I access to  localhost:3000/red some seconds later I obtain error:
     Error: Lost connection to server

What is wrong in my script???

Regards.

**Comment by knolleary** [comment]
Hi,
The 'Lost connection to server' message is a sign the websocket between the editor and runtime is failing.

In order to setup the websocket listener, the first argument to `RED.init` needs to be an instance of [HTTP Server](https://nodejs.org/api/http.html#http_class_http_server). You are passing in `app` which has been passed into your module. I don't know what that is, but I bet it isn't an http server object.

As an aside, for general questions, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red), and keep this issue list for things that need 
fixing in node-red.

**Comment by masalinas** [comment]
Thanks, I agree with you I resolved the problem, obtaining the http server created by loopback and configuring the init node-red that you explain in the web. Now I start node-red integrated with loopback correctly

**Comment by knolleary** [comment]
As it sounds like you've resolve your problem, I'm going to close this issue. If you have any other questions, please use the mailing list.

**Comment by terehov** [comment]
Would be still great to know how you resolved that problem and where you got the http server from the app. thx!

**Comment by masalinas** [comment]
Here is the boostrap code:

```javascript
// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
// Red-node back-end
boot(app, __dirname, function(err) {
    if (err) throw err;

    // start the server if `$ node server.js`
    if (require.main === module) {
        var server = app.start();

        // Create the settings object - see default settings.js file for other options
        var settings = {
            // By default, the Node-RED UI is available at http://localhost:1880/
            // The following property can be used to specifiy a different root path.
            // If set to false, this is disabled.
            httpAdminRoot:"/red",
            // Some nodes, such as HTTP In, can be used to listen for incoming http requests.
            // By default, these are served relative to '/'. The following property
            // can be used to specifiy a different root path. If set to false, this is
            // disabled.
            httpNodeRoot: "/api",
            // By default, all user data is stored in the Node-RED install directory. To
            // use a different location, the following property can be used
            userDir:".nodered/",
            // Anything in this hash is globally available to all functions.
            // It is accessed as context.global.
            // eg:
            //    functionGlobalContext: { os:require('os') }
            // can be accessed in a function block as:
            //    context.global.os
            functionGlobalContext: {
                fs:require('fs'),
                moment:require('moment'),
                loopback: app
            }
        };

        // Initialise the runtime with a server and settings
        RED.init(server, settings);

        // Serve the editor UI from /red
        app.use(settings.httpAdminRoot, RED.httpAdmin);

        // Serve the http nodes UI from /api
        app.use(settings.httpNodeRoot, RED.httpNode);

        // Start the runtime
        RED.start();
    }
});

**Comment by terehov** [comment]
Thank you very much! :-)
