### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined (In SubFlow Editor)

### ISSUE THREAD

**Issue by ggeorg** [node-red/node-red#766]
Hi,

I get this error on a randomly (I think) in sub-flow editor. The exception happens in:
```
    function refresh(markChange) {
    }
```
line 202 
```
                while (n.outputs < n.ports.length) {
                    n.ports.pop();
                }
```
Node-RED version 0.12.2

A workaround that helps is surround the while with 
```
if (n.ports) { ... }
```
Kind Regards,
George.

**Comment by knolleary** [comment]
Thanks! Have tracked down what is causing this, fix arriving shortly.
