### ISSUE TITLE
Input File node will not retain the file name

### ISSUE THREAD

**Issue by austinibm** [node-red/node-red#767]
Reinstalled node-red 0.12.3 and updated node.js to v4.2.3 but found that  (input) File would not accept a filename, either as input or as an entry.  An entered filename consistently clears after OK.

**Comment by austinibm** [comment]
I neglected to also specify this is on Windows 7 OS.

**Comment by knolleary** [comment]
Just in case it's relevant, what browser are you using?

**Comment by austinibm** [comment]
Firefox

**Comment by knolleary** [comment]
Thanks for raising this. Pushed a fix and we'll release 0.12.4 tonight/tomorrow.

**Comment by austinibm** [comment]
Thank you very much.  I really appreciate you having looked into this and  addressing this so urgently.
