### ISSUE TITLE
How to write Range Date function in node-red

### ISSUE THREAD

**Issue by yogieputra8** [node-red/node-red#768]
So I connected nodered to my Cloudant (CouchDB) Database. 
In cloudant Iam using --> uSN:"100040004" AND timetag:[9102015 TO 12122015] to query the Data from  Date 9-10-2015 to 12-12-2015
Now, how can I write the function in node-red to make the query works?

My API righ now was like this: 

msg.payload = {
    "query" : "usn:" + msg.req.query.uSN + " AND timetag:" [+ msg.req.query.tt + " TO " + msg.req.query.tt ]
};
return msg;

and it doesn't work

**Comment by knolleary** [comment]
Hi, for general howto type questions, please use the mailing list (linked at the bottom of nodered.org).

The cloudant node isn't maintained by the core Node-RED project so this issues list isn't the best place to ask for help on it. The mailing list will reach a wider audience who can assist.

**Comment by hipersenil** [comment]
How about date range queries in general?. I got messages stored in a mongodb with timestamp. I amtrying to achieve something in the other of:

db.mydata.find({TIMESTAMP:{ '$gte':1508936424502, '$lte':1508936604501}})

But I do not know how to add the TIMESTAMP  field to the whole msg JSON structure in the JS function node before hitting the mongo node with the find operation. Any ideas?

**Comment by knolleary** [comment]
@hipersenil please see my comment above. The best place for general questions is the node-red mailing list or slack (linked from nodered.org) - not an issue that's been closed for almost 2 years!
