### ISSUE TITLE
Using authentication for httpStatic 

### ISSUE THREAD

**Issue by semsitivity** [node-red/node-red#770]
Hi,
I'm using httpStatic node-red conf to host an angularjs app for dashboarding. (by the way using the excellent http://ngmodules.org/modules/angular-dashboard-framework).
This dashboard application is using some http and websockets calls on node-red and everything works fine.
I need to add authentication and roles to this application, basically * for all rights and 'read', same as node-red.
Actually, I'd like to use the same authentication than adminAuth (with custom provider) but for httpStatic zone. I'm using same users and approximatively same rights.
I'm totally new to express, is it possible to do such things with node-red?

**Comment by knolleary** [comment]
Hi,

out of the box, no, we only offer the ability to secure httpStatic using Basic Auth and with a single user. Given the many ways users may want to secure their own content when using node-red, we couldn't be so prescriptive as we can be with our own admin api.

Whilst we'd like to make some of this easier in the future, today you would have to [embed node-red](http://nodered.org/docs/embedding.html) within your own express app and then apply whatever security you want to the routes yourself. Unfortunately I don't have quite the example you'd be looking for to help you along. Again, something we know we need to make easier to do.

By the way, for general how-to type questions, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red) and keep the issues list for bugs and the like.

**Comment by knolleary** [comment]
Hi - did you resolve this? As I said, we know we want to make authentication for http nodes easier to manage - with more options available. But that's a longer term thing than perhaps this issue warrants.

**Comment by knolleary** [comment]
Without anything specific to look at, going to close this issue.
