### ISSUE TITLE
sendfile vs. sendFile i ui.js

### ISSUE THREAD

**Issue by psvensson** [node-red/node-red#771]
I've embedded node-red in another project and everything worked perfect until the build-step, when we roll everything into a node-webkit platform-specific stand-alone executable- Yes, me too. It's amazing it works at all :)

Anyway, everything worked great after that except for the icons, all of them were perfectly borked. Oddly enough other images was being served alright in the node-red UI.

I traced the problem to the file ../red/api/ui.js where the call res.sendfile() results in an 'undefined is not a function' error, which breaks the serving of icons.

When I use the older allowed express res.sendfile() it starts working again, so it seems to have something to do with the version of express you're having as a dependency. Express *should* still support both ways IIRC, and the sendFile (with a capital 'F') should have worked at all times. 

Anyway, I just thought you'd like to know.

**Comment by knolleary** [comment]
Hi,

what version of node-red are you reporting this against?

We only started to support Express 4 in version 0.12 and all mentions of `sendfile` were replaced with `sendFile` - https://github.com/node-red/node-red/blob/master/red/api/ui.js#L58

**Comment by psvensson** [comment]
Yes I ma using 0.12. Did an npm install just a couple of weeks ago, in fact.
I think that for some reason the express version of node-red does not gets used, maybe beacuse of the weird node-webkit build thing, and then another express present (being an older version, persumably) gets used and throws the spanner in the works. I'll check out if that's the case.

**Comment by psvensson** [comment]
Nope, the one we use is 4.13.3. Strange. Anyway, now if someone experiences the same things at least we have a hack for it :)

**Comment by knolleary** [comment]
Ok, but just to confirm, `sendfile` (with a lower-case `f`) does not appear in the node-red code base since 0.12. So I'm not clear what hack you're suggesting.

**Comment by psvensson** [comment]
Sorry to be unclear. I meant that when I changed sendFile (which does indeed appear (as it should) in the current codebase to sendfile, the icons starts being served.  And yes, it is very strange.

What we're building, btw is our open-source IoT development tool Evothings Studio. I just managed to build a sort-of not official release where you can use node-red as an editor for front-end web app flows. And you can see in the build that I've changed the sendFile to sendfile and that it works, for some reason or other.

https://s3-eu-west-1.amazonaws.com/evothings-download/EvothingsStudio_Linux_64_2.0.0beta2-node-red.zip
https://s3-eu-west-1.amazonaws.com/evothings-download/EvothingsStudio_Win_32_2.0.0beta2-node-red.zip
https://s3-eu-west-1.amazonaws.com/evothings-download/EvothingsStudio_Mac_64_2.0.0beta2-node-red.zip

These are way-pre-alpha builds and currently you have to restart the studio on OSX when you want to switch project. Hope to fix that soon :)

Cheers,
PS

**Comment by knolleary** [comment]
Ok, I don't think there's anything here we need to fix. Please reopen if I've misunderstood.
