### ISSUE TITLE
Unable to start node-red on windows 10

### ISSUE THREAD

**Issue by psvensson** [node-red/node-red#772]
I'm currently embedding node-red in out product and it does work very well, expect on windows. As part of the trouble-shooting I've installed node-red (0.12.4) via npm on a vanilla Windows 10 VM, rebooted it just in case, and.. can't get it to run.

When I start node-red from the command-prompt, it just sits there looking sad after saying 'started flows'. No errors, or security prompts or anything like that. Do you know of a way to get it working?

![screenshot-13](https://cloud.githubusercontent.com/assets/39554/11872544/1a231c3a-a4d6-11e5-94db-c5bf19ec7ae6.png)

**Comment by knolleary** [comment]
That screenshot shows a perfectly running instance of node-red to me. Why do you think it isn't running?

**Comment by psvensson** [comment]
You are correct and I am a donkey :) Sorry to bother you. I mistook our
behaviour from that of node-red proper.
