### ISSUE TITLE
Deployment not enabled when dragging nodes

### ISSUE THREAD

**Issue by ctmalan** [node-red/node-red#774]
When only changing the graphical layout, deployment is not enabled.

This means that the gui state cannot be saved.

(workaround:  change the name of any element)

c-:

**Comment by knolleary** [comment]
Hi, yes, that is intended. We have long discussed this on the [mailing list](https://groups.google.com/forum/#!forum/node-red). Hitting deploy causes your flows to restart - doing so purely for cosmetic reasons isn't desirable.

**Comment by ctmalan** [comment]
Can you save the layout only?

c-:

**Comment by knolleary** [comment]
There is no api for that today.

**Comment by ctmalan** [comment]
ty!
