### ISSUE TITLE
e-mail out STARTTLS issue "SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795"

### ISSUE THREAD

**Issue by wcat13** [node-red/node-red#776]
I am getting this error while trying to send email out of NR to postfix.

I believe this has something to do with NR or nodmailer not correctly using STARTTLS on 587(for me anyway) I can use gmail with the NR and send emails from terminal in the box NR is running on.

http://stackoverflow.com/a/22468122

> secureConnection - use SSL (default is false, not needed with service). If you're using port 587 then keep secureConnection false, since the connection is started in insecure plain text mode and only later upgraded with STARTTLS

I am guessing here.
from

<pre><code>
var smtpTransport = nodemailer.createTransport({
            host: node.outserver,
            port: node.outport,
            secure: true,
            auth: {
                user: node.userid,
                pass: node.password
            }
        });
</code></pre>

I edited  /usr/lib/node_modules/node-red/node_modules/node-red-node-email/61-email.js

and inserted 
            secureConnection: false,          // added this
            ignoreTLS: true,                        // added this

I am still receiving the same error
 found here
https://github.com/nodemailer/nodemailer-smtp-transport/issues/21

<pre><code>
var smtpTransport = nodemailer.createTransport({
            host: node.outserver,
            port: node.outport,
            secureConnection: false,          // added this
            ignoreTLS: true,                        // added this
            secure: true,
            auth: {
                user: node.userid,
                pass: node.password
            }
        });
</code></pre>

Still not working.  I am at a loss as to how to use STARTTLS

Thank you for any help.

Happy new year

**Comment by wayne13** [comment]
I am opening this back up.

I cannot for the life of me figure this out.

is /usr/lib/node_modules/node-red/node_modules/node-red-node-email/61-email.js being used here?

It does not seem to be using this file to create the transport for nodemailer.  Do I have to reload it somehow?

I have been working through nodemailer docs and added 

tls: { rejectUnauthorized: false  }


I then just deleted the whole variable to see if I could get a different error message.  No change.  leads me to believe this file is not being used or needs to be reloaded somehow.  Forgive my ignorance as I am new to nodes inner workings.

I lightened up security in postfix
 smtpd_tls_auth_only = no

I guess I will use gmail.  These kinds of things eat at me so if anyone could explain what is happening I will sleep better.

I guess I will go smash my head against node-gyp for a while trying to install the node-red-xmpp-node  :(

**Comment by milen100** [comment]
I see the same error when NOT using port 465 for gmail.  
Did you try to check what code does in case port is 465 and change it to use the compatible params for your port? I'm curious what would happen in this case.

**Comment by dceejay** [comment]
yes that is the file it uses. It get loaded when Node-RED starts so you have to stop it fully and restart. What platform are you on ? - if a Pi then use node-red-stop to stop it. 
feel free to add some console.log("ping");  lines around line 60 of that file to check it gets called.

and xmpp shouldn't be too bad as long as you have npm 2.x installed.

**Comment by wcat13** [comment]
Ubuntu.  Thank you for the confirmation. I had success sending messages out with xmpp.

**Comment by clickworkorange** [comment]
Here's what I did:

```
        var secureSmtp = node.outserver != "localhost";
        var smtpTransport = nodemailer.createTransport({
            host: node.outserver,
            port: node.outport,
            secure: secureSmtp,
            auth: {user: node.userid, pass: node.password} : false,
            tls: { rejectUnauthorized: secureSmtp }
        });
```
