### ISSUE TITLE
trigger node label is messy for one-shot

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#777]
If you select a 0 timeout for the trigger node, which is for one-shot operation, the node-label when you close the dialogue is
"trigger once &infin;"
I'd suggest just "trigger once" would be fine.

**Comment by dceejay** [comment]
Which browser ? Looks fine to me ?

**Comment by knolleary** [comment]
Can you share the exported json for such a node? I can't find the right set of options to cause the label you see.

**Comment by andysc** [comment]
Ah, sorry - it's on a Pi with an old version of node-red... 0.10.6. 
All shiny and much improved on the new version - thanks - #close
