### ISSUE TITLE
RED.events should be an EventEmitter rather than `events` module

### ISSUE THREAD

**Issue by dbaba** [node-red/node-red#778]
According to https://github.com/node-red/node-red/wiki/API-Reference#server-events,  `RED.events` is an EventEmitter object.
However, because of missing `./` in `require('events')`, `RED.events` property is always Node.js `events` module.

Please replace https://github.com/node-red/node-red/blob/master/red/red.js#L29 with
```javascript
var events = require("./events");
```
`./` prepended.

**Comment by knolleary** [comment]
Hi,

the wiki page you link to has a big warning at the top of the page: **This is a work-in-progress that is out of date - do not use!**. Whilst you are correct to have spotted the mistake in the require statement, the reality is that `RED.events` is an internal thing that should not be part of the public api.

In the next release (0.13) we are stabilising the external API of node-red and documenting it properly.

Nick

**Comment by dbaba** [comment]
Got it. Thanks.
