### ISSUE TITLE
exchange variable value without a deploy

### ISSUE THREAD

**Issue by zombinary** [node-red/node-red#779]
I written a simple node with a button and a textbox in node-red.

Now i try to put out the value from the textbox, in a console (server side) with a click on a button(client side/node-red).
But i find no way to do this without using the 'Deploy-Button'.

Has anyone an ideer to do this with the node-red api or with ajax?

**Comment by knolleary** [comment]
HI, for questions like this please use the mailing list, linked at the bottom of nodered.org

**Comment by hardillb** [comment]
Please use the mailing list for how to type questions- 
https://groups.google.com/forum/#!forum/node-red
