### ISSUE TITLE
Object (msg.payload) keys that are string begining with number not accepted in the Function editor

### ISSUE THREAD

**Issue by antoniodecicco** [node-red/node-red#781]
Assuming payload to be the following

{ list : [ "rain" : { "3h":0.085 } ] }

msg.payload.list[0].rain.3h is not accepted in the function editor, preventing direct access to the value of 3h.  Square bracket notation does not work either.  Javascript objects should allow keys that begin with a number if the key itself is a string.

Node-RED version: v0.12.5
Node.js  version: v0.10.32

**Comment by knolleary** [comment]
No, `msg.payload.list[0].rain.3h` is not a valid javascript identifier.

You should use `msg.payload.list[0].rain["3h"]`

**Comment by hardillb** [comment]
Also are you not missing a set of {} in that object

{ list : [ "rain" : { "3h":0.085 } ] }

should be

{ list : [ {"rain" : { "3h":0.085 }} ] }

**Comment by dceejay** [comment]
Obligatory Stackoverflow link - http://stackoverflow.com/questions/8698792/javascript-object-key-beginning-with-number-allowed

**Comment by antoniodecicco** [comment]
Apologies for posting as bug... should have dug a bit deeper.  The quoted
key in square brackets accessed the value as expected.  Thanks much!

**Comment by JesperAS** [comment]
Dear all, i have a simulate problem.

I am new at programming and need some help.
I am reading the below json object from a Rest API and want to filter out the “value”

measurements: object
	30456: object
		date: "2017-07-08T06:59:29+0000"
		type: 1
		value: 21.28
		seq: 1499497171982471
		min: null
		max: null
	code: 200
	max_age: 900
	time: 0.136

Works :
x = {payload: msg.payload.max_age}; returns 900
y = {payload: msg.payload.code}; returns 200

But how do I get the “value” 21,28 in to a variable ?

z = {payload: msg.payload.measurements.[“30456”].value} ; don’t work

Thanking in advance

**Comment by hardillb** [comment]
As mentioned in the [contribution guide](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) questions should be asked on the Google group (mailing list) or on the Node-RED Slack team (links to both are on the Node-RED home page) so the whole community can help, not just the core developers. 

Also it's really not clear what the object structure is as `value` seams to be at the same level as `code` and `max_age`. When you repost this to Slack or the Google group please include the actual structure of the message object.

**Comment by JesperAS** [comment]
OK will do, many thanks.



2017-07-10 11:02 GMT+02:00 Ben Hardill <notifications@github.com>:
