### ISSUE TITLE
CORS not working on paths with more than "1param"

### ISSUE THREAD

**Issue by samvloeberghs** [node-red/node-red#783]
Didn't know how to proper describe it.
But for example:

I've created a mock for an api:
`http://localhost:1880/users` -> returns a list of users
`http://localhost:1880/users/:id` -> returns the details of a specific user

requesting `http://localhost:1880/users` via ajax works.
but requesting `http://localhost:1880/users/1` gives a an error.

happpening on v `0.12.5`.

I don't think it's related to my setup, because reverting to v `0.11.2` fixes it for me.

Grtz

**Comment by knolleary** [comment]
Hi,

> requesting http://localhost:1880/users via ajax works.
> but requesting http://localhost:1880/users gives a an error

did you mean the same url in both cases or has something got stripped off as I don't see anything related to parameters.

**Comment by samvloeberghs** [comment]
check the edit, my bad :)

**Comment by knolleary** [comment]
Ok, that has made it clearer, thanks. 

Don't have an immediate answer as I'll need to recreate and investigate. An observation is that we did move from Express 3.x to 4.x between 0.11 and 0.12...

**Comment by samvloeberghs** [comment]
:+1: thx, I'm sticking to 0.11.x now. 
I have a too big dependency on this great tool :)

**Comment by knolleary** [comment]
Can you share your httpCors setting as well?

**Comment by samvloeberghs** [comment]
it's the default:

    httpNodeCors: {
        origin: "*",
        methods: "GET,PUT,POST,DELETE"
    },

**Comment by knolleary** [comment]
Ok - will take a look and see if there's something to slip into 0.13.

**Comment by samvloeberghs** [comment]
just a guess:
did you perhaps rename the option from 
httpNodeCors to httpCors from v0.11.x -> v.0.12.x?

**Comment by knolleary** [comment]
no - that's just me not bothering to double check the setting name when I added the comment ;)

**Comment by samvloeberghs** [comment]
hahaha that would've been too sweet

**Comment by knolleary** [comment]
Fixed in the runtime branch - will be available in the imminent 0.13

**Comment by samvloeberghs** [comment]
whoop! thx for the effort!
