### ISSUE TITLE
HTTP Request node does not allow self-signed certificates

### ISSUE THREAD

**Issue by jwcrawley** [node-red/node-red#784]
I am using a self-signed certificate because my domain is not allowed to have anything other than an EV2 cert ( a TOR .onion address). I still do like the privacy of the conversation between Node-Red and the client regardless, and do not want periphery nodes listening in on the conversation.

Now, with the HTTP Request node, I tried the code that was offered on Google Groups of the following:

    [{"id":"19de8d5.93bb373","type":"inject","z":"f6358f79.587a3","name":"","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"","once":false,"x":285,"y":231,"wires":[["87efe6cb.cce13"]]},{"id":"87efe6cb.cce13","type":"function","z":"f6358f79.587a3","name":"","func":"msg.headers = {\n    \"Node-RED-Deployment-Type\":\"reload\"\n}\nreturn msg;","outputs":1,"noerr":0,"x":425,"y":231,"wires":[["6883e89c.a350c"]]},{"id":"6883e89c.a350c","type":"http request","z":"f6358f79.587a3","name":"","method":"POST","ret":"txt","url":"https://localhost/flows","x":565,"y":231,"wires":[["a6de0642.bc767"]]},{"id":"a6de0642.bc767","type":"debug","z":"f6358f79.587a3","name":"","active":true,"console":"true","complete":"true","x":725,"y":231,"wires":[]}]

The code works when I am on an unsecured instance of Node-Red with no authentication and no SSL. However, when I move this to any server with Self-Signed certs, I get the following error (complete message object):

{ "topic": "", "payload": "Error: DEPTH_ZERO_SELF_SIGNED_CERT : https://localhost/flows", "_msgid": "bea8329c.4157d", "headers": { "Node-RED-Deployment-Type": "reload" } }

What must I do to forcefully enable accepting this certificate? Going to a LetsEncrypt is not viable, since this is a Node-Red server on my internal network that also serves to TOR as a Hidden Service.

**Comment by knolleary** [comment]
There is an environment variable you can export to tell node to accept self signed certs. Google should find it if you get there before I get to my laptop.

**Comment by jwcrawley** [comment]
Thank you for your speedy response.

Do you know of a mechanism that can change the export variables real-time within the system? 

This is my current gotcha for working with .onion links and dealing with self-signed certs: either I go all in, or don't at all.

**Comment by knolleary** [comment]
Right now it's all in, or not at all. Cert handling gin general is something we have on the list to look at in more detail in the near future.

**Comment by jwcrawley** [comment]
I understand. Thank you :)

Sincerely,
Josh Conway
