### ISSUE TITLE
multiple UDP inputs with same port doesn't throw any error

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red#786]
When using lots of udp inputs, if by mistake two or more are set with the same port, only the first will work as expected, but the log window reports that all are "udp listener at 0.0.0.0:4444". It would be good if the log window would catch this and throw an error. It could be great if the udpinput node would display a node status if the port is already used.

**Comment by darkyen** [comment]
UDP allows listening by multiple processess on same port although its not recommended against.

**Comment by dceejay** [comment]
Indeed UDP does allow that - but in this (Node-RED) case only the first node does actually get the data - so warning against it is probably a good idea. I think it's more of a warning than an error - so should alert the user at edit time if possible, and flag a warning on deploy if not. 

This applies to the input node only.

**Comment by darkyen** [comment]
@dceejay can't node-red make it possible so that multiple flows can process the same input ?  // although in flows context you should hear it in a node and then pipe it two ?

**Comment by dceejay** [comment]
Well - you can wire two (or more) flows to the node....

**Comment by darkyen** [comment]
yeah thats what i have been doing xD

On Sun, Jan 17, 2016 at 1:12 PM, Dave Conway-Jones <notifications@github.com

**Comment by knolleary** [comment]
It could be argued that having multiple nodes listening on the same port is valid and they ought to all receive the data - much as you can have multiple mqtt nodes subscribed to the same topic and they all get the messages.

**Comment by dceejay** [comment]
True - though typically you have different topics on each node. Is this a common enough use case to warrant it ? (and thence by implication for all other input nodes (and indeed output nodes ?)

**Comment by knolleary** [comment]
This issue is the first time, to my knowledge, that it has come up. Given the 'workaround' (single node, wired to multiple places) exists, I don't think there is sufficient demand to warrant changing it.

But I think it highlights a pattern we should be conscious of with any new nodes we create - that two identically configured input nodes would be reasonably expected to co-exist and operate regardless of how many there are.

**Comment by dceejay** [comment]
I think some of this depends on your mental model... Being an old hardware engineer I tend to think of one input being an actual pin in a physical connector - with then several wires attached... I guess software folk just fire up another virtual pin whenever they need one :-)
