### ISSUE TITLE
HTTP IN request object (msg.req) not pointing correctly to headers & etc.

### ISSUE THREAD

**Issue by macedolfm** [node-red/node-red#787]
Hi,

I am nubby at Node-RED but the new v0.13.0 release broke my previous code where I used to:

if(msg.req.header('authorization') === .....

And now this call gives me msg.req.header is undefined.

Inspecting the code for msg.req object I noticed that the JSON has a new schema or the msg.req is not being set. 

Node-RED version: v0.13.0  msg.req object
{"_req": {
		"_readableState": {
			"highWaterMark": 16384,
			"buffer": [],
			"length": 0,
			"pipes": null,
			"pipesCount": 0,
			"flowing": false,
			"ended": false,
			"endEmitted": false,
			"reading": false,
			"calledRead": false..........

Node-RED version: v0.12.2  msg.req object
{"_readableState": {
		"highWaterMark": 16384,
		"buffer": [],
		"length": 0,
		"pipes": null,
		"pipesCount": 0,
		"flowing": false,
		"ended": false,
		"endEmitted": false,
		"reading": false,
		"calledRead": false...........

Reseting msg.req seems fix the bug:

msg.req.headers = msg.req._req.headers;

Regards, Luís

**Comment by knolleary** [comment]
Hi,

thanks for raising this. Will get a fix released asap.

Nick

**Comment by knolleary** [comment]
Ah, a slight subtly here... `msg.req.header` is not a documented function of the request object provided by express - so we don't support its use. Instead, you should use the `msg.req.headers` object:

    msg.req.headers['authorization']

But... `msg.req.headers` has suffered the same fate in 0.13 as msg.req.header... sigh. Fix on its way

**Comment by knolleary** [comment]
0.13.1 has now been published to NPM. Thanks again for spotting this, apologies for the inconvenience.

**Comment by macedolfm** [comment]
My pleasure, thanks for the great & speedy fix !!

Another comment, @knolleary since you used to work at IBM (I guess...)...

After creating a Bluemix App using the Node-RED community boiler plate or the IoTF boilerplate you can use de APP WebIDE create a Git at DevOps that, supposedly, would be populated with the tricky config files: 

settings.js, manifest.yml, package.json

and the following folders and its contents: /defaults, /nodes, /public

Starting a few days ago, these are NOT being created anymore (checkbox set), also, I don´t know why, after the APP creation, the npm and node "engines" version get stuck forever at the first installed SDK version (IBM cached ?), I learned how to fix these using the "engine" but perhaps one should forcefully include the "engines" statement at first package.json as well as the "redis":"~0.10.1" key.

    "engines": {
        "npm":">2.0.0",
        "node":"0.10.41"
    },

As a Newbie at Bluemix, Node.js, Node-RED and CF took me hours until figure out what was going on with my new APP x old APP as IBM support did not even know what I was talking about.

Cheers and congrats for this AMAZING environment, best Luis

**Comment by knolleary** [comment]
Hi,
Thanks for the feedback.

I saw the sync to devops issue had been raised internallyyesterday and was being worked on. Don't have an ETA.

Nick
