### ISSUE TITLE
receiving Debug data from a deleted node.

### ISSUE THREAD

**Issue by scropion86** [node-red/node-red#788]
i have a debug node sending a Debug message to debug tab.
and this node already deleted and even i delete the entire flow and start from scratch and still receivng the debug message.
i am using the latest version V0.13.0 and below is the message 

    1/23/2016, 1:23:10 PMJED TEMP 
    msg : Object
    { "type": "keynotfound", "description": "this key does not exist" }

**Comment by hardillb** [comment]
Which node is it that is still sending messages?

It is most likely a badly written nor that is not closing down properly when removed from the flow

**Comment by hardillb** [comment]
Also just double checking something, how have hit deploy after deleting the nodes?

**Comment by scropion86** [comment]
it was the debug node , i have to restart the node-red after that this problem gone

**Comment by knolleary** [comment]
@scorpion86 but what node was sending data to the debug node? That's the key question.
