### ISSUE TITLE
Issue with http in node in v0.13.1

### ISSUE THREAD

**Issue by endemecio02** [node-red/node-red#790]
I found an issue in the http in node for v0.13.1.

in the http in core node lines 199 - 201, RED.settings.httpNodeMiddleware is always undefined.

if (RED.settings.httpNodeMiddleware) {
  if (typeof RED.settings.httpNodeMiddleware === "function") {
    httpMiddleware = RED.settings.httpNodeMiddleware;
  }
}

This is because the init function in ./red/runtime/settings.js does not add getter and setter functions for it in the settings object. It only add own non function properties.

if (settings.hasOwnProperty(i) && typeof settings[i] !== "function") {
  (function() {
    var j = i;
    persistentSettings.__defineGetter__(j,function() { return userSettings[j]; });
    persistentSettings.__defineSetter__(j,function() { throw new Error("Property '"+j+"' is read-only"); });
  })();
}

To fix this, the http in code node needs to be updated to this.

if (RED.settings.get('httpNodeMiddleware')) {
  if (typeof RED.settings.get('httpNodeMiddleware') === "function") {
    httpMiddleware = RED.settings.get('httpNodeMiddleware');
  }
}

This will have to be done for all places where using RED.settings.<propName> a function is expected.

**Comment by knolleary** [comment]
Thanks - will get that fixed as soon as possible (will be a couple days). Definite candidate for pushing out 0.13.2.

**Comment by endemecio02** [comment]
Thank you
