### ISSUE TITLE
lib/flows created for no apparent reason

### ISSUE THREAD

**Issue by boneskull** [node-red/node-red#791]
You can see [here](https://github.com/node-red/node-red/blob/392fd6fed3c56e7ca3b42c20de3118211f7535c1/red/runtime/storage/localfilesystem.js#L187) that the `lib/flows` dir will be created.

But it's not used anywhere, from what I can tell.

What's up with this?

**Comment by knolleary** [comment]
Hi,

That is you local flow library. In the editor if you select some nodes and select 'export->library', that's where they end up.

Some nodes also have the ability to save things to the library, such as functions and templates. They get put in their own subdir of lib as and when needed.

In the future, for this sort of question, please use the mailing list or slack team linked to at the bottom of nodered.org . 

Thanks.
