### ISSUE TITLE
Using mongodb and basic user authentication

### ISSUE THREAD

**Issue by user0403** [node-red/node-red#795]
I am trying to do custom user authentication for node-red admin UI. After successful authentication, I want to load the flows from mongo DB based on the user name. For each user, I am maintaining a separate DB. How to load the flows based on the valid user authentication.

**Comment by knolleary** [comment]
Hi, for user questions like this, please use the Google group mailing list - linked at bottom of nodered.org

The runtime is inherently single user - there is no distinction between the flows presented to the editor based on who has logged in.
