### ISSUE TITLE
Add options support for WebSocket Node

### ISSUE THREAD

**Issue by mobui** [node-red/node-red#797]
Feature request to add options support for WebSocket Node. I use SAP IoT Service, but it required header for authentication and I can't use WebSocket Node without modification source code.

**Comment by knolleary** [comment]
By options do you just mean username/password for basic authentication, or are there other things to consider?

**Comment by mobui** [comment]
For authentication I set this options:
For SAP IoT - { headers : {'Authorization': 'Bearer ' + 'your_oauth_token'} }
For ABAP Push Channel (development server with self signed certificate) - { headers : {'Authorization' : 'Basic ' + 'user_password'} , rejectUnauthorized: false} }

**Comment by dceejay** [comment]
is this for outbound client connections only, or would listening sockets needs extra options also ?

**Comment by knolleary** [comment]
The immediate requirement is the outbound connection - just as you can set
auth properties of the http request node. Although it's a bit more subtle
as the example above is more than just basic auth.

Whether we expose any of the options the websocket listener api accepts is
an entirely separate question and not part of the requirements here. It
isn't something I can see an immediate need for either.

**Comment by dceejay** [comment]
and I guess is per connection, rather than per request... so in the socket connection config rather than the incoming msg

**Comment by isramos** [comment]
I look forward to having the option to pass websocket url as a parameter. Just like I can do with HTTP requests. This feature would let me implement Watson's service tokens. These tokens have a 1hr life and right now I have to every one hour manually update the websocket url :/

```
var url = "wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?watson-token=";
var token = msg.payload.token;
var params = "&model=en-US_BroadbandModel";
msg.url =  url + token + params;
```

reference: http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/getting_started/gs-tokens.shtml

**Comment by janvda** [comment]
Hi, I have a very related issue.
I am getting following error:
{ "error": { "code": 401, "message": "Please provide a valid authorization header" }, "_session": { "type": "websocket", "id": "7d43d8ae.82bc28" }, "_msgid": "ef645fb5.109ba" }

I want to connect to a websocket requiring an access token.  Ideally this token should be passed as a parameter, but it would already be good if I can get it working with a hard coded access token.  
FYI this is the cloud service I want to connect to: [https://developer.artik.cloud/documentation/api-reference/websockets-api.html]

kr Jan

**Comment by knolleary** [comment]
@janvda have you tried hardcoding it in the url you configure the websocket node with? I'd expect that to work today.

**Comment by langanjp** [comment]
I have similar requirements as Mobui - I am trying to connect to an industrial time-series historian web api services (OSIsoft PI Web API service) that should have authentication and may need other information that either won't fit in a parameter or needs to be part of the header or body of the intial request.  I don't find this very feature useful without being able to put authorization (and other) headers.

One of the nice things of the websockets standard is the ability to start with a HTTPS message that has all the information in the headers or body and have that upgraded to a websocket.   For what I am trying to do, I need to start with an HTTPS POST and ask for it to upgrade to websockets.  Node-red does not seem to implement this part of the websockets standard.  

This is for 2 reasons: 

First is authentication header (or other required headers).  The service I am connecting to doesn't give me the option of putting authentication / token in the URL - nor would I want to.  (I might as well publish my credential at that point).  For one of the things I am trying to accomplish, I can set the authentication on the web api service to support "anonymous", but again - not a good solution.  So I would like to start with an HTTPS message that looks like this:

```
POST https://pivm/piwebapi HTTP/1.1
X-PIWEBAPI-HTTP-METHOD: GET
X-PIWEBAPI-RESOURCE-ADDRESS: https://pivm/piwebapi/streamsets/channel?includeInitialValues=true&webid=verylongstring&webid=anotherverylongstring&webid=anotherlongstring&webid=icanputasmanyoftheseonasneededdependinguponhowmanyobjectsineedtorsubscribeto
Authorization: Basic <credentials> 
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Key: <websocketkey>
Sec-WebSocket-Version: 13
```

(Note: this request works in a client that supports starting with an HTTP request and upgrading it to a websocket)

Second is that there are limitations to the size of a wss url.  So there is a need to be able to start with an HTTP POST that can have extended header properties (or a body) that has all of the necessary information of what I am trying to subscriber to.  In my case I won't be able to put all of the information in a url parameter as it could be too long - so the web api provider allows me to post my extended "URL" in the X-PIWEBAPI-RESOURCE-ADDRESS - i use this to be able to get around the size limit of a normal URL and can keep adding on as many parameters as I need.

**Comment by chan71** [comment]
Is there any update on this?

**Comment by ruchiranet1** [comment]
**(Note: this request works in a client that supports starting with an HTTP request and upgrading it to a websocket)**

But HTTP upgrade does not support NodeRED. Please let us know, do you have plan to support HTTP upgrade request in NodeRED ? 

Then only we can implement webSocket basic auth in NodeRED.

**Comment by knolleary** [comment]
@ruchiranet1 this issue is regarding exposing options for outbound WebSocket requests.

I think you're talking about inbound connections? I'm not sure what you mean by 'supporting HTTP upgrade request' - we already do that via the WebSocket listener node. What we don't have (and what I think you really mean) is a way for you to access the headers of the original upgrade request to make an authentication decision.

**Comment by chan71** [comment]
@knolleary Yes, it is about authenticating incoming websocket calls so that only intended clients can connect to the server.

**Comment by ruchiranet1** [comment]
@knolleary . You figure out the question exactly right. We are looking for the way to access the headers of the original upgrade request. We are currently using IBM bluemix for the NodeRED development.

**Comment by knolleary** [comment]
@chan71 @ruchiranet1 I have opened #1127 to cover inbound connections. Please use that issue if you want to follow up.

**Comment by knolleary** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Customise request headers of outbound WS connections](https://trello.com/c/nx4islGu/80-customise-request-headers-of-outbound-ws-connections)

**Comment by ruchiranet1** [comment]
@knolleary. Thank you.

**Comment by azrin1972** [comment]
@knolleary, How do I add basic user/pass to websocket since there is no input field for user/pass in websocket node. I've read the above thread and you did mention to hardcoding it - may I know how?

Thanks

**Comment by PaulWieland** [comment]
Any progress on this one? I want to connect to a hone automation hub and I have to pass a custom header.

I can manually create the connection like this:

```javascript
let auth = 'Basic ' + new Buffer(user + ':' + password).toString('base64');
let webSocket = new WebSocket.Client(
    "ws://"+address+"/rest/subscribe", 
    ["ISYSUB"],
    {
        headers: {
            "Origin": "com.universal-devices.websockets.isy",
            "Authorization": auth			
        }
    }
);
```

**Comment by jimwhitfield** [comment]
Thanks @PaulWieland 
I'd also like to upvote this request.  
Background: I'm hooking an ESP32 up by MongooseOS to their server at [mdash.net](url) and they require the HTTP header
```
Authorization: Bearer DEVICE_PASSWORD
```
in order for my Node-Red flow to receive the data.

**Comment by knolleary** [comment]
Given we try not to use this issue list to track feature requests, we have this item on our backlog that covers this: https://trello.com/c/nx4islGu

**Comment by dceejay** [comment]
Given backlog new features item also covers this - closing this here as well.
