### ISSUE TITLE
http request node hangs in requesting state

### ISSUE THREAD

**Issue by janvda** [node-red/node-red#801]
Hi,

I am having 2 http requests nodes in my flow and both nodes are now hanging for about 10 hours in "requesting" state.  (I assume they are hanging in requesting state as "requesting" is the state I can see just below these 2 nodes within the node-red UI).

FYI I am running Node-RED version: v0.12.5  (Node.js  version: v0.10.29) on raspberry pi model B with Jessie (=Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux)

For the first "http request node": 
> The request method = GET 
> The request URL = 192.168.1.30/control/relay.cgi?relay2={{{payload}}}
> The return = a UTF-8 string
> Use basic authentication is not flagged.

For the second "http request node": 
> The request method = GET 
> The request URL = 192.168.1.30/control/relay.cgi?state
> The return = a parsed jason object
> Use basic authentication is not flagged.

Note also that the connection to the device 192.168.1.30 is poor, so the nodered log file regularly report error like:

> 13 Feb 13:43:30 - [error] [function:extract cv pump state] Unexpected http get status code (=EHOSTUNREACH)
> 13 Feb 13:44:15 - [error] [function:extract cv pump state] Unexpected http get status code (=EHOSTUNREACH)
> 13 Feb 18:08:39 - [error] [function:extract cv pump state] Unexpected http get status code (=EHOSTUNREACH)
> 13 Feb 18:09:24 - [error] [function:extract cv pump state] Unexpected http get status code (=EHOSTUNREACH)
> 13 Feb 18:31:54 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 13 Feb 18:42:25 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 13 Feb 20:47:12 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 13 Feb 23:33:35 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 14 Feb 02:42:38 - [error] [function:extract cv pump state] Unexpected http get status code (=EHOSTUNREACH)
> 14 Feb 09:09:26 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 14 Feb 09:39:48 - [error] [function:extract cv pump state] Unexpected http get status code (=ECONNRESET)
> 14 Feb 09:43:49 - [error] [function:extract cv pump state] Unexpected http get status code (=ECONNRESET)
> 14 Feb 09:59:45 - [error] [function:extract cv pump state] Unexpected http get status code (=ECONNRESET)
> 14 Feb 10:41:31 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 14 Feb 10:41:58 - [error] [function:extract cv pump state] Unexpected http get status code (=ECONNRESET)
> 14 Feb 10:58:52 - [error] [function:extract cv pump state] Unexpected http get status code (=ECONNRESET)
> 14 Feb 11:01:04 - [error] [function:extract cv pump state] Unexpected http get status code (=ECONNRESET)
> 14 Feb 11:03:45 - [error] [function:extract cv pump state] Unexpected http get status code (=ETIMEDOUT)
> 14 Feb 11:20:22 - [error] [function:extract cv pump state] Unexpected http get status code (=EHOSTUNREACH)

So I am not complaining about above errors as they are most likely caused by a poor connection, The actual problem is that this sometimes resulted in a "http request node" that hangs.    The consequence is that the complete flow is stuck due this hanging node.

Note also that redeploying the flows didn't fix the hanging state.  In order to get this fixed I had to restart the node-red service.

What can I do to prevent this hanging ?

many thanks
jan.

**Comment by dceejay** [comment]
Indeed - we don't set a timeout and there doesn't seem to be one by default. (On being a server it defaults to 2 mins)... I suggest we also pick that as a default for request connections also ?
Any problems with this idea ?

**Comment by dceejay** [comment]
pushed the above fix. Default of two mins can be changed in settings.js  httpRequestTimeout

**Comment by janvda** [comment]
Thanks for the fast correction.  I manually copied your changes to my node-red installation on my raspberry pi and it is working.  Thanks to those changes the http request nodes no longer hang, instead  an error is logged in the log file (see below).

Excellent job
Jan.

```
pi@raspberrypi:/var/log $ grep "no response" node-red.log
17 Feb 07:27:46 - [error] [http request:http ESP8266 activate/deactivate CV relay] no response from server
18 Feb 19:32:22 - [error] [http request:get ESP8266 relay status] no response from server
18 Feb 21:11:25 - [error] [http request:get ESP8266 relay status] no response from server
18 Feb 21:33:27 - [error] [http request:get ESP8266 relay status] no response from server
pi@raspberrypi:/var/log $
```
