### ISSUE TITLE
'null' inject node type

### ISSUE THREAD

**Issue by njh** [node-red/node-red#806]
Hello,

I am enjoying the new type system in the Inject Node.

For several of flows, the inject node does not actually need to inject a value - the event trigger is enough.
Do you think it would be worthwhile having a 'null' type, if no message body is required?

nick.

**Comment by knolleary** [comment]
I did wonder about this and decided against it.

In the previous inject node, even if you said 'blank' it meant the payload was a blank string, not blank-as-in-non-existent.

The overhead of having the payload be a blank string is minimal - and will avoid the inevitable issues when it gets wired up to a node that assumes msg.payload exists.

There may be cases where a flow actively requires msg.payload not to exist - but I suspect they will be rare and can use the Change node to delete it.

**Comment by dceejay** [comment]
Most nodes expect some payload even if they don't care about the value. You can always use a string type with nothing in it you like. Does adding null add any value to the node apart from to add an item to the menu and to make the beginner have to read some more to work out what it does ?
Some of the philosophy of Node-RED is not to expose options if they don't really need to be exposed (whether intentionally out not ;-), unless they add value to the user.

**Comment by njh** [comment]
Understood, and I totally agree about not adding functionality that isn't required.

But I was actually thinking it might make things clearer to the user. When choosing a String type from the dropdown, the UX implies that there should be a value; so if adding a 'null' option (with no ability to enter a value), it would make it clear that it is the right 'pattern' to send a message without a value.

Also I was imagining that it would set ```msg.payload = null``` not undefined.

But I am sure there are bigger things to things to think about/work on.
