### ISSUE TITLE
Debug problem with arrays

### ISSUE THREAD

**Issue by jeanfbrito** [node-red/node-red#809]
I always get undefinied:
http://prntscr.com/a8i4w5
When I try to use "msg.payload[0][0].last" to show in debug:
http://prntscr.com/a8i528
The payload is this:
```
msg.payload : array [1]
[ [ { "time": "2016-02-27T07:35:45.628473338Z", "last": 99 } ] ]
```

If I use the function to extract that info, it works:
```
msg.payload = msg.payload[0][0].last;
return msg;
```
http://prntscr.com/a8i5l0

I lost more than 2 hours trying to make it work. I'm starting with JS, then I guessed that was my fault. Please, can someone say if is normal or a bug?

Node-RED: 0.13.1
Node Version v5.4.1

**Comment by knolleary** [comment]
Hi,
the field in the debug node where you specify the property to display does not support referencing elements in an array using the `[]` syntax. That's something we will add in the future.

You can however use the syntax: `payload.0.0.last`.

For general support questions like this, we prefer to use the [mailing list](https://groups.google.com/forum/#!forum/node-red).

**Comment by Dowster64** [comment]
Hi,
plus 1 for that... 
You have no idea how long it's taken me to realise that debug doesn't support the [] syntax and it wasn't my inability to use it properly...
Thanks for a great product though,
Steve

**Comment by knolleary** [comment]
@Dowster64 then I suspect you'll like the latest 0.14.2 release...

**Comment by Dowster64** [comment]
Thanks @knolleary  .  I do very much like the latest 0.14.3 release and I was able to test out the syntax straight away.  I have also found the forum and the pennies are starting to drop.
Thanks,
Steve
