### ISSUE TITLE
Unable to splice links when state is IMPORT_DRAGGING

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#811]
When the view state is IMPORT_DRAGGING, (ie following a `ctrl-v` or `import nodes`), if the node being imported is a single node and has both input and output ports, it should be possible to splice this node into an existing link.

**Comment by Cancelor** [comment]
Is this a bug or are you proposing this as a new feature?

As a comparison, if I delete a node that has both input and output ports the remaining links are not spliced.

**Comment by knolleary** [comment]
This is a reminder to me to fix this bug.

As for unsplicing a link if a node is deleted... that would be a feature request. Not something I'd considered... but can see how it would be useful. Perhaps a behaviour triggered by `Ctrl-Delete`.
