### ISSUE TITLE
Unused MQTT connections should not attempt to connect

### ISSUE THREAD

**Issue by mkarliner** [node-red/node-red#813]
I use an MQTT broker that enforces unique client IDs and disconnects when a duplicate
connection is attempted. While trying to debug other problems, I disconnected this
connection from my flow, imagining it to remain quiescent. However, it appears
that even unused connections continue to attempt connection. I think that this
is the wrong behaviour, as in the case where I am testing several alternate brokers,
it leads to confusion.

**Comment by knolleary** [comment]
Where you say you disconnected the node from the flow, do you mean you removed the MQTT node from the workspace or that you just removed the wires connecting it to the next node?

If the former, then yes, there should not be a connection - and that's something I tested very recently to ensure was correct. If the latter, then you still have an active mqtt node in your workspace so a connection is attempted.

**Comment by mkarliner** [comment]
Sorry, it appears that I was crying wolf, the broker in question is still showing dups after I changed the hostname for the connection in node red. I'll have to look for the culprit elsewhere.
