### ISSUE TITLE
Enhancement: Add documentation section to each node.

### ISSUE THREAD

**Issue by nkolban** [node-red/node-red#814]
As I use Node-RED, I find that I wish to add documentation to each node instance that I place on the canvas.  Think of this as the equivalent of code comments.  When I come back to a node weeks or months later, I can't always remember the details and when I pick up other folk's flows, I have trouble following their logic.  While I understand I can add comments to the flow as a whole through the comment node, my desire is to be able to add documentation that I can open up when I look at a specific node instance.

**Comment by knolleary** [comment]
Hi @nkolban 

We've held off enabling this level of documentation - it always felt too heavy weight. In my experience, the nodes that typically need documentation are Function nodes, that inherently can have as much inline documentation by way of comments. This is because most other nodes are pretty well-defined in their purpose and their exact behaviour can be determined pretty quickly by looking at how it is configured.

Personally, I find the Comment node approach sufficient, as you can document a flow at whatever granularity it requires - either as a single comment for the whole thing or for subsets of nodes.

**Comment by nkolban** [comment]
Howdy,
My experience with integration technologies is that we need a place to log detailed docs.  While the code may be able to be "re-read", non-code aspects might not be able to be discovered.  For example in real-world projects, documentation may read: "Why are using port 1234?", "Who do I contact to get some credentials for XYZ?", "Manually recorded change history", "DO NOT CHANGE THE INTERFACE HERE AS IT IS USED BY Finance Dept!!".

Obviously this is an ultra low priority request as it impedes nothing in terms of using the package.  I'll add two more thoughts in case they are useful:

1. If there gets to be enough issues for enhancement maybe we could create a "voting" mechanism where each user gets maybe 3 votes that they can apply to their favorite enhancements so we can see what folks want the most and least.
1. If there is further demand or interest for this additional level of documentation, perhaps it could be implemented in Node-RED but "switched off" or "hidden" by default such that there is no visualization to the end user and hence no consumption of real-estate but for those who want it, they can switch it on in their preferences (some how) that would allow it to be visualized.

**Comment by dceejay** [comment]
One of the key tenets of Node-RED is things should not be hidden. (I was actually against even adding sub-flows as they "hide" what they are doing inside a node)  - We don't want to add hidden wiring, levels of settings, or documentation. The whole idea is that any user should be able to look at any flow and work out what is going on fairly quickly, as the visual nature should help guide them. Yes there probably is a place for documenting your design decisions like which port etc - but I'm not sure why that needs to be at a per node / field level, as they would tend to be relevant to operation of the whole flow.

**Comment by TotallyInformation** [comment]
Whilst I understand the desire to keep everything open, I also find that only having a comment node is restrictive. I often want to add some detail to a node. For example I have some large switch nodes that translate one thing (e.g. an incoming MQTT message with a logical name) to another (e.g. a physical ID being output to hardware). The ability to put some documentation within the node would save a lot of time and effort when I come back to it 6 months later. While this can be done using a comment node, the limitations of the layouts mean that it can be very difficult to keep a clean layout and have comment nodes scatterer around. Furthermore, you have to remember to move the comment node when moving the flows around.

**Comment by knolleary** [comment]
0.20 introduces an info property to all nodes, flows and subflows that gets displayed in the info sidebar.
