### ISSUE TITLE
After a sense HAT is removed from Raspberry, it halts node-red

### ISSUE THREAD

**Issue by sisomm** [node-red/node-red#818]
I added the sense HAT node (great btw), but when i removed the sense HAT shield node-red went into an endless loop because of some hardware(?) error

I then chose to remove the node by issuing the command
npm uninstall node-red-node-pi-sense-hat

Now, even if I have a flow without the sensor hat node, node red won't start. It says:
5 Mar 21:09:26 - [info] Waiting for missing types to be registered:
5 Mar 21:09:26 - [info]  - rpi-sensehat in

I have tried to locate where this rpi-sensehat in is, but can not find it and remove the reference

**Comment by knolleary** [comment]
Hi, thanks for this. Not a scenario i'd tested yet.

You must have a rpi-sensehat in node in your flow for it to display that message.

When Node-RED starts it logs the flow file it is using - have you checked that file for the SH node?

**Comment by sisomm** [comment]
Just to make sure I fetched an old flowfile from the GIT repository - from before I even tried the sensehat. So yes, there can not possibly be a SH node in the file. The strange thing is, that even if i do a grep -r sensehat in all places node-red can be, I get no match

**Comment by sisomm** [comment]
SORRY i don't know how this happened. Yes there is a reference. Will remove it.

**Comment by sisomm** [comment]
So I guess the first issue remains then... Node-Red stops if you have added a sensehat node and then remove the sense HAT itself

**Comment by knolleary** [comment]
Good stuff. Just sat down to fix the unplug issue to remember I screwed my senseHAT onto my Pi - which is why I hadn't tested the unplug scenario. Will have to wait until tomorrow evening now.

**Comment by knolleary** [comment]
I've added some error handling that stops the crash, but there is still some odd behaviour we may need to follow up on later. On some occasions after unplugging the hat we don't get any indication that it's gone - our calls to read the sensors return without error albeit with slightly wonky looking data. But at least it doesn't kill node-red.

Published as 0.0.7 to npm
