### ISSUE TITLE
Occasional flow file corruption - file length 0

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#819]
Very occasionally - (usually on  Pi) the flow file seems to get corrupted to file length 0 - this may well be due to removing power before OS has finished writing to SD... but...  when Node-RED starts it then crashes with

    6 Mar 11:58:27 - [red] Uncaught Exception:
    6 Mar 11:58:27 - SyntaxError: Unexpected end of input
        at Object.parse (native)
        at /usr/lib/node_modules/node-red/red/runtime/storage/localfilesystem.js:202:41
        ....

a) this should be caught....
b) If a flow file of length 0 is detected on start then we should attempt to recover by copying the backup file - or at least alert the user and ask them if they want us to copy over the backup file.

Easy to recreate. Just create a flow file of size 0

**Comment by knolleary** [comment]
-  If a flow file is found to be zero-bytes:
    -  If there is a non-empty backup, restore the backup and resolve
    -  If there is no backup or it is also empty, resolve empty flow
 - If a flow file is found to be invalid json:
     - Log and resolve empty flow

**Comment by knolleary** [comment]
(and log what's happening in all cases)

**Comment by dceejay** [comment]
Thanks - tick ;-)
