### ISSUE TITLE
Version of flows.nodered.org It's not updated after updating package.json and npm publish

### ISSUE THREAD

**Issue by chameleonbr** [node-red/node-red#820]
Hello, I do not know if it was a change of behavior in flows.nodered.org or something I did that generated something wrong, but when I update package.json and publish the package, is no longer updated version or documentation on the site.
I noticed other projects continue working.
Is there something wrong?

**Comment by knolleary** [comment]
Hi, thanks for raising. What module are you having an issue with? I'll investigate.

For questions like this, best to use the mailing list.

**Comment by chameleonbr** [comment]
node-red-contrib-redis

**Comment by knolleary** [comment]
Thanks, have forced through the update and it's there now. Not entirely sure what caused it to get stuck, but will investigate later. I'll need to check there aren't any other nodes in a similar state.

Let me know if it happens again.

**Comment by chameleonbr** [comment]
Thank you for your attention and I will sign up the group to address these issues.
