### ISSUE TITLE
Each flowchart should have its separate folder for static files.

### ISSUE THREAD

**Issue by tosone** [node-red/node-red#822]
Sometimes,i have a lot of flowcharts. the flowchart needs to store some static files. Thus, each flowchart should have its separate folder,and nodeRED should give each of these flowcharts a root directory.

**Comment by knolleary** [comment]
Hi,

for general feature requests/discussions, please use the [mailing list](https://groups.google.com/forum/#!forum/node-red)

Nick

**Comment by knolleary** [comment]
The [storage mechanism is pluggable](http://nodered.org/docs/api/storage/). If this is how you want node-red to store flows, you can create your own storage implementation and use that. We won't change the default filesystem storage plugin to split the flows across multiple files.
