### ISSUE TITLE
Can't use $(PORT) in MQTT port field due to validator

### ISSUE THREAD

**Issue by ozzieg** [node-red/node-red#825]
Is it possible to turn off the validator on the MQTT config node port field? It doesn't accept reading environment variable and it makes it hard to auto-deploy to a PaaS, like, Heroku.

**Comment by knolleary** [comment]
Hi,

This is a current limitation of the environment variable substitution. You can still deploy with validation errors, so it shouldn't stop you using `$(PORT)` in the field - it will flag it up though, so the user experience isn't ideal.

What we need to consider adding a global validation that allows `$(VAR)` values through even if the node's own validation fails.
