### ISSUE TITLE
MQTT publish when not yet connected

### ISSUE THREAD

**Issue by paulRenault** [node-red/node-red#829]
Hello,

I had a crash when I tried to publish a message sometime after a mqtt disconnect and before a mqtt connect.

The crash occurred because the variable client is null.

In the file mqttConnectionPool.js

Before :
`publish: function(msg) {
if (client.isConnected()) {
client.publish(msg.topic,msg.payload,msg.qos,msg.retain);
} else {
if (!connecting) {
connecting = true;
client.connect(options);
}
queue.push(msg);
}
},`

After :
`publish: function(msg) {
if (client && client.isConnected()) {
client.publish(msg.topic,msg.payload,msg.qos,msg.retain);
} else {
if (!connecting && client) {
connecting = true;
client.connect(options);
}
queue.push(msg);
}
},`

**Comment by knolleary** [comment]
As per my comment on your pull request #828, `mqttConnectionPool.js` is deprecated and should not be used by 3rd party nodes. It will be removed in a future release of node-red.
