### ISSUE TITLE
Cannot embed node-red in a loopback.io server

### ISSUE THREAD

**Issue by thaiat** [node-red/node-red#831]
As loopback.io is built on top of express, i was expecting this to work "as is"...

This is not the case : https://github.com/strongloop/loopback/issues/2139

**Comment by knolleary** [comment]
You have not called `RED.start()`, so the node-red runtime is not actually running so the routes don't behave as expected.

**Comment by thaiat** [comment]
@knolleary thks for the quick reply,
i added `RED.start()` and now can see the node-red ui correctly populated

However when i start a simple flow, i get a connection error in the dashboard and nothing outputed to the DEBUG tab

<img width="1770" alt="node-red" src="https://cloud.githubusercontent.com/assets/4806944/13711656/745e7796-e7c8-11e5-9168-5d6de627558f.png">

**Comment by thaiat** [comment]
@knolleary thks for the quick reply,
i added `RED.start()` and now can see the node-red ui correctly populated

However when i start a simple flow, i get a connection error in the dashboard and nothing outputed to the DEBUG tab

<img width="1770" alt="node-red" src="https://cloud.githubusercontent.com/assets/4806944/13711656/745e7796-e7c8-11e5-9168-5d6de627558f.png">

**Comment by thaiat** [comment]
the client error is :
```
WebSocket connection to 'ws://localhost:3000/red/comms' failed: Connection closed before receiving a handshake response
```

**Comment by thaiat** [comment]
the express integration works fine if this is of any help....

**Comment by knolleary** [comment]
You need to pass an HTTP server object as the first argument to `RED.init()`, not an express instance. This is because it is not possible to attach websocket listeners to express instances - you have to do it with the underlying HTTP server.

**Comment by thaiat** [comment]
any idea where i grab the http server from the loopback instance obj ?

**Comment by knolleary** [comment]
I'm not that familiar with loopback (although I really ought to play with it...)

**Comment by thaiat** [comment]
all right i found a way:
```js
var loopback = require('loopback');
var boot = require('loopback-boot');
var RED = require('node-red');

var settings = {
    httpAdminRoot: '/red',
    httpNodeRoot: '/red',
    userDir: '/Users/thaiat/.node-red',
    uiPort: 3000,
    functionGlobalContext: {} // enables global context
};
debugger;
var app = module.exports = loopback();

app.start = function() {
    // start the web server
    return app.listen(function() {
        RED.start();
        app.emit('started');
        var baseUrl = app.get('url').replace(/\/$/, '');
        console.log('Web server listening at: %s', baseUrl);
        if (app.get('loopback-component-explorer')) {
            var explorerPath = app.get('loopback-component-explorer').mountPath;
            console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
        }
    });
};

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
    if (err) throw err;

    // start the server if `$ node server.js`
    if (require.main === module) {
        // we grab the http server from loopback instance
        var server = app.start();
        // first parameter needs to be the http server for websocket to works properly, do not try to pass here app : https://github.com/node-red/node-red/issues/831
        RED.init(server, settings);
        app.use(settings.httpAdminRoot, RED.httpAdmin);
        app.use(settings.httpNodeRoot, RED.httpNode);
    }
});
```

**Comment by thaiat** [comment]
@knolleary i am pretty experienced with loopback, i offer you a deal, i learn you everything i know about it, in return you help me with my little node-red experiment

or you can have a look at my last talk on loopback:
https://www.youtube.com/watch?v=EEPzQLRsVQk

**Comment by sachinhub** [comment]
There is a a node-RED contrib module available @ https://github.com/EdgeVerve/loopback-connector-nodes-for-Node-RED which allows running Node-RED from within loopback application. It also provides nodes which can observe events happening in loopback application and trigger a flow.

Please have a look at the wiki page @ https://github.com/EdgeVerve/loopback-connector-nodes-for-Node-RED/wiki/Loopback-connector-for-Node-RED

**Comment by sachinhub** [comment]
@knolleary and @thaiat I request you to visit the project at https://github.com/EdgeVerve/loopback-connector-nodes-for-Node-RED/wiki/Loopback-connector-for-Node-RED

This project provides a set of node red nodes to observe events happening in loopback application and trigger a node-RED flow.

This is my recent work which our company has open-sourced. Your feedback would really help.
