### ISSUE TITLE
Add dismissible notifications in the editor for runtime events

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#832]
There are certain events that occur in the runtime that if you don't watch the log output you don't know have happened, but we should really make sure the user knows about. The list of such events includes:
- restored a flows from backup after a zero-length flow file was detected
- flows are not running due to missing node types (either on startup or after a deploy)

A component in the runtime should be able to send a message to the editor that gets displayed as a notification. The notification stays in place until the user dismisses it. The message must be persistent in the runtime so each time an editor connects it gets displayed. The component that generated the message must be able to clear the message (both in the runtime and any connected editors) when the condition is resolved.

Of the events listed above, they would get cleared by:
- (restored flows) - when a new set of flows are deployed
- (not running) - when the missing types are registered and the flows have now started

Need to consider the behaviour of an editor that is connecting from a fresh page load, versus a client that is reconnected after a websocket connection loss. The reconnect would trigger the messages being sent over comms, but the editor should not display them if they have already been dismissed by the user.

**Comment by Belphemur** [comment]
@knolleary would this "notification/message system" be available to node developers ?

**Comment by knolleary** [comment]
@Belphemur It wasn't a use case I was considering - did you have something in mind?

**Comment by Belphemur** [comment]
Mostly the same use case as for the status. A notification would be more visible in case of significant failure in the node (like an HTTP Error for an API call) or any significant breaking into the flow.

**Comment by knolleary** [comment]
This type of runtime notification is now in use with Node-RED.
