### ISSUE TITLE
Flow Deploy overwrites custom configuration fields.

### ISSUE THREAD

**Issue by LeifLazar** [node-red/node-red#841]
Hi,

I'll start with a picture:
![mqtt_default_config](https://cloud.githubusercontent.com/assets/12189877/13875849/f627b91e-ed08-11e5-9b0e-def037eb68d4.png)

This is the flows_hostName.json file:
```json
[
   {
      "id":"SomeId",
      "type":"mqtt-broker",
      "z":"",
      "broker":"my.server.com",
      "port":"1883",
      "clientid":"ClientId",
      "usetls":false,
      "verifyservercert":true,
      "compatmode":true,
      "keepalive":"15",
      "cleansession":true,
      "willTopic":"",
      "willQos":"0",
      "willRetain":null,
      "willPayload":"",
      "birthTopic":"",
      "birthQos":"0",
      "birthRetain":null,
      "birthPayload":"",
	  "isDefaultConfig":true
   }
]
```

The last field in the config file, isDefaultConfig, is not a standard one.

What I'm trying to achieve here is to set up a predefined MQTT broker that shouldn't be editable or deletable, while allowing users to define their own brokers.

The problem is that, somewhere along the way, that custom field gets removed from the node configuration.
I tried removing the "Update" button from the form by changing the behaviour of the `showEditConfigNodeDialog` function in `node-red/editor/js/ui/editor.js`.
The first few lines of that function look like this:
```javascript
function showEditConfigNodeDialog(name,type,id) {
        var adding = (id == "_ADD_");
        var node_def = RED.nodes.getType(type);
        editing_config_node = RED.nodes.node(id);
```

When I do a `console.log(editing_config_node);` I can see all of the fields that are present in the .json file except `isDefaultConfig`.

Another problem is that if I Deploy my flow the .json file will be overwritten with my custom fields removed from the configuration.

I assume that there's a place where these fields are defined but I couldn't find it. Can I get some help?
Also, I'm new to node-red so I might've missed something obvious.

Thank you!

**Comment by knolleary** [comment]
There are two types of node properties; those that are defined in the node's html definition and those reserved by the editor - details [here](http://nodered.org/docs/creating-nodes/properties). Anything else gets ignored/stripped whenever the flow is exported/deployed by the editor - see `convertNode` in `editor/js/nodes.js`, 

We do not support the ability to have read-only nodes that cannot be deleted.

**Comment by knolleary** [comment]
As this is a request for help, rather than an issue, I'm going to close. If you still have questions, please follow up on the mailing list.
