### ISSUE TITLE
rbe node unexpected result, bug?

### ISSUE THREAD

**Issue by greyltc** [node-red/node-red#843]
I'm using v0.13.3 and I have a rbe node configured as `block if value changes by more than` `500` with the Start Value set to be `9999`.

If I send a msg.payload of 14 twice consecutively to my rbe node, I expect the first message to be dropped (since abs(9999 - 14)>500) and the second message to make it through (since abs(14-14)<500), but instead they both get dropped.

Am I missing something or is this a bug?

**Comment by dceejay** [comment]
good question... the current behaviour is that if a value is outside the desired range it is ignored (and thus doesn't count towards the next comparison)... so the second comparison in your example is still abs(9999 -14) > 500 - so also gets ignored...

**Comment by greyltc** [comment]
Oops! Looks like I posted this issue to the wrong project. I thought rbe was a core node. I'll move this to node-red/node-red-nodes

**Comment by dceejay** [comment]
no problem - it'll be me looking at it again anyway...
