### ISSUE TITLE
Abort trap: 6 on call to node.error

### ISSUE THREAD

**Issue by rgstephens** [node-red/node-red#844]
node-red is exiting on a call to node.error with the following:

```
Assertion failed: (object->InternalFieldCount() > 0), function Unwrap, file ../src/util-inl.h, line 117.
Abort trap: 6
```
I suspect it's related to [node.js issue #9028](https://github.com/nodejs/node-v0.x-archive/issues/9028) and I'm making a build of node to see if the issue is resolved.

Still, the specifics of the problem make me wonder if I'm doing something wrong or if there's a node-red issue. The error occurs only when I load the payload with the response from an HTTP request like this:

```
node.msg = { payload: response };
node.error(errorMsg, node.msg);
```
If I don't modify the message payload and make the node.error call, then the abort doesn't occur. Am I modifying the message or payload incorrectly?

After doing more testing, it looks like the problem is the HTML in the body portion of the response. If I exclude the body object from the payload then the problem does not occur.

```
"body":"<!doctype html>\n<html>\n<head>\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\n    <meta charset=\"utf-8\" />\n    <title> - APIC - Enterprise Module</title>\n\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <meta name=\"theme-color\" content=\"#28cdc1\">\n    \n    <link href=\"/fonts/font-awesome-4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n    <link rel=\"stylesheet\" href=\"/core/css/common.css\" />\n    <script type=\"text/javascript\" src=\"/core/requirejsAdmin.js\"></script>\n    <script type=\"text/javascript\" src=\"/libs/apic-em.js\"></script>\n    \n</head>\n<body>\n  <!doctype html>\n<html>\n<head>\n    <meta charset=\"utf-8\" />\n    <title>Error</title>\n</head>\n<body>\n  <h1>invalid csrf token</h1>\n  <h2></h2>\n  <pre></pre>\n</body>\n</html>\n</body>\n\n</body>\n</html>\n<script type=\"text/javascript\">\n  var appcontext = {\n    name: \"\",\n    uuid: \"\"\n  };\n</script>\n<script type=\"text/javascript\">\n  window.GRAPEVINE_API_URL_PREFIX = \"/apic/grapevine/api\";\n  window.API_URL_PREFIX = \"/apic/api/v1\";\n  window.API_URL_PREFIX_V0 = \"/apic/api/v0\";\n  window.CSRF = \"\";\n</script>\n\n\n"
```

**Comment by knolleary** [comment]
What version of node are you using?

In you example code:
```
node.msg = { payload: response };
node.error(errorMsg, node.msg);
```

What exactly is `response`? And is there a reason you're setting it under a property of `node`? The intention of the message object you pass `node.error` is it to be the original message the node received that caused the error - it isn't meant to be the error message as that doesn't let the user recover the original message in case they need other properties of it in order to recover.

**Comment by rgstephens** [comment]
I'm on Node 0.12.6.  `response`, is an http response object.

I included the entire response to provide all of the information regarding the error to the user. It doesn't seem like a call to node.error should cause node red to abort.

**Comment by knolleary** [comment]
I agree it shouldn't cause an abort - but this is going to be a low-level node.js thing.

As I said, normally we'd expect you to pass through the originating message so the user can determine what to do next without losing the other properties that it held. You can of course attach additional properties to the message if you want - I would suggest not attaching the full response object, but pull out the bits that will be of interest to the user.

**Comment by rgstephens** [comment]
Thanks, that's what I've done.

**Comment by dceejay** [comment]
OK to close this issue ?

**Comment by rgstephens** [comment]
Shouldn't Node Red catch this error instead of failing?

**Comment by knolleary** [comment]
I'm not sure this is something we can catch... Do you have a more complete log output that shows how it's exiting?

**Comment by rgstephens** [comment]
Thanks for looking at this.  Closing.
