### ISSUE TITLE
Inject node runs at wrong time

### ISSUE THREAD

**Issue by Dyldog** [node-red/node-red#845]
Hey guys,

I've got an inject node setup to run at a specific time, but it doesn't run at the time I want. I'm pretty sure it's because my local time zone isn't being acknowledged properly.

I am able to get my current time with 'new Date().toLocaleString();' from a function node. But it seems like the inject node doesn't use my local time, it uses whatever time is given by 'new Date()'.

I've tried setting the TZ environment variable, but no dice.

Any help would be much appreciated.

**Node.js Version:**  v0.12.4
**Node-Red Version:** v0.13.1

**Comment by knolleary** [comment]
Sorry, I know I wrote a reply to this issue a few days ago, but I must have not hit the button...

There was a recent discussion on the mailing list regarding timezone handling the Inject node. Someone volunteered to take a look at work up a pull-request. Done right, that ought to help here.

**Comment by Bra1nK** [comment]
Similar issue here although my server is set to the correct time zone (London-UK) the node-red inject node appears to think BST  starts on the 3rd April (Australia, Mexico ?)  rather than the correct 27th March. Caused me some issues and puzzlement.

**Comment by ElectronHacks** [comment]
Any updates on this issue? My project doesn't seem to be injecting at the proper time as well.
Thanks.

**Comment by knolleary** [comment]
@electronhacks any more information you can share that may help us? Is it consistently wrong by a fixed amount? What timezone is your node-red instance running under?

**Comment by ElectronHacks** [comment]
Actually all is well this morning. I had my Raspberry pi localization and time zones all set but there must have been some other user error in my project, maybe I just needed some sleep. It is working fine now up to the minute! Thanks!

**Comment by petong** [comment]
I'm hitting this as well, running node-red inside docker. timezone is set to PST8, and `/etc/localtime` is mounted into the running docker image. I can verify running date inside the image gives me the correct time, yet even the logs coming from node-red docker image are in UTC.

Happy to help debug and provide more info

**Comment by petong** [comment]
Just discovered that adding `process.env.TZ = "America/Los_Angeles";` to `settings.js` fixes the issue. Perhaps putting a default UTC line in the config would be beneficial?

**Comment by guimeca** [comment]
Hello @petong I tryed to add this line to settings.js but didnt work, a try to save in diferent positions but no success too.

**Comment by jhottell** [comment]
I actually had to use this yesterday and it worked in my docker containers, stopped them and edited settings.js and fired them back up.
 
Add `process.env.TZ = "America/Chicago";` (change to the desired time zone) to "settings.js" OUTSIDE of the "module.exports" object.
i.e. just paste that line right above "module.exports = {"

Credit to "The Smart Enough Factory" on YouTube for pointing out where to put it.

**Comment by guimeca** [comment]
@jhottell I find out the problem, I was using "" instead of '', when I set with '' it worked !

thank you, I left a like in the channel.




![image](https://user-images.githubusercontent.com/112285298/187068119-9d050024-a908-47e4-a0b8-62398529ef1b.png)

**Comment by Steve-Mcl** [comment]
Closing thread as it is resolved.
