### ISSUE TITLE
Error: Lost connection to server

### ISSUE THREAD

**Issue by MarineElectric** [node-red/node-red#846]
I'm running node-red in a raspberry pi 2 with raspbian.

I've installed node-red and a few nodes, modbustcp and others... (Don't know if it matters)

The web works, but few minutes go by, I get that error, and it disconects. (The connection does not stop working really, I'm SSH and does not disconnect) but Node-red conection stops.

Any ideas? 

Thanks btw.

![123123](https://cloud.githubusercontent.com/assets/17979775/13915265/f80619e0-ef53-11e5-8a47-faabd28c2a98.png)
![sin titulo](https://cloud.githubusercontent.com/assets/17979775/13915266/f80a61f8-ef53-11e5-8cd1-16acf9c65f13.png)

pics relateds.

**Comment by hardillb** [comment]
Can you add the node-red console output so we can see if there are any error messages that might point us in the right direction

**Comment by MarineElectric** [comment]
If I understanded well, this is the messages that I've got. 

![](https://i.gyazo.com/3eec2e8eaa4d698b71de038d7579d70f.png)

I see the errors, but don't know what can I do. :(

**Comment by MarineElectric** [comment]
I just realiced that when I get the error, I can still work, I can add nodes and deploy, but I got "Error: no response from the server" And a few seconds later I try again and it works. (Or it seems like works)

But constantly Im getting this error, lost conection. :(

**Comment by knolleary** [comment]
From that screenshot, it appears the freeboard node is crashing node-red.

The quickest solution will be to remove that node (delete node-red-contrib-freeboard from `~/.node-red/node_modules`).

I would suggest raising an issue against that node so they can have a look at what caused this. The key part to include is the 'Uncaught Exception...' message (and the lines that follow) - https://github.com/urbiworx/node-red-contrib-freeboard/issues

**Comment by MarineElectric** [comment]
Sounds possible, I'll try it.

I restarted node and got this, perhaps clarifies something.

Thanks a lot for the responsing


![](https://i.gyazo.com/3225566f8d0f25e10698afa2fcf6fd88.png)
