### ISSUE TITLE
SIGSEV using function node and file node

### ISSUE THREAD

**Issue by dzdas** [node-red/node-red#847]
Os : Ubuntu MATE
node -v : 5.9.0
node-red :  0.13.3

I have the following flow:

interval(repeating) -> function(sets msg.filename) -> file -> ... 

Depending on the size of the file this flow will always crash with the following error :  

![screenshot](https://cloud.githubusercontent.com/assets/10877340/13925801/9f4d116e-efee-11e5-988f-f1be2b097a4c.png)

A file of about 2 mb takes 4 iterations of the flow to cause the error, a smaller file will take longer. 

A flow without the function where the filename is set in the file node itself will not fail.

The error occurs during  this.script.runInContext(context) in the callback of the nodes input event. I followed this into the "var" module, https://github.com/vdsabev/var, but have had no luck so far.
I think it's something to do with contextify module.

**Comment by dceejay** [comment]
What happens if you try using the switch node to set the msg.filename rather than a function node ?

**Comment by dzdas** [comment]
Using the change node does not cause the error. This is expected because I think the the issue lies with the function node. As I said before the sigsev is caused somewhere inside  this.script.runInContext(context). 

The repeat rate on the inject node is about four seconds, however this doesn't effect the outcome, I have attempted this with an inject rate of 20 seconds and it will still fail after the same number of iterations.

Thanks for the reply.

**Comment by knolleary** [comment]
This will be an issue with the underlying node.js vm module in the node 5.x stream; it should not be possible for application code to cause a seg fault like this. It would also be useful to create as minimal a test case as possible for it.

**Comment by dceejay** [comment]
Indeed - does this also occur on the 4.x LTS version of node.js ?

**Comment by dzdas** [comment]
Sorry for the late reply very bust at the moment, I am not sure whether the error occours in the LTS

**Comment by knolleary** [comment]
@dzdas yes, as I said, this is an issue with the underlying node runtime - it is not a something we can fix in node-red code.
