### ISSUE TITLE
nod-red sense hat node using lots of CPU

### ISSUE THREAD

**Issue by sisomm** [node-red/node-red#848]
Hi, 

I notice that the CPU load is high even if it just sits there 
<img width="773" alt="skjermbilde 2016-03-23 kl 22 36 48" src="https://cloud.githubusercontent.com/assets/4808844/14001798/40ab59d0-f148-11e5-8a01-7fd0c18becba.png">

When I look at the details I see that there is a python process talking to the sense hat. Is that a common problem? 

<img width="779" alt="skjermbilde 2016-03-23 kl 22 37 53" src="https://cloud.githubusercontent.com/assets/4808844/14001843/7a51a02c-f148-11e5-9d50-321a74225b63.png">

Note: I[ did have an issue](https://github.com/raspberrypi/documentation/issues/326#issuecomment-196622229) with updating the EEPROM on the sense HAT. Could this be related? It seems to be working fine now.

**Comment by knolleary** [comment]
I assume you have some senseHat nodes deployed? Have you got any set to emit motion events?

**Comment by knolleary** [comment]
From reading the issue you linked to, I assume you're seeing this on a pi3? I did all the development on a pi2 - will try it in the pi3 to see if there's a difference.

**Comment by knolleary** [comment]
Just plugging it into a Pi3 and run with the motion events enabled (as that causes the most work load in the script), and the python process is sat at about 4% CPU usage.

A test you could do would be, with node-red stopped (or without any sense hat nodes deployed), run the python code directly:

    /home/pi/.node-red/node_modules/node-red-node-pi-sense-hat/sensehat

Once it has started, check the CPU usage - in this mode it ought to be <1% CPU. Then type

    X <enter>

into the terminal window. This will turn on reporting of the motion events - they should start streaming into the terminal. Check the CPU usage again - roughly 4% for me.

When you're done, hit `ctrl-c` in the window to quit.

**Comment by sisomm** [comment]
I stopped Node-red,

got 0% ish CPU load,

and  started

/home/pi/.node-red/node_modules/node-red-node-pi-sense-hat/sensehat

And it was back on almost exactly 300%

Hitting the X increased the load to ca. 303%

Sorry if I can't answer tomorrow before late or even friday. We have a
digital-free day in all the family tomorrow. Happy easter, btw!

cheers, Simen

**Comment by sisomm** [comment]
And yes - it is a PI3!

**Comment by sisomm** [comment]
I ran this command on my pi.. 
sudo python -m trace --count sensehat.py

Which resulted in this .cover file after a few seconds (I stopped it with ^C)

[sensehat.txt](https://github.com/node-red/node-red/files/188856/sensehat.txt)

**Comment by knolleary** [comment]
@sisomm around line 221 of sensehat.py there's a `select.select` statement. Could you wrap it like this:

      t1 = time.time()
      ready = select.select(files, [], [], 0.01)[0]
      t2 = time.time()
      print(t2-t1)

And then run it (directly, not with node-red). The 0.01 in the select line is how long it times out if there's nothing to be done. If I reduce that to 0, I get 100% cpu usage as it's never given a chance to rest. For me, 0.01 gives cpu usage of 4%. The debug above is to see if the select statement is pausing for 0.01 as we expect it to.

You could also try increasing that value to 0.05 (without the above debug print statement) - any more and it will start impacting the rate at which it'll be able to report sensor data.

**Comment by sisomm** [comment]
0.0101029872894

0.0100951194763

0.0100951194763

0.0100920200348

0.0100920200348

0.0100910663605

0.0100910663605

0.0100898742676

0.0100901126862

0.0100898742676

0.0100901126862

0.0100901126862

0.0100908279419

0.0100901126862

0.0100739002228

0.0100901126862

**Comment by sisomm** [comment]
Sorry Wife wants something. I will try the .05 later

**Comment by knolleary** [comment]
Ok, so the timeout is working as expected. Would be interested to hear what a longer timeout does to your cpu usage. Also, have you overclocked the pi?

**Comment by sisomm** [comment]
printouts with .05. Still 300% CPU

And no, I haven't overclocked it. We could do a skype session if you'd
like.

0.0501070022583

0.0501058101654

0.0501070022583

0.0501048564911

0.0501079559326

0.0501070022583

0.0501079559326

0.0501070022583

0.050106048584

0.0501081943512

0.0501070022583

0.0501089096069

0.0501070022583

0.0501070022583

**Comment by sisomm** [comment]
BTW kudos for making Node-RED. I am the founder of www.kidsakoder.no - the norwegian version of Computing at School / Code Club. Node-RED is an excellent intro to coding for youth - when they get past the level of Scratch - and find that bare Python is a step back when it comes to the kind of instant gratification they are used to with Scratch. Keep up the good work! Cheers, Simen

**Comment by sisomm** [comment]
If it can help: I ran the command 
** time -p python sensehat.py**
...pressed <ctrl>C after a few seconds and this is the output

**real 8.06
user 8.21
sys 15.91**

**Comment by sisomm** [comment]
I have done a complete reinstall of everything, and the CPU load is now low. I am sorry to have bothered you; it must have been something to do with the settings I changed during the firmware upgrade ordeal. I close the issue.

**Comment by larkolab** [comment]
Hello,
I just ran into the exact same issue, with a fresh install of Raspian (Release 2017-03-02) on a RPi3.
As soon as I add a sense-hat node in a flow, the CPU reach 300%.
The same flow was running on a PiZero with no more than 12% CPU usage.
Since this issue is old, have you identified the cause already?
Thanks!

**Comment by larkolab** [comment]
I've check the timer as asked above, and it's working fine.
I've also tried to put 0.1 instread of 0.01 and CPU is still 300%.

**Comment by sisomm** [comment]
I gave up and reinstalled the Raspberry. The problems went away then, and I can not help you with more details. Sorry!

**Comment by dceejay** [comment]
which versions of node.js and node-red are you using ?
It may be that you have a combination of newer node.js but older binary files, from a partial upgrade.

**Comment by larkolab** [comment]
I've tried a fresh reinstall atfer having seen this thread, but it didn't helped.

I've done the same on the fresh install and after having run the update-nodejs-and-nodered script.
Same result.

After the upgrade of node-red, have the following versions:
Welcome to Node-RED
===================
5 Mar 20:18:09 - [info] Node-RED version: v0.16.2
5 Mar 20:18:09 - [info] Node.js  version: v6.10.0
5 Mar 20:18:09 - [info] Linux 4.4.50-v7+ arm LE

@dceejay Which older binaries are you refering to?

Thanks for your answers!

**Comment by larkolab** [comment]
oops, and the bold text in my previous message was not intended :)

**Comment by dceejay** [comment]
That should be all good.Not sure what to suggest next. What else is your flow doing ? Are there any other non-core nodes loaded ?

**Comment by larkolab** [comment]
I've tried, after the fresh install, a simple flow with just { Inject -> SenseHat } and problem is there.
Anyway, even without node-red, just launching the /usr/lib/node_modules/node-red-node-pi-sense-hat/sensehat script is enough to reproduce the problem. :(

**Comment by larkolab** [comment]
Just in case someone has the same issue, the solution is described here:
https://github.com/RPi-Distro/python-sense-hat/issues/64
