### ISSUE TITLE
Using custom variables in API key field

### ISSUE THREAD

**Issue by egadgetjnr** [node-red/node-red#850]
Hi There,
I'm fairly new to Node-Red and was hoping you could help me (I'm not sure where else to go for help and can't find anything on the web to answer my question).

I have a few people whom are using a project in the Blynk app, and each of them have a Hardware Device.

I was looking at routing the data (that is communicated using MQTT for legacy reasons) from their hardware device through to the relevant Blynk App and although I could just use a function in Node-Red, It makes it difficult to add more devices in the future.

I was thinking of having Node-Red run a SQL Query based on the users Hardware ID and retrieve their Auth Key, however, I'm not sure how to set using the Blynk Node this Auth Key as a variable.

Does what I'm trying to say make sense? lol. Is there a Node-Red specific way to do this?

Thanks heaps for your help.

**Comment by knolleary** [comment]
Hi, the best place for this sort of question is the mailing list - linked to from the bottom of nodered.org and on the front page of docs under 'other places to get help': http://nodered.org/docs/

This issue list is for bugs and issues with the core of Node-RED and the blynk node is not one maintained by us.

Thanks,
Nick
