### ISSUE TITLE
Warning appearing for MQTT Connections

### ISSUE THREAD

**Issue by egadgetjnr** [node-red/node-red#851]
Hi There,
I'm getting a strange anomaly in the debug and log for all MQTT connections (tried 2 servers so far, they're both the same.).

I've narrowed it down to the the MQTT input, other Nodes aren't causing it, but cannot figure out what is causing it.

On the MQTT server side, I can see the connection being established fine.

I'm running version v0.13.4

This appears to have started overnight.

log:
`28 Mar 23:50:56 - [info] Server now running at http://127.0.0.1:1880/`
`28 Mar 23:50:56 - [info] Starting flows`
`28 Mar 23:50:56 - [info] Started flows`
`29 Mar 00:13:14 - [info] Stopping flows`
`29 Mar 00:13:14 - [info] Stopped flows`
`29 Mar 00:13:14 - [info] Starting flows`
`29 Mar 00:13:15 - [info] Started flows`
`29 Mar 00:13:15 - [warn] Communication send error: Error: not opened`
`29 Mar 00:13:16 - [info] [mqtt-broker:7470c6d4.677748] Connected to broker: mqtt://test.mosquitto.org:1883`
`29 Mar 00:13:16 - [warn] Communication send error: Error: not opened`
`29 Mar 00:13:17 - [warn] Communication send error: Error: not opened`
`29 Mar 00:13:19 - [warn] Communication send error: Error: not opened`
`29 Mar 00:13:20 - [warn] Communication send error: Error: not opened`
`and on....`

**Comment by knolleary** [comment]
I know you popped up on Slack with the same question, but I don't think we fully resolved it.

That comms message is related to the websocket connection between the runtime and editor. Where are you running? Is it on a local machine or cloud-hosted server?

Whilst we can add some error handling to avoid trying to write to a closed connection, I want to understand how it has got into this state - we already have code to tidy up closed sockets. Any background info you could add would be helpful.

**Comment by knolleary** [comment]
(slack/mailing list... it was one of those...)

**Comment by egadgetjnr** [comment]
@knolleary 
It was in Slack.

I don't think it's resolved at all as It's still occurring.
It is on a cloud hosted (Azure-Ubuntu 14.04) server.

I have no idea how it started, It literally happened overnight and when nothing was being done to the servers.

I've tried other Brokers and the same issue occurs. As soon as I remove the MQTT Node from the workflow completely, the message stops.

**Comment by jschuryk** [comment]
not sure if I'm hijacking or not, but I started getting the same error when I enabled authentication for node red administration.  Wanted to open up node-red to the outside world - uncommented the adminAuth section in settings.js.  I was then able to login succesfully with my user/pass but started getting those same messages.  I went back and commented out that section again, restarted and the errors went away.  Everything worked perfectly even when the warnings were appearing.

I am on a Raspberry Pi 2:

Welcome to Node-RED
===================

22 Apr 14:45:03 - [info] Node-RED version: v0.13.4
22 Apr 14:45:03 - [info] Node.js  version: v0.12.9
22 Apr 14:45:03 - [info] Linux 4.1.7-v7+ arm LE

**Comment by knolleary** [comment]
@jschuryk not been able to track this one down yet, but your comment is useful, so thanks!

**Comment by knolleary** [comment]
@jschuryk did you reload the editor in your browser after enabling adminAuth?

**Comment by knolleary** [comment]
I now understand the apparent link to the MQTT nodes.

When an MQTT node connects, it sends a status message over comms to indicate this state. The message is set so that whenever an editor's comms link connects, it will get republished so the editor's view is up to date.

Now, for some reason, the websocket connection is in a bad state. When the editor connects, we publish the state message and fail the connection. The editor attempts to reconnect 1 second later and the cycle repeats.

The question is then why have we received a new websocket connection event but the websocket is not ready for writing to.

**Comment by jschuryk** [comment]
My initial answer would have been 'of course I reloaded', however I just performed the test again, and coming up from a fresh browser session, I don't see the error messages.

Jerry

**Comment by nsw935** [comment]
Any epiphanies on this topic since last month?  I have the same problem.  My MQTT pub and sub nodes are functional, but I get the warning above once per second on the node window and in the debug window.  Like the above, this started when I enabled basic authentication in settings.js, and also have a flow containing an MQTT config node.

**Comment by egadgetjnr** [comment]
Somehow it stopped coming up for me and I have no clue how/why. I think
maybe it could have been on the sub node.

I'll have a play with it this weekend as I think maybe I bypassed the sub
stage of the project in working on and decided to come back to it later.

**Comment by knolleary** [comment]
Would like to know if this is still an issue with the latest 0.14.6 release.

**Comment by kriztoph** [comment]
This is still an issue for me and I do get it after enabling `adminAuth`.

**Comment by porkyneal** [comment]
Just stumbled across this issue also, again as @kriztoph mentioned, if I disable adminAuth it goes away.

**Comment by i8beef** [comment]
Also getting this issue as soon as adminAuth is turned on.

**Comment by atsakir** [comment]
Hi, also getting the "Communication send error" after enabling adminAuth. 
Flow includes johnnyFive nodes (GPIO access) on RPi so I have to run node-red as root, if that helps any. warnings start as soon as node-red starts even without editor or dashboard open on browser

**Comment by i8beef** [comment]
To add on what atsakir said, my installation does NOT use GPIO at all... Everything still seems to WORK right, I just get the flood of warnings. Willing to enable whatever logging, etc., would help here to diagnose.

**Comment by jdwaymire** [comment]
I am having the exact same issue after enabling auth on mosquito...  Disable auth and errors stop, the connection is  establishing as I can see normal MQTT traffic in between the error messages.

**Comment by jdwaymire** [comment]
OK...  this is what I have found out, for my issue anyway...  going over the thread and seeing that @knolleary had asked if the browser was closed between getting this error, it got me thinking.  I normally have node-red ui open at my office remotely and my home computer.  I shutdown node-red, closed my browser, enabled auth on mosquito, opened the node-red config and just changed my ui port to make sure anywhere else I had the ui open was unable to connect and started everything back up.  NO WARNINGS..   None...

**Comment by TTVert** [comment]
I've also got the same issue when enabling auth.  Disabling also stops the errors.

**Comment by JonSilver** [comment]
I realise it's a closed issue, but... Over the past few days I've been seeing this error popping up in my debug pane too, with 0.18.4 hosted on Azure using the https://github.com/jmservera/node-red-azure-webapp method. MQTT broker is CloudMQTT, adminAuth is enabled. I'm using websockets between a ReactJS web app and Node-Red too, though this is a new feature added only in the past couple of weeks so could conceivably have contributed. I've been running Node-Red this way for almost a year now, starting at v0.16.2, and have never seen this error before the last couple of days. Happy to provide any additional information that might help nail it down.
