### ISSUE TITLE
Node red shuts down

### ISSUE THREAD

**Issue by idi0tech** [node-red/node-red#852]
Hi all

Ive been using node red for a while on a Raspi 2 running rasbian wheezy. Node red shuts down two to three times a day and has to be restarted.

Its a major problem as it manages my serial coms for openhab

Can anybody help please?

**Comment by knolleary** [comment]
Hi, to help we need some more information:

- what version of node-red are you running? How did you install it?
- what version of node.js are you using?
- How are you running node-red?
- What does the node-red log output say to indicate why it may have shutdown?

**Comment by idi0tech** [comment]
im using Node-RED version: v0.12.5-git and Node.js  version: v0.12.6 
Im Running node red on a raspberry pi 2 by sudo su > cd node-red > node red
I interact with the Pi via MobaXterm and sometimes via VNC

As for the log file I dont know where to find it.

**Comment by dceejay** [comment]
If you are just running "node red" then the log will be in that console window... unless you re-direct it somewhere.

**Comment by dceejay** [comment]
if you are running using a terminal program you probably have to leave the terminal window open... 
Also you are not limiting the memory usage in any way - so depending on what your flow is doing you may be running out of space... see - http://nodered.org/docs/hardware/raspberrypi#starting-node-red

**Comment by idi0tech** [comment]
Hi

This is what appears in the terminal after it shuts down

29 Mar 17:29:21 - [info] Node-RED version: v0.12.5-git
29 Mar 17:29:21 - [info] Node.js  version: v0.12.6
29 Mar 17:29:21 - [info] Loading palette nodes
29 Mar 17:29:30 - [info] Settings file  : /root/.node-red/settings.js
29 Mar 17:29:31 - [info] User directory : /root/.node-red
29 Mar 17:29:31 - [info] Flows file : /root/.node-red/flows_brynbach.json
29 Mar 17:29:31 - [info] Server now running at http://127.0.0.1:1880/
29 Mar 17:29:31 - [info] Starting flows
29 Mar 17:29:31 - [info] [udp out:e3ca1e06.4c12b] udp ready: 10.10.100.254:8899
29 Mar 17:29:33 - [error] [function:as above with divide by zero added] SyntaxError: evalmachine.<anonymous>:9
        if numInput = 0;
           ^^^^^^^^
Unexpected identifier
29 Mar 17:29:34 - [info] [udp out:d1ca63ad.b65a08] udp ready: 255.255.255.255:50000
29 Mar 17:29:34 - [error] [mqtt in:home/openhab/out/RGBLight/command] topic not defined
29 Mar 17:29:34 - [error] [mqtt out:958d52a5.8f2bb8] missing broker configuration
(node) warning: possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:179:15)
    at Object.connections.(anonymous function).obj.on (/home/pi/node_modules/node-red-node-serialport/25-serial.js:214:63)
    at new SerialOutNode (/home/pi/node_modules/node-red-node-serialport/25-serial.js:78:23)
    at createNode (/home/pi/node-red/red/nodes/flows/Flow.js:273:18)
    at Flow.start (/home/pi/node-red/red/nodes/flows/Flow.js:60:43)
    at start (/home/pi/node-red/red/nodes/flows/index.js:251:29)
    at tryCatchReject (/home/pi/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/pi/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/pi/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/home/pi/node-red/node_modules/when/lib/makePromise.js:483:13)
(node) warning: possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:179:15)
    at Object.connections.(anonymous function).obj.on (/home/pi/node_modules/node-red-node-serialport/25-serial.js:214:63)
    at new SerialOutNode (/home/pi/node_modules/node-red-node-serialport/25-serial.js:81:23)
    at createNode (/home/pi/node-red/red/nodes/flows/Flow.js:273:18)
    at Flow.start (/home/pi/node-red/red/nodes/flows/Flow.js:60:43)
    at start (/home/pi/node-red/red/nodes/flows/index.js:251:29)
    at tryCatchReject (/home/pi/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/pi/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/pi/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/home/pi/node-red/node_modules/when/lib/makePromise.js:483:13)
29 Mar 17:29:35 - [info] Started flows
29 Mar 17:29:35 - [info] [udp in:bc74f8ee.e08798] udp listener at 0.0.0.0:8899
29 Mar 17:29:35 - [error] [udp in:bc74f8ee.e08798] Bad Multicast Address
29 Mar 17:29:35 - [info] [tcp in:a6e5ec1e.c96b7] listening on port 0
29 Mar 17:29:35 - [info] [udp out:d9e1def.ccaeda] udp broadcast ready: 4899 -> 192.168.1.183:48899
29 Mar 17:29:35 - [info] [udp in:de0ac7d8.1a9e3] udp listener at 0.0.0.0:8899
29 Mar 17:29:35 - [info] [udp in:df6c8205.b54bf] udp listener at 0.0.0.0:50000
29 Mar 17:29:35 - [error] [udp in:df6c8205.b54bf] Bad Multicast Address
29 Mar 17:29:35 - [info] [udp out:MiLight UDP send] udp broadcast ready: 8899 -> 255.255.255.255:8899
29 Mar 17:29:35 - [info] serial port /dev/ttyAMA0 opened at 9600 baud 8N1
29 Mar 17:29:35 - [info] [mqtt-broker:eb47249.50b8bd8] Connected to broker: mqtt://192.168.1.110:1883
29 Mar 17:29:35 - [info] [mqtt-broker:29ab0259.bbc58e] Connected to broker: mqtt://192.168.1.110:1883
29 Mar 17:29:35 - [info] [mqtt-broker:3df728f1.e3bd78] Connected to broker: mqtt://brynbach:1883
29 Mar 17:29:35 - [info] [mqtt-broker:daa711e7.3e267] Connected to broker: mqtt://brynbach:1883
29 Mar 17:29:35 - [info] [mqtt-broker:9c3aa628.081cc8] Connected to broker: mqtt://localhost:1883
29 Mar 17:29:35 - [info] [mqtt-broker:50c3edeb.2e75ac] Connected to broker: mqtt://localhost:1883
^C29 Mar 17:32:04 - [info] Stopping flows
29 Mar 17:32:04 - [info] [udp out:e3ca1e06.4c12b] udp output stopped
29 Mar 17:32:04 - [info] [udp in:bc74f8ee.e08798] udp listener stopped
29 Mar 17:32:04 - [info] [tcp in:a6e5ec1e.c96b7] stopped listening on port
29 Mar 17:32:04 - [info] [udp out:d9e1def.ccaeda] udp output stopped
29 Mar 17:32:04 - [info] [udp in:de0ac7d8.1a9e3] udp listener stopped
29 Mar 17:32:04 - [info] [udp in:df6c8205.b54bf] udp listener stopped
29 Mar 17:32:04 - [info] [udp out:d1ca63ad.b65a08] udp output stopped
29 Mar 17:32:04 - [info] [udp out:MiLight UDP send] udp output stopped

**Comment by dceejay** [comment]
any more updates ? did you find the log ? any more details ?

**Comment by idi0tech** [comment]
Hi.

Yeah it was a problem with using putty or mobxterm.

I opened a terminal within VNC and it now runs fine.  

Thanks all. :-)
