### ISSUE TITLE
[exec] add a timeout option

### ISSUE THREAD

**Issue by arthurlutz** [node-red/node-red#856]
It would be super useful to be able to have a timeout on the exec node. If the execution takes more than X time, then kill the process for example.

**Comment by dceejay** [comment]
Hi,

in general we prefer to raise and discuss ideas on the Google group unless there is an actual issue, but this does seem like a sensible thing to consider.

**Comment by knolleary** [comment]
This has been added to the 0.14.0 branch by this commit: bd59398cab675f9d750b734f95294e986fbbb92d
