### ISSUE TITLE
[exec] add a "no more than one execution at a time" for the exec node

### ISSUE THREAD

**Issue by arthurlutz** [node-red/node-red#857]
It would be nice to have a limit on the number of executions of a given exec node. For example configuring that if a previous exec has not finished, skip it. For a process that does not come back  this would prevent having a "fork bomb". 

This is related to #856

**Comment by dceejay** [comment]
Again - we prefer ideas to be discussed on the Google group unless there is a real issue to fix.

The exec node outputs can be used to block further execution if you need to.. See this for an example
http://flows.nodered.org/flow/cea8afa28b7a93ebdc0f
