### ISSUE TITLE
Clear contexts on unload test helper

### ISSUE THREAD

**Issue by sunbit** [node-red/node-red#858]
I was using the test helper from

https://github.com/node-red/node-red/blob/master/test/nodes/helper.js

when i realized some weird behaviour that i related to node context data, not ocurring in a real nodered instance. After some debugging I ended up cleaning contexts after each test. I've added

`contexts.clean({allNodes:[]})`

on 
https://github.com/node-red/node-red/blob/master/test/nodes/helper.js#L119

As i see a comment wondering if there was someting else to cleanup, should i make a pull request of it?

Thank you

**Comment by knolleary** [comment]
Looks sensible - and makes me aware I've not added context-accessing tests for the inject/change/switch nodes which would have tripped over this.

Will add for the next release.
