### ISSUE TITLE
v0.13.4, TypeError in TCP Request Node

### ISSUE THREAD

**Issue by akarak** [node-red/node-red#860]
v0.13.4 installed using npm. Node mode is "never - keep connection open" or "when character received is" (\0). Sometimes there is an error:

```
KFrame2Vizrt-0 TypeError: Cannot set property '0' of null
KFrame2Vizrt-0     at Socket.<anonymous> (D:\Tools\NodeJS\Node-Red\0.13.4\node-red\nodes\core\io\31-tcpin.js:472:40)
KFrame2Vizrt-0     at emitOne (events.js:77:13)
KFrame2Vizrt-0     at Socket.emit (events.js:169:7)
KFrame2Vizrt-0     at readableAddChunk (_stream_readable.js:146:16)
KFrame2Vizrt-0     at Socket.Readable.push (_stream_readable.js:110:10)
KFrame2Vizrt-0     at TCP.onread (net.js:529:20)
KFrame2Vizrt-0 4 Apr 21:10:20 - [red] Uncaught Exception:
KFrame2Vizrt-0 4 Apr 21:10:20 - TypeError: Cannot set property '0' of null
KFrame2Vizrt-0     at Socket.<anonymous> (D:\Tools\NodeJS\Node-Red\0.13.4\node-red\nodes\core\io\31-tcpin.js:472:40)
KFrame2Vizrt-0     at emitOne (events.js:77:13)
KFrame2Vizrt-0     at Socket.emit (events.js:169:7)
KFrame2Vizrt-0     at readableAddChunk (_stream_readable.js:146:16)
KFrame2Vizrt-0     at Socket.Readable.push (_stream_readable.js:110:10)
KFrame2Vizrt-0     at TCP.onread (net.js:529:20)
```

Version:

```
4 Apr 21:10:21 - [info] Node-RED version: v0.13.4
4 Apr 21:10:21 - [info] Node.js  version: v4.4.0
4 Apr 21:10:21 - [info] Windows_NT 6.1.7601 x64 LE
```

**Comment by dceejay** [comment]
how often does this occur ? Is there a lot of traffic going on ? or very little ? is it randomly during running or when starting up / redeploy ? Anything that can help us re-create ?
Thanks

**Comment by akarak** [comment]
Dave,

3 strings are sent every 3 seconds. The length of every string is 20 to 60 characters, and it ends with \0. In response to every string, a string with the length of 10 to 30 characters ending with \0 is returned.

The problem arises randomly about 2-3 times per 24 hours.

**Comment by Steve-Mcl** [comment]
I suspect this bug has been long resolved.

In v0.13.4, the `Buffer` `buf` was [initialised at node creation](https://github.com/node-red/node-red/blob/129ca0e39fb7d63dc68b575f36fdf24782b225c4/nodes/core/io/31-tcpin.js#L399) time and `null`ed [at socket close](https://github.com/node-red/node-red/blob/129ca0e39fb7d63dc68b575f36fdf24782b225c4/nodes/core/io/31-tcpin.js#L526) time. 




In V2.2.0 this is no longer the case.

For that reason (and that no additional "still happening" comments have been added in the past 5 years), I will close this thread. 

Feel free to re-open if you are still experiencing this issue.
