### ISSUE TITLE
Crashed with node-red-contrib-gpio and node-red-contrib-freeboard installed

### ISSUE THREAD

**Issue by microspace** [node-red/node-red#861]
Node-red crashed when https://github.com/urbiworx/node-red-contrib-freeboard and https://github.com/monteslu/node-red-contrib-gpio are installed.

Node-red does not crash if one of these libraries is installed. 
I now that it is better to ask those libraries developers, but maybe problem is better seen from node-red developers.

Node-RED version: v0.13.1
Node.js  version: v0.10.38

```
5 Apr 12:18:08 - [red] Uncaught Exception:

5 Apr 12:18:08 - TypeError: Object function (entry) {
  return this.indexOf(entry) !== -1;
} has no method 'end'
    at interval (/home/root/node-red/node_modules/node-red-contrib-freeboard/freeboard.js:71:12)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```
Please can you point me to the problem?

**Comment by hardillb** [comment]
The error stacktrace points to the freeboard node, you should probably raise an issue with that project first -> https://github.com/urbiworx/node-red-contrib-freeboard

**Comment by knolleary** [comment]
Closing this issue as you have raised it against freeboard - https://github.com/urbiworx/node-red-contrib-freeboard/issues/17
