### ISSUE TITLE
Node-red installation is broken

### ISSUE THREAD

**Issue by bramhg** [node-red/node-red#863]
When trying to install Node-Red following the documentation instructions using: "npm install -g node-red" the installation fails with multiple errors.

We noticed that if the earlier version of Node-RED is installed the upgrade works. However, when you install it for the first time on a machine it does work. We have tried it on Mac OS X, Ubuntu and docker containers and we observe the same behavior.

**Comment by knolleary** [comment]
Hi, please can you share the errors you are seeing... otherwise we have nothing to look at

**Comment by dceejay** [comment]
I'm sure ask the docs say use sudo...

What exact command did you use ?

**Comment by bramhg** [comment]
Thanks for the quick response .We used sudo and we have had installed node-red earlier with no issues. Attached is the install log for this error.
[npm-debug.log.txt](https://github.com/node-red/node-red/files/206930/npm-debug.log.txt)

**Comment by knolleary** [comment]
In general, we don't need the full debug log - just the regular npm output is enough to identify the issue.

In this instance, I believe the issue is the version of npm you are using - 1.3.10. That is very old and we know we have issues using 1.x levels.

Update npm to the latest 2.x version with:

    sudo npm install -g npm@2.x

Then try again.

**Comment by bramhg** [comment]
Thanks Nick, It worked.. Appreciate your help..

Regards,
Bramh

**Comment by knolleary** [comment]
Great.

**Comment by knolleary** [comment]
FYI, have added a note on the install guide pointing out we require npm 2.x. We already had it on the RaspberryPi page, just not on the main install page.
