### ISSUE TITLE
Adding a global configuration node using runtime API

### ISSUE THREAD

**Issue by sunbit** [node-red/node-red#864]
I tried to programatically add a global configuration node alongside other nodes when creating a new flow by specifying an empty z field as i saw the editor is doing:

```
RED.nodes.addFlow({
    label: 'myFLow',
    nodes: [
        {--node1--},
        {--node2--},
        { type: 'my-config-node',
          z = '',
          id: 'myId'
        }
   ]
})

```
But "z" gets overwritten by the addFlow method. I see there's an alternate "config" field where to add nodes in the flow object that is passed to addFlow, but it also overwrites "z".

Looking at the code i cannot see a way to add a global configuration node using the exposed runtime apis. Can this use case be included in the addFlow method or in any other place that fits better?

Thank you

**Comment by knolleary** [comment]
As you've seen, `addFlow` is for adding a self-contained flow. The runtime generates an id for the flow and ensures all nodes have that id as their `z` value.

There is a flow called `global` that contains the global config nodes and the subflow templates. If you want to add a global node you would need to do:

    // Get the current global flow
    var globalFlow = RED.nodes.getFlow('global');
    // Add your new node
    globalFlow.configs.push({ type: 'my-config-node', id: 'myId', ... });
    // Update the global flow
    RED.nodes.updateFlow('global',globalFlow).then(function() {
        // Update complete and deployed
    });

And yes, this all desperately needs documenting properly.

**Comment by sunbit** [comment]
Thank you!

Runtime documentation will be nice indeed. On the positive side, it's been a great journey walking out the code to discover things!
