### ISSUE TITLE
Garbage characters appear at the text area  when inputting CJK characters

### ISSUE THREAD

**Issue by yasuday** [node-red/node-red#866]
Windows 7 Japanese / Firefox 38.7.1 
Garbage characters appear at the text area when inputting  CJK characters. 

Steps:
1. Go to Node-red flow editor and add a function, template or comment node
2. Double click it to edit. 
3. Move the cursor to the text area（Function, template or Body) 
4. Switch the IME to Japanese and input some Japanese characters.
And then, you can see some garbage characters at the beginning of the line.

**Comment by dceejay** [comment]
I suspect this is due to the underlying Ace editor - see this open issue
https://github.com/ajaxorg/ace/issues/2855

**Comment by vicary** [comment]
Should be related to ajaxorg/ace#1401, looks like they landed in master.

Tested in the live demo directly at https://ace.c9.io, they no longer have this issue.

**Comment by dceejay** [comment]
Thanks for the heads up - not quite made it to the builds yet.
https://github.com/ajaxorg/ace-builds/

**Comment by knolleary** [comment]
We upgraded ACE a few releases ago - so this issue should be resolved now.
