### ISSUE TITLE
How to load a local CSV file for subsequent parsing and analysis?

### ISSUE THREAD

**Issue by brylie** [node-red/node-red#868]
# User story
> As a data scientist
> I would like to load a static CSV file into a Node-RED graph
> so that I can perform analysis on the data

# Support request
How can a user load a local CSV file into a Node-RED graph?

# Feature request
Add a "Browse" button next to the "file" field.

![screenshot-2](https://cloud.githubusercontent.com/assets/17307/14428895/ccdfa946-0003-11e6-9abc-18ebfe5169f3.png)

**Comment by hardillb** [comment]
Things like this should be raised on the news group https://groups.google.com/forum/#!forum/node-red or on slack https://node-red.slack.com

Issues are used for actual defects

**Comment by dceejay** [comment]
Hi,

for user help like this the best place is the google group mailing list.  https://groups.google.com/forum/#!forum/node-red

However the answer is probably an inject node -> file node (to read the file) -> csv node (to parse the csv) -> function node (to do whatever you want....)

**Comment by brylie** [comment]
Ah, I do not use Slack or Google groups on a regular basis.

Also, this is somewhat an enhancement request.

**Comment by hardillb** [comment]
Feature requests should also be discussed in the news group first

**Comment by brylie** [comment]
OK. Thank you for your quick responses.

**Comment by dceejay** [comment]
No problem, as it can already parse csv into objects you can manipulate I'm not sure what else is needed - so leaving this closed. See http://flows.nodered.org/flow/edca3ef3e88a00e7e082 for a simple example of it's use.

**Comment by aco7342** [comment]
You can load csv file into mysql.  Node-red contains csv2json object. 
Em 11/04/2016 15:36, Brylie Christopher Oxley <notifications@github.com> escreveu:User story


As a data scientist
I would like to load a static CSV file into a Node-RED graph
so that I can perform analysis on the data


Support request

How can a user load a local CSV file into a Node-RED graph?
