### ISSUE TITLE
Context not cleared on re-deploy

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#870]
The context is not cleared during a full re-deploy.
To replicate put the following code in a function block

last_time = context.get('last_time');
node.log("last time: " + last_time);
context.set(last_time', new Date());

Run the flow and then perform a full re-deploy.  The first time through after re-deploy, last_time should be undefined, but in fact it gets the value from the context.set before the re-deploy.

Running on Pi (Jessie)
Node-RED version: v0.13.3
Node.js  version: v0.10.29
Linux 4.1.19-v7+ arm LE

**Comment by colinl** [comment]
I am also seeing the problem with a user defined nodes (html and js files in the nodes folder under my flows), but in this case the context is also not cleared on deploy if I use the old method, 
context.x = x
x = context.
In the case of function blocks the context is cleared when using the old method.

**Comment by dceejay** [comment]
In the user defined node it will depend where/when they are attaching themselves to context - (and indeed depending how it's being done it may or may not be the same context as functions use). If it's in the general setup but before the actual node instance definition then it will be  global across that node definition (and so not cleared as that is only set up at start time) - If inside the actual node instance then again it depends which context they have attached to. It's up to the node author to do the right thing.

**Comment by colinl** [comment]
Thanks Dave, This is my first user defined node and I have just said
var context = node.context
in on('input', ..) and used it.  Is that a different context to that available in a Function node?

**Comment by knolleary** [comment]
For a custom node, you *must* access context as described in the docs: http://nodered.org/docs/creating-nodes/context

    var context = node.context();

IE, call the context function.

**Comment by colinl** [comment]
Sorry, I mistyped in my previous comment.  I think I have what is described in the docs, I have:
module.exports = function(RED) {
  function Func(config) {
    RED.nodes.createNode(this,config);
    var node = this;
    this.on('input', function(msg) {
      var context = node.context();
      ...
The context appears to be working perfectly except that it does not get cleared on re-deploy, when using either the old or the new syntax.

**Comment by knolleary** [comment]
Fixed in the imminent 0.14.0 release
