### ISSUE TITLE
Schema for wiring like the passive adapter

### ISSUE THREAD

**Issue by lucas-pouchot** [node-red/node-red#874]
Hi, I would like test the wiring of the passive adapter but I don't found the schema like for the active adapter here : 
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/img/active3-schematic.png

Can I just to connect them like the active adapter, without the four controllers ?
If no, could you share a schema of the wiring for the passive board ?

Thanks in advance.

EDIT : sorry, I was on the wrong github

**Comment by knolleary** [comment]
Hi, have you raised this on the right repository? Not sure what this is to do with node-red.
