### ISSUE TITLE
Email Node fails to include Return-Path, rejected at SMS Gateway

### ISSUE THREAD

**Issue by martrw** [node-red/node-red#875]
Edit 05/10:  Chose Node-Red over other options because of it's apparent utility. If my monitoring systems can not notify me of events, there is no utility.  I have difficulty understanding why this post has not been viewed for three weeks.

Original:
Created a flow in Kubuntu 12.04 Desktop for transfer to a Raspberry installation after working out issues.  Have an email node which notifies me of issues through the tmomail.net sms gateway.  Worked great on the Desktop system.  After getting the Raspberry setup, I exported the flow to import into the Raspberry Node-red installation. Everything worked great except I could no longer receive the SMS notifications.  After some investigation, it appears that the Raspberry installation is not including the return path in the email header.  I am thinking this may not pass muster with the TMobile spam filters.

After about a week, I decided to toss the Raspberry because of configuration issues with storage of database files and exported the flow again to an Acer Netbook running Ubuntu 14.04.  The same issue is present on this system.  There is no return path in the header and the SMS is not getting through.  Email to a Yahoo account gets through which shows that the email node is sending the mail and this is where I get the information that shows that the Return Path is blank.

Please reference this posting in Google Groups for a more extensive comparison of the email headers: [https://groups.google.com/forum/#!topic/node-red/MhbucJAjkok](url)

I am thinking the interface to the nodemailer may be broken.  I did send SMS Gateway email from the Raspberry with the cli ssmtp successfully.  I tried to build a standalone installation of nodemailer in the 12.04 system but had build issues and had to bail on that attempt.

Below is the listing of the versions I think may be of interest and the Return Path lines from the email headers of the two systems:
This system gets the SMS through:
Kubuntu 12.04
Node.js  version: v0.12.7
Node-RED version: v0.11.1
Return-Path: <myemail@gmail.com>

This system and a Raspberry system failed to get the SMS through:
Ubuntu 14.04
Node.js version: v5.10.1
Node-RED version: v0.13.4
Return-Path: <>

Is there something that I am missing?

**Comment by knolleary** [comment]
Hi @martrw, apologies for the lack of response. I had hoped your google group posting would have reached more of a conclusion as I have no further technical insight as to what's going on here.

I guess the only thing to try is to figure out how to get the node to include the `Return-Path` field and have you test that. I'm not overly familiar with the node (which is actually maintained in the node-red/node-red-nodes repo, not this one), but will see what we can do.

For future reference, if you edit the title or description of an issue, no notification is sent out. So ironically your update asking if the post was invisible was, well, invisible. You are best to add comments to issues to bump them when needed.

**Comment by dceejay** [comment]
quick hunt indicates this may be relevant - https://github.com/nodemailer/nodemailer/issues/174
the fix they used was to specify an envelope option... not sure that should be necessary but ... we could add allowing the user to set msg.envelope as a property that may then do the necessary ? 
Any thoughts ? @nkolban ?

**Comment by dceejay** [comment]
@martrw , I have added msg.envelope to version 0.1.6 of email node on npm. Please try setting it as per examples on that nodemailer issue (modified to suit yourself of course).

**Comment by martrw** [comment]
@knolleary thanks for the response.
@dceejay I think you have overestimated my abilities.  When I sudo npm install -g node-red-node-email as I always do, the node was placed in the same location as all the node-red-contrib-* nodes.  The original node-red-email-node still existed many node_module layers beneath the surface.  I don't believe this to be proper.

I did take a look within and the only place any code structure appears per examples mentioned is in the README.md files, so I know that I don't have the right road map.

**Comment by dceejay** [comment]
Hi, no problem :-) 
Indeed you don't want two of them... so yes please remove the (new) one from .node-red/node-modules
On the Pi at least the place to install is over the existing one in Node-RED which should be

    cd /usr/lib/node_modules/node-red
    sudo npm i node-red-node-email

**Comment by martrw** [comment]
@dceejay 
I finally sat down and hammered away at this.  The envelope resolved the issue with the SMS gateway.  If I understand correctly, I can no longer stack email addys in the email node, e.g. for each email address there has to be a unique envelope... Correct?

**Comment by dceejay** [comment]
Hi, I must admit I thought the envelope was more like an outer' from' wrapper, so you would still be able to send to a list of addresses, but don't know as I have never needed to use it :-)

**Comment by martrw** [comment]
I was not able to get my typical two recipients to work.  And if I remember correctly, if I tried to send an email to an address which did not match the envelope "to" address, it failed.  I'm thinking this is what is referred to in the referenced nodemailer issue [:](https://github.com/nodemailer/nodemailer/issues/174)

_If you want to dynamically catch bounces, you should send an individual e-mail for every recipient. Eg. when you have a mail structure like this:

mail = {
    from: "sender@example.com",
    to: "receiver1@example.com",
    cc: "receiver2@example.com"
}

then you should copy this message into two objects (one for every individual receiver) and set different envelopes:

mail1 = {
    from: "sender@example.com",
    to: "receiver1@example.com",
    cc: "receiver2@example.com",
    envelope: {
        from: "bounce1@example.com",
        to: "receiver1@example.com"
    }
}

mail2 = {
    from: "sender@example.com",
    to: "receiver1@example.com",
    cc: "receiver2@example.com",
    envelope: {
        from: "bounce2@example.com",
        to: "receiver2@example.com"
    }
}_

I would like to suggest that the issue remain open as a bug if you agree?

**Comment by dceejay** [comment]
Can you now set the envelope as you require ?
Most servers don't need it set explicitly so is not something we would do by default. Not sure how you would like it to be fixed from here ?

**Comment by martrw** [comment]
Yes, envelope is set as required.
Can you help me understand why a desktop running the same node-red release and a raspberry with one rev earlier version have no problem with the SMS gateway while the latest version on raspberry and an atom netbook fail?  For my own edification?

**Comment by dceejay** [comment]
Hi. Very good question(s).
you could check the versions of each email node on each. I'd be interested to see which is where.
  npm list | grep node-email
should show the versions.

**Comment by martrw** [comment]
@dceejay, Here are the four systems I have tried the SMS Gateway with:

**Desktop Linux System**			**Works with SMS**
node-red-node-email@0.1.0

**Pi One**						**Fails with SMS**
node-red-node-email@0.1.1
npm ERR! missing: node-pre-gyp-github@^1.1.0, required by serialport@2.0.6

**Pi Two**						**Works after your help with envelope manipulation**
node-red-node-email@0.1.6
npm ERR! extraneous: buildmail@1.3.0 /usr/lib/node_modules/node-red/node_modules/buildmail
npm ERR! extraneous: duplexer2@0.0.2 /usr/lib/node_modules/node-red/node_modules/duplexer2
npm ERR! extraneous: hyperquest@1.3.0 /usr/lib/node_modules/node-red/node_modules/hyperquest
npm ERR! extraneous: imap@0.8.14 /usr/lib/node_modules/node-red/node_modules/imap
npm ERR! extraneous: nodemailer@1.3.4 /usr/lib/node_modules/node-red/node_modules/nodemailer
npm ERR! missing: node-pre-gyp-github@^1.1.0, required by serialport@2.0.6

**AcerOne Atom**				**Fails with SMS**
node-red-node-email@0.1.3
