### ISSUE TITLE
Embedding node-red in angularjs app

### ISSUE THREAD

**Issue by swapnil002** [node-red/node-red#877]
How do I add node-red in my angular web app? I want to load node-red UI in an angularjs state, but I dont see to find any .html file, where i can redirect my state.

**Comment by knolleary** [comment]
Hi, for questions like this, please use the mailing list.

I don't immediately know if it's possible to embed it as you want - I'm not familiar enough with angular. We don't have a static index.html - we have index.mst which is a mustache template that the runtime renders when the editor is loaded.

**Comment by swapnil002** [comment]
Thanks for your reply. I can create index.html from .mts file. But what all files do i need to run to make it work? I saw your demo and found out that red.min.js and ace.js etc. So suppose i have index.html and all the required files (red.min.js and ace.js in a folder) will it work? 

I urgently need to embedd node-red in my web app. Any help will be highly appreciated. Thanks !

**Comment by knolleary** [comment]
You need everything in the 'public' folder and you need the node-red runtime running to serve up the various http admin routes that provide the data to the editor. But if that will be possible with what you're trying to do, I simply don't know.

**Comment by Humancell** [comment]
As a side note, we currently embed Node-RED into our portal using an iFrame ... I mean ... it's quick and easy and works.

**Comment by knolleary** [comment]
I'm going to close this as it is not an issue with Node-RED. Please follow up on slack/mailing list if you have any more questions on this topic.

**Comment by karangarg45** [comment]
@Humancell i am not able to node-cell in iframe. is there any extra configuration you did because i am getting x-frame deny error

**Comment by gunjan-it-engg** [comment]
So how this iframe will show in angular framework ? or embeded the the node-red with any web app ?
