### ISSUE TITLE
Question: is there a reason the error stack trace is ignored when logging?

### ISSUE THREAD

**Issue by joakimbeng** [node-red/node-red#879]
When trying to debug an error it's quite difficult because the error stack trace is never shown for errors emitted with `node.error`. Is there a reason for this? Or could we change the `Flow.handleError` to also attach `stack` to `errorMessage.error` if `logMessage.stack` exists? Then a "catch all" node will send the stack as well which can be really useful when debugging.

Also if something is throwing objects (which is quite common in JavaScript modules) instead of `Error` instances, the `consoleLogger` function will convert it to a string (because of the concatenation) and `[object Object]` is the only thing showing in the console. This could also be easily fixed by changing `+msg.msg` to `+(msg.msg.message || msg.msg)` (because thrown objects usually have the same property names as an `Error` instance).

How do you reason about this? Would you accept a PR addressing this?

**Comment by knolleary** [comment]
Hi,

thanks for raising this. You make a good point that we could surface more of the error details here.

If you wanted to propose a PR we could certainly take a look. Two items on that - please ensure you've read our contribution guidelines, particularly the requirements on having a CLA in place. Second thing, please target the 0.14.0 branch.

**Comment by dceejay** [comment]
HI  @joakimbeng , 
we are looking to get release 0.14.0 out sometime soon. Are you interested in adding a PR for this as per Nick's reply above ?

**Comment by joakimbeng** [comment]
@dceejay ah, yes that's my intent! Sorry for the delay!
I see I would need both a printer and a scanner to be able to sign the CLA, which I don't have access to in a few days though.

**Comment by dceejay** [comment]
Printer yes, then a camera on a phone will do 😀
