### ISSUE TITLE
Way to programatically know if a node needs a deploy

### ISSUE THREAD

**Issue by sunbit** [node-red/node-red#883]
I was looking troug the red.js editor code to find a way to tell if a config node has beed edited and so it needs a redeploy, from the dialog of a node that uses it. I found that the "dirty" property is set when changes are saved, but not removed or setted to false after a deploy as i expected.

Is this the purpose of the dirty property? Can i use anything else to check what i'm looking for?

Thank you!

**Comment by knolleary** [comment]
For questions, please using the mailing list.
