### ISSUE TITLE
Expose/send a variable to an MQTT topic

### ISSUE THREAD

**Issue by JBX028** [node-red/node-red#884]
Hi,

Perhaps my question is stupid, but is there a way to send a variable to an MQTT out topic?
Let me give a bit more context. I have connected my BB8 sphero device to my rasp pi and I want to use node-red to control it.
I have created a node script which is used as an mqtt server using mosca and the same script uses another npm package to control the device.
I have been able to create basic nodes but I have to duplicate nodes as soon as I want to send something to the mqtt server. For example, if I want to send a color to my BB8 what I did so far, is to use one mqtt out component per color, that mean the "Topic" contains either red, blue, etc...
How I can submit a variable to this component to avoid multiple outputs on the same flow? 
I have tried to find examples in internet but I haven't and the cookbook is unfortunately not yet created for the MQTT section.
Thanks in advance for your help knowing that I am pretty new with node-red but the potential seems awesome.

- A french user

**Comment by hardillb** [comment]
Please use the mailing list (https://groups.google.com/forum/#!forum/node-red) for basic questions, we keep issues for actual defects.

For this, you don't have to set a topic in the MQTT Out node, if none is set then it will take the msg.topic value as the topic to publish the message on

**Comment by JBX028** [comment]
Ok thanks. I will play wit msg.topic and will post a message to the dedicated google group for any questions going forward.

**Comment by dceejay** [comment]
All nodes should describe their capabilities in their associated info panel on the right

![image](https://cloud.githubusercontent.com/assets/5375409/14943781/d82bfd32-0fd9-11e6-8a5f-72cecead4c4d.png)

**Comment by JBX028** [comment]
Thanks @dceejay. I haven't realized this documentation! I looked at the few information visible when you drag the mouse on top of a component on the left panel.

**Comment by dceejay** [comment]
:-). No problem.
