### ISSUE TITLE
make repeating "inject" nodes and non-repeating "inject" nodes visually distinct

### ISSUE THREAD

**Issue by boneskull** [node-red/node-red#887]
Does that make sense?  Some are just for debugging; others are for cron-like functionality

**Comment by knolleary** [comment]
Please use the mailing list for feature suggestions/discussions

**Comment by knolleary** [comment]
Have thrown this together, but not 100% sold on it yet.

<img width="300" alt="node-red" src="https://cloud.githubusercontent.com/assets/51083/15340415/413800c4-1c81-11e6-8b4b-2f1625ea869f.png">

Uses a unicode symbol in the label to indicate it's a repeating node - this was the best symbol I could find. Currently doesn't show it if you set the name field - but it could...

Will chew it over some more.

**Comment by knolleary** [comment]
Have put the icon on the right, and included it even if you've set the name field.

Pushed to the 0.14.0 branch - this issue will get closed when we merge to master for the release.

**Comment by knolleary** [comment]
Change of plan - closing now so I don't keep thinking there is more work to do on this

**Comment by boneskull** [comment]
@knolleary Thanks!
