### ISSUE TITLE
No http request inside a subflow

### ISSUE THREAD

**Issue by guitar-hero** [node-red/node-red#888]
Hi there

Is it possible, that the http nodes, for example for an easy GET method, don't work inside a subflow? If so, do you know how to bypass this?

I want to put some http nodes in many of my subflow, but I'm unable to. However, the request works fine when put in a regular flow.

Kind Regards

**Comment by knolleary** [comment]
Hi - as you've also asked this on the mailing list, I'm closing this issue.
