### ISSUE TITLE
Can't install dev version on node 4.4

### ISSUE THREAD

**Issue by andig** [node-red/node-red#889]
grunt seems to conflict:

	pi@raspberrypi:~/node-red $ sudo npm install -g grunt-cli
	/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
	grunt-cli@1.2.0 /usr/local/lib/node_modules/grunt-cli
	+-- grunt-known-options@1.1.0
	+-- nopt@3.0.6 (abbrev@1.0.7)
	+-- resolve@1.1.7
	+-- findup-sync@0.3.0 (glob@5.0.15)
	pi@raspberrypi:~/node-red $ grunt build
	Loading "sass.js" tasks...ERROR
	>> Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 4.x
	>> For more information on which environments are supported please see:
	>> https://github.com/sass/node-sass/releases/tag/v3.7.0
	Warning: Task "sass:build" not found. Use --force to continue.

	Aborted due to warnings.

Unfortunately I need node 4.4 as pimatic depends no it.

**Comment by knolleary** [comment]
Hi,

as the error message says, this is an issue with node-sass not yet supporting arm on Node 4.4 - not something we have any control of.

Is there a reason you need to build node-red on the pi versus using the prebuilt stable release you can just npm install?

**Comment by andig** [comment]
> Is there a reason you need to build node-red on the pi versus using the prebuilt stable release you can just npm install?

Yes. If I npm install it pulls node 0.10 on the raspberry while I really need 4.4. I understand thats  a grunt issue and the grunt version is not determined by the node package.json?

**Comment by knolleary** [comment]
npm has no part in installing node.js. You can install whatever version of node.js you want on the Pi and then npm install node-red as normal.

http://nodered.org/docs/hardware/raspberrypi.html#manual-install

**Comment by dceejay** [comment]
I do have a script here - https://github.com/node-red/raspbian-deb-package/blob/master/resources/update-nodejs-and-nodered
that does pull latest of both. (but does wipe anything already installed)

**Comment by andig** [comment]
> npm has no part in installing node.js.

Thats not what I was trying to say. If I install nodered from package it installs nodejs 0.10 which is not what I want. 

Maybe I should install from package and remove the wrong node version afterwards?

**Comment by andig** [comment]
> I do have a script here - https://github.com/node-red/raspbian-deb-package/blob/master/resources/update-nodejs-and-nodered that does pull latest of both. (but does wipe anything already installed)

I'm confused. That would again clash with grunt, or not?

**Comment by knolleary** [comment]
If you `apt-get install nodered` that will pull in `nodejs` 0.10.

If you follow the instructions I linked to, you will get node.js 4.x installed and node-red npm installed - no need to build it.

**Comment by dceejay** [comment]
apt-get install and npm install are two different things - you can do either. apt-get will get you the node.js v10 and node-red 0.13.4  -... but if you want node 4.4 - then don't do that... (in fact if you have already done that then best to do an  apt-get purge node-red  to remove first) - then do either what Nick suggest - ie - following the manual install instructions - or run that script. Both will get you Node.js 4.4.4 LTS version plus Node-RED 0.13.4

**Comment by andig** [comment]
Excellent, much appreciated. Might be worth linking on the Raspi docs page.

**Comment by andig** [comment]
@dceejay got it running with your script, much appreciated.
