### ISSUE TITLE
How to write a function for making a loop condition??

### ISSUE THREAD

**Issue by rprasanth** [node-red/node-red#891]
Hi friends,
 i am using node red to  implement my idea, here i am getting sensor data from Raspberry pi using gpio nodes in node-red, but i have to write a function that the values should be delivered when there is a variation in the sensor value. For eg: if the sensor value is 10 continuously if the values goes to 9 or 11 it means increases or decrease i have to get an message as "change in value". could any one give me the code for writing the if else statement in java script?? please.

**Comment by knolleary** [comment]
Hi - you've just asked this on the mailing list - no need to raise an issue as well. Thanks!
