### ISSUE TITLE
status node not working

### ISSUE THREAD

**Issue by icyhoty2k** [node-red/node-red#892]
im tring to get the pin state of an output pin in raspberry pi 3 and send it to mqtt(mosuqitto) but i get error and nothing is send : the error in the debugger is :" msg.payload:undefined"

**Comment by icyhoty2k** [comment]
how can i get status of an output pin and send it to mqtt ?

**Comment by knolleary** [comment]
Please share the flow you are using so we can see what you've tried.

**Comment by icyhoty2k** [comment]
[{"id":"54148ca4.e055e4","type":"debug","z":"f005ee81.158b4","name":"","active":true,"console":"false","complete":"false","x":474,"y":134,"wires":[]}]

**Comment by icyhoty2k** [comment]
here is the flow

**Comment by knolleary** [comment]
That's just a debug node. Make sure you've selected all the nodes in your flow before you export.

(the mailing list is a better venue for general support questions)

**Comment by icyhoty2k** [comment]
[{"id":"b3c0d72f.4ff5f8","type":"mqtt-broker","z":"f005ee81.158b4","broker":"localhost","port":"1883","clientid":"","usetls":false,"verifyservercert":true,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willRetain":null,"willPayload":"","birthTopic":"","birthQos":"0","birthRetain":null,"birthPayload":""},{"id":"411c323f.6c8e6c","type":"mqtt in","z":"f005ee81.158b4","name":"","topic":"in","broker":"b3c0d72f.4ff5f8","x":165,"y":84,"wires":[["31c800b0.4145a","bbd63462.5802a8"]]},{"id":"551cee46.f452e","type":"mqtt out","z":"f005ee81.158b4","name":"","topic":"out","qos":"","retain":"","broker":"b3c0d72f.4ff5f8","x":534,"y":374,"wires":[]},{"id":"31c800b0.4145a","type":"rpi-gpio out","z":"f005ee81.158b4","name":"BCM17","pin":"11","set":"","level":"0","out":"out","x":385,"y":80,"wires":[]},{"id":"bbd63462.5802a8","type":"debug","z":"f005ee81.158b4","name":"","active":true,"console":"false","complete":"false","x":531,"y":182,"wires":[]},{"id":"ad184ceb.14b0a","type":"status","z":"f005ee81.158b4","name":"","scope":null,"x":210,"y":180,"wires":[["551cee46.f452e","bbd63462.5802a8"]]}]

**Comment by icyhoty2k** [comment]
sorry my mistake

**Comment by icyhoty2k** [comment]
this is the flow

**Comment by knolleary** [comment]
Ok, that's a slightly unconventional way of doing it. The status node is for capturing the status messages that various nodes emit. Here, your status node is set to target all nodes - that means it will get triggered by the MQTT nodes as they update their status (connected/disconnected etc) as well as the GPIO output node.

The info of the status node describes how it puts the status information in `msg.status` - `msg.payload` is not set - which is why you see `msg.payload:undefined` in debug.

For what you're trying to do, you should simply use a gpio input node that emits messages when the state of the pin changes, and not use the status node in this way.

**Comment by icyhoty2k** [comment]
no no
i have pasted wrong code again sorry

**Comment by icyhoty2k** [comment]
the status node is for status of the BCM17

**Comment by knolleary** [comment]
if you really want to use the status node to do this, you need to:
1. ensure you configure the status node to target just the GPIO output node
2. either use a Change of Function node to copy whatever you want out of `msg.status` into `msg.payload` so it will get published by the mqtt node.

**Comment by icyhoty2k** [comment]
look
is it something like this :

**Comment by icyhoty2k** [comment]
[{"id":"b3c0d72f.4ff5f8","type":"mqtt-broker","z":"f005ee81.158b4","broker":"localhost","port":"1883","clientid":"","usetls":false,"verifyservercert":true,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willRetain":null,"willPayload":"","birthTopic":"","birthQos":"0","birthRetain":null,"birthPayload":""},{"id":"411c323f.6c8e6c","type":"mqtt in","z":"f005ee81.158b4","name":"","topic":"in","broker":"b3c0d72f.4ff5f8","x":165,"y":84,"wires":[["31c800b0.4145a","bbd63462.5802a8"]]},{"id":"551cee46.f452e","type":"mqtt out","z":"f005ee81.158b4","name":"","topic":"out","qos":"","retain":"","broker":"b3c0d72f.4ff5f8","x":544,"y":266,"wires":[]},{"id":"31c800b0.4145a","type":"rpi-gpio out","z":"f005ee81.158b4","name":"BCM17","pin":"11","set":"","level":"0","out":"out","x":385,"y":80,"wires":[]},{"id":"bbd63462.5802a8","type":"debug","z":"f005ee81.158b4","name":"","active":true,"console":"false","complete":"false","x":531,"y":182,"wires":[]},{"id":"ad184ceb.14b0a","type":"status","z":"f005ee81.158b4","name":"Status of BCM17","scope":["31c800b0.4145a"],"x":230,"y":180,"wires":[["551cee46.f452e","bbd63462.5802a8"]]},{"id":"36090efd.6cbb82","type":"rpi-gpio in","z":"f005ee81.158b4","name":"bcm17","pin":"11","intype":"tri","debounce":"25","read":false,"x":221,"y":270,"wires":[["551cee46.f452e"]]}]

**Comment by icyhoty2k** [comment]
to get the status of a pin

**Comment by icyhoty2k** [comment]
published to mqtt out topic

**Comment by icyhoty2k** [comment]
please give me example i cannot manage to do it

**Comment by knolleary** [comment]
1. I was wrong to suggest using a GPIO Input node. I forgot that tries to use the pin as both an input and an output, which you can't do. So get rid of your GPIO input node.

2. As I've said previously, the help for the status node tells you that it emits `msg.status` *not* `msg.payload` - so you cannot simply wire the status node to the mqtt node. If you configure your Debug node to output the complete message object, you'll see what I mean.

The Change node I've exported below will copy `msg.status.text` over to `msg.payload`. Insert that between the Status node and the MQTT node.

[{"id":"f5eee8b9.2d4d38","type":"change","z":"af24c219.ce192","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"status.text","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":300,"y":480,"wires":[[]]}]

**Comment by icyhoty2k** [comment]
it worked thanks so much I was trying to do that for days.You helped me alot

**Comment by icyhoty2k** [comment]
why when i input number different than 1 or 0 it does not display nothing in the mqtt , rather than:invalid input like in the debug

**Comment by knolleary** [comment]
The sidebar help for the GPIO Output node says this:

> Digital mode expects a msg.payload with either a **0** or **1** (or true or false), and will set the selected physical pin high or low depending on the value passed in.

**Comment by icyhoty2k** [comment]
yes but i cannot pass the invalid input to the mqtt .

**Comment by icyhoty2k** [comment]
even if it is invalid input i need to pass it , or at least a error message to mqtt

**Comment by icyhoty2k** [comment]
it passes it to the debug but not to the mqtt(mosquitto)

**Comment by knolleary** [comment]
If you have set the Debug node to show the complete message, what does the full message look like? Does it have msg.status.text ?

**Comment by dceejay** [comment]
It tries to make it into a number - and if that results in an invalid number (ie not 0 or 1 (or 100 in case of pwm) then we warn.
