### ISSUE TITLE
Trigger event on re-deploy.

### ISSUE THREAD

**Issue by romeovs** [node-red/node-red#893]
I'm building a node that connects to an external server to listen for events.

It seems logical to close this connection whenever the node closes:

```
   this.on('close', function () {
      serverClient.close();
   });
```

Re-deploying the flow causes the node to send the `close` event. However, I do not an event that marks
to `open` of a node (or something similar).

Is there a way to re-open the connection to the remote server after deployment?

**Comment by romeovs** [comment]
A good example of why this might be necessary is the `Watch` node. It stops watching the files whenever the flow is re-deployed.

**Comment by knolleary** [comment]
Your node constructor being invoked **is** the event that marks the 'opening' of the node.

**Comment by romeovs** [comment]
@knolleary But the constructor only gets invoked once, not on every re-deploy

**Comment by knolleary** [comment]
When you do a full deploy, all nodes a closed and disposed of. New nodes are then created - and thus the constructor invoked.

If you do a partial deploy, only modified nodes are closed and recreated - unmodified nodes are left untouched.

**Comment by romeovs** [comment]
@knolleary That is not what I am experiencing. I'm doing a full re-deploy and my nodes get closed, allright, but they do not get re-created.

**Comment by knolleary** [comment]
Are you sure? This is pretty much the most fundamental part of the node/flow lifecycle.

     function RandomNode(config) {
        RED.nodes.createNode(this, config);
        console.log("New RandomNode Created");
     }

**Comment by romeovs** [comment]
this does not work:
```
 function RandomNode(config) {
    RED.nodes.createNode(this, config);
    console.log("New RandomNode Created');
    this.on('close', function () {
        console.log('RandomNode Closed');
    });
 }
```

**Comment by knolleary** [comment]
For me that does work:

```
25 May 21:19:18 - [info] Starting flows
RandomNode Created
25 May 21:19:18 - [info] Started flows
25 May 21:19:31 - [info] Stopping flows
RandomNode Closed
25 May 21:19:31 - [info] Stopped flows
25 May 21:19:31 - [info] Starting flows
RandomNode Created
25 May 21:19:31 - [info] Started flows
```

What version of node-red are you using?

**Comment by romeovs** [comment]
```
25 May 22:22:19 - [info] Node-RED version: v0.13.4
25 May 22:22:19 - [info] Node.js  version: v5.7.0
25 May 22:22:19 - [info] Darwin 15.5.0 x64 LE
```

The issue goes away when I call the callback on the close event:

```
 function RandomNode(config) {
    RED.nodes.createNode(this, config);
    console.log("New RandomNode Created');
    this.on('close', function (done) {
        console.log('RandomNode Closed');
        done();
    });
 }
```

**Comment by knolleary** [comment]
If your close handler accepts a `done` callback but you never call it, you will block the deploy - and then you won't get the nodes recreated - which is what you're seeing.

````
this.on('close', function () { // <-- no 'done' argument, nothing more is needed
        console.log('RandomNode Closed');
});
this.on('close', function (done) { <-- 'done' argument - you MUST call this when you're done.
        console.log('RandomNode Closed');
        done();
});
````

**Comment by romeovs** [comment]
Yes! Thanks for your assistance!
