### ISSUE TITLE
Storage Module getSessions invoked before initialized

### ISSUE THREAD

**Issue by simon29428** [node-red/node-red#895]
Hi,
I try to add adminAuth to the settings.
But I found the getSessions method invoke by the Tokens module before storageModule do init.

Node-RED version: v0.13.4
Node.js  version: v6.0.0

**Comment by knolleary** [comment]
Thanks - will resolve for the imminent 0.14 release

**Comment by knolleary** [comment]
Fixed by b5d3f505e3e2779a14552ec0b5039e2057d823cd
