### ISSUE TITLE
typedInput has issues when window is scolled

### ISSUE THREAD

**Issue by deldrid1** [node-red/node-red#896]
Take a look at this video: https://www.dropbox.com/s/29c7iwn0kwmvr2e/Node-RED%20typedInput%20Bug.mov?dl=0

There is a bug in the typedInput widget where it will not change its value if the input is not scrolled correctly.  I realize that my zoom is a bit ridiculous, but a combination of Windows 7, an old version of Fusion, and a retina display Macbook Pro leads me to this situation.

My jQuery isn't too great but this looks like an issue with events bubbling up when they shouldn't?

I'm trying to use the typedInput in [node-red-contrib-firebase](https://www.npmjs.com/package/node-red-contrib-firebase).

**Comment by knolleary** [comment]
Hi,

with the new editor tray in 0.14.0 I've not been able to recreate this. Could you see if you can reproduce it on this instance: http://node-red-editor-demo.mybluemix.net/

Nick

**Comment by deldrid1** [comment]
Looks like this is resolved in 0.14.0 - I can no longer reproduce!
