### ISSUE TITLE
httpNodeAuth in settings.js is not working

### ISSUE THREAD

**Issue by adadgio** [node-red/node-red#897]
When setting the `httpNodeAuth` option, NodeRed does not start.

**Comment by hardillb** [comment]
It would be useful to include the section of settings.js you changed and the Node-RED output at startup so we can see any error messages

**Comment by adadgio** [comment]
I have tried all of the following: 

```
// nodeAuth: {user:"user",pass:"5f4dcc3b5aa765d61d8327deb882cf99"},
    httpNodeAuth: {user:"user",pass:"5f4dcc3b5aa765d61d8327deb882cf99"},
    //
    // httpNodeAuth: {
    //     user: "360medical",
    //     pass: "$2a$08$GmVpyw7eppmSOtX.fy/2Lu2yjcoiqLemzrNOhXE.EFHRQjy3nu2Ku"
    // },
```

Apprently the issues seems related to express

```
node-red-0 (err):     at Module._compile (module.js:541:32)
node-red-0 (err):     at Object.Module._extensions..js (module.js:550:10)
node-red-0 (err): TypeError: express.basicAuth is not a function
node-red-0 (err):     at Object.<anonymous> (/usr/local/lib/node_modules/node-red/red.js:192:17)
node-red-0 (err):     at Module._compile (module.js:541:32)
node-red-0 (err):     at Object.Module._extensions..js (module.js:550:10)
```

... and to this: [https://groups.google.com/forum/#!msg/node-red/FHTw8jyCkRE/RNRD_XVOEwAJ](https://groups.google.com/forum/#!msg/node-red/FHTw8jyCkRE/RNRD_XVOEwAJ)

**Comment by knolleary** [comment]
What version of Node-RED are you using?

**Comment by adadgio** [comment]
Upgradin npm packages such as express make it work. (to `express 3.9.3` as least)

**Comment by knolleary** [comment]
@adadgio : what version of node-red are you using? Node-RED has depended on Express 4.x in its package.json since 0.12 which was released last November.
