### ISSUE TITLE
node-red will not run. 

### ISSUE THREAD

**Issue by phoenixcomm** [node-red/node-red#898]
I have a LinuxMint 17.x 64 bit system
after more than several attempts to instal,l I give up. 
here is my log

harrison@Whirlwind ~ $ "usr/bin/nodejs" "/usr/bin/npm" "install" "npm" "-g"
bash: usr/bin/nodejs: No such file or directory
harrison@Whirlwind ~ $ /usr/bin/nodejs /usr/bin/npm install npm -g
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/bin/npm'
npm ERR! error rolling back  npm@3.9.5 { [Error: EACCES, unlink '/usr/local/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/local/bin/npm' }
npm ERR! Error: EACCES, unlink '/usr/local/bin/npm'
npm ERR!  { [Error: EACCES, unlink '/usr/local/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/local/bin/npm' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "npm" "-g"
npm ERR! cwd /mnt/MyData/home/harrison
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/bin/npm
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/bin/npm'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /mnt/MyData/home/harrison/npm-debug.log
npm ERR! not ok code 0
harrison@Whirlwind ~ $ sudo sh
# /usr/bin/nodejs /usr/bin/npm install npm -g
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.9.5 /usr/local/lib/node_modules/npm
# node -v
sh: 2: node: not found
# cwd
sh: 3: cwd: not found
# cwd
sh: 4: cwd: not found

**Comment by dceejay** [comment]
Hi

you have an old copy of node.js installed - which I guess is the default one in the apt-get repo for Mint.
You can either - add the nodejs-legacy package - to get the command line alias to work correctly
    sudo apt-get install nodejs-legacy
and then continue with 
   sudo npm install -g --unsafe-perm node-red

or remove the old v0.10.25 one 
   sudo apt-get purge nodejs npm
and then re-start over, following the package manager instructions (about para 3 or 4 on here - http://nodered.org/docs/getting-started/installation

PS in general we prefer help questions like this on the google group

**Comment by knolleary** [comment]
Hi @phoenixcomm - any updates on this? In additional to the comments from dceejay, this seems to mostly be node.js issues due to the packaging? I don't see anything specific to node-red here.

**Comment by knolleary** [comment]
Hi @phoenixcomm, in the absence of any updates from you, I'm going to close this issue. Please reopen if you continue to have an issue.
