### ISSUE TITLE
Enhancement: Add PATCH operation to http in node

### ISSUE THREAD

**Issue by tonykambo** [node-red/node-red#904]
Currently the HTTP in node includes GET, PUT, POST, DELETE operations. 

Would appreciate having the PATCH operation added.

**Comment by knolleary** [comment]
Hi @tonykambo, thanks for raising this. We'll look at adding patch for the imminent 0.14.0 release.

FYI, as per the contributing guidelines, we prefer feature requests come via the mailing list in the first instance.
