### ISSUE TITLE
context not working

### ISSUE THREAD

**Issue by rajatksud** [node-red/node-red#905]
i am running code from [nodered guide](url http://noderedguide.com/index.php/2015/11/06/node-red-lecture-6-intermediate-flows-2/#h.69g8vtphne2u) at function 6.21 and cannot get to set context. i have tried to tweak the code as the original code does not work. I tried debugging with inserting node.log() and find that the context.data resets when new data is injected into the code. 
Tried this change
var context =this.context;
 context.data = context.data || {};

this.context() does not work - says context is not a function. 
I am using v0.13.4 on Node 4.4.5 WinNT 10.0.10240 x64. I checked the previous issues and have the settings file unmodified with the functionGlobalContext. I checked this on FRED and find it is not working there as well.

**Comment by dceejay** [comment]
In general we prefer questions like this on the mailing list. Especially as in this case the guide you refer to is not part of the main Node-RED project... 
Have a look at the Node-RED docs - http://nodered.org/docs/writing-functions#storing-data
you do not need to setup the context  variable - it is already provided for you.

**Comment by knolleary** [comment]
@rajatksud As Dave says, this is a question for either the mailing list or for the authors of the guide you are following. At a glance I can't see anything obviously wrong with their code - whilst we've evolved how you access context in a Function node, the old way used here still works.

If you do want to follow up you may want to share the specific code you've tried that isn't working for you.

**Comment by rajatksud** [comment]
[{"id":"265dc294.052636","type":"function","z":"2c88f54a.cfc50a","name":"ratio","func":"var context =this.context.global;\n//        node.log(\" preprocess - task1 \"+context.data.task1+\" task2 \"+context.data.task2)\n\n context.data = context.data || {};\nnode.log(\"processing \")\nswitch (msg.topic){\n    case \"task1\":\n        context.data.task1=msg.payload;\n        node.log(\" task1 \"+context.data.task1+\" task2 \"+context.data.task2)\n        msg=null;\n        break;\n    case \"task2\":\n        context.data.task2 = msg.payload;\n        node.log(\" task1 \"+context.data.task1+\" task2 \" +context.data.task2)\n        msg=null;\n        break;\n    default:\n    node.error(\"error\")\n    msg = null;\n    break;}\nif(context.data.task1!== null && context.data.task2!==null){\n    var ratio =Number(context.data.task1/context.data.task2);\n    context.data = null\n    return {payload:ratio}\n} else return msg","outputs":1,"noerr":0,"x":370,"y":168,"wires":[["a9414a64.b34d58"]]},{"id":"540a318f.3ddf1","type":"inject","z":"2c88f54a.cfc50a","name":"task1","topic":"task1","payload":"3","payloadType":"num","repeat":"","crontab":"","once":false,"x":185,"y":125.80001831054688,"wires":[["265dc294.052636"]]},{"id":"d503d6aa.89f4","type":"inject","z":"2c88f54a.cfc50a","name":"task2","topic":"task2","payload":"6","payloadType":"num","repeat":"","crontab":"","once":false,"x":184,"y":226.80001831054688,"wires":[["265dc294.052636"]]},{"id":"a9414a64.b34d58","type":"debug","z":"2c88f54a.cfc50a","name":"","active":true,"console":"false","complete":"false","x":539.9999694824219,"y":171.43331909179688,"wires":[]}]

**Comment by knolleary** [comment]
@rajatksud refer to the docs @dceejay pointed you at as they explain how to use context properly. The object `context` already exists in the Function node - your first line is reassigning it to something different so won't work as expected anymore.

**Comment by dceejay** [comment]
also in your third last line you 
    context.data = null
which of  course just clears it all out... every time...

**Comment by rajatksud** [comment]
Yes this makes sense. I tried with the set method this is simpler. I could not follow the || command to set the context.data - Just wondering that these examples would have worked at some time.

**Comment by rajatksud** [comment]
Thanks for the help and look forward to catching up with on the 17th

**Comment by dceejay** [comment]
whats the 17th ?
