### ISSUE TITLE
GPIO output failure when writing many pins

### ISSUE THREAD

**Issue by DrLucyRogers** [node-red/node-red#906]
Hello,

Am using NodeRED  V0.13.4 (@AndySC Eskills 30) - I have put LEDs (plus resistors!) on every GPIO pin of a Pi2. 

![img_2575](https://cloud.githubusercontent.com/assets/3532238/15985799/e74eab2a-2ff0-11e6-963c-4b4e834fdba9.JPG)

Turning all the pins on, then off again works a few times, and then some of the pins, (physical pins 11,12, 15, 16, 32, 35, 36, 38 and 40) become floating.

If I run for example, "nrgpio.py out 36" in a terminal, then pin 36 gets re-enabled (and can turn on/off in NodeRED), until I exit the command.

If it helps to diagnose the problem, here's the flow to turn every pin on/off individually or all together: 

`[{"id":"edbb161e.34d748","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"3","set":"","level":"0","out":"out","x":730,"y":40,"wires":[]},{"id":"1a0c8c55.0a1454","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":40,"wires":[["edbb161e.34d748"]]},{"id":"6585ed24.27187c","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":80,"wires":[["edbb161e.34d748"]]},{"id":"332bb059.01a518","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"5","set":"","level":"0","out":"out","x":690,"y":120,"wires":[]},{"id":"1876a056.27d518","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":120,"wires":[["332bb059.01a518"]]},{"id":"b6e4aac.b1d57d8","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":160,"wires":[["332bb059.01a518"]]},{"id":"e7ae3eb.4d91a4","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"7","set":"","level":"0","out":"out","x":710,"y":200,"wires":[]},{"id":"451c8931.41f74","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":200,"wires":[["e7ae3eb.4d91a4"]]},{"id":"2d0c9237.93b216","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":240,"wires":[["e7ae3eb.4d91a4"]]},{"id":"300f1d99.bd1192","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"8","set":"","level":"0","out":"out","x":690,"y":280,"wires":[]},{"id":"c448e39d.f56298","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":280,"wires":[["300f1d99.bd1192"]]},{"id":"d95be28f.6a2d7","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":320,"wires":[["300f1d99.bd1192"]]},{"id":"4f823a32.61ed9c","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"10","set":"","level":"0","out":"out","x":700,"y":340,"wires":[]},{"id":"b11f031b.67aa28","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":360,"wires":[["4f823a32.61ed9c"]]},{"id":"704ef1f.7f7441","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":400,"wires":[["4f823a32.61ed9c"]]},{"id":"c62b79a6.b6e298","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"11","set":"","level":"0","out":"out","x":700,"y":440,"wires":[]},{"id":"ae631169.10ee68","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":440,"wires":[["c62b79a6.b6e298"]]},{"id":"d154cb24.cb401","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":550,"y":480,"wires":[["c62b79a6.b6e298"]]},{"id":"e60af926.ff59e","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"12","set":"","level":"0","out":"out","x":680,"y":520,"wires":[]},{"id":"c3ecf8aa.3cf67","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":520,"wires":[["e60af926.ff59e"]]},{"id":"4f7020ec.b1a3c","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":560,"wires":[["e60af926.ff59e"]]},{"id":"b130a9e5.f6627","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"13","set":"","level":"0","out":"out","x":680,"y":600,"wires":[]},{"id":"ec0fbfec.14f36","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":600,"wires":[["b130a9e5.f6627"]]},{"id":"4c383555.c1caec","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":640,"wires":[["b130a9e5.f6627"]]},{"id":"752e3021.391258","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"15","set":"","level":"0","out":"out","x":700,"y":680,"wires":[]},{"id":"ddd5ea69.e3db5","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":680,"wires":[["752e3021.391258"]]},{"id":"975d49d6.9f8418","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":720,"wires":[["752e3021.391258"]]},{"id":"83d7c067.36f0f","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"16","set":"","level":"0","out":"out","x":680,"y":760,"wires":[]},{"id":"d9d7751f.702818","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":760,"wires":[["83d7c067.36f0f"]]},{"id":"23950c29.542c64","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":800,"wires":[["83d7c067.36f0f"]]},{"id":"f91b90b9.8afaa","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"18","set":"","level":"0","out":"out","x":680,"y":820,"wires":[]},{"id":"729d5534.708ed4","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":840,"wires":[["f91b90b9.8afaa"]]},{"id":"d8b62f62.21c2c","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":880,"wires":[["f91b90b9.8afaa"]]},{"id":"9e58d3f1.d894b","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"19","set":"","level":"0","out":"out","x":680,"y":920,"wires":[]},{"id":"9626cf7c.f68d5","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":920,"wires":[["9e58d3f1.d894b"]]},{"id":"f28251a1.69118","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":530,"y":960,"wires":[["9e58d3f1.d894b"]]},{"id":"d4c21ce5.e31438","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"38","set":"","level":"0","out":"out","x":1000,"y":1000,"wires":[]},{"id":"ba61636e.3e1098","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":1000,"wires":[["d4c21ce5.e31438"]]},{"id":"70910d8b.535e5c","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":1040,"wires":[["d4c21ce5.e31438"]]},{"id":"dd4f96be.dd30d8","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"21","set":"","level":"0","out":"out","x":1020,"y":120,"wires":[]},{"id":"a4edbc8f.16cf68","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":120,"wires":[["dd4f96be.dd30d8"]]},{"id":"e6d5fbb6.a638a","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":160,"wires":[["dd4f96be.dd30d8"]]},{"id":"c8598e6a.cf737","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"22","set":"","level":"0","out":"out","x":1026,"y":204,"wires":[]},{"id":"3293176f.b393e","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":200,"wires":[["c8598e6a.cf737"]]},{"id":"3f3ce25d.3d2a36","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":240,"wires":[["c8598e6a.cf737"]]},{"id":"5414c6f8.3c796","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"23","set":"","level":"0","out":"out","x":1020,"y":280,"wires":[]},{"id":"44f79622.453b68","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":280,"wires":[["5414c6f8.3c796"]]},{"id":"7c4a4649.ec0bf","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":320,"wires":[["5414c6f8.3c796"]]},{"id":"478d0b2a.01d0ac","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"24","set":"","level":"0","out":"out","x":1020,"y":340,"wires":[]},{"id":"39c3a607.5c5432","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":360,"wires":[["478d0b2a.01d0ac"]]},{"id":"8ac580dc.0c3a","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":400,"wires":[["478d0b2a.01d0ac"]]},{"id":"54aeed24.b90eac","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"26","set":"","level":"0","out":"out","x":1020,"y":440,"wires":[]},{"id":"3b9ff21d.076476","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":440,"wires":[["54aeed24.b90eac"]]},{"id":"583ebbc7.b620e4","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":870,"y":480,"wires":[["54aeed24.b90eac"]]},{"id":"49cdf054.c92b18","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"29","set":"","level":"0","out":"out","x":1000,"y":520,"wires":[]},{"id":"d4f53e3a.7e1d68","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":520,"wires":[["49cdf054.c92b18"]]},{"id":"d16d2956.8a7c5","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":560,"wires":[["49cdf054.c92b18"]]},{"id":"18d07a47.759dd6","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"31","set":"","level":"0","out":"out","x":1000,"y":600,"wires":[]},{"id":"ca6f6011.cf00d8","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":600,"wires":[["18d07a47.759dd6"]]},{"id":"cbb262f4.bd3e4","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":640,"wires":[["18d07a47.759dd6"]]},{"id":"fac89726.9485c","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"32","set":"","level":"0","out":"out","x":1020,"y":680,"wires":[]},{"id":"b8a116b7.98a9c8","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":680,"wires":[["fac89726.9485c"]]},{"id":"2bae0828.ddcff8","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":720,"wires":[["fac89726.9485c"]]},{"id":"8d53265a.e17778","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"33","set":"","level":"0","out":"out","x":1000,"y":760,"wires":[]},{"id":"6d9ba8c1.926","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":760,"wires":[["8d53265a.e17778"]]},{"id":"9369b8a9.b57828","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":800,"wires":[["8d53265a.e17778"]]},{"id":"8355c52d.8c5638","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"35","set":"","level":"0","out":"out","x":1000,"y":820,"wires":[]},{"id":"a1a73681.d0ff58","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":840,"wires":[["8355c52d.8c5638"]]},{"id":"c782da47.8029b","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":880,"wires":[["8355c52d.8c5638"]]},{"id":"63e270a4.2065b8","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"37","set":"","level":"0","out":"out","x":1000,"y":920,"wires":[]},{"id":"b96c99c3.d5d878","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":920,"wires":[["63e270a4.2065b8"]]},{"id":"7857336.540bd4c","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":850,"y":960,"wires":[["63e270a4.2065b8"]]},{"id":"6959571a.434028","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"40","set":"","level":"0","out":"out","x":660,"y":1000,"wires":[]},{"id":"f23595fe.4c5128","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":510,"y":1000,"wires":[["6959571a.434028"]]},{"id":"f6bdb1bd.7f7d88","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":510,"y":1040,"wires":[["6959571a.434028"]]},{"id":"674e167d.dba89","type":"rpi-gpio out","z":"4125f04b.beda1","name":"","pin":"36","set":"","level":"0","out":"out","x":1020,"y":1120,"wires":[]},{"id":"6efe58f4.3ceb78","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":830,"y":1080,"wires":[["674e167d.dba89"]]},{"id":"c8fbe6c7.962c88","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":830,"y":1120,"wires":[["674e167d.dba89"]]},{"id":"1d92d4a0.e26d2b","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":281.875,"y":58.75,"wires":[["b0f78b3b.4f0878"]]},{"id":"20cb4401.df34bc","type":"inject","z":"4125f04b.beda1","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":298.75000381469727,"y":311.25000190734863,"wires":[["b0f78b3b.4f0878"]]},{"id":"b0f78b3b.4f0878","type":"function","z":"4125f04b.beda1","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":296.875,"y":196.75,"wires":[["e7ae3eb.4d91a4","edbb161e.34d748","332bb059.01a518","4f823a32.61ed9c","c62b79a6.b6e298","e60af926.ff59e","300f1d99.bd1192","b130a9e5.f6627","752e3021.391258","83d7c067.36f0f","f91b90b9.8afaa","9e58d3f1.d894b","6959571a.434028","d4c21ce5.e31438","674e167d.dba89","63e270a4.2065b8","8355c52d.8c5638","8d53265a.e17778","fac89726.9485c","18d07a47.759dd6","49cdf054.c92b18","478d0b2a.01d0ac","54aeed24.b90eac","5414c6f8.3c796","c8598e6a.cf737","dd4f96be.dd30d8"]]}]
`
Yours, 
Confused of Buckinghamshire

**Comment by DrLucyRogers** [comment]
Have now removed all non GPIO labelled pins from the flow. Am left with 17 physical pins 7,11,13,15,29,31,33,35, 37,12,16,18,22,32,36,38,40.

Same problem - after a few "all on" and "all off" some of them don't come on - (11,15,37,12,16,22,32,36,38,40).

**Comment by dceejay** [comment]
In 0.14.0 I'm going to restrict the pins available list to only the ones specifically for GPIO - rather than allow all the others to be used as well. While the other can be used they often need some of the drivers turned off in raspi-config - or even more complex things... like editing files... So to keep it simpler I'm going to remove the options to select them. Existing flows will still run as it's only these more complex choices that have been removed.

So far running the above flow with only GPIO pins (ie removing others) has been stable for me toggling at 0.2s on 0.2s off for 20 minutes.

**Comment by DrLucyRogers** [comment]
Apologies. It seems to be related to some extra nodes I installed. Am closing the bug and taking it up with the node creator ...
