### ISSUE TITLE
Create default settings.js in the specified user directory

### ISSUE THREAD

**Issue by jimbojw** [node-red/node-red#908]
When starting up, Node-RED should create the default `settings.js` file in the specified `userDir` if not present.

To reproduce this issue,  run `node-red` with the `--userDir` argument pointing to a directory that doesn't exist, and do not specify `--settings`.

```sh
$ node-red --userDir ./config
```

*Expected behavior*

The specified directory is created, and the default `settings.js` file is created therein.

*Actual behavior*

The user directory is created, but the default `settings.js` is put into `~/.node-red/` instead.

*Root cause*

In `red.js`, on [line 84](https://github.com/node-red/node-red/blob/0.13.4/red.js#L84), the `userDir` variable ignores the specified user directory (if any).

```js
var userDir = path.join(process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE,".node-red");
```

*Recommended fix*

Use `parsedArgs.userDir` if present before looking to the user's `.node-red` directory.

```js
var userDir = parsedArgs.userDir || path.join(...
```

Node-RED Version: v0.13.4
Node.js Version: v6.2.1

**Comment by knolleary** [comment]
Ooo - good spot, thanks!

And _**just**_ in time for 0.14.

**Comment by jimbojw** [comment]
No problem! Impressive turn-around on tagging the issue :)

**Comment by natcl** [comment]
Not sure this got fixed properly, here's what happen when I run in a custom user directory:

```
19 Jun 22:29:03 - [info] Settings file  : /Users/Nat/Desktop/14/.node-red/settings.js
19 Jun 22:29:03 - [info] User directory : /Users/Nat/Desktop/14
19 Jun 22:29:03 - [info] Flows file     : /Users/Nat/Desktop/14/flows_Papet.local.json
```

Seems like settings get create in that custom directory but in a .node-red subfolder still, is that the normal behaviour ?

**Comment by knolleary** [comment]
Grrrrrr

**Comment by ekyo0506** [comment]
@jimbojw  Hi Sir
Can you make it more clearly ??
how to run node-red with the --userDir????
i'm so glad because of your responce :D:D

**Comment by knolleary** [comment]
@ekyo0506 http://nodered.org/docs/getting-started/running#command-line-usage

Please ask any further questions on the mailing list as this issue is closed.
