### ISSUE TITLE
Twitter Input - Add New Twitter-Credentials

### ISSUE THREAD

**Issue by AndrewBigMac** [node-red/node-red#913]
I am trying to use the Twitter input, but am unable to authenticate. When I click on the edit icon there is no click here to authenticate as expected.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/20044107/16194104/c4c0b3d6-36ea-11e6-972e-4061fa5b8c65.png)

![image](https://cloud.githubusercontent.com/assets/20044107/16194083/9f61da8e-36ea-11e6-9cd7-89903a55737c.png)

**Comment by knolleary** [comment]
Hi - yes, we spotted this a short time ago. Currently working on the fix and 0.14.2 will follow - hopefully within the hour.
