### ISSUE TITLE
InjectNode input event ignoring incoming message

### ISSUE THREAD

**Issue by gavinhungry** [node-red/node-red#914]
https://github.com/node-red/node-red/blob/0.14.3/nodes/core/core/20-inject.js#L52-L54

The `_msgid` generated by `receive` is ignored, then a new ID is created when the message gets to `send`. I suggest for line 54:

```javascript
msg.topic = this.topic;
```

**Comment by knolleary** [comment]
Hi - thanks for pointing this out.

As the Inject node is an Input node, it never gets passed an existing message other than the one it generates for itself, so besides a slight redundancy in that it ends up generating two `_msgid`'s, I'm not sure this has any real impact?

Needs tidying up regardless - thanks.
