### ISSUE TITLE
Node-RED UI failing with vendor.js net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by nssundar** [node-red/node-red#915]
After installing some nodes and restarting Node-RED I get 
`GET http://myipaddress:1880/vendor/vendor.js net::ERR_CONNECTION_RESET`. I have tried browser cache clean. I also see that the vendor.js file is present in `/usr/local/lib/node_modules/node-red/public/vendor` folder. 

Here are the versions that I am running:
node-red : 0.13.4
node : 5.10.1

**Comment by knolleary** [comment]
Can you access `http://myipaddress:1880/vendor/vendor.js` directly in your browser?

What nodes did you install? Have you tried removing them?

**Comment by nssundar** [comment]
I have installed Crate, Swagger, UI and NEST nodes. No I did not try removing them. From the browser too when I hit http://myipaddress:1880/vendor/vendor.js, the file does not load.

**Comment by knolleary** [comment]
And presumably you access the editor at `http://myipaddress:1880/` and have not modified the `httpAdminRoot` or `httpNodeRoot` settings?

Given you have so few nodes, it would help us enormously if you could see if removing any of those nodes has a bearing on this.

**Comment by knolleary** [comment]
Hi, any updates on this?

**Comment by nssundar** [comment]
This somehow fixed itself after a few restarts of node-red. I am not sure what solved it.
