### ISSUE TITLE
trigger node reuses msg object

### ISSUE THREAD

**Issue by jimbojw** [node-red/node-red#916]
Node-Red version: 0.14.3
Node version: 6.2.2

The built-in [trigger node](https://github.com/node-red/node-red/blob/0.14.3/nodes/core/core/89-trigger.js) reuses the same `msg` object when sending the second message, clobbering the first message's payload. This causes a race condition where any delay to the first message appears to downstream receivers as two copies of the same message.

To reproduce this issue:

* Start with a clean workspace.
* Drag an inject node, a trigger node, a delay node, and a debug node onto the workspace and wire them in that order.
* Deploy, then click the inject node's button.

Expected: After 5s, see `1` and then `0` in the debug tab.

Actual: After 5s, see `0` and then `0` again in the debug tab.

Proposed fix: In `89-trigger.js`, prior to creating the `tout` timer (lines 73 & 84), clone the `msg` object. Then inside the timeout callback, send the cloned object rather than the original.

Example flow:

```js
[
  {
    "_def": {
      "defaults": {
        "label": {
          "value": ""
        }
      }
    },
    "label": "Flow 1",
    "id": "3dea0142.008576",
    "type": "tab"
  },
  {
    "wires": [
      [
        "d7d3a69e.4f34a"
      ]
    ],
    "y": 168.46665954589844,
    "x": 149.25001525878906,
    "once": false,
    "crontab": "",
    "id": "9d86ef7d.256c18",
    "type": "inject",
    "z": "3dea0142.008576",
    "name": "",
    "topic": "",
    "payload": "",
    "payloadType": "date",
    "repeat": ""
  },
  {
    "wires": [
      [
        "f8315efc.a1f428"
      ]
    ],
    "y": 229.81666564941406,
    "x": 295.25001525878906,
    "name": "",
    "reset": "",
    "units": "ms",
    "extend": "false",
    "id": "d7d3a69e.4f34a",
    "type": "trigger",
    "z": "3dea0142.008576",
    "op1": "1",
    "op2": "0",
    "op1type": "val",
    "op2type": "val",
    "duration": "250"
  },
  {
    "wires": [
      [
        "ed9b58dc.3d5d1"
      ]
    ],
    "y": 298.9833221435547,
    "x": 453.25001525878906,
    "drop": false,
    "randomUnits": "seconds",
    "randomLast": "5",
    "randomFirst": "1",
    "rateUnits": "second",
    "id": "f8315efc.a1f428",
    "type": "delay",
    "z": "3dea0142.008576",
    "name": "",
    "pauseType": "delay",
    "timeout": "5",
    "timeoutUnits": "seconds",
    "rate": "1"
  },
  {
    "wires": [],
    "y": 350.18333435058594,
    "id": "ed9b58dc.3d5d1",
    "type": "debug",
    "z": "3dea0142.008576",
    "name": "",
    "active": true,
    "console": "false",
    "complete": "false",
    "x": 626.2500152587891
  }
]
```

**Comment by dceejay** [comment]
Good spot. Thanks. 
Bonus points for the flow to test.
