### ISSUE TITLE
Watch node does not display edit screen

### ISSUE THREAD

**Issue by DeanCording** [node-red/node-red#917]
Double clicking on a Watch node does not display the edit screen.  Browser window dims but edit screen does not slide out.

Browser reports Javascript error:
TypeError: b(...) is not a function
m.access()  vendor.js:4
m.fn[d]()      vendor.js:5
a()              red.min.js:20
RED.tray</<.show()    red.min.js:20
p()                   red.min.js:19
v()                  red.min.js:18
i()                   vendor.js:32

Upgraded to Node Red 0.14

**Comment by DeanCording** [comment]
If you deploy the unconfigured node, the edit screen will then display.

**Comment by DeanCording** [comment]
Now that I've deployed the Watch node, if I delete it and create another it works ok.

**Comment by DeanCording** [comment]
But refreshing the browser window causes the problem to reoccur.  Doesn't appear to affect other types of nodes.

**Comment by DeanCording** [comment]
Deploying the unconfigured Watch node doesn't always fix the problem.

**Comment by knolleary** [comment]
So far, I've not been able to recreate this having tried a variety of combinations of sequences.

Whilst it shouldn't matter, what browser are you using?

To help debug this, could you run node-red with the `NODE_ENV` environment variable set to `development`. The editor will then load an un-minified version of its code and we'll be able to see exactly where this is tripping up.

Thanks.

**Comment by knolleary** [comment]
Hi @DeanCording - any idea if/when you may be able to look at this? We want to get 0.14.4 done and are currently holding it pending understanding this issue.

**Comment by DeanCording** [comment]
Output with NODE_ENV=development

TypeError: b(...) is not a function
m.access()          vendor.js:4
m.fn[d]()              vendor.js:5
showTray()          red.js:8550
show()                 red.js:8658
showEditDialog() red.js:7830
nodeMouseUp()  red.js:4799
i()                         vendor.js:32

**Comment by DeanCording** [comment]
Output with NODE_ENV=development and prettified vendor.js

TypeError: b(...) is not a function
m.access() vendor.js:1803
m.fnd vendor.js:4411
showTray() red.js:8550
show() red.js:8658
showEditDialog() red.js:7830
nodeMouseUp() red.js:4799
i() vendor.js:32

**Comment by knolleary** [comment]
@DeanCording can you attach your prettified vendor.js or tell me exactly how you prettified it, as I can't get those line numbers to line up locally.

**Comment by DeanCording** [comment]
Used the prettifier in FIrefox's web developer debugger

**Comment by knolleary** [comment]
And what exact version of node-red? 0.14.3?

**Comment by DeanCording** [comment]
0.14.0: Milestone Release

**Comment by knolleary** [comment]
Hmm, can't get it to line up. Can you copy into a file and attach it here?

**Comment by DeanCording** [comment]
[vendor.js.zip](https://github.com/node-red/node-red/files/336822/vendor.js.zip)

**Comment by knolleary** [comment]
Took a while, but I got there. This is only reproducible with Firefox as it has support for the `Object.watch` function, which Chrome doesn't yet.

The name clash between the node type and the built-in function on Object was the root cause. Updated to do a proper `hasOwnProperty` check so it ignores the prototype functions and avoids the clash.
