### ISSUE TITLE
IBM IoT output node reports error "JSON Message expected".

### ISSUE THREAD

**Issue by janvda** [node-red/node-red#918]
On my node-red instance running on bluemix I get following error on my IBM IoT output node:

> 24-6-2016 16:40:26IBM IoT
> msg : string [21]
> JSON Message expected

The message that is send to the IBM IoT output =

> 24-6-2016 16:40:26msg stored in cloudant DB
> test : msg : Object
> { "topic": "test", "payload": { "timestamp": "2016-06-24T14:40:34.605Z", "power": 0, "deltaTimeInMs": 1792, "deltaPower": -1000, "prevTimestamp": "2016-06-24T14:40:32.813Z", "prevPower": 1000, "oldState": "on and increasing", "newState": "off", "startTime": "2016-06-24T14:17:13.280Z", "startPower": 0, "increaseCount": 1, "onsetPower": 1000, "powerConsumption": 389.00791666666663, "sampleCount": 2, "stopTime": "2016-06-24T14:40:33.709Z", "stopPower": 0, "durationInMs": 1400429, "avgPower": 999.999642966548, "peakPower": 1000, "deviceType": "NotYetSpecified", "topic": "test" }, "_msgid": "19292ac2.e6d6d5" }
> 

The configuration of my IBM IoT output =

![image](https://cloud.githubusercontent.com/assets/17238398/16341042/70f67814-3a2b-11e6-8d46-b03dfc20eba3.png)

I have specified the "Data" property above as otherwise node-red is complaining
but the actual data that I want to be send, can be found in the msg.payload of the message above.

Any help would be much appreciated.
kr
Jan.

**Comment by knolleary** [comment]
Hi, this node is not one maintained by the node-red project. You should report issues for it with the maintainers over here: https://github.com/ibm-watson-iot/iot-nodered

(I happen to know the answer - the node (incorrectly) requires you to convert your message to a String before you pass it in. So if you add a JSON node in your flow beforehand, it will encode your message properly. I have previously raised this with the underlying library the node uses and you've reminded me to chase them on it - https://github.com/ibm-watson-iot/iot-nodejs/issues/18)

**Comment by janvda** [comment]
Thanks a lot Nick,  Indeed putting a json node before fixed it.  My excuses for posting this at the wrong project. Jan
