### ISSUE TITLE
Inject node: Payload input field is fixed width

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#919]
Unlike the other fields, the payload field is fixed at 300px. This makes it harder to enter the more complex data that is allowed. Line 20 should be `style="width:70%"` instead of `style="width:300px"`

I think there is an error in the topic field as well as the style has a trailing "x" after the % sign. Line 26 should be `style="width: 70%"` instead of `style="width: 70%x"`

**Comment by TotallyInformation** [comment]
Same issue with the property field in the Switch node.

**Comment by knolleary** [comment]
This is a common issue with the typedInput element we introduced in the last release. This needs resolving globally and not on a case-by-case basis.

**Comment by TotallyInformation** [comment]
Hi Nick, I saw that as I started looking for examples to help with updating my moment node ;)

I'll stop pestering you then.
