### ISSUE TITLE
twitter input node returning unexpected tweets

### ISSUE THREAD

**Issue by andysc** [node-red/node-red#92]
If I configure "tweets from who you follow" and for (say)  "IBM" (no quotes, just the three letters), and connect it to a debug node,
I get tweets which contain IBM, but also ones which don't, and which aren't by people who have IBM in their bio or screen name.
I suspect this is a twitter API problem, but I don't see it when I search for IBM in the twitter home page when I'm logged in... that only gives tweets containing or by IBM names.

Indeed, if I put in a random string of letters in the FOR field, I still get some hits (not containing those letters)

**Comment by knolleary** [comment]
Marked wontfix for some time now. It's all an unfortunate artefact of what the twitter api gives us.
