### ISSUE TITLE
Switch node: formatting issue when >9 entries

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red#920]
After 9 entries in a switch node, the formatting goes wonky.

Some have missing numbers and some wrap over 2 lines no matter how wide you make the tray. 

Happened prior to v0.14 as well I think.

I put a screen shot in the Google Group.

**Comment by dceejay** [comment]
Issue #919 re width also applies here

**Comment by knolleary** [comment]
Resolved by the commit referenced above
