### ISSUE TITLE
Enabling importing a flow with credentials attached

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#925]
Currently it is not possible to import a flow that has credentials attached to individual nodes. This is a reflection of the fact you cannot export a flow with credentials attached. But there are valid cases for wanting to import a flow that includes credentials, even if, currently, such a flow would have to have had the credentials added by hand.

**Comment by piotrpad** [comment]
It does not work via "Import" from menu, but (for me) works perfectly from post to /flows. One observation - in dialogs credentials often have different names (labels) like API key / API token etc. while in "credentials { ...}" they are always (?) password and user. Most simple solution would be to export credentials {...} with blank values for user/password so users know how to name JSON properties (and then again on import just ignore empty credentials in case careless user tries to import just-exported flow?).

**Comment by knolleary** [comment]
@piotrpad this issue is specifically for the action of importing within the editor.

The runtime API's support the flow including credentials as that is what the editor uses to set them in the first place.

**Comment by knolleary** [comment]
closed by 538a16a5fb4c1bf4189c147540735109c8dd1f52
