### ISSUE TITLE
Memory leak (suspected)

### ISSUE THREAD

**Issue by stefanoco** [node-red/node-red#926]
After upgrading to 0.14.0 on a host I'm experiencing a (suspected) memory leak, eats 100% in a few days. Also using a few contrib nodes so not sure this is related to NodeRED itself, any suggestion for identifying the leak?

**Comment by stefanoco** [comment]
Confirm:

```bash
user@host:~$ watch smem node-red
```

reveals increasing memory usage every few seconds

**Comment by knolleary** [comment]
Memory usage will natural increase until node's garbage collector kicks in around the 2gb mark. So want to be certain this is a real leak and not just that 'normal' behaviour.

For it to be actively increasing that should give some clues as to which flows are involved. What nodes have you got that are being triggered with the sort of regularity you see the memory increase by?

You could systematically disable each flow (temporarily delete its input node) and see how that affects the memory pattern.

**Comment by stefanoco** [comment]
I'm pretty sure it goes well over 2gb, I'll keep it under control and try to understand which flow/node with your suggestion, thanks

**Comment by davidoc85** [comment]
I have seen a similar issue.  How can I disable each flow to check issues?
Currently running:
node-red-dashboard
node-red-contrib-modbus
mqtt nodes
Node-red is running very slow.  Any ideas as to why this might be?  (Can open a new issue for this)
The following output came when running node-red as it mentions that there is a memory leak:

`Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-57-generic x86_64)`
`  System information as of Thu Jan  5 13:01:33 GMT 2017`
`  System load: 0.4                Memory usage: 0%   Processes:       268`
`  Usage of /:  2.4% of 423.47GB   Swap usage:   0%   Users logged in: 0`

`Welcome to Node-RED`
`===================`

`5 Jan 15:04:24 - [info] Node-RED version: v0.15.2`
`5 Jan 15:04:24 - [info] Node.js  version: v4.6.2`
`5 Jan 15:04:24 - [info] Linux 4.4.0-57-generic x64 LE`
`5 Jan 15:04:24 - [info] Loading palette nodes`
`5 Jan 15:04:25 - [info] Dashboard version 2.1.0 started at /ui`
`5 Jan 15:04:25 - [warn] ------------------------------------------------------`
`5 Jan 15:04:25 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node`
`5 Jan 15:04:25 - [warn] ------------------------------------------------------`
`5 Jan 15:04:25 - [info] Settings file  : /home/pancras6/.node-red/settings.js`
`5 Jan 15:04:25 - [info] User directory : /home/pancras6/.node-red`
`5 Jan 15:04:25 - [info] Flows file     : /home/pancras6/.node-red/flows_ubuntu-server.json`
`5 Jan 15:04:25 - [info] Server now running at http://127.0.0.1:1880/`
`5 Jan 15:04:25 - [info] Starting flows`
`2017-01-05 15:04:25: Connecting to modbustcp slave at 100.120.87.49:502 unit_id: 1`
`(node) warning: possible EventEmitter memory leak detected. 11 mbinit listeners added. Use` `emitter.setMaxListeners() to increase limit.`
`Trace at ModbusClientNode.addListener (events.js:239:17)`
`    at ModbusClientNode.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)`
`    at new ModbusWrite (/home/pancras6/.node-red/node_modules/node-red-contrib-modbus/modbus` `/modbus-write.js:95:18)`
    `at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)`
    `at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)`
    `at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:277:29)`
    `at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)`
    `at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)`
    `at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)`
    `at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)`
    `at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)`
    `at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)`
    `at nextTickCallbackWith0Args (node.js:436:9)`
    `at process._tickCallback (node.js:365:13)`
`(node) warning: possible EventEmitter memory leak detected. 11 mbconnected listeners added. Use`  `emitter.setMaxListeners() to increase limit.`
`Trace`
   ` at ModbusClientNode.addListener (events.js:239:17)`
    `at ModbusClientNode.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)`
    `at new ModbusWrite (/home/pancras6/.node-red/node_modules/node-red-contrib-modbus/modbus` `/modbus-write.js:96:18)`
    `at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)`
    `at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)`
    `at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:277:29)`
    `at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)`
    `at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)`
    `at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)`
    `at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)`
    `at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)`
    `at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)`
    `at nextTickCallbackWith0Args (node.js:436:9)`
   `at process._tickCallback (node.js:365:13)`
`(node) warning: possible EventEmitter memory leak detected. 11 mberror listeners added. Use` `emitter.setMaxListeners() to increase limit.`
`Trace`
    `at ModbusClientNode.addListener (events.js:239:17)`
    `at ModbusClientNode.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)`
    `at new ModbusWrite (/home/pancras6/.node-red/node_modules/node-red-contrib-modbus/modbus` `/modbus-write.js:97:18)`
    `at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)`
    `at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)`
    `at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:277:29)`
    `at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)`
    `at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)`
    `at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)`
    `at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)`
    `at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)`
    `at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)`
    `at nextTickCallbackWith0Args (node.js:436:9)`
    `at process._tickCallback (node.js:365:13)`
`(node) warning: possible EventEmitter memory leak detected. 11 mbclosed listeners added. Use` `emitter.setMaxListeners() to increase limit.`
`Trace`
    `at ModbusClientNode.addListener (events.js:239:17)`
    `at ModbusClientNode.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)`
    `at new ModbusWrite (/home/pancras6/.node-red/node_modules/node-red-contrib-modbus/modbus` `/modbus-write.js:98:18)`
    `at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)`
    `at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)`
    `at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:277:29)`
    `at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)`
    `at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)`
    `at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)`
    `at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)`
    `at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)`
    `at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)`
    `at nextTickCallbackWith0Args (node.js:436:9)`
    `at process._tickCallback (node.js:365:13)`
`5 Jan 15:04:25 - [info] Started flows`
`5 Jan 15:04:25 - [info] [mqtt-broker:4aebbc11.d6c5fc] Connected to broker: mqtt://localhost:1883`
`5 Jan 15:04:53 - [error] [modbus-write:807] Data length error, expected 8 got 20`
`5 Jan 15:04:58 - [error] [modbus-write:806] Timed out`
`5 Jan 15:05:23 - [error] [modbus-write:807] Data length error, expected 8 got 20`
`5 Jan 15:05:23 - [error] [modbus-write:802] TypeError: value is out of bounds`
`5 Jan 15:05:28 - [error] [modbus-write:806] Timed out`
`5 Jan 15:05:53 - [error] [modbus-write:807] Data length error, expected 8 got 20`

**Comment by knolleary** [comment]
@davidoc85 that 'leak' is specifically with the ModbusClientNode - you should raise an issue against the `node-red-contrib-modbus` project: https://github.com/biancode/node-red-contrib-modbus

**Comment by knolleary** [comment]
@stefanoco did this go anywhere? We've not had any other reports of memory leaks (other than the websocket one that slipped into 0.16.0 and was fixed in 0.16.2... oops).

**Comment by stefanoco** [comment]
@knolleary sorry for not adding more info here: memory usage is now stable, I suspect this happened after an upgrade (0.15.2 now). No problem so far in weeks.

**Comment by knolleary** [comment]
Ok... Going to close then. Thanks!
