### ISSUE TITLE
Javascript issue - Too many errors

### ISSUE THREAD

**Issue by krambriw** [node-red/node-red#927]
When adding too many lines of javascript code in a function the editor indicates an error, "Too many errors found..."

Checking my javascript code in an external lint tool indicates no errors. The code seems to be working fine.

By reducing the number of lines (in my case to 118) the error warning goes away. 

This problem has been discussed in the Node-RED Google group:
https://groups.google.com/forum/#!topic/node-red/l9dlJzoxBOk

**Comment by knolleary** [comment]
Looks like it is the linting flagging errors on the globals that a Function node uses (`msg`, `context` etc).

Have asked over on the ace mailing list for advise on how to tell it about these globals: https://groups.google.com/forum/#!topic/ace-discuss/JdOI8mX6-tE

**Comment by knolleary** [comment]
Looking in their code, it appears they've recently added the ability to pass in a list of custom global variables that the linter should accept. However that is in git master and not been made available in a release...
