### ISSUE TITLE
SwitchNode not saving settings when exiting editor

### ISSUE THREAD

**Issue by madeinoz67** [node-red/node-red#928]
Recently upgraded to V0.14.3 from the previous latest 0.13 latest on RPM based centos server

Switch node does not save any changes to rules when clicking 'Done' and exiting the editor.

The Number of rules are correct

first rule is blank (same as when node is first added)  will not remember any values

Additional rules will remember the values

with all rules the logical operator is always set to ==   if changes will reflect the change until the 'done' button is pushed

1) screenshot of correct settings before "done" is pushed
http://www.screencast.com/t/a1cLZ0geDLIf

2) screenshot of results after going back into edit the node after saving
http://www.screencast.com/t/1xYByZsP5x

**Comment by natcl** [comment]
I have the exact same issue.

**Comment by knolleary** [comment]
What browser are you using? I cannot reproduce this on Chrome or Firefox.

**Comment by madeinoz67** [comment]
Safari 9.1.1 on OS X 10.11.5 - apologies, I should have put this in the original ticket

**Comment by knolleary** [comment]
Ah ha - Safari, aka, the one I always forget to test with. Yup, recreated it now. Thanks.

**Comment by madeinoz67** [comment]
I just checked on Firefox and correct saved settings are there, so appears to be saving correctly, just not displaying them correctly on Safari.
