### ISSUE TITLE
focusView does not work if node-red build in other page

### ISSUE THREAD

**Issue by GermanBluefox** [node-red/node-red#932]
With 0.14.3 all my users get an error in Chrome and FF.
![image](https://cloud.githubusercontent.com/assets/4582016/16616081/23a392e6-437b-11e6-821b-b9271c12e4e5.png)
node-red is build in with iframe into other configuration page.

The reason of problem is that focusView here
https://github.com/node-red/node-red/blob/master/editor/js/ui/view.js#L2164
wants to access parent window and this is not allowed. (security reason)

Why focusView access window.parent?

If I change focusView to this one:
```
function focusView() {
        var scrollX = window.scrollX;
        var scrollY = window.scrollY;
        $("#chart").focus();
        window.scrollTo(scrollX,scrollY);
    }
```
Everything is fine.

**Comment by knolleary** [comment]
Previously, as soon as you focused the workspace, it would cause the parent window to scroll to bring the iframe into full view - on certain browsers. This change was added as a workaround for that issue.

But I hadn't considered the origin mismatch issue... and in fact my local testing was done from the same server.

The change you've proposed doesn't add anything; the issue isn't with the window containing node-red.

Will investigate if we can try/catch this error to let it fail silently in the cases it isn't allowed.

**Comment by rafaelamorim** [comment]
Just to let you guys know...
I had the same issue, but setting `document.domain = '{{my_domain}}';` on both the main window and in the NODE_RED's template solved the issue.
I'm using both main window and nodered's iframe in the same domain, so if that's the case, i hope this works for you also...

Best,
Rafa

**Comment by knolleary** [comment]
@rafaelamorim oh, that's interesting. Will look to see if we can formalise that sort of thing in a future release.
