### ISSUE TITLE
typed input set to numeric in change node returns string

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#934]
Matt pointed this out in the general slack channel - but also cross posted his flow here.

https://groups.google.com/forum/#!topic/node-red/6MYENHLYViE

The change node is set to change a string to a numeric type - but returns a string...

**Comment by knolleary** [comment]
In 'change' mode it is doing a string search/replace. So if the the replacement the replace value is declared as a number, it is still be substituted into a string... resulting in a string.

We need to tighten up the options on the change mode as it is really only meant for this sort of string search/replace.

That said, when this came up on slack a couple weeks ago, the user wanted to do "if the payload is "foo" replace it with the boolean true... but was getting the string "true". So should consider if there is a special behaviour if the search value matches the entire thing, so replace it with the desired value AND type.

**Comment by dceejay** [comment]
I think this may be a simple fix...
if the add the test for fromType being a string to the existing exact match condition - added in bold below

<pre>if (typeof current === 'string') {
    if ((fromType === 'num' || fromType === 'bool' <b>|| fromType === 'str'</b>) && current === fromValue) {
        // str representation of exact from number/boolean
        // only replace if they match exactly
            RED.util.setMessageProperty(msg,property,value);
        } else {
            current = current.replace(fromRE,value);
            RED.util.setMessageProperty(msg,property,current);
        }
    } </pre>
