### ISSUE TITLE
Selecting deployment target(server) for a given flow

### ISSUE THREAD

**Issue by vu3mmg** [node-red/node-red#936]
Hi ,

Can I select a specific deployment target for a given  flow .
The scenario -

- I have a server which serves the UI .I will create flows using the ui.
- I have a farm of node.js servers . I want to select one server from the farm  and deploy my flow on that specific server.

regards
mahesh

**Comment by vu3mmg** [comment]
Closing this issue , since i will move this to mailing list.

**Comment by knolleary** [comment]
Hi, this is a question for the mailing list, not really an issue against the project.

You can push flows to a remote runtime instance using the admin rest api... so you could create a system that pushes a given set of flows to a targeted runtime.

But what you can't do today is run an editor by itself - it is still coupled to a runtime instance. Nor are there the necessary hooks in the code for you to add your deploy logic.

We've been (slowly) moving towards separating them out in the underlying code, that would enable you to run them as individual components. Bit we aren't there yet.
