### ISSUE TITLE
node-red crashes with empty flows_raspberrypi_cred.json file

### ISSUE THREAD

**Issue by johnwalicki** [node-red/node-red#937]
Similar to the crash reported in #824 , node-red will crash if there is an empty flows_raspberrypi_cred.json  file.

To reproduce, just create an empty flows cred file:
```
pi@raspberrypi:~/.node-red $ rm flows_raspberrypi_cred.json 
pi@raspberrypi:~/.node-red $ touch flows_raspberrypi_cred.json 
```

Presumably, no one would intentionally start node-red with an empty flow cred file. However, since it seems it is possible to do so accidentally (probably due to power failure between saving on re-deploy and syncing the actual disk) perhaps it would be a good idea to catch the error and continue as if starting with no flow file.  It happened on my Pi.

**Comment by knolleary** [comment]
What version if Node-RED are you running? This should be fixed in the recently released 0.14, which is making its way to the Jessie apt repositories as I write.

**Comment by johnwalicki** [comment]
I had previously updated my node-red nodes on my Pi
$ npm -g ls node-red
node-red@0.14.4

This is still a valid bug.

**Comment by dceejay** [comment]
error is
26 Jul 16:17:52 - [red] Uncaught Exception:
26 Jul 16:17:52 - SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/conway/node-red/red/runtime/storage/localfilesystem.js:266:34
    at /Users/conway/node-red/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by knolleary** [comment]
Ahh - credentials file. I'll put my 👓  back on when reading issues.

**Comment by dceejay** [comment]
So yes the fix fixed missing file ... but not bad or empty file

**Comment by johnwalicki** [comment]
Thanks Nick
