### ISSUE TITLE
AWS S3 "Watch" node not working

### ISSUE THREAD

**Issue by tedbarnett** [node-red/node-red#938]
I have been trying to use the "amazon s3 watch" node (from http://flows.nodered.org/node/node-red-node-aws) and having no luck with the "watch" functionality.  It never fires when a file is added to my S3 bucket.  Using the same AWS credentials, I am able to use the S3 "in" node just fine (i.e. specifying a specific file to download from S3), but the Watch node never fires.  I see no errors in my log files, so I have no idea what might be the problem.  I am running Node-Red on Bluemix.  Any thoughts appreciated.  My app depends on having this watch feature work correctly.  I've attached a screenshot of my node configuration: I've tried all forms of file wildcard to no avail.

![screen shot 2016-07-14 at 3 47 25 pm](https://cloud.githubusercontent.com/assets/694013/16858244/6edeca86-49da-11e6-846f-906cbb2cb6d8.png)

**Comment by hardillb** [comment]
As the AWS nodes are not part of the core Node-RED nodes, could you please raise this under the [node-red/node-red-web-nodes](https://github.com/node-red/node-red-web-nodes/) project

**Comment by tedbarnett** [comment]
Will do.  Apologies.
