### ISSUE TITLE
Sender.js became corrupt

### ISSUE THREAD

**Issue by erikvg01** [node-red/node-red#939]
After several weeks of running without issue, the file at /usr/lib/node_modules/node-red/node_modules/ws/lib called Sender.js became completely corrupt (Head of file):

/*!
 * ws: a node>{s vebsocket�cLient
 * Copyright(ci 2011 �iN�r Otto Stangvik <einaros@gmail.com>
 * MIT!Hicensed
 */

va� events = require('events')
  , util = requiRe(7util')
  ,0EventEmitter�= events.EventEmitter
  , ErrorCodes = requize('./EzrorCodes')*  , bufFerUtil = require(�./BuvferUtil/).BuffepUtil

I have not found any reason for this to have botched as it has.  Would it be possible to get a hold of the original Sender.js file?

**Comment by knolleary** [comment]
Hi,

this file comes from the `ws` module we depend on. The cleanest way to reinstall will be to:

1. have a look in `/usr/lib/node_modules/node-red/node_modules/ws/package.json` and make a note of the `version` - I'm guessing it is `0.8.1` but as you don't say what version of node-red you are using, I can't be certain.

2. Delete the whole `ws` module:

        cd /usr/lib/node_modules/node-red
        sudo rm -rf node_modules/ws

3. Reinstall the appropriate version of the module (still in the `/usr/lib/node_modules/node-red/` directory). Replace `0.8.1` below with the version from the `package.json` file you recorded in step 1.

        sudo npm install ws@0.8.1

**Comment by erikvg01** [comment]
This did not fix the problem.  Many files were in fact corrupt and I rebuilt.  Thank you for the fast response.
