### ISSUE TITLE
Passing parameter at runtime to node-red in the URL

### ISSUE THREAD

**Issue by masalinas** [node-red/node-red#941]
Before Start node-red, I would like to do from my app this:

Open in a new tab of my browser the node-red designer only with the flows of a project. To do that I implement a Storage API that save my flows in my mongoDB instance, but I observe that I have no posibility to getFlows passing an atribute to filter then

I imagine is possible pass atributes in the URL for example like this:

  `window.open("http://localhost:1880/red?projectId=HY566YUJyj5G");`

And then recover this atributes from my Storage API implementattion to get a filtered query and recover only the flows from the project id passed and then only show the tabs (flows) of this project.

Somebody knows how can make that?,

Regards.

**Comment by knolleary** [comment]
Hi, please use the mailing list for how-to/feature request type of items - links in the [CONTRIBUTING.md](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
