### ISSUE TITLE
Arch Arm Linux: "[warn] Cannot find Pi RPi.GPIO python library" with installed RPi.GPIO

### ISSUE THREAD

**Issue by coolchip** [node-red/node-red#945]
Hello,
I use the following system:
- Rasperry Pi 2
- Node-RED version: v0.14.5
- Node.js  version: v4.4.7
- RPi.GPIO version: v0.6.2

At Raspbian (Linux 4.4.13-v7+ arm LE) everything is working fine. With Arch Linux (Linux 4.4.15-1-ARCH arm LE) everytime I start node-red i get:

```
[warn] Cannot find Pi RPi.GPIO python library
[warn] [rpi-gpio] Warning : Cannot find Pi RPi.GPIO python library
```

But RPi.GPIO is proper installed. I can use it in python and I also be able to call 

```
$ node-red/nodes/core/hardware/nrgpio ver
0.6.2
```

A closer inspection of "node-red/nodes/core/hardware/36-rpi-gpio.js" shows this lines:

```
try {
	fs.statSync("/usr/share/doc/python-rpi.gpio");
} catch(err) {
	RED.log.warn(RED._("rpi-gpio.errors.libnotfound"));
	throw "Warning : "+RED._("rpi-gpio.errors.libnotfound");
}
```

At my Arch system I don't have the "/usr/share/doc/python-rpi.gpio" directory. If I create this dir, node-red is working without warnings, as aspected. 
Perhaps there is a better way to check if RPi.GPIO is available.

**Comment by dceejay** [comment]
Where did arch install that file to ?

**Comment by coolchip** [comment]
Did you mean this?

```
>>> import RPi.GPIO as GPIO
>>> print(GPIO.__file__)
/usr/lib/python2.7/site-packages/RPi/GPIO/__init__.pyc

```

**Comment by dceejay** [comment]
Actually I meant the doc/python-rpi.gpio dir

**Comment by coolchip** [comment]
I don't know. Perhaps there is no documentation.

**Comment by dceejay** [comment]
should be closed by 53ca3046b34d88210cea3a4b1aad52f3f505e47d

**Comment by goliatone** [comment]
FYI I had the same issue on [HypriotOS][1], had to manually create **/usr/share/doc/python-rpi.gpio** to get it to work.

[1]: http://blog.hypriot.com/downloads/

**Comment by dceejay** [comment]
can you report where it does install it ?  
(same as Coolchip above..."Did you mean this...") Thanks

**Comment by goliatone** [comment]
@dceejay It was found here:
`/usr/lib/python2.7/dist-packages/RPi/GPIO`

**Comment by pokryva** [comment]
Whereas to make it work on my Raspberry Pi 2 running OSMC (4.4.27-9-osmc) I had to modify [36-rpi-gpio.js file](https://github.com/node-red/node-red/commit/53ca3046b34d88210cea3a4b1aad52f3f505e47d) and point the fs.statSync  to /usr/local/lib/python2.7/dist-packages/RPi/GPIO
