### ISSUE TITLE
Lost all wires between nodes? How to re-create?

### ISSUE THREAD

**Issue by solars** [node-red/node-red#948]
Hi there,

My deployed wiring is still running, however, if I open node-red all the wires
between nodes seem to have been lost.

Can anyone tell me how I can recreate this? Is there any way I can re-import the
running version?

Thank you,
Christoph

**Comment by knolleary** [comment]
If your flows are still running, then the wires have not been lost. Take a backup of your flow file, just in case. And don't hit the deploy button.

What version of Node-RED are you running?

Are there any errors in the browser's JavaScript console?

**Comment by solars** [comment]
@knolleary Wow that was a fast answer! Thanks a lot!

I'm getting an error in the console, not sure if it is related:
Uncaught TypeError: Cannot read property 'valid' of null at:
red.min.js:19
...{var f=RED.nodes.node(d).valid;e=null==f||f}else e=b[c].hasOwnProperty("required")&&...

When opening the page I don't see any nodes in the first flow tab, if I change to the second tab then back, the nodes appear but no wiring.

Version is 0.13.2 (from docker image cpswan/node-red)

**Comment by knolleary** [comment]
That's quite an old version.You should consider upgrading. We now provide official docker images: http://nodered.org/docs/platforms/docker

**Comment by solars** [comment]
Thanks for the hint, I've updated now and everything seems to be working as before! Thank you
