### ISSUE TITLE
Feature request: Closing a flow

### ISSUE THREAD

**Issue by PerMalmberg** [node-red/node-red#949]
Based on what I have planed, I can see that there will be a lot of flows which will make the editor cluttered. Although I can make a lot of things into sub flows, I'd also loose the ability to debug them as they then become templates with no "runtime" while opened in the editor.

How about support for closing a flow in the editor, just like you can do with a sub-flow?

**Comment by knolleary** [comment]
Hi, as per our contribution guidelines, please direct feature requests to the mailing list.

**Comment by PerMalmberg** [comment]
oh, right. sorry :)
