### ISSUE TITLE
Adding a new valid config fails to clear node validitiy flag (orange triangle)

### ISSUE THREAD

**Issue by jimbojw** [node-red/node-red#951]
Node-RED version: v0.14.6
Node.js  version: v6.3.1
OS: Linux 3.13.0-92-generic x64 LE

### Problem description

When creating a new, valid, MQTT config, the node using it will not have its invalid state cleared. The orange triangle remains, and attempting to Deploy will trigger the "Confirm deploy" dialog.

This does not prevent the node from connecting properly. I have not yet tested this problem with other kinds of nodes which require configs.

### Steps to reproduce

1. Start with an empty workspace.
2. Drag an mqtt output node onto the workspace. Observe orange triangle.
3. Double-click to open the node editor.
4. Select "Add new mqtt-broker..." from the Server dropdown, then click the pencil button to add a new config.
5. Click "Add" to close the new config menu, accepting all defaults.
6. Back in the mqtt output node editor, click Done.

### Expected result

Back in the workspace, the mqtt output node's orange triangle should be cleared, and clicking Deploy should proceed normally.

### Actual result

The mqtt output node's orange triangle is not cleared, and attempting to deploy will throw up the "Confirm deploy" dialog indicating that "The workspace contains some nodes that are not properly configured".

Note that this does not prohibit the deploy from succeeding, and the node will still be able to establish a connection.

### Workaround

To clear the orange triangle (and underlying "invalid" state), perform these steps:

1. Double-click to open the node editor.
2. Click the pencil button under the Server heading.
3. In the config editor, click Update.
4. Back in the node editor, click Done.

Note that you do not have to make any changes to the config. Merely clicking the Update button (as opposed to the Add button on first creation) will successfully clear the node's invalid state.

**Comment by knolleary** [comment]
What version of node-red is this with?

**Comment by jimbojw** [comment]
Sorry, forgot to add that.

```sh
2 Aug 06:16:30 - [info] Node-RED version: v0.14.3
2 Aug 06:16:30 - [info] Node.js  version: v6.3.1
2 Aug 06:16:30 - [info] Linux 3.13.0-92-generic x64 LE
```

**Comment by jimbojw** [comment]
Update: Confirmed same behavior in v0.14.6

**Comment by dceejay** [comment]
Hi,
actually this is a half invalid configuration :-)...  At step 5 you can't just accept all defaults - as the broker host is a placeholder and not a default... but once you backout the label defaults to localhost (bug), and then when you deploy it uses that - so the underlying config is not complete - hence red triangle - but deploy still works...  
I have pushed a fix.

**Comment by jimbojw** [comment]
I see. `localhost` seemed like a perfectly reasonable default value, why not use it instead of forcing the user to type it out?

**Comment by dceejay** [comment]
it's only a reasonable default if you have a local broker installed. If you don't - e.g in cloud - (or it's not running) then you just get a node that doesn't connect - and the user has to work out what that means. Actually requiring them to use 2 seconds thought up front should mean they have a grasp of what's actually configured.
