### ISSUE TITLE
Howto load multiple flows.json via cmd line

### ISSUE THREAD

**Issue by Krieke** [node-red/node-red#953]
I didn't found directly an answer in the documentation and also not in the open and closed issue list.
When multiple flow taps are created:
1) Is it possible to export all the tabs into a single *.json file? (it seems not. It seems only the selected elements within a certain flow tab can be exported)
2) How can we export within one flow tab all the elements + including the flow tab name?
3) How can we load via cmd line multiple *.json flows? Each flow represents a flow tab within the node-red ui. Currently experimenting with the cmd line we are only able to load one.
4) Is it correct that when we call the *.json files like <"flows_"><hostname_><whatever>.json that we can launch multiple flows? Then we of course would like to identify the flow tabs which is currently unknown. Even when manually added "label":"desc"..nothing happens.

**Comment by knolleary** [comment]
Hi, please use the mailing list for general questions

**Comment by sivachaitanya** [comment]
did you resolve the problem with handling multiple .json flow files ?
