### ISSUE TITLE
Delete button?

### ISSUE THREAD

**Issue by 9H5G** [node-red/node-red#957]
Its (only a little) frustrating to have to get my PC up and running just to delete a node. I'm wondering if a delete button could be included as a standard editing 'tool' so we can use out tablets and other touch-screen devices?  Thx :)

**Comment by dceejay** [comment]
Please provide don't more context as to why this is an issue. If it is just a question or suggestion please use the mailing list to discuss it first. Thanks

**Comment by 9H5G** [comment]
Hi Dave,  We're using more and more tablets and touch-screen devices and it
would be nice, during development, not to have to switch back and forth
just to delete a node. Its not an 'issue' - just a nice-to-have.

Point taken on the mailing list - will ask there first in future :)

Kind Regards
John

**Comment by 9H5G** [comment]
Sweet! Thanks :) Now I can sit on the couch and edit nodes and flows :)

Kind Regards
John
