### ISSUE TITLE
How can I resolve watch a directory and publish throw Mqtt client

### ISSUE THREAD

**Issue by masalinas** [node-red/node-red#958]
I have a problem like this and I want resolve it with node-red:

   1) A service generate files in a directory at a frecuency rate.
   2) A want to recover this files and publish the payload of this files to a mqtt server.

I simple flow to resolve this would be:

- To resolve the problem 1) I have a watch node to recover these files from a folder.
- To resolve the problem 2) I have a Mqtt publisher node to publish the payload of this files.
 
To avoid that the watch continually get the same file from the directory if the publish was ok I will send the file to a history folder and if the publication was wrong I will keep this in the folder.

My question is: 
How can I control the publish callback events to check if the publish was ok or give me an error and then execute a javascript process of historicizing??

**Comment by dceejay** [comment]
Please use the google group mailing list (or slack channel)  for general how to queries.
Thank you

The status node will indicate if there is a problem with the mqtt link , but won't indicate success or confirm receipt. You would need another message to be sent from the receiving end to confirm correct receipt.

**Comment by knolleary** [comment]
Hi - as @dceejay says, please use the google group for general how-to queries.
