### ISSUE TITLE
Connect ECONNREFUSED with multiples HTTP requests

### ISSUE THREAD

**Issue by spawnrider** [node-red/node-red#959]
Hi,

We are encountering an issue when we are doing a lot of requests using HTTP Request on our NodeJS API server using NodeRED. 

By the way, we also tested this using our [WWW Request](https://www.npmjs.com/package/node-red-contrib-http-request) node which his implemented on the Request library. The result is the same :(

Here is the error stacktrace: 
`error:
  { message: 'Error: connect ECONNREFUSED 163.113.172.80:1337',
    source:
     { id: '5d2aa78c.a2d558',
       type: 'http-request',
       name: undefined,
       count: 1 },
    stack: 'Error: connect ECONNREFUSED 163.113.172.80:1337\n    at Object.exports._errnoException (util.js:856:11)\n    at exports._exceptionWithHostPort (util.js:879:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)' } }`

Of course, we tested our API server using Apache Benchmark (ab CLI) with success (no failure) and an API Rate of 500 req/s.

Technical information : 
- Node-RED version: v0.14.5
- Node.js  version: v5.5.0
- Windows_NT 6.1.7601 x64 LE
- Processor: Intel Xeon CPU E5-630 v3 3.70Ghz 8 Cores
- Memory: 64 Gb

Any idea ?

**Comment by knolleary** [comment]
Are you saying it works up to a certain request rate then stops working? Any sense of where that breaking point is?

**Comment by spawnrider** [comment]
Indeed, it breaks when it reaches a specific API rate.
We've found an workaround by setting the max sockets value like this :
```
http.globalAgent.maxSockets = 100;
https.globalAgent.maxSockets = 100; 
```
By default, the HTTP(S) global agent max socket value seems to be infinite... 

Do you have any idea of where to put this code? We actually place it our local implementation of HTTP Request but I think there is a better to do this.

**Comment by knolleary** [comment]
You can put that in your settings.js file - or do you think it needs to be something Node-RED explicitly sets for you?

**Comment by spawnrider** [comment]
Ok, I will put this code in my settings.js.

I think this is project/flow specific and not to be setted by default in the settings.js (may be only suggested?). 
We can close this issue.

**Comment by knolleary** [comment]
Thanks - good discovery though - will remember that in case it comes up again.

**Comment by jiajianrong** [comment]
@spawnrider, did you find the reason?  I met the same problem and the workaround worked too.   But I dont know why the problem occurs.
