### ISSUE TITLE
Node-red (IoT Integrations)

### ISSUE THREAD

**Issue by auluxa** [node-red/node-red#960]
Hi there,

I came across Node-Red and was wondering if I could integrate products like Nest Thermostat, Phillips Hue, etc to our web service with Node-Red and control them through our Mobile Apps.

Essentially use our mobile app to search, authenticate, and configure IoT products using Node-red APIs and control them using our mobile app. 

Our current cloud web service has the following functionalities:

- Users can register and authenticate themselves
- Select a service and purchase via ChargBee (Subscription Billing Service)
- Enable users to control our ZigBee Devices remotely via Bridge between the Gateway (Controller) to our Cloud Web Service.
- Our web service API also can search third party devices that have been integrated (currently none, hoping to use a service like yours) to our cloud web service and categorise them based on brand name, model name, and product category. It also has the following functions:
     - Assign name for device
     - Authenticate device through login
     - Assign room for device
     - Control Device using existing iOS App UI
     - Delete Device

I'm not a developer myself but wanted to know if Node-Red would be something we should be looking into.

**Comment by hardillb** [comment]
For questions please use the Node-RED mailing list here https://groups.google.com/forum/#!forum/node-red

**Comment by knolleary** [comment]
Hi,

Yes, you should take a look at node-red... But then we would say that.

If you want to discuss, please use the mailing list or slack linked from nodered.org. we keep this issues list for actual issues.

Nick
