### ISSUE TITLE
Lack support of STT

### ISSUE THREAD

**Issue by samarsultan** [node-red/node-red#962]
Depending on the PR #838 , Node-RED is supposed to handle the structured text expression (FilePath, email, URL).  So far, there is no effect of such handling. Here is an attachment illustrating the defects found while testing the bidi branch.
[STT issues.docx](https://github.com/node-red/node-red/files/419973/STT.issues.docx)

Thanks.

**Comment by knolleary** [comment]
The code has not been merged to master... this is still in progress.

**Comment by knolleary** [comment]
@wajnberg please have a look at this and advise

**Comment by wajnberg** [comment]
Hello @samarsultan ,

For now only the watch node has been STT enabled.
I will certainly enabled the remaining contexts you mentioned once Bidi branch would be merged.

Thank you

**Comment by tomerm** [comment]
@samarsultan thanks a lot for reporting on the issues. The work on STT is in progress. Please drop me a note if you wish to have more details on the progress and future plans.
