### ISSUE TITLE
unable to export flows

### ISSUE THREAD

**Issue by openStove** [node-red/node-red#966]
The export menu ist inactive, I cannot export flow anymore. What happened ?

Node-RED version: v0.14.6
Node.js  version: v4.4.7
Linux 4.4.13-v7+ arm LE

**Comment by hardillb** [comment]
You have to select the nodes you want to export

**Comment by openStove** [comment]
You-re right, thats not intuitive, I would expect being able to export everything, when nothing is selected

**Comment by dceejay** [comment]
yup - just like Microsoft Word, Powerpoint, Excel... :-)

**Comment by openStove** [comment]
and is there a way to export the config nodes ?
I the a way do download the whole config as json for example ?

**Comment by knolleary** [comment]
Better export options are on the to-do list: https://trello.com/c/LxAAMlww/53-better-flow-export-options-in-editor

You can grab the whole flow config by opening http://localhost:1880/flows (or where ever you are hosting node-red with /flows on the end).

**Comment by cuonglq** [comment]
@hardillb thanks you so much
