### ISSUE TITLE
Best Practice vs Node Processing Order

### ISSUE THREAD

**Issue by JpEncausse** [node-red/node-red#968]
Hi,
(I'm working on a MS BotBuilder library)

- I have a NodeA receiving and forwarding messages
- I have a NodeB sending back a message to chat client

I want to link NodeA with multiple NodeB then execute the NodeB matching the good value

- I can perform the test in NodeB but if it cost CPU I'l have to do it N times
- I can perform the test in NodeA but matching rul will be in NodeB
- I can perform the test in a Node between NodeB and NodeA

So I have some questions:

- If NodeA is linked to multiple NodeB is there a processing order ?
- From NodeA code can I have the list of NodeB attached to me ?

I assume NodeB will handle the regexp to match, but because the matching is also performed in Cloud (aka LUIS) I have to do it only once in NodeA.

**Comment by hardillb** [comment]
Questions should be asked on the [Google Group](https://groups.google.com/forum/#!forum/node-red) as we try to keep issues for actual defects.

**Comment by knolleary** [comment]
As Ben says, please use the mailing list for this type of question. You may want to provide a bit more context as it isn't clear what you mean by 'the test'.

Quick answers (but please follow up on mailing list):
 - messages are sent to the connected nodes in the order they were connected
 - no, a principle of flow based programming is that each node should act as a black box with no knowledge of what it is connected to.
