### ISSUE TITLE
Make config nodes scoped as global by default

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#972]
Having them scope to the current flow causes too many unexpected side effects to new users - they end up creating identical mqtt-broker configs for each tab, rather than share the same config.

**Comment by knolleary** [comment]
Done in 0.15.0 branch - d7d30aa9725ad532c49444f0b1bc44b4cb0835fe

**Comment by TheAlphaNerd** [comment]
Thanks for making this decision. I was just looking into the openwhisk node and was concerned I would have to implement some weird stuff to share a config node across flows. I'm going to send a doc fix to make sure this is clear.
