### ISSUE TITLE
http request  Parse Error statusCode: 'HPE_INVALID_HEADER_TOKEN' 

### ISSUE THREAD

**Issue by openStove** [node-red/node-red#974]
I'm always getting that error, even with a simple example, sending 
```
{ headers: { 'Content-Type': 'application/json' },
  payload: { features: { status: 'off' } },
  _msgid: 'add8adea.52275' }
```

I don't understand that error, does it mean it has problem to parse the msg input from node-red before sending ? or the response ? (I also tried to change the return mode to json, binary or string, with the same result)

26 Aug 10:01:28 - [info] Node-RED version: v0.14.4
26 Aug 10:01:28 - [info] Node.js  version: v4.2.6
26 Aug 10:01:28 - [info] Linux 4.4.0-36-generic x64 LE

**Comment by knolleary** [comment]
Can you provide an example flow to put this into context?

**Comment by openStove** [comment]
[{"id":"65950ecc.56ca9","type":"inject","z":"fd018827.f2d908","name":"","topic":"","payload":" { \"features\": { \"status\": \"off\" } }","payloadType":"json","repeat":"","crontab":"","once":false,"x":304,"y":263,"wires":[["3f5fa2a2.9953be"]]},{"id":"3f5fa2a2.9953be","type":"http request","z":"fd018827.f2d908","name":"","method":"POST","ret":"obj","url":"http://172.17.0.1:9995/public/api/v1/prediction/prediction/predict","tls":"","x":500.5,"y":263,"wires":[["ac1c4c6a.06825"]]},{"id":"ac1c4c6a.06825","type":"debug","z":"fd018827.f2d908","name":"","active":true,"console":"false","complete":"false","x":688.5,"y":263,"wires":[]}]

**Comment by openStove** [comment]
If needed I could send you privately a docker instance from the server, but I'm not sure the problem is the server ?

**Comment by knolleary** [comment]
It would appear your server is responding with a malformed response: http://stackoverflow.com/questions/34048476/node-js-get-request-errors-with-hpe-invalid-header-token

**Comment by openStove** [comment]
Yes you're right, I tried with a fake rest api : http://jsonplaceholder.typicode.com/, and a newer version of the server, and it working... seems to be a bug in the specific version we're using...
Thanks a lot !

**Comment by regevbr** [comment]
https://github.com/creationix/http-parser-js fixed the issue for me

**Comment by dandres16** [comment]
> https://github.com/creationix/http-parser-js fixed the issue for me

Have you used it in node-red?

**Comment by regevbr** [comment]
Nope
