### ISSUE TITLE
not able to start and stop node red console from console

### ISSUE THREAD

**Issue by premvikr** [node-red/node-red#977]
i have added couple of packages but have not been able to see in my Node red editor even after refreshing the browser. i am unable to start and stop the node red console.

**Comment by dceejay** [comment]
Pleas use the google mailing list for general how-to type  questions..

**Comment by hardillb** [comment]
The mailing list is here https://groups.google.com/forum/#!forum/node-red
Also you are going to have to supply a LOT more information
