### ISSUE TITLE
How to receive data on TCP/IP with Node-red

### ISSUE THREAD

**Issue by ekyo0506** [node-red/node-red#984]
I being on small problem about my Node-red Project
actually i want to receive data from outer sensor via TCP/IP Node-red and display it on Node-red broswer ( ui-gauge, ui-chart,... anything like that). 
So i appreciate any idea ^^
Tks for reading my problem

**Comment by dceejay** [comment]
Please use the mailing list or slack channel for questions like this. We prefer to keep the issue list for defects in the software.

**Comment by ekyo0506** [comment]
i'm so sorry but this my first time i ask via github.com
so i can not get your mean
i so glad if you can make it more clearly
again i'm so sorry if make anything wrong

**Comment by ekyo0506** [comment]
That's so nice of you
if i'm wrong, can you show me the way how to ask a question in this web rightly????

**Comment by knolleary** [comment]
@ekyo0506 please ask your question here: https://groups.google.com/forum/#!forum/node-red
