### ISSUE TITLE
debug messages for node-red embedded with prepend URL path variables

### ISSUE THREAD

**Issue by oprince** [node-red/node-red#986]
We run node-red embedded architecture. Messages are not displayed at the editor UI debug sidebar if a path variable is preppended to editor URL.

The following code is used to start node-red:

> var express = require('express');
var app = express();
var RED = require("node-red");
var path = require('path');
var settings = require(path.join( process.cwd(),'nr_settings_test.js'));
var http = require('http');
var app = express();
app.use("/",express.static("public"));
var server = http.createServer(app);
RED.init(server,settings);
app.use(function(req, res, next){
    query = req.method + " " + req.path;
    console.log(JSON.stringify( query));
    next();
});
console.log("httpAdminRoot: " + settings.httpAdminRoot);
app.use(settings.httpAdminRoot,RED.httpAdmin);
//app.use("/wf-engine" + settings.httpAdminRoot,RED.httpAdmin);
console.log("httpNodeRoot: " + settings.httpNodeRoot);
app.use(settings.httpNodeRoot,RED.httpNode);
//app.use("/wf-engine" + settings.httpNodeRoot,RED.httpNode);
app.use('/cfg-mng', function(req, res){
    console.log("configuration api - TBD");
    next();
});
server.listen(1882);
RED.start();

nr_settings_test.js:

> 
var skipper = require("skipper")();
var path = require("path");
module.exports = {
    uiPort: 1880,
    mqttReconnectTime: 15000,
    serialReconnectTime: 15000,
    debugMaxLength: 1000,
	flowFile: 'test_flows.json',
    flowFilePretty: true,
    userDir: path.join(process.cwd(), "node-red"),
    nodesDir: [path.join(process.cwd(), "node-red", "nodes"),process.argv[4]],
    httpAdminRoot: '/red',
    httpNodeRoot: '/api',
    httpNodeMiddleware: function(req,res,next) {
	   console.log("httpNodeMiddleware");
	   skipper(req,res, function(arg1, arg2){
		   console.log("back from skipper");
		   next();
	   });
    },
    functionGlobalContext: {
		fs: require('fs'),
		path: require('path'),
    },
    logging: {
        console: {
            level: "debug",
            metrics: false,
            audit: false
        }
    },
	"swagger": {
		"template": {
		  "swagger": "2.0",
		  "info": {
			"title": "My Node-RED API",
			"version": "0.0.1"
		  }
		}
	  } 
}

Flow:

> 
[
    {
        "id": "be2ba3e7.1b61e",
        "type": "tab",
        "label": "Flow 1"
    },
    {
        "id": "683d05c5.f7d35c",
        "type": "swagger-doc",
        "z": "be2ba3e7.1b61e",
        "summary": "",
        "description": "",
        "tags": "",
        "consumes": "",
        "produces": "",
        "parameters": [
            {
                "name": "param1",
                "in": "query",
                "required": false,
                "type": "string"
            }
        ],
        "responses": {},
        "deprecated": false
    },
    {
        "id": "44cd0fde.4c3e8",
        "type": "http in",
        "z": "be2ba3e7.1b61e",
        "name": "test",
        "url": "/test",
        "method": "get",
        "swaggerDoc": "683d05c5.f7d35c",
        "x": 98.09944152832031,
        "y": 123.77556610107422,
        "wires": [
            [
                "1be1727c.77fefe",
                "c243786.d786188"
            ]
        ]
    },
    {
        "id": "1be1727c.77fefe",
        "type": "http response",
        "z": "be2ba3e7.1b61e",
        "name": "",
        "x": 336.10792541503906,
        "y": 122.44318389892578,
        "wires": []
    },
    {
        "id": "c243786.d786188",
        "type": "debug",
        "z": "be2ba3e7.1b61e",
        "name": "debug me",
        "active": true,
        "console": "true",
        "complete": "payload",
        "x": 344.10223388671875,
        "y": 56,
        "wires": []
    }
]

Steps to reproduce:
1. Run the server code and use postman to check that the flow is working and debug messages are displayed in editor UI.
postman query: http://localhost:1882/api/test?param1=value4
Editor URL: http://localhost:1882/red
2. Change server code to support '/wf-engine' in path, as below: 

> 
console.log("httpAdminRoot: " + settings.httpAdminRoot);
//app.use(settings.httpAdminRoot,RED.httpAdmin);
app.use("/wf-engine" + settings.httpAdminRoot,RED.httpAdmin);
console.log("httpNodeRoot: " + settings.httpNodeRoot);
//app.use(settings.httpNodeRoot,RED.httpNode);
app.use("/wf-engine" + settings.httpNodeRoot,RED.httpNode);

3. Run the server code and use postman to check that the flow is working. See that debug messages are not displayed in editor UI.
**postman query:** http://localhost:1882/wf-engine/api/test?param1=value4
**Editor URL:** http://localhost:1882/wf-engine/red

**Comment by knolleary** [comment]
Hi,

took me a while to figure this out: it is usage error.

`httpAdminRoot` needs to be the complete root path - you cannot prepend anything else to it.

The WebSocket server needs to know the complete path it should be listening on - which it gets from `httpAdminRoot`. If you mount admin on a different path (by prepending extra parts as your code does), then the WebSocket server will be listening on a different path to where the editor thinks it is.

**Comment by oprince** [comment]
Thanks for explanation. Would it be possible to enable prepanding path tokens ?

**Comment by knolleary** [comment]
The problem is we have to pass the fully-qualified path through to the WebSocket server. To support prepending path tokens, we'd need to introduce another setting which you can use to tell us what token you are prepending to `httpAdminRoot`. But if you're going to do that, you may as well give us fully qualified `httpAdminRoot` and `httpNodeRoot` values.
