### ISSUE TITLE
Finding node-red stopped with not apparent reason

### ISSUE THREAD

**Issue by gbrian** [node-red/node-red#987]
Hi,

I've install latest version with npm on an Ubuntu 1vCPU, 0.6GB Ram Google Cloud Virtual machine.
Same machine is running graphite & grafana apps.
It runs two workflows:
* First just define global settings
* Second sends metrics to a graphite server: cpu, ram, IO
I find it stopped after ~28hours running. 
I've tried to drop console output to a file but no error or strange messages there.

![image](https://cloud.githubusercontent.com/assets/767180/18430475/f7f41916-78d8-11e6-80c6-d49fe1982c28.png)

Any other place where to look for more details about what's causing node-red to stop?

Thanks in advance!

**Comment by hardillb** [comment]
Please ask questions like this in the forum (https://groups.google.com/forum/#!forum/node-red) or slack, we keep GitHub issues for actual identified code defect.

**Comment by gbrian** [comment]
Ok, I thought having this unexpected behavior could belong to a bug. I'll do and reopen in case we find more details pointing to a bug in the code. 
Thanks.

**Comment by dceejay** [comment]
In meantime, check the amount of memory being used. You may need to limit it, for example as pet "passing arguments" section of http://nodered.org/docs/getting-started/running 
(By default node will try to use 2gb)

**Comment by gbrian** [comment]
@dceejay Thanks, I'll take a look.
I'm testing Grafana alarms as well and see none related with an increase in memory.
![image](https://cloud.githubusercontent.com/assets/767180/18430810/73fb2efe-78da-11e6-8c34-bea67cc6c491.png)

**Comment by gbrian** [comment]
Moving discussion to: https://groups.google.com/forum/#!topic/node-red/qN6nNm0h9aY
