### ISSUE TITLE
0.15.0/bidi: cannot edit HTTP Request node

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red#988]
@wajnberg - please take a look at this

When trying to edit the following HTTP Request node, an error is thrown in the bidi handling and the edit dialog fails to display:

    [{"id":"788bca64.254f94","type":"http request","z":"55c9f668.f8d328","name":"","method":"GET","url":"http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.csv","x":278.5,"y":159.999755859375,"wires":[["3fd3208d.31751"]]}]

<img width="667" alt="node-red" src="https://cloud.githubusercontent.com/assets/51083/18444613/ec183d64-7911-11e6-89bc-51da22d8c217.png">

**Comment by knolleary** [comment]
If you double click the node enough times, the edit dialog does eventually open... but then #989

**Comment by knolleary** [comment]
@wajnberg 

steps to recreate:

1. import the flow from here: http://flows.nodered.org/flow/edca3ef3e88a00e7e082
2. try to edit the HTTP Request node - it fails with the above error
3. hit deploy, reload the browser, still can't edit the node.

This is Chrome 53 on Mac... can't reproduce on FF.

Will dig some more.

**Comment by knolleary** [comment]
Does appear to be WebKit specific - http://stackoverflow.com/questions/22935320/uncaught-indexsizeerror-failed-to-execute-getrangeat-on-selection-0-is-not

**Comment by knolleary** [comment]
@wajnberg - I'm struggling to understand the `displayWithStructure` function in `format.js` which is making it hard to see how to fix this. I would really like, from you, one or both of:

 - documented code so we can maintain it
 - a set of test cases that properly exercise this code so we can make changes with confidence. Initially, just some sample strings and images to show how they ought to be rendered would be enough

**Comment by wajnberg** [comment]
Hello @knolleary 

Thank you for your explanations. I eventually succeeded in reproducing the problem
I also made a fix for it; Please refer to https://github.com/node-red/node-red/pull/997

I will certainly add some documentation in format.js.

But in a general manner I'd like to tell you that we are committed to maintain the Bidi code. So you don't need to worry about the maintenance of this code

Thank you

**Comment by dceejay** [comment]
The question is also. When we want to maybe add any new node, or change function of an existing one, what simple rules do we need to follow to bidi enable it in the first place. We shouldn't need to go via you every time we make a change.

**Comment by wajnberg** [comment]
Hello @dceejay ,

I will forward you a note I sent  a month ago to Nick which explains what exactly you need to do when you add a new node requiring a special handling for Bidi STT (Structured Text)

**Comment by knolleary** [comment]
@wajnberg thanks for fixing. We still really need some examples to help us see for ourselves what the expected behaviour is. I know your team is going to help maintain this, but I don't like having parts of the code base that we, the core team, are not able to verify for ourselves - especially as we don't have automated tests for the UI at all.
