### ISSUE TITLE
Cannot enqueue Query after fatal error

### ISSUE THREAD

**Issue by kenvernaillenvub** [node-red/node-red#991]
My node-red applications directs MQTT messages to my MySQL database.
When I noticed a lot of data was missing in the database, I checked the logs and found thousands errors like:

> [error] [mysql:3a8296e6.89951a] Error: Cannot enqueue Query after fatal error.

When I searched for the error before these errors (the fatal one), I found:

> [error] [mysql:3a8296e6.89951a] Error: Connection lost: The server closed the connection.

In a relevant mysqljs error (https://github.com/mysqljs/mysql/issues/832), they notice that the db connection is not released properly. Can this be the case?

I don't know if this has anything to do with it, but I noticed some errors like this too (also before this issue):

> [error] [MySQLdatabase:4a1035a.a61eacc] Error: connect ECONNREFUSED

_Context:_
_[info] Node-RED version: v0.14.4_
_[info] Node.js  version: v0.10.25_
_[info] Linux 4.4.0-28-generic x64 LE_

**Comment by dceejay** [comment]
So your server stopped the connection ? The catch node should be able to report the error into the flow if you want to act on it.
For general questions we prefer the mailing list, or is there some issue with the node ?

**Comment by knolleary** [comment]
Yes... but this sounds like a failure to recover automatically from a server disconnect. If the node fails to reconnect, there isn't much you can do in the flow with a catch node or otherwise.

**Comment by kenvernaillenvub** [comment]
So there is an issue with the node? Or how can I automatically let it recover, so no data gets lost?

**Comment by knolleary** [comment]
@kenvernaillenvub at this point, we don't know... need to investigate

**Comment by dceejay** [comment]
It does automatically try to reconnect...  But will have to check some more.

**Comment by kenvernaillenvub** [comment]
Does node-red use one single connection? Or a connection per query (that is also released)? I don't find it in the code. (like noticed here: mysqljs/mysql#832)

**Comment by dceejay** [comment]
One single connection

**Comment by kenvernaillenvub** [comment]
While redeploying (to fix the issue of 'cannot enqueue query'),  I also found the error:

> 14 Sep 14:31:48 - [error] [MySQLdatabase:4a1035a.a61eacc] Error: Cannot enqueue Quit after fatal error.

After deploy everything works again.

Since it is a single connection, how can I catch the error and release and reconnect the database connection?

**Comment by dceejay** [comment]
So - I guess the best we can do is to reject any input while "not connected" - rather than get the cannot enqueue error - and let it reconnect before accepting any more input.

**Comment by kenvernaillenvub** [comment]
sounds good to me.
so the input that is rejected wouldn't be buffered and will be lost?

**Comment by dceejay** [comment]
Yes, none of the other nodes buffer. Buffering , queue management, and error recovery are all topics beyond the scope of a "simple" database node :-)

**Comment by dceejay** [comment]
But we would raise an error, so at least you would know...

**Comment by kenvernaillenvub** [comment]
Ok thanks

**Comment by dceejay** [comment]
Hi, published to npm as version 0.0.10.
the default retry time is 20 seconds  - this can be overridden in the settings.js file by using
mysqlReconnectTime = 20000,   // time in milliseconds

Now rather than that obscure message it creates an error that can be caught with the catch node - that contains the original inut msg object so you can feed it back round or drop it or whatever you wna to do.

PS - this Issue should really be raised against the node-red-nodes project
