### ISSUE TITLE
"node-red-contrib-python-functions" does not come to.

### ISSUE THREAD

**Issue by kovaccs** [node-red/node-red#995]
I installed the mentioned node and restarted Node-RED. After that I can't find the installed node in my Node-RED system.
I tried it load several time and different methodes without success. npm ended no errors, python 2.7 is installed. There is node-red-contrib-python-function directory inside ~/.node-red/node_modules/

Have anybody some suggestion what I doing wrong? I've got a large number of used extra nodes insatlled.
Kovaccsaba

**Comment by knolleary** [comment]
Hi,
please can you use the mailing list (link at bottom of nodered.org) for these sort of questions - particularly as it involves a 3rd party node and not one we maintain.

Many thanks,

Nick

**Comment by kovaccs** [comment]
Ok! I' moving.
