### ISSUE TITLE
Failed to list databases: couch returned 403

### ISSUE THREAD

**Issue by ElizBth** [node-red/node-red#998]
Hi everyone

I am using NodeRed on a Beaglebone Black and I have installed the Cloudant nodes. But when a i try to send my data through the node "cloudant output"  I get the error "Failed to list databases: couch returned 403".

I don´t know if I have a bad configuration into my node because the examples what I could find, It is working into the bluemix enviroment and when they configure their cloudant node, they have an service active to choose and the thing is different onto my enviroment.

Someone can I help?

I have the next configurations:

Node Cloudant output:

Service           External cloudant or couchdb service   (It is the unique option that I have)
Server            https://username.cloudant.com
Datebase       test
Operation      insert
                        Only store msg.payload. object?     (It is unchecked)
Name             empty

https://username.cloudant.com Server configuration   (Edit cloudant node)

Host                https://username.cloudant.com/
Username      (I am using the key that I get when I have generated my API KEY on cloudant)
Password       (I am using the key password )
Name              empty

**Comment by knolleary** [comment]
Hi, this issue list is for the core of Node-RED.

For general support questions, please use the mailing list linked to from the bottom of nodered.org
